### PR TITLE
Change OpenAPI document name resolution to be case-insensitive

### LINKED ISSUE #59175: OpenAPI document names are case-sensitive in urls
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I included several different openapi documents via .AddOpenApi("myDoc"). The document name contains upper- and lowercase letters. Later on I want to retrieve my document via /openapi/mydoc.json but I get a 404. After looking into it I found out that this should come from the fact that we're using keyed services:

```csharp
        return endpoints.MapGet(pattern, async (HttpContext context, string documentName = OpenApiConstants.DefaultDocumentName) =>
            {
                // It would be ideal to use the `HttpResponseStreamWriter` to
                // asynchronously write to the response stream here but Microsoft.OpenApi
                // does not yet support async APIs on their writers.
                // See https://github.com/microsoft/OpenAPI.NET/issues/421 for more info.
                var documentService = context.RequestServices.GetKeyedService<OpenApiDocumentService>(documentName);
                if (documentService is null)
                {
                    context.Response.StatusCode = StatusCodes.Status404NotFound;
                    context.Response.ContentType = "text/plain;charset=utf-8";
                    await context.Response.WriteAsync($"No OpenAPI document with the name '{documentName}' was found.");
                }
```

Keyed services seem to be case sensitive. I can resolve this issue by lowercasing everything but this is counter-intuitive for me because the rest of aspnetcore does not use case sensitive routing AFAIK. 

### Expected Behavior

I expect the url for the openapi documents to be case insensitive, so I can receive my document regardless of the casing I use.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sander1095**
# Change OpenAPI document name resolution to be case-insensitive

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Case-sensitive urls are now supported when retrieving OpenAPI documents.

## Description

There was a routing issue when using case-sensitive document names in `Microsoft.AspNetCore.OpenApi`'s `AddOpenApi()` and `MapOpenApi()` methods. If you registered a document in a case-sensitive manner (`MyDocument`) and tried to retrieve it at `/openapi/mydocument.json`, it would result in a 404.

This is odd, as ASP.NET Core's routing has always been case-insensitive by default.

The reason for this bug is that keyed services are used to register relevant services. The key is the document name, and keyed services are case-sensitive.

This PR changes this inconsistent behaviour by allowing case-insensitive document resolution by invariantly lowercasing both the registered document name and the document name that's being retrieved.

Fixes #59175

### CODE REVIEW

File: src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs [hunk 1]
```diff
@@ -57,13 +57,35 @@ public static IServiceCollection AddOpenApi(this IServiceCollection services, st
...
+        AddOpenApiCore(services, lowercasedDocumentName);
+        services.Configure<OpenApiOptions>(lowercasedDocumentName, options =>
         {
-            options.DocumentName = documentName;
+            options.DocumentName = lowercasedDocumentName;
             configureOptions(options);
         });
         return services;
+
+        // The reason this method is a local function is to prevent case-sensitive document names being passed into this method (from other methods) in the future.
```
Comment (captainsafia) [inline src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs:74]: Is this necessary if the method was previously private and only accessible from methods in this class?

File: src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Extensions/OpenApiEndpointRouteBuilderExtensionsTests.cs [hunk 2]
```diff
@@ -59,7 +59,7 @@ public async Task MapOpenApi_ReturnsRenderedDocument()
         context.Response.Body = responseBodyStream;
         context.RequestServices = serviceProvider;
         context.Request.RouteValues.Add("documentName", "v1");
-        var endpoint = builder.DataSources.First().Endpoints.First();
+        var endpoint = builder.DataSources.First().Endpoints[0];
```
Comment (captainsafia) [inline src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Extensions/OpenApiEndpointRouteBuilderExtensionsTests.cs:62]: Is moving from `First()` to the indexer a result of XUnit analyzers here or...?

File: src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs (hunk 1 above)
Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs:74]: It's not 100% required. It's a bit of defensive programming as explained in the comment. :) 

Keeping it a private method _might_ introduce scenarios in the future where non-lowercased input is passed into it, which would reintroduce the bug. 

With the code written this way, it's less likely.

Let me know if you'd like me to revert this! :)

File: src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Extensions/OpenApiEndpointRouteBuilderExtensionsTests.cs (hunk 2 above)
Comment (captainsafia) [reply src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Extensions/OpenApiEndpointRouteBuilderExtensionsTests.cs:62]: Nope! This change looks good. I just wanted to verify that it was coming from the analyzer. I believe similar warnings have been addressed in other files.

File: src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs (hunk 1 above)
Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs]: I have reset it! Let me know if there's anything else I can still do! Otherwise, feel free to merge!

**Review by captainsafia — APPROVED** [review]
