### PR TITLE
Unquarantine 2 build and publish template tests

### LINKED ISSUE #23993: Hanging tests MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes and Template_Produces_The_Right_Set_Of_FilesAsync
```
[xUnit.net 00:15:55.56] ProjectTemplates.Tests: [Long Running Test] 'Templates.Test.BaselineTest.Template_Produces_The_Right_Set_Of_FilesAsync(arguments: "new razor -au Individual", expectedFiles: ["app.db", "appsettings.Development.json", "appsettings.json", "Program.cs", "Startup.cs", ...])', Elapsed: 00:12:13
[Long Running Test] 'Templates.Test.MvcTemplateTest.MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes', Elapsed: 00:12:01
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot process request because the process (14604) has exited.)
 ---> System.InvalidOperationException: Cannot process request because the process (14604) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.AspNetCore.Internal.ProcessEx.<>c__DisplayClass13_0.<.ctor>b__0() in /_/src/Shared/Process/ProcessEx.cs:line 55
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot process request because the process (14910) has exited.)
 ---> System.InvalidOperationException: Cannot process request because the process (14910) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.AspNetCore.Internal.ProcessEx.<>c__DisplayClass13_0.<.ctor>b__0() in /_/src/Shared/Process/ProcessEx.cs:line 55
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=730760&view=ms.vss-test-web.build-test-results-tab&runId=22604528&resultId=121668&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/23993

BlazorServerTemplates_Identity_BuildAndPublish stats: passed 284/284 in quarantine
Templates.Test.MvcTemplateTest.MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes: passed 707/707 quarantine

Per https://dev.azure.com/dnceng/public/_test/analytics?definitionId=869&contextType=build

### CODE REVIEW

File: src/ProjectTemplates/test/MvcTemplateTest.cs [hunk 1]
```diff
@@ -306,7 +306,6 @@ public async Task MvcTemplate_SingleFileExe()
         }
 
         [Fact]
-        [QuarantinedTest("https://github.com/dotnet/aspnetcore/issues/23993")]
         public async Task MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes()
```
Comment (captainsafia) [inline src/ProjectTemplates/test/MvcTemplateTest.cs:309]: I saw @Tratcher's comment at https://github.com/dotnet/aspnetcore/issues/23993#issuecomment-696427823. Do we need to take action on that?

Comment (HaoK) [reply src/ProjectTemplates/test/MvcTemplateTest.cs:309]: That test was already fixed in another PR https://github.com/dotnet/aspnetcore/pull/26825, the tracking for fixing tests is slightly awkward since they are filed in batches, but the fixes/issues aren't necessarily the same.

Comment (captainsafia) [reply src/ProjectTemplates/test/MvcTemplateTest.cs:309]: Got it! Thanks for clarifying.

**Review by captainsafia — APPROVED** [review]
