### PR TITLE
Fix route analyzer performance with highly concatenated strings

### LINKED ISSUE #53899: RoutePatternAnalyzer (ASP0017, ASP0018) performance issue (1.5 minute execution time)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For roughly 2.5 weeks now I am experiencing extremely slow build times. `dotnet build` says that `Core Compile` takes forever here. Through the MSBuild Structured Log Viewer I was able to track down a few analyzers:

image

I can't really tell why this is happening.

Disabling analyzers on the project DOES help:
```xml
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
```

### Expected Behavior

Better performance.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

8.0.200-preview.23624.5

### Anything else?

```
Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.9.0 Preview 5.0
````
```xml
<TargetFramework>net8.0</TargetFramework>
```

### LINKED ISSUE #54293: Very slow build - can't build project
**Version Used**: 
8.0.200
Visual Studio 2022, 17.9.0

**Steps to Reproduce**:

After upgrading to .NET 8 I can't build my project.
Build doesn't finish (maybe infinite loop).
This project contains classes which are generated by Antlr4.
These classes are very large so maybe this causes problems.

I created small project with same problem:
[academitslearn.zip](https://github.com/dotnet/roslyn/files/14314416/academitslearn.zip)

Here build finishes but it takes about 10 seconds.
In previous versions build was immediate.

**Expected Behavior**:

Build finishes and build is fast.

**Actual Behavior**:

Build not finishes for real project.
Build is very slow for small project.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/54293
Fixes https://github.com/dotnet/aspnetcore/issues/53899

Route analyzer introduced in .NET 8 is causing very long build times if some projects. Highly concatenated strings caused a lot of time to be spent in `HasLanguageComment`. 

The PR:

* Matches Roslyn change in https://github.com/dotnet/roslyn/pull/72620
* Adds a test that recreates https://github.com/dotnet/aspnetcore/issues/54293.
  * **Before change:** 5 seconds
  * **After change:** ~0.2 seconds~ 0.05 seconds

This PR will likely be backported to 8.0.

### CODE REVIEW

**Comment by JamesNK** [comment]
@jjonescz, @CyrusNajmabadi, @cston Roslyn expert opinion on this fix would be great.

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs [hunk 1]
```diff
@@ -512,4 +521,38 @@ public object TestAction(int id)
         // Assert
         Assert.Empty(diagnostics);
     }
+
+    [Fact]
+    public async Task ConcatString_PerformanceTest()
+    {
+        // Arrange
+        var fileText = File.ReadAllText("RouteEmbeddedLanguage\\Class1.cs.txt");
```
Comment (martincostello) [inline src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs:529]:
```suggestion
        var fileText = File.ReadAllText(System.IO.Path.Combine("RouteEmbeddedLanguage", "Class1.cs.txt"));
```

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs [hunk 2]
```diff
@@ -68,7 +81,7 @@ private static bool IsAnyStringLiteral(int rawKind)
             return false;
         }
 
-        if (HasLanguageComment(token, out identifier, out options))
+        if (HasLanguageComment(token, lastInspectedStringNode, out identifier, out options))
```
Comment (jjonescz) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:84]: In the issue you said roslyn does something similar but isn't slow. Have you figured out why?

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs [hunk 3]
```diff
@@ -151,6 +165,16 @@ private static bool IsAnyStringLiteral(int rawKind)
 
         for (var node = token.Parent; node != null; node = node.Parent)
         {
+            // Searching for the language comment on all parents is expensive (GetLeadingTrivia) if the token is deeply nested.
+            // An example of this is a string with hundreds of concatenations. Avoid this by checking the last inspected string node.
+            // The last inspected string will be a parent and allows us to exit quickly from a deeply nested tree.
```
Comment (jjonescz) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:170]: Alternatively I guess you could somehow limit the number of strings in a concatenation you visit. I imagine it's not necessary to support "route string syntax" on strings consisting of lots of concatenated parts. Or don't support comments anywhere inside the concatenation, just at the top level. Not saying those are better solutions, just some thoughts.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs (hunk 2 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:84]: No. I looked for a couple of hours but I couldn't find a difference.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs [hunk 4]
```diff
@@ -151,6 +165,16 @@ private static bool IsAnyStringLiteral(int rawKind)
 
         for (var node = token.Parent; node != null; node = node.Parent)
         {
+            // Searching for the language comment on all parents is expensive (GetLeadingTrivia) if the token is deeply nested.
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:168]: >GetLeadingTrivia [](http://example.com/codeflow?start=79&length=16)

Is the call to `GetLeadingTrivia()` expensive or is the issue that `HasLanguageComment()` and therefore `GetLeadingTrivia()` were called too many times for a concatenation of many strings?

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs [hunk 5]
```diff
@@ -512,4 +521,38 @@ public object TestAction(int id)
         // Assert
         Assert.Empty(diagnostics);
     }
+
+    [Fact]
+    public async Task ConcatString_PerformanceTest()
+    {
+        // Arrange
+        var fileText = File.ReadAllText(System.IO.Path.Combine("RouteEmbeddedLanguage", "Class1.cs.txt"));
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs:529]: >File.ReadAllText(System.IO.Path.Combine("RouteEmbeddedLanguage", "Class1.cs.txt")) [](http://example.com/codeflow?start=23&length=82)

Is the actual string content important? If not, perhaps generate the source in the test rather than checking it in.
```csharp
var builder = new System.Text.StringBuilder();
builder.AppendLine("""
    class Program
    {
        static void Main() { }
        static readonly string _s =
    """);
for (int i = 0; i < 2000; i++)
    builder.AppendLine("        \"abc\" +");
builder.AppendLine("""
            "";
    }
    """);
var source = TestSource.Read(builder.ToString());
```

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs (hunk 4 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:168]: I don't know. I don't know how fast `GetLeadingTrivia()` should be.

It's true that `HasLanguageComment` was doing unneccessary work and calling `GetLeadingTrivia()` a lot.

One thing I noticed: even after the optimization in this PR to reduce calls to `HasLanguageComment`, which reduced analysis time from 5 seconds to 0.2 seconds, `GetLeadingTrivia()` is still the hottest method in the profile.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs (hunk 3 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:170]: Yeah, got it. If this didn't work, then I'd fall back to that to fix. Not needed at the moment.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs (hunk 4 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:168]: After the optimization:
image

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs]: I just improved the time some more by looking ahead when matching a previously matched node. Reduces the number of calls to GetLeadingTrivia.

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs [hunk 6]
```diff
@@ -526,17 +527,22 @@ public object TestAction(int id)
...
-
-" + fileText);
+        var builder = new StringBuilder();
+        builder.AppendLine("""
+    class Program
+    {
+        static void Main() { }
+        static readonly string _s =
+    """);
+        for (var i = 0; i < 3; i++)
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs:537]: Should N be 2000 or more?

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs [hunk 7]
```diff
@@ -555,4 +561,33 @@ static void Main()
...
+        // Arrange
+        var builder = new StringBuilder();
+        builder.AppendLine("""
+    class Program
+    {
+        static void Main() { }
+        // lang=Route
+        static readonly string _s =
+    """);
+        for (var i = 0; i < 100; i++)
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs:577]: 2000 or more?

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs:577]: The intent of the test is deeply nested concat strings are all classified as routes. 100 is enough.

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternAnalyzerTests.cs]: I changed it to 2000 and found another example of `HasLanguageComment` being repeatedly called. Fixed, and I left this at 2000.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/Infrastructure/RouteUsageCache.cs [hunk 8]
```diff
@@ -74,6 +92,15 @@ private RouteUsageCache(Compilation compilation)
...
             };
-        });
+        }
+    }
+
+    private RouteUsageModel? GetAndCache(SyntaxToken syntaxToken, ref LastInspectedStringNode? lastInspectedStringNode, CancellationToken cancellationToken)
+    {
+        var routeUsageModelLoader = new RouteUsageModelLoader(_compilation, lastInspectedStringNode, cancellationToken);
+        var model = _lazyRoutePatterns.GetOrAdd(syntaxToken, routeUsageModelLoader.Load);
+        lastInspectedStringNode = routeUsageModelLoader.LastInspectedStringNode;
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/Infrastructure/RouteUsageCache.cs:102]: >lastInspectedStringNode = routeUsageModelLoader.LastInspectedStringNode [](http://example.com/codeflow?start=8&length=71)

`LastInspectedStringNode?` is a `struct`. Is it possible for two threads to be writing to the same instance? If so, there is a chance of tearing.

Perhaps `LastInspectedStringNode` should be a `class` instead.

Comment (cston) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/Infrastructure/RouteUsageCache.cs:102]: It looks like `LastInspectedStringNode` instances are not shared across threads, so this may not be an issue. But it might be worth using a `class` so it's clear there is no potential issue.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs [hunk 9]
```diff
@@ -34,22 +34,39 @@ private void AnalyzeSemanticModel(SemanticModelAnalysisContext context)
         var routeUsageCache = RouteUsageCache.GetOrCreate(context.SemanticModel.Compilation);
 
         // Update to use FilterSpan when available. See https://github.com/dotnet/aspnetcore/issues/48157
-        foreach (var item in root.DescendantTokens())
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:37]: >foreach (var item in root.DescendantTokens()) [](http://example.com/codeflow?start=8&length=45)

Was this change needed to fix the issue? The reason for asking is if the fix may be considered for .NET 8, it might be useful to reduce the size of the change.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs [hunk 10]
```diff
@@ -164,6 +189,30 @@ private static bool IsAnyStringLiteral(int rawKind)
...
+        // The last inspected string will be a parent and allows us to exit quickly from a deeply nested tree.
+        static bool TryMatchPreviousStringNode(
+            SyntaxNode? node,
+            LastInspectedStringNode? lastInspectedStringNode,
+            out string? identifier,
+            out IEnumerable<string>? options)
+        {
+            if (lastInspectedStringNode is { } previousNode)
+            {
+                if (node != null && node == previousNode.Node.Parent)
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:204]: >node == previousNode.Node.Parent [](http://example.com/codeflow?start=36&length=32)

It looks like we're returning the identifier from the last string checked if the current node `node` is the parent of that last string node. If so, is that correct that the same identifier should be returned for all ancestors?

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:204]: That's how the current HasLanguageComment works. If any parent has a comment, then children inherit it.

However, there is a case where siblings can have different languages, e.g.

```cs
public static readonly string _test =
    // lang=regex
    "^(sdf)+" +
    // lang=Route
    "{sdf}";
```

And a child can override a parent, e.g. a comment on the field will be overriden by a comment on a string.

I'll add tests that these scenarios still work correctly.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/Infrastructure/RouteUsageCache.cs (hunk 8 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/Infrastructure/RouteUsageCache.cs:102]: It's not shared. I'll add a comment that it's ok.

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs [hunk 11]
```diff
@@ -149,18 +149,29 @@ private static bool IsAnyStringLiteral(int rawKind)
...
 
+        bool first = true;
         for (var node = token.Parent; node != null; node = node.Parent)
         {
-            if (HasLanguageComment(node.GetLeadingTrivia(), out identifier, out options))
+            // Deeply nested tree of strings can cause poor performance. The scenario is highly concatenated strings.
+            // GetLeadingTrivia is a hot path for this analyzer so don't call it for every parent binary node.
+            // Just check the first parent and then resume checking once out of nested binary nodes.
+            // The "ConcatString_PerformanceTest" test runs to check for this scenario.
+            if (first || (node is not BinaryExpressionSyntax && node.Parent is not BinaryExpressionSyntax))
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:159]: >if (first || (node is not BinaryExpressionSyntax && node.Parent is not BinaryExpressionSyntax)) [](http://example.com/codeflow?start=12&length=95)

We're skipping `GetLeadingTrivia()` here, but we're still calling `node.Parent` N^2 times when walking a set of tokens that represent a concatenation of N strings. If N is large enough, that might be an issue.

For instance, timing the following, with the source from `ConcatString_PerformanceTest`:
N = 20,000, time = ~2 secs
N = 200,000, time = ~150 secs

```csharp
var tokens = tree.GetRoot().DescendantTokens().ToArray();
foreach (var t in tree.GetRoot().DescendantTokens())
{
    RouteEmbeddedLanguage.Infrastructure.RouteStringSyntaxDetector.IsRouteStringSyntaxToken(t, model, cancellationToken: default, out _);
}
```

Comment (cston) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:159]: If the lang comment is on a `BinaryExpressionSyntax`, are we going to ignore that comment for tokens beneath the `BinaryExpressionSyntax` node that aren't direct children?

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs:159]: `node.Parent` is a plain old getter property. Its perf should be fine until you get to ludicrous scale - string concats with tens of thousands of items.

**Comment by CyrusNajmabadi** [comment]
image

**Comment by CyrusNajmabadi** [comment]
@JamesNK i just went with https://github.com/dotnet/roslyn/pull/72620 as a simple approach.

**Comment by JamesNK** [comment]
> @JamesNK i just went with [dotnet/roslyn#72620](https://github.com/dotnet/roslyn/pull/72620) as a simple approach.

Perfect, I like it.

Trying to match Roslyn behavior while getting good perf was wrapping this PR up in knots. Great that Roslyn just simplified, and this PR can copy it.

**Review by mitchdenny — APPROVED** [review]
LGTM.

**Review by CyrusNajmabadi — APPROVED** [review]
