### PR TITLE
HTTP/3: Fix flakey request headers timeout tests

### LINKED ISSUE #32106: Test failure: HEADERS_HeaderFrameReceivedWithinRequestHeadersTimeout_Success
https://dev.azure.com/dnceng/public/_build/results?buildId=1104117&view=ms.vss-test-web.build-test-results-tab&runId=33729836&resultId=122466&paneView=debug

```
System.Exception : Assert failed after 10 retries: Wait until streams have been created.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests.AssertIsTrueRetryAsync(Func`1 assert, String message) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs:line 212
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 119
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests.HEADERS_HeaderFrameReceivedWithinRequestHeadersTimeout_Success() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs:line 64
--- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/32106

### CODE REVIEW

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs [hunk 1]
```diff
@@ -183,35 +173,13 @@ public async Task ControlStream_RequestHeadersTimeoutMaxValue_ExpirationIsMaxVal
...
+            await outboundControlStream.OnStreamCreatedTask.DefaultTimeout();
 
             var serverInboundControlStream = Connection._streams[outboundControlStream.StreamId];
 
             TriggerTick(now);
 
             Assert.Equal(TimeSpan.MaxValue.Ticks, serverInboundControlStream.HeaderTimeoutTicks);
         }
-
-        private static async Task AssertIsTrueRetryAsync(Func<bool> assert, string message)
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs:197]: ❤️

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TestBase.cs [hunk 2]
```diff
@@ -242,10 +244,74 @@ protected void CreateConnection()
             httpConnectionContext.TimeoutControl = _mockTimeoutControl.Object;
 
             Connection = new Http3Connection(httpConnectionContext);
+            Connection._streamLifetimeHandler = new LifetimeHandlerInterceptor(Connection, this);
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TestBase.cs:247]: Clever. I like it a lot.

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TestBase.cs (hunk 2 above)
Comment (JamesNK) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TestBase.cs:247]: 😄
