### PR TITLE
fixes minimal apis not returning traceid on problem details upon exceptions

### LINKED ISSUE #54325: Minimal API does not return ProblemDetails traceid on Exception
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When and **Exception** is thrown then **Minimal API** returns **ProblemDetails** without **traceid** even though it is available. This happens in all environments and is in contrast with **Controller API**s which does log **traceid** in all scenarios. It would be good if this was automatically included and both exhibited the same behaviour. A workaround is to manually add **traceid** to **ProblemDetails.Extensions** like below. Please see the test below to reproduce.

### Expected Behavior

**Minimal API** should return **ProblemDetails**  **traceid**  just like **Controller API**s do like below.

### Steps To Reproduce

**Minimal API Test**
1 - Create a new **Minimal API** project.

2 - Enable **ProblemDetails** like below.
```
builder.Services.AddProblemDetails(po => po.CustomizeProblemDetails = pc =>
{
    pc.ProblemDetails.Extensions.Add("testSpanId", Activity.Current.SpanId.ToString());
    pc.ProblemDetails.Extensions.Add("testTraceId", Activity.Current.TraceId.ToString());
    pc.ProblemDetails.Extensions.Add("testId", Activity.Current.Id);
});
```

3 - Optionally enable ExceptionHandler like below.
`app.UseExceptionHandler();`

4 - Add test endpoint like below
```
app.MapGet("/test", () =>
{
    throw new NotImplementedException();
});
```

5 - Run project and hit the Minimal endpoint and notice the **ProblemDetails** does not include the **traceid** like below.
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500,
  "testSpanId": "b462c6e945fce474",
  "testTraceId": "3949b14c78afa8febf630c6ab7b9b990",
  "testId": "00-3949b14c78afa8febf630c6ab7b9b990-b462c6e945fce474-00"
}
```

**Controller API Test**
1 - Create a new **Controller API** project.

2 - Add the above sample code.

3 - Additionally Add code to throw an **Exception** from the Controller Action.

4 - Run project and hit the Controller Endpoint and notice the **ProblemDetails** includes the **traceid** like below.
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500,
  "traceId": "00-a6d6b1be7ff2d0ead53fabf178be6d71-a71db9a8a184fdec-00",
  "testSpanId": "a71db9a8a184fdec",
  "testTraceId": "a6d6b1be7ff2d0ead53fabf178be6d71",
  "testId": "00-a6d6b1be7ff2d0ead53fabf178be6d71-a71db9a8a184fdec-00"
}
```

### Exceptions (if any)

_No response_

### .NET Version

8.0.200

### Anything else?

.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by tcortega**
I took liberty to remove an if condition that was in the previous code for Controllers:
https://github.com/dotnet/aspnetcore/blob/b3b8dffff4d092058b2d8942268b498cbfdb14ec/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L92-L96

Since they don't represent any threat, because the received `HttpContext` can never be null, and the `TraceIdentifier` is always filled by Kestrel. Should not represent any threats.

closes #54325

### CODE REVIEW

File: src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs [hunk 1]
```diff
@@ -12,6 +12,7 @@
 using System.Text.Json.Serialization;
 using Microsoft.CodeAnalysis;
 using JsonOptions = Microsoft.AspNetCore.Http.Json.JsonOptions;
+using System.Diagnostics;
```
Comment (gfoidl) [inline src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs:15]: Please keep the `using`s sorted.

Comment (captainsafia) [reply src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs:15]: Good catch, @gfoidl! It looks like the using in this file were previously unsorted anyways (likely because it is a test file).

@tcortega If you're able to fix the using sorting on this file overall that would be great! Otherwise, I can edit and merge.

**Review by captainsafia — APPROVED** [review]
Looks good overall other than the comment about sort using. Will wait to see if @tcortega can edit before merging otherwise I am happy to make the edit.

File: src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs (hunk 1 above)
Comment (tcortega) [reply src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs]: Resolved, also removed some unnecessary usings @gfoidl, @captainsafia

**Comment by tore-hammervoll** [comment]
Will we see this change in a patch release of .Net 8? Or do we have to wait for .Net 9?

**Comment by captainsafia** [comment]
@tore-hammervoll You'll have to wait until .NET 9. We don't typically backport changes unless they are critical and they are no viable workarounds. The referenced issue (https://github.com/dotnet/aspnetcore/issues/54325) outlines a workaround. Let me know if it don't work for you.
