### PR TITLE
Capture target from delegates and MethodInfo

### LINKED ISSUE #41188: Support for route handler filters in minimal APIs issue
.net version is 7.0.100-preview.3.22179.4

The following code will work：
```
string SayHello(string name) => $"Hello, {name}!.";
app.MapGet("/hello/{name}", SayHello)
    .AddFilter(async (RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next) =>
    {
        return await next(context);
    });
```

But the following code doesn't work：
```
app.MapGet("/hello/{name}", (string name) => $"Hello, {name}!.")
    .AddFilter(async (RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next) =>
    {
        return await next(context);
    });
```
System.NullReferenceException:“Object reference not set to an instance of an object.”

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/41188

### CODE REVIEW

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -250,22 +252,28 @@ private static FactoryContext CreateFactoryContext(RequestDelegateFactoryOptions
...
 
-    private static RouteHandlerFilterDelegate CreateFilterPipeline(MethodInfo methodInfo, Expression? target, FactoryContext factoryContext)
+    private static RouteHandlerFilterDelegate CreateFilterPipeline(MethodInfo methodInfo, Expression? targetExpression, FactoryContext factoryContext, Expression<Func<HttpContext, object?>>? targetFactory)
     {
         Debug.Assert(factoryContext.Filters is not null);
         // httpContext.Response.StatusCode >= 400
         // ? Task.CompletedTask
-        // : handler((string)context.Parameters[0], (int)context.Parameters[1])
+        // : {
+        //  target = targetFactory(httpContext);
```
Comment (davidfowl) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:261]: this is confusing, where is target used?

Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:261]: In `handler`, which might be something like `Convert(target).MethodName(parameters)`

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 2]
```diff
@@ -4251,6 +4251,73 @@ string HelloName(string name)
...
+            BindingFlags.NonPublic | BindingFlags.Instance,
+            new[] { typeof(string) });
+        var httpContext = CreateHttpContext();
+        httpContext.Request.Query = new QueryCollection(new Dictionary<string, StringValues>
+        {
+            ["name"] = "TestName"
+        });
+
+        // Act
+        var factoryResult = RequestDelegateFactory.Create(methodInfo!, null, new RequestDelegateFactoryOptions()
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4303]: We need a test that passes in a non-null targetFactory and does something with the HttpContext so we know it's flowing properly

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 3]
```diff
@@ -4251,6 +4251,73 @@ string HelloName(string name)
...
+        });
+
+        // Act
+        var factoryResult = RequestDelegateFactory.Create((string name) => "Hello, {name}!", new RequestDelegateFactoryOptions()
+        {
+            RouteHandlerFilterFactories = new List<Func<RouteHandlerContext, RouteHandlerFilterDelegate, RouteHandlerFilterDelegate>>()
+            {
+                (routeHandlerContext, next) => async (context) =>
+                {
+                    Console.WriteLine(context.Parameters[0]);
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4271]: Console.WriteLine is odd in a test 😃

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 4]
```diff
@@ -250,22 +252,28 @@ private static FactoryContext CreateFactoryContext(RequestDelegateFactoryOptions
...
+        //  handler((string)context.Parameters[0], (int)context.Parameters[1]);
+        // }
         var filteredInvocation = Expression.Lambda<RouteHandlerFilterDelegate>(
             Expression.Condition(
                 Expression.GreaterThanOrEqual(FilterContextHttpContextStatusCodeExpr, Expression.Constant(400)),
                 CompletedValueTaskExpr,
                 Expression.Block(
-                    new[] { TargetExpr },
+                    new[] { TargetExpr, HttpContextExpr },
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:269]: The HttpContextExpr here worries me. Looks like it might define a local which wouldn't be good. I think we should instead be using FilterContextHttpContextExpr directly in the Expression.Invoke below

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs (hunk 3 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4271]: Yeah, not totally necessary for this test. Will nuke it.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 4 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:269]: Good call!

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs (hunk 2 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4303]: Good call -- I'll add a test to this effect.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:261]: I added a note to the comment clarifying where the `target` comes in.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 5]
```diff
@@ -250,22 +252,29 @@ private static FactoryContext CreateFactoryContext(RequestDelegateFactoryOptions
...
-    private static RouteHandlerFilterDelegate CreateFilterPipeline(MethodInfo methodInfo, Expression? target, FactoryContext factoryContext)
+    private static RouteHandlerFilterDelegate CreateFilterPipeline(MethodInfo methodInfo, Expression? targetExpression, FactoryContext factoryContext, Expression<Func<HttpContext, object?>>? targetFactory)
     {
         Debug.Assert(factoryContext.Filters is not null);
         // httpContext.Response.StatusCode >= 400
         // ? Task.CompletedTask
-        // : handler((string)context.Parameters[0], (int)context.Parameters[1])
+        // : {
+        //  target = targetFactory(httpContext);
+        //  // handler is ((Type)target).MethodName(parameters);
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:262]:
```suggestion
        // handler is ((Type)target).MethodName(parameters);
```

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs (hunk 3 above)
Comment (BrennanConroy) [reply src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4271]: 😢

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 6]
```diff
@@ -4251,6 +4251,114 @@ string HelloName(string name)
...
+        Assert.Equal(200, httpContext.Response.StatusCode);
+    }
+
+    string GetString(string name)
+    {
+        return $"Hello, {name}!";
+    }
+
+    [Fact]
+    public async Task RequestDelegateFactory_InvokesFilters_OnMethodInfoWithTargetFactory()
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4289]:
```suggestion
    public async Task RequestDelegateFactory_InvokesFilters_OnMethodInfoWithNullTargetFactory()
```

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 7]
```diff
@@ -4251,6 +4251,114 @@ string HelloName(string name)
...
+            context.Items["invoked"] = true;
+            return methodInfo!.DeclaringType!;
+        };
+        var factoryResult = RequestDelegateFactory.Create(methodInfo!, targetFactory, new RequestDelegateFactoryOptions()
+        {
+            RouteHandlerFilterFactories = new List<Func<RouteHandlerContext, RouteHandlerFilterDelegate, RouteHandlerFilterDelegate>>()
+            {
+                (routeHandlerContext, next) => (context) =>
+                {
+                    return ValueTask.FromResult<object?>(Results.Created("/foo", "Great!"));
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4348]: Wait, these tests aren't hitting the problem code-path. They need to call `next` in order to test the previously broken scenario.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 5 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:262]: My brain reasoned about this like a comment in a code sample. 😅

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 8]
```diff
@@ -4251,6 +4251,113 @@ string HelloName(string name)
...
+                {
+                    return await next(context);
+                }
+            }
+        });
+        var requestDelegate = factoryResult.RequestDelegate;
+        await requestDelegate(httpContext);
+
+        // Assert
+        Assert.Equal(200, httpContext.Response.StatusCode);
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4279]: Sorry for being a pain, but this should verify the "Hello, TestName!" response otherwise for all we know the code doesn't invoke the delegate.

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 9]
```diff
@@ -4251,6 +4251,113 @@ string HelloName(string name)
...
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4316]: Same here

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 10]
```diff
@@ -4251,6 +4251,113 @@ string HelloName(string name)
...
+        Assert.True(invoked);
+        var invokedInContext = Assert.IsType<bool>(httpContext.Items["invoked"]);
+        Assert.True(invokedInContext);
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:4358]: And here

**Review by BrennanConroy — APPROVED** [review]
Looks great! Especially changing the "target" param name to "targetExpression" 😃 

Just some final test nits.
