### PR TITLE
Fix IRequestCookieCollection.TryGetValue() possible null reference

### LINKED ISSUE #42032: IRequestCookieCollection.TryGetValue() causes "Possible null reference" even if if-statement and return is used
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Consider the following code:
image

### Expected Behavior

Since the if-statement returns if `TryGetValue()` returns false, the compiler should be aware that the value can not be null.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

6.0.102

### Anything else?

I already figured out how to fix this, and will open a PR soon.

### PR DESCRIPTION
**Pull request by Visne**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

`TryGetValue()` currently has the parameter `[MaybeNullWhen(false)] out string? value`. This is nonsensical, as `MaybeNullWhen` will tell the compiler that a value might be null even if the type disallows it. Since `value` has type `string?`, the attribute does nothing. This causes an annoying issue where the compiler will think that the returned value can be null even if a null-check has been performed using the return value of `TryGetValue()`:

image

Fixes #42032

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42033) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42033) before we can accept your contribution.<br/><br/>:x: Visne [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42033)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=42033) it.</sub>

File: src/Http/Http/src/Internal/RequestCookieCollection.cs [hunk 1]
```diff
@@ -117,7 +117,7 @@ public bool ContainsKey(string key)
         return Store.ContainsKey(key);
     }
 
-    public bool TryGetValue(string key, [MaybeNullWhen(false)] out string? value)
+    public bool TryGetValue(string key, [MaybeNullWhen(false)] out string value)
```
Comment (martincostello) [inline src/Http/Http/src/Internal/RequestCookieCollection.cs:120]: `value` is assigned the value `null` on line 124. You're just "hiding" the nulls from the signature, which is misleading, and isn't really fixing the original issue.

Comment (Visne) [reply src/Http/Http/src/Internal/RequestCookieCollection.cs:120]: That's what the MaybeNullWhen is for. Look at for example TryGetValue from Dictionary, and then you will see it is not nullable, but it has MaybeNullWhen. MaybeNullWhen tells the compiler that a value might be null _even if the type doesn't allow it_, but if the type is already nullable then the attribute is redundant.

You can look at the documentation of MaybeMullWhenAttribute for clarification.

Comment (halter73) [inline src/Http/Http/src/Internal/RequestCookieCollection.cs:120]:
```suggestion
    public bool TryGetValue(string key, [NotNullWhen(true)] out string? value)
```

> Look at for example TryGetValue from Dictionary

I think dictionary is using `MaybeNullWhen` because `TValue` is generic and `TValue?` would lead to `TryGetValue` producing a nullable which is undesirable. Eg. `Dictionary<MyKey, MyStruct>.TryGetValue(myKey, out Nullable<MyStruct> myStruct)`. For non-generic parameters, I think it's more common to use `NotNullWhen`. [Example](https://github.com/dotnet/runtime/blob/eef6c7f6cb7f73163313d349fbb796f37b4c3996/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/MemoryMarshal.cs#L381).

**Comment by halter73** [comment]
@adityamandaleeka I don't think nullability changes need to go through API review if they more accurately reflect the actual behavior. It can be source breaking, but we've decided it's more important to get nullablity right in the end. See https://github.com/dotnet/aspnetcore/pull/41959#issue-1254629195.

File: src/Http/Http/src/Internal/RequestCookieCollection.cs (hunk 1 above)
Comment (Visne) [reply src/Http/Http/src/Internal/RequestCookieCollection.cs]: Yeah, that makes sense to me. Also makes it so the API doesn't change.

**Review by halter73 — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks
