### PR TITLE
Throw BadHttpRequestException for non-ASCII in absolute-form targets

### LINKED ISSUE #41071: Kestrel should throw BadHttpRequestException instead of InvalidOperationExceptions for absolute-form targets with non-ASCII characters
```
GET /ÿÿÿÿÿÿÿÿÿÿÿ HTTP/1.1
```

Making a request like the above to Kestrel with latin1 encoding would result in the following error:

```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: '/\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseTarget(TargetOffsetPathLength targetPath, Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnOriginFormTarget(TargetOffsetPathLength targetPath, Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ParsingHandler.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine)
```

The absolute-form version of this request results in an InvalidOperationException which is a lot harder to diagnose.

```
GET http://localhost/ÿÿÿÿÿÿÿÿÿÿÿ HTTP/1.1
```

```
InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.StringUtilities.GetAsciiStringNonNullCharacters(Span`1 buffer, IntPtr state)
   at System.String.Create[TState](Int32 length, TState state, SpanAction`2 action)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.StringUtilities.GetAsciiStringNonNullCharacters(ReadOnlySpan`1 span)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.HttpUtilities.GetAsciiStringNonNullCharacters(Span`1 span)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnAbsoluteFormTarget(TargetOffsetPathLength targetPath, Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine)
```

This happens because Kestrel doesn't catch the exception thrown from GetAsciiStringNonNullCharacters like we do in the more common origin-form case

https://github.com/dotnet/aspnetcore/blob/b24acedc162732423811c4fc3e02a3e6a6283681/src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs#L396-L399

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix #41071

This change makes it so that when non-ASCII chars are included with absolute-form targets, we show a meaningful `BadHttpRequestException` instead of an opaque `InvalidOperationException: Operation is not valid due to the current state of the object.`

After this change, `GET http://127.0.0.1:5000/ÿÿÿÿÿÿÿÿÿÿÿ HTTP/1.1` will result in this:

```
      Connection id "0HMH4OCKNS0RO" bad request data: "Invalid request target: 'http://127.0.0.1:5000/\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF'"
      Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: 'http://127.0.0.1:5000/\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF'
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnAbsoluteFormTarget(TargetOffsetPathLength targetPath, Span`1 target) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 527
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 286
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ParsingHandler.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1ParsingHandler.cs:line 48
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySpan`1 requestLine) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpParser.cs:line 164
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, SequenceReader`1& reader) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpParser.cs:line 68
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(SequenceReader`1& reader) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 196
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(SequenceReader`1& reader) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 164
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 679
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 639
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in C:\code\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 564
```

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs [hunk 1]
```diff
@@ -512,9 +512,20 @@ private void OnAbsoluteFormTarget(TargetOffsetPathLength targetPath, Span<byte>
...
+                // so we will need to generate a new string.
+                RawTarget = _parsedRawTarget = target.GetAsciiStringNonNullCharacters();
+            }
+            catch (InvalidOperationException)
+            {
+                // GetAsciiStringNonNullCharacters throws an InvalidOperationException if there are
+                // invalid characters in the string. This is hard to understand/diagnose, so let's
+                // catch it and instead throw a more meaningful error. This matches the behavior in
+                // the origin-form case.
+                ThrowRequestTargetRejected(target);
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs:527]: Can the IOE exception be captured and flow as an inner exception?

Comment (adityamandaleeka) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs:527]: @Tratcher Looking at the IOE I don't think there's anything there that would really be useful. This approach is also consistent with how we surface the rejected target errors in other places.

**Review by Tratcher — APPROVED** [review]
