### PR TITLE
[Blazor] Allow `null` parameter values to be supplied to interactive components via enhanced page update

### LINKED ISSUE #52434: [Blazor] Supplying a `null` parameter value to an interactive root component causes a `NullReferenceException` on enhanced navigation
## Summary

If a `null` value is supplied as a parameter to a render mode boundary component during static SSR, and the SSR'd component is matched up with an existing interactive root component, a `NullReferenceException` gets thrown by the framework.

## Steps to reproduce

1. Create a Blazor Web App with Server interactivity
2. Define a component (`MyComponent.razor`):
    ```razor
    @inject NavigationManager NavigationManager
    
    <button @onclick="@(() => NavigationManager.Refresh())">Refresh</button>
    
    @code {
        [Parameter]
        public string? Value { get; set; }
    }
    ```
4. Render the component from `Home.razor` and supply the value `null` for the `Value` parameter:
    ```razor
    <MyComponent Value="@null" @rendermode="InteractiveServer" />
    ```
5. Run the app
6. Click the button labeled "Refresh"
7. Observe that an exception gets thrown and the circuit gets terminated

## Relevant output

Stack trace:

```text
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.WebRootComponentParameters.DefinitelyEquals(Microsoft.AspNetCore.Components.WebRootComponentParameters other) Line 43
	at Microsoft.AspNetCore.Components\WebRootComponentParameters.cs(43)
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.WebRootComponentManager.WebRootComponent.UpdateAsync(Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer renderer, System.Type newComponentType, Microsoft.AspNetCore.Components.ComponentMarkerKey? newKey, Microsoft.AspNetCore.Components.WebRootComponentParameters newParameters) Line 245
	at Microsoft.AspNetCore.Components.Server.Circuits\RemoteRenderer.cs(245)
.
.
.
```

## Proposed fix

Update [`WebRootComponentParameters`](https://github.com/dotnet/aspnetcore/blob/5b1ad1ee4934be7d587e50670524876763cd45eb/src/Components/Shared/src/WebRootComponentParameters.cs#L48-L49) to account for the possibility that the parameter values are `null` rather than being valid `JsonElement`s.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Allow `null` parameter values to be supplied to interactive components via enhanced page update

Fixes an issue where a `NullRefrenceException` would be thrown if an enhanced page update supplied a `null` parameter to an interactive root component. This would cause the circuit to crash when using Server interactivity, and it would cause an error to be logged in the browser console when using WebAssembly interactivity.

Fixes #52434

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs [hunk 1]
```diff
@@ -597,6 +597,36 @@ public void LocationChangingEventGetsInvokedOnEnhancedNavigationOnlyForRuntimeTh
...
+        Browser.Exists(By.TagName("nav")).FindElement(By.LinkText($"Null component parameter ({renderMode})")).Click();
+        Browser.Equal("Page rendering component with null parameter", () => Browser.Exists(By.TagName("h1")).Text);
+        Browser.Equal("0", () => Browser.Exists(By.Id("current-count")).Text);
+
+        Browser.Exists(By.Id("button-increment")).Click();
+        Browser.Equal("1", () => Browser.Exists(By.Id("current-count")).Text);
+
+        // This refresh causes the interactive component to receive a 'null' parameter value
+        Browser.Exists(By.Id("button-refresh")).Click();
+        Browser.Equal("1", () => Browser.Exists(By.Id("current-count")).Text);
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs:618]: This doesn't seem like an effective assertion, since it's checking the same thing checked on L614 and could pass falsely just because the UI hasn't updated yet.

Can we validate that the "refresh" command actually completed before this assertion?

**Review by SteveSandersonMS — APPROVED** [review]
Possibly one small tweak to the E2E tests would be good, but besides that, nice!
