### PR TITLE
consider escaped commas in LDAP distinguished name

### LINKED ISSUE #45648: Linux: RBAC claims resolution fails if user has group with comma in name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Real-world AD deployments can have groups with comma in name (example: `Testing group, City`). In this case, when nested claims resolution is enabled, Linux clients will get exception on resolving this kind of group, because group Common Name parsed from Distinguished Name (`CN=Testing group\,City,OU=Department,DC=contoso,DC=com`) incorrectly (`Testing group,`).

### Expected Behavior

In case, when nested claims resolution is enabled, expected that Common Name of each user's group will parse correctly, even if it contains comma.

### Steps To Reproduce

1. Set up any AD server (contoso.com in the example).
2. Add AD group with comma in name (`Testing group, City`).
3. Add user to that group.
4. Create a simple API project, set up RBAC claims resolution:

```
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate(options =>
{
    if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        return;
    }
    
    options.EnableLdap(settings =>
    {
        settings.Domain = "contoso.com";
        settings.MachineAccountName = "someuser";
        settings.MachineAccountPassword = "somepassword";
    });
});

services.AddAuthorization();
```

```
[ApiController]
[Route("api/[controller]")]
[Authorize(Roles = "GroupA")]
public class SomeController : Controller
{
    [HttpGet]
    [Route("someMethod")]
    public async Task<ActionResult<int>> SomeMethod()
    {
        return 1;
    }
 }
```

### Exceptions (if any)

System.DirectoryServices.Protocols.LdapException: The search filter is invalid.

### .NET Version

6.0.11

### Anything else?

- ASP.NET Core 6.0, via docker dotnet/aspnet:6.0
- Visual Studio 2022

### PR DESCRIPTION
**Pull request by teh13th**
# Consider escaped commas in LDAP distinguished name

## Description

In real world DN can be like this: `CN=Testing group\,City,OU=Department,DC=contoso,DC=com`. We need to process this case correct - consider escaped comma and don't fail.
Without this fix DN parsing is incorrect -> we getting `Testing group\` as CN instead of  `Testing group`. Next, we try to resolve group with incorrect CN and getting exception.

Fixes #45648

### CODE REVIEW

File: src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs [hunk 1]
```diff
@@ -6,13 +6,16 @@
...
 using System.Text;
+using System.Text.RegularExpressions;
 using Microsoft.Extensions.Caching.Memory;
 using Microsoft.Extensions.Logging;
 
 namespace Microsoft.AspNetCore.Authentication.Negotiate;
 
 internal static class LdapAdapter
 {
+    private static readonly Regex DistinguishedNameSeparator = new Regex(@"(?<!\\),");
```
Comment (danmoseley) [inline src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs:17]: Use source generator?

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators

(I don't have context on the change, but we would prefer statically defined Regex are source generated)

Comment (danmoseley) [reply src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs:17]: I just realized I'm not in the runtime repo, so this may not apply...

Comment (teh13th) [reply src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs]: Done.

Comment (danmoseley) [reply src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs]: I suggest the method name should end with "Regex" as this is the emerging convention.

I'll let a domain expert review the correctness of the change itself...

**Comment by teh13th** [comment]
@HaoK, @Tratcher can you look this, please?

**Comment by davidfowl** [comment]
Can you add some unit tests?

**Comment by davidfowl** [comment]
> @HaoK, @Tratcher can you look this, please?

Also, people are still on vacation so expect slow responses until next week.

File: src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs [hunk 2]
```diff
@@ -6,13 +6,17 @@
...
+using System.Text.RegularExpressions;
 using Microsoft.Extensions.Caching.Memory;
 using Microsoft.Extensions.Logging;
 
 namespace Microsoft.AspNetCore.Authentication.Negotiate;
 
-internal static class LdapAdapter
+internal static partial class LdapAdapter
 {
+    [GeneratedRegex(@"(?<!\\),")]
```
Comment (joperezr) [inline src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs:17]: Can a valid CN name end with a backlash? If so, we may need to also validate that the backlash is actually escaping the comma as opposed to be escaped by a previous backlash itself.

Comment (teh13th) [reply src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs]: Backslash can be escaped too (https://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx). Consider this fact in regex.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45649) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45649) before we can accept your contribution.<br/><br/>:x: teh13th [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45649)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=45649) it.</sub>

**Comment by teh13th** [comment]
> Some checks haven’t completed yet

Done.

**Comment by teh13th** [comment]
@Tratcher, @danmoseley, @joperezr, @HaoK ping :)

**Comment by HaoK** [comment]
Thanks for the fix @teh13th! I'm just triggering a rerun of the build and marking this as auto merge once that passes.

**Review by HaoK — APPROVED** [review]

**Comment by teh13th** [comment]
@HaoK something gone wrong.
