### PR TITLE
Fix #4212 area ambient value page->controller

### LINKED ISSUE #4212: Link generation behaviour change: page to controller in area
Linking from a page in an area to a controller in the same area, without specifying the area is changing.

* Succeeded in 2.1
* Succeeded in 2.2 (unintentionally)
* Fails in 3.0 (current behaviour)

We could make 3.0 succeed with a moderate amount of additional work. The question is whether anyone is doing this and if it is important to customers.

This issue is something to evaluate near the end of 3.0 to make a decision.

Affected test: PagesInAreas_CanGenerateLinksToControllersAndPages
```cs
<a asp-controller="Home" asp-action="Index">Link to area action</a>
```

PR that is changing this - https://github.com/aspnet/Routing/pull/914

### PR DESCRIPTION
**Pull request by rynowak**
This change enhances our ambient value logic to also deal with required
values. In 2.2 we introduced a 'required values' semantic to allow route
values to appear "to the left" of a route pattern for the purpose of
ambient values copying. This is a complicated way of saying "when you
like to a different endpoint then discard the ambient values".

What we didn't consider is that some ambient values are special (like
area). So basically, we'll allow an ambient value to be used if it's
part of the required values - even if we've already decided to discard
the ambient values.

This is a pretty surgical fix and only affected the desired scenario
based on tests.

-----

I also removed an optimization that I think is broken. I put an earlier
optimization in place that attempted to count ambient values as they
were "seen" to try and avoid some extra copying. This copying loop has a
cost even if it no-ops which is what I was trying to prevent.

Unfortunately since we added 'required values' - it's now possible for
an ambient value to be double-counted, which makes this optimization
incorrect.

### CODE REVIEW

File: src/Http/Routing/src/Template/TemplateBinder.cs [hunk 1]
```diff
@@ -118,10 +118,9 @@ public TemplateValuesResult GetValues(RouteValueDictionary ambientValues, RouteV
             var slots = new KeyValuePair<string, object>[_slots.Length];
             Array.Copy(_slots, 0, slots, 0, slots.Length);
 
-            // Keeping track of the number of 'values' and 'ambient values' we've processed can be used to avoid doing
+            // Keeping track of the number of 'values' we've processed can be used to avoid doing
             // some expensive 'merge' operations later.
             var valueProcessedCount = 0;
-            var ambientValueProcessedCount = 0;
```
Comment (rynowak) [inline src/Http/Routing/src/Template/TemplateBinder.cs]: Removed all usage of this because we can't count this accurately in practice.

File: src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/RazorPagesWithBasePathTest.cs [hunk 2]
```diff
@@ -323,7 +323,7 @@ public async Task PagesInAreas_CanGenerateLinksToControllersAndPages()
             var expected =
 @"<a href=""/Accounts/Manage/RenderPartials"">Link inside area</a>
 <a href=""/Products/List/old/20"">Link to external area</a>
-<a href="""">Link to area action</a>
+<a href=""/Accounts"">Link to area action</a>
```
Comment (rynowak) [inline src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/RazorPagesWithBasePathTest.cs]: This was the original regression.

File: src/Http/Routing/src/Template/TemplateBinder.cs [hunk 3]
```diff
@@ -226,15 +220,10 @@ public TemplateValuesResult GetValues(RouteValueDictionary ambientValues, RouteV
 
                 var parameter = parameters[i];
 
+                // We are copying **all** ambient values OR
```
Comment (pranavkm) [inline src/Http/Routing/src/Template/TemplateBinder.cs]: OR?

**Comment by JamesNK** [comment]
https://github.com/aspnet/AspNetCore/issues/5055 is also a link generation issue with required values. Are they the same issue?

**Comment by rynowak** [comment]
> #5055 is also a link generation issue with required values. Are they the same issue?

Nope. That issue is much much much more frightening.

File: src/Http/Routing/src/Template/TemplateBinder.cs [hunk 4]
```diff
@@ -261,6 +250,29 @@ public TemplateValuesResult GetValues(RouteValueDictionary ambientValues, RouteV
                     }
                 }
 
+                // This might an ambient value that matches a required value. We want to use these even if we're
```
Comment (JamesNK) [inline src/Http/Routing/src/Template/TemplateBinder.cs]: Clean up comment

**Review by JamesNK — APPROVED** [review]

File: src/Http/Routing/src/Template/TemplateBinder.cs (hunk 4 above)
Comment (rynowak) [reply src/Http/Routing/src/Template/TemplateBinder.cs]: Sorry can you make a suggestion? I don't get what you're asking me to change.

Comment (JamesNK) [reply src/Http/Routing/src/Template/TemplateBinder.cs]:
```suggestion
                // This might be an ambient value that matches a required value. We want to use these even if we're
```
