### PR TITLE
Load IConfigurationProviders once in WebApplicationBuilder

### LINKED ISSUE #37030: [Bug] Memory stream is closed inside WebApplicationBuilder and MauiAppBuilder while configuring the host configuration.
### Description
When configuring the host configuration from MauiProgram.cs, using the dotnet Core Generic Host. 
The exception "Stream was not readable" is thrown.

This bug appears when adding a MemoryStream to the configurationBuilder.

Below is an image of the locals from the de Microsoft.Maui.MauiAppBuilder, as you can see it tries to read the Memory Stream twice. Throwing a System.ObjectDisposedException the second time.

MauiAppBugLocal png

### Steps to Reproduce
I have added a reproduction link. For now it is added as a google drive link as I had trouble inserting the .zip file directly.
Sorry for the inconvenience.

### Expected Behavior
Configure the host configuration using the Memory Stream.

### Actual Behavior
MauiAppBuilder throws  System.ArgumentException: 'Stream was not readable.'

### Basic Information

- Version with issue: .NET MAUI Preview 8
- Last known good version: .NET MAUI Preview 7
- IDE: Visual Studio 2022 Preview 4
- Affected Devices:  Android 11.0 - API 30

### Reproduction Link
https://drive.google.com/file/d/1m2nfYmfDV2guJLfPAtlMJJupTHU57YH1/view?usp=sharing

### LINKED ISSUE #37046: WebApplication does not react to appsettings.json changes
### Describe the bug

Starting in rc2, WebApplicationBuilder indirectly disposes IConfigurationProviders that are still in use by WebApplication. For FileConfigurationProviders, this prevents IConfigurationProvider.GetReloadToken() from firing. This means changes to configuration sources like appsettings.json are not observed after the WebApplication is built.

### To Reproduce

Run the following commands:

```
> dotnet new globaljson --sdk-version 6.0.100-rc.2.21472.38
> dotnew new web
> dotnet run
```

While the application is running, change `"Microsoft.AspNetCore": "Warning"` to `"Microsoft.AspNetCore": "Information"` and make a request.

Expected output:

```
C:\dev\halter73\MinimalPlayground master ≢  ~1 ❯ dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7159
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5016
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\halter73\MinimalPlayground
dbug: Microsoft.AspNetCore.Server.Kestrel[0]
      Config reload token fired. Checking for changes...
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMC22SP3DB29" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMC22SP3DB29" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[3]
      Connection 0HMC22SP3DB29 established using the following protocol: Tls12
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:7159/ - -
...
```

Actual output:

```
> dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7159
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5016
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\halter73\MinimalPlayground
```

### PR DESCRIPTION
**Pull request by halter73**
This updates `WebApplicationBuilder` to only load `IConfigurationProvider`s once. Before this change, they would be loaded twice. Once by `Configurationmanager` and then again by the inner generic host's `ConfigurationBuilder`.

This causes problems with `StreamConfigurationSource`s like the one used by `builder.Configuration.AddJsonStream(jsonStream)` throwing errors similar to the following:

```
System.Text.Json.JsonReaderException
  HResult=0x80131500
  Message=The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
```

Fixes #37030
Fixes #37046

### CODE REVIEW

**Comment by davidfowl** [comment]
I think this change might be too braking. Nothing looks at sources but lots of things look at providers. Having them wrapped is pretty breaking. For example GetDebugView is completely broken by this change

**Comment by halter73** [comment]
> I think this change might be too braking. Nothing looks at sources but lots of things look at providers. Having them wrapped is pretty breaking. For example GetDebugView is completely broken by this change

GetDebugView() is fixed pretty trivially by forwarding ToString() which I just did in [this commit](https://github.com/dotnet/aspnetcore/pull/37039/commits/2570a38e09ab192ce12f61fc179c54f928486f11). Do you have examples of any code looking at the actual type of the providers @davidfowl?

**Comment by davidfowl** [comment]
I generally don't feel comfortable with wrapping providers because they  are exposed on IConfigurationRoot. I'm super paranoid about doing anything funky that changes the behavior after the service provider is built. There's too much code running not to break stuff

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 1]
```diff
@@ -212,9 +213,21 @@ public WebApplication Build()
...
+                    providerList[i] = wrappedProvider.OriginalProvider;
+                }
+            }
+
             // Make builder.Configuration match the final configuration. To do that
-            // we clear the sources and add the built configuration as a source
-            ((IConfigurationBuilder)Configuration).Sources.Clear();
+            // we recreate the ConfigurationManager and add the built configuration as a source.
+            // We do not clear or dispose the old ConfigurationManager as this would dispose IConfigurationProviders that are in use.
+            Configuration = new ConfigurationManager();
```
Comment (davidfowl) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:230]: We need to fix the regression here where the captured reference doesn't see the final configuration.  I wonder if we can pull off a similar trick that we do with the  `IConfigurationBuilder`. If only the list of providers here wasn't a copy...

https://github.com/dotnet/runtime/blob/51e4954e785732cc551a841e9567d7bf2073ee21/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L75-L86

Ideally we wouldn't use private reflection here but it looks like the only answer currently...

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 2]
```diff
@@ -212,9 +213,21 @@ public WebApplication Build()
 
             _builtApplication = new WebApplication(_hostBuilder.Build());
 
+            // We know that ConfigurationBuilder constructs ConfigurationRoot with a List<IConfigurationProvider> and all the
+            // IgnoreLoadConfigurationProviders have been "loaded", so we can put the originals back.
+            var providerList = (List<IConfigurationProvider>)((IConfigurationRoot)_builtApplication.Configuration).Providers;
```
Comment (davidfowl) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:218]: We should be defensive here. If the user adds a custom `IConfiguration` this will explode. At best it should just noop.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 3]
```diff
@@ -100,7 +99,7 @@ internal WebApplicationBuilder(WebApplicationOptions options, Action<IHostBuilde
             Host = new ConfigureHostBuilder(hostContext, Configuration, Services);
             WebHost = new ConfigureWebHostBuilder(webHostContext, Configuration, Services);
 
-            Services.AddSingleton<IConfiguration>(Configuration);
+            Services.AddSingleton<IConfiguration>(_ => Configuration);
```
Comment (captainsafia) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:102]: Is there a functional difference with this change?

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 4]
```diff
@@ -723,7 +722,28 @@ public void ManuallyAddingConfigurationAsServiceWorks()
             var app = builder.Build();
 
             // These are different
```
Comment (davidfowl) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:724]:
```suggestion
```

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 5]
```diff
@@ -706,7 +705,7 @@ public void CanResolveIConfigurationBeforeBuildingApplication()
...
```
Comment (davidfowl) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:707]:
```suggestion
```

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 6]
```diff
@@ -205,18 +192,23 @@ public WebApplication Build()
                 // Drop the reference to the existing collection and set the inner collection
                 // to the new one. This allows code that has references to the service collection to still function.
                 _services.InnerCollection = services;
+
+                // Make builder.Configuration match the final configuration. To do that, we add the additional
+                // providers in the inner _hostBuilders's Configuration to the ConfigurationManager.
+                foreach (var provider in ((IConfigurationRoot)context.Configuration).Providers)
```
Comment (davidfowl) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:198]: I love this! There are 1 edge case we should handle, clearing providers. If the web application factory clears providers then clear providers on the configuration manager

The other is too edgy: somebody replaces `context.Configuration` with another implementation that doesn't implement `IConfigurationRoot`.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 3 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:103]: By changing the service descriptor from an instance to a factory, this gives the host ownership and now it disposes the ConfigurationManager. What's interesting is HostBuilder itself was using the same trick for its ConfigurationRoot and that no longer gets disposed, but it doesn't matter because ConfigurationManager took ownership of all the providers except the ChainedConfigurationSource to itself.

**Comment by halter73** [comment]
@dotnet/minimal-apis I think this is ready for another review.

I've updated the approach to reverse the direction we're chaining configuration. Before, we chained the HostBuilder's IConfiguration to the WebApplicationBuilder's ConfigurationManager after the host was built. Now we chain the ConfigurationManager to the HostBuilders IConfigurationBuilder when we start building the host. This also makes the ConfigurationManager the IConfiguration that's resolved from DI rather than the HostBuilder's IConfiguration.

This forces us to copy IConfigurationProviders in the opposite direction we did before, and we still have to wrap these providers to prevent double loads. However, we expect this will mostly be test providers, so not preserving the provider types should be less of an issue.

File: src/DefaultBuilder/src/ConfigurationProviderSource.cs [hunk 7]
```diff
@@ -64,6 +65,11 @@ public bool TryGet(string key, out string value)
                 return _provider.TryGet(key, out value);
             }
 
+            // Provide access to the original IConfigurationProvider via a single-element IEnumerable to code that goes out of its way to look for it.
+            public IEnumerator<IConfigurationProvider> GetEnumerator() => new List<IConfigurationProvider> { _provider }.GetEnumerator();
```
Comment (davidfowl) [inline src/DefaultBuilder/src/ConfigurationProviderSource.cs:69]: I was gonna suggest you could use the compiler generated enumerable:

```C#
IEnumerable<IConfigurationProvider> Enumerable()
{
    yield return _provider;
}
```

Then do GetEnumerator from that.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 3 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:103]: > but it doesn't matter because ConfigurationManager took ownership of all the providers except the ChainedConfigurationSource to itself.

What about the dangling change tokens?

Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:103]: Since all the providers get disposed, I would expect the change tokens to be unregistered from any filewatchers or anything like that (and manual testing confirms that). We could do a [similar trick to HostBuilder](https://github.com/dotnet/runtime/blob/3fa2860847df903b448d0af228b3362ca72480db/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L285) and call `Services.GetService<IEnumerable<IConfiguration>>()` to resolve both the HostBuilder's ConfgiruationRoot and WebApplicationBuilder's ConfigurationManager out of DI and ensure both get disposed. This will double-dispose providers added by tests or IHostingStartups, but that should be safe.

File: src/DefaultBuilder/src/ConfigurationProviderSource.cs (hunk 7 above)
Comment (halter73) [reply src/DefaultBuilder/src/ConfigurationProviderSource.cs:69]: Not that I would expect this to ever be called repeatedly, but I was still curious whether this improves performance. It doubles it.

```
|                            Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|---------------------------------- |---------:|---------:|---------:|-------:|----------:|
|           EnumerateListEnumerable | 33.46 ns | 0.517 ns | 0.432 ns | 0.0122 |     128 B |
| EnumerateIteratorMethodEnumerable | 15.75 ns | 0.255 ns | 0.239 ns | 0.0038 |      40 B |
```

<details><summary>Benchmark code</summary>

```C#
using System.Collections;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run(typeof(Program).Assembly);

[MemoryDiagnoser]
public class EnumerableBenchmark
{
    private ListEnumerable _listEnumerable = new();
    private IteratorMethodEnumerable _iteratorMethodEnumerable = new();

    [Benchmark]
    public object EnumerateListEnumerable() => GetLast(_listEnumerable);

    [Benchmark]
    public object EnumerateIteratorMethodEnumerable() => GetLast(_iteratorMethodEnumerable);

    private static object GetLast(IEnumerable<object> collection)
    {
        object? result = null;

        foreach (var item in collection)
        {
            result = item;
        }

        return result;
    }

    private class ListEnumerable : IEnumerable<object>
    {
        public IEnumerator<object> GetEnumerator() => new List<object> { this }.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => new List<object> { this }.GetEnumerator();
    }

    private class IteratorMethodEnumerable : IEnumerable<object>
    {
        public IEnumerator<object> GetEnumerator() => IteratorMethod().GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => IteratorMethod().GetEnumerator();

        private IEnumerable<object> IteratorMethod()
        {
            yield return this;
        }
    }
}
```
</details>

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 3 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:103]: I did the `GetService<IEnumerable<IConfiguration>>()` thing: https://github.com/dotnet/aspnetcore/pull/37039/files#diff-f0e6f715f99a336de90bdbeef327cb71b7ee811d00d7c1722049557adaa009c5R227

**Review by davidfowl — APPROVED** [review]
