### PR TITLE
Fix stale values from [SupplyParameterFromQuery]

### LINKED ISSUE #52483: Exception when navigating between Blazor pages with a [SupplyParameterFromQuery] of the same name but different type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If there are two Blazor pages with a query parameter of the same name, but different type, navigating between them will cause an exception to be thrown.

```razor
@page "/TestInt"
<a href="/TestGuid?p=47259a22-9fd8-4938-b40d-e5c8d8642a3d">TestGuid</a>
@code {
    [Parameter]
    [SupplyParameterFromQuery]
    public int? p { get; set; }
}
```

```razor
@page "/TestGuid"
<a href="/TestInt?p=123">TestInt</a>
@code {
    [Parameter]
    [SupplyParameterFromQuery]
    public Guid? p { get; set; }
}
```

In the above example blazor tries to parse `123` as `Guid?` when you navigate from `/TestInt?p=123` to `/TestGuid?p=47259a22-9fd8-4938-b40d-e5c8d8642a3d`

```
Error: System.InvalidOperationException: Cannot parse the value '123' as type 'System.Nullable`1[System.Guid]' for 'p'.
   at Microsoft.AspNetCore.Components.Routing.UrlValueConstraint.TypedUrlValueConstraint`1.Parse(ReadOnlySpan`1 value, String destinationNameForMessage)
   at Microsoft.AspNetCore.Components.Routing.QueryParameterValueSupplier.GetQueryParameterValue(Type targetType, String queryParameterName)
   at Microsoft.AspNetCore.Components.ParameterView.CascadingParameterEnumerator.MoveNext()
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

### Expected Behavior

Clicking a link to the other page should successfully navigate to it without throwing an exception.

### Steps To Reproduce

An example project is located: [here](https://github.com/MatElcome/BlazorQueryParamBug)

- Load up the project to the index page `/`
- Click the link `TestInt 123`
- Click the link `TestGuid 47259a22-9fd8-4938-b40d-e5c8d8642a3d`
- An exception is thrown
  - `An unhandled exception has occurred. See browser dev tools for details` is displayed at the bottom of the page
  - The browser's console displays the exception stack trace

### Exceptions (if any)

```
Error: System.InvalidOperationException: Cannot parse the value '123' as type 'System.Nullable`1[System.Guid]' for 'p'.
   at Microsoft.AspNetCore.Components.Routing.UrlValueConstraint.TypedUrlValueConstraint`1.Parse(ReadOnlySpan`1 value, String destinationNameForMessage)
   at Microsoft.AspNetCore.Components.Routing.QueryParameterValueSupplier.GetQueryParameterValue(Type targetType, String queryParameterName)
   at Microsoft.AspNetCore.Components.ParameterView.CascadingParameterEnumerator.MoveNext()
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```
or if you visit the links in the reverse order:
```
Error: System.InvalidOperationException: Cannot parse the value '47259a22-9fd8-4938-b40d-e5c8d8642a3d' as type 'System.Nullable`1[System.Int32]' for 'p'.
   at Microsoft.AspNetCore.Components.Routing.UrlValueConstraint.TypedUrlValueConstraint`1.Parse(ReadOnlySpan`1 value, String destinationNameForMessage)
   at Microsoft.AspNetCore.Components.Routing.QueryParameterValueSupplier.GetQueryParameterValue(Type targetType, String queryParameterName)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

### .NET Version

8.0.100

### Anything else?

This is a regression - it occurs in `net8.0`, but not if the project is downgraded to `net7.0`.

### PR DESCRIPTION
**Pull request by halter73**
`Router.OnLocationChanged` calls `SupplyParameterFromQueryValueProvider.GetCurrentValue` before the `SupplyParameterFromQueryValueProvider.OnLocationChanged` handler which updated the query string values from `QueryParameterValueSupplier`, so we have to compare strings rather than rely on a bool set in `OnLocationChanged`.

~TODO: Add unit test for `SupplyParameterFromQueryValueProvider` in addition to the E2E RoutingTest.cs.~

I think the E2E test is sufficient. I wanted a unit test that directly called into `SupplyParameterFromQueryValueProvider` witha mock `ComponentState`, but `ComponentState` is not very mockable. I could create an internal `ISubscriber` and have `ComponentState` implement it, but I'm trying to reduce the churn since this is going to be backported.

Fixes #52483

### CODE REVIEW

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+            _pendingSubscribers.Add(subscriber);
+            return;
+        }
+
+        _subscribers ??= new();
+        _subscribers.Add(subscriber);
+        SubscribeToLocationChanges();
+    }
+
+    public void Unsubscribe(ComponentState subscriber, in CascadingParameterInfo parameterInfo)
```
Comment (halter73) [inline src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:48]: One thing I do not like about how this works is that the same `ComponentState` can subscribe multiple times in a row for multiple different parameters, but as soon as it unsubscribes one parameter, it gets completely unsubscribed.

However, I don't know how a component would unsubscribe from a subset of parameters in practice, and this was a preexisting problem with the class. Do we care about fixing this?

**Review by MackinnonBuck — APPROVED** [review]
Looks good - it took a bit for me to grasp what's fully happening but the approach seems correct!

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    private bool TryUpdateQueryParameters()
+    {
+        _queryParameterValueSupplier ??= new();
+
+        // Router.OnLocationChanged calls GetCurrentValue before our own OnLocationChanged handler,
+        // so we have to compare strings rather than rely on a bool set in OnLocationChanged.
+        if (navigationManager.Uri == _lastUri)
+        {
+            return false;
+        }
```
Comment (javiercn) [inline src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: Do we want to be more "precise" here? As in, do we want to find the querystring and compare that bit? We don't care if the path or hash change, do we?

Comment (javiercn) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: Seems like we can call `GetQueryString` on both instances and compare that instead of the full URL.

Comment (javiercn) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: https://github.com/dotnet/aspnetcore/pull/53443/files#diff-71e3430f05198494d6d314c3ffcd4ee38d0ba908458544901a96a0b66824dbe4R78

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: If we're doing this, we might even prefer to do `Object.ReferenceEquals(old, new) || GetQueryString(old) == GetQueryString(new)` since in most cases if it hasn't changed, it will be the same string instance. That saves us from the work of finding the `?` etc.

Comment (javiercn) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: That's fine by me. We call `GetQueryString` later on in the code, so we might as well call it earlier and keep the value in a local.

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs (hunk 1 above)
Comment (halter73) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:48]: We could just change the sets to be `HashSet<(ComponentState Subscriber, string QueryName)>` rather than use a dictionary if we think this is important. I just wanted to make sure I wasn't fixing something that wasn't really broken. While the current behavior is certainly very weird which is why I pointed it out, I was worried "fixing" it in this way could lead to excessive parameter change notifications and renders when a component has multiple query string parameters.

> Or perhaps even when navigating away from any page that subscribed to a query parameter, possibly causing extra rendering work.

I was worried about this too, but this fortunately does not induce extra rendering work because `Router.OnLocationChanged` gets called first and unsubscribes clearing the `_subcribers` before `SupplyParameterFromQueryValueProvider.OnLocationChanged` has a chance to notify them.

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs (hunk 2 above)
Comment (halter73) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:71]: The scenario of a component binding a parameter to the query string and interpreting it the same way regardless of the endpoint is a little strange. And being less precise just means overreporting possible parameter changes which still happens if only an irrelevant part of the query string changes which I suspect is even more common.

`if (navigationManager.Uri == _lastUri)` already short-circuits on reference equality, and we still need to compare the full URI so we know whether the components attempting to subscribe have seen the current Uri already regardless of whether or not the query component of the URI changed. Even if the query string has changed, those components do not need to be notified about a URI they have already observed.

The fix would have to look something like [this](https://github.com/dotnet/aspnetcore/commit/52c7e37462b1c35adfe266f7917fc0e190583911), and I don't think it's worth that level of extra complexity. If someone has a far simpler way to do this, I'm all ears.

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:51]: > We could just change the sets to be HashSet<(ComponentState Subscriber, string QueryName)> rather than use a dictionary if we think this is important.

I thought we needed to be able to get the set of distinct subscribers, since at notification time, we only want to issue one notification per subscriber even if multiple query params have changed (a common case). The tuple would force us to compute the set of distinct subscribers on each notification.

> I was worried about this too, but this fortunately does not induce extra rendering work 

In that case it seems fine already :)

File: src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:74]: @halter73 you've thought more deeply about this than the rest of us recently so would be best placed to make a call on what you think is the best tradeoff (@javiercn if you feel strongly we should do a specific thing, please say so!)

Comment (javiercn) [reply src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs:74]: No, I'll trust @halter73 makes the right calls
