### PR TITLE
Stop Calling JSON GetTypeInfo with the runtime type

### LINKED ISSUE #47548: Stop Calling JSON GetTypeInfo with the runtime type
In both the RDF and RDG we have code like the following:

https://github.com/dotnet/aspnetcore/blob/0b10e1349063b1b5b39dd0435509abb52cc81d90/src/Shared/RouteHandlers/ExecuteHandlerHelper.cs#L36-L53

This doesn't work with the unspeakable types behavior that was added to System.Text.Json - https://github.com/dotnet/runtime/pull/83631. In particular, `GetTypeInfo(runtimeType)` doesn't work when using unspeakable types.

We started using the "runtimeType" back in .NET Core 3.0 (https://github.com/dotnet/aspnetcore/commit/bed3542a9ba7b1504882e7d34e2b3d6af63afdb5) when we switched from Json.Net to System.Text.Json and wanted to maintain the polymorphic serialization behavior of Json.Net (ex. if the "declared type" was a base type, and the endpoint returned a derived type, we want to serialize all the derived properties). This strategy was adopted by Minimal APIs as well, when they were introduced.

This approach was then changed early in .NET 8 in order to support "System.Text.Json Polymorphism" features that were added in .NET 7. (See https://github.com/dotnet/aspnetcore/pull/45405). The strategy used by that PR was: "when a `JsonPolymorphismOptions` is detected, uses the declared type's JsonTypeInfo to call the serializer." When it isn't detected, use the "runtimeType"'s `JsonTypeInfo` to maintain the above polymorphic serialization behavior to not break backwards compatibility.

In order to support all these scenarios, we need to tweak our JSON serialization strategy. After consulting with @brunolins16 and @eiriktsarpalis, the strategy we have settled on is:

1. When a `JsonPolymorphismOptions` is detected (or when polymorphism is not possible - ex. ValueType, sealed, etc), use the declared type's `JsonTypeInfo` to call the serializer.
    - This is no change to what we do today in .NET 8.
2. When the above rule doesn't work, instead of using the "runtimeType", we will serialize the value "as object" - i.e. `JsonSerializer.Serialize<object>(value, options)`.
    - This will allow System.Text.Json to control the behavior of serialization. It will allow to fix issues like:
        - "unspeakable type support" https://github.com/dotnet/runtime/issues/82457
        - Polymorphic Type Resolving https://github.com/dotnet/runtime/issues/77532
        - Along with keeping the above behavior consistent with Json.Net before .NET Core 3.0.

A drawback to this strategy is that `JsonSerializer.Serialize<object>(value, options)` is not guaranteed to be trim/AOT-compatible, and thus it is annotated as incompatible. We will need to suppress these warnings in ASP.NET, which is OK because of the other mechanisms we are adding to support trimming/AOT - https://github.com/dotnet/runtime/issues/83279.

However, we can't do this until the [JSON Trimming feature switch](https://github.com/dotnet/runtime/pull/83844) is merged, or we will regress the AOT size and warnings. We may also need to wait for [System.Text.Json Polymorphic Type Resolving Issue](https://github.com/dotnet/runtime/issues/77532).

### PR DESCRIPTION
**Pull request by eerhardt**
Calling GetTypeInfo with the object's runtime type doesn't work when using unspeakable types and using JSON source generation. There is no way to mark the unspeakable type (like a C# compiler implemented IAsyncEnumerable iterator) as JsonSerializable.

Instead, when the "declared type"'s JsonTypeInfo isn't compatible with the runtime type w.r.t. polymorphism, serialize the value "as object", letting System.Text.Json's serialization take over to serialize the value.

Fix #47548

### CODE REVIEW

File: src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs [hunk 1]
```diff
@@ -83,6 +83,9 @@ private static async ValueTask<(bool, T?)> TryResolveBodyAsync<T>(HttpContext ht
 """;
 
     public static string WriteToResponseAsyncMethod => """
+        [UnconditionalSuppressMessage("Trimming", "IL2026:RequiresUnreferencedCode",
+            Justification = "<Pending>")]
+        [UnconditionalSuppressMessage("AOT", "IL3050:RequiresDynamicCode", Justification = "See above.")]
         private static Task WriteToResponseAsync<T>(T? value, HttpContext httpContext, JsonTypeInfo<T> jsonTypeInfo, JsonSerializerOptions options)
```
Comment (eiriktsarpalis) [inline src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs:89]: Having the method accept both a `JsonTypeInfo<T>` and a `JsonSerializerOptions` parameter seems a bit redundant. Assuming it's meant to accept a pre-cached `JsonTypeInfo` instance then it might make sense to an assert checking that
```C#
Debug.Assert(jsonTypeInfo.Options == options);
```
but otherwise it looks like either of the two parameters should be removed.

File: src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs [hunk 2]
```diff
@@ -212,8 +213,7 @@ static async Task WriteAsJsonAsyncSlow(HttpResponse response, object? value, Jso
     {
         ArgumentNullException.ThrowIfNull(response);
 
-        var options = ResolveSerializerOptions(response.HttpContext);
-        return response.WriteAsJsonAsync(value, jsonTypeInfo: options.GetTypeInfo(type), contentType: null, cancellationToken);
+        return response.WriteAsJsonAsync(value, type, options: null,  contentType: null, cancellationToken);
```
Comment (eiriktsarpalis) [inline src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs:216]: Does the null parameter mean that it's using the default options or that the options instance is being resolved elsewhere?

File: src/Http/Http.Results/src/HttpResultsHelper.cs [hunk 3]
```diff
@@ -34,8 +38,8 @@ internal static partial class HttpResultsHelper
         jsonSerializerOptions ??= ResolveJsonOptions(httpContext).SerializerOptions;
         var jsonTypeInfo = (JsonTypeInfo<TValue>)jsonSerializerOptions.GetTypeInfo(typeof(TValue));
 
-        Type? runtimeType;
-        if (jsonTypeInfo.IsValid(runtimeType = value.GetType()))
+        Type? runtimeType = value.GetType();
+        if (jsonTypeInfo.IsValid(runtimeType))
```
Comment (eiriktsarpalis) [inline src/Http/Http.Results/src/HttpResultsHelper.cs:42]: Nit: naming
```suggestion
        if (jsonTypeInfo.ShouldUseWith(runtimeType))
```

File: src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs:155]: Yes, we pre-compute the `JsonTypeInfo` and `JsonSerializerOptions` once at startup for each endpoint.

https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/EndpointJsonResponseEmitter.cs#L14-L15

I think it's fine to take only `JsonSerializerOptions` for this API.

Comment (eerhardt) [reply src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs:155]: > I think it's fine to take only JsonSerializerOptions for this API.

Did you mean `JsonTypeInfo<T>` instead? If we just took JsonSerializerOptions, it wouldn't make sense to pre-compute the JsonTypeInfo. Because we would need to look it up again if we just had the options.

File: src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonOutputFormatterTest.cs [hunk 4]
```diff
@@ -4,16 +4,14 @@
...
 using System.Text.Json.Serialization;
 using System.Text.Json.Serialization.Metadata;
-using Microsoft.AspNetCore.Testing;
 using Microsoft.Extensions.Primitives;
 using Microsoft.Net.Http.Headers;
 
 namespace Microsoft.AspNetCore.Mvc.Formatters;
 
-public class SystemTextJsonOutputFormatterTest : JsonOutputFormatterTestBase
+public partial class SystemTextJsonOutputFormatterTest : JsonOutputFormatterTestBase
```
Comment (captainsafia) [inline src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonOutputFormatterTest.cs:14]: Why is this partial now?

File: src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs (hunk 2 above)
Comment (eerhardt) [reply src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs:216]: It means it is using the options instance that is resolved from DI, if available. If not, it uses the JsonOptions.DefaultSerializerOptions. See:


https://github.com/dotnet/aspnetcore/blob/d07f377b6c4c72f44a0eb2810c8abf1ae3fabd40/src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs#L254-L275

https://github.com/dotnet/aspnetcore/blob/d07f377b6c4c72f44a0eb2810c8abf1ae3fabd40/src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs#L339-L343

File: src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs [hunk 5]
```diff
@@ -108,9 +109,7 @@ public static partial class HttpResponseJsonExtensions
     /// <param name="contentType">The content-type to set on the response.</param>
     /// <param name="cancellationToken">A <see cref="CancellationToken"/> used to cancel the operation.</param>
     /// <returns>The task object representing the asynchronous operation.</returns>
-#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
```
Comment (captainsafia) [inline src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs:111]: Why do these no longer apply?

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs [hunk 6]
```diff
@@ -248,4 +249,40 @@ public async Task MapAction_HandlesCompletedTaskReturn()
...
+        });
+        var endpoint = GetEndpointFromCompilation(compilation, serviceProvider: serviceProvider);
+
+        var httpContext = CreateHttpContext(serviceProvider);
+
+        await endpoint.RequestDelegate(httpContext);
+
+        var expectedBody = """[{"id":1,"name":"One","isComplete":true},{"$type":"JsonTodoChild","child":"TwoChild","id":2,"name":"Two","isComplete":false}]""";
+        await VerifyResponseBodyAsync(httpContext, expectedBody);
+    }
```
Comment (captainsafia) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs:287]: Time permitting, it would be good to move this test to the shared set: (https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs#L2049-L2074).

But we can do this in a follow-up PR as well.

File: src/Http/Http.Results/src/HttpResultsHelper.cs (hunk 3 above)
Comment (eerhardt) [reply src/Http/Http.Results/src/HttpResultsHelper.cs:42]: He’s suggesting renaming IsValid to ShouldUseWith

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs (hunk 6 above)
Comment (eerhardt) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs:287]: I can try fitting it in here to help with the test coverage.

File: src/Http/Http.Results/src/HttpResultsHelper.cs (hunk 3 above)
Comment (captainsafia) [reply src/Http/Http.Results/src/HttpResultsHelper.cs:42]: 🤦🏽‍♀️ In that case, I think that's a great recommendation. Reads much more nicely...

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs (hunk 6 above)
Comment (eerhardt) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.Responses.cs:352]: Done. Please take a look.

**Review by captainsafia — APPROVED** [review]
LGTM! TY for migrating the test over.

File: src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs (hunk 1 above)
Comment (eerhardt) [reply src/Http/Http.Extensions/gen/RequestDelegateGeneratorSources.cs]: I've removed the `JsonSerializerOptions` from here and in RDF.

File: src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs (hunk 5 above)
Comment (eerhardt) [reply src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs:111]: IDK. It builds without them... 🤷

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by eerhardt** [comment]
OK, I have addressed all feedback. I'm going to merge this once it is green to make the 8.0-preview4 cutoff.
