### PR TITLE
Fix Blazor crash when interactive component is in layout with enhanced nav

### LINKED ISSUE #64722: Blazor Web App Crash in .NET 10 When Auto Component on the Homepage
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Web-App-Crash-in-NET-10-When-Ser/11013735)._

---
[BlazorNet10BugRepro.zip](https://aka.ms/dc/file?name=B8154b1057d954ab69374b06015cf3a2f639009380393088592_BlazorNet10BugRepro.zip&tid=8154b1057d954ab69374b06015cf3a2f639009380393088592)

In a Blazor Web App, when I add the Counter component to the Home page, the site will crash when I navigate from Home to Counter (the dedicated page) and then back to Home. I get a JavaScript error in the Blazor.web.js file that states TypeError: Cannot read properties of null (reading 'insertBefore')

This does not happen in .NET 9 projects, only if I build a .NET 10 project. Also, this happens whether I am using Visual Studio 2026, VS Code, or even just dotnet run. It does not matter if I use localhost or use the new dev.localhost TLD.

Also, if I navigate to a different page (I created a /Demo page that was InteractiveServer) after the site starts up on Home, I can then use the site without issues. I can go to /Counter without a problem, I can go to /Home, then to /Counter and back without a problem. It is only if I navigate from /Home to /Counter directly on load that there is an issue. And that is only an issue when the Counter component is also on the /Home page.

I have attached a simple demo project that shows off the issue.

---
#### Feedback Bot on 12/10/2025, 06:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

### PR DESCRIPTION
**Pull request by maraf**
## Fix Blazor crash when interactive component is in layout with enhanced navigation

Fixes #64722

### Problem

When an `InteractiveAuto` or `InteractiveWebAssembly` component is placed in the layout (e.g. `<Counter />` in `MainLayout.razor`), navigating between pages via enhanced navigation causes:

```
TypeError: Cannot read properties of null (reading 'insertBefore')
```

### Root Cause

The `<!--Blazor-WebAssembly:{...}-->` metadata comment was removed from the physical DOM during `discoverWebAssemblyOptions()`, but remained in the parent element's logical children array as an orphaned node (`parentNode === null`). On subsequent enhanced navigations, `insertLogicalChild()` picked this orphaned comment as a reference node for `insertBefore`, crashing because `parentNode` was null.

### Changes

1. **Reorder `registerAllComponentDescriptors`** — Call `discoverWebAssemblyOptions` *before* `upgradeComponentCommentsToLogicalRootComments`, ensuring metadata comments are removed from the DOM before the logical tree is built.

2. **Strip metadata in `preprocessAndSynchronizeDomContent`** — Remove metadata comments from new enhanced-nav content before building the logical tree, preventing orphaned nodes during navigation.

3. **Defensive null check in `insertLogicalChild`** — Replace the non-null assertion `parentNode!.insertBefore(...)` with a null check, falling back to `appendDomNode` if the reference node is disconnected.

### CODE REVIEW

**Comment by maraf** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by maraf** [comment]
Addressing Copilot review feedback:

**Comment on staleness assertion (line 938):** Good catch. Applied — I now capture a layout element (`#layout-counter`) that persists across pages and assert it is not stale after each navigation to verify enhanced navigation was used.

**Comment on error detection (line 949):** Agreed. Replaced the unreliable `blazor-error-ui` check with `Browser.GetBrowserLogs(LogLevel.Warning)` + `Assert.DoesNotContain(Error)`, matching the existing pattern in this file. Also added a click on the interactive counter button to prove the interactive layout component is still functional after navigation.

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts [hunk 1]
```diff
@@ -183,7 +183,11 @@ export function insertLogicalChild(child: Node, parent: LogicalElement, childInd
   if (childIndex < newSiblings.length) {
     // Insert
     const nextSibling = newSiblings[childIndex] as any as Node;
-    nextSibling.parentNode!.insertBefore(nodeToInsert, nextSibling);
+    if (nextSibling.parentNode) {
+      nextSibling.parentNode.insertBefore(nodeToInsert, nextSibling);
+    } else {
+      appendDomNode(nodeToInsert, parent);
```
Comment (ilonatommy) [inline src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Should we preserve the correct DOM ordering when orphaned node is in the middle to prevent possible flickering?

```
if (nextSibling.parentNode) {
   nextSibling.parentNode.insertBefore(nodeToInsert, nextSibling);
 } else {
   // Reference sibling is disconnected — find the next connected sibling
   let inserted = false;
   for (let i = childIndex + 1; i < newSiblings.length; i++) {
     const laterSibling = newSiblings[i] as any as Node;
     if (laterSibling.parentNode) {
       laterSibling.parentNode.insertBefore(nodeToInsert, laterSibling);
       inserted = true;
       break;
     }
   }
   if (!inserted) {
     appendDomNode(nodeToInsert, parent);
   }
 }
```

**Review by ilonatommy — APPROVED** [review]
Looks correct, one nit for discussion.

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts (hunk 1 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Actually, that's not all. We should also remove the siblings that are orphaned so that the next operation on the same parent won't hit the same problematic node.

Comment (maraf) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Thanks for the feedback! I've implemented a cleanup-first approach that addresses both concerns:

Instead of walking forward to find the next connected sibling, the code now **scans and removes all orphaned nodes from the siblings array before the insert logic runs**, adjusting the insertion index as orphans are pruned. This means:

1. **Correct DOM ordering is preserved** — after cleanup, the reference sibling at `childIndex` is always connected, so `insertBefore` naturally puts the node in the right place. No forward-walk needed because the sibling set is normalized first.
2. **Orphaned siblings are removed** — they won't cause issues for subsequent operations on the same parent.

I also added unit tests in `test/LogicalElements.test.ts` covering:
- Orphan at the exact reference position
- Multiple consecutive orphans before the insertion index (validating index adjustment)
- Orphans interspersed with connected nodes
- Fallback to append when orphan cleanup pushes the index past the end
- Normal insert behavior (no regression)

See commit for the implementation.

Comment (ilonatommy) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Thank you. From what I understand this change is just a precaution for the future (the core fix is in `DomSync.ts`). Situations when this loop will hit an orphan are just hypothetical (future changes, 3rd party DOM manipulation etc). Should we be noisy about dropping these orphans so that we could prevent orphaning in the first place when we change the code logic and it starts happening again?

Comment (maraf) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: I hope the test will cover it in case of regression

**Comment by maraf** [comment]
/ba-g Failures are not related to this PR (Components enhanced-nav layout fix).

**Build [1383735](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1383735):**

- **macOS Tests job canceled** — matches known issue [dnceng#1883](https://github.com/dotnet/dnceng/issues/1883) (slow macOS 60-min timeout). Also matches [#6408](https://github.com/dotnet/dnceng/issues/6408) and [#3008](https://github.com/dotnet/dnceng/issues/3008).
- **Helix test failures** are all in Kestrel / Sockets / HttpSys / IIS areas — unrelated to the changed files:
  - `ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate` (known-flaky TLS test)
  - `KestrelConfigurationLoaderTests.ConfigureEndpoint_CanLoadPemCertificates`
  - `DelegateTests.DelegateAfterReceiverRestart`
  - Several `IIS.NewShim.FunctionalTests.StartupTests.*`
  - `QuarantinedTestAttributeTest.FlakyTestToEnsureRetryWorks` (by design)

No Components/Blazor tests failed and no correlation with the 8 files changed in this PR.
