### PR TITLE
Fix for Kestrel's ParseHeaders throwing ArgumentOutOfRange exception

### LINKED ISSUE #61245: Kestrel's ParseHeaders throws an ArgumentOutOfRange exception on certain headers
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have been fuzzing some of the Kestrel methods and ran into a part where in crashes on certain multi-span headers. The issue seems to be in the fact that on multispan headers where one section ends with cr kestrel tries to see if there is data after cr inside the whole header (there is) and then when it rejects the header it tries to grab extra data from the specific span it inspects (and there is no data) so it throws

### Expected Behavior

ParseHeaders module cleanly rejects the problematic header without exceptions

### Steps To Reproduce

https://github.com/WereWind1/KestrelHttpParserExceptionMinimal

### Exceptions (if any)

ArgumentOutOfRange

### .NET Version

6.0.36 8.0.14 9.0.3

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by WereWind1**
# Fix for Kestrel's ParseHeaders throwing ArgumentOutOfRange exception

RejectRequestHandler no longer tries to look beyond the scope of the span

## Description

Fixes #61245

### CODE REVIEW

**Comment by WereWind1** [comment]
Also can anybody tell me if this change would propagate to different versions of ASP like 8.0? Or should I submit a separate PR?

**Comment by WereWind1** [comment]
@dotnet-policy-service agree

**Comment by martincostello** [comment]
> Also can anybody tell me if this change would propagate to different versions of ASP like 8.0? Or should I submit a separate PR?

If it meets the [servicing bar](https://github.com/dotnet/aspnetcore/blob/main/docs/Servicing.md#servicing-bar), the team would manage porting the fix to the relevant branches post-merge.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs [hunk 1]
```diff
@@ -251,6 +251,7 @@ public bool ParseHeaders(TRequestHandler handler, ref SequenceReader<byte> reade
                         {
                             // Include the thing after the CR in the rejection exception.
                             var stopIndex = crIndex + 2;
+                            stopIndex = stopIndex > span.Length ? span.Length : stopIndex;
```
Comment (gfoidl) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs:254]:
```suggestion
                            var stopIndex = Math.Max(crIndex + 2, span.Length);
```
?

**Comment by BrennanConroy** [comment]
> Also can anybody tell me if this change would propagate to different versions of ASP like 8.0? Or should I submit a separate PR?

Why do you think this should be backported? It just ends up getting logged as an `ArgumentOutOfRange` exception instead of a `BadHttpRequestException`.

**Review by halter73 — APPROVED** [review]
Thanks for the fix and the test. It's always nice to get the fundamentals right.

However, I agree with Brennan that it's probably not worth spending our time backporting this.

**Comment by WereWind1** [comment]
My wish for a backport was mostly caused by me working with older versions and not being overly familiar with the workflow of the community

Now is there anything else for me to do to have this branch merged?
