### PR TITLE
Fix ModelMetadata for TryParse-parameters in ApiExplorer

### LINKED ISSUE #58318: OpenAPI documentation is incorrect when using custom TryParse() binding with Minimal APIs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have used the same title of https://github.com/dotnet/aspnetcore/issues/36412 because the same issue happens today using the new OpenAPI documentation generator that is built-in in .NET 9.0.

With this code:

```csharp
app.MapGet("/student/{student}", (Student student) => $"Hi {student.Name}");

public record Student(string Name)
{
    public static bool TryParse(string value, out Student? result)
    {
        if (value is null)
        {
            result = null;
            return false;
        }

        result = new Student(value);
        return true;
    }
}
```

OpenAPI documentation is wrongly created as the following:

```json
"parameters": [
    {
        "name": "student",
        "in": "query",
        "required": true,
        "schema": {
            "$ref": "#/components/schemas/Student"
        }
    }
],
// ...
"components": {
    "schemas": {
        "Student": {
            "required": [
                "name"
            ],
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
},
```

### Expected Behavior

Parameters that use a `TryParse` custom binding should be configured as string in the `openapi/v1.json` file:

```json
"parameters": [
    {
        "name": "student",
        "in": "query",
        "required": true,
        "schema": {
            "type": "string"
        }
    }
],
```

### Steps To Reproduce

Minimal repro: https://github.com/marcominerva/TryParseOpenApiIssue

### Exceptions (if any)

_No response_

### .NET Version

9.0.0-rc.2.24474.3

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/58318.

### CODE REVIEW

File: src/OpenApi/src/Services/OpenApiDocumentService.cs [hunk 1]
```diff
@@ -686,10 +686,17 @@ private static Type GetTargetType(ApiDescription description, ApiParameterDescri
...
             : parameter.Type;
-        var requiresModelMetadataFallback = parameterType == typeof(string) && parameter.ModelMetadata.ModelType != parameter.Type;
+
+        // parameter.Type = typeof(string)
+        // parameter.ModelMetadata.Type = typeof(TEnum)
+        var requiresModelMetadataFallbackForEnum = parameterType == typeof(string)
+            && parameter.ModelMetadata.ModelType != parameter.Type
+            && parameter.ModelMetadata.ModelType.IsEnum;
         // Enums are exempt because we want to set the OpenApiSchema.Enum field when feasible.
+        // parameter.Type = typeof(TEnum), typeof(Student), typeof(ITryParse)
```
Comment (BrennanConroy) [inline src/OpenApi/src/Services/OpenApiDocumentService.cs:696]: `typeof(Student)` won't mean anything when we forget this issue in a few months 😄 
`typeof(typeWithTryParse)`?

**Review by BrennanConroy — APPROVED** [review]

File: src/OpenApi/src/Services/OpenApiDocumentService.cs (hunk 1 above)
Comment (captainsafia) [reply src/OpenApi/src/Services/OpenApiDocumentService.cs:696]:
```suggestion
        // parameter.Type = typeof(TEnum), typeof(TypeWithTryParse)
```
