### PR TITLE
Clear unused routing params. Fixes #7419

### LINKED ISSUE #7419: Optional parameter is not cleared when navigating to same page with a different set of parameters
When navigating to a page which has two @page directives with one or two parameters, the optional one is not always cleared when navigating to this page when the optional parameter should have be set to its default.

In the [documentation](https://docs.microsoft.com/en-us/aspnet/core/razor-components/routing?view=aspnetcore-3.0#route-parameters) it is said to use two @page directives for support for optional parameters.

### To Reproduce:

Start with the sample app of Razor Components, and add a new page:

```
@page "/node/{Id:int}"
@page "/node/{ParentId:int}/{Id:int}"

@functions {
    [Parameter]
    private int? ParentId { get; set; } = null;

    [Parameter]
    private int Id { get; set; }
}
```

update NavMenu.cshtml to include:

```
<NavLink href="node/1">First click me</NavLink>
<NavLink href="node/2/3">Then click me</NavLink>
<NavLink href="node/4">And finally click me</NavLink>
```

Start the app.

Navigating to node/1 works: `ParentId` is null and `Id` is 1.
Navigating to node/2/3 works: `ParentId` is 2 and `Id` is 3.
Navigating to node/4 works but gives: `ParentId` *stays* 2, and `Id` is 4.

### Expected behavior

When navigating to node/4 I expect `ParentId` to be null again and `Id` to be 4. `ParentId` is a Parameter, and should be set to null when the route does not provide the information.

### Additional context

```.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]```

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This implements the plan described in #7419, i.e., that when routing, we always supply *all* the possible route parameters for the target component (supplying `default` for any not in the matched URL).

~~**Still to do:** Run all the other E2E tests to be sure this doesn't break anything.~~ Done that

### CODE REVIEW

File: src/Components/Components/src/Routing/RouteEntry.cs [hunk 1]
```diff
@@ -45,6 +48,18 @@ internal void Match(RouteContext context)
                 }
             }
 
+            // In addition to extracting parameter values from the URL, each route entry
+            // also knows which other parameters should be supplied with null values. These
+            // are parameters supplied by other route entries matching the same handler.
+            if (UnusedRouteParameterNames.Length > 0)
```
Comment (rynowak) [inline src/Components/Components/src/Routing/RouteEntry.cs]: You should double check that this handles cases with optional parameters (if Blazor supports them) like `{a}/{b?}`. Depending on the implementation it's possible for you to get `b` omitted, or `b => null` in the dictionary and it seems like we need `b => null`.

File: src/Components/Components/src/Routing/RouteTableFactory.cs [hunk 2]
```diff
@@ -34,26 +34,53 @@ public static RouteTable Create(Assembly appAssembly)
 
         internal static RouteTable Create(IEnumerable<Type> componentTypes)
         {
-            var routes = new List<RouteEntry>();
-            foreach (var type in componentTypes)
+            var templatesByHandler = new Dictionary<Type, string[]>();
```
Comment (rynowak) [inline src/Components/Components/src/Routing/RouteTableFactory.cs]: `templatesByComponent`?

File: src/Components/test/testassets/ComponentsApp.App/Pages/FetchData.razor [hunk 3]
```diff
@@ -34,28 +34,24 @@ else
...
-        StartDate = DateTime.Now;
-        return base.SetParametersAsync(parameters);
-    }
+    DateTime startDate;
 
     protected override async Task OnParametersSetAsync()
     {
-        forecasts = await ForecastService.GetForecastAsync(StartDate);
+        startDate = StartDate.GetValueOrDefault(DateTime.Now);
+        forecasts = await ForecastService.GetForecastAsync(startDate);
```
Comment (rynowak) [inline src/Components/test/testassets/ComponentsApp.App/Pages/FetchData.razor]: Do we also need a template update?

File: src/Components/Components/src/Routing/RouteEntry.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/RouteEntry.cs]: It’s a good thought, but Blazor routes don’t yet support optional parameters.

File: src/Components/Components/src/Routing/RouteTableFactory.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/RouteTableFactory.cs]: It’s weird, but I’m using the term “handler” for consistency with the rest of the code in this file.

File: src/Components/test/testassets/ComponentsApp.App/Pages/FetchData.razor (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/test/testassets/ComponentsApp.App/Pages/FetchData.razor]: No, there’s no equivalent to this in the template. The forecasts page in the template doesn’t take any route parameters.

File: src/Components/Components/src/Routing/RouteEntry.cs (hunk 1 above)
Comment (rynowak) [reply src/Components/Components/src/Routing/RouteEntry.cs]: OK - worth a comment somewhere then? It's really likely we'll try to converge on features at some point. If we have an issue tracking that then we could add the note there.

**Comment by rynowak** [comment]
FYI there were some problems with functional tests (non-Blazor) hitting an infinite loop over the weekend and have since been fixed. If you're having CI problems, rebasing might fix it.

**Review by rynowak — APPROVED** [review]

File: src/Components/Components/src/Routing/RouteEntry.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/RouteEntry.cs]: Yes, commented here: https://github.com/aspnet/AspNetCore/issues/10759#issuecomment-513622534
