### PR TITLE
Custom hub options don't change global hub options

### LINKED ISSUE #9627: Extra SignalR hubs in a Server-side Blazor app throw exceptions
### Describe the bug
In aspnetcore-preview-4, I can no longer use other SignalR Hubs at the same time as running Server-Side Blazor.  My prev-3 project was running fine.  When I completed the upgrade to prev-4, I could not get any clients to connect to the hub I have setup in `UseEndpoints`.  The error message is always:
```
Error: Server returned handshake error: The protocol 'json' is not supported.
```
If I try to replace the `AddNewtonsoftJsonProtocol` with `AddMessagePackProtocol`, and setup my client to use MessagePack, the client says the messagepack protocol is not supported.

### To Reproduce
1. Using preview 4 of ASP.NET Core 
2. Create a default Server-side Blazor app (Razor Components template still)
3.  Add all the standard SignalR setup including `AddNewtonsoftJsonProtocol`
4. Setup a client to connect to the hub and watch the error.

I've also got my source code here:
https://github.com/limefrogyank/DynamicData/tree/master/DynamicData.SignalR.JSInterop.TestBlazorApp
A javascript client attempted to connect (in wwwroot/dynamicDataSignalRInterop.js) when the Index.razor page is displayed.  The call to the javascript file is deep, deep in the SignalRSourceCache class... but it was working fine in prev 3.

### Expected behavior
The hub should connect (complete handshaking) and start passing data.  

### Additional context
Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/AspNetCore/issues/9627

The issue was we were shallow copying the list of protocols from the global options to the hub specific options, which for classes means they will point to the same object.

The change is to ~deep~ copy the list.

### CODE REVIEW

File: src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs [hunk 1]
```diff
@@ -16,7 +16,7 @@ public class HubOptionsSetup : IConfigureOptions<HubOptions>
 
         internal static TimeSpan DefaultClientTimeoutInterval => TimeSpan.FromSeconds(30);
 
-        internal const int DefaultMaximumMessageSize = 32 * 1024 * 1024;
```
Comment (BrennanConroy) [inline src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs]: @davidfowl 😆

Comment (davidfowl) [reply src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs]: 😨

Comment (anurse) [reply src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs]: https://github.com/aspnet/AspNetCore/blob/f4972dc6b61968ab244f6e030535974376298ba1/src/SignalR/server/Core/src/HubOptions.cs#L40

Comment (anurse) [reply src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs]: image

image

Comment (anurse) [reply src/SignalR/server/Core/src/Internal/HubOptionsSetup.cs]: :trollface:

**Review by davidfowl — APPROVED** [review]

**Review by analogrelay — APPROVED** [review]
Approved for preview 5

**Review by mikaelm12 — APPROVED** [review]
