### PR TITLE
Scope ActivityListener in test to not interfere with other tests

### LINKED ISSUE #34072: Flaky test: IHttpActivityFeatureIsNotPopulatedWithoutAListener
## Failing Test(s)

Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener

## Error Message

```text
Assert.Null() Failure
Expected: (null)
Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener() in /_/src/Hosting/Hosting/test/HostingApplicationTests.cs:line 174
```
</details>

## Logs

<details>

```text
[xUnit.net 00:00:02.44]     Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener [FAIL]
[xUnit.net 00:00:02.45]       Assert.Null() Failure
[xUnit.net 00:00:02.45]       Expected: (null)
[xUnit.net 00:00:02.45]       Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:02.45]       Stack Trace:
[xUnit.net 00:00:02.45]         /_/src/Hosting/Hosting/test/HostingApplicationTests.cs(174,0): at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener()
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1219377&view=results

### PR DESCRIPTION
**Pull request by BrennanConroy**
Might fix https://github.com/dotnet/aspnetcore/issues/34072

### CODE REVIEW

File: src/Hosting/Hosting/test/HostingApplicationDiagnosticsTests.cs [hunk 1]
```diff
@@ -496,11 +496,12 @@ public void ActivityOnImportHookIsCalled()
...
         public void ActivityListenersAreCalled()
         {
-            var hostingApplication = CreateApplication(out var features);
+            var testSource = new ActivitySource(Path.GetRandomFileName());
+            var hostingApplication = CreateApplication(out var features, activitySource: testSource);
             var parentSpanId = "";
             using var listener = new ActivityListener
             {
-                ShouldListenTo = activitySource => true,
+                ShouldListenTo = activitySource => ReferenceEquals(activitySource, testSource),
```
Comment (davidfowl) [inline src/Hosting/Hosting/test/HostingApplicationDiagnosticsTests.cs:504]: clever

**Review by davidfowl — APPROVED** [review]
