### PR TITLE
[Blazor] Correctly encode non-ASCII characters in redirect URL

### LINKED ISSUE #52438: `InvalidOperationException` occurs on `onsubmit` event when using `NavigateTo` method with non-ASCII characters on Blazor SSR render mode.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`InvalidOperationException` occurs on `onsubmit` event when using `NavigateTo` method with non-ASCII characters on Blazor SSR render mode. Only ASCII case works fine.

```csharp
// OK
NavigationManager.NavigateTo("navtarget?text=HelloWorld");

// Error
NavigationManager.NavigateTo("navtarget?text=😀");
```

The error page:
image

The stack trace:
```
InvalidOperationException: Invalid non-ASCII or control character in header: 0xD83D
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(char ch)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(string headerCharacters, bool requireAscii)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(string headerName, StringValues headerValues, Func<string, Encoding> encodingSelector)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Location(StringValues value)
Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.HandleNavigationException(HttpContext httpContext, NavigationException navigationException)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__10_0>d.MoveNext()
Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

Navigating works without error.

## Scratch
1. Create a Blazor Web App project.
  - Authentication type: None
  - Interactive render mode: None
  - Interactivity location: Per page/component
  - Uncheck Include sample pages
     image

2. Edit `Components/Pages/Home.razor` like below:
```razor
@page "/"
@inject NavigationManager NavigationManager

<PageTitle>Home</PageTitle>

<form method="post" @formname="form1" @onsubmit="Navigate">
    <AntiforgeryToken />
    <input type="submit" />
</form>

@code {
    private void Navigate() => 
        NavigationManager.NavigateTo("somepage?text=😀");
}
```

3. Launch the project.
4. Click the submit button.

## Use a repro project

I created a sample project for repro.
https://github.com/runceel/NoAsciiError

1. Clone the repository.
2. Open NoAsciiError.sln
3. Launch the project
4. Click `NavigationManager.NavigateTo("navtarget?text=😀")` button.

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

I faced the error when implement a search page like Bing and Google.
Those pages have a textbox and a submit button. And then search result page has search key words in query parameters.
If search key worlds are non ASCII characters such as Emoji and Japanese and other languages, the error occurs.
I guess it is a serious blocker to use Blazor SSR mode.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Correctly encode non-ASCII characters in redirect URL

Encodes non-ASCII characters included in redirect URLs.

## Description

The culprit was the use of [`Uri.ToString()`](https://github.com/dotnet/runtime/blob/2558ff925b907633332c2f5160c15d153f29f2db/src/libraries/System.Private.Uri/src/System/Uri.cs#L1556), which decodes URL-encoded characters. This PR replaces the relevant occurrences of `Uri.ToString()` with `Uri.AbsoluteUri`, which does not perform any decoding.

Fixes #52438

### CODE REVIEW

File: src/Components/Endpoints/src/DependencyInjection/HttpNavigationManager.cs [hunk 1]
```diff
@@ -11,7 +11,7 @@ internal sealed class HttpNavigationManager : NavigationManager, IHostEnvironmen
 
     protected override void NavigateToCore(string uri, NavigationOptions options)
     {
-        var absoluteUriString = ToAbsoluteUri(uri).ToString();
+        var absoluteUriString = ToAbsoluteUri(uri).AbsoluteUri;
```
Comment (MackinnonBuck) [inline src/Components/Endpoints/src/DependencyInjection/HttpNavigationManager.cs:14]: Accessing the `Uri.AbsoluteUri` property will throw if the `Uri` instance does not represent an absolute URI, but this case is safe because `ToAbsoluteUri()` always returns an absolute URI.

**Review by javiercn — APPROVED** [review]
