### PR TITLE
Use ArrayPool as default pool fallback

### LINKED ISSUE #30364: ResponseCachingMiddleware: exception "Cannot allocate more than 4096 bytes in a single buffer" when a client disconnects
When we upgraded from .NET Core 3.1 to .NET 5.0 (5.0.3), we started getting ~~rare~~ random exception from `ResponseCachingMiddleware`:
```
System.ArgumentOutOfRangeException: Cannot allocate more than 4096 bytes in a single buffer (Parameter 'size')
at System.Buffers.MemoryPoolThrowHelper.ThrowArgumentOutOfRangeException_BufferRequestTooLarge(Int32 maxSize)
at System.Buffers.SlabMemoryPool.Rent(Int32 size)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.GetSpan(Int32 sizeHint)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)
at Microsoft.AspNetCore.ResponseCaching.CachedResponseBody.CopyToAsync(PipeWriter destination, CancellationToken cancellationToken)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.TryServeCachedResponseAsync(ResponseCachingContext context, IResponseCacheEntry cache
Entry)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.TryServeFromCacheAsync(ResponseCachingContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at ResponseCachingMiddleware.DotNet5.Bug.RequestLoggingMiddleware.Invoke(HttpContext httpContext) in C:\Projects\ResponseCachingMiddleware.DotNet5.Bug\
ResponseCachingMiddleware.DotNet5.Bug\RequestLoggingMiddleware.cs:line 22
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext] (IHttpApplication`1 application)
```
We get this exception once in 3 days, very random and very rare. I discovered it is likely happening when a client disconnects in the middle of downloading a large cached response. Here is a demo project with a clean Web API project to replicate it: https://github.com/xhafan/ResponseCachingMiddleware.DotNet5.Bug

I can replicate it on Amazon Linux (amzn2-ami-ecs-hvm-2.0.20190614-x86_64-ebs) and on Windows 7 SP1 with latest .NET 5.0.3 . This issues was not happening on .NET Core 3.1

### PR DESCRIPTION
**Pull request by sebastienros**
`GetFakeMemory()` can throw an exception if `sizeHint` is greater than `MaxPoolSize`. The default pool is `PinnedBlockMemoryPool` with a max size of 4096.

Fixes #30364

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace System.Buffers
+{
+    internal class HttpOutputProducerHelper
+    {
+        public static IMemoryOwner<byte> ReserveFakeMemory(MemoryPool<byte> memoryPool, int sizeHint)
```
Comment (adityamandaleeka) [inline src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs:8]: Any reason why we can't rename `sizeHint` everywhere since it's not really a hint anymore, but a min?

Comment (sebastienros) [reply src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs:8]: This one could be. The other ones would introduce a breaking change, or it would be done just on "some" methods that are private/internal.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs:8]: I like changing the name in non-public APIs.

File: src/Servers/Kestrel/Core/test/OutputProducerTests.cs [hunk 2]
```diff
@@ -74,6 +74,89 @@ public void AbortsTransportEvenAfterDispose()
             mockConnectionContext.Verify(f => f.Abort(null), Times.Once());
         }
 
+        [Fact]
+        public void AllocatesFakeMemorySmallerThanMaxBufferSize()
```
[the remark this answers is not in the document]
Comment (sebastienros) [reply src/Servers/Kestrel/Core/test/OutputProducerTests.cs:78]: Did the suggested changes, including functional tests for h2 and h3

File: src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs (hunk 1 above)
Comment (sebastienros) [reply src/Servers/Kestrel/Core/src/Internal/HttpOutputProducerHelper.cs]: Changed it where internal and private were used

**Review by halter73 — APPROVED** [review]

**Comment by davidfowl** [comment]
Wouldn't it be simpler to support a null fake memory owner and just use ArrayPool.Shared?

**Comment by halter73** [comment]
> Wouldn't it be simpler to support a null fake memory owner and just use ArrayPool.Shared?

What's the benefit? Wouldn't you need to special case returning the array in Dispose() in that case?

**Comment by sebastienros** [comment]
I would understand @davidfowl 's suggestion as replacing `_fakeMemoryOwner` by `byte[] _fakeMemory` which would always come from the `ArrayPool.Shared` if set, and then returned in `Dispose`. So as single source. But I don't know why it was using `_memoryPool` before vs. the array pool.

**Comment by davidfowl** [comment]
> What's the benefit? Wouldn't you need to special case returning the array in Dispose() in that case?

This code originally came from https://source.dot.net/#System.IO.Pipelines/System/IO/Pipelines/BufferSegment.cs,56 which handles this in a much nicer way IMO.

**Comment by halter73** [comment]
What's nicer about BufferSegment's way of doing it?

**Comment by davidfowl** [comment]
It's isolated in the buffer segment and doesn't allocate another kind of `IMemoryOwner<byte>`.

**Comment by sebastienros** [comment]
I am trying to implement what I think you meant ... hope it's worth it. Will do it in a separate branch as I am very not sure about the end result.

**Comment by sebastienros** [comment]
@davidfowl is this what you meant?

https://github.com/dotnet/aspnetcore/commit/5de377a97b6ccb07ef1bb827cf6019e2f9efc06d

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs [hunk 3]
```diff
@@ -486,11 +486,13 @@ static void ThrowUnexpectedState()
             }
         }
 
-        private Memory<byte> GetFakeMemory(int sizeHint)
+        internal Memory<byte> GetFakeMemory(int minSize)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs:489]: Nit:

```suggestion
        private Memory<byte> GetFakeMemory(int minSize)
```

**Comment by sebastienros** [comment]
@halter73 now I understand the comment, thanks.

**Comment by sebastienros** [comment]
updated

**Comment by sebastienros** [comment]
@davidfowl are the changes what you expected?

**Review by davidfowl — APPROVED** [review]
