### PR TITLE
 Fix Heartbeat logging after disposal

### LINKED ISSUE #47577: Heartbeat.TimerLoop continues running after WebHost stopped and disposed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CoreWCF has a new test to validate a fix for a failure code path in PR (CoreWCF/CoreWCF#1011). It consistently fails running on Linux in .NET 6.0 and .NET 7.0, and occasionally fails on Windows.  

We configure a custom logger provider which writes to the XUnit ITestOutputHelper so that we can capture any log output with the test that's running. XUnit throws an exception if you try to write to the logger after the test has ended. We added some extra instrumentation to record which test was getting an exception due to writing to the ITestOutputHelper after the test has completed. We did this to catch test failures where we had forgotten to clean up the WebHost correctly so the exception message when this happens includes the test name in the exception message. In the test that we're seeing problems, we have received the entire Http response as we have created an exception (which we catch and check) from the response.  
The error we get when running the test as part of our PR tests is this:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (ThrowingExtensibilityReturnsFault is no longer an active test.)
 ---> System.InvalidOperationException: ThrowingExtensibilityReturnsFault is no longer an active test.
   at Helpers.XunitLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/vsts/work/1/s/src/Common/tests/Helpers/XunitLogger.cs:line 41
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()
```
We are correctly disposing the WebHost (which will call StopAsync for us) as we have a using block around the host. It looks like the TimerLoop is failing a heartbeat check (as expected as the WebHost has been shut down) and logging the failure. The logging after test end is causing XUnit to abort the test run.  

I don't know why we aren't seeing this problem on other tests. The only thing which is different with this test is it's a lot quicker than our other tests as the operation dispatch is purposefully failed quite early in our dispatch process and generates a failure message very quickly. From an aspnetcore perspective, we aren't doing anything different.

### Expected Behavior

The HeartBeat timer doesn't run after the WebHost has stopped and been disposed. If this is difficult because of race conditions, at least don't log anything after the host has been stopped.

### Steps To Reproduce

The behavior reproduces with the new test `ThrowingExtensibilityReturnsFault` in the CoreWCF PR CoreWCF/CoreWCF#1011. It's possible the issue only reproduces in a 2 CPU core environment. Doing that can be done by providing a xunit.runner.json file with the following contents:
```json
{
    "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
    "maxParallelThreads" : 2
}
```

We are mostly seeing this reproduce on Linux, but I have seen it fail on Windows in our PR test runs.

### Exceptions (if any)

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (ThrowingExtensibilityReturnsFault is no longer an active test.)
 ---> System.InvalidOperationException: ThrowingExtensibilityReturnsFault is no longer an active test.
   at Helpers.XunitLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/vsts/work/1/s/src/Common/tests/Helpers/XunitLogger.cs:line 41
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()
```

### .NET Version

Latest 6.0 and 7.0 GA releases

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mconnew**
#  Fix Heartbeat logging after disposal
Prevent Heartbeat from logging exceptions after disposal.
Fix timer loop so disposal check is immediately before heartbeat execution.

## Description
During CoreWCF (based on aspnetcore) unit tests we have an ILogger built on `ITestOutputHelper` which will abort the test run if something is logged after the test has completed execution. The Heartbeat class can log after `Dispose()` has been called, which means our test run is getting aborted.

This change fixes 2 issues. First, the existing implementation called `Thread.Sleep` between the disposal check and calling the heart beat handlers which means the handlers can easily get called after the host has been stopped. Then in the handler code, if there's an exception it would always log even if it was disposed.

Fixes #47577

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 1]
```diff
@@ -62,17 +62,20 @@ internal void OnHeartbeat()
...
+            if (!_stopped)
+            {
+                _trace.LogError(0, ex, $"{nameof(Heartbeat)}.{nameof(OnHeartbeat)}");
+            }
         }
     }
 
     private void TimerLoop()
     {
+        Thread.Sleep(_interval);
```
Comment (mconnew) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:74]: I added an initial `Thread.Sleep` before the timer loop to avoid a potential breaking change. The previous code guaranteed a `Thread.Sleep` call before the first invocation of `OnHeatbeat`. I wanted to avoid the possibility of any latent issues of a heartbeat handler failing if called too soon. This change maintains this behavior.

**Comment by JamesNK** [comment]
Seems ok to me.

Off-topic to PR but related to this area: It seems wasteful that the heartbeat thread can sleep for 5 seconds after the app is stopped. Instead of Thread.Sleep, have we considered using a WaitHandle that can be triggered on stop to exit the TimerLoop immediately?

@halter73 @Tratcher

**Comment by mconnew** [comment]
Isn't it only 1 second?

**Review by JamesNK — APPROVED** [review]

**Comment by danmoseley** [comment]
> Thread.Sleep can't be canceled.

I put this in the other issue but I believe Thread.Interrupt will cancel it. Of course you have to have the thread object.
