### PR TITLE
Add ClaimData for AuthenticationStateData and fix overtrimming

### LINKED ISSUE #52769: Build in AuthenticationStateProviders from Blazor Web templates
In .NET 9, we should automatically register both server and client `AuthenticationStateProvider`'s similar to the ones added by the "Individual Auth" option in the Blazor Web templates.

- [PersistingServerAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/PersistingServerAuthenticationStateProvider.cs)
- [PersistentAuthenticationStateProvider.cs](https://github.com/dotnet/aspnetcore/blob/94f1d2f852de34cbf8797f3363dc5161e83eebe2/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/PersistentAuthenticationStateProvider.cs)

This should make it a lot easier to add auth to a Blazor project that is created without the "Individual Auth" template. As part of this, we will want to figure out which claims are safe to transmit to the clients, and potentially add a callback to configure custom claims.

### LINKED ISSUE #56207: Build in AuthenticationStateProvider breaks after trimming
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just tried the new API from #52769 and replaced my implementation with it.
After the trimming during dotnet publish I get an exception as soon as the app tries to hand over to WebAssembly:
Screenshot 2024-06-12 205246

May relate to #52947 as I noticed that the `AuthenticationStateData` is using a `IList<KeyValuePair<string, string>>` but that is only my wild guess.

I'm **not** using the JSON Source Code Generation Serialization

After removing this line on client:
```
builder.Services.AddAuthenticationStateDeserialization();
```
And this line on the server side:
```
.AddAuthenticationStateSerialization(options => options.SerializeAllClaims = true)
```

The app worked again as expected.

### Expected Behavior

The handover to Web Assembly should work flawless.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.0-preview.5.24306.7

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by halter73**
This PR is a follow up to #55821 which added the `AuthenticationStateProvider` implementations from the .NET 8 Blazor web project templates to the runtime. You can opt into using these by adding the new services as follows.

```csharp
// Server Program.cs
builder.Services.AddRazorComponents()
    .AddInteractiveWebAssemblyComponents()
    .AddAuthenticationStateSerialization();
```

```csharp
// Client Program.cs
builder.Services.AddAuthenticationStateDeserialization();
```

These services rely on JSON serializing and deserializing the newly added `AuthenticationStateData` type which previously contained a `Claims` property of type `IList<KeyValuePair<string, string>>`. After API review feedback in #52769, we've decided to update `AuthenticationStateData.Claims` to be an `IList<ClaimData>`.

This PR also fixes #56207 which was caused by the overtrimming `AuthenticationStateData.Claims` and updates the `ServerRenderedAuthenticationStateTest` and  `DefaultAuthenticationStateSerializationOptionsTest` to test published trimmed WebAssembly static assets.

As part of this, I refactored the common logic of most tests that currently use static assets published to the "trimmed-or-threading" to use the new `TrimmingServerFixture`. However, I wonder if we should go further and make `BasicTestAppServerSiteFixture` use trimmed static assets by default when `TestTrimmedOrMultithreadingApps` is configured.

Fixes #52769
Fixes #56207

### CODE REVIEW

File: src/Components/test/E2ETest/Infrastructure/ServerFixtures/TrimmingServerFixture.cs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+using Microsoft.AspNetCore.Hosting;
+using Microsoft.Extensions.DependencyInjection;
+using Microsoft.Extensions.Hosting;
+using Microsoft.Extensions.Logging;
+using Microsoft.Extensions.Logging.Testing;
+
+namespace Microsoft.AspNetCore.Components.E2ETest.Infrastructure.ServerFixtures;
+
+// REVIEW: Should this be merged into BasicTestAppServerSiteFixture? Is there any case where we wouldn't
+// want to trim BasicTestAppServerSiteFixture tests when TestTrimmedOrMultithreadingApps is true?
```
Comment (halter73) [inline src/Components/test/E2ETest/Infrastructure/ServerFixtures/TrimmingServerFixture.cs:14]: @dotnet/aspnet-blazor-eng I'm curious what everyone thinks about this.

File: src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs [hunk 2]
```diff
@@ -86,7 +86,17 @@ public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
 
             _ = app.UseEndpoints(endpoints =>
             {
-                endpoints.MapStaticAssets();
+                // REVIEW: Why doesn't MapStaticAssets search env.ContentRootPath before AppContext.BaseDirectory first to begin with?
```
Comment (halter73) [inline src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs:89]: @javiercn Would it make sense for `MapStaticAssets()` to search the content root first for the manifest by default? This would make things behave more similarly to `UseStaticFiles()` and probably prevent a lot of future bug reports.

It's designed to be the configurable root for things like static assets manifests

> The content root is the base path for:
>
> * The executable hosting the app (*.exe*).
> * Compiled assemblies that make up the app (*.dll*).
> * Content files used by the app, such as:
>  * Razor files (`.cshtml`, `.razor`)
>  * Configuration files (`.json`, `.xml`)
>  * Data files (`.db`)
> * The [Web root](#web-root), typically the *wwwroot* folder.

https://learn.microsoft.com/aspnet/core/fundamentals/#content-root

Of course, it makes sense to fall back to `AppContext.BaseDirectory` primarily for development where the content root is the project root which will not contain the manifest. But I think it makes sense to look in the user-configurable location first.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DeserializedAuthenticationStateProvider.cs [hunk 3]
```diff
@@ -5,6 +5,7 @@
 using System.Security.Claims;
 using Microsoft.AspNetCore.Components.Authorization;
 using Microsoft.Extensions.Options;
+using static Microsoft.AspNetCore.Internal.LinkerFlags;
```
Comment (amcasey) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DeserializedAuthenticationStateProvider.cs:8]: Where was this used?

**Review by amcasey — APPROVED** [review]
Product change LGTM.  I'll let the stakeholders figure out the test infra changes.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DeserializedAuthenticationStateProvider.cs (hunk 3 above)
Comment (halter73) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DeserializedAuthenticationStateProvider.cs:8]: That's where `JsonSerialized` is defined. I might have just used `LinkerFlags.JsonSerialized`, but this `using static` pattern is consistently used elsewhere in the project where `JsonSerialized` is used.

File: src/Components/test/E2ETest/Infrastructure/ServerFixtures/TrimmingServerFixture.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/test/E2ETest/Infrastructure/ServerFixtures/TrimmingServerFixture.cs:14]: I would say that if other tests don't break, we could enable it, but I suspect we wanted to have this isolated. I believe in the past we would test all the apps with trimming during release. I don't know if/when that changed, but I'm ok if we bring that back.

File: src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs:89]: @halter73 we use `AppContext.BaseDirectory` because that's where the system generates the manifest during build/publish. I believe that's the "correct" thing to do.

As for looking at the "ContentRoot" i'm not sure if it's correct. When will the file not be on the same location as the assembly?

**Review by javiercn — APPROVED** [review]

File: src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs (hunk 2 above)
Comment (halter73) [reply src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs:89]: I thought it might be useful for people writing custom msbuild logic to publish wasm dependencies to a nonstandard PublishDir like our tests. Those people could make that work before with UseStaticFiles by modifying their content root like our tests did, and I was wondering if we should keep that working.

It's an advanced scenario though, and MapStaticAssets is a new thing. It's probably fine to say those people just need to specify the full path to the manifest.
