### PR TITLE
[7.0] Disable body streams for H2 CONNECT requests 

### LINKED ISSUE #43697: HTTP/2 WebSockets should not allow using the body streams
Forking from https://github.com/dotnet/aspnetcore/issues/42101

### Describe the bug

It should not be possible to use `Response.Body.WriteAsync()` to accidently write responses to extended CONNECT requests. Unlike with an HTTP/1.1 upgrade where a normal 200 response would not be treated as a WebSocket by the client, now it will be! The framing would likely be wrong, but it's a bad experience.

We should throw from `Response.Body.WriteAsync()` for extended CONNECT requests if the status is 200. This will at least cause Kestrel to produce a 500 response in most cases which is preferrable. I think `Response.Body.ReadAsync()` should throw too, but at least that currently no-ops.

I do not think we should be reusing `HttpProtocol.IsUpgraded` for both HTTP/1.1 upgrades and extended CONNECTs. They are different enough we should be able to distinguished at the HttpProtocol layer if that's where the implementation of `IHttpExtendedConnectFeature` is going to stay

### Expected Behavior

I wrote this test case that can go in Http2WebSocketsTests that demonstrate these issues.

```csharp
    [Fact]
    public async Task HEADERS_Received_ExtendedCONNECTMethod_DoesNotProvideUsableBodyStreams()
    {
        await InitializeConnectionAsync(async context =>
        {
            var connectFeature = context.Features.Get<IHttpExtendedConnectFeature>();

            // The below should really throw instead, but nooping is better than our current Response.Body behavior.
            Assert.Equal(0, await context.Request.Body.ReadAsync(new byte[1]));
            // Tell me this doesn't get sent in a DATA frame with a 200 status code!!!
            // This will be interpreted as a valid data from the server to client over the connection rather than a normal response.
            await Assert.ThrowsAsync<InvalidOperationException>(() => context.Response.Body.WriteAsync(new byte[1] { 0x00 })); // FAILS!

            var stream = await connectFeature.AcceptAsync();
            await stream.WriteAsync(new byte[] { 0x01 });
        });

        var headers = new[]
        {
            new KeyValuePair<string, string>(HeaderNames.Method, "CONNECT"),
            new KeyValuePair<string, string>(HeaderNames.Protocol, "websocket"),
            new KeyValuePair<string, string>(HeaderNames.Scheme, "http"),
            new KeyValuePair<string, string>(HeaderNames.Path, "/chat"),
            new KeyValuePair<string, string>(HeaderNames.Authority, "server.example.com"),
            new KeyValuePair<string, string>(HeaderNames.WebSocketSubProtocols, "chat, superchat"),
            new KeyValuePair<string, string>(HeaderNames.SecWebSocketExtensions, "permessage-deflate"),
            new KeyValuePair<string, string>(HeaderNames.SecWebSocketVersion, "13"),
            new KeyValuePair<string, string>(HeaderNames.Origin, "http://www.example.com"),
        };
        await SendHeadersAsync(1, Http2HeadersFrameFlags.END_HEADERS, headers);

        await SendDataAsync(1, new byte[(int)_serviceContext.ServerOptions.Limits.MaxRequestBodySize + 1], endStream: true);

        var headersFrame = await ExpectAsync(Http2FrameType.HEADERS,
            withLength: 32,
            withFlags: (byte)Http2HeadersFrameFlags.END_HEADERS,
            withStreamId: 1);

        _hpackDecoder.Decode(headersFrame.PayloadSequence, endHeaders: false, handler: this);

        Assert.Equal(2, _decodedHeaders.Count);
        Assert.Contains("date", _decodedHeaders.Keys, StringComparer.OrdinalIgnoreCase);
        Assert.Equal("200", _decodedHeaders[HeaderNames.Status]);

        var dataFrame = await ExpectAsync(Http2FrameType.DATA,
            withLength: 1,
            withFlags: (byte)Http2DataFrameFlags.NONE,
            withStreamId: 1);
        Assert.Equal(0x01, dataFrame.Payload.Span[0]); // FAILS! because Response.Body.WriteAsync wrote 0x00 instead of 0x01.

        dataFrame = await ExpectAsync(Http2FrameType.DATA,
            withLength: 0,
            withFlags: (byte)Http2DataFrameFlags.END_STREAM,
            withStreamId: 1);

        await StopConnectionAsync(expectedLastStreamId: 1, ignoreNonGoAwayFrames: false);
    }
```

### PR DESCRIPTION
**Pull request by Tratcher**
Disallow reading the request body or writing to the response body for H2 CONNECT requests.

## Description

HTTP/2 CONNECT requests use a new protocol implemented in 7.0 to enable WebSockets over HTTP/2. When the request is presented to the application the normal request and response body streams and pipe reader/writers let you interact with it as a normal request. Since CONNECT requests aren't supposed to have a normal request or response body this may cause someone to accidently break the request if they weren't paying attention to the CONNECT. E.g. buffering all the data, or responding with HTML.

Responses with a status code of 300+ are allowed to have a body (e.g. for errors), so we need to check the status code when writing.

I noticed that Upgrades only disabled the Stream, not the PipeWriter, so I did something similar there.

Fixes #43697

## Customer Impact

This helps apps avoid accidentally mishandling a CONNECT request.

## Regression?

- [ ] Yes
- [x] No

## Risk

- [ ] High
- [ ] Medium
- [x] Low

New feature area.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/WrappingPipeWriter.cs [hunk 1]
```diff
@@ -0,0 +1,70 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.IO.Pipelines;
+
+namespace Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure;
+
+internal class WrappingPipeWriter : PipeWriter
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/WrappingPipeWriter.cs:8]:
```suggestion
internal sealed class WrappingPipeWriter : PipeWriter
```

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs [hunk 2]
```diff
@@ -1166,7 +1166,7 @@ internal async Task<byte[]> ReadAllAsync()
         }
     }
 
-    internal async Task<Http2FrameWithPayload> ReceiveFrameAsync(uint maxFrameSize = Http2PeerSettings.DefaultMaxFrameSize)
+    internal async Task<Http2FrameWithPayload> ReceiveFrameAsync(uint maxFrameSize = uint.MaxValue)
```
Comment (JamesNK) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:1169]: Reason for this change?

**Comment by JamesNK** [comment]
Noticed after I reviewed that this is still draft. Apologies for jumping the gun 😄

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs [hunk 3]
```diff
@@ -1208,7 +1208,7 @@ internal async Task<Http2FrameWithPayload> ReceiveFrameAsync(uint maxFrameSize =
 
     internal async Task<Http2FrameWithPayload> ExpectAsync(Http2FrameType type, int withLength, byte withFlags, int withStreamId)
     {
-        var frame = await ReceiveFrameAsync((uint)withLength);
+        var frame = await ReceiveFrameAsync();
```
[the remark this answers is not in the document]
Comment (Tratcher) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:1211]: I changed this here and the max value because when Expect fails it's usually because it received a different frame than expected, and the frame length is the least interesting bit of information. I want the checks below for the type and flags to run and then it verifies the length last.

**Comment by Tratcher** [comment]
> Noticed after I reviewed that this is still draft. Apologies for jumping the gun 😄

No worries, I only drafted it because I realized I forgot to handle the non-200 responses.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs (hunk 2 above)
Comment (Tratcher) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:1169]: See the discussion at the call site.

File: src/Servers/Kestrel/Core/src/CoreStrings.resx [hunk 4]
```diff
@@ -716,4 +716,7 @@ For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?l
   <data name="Http3ErrorControlStreamClosed" xml:space="preserve">
     <value>A control stream used by the connection was closed or reset.</value>
   </data>
-</root>
\ No newline at end of file
+  <data name="ConnectResponseCanNotHaveBody" xml:space="preserve">
+    <value>'CONNECT' requests with a 2XX success status code cannot have a response body.</value>
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/CoreStrings.resx:720]: Nit. Let's just include the non-error status code in the exception message. Maybe someone will try setting a 101 status code or something and gets confused by this 😆.

```suggestion
    <value>Responses to 'CONNECT' requests cannot produce a response body with the successful status code: '{StatusCode}'. See IHttpExtendedConnectFeature.</value>
```

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs [hunk 5]
```diff
@@ -437,4 +428,134 @@ public async Task ExtendedCONNECT_AcceptAsyncStream_IsNotLimitedByMaxRequestBody
...
+        {
+            var connectFeature = context.Features.Get<IHttpExtendedConnectFeature>();
+            // We could throw, but no-oping is adequate.
+            Assert.Equal(0, await context.Request.Body.ReadAsync(new byte[1]));
+            var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => context.Response.Body.WriteAsync(new byte[1] { 0x00 }).AsTask());
+            Assert.Equal(CoreStrings.ConnectResponseCanNotHaveBody, ex.Message);
+            ex = await Assert.ThrowsAsync<InvalidOperationException>(() => context.Response.BodyWriter.WriteAsync(new byte[1] { 0x00 }).AsTask());
+            Assert.Equal(CoreStrings.ConnectResponseCanNotHaveBody, ex.Message);
+
+            var stream = await connectFeature.AcceptAsync();
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:445]: What happens when the endpoint does absolutely nothing for an extended CONNECT request? Just `httpContext => Task.CompletedTask`. Do we just produce an "empty" 200 response? Or a 500? I think it should be a 500 given the request was not successfully handled. Do we log anything about not properly handling an extended CONNECT in this case?

I know that isn't the original issue, but this got me thinking. If we are producing a 200 response this case, I guess this could be addressed in a follow up.

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/CoreStrings.resx (hunk 4 above)
Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/CoreStrings.resx:720]: Why reference the IHttpExtendedConnectFeature? So they can formally accept the CONNECT? In that case it should say something like "Use IHttpExtendedConnectFeature to accept the CONNECT request."

Comment (halter73) [reply src/Servers/Kestrel/Core/src/CoreStrings.resx:720]: I'm fine with "Use IHttpExtendedConnectFeature to accept the CONNECT request." 

I think the exception will be confusing for some people if the message just says you cannot produce a response body with a successful status code without indicating how to handle the request successfully.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs (hunk 5 above)
Comment (Tratcher) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:445]: I just tried this. The client gets back a 200, END_STREAM. They might get an additional RST_STREAM frame if the request side of the stream is still open.

I think this is fine. The connection is 'accepted' and immediately closed. Yes the server did this by mistake, but the client isn't left in a bad state.

I chalk this ambiguity up to 200 being a bad choice for an accept status code 😁.

Comment (Tratcher) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:445]: This is something I'd like to revisit based on customer feedback.

**Comment by Tratcher** [comment]
While updating the error messages I realized Accept was limiting responses to exactly 200 instead of 2XX. Fixed.

**Comment by halter73** [comment]
> While updating the error messages I realized Accept was limiting responses to exactly 200 instead of 2XX. Fixed.

Out of curiosity, why would you use a 2XX status code other than 200 for an accepted connection? I'm surprised the spec allows it.

**Comment by Tratcher** [comment]
No idea.

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.

**Comment by Tratcher** [comment]
@dotnet/aspnet-admins please merge.
