### PR TITLE
[GenerateEmbeddedResourcesManifest] handle Items with empty LogicalName #29306

### LINKED ISSUE #29306: ManifestEmbeddedFileProvider corrupt manifest file
### Describe the bug
I am seeing the same issue that was described here: https://www.gitmemory.com/issue/aspnet/Extensions/1333/507701113
II get a runtime exception constructing the `ManifestEmbeddedFileProvider` because it complains that the format of it's embedded manifest file is wrong - even though this is produced for me (i.e by the build task).

image

On looking around I came accross the above link and can confirm it only happens in the project on which I also am embedded a resx file i.e I have these additional csproj entries:

```
 <ItemGroup>
        <Compile Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>PlatformSeedData.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>PlatformSeedData.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

```

### To Reproduce
Create a vanilla csproj project, include the `ManifestEmbeddedFileProvider` but also set up an embedded RESX file like so:

```
 <ItemGroup>
        <Compile Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>PlatformSeedData.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>PlatformSeedData.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
```

Start your application and create an instance of the file provider. 

### Exceptions (if any)
As shown above.

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

### PR DESCRIPTION
**Pull request by rafd123**
# [GenerateEmbeddedResourcesManifest] handle Items with empty LogicalName #29306

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Ensure that the `GenerateEmbeddedResourcesManifest` task handles the possibility of `Item`s with no `LogicalName`

## Description

A `LogicalName` isn't assigned to Resx resources. See https://github.com/dotnet/msbuild/blob/6300d22b25cc1bcb634663bd7087e31d8312bb15/src/Tasks/CreateManifestResourceName.cs#L231-L238

As a result, `GenerateEmbeddedResourcesManifest` needs to handle this possibility...otherwise it'll generate an invalid `Microsoft.Extensions.FileProviders.Embedded.Manifest.xml` with empty name attributes for `File` elements and empty `ResourcePath` elements.

Fixes #29306

### CODE REVIEW

File: src/FileProviders/Manifest.MSBuildTask/src/GenerateEmbeddedResourcesManifest.cs [hunk 1]
```diff
@@ -90,11 +90,11 @@ public Manifest BuildManifest(EmbeddedItem[] processedItems)
         return manifest;
     }
 
-    private static string GetManifestPath(ITaskItem taskItem) => string.Equals(taskItem.GetMetadata(LogicalName), taskItem.GetMetadata(ManifestResourceName)) ?
+    private static string GetManifestPath(ITaskItem taskItem) => string.IsNullOrEmpty(taskItem.GetMetadata(LogicalName)) || string.Equals(taskItem.GetMetadata(LogicalName), taskItem.GetMetadata(ManifestResourceName)) ?
         taskItem.GetMetadata(TargetPath) :
         NormalizePath(taskItem.GetMetadata(LogicalName));
 
-    private static string GetAssemblyResourceName(ITaskItem taskItem) => string.Equals(taskItem.GetMetadata(LogicalName), taskItem.GetMetadata(ManifestResourceName)) ?
+    private static string GetAssemblyResourceName(ITaskItem taskItem) => string.IsNullOrEmpty(taskItem.GetMetadata(LogicalName)) || !string.IsNullOrEmpty(taskItem.GetMetadata(LogicalName)) && string.Equals(taskItem.GetMetadata(LogicalName), taskItem.GetMetadata(ManifestResourceName)) ?
```
Comment (MackinnonBuck) [inline src/FileProviders/Manifest.MSBuildTask/src/GenerateEmbeddedResourcesManifest.cs:97]: I think we can remove the "`!string.IsNullOrEmpty(taskItem.GetMetadata(LogicalName))`" check, since that expression will only get reached if the previous "`string.IsNullOrEmpty(taskItem.GetMetadata(LogicalName))`" check evaluates to `false`.

**Review by MackinnonBuck — COMMENTED** [review]
Thanks for the contribution, @rafd123!

Just a small suggestion and then this should be good to go.

File: src/FileProviders/Manifest.MSBuildTask/src/GenerateEmbeddedResourcesManifest.cs (hunk 1 above)
Comment (rafd123) [reply src/FileProviders/Manifest.MSBuildTask/src/GenerateEmbeddedResourcesManifest.cs]: 🤦 Thanks for catching that! Was a remnant of when I was initially floundering and missed it 'cause it ran off the screen. My bad!

Fixed!

**Review by MackinnonBuck — APPROVED** [review]
🎉
