### PR TITLE
Fix RedisCache update that breaks usage against older redis servers

### LINKED ISSUE #38715: RedisCache update in .NET 6 breaks usage against older redis servers
Timeline:

- redis 2.0 had `HSET key field value` for setting individual hash fields, and `HMSET key field value [field value ...]` for setting multiple hash fields (against the same key); as you can see, there's a lot of overlap here
- redis 4.0 observes this redundancy, and adds `HSET key field value [field value ...]`, and also *marks `HMSET` as deprecated*, although it still works fine
- `RedisCache` wants to set a hash with 3 fields against a single key; historically it has used `HMSET` for this (via Lua)
- .NET 6 switches to using the non-deprecated `HSET` API

Impact:

For users targeting redis versions that lack the varadic `HSET` (so: versions before 4.0), it simply doesn't work, manifesting in a `RedisServerException`:

> Wrong number of args calling Redis command From Lua script

Suggestions:

1. check the redis server version (APIs exist on SE-Redis for this) before deciding which to use
2. or, just use `HMSET`; it hasn't gone anywhere, and is honestly: unlikely to go anywhere
3. make 3 simple calls to `HSET`, which would work everywhere and still be contiguous (thanks to the single-threaded core) - although I confess that this is inelegant

A complicating factor is that the [Redis-64](https://www.nuget.org/packages/Redis-64) port of Redis on Windows by Microsoft (now abandoned): stops at 3.0.503. Alternatives for Windows hosting are WSL or Memurai (commercial), or containers such as Docker. This means that some folks have (perhaps unwisely) stagnated on v3, wanting to keep things simple.

Links:

- relevant .NET 6 change: [here](https://github.com/dotnet/aspnetcore/commit/bf4d9b9bd0d11e4e46924e4e09014580ec1a1449)
- [existing aspnetcore bug](https://github.com/dotnet/aspnetcore/issues/33628), ccing @JunTaoLuo who closed it (I can't comment on the existing one)
- [customer impact](https://github.com/StackExchange/StackExchange.Redis/issues/1904) (being reported in the SE-Redis library)

### PR DESCRIPTION
**Pull request by fvoronin**
### Summary of the changes
Checking Redis version and then calling the right API.

A couple of questions:
- Is it necessary to log the switch to the old API?
- What to do with integration tests? They are currently disabled.

Fixes #38715

### CODE REVIEW

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 1]
```diff
@@ -22,20 +22,29 @@ public class RedisCache : IDistributedCache, IDisposable
...
+                if ARGV[3] ~= '-1' then
+                  redis.call('EXPIRE', KEYS[1], ARGV[3])
+                end
+                return 1");
+
     private const string AbsoluteExpirationKey = "absexp";
     private const string SlidingExpirationKey = "sldexp";
     private const string DataKey = "data";
     private const long NotPresent = -1;
+    private readonly Version ServerVersionWithExtendedSetCommand = new Version(4, 0, 0);
```
Comment (sebastienros) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:42]:
```suggestion
    private static readonly Version ServerVersionWithExtendedSetCommand = new Version(4, 0, 0);
```

Maybe?

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 2]
```diff
@@ -257,6 +266,29 @@ private async Task ConnectAsync(CancellationToken token = default(CancellationTo
...
+    private void ValidateServerFeatures()
+    {
+        if (_connection is null)
+        {
+            return;
+        }
+
+        foreach (var endPoint in _connection.GetEndPoints())
+        {
+            if (_connection.GetServer(endPoint).Version < ServerVersionWithExtendedSetCommand)
```
Comment (sebastienros) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:284]: Is there an async version of that?

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 3]
```diff
@@ -22,20 +22,29 @@ public class RedisCache : IDistributedCache, IDisposable
     // ARGV[3] = relative-expiration (long, in seconds, -1 for none) - Min(absolute-expiration - Now, sliding-expiration)
     // ARGV[4] = data - byte[]
     // this order should not change LUA script depends on it
-    private const string SetScript = (@"
+    private const string RegularSetScript = (@"
```
Comment (Tratcher) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:25]:
```suggestion
    private const string LatestSetScript = (@"
```

**Review by Tratcher — APPROVED** [review]

File: src/Caching/StackExchangeRedis/src/RedisCache.cs (hunk 2 above)
Comment (fvoronin) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:284]: No, there are no async versions of that
[IConnectionMultiplexer.GetEndPoints() source](https://github.com/StackExchange/StackExchange.Redis/blob/f3052db96b071aa4bd88010ef2716d4d6f0329c7/src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs#L118)
[IConnectionMultiplexer.GetServer() source](https://github.com/StackExchange/StackExchange.Redis/blob/f3052db96b071aa4bd88010ef2716d4d6f0329c7/src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs#L190)

Comment (halter73) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:284]: After a quick glance, it looks like the version is [read from in-memory config](https://github.com/StackExchange/StackExchange.Redis/blob/f3052db96b071aa4bd88010ef2716d4d6f0329c7/src/StackExchange.Redis/ServerEndPoint.cs#L52) rather than queried from the server. Is that right, @NickCraver?

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 4]
```diff
@@ -257,6 +266,29 @@ private async Task ConnectAsync(CancellationToken token = default(CancellationTo
...
 
+    private void PrepareConnection()
+    {
+        ValidateServerFeatures();
+        TryRegisterProfiler();
+    }
+
+    private void ValidateServerFeatures()
+    {
+        if (_connection is null)
```
Comment (halter73) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:277]: Is `_connection` ever really null here? Maybe just assert if not.

**Review by halter73 — APPROVED** [review]

File: src/Caching/StackExchangeRedis/src/RedisCache.cs (hunk 4 above)
Comment (fvoronin) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:277]: Made by analogy with existing [TryRegisterProfiler()](https://github.com/dotnet/aspnetcore/blob/a364bcbd1c360762d5e8bda8fe04fa004973489a/src/Caching/StackExchangeRedis/src/RedisCache.cs#L262).
Imho, it's better to make less noise in likely scenarios.

Comment (halter73) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:277]: I guess this doesn't make things any worse. I prefer assertions over if checks where possible because it makes future code reviews easier. It makes it much more obvious what the invariants actually are.

Comment (fvoronin) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:277]: Clear.
Should I change the check to assertion in [TryRegisterProfiler()](https://github.com/dotnet/aspnetcore/blob/a364bcbd1c360762d5e8bda8fe04fa004973489a/src/Caching/StackExchangeRedis/src/RedisCache.cs#L262) method for consistency?

Comment (halter73) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:277]: If you don't mind. This was just a nit on my part. Thanks!

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 5]
```diff
@@ -22,20 +22,29 @@ public class RedisCache : IDistributedCache, IDisposable
...
     // ARGV[4] = data - byte[]
     // this order should not change LUA script depends on it
-    private const string SetScript = (@"
+    private const string LatestSetScript = (@"
                 redis.call('HSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], 'data', ARGV[4])
                 if ARGV[3] ~= '-1' then
                   redis.call('EXPIRE', KEYS[1], ARGV[3])
                 end
                 return 1");
+    private const string DeprecatedSetScript = (@"
```
Comment (adityamandaleeka) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:31]: It would be nice to have a comment here explain why this exists.

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 6]
```diff
@@ -22,20 +22,29 @@ public class RedisCache : IDistributedCache, IDisposable
     // ARGV[3] = relative-expiration (long, in seconds, -1 for none) - Min(absolute-expiration - Now, sliding-expiration)
     // ARGV[4] = data - byte[]
     // this order should not change LUA script depends on it
-    private const string SetScript = (@"
+    private const string LatestSetScript = (@"
```
Comment (adityamandaleeka) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:25]: Nit: Consider names other than "Latest..." and "Depreceated...". Maybe "SetScript_HsetBased" and "SetScript_HmsetBased" or something like that?

**Review by adityamandaleeka — CHANGES_REQUESTED** [review]
Thanks @fvoronin, this looks good to me aside from a couple of minor comments I left.

File: src/Caching/StackExchangeRedis/src/RedisCache.cs (hunk 6 above)
Comment (fvoronin) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: Nothing good comes to mind :(
Imho, nearby comment, explaining why two types of SetScript are used, helps a lot.

Comment (NickCraver) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: FWIW I'd name this aligned with the property, e.g. `SetScriptPreExtendedSetCommand` - verbose but super clear.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
Thanks @fvoronin!

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 7]
```diff
@@ -16,26 +16,42 @@ namespace Microsoft.Extensions.Caching.StackExchangeRedis;
...
+    // But HSET doesn't allows multiple field/value pairs for Redis prior 4.0.
+
     // KEYS[1] = = key
     // ARGV[1] = absolute-expiration - ticks as long (-1 for none)
     // ARGV[2] = sliding-expiration - ticks as long (-1 for none)
     // ARGV[3] = relative-expiration (long, in seconds, -1 for none) - Min(absolute-expiration - Now, sliding-expiration)
     // ARGV[4] = data - byte[]
     // this order should not change LUA script depends on it
-    private const string SetScript = (@"
+    private const string SetScriptPerExtendedSetCommand = (@"
```
Comment (halter73) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: @NickCraver @adityamandaleeka Was this supposed to be SetScript*Pre*ExtendedSetCommand? And was this meant to apply to what's currently called DeprecatedSetScript?

Comment (adityamandaleeka) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: @halter73 You're right, that's how I interpreted @NickCraver's comment too. I saw that it was renamed but didn't catch that it was applied to the newer one (in which case I guess "per" kinda makes sense :smile:).

Comment (NickCraver) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: @halter73 yep, that's what I was pitching there :)

Comment (adityamandaleeka) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: I'll send a quick PR to rename them to SetScript and SetScriptPreExtendedSetCommand.

Comment (adityamandaleeka) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: https://github.com/dotnet/aspnetcore/pull/38928

Comment (adityamandaleeka) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: Thanks again for noticing that @halter73

Comment (fvoronin) [reply src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: @adityamandaleeka, @halter73, thanks!
