### PR TITLE
Fix handling for more method signature types

### LINKED ISSUE #60417: XML document application should handle void-returning methods
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

XML comments on record constructors produce invalid code.

```
/// <summary>
/// Represents a client in the system.
/// </summary>
public record Client()
```

produces:

```
_cache.Add(new MemberKey(typeof(global::TrainingApi.Shared.Client), MemberType.Method, ".ctor", typeof(global::System.Void), [typeof(global::System.Int32), typeof(global::System.String), typeof(global::System.String), typeof(global::System.String), typeof(global::System.Int32), typeof(global::System.Int32), typeof(global::System.DateTime)]), new XmlComment(@"Represents a client in the system.", null, null, null, null, false, null, null, null));
```

Which throws:

```
/Users/captainsafia/git/TrainingApi/net10.0/src/obj/Debug/net10.0/generated/Microsoft.AspNetCore.OpenApi.SourceGenerators/Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator/OpenApiXmlCommentSupport.generated.cs(184,131): error CS0673: System.Void cannot be used from C# -- use typeof(void) to get the void type object
```

### Expected Behavior

No errors please.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Fixes https://github.com/dotnet/aspnetcore/issues/60417.

### CODE REVIEW

File: src/OpenApi/gen/XmlComments/MemberKey.cs [hunk 1]
```diff
@@ -23,17 +23,68 @@ internal sealed record MemberKey(
...
+                }
+                else
+                {
+                    returnType = "typeof(void)";
+                }
+            }
+
+            returnType = actualReturnType.TypeKind == TypeKind.TypeParameter
+                ? "typeof(object)"
+                : $"typeof({actualReturnType.ToDisplayString(_typeKeyFormat)})";
```
Comment (martincostello) [inline src/OpenApi/gen/XmlComments/MemberKey.cs:49]: Looks like the assignment in the `else` here is redundant as it gets overwritten after the block?

**Comment by captainsafia** [comment]
@BrennanConroy For your review: found some issues while bug bashing the XML doc support implementation.

**Review by BrennanConroy — APPROVED** [review]
