### PR TITLE
Make static prerendering support auth. Fixes #11799

### LINKED ISSUE #11799: Using RenderStaticComponentAsync in default template results in exception
Steps

* Create a new blazor template `dotnet new blazorserverside`
* Edit `_Host.cshtml` and replace `RenderComponentAsync` with `RenderStaticComponentAsync`
* `dotnet run`

This results in an exception:

```C#
InvalidOperationException: GetAuthenticationStateAsync was called before Initialize.
Microsoft.AspNetCore.Components.Server.Circuits.FixedAuthenticationStateProvider.GetAuthenticationStateAsync()
Microsoft.AspNetCore.Components.CascadingAuthenticationState.OnInit()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
```

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is needed during preview 8 as a prerequisite to doing #12245

The design here also covers much of the requirements for fixing #12051 too. The core requirement is to give the hosting environment a way of telling the authentication state provider to update its claims principal.

### CODE REVIEW

File: src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    /// state information from the host environment.
+    /// </summary>
+    public interface IHostEnvironmentAuthenticationStateProvider
+    {
+        /// <summary>
+        /// Supplies updated authentication state data to the <see cref="AuthenticationStateProvider"/>.
+        /// </summary>
+        /// <param name="authenticationStateTask">A task that resolves with the updated <see cref="AuthenticationState"/>.</param>
+        void SetAuthenticationState(Task<AuthenticationState> authenticationStateTask);
+    }
```
Comment (javiercn) [inline src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: I'm not super sure what this is needed, but the name immediately threw me off path, its too similar to IHostingEnvironment.

Comment (javiercn) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: Could we instead, have an HttpContextAuthenticationStateProvider in MVC, and have the FixedAuthenticationStateProvider contain this extra method that you can call during reconnection?

That way we don't have to carry around an additional interface.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: That doesn't work, because `StaticComponentRenderer` still has to initialize whatever `AuthenticationStateProvider` you have in DI. If the one you have there is a `FixedAuthenticationStateProvider`, it wouldn't be able to invoke any methods on it, because it lives in an assembly not referenced from ViewFeatures.

Comment (javiercn) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: What do you think about adding it to the base class instead?

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: It's not applicable in general because, say, in client-side Blazor there's no host environment that can tell you what the authentication state is. The `AuthenticationStateProviderBase` is about *providing* the authentication state, not receiving it from someone else.

I don't mind renaming `IHostEnvironmentAuthenticationStateProvider` to something else if you prefer.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: Alternatively we could make ViewFeatures reference Components.Server and do all this on the concrete type for FixedAuthenticationStateProvider. 

Can’t remember why we didn’t want ViewFeatures to reference Components.Server originally. Can you?

Comment (javiercn) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: Yeah, but this is not about the interface name, its about the functionality. the ABC can simply have a
`SetAuthenticationState` you can use to set the authstate and that way you don't have to implement your own.

You can make it virtual so that if your implementation doesn't support setting it multiple times you throw, but in general I think this is similar to HttpContext.User, we provide a default mutable implementation, and if you choose to modify it is up to you.

I would not guard against users trying to change the auth state through the type system.

Comment (javiercn) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: We don't want MVC referencing signalr.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: > We don't want MVC referencing signalr.

Ah yes, now I remember.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: > Yeah, but this is not about the interface name, its about the functionality. the ABC can simply have a
SetAuthenticationState you can use to set the authstate and that way you don't have to implement your own.

It is about the functionality, yes. Setting the state has no place on the base contract as it’s not a concept that exists generally (at all, not just multiple times). That’s why I’m avoiding putting it there.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: @javiercn Do you have any further concerns about this?

Comment (javiercn) [reply src/Components/Components/src/Auth/IHostEnvironmentAuthenticationStateProvider.cs]: No, I think we have a different trade-off balance, so I leave it to your better judgement.

**Review by javiercn — APPROVED** [review]
