### PR TITLE
Signify bodylessness for HTTP/2 extended CONNECTs

### LINKED ISSUE #46002: CanHaveBody should be false for HTTP/2 CONNECT
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IHttpRequestBodyDetectionFeature.CanHaveBody is used by consumers like YARP that want to know at the protocol level if there's the possibility of a request body without trying to read from it yet. This is usually true for POST requests, false for GET requests, etc.. It's false for WebSocket upgrade requests because those are GET's. However, it's true for HTTP/2 WebSocket CONNECT requests because it technically uses a normally HTTP/2 body, but only if the CONNECT is accepted. 

https://github.com/dotnet/aspnetcore/blob/3ca6b33ba271e86c879e5299a9314e3999c09d23/src/Servers/Kestrel/Core/src/Internal/Infrastructure/BodyControl.cs#L61
https://github.com/dotnet/aspnetcore/blob/3ca6b33ba271e86c879e5299a9314e3999c09d23/src/Servers/Kestrel/Core/src/Internal/Infrastructure/BodyControl.cs#L74
https://github.com/dotnet/aspnetcore/blob/3ca6b33ba271e86c879e5299a9314e3999c09d23/src/Http/Http.Features/src/IHttpExtendedConnectFeature.cs#L12-L18

### Expected Behavior

IHttpRequestBodyDetectionFeature.CanHaveBody should return false when IHttpExtendedConnectFeature.IsExtendedConnect is true. The body should only be accessed through IHttpExtendedConnectFeature.AcceptAsync.

See the current workaround:
https://github.com/microsoft/reverse-proxy/blob/a420c76cd69e43a59005f664a311c507b18e0d3a/src/ReverseProxy/Forwarder/HttpForwarder.cs#L488-L501

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

7.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix https://github.com/dotnet/aspnetcore/issues/46002

This change makes it so that for HTTP/2 extended CONNECTs (used in HTTP/2 WebSocket scenarios, see [RFC 8441](https://www.rfc-editor.org/rfc/rfc8441#page-4)), `CanHaveBody` is false.

There's more info in the linked issue.

@MihaZupan @Tratcher PTAL

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/BodyControl.cs [hunk 1]
```diff
@@ -75,6 +74,7 @@ public Stream AcceptConnect()
         {
             // CONNECT requests do not have a request or response body until after accepted,
             // unless it's a 300+ response.
+            CanHaveBody = false;
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/BodyControl.cs:77]: What about the "unless it's a 300+ response"? Doesn't that conflict with the no body flag?

(I'm not experienced with CONNECT scenarios or code. Just raising it because of the comment)

Comment (adityamandaleeka) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/BodyControl.cs:77]: Will clarify the comment. `CanHaveBody` here is only for request bodies.

**Review by JamesNK — APPROVED** [review]
LGTM. Recommend you double check with @Tratcher

**Review by Tratcher — APPROVED** [review]
