### PR TITLE
Fix SSR page rendering intermediate state instead of the end state of components

### LINKED ISSUE #52131: Incorrect child component content is rendered with static SSR or prerendering on server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During static SSR or prerendering parent component loads data in OnInitialiedAsync method. If loaded data is not null then Child component is rendered. In this case only initial state of Child component is rendered on the UI. If Child component itself loads data in OnInitialiedAsync method then the loaded data will not be rendered.

### Expected Behavior

The latest state which is formed after OnInitializedAsync of parent and child components should be returned to browser

### Steps To Reproduce

Create Blazor 8 app from default template and select static rendering with no interactivity.

Add Child.razor component to the project:

```
<div>@childString</div>

@code {
   private string childString = "initial child";

   protected override async Task OnInitializedAsync()
   {
      await base.OnInitializedAsync();
      await Load();
   }

   private async Task Load()
   {
      await Task.Delay(1000);

      childString = "loaded child";
   }
}

```

Update Home.razor to:

```
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@if (someProperty != null)
{
   <div>@someProperty</div>
   <Child />
}

@code {
   private string? someProperty = null;

   protected override async Task OnInitializedAsync()
   {
      await base.OnInitializedAsync();
      someProperty = await Load();
   }

   private async Task<string> Load()
   {
      await Task.Delay(1000);

      return "parent";
   }
}
```

Run the project and check content of home page.

It displays:
Welcome to your new app.
parent
initial child

but should display:
Welcome to your new app.
parent
loaded child

If I remove @if (someProperty != null) condition in parent component then I see expected result on the UI

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

_No response_

### LINKED ISSUE #52871: Post request does not render end state of components on SSR page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/889b89f6000b60ac6310c152f799e90a3f1ee245/src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs#L102-L111

This happens because not all non streaming pending tasks are awaited.
By the time it reaches this line 110 not all non streaming pending tasks are in the list. Later other tasks can be added by child components.

### Expected Behavior

All non streaming pending tasks should be rendered

### Steps To Reproduce

1. Create new Blazor Web App
2. Add these 2 files to the project
`Parent.razor`
```razor
@if (someProperty)
{
    <div>@someProperty</div>
    <Child />
}

@code {
    private bool someProperty;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        someProperty = await Load();
    }

    private async Task<bool> Load()
    {
        await Task.Delay(1000);

        return true;
    }
}
```
and 
`Child.razor`
```razor
<div>@childString</div>

@code {
   private string childString = "initial child";

   protected override async Task OnInitializedAsync()
   {
        await Task.Delay(1000);

        childString = "loaded child";
   }

}
```
3. Change `Home.razor`
```razor
@page "/"
@using Microsoft.AspNetCore.Components.Forms

<PageTitle>Home</PageTitle>

@if (render)
{
    <Parent />
}

<form @onsubmit="@(() => RenderParent())" @formname="myform" method="post">
    <AntiforgeryToken />
    <button>Submit</button>
</form>

@code
{
    bool render;
    void RenderParent()
    {
        render = true;
    }
}

```
4. Run app and click submit button
5. See that `initial child` is rendered but should be `loaded child`

### Exceptions (if any)

_No response_

### .NET Version

8

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fix SSR page rendering intermediate state instead of the end state of components

The problem was that not all non streaming pending tasks are awaited.
By the time it reaches this [line](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Prerendering.cs#L165) not all non streaming pending tasks are in the list. Later other tasks can be added by child components.
I used a similar technique to correctly await all the non streaming pending tasks that is already is used [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs#L334-L351).

Same problem when post requests awaits non streaming pending tasks. Not all non streaming pending tasks are in the list. Later other tasks can be added by child components.

Fixes #52131
Fixes #52871

### CODE REVIEW

File: src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Prerendering.cs [hunk 1]
```diff
@@ -161,8 +161,23 @@ private async Task WaitForResultReady(bool waitForQuiescence, PrerenderedCompone
...
+
+    private async Task WaitForNonStreamingPendingTasks()
+    {
+        while (_nonStreamingPendingTasks.Count > 0)
+        {
+            // Create a Task that represents the remaining ongoing work for the rendering process
+            var pendingWork = Task.WhenAll(_nonStreamingPendingTasks);
+
+            // Clear all pending work.
+            _nonStreamingPendingTasks.Clear();
```
Comment (SteveSandersonMS) [inline src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Prerendering.cs:176]: It took me a minute to be convinced by the thread safety of this but I think it is valid, based on:

 * The code executing here holds the renderer's sync context
 * The only code that would add to `_nonStreamingPendingTasks` would itself have to be on the same sync context

If we wanted to make this more explicitly robust, it would be good to add a call to `Dispatcher.AssertAccess();` at the start of `Renderer.cs`'s `AddPendingTask` method. We could even no-op it in the case where we aren't tracking pending tasks, e.g.:

```cs
    // This is inside src\Components\Components\src\RenderTree\Renderer.cs
    protected virtual void AddPendingTask(ComponentState? componentState, Task task)
    {
        // The pendingTasks collection is only used during prerendering to track quiescence,
        // so will be null at other times.
        if (_pendingTasks is {} tasks)
        {
            Dispatcher.AssertAccess();
            tasks.Add(task);
        }
    }
```

Assuming that change does not break anything, would you mind including it in this PR? Then it's much easier to be confident that nothing will be posting extra tasks in a non-threadsafe way.

**Comment by SteveSandersonMS** [comment]
@surayya-MS This approach looks perfect to me. It's reassuring that nothing weird is going on and we just need to extend our use of the same pattern. Thanks for figuring this out!

File: src/Components/Endpoints/test/RazorComponentResultTest.cs [hunk 2]
```diff
@@ -368,7 +368,7 @@ public async Task StreamingRendering_CanBeDisabledForSubtree()
     {
         // Arrange
         var testContext = PrepareVaryStreamingScenariosTests();
-        var initialOutputTask = Task.WhenAll(testContext.Renderer.NonStreamingPendingTasks);
+        var initialOutputTask = Task.WhenAll(testContext.Renderer.AllNonStreamingPendingTasks);
```
Comment (surayya-MS) [inline src/Components/Endpoints/test/RazorComponentResultTest.cs:371]: I had to introduce a class for non streaming pending tasks because of these tests. By the time the execution reaches this line in the test, the list was already cleared and `Assert.False(initialOutputTask.IsCompleted);` fails.

Comment (MackinnonBuck) [reply src/Components/Endpoints/test/RazorComponentResultTest.cs:371]: Could we find a way to accomplish the same thing without allocating an extra list of tasks? Maybe we could find an approach that doesn't involve clearing the `_nonStreamingPendingTasks` list so we can keep the same approach as what we had before.

For example, something like this might work:

```csharp
private async Task WaitForNonStreamingPendingTasks()
{
    while (true)
    {
        // Create a Task that represents the remaining ongoing work for the rendering process
        var pendingWork = Task.WhenAll(_nonStreamingPendingTasks);

        if (pendingWork.IsCompletedSuccessfully)
        {
            // Since all tasks completed synchronously, that means each pending task
            // had already successfully run to completion, and there's no extra work to do.
            break;
        }

        // Wait for streaming operations to complete before checking again.
        await pendingWork;
    }
}
```

Or, a possibly better approach might be to change the visibility of `WaitForNonStreamingPendingTasks()` to `internal` and then have it lazily run a Task based on the current implementation. Something like this:

```csharp
private Task? _waitForNonStreamingPendingTasks;

// ...

internal Task WaitForNonStreamingPendingTasks()
{
    return _waitForNonStreamingPendingTasks ??= Execute();

    async Task Execute()
    {
        while (_nonStreamingPendingTasks.Count > 0)
        {
            // Create a Task that represents the remaining ongoing work for the rendering process
            var pendingWork = Task.WhenAll(_nonStreamingPendingTasks);

            // Clear all pending work.
            _nonStreamingPendingTasks.Clear();

            // new work might be added before we check again as a result of waiting for all
            // the child components to finish executing SetParametersAsync
            await pendingWork;
        }
    }
}
```

That way, you could change the line in this test to:

```csharp
var initialOutputTask = testContext.Renderer.WaitForNonStreamingPendingTasks();
```

What do you think?

Comment (MackinnonBuck) [reply src/Components/Endpoints/test/RazorComponentResultTest.cs:371]: Actually, that 2nd example could be improved further if you keep `WaitForNonStreamingPendingTasks` private, but then have a public property to access `_waitForNonStreamingPendingTasks` and throw if it's `null`. That way you don't accidentally call `WaitForNonStreamingPendingTasks` from a test before any tasks have been actually added to the list (because then `_waitForNonStreamingPendingTasks` would be stuck in a "completed" state and any future non-streaming pending tasks get ignored).

Comment (surayya-MS) [reply src/Components/Endpoints/test/RazorComponentResultTest.cs]: Thanks, Mackinnon. I think it is a great idea! Indeed, I don't need to keep all the non streaming rendering tasks, it is enough to save the WaitForNonStreamingPendingTasks() into a variable and check its completion in these tests.

Note: the class is internal and that is why WaitForNonStreamingPendingTasks() is also internal. I didn't mark it explicitly as internal because there are many other public methods in this class.

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Components/ChildComponentThatDelaysLoading.razor [hunk 3]
```diff
@@ -0,0 +1,13 @@
+﻿<p id="child">@childString</p>
+
+@code {
+    private string childString = "initial child";
+
+    protected override async Task OnInitializedAsync()
+    {
+        await Task.Delay(1000);
```
Comment (javiercn) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Components/ChildComponentThatDelaysLoading.razor:8]:
```suggestion 
        await Task.Yield();
```

**Review by javiercn — APPROVED** [review]
Looks great!

A small tweak to the tests, if you want to make something asynchronous, `Task.Yield()` is better than `Task.Delay()` it does the same thing and we aren't adding time to the test run (imagine this over 60 tests, it adds 1 minute to the test run, and so on).

As long as we change, the rest looks good.
