### PR TITLE
Make Blazor WASM respect current UI culture

### LINKED ISSUE #56824: Blazor WASM only relies on the current culture (current UI culture isn't respected)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is essentially a dup of the unaddressed, closed issue filed by @SQL-MisterMagoo at [Blazor WebAssembly Localization does not behave the same as Server side (dotnet/aspnetcore #25296)](https://github.com/dotnet/aspnetcore/issues/25296) and a new issue that just arrived again on the docs repo at [Can we have more details for the note, please? (dotnet/AspNetCore.Docs #33077)](https://github.com/dotnet/AspNetCore.Docs/issues/33077).

cc: @hishamco @voroninp

### Expected Behavior

It came to light several years ago via a docs issue from @SQL-MisterMagoo that resource loading is only based on the current culture in the WASM culture provider ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs#L65

Why doesn't Blazor WASM load resources for both current culture and current UI culture? I'm going to (at least temporarily) react to this with a doc update that has devs only set the current culture in Blazor WASM apps.

Chatting with @SteveSandersonMS offline, this might be a bug ...

> I think we should be loading the localization resources for CurrentUICulture (and possibly also CurrentCulture if that’s needed to make formatting/parsing work correctly). Whereas like you point out, we only load for CurrentCulture.

The original issue was backlogged for work but closed without work by @SQL-MisterMagoo.

### Steps To Reproduce

From the report of @SQL-MisterMagoo, one can follow our [Statically set the client-side culture](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0#statically-set-the-client-side-culture) guidance using a different culture for current culture and current UI culture and with the [client-side localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0#client-side-localization) guidance for a culture that matches the current UI culture.

I've placed a repro app at ...

https://github.com/guardrex/Blazor-WASM-Loc-PU-Issue-56824

1. The app configures the current culture and current UI culture to US English (`en-us`). Run the app and see the correct globalization and localization in the `CultureExample1` and `CultureExample2` components.
2. In `Program.cs`, change the current UI culture to Spanish (`es-es`). `CultureExample1` globalizes correctly to English, but `CultureExample2` doesn't localize to Spanish.
3. Change the current culture to Spanish. Now, both `CultureExample1` and `CultureExample2` globalize and localize correctly to Spanish, respectfully.

### Exceptions (if any)

None

### .NET Version

AFAIK, this is for all versions.

### Anything else?

Looks like it came in here :point_right: https://github.com/dotnet/aspnetcore/pull/20033 ... and I don't see discussion on the point of only setting current culture.

### PR DESCRIPTION
**Pull request by dariatiurina**
# Make Blazor WASM respect current UI culture

## Description

This pull request introduces support for differentiating between `CultureInfo.CurrentCulture` and `CultureInfo.CurrentUICulture` in WebAssembly applications. 

### Changes
* Updated `GetCultures` method in `WebAssemblyCultureProvider` to accept both `CultureInfo.CurrentCulture` and `CultureInfo.CurrentUICulture`, enabling separate handling of culture and UI culture. Adjusted logic to compute culture closure for both values.
* Added a new unit test in `WebAssemblyCultureProviderTest` to verify that `GetCultures` correctly computes the culture closure when both culture and UI culture are provided. 
* Added an E2E test in `WebAssemblyLocalizationTest` to validate that the application can differentiate between `CurrentCulture` and `CurrentUICulture` and display localized resources accordingly. To make this test work the changes were done to `LocalizedText.razor` and `BasicTestApp/Program.cs`.

Fixes #56824

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 1]
```diff
@@ -81,16 +81,20 @@ internal static string[] GetCultures(CultureInfo cultureInfo)
         // starting from the current culture and walking up the graph of parents.
         // At the end of the the walk, we'll have a list of culture names that look like
         // [ "fr-FR", "fr" ]
-        while (cultureInfo != null && cultureInfo != CultureInfo.InvariantCulture)
+        while (cultureInfo != null || uiCultureInfo != null)
         {
-            culturesToLoad.Add(cultureInfo.Name);
+            if (cultureInfo != null && cultureInfo != CultureInfo.InvariantCulture)
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: This is not a bad idea. Let's e.g. have:
```
private static IEnumerable<string> GetCultureHierarchy(CultureInfo? culture)
{
    while (culture != null && culture != CultureInfo.InvariantCulture)
    {
        yield return culture.Name;
        if (culture.Parent == culture)
            break;
        culture = culture.Parent;
    }
}
```

Thanks to moving the parent-extraction logic, the `GetCultures` method would just have `HashSet` creation and two simple `for` loops that would add items to the set.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 2]
```diff
@@ -72,28 +73,32 @@ public virtual async ValueTask LoadCurrentCultureResourcesAsync()
...
+                culturesToLoad.Add(uiCultureInfo.Name);
             }
 
-            cultureInfo = cultureInfo.Parent;
+            cultureInfo = (cultureInfo?.Parent == cultureInfo || cultureInfo == CultureInfo.InvariantCulture) ? null : cultureInfo?.Parent;
+            uiCultureInfo = (uiCultureInfo?.Parent == uiCultureInfo || uiCultureInfo == CultureInfo.InvariantCulture) ? null : uiCultureInfo?.Parent;
         }
 
-        return culturesToLoad.ToArray();
+        return culturesToLoad.ToList().ToArray();
```
Comment (ilonatommy) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: This is a costly operation. `culturesToLoad` is a `HashSet<string>`, calling `ToList` allocates and copies elements and then `ToArray` does it again. `HashSet` has it's own `ToArray` inherited from `IEnummerable` (you have to have `System.Linq` reference to use it).

File: src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyCultureProviderTest.cs [hunk 3]
```diff
@@ -24,6 +24,21 @@ public void GetCultures_ReturnsCultureClosure(string cultureName, string[] expec
         Assert.Equal(expected, actual);
     }
 
+    [Theory]
+    [InlineData("fr-FR", "tzm-Latn-DZ", new[] { "fr-FR", "tzm-Latn-DZ", "fr", "tzm-Latn", "tzm" })]
+    [InlineData("fr-FR", null, new[] { "fr-FR", "fr" })]
+    [InlineData(null, null, new string[0])]
+    public void GetCultures_ReturnCultureClosureWithUICulture(string cultureName, string uiCultureName, string[] expected)
```
Comment (ilonatommy) [inline src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyCultureProviderTest.cs:31]: You're using hash set, so there should be no duplicates right now but let's add test data with same culture for both args to make sure that the list has always unique elements. Or same-parent cultures if you prefer, e.g. "en-US" and "en-GB", to make sure they won't have "en" twice.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 4]
```diff
@@ -81,16 +81,20 @@ internal static string[] GetCultures(CultureInfo cultureInfo)
...
+        while (cultureInfo != null || uiCultureInfo != null)
         {
-            culturesToLoad.Add(cultureInfo.Name);
+            if (cultureInfo != null && cultureInfo != CultureInfo.InvariantCulture)
+            {
+                culturesToLoad.Add(cultureInfo.Name);
+            }
 
-            if (cultureInfo.Parent == cultureInfo)
+            if (uiCultureInfo != null && uiCultureInfo.Name != cultureInfo?.Name && uiCultureInfo != CultureInfo.InvariantCulture)
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: This would be solved by method simplification.

**Review by ilonatommy — COMMENTED** [review]
Good job! I added a few improvement ideas.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 5]
```diff
@@ -62,7 +63,7 @@ public virtual async ValueTask LoadCurrentCultureResourcesAsync()
             throw new PlatformNotSupportedException("This method is only supported in the browser.");
         }
 
-        var culturesToLoad = GetCultures(CultureInfo.CurrentCulture);
+        var culturesToLoad = GetCultures(CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture);
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:66]: In which situation do we need to handle `null` instances. `CultureInfo.CurrentCulture` is never null according to `https://learn.microsoft.com/es-es/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-10.0`. Same for `https://learn.microsoft.com/es-es/dotnet/api/system.globalization.cultureinfo.currentuiculture?view=net-10.0`.

As far as I understand, they are either InvariantCulture or a specific culture like `es-ES` that "walks" up to `InvariantCulture, so the `null` checks should be replaceable against the `InvariantCulture`.

Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:66]: In this case it would be `es-ES -> es -> Invariant`.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: You can also change the return type or keep the list and use `Contains`. Realistically this list is going to be "at most" 4 cultures. It's not going to make a difference. There's also a very cheap check which is to check CurrentUICulture != CurrentCulture and avoid processing the latter if they are the same.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 6]
```diff
@@ -3,6 +3,7 @@
 
 using System.Diagnostics.CodeAnalysis;
 using System.Globalization;
+using System.Linq;
```
Comment (pavelsavara) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:6]: Did we have `Linq` as blazor dependency before ? (it's large download)

**Review by pavelsavara — COMMENTED** [review]
Should we try to implement this for general WASM in runtime ? (not just Blazor)

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs (hunk 5 above)
Comment (dariatiurina) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:66]: I did this to check the condition in while loop. After the changes it is no longer necessary

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs (hunk 6 above)
Comment (dariatiurina) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:6]: I looked up and found imports in `LazyAssemblyLoader.cs` and in other components in Blazor, but I can rewrite the code to not use it in this file

Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs:6]: Linq is already a dependency in many other places and it's going to be on the majority of libraries/users apps, there is low ROI on trying to avoid it.

**Comment by javiercn** [comment]
> Should we try to implement this for general WASM in runtime ? (not just Blazor)

I was filing an issue to track this, but I just thought that it would "fundamentally" change the way this works. Currently you set the culture on the current thread (in managed code) before you start up the host and that triggers an async process when the host is built.

If we were to do something for wasm, it will have to be something that gets specified before any managed code runs, doesn't it? As we can't load the dlls when you change the CultureInfo.CurrentCulture for example.

**Comment by pavelsavara** [comment]
> As we can't load the dlls when you change the CultureInfo.CurrentCulture for example.

We can't load it from synchronous code, but our startup is async. 

That said, runtime already detects browser culture and sets it to managed during startup. 
During runtime startup we could load proper satellite assemblies and set UI culture too.
I think we just don't do it yet.

Does Blazor trigger `LoadCurrentCultureResourcesAsync` even later than during startup ? 
Is there public API for it ?

File: src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyCultureProviderTest.cs [hunk 7]
```diff
@@ -24,6 +24,22 @@ public void GetCultures_ReturnsCultureClosure(string cultureName, string[] expec
         Assert.Equal(expected, actual);
     }
 
+    [Theory]
+    [InlineData("fr-FR", "tzm-Latn-DZ", new[] { "fr-FR", "fr", "tzm-Latn-DZ", "tzm-Latn", "tzm" })]
+    [InlineData("en-US", "en-GB", new[] { "en-US", "en", "en-GB" })]
+    [InlineData("fr-FR", null, new[] { "fr-FR", "fr" })]
+    [InlineData(null, null, new string[0])]
```
Comment (ilonatommy) [inline src/Components/WebAssembly/WebAssembly/test/Hosting/WebAssemblyCultureProviderTest.cs]: After the last commit, double `null` `InlineData` can be removed, `cultureInfo` cannot be null:
`internal static string[] GetCultures(CultureInfo cultureInfo, CultureInfo? uiCultureInfo = null)`

**Review by ilonatommy — APPROVED** [review]
Good job! The failures do not look related but also, they have not failed before your PR. I triggered a rerun. If you want to look into them to asses it yourself, that's the build link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1109517&view=ms.vss-test-web.build-test-results-tab&runId=30444950&resultId=114098&paneView=history

**Comment by ilonatommy** [comment]
> That said, runtime already detects browser culture and sets it to managed during startup. 

I don't think we are reading any managed info on runtime startup. We are checking 2 things:
- user preference passed to the startup config (`withApplicationCulture`)
- if not specified, checking the browser settings.

https://github.com/dotnet/runtime/blob/ac764af3e2d77aa582dff3511295ee701b831a7d/src/mono/browser/runtime/loader/icu.ts#L48

**Comment by javiercn** [comment]
> > As we can't load the dlls when you change the CultureInfo.CurrentCulture for example.
> 
> We can't load it from synchronous code, but our startup is async.
> 
> That said, runtime already detects browser culture and sets it to managed during startup. During runtime startup we could load proper satellite assemblies and set UI culture too. I think we just don't do it yet.
> 
> Does Blazor trigger `LoadCurrentCultureResourcesAsync` even later than during startup ? Is there public API for it ?

I'm not sure how much it will buy us through. The issue stands that a user can do `CultureInfo.CurrentCulture = "my-culture"` before the host starts and the right cultures/assemblies get loaded when the webassembly host starts.

Note that it's not enough to load the culture from the browser. Apps should be able to override that with values from cookies or any other source.

If we try to do it automatically, we run the risk of downloading unnecessary assemblies when the app developer sets the culture to a different value. That said, I don't think it would be a big deal, so if longer term we also want to do it on the runtime, that would be ok. I just question how much that buys us considering we need to keep the current functionality working.

**Comment by pavelsavara** [comment]
> I don't think we are reading any managed info on runtime startup. We are checking 2 things:

We are not reading it, but we are setting it. The env variable will influence Mono and managed too AFAIK

https://github.com/dotnet/runtime/blob/abc4c652eca9e02c4ff5d4dac0ceb58a4a15b8e3/src/mono/browser/runtime/loader/config.ts#L222

I don't know if this would also set UI culture

**Comment by ilonatommy** [comment]
> > I don't think we are reading any managed info on runtime startup. We are checking 2 things:
> 
> We are not reading it, but we are setting it. The env variable will influence Mono and managed too AFAIK
> 
> https://github.com/dotnet/runtime/blob/abc4c652eca9e02c4ff5d4dac0ceb58a4a15b8e3/src/mono/browser/runtime/loader/config.ts#L222

I already forgot how it was, I am checking now and that `LANG` is used only for console encoding:

https://github.com/dotnet/runtime/blob/abc4c652eca9e02c4ff5d4dac0ceb58a4a15b8e3/src/libraries/Common/src/System/Text/EncodingHelper.Unix.cs#L29

The culture flow is rather:
- start runtime,
- check if config does not set invariant mode,
- if not, check if user set any preference with `withApplicationCulture`,
- if not, check the browser's culture
- load the shared based on this info.

I don't see a feedback loop runtime -> managed, beyond env variables about globalization mode:
https://github.com/dotnet/runtime/blob/abc4c652eca9e02c4ff5d4dac0ceb58a4a15b8e3/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.cs#L15

**Comment by pavelsavara** [comment]
We are not running this test because we don't have remote executor

https://github.com/dotnet/runtime/blob/abc4c652eca9e02c4ff5d4dac0ceb58a4a15b8e3/src/libraries/System.Runtime/tests/System.Globalization.Tests/CultureInfo/CultureInfoCurrentCulture.cs#L122-L145

But I think this is the functionality we should be striving for. I think this is not just for console

**Comment by guardrex** [comment]
I created an RC1 doc tracking issue for this ...

**[RC1] Blazor WASM respects the current UI culture**
https://github.com/dotnet/AspNetCore.Docs/issues/35872
