### PR TITLE
Wait for Request to finish

### LINKED ISSUE #40498: ANCM intermittently notifies the wrong HttpContext of disconnect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are observing an intermittent issue in a local development environment (using IIS Express) whereby ANCM appears to be notifying the wrong HttpContext of a disconnect.

The behaviour we observe is as follows:

For a "normal" (successful) request (made by a Blazor application running under Edge), we see the following sequence in the logs for a CORS pre-flight OPTIONS request followed by a POST:

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 OPTIONS https://localhost:44302/...
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '...'
[...]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 OPTIONS https://localhost:44302 ...
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Debug: Connection ID "5908722738490511504" disconnecting.

Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 POST  https://localhost:44302/...
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path  '...'
[...]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 POST https://localhost:44302/...
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Debug: Connection ID "1585267091919867554" disconnecting.

```
For a request that fails, we see the following sequence, with the "Connection ID ... disconnecting" message appearing *after* the second (POST) request starts:

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 OPTIONS https://localhost:44302/...
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '...'
[...]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 OPTIONS https://localhost:44302/...

Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 POST https://localhost:44302/...
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Debug: Connection ID "10520408744032996894" disconnecting.
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/DistanceService.svc'
[...]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 POST https://localhost:44302/
```

Additionally, for a request that fails we observe the following behaviour:

- Adding a custom middleware to log ```HttpContext.RequestAborted.IsCancellationRequested``` shows that the POST request appears to be disconnected from the very start of request processing.
- For terminal middleware that does _not_ check RequestAborted, the browser receives a response that has the correct headers but no body (presumably since ```IISHttpContext.AbortIO``` has called ```.Complete()``` on the body output pipe). This can be observed both in the IIS FRT logs, and also in the browser dev tools.
- For terminal middleware that does check ```RequestAborted```, the browser receives a response with whatever response was generated up until that point (e.g. typically a 200 but with no body and only the default response headers set). Again, observed in both IIS FRT logs and browser dev tools.
- IIS Failed Request Tracing logs show that the ```ANCM_INPROC_REQUEST_DISCONNECT``` event for both requests only happened _after_ normal processing (i.e. immediately after the ```GENERAL_FLUSH_RESPONSE_END``` event), i.e. there is no evidence in the FRT log that the browser disconnected early, or that the second (POST) request should be showing as aborted when checking ```RequestAborted.IsCancellationRequested```.

Our entire middleware pipeline is _very_ simple, and is currently just returning mock data and as such does not even use any asynchronous APIs other than for HTTP IO (i.e. reading the request body and writing the response body). We are _not_ using any multithreading outside of what is provided by ASP.NET, i.e. we are not using ```Task.Run()``` or any other API that could be introducing concurrency issues, nor are we doing anything unusual which could explain this issue (such as allowing a ```HttpContext``` or other request scoped object to outlive its normal scope). Additionally, the logs (as above) show that the "Connection ID ... disconnecting" message appears before routing has even occurred, i.e. before the request has reached any custom middleware.

Note that the issue is _very_ intermittent, but we have observed it on at least four different development machines. For one developer it sometimes happens several times per day during the course of normal development/testing/debugging, but for others it very rarely happens (less than once per week under the same conditions).

### Expected Behavior

HttpContext.RequestAborted.IsCancellationRequested should not return true if the browser is able to receive a reponse.

### Steps To Reproduce

We are unable to consistently reproduce this issue. However, we can provide detailed logs (e.g. IIS Failed Request Trace logs, VS debug output, etc) that clearly demonstrates the issue occurring.

### Exceptions (if any)

No exceptions are logged.

### .NET Version

6.0.200

### Anything else?

- ASP.NET Core 6.0.2
- VS 2022 17.1.0
- Windows 10 Pro 10.0.19043
- aspnetcorev2.dll 16.0.21322.1
- iisexpress.exe 10.0.22489.1000
- Microsoft Edge 98.0.1108.62
- dotnet --info: https://github.com/dotnet/aspnetcore/files/8168912/dotnetinfo.txt

We can provide detailed IIS Failed Request Trace logs and debugging output from VS if required.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/40498

<h2>The problem</h2>

IIS can detect a request disconnection and calls our `NotifyDisconnect` method which will notify our managed code which aborts the managed side of the request
https://github.com/dotnet/aspnetcore/blob/e67e77d85e74c94fd72a942b3b8e77c74c228cd6/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp#L116
https://github.com/dotnet/aspnetcore/blob/e67e77d85e74c94fd72a942b3b8e77c74c228cd6/src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs#L226

At the same time the request could be completing because it finished writing a response in which case it will tell native code
https://github.com/dotnet/aspnetcore/blob/1dd6f451a0df2ee8e4575dd8dca9df77fda129b1/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp#L121
and free the GCHandle pointing at the managed IISHttpContext
https://github.com/dotnet/aspnetcore/blob/e67e77d85e74c94fd72a942b3b8e77c74c228cd6/src/Servers/IIS/IIS/src/Core/IISHttpContext.cs#L801-L821

The problem is that once a `GCHandle` has been freed, the next `GCHandle` allocated can point to the same address. What this means is that if native code is still running and pointing at a `GCHandle` that has been freed and re-allocated, the native code will now be operating on a different object. In the original issue the `GCHandle` was replaced by the next request and `NotifyDisconnect` is still running and will end up aborting the next request.

<h2>The fix</h2>

The proposed fix blocks the managed->native call that tells the native side that the request completed **if** the native side is already attempting to abort the request.

Blocking this call means that the managed side will not free the `GCHandle` until we know the native side is done using the managed request object, preventing the `GCHandle` from pointing to a new request while the native side is still using it.

Blocking **does not** occur if the managed->native call happens first, because it nulls out the managed pointer which prevents any future `NotifyDisconnect` calls from doing anything. And it avoids running the blocking code via the `m_disconnectFired` bool being false.

The potential deadlock described at the top of `NotifyDisconnect` is still avoided because we _didn't_ change the disconnect handler callback to run in a lock.

<h2>The testing</h2>

We haven't reproduced this issue ourselves, so it's mostly an educated guess that we fixed the issue. I will be trying to force the issue to occur by using thread freezing in the debugger and make sure the fix behaves as intended. Since it's a race we generally can't write a targeted unit/functional test to verify the fix, and we rely on other tests to make sure we don't regress anything.

@antmjones would it be possible for you to test the fix since you've been able to reproduce the issue multiple times?

### CODE REVIEW

**Comment by antmjones** [comment]
@BrennanConroy, thanks for that. I'll have a careful read through your comment (and my notes on #40498), and also try to see if I can get my old test case up and running.

FWIW, looking back it looks like the way I finally managed to reproduce this consistently was by adding a sleep into `IN_PROCESS_HANDLER::NotifyDisconnect()` after exiting `m_srwDisconnectLock` but before calling `m_pDisconnectHandler`:

<pre>
    void* pManagedHttpContext = nullptr;
    {
        SRWExclusiveLock lock(m_srwDisconnectLock);

       // ...
        
        pManagedHttpContext = m_pManagedHttpContext;
        m_disconnectFired = true;
    }

    <b>std::this_thread::sleep_for(std::chrono::milliseconds(50));</b>

    if (pManagedHttpContext != nullptr)
    {
        m_pDisconnectHandler(pManagedHttpContext);
    }
</pre>

Apologies for not mentioning this on the original issue, I think I wrote all the comments before I thought to try adding the sleep! It may well be that even with the sleep in there the race condition isn't hit every time of course.

**Comment by antmjones** [comment]
@BrennanConroy, I've had another read through the code and also your commit, and your logic makes perfect sense to me. I'll try to get my test case up and running, I most likely won't get time to do this until next week though.

**Review by mgravell — COMMENTED** [review]
looks compelling, but I don't feel qualified to opine on the code part... ¯\_(ツ)_/¯

File: src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp [hunk 1]
```diff
@@ -122,11 +129,27 @@ IN_PROCESS_HANDLER::IndicateManagedRequestComplete(
...
+        disconnectFired = m_disconnectFired;
+    }
+
+    if (disconnectFired)
+    {
+        // Block until we know NotifyDisconnect completed
+        // this is because the caller of IndicateManagedRequestComplete will dispose the
+        // GCHandle pointing at m_pManagedHttpContext, and a new GCHandle could use the same address
+        // for the next request, this could cause an in-progress NotifyDisconnect call to disconnect the new request
+        std::unique_lock<std::mutex> lock(m_lockQueue);
```
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp:146]: Any reason for this being a `unique_lock` rather than, say, a `lock_guard`?

Comment (adityamandaleeka) [reply src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp:146]: Ah, nvm, I see it's required for the `conditional_variable` wait.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
Looks good. I'd love to hear back from @antmjones on how this fix works out for their scenario before we merge.

File: src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp [hunk 2]
```diff
@@ -114,6 +115,12 @@ IN_PROCESS_HANDLER::NotifyDisconnect()
     if (pManagedHttpContext != nullptr)
     {
         m_pDisconnectHandler(pManagedHttpContext);
+        // lock before notifying, this prevents the condition where m_queueNotified is already checked but
+        // the condition_variable isn't waiting yet, which would cause notify_all to NOOP and block
+        // IndicateManagedRequestComplete until a spurious wakeup
+        std::unique_lock<std::mutex> lock(m_lockQueue);
+        m_queueNotified = true;
+        m_queueCheck.notify_all();
```
Comment (halter73) [inline src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp:123]:
```suggestion
        m_lockQueue.unlock();
        m_queueCheck.notify_all();
```

Nit: Is it better to unlock, or is the msvc runtime smart enough to avoid waking another thread too early here?

**Review by halter73 — APPROVED** [review]

File: src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp (hunk 2 above)
Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp:123]: Looks like we should also be using a `std::lock_guard` here since we only need a `std::unique_lock` for the `std::condition_variable`

**Comment by adityamandaleeka** [comment]
@antmjones, do you think you'll be able to give this a try soon?

**Comment by adityamandaleeka** [comment]
@BrennanConroy let's get this in for Preview 3?

**Comment by recumbented** [comment]
I have a [issue](https://github.com/dotnet/aspnetcore/issues/51121) that managed thread blocked at `Microsoft.AspNetCore.Server.IIS.dll!Microsoft.AspNetCore.Server.IIS.NativeMethods.http_set_completion_status`  keep growing when many concurrent cancelled/aborted requests incoming.
This issue is caused only .NET 8 and running in IIS InProcess hosting model.
Does anyone have any idea of the cause?
