### PR TITLE
Fix Virtualize scroll container detection with horizontal overflow

### LINKED ISSUE #58200: Blazor Virtualize: root-level scrolling breaks on horizontal scroll enabled in the container
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When placing the Virtualize into a horizontally scrollable container it breaks and only ever shows the top 1000 rows if we hide the container y axis scroller that appears on the component. By design the whole page should be scrollable and a second vertical scroller shouldn't be added but it is and it makes the page look weird. If we hide it then the Virtualize component breaks as described, leaving it on and having two scrollers appear on the page makes for bad UX though so that is not an option for us.

The horizontal scrolling is needed here because there are enough simulated columns that do not fit in one screen width and that is what is our use case that the customer wants to have in the application.

### Expected Behavior

The Virtualize component shows new items on scrolling to the end of the visible list of items, only one scrollbar is shown on the whole page.

### Steps To Reproduce

1. create a new project in Blazor WASM `dotnet new blazorwasm`
2. add the following page to the Pages folder
```
@page "/virtualized-table"

<PageTitle>Virtualized Table</PageTitle>

<HeadContent>
    <style>
        html, body {
            overflow-y: scroll
        }
    </style>
</HeadContent>

<h1>Virtualized Table Example</h1>

<button @onclick="LoadData">New data</button>

<div style="position: relative; overflow-x:auto; overflow-y: hidden;">
    <table id="virtualized-table"
           style="width: 100%; table-layout: auto; text-align: left; font-size: 0.75rem; line-height: 1.25rem;">
        <thead style="position: sticky; top: 0; background-color: silver">
            <tr>
                <th>Item</th>
                @for (var i = 0; i < 20; i++)
                {
                    <th style="text-wrap: nowrap">Another column</th>
                }
            </tr>
        </thead>
        <tbody style="@(isLoading ? "opacity: 0.75" : "")">
            <Virtualize Items="fixedItems" ItemSize="30" SpacerElement="tr">
                <tr @key="context" style="height: 30px;" id="row-@context">
                    <td>Item @context</td>
                    <td>Another value</td>
                </tr>
            </Virtualize>
        </tbody>
    </table>
</div>

@code {
    private List<Guid> fixedItems = new List<Guid>();
    private bool isLoading = false;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (firstRender)
        {
            await LoadData();
        }
    }

    private async Task LoadData()
    {
        isLoading = true;

        await InvokeAsync(StateHasChanged);

        // simulate long fetch from server
        await Task.Delay(3000);
        var maxRange = Math.Min(new Random().Next(), 10000);
        fixedItems = Enumerable.Range(0, maxRange).Select(item => Guid.NewGuid()).ToList();
        isLoading = false;

        await InvokeAsync(StateHasChanged);
    }
}
```

### Exceptions (if any)

_No response_

### .NET Version

8.0.400

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ilonatommy**
`findClosestScrollContainer()` incorrectly selected elements with `overflow-x` set to a non-visible value as the vertical scroll root.
 Per the CSS spec, setting `overflow-x` to a non-visible value promotes `overflow-y` from 'visible' to 'auto', causing the heuristic to pick containers that don't actually scroll vertically.

## Description

The fix adds a check that the candidate element can actually scroll vertically (`scrollHeight > clientHeight`) or has overflow-y explicitly set to 'scroll' before selecting it as the scroll container.

Proposal https://github.com/dotnet/aspnetcore/issues/58200#issuecomment-3563363304 works the issue around and can be used until this fix gets in.

Fixes #58200

### CODE REVIEW

File: src/Components/Web.JS/src/Virtualize.ts [hunk 1]
```diff
@@ -22,7 +22,9 @@ function findClosestScrollContainer(element: HTMLElement | null): HTMLElement |
   const style = getComputedStyle(element);
 
   if (style.overflowY !== 'visible') {
-    return element;
+    if (element.scrollHeight > element.clientHeight || style.overflowY === 'scroll') {
```
Comment (oroztocil) [inline src/Components/Web.JS/src/Virtualize.ts]: Is there an edge case that is not covered? If you have a container with `overflow-x: auto, overflow-y: hidden`, and a fixed height (e.g., 400px), the content inside is taller than the container, so `scrollHeight > clientHeight` is true. Even with the fix we would pick this container as the scroll root. But `overflow-y: hidden` means the user can't actually scroll it, so virtualization would still be broken in that scenario. 

This isn't a regression, though. The old code also picked this element because its
computed `overflowY` was `hidden`, which isn't `visible`. A stronger fix could also exclude
`hidden` and `clip` values since those never allow user scrolling:

```ts
if (style.overflowY !== 'visible') {
    const canScroll = style.overflowY !== 'hidden' && style.overflowY !== 'clip';
    if (canScroll && (element.scrollHeight > element.clientHeight || style.overflowY === 'scroll')) {
        return element;
    }
}
```

Feel free to not handle this case in this PR.

Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: True, I was focused on the reported case. I am not sure how much real-life is your example. Why to use virtualization when we don't intend to scroll? That looks like a not supported scenario.

Comment (oroztocil) [reply src/Components/Web.JS/src/Virtualize.ts]: To clarify the concern: it was not about someone intentionally using Virtualize with `overflow-y: hidden`, it's that `findClosestScrollContainer` walks ancestors and could encounter an intermediate `<div>` with that style. The current code looks good.

**Review by oroztocil — APPROVED** [review]
