### PR TITLE
More thorough support for retrieving OpenAPI routes in a case-sensitive manner

### LINKED ISSUE #59175: OpenAPI document names are case-sensitive in urls
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I included several different openapi documents via .AddOpenApi("myDoc"). The document name contains upper- and lowercase letters. Later on I want to retrieve my document via /openapi/mydoc.json but I get a 404. After looking into it I found out that this should come from the fact that we're using keyed services:

```csharp
        return endpoints.MapGet(pattern, async (HttpContext context, string documentName = OpenApiConstants.DefaultDocumentName) =>
            {
                // It would be ideal to use the `HttpResponseStreamWriter` to
                // asynchronously write to the response stream here but Microsoft.OpenApi
                // does not yet support async APIs on their writers.
                // See https://github.com/microsoft/OpenAPI.NET/issues/421 for more info.
                var documentService = context.RequestServices.GetKeyedService<OpenApiDocumentService>(documentName);
                if (documentService is null)
                {
                    context.Response.StatusCode = StatusCodes.Status404NotFound;
                    context.Response.ContentType = "text/plain;charset=utf-8";
                    await context.Response.WriteAsync($"No OpenAPI document with the name '{documentName}' was found.");
                }
```

Keyed services seem to be case sensitive. I can resolve this issue by lowercasing everything but this is counter-intuitive for me because the rest of aspnetcore does not use case sensitive routing AFAIK. 

### Expected Behavior

I expect the url for the openapi documents to be case insensitive, so I can receive my document regardless of the casing I use.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sander1095**
# More thorough support for retrieving OpenAPI routes in a case-sensitive manner

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

This PR fixes some oversights from #59199 around retrieving OpenAPI documents case-insensitively.

## Description

This PR modifies missed files from #59199 that use the registered document name as a key for retrieving services or options. This needs to be done case-insensitively to:

- Ensure documents can be retrieved correctly
  - Trying to retrieve services around OpenAPI documents that are registered with a differently cased document name, will result in an exception, which is not desired!
- Ensure documents are generated and retrieved with the correct OpenAPI version
  - If the configuration options are retrieved with an incorrectly cased document name argument, a default instance of `OpenApiOptions` is returned, which might contain different settings than what the user had configured.

This PR also adds some more comments and improves existing ones based on the previous PR around case-insensitive OpenAPI document names.

Fixes #59175

### CODE REVIEW

File: src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs [hunk 1]
```diff
@@ -50,7 +50,7 @@ public static IEndpointConventionBuilder MapOpenApi(this IEndpointRouteBuilder e
                 else
                 {
                     var document = await documentService.GetOpenApiDocumentAsync(context.RequestServices, context.RequestAborted);
-                    var documentOptions = options.Get(documentName);
+                    var documentOptions = options.Get(lowercasedDocumentName);
```
Comment (martincostello) [inline src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:53]: Is there a test that can updated that would fail before your change and pass afterwards?

Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:53]: I can't really find a way to write a test for this. Looking at the source code, if the options can't find a value, it will add it instead. As this is an integration test, I don't have access to the instances and can't mock or verify method calls.

Comment (martincostello) [reply src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:53]: Would an HTTP request to a test server hosting an OpenAPI endpoint find the bug you're fixing?

Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:53]: Never mind, I found a way! Working on it now..

Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:53]: @martincostello I've added the test. Feel free to review. For now, I'll resolve this conversation as the test has been added.

**Review by captainsafia — CHANGES_REQUESTED** [review]
Thanks for catching this and following up with a PR!

This has got me thinking that we should audit other places where we pass in documentName in the same way. As a result, it looks like we'll also want to make a change in `OpenApiDocumentProvider`. The same test around the API version should work here.

**Comment by sander1095** [comment]
@captainsafia I've implemented your requested changes, added extra comments, improved existing ones and updated the title and description of PR to better reflect the changes.

Let me know if you want me to do anything else! :)

File: src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs [hunk 2]
```diff
@@ -106,6 +105,9 @@ public static IServiceCollection AddOpenApi(this IServiceCollection services, Ac
     public static IServiceCollection AddOpenApi(this IServiceCollection services)
         => services.AddOpenApi(OpenApiConstants.DefaultDocumentName);
 
+    /// <param name="services">The <see cref="IServiceCollection"/> to register services onto.</param>
```
Comment (captainsafia) [inline src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs:108]: We can remove the docstrings on private methods.

File: src/OpenApi/src/Services/OpenApiDocumentProvider.cs [hunk 3]
```diff
@@ -25,10 +25,17 @@ internal sealed class OpenApiDocumentProvider(IServiceProvider serviceProvider)
     /// <param name="writer">A text writer associated with the document to write to.</param>
     public async Task GenerateAsync(string documentName, TextWriter writer)
     {
+        // We need to retrieve the document name in a case-insensitive manner to support case-insensitive document name resolution.
```
Comment (captainsafia) [inline src/OpenApi/src/Services/OpenApiDocumentProvider.cs:28]: I think we can just reference the comment in the `IServiceCollection` extensions file instead of duplicating the content here.

File: src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Services/OpenApiDocumentProviderTests.cs [hunk 4]
```diff
@@ -30,6 +31,56 @@ public async Task GenerateAsync_ReturnsDocument()
...
+        // Assert
+
+        // If the Document Service is retrieved with a non-existent (case-sensitive) key, it would throw:
+        // https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderkeyedserviceextensions.getrequiredkeyedservice?view=net-9.0-pp
+
+        // In this test's case, we're testing that the document service is retrieved with a case-insensitive key.
+        // It's registered as "casesensitive" but we're passing in "CaseSensitive", which doesn't exist.
+        // Therefore, if the test doesn't throw, we know it has passed correctly.
+        // We still do a small check to validate the document, just in case. But the main test is that it doesn't throw.
+        ValidateOpenApiDocument(stringWriter, _ => { });
```
Comment (captainsafia) [inline src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Services/OpenApiDocumentProviderTests.cs:81]: Nit: Add an assertion here to validate the OpenAPI version as above?

**Comment by sander1095** [comment]
Thanks for the review! I'll implement requested changes after my holiday (in ~2 weeks)

File: src/OpenApi/src/Services/OpenApiDocumentProvider.cs (hunk 3 above)
Comment (sander1095) [reply src/OpenApi/src/Services/OpenApiDocumentProvider.cs:28]: Done

File: src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs (hunk 2 above)
Comment (sander1095) [reply src/OpenApi/src/Extensions/OpenApiServiceCollectionExtensions.cs:108]: Done

File: src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Services/OpenApiDocumentProviderTests.cs (hunk 4 above)
Comment (sander1095) [reply src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Services/OpenApiDocumentProviderTests.cs:82]: Done

**Comment by sander1095** [comment]
@captainsafia I've processed the PR comments!

**Review by captainsafia — APPROVED** [review]
