### PR TITLE
Don't always create log for Response in HttpLoggingMiddleware

### LINKED ISSUE #40427: HttpLoggingMiddleware logs an "empty" message for Response when disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`HttpLoggingMiddleware` logs an "empty" message for the response when `options.LoggingFields == HttpLoggingFields.None`. Specifically, I end up with a bunch of messages that simply say:

> Response:

Which comes from `HttpResponseLog.ToString`
https://github.com/dotnet/aspnetcore/blob/bc1fed99372d9c3d7389e9c44a8974cba00689f3/src/Middleware/HttpLogging/src/HttpResponseLog.cs#L41

By way of `LogResponseHeaders`: https://github.com/dotnet/aspnetcore/blob/bc1fed99372d9c3d7389e9c44a8974cba00689f3/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L217

Unlike the request-based properties at the start of the Middleware, this method doesn't check whether or not *everything* is disabled before executing. It then calls the `ResponseLog` method with an empty `HttpResponseLog` container.

This isn't necessarily limited to the `None` case. If you select options that would otherwise exclude the response headers you'll end up with similar behavior. 

### Expected Behavior

If `options.LoggingFields` is set to `HttpLoggingFields.None` then **no message** should be emitted to the logger.

I think this would need to be checked in the Middleware itself,  as by the time it reaches `HttpRequestLog.ToString` it would be too late. It'd either need to be within the `LogResponseHeaders` method or part of this guard:
https://github.com/dotnet/aspnetcore/blob/bc1fed99372d9c3d7389e9c44a8974cba00689f3/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L162

### Steps To Reproduce

In `ConfigureServices`, set up the `HttpLoggingOptions` so that `LoggingFields`  is set to `None`:

```csharp
services.Configure<HttpLoggingOptions>(
   o => o.LoggingFields = HttpLoggingFields.None
):
```

Add the Middleware in `Configure`:

```csharp
app.UseHttpLogging();
```

Make a request and observe the "empty" message:

> Response:

Note: this is the minimal configuration necessary to reproduce. Obviously you'd not even add the Middleware if this was the final state. See below. 

### Exceptions (if any)

_No response_

### .NET Version

NET6.0 

### Anything else?

We enable/disable this Middleware via configuration and a custom `IConfigureOptions<>` implementation. The majority of the time it is left disabled. We conditionally enable it when necessary (without a restart), making use of the fact that the Middleware leverages `IOptionsMonitor<>`. Unfortunately in its disabled state its still triggering this log entry on every request.

I'm currently side stepping this behavior with a custom Serilog filter that itself uses the same Options Monitor. It has to check the SourceContext (the Category) of every message and filter it out if the current options are set to `None`. This is quite heavy handed as you need to do a bunch of pattern matching to pull out the value from Serilog's property collection.

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes https://github.com/dotnet/aspnetcore/issues/40427

Stops us from logging an empty event when response status code/headers are not enabled in HttpLoggingMiddleware:

```
  "Message": "Response:\r\n",
  "State": {
    "Message": "Response:\r\n"
  }
```

After this change, no event is fired for `HttpLoggingMiddleware` when `HttpLoggingFields.None` is selected

### CODE REVIEW

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs [hunk 1]
```diff
@@ -86,6 +86,7 @@ public async Task NoopWhenLoggingDisabled()
         Assert.DoesNotContain(TestSink.Writes, w => w.Message.Contains("Connection: keep-alive"));
         Assert.DoesNotContain(TestSink.Writes, w => w.Message.Contains("Body: test"));
         Assert.DoesNotContain(TestSink.Writes, w => w.Message.Contains("StatusCode: 200"));
+        Assert.DoesNotContain(TestSink.Writes, w => w.Message.Contains("Response:"));
```
Comment (halter73) [inline src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:89]: Can we just assert there are no logs with the `Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware` category name?

Comment (wtgodbe) [reply src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs]: Done

**Review by BrennanConroy — APPROVED** [review]
Only objection is we could lazily allocate the `List<T>`

**Review by Tratcher — APPROVED** [review]
