### PR TITLE
Include project file in F# Worker Service template

### LINKED ISSUE #25158: FSharp worker template is missing project file
### Describe the bug

The FSharp worker template doesn't contain an `.fsproj` file

### To Reproduce
```cmd
dotnet new worker -lang f# -o fsharpworker
```
```
tree  /f
C:\SOURCE\TEMP\FSHARPWORKER
│   appsettings.Development.json
│   appsettings.json
│   Program.fs
│   Worker.fs
│
└───Properties
        launchSettings.json
```

### Exceptions (if any)

```
The template "Worker Service" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on fsharpworker\Company.Application1.fsproj...
MSBUILD : error MSB1009: Project file does not exist.
Switch: fsharpworker\Company.Application1.fsproj
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20421.11
 Commit:    c97f437b19

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20190
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20421.11\

Host (useful for support):
  Version: 5.0.0-rc.1.20417.14
  Commit:  907f7da59b

.NET SDKs installed:
  5.0.100-rc.1.20421.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.1.20420.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20417.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20420.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by dougbu**
- add test of this project template

# Description

We discovered the Worker Service template for F# lacks a `*.fsproj` file in the Microsoft.DotNet.Web.ProjectTemplates package. The file existed in this repo since a722c4cd7a3a1ed7ea8f10727d1cf802753b0e2d but was not included when building our project templates.

Though this was discovered internally, a customer noticed the problem a couple of days ago and reported it in #25158.

# Customer Impact

As-is, created "projects" are not complete. Customers wishing to use the F# Worker Service template must craft the `*.fsproj` file themselves.

# Regression?

No. Appears the problem existed since the template was added in early July.

# Risk

Very very low. The fix is a one-liner to add the missing `*.fsproj.in` template file to the Microsoft.DotNet.Web.ProjectTemplates.csproj. That results in the creating and packing the `*.fsproj` file into the package.

Also added a test confirming the project works as expected.

# Examples
``` text
> dotnet new --list
Templates                                         Short Name               Language          Tags
--------------------------------------------      -------------------      ------------      ----------------------
Console Application                               console                  [C#], F#, VB      Common/Console
Class library                                     classlib                 [C#], F#, VB      Common/Library
WPF Application                                   wpf                      [C#], VB          Common/WPF
WPF Class library                                 wpflib                   [C#], VB          Common/WPF
WPF Custom Control Library                        wpfcustomcontrollib      [C#], VB          Common/WPF
WPF User Control Library                          wpfusercontrollib        [C#], VB          Common/WPF
Windows Forms (WinForms) Application              winforms                 [C#], VB          Common/WinForms
Windows Forms (WinForms) Class library            winformslib              [C#], VB          Common/WinForms
Worker Service                                    worker                   [C#], F#          Common/Worker/Web
...
```

``` text
> dotnet new worker --language f#
The template "Worker Service" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\dd\dnx\aspnetcore\Company.Application1.fsproj...
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\dd\dnx\aspnetcore\Company.Application1.fsproj
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

### CODE REVIEW

**Comment by dougbu** [comment]
Separated from #24983.

**Comment by dougbu** [comment]
I'm not very optimistic about new test.

Apparently the F# project templates have been problematic. A number of issues (e.g. #14022) are marked as fixed but the tests all short-circuit before building generated F# projects. Hopefully they should have been re-enabled and this new one will be reliable&hellip;

**Comment by dougbu** [comment]
@cartermp @pranavkm @Pilchie this template has been broken for a while at least. But, is it important to get fix into RC1 anyhow❔

File: src/ProjectTemplates/test/WorkerTemplateTest.cs [hunk 1]
```diff
@@ -21,13 +21,18 @@ public WorkerTemplateTest(ProjectFactoryFixture projectFactory, ITestOutputHelpe
         public ProjectFactoryFixture ProjectFactory { get; }
         public ITestOutputHelper Output { get; }
 
-        [ConditionalFact]
+        [ConditionalTheory]
         [OSSkipCondition(OperatingSystems.Linux, SkipReason = "https://github.com/dotnet/sdk/issues/12831")]
-        public async Task WorkerTemplateAsync()
+        [TheoryData("C#")]
```
Comment (cartermp) [inline src/ProjectTemplates/test/WorkerTemplateTest.cs:26]: InlineData doesn't work here?

**Review by cartermp — COMMENTED** [review]
Can't say I'm qualified for the test changes but the project template inclusion looks right

File: src/ProjectTemplates/test/WorkerTemplateTest.cs (hunk 1 above)
Comment (dougbu) [reply src/ProjectTemplates/test/WorkerTemplateTest.cs:26]: Yes, it works. I just did the wrong thing. Will fix it tomorrow&hellip;

File: src/ProjectTemplates/test/WorkerTemplateTest.cs [hunk 2]
```diff
@@ -21,13 +21,18 @@ public WorkerTemplateTest(ProjectFactoryFixture projectFactory, ITestOutputHelpe
...
+        [TheoryData("F#")]
```
Comment (dougbu) [inline src/ProjectTemplates/test/WorkerTemplateTest.cs:27]:
```suggestion
        [InlineData("C#")]
        [InlineData("F#")]
```

File: src/ProjectTemplates/test/WorkerTemplateTest.cs [hunk 3]
```diff
@@ -21,13 +21,18 @@ public WorkerTemplateTest(ProjectFactoryFixture projectFactory, ITestOutputHelpe
...
+        [Repeat]
+        public async Task WorkerTemplateAsync(string language)
         {
-            Project = await ProjectFactory.GetOrCreateProject("worker", Output);
+            Project = await ProjectFactory.GetOrCreateProject(
+                $"worker-{ language.ToLowerInvariant()[0] }sharp",
+                Output);
 
-            var createResult = await Project.RunDotNetNewAsync("worker");
+            var createResult = await Project.RunDotNetNewAsync("worker", language: language);
```
Comment (pranavkm) [inline src/ProjectTemplates/test/WorkerTemplateTest.cs:35]: I recall the F# MVC templates do not completely run because of issues we ran into with the F# compiler. Nice that it works, but just something to be aware of

**Review by pranavkm — APPROVED** [review]
Did you mean to target 5.0?

File: src/ProjectTemplates/test/WorkerTemplateTest.cs (hunk 3 above)
Comment (cartermp) [reply src/ProjectTemplates/test/WorkerTemplateTest.cs:35]: Which issues? Happy to investigate

**Comment by dougbu** [comment]
> Did you mean to target 5.0?

Not unless you, @cartermp or @Pilchie think this needs to be done before 6.0. It's a long-standing bug. Was it ever reported❔

> I recall the F# MVC templates do not completely run because of issues we ran into with the F# compiler.

Agreed. I commented about this in https://github.com/dotnet/aspnetcore/pull/25180#issuecomment-678872566 If the test can run successfully five or ten times (may need to reduce the repetitions here), then I won't short-circuit it.

**Comment by Pilchie** [comment]
I think it's worth putting in 5.0.  It's the sort of thing that is fairly low-risk, but also fairly obvious to any customer attempting the scenario.

**Comment by dougbu** [comment]
New test was successful in https://dev.azure.com/dnceng/public/_build/results?buildId=785210&view=ms.vss-test-web.build-test-results-tab across multiple platforms i.e. on Helix and in the `Test: Templates - Windows Server 2016 x64` job. I'll remove the `[Repeat]` attribute and rebase on 'release/5.0'.

**Comment by dougbu** [comment]
:up::date: Will add ask-mode template tomorrow

**Comment by dougbu** [comment]
@Pilchie can `msftbot` be taught to mark up 'release/5.0' PRs appropriately❔ If this is a change I can make, please point me to the configuration.

**Comment by Pilchie** [comment]
@dougbu I believe the bot will already do what you expect, but it's based on the `servicing-consider` label, not the `ask-mode`.  I don't think there is actually any particular use of `ask-mode` anymore, so maybe we should remove it.
