### PR TITLE
[Java] Observe accessTokenProvider on error

### LINKED ISSUE #23820: Android SignalR Client: App is crashed if AccessTokenProvider Single emits an Error
### Describe the bug
When constructing an instance of the HubConnection using the SignalR Java client and passing in an AccessTokenProvider that could emit an error, the app is being crashed with a `io.reactivex.exceptions.OnErrorNotImplementedException`. 

### To Reproduce

```java
final HubConnection hubConnection = HubConnectionBuilder.create("https://example.com")
        .withAccessTokenProvider(Single.defer(() -> Single.error(new RuntimeException("Simulated Error"))))
        .build();

hubConnection.start().subscribe(() -> {
    // success handler
}, throwable -> {
    // error handler
});
```

The issue is incorrect use of RxJava's subscribe method by not including an onError handler when subscribing to the AccessTokenProvider:
https://github.com/dotnet/aspnetcore/blob/8e50db65f32dd71a24a1771cc0f295897ce2fdce/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L339-L344

### Desired behavior:
Exceptions from the AccessTokenProvider's should be handled transparently by propagating them to the Completable that is being returned by `HubConnection.start()`.

### Exceptions (if any)

```
W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
W/System.err:     at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
W/System.err:     at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
        at io.reactivex.Single.subscribe(Single.java:3666)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3652)
        at io.reactivex.Single.subscribe(Single.java:3620)
W/System.err:     at com.microsoft.signalr.HubConnection.start(HubConnection.java:334)
```

### Further technical details
- SignalR Dependency: com.microsoft.signalr:signalr:3.0.0

### PR DESCRIPTION
**Pull request by BrennanConroy**
Originally this was just a simple 1 line fix with a single test. But I had to do my due-diligence and check the LongPolling usage of accessTokenProvider and fix it too :D

Fixes https://github.com/dotnet/aspnetcore/issues/23820

### CODE REVIEW

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java [hunk 1]
```diff
@@ -150,23 +156,28 @@ public void setOnClose(TransportOnClosedCallback onCloseCallback) {
...
+            }).andThen(Completable.defer(() -> {
                 CompletableSubject stopCompletableSubject = CompletableSubject.create();
-                return this.receiveLoop.andThen(Completable.defer(() -> {
-                    logger.info("LongPolling transport stopped.");
-                    this.onReceiveThread.shutdown();
-                    this.threadPool.shutdown();
-                    this.onClose.invoke(this.closeError);
-                    return Completable.complete();
-                })).subscribeWith(stopCompletableSubject);
+                return this.receiveLoop.doOnComplete(() -> {
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:167]: Could we hook this up before the call to stop? That way you wouldn't need to set up an onErrorResumeNext callback to call stope().

Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:167]: Looks promising, I'll give it a try

Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:164]: While doing this I ended up fixing a scenario where we could leak a thread or two

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java [hunk 2]
```diff
@@ -75,18 +73,27 @@ public Completable start(String url) {
                     this.active = true;
                 }
                 this.threadPool = Executors.newCachedThreadPool();
-                threadPool.execute(() -> poll(url).subscribeWith(receiveLoop));
+                threadPool.execute(() -> {
+                    this.onReceiveThread = Executors.newSingleThreadExecutor();
```
Comment (davidfowl) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:77]: Why move this?

Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:77]: Because if there is an error before the second poll, we don't need to make a thread 🤷‍♀️

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java [hunk 3]
```diff
@@ -75,18 +73,27 @@ public Completable start(String url) {
...
+                    receiveLoop.subscribe(() -> {
+                        this.stop().onErrorComplete().subscribe();
+                    }, e -> {
+                        this.stop().onErrorComplete().subscribe();
+                    });
+                    poll(url)
+                    .subscribeWith(receiveLoop);
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:84]: Nit: single line or indent.

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java [hunk 4]
```diff
@@ -150,23 +154,31 @@ public void setOnClose(TransportOnClosedCallback onCloseCallback) {
...
-                return this.receiveLoop.andThen(Completable.defer(() -> {
-                    logger.info("LongPolling transport stopped.");
-                    this.onReceiveThread.shutdown();
-                    this.threadPool.shutdown();
-                    this.onClose.invoke(this.closeError);
-                    return Completable.complete();
-                })).subscribeWith(stopCompletableSubject);
+                return this.pollingClient.delete(this.url, request).ignoreElement()
+                .andThen(receiveLoop)
+                .doOnComplete(() -> {
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:164]: Nit: indent.

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java [hunk 5]
```diff
@@ -75,18 +73,27 @@ public Completable start(String url) {
...
-        });
+        }));
     }
 
     private Completable poll(String url) {
         if (this.active) {
             pollUrl = url + "&_=" + System.currentTimeMillis();
             logger.debug("Polling {}.", pollUrl);
-            return this.updateHeaderToken().flatMapCompletable((x) -> {
+            return this.updateHeaderToken().andThen(Completable.defer(() -> {
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:96]: What's the difference between `.andThen(Completable.defer(() ->` and `.flatMapCompletable((x) ->`. Just the lack of the unused `x` argument?

**Review by halter73 — APPROVED** [review]

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java (hunk 5 above)
Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/LongPollingTransport.java:96]: Right, and updateHeaderToken no longer returns a value.

**Comment by A8K4** [comment]
I faced the same problem in my project, I cannot catch the exception thrown in the AccessTokenProvider.

Here is my code: 

```
    hubConnection = HubConnectionBuilder
        .create(serverUrl)
        .withAccessTokenProvider(Single.defer(() -> Single.just(tokenService.fetchToken())))
        .build();
      hubConnection.on("Error", () -> {
        Logger.info("hubConnection.on Error.");
      })

    hubConnection
        .start()
        .doOnComplete(() -> {
          ...
        })
       .doOnError(error -> {
            Logger.error("error", error);
           handleError(error);
            retry();
      })
        .blockingAwait();
```

So if an exception occurs in **tokenService.fetchToken()** I can't handle it anywhere.

**Comment by fi8er1** [comment]
> I faced the same problem in my project, I cannot catch the exception thrown in the AccessTokenProvider.
> 
> Here is my code:
> 
> ```
>     hubConnection = HubConnectionBuilder
>         .create(serverUrl)
>         .withAccessTokenProvider(Single.defer(() -> Single.just(tokenService.fetchToken())))
>         .build();
>       hubConnection.on("Error", () -> {
>         Logger.info("hubConnection.on Error.");
>       })
> 
>     hubConnection
>         .start()
>         .doOnComplete(() -> {
>           ...
>         })
>        .doOnError(error -> {
>             Logger.error("error", error);
>            handleError(error);
>             retry();
>       })
>         .blockingAwait();
> ```
> 
> So if an exception occurs in **tokenService.fetchToken()** I can't handle it anywhere.

still facing the same issue, lib version 6.0.8 
https://stackoverflow.com/questions/73754257/android-signalr-java-client-onerrornotimplementedexception
