### PR TITLE
Stop enforcing JSON read till end if `EndInvokeJS` returns early

### LINKED ISSUE #38962: Semi-random JsonException thrown from EndInvokeJS
### Describe the bug

In some random cases, Blazor JSInterop throws JsonExceptions. I didn't find a way to create a minimal reproduction, since this appears to be a timing issue which is super hard to reproduce. Moreover, it happens at different points on my versions of Chrome & Firefox, and changes (pass on one page previously failing, & fail on page previously passing) depending on `Task.Delay()`s.
So, yeah, a repro gonna be hard. Yet, I think I could give you access to my full app where the error occurs.

This is probably a continuation of #34267

---

So I've tweaked around, cloned aspnetcore entierly & built it locally to test some little things. And I've managed to track it down to this:

My error was thrown here:

https://github.com/dotnet/aspnetcore/blob/ae1a6cbe225b99c0bf38b7e31bf60cb653b73a52/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs#L311-L314

I've found out that an entire JSON object was still pending for read in the JsonReader.

So I've digged deeper to here:

https://github.com/dotnet/aspnetcore/blob/ae1a6cbe225b99c0bf38b7e31bf60cb653b73a52/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs#L228-L235

So, if the invocation timed out (or whatever, but yet, the task is not there anymore), the stream is let as-is, untouched, with data pending.

**I've managed to reliably fix my issue by adding `jsonReader.Skip()` before here:**
https://github.com/dotnet/aspnetcore/blob/ae1a6cbe225b99c0bf38b7e31bf60cb653b73a52/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs#L234

I don't know if it makes sense. I don't have a repro, but at least, you might have more clue about the underlying problem.

### Exceptions (if any)

```
dotnet.6.0.0.iveziqpht8.js:1 Uncaught (in promise) Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments) in F:\Work\cs\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs:line 313
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.<>c.<EndInvokeJS>b__7_0(String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCallQueue.Schedule[String](String state, Action`1 callback)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS(String argsJson)
    at Object._convert_exception_for_method_call (dotnet.6.0.0.iveziqpht8.js:1)
    at Object._handle_exception_for_call (dotnet.6.0.0.iveziqpht8.js:1)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS (managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:17)
    at Object.endInvokeJSFromDotNet (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
```

<details>

```
blazor.webassembly.js:1 
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1 Unhandled Exception:
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1 System.Text.Json.JsonException: Invalid JSON
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1    at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments) in F:\Work\cs\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs:line 313
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.<>c.<EndInvokeJS>b__7_0(String argsJson)
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCallQueue.Schedule[String](String state, Action`1 callback)
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS(String argsJson)
window.Module.s.printErr @ blazor.webassembly.js:1
put_char @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
write @ dotnet.6.0.0.iveziqpht8.js:1
doWritev @ dotnet.6.0.0.iveziqpht8.js:1
_fd_write @ dotnet.6.0.0.iveziqpht8.js:1
$func5840 @ 00945abe:0x14830e
$func3598 @ 00945abe:0xba938
$func205 @ 00945abe:0x7351
$func2574 @ 00945abe:0x7e545
$func8617 @ 00945abe:0x1b6c57
$func517 @ 00945abe:0x12740
$func4079 @ 00945abe:0xdc5a1
$func2151 @ 00945abe:0x5ca12
$func4231 @ 00945abe:0xe4a21
$func4232 @ 00945abe:0xe5172
$func124 @ 00945abe:0x5802
$func2307 @ 00945abe:0x6e5d7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$func6537 @ 00945abe:0x166a21
$Hb @ 00945abe:0x176082
Module._mono_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
pump_message @ dotnet.6.0.0.iveziqpht8.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.0.iveziqpht8.js:1
$func1289 @ 00945abe:0x2f8dc
$func6721 @ 00945abe:0x16c00e
$func2588 @ 00945abe:0x806c2
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.iveziqpht8.js:1
_js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
js_to_mono_obj @ dotnet.6.0.0.iveziqpht8.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.iveziqpht8.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.iveziqpht8.js:1
_call_method_with_converted_args @ dotnet.6.0.0.iveziqpht8.js:1
call_method @ dotnet.6.0.0.iveziqpht8.js:1
(anonymous) @ dotnet.6.0.0.iveziqpht8.js:1
call_assembly_entry_point @ dotnet.6.0.0.iveziqpht8.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
await in St (async)
(anonymous) @ app.js:48
dotnet.6.0.0.iveziqpht8.js:1 Uncaught (in promise) Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments) in F:\Work\cs\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs:line 313
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.<>c.<EndInvokeJS>b__7_0(String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCallQueue.Schedule[String](String state, Action`1 callback)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS(String argsJson)
    at Object._convert_exception_for_method_call (dotnet.6.0.0.iveziqpht8.js:1)
    at Object._handle_exception_for_call (dotnet.6.0.0.iveziqpht8.js:1)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS (managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:17)
    at Object.endInvokeJSFromDotNet (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
```

</details>

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022 Community
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

### LINKED ISSUE #39087: Blazor WASM: File Upload - MultipartFormDataContent.Add() throws internal Invalid JSON exception
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Uploading a file results in `Invalid JSON` in internal code.

`ImageUploader.razor`:
```razor
<InputFile OnChange="UploadFiles" multiple  />
```

`ImageUploader.razor.cs`:
```c#
using BlazorTests.Shared;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace BlazorTests.Client.Shared
{
    public partial class ImageUploader : ComponentBase
    {
        private List<File> files = new();
        private List<UploadResult> uploadResults = new();
        private int maxAllowedFiles = 10;

        private bool shouldRender;

        protected override bool ShouldRender() => shouldRender;

        private void UploadFiles(InputFileChangeEventArgs e)
        {
            shouldRender = false;
            long maxFileSize = 1024 * 1024 * 15;
            var upload = false;

            using var content = new MultipartFormDataContent();


            foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
            {
                if (uploadResults.SingleOrDefault(
                    f => f.FileName == file.Name) is null)
                {
                    try
                    {
                        var fileContent =
                            new StreamContent(file.OpenReadStream(maxFileSize));

                        fileContent.Headers.ContentType =
                            new MediaTypeHeaderValue(file.ContentType);

                        files.Add(new() { Name = file.Name });
                        try // This is the block that throws. Note that the exception is not catched and the app breaks.
                        {
                            content.Add(
                            content: fileContent,
                            name: "\"files\"",
                            fileName: file.Name);
                        }catch(JsonException ex)
                        {
                            Console.WriteLine(ex.Message);
                        }

                        upload = true;
                    }
                    catch (Exception)
                    {
                        uploadResults.Add(
                            new()
                            {
                                FileName = file.Name,
                                ErrorCode = 6,
                                Uploaded = false
                            });
                    }
                }
            }

            shouldRender = true;
        }

        private class File
        {
            public string Name { get; set; }
        }
    }
}

```

The code is taken from [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly#upload-files-to-a-server).

### Expected Behavior

No exception, obviously.

### Steps To Reproduce

https://github.com/Grizzlly/BlazorTests

### Exceptions (if any)

When I debug and try to upload a file, I get this:
image

### .NET Version

6.0.100

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by TanayParikh**
We don't want to enforce we've read till the end of the JSON if we've just abandoned the `EndInvokeJS` call entirely due to the task timing out or if it stopped waiting. If we abandoned the `EndInvokeJS` call, we know we haven't read till the end of the JSON (and that's expected), hence we shouldn't be throwing an exception in that case. 

Fixes: https://github.com/dotnet/aspnetcore/issues/38962

### CODE REVIEW

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs [hunk 1]
```diff
@@ -306,9 +306,9 @@ public static void EndInvokeJS(JSRuntime jsRuntime, string arguments)
         var success = reader.GetBoolean();
 
         reader.Read();
-        jsRuntime.EndInvokeJS(taskId, success, ref reader);
+        var completed = jsRuntime.EndInvokeJS(taskId, success, ref reader);
```
Comment (pranavkm) [inline src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:309]: Any reason we wouldn't want to do? I imagine we don't care about reading more JSON if it previously failed?

```suggestion
        if (!jsRuntime.EndInvokeJS(taskId, success, ref reader))
        {
           return;
        }
```

File: src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs [hunk 2]
```diff
@@ -225,13 +225,13 @@ protected internal virtual Task<Stream> ReadJSDataAsStreamAsync(IJSStreamReferen
...
     [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2072:RequiresUnreferencedCode", Justification = "We enforce trimmer attributes for JSON deserialized types on InvokeAsync.")]
-    internal void EndInvokeJS(long taskId, bool succeeded, ref Utf8JsonReader jsonReader)
+    internal bool EndInvokeJS(long taskId, bool succeeded, ref Utf8JsonReader jsonReader)
     {
         if (!_pendingTasks.TryRemove(taskId, out var tcs))
         {
             // We should simply return if we can't find an id for the invocation.
             // This likely means that the method that initiated the call defined a timeout and stopped waiting.
-            return;
+            return false;
```
Comment (pranavkm) [inline src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:234]: Could you remind me what the workflow looks like in this case? The EndInvokeJS is called by JS but the task on the server is removed, so there's nothing to do?

File: src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs [hunk 3]
```diff
@@ -314,6 +314,110 @@ public async Task EndInvoke_WithNullError()
...
+
+        DotNetDispatcher.EndInvokeJS(jsRuntime, argsJson);
+
+        // Assert
+        Assert.False(task.IsCompletedSuccessfully);
+        Assert.True(task.IsCanceled);
+    }
+
+    [Fact]
+    public void EndInvokeJS_ThrowsIfJsonIsEmptyString()
```
Comment (TanayParikh) [inline src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs:339]: Remaining tests have been moved up from later in the file (so all the `EndInvokeJS` tests remain in one section). The `Arrange` section was also added for the tests.

File: src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs [hunk 4]
```diff
@@ -314,6 +314,110 @@ public async Task EndInvoke_WithNullError()
...
     }
 
+    [Fact]
+    public void EndInvokeJS_DoesNotThrowJSONExceptionIfTaskCancelled()
+    {
+        // Arrange
+        var jsRuntime = new TestJSRuntime();
+        var testDTO = new TestDTO { StringVal = "Hello", IntVal = 4 };
+        var cts = new CancellationTokenSource();
+        var argsJson = JsonSerializer.Serialize(new object[] { jsRuntime.LastInvocationAsyncHandle, true, testDTO }, jsRuntime.JsonSerializerOptions);
```
Comment (pranavkm) [inline src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs:324]: Do we need an other test where the json is malformed but the cts is canceled prior to it being read?

File: src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs (hunk 2 above)
Comment (TanayParikh) [reply src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:234]: Exactly. So for WASM this would look something like 

Call Tree:
- JS
- DefaultWebAssemblyJSRuntime.EndInvokeJS
- DotNetDispatcher.EndInvokeJS
- JSRuntime.EndInvokeJS (here)

Comment (pranavkm) [reply src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:234]: Ok. As long as nothing (incidentally) relied on the JSException being previously thrown, this looks great.

**Review by pranavkm — APPROVED** [review]

File: src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs (hunk 2 above)
Comment (TanayParikh) [reply src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:234]: Nothing that I can tell. This is also the only call to `JSRuntime.EndInvokeJS`: https://source.dot.net/#Microsoft.JSInterop/JSRuntime.cs,64701806bdd192b1,references
