### PR TITLE
Issue #60416 - Correction of BufferedReadStream 's Position

### LINKED ISSUE #60416: Microsoft.AspNetCore.WebUtilities.BufferedReadStream - incorrect implementation of Position property's setter
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi. By trying to use Microsoft.AspNetCore.WebUtilities.MultipartReader in a way that is directly using the section streams outside the initial reading loop (made through ReadNextSectionAsync), I've come to at least one case (when dealing with more than two section streams) where the conclusion is that the Position property of BufferedReadStream has an incorrect implementation when trying to position inside the internal buffer. I guess it's a pretty invalidating bug, making the whole MultipartReader support unstable / unpredictible / unusable.

To be more exact, these two lines are incorrect, in my opinion:

https://github.com/dotnet/aspnetcore/blob/ec389c71560ceba39148831343ba8f20962e0228/src/Http/WebUtilities/src/BufferedReadStream.cs#L110-L112

### Explaination

It should advance in the internal buffer not **with** the offset between old position and new position (i.e. backward innerOffset), but **until** that offset / distance, so in the end the new Position will reflect the desired input value when getting the property. That means we should advance _bufferCount (number of bytes left for reading until old position) minus innerOffset (previously mentioned offset).

### Expected Behavior

It should have been replaced by these lines:

_bufferOffset += _bufferCount - innerOffset;
_bufferCount = innerOffset;

### Steps To Reproduce

Try to use a Microsoft.AspNetCore.WebUtilities.MultipartReader in a request having at least two uploaded form data files and store the section streams for later reading (not some copies of them), it will be impossible to correctly read the second stream because the functionality has unpredictible behavior (see description of the problem).

### Exceptions (if any)

In some scenarios it throws: **IOException**("Unexpected end of Stream, the content may have already been read by another component. ")

### .NET Version

_No response_

### Anything else?

It would be nice if this can be fixed in order to not be forced to make copies of large uploaded files. I can contribute with the fix for it (described above), if this would be the easiest and fastest way to push the fix, after checking the validity of the issue. Thank you.

### PR DESCRIPTION
**Pull request by nidaca**
# Correction of Microsoft.AspNetCore.WebUtilities.BufferedReadStream Position property

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

The implementation of Position's property setter for Microsoft.AspNetCore.WebUtilities.BufferedReadStream class was incorrect and changed accordingly with the proposed solution described in the issue #60416 .

## Description

By trying to use Microsoft.AspNetCore.WebUtilities.MultipartReader in a way that is directly using the section streams outside the initial reading loop (made through ReadNextSectionAsync), I've come to at least one case (when dealing with more than two section streams) where the conclusion is that the Position property of BufferedReadStream has an incorrect implementation when trying to position inside the internal buffer.
The solution was to advance in the internal buffer not with the offset between old position and new position (i.e. backward innerOffset), but until that offset / distance, so in the end the new Position will reflect the desired input value when getting the property. 

Fixes #60416

### CODE REVIEW

**Comment by nidaca** [comment]
> @nidaca please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
> ### Contribution License Agreement
> This Contribution License Agreement ( **“Agreement”** ) is agreed to by the party signing below ( **“You”** ), and conveys certain license rights to the .NET Foundation ( **“.NET Foundation”** ) for Your contributions to .NET Foundation open source projects. This Agreement is effective as of the latest signature date below.
> 
> **1. Definitions.**
> 
> **“Code”** means the computer software code, whether in human-readable or machine-executable form, that is delivered by You to .NET Foundation under this Agreement.
> 
> **“Project”** means any of the projects owned or managed by .NET Foundation and offered under a license approved by the Open Source Initiative ([www.opensource.org](http://www.opensource.org)).
> 
> **“Submit”** is the act of uploading, submitting, transmitting, or distributing code or other content to any Project, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of discussing and improving that Project, but excluding communication that is conspicuously marked or otherwise designated in writing by You as “Not a Submission.”
> 
> **“Submission”** means the Code and any other copyrightable material Submitted by You, including any associated comments and documentation.
> 
> **2. Your Submission.** You must agree to the terms of this Agreement before making a Submission to any Project. This Agreement covers any and all Submissions that You, now or in the future (except as described in Section 4 below), Submit to any Project.
> 
> **3. Originality of Work.** You represent that each of Your Submissions is entirely Your original work. Should You wish to Submit materials that are not Your original work, You may Submit them separately to the Project if You (a) retain all copyright and license information that was in the materials as you received them, (b) in the description accompanying your Submission, include the phrase "Submission containing materials of a third party:" followed by the names of the third party and any licenses or other restrictions of which You are aware, and (c) follow any other instructions in the Project's written guidelines concerning Submissions.
> 
> **4. Your Employer.** References to “employer” in this Agreement include Your employer or anyone else for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your Submission is made in the course of Your work for an employer or Your employer has intellectual property rights in Your Submission by contract or applicable law, You must secure permission from Your employer to make the Submission before signing this Agreement. In that case, the term “You” in this Agreement will refer to You and the employer collectively. If You change employers in the future and desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement and secure permission from the new employer before Submitting those Submissions.
> 
> **5. Licenses.**
> 
> **a. Copyright License.** You grant .NET Foundation, and those who receive the Submission directly or indirectly from .NET Foundation, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third parties.
> 
> **b. Patent License.** You grant .NET Foundation, and those who receive the Submission directly or indirectly from .NET Foundation, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under Your patent claims that are necessarily infringed by the Submission or the combination of the Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and import or otherwise dispose of the Submission alone or with the Project.
> 
> **c. Other Rights Reserved.** Each party reserves all rights not expressly granted in this Agreement. No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are granted by implication, exhaustion, estoppel or otherwise.
> 
> **6. Representations and Warranties.** You represent that You are legally entitled to grant the above licenses. You represent that each of Your Submissions is entirely Your original work (except as You may have disclosed under Section 3 ). You represent that You have secured permission from Your employer to make the Submission in cases where Your Submission is made in the course of Your work for Your employer or Your employer has intellectual property rights in Your Submission by contract or applicable law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You have the necessary authority to bind the listed employer to the obligations contained in this Agreement. You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES EXPRESSLY STATED IN SECTIONS 3, 4, AND 6 , THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
> 
> **7. Notice to .NET Foundation.** You agree to notify .NET Foundation in writing of any facts or circumstances of which You later become aware that would make Your representations in this Agreement inaccurate in any respect.
> 
> **8. Information about Submissions.** You agree that contributions to Projects and information about contributions may be maintained indefinitely and disclosed publicly, including Your name and other information that You submit with Your Submission.
> 
> **9. Governing Law/Jurisdiction.** This Agreement is governed by the laws of the State of Washington, and the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County, Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all defenses of lack of personal jurisdiction and forum non-conveniens.
> 
> **10. Entire Agreement/Assignment.** This Agreement is the entire agreement between the parties, and supersedes any and all prior agreements, understandings or communications, written or oral, between the parties relating to the subject matter hereof. This Agreement may be assigned by .NET Foundation.
> 
> _.NET Foundation dedicates this Contribution License Agreement to the public domain according to the Creative Commons CC0 1._

@dotnet-policy-service agree

File: src/Http/WebUtilities/test/MultipartReaderTests.cs [hunk 1]
```diff
@@ -93,6 +92,26 @@ public class MultipartReaderTests
 "Content of a.txt.\r\n" +
 "\r\n" +
 "--9051914041544843365";
+    private const string ThreePartBodyWithMixedFiles =
```
Comment (halter73) [inline src/Http/WebUtilities/test/MultipartReaderTests.cs:95]: Is there a reason the existing `ThreePartBody` couldn't be used for this test? Even if so, I'd just store this in a local variable if it's not going to be used by more than one test.

File: src/Http/WebUtilities/test/MultipartReaderTests.cs [hunk 2]
```diff
@@ -315,6 +334,57 @@ public void MultipartReader_BufferSizeMustBeLargerThanBoundary_Throws()
...
+        Assert.Equal("application/json", section.Headers["Content-Type"][0]);
+        var stream3 = section.Body;
+
+        Assert.Null(await reader.ReadNextSectionAsync());
+
+        Assert.True(stream1.CanSeek);
+        Assert.Equal(0, stream1.Seek(0, SeekOrigin.Begin));
+        var buffer = new MemoryStream();
+        var exception = await Record.ExceptionAsync(() => stream1.CopyToAsync(buffer));
+        Assert.Null(exception);
```
Comment (halter73) [inline src/Http/WebUtilities/test/MultipartReaderTests.cs:370]:
```suggestion
        await stream1.CopyToAsync(buffer);
```

There's no need to null check exceptions. If `CopyToAsync` throws, it will fail the test already. I'd remove the other two calls to `Record.ExceptionAsync` too. Thanks.

**Review by halter73 — APPROVED** [review]
Thanks for reporting this issue and following through with the fix.

File: src/Http/WebUtilities/test/MultipartReaderTests.cs (hunk 1 above)
Comment (nidaca) [reply src/Http/WebUtilities/test/MultipartReaderTests.cs:95]: hi. no, not a serious one. by using the existing body I should have involved - skipped the first section. such that I've come with another body, just with files.... but is not a problem to replace it, if redundant.

Comment (nidaca) [reply src/Http/WebUtilities/test/MultipartReaderTests.cs]: I have removed it anyway and used ThreePartBody, to shorten the suite.

File: src/Http/WebUtilities/test/MultipartReaderTests.cs (hunk 2 above)
Comment (nidaca) [reply src/Http/WebUtilities/test/MultipartReaderTests.cs]: @halter73 : Ok, good suggestion. it should be solved. Thanks!

**Comment by nidaca** [comment]
CLA

**Review by halter73 — APPROVED** [review]
LGTM. Even though this is a bug fix, I don't think this meets the bar for patching given that it's unusual to seek a `BufferedReadStream` and it's rare for the inner stream to even be seekable which is probably why this took so long to discover.

File: src/Http/WebUtilities/src/BufferedReadStream.cs [hunk 3]
```diff
@@ -108,8 +108,8 @@ public override long Position
                 if (innerOffset <= _bufferCount)
                 {
                     // Yes, just skip some of the buffered data
-                    _bufferOffset += innerOffset;
-                    _bufferCount -= innerOffset;
+                    _bufferOffset += _bufferCount - innerOffset;
+                    _bufferCount = innerOffset;
```
Comment (rhuijben) [inline src/Http/WebUtilities/src/BufferedReadStream.cs:112]: Doesn't this drop the buffer behind the current position?

It looks like it makes some already read data available again, but then at the same time forgets everything not already read.

Comment (nidaca) [reply src/Http/WebUtilities/src/BufferedReadStream.cs:112]: Hi. What do you mean by "looks like it makes some already read data available again"? .....as long as the _bufferOffset is incremented with something (pls read the full explaination within the description of the issue).
