### PR TITLE
Fix #6102 - Intense CPU utilization on page change

### LINKED ISSUE #6102: Memory Leak in new ASPNET 2.2 routing?
### Describe the bug
I was editing some Razor Pages (the `Project\Pages` kind) then refreshing the changes in Chrome (Version 71.0.3578.98). My dev loop is tight, so I make a small edit then refresh the page, and the change is visible in Chrome.

Eventually, I noticed my edits were not making their way to the browser. On a few occasions, I noticed waiting a longer time delay before refreshing the browser *sometimes* helped the situation. Eventually, though, edits would no longer make their way to the browser.

Originally, I was using `InProcess` but decided to switch to `OutOfProcess`, rebooted PC, and the same problem occurred. Somewhere between 15 minutes to 1 hour of constantly editing Razor Pages in Visual Studio, I begin to notice my edits not showing up in the browser.

With out of `OutOfProcess` enabled, I noticed, a massive **9.7 GB** memory usage in `dotnet.exe`

procexp64_2548

(later, trying to debug `dotnet.exe`, we're up at **27GB**)
devenv_2562

procexp64_2550

`dotnet.exe`:
screen_2567

As `dotnet.exe` consumes memory, there appears to be a few threads that pop off `coreclr_shutdown`. Not much to discern, but worth noting.

Next, I attached a VS debugger to `dotnet.exe`, broke into the debugger and landed in `Program.Main()`. None of my user code was running. **Continue & Pausing** the debugger multiple times did show one thread standing out. Specifically, **Thread 3952** playing around in the new ASPNET Core 22 routing code? `Microsoft.AspNetCore.Routing.DecisionTree`.

Specifically, `Array.Copy`, `DecisionTree.Resize` and `Capacity.set` seem to be popular destinations with **Thread 3952**. **Thread 3952** is the only thread that appears to be active during this memory leak.

devenv_2561
devenv_2560
devenv_2558
devenv_2557

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Edit somewhat complex Razor Pages for about 15 minutes to 1 hour in a tight dev loop.

### Expected behavior
I should be able to make edits in Razor Pages and see my changes in the browser without having to restart `IISExpress` or kill `dotnet.exe` manually or experience a memory leak during the editing experience.

#### Operating System
* Windows 7

#### IDE
* Visual Studio 15.9.4
```
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Also, here is **Process Monitor** monitoring file access during the memory leak event:
procmon64_2553

-----

I will continue to do more testing to see if I can narrow down the issue. Thanks for your help in advance.

Thanks,
Brian Chavez

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

### PR DESCRIPTION
**Pull request by rynowak**
The issue here was that every time a Razor Page changed, we would
subscribe an additional time to the endpoint change notifications. This
means that if you tweaked a page 30 times, we would update the address
table 31 times when you save the file. If you were doing a lot of editing
then this would grow to a really large amount of computation.

The fix is to use DataSourceDependentCache, which is an existing utility
type we developed for this purpose. I'm not sure why it wasn't being
used for this already. We're already using DataSourceDependentCache in a
bunch of other places, and it's well tested.

I also tweaked the stucture of this code to be more similar to
EndpointNameAddressScheme. This involved some test changes that all
seemed like good cleanup. The way this was being tested was a little
wonky.

### CODE REVIEW

File: src/Http/Routing/src/DataSourceDependentCache.cs [hunk 1]
```diff
@@ -26,6 +26,11 @@ public DataSourceDependentCache(EndpointDataSource dataSource, Func<IReadOnlyLis
                 throw new ArgumentNullException(nameof(dataSource));
             }
 
+            if (initialize == null)
+            {
+                throw new ArgumentNullException(nameof(initialize));
+            }
+
```
Comment (rynowak) [inline src/Http/Routing/src/DataSourceDependentCache.cs]: I noticed this was missing while re-reviewing this code. It's worth adding because this could would nullref eventually during change token refresh.

File: src/Http/Routing/src/RouteValuesAddressScheme.cs [hunk 2]
```diff
@@ -1,46 +1,44 @@
...
-using System;
-using System.Collections.Generic;
-using System.Linq;
 using Microsoft.AspNetCore.Http;
 using Microsoft.AspNetCore.Routing.Internal;
 using Microsoft.AspNetCore.Routing.Template;
 using Microsoft.AspNetCore.Routing.Tree;
-using Microsoft.Extensions.Primitives;
+using System;
+using System.Collections.Generic;
```
Comment (rynowak) [inline src/Http/Routing/src/RouteValuesAddressScheme.cs]: Thanks VS. It keeps changing my settings.

**Review by JamesNK — APPROVED** [review]

File: src/Http/Routing/test/UnitTests/RouteValuesAddressSchemeTest.cs [hunk 3]
```diff
@@ -84,11 +84,12 @@ public void EndpointDataSource_ChangeCallback_Refreshes_OutboundMatches()
             var dynamicDataSource = new DynamicEndpointDataSource(new[] { endpoint1 });
 
             // Act 1
-            var addressScheme = new CustomRouteValuesBasedAddressScheme(new CompositeEndpointDataSource(new[] { dynamicDataSource }));
+            var addressScheme = new RouteValuesAddressScheme(new CompositeEndpointDataSource(new[] { dynamicDataSource }));
```
[the remark this answers is not in the document]
Comment (rynowak) [reply src/Http/Routing/test/UnitTests/RouteValuesAddressSchemeTest.cs]: Yes. notice that I added a bunch of verification that was missing.

File: src/Http/Routing/src/RouteValuesAddressScheme.cs [hunk 4]
```diff
@@ -1,46 +1,44 @@
...
 
+        // Internal for tests
+        internal StateEntry State => _cache.EnsureInitialized();
+
         public IEnumerable<Endpoint> FindEndpoints(RouteValuesAddress address)
         {
+            if (address == null)
+            {
+                throw new ArgumentNullException(nameof(address));
+            }
```
Comment (rynowak) [inline src/Http/Routing/src/RouteValuesAddressScheme.cs]: This would cause a nullref a few lines down.

**Comment by davidfowl** [comment]
Ah you’re not using the helper. I guess it’s ok because you never dispose the registration. Is there another leak there because of that?

File: src/Http/Routing/src/RouteValuesAddressScheme.cs [hunk 5]
```diff
@@ -1,46 +1,44 @@
...
-using System.Linq;
 using Microsoft.AspNetCore.Http;
 using Microsoft.AspNetCore.Routing.Internal;
 using Microsoft.AspNetCore.Routing.Template;
 using Microsoft.AspNetCore.Routing.Tree;
-using Microsoft.Extensions.Primitives;
 
 namespace Microsoft.AspNetCore.Routing
 {
     internal class RouteValuesAddressScheme : IEndpointAddressScheme<RouteValuesAddress>
```
Comment (davidfowl) [inline src/Http/Routing/src/RouteValuesAddressScheme.cs]: I would make this disposable and dispose the DataSourceDependentCache in Dispose.

**Review by davidfowl — CHANGES_REQUESTED** [review]
Make DataSourceDependentCache disposable and dispose it in the places that use it.

File: src/Http/Routing/src/RouteValuesAddressScheme.cs (hunk 5 above)
Comment (davidfowl) [reply src/Http/Routing/src/RouteValuesAddressScheme.cs]: Starting and stopping the host in process. We've already had an instance of an issue like this in options.

**Comment by rynowak** [comment]
Updated. @davidfowl - do middleware get disposed? https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L64 will have a change token inside.

**Comment by davidfowl** [comment]
> Updated. @davidfowl - do middleware get disposed? https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L64 will have a change token inside.

@rynowak Nope 😢. Can you move it into a service that is itself disposable?

**Comment by rynowak** [comment]
> Can you move it into a service that is itself disposable?

No not really, it's not a singleton, and requires **data** to construct.

**Comment by rynowak** [comment]
I can do something totally hack mode, by resolving another service from DI and then making that thing responsible for dispose.

**Review by davidfowl — APPROVED** [review]

**Comment by rynowak** [comment]
Checks out my cool hack. DI is like duct tape, you can use it to fix anything.
