### PR TITLE
Fix multiple attributes usage in conjunction with OpenRegion. Fixes #16570

### LINKED ISSUE #16570: InputSelect loses class attribute when setting disabled equals true
### Describe the bug
InputSelect component loses it's class attribute when setting disabled attribute to true, e.g.

`<InputSelect disabled="@(isRemoved)">...</InputSelect>`

### To Reproduce
1. Using this version of ASP.NET Core 3.1 preview and Visual Studio preview

### Expected behavior
The component should not drop class attribute for the select control. I've not seen other input components having the same behavior.

### Additional context
Include the output of `dotnet --info`
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Each of the scope-opening methods (`OpenElement`, `OpenComponent`, `OpenRegion`) is meant to do a bit of housekeeping related to `AddMultipleAttributes`.

However it seems that `OpenRegion` had been missed out, and the necessary logic had only been applied to `OpenElement` and `OpenComponent`. This resulted in duplicated attributes that confused the diff and produced overall strangeness as seen in #16570.

### CODE REVIEW

**Review by javiercn — COMMENTED** [review]
Looks great!

I'll take a deeper look tomorrow, just because the area is complicated and want to make sure that I sign-off with enough understanding.

File: src/Components/Components/src/Rendering/RenderTreeBuilder.cs [hunk 1]
```diff
@@ -581,6 +581,14 @@ public void AddComponentReferenceCapture(int sequence, Action<object> componentR
         /// <param name="sequence">An integer that represents the position of the instruction in the source code.</param>
         public void OpenRegion(int sequence)
         {
+            // We are entering a new scope, since we track the "duplicate attributes" per
+            // element/component we might need to clean them up now.
+            if (_hasSeenAddMultipleAttributes)
+            {
+                var indexOfLastElementOrComponent = _openElementIndices.Peek();
+                ProcessDuplicateAttributes(first: indexOfLastElementOrComponent + 1);
```
Comment (javiercn) [inline src/Components/Components/src/Rendering/RenderTreeBuilder.cs]: I haven't fully wrap my head around this yet, but CloseComponent and CloseElement also do housekeeping and closeRegion doesn't seem to. Do we need to account for that?

https://github.com/aspnet/AspNetCore/pull/16640/files#diff-c09589b3f0826f7ed0084bef9e8816c2R532-R535

Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/RenderTreeBuilder.cs]: I don’t think that’s necessary, since regions can’t have attributes of their own.

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/Rendering/RenderTreeBuilder.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/RenderTreeBuilder.cs]: Understood

**Comment by SteveSandersonMS** [comment]
@Pilchie Seeking approval for preview 3

**Comment by Pilchie** [comment]
Approved for 3.1.0-Preview3.

**Review by rynowak — COMMENTED** [review]
:shipit:
