### PR TITLE
backport 8.0 - http.sys accept loop - mitigate against break due to possible conflicting IO callbacks

### LINKED ISSUE #54251: System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations after .NET 6 to .NET 8 upgrade
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After migration from .NET 6 to .NET 8 we started seeing multiple .NET Runtime crashes with below callstacks. The callstack suggests a problem with IO completion and async operations. It does not point to any application code, so I am seeking for help. I have memory dumps of both crash scenarios.

Windows Server 2022
HTTP.sys ASP.NET Core
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1

### Expected Behavior

No crash.

### Steps To Reproduce

_No response_

### Exceptions (if any)

```
Application: foo
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

```
Application: foo
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.OnCompleted(Action`1 continuation, Object state, Int16 token, ValueTaskSourceOnCompletedFlags flags)
   at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.OnCompleted(Action`1 continuation, Object state, Int16 token, ValueTaskSourceOnCompletedFlags flags)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.System.Runtime.CompilerServices.IStateMachineBoxAwareAwaiter.AwaitUnsafeOnCompleted(IAsyncStateMachineBox box)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter](TAwaiter& awaiter, IAsyncStateMachineBox box)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

```
Application: foo
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: 'overlapped' has already been freed.
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### .NET Version

8.0.1

### Anything else?

In the second crash we see `_mrvts` is in completed state with cached request context. I wonder if `_mrvts.SetResult` is throwing before returning, which is then caught by the catch block which calls `_mrvts.SetException` and throws because _mrvts is already in completed state. Or maybe IO completion is called twice on the same _mrvts.

image

image

### PR DESCRIPTION
**Pull request by mgravell**
# backport https://github.com/dotnet/aspnetcore/pull/54368 to .NET 8

Context: https://github.com/dotnet/aspnetcore/issues/54251

System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations after .NET 6 to .NET 8 upgrade

This manifests as a fatal exception in the http.sys "accept" loop, which can either:

- fault in purely managed code, stopping the message pump (MessagePump.ExecuteAsync)
- fault during an IOCP callback, potentially killing the process

## Description

Apply mitigation and logging

Fixes #54251

## Customer Impact

without fix, http.sys web-server stops taking traffic (best case) or segfaults

## Regression?

- [x] Yes
- [ ] No

*believed* to be a regression since .net 6; scenario is hard to repro reliably

## Risk

- [ ] High
- [x] Medium
- [ ] Low

This change is "fresh", and hasn't been validated in nightly (or even merged to "main"); the technical changes are minor (logging, improved error handling), and the competing behaviour is catastrophic.

### CODE REVIEW

**Comment by mgravell** [comment]
approved by servicing tactics 8th /cc @wtgodbe

File: src/Servers/HttpSys/src/AsyncAcceptContext.cs [hunk 1]
```diff
@@ -84,22 +99,69 @@ private void IOCompleted(uint errorCode, uint numBytes)
...
+    }
+
+    private void SetExpectCompletion() // we anticipate a completion *might* occur
+    {
+        // note this is intentionally a "reset and check" rather than Increment, so that we don't spam
+        // the logs forever if a glitch occurs
+        var value = Interlocked.Exchange(ref _expectedCompletionCount, 1); // should have been 0
+        if (value != 0)
+        {
+            if (_logExpectationFailures)
```
Comment (halter73) [inline src/Servers/HttpSys/src/AsyncAcceptContext.cs:135]: Why even gate this behind a flag? I doubt many people will know to turn it on, and if these are failing commonly, wouldn't we want to hear about it? You could disable the HttpSysListener logger if it's too noisy. 

This is another case where being able to filter logs by event ID would be nice. https://github.com/dotnet/runtime/issues/49924

**Review by halter73 — APPROVED** [review]
