### PR TITLE
Dispose the prior response on retry 

### LINKED ISSUE #28384: Microsoft.Extensions.Http.Polly: Deadlock when retrying a "503 - Service unavailable"
### Description: 
When the Application Pool of an IIS hosted website stops for whatever reason (in my case i stopped it manually), IIS returns a 503 - Service unavailable status code and adds a Connection: close response header.

When retrying such a request with the retry policies (the below is with `WaitAndRetryAsync`), the first 2 retries are returning the same status (503) but the third retry is causing the application to stop responding (most probably a deadlock happens).

### Steps to reproduce
1. Copy the below code into a .Net framework 4.7.2 console application
2. Import the following Nuget packages
``` xml
  <PackageReference Include="Microsoft.Extensions.DependencyInjection">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Polly">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="Polly">
      <Version>7.0.3</Version>
    </PackageReference>
```
2. Replace URLPlaceholder with a URL pointing to an IIS hosted API hosted on the network (not on localhost)
3. After receiving a couple of 200 OK requests, manually Stop the Application pool of the IIS hosted API
4. After receiving a couple of 503 Service Unavailable responses, manually Start the Application pool of the IIS hosted API

### Expected behavior 
The application should start receiving 200 OK responses.

### Actual behaviour
The application hangs after the first 2 retries of the first 503 Service unavailable response.

Note that if the `WaitAndRetryAsync` policy addition is commented out, the application behaves as expected (without the retries of course).

### Code to reproduce the problem
``` csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http;
using Polly;
using Polly.Timeout;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class Program
    {
        async static Task Main(string[] args)
        {
            IServiceCollection services = new ServiceCollection();
            services.AddHttpClient("test")
              // comment out the below policy for a correct behavior
               .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(new[]{
               TimeSpan.FromSeconds(1),
               TimeSpan.FromSeconds(2),
               TimeSpan.FromSeconds(4),
               }));
  
              // removing the logging handlers as a work around for https://github.com/aspnet/Extensions/issues/563
            ServiceDescriptor loggingHandler = services.FirstOrDefault(e => e.ServiceType == typeof(IHttpMessageHandlerBuilderFilter));
            if (loggingHandler != null)
            {
                services.Remove(loggingHandler);
            }

            IHttpClientFactory factory = services.BuildServiceProvider().GetService<IHttpClientFactory>();

            HttpClient client = factory.CreateClient("test");

            while (true)
            {
                HttpResponseMessage response = null;
                try
                {
                    response = await client.GetAsync("URLplaceholder").ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    // logging
                }

                Thread.Sleep(5000);
            }
        }
    }
}

```

### Observations

1. With only one retry for the request, the behavior is as expected.
2. The problem does not seem to be in the Polly library, as the same request executed through a `ExecutyPolicyAsync` (with the ` .AddTransientHttpErrorPolicy` commented out) is working as expected:
``` csharp
response = await Policy
                .HandleResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.ServiceUnavailable)
                .WaitAndRetryAsync(
                new[]{
                 TimeSpan.FromSeconds(1),
                 TimeSpan.FromSeconds(2),
                 TimeSpan.FromSeconds(4),
                 }).ExecuteAsync(() => client.GetAsync(url)).ConfigureAwait(false);
```

### PR DESCRIPTION
**Pull request by Tratcher**
Fixes #28384
6.0 rc2 candidate: resource leak / hang

- The HttpResponseMessage needs to be buffered, drained, or disposed to free up the connection for the next request.
- Polly is a generic policy library, it's not aware of HttpRequest/ResponseMessage lifetimes or the need to dispose them on retry. Polly.Extensions.Http is aware of HttpRequest/ResponseMessage but doesn't participate in the retry execution, only the decision on if a retry is recommended.

Fix: Add a reference from the request to the response so that if the request is retried, it can dispose the prior response.

### CODE REVIEW

File: src/HttpClientFactory/Polly/test/PolicyHttpMessageHandlerTest.cs [hunk 1]
```diff
@@ -98,6 +99,54 @@ public async Task SendAsync_DynamicPolicy_PolicyTriggers_CanReexecuteSendAsync()
             Assert.Same(expectedRequest, policySelectorRequest);
         }
 
+        [Fact]
+        public async Task SendAsync_StaticPolicy_PolicyTriggers_CanReexecuteSendAsync_FirstResponseDisposed()
+        {
+            // Arrange
+            var policy = HttpPolicyExtensions.HandleTransientHttpError()
+                .RetryAsync(retryCount: 1);
```
Comment (captainsafia) [inline src/HttpClientFactory/Polly/test/PolicyHttpMessageHandlerTest.cs:107]: Assuming I understand what this is doing correctly, the original issue report seems to indicate that it happens after two retries. I assume that that was just a scenario specific detail and validating on 1 retry is enough for this case?

Comment (Tratcher) [reply src/HttpClientFactory/Polly/test/PolicyHttpMessageHandlerTest.cs:107]: Right, in their scenario it took two leaks to notice the problem because that's how many resources they had available, two connections. The solution is to always dispose the previous response, it doesn't matter how many retries there are.

**Review by captainsafia — APPROVED** [review]
