### PR TITLE
Dispatch dispose to sync context. Fixes #32411

### LINKED ISSUE #32411: DataAnnotationsValidator attempts to force render during renderer disposal resulting in circuit exception
Found in version 6.0.100-preview.5.21254.10

## Repro
1. Create new Blazor Server app targeting .NET 6.0
2. In "Index.razor" add the following block:
``` razor
<EditForm Model="widget">
    <DataAnnotationsValidator />
    Widget Name: <InputText @bind-Value="widget.Name" />
</EditForm>

@code {
    Widget widget = new Widget();

    class Widget
    {
        public string Name { get; set; }
    };
}
```
3. Run the app
4. In the console output see the following exception:
``` csharp
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8FAL8PSLLA", Request id "0HM8FAL8PSLLA:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
         at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess() in Microsoft.AspNetCore.Components.dll:token 0x60000b2+0x12
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in Microsoft.AspNetCore.Components.dll:token 0x6000232+0x0
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in Microsoft.AspNetCore.Components.dll:token 0x6000098+0x2d
         at Microsoft.AspNetCore.Components.Forms.InputBase`1.OnValidateStateChanged(Object sender, ValidationStateChangedEventArgs eventArgs) in Microsoft.AspNetCore.Components.Web.dll:token 0x6000150+0x6
         at Microsoft.AspNetCore.Components.Forms.EditContext.NotifyValidationStateChanged() in Microsoft.AspNetCore.Components.Forms.dll:token 0x6000018+0x16
         at Microsoft.AspNetCore.Components.Forms.EditContextDataAnnotationsExtensions.DataAnnotationsEventSubscriptions.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x6000062+0x39
         at Microsoft.AspNetCore.Components.Forms.DataAnnotationsValidator.System.IDisposable.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x600000b+0x0
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose() in Microsoft.AspNetCore.Components.dll:token 0x60002cd+0x15
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000242+0x92
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000060+0x0
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__NotifyExceptions|65_1(List`1 exceptions) in Microsoft.AspNetCore.Components.dll:token 0x600024a+0x2a
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000242+0xec
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync() in Microsoft.AspNetCore.Components.dll:token 0x6000244+0x9b
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|16_0(Int32 i, ValueTask vt, List`1 toDispose) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000128+0x6e
         at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt) in Microsoft.AspNetCore.Http.dll:token 0x6000228+0x5b
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnCompleted>g__ProcessEvents|227_0(HttpProtocol protocol, Stack`1 events) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000b1e+0x81
```

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
A straightforwards fix for #32411, or any other issue that comes down to `Dispose` not previously running on the sync context. Now it does.

### CODE REVIEW

File: src/Components/Components/src/RenderTree/Renderer.cs [hunk 1]
```diff
@@ -582,9 +583,10 @@ private ComponentState GetRequiredRootComponentState(int componentId)
         /// </summary>
         protected virtual void ProcessPendingRender()
         {
-            if (Disposed)
+            if (_rendererIsDisposed)
             {
-                throw new ObjectDisposedException(nameof(Renderer), "Cannot process pending renders after the renderer has been disposed.");
+                // Once we're disposed, we'll disregard further attempts to render anything
+                return;
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/RenderTree/Renderer.cs:589]: Previously we didn't get this far, because an earlier `Dispatcher.CheckAccess` call would have thrown. But now we do get this far so we need to not regard it as an error any more. It's now just a no-op to try rendering after disposal.

File: src/Components/Components/src/RenderTree/Renderer.cs [hunk 2]
```diff
@@ -1079,7 +1091,7 @@ public void Dispose()
         /// <inheritdoc />
```
Comment (javiercn) [inline src/Components/Components/src/RenderTree/Renderer.cs:1091]: I know it's not the topic of this PR, however since we are already updating this, I would like to take the chance to suggest that we mark Dispose here as obsolete and remove it in the future. The renderer is an "internal" API and  for all intents and purposes we are the only ones (with a few exceptions) using it.

The renderer implementing IDisposable is a remnant of olden times when IAsyncDisposable didn't exist, and our programming model is highly skewed towards async computing, so we should take the opportunity now to start obsoleting these and avoid having to worry about them in the future.

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/Renderer.cs:1091]: I'd be fine with us doing this, but don't want to make it part of this PR as there's relatively little time for me to do the remaining things that need to be done this week. Do you want to file an issue? Maybe we can do it in RC2.

**Review by javiercn — APPROVED** [review]
