### PR TITLE
fix #43523 Content-Length and Transfer-Encoding conflicts

### LINKED ISSUE #43523: Content-Length and Transfer-Encoding conflicts
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2
>    A sender MUST NOT send a Content-Length header field in any message
   that contains a Transfer-Encoding header field.

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.3
> If a message is received with both a Transfer-Encoding and a
       Content-Length header field, the Transfer-Encoding overrides the
       Content-Length.  Such a message might indicate an attempt to
       perform request smuggling ([Section 9.5](https://datatracker.ietf.org/doc/html/rfc7230#section-9.5)) or response splitting
       ([Section 9.4](https://datatracker.ietf.org/doc/html/rfc7230#section-9.4)) and ought to be handled as an error.  A sender MUST
       remove the received Content-Length field prior to forwarding such
       a message downstream.

Kestrel follows this today by honoring the `Transfer-Encoding: chunked` and ignoring the Content-Length header. However, the Content-Length header is still present on the request and apps may still be consuming it.
https://github.com/dotnet/aspnetcore/blob/94cc679bce4967568fd458433ecda3b3fb0578b6/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs#L146-L177

E.g. YARP has to check for this condition too to avoid a smuggling attempt when proxying.
https://github.com/microsoft/reverse-proxy/blob/06f28a36140543512a3fc3e1e9423094c43296ec/src/ReverseProxy/Forwarder/HttpTransformer.cs#L80-L92

App developers are not usually aware of spec nuances like this and write logic that makes decisions based on the Content-Length header when present. This can lead to application level functional and security issues like over/under buffering.

### Expected Behavior

Proposal: Kestrel should implement the following spec guideline "A sender MUST remove the received Content-Length field prior to forwarding such a message downstream.", treating the application as the downstream entity. If there is a Transfer-Encoding header then kestrel should remove any Content-Length header to avoid app level confusion.

Since Kestrel avoids modifying the request in most cases, giving the app as much of the original data as possible, we want to preserve the Content-Length header value by moving it to `x-Content-Length`. This should avoid people consuming the unvalidated value by accident, but it's still available for compat reasons.

YARP could remove its mitigation after this change.

### Steps To Reproduce

```
POST / HTTP/1.1
Content-Length: 500000
Transfer-Encoding: chunked

5
Hello
0
```

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

Recommended for .NET 8.

### PR DESCRIPTION
**Pull request by FatTigerWang**
# fix #43523 Content-Length and Transfer-Encoding conflicts

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Fixes #43523 Content-Length and Transfer-Encoding conflicts

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs [hunk 1]
```diff
@@ -159,6 +160,25 @@ protected async Task OnConsumeAsyncAwaited()
...
+            // If a message is received with both a Transfer-Encoding and a
+            // Content-Length header field, the Transfer-Encoding overrides the
+            // Content-Length.  Such a message might indicate an attempt to
+            // perform request smuggling (Section 9.5) or response splitting
+            // (Section 9.4) and ought to be handled as an error.  A sender MUST
+            // remove the received Content-Length field prior to forwarding such
+            // a message downstream.
+            // We should remove the Content-Length request header in this case, for compatibility
+            // reasons, increase x-Content-Length so that the original Content-Length is still available.
+            if (headers.ContentLength.HasValue)
```
Comment (FatTigerWang) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs:176]: I'm not quite sure if removing the request header addition is appropriate here, as it looks like this method is just for creating the MessageBody.

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs [hunk 2]
```diff
@@ -159,6 +160,25 @@ protected async Task OnConsumeAsyncAwaited()
...
+            {
+                context.RequestHeaders.Add($"x-{HeaderNames.ContentLength}", context.RequestHeaders[HeaderNames.ContentLength]);
+                context.RequestHeaders.Remove(HeaderNames.ContentLength);
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs:179]: Using the property is more efficient. Also, we don't want to re-create this string each time.
```suggestion
                headers.Add("X-Content-Length", headers[HeaderNames.ContentLength]);
                headers.ContentLength = null;
```

File: src/Servers/Kestrel/Core/test/Http1/Http1ConnectionTests.cs [hunk 3]
```diff
@@ -1014,6 +1015,23 @@ public void BadRequestFor11BadHostHeaderFormat()
...
+        // Arrange
+        string contentLength = "1024";
+        _http1Connection.RequestHeaders.Add(HeaderNames.ContentLength, contentLength);
+        _http1Connection.RequestHeaders.Add(HeaderNames.TransferEncoding, "chunked");
+
+        // Act
+        Http1MessageBody.For(Kestrel.Core.Internal.Http.HttpVersion.Http11, (HttpRequestHeaders)_http1Connection.RequestHeaders, _http1Connection);
+
+        // Assert
+        Assert.True(_http1Connection.RequestHeaders.ContainsKey($"x-{HeaderNames.ContentLength}"));
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/test/Http1/Http1ConnectionTests.cs:1030]: Also verify TransferEncoding

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs (hunk 2 above)
Comment (FatTigerWang) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs]: Here `headers.Add("X-Content-Length", headers[HeaderNames.ContentLength]);`, `headers[HeaderNames.ContentLength]` should be changed to use `headers.ContentLength`?

Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs]: I avoided that because headers.ContentLength is a long where the indexer returns a StringValues, and we need a StringValues.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks
