### PR TITLE
Fix recursive shadow copy

### LINKED ISSUE #31864: ShadowCopy dir set inside current dir causes recursive copies of itself
### Describe the bug
When enabling the new experimental shadowCopy, the startup time can be 2+ min.

### To Reproduce
Web.config:
```
               <handlerSetting name="experimentalEnableShadowCopy" value="true" />
               <handlerSetting name="shadowCopyDirectory" value="./ShadowCopyDirectory/" />
```

Repro code:

```
   [ApiController]
   public class MyController : ControllerBase
   {
      [HttpGet("Test")]
      public string Test() =>  "working";
   }
```

Published to "Folder", hosted in IIS in subfolder, "converted to application" on folder.

Occasionally after serving the first request (after the 2+min), it immediately shuts down and returns a 503 on the next request. The next request again triggers the 2+ min delay again.

The 503 might be a timing issue if requesting something right after making a change.

### Exceptions (if any)
Debug logs shows:
```
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\7.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```
or
```
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```

Then on the first request, this is added:
```
[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 14208.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.
```
Here it hangs for 2+ min... Then continues with:
```
[aspnetcorev2.dll] Resolving hostfxr parameters for application: '.\CdnAdmin.exe' arguments: '' path: 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8'
[aspnetcorev2.dll] Known dotnet.exe location: ''
[aspnetcorev2.dll] Process path '.\CdnAdmin.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2.dll] Checking application.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2.dll] Checking hostfxr.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll'
[aspnetcorev2.dll] hostfxr.dll not found at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet'
[aspnetcorev2.dll] Invoking where.exe to find dotnet.exe
[aspnetcorev2.dll] where.exe invocation returned: 'C:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe
'
[aspnetcorev2.dll] Current process bitness type detected as isX64=1
[aspnetcorev2.dll] Processing entry 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Binary type 6
[aspnetcorev2.dll] Found dotnet.exe via where.exe invocation at 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll'
[aspnetcorev2.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll' arguments:
[aspnetcorev2.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Argument[1] = 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll
[aspnetcorev2.dll] Canceling standard stream pipe reader
[aspnetcorev2.dll] Loading request handler:  'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.0-preview.3.21201.13\aspnetcorev2_inprocess.dll'
[aspnetcorev2.dll] Creating handler application
[aspnetcorev2_inprocess.dll] Initializing logs for 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.0-preview.3.21201.13\aspnetcorev2_inprocess.dll'. Process Id: 38756.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.
[aspnetcorev2_inprocess.dll] Waiting for initialization
[aspnetcorev2_inprocess.dll] Starting app_offline monitoring in application 'c:\src\Cdn\CdnAdmin\'
[aspnetcorev2_inprocess.dll] Starting file watcher thread
[aspnetcorev2_inprocess.dll] Starting in-process worker thread
[aspnetcorev2_inprocess.dll] Resolving hostfxr parameters for application: '.\CdnAdmin.exe' arguments: '' path: 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8'
[aspnetcorev2_inprocess.dll] Known dotnet.exe location: 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Process path '.\CdnAdmin.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2_inprocess.dll] Checking application.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2_inprocess.dll] Checking hostfxr.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll'
[aspnetcorev2_inprocess.dll] hostfxr.dll not found at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2_inprocess.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll'
[aspnetcorev2_inprocess.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll' arguments:
[aspnetcorev2_inprocess.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Argument[1] = 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_HTTPAUTH=anonymous;
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_PHYSICAL_PATH=c:\src\Cdn\CdnAdmin\
[aspnetcorev2_inprocess.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll
[aspnetcorev2_inprocess.dll] Initial Dll directory: '', current directory: 'c:\windows\system32\inetsrv'
[aspnetcorev2_inprocess.dll] Setting dll directory to c:\windows\system32\inetsrv
[aspnetcorev2_inprocess.dll] Setting current directory to c:\src\Cdn\CdnAdmin\
[aspnetcorev2_inprocess.dll] In-process callbacks set
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'c:\src\Cdn\CdnAdmin\' started successfully.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Adding request. Total Request Count 1
[aspnetcorev2_inprocess.dll] Removing Request 0
```

log when getting the 503:
```
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\9.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] Application went offline
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```
It doesnt show the "startup" line with
`[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 14208.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.` when showing the 503.

### Further technical details
- .net 6 preview 3

image
image
image

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/31864

### CODE REVIEW

**Review by jkotalik — APPROVED** [review]

File: src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp [hunk 1]
```diff
@@ -188,16 +188,17 @@ void Environment::CopyToDirectoryInner(const std::filesystem::path& source, cons
...
+            copiedFileCount++;
             CopyFile(path.path().wstring().c_str(), destinationPath.wstring().c_str(), FALSE);
         }
         else if (path.is_directory())
         {
             auto sourceInnerDirectory = path.path();
 
             // Make sure we aren't navigating into shadow copy directory.
-            if (sourceInnerDirectory.wstring().rfind(directoryToIgnore, 0) != 0)
+            if (!std::filesystem::equivalent(sourceInnerDirectory, directoryToIgnore))
```
Comment (jkotalik) [inline src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp:199]: Is there any way to check if we are nested in the directoryToIgnore as well? That may be a bit more protective.

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp:199]: That would be better, doesn't look like there is any nice api for it :(

Comment (jkotalik) [reply src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp:199]: I was hoping a "startsWith" check would be useful here.

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp:199]: Might be able to use https://en.cppreference.com/w/cpp/filesystem/path/compare, I'll have to test it a little to make sure it handles relative paths etc.

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/CommonLib/Environment.cpp:199]: I'm going back to the original code here, I think it is better since we make sure the path is absolute relative to the app path.

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp [hunk 2]
```diff
@@ -303,8 +303,18 @@ APPLICATION_INFO::HandleShadowCopy(const ShimOptions& options, IHttpContext& pHt
...
+        int copiedFileCount = 0;
+
         shadowCopyPath = shadowCopyPath / directoryNameStr;
-        HRESULT hr = Environment::CopyToDirectory(physicalPath, shadowCopyPath, options.QueryCleanShadowCopyDirectory(), std::filesystem::canonical(shadowCopyBaseDirectory.path()));
+        LOG_INFOF(L"Copying to shadow copy directory %ls.", shadowCopyPath.c_str());
+
+        // Avoid using canonical for shadowCopyBaseDirectory
+        // It could expand to a network drive, or an expanded link folder path
+        // We already made it an absolute path relative to the physicalPath above
+        HRESULT hr = Environment::CopyToDirectory(physicalPath, shadowCopyPath, options.QueryCleanShadowCopyDirectory(), shadowCopyBaseDirectory.path(), copiedFileCount);
```
Comment (jkotalik) [inline src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: Can shadowCopyBaseDirectory include '..', '.', etc. that would cause the rfind to return false though, even though they are equivalent paths?

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: No because we make it absolute above. I added a test with a ".." in it to verify.

Comment (jkotalik) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: Hm, interesting. The last commit I made in the implementation PR added canonical. https://github.com/dotnet/aspnetcore/pull/28357/commits/dca5ec4a9bdd71763ede9f12e31a81acf341ba9c#diff-300f4ab20a90b601a89471e5c5710667857a6d631e53d5d96d01c39538259122L307. I believe this was to fix an issue where the paths weren't equal with rfind.

Maybe we have the rfind check as well as `|| std::filesystem::equivalent`

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: I don't see why rfind by itself isn't good enough though

Comment (jkotalik) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: Are you sure calling absolute will remove '..' and '.'. The docs say absolute will not remove those. https://en.cppreference.com/w/cpp/filesystem/absolute. I'm just very suspicious of this change because this is effectively what I had prior to changing to canonical.

Comment (jkotalik) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp:314]: I just did some of verification locally on this, and I think maybe the difference was that before I was calling parent_path() on the absolute path [here](https://github.com/dotnet/aspnetcore/pull/28357/commits/dca5ec4a9bdd71763ede9f12e31a81acf341ba9c#diff-300f4ab20a90b601a89471e5c5710667857a6d631e53d5d96d01c39538259122L307).

Change LGTM now.
