### PR TITLE
Use Node-Fetch instead of Request for TS client

### LINKED ISSUE #19420: SignalR client depends on deprecated npm package "request"
The `@aspnet/signalr` npm package depends on the `request` package [npm](https://www.npmjs.com/package/request), which has been deprecated and is no longer maintained.

This might be causing Azure DevOps builds to fail with errors such as this one:
> Installing website NPM packages
> ##[error]npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> Finishing: Build Solution

However, the package does still appear to be available on npm, so the build could potentially have failed for other reasons.

The error message contains an issue link with additional details on the reasoning for deprecating the package and provides suggestions for alternatives.

Note: description has been updated to clarify that I am not sure about the DevOps relation.

### PR DESCRIPTION
**Pull request by BrennanConroy**
The `request` module has been deprecated, so we're taking this opportunity to share our fetch code with the browser and Node by using a fetch polyfill on Node.

Fixes https://github.com/dotnet/aspnetcore/issues/19420

### CODE REVIEW

File: src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts [hunk 1]
```diff
@@ -1,9 +1,36 @@
...
+
+    // Cookies aren't automatically handled in Node so we need to add a CookieJar to preserve cookies across requests
+    jar = new (requireFunc("tough-cookie")).CookieJar();
+    fetchType = requireFunc("node-fetch");
+
+    // node-fetch doesn't have a nice API for getting and setting cookies
+    // fetch-cookie will wrap a fetch implementation with a default CookieJar or a provided one
+    fetchType = requireFunc("fetch-cookie")(fetchType, jar);
+
+    // Node needs EventListener methods on AbortController which our custom polyfill doesn't provide
```
Comment (anurse) [inline src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: How complex would it be to add it to our polyfill?

File: src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts [hunk 2]
```diff
@@ -97,6 +124,15 @@ export class FetchHttpClient extends HttpClient {
             payload,
         );
     }
+
+    public getCookieString(url: string): string {
```
Comment (anurse) [inline src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: What's this for?

File: src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: Difficult because I have no idea how to work with the EventListener API.

Comment (anurse) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: I guess we can't just use https://nodejs.org/api/events.html because our polyfill still has to work on the browser.

File: src/SignalR/clients/ts/FunctionalTests/ts/Common.ts [hunk 3]
```diff
@@ -120,12 +118,7 @@ export function getHttpClients(): HttpClient[] {
     if (typeof XMLHttpRequest !== "undefined") {
         httpClients.push(new XhrHttpClient(TestLogger.instance));
     }
-    if (typeof fetch !== "undefined") {
```
Comment (halter73) [inline src/SignalR/clients/ts/FunctionalTests/ts/Common.ts]: Why stop checking if fetch is defined? Could this break scenarios that would work otherwise if XMLHttpRequest is defined, but fetch isn't?

Comment (halter73) [reply src/SignalR/clients/ts/FunctionalTests/ts/Common.ts]: Nvm. I see this is test code.

Comment (anurse) [reply src/SignalR/clients/ts/FunctionalTests/ts/Common.ts]: I think I'd still prefer to use `fetch` if it's defined rather than as a fallback. Almost all of our supported browsers have it (except IE 11).

File: src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts (hunk 2 above)
Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: It's the way we apply cookies to WebSockets and SSE

Comment (anurse) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: So where do we call it? I don't see it in the diff anywhere and it looks new.

Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: It isn't new. It just has a [default implementation](https://github.com/dotnet/aspnetcore/blob/e00a7c4d52107e8090d06d1345920ef3e39e3233/src/SignalR/clients/ts/signalr/src/HttpClient.ts#L163) and since the `FetchHttpClient` wasn't used in Node before it wasn't needed. But now it is.

One [usage](https://github.com/dotnet/aspnetcore/blob/e00a7c4d52107e8090d06d1345920ef3e39e3233/src/SignalR/clients/ts/signalr/src/ServerSentEventsTransport.ts#L66).

Comment (anurse) [reply src/SignalR/clients/ts/signalr/src/FetchHttpClient.ts]: Ah riiiiight. Ok, thanks for clearing that up. Just saw a new public API and was confused. There's a good reason C# has the `override` keyword ;P.

**Review by halter73 — APPROVED** [review]
