### PR TITLE
Handle JsonExceptions in RequestDelegateFactory

### LINKED ISSUE #36499: Route handlers throw System.Text.Json.JsonReader exception for requests with invalid JSON body rather than returning 422
Consider the following minimal API:
``` c#
app.MapPost("/todos", (Todo todo) =>
{
    // Do something with todo here...
});

class Todo
{
    public string? Text { get; set; }
}
```

Sending a request with invalid JSON body but that is otherwise well-formed results in a 500 response, due to the underlying JSON reader exception not being handled by the framework:

image

We should likely be returning a [422 Unprocessable Entity](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) instead.

### PR DESCRIPTION
**Pull request by halter73**
This change causes minimal API route handlers to respond with a "400 Bad Request" instead of "500 Internal Server Error" when given a request body with an `application/json` Content-Type but malformed JSON.

Before, we expected this to throw an `InvalidDataException` but malformed JSON results in a `JsonException` instead.

I plan to backport this to `release/6.0-rc2`.

Fixes #36499

### CODE REVIEW

**Comment by Tratcher** [comment]
InvalidDataException is what's thrown by the form parser. Was this accidentally copied from that code path?

**Comment by rafikiassumani-msft** [comment]
@halter73 are you returning 400 to be consistent with MVC? Any reason why we are not returning 422 ?

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -618,10 +624,10 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
                             Log.RequestBodyIOException(httpContext, ex);
                             return;
                         }
-                        catch (InvalidDataException ex)
+                        catch (Exception ex) when (ex is InvalidDataException || ex is JsonException)
```
Comment (captainsafia) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:627]: From looking at [the tests here](https://github.com/dotnet/aspnetcore/blob/f6efa13e71d3f82f149d9af8f7c47860d87ffa9c/src/Http/Http.Extensions/test/HttpRequestJsonExtensionsTests.cs) it looks like the deserialization process will throw one of three exceptions:

- InvalidOperationException
- JsonException
- TaskCancelledException

And [the docs for the JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserializeasync?view=net-5.0) indicate that it can also throw:

- NotSupportedException
- ArgumentNullException

I think for this case we probably want to catch the NotSupportedException and the JsonException since both indicate an inability to parse the response.

Comment (davidfowl) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:627]: Not sure about `NotSupportedException`. That one feels like it's an issue on the server side. You could imagine adding a converter, not changing the client's payload and things beginning to work all of a sudden.

Comment (halter73) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:627]: I think that the `JsonException` is the only thing listed that clearly points to the input being the error. All the rest looks like API misusage on the server or server-side cancellation.

**Comment by halter73** [comment]
> @halter73 are you returning 400 to be consistent with MVC? Any reason why we are not returning 422 ?

I mostly did this to be consistent with MVC and our current InvalidDataException behavior.

Also, the [rfc](https://datatracker.ietf.org/doc/html/rfc4918#section-11.2) claims

>   The 422 (Unprocessable Entity) status code means the server
>   understands the content type of the request entity (hence a
>   415(Unsupported Media Type) status code is inappropriate), and the
>   syntax of the request entity is correct (thus a 400 (Bad Request)
>   status code is inappropriate) but was unable to process the contained
>   instructions.  For example, this error condition may occur if an XML
>   request body contains well-formed (i.e., syntactically correct), but
>   semantically erroneous, XML instructions.

And I think JsonExceptions indicate the JSON is not "well-formed". A 422 would be more appropriate if the request was missing a required property or something like that (assuming that was something we supported).

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:627]: Fair enough. I agree with the sentiment that we can safely remove the check for `InvalidDataException` and just check for `JsonException`.

Comment (halter73) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs]: @captainsafia @Tratcher I've updated this to only catch JsonExceptions now.

**Comment by halter73** [comment]
@captainsafia Can you approve this PR too? Thanks!

**Review by BrennanConroy — APPROVED** [review]
