### PR TITLE
Optimize RouteTableFactory.DetectAmbiguous routes

### LINKED ISSUE #55114: DetectAmbiguousRoutes on RouteTableFactory doesn't scale well with large number of routes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The algorithm in DetectAmbiguousRoutes is too expensive and involves a lot of string comparison/init which doesn't fare well when running in WASM on Blazor.

### Expected Behavior

Initializing the Router should be quick and efficient even with thousands of Inbound Routes. Or, the detection of ambiguous routes should at least be optional and something you can disable.

### Steps To Reproduce

Run vnext of https://github.com/IgniteUI/igniteui-blazor-examples

As of commit 99125344f35b9c8df3ee3da1d55f1c539b139b2d

Maybe we will have worked around it in some way now that the hot area is identified. But it should exist as of that commit.

Make sure to run the client WASM head, and observe the time spent during startup. Also, make sure to follow the readme instructions on how to ingest all the individual samples into the combined browser, before running it.

If you want a simpler repro, I assume any project with sufficiently large number of routes running as WASM should trigger the problem.

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by andrewjsaid**
Make RouteTableFactory.DetectAmbiguous faster using a hash table after it was reported as slow in #55114

## Description

I've added a performance benchmark to the code with the routes found in https://github.com/IgniteUI/igniteui-blazor-examples as reported in original ticket. I am unsure as to whether that's appropriate please advise if I must change them.

**Before**

|           Method |     Mean |   Error |  StdDev |  Op/s |     Gen 0 |    Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|--------:|--------:|------:|----------:|---------:|------:|----------:|
| CreateRouteTable | 223.1 ms | 4.32 ms | 6.05 ms | 4.482 | 1000.0000 | 333.3333 |     - |    749 MB |

**After**
|           Method |     Mean |     Error |    StdDev |  Op/s |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|------:|-------:|------:|------:|----------:|
| CreateRouteTable | 3.889 ms | 0.0629 ms | 0.0588 ms | 257.1 | 7.8125 |     - |     - |      6 MB |

Fixes #55114

### CODE REVIEW

File: src/Components/Components/src/Routing/RouteTableFactory.cs [hunk 1]
```diff
@@ -334,4 +298,70 @@ internal static int RouteComparison(InboundRouteEntry x, InboundRouteEntry y)
             _ => throw new InvalidOperationException("Invalid comparison result."),
         };
     }
+
+    private class InboundRouteEntryEqualityComparer : IEqualityComparer<InboundRouteEntry>
```
Comment (campersau) [inline src/Components/Components/src/Routing/RouteTableFactory.cs:302]: Seal and use a singleton?
```suggestion
    private sealed class InboundRouteEntryEqualityComparer : IEqualityComparer<InboundRouteEntry>
```

Comment (andrewjsaid) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:302]: `sealed` sure but why use singleton if it will only ever be run once per app as far as I can tell?

File: src/Components/Components/perf/RouteTableFactoryBenchmarks.cs [hunk 2]
```diff
@@ -0,0 +1,2833 @@
...
+        _templatesByHandler = new Dictionary<Type, string[]>
+        {
+            { typeof(object), _routes }
+        };
+    }
+
+    [Benchmark]
+    public object CreateRouteTable() => RouteTableFactory.Create(_templatesByHandler, _serviceProvider);
+
+    private static readonly string[] _routes = [
```
Comment (halter73) [inline src/Components/Components/perf/RouteTableFactoryBenchmarks.cs:29]: Can this be dynamically generated to test different numbers of routes and segments? It might also be a good idea to include some routes with `{routeValues}` even though the comparison ignores them.

**Comment by andrewjsaid** [comment]
With new benchmark (dynamically generated routes) on latest commit I have these numbers.

**Before**
```
|           Method |     Mean |   Error |  StdDev |  Op/s |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|--------:|--------:|------:|----------:|------:|------:|----------:|
| CreateRouteTable | 208.6 ms | 3.92 ms | 3.66 ms | 4.794 | 1000.0000 |     - |     - |    619 MB |
```

**After**
```
|           Method |     Mean |     Error |    StdDev |  Op/s |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|------:|-------:|------:|------:|----------:|
| CreateRouteTable | 5.226 ms | 0.1043 ms | 0.1356 ms | 191.3 | 7.8125 |     - |     - |      7 MB |
```

File: src/Components/Components/test/Routing/RouteTableFactoryTests.cs [hunk 3]
```diff
@@ -1029,8 +1029,10 @@ public void DoesNotThrowIfStableSortComparesRouteWithItself()
     [Theory]
     [InlineData("/literal", "/Literal/")]
     [InlineData("/{parameter}", "/{parameter}/")]
+    [InlineData("/{parameter}part", "/part{parameter}")]
```
Comment (andrewjsaid) [inline src/Components/Components/test/Routing/RouteTableFactoryTests.cs:1032]: Here's an interesting case I wanted to document in tests. In this case the route is counted as duplicate even though it's debatable if parameter is non-empty.

To be clear all tests were run before and after and pass in both.

Comment (javiercn) [reply src/Components/Components/test/Routing/RouteTableFactoryTests.cs:1032]: It's ambiguous because if we sent "/partpart" will match both.

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
@andrewjsaid thanks for the contribution!
