### PR TITLE
[Blazor] Emit action attribute when not explicit.

### LINKED ISSUE #51118: Opaque redirect handler results in message "Error: 405 Method Not Allowed" in Blazor app
Repro app: https://github.com/DamianEdwards/BlazorFormFun

.NET SDK version: 8.0.100-rc.2.23472.8

I have a Blazor app that's built to simulate an online store, listing items from a catalog, with the capability to add items to a cart/basket. The app is using Blazor SSR with streaming rendering, enhanced navigation & form handling. There is no interactive rendering enabled. Calls to load products, add an item to the cart, get the current cart item count, etc. are async and introduce async delay in order to simulate remote call processing. The availability of the cart itself is delayed to simulate only showing cart UX if the cart service can be successfully called.

When running the application and rapidly clicking the "Add to cart" buttons, an error can be shown in the browser. Note it can take dozens of clicks to reproduce the issue. Opening the browser dev tools network window can sometimes reduce the number of clicks required to reproduce the issue.

image

I've tried to reduce the repro but this is as far as I could go while still having the issue occur.

### PR DESCRIPTION
**Pull request by javiercn**
This change updates the server rendering logic to always emit an absolute URL for a form action when none is specified explicitly.

## Description

When as part of rendering a form, the developer does not explicitly add an `action` attribute, the framework will automatically generate one with the value of the current request URL.

Fixes #51118

## Customer Impact

When enhanced navigation is active, the URL might change while an update to the page is in progress. In such situations, if the user clicks a button and submits a form, the form might incorrectly post to the wrong URL, as the page URL might have already been updated. 

Given that when the URL updates on the document is not a behavior, we have control over, we have to account for this, and to prevent it, we make sure that we always generate forms with an action attribute, which is unambiguous.

## Regression?

- [ ] Yes
- [X] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [X] Low

The fix is to detect forms without an `action` attribute and emit it to the current URL. This is correct in all cases and is unambiguous.

## Verification

- [x] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs [hunk 1]
```diff
@@ -323,7 +338,22 @@ private static bool TryFindEnclosingElementFrame(ArrayRange<RenderTreeFrame> fra
...
+
+        void EmitFormActionIfNotExplicit(TextWriter output, bool isForm, bool hasExplicitActionValue)
+        {
+            if (isForm && !hasExplicitActionValue)
+            {
+                output.Write(' ');
+                output.Write("action");
+                output.Write('=');
+                output.Write('\"');
+                _htmlEncoder.Encode(output, _navigationManager.Uri);
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:353]: Do we know this always matches the client's view of the URL? Just want to be sure that in URL-rewriting scenarios this doesn't generate a wrong URL. In particular in cases where people are using K8s or similar and have some HTTP ingress that forwards https://mysite.com/abc to http://internal:1234/abc

Comment (SteveSandersonMS) [reply src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:353]: If we know `_navigationManager.Uri` is always a relative URL then that's likely good enough, but ideally we'd do the same as whatever MVC/Razor Pages do for setting a form `action`.

Comment (SteveSandersonMS) [reply src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:354]: They have to account for `X-Forwarded-For` or whatever otherwise it would be broken, wouldn't it?

I don't think we can safely emit absolute URLs here, at least not ones that just come naively from `HttpContext.Request`.

Comment (javiercn) [reply src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:354]: > It doesn't solve more complex URL rewriting which is why I wondered what MVC/Razor Pages do - maybe they just don't try to solve that, in which case I'd be fine with limiting it to just returning root-relative URLs.

We don't need to solve this problem. Apps need to have correctly setup their forwarding headers if behind a proxy. That's what routing relies on too for link generation. Whatever is on HttpContext is expected to be externally reachable

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 2]
```diff
@@ -148,6 +149,15 @@ export async function performEnhancedPageLoad(internalDestinationHref: string, f
...
   currentEnhancedNavigationAbortController = new AbortController();
+  if (currentUrl) {
+    currentEnhancedNavigationAbortController.signal.addEventListener('abort', () => {
+      // If the navigation was aborted, we need to revert the URL change
+      if (location.href === internalDestinationHref && location.href !== currentUrl) {
+        history.replaceState(null, /* ignored title */ '', currentUrl);
+      }
+    }, { once: true });
+  }
+
```
Comment (javiercn) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:160]: The rationale behind this is:
* Capture the URL before it gets changed by clicking a link.
* Pass it down to the code that performs the actual page load.
* If the load is cancelled, then another enhanced nav has replaced this one.
* Check if the thing that triggered the cancellation already updated the URL
* If it didn't, and the current url is different from the previous url, then re-apply the old url.

I think this might still not handle forms that explicitly target a different endpoint, but I haven't tried that yet. We can probably tweak the behavior based on the presence of fetchOptions

File: src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:354]: OK good

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:160]: Unfortunately I don't think this covers it. Various things can still go wrong, e.g.:

 * Enhanced navigation isn't always triggered by a link click. It can also be triggered by back/forwards, at which point the "current URL" has already changed before you got a chance to capture it. Or it could be triggered by a different form submission.
 * Replacing the URL via `replaceState` is going to corrupt the history stack even further. This code doesn't know how many times the user did back/forwards, so there's no way to say if replacing the current history entry will produce the desired result or will just create further weirdness if you do a later back/forwards

Let's discuss this offline. Hopefully we can find a different way of constraining the problem so that there aren't so many edge cases.

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 3]
```diff
@@ -217,10 +221,23 @@ export async function performEnhancedPageLoad(internalDestinationHref: string, f
...
+        // If this is the result of a form post that didn't trigger a redirection.
+        if (!isForSamePath(response)) {
+          // In this case we don't want to push the currentContentUrl to the history stack because we don't know if this is a location
+          // we can navigate back to (as we don't know if the location supports GET) and we are not able to replicate the Resubmit form?
+          // browser behavior.
+          // The only case where this is acceptable is when the last content URL, is the same as the URL for the form we posted to.
+          isNonRedirectedPostToADifferentUrlMessage = `Cannot perform enhanced form submission that changes the URL (except via a redirection), because then back/forward would not work. Either remove this form\'s \'action\' attribute, or change its method to \'get\', or do not mark it as enhanced.\nOld URL: ${location.href}\nNew URL: ${response.url}`;
+        } else {
+          // The url on the browser might be out of data, so push an entry to the stack to update the url in place.
+          history.pushState(null, '', currentContentUrl);
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:234]: I think you'll have to do that conditionally (i.e., only if `location.href !== currentContentUrl`) otherwise it will keep appending duplicate URLs to the history stack.

Note that I checked and `history.pushState(null, '', location.href)` is *not* a no-op. It really does append duplicates, making 'back' hard to use.

File: src/Components/Web/test/HtmlRendering/HtmlRendererTest.cs [hunk 4]
```diff
@@ -649,21 +642,19 @@ public async Task RenderComponentAsync_CanPassParameters()
...
-                "<", "p", ">", "<", "input", " ", "value", "=", "\"", "5", "\"", " />", "</", "p", ">" };
+                "<", "p", ">", "<", "input", " ", "configure", "=", "\"", "5", "\"", " />", "</", "p", ">" };
 
         RenderFragment Content(ParameterView pc) => new RenderFragment((RenderTreeBuilder rtb) =>
         {
             rtb.OpenElement(0, "p");
             rtb.OpenElement(1, "input");
             rtb.AddAttribute(2, "change", pc.GetValueOrDefault<Action<ChangeEventArgs>>("update"));
-            rtb.AddAttribute(3, "value", pc.GetValueOrDefault<int>("value"));
+            rtb.AddAttribute(3, "configure", pc.GetValueOrDefault<int>("configure"));
```
Comment (SteveSandersonMS) [inline src/Components/Web/test/HtmlRendering/HtmlRendererTest.cs:652]: Out of interest, is there some reason this attribute name needed to change? Just want to check there isn't some actual product behavioral change this represents.

Comment (javiercn) [reply src/Components/Web/test/HtmlRendering/HtmlRendererTest.cs:652]: No, it's a bug in the find/replace stuff. I thought I had "cleaned" up all the places it messed up. I'll fix it

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts (hunk 3 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:234]: @SteveSandersonMS you are right.

I'm not able to run the tests from VS, so I am trying to work this out on the CI and will update the PR when its ready. I still need to make sure the back button works.

File: src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs [hunk 5]
```diff
@@ -160,6 +160,11 @@ private static void MapEnhancedNavigationEndpoints(IEndpointRouteBuilder endpoin
             return Results.Ok(value);
         });
 
+        endpoints.Map("/forms/endpoint-that-never-finishes-rendering", (HttpResponse response, CancellationToken token) =>
+        {
+            return Task.Delay(Timeout.Infinite, token);
```
Comment (SteveSandersonMS) [inline src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs:165]: Might this have any negative effects on running the E2E tests? The server will permanently think there's an ongoing request.

It's not that I have specific knowledge this will cause any problems. Just checking you think the server will still gracefully exit at the right time.

If necessary this could be changed to just delay for 10 seconds, say, since that would easily be enough to show the behavior we're testing.

**Review by SteveSandersonMS — APPROVED** [review]
Since you've confirmed you'll deal with the duplicate history entries thing, I'm happy to approve now and leave it with you to address the final bits.

File: src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/test/testassets/Components.TestServer/RazorComponentEndpointsStartup.cs:165]: No, it will actually get cancelled when the connection is aborted by the browser, that's why I am passing the cancellation token.
