### PR TITLE
Do not close connection for http1.0 when client request connection keep-alive

### LINKED ISSUE #56223: Connection Close Behavior on HTTP1.0 Requests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/83573c72d12e1c2018805bc5d461d730bcb9dcc4/src/Servers/HttpSys/src/RequestProcessing/Response.cs#L406

> if (requestVersion <= Constants.V1_0 // Http.Sys does not support "Keep-Alive: true" or "Connection: Keep-Alive"

The comment in the code indicates http.sys does not support "Connection: Keep-Alive". However, we certainly see that header got to work in IIS, so the comment might be wrong. Thus, we want to change the behavior so that it aligns with IIS.

The reason we want to change this behavior on the server-side is that we don't want to keep closing connections on every request for http1.0, that will increase TLS costs on our end for subsequent re-connects. Given http1.0 traffic is not trivial amount.

### Expected Behavior

If the request is http1.0 AND the request contains "Connection: keep-alive", we also send the "Connection: keep-alive" header in the response.

### Steps To Reproduce

Send http 1.0 request using curl to ASP.NET endpoint with "Connection: keep-alive" header
> curl.exe --http1.0 -i <ASP.NET endpoint uri> -H "Connection: keep-alive"

From the response, you'll see the "Connection: close" header.

### Exceptions (if any)

_No response_

### .NET Version

6.0.131

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaozhao018**
# Do not close connection for http1.0 when client request connection keep-alive

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

The comment in the code indicates http.sys does not support "Connection: Keep-Alive". However, we certainly see that header got to work in IIS, so the comment might be wrong. Thus, we want to change the behavior so that it aligns with IIS.

The reason we want to change this behavior on the server-side is that we don't want to keep closing connections on every request for http1.0, that will increase TLS costs on our end for subsequent re-connects. Given http1.0 traffic is not trivial amount.

The expected behavior would be - If the request is http1.0 AND the request contains "Connection: keep-alive", we also send the "Connection: keep-alive" header in the response.

Fixes #56223 (in this specific format)

### CODE REVIEW

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs [hunk 1]
```diff
@@ -221,7 +220,28 @@ public async Task ResponseHeaders_HTTP10KeepAliveRequest_Gets11Close()
...
+            var context = await server.AcceptAsync(Utilities.DefaultTimeout).Before(responseTask);
+            context.Response.Headers["Transfer-Encoding"] = new string[] { "chunked" };
+            var responseBytes = Encoding.ASCII.GetBytes("10\r\nManually Chunked\r\n0\r\n\r\n");
+            await context.Response.Body.WriteAsync(responseBytes, 0, responseBytes.Length);
+            context.Dispose();
+
+            HttpResponseMessage response = await responseTask;
+            response.EnsureSuccessStatusCode();
+            Assert.Equal(new Version(1, 1), response.Version);
+            Assert.True(response.Headers.TransferEncodingChunked.HasValue, "Chunked");
```
Comment (BrennanConroy) [inline src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:244]: This should be checking for close?

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs [hunk 2]
```diff
@@ -403,7 +404,12 @@ internal uint ComputeHeaders(long writeCount, bool endOfRequest = false)
 
         // Determine if the connection will be kept alive or closed.
         var keepConnectionAlive = true;
-        if (requestVersion <= Constants.V1_0 // Http.Sys does not support "Keep-Alive: true" or "Connection: Keep-Alive"
+
+        // An HTTP/1.1 server may also establish persistent connections with
+        // HTTP / 1.0 clients upon receipt of a Keep-Alive connection token.
+        // However, a persistent connection with an HTTP/1.0 client cannot make
+        // use of the chunked transfer-coding. From: https://www.rfc-editor.org/rfc/rfc2068#section-19.7.1
+        if ((requestVersion <= Constants.V1_0 && (!requestConnectionKeepAliveSet || responseChunkedSet))
```
Comment (BrennanConroy) [inline src/Servers/HttpSys/src/RequestProcessing/Response.cs:412]: We should check for Http/0.9 and not set keep-alive in that case too.

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs [hunk 3]
```diff
@@ -403,7 +404,12 @@ internal uint ComputeHeaders(long writeCount, bool endOfRequest = false)
 
         // Determine if the connection will be kept alive or closed.
         var keepConnectionAlive = true;
-        if (requestVersion <= Constants.V1_0 // Http.Sys does not support "Keep-Alive: true" or "Connection: Keep-Alive"
+
+        // An HTTP/1.1 server may also establish persistent connections with
+        // HTTP / 1.0 clients upon receipt of a Keep-Alive connection token.
```
Comment (BrennanConroy) [inline src/Servers/HttpSys/src/RequestProcessing/Response.cs:409]:
```suggestion
        // HTTP/1.0 clients upon receipt of a Keep-Alive connection token.
```

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs (hunk 2 above)
Comment (BrennanConroy) [reply src/Servers/HttpSys/src/RequestProcessing/Response.cs:412]: Also, let's put this addition behind an opt-in feature flag since Http/1.0 + Keep-Alive isn't the most well-defined feature.
See https://github.com/dotnet/aspnetcore/blob/59d4050e7a26326764aa0f008b378f0adbc40efa/src/Caching/StackExchangeRedis/src/RedisCacheOptions.cs#L57 as an example. Probably call it something like "Microsoft.AspNetCore.Server.HttpSys.AllowHttp10KeepAlive"?

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs [hunk 4]
```diff
@@ -221,6 +220,28 @@ public async Task ResponseHeaders_HTTP10KeepAliveRequest_Gets11Close()
             HttpResponseMessage response = await responseTask;
             response.EnsureSuccessStatusCode();
             Assert.Equal(new Version(1, 1), response.Version);
+            Assert.Null(response.Headers.ConnectionClose);
```
Comment (halter73) [inline src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:223]: Ideally, we'd verify that not only was the `Connection: close` header not sent, but that the underlying socket wasn't closed. The easiest way to verify this would probably be to hook [SocketsHttpHandler.ConnectCallback](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-8.0) and verify that it was only called once for 2 requests.

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs (hunk 1 above)
Comment (halter73) [reply src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:244]: Isn't that on the next line? `Assert.True(response.Headers.ConnectionClose.Value);`?

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs (hunk 2 above)
Comment (halter73) [inline src/Servers/HttpSys/src/RequestProcessing/Response.cs:412]: I didn't know the bit about HTTP/1.0 clients not being allowed to use chunked transfer encoding on HTTP/1.1 keep-alive connections. The updated sections in [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-19.6.2) and [RFC 9112](https://www.rfc-editor.org/rfc/rfc9112#appendix-C.2.2) seem to be less opinionated, but they reference RFC 2068, so it seems like a good idea to play it safe and close the connection in the "responseChunkedSet" case.

I think we should do the same thing in Kestrel:

https://github.com/dotnet/aspnetcore/blob/59d4050e7a26326764aa0f008b378f0adbc40efa/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1145-L1155

We could add the following and a test to keep the behaviors of Http.Sys and Kestrel aligned:

```csharp
if (hasTransferEncoding && _httpVersion == Http.HttpVersion.Http10)
{
    _keepAlive = false;
}
```

It might also be a good idea to have HttpSys do the `HttpHeaders.GetFinalTransferCoding(responseHeaders.HeaderTransferEncoding) != TransferCoding.Chunked` check that Kestrel does and disable keep-alive connections even for HTTP/1.1 due to RFC 7230 3.3.1.

I also don't think `var responseChunkedSet = Matches(Constants.Chunked, transferEncodingString);` properly handles things like apps that manually set something like `Transfer-Encoding: gzip, chunked`, so it's probably good to call `HttpHeaders.GetFinalTransferCoding` just to fix the other logic that relies on `responseChunkedSet`.

Comment (halter73) [reply src/Servers/HttpSys/src/RequestProcessing/Response.cs:412]: I don't think this needs to be opt-in since it aligns closer to the current behavior Kestrel and IIS which both already allow HTTP/1.0 keep-alive connections.

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs (hunk 4 above)
Comment (xiaozhao018) [reply src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs]: Good point, added the verification

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs (hunk 1 above)
Comment (xiaozhao018) [reply src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:270]: Fixed now.

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs (hunk 2 above)
Comment (xiaozhao018) [reply src/Servers/HttpSys/src/RequestProcessing/Response.cs:412]: > We should check for Http/0.9 and not set keep-alive in that case too.

I'm leaning towards not touching Http/0.9 as the change is intended for Http/1.0. Let me know if that makes sense.

> I don't think this needs to be opt-in since it aligns closer to the current behavior Kestrel and IIS which both already allow HTTP/1.0 keep-alive connections.

Agreed. I thought about using feature flag but I didn't go down that path for the same reason.

Comment (xiaozhao018) [reply src/Servers/HttpSys/src/RequestProcessing/Response.cs:413]: Moved HttpHeaders.GetFinalTransferCoding into StringUtilities as a shared source between the projects. And fix the other logic that relies on responseChunkedSet. I'll leave the Kestrel changes to a separate PR.

**Review by halter73 — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]
