### PR TITLE
Set Content-Type more accurately in SignalR TS client

### LINKED ISSUE #41378: SignalR: Content-Type header in GET requests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WAF is flagging signalR long polling requests due to them having the Content-Type header on GET requests.

The issues was also report on the old code base: https://github.com/SignalR/SignalR/issues/4373

### Expected Behavior

There should be no content-type header for SignalR long polling GET requests.

### Steps To Reproduce

Use a long polling TypeScript client to communicate to a signalR hub.
Inspect the long polling requests in the developer tools of the browser and you see that the GET requests have a content type set.
"Content-Type": "text/plain;charset=UTF-8",

### Exceptions (if any)

_No response_

### .NET Version

.NET 6

### Anything else?

Ideally I would like to see POST requests and then also move the access token from the query string to the body of the request.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/41378 and https://github.com/dotnet/aspnetcore/issues/34537

| | Before | After |
| - | - | - |
| no content | "text/plain;charset=UTF-8" | `<none>` |
| binary content | "text/plain;charset=UTF-8" | "application/octet-stream" |
| text content | "text/plain;charset=UTF-8" | "text/plain;charset=UTF-8" |

Tested against react-native android which is where we previously had issues with content-type, this change works with that environment.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Ping

File: src/SignalR/clients/ts/FunctionalTests/ts/HubConnectionTests.ts [hunk 1]
```diff
@@ -1019,29 +1019,6 @@ describe("hubConnection", () => {
         }
     });
 
-    it("populates the Content-Type header when sending XMLHttpRequest", async () => {
```
Comment (halter73) [inline src/SignalR/clients/ts/FunctionalTests/ts/HubConnectionTests.ts:1022]: Why did we need to delete this test? I thought this should still work for long polling sends with a JSON payload.

**Review by halter73 — APPROVED** [review]

File: src/SignalR/clients/ts/FunctionalTests/ts/HubConnectionTests.ts (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/clients/ts/FunctionalTests/ts/HubConnectionTests.ts:1022]: The send http requests don't affect the headers visible from the Hub
