### PR TITLE
Skip h2spec test enumeration on unsupported platforms 

### LINKED ISSUE #38794: Interop.Functional tests failing on Debian 11 arm
Debian 11 isn't a recognized OS it looks like which the test discoverer can't handle

Here's the fallthrough exception:

https://github.com/dotnet/aspnetcore/blob/a32dde1438404a98ec437e249f43666cd4001170/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs#L65

## Failing Test(s)

- Interop.FunctionalTests

## Error Message

```text
[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS
   at Interop.FunctionalTests.H2SpecCommands.GetToolLocation() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 65
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 71
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 64
```

## Stacktrace

<details>

```text
[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS
   at Interop.FunctionalTests.H2SpecCommands.GetToolLocation() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 65
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 71
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 64
```
</details>

## Logs

<details>

[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-80d93324627e4f1ea9/Interop.FunctionalTests--net7.0/1/console.11ec61c9.log?sv=2019-07-07&se=2021-12-22T13%3A00%3A08Z&sr=c&sp=rl&sig=Dkh%2F8MeAYRycAp%2FJeFwwgi4YTOspIani5DX8s6NtBO0%3D

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1493839&view=ms.vss-test-web.build-test-results-tab&runId=42666076&resultId=119419&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by Tratcher**
Fixes #38794

Test build: https://dev.azure.com/dnceng/public/_build/results?buildId=1494828&view=results

### CODE REVIEW

File: src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs [hunk 1]
```diff
@@ -50,8 +50,14 @@ private static string GetToolLocation()
         {
             return Path.Combine(root, "windows", "h2spec.exe");
         }
-        else if (OperatingSystem.IsLinux() && (RuntimeInformation.OSArchitecture == Architecture.X64))
+        else if (OperatingSystem.IsLinux())
         {
+            if (RuntimeInformation.OSArchitecture != Architecture.X64)
```
Comment (HaoK) [inline src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:55]: Will this be an issue on other non linux machines possibly in the future?

**Comment by Tratcher** [comment]
The test build passed, this should be ready to go.

**Review by HaoK — APPROVED** [review]
