### PR TITLE
Throw for bad requests intended for minimal route handlers in development

### LINKED ISSUE #35857: DeveloperExceptionPageMiddleware should set response status code from BadHttpRequestException
If the exception caught by `DeveloperExceptionPageMiddleware` is of type `BadHttpRequestException`, it should set the response status code to the value of `BadHttpRequestException.StatusCode` rather than 500.

### LINKED ISSUE #35858: RequestDelegateFactory should throw BadHttpRequestException when in development to make diagnosing handler issues easier
When using the new "Map*" methods to build minimal APIs via the `RouteDelegateFactory`, it can be difficult to diagnose the cause of 400 and 415 responses that are implicitly returned when the mapped route handler's parameters cannot be satisfied from the request, either via the implicit parameter binding behavior or `TryParse' and 'BindAsync` methods on the parameter target types.

It would be helpful if when in development (i.e. `Environment.IsDevelopment() == true`) instead of implicitly returning the response with a 4xx status code, a `BadHttpRequestException` was thrown instead, with the relevant status code set and an appropriate exception message added, making it clear why the exception/status code is being throw/set. With the `DeveloperExceptionPageMiddleware` on (which it is by default in development in .NET 6 when using `WebApplication`) the exception message and stack trace will be returned in the response body, making it much clearer why the invocation of the route handler failed.

This behavior should be controllable via a new options type `RouteHandlerOptions` with boolean property `ThrowOnBadRequest` that is configured by default to be `true` when `Environment.IsDevelopmet()` is true. The default configuration would be achieved via an internal type implementing `IConfigureOptions<RouteHandlerOptions>` that is registered in DI when `IServiceCollection.AddRouting()` is called.

Related:
- #35856
- #35857

## Proposed APIs
``` diff
namespace Microsoft.AspNetCore.Routing
{
+    public class RouteHandlerOptions
+    {
+        public bool ThrowOnBadRequest { get; set; }
+    }
}

namespace Microsoft.AspNetCore.Http
{
    public class RequestDelegateFactoryOptions
    {
+        public bool ThrowOnBadRequest { get; init; }
    }
}
```

## Example usage
``` c#
var builder = WebApplication.CreateBuilder(args);

// Enable exceptions for implicit 4xx responses in custom "LocalDev" environment
var isDev = app.Environment.IsDevelopment() || app.Environment.IsEnvironemnt("LocalDev");
builder.Services.Configure<RouteHandlerOptions>(options => options.ThrowOnBadRequest = isDev);

var app = builder.Build();
```

### LINKED ISSUE #35954: UseDeveloperExceptionPage plain-text response should set charset
### Describe the bug
In ASP.NET Core 3.0 and later, the Developer Exception Page displays a plain-text response if the client doesn't request HTML-formatted output. The problem is, when display plain-text response, there is no charset set, just "Content-Type: text/plain" causing garbled when view the text but HTML-formatted output will set with "Content-Type: text/html; charset=utf-8" works.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

### PR DESCRIPTION
**Pull request by halter73**
Now instead of having to enable debug logging in development to see why a request is failing with a 400 response, you can easily see why the request is being rejected using the developer exception page or error logs.

This updates the DeveloperExceptionPageMiddleware to preserve the status code requested by the BadHttpRequestException instead of always responding with a 500. This way, the client can still get a 400 response in development but also get more error details.

This also updates the log messages (and the matching Exception messages) to use TypeNameHelper to produce friendlier parameter type names. And this includes the changes from https://github.com/dotnet/aspnetcore/pull/35580 which I'll close in favor of this.

image

Fixes #35858
Fixes #35857
Fixes #35954

### CODE REVIEW

File: src/Http/Routing/src/ConfigureRouteHandlerOptions.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using Microsoft.Extensions.Hosting;
+using Microsoft.Extensions.Options;
+
+namespace Microsoft.AspNetCore.Routing
+{
+    internal class ConfigureRouteHandlerOptions : IConfigureOptions<RouteHandlerOptions>
```
Comment (Kahbazi) [inline src/Http/Routing/src/ConfigureRouteHandlerOptions.cs:14]:
```suggestion
    internal sealed class ConfigureRouteHandlerOptions : IConfigureOptions<RouteHandlerOptions>
```

File: src/Http/Routing/src/ConfigureRouteHandlerOptions.cs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+        private readonly IHostEnvironment _environment;
+
+        public ConfigureRouteHandlerOptions(IHostEnvironment environment)
+        {
+            _environment = environment;
+        }
+
+        public void Configure(RouteHandlerOptions options)
+        {
+            options.ThrowOnBadRequest = _environment.IsDevelopment();
```
Comment (Kahbazi) [inline src/Http/Routing/src/ConfigureRouteHandlerOptions.cs:25]: Should it be like this, in case someone calls configure before `AddRouting`?
```suggestion
            if (_environment.IsDevelopment())
            {
                options.ThrowOnBadRequest = true;
            }
```

**Comment by davidfowl** [comment]
2 things:
- We should do an API review cc @pranavkm 
- We shouldn't log debug and throw. I think it should be one or the other.

File: src/Middleware/Diagnostics/test/UnitTests/DeveloperExceptionPageMiddlewareTest.cs [hunk 3]
```diff
@@ -117,12 +115,47 @@ public async Task ErrorPageWithoutAcceptHeaderForHtmlReturnsPlainText()
...
+                .ConfigureWebHost(webHostBuilder =>
+                {
+                    webHostBuilder
+                    .UseTestServer()
+                    .Configure(app =>
+                    {
+                        app.UseDeveloperExceptionPage();
+                        app.Run(context =>
+                        {
+                            throw new BadHttpRequestException("Not found!", 404);
```
Comment (Tratcher) [inline src/Middleware/Diagnostics/test/UnitTests/DeveloperExceptionPageMiddlewareTest.cs:140]: 404 is awkward because that's actually used elsewhere in the stack. Always test with 418 😁. 
Also use the constant here.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
> * We shouldn't log debug and throw. I think it should be one or the other.

Agreed, the dev exception page or the server will log at the error level when it catches.

**Review by davidfowl — APPROVED** [review]

File: src/Http/Routing/src/DependencyInjection/RoutingServiceCollectionExtensions.cs [hunk 4]
```diff
@@ -98,6 +98,10 @@ public static IServiceCollection AddRouting(this IServiceCollection services)
             //
             services.TryAddSingleton<TemplateBinderFactory, DefaultTemplateBinderFactory>();
             services.TryAddSingleton<RoutePatternTransformer, DefaultRoutePatternTransformer>();
+
+            // if (_environment.IsDevelopment()) RouteHandlerOptions.ThrowOnBadRequest = true;
```
Comment (davidfowl) [inline src/Http/Routing/src/DependencyInjection/RoutingServiceCollectionExtensions.cs:102]: Maybe an english comment 😄

File: src/Http/Routing/src/Builder/DelegateEndpointRouteBuilderExtensions.cs [hunk 5]
```diff
@@ -168,10 +170,14 @@ public static class DelegateEndpointRouteBuilderExtensions
                 routeParams.Add(part.Name);
             }
 
+            // REVIEW: Should we just default ThrowOnBadRequest to false if Options is somehow missing?
```
Comment (davidfowl) [inline src/Http/Routing/src/Builder/DelegateEndpointRouteBuilderExtensions.cs:173]: I think we should do this (treat null as no options).
