### PR TITLE
Handle exceptions thrown by PEReader

### LINKED ISSUE #14609: PortablePdbReader/ExceptionDetailsProvider may throw an exception which causes problems in callers like DeveloperExceptionPageMiddleware
### Describe the bug
`PortablePdbReader.GetPdbPath()` calls `PEReader.ReadDebugDirectory()` but doesn't handle exceptions that this call might throw. This in turn will then cause problems for callers higher up in the call stack, like `DeveloperExceptionPageMiddleware` or [Hellang.Middleware.ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails) which call it via `ExceptionDetailsProvider.GetDetails`.

### To Reproduce
1. Using version 2.2 or 3.0 of ASP.NET Core
2. Add a reference to [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) to the project (the current version is 19.3.1, future versions might not be affected)
3. Add the packages `Microsoft.Extensions.StackTrace.Sources` and `Microsoft.Extensions.TypeNameHelper.Sources` (via https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json)
4. Run this code:
``` cs
try
{
    // Trigger an exception inside Oracle.ManagedDataAccess.dll
    using (var conn = new OracleConnection())
    {
        conn.Open();
    }
}
catch (Exception ex)
{
    var provider = new ExceptionDetailsProvider(env.ContentRootFileProvider, 10);
    foreach (var detail in provider.GetDetails(ex))
    {
        // Would do something with 'detail' here.
    }
}
```
5. See this exception in the DeveloperExceptionPage:
```
System.BadImageFormatException: Invalid directory size.
   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath(String assemblyPath) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 99
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetMetadataReader(String assemblyPath) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 72
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 27
   at Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\StackTraceHelper.cs:line 61
   at Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.GetDetails(Exception exception)+MoveNext() in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\ExceptionDetails\ExceptionDetails\ExceptionDetailsProvider.cs:line 30
```
6. Remove the try-catch block around the code that triggers the exception.
7. See that the DeveloperExceptionPage is empty. Instead the following exception is written to the output window:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An exception was thrown attempting to display the error page.

System.BadImageFormatException: Invalid directory size.
   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath(String assemblyPath)
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetMetadataReader(String assemblyPath)
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset)
   at Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception)
   at Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.GetDetails(Exception exception)+MoveNext()
   at Microsoft.AspNetCore.Diagnostics.RazorViews.ErrorPage.ExecuteAsync()
   at Microsoft.Extensions.RazorViews.BaseView.ExecuteAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Expected behavior
No exception should be thrown while getting the details of another exception. If the exception details can't be collected, show as many details as possible, but don't fail.

### Additional context
It is important to use [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) to reproduce the problem. [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/) will **not** cause the problem! It looks like Oracle.ManagedDataAccess is obfuscated and I assume that causes the exception in `PEReader.ReadDebugDirectory()`.
To explain why I use the non-core version of Oracle.ManagedDataAccess: I initially found this in an solution that runs ASP.NET Core 2.2 on .NET Framework 4.7.1

Output of `dotnet --info`:
```
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100
 Commit:    04339c3a26

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by khellang**
If the `PEReader` fails to read the debug directory from the assembly, the `GetMetadataReader` will now return `null` and short-circuit in `PopulateStackFrame`.

Fixes #14609

### CODE REVIEW

File: src/Shared/StackTrace/StackFrame/PortablePdbReader.cs [hunk 1]
```diff
@@ -66,60 +66,77 @@ public void PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, int
...
+                            if (entry.Type == DebugDirectoryEntryType.CodeView)
+                            {
+                                var codeViewData = peReader.ReadCodeViewDebugDirectoryData(entry);
+                                var peDirectory = Path.GetDirectoryName(assemblyPath);
+                                pdbPath = Path.Combine(peDirectory, Path.GetFileName(codeViewData.Path));
+                                return true;
+                            }
                         }
                     }
+                    catch
```
Comment (halter73) [inline src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Should the exception still be logged at a debug level?

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Yeah, I thought about that. Might be valuable. But is it OK to take a dependency on `ILogger` or something in these shared source packages?

Comment (Tratcher) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Try it and we'll see if we hit any conflicts.

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: We shouldn't have a dependency on `ILogger` at this level of component.

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: It'd look a bit like this; https://github.com/aspnet/AspNetCore/commit/90c65b3482cd42907c213de76aa7b0e579e801fb

Comment (Tratcher) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: @davidfowl what's wrong with optionally passing in the caller's logger?

Comment (Tratcher) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: @davidfowl what's wrong with optionally passing in the caller's logger?

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: The caller should just catch the exception.

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: The `ExceptionDetailsProvider` already has a dependency on Microsoft.Extensions.FileProviders though.

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: That's the component that should catch the exception then.

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: So what's the verdict? Move the `try`/`catch` up into `ExceptionDetailsProvider`?

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Yep

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: There's an issue with moving it higher up in the stack. The call that would throw is

https://github.com/aspnet/AspNetCore/blob/8e05fb0cf450afdf629b275435c69c836ae8df68/src/Shared/StackTrace/StackFrame/StackTraceHelper.cs#L61

If the exception isn't caught inside the `PopulateStackFrame` call, there's no way to get `StackFrameInfo` for other frames in the stack, which could be valuable. You'd basically end up with no info.

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: I'm missing something, why would you miss all frames if we failed to populate info for this single frame?

Comment (khellang) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Because the exception would bubble up through `StackTraceHelper.GetFrames` and be caught in `ExceptionDetailsProvider.GetDetails`. At that point, it would have no choice but to use `Enumerable.Empty<StackFrameInfo>` for that exception.

Comment (davidfowl) [reply src/Shared/StackTrace/StackFrame/PortablePdbReader.cs]: Oh I was assuming you would still populate remaining frames. You need an out parameter from that method with an aggregate exception.

File: src/Shared/StackTrace/StackFrame/StackTraceHelper.cs [hunk 2]
```diff
@@ -56,14 +60,33 @@ public static IList<StackFrameInfo> GetFrames(Exception exception)
...
+                            }
+
+                            exceptions.Add(ex);
+                        }
                     }
 
                     frames.Add(stackFrame);
                 }
 
+                if (exceptions is object)
```
Comment (davidfowl) [inline src/Shared/StackTrace/StackFrame/StackTraceHelper.cs]: nah, != null is more sane  😄

File: src/Shared/StackTrace/ExceptionDetails/ExceptionDetailsProvider.cs [hunk 3]
```diff
@@ -30,15 +33,27 @@ public IEnumerable<ExceptionDetails> GetDetails(Exception exception)
...
+        {
+            var stackFrames = StackTraceHelper.GetFrames(original, out var exception)
+                .Select(frame => GetStackFrameSourceCodeInfo(
+                    frame.MethodDisplayInfo.ToString(),
+                    frame.FilePath,
+                    frame.LineNumber));
+
+            if (exception is object && _logger is object)
+            {
+                _logger.FailedToReadStackTraceInfo(original, exception);
```
Comment (davidfowl) [inline src/Shared/StackTrace/ExceptionDetails/ExceptionDetailsProvider.cs]: _logger?.FailedToReadStackTraceInfo(original, exception);

File: src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+        {
+            _failedToReadStackFrameInfo = LoggerMessage.Define<string>(
+                logLevel: LogLevel.Debug,
+                eventId: new EventId(1, "FailedToReadStackFrames"),
+                formatString: "Failed to stack trace information for exception of type '{ExceptionType}'");
+        }
+
+        public static void FailedToReadStackTraceInfo(this ILogger logger, Exception originalException, Exception exception)
+        {
+            _failedToReadStackFrameInfo(logger, originalException.GetType().FullName, exception);
```
Comment (davidfowl) [inline src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs]: check for null in here?

File: src/Shared/StackTrace/ExceptionDetails/ExceptionDetailsProvider.cs [hunk 5]
```diff
@@ -30,15 +33,27 @@ public IEnumerable<ExceptionDetails> GetDetails(Exception exception)
...
+        {
+            var stackFrames = StackTraceHelper.GetFrames(original, out var exception)
+                .Select(frame => GetStackFrameSourceCodeInfo(
+                    frame.MethodDisplayInfo.ToString(),
+                    frame.FilePath,
+                    frame.LineNumber));
+
+            if (exception is object && _logger is object)
+            {
+                _logger.FailedToReadStackTraceInfo(exception);
```
Comment (khellang) [inline src/Shared/StackTrace/ExceptionDetails/ExceptionDetailsProvider.cs]: Should this include the original exception as well? Is it OK to include the `Exception` object in the structured log?

File: src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+{
+    internal static class LoggerExtensions
+    {
+        private static readonly Action<ILogger, Exception> _failedToReadStackFrameInfo;
+
+        static LoggerExtensions()
+        {
+            _failedToReadStackFrameInfo = LoggerMessage.Define(
+                logLevel: LogLevel.Debug,
+                eventId: new EventId(1, "FailedToReadStackTraceInfo"),
```
Comment (khellang) [inline src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs]: Is this `EventId` OK? I'm not sure how it works when you don't have control over the (name of the) logger that's passed in.

Comment (Tratcher) [reply src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs]: Then use 0.

Comment (davidfowl) [reply src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs]: It can still clash and that's the problem with defining logging outside of the component. It needs to be owned by the component that does the logging. So it needs to be a parameter...

Comment (davidfowl) [reply src/Shared/StackTrace/ExceptionDetails/LoggerExtensions.cs]: 0 is fine though, we currently use that when we don't specify the event id

**Comment by khellang** [comment]
Looks like the CI is really flaky lately... 😞

**Review by davidfowl — APPROVED** [review]
