### PR TITLE
[blazor][debugger] Fixing vs-js-debugger: redirect ws to http is not supported anymore

### LINKED ISSUE #1190: Debug Blazor using Edge on Ubuntu
**Describe the bug**
Launch Edge on ubuntu and redirect to the page set in url parameter - using nightly build of vscode-js-debug.

**To Reproduce**
1. Create a new folder called `MyBlazorApp` somewhere
2. Navigate inside the folder and Open in Terminal
3. Type `dotnet new blazorwasm`
4. Type `code .; exit`
5. Allow VS Code to auto-generate `launch.json` and `tasks.json`
6. Inside `launch.json`, add `"browser": "edge"` to the first configuration in the list and set the url to the url defined in your `launchSettings.json`
6. Go to the file `Counter.razor` inside of the `Pages` folder and put a breakpoint where it says `currentCount++;`
7. Press `F5` to debug
8. It launches the browser but doesn't redirect to the url set in `launch.json`

Related to https://github.com/dotnet/aspnetcore/issues/38413

### LINKED ISSUE #39976: Debugging with VSCode on Linux:  Cannot launch browser, debugging not possible
**Describe the bug:**
Following the guides [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio-code) and [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux) it is not possible to launch the basic Blazor webassembly template for debugging in Visual Studio Code on Linux.

**Version used:**
- Ubuntu 20.04
- Chromium Browser Version 97.0.4692.99 (Official Build) snap (64-bit)
- google-chrome browser (Version 97.0.4692.99 (Official Build) (64-bit))
  (I've installed it additionally, because I think that the c# extension doesn't
  work with chromium. But this is another topic)
- .NET 6.0.101 (sdk)
- **Visual studio Code Version: 1.63.2**
  Electron: 13.5.2
  Chromium: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Linux x64 5.13.0-27-generic snap
  With the following extensions:
  - [C# for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) v1.24.0
  - [Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion) Released on 2/2/2021, 01:34:39,  Last updated5/21/2021, 19:16:17

**To reproduce:**
1. Create a new project
```
dotnet new blazorwasm -o BlazorWasmDemo1
```
2. Open project in VSCode. You'll be asked *Required assets to build and debug are missing from 'BlazorWasmDemo1'. Add them?*
Click on *Yes*
3. Start a debugging session by hitting F5.

**Expected behavior:**
Browser should be opened and load the application for debugging, breakpoints should work.

**Actual behavior:**
When starting for debugging (**F5**)
Chrome-browser opens up in some kind of integrated window of VSCode but with an empty address field.
After a few seconds I get the error-message **Unable to launch browser**.
Even if I enter the address https://localhost:7046 manually, the error message appears after a few seconds.
Screenshot_vscode_unabletoconnect

Stopping the debug session and starting it again after a few **minutes** I get the message, that it looks, that a browser is already running from an old debug session.
Screenshot_vscode_alreadyrunning

Debugging is not possible at all. If i set a breakpoint, for example on the line where the count-page increases the count-variable, it shows me "unbound breakpoint".

If I'm fast enough and enter the address https://localhost:7046 manually, wait for the page to be loaded and press **SHIFT** + **ALT** + **D** to start the debugging view from chrome, I see this page
```
Unable to find debuggable browser tab
Could not get a list of browser tabs from http://localhost:9222/json. Ensure your browser is running with debugging enabled.

Resolution
If you are using Google Chrome for your development, follow these instructions:
In a terminal window execute the following:

google-chrome --remote-debugging-port=9222 --user-data-dir=/tmp/blazor-chrome-debug https://localhost:7046/

If you are using Microsoft Edge (80+) for your development, follow these instructions:
Edge is not current supported on your platform

This should launch a new browser window with debugging enabled..
Underlying exception:
System.Net.Http.HttpRequestException: Connection refused (localhost:9222)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Server.TargetPickerUi.GetOpenedBrowserTabs()
   at Microsoft.AspNetCore.Components.WebAssembly.Server.TargetPickerUi.Display(HttpContext context)
```

**Additional context:**
And I got this files added:
**tasks.json**
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/BlazorWasmDemo1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/BlazorWasmDemo1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "--project",
                "${workspaceFolder}/BlazorWasmDemo1.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```
and
**launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

and for completeness, the
**launchsettings.json**
```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:43638",
      "sslPort": 44332
    }
  },
  "profiles": {
    "BlazorWasmDemo1": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:7046;http://localhost:5256",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

The full project be found [here](https://github.com/wk-done/20220130-BlazorWasm).

### PR DESCRIPTION
**Pull request by thaystg**
After microsoft/vscode-js-debug update the ws package to use version "8.4.2" as you can see here:
https://github.com/microsoft/vscode-js-debug/blob/2dfdba1f6f6e4f264d2beb90c80fa7cc4d4396dc/package.json#L78

This new check was added in ws library:
https://github.com/websockets/ws/blob/35d45c2a4fead953654ae7bcf029cdf6d2590121/lib/websocket.js#L682

So as we were trying to redirect `ws://localhost:[PORTNUMBER]/_framework/debug/ws-proxy?browser={browserInspectUri}` to `http://localhost:[BROWSERDEBUGPROXYPORT]/{browserInspectUri}` we were getting this new error:
`The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"`

Then the browser was being launched correctly but it never loads the Blazor App Page.

With this fix it works in the current version of the vscode-js-debug and also in the nightly build.

Fixes: https://github.com/microsoft/vscode-js-debug/issues/1190
Related: https://github.com/dotnet/aspnetcore/issues/38413
Fixes: https://github.com/dotnet/aspnetcore/issues/39976

### CODE REVIEW

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs [hunk 1]
```diff
@@ -168,6 +168,7 @@ void OnOutputDataReceived(object sender, DataReceivedEventArgs eventArgs)
                 if (match.Success)
                 {
                     capturedUrl = match.Groups["url"].Value;
+                    capturedUrl = capturedUrl.Replace("http://", "ws://");
```
Comment (pranavkm) [inline src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:171]: Should we also also include the wss? 
```suggestion
                    capturedUrl = capturedUrl.Replace("http://", "ws://");
                    capturedUrl = capturedUrl.Replace("https://", "wss://");
```

Also any chance this has an unescaped http:// as part of the query / route?

Comment (thaystg) [reply src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:171]: I don't think we need https:// because BrowserDebugProxy is always started as http, right?
https://github.com/dotnet/runtime/blob/59e643b9932122a12e71ceb360a9ae3bb9420dec/src/mono/wasm/debugger/BrowserDebugHost/Program.cs#L36

Comment (thaystg) [reply src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:171]: I don't think so the query/route part will be like this: ws%3A%2F%2F127.0.0.1%3A53061%2Fdevtools%2Fbrowser%2F2979b015-4625-bea7-2071-e9b04f9ca35c

**Review by pranavkm — APPROVED** [review]

**Review by TanayParikh — APPROVED** [review]
This is great, thanks! ~~Should we consider this for patching for 6.0.3xx?~~ Edit: nevermind, I see you're ahead of it 😄

**Comment by TanayParikh** [comment]
fyi/ @mkArtakMSFT for potential servicing consideration via https://github.com/dotnet/aspnetcore/pull/39996. I've added the issue to the servicing project.

**Comment by ChristianWeyer** [comment]
What will be the delivery vehicle for this patch? SDK update?

**Comment by pranavkm** [comment]
This is a runtime change, consequently it would appear as part of a 6.0 patch release.

**Comment by TanayParikh** [comment]
> This is a runtime change, consequently it would appear as part of a 6.0 patch release.

For those who may be following along, this issue is resolved via https://github.com/microsoft/vscode-js-debug/pull/1195 (and thus no longer required to get into the 6.0 patch release).
