### PR TITLE
Fix handling of default values in RDG

### LINKED ISSUE #51183: RequestDelegateGenerator creates incorrect code with default parameters for bool and CancellationToken in Lambda expressions (AOT)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Creating an AOT Web API project (dotnet new webapiaot), and using default parameter values in Lambda expression for bool and CancellationToken, such as the following creates invalid code.

```csharp
        group.MapGet("/", async (
            IGamesService gameService,
            string? gameType = default,
            string? playerName = default,
            DateOnly? date = default,
            bool ended = default,
            CancellationToken cancellationToken = default) =>
        {
          //...
        });
```

This is part of the generated code:

```csharp
                var handler = Cast(del, global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Http.HttpResults.Ok<global::System.Collections.Generic.IEnumerable<global::Codebreaker.GameAPIs.Models.Game>>> (global::Codebreaker.GameAPIs.Services.IGamesService arg0, global::System.String? arg1= null, global::System.String? arg2= null, global::System.DateOnly? arg3= null, global::System.Boolean arg4= False, global::System.Threading.CancellationToken arg5= null) => throw null!);
```

With the `bool` parameter, the value `False` is created which should be `false`.
With the default value for the `CancellationToken`, `null` is assigned - but this is a vlaue type.

### Expected Behavior

I would expect to create true/false for bool types, and correct defaults for value types such as CancellationToken.

### Steps To Reproduce

Create an AOT Web API project (webapiaot template)
Define an API method with bool and CancellationToken parameters, and assign default values

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

In this repository
https://github.com/PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure

in the branch requestdelegategenerator
the issue is in the folder ch05, Codebreaker.GameAPIs.NativeAOT.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/51183.

`IParameterSymbol.ExplicitDefaultValue` returns null when the type is a struct type and th default value of the parameter is the default value of the struct type ([ref](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.iparametersymbol.explicitdefaultvalue?view=roslyn-dotnet-4.6.0)). Update the code generation to handle `IParameterSymbol.HasExplicitDefaultValue = true` and `IParameterSymbol.ExplicitDefaultValue = null`. Also fixes formating of stringified boolean default.

### CODE REVIEW

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs [hunk 1]
```diff
@@ -148,4 +148,40 @@ static void TestAction([AsParameters] ParametersListWithHttpContext args)
         Assert.Same(httpContext.Request, httpContext.Items["request"]);
         Assert.Same(httpContext.Response, httpContext.Items["response"]);
     }
+
+    [Fact]
+    public async Task RequestDelegatePopulatesParametersWithDefaultValues()
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs:153]: Do we have any other coverage for default values?
If not, this feels like a good opportunity to add a few more. Like `bool value = true`, `string s = "test"`

File: src/Shared/RoslynUtils/SymbolExtensions.cs [hunk 2]
```diff
@@ -176,7 +176,18 @@ public static string GetDefaultValueString(this IParameterSymbol parameterSymbol
...
+    }
+
+    private static string InnerGetDefaultValueString(object? defaultValue)
+    {
+        return defaultValue switch
+        {
+            string s => SymbolDisplay.FormatLiteral(s, true),
+            bool b => SymbolDisplay.FormatLiteral(b.ToString().ToLowerInvariant(), false),
+            null => "default",
+            _ => SymbolDisplay.FormatLiteral(defaultValue.ToString(), false)
```
Comment (martincostello) [inline src/Shared/RoslynUtils/SymbolExtensions.cs:189]: I'm not familiar with `FormatLiteral()`, so sorry if this is a silly question, but if the value was a float and had a default of say, `1.0`, would this correctly emit `1.0` if the code ran on a machine where the default culture was one that uses `,` as a decimal point like French, rather than incorrectly emit `1,0`?

Comment (martincostello) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:189]: What I'm thinking might be similar to this issue with the config binding source generator: https://github.com/dotnet/runtime/pull/93160

Comment (captainsafia) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:189]: Interesting! It looks like there is an alternate API recommended [here](https://github.com/dotnet/roslyn/issues/58705#issuecomment-1751582384) that might be helpful, although it requires pulling in different M.CA dependencies.

I'm not a huge fan of maintaining a custom implementation of `FormatLiteral` within our codebase.

I wonder if in this particular case, we can get away with not using `FormatLiteral` at all for certain types.

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs:153]: There's a few tests sprinkled in other places but it's a good idea to put them in one place.

File: src/Shared/RoslynUtils/SymbolExtensions.cs (hunk 2 above)
Comment (captainsafia) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:189]: Yep, I think it's worth filing an issue for this. From my experimentation, doing something like `((ParameterSyntax)IParameterSymbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax()).Default.Value.GetText().ToString()` will allow us to capture the exact constant passed as a default but we'd have to verify that nothing funky happens as a result.

Comment (captainsafia) [reply src/Shared/RoslynUtils/SymbolExtensions.cs]: https://github.com/dotnet/aspnetcore/issues/51241

**Comment by captainsafia** [comment]
@martincostello @BrennanConroy  I just pushed https://github.com/dotnet/aspnetcore/pull/51193/commits/ded57947583bc134cc7aaa29e42ed861b0703a5b which I think covers scenarios here.

@martincostello I added a test to cover the culture scenario in https://github.com/dotnet/aspnetcore/pull/51193/commits/2cf25ead7c9cb34e23cbae0c5993b0fb5afbb3d3. I think it should be sufficient but let me know if there's other scenarios to test out.

**Comment by martincostello** [comment]
@captainsafia The ex-QA in me loves the breadth of the test cases! Assuming they all pass looks like you've covered what I was thinking of 🌟

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs [hunk 3]
```diff
@@ -148,4 +149,130 @@ static void TestAction([AsParameters] ParametersListWithHttpContext args)
...
+static void TestAction(
+    HttpContext context,
+    {{type}} parameterWithDefault = {{defaultValue}},
+    {{type}} parameterWithConst = defaultConst)
+{
+    context.Items.Add("parameterWithDefault", parameterWithDefault);
+    context.Items.Add("parameterWithConst", parameterWithConst);
+}
+app.MapPost("/", TestAction);
+""" :$$"""
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTests.SpecialTypes.cs:225]: Multi-line ternary is kinda hard to read 😆

File: src/Shared/RoslynUtils/SymbolExtensions.cs [hunk 4]
```diff
@@ -176,7 +177,27 @@ public static string GetDefaultValueString(this IParameterSymbol parameterSymbol
...
+            char c => SymbolDisplay.FormatLiteral(c, true),
+            bool b => b ? "true" : "false",
+            null => "default",
+            float f when f is float.NegativeInfinity => "float.NegativeInfinity",
+            float f when f is float.PositiveInfinity => "float.PositiveInfinity",
+            float f when f is float.NaN => "float.NaN",
+            float f => $"{SymbolDisplay.FormatPrimitive(f, false, false)}F",
+            double d when d is double.NegativeInfinity => "double.NegativeInfinity",
+            double d when d is double.PositiveInfinity => "double.PositiveInfinity",
+            double d when d is double.NaN => "double.NaN",
```
Comment (BrennanConroy) [inline src/Shared/RoslynUtils/SymbolExtensions.cs:197]: Does `double` get handled by `_ => SymbolDisplay.FormatPrimitive`?

Did that API not handle `double.NaN`, `float.PositiveInfinity`, etc.? It claims to support all the types, so kinda odd that they need to be special cased?

**Review by BrennanConroy — APPROVED** [review]

File: src/Shared/RoslynUtils/SymbolExtensions.cs (hunk 4 above)
Comment (captainsafia) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:197]: Yep, the `double` is handled correctly by our terminal case. The comment on this API is rather deceptive given the conversation that is occuring in https://github.com/dotnet/roslyn/issues/58705. Evidently, `SymbolDisplay.FormatX` APIs are not intended for code gen. The recommended alternative [defined here](https://github.com/dotnet/roslyn/blob/0caa880a161057559d1dcaad890e4053f520136e/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L1803) is defined in the workspace layer and would require introducing some new dependencies for the generator.

Given that we've been successful using SymbolDisplay in other places (displaying FQNs) I'm incline to workaround its limitations given the finite set of types we have to deal with here.

Comment (campersau) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:197]: The runtime does it like this: https://github.com/dotnet/runtime/pull/93160/files#diff-60e086268f0958325d865a75b553a6ed42b402d0a1792132e426a598172dace5R57

Comment (captainsafia) [reply src/Shared/RoslynUtils/SymbolExtensions.cs:197]: > The runtime does it like this: https://github.com/dotnet/runtime/pull/93160/files#diff-60e086268f0958325d865a75b553a6ed42b402d0a1792132e426a598172dace5R57

Yeah, I think using `FormatPrimitive` is a sufficient alternative to calling the converter here. In any case, I'm planning on merging this to 9.0, evaluating the fix, then putting it into a servicing release of 8.0
