### PR TITLE
Fixed HostFilteringMiddleware. Added HostFilteringMiddleware.MiddlewareConfigurationManager

### LINKED ISSUE #51960: HostFilteringMiddleware. It is returning "The host '{Host}' does not match an allowed host." time to time.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In HostFilteringMiddleware we are using IOptionsManager. 
During reloading the configuration, it clears the state used to evaluate the host.
In edge cases we may end up with an inconsistent state when calling the main Middleware method, the state can be cleared during the execution of the "Invoke" method. 

### Expected Behavior

Middleware shouldn't return us badrequest when allowed host are properly configured.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

We shouldn't clear state but re-evaluate it during OnChange action.

### PR DESCRIPTION
**Pull request by charytech**
# Fixed HostFilteringMiddleware. Added HostFilteringMiddleware.MiddlewareConfigurationManager

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Added HostFilteringMiddleware.MiddlewareConfigurationManager which is responisible for maintenence configuration state used by middleware invocation.

Fixes #51960

### CODE REVIEW

**Comment by charytech** [comment]
@dotnet-policy-service agree

File: src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs [hunk 1]
```diff
@@ -62,140 +55,196 @@ public class HostFilteringMiddleware
...
+        private static bool IsTopLevelWildcard(string host)
+        {
+            return (
+                string.Equals("*", host, StringComparison.Ordinal) // HttpSys wildcard
+                || string.Equals("[::]", host, StringComparison.Ordinal) // Kestrel wildcard, IPv6 Any
+                || string.Equals("0.0.0.0", host, StringComparison.Ordinal)
+            ); // IPv4 Any
+        }
+
+        private sealed record MiddlewareHostFilteringOptions(ReadOnlyCollection<string> AllowedHosts, bool AllowEmptyHosts, bool IncludeFailureMessage)
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: I'm not sure why you need this type either? HostFilteringOptions returned from IOptionsMonitor should be stable.

File: src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs [hunk 2]
```diff
@@ -62,140 +55,196 @@ public class HostFilteringMiddleware
...
         }
+
         _logger.RequestAllowedMissingHost(context.Request.Protocol);
+
         return true;
     }
+
+    internal sealed record MiddlewareConfiguration(bool AllowAnyNonEmptyHost, bool AllowEmptyHosts, bool IncludeFailureMessage, ReadOnlyCollection<StringSegment>? AllowedHosts = default);
+
+    internal sealed class MiddlewareConfigurationManager
```
[the remark this answers is not in the document]
Comment (charytech) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:135]: Hey, 
1. Separation of responsibility. 
2. I think it is easier to maintain code.
3. We can always add everything under one object but it looks more clear to me.

File: src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs (hunk 1 above)
Comment (charytech) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: HostFilteringOptions provided from IOptionsMonitor Onchange method is a reference type and it could be changed in any other event handlers, so we should avoid such situations, to achieve this we can create a copy of HostFilteringOptions or use our internal type during evaluation.

Also, the new type could be useful for checking if the new values will be different from the previous ones, and then we can skip the configuration re-evaluation. But it is a good candidate for the future and is not covered by this bug fix.

Comment (Tratcher) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: Maybe in theory, but this is the only place this type is consumed so such defense is not needed. We'd rather avoid the extra allocations and work. We'll address it if it becomes an issue in the future.

Comment (charytech) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: I understand your point as it is really an edge case. But why are you afraid of simple allocation? If users will not update configs often it will be only single allocation. But two quick update can cause various strange behaviors which will be difficult to debug. I can see quite clear benefits of doing it in atomic way and code is more stable.
What do you think?

File: src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Tratcher) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:135]: It's substantial enough that it deserves to be in its own file. Nesting large components makes things harder to navigate and make sense of.

File: src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs (hunk 1 above)
Comment (Tratcher) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: Keep It Simple. Don't solve theoretical problems, only real ones. Unnecessary code makes components harder to understand and maintain.

Comment (charytech) [reply src/Middleware/HostFiltering/src/HostFilteringMiddleware.cs:238]: Ok. I will change it as you want

**Comment by charytech** [comment]
Hey, @Tratcher I changed it as you wanted, removed an extra object, and moved Manager to a new file.
I left a new object allocation because if we don't want to do it lock statement does not make sense. It will be allocated only when a change request is registered. 
Config can change during the lifecycle of Middleware so it is expected behavior as we are using IOptionsManager, but config shouldn't change during ConfigureMiddleware and it should be an atomic operation. 
Without it could bring us unexpected behavior, code should be stable.

**Comment by charytech** [comment]
Hey @Tratcher sorry for the delay. Changed as you suggested.

**Comment by charytech** [comment]
what about previous versions? will you patch them?

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+        _optionsMonitor.OnChange(options =>
+        {
+            lock (_syncObject)
+            {
+                _getChangeRequestObject = () => options;
+                if (_logger.IsEnabled(LogLevel.Debug))
+                {
+                    _logger.OptionsChanged(GetLogMessageForHostFilteringOptions(options));
+                }
+            }
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:36]:
```suggestion
            _middlewareConfiguration = ConfigureMiddleware(options);
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+    private readonly object _syncObject = new();
+    private event Func<HostFilteringOptions>? _getChangeRequestObject;
+    private MiddlewareConfiguration? _middlewareConfiguration;
+    private readonly ILogger<HostFilteringMiddleware> _logger;
+
+    internal MiddlewareConfigurationManager(IOptionsMonitor<HostFilteringOptions> _optionsMonitor, ILogger<HostFilteringMiddleware> logger)
+    {
+        _logger = logger;
+        // Configuration will evaluate during first request
+        _getChangeRequestObject = () => _optionsMonitor.CurrentValue;
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:26]:
```suggestion
        _middlewareConfiguration = ConfigureMiddleware(options);
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+
+namespace Microsoft.AspNetCore.HostFiltering;
+
+internal sealed record MiddlewareConfiguration(bool AllowAnyNonEmptyHost, bool AllowEmptyHosts, bool IncludeFailureMessage, ReadOnlyCollection<StringSegment>? AllowedHosts = default);
+
+internal sealed class MiddlewareConfigurationManager
+{
+    private readonly object _syncObject = new();
+    private event Func<HostFilteringOptions>? _getChangeRequestObject;
+    private MiddlewareConfiguration? _middlewareConfiguration;
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:19]:
```suggestion
    private MiddlewareConfiguration _middlewareConfiguration;
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+using Microsoft.Extensions.Primitives;
+
+namespace Microsoft.AspNetCore.HostFiltering;
+
+internal sealed record MiddlewareConfiguration(bool AllowAnyNonEmptyHost, bool AllowEmptyHosts, bool IncludeFailureMessage, ReadOnlyCollection<StringSegment>? AllowedHosts = default);
+
+internal sealed class MiddlewareConfigurationManager
+{
+    private readonly object _syncObject = new();
+    private event Func<HostFilteringOptions>? _getChangeRequestObject;
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:18]: I don't think this locking or indirection are needed. We just need to make sure _middlewareConfiguration is handled atomically.
```suggestion
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+            HostFilteringOptions options;
+            lock (_syncObject)
+            {
+                options = _getChangeRequestObject();
+                _getChangeRequestObject = null;
+            }
+            _middlewareConfiguration = ConfigureMiddleware(options);
+        }
+
+        if (_middlewareConfiguration?.AllowAnyNonEmptyHost != true && (_middlewareConfiguration?.AllowedHosts is null || _middlewareConfiguration.AllowedHosts?.Count == 0))
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]:
```suggestion
        var config = _middlewareConfiguration;
        if (!config.AllowAnyNonEmptyHost && (config.AllowedHosts is null || config.AllowedHosts.Count == 0))
```

You can also add this check in the constructor.

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+
+        if (_logger.IsEnabled(LogLevel.Debug))
+        {
+            _logger.MiddlewareConfigurationStarted(GetLogMessageForHostFilteringOptions(options));
+        }
+
+        if (
+            options.AllowedHosts?.Count > 0
+            && !TryProcessHosts(options.AllowedHosts, allowedHosts)
+        )
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:72]:
```suggestion
        if (options.AllowedHosts?.Count > 0
            && !TryProcessHosts(options.AllowedHosts, allowedHosts))
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+        return true;
+    }
+
+    private static bool IsTopLevelWildcard(string host)
+    {
+        return (
+            string.Equals("*", host, StringComparison.Ordinal) // HttpSys wildcard
+            || string.Equals("[::]", host, StringComparison.Ordinal) // Kestrel wildcard, IPv6 Any
+            || string.Equals("0.0.0.0", host, StringComparison.Ordinal)
+        ); // IPv4 Any
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:114]:
```suggestion
        return string.Equals("*", host, StringComparison.Ordinal) // HttpSys wildcard
            || string.Equals("[::]", host, StringComparison.Ordinal) // Kestrel wildcard, IPv6 Any
            || string.Equals("0.0.0.0", host, StringComparison.Ordinal); // IPv4 Any
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+    }
+    private static string GetLogMessageForHostFilteringOptions(HostFilteringOptions hostFilteringOptions)
```
Comment (Tratcher) [inline src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:116]:
```suggestion
    }
    
    private static string GetLogMessageForHostFilteringOptions(HostFilteringOptions hostFilteringOptions)
```

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs (hunk 7 above)
Comment (charytech) [reply src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]: Why do you want to do all operations in the constructor?
_Constructors should not do much work other than capture the constructor parameters. The cost of any other processing should be delayed until required._

The configuration of the middleware should be evaluated as needed. 
Even from a performance perspective, it's better.
You can have several HostFilteringOptions updates (e.g. 5 ) but only one request after those updates so reconfiguration should be done only once.
That's why I created the delegate, to transfer responsibility from the constructor to the method when configuration is needed.

**Comment by charytech** [comment]
@Tratcher  Why do you want to do all operations in the constructor?
Constructors should not do much work other than capture the constructor parameters. The cost of any other processing should be delayed until required.

The configuration of the middleware should be evaluated as needed.
Even from a performance perspective, it's better.
You can have several HostFilteringOptions updates (e.g. 5 ) but only one request after those updates so reconfiguration should be done only once.
That's why I created the delegate, to transfer responsibility from the constructor to the method when configuration is needed.

File: src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs (hunk 7 above)
Comment (Tratcher) [reply src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]: Constructors should make sure the object is initialized and ready to use. This data is going to be needed on all requests, so it makes sense to get it ready in advance. It's not a lot of extra work in this case.

> You can have several HostFilteringOptions updates (e.g. 5 ) but only one request after those updates so reconfiguration should be done only once.

Requests are _much_ more common than options updates.

Comment (charytech) [reply src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]: > Constructors should make sure the object is initialized and ready to use. This data is going to be needed on all requests, so it makes sense to get it ready in advance. It's not a lot of extra work in this case.

why my implementation is wrong? it is doing the same as you mentioned it is initializing data to be ready to use, with the difference that middleware initialization is faster and reevaluation is done only when needed, you can have a bigger list of allowed hosts that will use not needed resources to reevaluate state.

> Requests are _much_ more common than options updates.
You are right but it is theoretical

Comment (Tratcher) [reply src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]: My main complaint is that the implementation is more complex than necessary. Keep it simple.

As for perf, avoid doing work on a request thread when possible, do it at startup or on an event thread instead.

Comment (charytech) [reply src/Middleware/HostFiltering/src/MiddlewareConfigurationManager.cs:52]: I can partially agree as it is better to do work on an event thread :D but about complexity, I think it is still simple 10 extra lines with logging. 
We have two different concepts which have their own pros and cons.
I kept the current implementation because the configuration was evaluated during the request, I also agree with this because it is better to avoid unnecessary evaluation. Re-evaluation on the event thread is slowing down event processing, any nested methods assigned to an event will be delayed. 

You maintain this code so I will change it as you requested :)

**Comment by charytech** [comment]
@Tratcher  I think I resolved all of your comments

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks!
