### PR TITLE
Blazor input component support when EditContext is not supplied

### LINKED ISSUE #27804: Throw informative exception when Input Controls are not surrounded by EditForm
This is obviously a minor issue, but a NullReferenceException is thrown in the scenario (rather than something more useful), and a new user learning Blazor user would probably have no way to debug this.  We need a more useful exception to be thrown (I was in Debug more as well, and there also was no inner exception).

The scenario is using the Blazor Input controls (InputText, etc) without wrapping them with the EditForm.  In this case, when in the default ServerPrerendering mode, the NullReferenceException breaks to this line below in the _Host.cshtml file:
```
<component type="typeof(App)" render-mode="ServerPrerendered" />
```
Obviously an exception is being thrown during prerendering (due to the code bug), but I cannot see how a new user learning Blazor would be able to figure out what the bug is.  The framework needs to throw a more informative exception here to help new users.  

Without PreRendering, the error is clear.  If this is a more general issue (where PreRendering causes NullReferenceExceptions to be thrown), we need to provide as helpful diagnostics as possible due to ServerPrerendering being the default.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Blazor input component support when EditContext is not supplied
This PR enables Blazor input component functionality (`InputText`, `InputSelect`, etc.) when no `EditContext` is provided by a parent `EditForm`.

### PR Description
The current approach solves the issue by allowing `InputBase.EditContext` to be `null`. Validation styling won't be applied to input components without an `EditContext`.

Fixes #27804

### CODE REVIEW

**Comment by MackinnonBuck** [comment]
Something else to consider: Do we want validation styling to apply to input components without a parent `EditForm`? The validation css class will always be either `valid` or `modified valid`, but this is meaningless since data annotations are ignored in these cases.

**Comment by pranavkm** [comment]
>  but it has the crucial drawback that Inputbase<>.EditContext is part of the public API surface and marking it as nullable would be a breaking change

We've been playing [somewhat loosey](https://github.com/aspnet/Announcements/issues/444) with nullable annotations as we work thru the repo. One could further argue that the current annotations are incorrect to begin with given if you create a new component, the edit context is null even though the compiler says otherwise:

ie..
```C#
var inputText = new InputText();
Console.WriteLine(inputText.EditContext.ToString()); // The compiler will claim this is null safe, even though we know this will null-ref
```

How does it look if we make `EditContext` nullable and let it be null in some cases?

**Comment by MackinnonBuck** [comment]
> We've been playing somewhat loosey with nullable annotations as we work thru the repo.

Good to know - I'll give the other approach a go.

File: src/Components/Web/src/Forms/InputBase.cs [hunk 1]
```diff
@@ -159,62 +160,53 @@ protected InputBase()
...
+
                 if (AdditionalAttributes != null &&
                     AdditionalAttributes.TryGetValue("class", out var @class) &&
                     !string.IsNullOrEmpty(Convert.ToString(@class, CultureInfo.InvariantCulture)))
                 {
-                    return $"{@class} {FieldClass}";
+                    return string.IsNullOrEmpty(fieldClass) ? @class.ToString()! : $"{@class} {fieldClass}";
                 }
 
-                return FieldClass; // Never null or empty
```
Comment (MackinnonBuck) [inline src/Components/Web/src/Forms/InputBase.cs:184]: Since the `EditContext` is optional now, the class string can be empty if there is no class provided via `AdditionalAttributes`. This is the reason I added the extension method `RenderTreeBuilder.AddAttributeIfNotNullOrEmpty()`.

File: src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Microsoft.AspNetCore.Components.Rendering;
+
+namespace Microsoft.AspNetCore.Components.Forms;
+
+internal static class RenderTreeBuilderExtensions
+{
+    public static void AddAttributeIfNotNullOrEmpty(this RenderTreeBuilder builder, int sequence, string name, string? value)
```
Comment (MackinnonBuck) [inline src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs:10]: This was added because the `class` attribute can now be empty for input components, and we don't want to render `class` attributes with empty values.

**Comment by MackinnonBuck** [comment]
@pranavkm I've updated the implementation to allow `EditContext` to be `null`. Also, my previous comment...

> Something else to consider: Do we want validation styling to apply to input components without a parent `EditForm`?

...is no longer relevant because validation styling won't happen without an edit context. It's probably better this way, since validation styling would just get in the way if no actual validation was happening.

File: src/Components/test/E2ETest/Tests/FormsTest.cs [hunk 3]
```diff
@@ -848,6 +848,47 @@ public void InputRangeAttributeOrderDoesNotAffectValue()
             Browser.Equal("210", () => rangeWithValueLast.GetDomProperty("value"));
         }
 
+        [Fact]
```
Comment (MackinnonBuck) [inline src/Components/test/E2ETest/Tests/FormsTest.cs:851]: I've only added tests verifying that `InputSelect` and `InputRadioGroup` work without a parent `EditForm`, since they contain most of the unique logic of the input components (other logic comes from `InputBase`). `InputRadioGroup` is a bit special in that it still calculates its own styling. The `InputSelect` test verifies that complicated binding scenarios still work (binding to arrays, boolean values).

**Comment by MackinnonBuck** [comment]
It also appears that the CI is a bit unhappy that the baseline API files are getting modified (by making `InputBase<>.EditContext` nullable). We would have to make some exception for this (or keep lying about the nullability of `EditContext` 😬).

File: src/Components/Web/src/Forms/InputBase.cs [hunk 4]
```diff
@@ -112,21 +111,24 @@ public abstract class InputBase<TValue> : ComponentBase, IDisposable
                 {
                     parsingFailed = true;
 
-                    if (_parsingValidationMessages == null)
+                    if (EditContext != null)
```
Comment (pranavkm) [inline src/Components/Web/src/Forms/InputBase.cs:114]:
```suggestion
                    // EditContext may be null if the input is not a child component of a EditForm.
                    if (EditContext is not null)
```

File: src/Components/Web/src/Forms/InputBase.cs [hunk 5]
```diff
@@ -112,21 +111,24 @@ public abstract class InputBase<TValue> : ComponentBase, IDisposable
...
                     {
-                        _parsingValidationMessages = new ValidationMessageStore(EditContext);
-                    }
+                        if (_parsingValidationMessages == null)
+                        {
+                            _parsingValidationMessages = new ValidationMessageStore(EditContext);
+                        }
```
Comment (pranavkm) [inline src/Components/Web/src/Forms/InputBase.cs:119]:
```suggestion
                        _parsingValidationMessages ??= new ValidationMessageStore(EditContext);
                        
```

File: src/Components/Web/src/Forms/InputBase.cs (hunk 1 above)
Comment (pranavkm) [reply src/Components/Web/src/Forms/InputBase.cs:184]: This is super unrelated to your change, but could we capture the result of `Convert.ToString(@class, CultureInfo.InvariantCulture)` and use that inside the `if`? It feels like that's what we should have been using instead of relying on `@class.ToString()` to produce the right representation inside the interpolated string.

File: src/Components/Web/src/Forms/InputBase.cs [hunk 6]
```diff
@@ -243,7 +236,7 @@ private void OnValidateStateChanged(object? sender, ValidationStateChangedEventA
         private void UpdateAdditionalValidationAttributes()
         {
             var hasAriaInvalidAttribute = AdditionalAttributes != null && AdditionalAttributes.ContainsKey("aria-invalid");
-            if (EditContext.GetValidationMessages(FieldIdentifier).Any())
+            if (EditContext != null && EditContext.GetValidationMessages(FieldIdentifier).Any())
```
Comment (pranavkm) [inline src/Components/Web/src/Forms/InputBase.cs:239]:
```suggestion
            if (EditContext is not null && EditContext.GetValidationMessages(FieldIdentifier).Any())
```

File: src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs (hunk 2 above)
Comment (pranavkm) [reply src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs:10]:
```suggestion
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void AddAttributeIfNotNullOrEmpty(this RenderTreeBuilder builder, int sequence, string name, string? value)
```

File: src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs [hunk 7]
```diff
@@ -0,0 +1,17 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Microsoft.AspNetCore.Components.Rendering;
+
+namespace Microsoft.AspNetCore.Components.Forms;
```
Comment (pranavkm) [inline src/Components/Web/src/Forms/RenderTreeBuilderExtensions.cs:6]: Should we put this in the Rendering namespace?

**Review by pranavkm — COMMENTED** [review]
Looks great. @javiercn could you have a look since you said you did something similar?

File: src/Components/Web/src/Forms/InputBase.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/Components/Web/src/Forms/InputBase.cs:184]: @pranavkm I've made this change. Since `InputRadio` had nearly identical logic for creating its class string, I've added a static class `AttributeUtilities` containing a method `CombineClassNames` that does this (`InputRadio` cannot inherit the implementation in `InputBase` because it does not extend `InputBase`).

**Review by pranavkm — APPROVED** [review]

**Review by TanayParikh — APPROVED** [review]
