### PR TITLE
Fail on startup for Http/2 HTTPS on Win7

### LINKED ISSUE #11970: Fail on startup for Http/2 HTTPS on Windows 7
Following up on https://github.com/aspnet/AspNetCore/issues/11061. We should also fail fast on Windows 7 where there is no ALPN support. 

As a further consideration, is the platform the only way to determine ALPN support. How would this work on Linux?

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/aspnet/AspNetCore/issues/11970

### CODE REVIEW

File: src/Servers/Kestrel/test/FunctionalTests/Http2/HandshakeTests.cs [hunk 1]
```diff
@@ -57,6 +56,29 @@ public void TlsAndHttp2NotSupportedOnMac()
             Assert.Equal("HTTP/2 over TLS is not supported on OSX due to missing ALPN support.", ex.Message);
         }
 
+
+        [ConditionalFact]
+        [OSSkipCondition(OperatingSystems.Linux | OperatingSystems.MacOSX)]
+        [OSSkipCondition(OperatingSystems.Windows, WindowsVersions.Win10, WindowsVersions.Win8, WindowsVersions.Win81)]
+        // Mac SslStream is missing ALPN support: https://github.com/dotnet/corefx/issues/30492
```
Comment (Tratcher) [inline src/Servers/Kestrel/test/FunctionalTests/Http2/HandshakeTests.cs]:
```suggestion
        // Win7 SslStream is missing ALPN support.
```

**Review by Tratcher — APPROVED** [review]
