### PR TITLE
Remove reflection from KestrelServer constructor

### LINKED ISSUE #50255: NativeAOT with reflection disabled working in .NET 7, not in .NET 8 for new KestrelServer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

2 years ago I spent quite some time (and David Fowler even corrected my code in https://github.com/LLT21/NativeAOT5) to make a tiny kestrel that worked with Native AOT and reflection disabled for reasons described in closed issue #31561. 

I upgraded the tiny kestrel code today to make it in sync with the one I use in the TechEmpower benchmarks under framework https://github.com/LLT21/FrameworkBenchmarks/tree/master/frameworks/CSharp/appmpower: 
1) First I upgraded to .NET 7: this is the project that now is in the master of https://github.com/LLT21/NativeAOT5. If one compiles this native with reflection disabled - specified in project file - on Mac M1 or Linux, this works perfect and runs as such each week successfully in the TechEmpower benchmarks. 
2) Then I upgraded to .NET 8 and receive an Unhandled Exception: MT4302744992: Reflection_Disabled error on the line: `using var kestrelServer = new KestrelServer(Options.Create(kestrelServerOptions), socketTransportFactory, NullLoggerFactory.Instance);` -> some reflection code has been added here in .NET 8. 

The output is: 

```
Unhandled Exception: MT4302744992: Reflection_Disabled
   at Internal.Reflection.RuntimeTypeInfo.get_Name() + 0x5d
   at Microsoft.Extensions.Internal.TypeNameHelper.ProcessType(StringBuilder&, Type, TypeNameHelper.DisplayNameOptions&) + 0x9c
   at Microsoft.Extensions.Internal.TypeNameHelper.GetTypeDisplayName(Type, Boolean, Boolean, Boolean, Char) + 0x36
   at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory) + 0x23
   at Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger[T](ILoggerFactory) + 0x2f
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1, IConnectionListenerFactory, ILoggerFactory) + 0x76
   at tinykestrel.Program.<Main>d__0.MoveNext() + 0x119
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x6a
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x53
   at tinykestrel.Program.<Main>(String[]) + 0x26
   at tinykestrel!<BaseAddress>+0x3424d0
```

Could you please have a look into this as it is crucial for us to keep this tiny bit working. 
@davidfowl : do you have an idea for the cause of this ? 

### Expected Behavior

Would be nice to keep the behavior backward compatible

### Steps To Reproduce

Compile https://github.com/LLT21/NativeAOT5 with .NET 7 and with .NET 8: with the former it is working, with the latter not.

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by halter73**
Fixes #50255

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/KestrelServer.cs [hunk 1]
```diff
@@ -93,7 +86,7 @@ public void Initialize(IHostEnvironment hostEnvironment, ILogger<KestrelServer>
 
         public void PopulateMultiplexedTransportFeatures(FeatureCollection features, ListenOptions listenOptions)
         {
-            HttpsConfigurationService.PopulateMultiplexedTransportFeaturesWorker(features, listenOptions, _httpsLogger);
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/KestrelServer.cs:96]: This is where I thought it might be used: https://github.com/dotnet/aspnetcore/blob/c2d95a80e60c20dd6ec9a7debc522c47782b2bf5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs#L75

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServer.cs:96]: If we need to keep it, Brennan suggested the possibility of passing the type to the logger by name, rather than as a type argument.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/KestrelServer.cs:96]: Fortunately, we throw right before reaching that line if there is no `IMultiplexedConnectionListenerFactory` available and there never should any be when using the `KestrelServer` constructor.

https://github.com/dotnet/aspnetcore/blob/c2d95a80e60c20dd6ec9a7debc522c47782b2bf5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs#L67-L75

https://github.com/dotnet/aspnetcore/blob/c2d95a80e60c20dd6ec9a7debc522c47782b2bf5/src/Servers/Kestrel/Core/src/KestrelServer.cs#L31-L39

**Comment by halter73** [comment]
Sadly, this does show there is at least one use case for calling the `KestrelServer` constructor directly rather resolving it out of DI. This could be a reason not to obsolete `KestrelServer` like [I suggested last week](https://github.com/dotnet/aspnetcore/issues/49967#issuecomment-1679648739), but this still does feel like a pretty niche use case.

File: src/Servers/Kestrel/Core/src/KestrelServer.cs (hunk 1 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServer.cs:96]: That's what I was missing.  Thanks!

File: src/Servers/Kestrel/Core/src/KestrelServer.cs [hunk 2]
```diff
@@ -93,7 +86,7 @@ public void Initialize(IHostEnvironment hostEnvironment, ILogger<KestrelServer>
...
+            throw new NotImplementedException(); // Not actually required by this impl
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/KestrelServer.cs:89]:
```suggestion
            throw new NotImplementedException(); // Not actually required by this impl, which never provides an IMultiplexedConnectionListenerFactory
```

**Review by amcasey — APPROVED** [review]

**Comment by LLT21** [comment]
Did a quick test of this branch locally and it seems to solve my issue. Will do some extra tests tomorrow as it is late in Europe.

**Comment by halter73** [comment]
@adityamandaleeka Can you merge this?

**Comment by adityamandaleeka** [comment]
Yup, approved for RC2.
