### PR TITLE
Fixed duplicate metadata in ModelDataSource

### LINKED ISSUE #34199: RouteEndpoint metadata from convention builders are duplicated
### Describe the bug

When inspecting endpoints with `EndpointDataSource`, for example in an `IApiDescriptionProvider`, some of the metadata on `RouteEndpoint` instances is duplicated. As shown in the screenshot below, there are two duplicated HTTP method metadata items.

image

Tracing through the code, this appears to be caused by a number of factors that together contribute to the routing endpoint conventions for an endpoint builder being run multiple times. The screenshot below shows the HTTP method metadata being added to the endpoint builder a second time.

image

The contributing factors to this issue appear to be:

1. There are two `CompositeEndpointDataSource` instances created by the application: https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L44 https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/DependencyInjection/RoutingServiceCollectionExtensions.cs#L65
2. Each `CompositeEndpointDataSource` enumerates the `Endpoints` property of each underlying endpoint data source once: https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/CompositeEndpointDataSource.cs#L115
3. `ModelEndpointDataSource` calls `Build()` on each convention builder each time the `Endpoints` property is accessed https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/ModelEndpointDataSource.cs#L35
4. Each call to `Build()` runs the convention action(s): https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/DefaultEndpointConventionBuilder.cs#L30-L33
5. The conventions may mutate the endpoint builder's state multiple times: https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Http/Routing/src/Builder/RoutingEndpointConventionBuilderExtensions.cs#L111-L117

The net result is that every time the `Endpoints` property of an `ModelEndpointDataSource` is accessed, the number of `Metadata` items on a route endpoint increases by the number of conventions configured.

Below is an example of four duplicate metadata items in a sample application:

image

### To Reproduce

To reproduce this issue, edit [this test](https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Mvc/test/WebSites/SimpleWebSiteWithWebApplicationBuilder/Program.cs#L11) to have the following code:

```csharp
app.MapGet("/json", (IApiDescriptionGroupCollectionProvider provider) =>
{
    if (provider.ApiDescriptionGroups is not null)
    {
        // Used to inspect and debug ApiDescriptionGroups
    }

    return Json(new Person("John", 42));
});
```

Then debug the [`JsonResult_Works()`](https://github.com/dotnet/aspnetcore/blob/b9efadc59ddbf6743775244622fb95301dd1846c/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs#L34) test with a breakpoint set here:

https://github.com/dotnet/aspnetcore/blob/b9efadc59ddbf6743775244622fb95301dd1846c/src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs#L59

Inspecting `routeEndpoint.Metadata` with the debugger will show the duplicated metadata as shown in the preceding screenshots.

### Further technical details

- ASP.NET Core version `6.0.0-preview.7.21357.1`
- .NET Core SDK `6.0.100-preview.7.21357.57`
- Visual Studio 2022 17.0.0 Preview 1.1

### PR DESCRIPTION
**Pull request by davidfowl**
- Today when we make endpoints for the ModelDataSource, we apply the callbacks to the EndpointBuilder before creating the endpoint. This happens every time anyone accesses the endpoints property. Instead of re-applying the conventions, we do it once on Build. We also throw if more conventions are added after building.
- Added tests

Fixes https://github.com/dotnet/aspnetcore/issues/34199

### CODE REVIEW

File: src/Http/Routing/src/DefaultEndpointConventionBuilder.cs [hunk 1]
```diff
@@ -12,24 +12,37 @@ internal class DefaultEndpointConventionBuilder : IEndpointConventionBuilder
...
+            conventions.Add(convention);
         }
 
         public Endpoint Build()
         {
-            foreach (var convention in _conventions)
+            // Only apply the conventions once
+            var conventions = Interlocked.Exchange(ref _conventions, null);
+
+            if (conventions != null)
```
Comment (pranavkm) [inline src/Http/Routing/src/DefaultEndpointConventionBuilder.cs:40]:
```suggestion
            if (conventions is not null)
```

File: src/Http/Routing/src/DefaultEndpointConventionBuilder.cs [hunk 2]
```diff
@@ -12,24 +12,37 @@ internal class DefaultEndpointConventionBuilder : IEndpointConventionBuilder
...
+            }
+
+            conventions.Add(convention);
         }
 
         public Endpoint Build()
         {
-            foreach (var convention in _conventions)
+            // Only apply the conventions once
+            var conventions = Interlocked.Exchange(ref _conventions, null);
```
Comment (pranavkm) [inline src/Http/Routing/src/DefaultEndpointConventionBuilder.cs:38]: It's interlocked because we're worried about `Add` / `Build` being called concurrently?

File: src/Http/Routing/test/UnitTests/Builder/DelegateEndpointRouteBuilderExtensionsTest.cs [hunk 3]
```diff
@@ -178,7 +182,61 @@ public async Task MapGetWithoutRouteParameter_BuildsEndpointWithQuerySpecificBin
...
+            var builder = new DefaultEndpointRouteBuilder(new ApplicationBuilder(new EmptyServiceProvider()));
+
+            map(builder, "/{ID}", () => { }).WithName("Foo");
+
+            var dataSource = GetBuilderEndpointDataSource(builder);
+
+            // Access endpoints a couple of times to make sure it gets built
+            _ = dataSource.Endpoints;
+            _ = dataSource.Endpoints;
+            _ = dataSource.Endpoints;
```
Comment (pranavkm) [inline src/Http/Routing/test/UnitTests/Builder/DelegateEndpointRouteBuilderExtensionsTest.cs:196]: 3 is more than a "couple".

**Review by pranavkm — APPROVED** [review]

File: src/Http/Routing/src/DefaultEndpointConventionBuilder.cs (hunk 2 above)
Comment (davidfowl) [reply src/Http/Routing/src/DefaultEndpointConventionBuilder.cs:38]: I'm just being extra defensive. It's unclear if these APIs are intended
