### PR TITLE
Release object URL after image for resize has loaded

### LINKED ISSUE #35156: Blazor InputFile RequestImageFileAsync not revoking ObjectURL
### Describe the bug
When invoking `IBrowserFile.RequestImageFileAsync`, a file/blob object URL is created for the resize operation: https://github.com/dotnet/aspnetcore/blob/1795d691005181241617007399abd3c8d10ef32a/src/Components/Web.JS/src/InputFile.ts#L62

But this objectURL is never revoked (with `URL.revokeObjectURL()`) after the resize has completed, leading to the objectURL and consequently the blob (original image file reference in this case) not being released from memory until the tab is reloaded or closed.

[createObjectURL Usage Notes (Mozilla)](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#usage_notes)

### To Reproduce
1. Run the sample to resize images.
``` razor
<InputFile OnChange="OnInputFileChange" multiple/>

<div class="image-list">
    @foreach (var imageDataUrl in imageDataUrls)
    {
        <img src="@imageDataUrl" />
    }
</div>

@code {
    IList<string> imageDataUrls = new List<string>();

    async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        var imageFiles = e.GetMultipleFiles().Where(file => file.ContentType.StartsWith("image/"));

        var format = "image/png";
        foreach (var imageFile in imageFiles)
        {
            var resizedImageFile = await imageFile.RequestImageFileAsync(format, 100, 100);
            var buffer = new byte[resizedImageFile.Size];
            await resizedImageFile.OpenReadStream().ReadAsync(buffer);
            var imageDataUrl = $"data:{format};base64,{Convert.ToBase64String(buffer)}";
            imageDataUrls.Add(imageDataUrl);
        }
    }
}
```

2. Inspect the page, and find the ever growing list of blob URLs in the sources tab.

### Further technical details
- ASP.NET 5.0

### PR DESCRIPTION
**Pull request by MichelJansson**
Releases/revokes objectURL of original image (sent to `toImageFile`) after it has been loaded, as it is no longer needed after that point.

No automated tests added, as there is no simple way (without overriding APIs anyway) to find/get existing objectURL's.
Manual testing however shows that the URL's are released by;
1. Using the sample outlined in #35156
2. Inspect page with DevTools, finding object URL's in the sources tab
3. Trying to open any of the URL's (open in new tab) -> ERR_FILE_NOT_FOUND

Fixes #35156

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=35499) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=35499) before we can accept your contribution.<br/><br/>:x: MichelJansson [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=35499)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=35499) it.</sub>

**Review by TanayParikh — COMMENTED** [review]
Thanks @MichelJansson, this looks good to me. cc/ @MackinnonBuck as he was the original author in this area so would like to get his take.

**Comment by MichelJansson** [comment]
@TanayParikh, Thanks for checking. I read somewhere that the main branch now was targeting .NET 7, is that correct? If so, should we change the target branch to one relevant for 6-rc2?

**Comment by TanayParikh** [comment]
> @TanayParikh, Thanks for checking. I read somewhere that the main branch now was targeting .NET 7, is that correct? If so, should we change the target branch to one relevant for 6-rc2?

From my understanding the `main` branch should still be appropriate for `rc2` targeted patches, I'll update if I find out otherwise.

**Comment by MackinnonBuck** [comment]
@TanayParikh This looks good to me as well

**Comment by TanayParikh** [comment]
Did some quick additional manual validations, things are looking good, ready to merge! Thanks again @MichelJansson

File: src/Components/Web.JS/src/InputFile.ts [hunk 1]
```diff
@@ -57,6 +57,7 @@ async function toImageFile(elem: InputElement, fileId: number, format: string, m
   const loadedImage = await new Promise(function(resolve: (loadedImage: HTMLImageElement) => void): void {
     const originalFileImage = new Image();
     originalFileImage.onload = function(): void {
+      URL.revokeObjectURL(originalFileImage.src);
```
Comment (pranavkm) [inline src/Components/Web.JS/src/InputFile.ts:60]: Should we also do this `onerror`? Is there an opportunity for that to happen?

Comment (TanayParikh) [reply src/Components/Web.JS/src/InputFile.ts:60]: Sure, can't hurt. Note, we'll have to `onerror = null` first though: https://stackoverflow.com/questions/8124866/how-does-one-use-the-onerror-attribute-of-an-img-element

File: src/Components/Web.JS/src/InputFile.ts [hunk 2]
```diff
@@ -57,6 +57,7 @@ async function toImageFile(elem: InputElement, fileId: number, format: string, m
...
       resolve(originalFileImage);
     };
```
Comment (TanayParikh) [inline src/Components/Web.JS/src/InputFile.ts:62]:
```suggestion
    };
    originalFileImage.onerror = function(): void {
      originalFileImage.onerror = null;
      URL.revokeObjectURL(originalFileImage.src);
    };
```

File: src/Components/Web.JS/src/InputFile.ts (hunk 1 above)
Comment (TanayParikh) [reply src/Components/Web.JS/src/InputFile.ts:60]: https://github.com/dotnet/aspnetcore/pull/35499/commits/4bb17a6f6f7fb783dd3c30ac1f92f574da3f4b40

**Review by TanayParikh — APPROVED** [review]

File: src/Components/Web.JS/src/InputFile.ts (hunk 1 above)
Comment (MichelJansson) [reply src/Components/Web.JS/src/InputFile.ts:60]: Good idea. I guess it would error out if the file sent wasn't an image?

@TanayParikh - Looks like the compiled dist/Release/blazor.*.js files didn't get this last update. From my understanding those also has to be committed?

Comment (TanayParikh) [reply src/Components/Web.JS/src/InputFile.ts:60]: > Good idea. I guess it would error out if the file sent wasn't an image?

More so if the image doesn't exist at all: 
https://www.w3schools.com/jsref/event_onerror.asp

> @TanayParikh - Looks like the compiled dist/Release/blazor.*.js files didn't get this last update. From my understanding those also has to be committed?

Usually yes, however given the final change wouldn't have any effect on tests, updating the file isn't strictly necessary here (I also didn't have push permissions via git due to this branch being on a separate fork, only could make changes via GitHub UI). Regardless, the update will be picked up automatically via the next change-set. Good eye though! 😄

**Comment by MikeReedGH** [comment]
Hi All,

This error still appears to be happening in a .Net 7 Blazor WASM PWA app :(

After calling e.File.RequestImageFileAsync I can see the blob is created in the chrome sources tab.
For each file I select a blob is created. They never disappear from the sources tab unless I refresh (f5) the page.
If I don't use the e.File.RequestImageFileAsync but rather just the e.File.OpenReadStream(e.File.Size) then the blob is not created at all, and so the memory leak does not occur.

Will the fix mentioned above made it's way into the .Net 7 release?

I am running as a client side Blazor WASM/PWA and therefore internally navigating between pages rather than just a traditional redirect in the browser, could that mean that the revokeObjectURL is never called?

Thanks and Regards

**Comment by MichelJansson** [comment]
> Hi All,
> 
> This error still appears to be happening in a .Net 7 Blazor WASM PWA app :(
> 
> After calling e.File.RequestImageFileAsync I can see the blob is created in the chrome sources tab. For each file I select a blob is created. They never disappear from the sources tab unless I refresh (f5) the page. If I don't use the e.File.RequestImageFileAsync but rather just the e.File.OpenReadStream(e.File.Size) then the blob is not created at all, and so the memory leak does not occur.
> 
> Will the fix mentioned above made it's way into the .Net 7 release?
> 
> I am running as a client side Blazor WASM/PWA and therefore internally navigating between pages rather than just a traditional redirect in the browser, could that mean that the revokeObjectURL is never called?
> 
> Thanks and Regards

@MikeReedGH The fix was implemented into .NET6 so should also have been released with .NET7. I can still see the fix in the main branch.

If i remember correctly, the blobs will still be visible under the sources tab even though they have been released. Try and open the URL's from the sources tab to see if they actually still exist (.3 of the manual testing suggested in the PR description)

**Comment by MikeReedGH** [comment]
@MichelJansson. Thanks for replying. Ah ok, so the blobs still showing may just be a red herring!? I'll check.

I do still have the problem....as soon a user selects a photo/or takes a camera photo that the WASM app just immediately crashes and restarts. It's not a silly bug in my handling of the IBrowserFile. I have quadrupled checked.
It happens seemingly randomly, it will work fine for hours and then suddenly just crash.
It just smells like a memory leak, and I really thought I had found it when reading about this bug.
I am running out of ideas :(

Thanks
