### PR TITLE
Fix unobserved JSDisconnectedException in NavigationManager

### LINKED ISSUE #47109: NavigationLock silently throws JSDisconnected exception with OnBeforeInternalNavigation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using navigation lock on server side blazor with OnBeforeInternalNavigation property set (even with empty function) UnobservedTaskException is raised with JSDisconnected inside when reloading page.

It doesn't affect the app at all and also it seems to happen randomly. 
I'm using sentry for logging and now it's all flooded with this exception. 
It's hard to reproduce locally but it happens on almost every reload while running on the cloud.

https://user-images.githubusercontent.com/50521366/224004503-b86ffdda-e848-4084-9f85-73f7f3c698f2.mp4

### Expected Behavior

Exception is not raised.

### Steps To Reproduce

1. Clone: https://github.com/gaplin/LockException
2. Run the app
3. Refresh page many times

### Exceptions (if any)

Unhandled exception. System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.)
 ---> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)

### .NET Version

7.0.200

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Fix unobserved JSDisconnectedException in NavigationManager

Fixes an issue where an unobserved `JSDisconnectedException` thrown in `NavigationManager` may invoke `TaskScheduler.UnobservedTaskException` when there is sufficient GC pressure on the server.

## Description

When all "location changing" listeners in a Blazor Server `NavigationManager` get disposed, a JS interop call notifies the browser that there is no need to invoke the .NET "location changing" event for future navigations. Assuming the application is implemented correctly, all location changing listeners will be disposed when the circuit shuts down. If the user of the app clicks the browser's refresh button, the circuit is closed and server-side Blazor state is disposed, ultimately causing the aforementioned JS interop call to run. This JS interop call will throw a `JSDisconnectedException` because the circuit has been disposed by that point.

The exception does not surface because it was thrown in a fired-and-forgotten task. However, when the `Task` object eventually gets GC'd, the `TaskScheduler.UnobservedTaskException` event gets invoked. This doesn't affect the behavior of the app, but it's annoying for customers to have to filter out meaningless unhandled exceptions thrown from the framework.

This PR fixes the problem by catching and ignoring the `JSDisconnectedException`, which is the recommended and common practice for that specific exception type.

Fixes #47109

### CODE REVIEW

File: src/Components/Server/src/Circuits/RemoteNavigationManager.cs [hunk 1]
```diff
@@ -131,11 +131,20 @@ protected override void SetNavigationLockState(bool value)
...
-        => _jsRuntime.InvokeVoidAsync(Interop.SetHasLocationChangingListeners, value).Preserve();
+    private async Task SetHasLocationChangingListenersAsync(bool value)
+    {
+        try
+        {
+            await _jsRuntime.InvokeVoidAsync(Interop.SetHasLocationChangingListeners, value);
+        }
+        catch (JSDisconnectedException)
+        {
+            // If the browser is gone, we don't need it to clean up any browser-side state
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/RemoteNavigationManager.cs:145]: This could also happen during a temporary disconnect, doesn't it?

**Review by javiercn — APPROVED** [review]
Just a question, but otherwise looks good

File: src/Components/Server/src/Circuits/RemoteNavigationManager.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/Components/Server/src/Circuits/RemoteNavigationManager.cs:145]: I think `JSDisconnectedException`s are only thrown upon permanent circuit disconnection: https://github.com/dotnet/aspnetcore/blob/3c542fec8e5e47db328f8bd631d2a5e4feb28db4/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L109-L113

**Comment by MackinnonBuck** [comment]
@javiercn I'm going to merge this now, but I can open a follow-up if there ends up being more conversation around the question in your review.
