### PR TITLE
Initialize Activity with parent ID

### LINKED ISSUE #37471: [.Net 6.0] Sampler does not receive the correct ParentId when enabling ActivitySource listener for `Microsoft.AspNetCore`
### Describe the bug

Starting .NET6.0, There is an option to subscribe to Activity created by [HostingApplicationDiagnostics.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs) by enabling listener for ActivitySource named `Microsoft.AspNetCore`. However, the approach has following two issues:

1) When using sampling, the sampler does not receive the correct parent context as the parentId is extracted after calling _activitySource.CreateActivity() [here](https://github.com/dotnet/aspnetcore/blob/4bdaaebaa8dfa94c180ea899fb8d569cbd9bb501/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L285). Due to this, the sampler which relies on parent context will not be able to make accurate sampling decisions.

2) The approach will create a new traceId for the activity even if incoming headers have requestId. This case only gets triggered when trying to access traceId from `ActivityCreationOptions<ActivityContext> options` inside sampler.

### To Reproduce

The following example shows the behavior, the code flow follows the same flow as [HostingApplicationDiagnostics.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs)

```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        ActivitySource src = new ActivitySource("Test");
        using var listener = new ActivityListener
        {
            ShouldListenTo = activitySource => true,
            Sample = (ref ActivityCreationOptions<ActivityContext> options) =>  ComputeActivitySamplingResult(options)
        };

        ActivitySource.AddActivityListener(listener);

        var _activity = src.CreateActivity("Test", ActivityKind.Server);

        // Set ParentId extracted from header
        _activity?.SetParentId("00-35aae61e3e99044eb5ea5007f2cd159b-40a8bd87c078cb4c-00");  
        _activity?.Start();

        Console.WriteLine(_activity?.ParentId); // 00-35aae61e3e99044eb5ea5007f2cd159b-40a8bd87c078cb4c-00
        Console.WriteLine(_activity?.ParentSpanId); // Expected: 40a8bd87c078cb4c, Actual: 40a8bd87c078cb4c
        Console.WriteLine(_activity?.SpanId); // new SpanId
        Console.WriteLine(_activity?.TraceId); // Expected: 35aae61e3e99044eb5ea5007f2cd159b, Actual: New Id
    }

    private static ActivitySamplingResult ComputeActivitySamplingResult(
        in ActivityCreationOptions<ActivityContext> options)
    {
        var traceID = options.TraceId; // traceId here will be the traceId for created Activity.
        var parent = options.Parent; // Parent not available here.

        return ActivitySamplingResult.AllDataAndRecorded;
    }
}


```

Also adding sample Asp.Net Core app [here](https://github.com/vishweshbankwar/DotNet6_AspNetCore_ActivitySource)

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix #37471

@noahfalk Please take a look. This seems to work but it's weird from an API perspective that calling `CreateActivity` with the parent ID specified behaves differently than specifying the parent ID using `SetParentId` between creating and starting the Activity. The difference doesn't seem to be mentioned in the API docs either unless I missed something.

### CODE REVIEW

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 1]
```diff
@@ -332,9 +323,26 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
...
+            ActivityName,
+            ActivityKind.Server,
+            string.IsNullOrEmpty(requestId) ? null! : requestId
+            );
+
+        if (activity is null)
+        {
+            if (loggingEnabled || diagnosticListenerActivityCreationEnabled)
+            {
+                activity = new Activity(ActivityName);
```
Comment (noahfalk) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:336]: I think the activity winds up unassociated with the requestId now because of the deletion at 337. We probably want this:
```C#
if(!string.IsNullOrEmpty(requestId)
{
    activity.SetParentId(requestId);
}
```

**Review by noahfalk — APPROVED** [review]

**Comment by noahfalk** [comment]
The difference you are seeing is because the sampling callback occurs during the Create() call.
```
Activity a = Activity.Create(...) // sampling callback happens inside here, from this point onwards parent is immutable
a.SetParent(foo); // ideally this would throw an exception, but for back-compat it silently has no effect
                           // I agree, its not what you would expect.
```

I submitted a docs PR to clarify the behavior. https://github.com/dotnet/dotnet-api-docs/pull/8048

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 2]
```diff
@@ -332,9 +323,26 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
             out var requestId,
             out var traceState);
 
+        Activity? activity = _activitySource.CreateActivity(
```
Comment (JamesNK) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]:
```suggestion
        var activity = _activitySource.CreateActivity(
```

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 3]
```diff
@@ -332,9 +323,26 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
...
+            ActivityName,
+            ActivityKind.Server,
+            string.IsNullOrEmpty(requestId) ? null! : requestId
+            );
+
+        if (activity is null)
```
Comment (JamesNK) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:332]: Weird that CreateActivity sometimes doesn't create an activity. Add a comment saying why activity might be null

Comment (noahfalk) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:332]: its a perf optimization, if there are no listeners the activity isn't created

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 4]
```diff
@@ -332,9 +323,32 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
             out var requestId,
             out var traceState);
 
+        var activity = _activitySource.CreateActivity(
```
Comment (vishweshbankwar) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: Should parent `ActivityContext` be passed in here with `IsRemote` set as `true` instead of ParentID?. So that the sampler gets correct details. With ParentID, `IsRemote` comes in as `false`. Not sure if there is another way to achieve that. @noahfalk @cijothomas.

My test
```csharp
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        ActivitySource src = new ActivitySource("Test");
        using var listener = new ActivityListener
        {
            ShouldListenTo = activitySource => true,
            Sample = (ref ActivityCreationOptions<ActivityContext> options) => ComputeActivitySamplingResult(options)
        };
        ActivitySource.AddActivityListener(listener);

        var parentId = "00-35aae61e3e99044eb5ea5007f2cd159b-40a8bd87c078cb4c-00";

        // Create using parentID
        // var _activity = src.CreateActivity("Test", ActivityKind.Server, parentId);

        var ctx = new ActivityContext(ActivityTraceId.CreateFromString("35aae61e3e99044eb5ea5007f2cd159b"),
            ActivitySpanId.CreateFromString("40a8bd87c078cb4c"),
            ActivityTraceFlags.None,
            null,
            true);

        // Create using ctx
        var _activity = src.CreateActivity("Test", ActivityKind.Server, ctx);
    }

    private static ActivitySamplingResult ComputeActivitySamplingResult(
        in ActivityCreationOptions<ActivityContext> options)
    {
        var isRemote = options.Parent.IsRemote;
        Console.WriteLine(isRemote);
        return ActivitySamplingResult.AllDataAndRecorded;
    }
}
```

Comment (cijothomas) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: Good callout!

The extractor itself is expected to set IsRemote as true. It looks like extractor is not extracing `ActivityContext` but rather doing the string traceparent only. I think the best that can be done now, is to create ActivityContext here from the extracted traceparent, and set IsRemote to true, and pass it to the StartActivity call.

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 5]
```diff
@@ -332,9 +323,32 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
...
+            ActivityName,
+            ActivityKind.Server,
+            string.IsNullOrEmpty(requestId) ? null! : requestId
```
Comment (cijothomas) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:329]: nit: It might be a good opportunity to rename requestId variables to traceParent..

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs (hunk 4 above)
Comment (noahfalk) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: @tarekgh 

This looks like a deeper issue. The interface for the propagator doesn't have any parameter to pass out the isRemote boolean though I would think isRemote=true is implied if you are in a scenario where the id needs to be deserialized from a message. CreateActivity() also has no parameter to pass it in even if the propagator did specify it. ActivityContext does have the isRemote property, but converting the string id to ActivityContext is only legal for W3C TraceParent format ids, not for hierarchical format ids. Internally ActivitySource.CreateActivity determines the ID format is W3C and converts it to an ActivityContext at which point it is an arbitrary decision to resolve the ambiguity isRemote = false. 

https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/ActivityCreationOptions.cs,60

isRemote = false is probably the rare case in practice so it is unfortunate I didn't spot it. Changing that behavior is technically breaking, but maybe we should do it. Another alternative would be adding more overloads where we can pass in more information that eliminates the isRemote ambiguity. Thoughts?

Comment (tarekgh) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: Can the caller try to parse the Id to ActivitContext before calling CreateActivity and set the desired remote value? If the Id cannot be parsed, do we care much about this case? If we care, I think we go with the breaking change, and it is not worth introducing new APIs just for this case.

Comment (noahfalk) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: yeah it is possible for the caller to do it as a workaround, but is that the pattern you'd want to document as the proper way for everyone to use the API going forward? Effectively the 'HelloWorld' of receiving a message and starting an Activity would change from:

```C#
using(var activity = src.CreateActivity("Test", ActivityKind.Server, id))
{
   ...
}
```

into:

```C#
Activity? a = null;
if(ActivtyContext.TryParse(id, isRemote:true, out ActivityContext ctx))
{
    activity = src.CreateActivity("Test", ActivityKind.Server, ctx);
}
else
{
    activity = src.CreateActivity("Test", ActivityKind.Server, id);
}
using(activity)
{
   ...
}
```

Comment (tarekgh) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]:
```C#
            using (Activity? a = ActivityContext.TryParse("Id", "", true, out ActivityContext context) ? aSource.CreateActivity("A", ActivityKind.Server, context) : aSource.CreateActivity("A", ActivityKind.Server, "id"))
            {

            }
```
Not perfect but acceptable, I guess. Also, in general, should we promote using ActivityContext over Id's?

Comment (noahfalk) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: > Not perfect but acceptable, I guess

You can make the call. Neither option is risk-free. Two downsides of this one I could foresee:
1. Other implementers who aren't ASP.NET are unlikely to replicate the workaround so the error will probably be repeated in the future.
2. This pattern forces paying a small perf cost to parse the ID prior to knowing if there are any listeners who care about it.

> Also, in general, should we promote using ActivityContext over Id's?

I think this still comes down to how much effort should be make for back-compat with hierarchical IDs. So far we've seen very little feedback saying people cared about hierarchical so I think its fine for us to continue moving away from it while keeping an eye out for feedback.

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: @noahfalk @tarekgh What do you think? Is this worth changing or should I leave it as-is?

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: Is there a way to achieve this on .NET 6? The `isRemote` option on `TryParse` seems new in 7 right? I think there was some desire to have this change backported to 6. If that's the case, I think there's value in having the behavior be consistent across versions.

Comment (tarekgh) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:326]: I expect aspn.net will reference the latest `System.Diagnostics.DiagnosticSource` package that will ship with .NET 7.0. no? 

If you still want to work around the issue, you can have the helper method:

```C#
        private static bool TryParseActivityContext(string traceParent, string traceState, bool isRemote, out ActivityContext context)
        {
            if (ActivityContext.TryParse(traceParent, traceState, out context))
            {
                if (isRemote)
                {
                    context = new ActivityContext(context.TraceId, context.SpanId, context.TraceFlags, context.TraceState, isRemote);
                }
                return true;
            }
            
            return false;
        }
```

and then the calling code will look like:

```C#
            using (Activity? a = aSource.HasListeners() ? 
                                 TryParseActivityContext("Id", "", true, out ActivityContext context) ?  aSource.CreateActivity("A", ActivityKind.Server, context) : aSource.CreateActivity("A", ActivityKind.Server, "id") : 
                                 null)
            {
                ...
            }
```

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs]: Thanks @tarekgh. I just pushed an update using this approach (verified that it would apply the same way to 6.0 as well if we decide to backport it).

**Review by HaoK — APPROVED** [review]

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 6]
```diff
@@ -307,20 +307,26 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
         HostingEventSource.Log.RequestStart(httpContext.Request.Method, httpContext.Request.Path);
     }
 
-    [MethodImpl(MethodImplOptions.NoInlining)]
-    private Activity? StartActivity(HttpContext httpContext, bool loggingEnabled, bool diagnosticListenerActivityCreationEnabled, out bool hasDiagnosticListener)
+    private static bool TryParseActivityContext(string traceParent, string traceState, bool isRemote, out ActivityContext context)
```
Comment (noahfalk) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:310]: Nit: isRemote will always be true for you. You could eliminate the argument and simplify the logic.

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 7]
```diff
@@ -307,20 +307,26 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
...
     {
-        var activity = _activitySource.CreateActivity(ActivityName, ActivityKind.Server);
-        if (activity is null && (loggingEnabled || diagnosticListenerActivityCreationEnabled))
+        if (ActivityContext.TryParse(traceParent, traceState, out context))
```
Comment (noahfalk) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:312]: probably worth adding a comment that this could be simplified with the TryParse overload we added in .NET 7 as soon as you don't need to run on 6 any longer.

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 8]
```diff
@@ -332,9 +338,41 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
             out var requestId,
             out var traceState);
 
+        Activity? activity = null;
+        if (_activitySource.HasListeners())
+        {
+            if (TryParseActivityContext("Id", "", true, out ActivityContext context))
```
Comment (noahfalk) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:344]:
```suggestion
            if (TryParseActivityContext(requestId, traceState, true, out ActivityContext context))
```

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 9]
```diff
@@ -332,9 +338,41 @@ private static void RecordRequestStartEventLog(HttpContext httpContext)
...
+            {
+                // We have an existing context, let's use it.
```
Comment (noahfalk) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:346]:
```suggestion
// The requestId used W3C id format. Unfortunately the ActivitySource.CreateActivity overload with a string id sets
// ActivityContext.IsRemote = false when it parses the string internally. We work around that by using the
// ActivityContext id overload instead and setting ActivityContext.IsRemote = true after parsing it.
```

**Review by noahfalk — APPROVED** [review]
A few suggestions inline, but other than that LGTM

**Comment by JamesNK** [comment]
Can this be unit tested? Non-obvious behavior like diagnostics is easy to break without anyone noticing. IMO unit tests are required to keep this working long term.

**Comment by adityamandaleeka** [comment]
Thanks for the reviews. I've updated with feedback and added a regression test.

**Review by JamesNK — APPROVED** [review]

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs (hunk 7 above)
Comment (halter73) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:312]: Wait. This PR is for `main` right? Don't we have access to the most up-to-date .NET 7 preview versions of System.Diagnostics.DiagnosticSource?

https://github.com/dotnet/aspnetcore/blob/9a81d79124c46fa883132b48715ab3a08b7425a5/eng/Dependencies.props#L72

Can we update this to use the right `TryParse` overload and `isRemote: true` here and change only do the more complicated thing in `release/6.0`?

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:312]: Yea, I was on the fence about this at first because I wanted to minimize the delta, but now that it's done it seems simple enough that it's probably worth it.

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs]: Done.

**Comment by davidfowl** [comment]
Wait, I just realized this change went in. @adityamandaleeka and @noahfalk does this mean that we don't get a span id if logging is enabled and there's  no activity listener wired up?

**Comment by davidfowl** [comment]
Scratch that, I found the line of code https://github.com/dotnet/aspnetcore/blob/55f7089461d58a38951762b57be32e0cda199d90/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L350
