### PR TITLE
[Authentication] Use existing principal for single scheme

### LINKED ISSUE #32340: Windows authorization fails when specifying both Roles and AuthenticationSchemes
### Describe the bug
When using Windows authentication (using the Negotiate package), specifying both `Roles` and `AuthenticationSchemes` in the `[Authorize]` attribute fails when it should succeed.

It's likely to be caused by the `PolicyEvaluator`, which merges identities into a single principal, see [here](https://github.com/dotnet/aspnetcore/blob/v5.0.5/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L46). However this means the `WindowsPrincipal` is lost which is crucial to decoding the `groupsid` groups from AD when the authorization calls `IsInRole`.

Is this expected behavior? Am I doing something wrong?

### To Reproduce

Controller endpoint:
```c#
[ApiController]
public class WeatherForecastController : ControllerBase
{
    [Authorize(Roles = "Everyone", AuthenticationSchemes = NegotiateDefaults.AuthenticationScheme)]
    [HttpGet("weatherforecast")]
    public IActionResult Get()
    {
        // This endpoint call fails

        // Type of user is `ClaimsPrincipal`
        // If I remove `AuthenticaitonSchemes`, it is `WindowsPrincipal`
        var user = User;

        return Ok();
    }
}
```

Vanilla startup using Kestrel:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services
        .AddAuthentication(NegotiateDefaults.AuthenticationScheme)
        .AddNegotiate();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app
        .UseRouting()
        .UseAuthentication()
        .UseAuthorization()
        .UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
}
```

### Further technical details
- ASP.NET Core version `5.0`
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/32340

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

File: src/Shared/SecurityHelper/SecurityHelper.cs [hunk 1]
```diff
@@ -22,6 +22,12 @@ internal static class SecurityHelper
         /// <param name="additionalPrincipal">The <see cref="ClaimsPrincipal"/> containing <see cref="ClaimsIdentity"/> to be added.</param>
         public static ClaimsPrincipal MergeUserPrincipal(ClaimsPrincipal? existingPrincipal, ClaimsPrincipal? additionalPrincipal)
         {
+            // For the first principal, just use the new principal rather than copying it
+            if (existingPrincipal == null && additionalPrincipal != null)
+            {
+                return additionalPrincipal;
+            }
```
Comment (Tratcher) [inline src/Shared/SecurityHelper/SecurityHelper.cs:29]: The method signature claims either could be null? Should we apply the same short circuit if they're reversed?
```suggestion
        public static ClaimsPrincipal? MergeUserPrincipal(ClaimsPrincipal? existingPrincipal, ClaimsPrincipal? additionalPrincipal)
        {
            // For the first principal, just use the new principal rather than copying it
            if (existingPrincipal == null || additionalPrincipal == null)
            {
                return existingPrincipal ?? additionalPrincipal;
            }
```

Comment (HaoK) [reply src/Shared/SecurityHelper/SecurityHelper.cs:29]: Discussed offline and we are ok without this
