### PR TITLE
Fixed duplicate LoggerMessage EventNames in RemoteJSRuntime.cs file

### LINKED ISSUE #46072: Decide if duplicate EventNames in LoggerMessage is appropriate
We have a couple cases caught by the new LoggerMessage analyzer in https://github.com/dotnet/runtime/issues/64667.

Two duplicates here: `InvokeDotNetMethodException` and `InvokeDotNetMethodSuccess`
https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L199-L209

And a duplicate `LocationChangeFailed` between:

https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/CircuitHost.cs#L761-L762
https://github.com/dotnet/aspnetcore/blob/334da01db159058defbd39f128d659ddf3ae3f7e/src/Components/Server/src/Circuits/CircuitHost.cs#L812-L813

I've suppressed these warnings in #46055 for now. But we should make a conscious decision if we really want/need these EventNames to be the same, or if we should change them. My understanding is changing them is technically a breaking change, so we should be sure that they need changing if we do.

### PR DESCRIPTION
**Pull request by shiladitya-mukerji-22**
# fixing_duplicate_eventnames

In the RemoteJSRuntime.cs file EventNames of four Log Messages were duplicates of already existing names. So I modified the EventNames to make each one unique.

## Description

Fixed duplicate LoggerMessage EventNames in RemoteJSRuntime.cs file

Fixes #46072

### CODE REVIEW

**Comment by shiladitya-mukerji-22** [comment]
@dotnet-policy-service agree [company="Default"]
@dotnet-policy-service agree

**Comment by shiladitya-mukerji-22** [comment]
@dotnet-policy-service agree

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 1]
```diff
@@ -810,7 +810,7 @@ public static void BeginInvokeDotNetFailed(ILogger logger, string callId, string
         }
 
 #pragma warning disable SYSLIB1025
-        [LoggerMessage(219, LogLevel.Error, "Location change to '{URI}' in circuit '{CircuitId}' failed.", EventName = "LocationChangeFailed")]
+        [LoggerMessage(219, LogLevel.Error, "Location change to '{URI}' in circuit '{CircuitId}' failed.", EventName = "LocationChangeFailedInCircuit")]
```
Comment (Eilon) [inline src/Components/Server/src/Circuits/CircuitHost.cs:813]: What event name do you get if you remove `EventName` entirely? I've never specified the Event Name so I figured the default would be that is uses the method name. If that's the case then it would be even simpler.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @shiladitya-mukerji-22.
@javiercn can you please review this? Thanks!

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 1 above)
Comment (shiladitya-mukerji-22) [reply src/Components/Server/src/Circuits/CircuitHost.cs:813]: Hello @Eilon. Thank you for the question. Generally if the event name attribute is not provided when defining a `LoggerMessage`, the logging system will generate a default event name based on the `LoggerMessage `type and the position of the `LoggerMessage `definition in the source code.

The default event name is generated by concatenating the namespace, class name, and method name of the `LoggerMessage `definition, separated by dots in between. For now, I have provided the event name attribute to maintain the syntax uniformity in the code. If required I think it can be removed.

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
@shiladitya-mukerji-22 thanks for the contribution @shiladitya-mukerji-22!

**Comment by javiercn** [comment]
The last bit is that I think we need to publish an announcement for the event name changes
