### PR TITLE
[Blazor][Fixes #12056] Avoid producing warnings for bad inputs.

### LINKED ISSUE #12056: [Blazor] Incorrect batch acks should not produce warnings
We should log them as info events as otherwise the server logs get easily spammed with warnings

### PR DESCRIPTION
**Pull request by javiercn**
* Does not produce warnings when receiving invalid event arguments.
* Does not produce warnings when receiving an invalid event handler id.
* Does not produce warnings when receiving an ack for an unknown batch.

### CODE REVIEW

File: src/Components/Components/src/Rendering/InvalidEventException.cs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+        {
+        }
+
+        /// <summary>
+        /// Initializes a new instance of <see cref="InvalidEventException"/>.
+        /// </summary>
+        /// <param name="eventId">The id of the invalid event.</param>
+        /// <param name="message">The message explaining the reason for the error.</param>
+        /// <param name="exception">The original exception that caused the issue.</param>
+        public InvalidEventException(ulong eventId, string message, Exception exception) : base(message + $" EventId: {eventId}", exception)
```
Comment (rynowak) [inline src/Components/Components/src/Rendering/InvalidEventException.cs]: Should we order these the same way the base class does?

Comment (rynowak) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: `message + $" EventId: {eventId}"` do we need this? 

Usually it's pretty surprising when a constructor modifies the value you give it. Like if a class has a message property and a message constructor parameter, I don't want anything tricky to happen 😆 

Should we just inline this into the places where we need it?

File: src/Components/Server/src/ComponentHub.cs [hunk 2]
```diff
@@ -225,6 +236,16 @@ private async void CircuitHost_UnhandledException(object sender, UnhandledExcept
...
         }
 
+        private bool IsBadInput(Exception exception)
+        {
+            return exception switch
+            {
+                InvalidEventException _ => true,
+                RemoteRendererException { BadInput: true } => true,
+                _ => false
+            };
```
Comment (rynowak) [inline src/Components/Server/src/ComponentHub.cs]:
```C#
while (true)
{
    pranavPoints++;
}
```

File: src/Components/Server/src/Circuits/RemoteRendererException.cs [hunk 3]
```diff
@@ -5,17 +5,17 @@
...
         public RemoteRendererException(string message) : base(message)
         {
         }
+
+        public RemoteRendererException(bool badInput, string message) : this (message)
+        {
+            BadInput = badInput;
+        }
+
+        public bool BadInput { get; }
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/RemoteRendererException.cs]: Can we find a better piece of terminology for this? Like `IsMisbehavingClient`? Something more descriptive

File: src/Components/Components/src/Rendering/InvalidEventException.cs [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+
+namespace Microsoft.AspNetCore.Components.Rendering
+{
+    /// <summary>
+    /// Thrown when the renderer receives an invalid event ID that it can't dispatch.
+    /// </summary>
+    public class InvalidEventException : Exception
```
Comment (rynowak) [inline src/Components/Components/src/Rendering/InvalidEventException.cs]: Is the idea of this that the renderer will use more specific types of exceptions to indicate violations of its contract? 

Does this approach scale in practice? Like, are there other places in the renderer where we would define custom exceptions? How many would we end up with?


Should this inherit from `ArgumentException`?

File: src/Components/Server/src/ComponentHub.cs [hunk 5]
```diff
@@ -202,7 +204,16 @@ private async void CircuitHost_UnhandledException(object sender, UnhandledExcept
...
-                Log.UnhandledExceptionInCircuit(_logger, circuitId, (Exception)e.ExceptionObject);
+                var exception = (Exception)e.ExceptionObject;
+                if (!IsBadInput(exception))
+                {
+                    Log.UnhandledExceptionInCircuit(_logger, circuitId, exception);
+                }
+                else
+                {
+                    Log.UnhandledExceptionFromBadInput(_logger, circuitId, exception);
+                }
```
Comment (rynowak) [inline src/Components/Server/src/ComponentHub.cs]: I really like that the intention is that we can tell the difference between user code throwing and framework code - I just want to make sure we're thinking about the problem holistically.

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: My intention was to try and ensure that the event ID is always registered when we log/view the exception. We definitely could inline it in the places where we used. 

I was not sure about providing structured data vs ensuring the message always contains all the information.

File: src/Components/Server/src/Circuits/RemoteRendererException.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRendererException.cs]: I couldn't really think of a better name, I considered your suggestion, It might be me, but I interpret Misbehaving in this context as "Malicious" and I don't like to give it that implication.

There are different things we could do otherwise:
* Throw a more specialized exception. InvalidRenderBatchAcknowledge exception.
* Have a boolean to indicate that this was caused by an invalid acknowledge.
* Have an enum with the reasons why this failed.

In the end, all three options achieve the same goal, which is to allow us to differentiate specific situations that can be caused by bad input/bad clients from things we do care about.

Whatever option we choose I don't think it matters at all given this class is internal.
* bool is the cheapest.
* Followed by the enum.
* Having a derived class is the most expensive.

I would be ok with being explicit here and naming it InvalidRenderBatchAcknowledge or similar, thoughts?

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Sort of.

* We need to differentiate bad input from errors in the app, as we want to log them with different importance (and in the future we might decide to do different things).
* We need an exception we can throw in Components when we parse the event arguments or when we receive an event for which there's no associated event handler (both of which can be caused by bad input).

I wouldn't extend ArgumentException, this exception is thrown in response to an argument not being valid, but we are the only ones to throw and consume this exception and having the argument information doesn't add any value.

To go even further, I would even put this exception in the .Internal namespace if we can, as its purely infrastructure.

WRT scalability of the app, there are only three other places where we interact with user code.
* When we instantiate a component.
* When we run the BuildRenderTree (or equivalent) function from the component.
* When we run the handler for an event.


We currently don't explicitly catch exceptions in those call-sites (except for the handler). We simply let the exception bubble up (ultimately reaching ProcessRenderQueue) and we handle it there.

I don't think there's any special value in throwing a custom exception in those cases as we always do the same thing for exceptions in those cases.
* Log a warning.
* Terminate the circuit.

Accepting that the renderer is not something we expect customers to extend/replace, we could if we wanted introduce a new exception in the future, when we find a reason it adds value.

At that point, I would simply catch all exceptions at the call-sites and would wrap them inside a ComponentException or similar, but even if we were to create an exception hierarchy we woud have at most two or 3 new types to represent all the error space, I think:
* Exception in constructor.
* Exception injecting dependencies. (Could be folded into the one above)
* Exception rendering the component.
* Exception setting the parameters for the component.

That said, I don't think we need to be specific about any of the above as they all result in the same action.

File: src/Components/Server/src/ComponentHub.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: Explanation in the comment above.

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 4 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: I like the overall design here.

Regarding making this `public`, that's just because it has to be referenced in `.Server`, right? But the `.Server` project doesn't do anything more specific with `InvalidEventException` other than recognize its type?

If this is the case, instead of each of the exception types being `public`, could we have one `public` base class for them (e.g., `InvalidIncomingMessageException`)? Then that's the only thing `.Server` has to look for, and we can have as many `internal` subclasses as we want without it being visible on the public API surface.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Also, on naming, could we do something to be super clear that this means *incoming data was invalid*, as opposed to some other sense in which the event was "invalid"? For example, `InvalidIncomingEventDataException`.

File: src/Components/Components/src/Rendering/InvalidEventException.cs [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+    {
+        /// <summary>
+        /// Initializes a new instance of <see cref="InvalidEventException"/>.
+        /// </summary>
+        /// <param name="eventId">The id of the invalid event.</param>
+        public InvalidEventException(ulong eventId)
+            : this(eventId, $"There is no event handler associated with this event.")
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/Rendering/InvalidEventException.cs]: TBH it's strange to have this constructor overload with a hardcoded message that isn't completely obvious from the signature. Could this overload be `(ulong eventId, string message)`, so the caller specifies the message?

Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Oh in fact I see that overload already exists below. So could this one be removed?

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 7]
```diff
@@ -202,6 +202,18 @@ public async Task DispatchEvent(string eventDescriptorJson, string eventArgs)
             }
         }
 
+        internal void OnRenderCompleted(long renderId, string errorMessageOrNull)
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: Can be `public`, since the type itself is already `internal`

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 8]
```diff
@@ -202,6 +202,18 @@ public async Task DispatchEvent(string eventDescriptorJson, string eventArgs)
...
+        {
+            try
+            {
+                Renderer.OnRenderCompleted(renderId, errorMessageOrNull);
+            }
+            catch (Exception e)
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: It looks like the change here is to stop calling `HandleException` from `RemoteRenderer`'s `OnRenderCompleted`, and instead have that throw, but catch the exception here and then pass it on to the equivalent `UnhandledException`.

My awareness of all the code paths isn't super fresh, but it seems more or less the same result. Could you clarify for me why we're making this change? What different scenarios does it handle?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 9]
```diff
@@ -248,8 +248,9 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
 
                 if (lastBatchId < incomingBatchId)
                 {
-                    HandleException(
-                        new InvalidOperationException($"Received an acknowledgement for batch with id '{incomingBatchId}' when the last batch produced was '{lastBatchId}'."));
+                    // This exception is due to a bad client input, so we mark it as such to prevent loging it as a warning and
+                    // flooding the logs with warnings.
+                    throw new RemoteRendererException(badInput: true, $"Received an acknowledgement for batch with id '{incomingBatchId}' when the last batch produced was '{lastBatchId}'.");
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Why have a `bool` flag on `RemoteRendererException` instead of a more specific exception type like `InvalidAcknowledgementBatchIdException`?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 10]
```diff
@@ -248,8 +248,9 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
 
                 if (lastBatchId < incomingBatchId)
                 {
-                    HandleException(
-                        new InvalidOperationException($"Received an acknowledgement for batch with id '{incomingBatchId}' when the last batch produced was '{lastBatchId}'."));
+                    // This exception is due to a bad client input, so we mark it as such to prevent loging it as a warning and
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
                    // This exception is due to a bad client input, so we mark it as such to prevent logging it as a warning and
```

File: src/Components/Server/src/Circuits/RemoteRendererException.cs (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/RemoteRendererException.cs]: > Throw a more specialized exception. InvalidRenderBatchAcknowledge exception.

I'd go with that if possible as it's super clear. I'm not sure in what sense it would be more expensive.

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/ComponentHub.cs]: TBH I find this pattern of checking for specific types to be an issue in the long run. When people try to implement a new feature following the same pattern (e.g., defining a new exception type for invalid input, equivalent to `InvalidEventException`), there's nothing to force them to discover the need to also add it to the list here. By default they won't, and then that type will get logged as a warning. Even if they know they have to do something to whitelist their new exception type, there's no way of pressing F12 to follow the trail here.

If we had a common base type for "invalid input exception" this problem would disappear, as anyone copy-pasting the same approach as an existing bit of code would naturally copy the same base type for their new exception type.

File: src/Components/Web/src/RendererRegistryEventDispatcher.cs [hunk 11]
```diff
@@ -54,36 +54,30 @@ private static void InterpretEventDescriptor(BrowserEventDescriptor eventDescrip
...
-                    return Deserialize<UIProgressEventArgs>(eventArgsJson);
-                case "touch":
-                    return Deserialize<UITouchEventArgs>(eventArgsJson);
-                case "unknown":
-                    return Deserialize<UIEventArgs>(eventArgsJson);
-                case "wheel":
-                    return Deserialize<UIWheelEventArgs>(eventArgsJson);
-                default:
-                     throw new ArgumentException($"Unsupported value '{eventArgsType}'.", nameof(eventArgsType));
+                return eventArgsType switch
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/RendererRegistryEventDispatcher.cs]: Nice

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (rynowak) [reply src/Components/Server/src/ComponentHub.cs]: Another idea here would be to use a different kind of event args in our unhandled exception event. Then we could pass in whethere the execption was based on input, or background. It doesn't require defining new exception types, just a new eventargs type.

Comment (rynowak) [reply src/Components/Server/src/ComponentHub.cs]: For context, I discovered that .NET already has an `UnhandledExceptionEventArgs` which is what we're using. This could just be it's own type with all of the info we need.

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: @SteveSandersonMS Here are some thoughts:
* I wanted to avoid having something that was very specific to the server, like someone sent you bad input.
* The InvalidEvent sounded general enough to be thrown in the cases where we care about.
  * I don't expect us to have many of these.
  * I believe introducing a base class is not a breaking change, so we can do it later if we need to.
  * I see your point about IncommingData vs InvalidEventException, but I would like to see if we can find a better name. Maybe InvalidEventDescriptorException?

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: I think I'm going to inline the Event ID into the message at the call-sites and be done with it. (Will get rid of the EventId field)

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: I'm going to take it out and simply leave the string and string,exception overloads.

File: src/Components/Components/src/Rendering/InvalidEventException.cs [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+        /// <param name="message">The message explaining the reason for the error.</param>
+        public InvalidEventException(ulong eventId, string message) : base(message + $" EventId: {eventId}")
+        {
+            EventId = eventId;
+        }
+
+        /// <summary>
+        /// The id of the event.
+        /// </summary>
+        public ulong EventId { get; set; }
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Getting rid of htis

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 7 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: Will change

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: It does less logging.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Because it's internal, cheaper than having another type and is not going to be used inside a catch block, so there's no value of having an additional exception.

Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: My opinion is that exception hierarchies are good when you have public consumers or when you use them to handle different scenarios in code through catch blocks, when that's not the case, having an additional type is less valuable.

File: src/Components/Server/src/Circuits/RemoteRendererException.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRendererException.cs]: Ok, seems you feel super strong about having an additional exception type, so I'll just add one.

File: src/Components/Web/src/RendererRegistryEventDispatcher.cs (hunk 11 above)
Comment (javiercn) [reply src/Components/Web/src/RendererRegistryEventDispatcher.cs]: Also @pranavkm points 💲💲💲

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: I got rid of the EventId

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: done

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 7 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: done

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Removed the bool, switched to use specific exceptions

File: src/Components/Server/src/Circuits/RemoteRendererException.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRendererException.cs]: Added an additional exception type.

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: I believe we cover all the cases where we process input already. This wouldn't be a feature for customers to use if that's what it's implied here.

Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: This is also obsolete and has its own custom exception type.

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Would a marker interface play the same role here?

**Comment by javiercn** [comment]
:up :date:

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: Got rid of this, as we don't need it with Ryan's changes

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Used a different exception for this.

File: src/Components/Components/src/Rendering/InvalidEventException.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/InvalidEventException.cs]: I got rid of the type entirely

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 13]
```diff
@@ -143,6 +128,23 @@ public Task InitializeAsync(CancellationToken cancellationToken)
             });
         }
 
+        public async Task OnRenderCompleted(long renderId, string errorMessageOrNull)
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: Please add some comments here about the expected usage of this method, and its error handling model.

Please move this somewhere after the lifecycle methods. Right now this is right between `InitializeAsync` and `DisposeAsync`.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 14]
```diff
@@ -143,6 +128,23 @@ public Task InitializeAsync(CancellationToken cancellationToken)
...
+            AssertInitialized();
+            AssertNotDisposed();
+
+            try
+            {
+                await Renderer.OnRenderCompleted(renderId, errorMessageOrNull);
+            }
+            catch (Exception e)
+            {
+                Log.OnRenderCompletedFailed(_logger, renderId, CircuitId, e);
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: Please add some comments here about the kinds of things that cause errors, and why this is the right error handling strategy.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 15]
```diff
@@ -565,37 +551,47 @@ private async void SynchronizationContext_UnhandledException(object sender, Unha
         private async Task ReportUnhandledException(Exception exception)
         {
             Log.CircuitUnhandledException(_logger, CircuitId, exception);
+
             if (!Client.Connected)
             {
-                _logger.LogDebug("Client is disconnected YO.");
+                Log.UnhandledExceptionClientDisconnected(_logger, CircuitId, exception);
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: I would expect this to appear at L582 so that it gets logged in all cases.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 16]
```diff
@@ -565,37 +551,47 @@ private async void SynchronizationContext_UnhandledException(object sender, Unha
...
             {
-                Log.CircuitUnhandledExceptionFailed(_logger, CircuitId, ex);
+                return
+                    $"There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on " +
+                    $"detailed exceptions in '{typeof(CircuitOptions).Name}.{nameof(CircuitOptions.DetailedErrors)}'. {additionalInformation}";
             }
         }
 
-        private async Task NotifyClientError(IClientProxy client, string error)
+        private async Task TryNotifyClientError(IClientProxy client, string error)
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: `NotifyClientErrorAsync`?

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 17]
```diff
@@ -850,6 +874,10 @@ public static void BeginInvokeDotNetFailed(ILogger logger, string callId, string
...
             public static void LocationChangeFailed(ILogger logger, string uri, string circuitId, Exception exception) => _locationChangeFailed(logger, uri, circuitId, exception);
             public static void LocationChangeFailedInCircuit(ILogger logger, string uri, string circuitId, Exception exception) => _locationChangeFailedInCircuit(logger, uri, circuitId, exception);
+            public static void UnhandledExceptionClientDisconnected(ILogger logger, string circuitId, Exception exception) => _unhandledExceptionClientDisconnected(logger, circuitId, exception);
+            public static void CircuitTransmittingClientError(ILogger logger, string circuitId) => _circuitTransmittingClientError(logger, circuitId, null);
+            public static void CircuitTransmittedClientErrorSuccess(ILogger logger, string circuitId) => _circuitTransmittedClientErrorSuccess(logger, circuitId, null);
+            public static void OnRenderCompletedFailed(ILogger logger, long renderId, string circuitId, Exception e) => _onRenderCompletedFailed(logger, renderId, circuitId, e);
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: Thanks for cleaning all of this up.

File: src/Components/Shared/src/WebEventData.cs [hunk 18]
```diff
@@ -44,43 +53,34 @@ private WebEventData(int browserRendererId, ulong eventHandlerId, EventFieldInfo
...
+                    "progress" => Deserialize<UIProgressEventArgs>(eventArgsJson),
+                    "touch" => Deserialize<UITouchEventArgs>(eventArgsJson),
+                    "unknown" => EventArgs.Empty,
+                    "wheel" => Deserialize<UIWheelEventArgs>(eventArgsJson),
+                    _ => throw new InvalidOperationException($"Unsupported event type '{eventArgsType}'. EventId: '{eventHandlerId}'."),
+                };
+            }
+            catch (Exception e)
+            {
+                throw new InvalidOperationException($"There was an error parsing the event arguments. EventId: '{eventHandlerId}'.", e);
```
Comment (rynowak) [inline src/Components/Shared/src/WebEventData.cs]: This is kinda bizzare, why does including the event id here help anyone track down a problem? ids aren't really memorable.

File: src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs [hunk 19]
```diff
@@ -20,7 +23,7 @@ namespace Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests
 {
     public class ComponentHubReliabilityTest : IClassFixture<AspNetSiteServerFixture>, IDisposable
     {
-        private static readonly TimeSpan DefaultLatencyTimeout = TimeSpan.FromSeconds(10);
+        private static readonly TimeSpan DefaultLatencyTimeout = TimeSpan.FromSeconds(Debugger.IsAttached ? 60 : 10);
```
Comment (rynowak) [inline src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs]: Why not something like *much bigger** if you're debugging?

File: src/Components/Server/src/Circuits/RenderCompletionException.cs [hunk 20]
```diff
@@ -0,0 +1,14 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+
+namespace Microsoft.AspNetCore.Components.Web.Rendering
+{
+    internal class RenderCompletionException : Exception
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/RenderCompletionException.cs]: Where is this *caught*? Do we need this type if no one is catching it?

File: src/Components/Shared/src/WebEventData.cs (hunk 18 above)
Comment (javiercn) [reply src/Components/Shared/src/WebEventData.cs]: That's fair, but it can give you hints, for example, low value event ids signal that the problem happens relatively early in the lifecycle of the app.

File: src/Components/Server/src/Circuits/RenderCompletionException.cs (hunk 20 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RenderCompletionException.cs]: This was RemoteRenderer, we have two internal exceptions RenderCompletionException and InvalidRenderAcknowledgeException. We don't catch any of them specifically, but their name would show up in the logs.

We can simply remove them, I don't feel strongly about it.

Comment (javiercn) [reply src/Components/Server/src/Circuits/RenderCompletionException.cs]: (Removing them was something I already considered, just wasn't sure what your opinions would be)

File: src/Components/Shared/src/WebEventData.cs (hunk 18 above)
Comment (javiercn) [reply src/Components/Shared/src/WebEventData.cs]: It's also you are likely be able to search for in the frames under the network tab, if you want to see the payload.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: done

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: done

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 16 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: done

**Comment by javiercn** [comment]
:up: :date: @rynowak Anything left here?

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 21]
```diff
@@ -342,6 +327,28 @@ private async Task OnCircuitDownAsync(CancellationToken cancellationToken)
             }
         }
 
+        // Called by the client when it completes rendering a batch.
+        // OnRenderCompleted is used in a fire-and-forget context, so it's responsible for its own
+        // error handling.
+        public async Task OnRenderCompleted(long renderId, string errorMessageOrNull)
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: `OnRenderCompleteAsync` please, the rest of the methods in this class are using that convention.

**Comment by rynowak** [comment]
Looking good now. Just one nitpick about a name from me.

**Review by rynowak — APPROVED** [review]

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 21 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: done
