### PR TITLE
Fix incorrect HTTP/2 method header decoding

### LINKED ISSUE #40301: [7.0 preview 1] HTTP DELETE sometimes treated as HTTP POST
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a bit of a weird one, and I'm not sure _exactly_ what's at fault, but code that works fine with ASP.NET Core 6 is not working _some of the time_ with ASP.NET Core 7 preview 1.

Testing a sample app of mine with preview 1 is getting test failures in UI tests that attempt to delete items from a Razor Pages UI using some Minimal API endpoints. The upgrade PR illustrating the issue is here: martincostello/dotnet-minimal-api-integration-testing#257.

Some UI tests fail in GitHub Actions on Linux and Windows, but none of the UI tests on macOS do.

Debugging this locally on my Windows 11 laptop, I've been able to fairly reliably repo the issue with Firefox but not with Chrome.

The behaviour is that attempting to delete a _second_ Todo item from the application via the UI fails with an HTTP 400 error, which appears to be coming from anti-forgery.

Turning up logging and looking at the Network tab in Firefox appears to show that the second HTTP DELETE request from the browser is being interpreted by the app as an HTTP POST, which then doesn't match the Minimal API delete endpoint, and then goes through into MVC, where it then hits anti-forgery because there's no request token.

MVC blocking the request due to the missing token makes sense, but the sample app shouldn't be getting that far, as it should be just going to the Minimal API's delete endpoint.

Specific lines from the application logs that are interesting are shown below, with the full logs at the bottom of this issue.

First working request for the HTTP DELETE:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 DELETE https://localhost:5001/api/items/dcd544d4-ff5a-4828-ad35-a6420acec150 - -
<snip>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 DELETE https://localhost:5001/api/items/dcd544d4-ff5a-4828-ad35-a6420acec150 - - - 204 - - 215.2596ms
```

Second failing request for the HTTP DELETE:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2 - -
trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
      All hosts are allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint '405 HTTP Method Not Supported'
<snip>
trce: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[2]
      Authorization Filter: Before executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "RequestVerificationToken" is not present.
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
trce: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Authorization Filter: After executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter.
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
<snip>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/api/items/45ef5916-2b04-4d2a-b060-58fc1105e0c2 - - - 400 0 - 46.7893ms
```

## Screenshot showing the two HTTP DELETE calls

image

## Application logs

[delete-fails-logs.txt](https://github.com/dotnet/aspnetcore/files/8097262/delete-fails-logs.txt)

### Expected Behavior

The HTTP DELETE succeeds.

### Steps To Reproduce

* Clone martincostello/dotnet-minimal-api-integration-testing@8e09b89d7d3699deeb21688adaec1f3ca85e1dfe
* [Configure GitHub auth secrets](https://github.com/martincostello/dotnet-minimal-api-integration-testing/tree/8e09b89d7d3699deeb21688adaec1f3ca85e1dfe#debugging)
* Run the application
* Navigate to `https://localhost:5001` in Firefox
* Create two new Todo items
* Delete the two Todo items - the second delete should fail

### Exceptions (if any)

_No response_

### .NET Version

7.0.100-preview.1.22110.4

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/40301

@adityamandaleeka It's my Saturday tomorrow so I just went ahead and created a PR. The only fix required was `_hpackDecoder.Decode` after the first stream.

With HPACK, the response headers from the first stream tell the decoder that the headers should be added to the dynamic table. They are now available for the second stream which sends back response headers that use dynamic table indexes. Example: https://datatracker.ietf.org/doc/html/rfc7541#appendix-C.5

If you've ever wondered why HPACK was replaced by QPACK in HTTP/3, it's because HTTP/2 guarantees the order of delivery. With HTTP/2 the server knows exactly what is the client's dynamic table based on what it has sent. That means it can safely send a header identified with a dynamic header index. HTTP/3 **doesn't** guarantee the order of delivery (e.g. stream 3 response headers are received before stream 1 response headers) so a new header compression spec is required.

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2HeadersEnumerator.cs [hunk 1]
```diff
@@ -90,11 +90,29 @@ public bool MoveNext()
...
             return _genericEnumerator!.MoveNext()
-                ? SetCurrent(_genericEnumerator.Current.Key, _genericEnumerator.Current.Value, default)
+                ? SetCurrent(_genericEnumerator.Current.Key, _genericEnumerator.Current.Value, GetKnownRequestHeaderType(_genericEnumerator.Current.Key))
                 : false;
         }
     }
 
+    private static KnownHeaderType GetKnownRequestHeaderType(string headerName)
+    {
+#if DEBUG
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2HeadersEnumerator.cs:100]: This is only for debugging, it doesn't affect the tests?

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2HeadersEnumerator.cs:100]: It does, but in a way that tests work with and without it.

How do we feel about having code in product that is only used by tests?

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs [hunk 2]
```diff
@@ -103,22 +103,41 @@ public async Task HEADERS_Received_KnownOrCustomMethods_Accepted(string method)
...
+        Assert.Equal("200", _decodedHeaders[HeaderNames.Status]);
+        Assert.Equal("0", _decodedHeaders[HeaderNames.ContentLength]);
+        Assert.Equal(method, _decodedHeaders["Method"]);
+        _decodedHeaders.Clear();
+
+        // Second request (will use dynamic table indexes)
+        await StartStreamAsync(3, headers, endStream: true);
+
+        var headersFrame2 = await ExpectAsync(Http2FrameType.HEADERS,
+            withLength: 7,
```
Comment (adityamandaleeka) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:127]: The test will fail when run in release now right?

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2HeadersEnumerator.cs (hunk 1 above)
Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2HeadersEnumerator.cs:100]: Can we just copy this version of `Http2HeadersEnumerator` (and probably `HPackHeaderWriter`) into the test project and use those from `Http2TestBase` instead of the real versions?

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs (hunk 2 above)
Comment (halter73) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:127]: I'm pretty sure our PR checks run in release, so apparently not. I guess the DEBUG-only changes aren't strictly necessary for the test to pass. Can you explain this a little more @JamesNK?

Comment (JamesNK) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:127]: Response headers are always encoded with static compression. The hack in this or is to get request headers - :method in this case - to use static compression

**Review by adityamandaleeka — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
😆
