### PR TITLE
Fix event during onafterrender

### LINKED ISSUE #30070: Exception thrown if FocusAsync() and @onfocusin are used in custom input element at the same time - blazor Wasm
#### In a Blazor WebAssembly project
Simultaneously setting of focus and using of the razor component event onfocusin throws an exception:

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Event 3 is already tracked
      Error: Event 3 is already tracked

I want to create an input element that is focused after the first render. At the same time, I want to do further work once the element receives focus (from the user or programmatically) using @onfocusin.

For these reasons, my input element now looks like this:

```
@inherits InputText

<input type="text"
       @bind-value="CurrentValue"
       @ref="_inputReference"
       @onfocusin="FocusInHandler" />

@code {
        private ElementReference _inputReference;

        protected async override Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await SetFocus();
            }

            await base.OnAfterRenderAsync(firstRender);
        }

        public async Task SetFocus()
        {
            await _inputReference.FocusAsync();
        }

        async Task FocusInHandler(FocusEventArgs e)
        {
            ...
        }
```

The exception is thrown as soon as the focus is set (for the demo project its when the page containing the input is loaded).

### To Reproduce

[Demo project](https://github.com/DCIW/BlazorFocusIssue)

### The Exception
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Event 3 is already tracked
      Error: Event 3 is already tracked
          at e.add (https://localhost:44390/_framework/blazor.webassembly.js:1:42456)
          at e.setListener (https://localhost:44390/_framework/blazor.webassembly.js:1:40690)
          at e.applyAttribute (https://localhost:44390/_framework/blazor.webassembly.js:1:36857)
          at e.insertElement (https://localhost:44390/_framework/blazor.webassembly.js:1:35691)
          at e.insertFrame (https://localhost:44390/_framework/blazor.webassembly.js:1:34562)
          at e.applyEdits (https://localhost:44390/_framework/blazor.webassembly.js:1:32948)
          at e.updateComponent (https://localhost:44390/_framework/blazor.webassembly.js:1:32264)
          at Object.t.renderBatch (https://localhost:44390/_framework/blazor.webassembly.js:1:12129)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44390/_framework/blazor.webassembly.js:1:61899)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44390/_framework/blazor.webassembly.js:1:64421)
Microsoft.JSInterop.JSException: Event 3 is already tracked
Error: Event 3 is already tracked
    at e.add (https://localhost:44390/_framework/blazor.webassembly.js:1:42456)
    at e.setListener (https://localhost:44390/_framework/blazor.webassembly.js:1:40690)
    at e.applyAttribute (https://localhost:44390/_framework/blazor.webassembly.js:1:36857)
    at e.insertElement (https://localhost:44390/_framework/blazor.webassembly.js:1:35691)
    at e.insertFrame (https://localhost:44390/_framework/blazor.webassembly.js:1:34562)
    at e.applyEdits (https://localhost:44390/_framework/blazor.webassembly.js:1:32948)
    at e.updateComponent (https://localhost:44390/_framework/blazor.webassembly.js:1:32264)
    at Object.t.renderBatch (https://localhost:44390/_framework/blazor.webassembly.js:1:12129)
    at Object.window.Blazor._internal.renderBatch (https://localhost:44390/_framework/blazor.webassembly.js:1:61899)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44390/_framework/blazor.webassembly.js:1:64421)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
### Further technical details
- version: .NET 5.0.3
- dotnet --info:
>  .NET SDK (gemäß "global.json"):
>  Version:   5.0.103
>  Commit:    72dec52dbd
> 
> Laufzeitumgebung:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.103\
> 
> Host (useful for support):
>   Version: 5.0.3
>   Commit:  c636bbdc8a
> 
> .NET SDKs installed:
>   3.1.406 [C:\Program Files\dotnet\sdk]
>   5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
>   5.0.103 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio Professional 2019 v. 16.8.5

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes #30070, which is another case of execution order inconsistency between Blazor Server and WebAssembly.

Rather than fixing it by putting in another special case, I again wanted to design this class of bug out of existence by bringing WebAssembly hosting more closely into alignment with Server hosting. I say "again" because that was also the approach in #31612, but evidently there are still cases where I didn't go far enough. So now in this PR I'm going significantly further still by taking this out of the renderer and making a general-purpose work queue for all JS-to-.NET calls.

The solution here now simultaneously solves all three of the WebAssembly-specific event ordering problems we've had, and makes it possible to remove a lot of tricky special-case stuff we were using before. Hopefully it also has no perf or compat drawbacks for developers. It looks like not much code but it took a lot of thinking to reduce it to this, especially around things like exception handling. It's still not easy to reason about so please do say so if you have any concerns about whether it's really correct.

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs [hunk 1]
```diff
@@ -138,90 +160,6 @@ protected override void HandleException(Exception exception)
             }
         }
 
-        /// <inheritdoc />
-        public override Task DispatchEventAsync(ulong eventHandlerId, EventFieldInfo? eventFieldInfo, EventArgs eventArgs)
```
Comment (captainsafia) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:142]: Can you help me understand what the consequences of removing this API are?

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:142]: The API remains, it's just this override that is no longer needed, since the base class implementation is now sufficient.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        ///     further items (just like unhandled hub exceptions in Blazor Server)
+        /// [2] The exception will be thrown at the point of the top-level caller, which is not necessarily the
+        ///     code that scheduled the callback, so you may not be able to observe it.
+        ///
+        /// We could change this to return a Task and do the necessary try/catch things to direct exceptions back
+        /// to the code that scheduled the callback, but it's not required for current use cases and would require
+        /// at least an extra allocation and layer of try/catch per call, plus more work to schedule continuations
+        /// at the call site.
+        /// </remarks>
+        public static void Schedule<T>(T state, Action<T> callback)
```
Comment (HaoK) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:49]: nit: should the method be aligned with the class?  WebAssemblyCallScheduler / Schedule, or WebAssemblyCallQueue.Enqueue ?

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+    // Adding such a rule now would be too breaking, given how component libraries may be reliant
+    // on being able to render at any time without InvokeAsync. If we add true multithreading in the
+    // future, we should start enforcing dispatch if (and only if) multithreading is enabled.
+    // For now, this minimal work queue is an internal detail of how the framework dispatches
+    // incoming JS->.NET calls and makes sure they get deferred if a renderbatch is in process.
+
+    internal static class WebAssemblyCallQueue
+    {
+        private static bool _isCallInProgress;
+        private static Queue<Action> _pendingWork = new();
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:24]:
```suggestion
        private static readonly Queue<Action> _pendingWork = new();
```

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+    //
+    // The reason for not using an actual SynchronizationContext for this is that, historically,
+    // Blazor WebAssembly has not enforced any rule around having to dispatch to a sync context.
+    // Adding such a rule now would be too breaking, given how component libraries may be reliant
+    // on being able to render at any time without InvokeAsync. If we add true multithreading in the
+    // future, we should start enforcing dispatch if (and only if) multithreading is enabled.
+    // For now, this minimal work queue is an internal detail of how the framework dispatches
+    // incoming JS->.NET calls and makes sure they get deferred if a renderbatch is in process.
+
+    internal static class WebAssemblyCallQueue
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:21]: Super nit suggestion: You could consider making this a singleton to make unit testing this type easier.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs [hunk 5]
```diff
@@ -95,6 +92,32 @@ protected override void Dispose(bool disposing)
...
+            {
+                base.ProcessPendingRender();
+            }
+            else
+            {
+                WebAssemblyCallQueue.Schedule(this, static @this => @this.CallBaseProcessPendingRender());
+            }
+        }
+
+        void CallBaseProcessPendingRender() => base.ProcessPendingRender();
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:119]:
```suggestion
        private void CallBaseProcessPendingRender() => base.ProcessPendingRender();
```

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs [hunk 6]
```diff
@@ -103,22 +126,21 @@ protected override Task UpdateDisplayAsync(in RenderBatch batch)
...
+            if (WebAssemblyCallQueue.HasUnstartedWork)
             {
-                // In the vast majority of cases, since the call to update the UI is synchronous,
-                // we just return a pre-completed task from here.
-                return Task.CompletedTask;
+                // Because further incoming calls from JS to .NET are already queued (e.g., event notifications),
+                // we have to delay the renderbatch acknowledgement until it gets to the front of that queue.
+                // This is for consistency with Blazor Server which queues all JS-to-.NET calls relative to each
+                // other, and because various bits of cleanup logic rely on this ordering.
+                var tcs = new TaskCompletionSource();
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:135]: Should this specify RunContinuationsAsynchronously?

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+        /// We could change this to return a Task and do the necessary try/catch things to direct exceptions back
+        /// to the code that scheduled the callback, but it's not required for current use cases and would require
+        /// at least an extra allocation and layer of try/catch per call, plus more work to schedule continuations
+        /// at the call site.
+        /// </remarks>
+        public static void Schedule<T>(T state, Action<T> callback)
+        {
+            if (_isCallInProgress)
+            {
+                _pendingWork.Enqueue(() => callback(state));
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:53]: If you wanted to avoid the allocation, you could make this an `Action<object>`. This way the caller can be aware of any allocations incurred due to boxing.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs (hunk 6 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:135]: I'm not aware of any need for that here.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 7 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:53]: I didn't spot a good way to do that without forcing an extra allocation if `T` would otherwise be a value type. I guess technically there could be two overloads of this method, one if `T:class` and one for `T:struct`.

However since 99% of the time the call will be executed synchronously, I didn't think it worth making the code that much more to maintain and risk future inconsistencies.

Please let me know if you disagree or have ideas for how to avoid that drawback.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:49]: TBH with this being internal I'd be inclined to leave it. Trying to communicate something like "run it maybe right away or maybe later" is hard to put into a single word. We already use the term "dispatcher" for something different so I was going for "call queue" as the most literal statement of what it is.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 7 above)
Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:53]: None in particular. I guess if we profile this and see additional allocations, we could devise something interesting.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+using System.Collections.Generic;
+
+namespace Microsoft.AspNetCore.Components.WebAssembly.Hosting
+{
+    // A mechanism for queuing JS-to-.NET calls so they aren't nested on the call stack and hence
+    // have the same ordering behaviors as in Blazor Server. This eliminates serveral inconsistency
+    // problems and bugs that otherwise require special-case solutions in other parts of the code.
+    //
+    // The reason for not using an actual SynchronizationContext for this is that, historically,
+    // Blazor WebAssembly has not enforced any rule around having to dispatch to a sync context.
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:14]: While this is factually true (as in it will not break in webassembly) this has not been the guidance that we've been giving customers (we always told them to use use `InvokeAsync` when "dispatching" to Blazor) and we shouldn't think of this as a scenario with any level of support "It's a bug" that we didn't catch. 

We don't want to encourage this practice since it breaks "universal" libraries and is not a guarantee that we can make in the future if we introduce multithreading when available. If a library chose to avoid the guidance despite our efforts I don't think we should be jumping hoops to avoid breaking them.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs [hunk 9]
```diff
@@ -158,12 +158,19 @@ internal async Task RunAsyncCore(CancellationToken cancellationToken, WebAssembl
...
-                }
+                    var (rootComponents, renderer) = state;
+                    for (var i = 0; i < rootComponents.Length; i++)
+                    {
+                        var rootComponent = rootComponents[i];
+
+                        // No need to await because we want the root components to be added in parallel (e.g.,
+                        // not waiting for each other's OnInitializedAsync tasks), and any async exceptions will
+                        // be handled by normal component lifecycle mechanisms.
+                        _ = renderer.AddComponentAsync(rootComponent.ComponentType, rootComponent.Selector, rootComponent.Parameters);
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:171]: This changes the semantics for line 175 below. 

We should also look at what we do on Blazor server and Desktop and see if we do it in sequence or in parallel. I think we should be consistent across platforms

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 8 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:14]: This would be a really serious breaking change that we should only contemplate if there was no alternative, and after making some effort to quantify exactly how many apps would get hurt. Fortunately we have a straightforward way of not needing such a breaking change.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 4 above)
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:21]: This looks very similar to the RendererSynchronizationContext is there a way we could "reuse" that here instead of having a separate work queue?

These things are tricky to test implement and can lead to subtle bugs that are hard to track down

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:14]: > This would be a really serious breaking change that we should only contemplate if there was no alternative

This is detrimental for the Blazor ecosystem as a whole since it creates libraries that only work on Webassembly. It just "happens to work" on WASM because its currently single threaded, however we've made no guarantee that this would work. It's like relying on undefined behavior in a C compiler, the guidance is clear and if you choose not to follow it, your app might break when you update.

I think its best to address this sooner rather than later, the more we wait the bigger a problem this is going to be for people in the future. I don't think waiting until we are forced to do it is the right call here, since it will create a potentially much bigger problem in the future. And not just for Blazor users, but for the Blazor component ecosystem as a whole since the list of incompatible component libraries is likely to grow.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 4 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:21]: The main issue with using a sync context is the back-compat about enforcement of being "on" the sync context (discussed above), but even besides that, the existence of synchronous interop makes WebAssembly a different kind of runtime environment for which we can't assume that `RendererSynchronizationContext` has the right behaviors. For example, incoming calls may already be on the sync context but we still need to defer their work. It's not the right fit for this runtime.

I know your concern is more future-thinking and looks towards a scenario where we have real multithreading. My expectation is that when/if we get to that, we'll be in a position to recreate the same threading semantics as Server pretty much exactly (assuming we want to), but that's not the case today and shouldn't be considered in scope for fixing this bug. My goal in this PR is to wipe out the largest class of possible inconsistency issues I can while not regressing compat or perf.

**Review by javiercn — APPROVED** [review]
Looks great!

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs (hunk 8 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCallQueue.cs:14]: For anyone else reading and future clarity, we discussed this and came to the conclusion that, until WebAssembly has true multithreading, it's not really meaningful to talk about enforcement of a sync context, since nested synchronous calls would already be on it anyway (and nested calls are precisely the thing we need to defer to fix the bugs this addresses).
