### PR TITLE
Write readers for reading WebEventData JSON payloads

### LINKED ISSUE #33967: [WASM] SoD Changes
When we went from 6.0.100-preview.6.21318.1 -> 6.0.100-preview.6.21318.5 we saw the below regressions and improvements. 

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a02b668214e9711cb3d5f426f085601698a24b92](https://github.com/dotnet/runtime/commit/a02b668214e9711cb3d5f426f085601698a24b92)
Compare | [ca3c11d64516217134430d04354ac770b07c91ef](https://github.com/dotnet/runtime/commit/ca3c11d64516217134430d04354ac770b07c91ef)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a02b668214e9711cb3d5f426f085601698a24b92...ca3c11d64516217134430d04354ac770b07c91ef)

### Improvemnts in SOD - New Blazor Template - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 16.89 KB | 6.31 KB | 0.37 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .svg](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 54.04 KB | 31.32 KB | 0.58 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 13.34 KB | 7.51 KB | 0.56 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.wasm](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 2.11 MB | 2.04 MB | 0.97 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css.map.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 58.30 KB | 6.53 KB | 0.11 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.eot.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.77 KB | 7.90 KB | 0.53 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 2.55 MB | 2.45 MB | 0.96 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 152.11 KB | 47.45 KB | 0.31 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 3.26 MB | 3.11 MB | 0.96 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .ttf](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 27.37 KB | 15.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.otf.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 12.52 KB | 7.91 KB | 0.63 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .otf](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 20.50 KB | 12.01 KB | 0.59 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.71 KB | 7.90 KB | 0.54 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .eot](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 27.54 KB | 15.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .wasm](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 2.11 MB | 2.04 MB | 0.97 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .js](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 288.88 KB | 272.53 KB | 0.94 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.wasm.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 756.30 KB | 734.47 KB | 0.97 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.otf](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 20.50 KB | 12.01 KB | 0.59 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.VERSION.js.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 49.00 KB | 44.98 KB | 0.92 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.wasm.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 923.81 KB | 896.87 KB | 0.97 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.svg.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 13.14 KB | 7.83 KB | 0.60 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .woff](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.63 KB | 8.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 27.37 KB | 15.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.eot](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 27.54 KB | 15.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.woff.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.56 KB | 7.95 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.VERSION.js](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 236.66 KB | 220.04 KB | 0.93 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.eot.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 13.38 KB | 7.51 KB | 0.56 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.woff.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.61 KB | 8.01 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css.map.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 99.68 KB | 7.78 KB | 0.08 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 15.21 MB | 14.22 MB | 0.94 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 22.70 KB | 7.83 KB | 0.34 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.woff](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 14.63 KB | 8.03 KB | 0.55 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.timezones.blat.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 72.68 KB | 71.50 KB | 0.98 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/bootstrap/bootstrap.min.css.map](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 611.28 KB | 34.05 KB | 0.06 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.svg.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 10.65 KB | 6.44 KB | 0.60 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/dotnet.VERSION.js.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 56.51 KB | 51.81 KB | 0.92 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .css](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 166.59 KB | 61.94 KB | 0.37 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .map](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 611.28 KB | 34.05 KB | 0.06 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.svg](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 54.04 KB | 31.32 KB | 0.58 | 0.00 | | |
[SOD - New Blazor Template - Publish - SOD - New Blazor Template - Publish](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 15.21 MB | 14.22 MB | 0.94 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/css/open-iconic/font/fonts/open-iconic.otf.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 11.17 KB | 6.95 KB | 0.62 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.WebAssembly.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 44.00 KB | 96.50 KB | 2.19 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub - Count](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 166.00 count | 169.00 count | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 247.00 KB | 255.50 KB | 1.03 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.JSInterop.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 13.87 KB | 14.09 KB | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 7.36 KB | 8.64 KB | 1.17 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.JSInterop.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 30.50 KB | 31.00 KB | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.WebAssembly.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 19.96 KB | 35.57 KB | 1.78 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .gz - Count](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 55.00 count | 56.00 count | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 5.81 KB | 7.04 KB | 1.21 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 6.98 KB | 7.07 KB | 1.01 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .br - Count](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 55.00 count | 56.00 count | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.Web.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 18.00 KB | 20.50 KB | 1.14 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 81.97 KB | 84.31 KB | 1.03 | 0.00 | | |
[SOD - New Blazor Template - Publish - SOD - New Blazor Template - Publish - Count](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 166.00 count | 169.00 count | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.AspNetCore.Components.WebAssembly.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 17.62 KB | 28.29 KB | 1.61 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 95.87 KB | 98.57 KB | 1.03 | 0.00 | | |
[SOD - New Blazor Template - Publish - Aggregate - .dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 1.85 MB | 1.91 MB | 1.03 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/Microsoft.Extensions.Logging.Abstractions.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 8.39 KB | 8.56 KB | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/emptyblazorwasmtemplate.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 6.24 KB | 6.34 KB | 1.02 | 0.00 | | |

graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_19_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - New Blazor Template - Publish*'
```
<details>

### Payloads

[Baseline](<https://helixri8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-489d21790be3424586/SOD%20-%20New%20Blazor%20Template%20-%20Publish/Publish-emptyblazorwasmtemplate.zip?sv=2019-07-07&se=2021-09-15T02%3A16%3A07Z&sr=c&sp=rl&sig=IzEtxYwSADk4jUHgsA8R2mxB5kYcgNAii7StoM1jOKE%3D>)
[Compare](<https://helixri8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ed36d2de41b640b7b4/SOD%20-%20New%20Blazor%20Template%20-%20Publish/Publish-emptyblazorwasmtemplate.zip?sv=2019-07-07&se=2021-09-17T04%3A37%3A39Z&sr=c&sp=rl&sig=MH5OrPLrA%2FvgFrmNGrrMpU3VAzZt9GVZFv4r0N5%2BSTg%3D>)

#### SOD - New Blazor Template - Publish

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by pranavkm**
* Adding source generators without doing all of the work results in a size increase. We can avoid issues with reflection
and the additional size hit by writing bespoke readers.
* An additional optimziation this PR includes is to avoid a unicode string -> utf8 byte conversion along with the associated
string allocation by using JsonElement as the contract for deserializing JSON payload. At least in the Blazor Server scenario,
we could further consider pooling the byte array used for receiving and deserializing the JSON payload making parsing browser events largely allocation free.

Fixes https://github.com/dotnet/aspnetcore/issues/33967

### CODE REVIEW

File: src/Components/Server/src/ComponentHub.cs [hunk 1]
```diff
@@ -240,7 +241,7 @@ public async ValueTask<bool> ReceiveJSDataChunk(long streamId, long chunkId, byt
             return await circuitHost.ReceiveJSDataChunk(streamId, chunkId, chunk, error);
         }
 
-        public async ValueTask DispatchBrowserEvent(string eventDescriptor, string eventArgs)
+        public async ValueTask DispatchBrowserEvent(JsonElement eventDescriptor, JsonElement eventArgs)
```
Comment (BrennanConroy) [inline src/Components/Server/src/ComponentHub.cs:244]: Careful with changing public hub methods. Old clients will still pass strings which would break. Maybe old clients aren't a concern for blazor apps though 🤷‍♀️

**Review by captainsafia — APPROVED** [review]

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs [hunk 2]
```diff
@@ -19,11 +22,9 @@ namespace Microsoft.AspNetCore.Components.WebAssembly.Infrastructure
     [EditorBrowsable(EditorBrowsableState.Never)]
     public static class JSInteropMethods
     {
-        private static WebEventJsonContext? _jsonContext;
-
         /// <summary>
         /// For framework use only.
-        /// </summary>
+        /// </summary>z
```
Comment (campersau) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:27]:
```suggestion
        /// </summary>
```

File: src/Components/Shared/src/WebEventData/DragEventArgsReader.cs [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    internal static class DragEventArgsReader
+    {
+        private static readonly JsonEncodedText DataTransfer = JsonEncodedText.Encode("dataTransfer");
+        private static readonly JsonEncodedText DropEffect = JsonEncodedText.Encode("dropEffect");
+        private static readonly JsonEncodedText EffectAllowed = JsonEncodedText.Encode("effectAllowed");
+        private static readonly JsonEncodedText Files = JsonEncodedText.Encode("files");
+        private static readonly JsonEncodedText Items = JsonEncodedText.Encode("items");
+        private static readonly JsonEncodedText Types = JsonEncodedText.Encode("types");
+        private static readonly JsonEncodedText Kind = JsonEncodedText.Encode("kind");
+        private static readonly JsonEncodedText Type = JsonEncodedText.Encode("type");
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/WebEventData/DragEventArgsReader.cs:20]: Do you happen to know whether the static constructor runs (for all the types) during app startup, or is it deferred until the first time we see an event of the corresponding type?

If it's the latter that's great. If it all happens on startup, do you think in the wasm case all the string encoding would have any perceptible effect on startup time?

Comment (javiercn) [reply src/Components/Shared/src/WebEventData/DragEventArgsReader.cs:20]: The type constructor will run the first time the type is needed/used. It might be in startup if for some reason this gets referenced from the startup code path, otherwise, likely the first time we receive an event via JS interop, since likely mono will trigger the class load.

File: src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+                }
+                else if (property.NameEquals(MetaKey.EncodedUtf8Bytes))
+                {
+                    eventArgs.MetaKey = property.Value.GetBoolean();
+                }
+                else if (property.NameEquals(Type.EncodedUtf8Bytes))
+                {
+                    eventArgs.Type = property.Value.GetString()!;
+                }
+            }
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:94]: This pattern is `O(NM)` with the number of properties on the eventargs type * number of incoming values. I know that it's fixed and end users can't influence that, but this is still a lot of `NameEquals` calls with `N=M=14` here. At what point do you think it would be worth amortizing that by creating a `SortedDictionary<JsonEncodedText, Action<MouseEventArgs, JsonValue>>` or similar up front?

Separately, a hostile user could send an event payload like `{"a":0,"b":0,"c":0,..."zzz":0}` and force a lot of string comparisons per event. I estimate about 57,000 string comparisons per event based on 14 tests per inbound property, and and two-char property name combinations using chars in `a-zA-Z0-9`. Is it worth counting the number of properties we've considered, and throwing if it gets above (say) 50? That wouldn't make the code much more complex.

Comment (SteveSandersonMS) [reply src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:94]: In fact, would it be valid to throw if we see *any* property name that we didn't expect? Our JS client sends a known set, doesn't it (it doesn't just serialize raw JS `Event` objects, does it)?

File: src/Components/Shared/src/WebEventData/DragEventArgsReader.cs (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Shared/src/WebEventData/DragEventArgsReader.cs:20]: There’s one big event-handling method that references all of these types in different branches. I’m unsure whether that’s enough to trigger all their static constructors at once, or if it’s only when we enter the branches that reference each one.

Comment (SteveSandersonMS) [reply src/Components/Shared/src/WebEventData/DragEventArgsReader.cs:20]: TBH since it’s really on the first event, not during actual app startup before first UI render, I’m sure it will be fine to initialise them all then anyway.

Marking this as resolved.

File: src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs (hunk 4 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:94]: > In fact, would it be valid to throw if we see any property name that we didn't expect?

We could. It'd be different to the current behavior (values without corresponding C# properties get ignored by the serializer) but that might be fine since it would indicate a bug or suggest that we could be sending less data from JS if we genuinely don't need it.

Comment (pranavkm) [reply src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:98]: Adding a throw for unknown properties to all of the readers doesn't cause any of our tests to fail, so perhaps that's a sufficient solution to limit this sort of attack vector.

File: src/Components/Web.JS/src/Boot.Server.ts [hunk 5]
```diff
@@ -95,7 +95,9 @@ async function initializeConnection(options: CircuitStartOptions, logger: Logger
   const connection = connectionBuilder.build();
 
   setEventDispatcher((descriptor, args) => {
-    connection.send('DispatchBrowserEvent', JSON.stringify(descriptor), JSON.stringify(args));
+    const getJsonBytes = (value) => new TextEncoder().encode(JSON.stringify(value));
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Boot.Server.ts:98]: A long time ago [we added a polyfill for `TextEncoder` (the decoding part)](https://github.com/dotnet/blazor/pull/1168), which is still there now. At the time this was to help with legacy Edge support. Using `TextEncoder` directly here means taking an opinion that we don't need this any more.

### Suggestion

Either:

 * We should remove our `TextEncoder` polyfill (`Utf8Decoder.ts`) - my preferred options
 * Or, we should also polyfill the encoder here.

No problem if we address this in a follow-up PR as there's nothing urgent about it and no reason why @pranavkm should be responsible for it more than anyone else.

### Side-question

In 5.0 [we announced that Blazor Server and WebAssembly would no longer be *fully functional* in Legacy Edge](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/blazor-browser-support-updated#reason-for-change), but I don't see any clear statement about what *fully functional* means. Does it mean it works with polyfills? Or that it doesn't work at all under any circumstances? I don't know. @danroth27 Do you know what expectations we've been setting more recently with customers? Is there any reason to believe any customers are still reliant on polyfilling Legacy Edge support and are we saying anything about that in 6.0?

**Review by SteveSandersonMS — APPROVED** [review]
This is great. Thanks for taking the initiative on this, @pranavkm!

Approving, but before merging, could you please also consider including the suggestions from https://github.com/dotnet/aspnetcore/pull/34093? If you don't want to, I'm OK with turning that into a separate follow-up PR, but it would be cleaner if the two were merged as a single unit if you agree with those changes.

File: src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs [hunk 6]
```diff
@@ -49,6 +50,17 @@ protected override object DeserializeObject(ref MessagePackReader reader, Type t
...
+                {
+                    var bytes = reader.ReadBytes();
+                    if (bytes is null)
+                    {
+                        return default;
+                    }
+
+                    var jsonReader = new Utf8JsonReader(bytes.Value);
+                    return JsonElement.ParseValue(ref jsonReader);
+                }
```
Comment (javiercn) [inline src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: Does reader.ReadBytes() allocate a new array? Is there a way we could avoid the byte array allocation all together there?

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 7]
```diff
@@ -456,12 +455,7 @@ public async Task DispatchEvent(string eventDescriptorJson, string eventArgsJson
             {
                 // JsonSerializerOptions are tightly bound to the JsonContext. Cache it on first use using a copy
                 // of the serializer settings.
-                if (_jsonContext is null)
-                {
-                    _jsonContext = new(new JsonSerializerOptions(JSRuntime.ReadJsonSerializerOptions()));
-                }
-
-                webEventData = WebEventData.Parse(Renderer, _jsonContext, eventDescriptorJson, eventArgsJson);
+                webEventData = WebEventData.Parse(Renderer, JSRuntime.ReadJsonSerializerOptions(), eventDescriptorJson, eventArgsJson);
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitHost.cs:458]: Is there a way we could push this logic all the way down to the serializer level? (Keep the logic within WebEventData and avoid the intermediate JsonElement deserialization)

Or alternatively, defer any deserialization until we are out of the serializer.

File: src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:98]: I'm not sure there's a security concern here, there's a limit to the number of operations you can force and its not controlled by the end user. If we want to make the implementation more "scalable" that's fine, but I don't think we should do anything in the name of security.

There's only an issue when you can cause the work performed by the server to grow without growing your own work. (For example, if you have an input where you enter a number and the server calculates the factorial or fibonacci of that number as an example), but in general it's ok if you have to do more work to cause the server to do more work, even if the scale is different. At that point, its up to the server to establish the appropriate limits of what it considers acceptable.

In this case, even if this can be 57K string comparisons in the worst case, I think it'll be fast enough that it won't matter. It might even be the case, that this way is even faster than doing a hash and a lookup on a Dictionary.

Comment (SteveSandersonMS) [reply src/Components/Shared/src/WebEventData/MouseEventArgsReader.cs:98]: I was suggesting a structure that would seek via a series of comparisons, not a hash, but in any case it sounds like we’re all settled on the pattern here with the sequence of Equals checks.

File: src/Components/Web.JS/src/Boot.Server.ts (hunk 5 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.ts:98]: > * We should remove our `TextEncoder` polyfill (`Utf8Decoder.ts`) - my preferred option

I agree with you, we should just remove this.

WRT to 5.0 our statement has never been clear, but I think it's fair to summarize it as "your mileage will vary" as in we think it would work but we don't guarantee/test that it does.

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs [hunk 8]
```diff
@@ -34,23 +35,38 @@ public static void NotifyLocationChanged(string uri, bool isInterceptedLink)
         /// For framework use only.
         /// </summary>
         [JSInvokable(nameof(DispatchEvent))]
-        public static Task DispatchEvent(WebEventDescriptor eventDescriptor, string eventArgsJson)
+        public static async Task DispatchEvent(string eventDescriptorJson, string eventArgsJson)
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:38]: I think @SteveSandersonMS did this, but with Tanay's work, this can be a `byte []`

**Review by javiercn — APPROVED** [review]
Looks great!

Just a couple of small comments/suggestions on further optimizations.

File: src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs (hunk 6 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: Looks like `ReadBytes` returns `ReadOnlySequence<byte>` (https://github.com/neuecc/MessagePack-CSharp/blob/master/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackReader.cs#L669), so should not allocate.

Comment (javiercn) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: It would be nice if we could find a way to elide the allocation until we can parse the final event data (at which point we can't elide it).

Comment (SteveSandersonMS) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: What is allocating here?

Comment (javiercn) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: Isn't the `JsonElement.Parse` allocating? (I might be wrong)

Comment (SteveSandersonMS) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: I don't know for sure, wondered if you did. `JsonElement` is a `struct` and I would have thought, theoretically at least, it could just be a way of walking through the JSON-formatted information in a `ReadOnlySequence<byte>` without having to allocate anything.

Comment (javiercn) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: @SteveSandersonMS doesn't it have to at least capture the memory before returning? Otherwise wouldn't we be in a `use after free` kind of situation? (We might already be, since we don't know what happens with the memory of the `ReadOnlySequence` after we've exited this method).

(I believe Tanay was running into issues while he was trying to avoid the allocation on byte array interop, so this might present a similar issue)

Comment (javiercn) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: I've looked a bit, and I think it only parses the data without allocating (not 100% confirmed, just skimmed through the implementation).

However, it might still be worth to avoid deserializing the JSON payload at this level and wait until we are inside the hub (by receiving a byte [] or similar on the signature instead) for two reasons:
* What happens when we receive invalid JSON in this case (the error experience changes and we need to make sure we are ok with it, since we don't have a way here to know what circuit is crashing or potentially do appropriate cleanup/logging)
* We can avoid the JsonElement step all together, start parsing the data with the reader APIs (equivalent as if we were writing a JsonConverter) and use higher level APIs when we know what event type we are parsing (if possible)). At that point, the error experience would be the same and we would make sure we aren't doing any unnecessary work.

Am I missing something?

Comment (SteveSandersonMS) [reply src/Components/Server/src/BlazorPack/BlazorPackHubProtocolWorker.cs:63]: I basically agree. Earlier today I wrote a comment here saying (approximately) "`JsonElement` is an unusually high-level thing to handle at the protocol level - should we just return byte data here and deserialize into `JsonElement` later in the process?" but then decided it wasn't important enough to bother - it's all internal so we can change it any time if we want.

I understand Pranav wanted to use `JsonElement` rather than pure `Utf8JsonReader` because it significantly simplifies the parsing process. For example, you can directly find out the size of arrays up front rather than having to do things like capture into `List<T>` then do `.ToArray()` on them. I don't have much of a reason to regard that as problematic but am confident we could change it later if we wanted.

Maybe your point about the error experience would lead us to a different outcome - I'm not sure. But anyway this isn't something I feel strongly about because I think the perf characteristics would be overall the same and with it being internal it could be changed any time later.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 7 above)
Comment (pranavkm) [reply src/Components/Server/src/Circuits/CircuitHost.cs:458]: Let's do this in a follow up. I want to unblock the size increase issues for WASM for preview7

File: src/Components/Shared/src/WebEventData/WebEventData.cs [hunk 9]
```diff
@@ -0,0 +1,203 @@
...
+namespace Microsoft.AspNetCore.Components.Web
+{
+    internal class WebEventData
+    {
+        // This class represents the second half of parsing incoming event data,
+        // once the event ID (and possibly the type of the eventArgs) becomes known.
+        public static WebEventData Parse(
+            Renderer renderer,
+            JsonSerializerOptions jsonSerializerOptions,
+            JsonElement eventDescriptorJson,
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventData/WebEventData.cs:20]: Silly question - but why not base these on JsonReader instead of JsonElement?

Comment (pranavkm) [reply src/Components/Shared/src/WebEventData/WebEventData.cs:20]: There was one code path (among 3 that use this) that already constructed a `JsonElement`, so it was easier to use this than to do a bigger refactoring. there.

Comment (eerhardt) [reply src/Components/Shared/src/WebEventData/WebEventData.cs:20]: Got it. Thanks for the answer.

If we were really looking to squeeze out the perf, I wonder how much more could be gained to refactor it to straight `Utf8JsonReader`. But if we already have acceptable perf, it is probably not worth it.
