### PR TITLE
Fix form actions for apps deployed behind reverse proxy

### LINKED ISSUE #51380: Blazor forms should render target URL in action attribute as root-relative (absolute path), not fully qualified
The change recently made to always render the current fully qualified request URL as the value for any `form` element rendered in a Razor component, causes issues when the app is deployed behind any kind of reverse proxy/ingress controller, which is extremely common for any hosting PaaS, including Azure App Service for Linux/Containers, and Azure Container Apps.

In these environments, the value of `HttpRequest.Scheme`, `HttpRequest.Host`, etc. will not reflect the values the browser client sees unless the [forwarded headers middleware is added and properly configured](https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#http-headers). Doing so is a fairly complex task and tied strongly to the specific destination the app is deployed to.

Instead of using the fully qualified URL, MVC and Razor Pages renders the `action` attribute with just the root-relative (absolute) path, i.e. */shopping/cart* instead of *http://contoso.com/shopping/cart*, so that the scheme and host from the client's point of view, do not need to be known (it does this using `IUrlHelper`). Note that this must still take into consideration the current value of `HttpRequest.PathBase` if set. This makes it far simpler to have the application work correctly without need to configured forwarded headers.

We should update Blazor's form rendering logic to match what MVC and Razor Pages does, except that Blazor should always render a value (MVC skips it if it's for the current controller/action/page).

@javiercn @SteveSandersonMS

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Fix form actions for apps deployed behind reverse proxy

Makes forms work for apps deployed behind a reverse proxy.

## Description

Apps deployed behind a reverse proxy (e.g., container apps) should not try to emit absolute URLs by default because the scheme/hostname/port may differ from what is reachable from the outside world. The fix is to emit root-relative URLs.

Fixes #51380

## Customer Impact

Without this fix, apps deployed behind a reverse proxy (e.g., in ACA) would not support form posts.

## Regression?

- [ ] Yes
- [x] No

No because this only affects SSR forms, which is a new feature in .NET 8.

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Low because this is only a change to how we generate the URL for a form's `action` attribute. Previously we used an absolute URL, but now we use a root-relative one. There is no other runtime change. Everything else in this PR is extra tests and updating existing tests.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs [hunk 1]
```diff
@@ -351,12 +351,29 @@ void EmitFormActionIfNotExplicit(TextWriter output, bool isForm, bool hasExplici
...
+        //   to the current URL, but that would be wrong if there's an uncommitted navigation in
+        //   flight, e.g., after the user clicking 'back' - it would go to whatever's now in the
+        //   address bar, ignoring where the form was rendered)
+        // - if we used an absolute URL, then it creates a significant extra pit of failure for
+        //   apps hosted behind a reverse proxy (e.g., container apps), because the server's view
+        //   of the absolute URL isn't usable outside the container
+        //   - of course, sites hosted behind URL rewriting that modifies the path will still be
+        //     wrong, but developers won't do that often as it makes things like <a href> really
+        //     difficult to get right. In that case, developers must emit an action attribute manually.
+        return new Uri(navigationManager.Uri, UriKind.Absolute).PathAndQuery;
```
Comment (DamianEdwards) [inline src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:374]: Curious why you can't use the existing `Uri` instance in the private field on `NavigationManager` instead of allocating a new one?

**Review by mkArtakMSFT — APPROVED** [review]
Thank you, @SteveSandersonMS !

File: src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/HtmlRendering/StaticHtmlRenderer.HtmlWriting.cs:374]: The `_uri` on NavigationManager is a `string` so we wouldn't gain anything. Even if it was a `System.Uri`, it's in a different assembly and we don't have IVT to it. We would have to add IVT or a new public API.

Having one extra allocation per actionless-form is not likely to be problematic, and especially at this stage in the release we need to minimize code changes. We can optimize this more in the future if needed.

**Review by halter73 — APPROVED** [review]
