### PR TITLE
Set default JSON type resolver if not set

### LINKED ISSUE #49360: MVC apps no longer work with PublishTrimmed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using an MVC app with PublishTrimmed no longer works. The same app worked in .NET 7.

This appears to be caused by the JsonSerializerIsReflectionEnabledByDefault changes. See https://github.com/dotnet/runtime/issues/84378.

FYI @eiriktsarpalis 

### Expected Behavior

The app should work.

### Steps To Reproduce

1. `dotnet new mvc`
2. Add `<PublishTrimmed>true</PublishTrimmed>` to the csproj
3. `dotnet run`

### Exceptions (if any)

```
Unhandled exception. System.InvalidOperationException: JsonSerializerOptions instance must specify a TypeInfoResolver setting before being marked as read-only.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerOptionsNoTypeInfoResolverSpecified()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly()
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter..ctor(JsonSerializerOptions jsonSerializerOptions)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.CreateFormatter(JsonOptions jsonOptions)
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
```

### .NET Version

8.0.100-preview.7.23360.2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/49360

### CODE REVIEW

**Comment by eerhardt** [comment]
FYI - If you wanted to write some tests for this, you could do them like this:

https://github.com/dotnet/aspnetcore/blob/238dabc8bf7a6d9485d420db01d7942044b218ee/src/Mvc/Mvc.Core/test/JsonOptionsTest.cs#L29-L44

File: src/Shared/Json/JsonSerializerExtensions.cs [hunk 1]
```diff
@@ -18,6 +18,7 @@ public static bool ShouldUseWith(this JsonTypeInfo jsonTypeInfo, [NotNullWhen(fa
 
     public static JsonTypeInfo GetReadOnlyTypeInfo(this JsonSerializerOptions options, Type type)
     {
+        options.TypeInfoResolver ??= new EmptyJsonTypeInfoResolver();
```
Comment (eiriktsarpalis) [inline src/Shared/Json/JsonSerializerExtensions.cs:21]: Looks good. You can avoid creating a custom resolver if you just use `JsonTypeInfoResolver.Combine()` with no arguments.

File: src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs [hunk 2]
```diff
@@ -23,6 +23,7 @@ public SystemTextJsonOutputFormatter(JsonSerializerOptions jsonSerializerOptions
     {
         SerializerOptions = jsonSerializerOptions;
 
+        jsonSerializerOptions.TypeInfoResolver ??= JsonTypeInfoResolver.Combine();
```
Comment (eerhardt) [inline src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs:26]:
```suggestion
        // JsonTypeInfoResolver.Combine() produces an "empty" resolver
        jsonSerializerOptions.TypeInfoResolver ??= JsonTypeInfoResolver.Combine();
```

Could use a comment

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 3]
```diff
@@ -2903,6 +2904,45 @@ public async Task RequestDelegateFactory_AsParameters_SupportsRequiredMember_Nul
...
+        using var remoteHandle = RemoteExecutor.Invoke(static () =>
+        {
+            // Arrange
+            var @delegate = (string task) => new Todo();
+
+            // IsReflectionEnabledByDefault defaults to `false` when `PublishTrimmed=true`. For these scenarios, we
+            // expect users to configure JSON source generation as instructed in the `NotSupportedException` message.
+            var exception = Assert.Throws<NotSupportedException>(() => RequestDelegateFactory.Create(@delegate));
+            Assert.Equal(
+                "JsonTypeInfo metadata for type 'Microsoft.AspNetCore.Routing.Internal.RequestDelegateFactoryTests+Todo' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.",
```
Comment (eerhardt) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:2923]: (nit) do we want to hard-code this whole exception message in our tests? If they update the message, our tests would break. Would it be better to assert that it contains a few of type names we know it should?

`Microsoft.AspNetCore.Routing.Internal.RequestDelegateFactoryTests+Todo`
`JsonSerializableAttribute`

?

File: src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonOutputFormatterTest.cs [hunk 4]
```diff
@@ -254,13 +256,50 @@ private static async IAsyncEnumerable<JsonPerson> GetPeopleAsync()
...
         // Arrange
         var jsonOptions = new JsonOptions();
         jsonOptions.JsonSerializerOptions.TypeInfoResolver = null;
 
-        Assert.Throws<InvalidOperationException>(() => SystemTextJsonOutputFormatter.CreateFormatter(jsonOptions));
+        var stjOutputFormatter = SystemTextJsonOutputFormatter.CreateFormatter(jsonOptions);
+        Assert.IsType<IJsonTypeInfoResolver>(stjOutputFormatter.SerializerOptions.TypeInfoResolver);
+    }
+
+    [ConditionalFact]
```
Comment (eerhardt) [inline src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonOutputFormatterTest.cs:269]: Can these two tests be made into a Theory?

**Review by eerhardt — APPROVED** [review]
