### PR TITLE
Don't throw TaskCanceledException in RateLimitingMiddleware

### LINKED ISSUE #43473: RateLimitingMiddleware throws TaskCanceledException
Today when a request is canceled, if that request was in the queue of a RateLimiter used by RateLimitingMiddleware, the middleware will throw the TaskCanceledException that it observes. Instead we should just log that info and exit gracefully.

### PR DESCRIPTION
**Pull request by wtgodbe**
# Don't throw TaskCanceledException in RateLimitingMiddleware

Don't throw `TaskCanceledException` when the request gets canceled - instead log at the debug level & exit normally.

## Description

Today when a request is canceled, if that request was in the queue of a RateLimiter used by RateLimitingMiddleware, the middleware will throw the TaskCanceledException that it observes. Instead we should just log that info and exit gracefully.

Fixes #43473

## Customer Impact

Customers have reported that seeing a bunch of TaskCanceledExceptions when they refresh their site to be a bad experience.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [x] Medium
- [ ] Low

Adds a new branch for returning from the middleware when the request is canceled - this scenario is different from the normal one of attempting to acquire a lease, so there could be some unforeseen bug.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 1]
```diff
@@ -149,11 +149,19 @@ private LeaseContext CombinedAcquire(HttpContext context)
                 return new LeaseContext() { GlobalRejected = false, Lease = endpointLease };
             }
         }
-        catch (Exception)
+        catch (Exception ex)
         {
             endpointLease?.Dispose();
             globalLease?.Dispose();
-            throw;
+            if (ex is TaskCanceledException)
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:156]: Look for `OperationCanceledException` and check if `context.HttpContext.RequestAborted.IsCancellationRequested` is true.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 2]
```diff
@@ -234,5 +242,8 @@ private static partial class RateLimiterLog
 
         [LoggerMessage(2, LogLevel.Debug, "This endpoint requires a rate limiting policy with name {PolicyName}, but no such policy exists.", EventName = "WarnMissingPolicy")]
         internal static partial void WarnMissingPolicy(ILogger logger, string policyName);
+
+        [LoggerMessage(3, LogLevel.Debug, "The task for this request was canceled.", EventName = "TaskCanceled")]
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:246]: "The request was canceled." or closed.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs (hunk 1 above)
Comment (wtgodbe) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:156]: As in only log if it's an `OperationCanceledException` _and_ `IsCancellationRequested` is true (otherwise throw)?

Comment (BrennanConroy) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:156]: Right

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs [hunk 3]
```diff
@@ -0,0 +1,19 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Threading.RateLimiting;
+
+namespace Microsoft.AspNetCore.RateLimiting;
+
+internal sealed class DefaultAcquiredLease : RateLimitLease
+{
+    public override bool IsAcquired => true;
```
Comment (Kahbazi) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:10]: I'm a little confused here. Shouldn't this be false? If it's true, does it mean that if the request is cancelled, then all the rate limiting policy for that request would be skipped and request would execute completely unless that somewhere in the pipeline `HttpContext.RequestAborted.IsCancellationRequested` is being checked?

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 4]
```diff
@@ -149,11 +149,19 @@ private LeaseContext CombinedAcquire(HttpContext context)
...
-        catch (Exception)
+        catch (Exception ex)
         {
             endpointLease?.Dispose();
             globalLease?.Dispose();
-            throw;
+            if (ex is TaskCanceledException)
+            {
+                RateLimiterLog.TaskCanceled(_logger);
+                return new LeaseContext() { Lease = new DefaultAcquiredLease() };
```
Comment (Kahbazi) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:160]: Could this lease could be shared?
```suggestion
                return new LeaseContext() { Lease = DefaultAcquiredLease.Instance };
```

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 5]
```diff
@@ -149,11 +149,20 @@ private LeaseContext CombinedAcquire(HttpContext context)
...
             }
         }
-        catch (Exception)
+        catch (Exception ex)
         {
             endpointLease?.Dispose();
             globalLease?.Dispose();
-            throw;
+            // Don't throw if the request was canceled - instead log. 
+            if (ex is OperationCanceledException && context.RequestAborted.IsCancellationRequested)
```
Comment (halter73) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:157]: Nit: Why not make this its own `catch (OperationCanceledException ex)` block and move the disposals to a `finally`? It feels like that would be a lot simpler to follow.

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+
+    public override IEnumerable<string> MetadataNames { get => throw new NotImplementedException(); }
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:12]: This should probably return an empty list; `Array.Empty<string>()`

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+    public override bool TryGetMetadata(string metadataName, out object? metadata) => throw new NotImplementedException();
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:14]: `return false;`

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs (hunk 3 above)
Comment (wtgodbe) [reply src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:10]: If this was false it would cause `OnRejected` to fire - but the request didn't get rejected by the RateLimiter, it got canceled. So in this case the middleware shouldn't take any action.

Comment (halter73) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:10]: Wouldn't it make more sense to return an unacquired lease? Don't we risk bad actors canceling requests while they're in the queue, the middleware continuing with an acquired lease, and then completely blowing past whatever limit was in place to protect the backend or db?

I wouldn't expect the inner limiter(s) to account for canceled attempts to acquire towards resource utilization. All of our default limiters would treat canceled requests as unacquired, right?

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs (hunk 6 above)
Comment (halter73) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:12]:
```suggestion
    public override IEnumerable<string> MetadataNames => Array.Empty<string>();
```

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs (hunk 7 above)
Comment (halter73) [inline src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:14]:
```suggestion
    public override bool TryGetMetadata(string metadataName, out object? metadata) => false;
```

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs (hunk 3 above)
Comment (halter73) [reply src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:10]: We should check if we got this particular lease instance and no-op without calling through to the `next()` middleware and without calling `OnRejected`.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs (hunk 4 above)
Comment (halter73) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:160]: I don't think we'll end up exposing this to users since I agree we shouldn't call `OnRejected` in this case. So maybe we can make this super easy and return a `LeaseContext?` instead of a `LeaseContext` and special case `null` instead. Then we don't need this class at all.

File: src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs (hunk 3 above)
Comment (Kahbazi) [reply src/Middleware/RateLimiting/src/DefaultAcquiredLease.cs:10]: Hmmm 🤔. Maybe check if the lease is this certain type and just return from the middleware.

I'm thinking about an attack that would send multiple requests and would abort them at this precise time which cause for skipping the rate limiter and ignore its purpose.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs (hunk 4 above)
Comment (halter73) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:160]: `LeaseContext` is an internal struct, so we could make it nullable. We could also add a flag like `LeaseContext.GlobalRejected` instead of using `Nullable<T>`. Maybe the flags could even be stuffed into a flag enum.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs (hunk 5 above)
Comment (BrennanConroy) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:157]: Because we don't want to dispose on the success path

File: src/Middleware/RateLimiting/src/LeaseContext.cs [hunk 8]
```diff
@@ -7,12 +7,19 @@ namespace Microsoft.AspNetCore.RateLimiting;
 
 internal struct LeaseContext : IDisposable
 {
-    public bool? GlobalRejected { get; init; }
+    public RequestRejectionReason? RequestRejectionReason { get; init; }
 
-    public required RateLimitLease Lease { get; init; }
+    public RateLimitLease Lease { get; init; }
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/LeaseContext.cs:12]: Odd that the compiler isn't complaining about this, mark it nullable.

File: docs/UpdatingMajorVersionAndTFM.md [hunk 9]
```diff
@@ -18,7 +18,6 @@ Typically, we will update the Major Version before updating the TFM. This is bec
 * In [src/Framework/test/TestData.cs](/src/Framework/test/TestData.cs), update `ListedTargetingPackAssemblies` by incrementing the AssemblyVersion of all aspnetcore assemblies by 1 major version. Once dotnet/runtime updates their AssemblyVersions, we also need to update those in this file. They typically make that change at the same time as their TFM update, but we change our AssemblyVersions as soon as we update branding.
 * Add entries to [NuGet.config](/NuGet.config) for the new Major Version's feed. This just means copying the current feeds (e.g. `dotnet7` and `dotnet7-transport`) and adding entries for the new feeds (`dotnet8` and `dotnet8-transport`). Make an effort to remove old feeds here at the same time.
 * In [src/ProjectTemplates/Shared/TemplatePackageInstaller.cs](/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs), add entries to `_templatePackages ` for `Microsoft.DotNet.Web.ProjectTemplates` and `Microsoft.DotNet.Web.Spa.ProjectTemplates` matching the new version.
-* In [src/Framework/AspNetCoreAnalyzers/test/Verifiers/CSharpRouteHandlerCodeFixVerifier.cs], update the references to `ReferenceAssemblies.Net.Netx0` with the latest version.
```
Comment (wtgodbe) [inline docs/UpdatingMajorVersionAndTFM.md:21]: Artifact of rebasing/retargeting to release/7.0. I'm inclined to just keep the change here since technically it's correct, and only in a markdown file

File: src/Middleware/RateLimiting/src/LeaseContext.cs (hunk 8 above)
Comment (wtgodbe) [reply src/Middleware/RateLimiting/src/LeaseContext.cs:12]: Weird, done. If it's a point of curiosity, I built/tested on my mac, so maybe that's related

**Comment by BrennanConroy** [comment]
Any reason you aren't targeting rc1?

**Comment by wtgodbe** [comment]
> Any reason you aren't targeting rc1?

The build is supposed to be done today, I figured we didn't have time. I suppose it couldn't hurt to send it to ask mode, though. I'll write an email.

**Review by dougbu — COMMENTED** [review]
Not ready yet due to `RateLimitingMiddleware` nullability issues

**Comment by wtgodbe** [comment]
Servicing approved over email

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 10]
```diff
@@ -234,5 +258,8 @@ private static partial class RateLimiterLog
 
         [LoggerMessage(2, LogLevel.Debug, "This endpoint requires a rate limiting policy with name {PolicyName}, but no such policy exists.", EventName = "WarnMissingPolicy")]
         internal static partial void WarnMissingPolicy(ILogger logger, string policyName);
+
+        [LoggerMessage(3, LogLevel.Debug, "The request was canceled.", EventName = "TaskCanceled")]
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:262]: This should probably be named "RequestCanceled" or something like that.

File: src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs [hunk 11]
```diff
@@ -139,21 +145,30 @@ private LeaseContext CombinedAcquire(HttpContext context)
...
             }
         }
-        catch (Exception)
+        catch (Exception ex)
         {
             endpointLease?.Dispose();
             globalLease?.Dispose();
-            throw;
+            // Don't throw if the request was canceled - instead log. 
+            if (ex is OperationCanceledException && context.RequestAborted.IsCancellationRequested)
```
Comment (BrennanConroy) [inline src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:163]: This code path won't throw on request aborted will it?

Comment (wtgodbe) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:163]: It should log debug then return from the middleware (line 90)

Comment (BrennanConroy) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:163]: I mean, you call AttemptAcquire which doesn't take a cancellation token, so who would be throwing the OCE?

Comment (wtgodbe) [reply src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs:163]: Oh I see what you're saying - yeah, you're right, this was an unnecessary copy/paste. I'll remove.

**Review by BrennanConroy — APPROVED** [review]
