### PR TITLE
Blazor Desktop: Call ServiceScope.DisposeAsync() instead of Dispose()

### LINKED ISSUE #31112: Tear down of Microsoft.AspNetCore.Components.WebView
### Describe the bug
The tear down of the 'Microsoft.AspNetCore.Components.WebView' component will cause an exception

### To Reproduce
Add the following code line to "src\Components\WebView\Samples\BlazorWinFormsApp"
`public Form1()
 {
...
            serviceCollection.AddScoped<ExampleJsInterop>();
}
`
Add the following code line to "src\Components\WebView\Samples\WebviewAppShared"
`@inject ExampleJsInterop Js
`

### Exceptions (if any)
System.InvalidOperationException: ''WebviewAppShared.ExampleJsInterop' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.'

### Further technical details
The same problem has been reported here #13343

### PR DESCRIPTION
**Pull request by Eilon**
If you call Dispose() and there are IAsyncDisposable scoped services registered, it throws. Instead it needs to call DisposeAsync() that supports both sync and async disposable services.

Partial fix for #31112. The rest of this fix will be in the MAUI repo: https://github.com/dotnet/maui/issues/1280

### CODE REVIEW

File: src/Components/WebView/WebView/src/PageContext.cs [hunk 1]
```diff
@@ -45,10 +46,10 @@ internal class PageContext : IDisposable
             Renderer = new WebViewRenderer(services, dispatcher, ipcSender, loggerFactory, JSRuntime.ElementReferenceContext);
         }
 
-        public void Dispose()
+        public async ValueTask DisposeAsync()
         {
             Renderer.Dispose();
-            _serviceScope.Dispose();
+            await _serviceScope.DisposeAsync();
```
Comment (halter73) [inline src/Components/WebView/WebView/src/PageContext.cs:52]: Not sure how much this is called, but you could just return this if you don't mind losing the stack frame in any possible exceptions.

File: src/Components/WebView/WebView/src/WebViewManager.cs [hunk 2]
```diff
@@ -210,7 +212,9 @@ protected virtual void Dispose(bool disposing)
             {
                 if (disposing)
                 {
-                    _currentPageContext?.Dispose();
+                    // This is the same pattern that is used in Microsoft.Extensions.Hosting.Internal.Host.Dispose():
+                    //    https://github.com/dotnet/runtime/blob/645dfe69fb25407de7a5484d7a03d3342b4e0279/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L146
+                    _currentPageContext?.DisposeAsync().AsTask().GetAwaiter().GetResult();
```
Comment (halter73) [inline src/Components/WebView/WebView/src/WebViewManager.cs:217]: Can WebViewManager implement DisposeAsync?

Comment (Eilon) [reply src/Components/WebView/WebView/src/WebViewManager.cs:217]: Good idea, I can push this down 1 more layer (where maybe in theory some callers actually support async disposal).

File: src/Components/WebView/WebView/src/PageContext.cs (hunk 1 above)
Comment (Eilon) [reply src/Components/WebView/WebView/src/PageContext.cs:52]: Will do.

File: src/Components/WebView/WebView/src/WebViewManager.cs [hunk 3]
```diff
@@ -204,25 +206,29 @@ record RootComponent
...
 
                 _disposed = true;
             }
         }
 
         /// <inheritdoc/>
-        public void Dispose()
+        public ValueTask DisposeAsync()
         {
             // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
```
Comment (campersau) [inline src/Components/WebView/WebView/src/WebViewManager.cs:228]:
```suggestion
            // Do not change this code. Put cleanup code in 'DisposeAsync(bool disposing)' method
```

Comment (Eilon) [reply src/Components/WebView/WebView/src/WebViewManager.cs]: @campersau great catch, thank you!

**Review by taha-ghadirian — APPROVED** [review]

File: src/Components/WebView/WebView/src/WebViewManager.cs [hunk 4]
```diff
@@ -204,25 +206,29 @@ record RootComponent
...
 
         /// <inheritdoc/>
-        public void Dispose()
+        public ValueTask DisposeAsync()
         {
-            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
-            Dispose(disposing: true);
+            // Do not change this code. Put cleanup code in 'DisposeAsync(bool disposing)' method
+            var task = DisposeAsync(disposing: true);
             GC.SuppressFinalize(this);
```
Comment (halter73) [inline src/Components/WebView/WebView/src/WebViewManager.cs:230]: Nit: I'd just suppress finalization first. I don't see how order could matter here. And it's a bit weird to do it potentially in parallel with DisposeAsync.

**Review by halter73 — APPROVED** [review]

File: src/Components/WebView/WebView/src/WebViewManager.cs [hunk 5]
```diff
@@ -204,25 +206,29 @@ record RootComponent
...
                 if (disposing)
                 {
-                    _currentPageContext?.Dispose();
+                    if (_currentPageContext != null)
+                    {
+                        await _currentPageContext.DisposeAsync();
+                    }
                 }
 
                 _disposed = true;
```
Comment (halter73) [inline src/Components/WebView/WebView/src/WebViewManager.cs:221]: If it were me I'd set this flag first and then return `_currentPageContext?.DisposeAsync() ?? default` but I probably try to avoid async state machines too much 😅

Comment (Eilon) [reply src/Components/WebView/WebView/src/WebViewManager.cs:221]: This is the general pattern in [the docs](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync), though this exact case of sync-calling-async isn't present.

File: src/Components/WebView/WebView/src/WebViewManager.cs (hunk 4 above)
Comment (Eilon) [reply src/Components/WebView/WebView/src/WebViewManager.cs:230]: See other comment; this is roughly what's in the docs.

File: src/Components/WebView/WebView/src/PageContext.cs [hunk 6]
```diff
@@ -17,7 +18,7 @@ namespace Microsoft.AspNetCore.Components.WebView
     /// for web views, the IPC channel is outside the page context, whereas in Blazor Server,
     /// the IPC channel is within the circuit.
     /// </summary>
-    internal class PageContext : IDisposable
+    internal class PageContext : IAsyncDisposable
     {
```
Comment (davidfowl) [inline src/Components/WebView/WebView/src/PageContext.cs:22]: Maybe implement both?

**Comment by davidfowl** [comment]
I think you want components to implement both all the way down if possible

File: src/Components/WebView/WebView/src/PageContext.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/WebView/WebView/src/PageContext.cs:22]: We are the only consumers of this, what's the advantage of implementing both? From my point of view, the disadvantage of implementing both is that you can call `Dispose` by mistake and that will have to block without you knowing.

File: src/Components/WebView/WebView/src/WebViewManager.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/WebView/WebView/src/WebViewManager.cs:230]: We don't need to do the whole pattern here since this class (nor derived classes) have a finalizer, am I wrong?

**Review by javiercn — COMMENTED** [review]
I think we need a quick chat about how to do this proper, we've dealt with a similar thing recently on WebApplicationFactory and we should "standarize" the pattern.

**Comment by Eilon** [comment]
Happy to discuss further. It does strike me as odd to implement IDisposable on a _new_ type that will fail if you call it in seemingly-arbitrary circumstances instead of IAsyncDisposable.

File: src/Components/WebView/WebView/src/PageContext.cs (hunk 6 above)
Comment (Eilon) [reply src/Components/WebView/WebView/src/PageContext.cs:22]: Well, either block, which can be bad/dead-locky, or throw! This whole problem came about because the ServiceScope thing _throws_ if you call the wrong one.

**Comment by Eilon** [comment]
Here's the .NET MAUI/WPF/WinForms response to this: https://github.com/dotnet/maui/pull/1678

**Comment by Eilon** [comment]
Code review feedback applied. Apologies to others who got pinged on this PR. GitHub for Windows does _weird_ stuff when trying to rebase a branch and force push. I won't do that again (if I remember).

**Review by SteveSandersonMS — APPROVED** [review]
Apart from [this tweak](https://github.com/dotnet/aspnetcore/pull/33482/files#r650856980), looks great to me!

File: src/Components/WebView/WebView/src/WebViewManager.cs (hunk 4 above)
Comment (Eilon) [reply src/Components/WebView/WebView/src/WebViewManager.cs:225]: Removed 'bool disposing'
