### PR TITLE
Virtualize component: method to trigger data refresh

### LINKED ISSUE #26110: blazor: Virtualize does not respond to items change
### Describe the bug
There is no efficient way to change the items in `Virtualize`. Natural way to do it would be for `Virtualize` to respond to `Items` property change. Currently it does not respond.

Inefficient way is to update the `@key` for `Virtualize` . That approach causes flickering and resets the scrolling position.

In the [announcement](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-component-virtualization) `Virtualize` is advertized as a replacement of inefficient foreach. This bug makes the replacement impossible in some situations. 

### To Reproduce
Click "Add item". Virtualized list does not update. Non virtualized does.
In general, one would expect the virtualized and not virtualized versions to behave identically, for example, when it comes to preservation of scrolling position and when items are added/changed/removed.

```razor
@page "/"
@using System.Linq

Virtualized:
<div style="overflow-y: auto; height: 200px; border: 2px solid blue;">
    <Virtualize Items="@items" Context="item" @key="@revision">
        <div @key="@item">@item</div>
    </Virtualize>
</div>
Not Virtualized:
<div style="overflow-y: auto; height: 200px; border: 2px solid blue;">
    @foreach (var item in items)
    {
        <div @key="@item">@item</div>
    }
</div>
<button @onclick="AddItem">Add item</button>
<button @onclick="AddItemAndUpdateKey">Add item and update Virtualize's key</button>

@code {

int[] items = Enumerable.Range(0, 5).ToArray();
int revision = 0;

void AddItem()
{
    items = Enumerable.Range(0, items.Length + 1).ToArray();
}

void AddItemAndUpdateKey()
{
    AddItem();
    ++revision;
}

}
```

### Further technical details
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.515 [C:\Program Files\dotnet\sdk]
  2.1.517 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
## Description

`<Virtualize>` is a new feature first shipped in 5.0 RC1. We were very keen to get it into RC1 so we could capture customer feedback about its usability. Overall it's been well received. Customers have used it in a wide range of scenarios successfully.

However, one bit of feedback showed there's an important functional gap: #26110 

That is, there isn't any reasonable way to make the `<Virtualize>` list update when the number of items in the list changes. It does update when the items are mutated in place, but not when items are added or removed. More generally there isn't a way to tell the `ItemsProvider` to re-query the external data source, so there wouldn't be any way to implement a "Refresh" button in the application UI.

Since this kind of feedback is exactly what we hoped to get from shipping in RC1, it makes sense to address it in RC2.

## Customer impact

Without this change, developers using `<Virtualize>` have no reasonable way to make their UI update when items are added/removed in their list. That will be a common scenario.

## Regression?

No, it's a new feature since 5.0 RC1.

## Risk

The changes are completely scoped to the `<Virtualize>` component and its tests. So the worst case would be causing some new problem in `<Virtualize>`, but nothing else could be affected.

Looking at the changes in this PR, I don't personally think they are likely to trigger any new unwanted behaviors. The implementation is fairly straightforwards.

### CODE REVIEW

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 1]
```diff
@@ -204,5 +210,136 @@ public void CanUseViewportAsContainer()
...
+                name => Assert.Equal("Person 3", name));
+        }
+
+        [Fact]
+        public void CanMutateDataInPlace_Async()
+        {
+            Browser.MountTestComponent<VirtualizationDataChanges>();
+
+            // Initial data
+            var container = Browser.FindElement(By.Id("using-itemsprovider"));
```
Comment (HaoK) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs:243]: nit: since the tests are named sync/async, maybe the element id's should also have sync/async suffixes to align, mostly to make it more clear from just looking at the test code what's going on

Comment (SteveSandersonMS) [reply src/Components/test/E2ETest/Tests/VirtualizationTest.cs:243]: Unless you feel strongly, I'd prefer to keep this as-is, because it's not really about sync vs async in terms of the underlying scenario. The underlying scenario is really about `Items` vs `ItemsProvider`. I know the existing E2E test cases are named with sync/async which is why I followed that pattern there, but the implementation doesn't really need to do that.

**Review by pranavkm — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT This PR is ready for tactics now.

**Review by captainsafia — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Ready to merge
