### PR TITLE
[blazor][wasm] Dispatch rendering to main thread (Net9)

### LINKED ISSUE #48768: Integrate with WebAssembly multithreading
As multithreading is added to the core .NET WebAssembly runtime, we need to ensure this doesn't lead to invalid/dangerous scenarios for Blazor components.

 * Min bar: if the renderer is accessed from the wrong thread, throw
 * Ideal: sync context with semantics equivalent to Blazor Server or WebView, so `InvokeAsync` works

This is going to come in late so we should take a risk-averse position on how much we attempt to implement here.

### LINKED ISSUE #95547: [browser][MT] InvokeAsync in Blazor WASM components calls into the caller thread instead of the UI thread.
### Description

ComponentBase.InvokeAsync does not call on the UI thread when called from another thread.

### Reproduction Steps

Test project repo: [Threads Test](https://github.com/LostBeard/ThreadsTest)

The project msut have ```<WasmEnableThreads>true</WasmEnableThreads>``` and reference Microsoft.NET.WebAssembly.Threading. I also have the workload ```wasm-experimental``` installed.

In a Blazor WASM threading project replace the Counter.razor page with the below code.
```cs
@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current text: @screenData</p>
<button class="btn btn-primary" @onclick="ButtonClicked">Use InvokeAsync</button>

@code {
    private string screenData = "";

    // This does not work using InvokeAsync
    private async void ButtonClicked()
    {
        Console.WriteLine("Message1,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
        screenData = "AfterMessage1";
        StateHasChanged();
        await Task.Run(async () =>
        {
            Console.WriteLine("Message2,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
            await Task.Delay(2000);
            Console.WriteLine("Message3,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
            await InvokeAsync(() =>
            {
                // This is not called on the UI thread as expected
                screenData = "AfterMessage3";
                Console.WriteLine("Message4,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
                // *** Below line throws errors viewable in devtools console ***
                StateHasChanged();
            });
            await Task.Delay(2000);
            Console.WriteLine("Message5,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
        });
        Console.WriteLine("Message6,MyThreadID:" + System.Threading.Thread.CurrentThread.ManagedThreadId);
        screenData = "AfterMessage6";
        StateHasChanged();
    }
}
```

### Expected behavior

I expect InvokeAsync (in a Blazor WASM component) to call on the UI thread context.

### Actual behavior

 InvokeAsync (in a Blazor WASM component) calls on the same thread it is called from.

### Regression?

Unknown.

### Known Workarounds

This (InvokeAsyncAlt) works in place on InvokeAsync in a Blazor Component
```cs
    SynchronizationContext sctx = SynchronizationContext.Current!;
    Task InvokeAsyncAlt(Action action)
    {
        sctx.Post((object state) => action(), null);
        return Task.CompletedTask;
    }
    Task InvokeAsyncAlt(Func<Task> action)
    {
        sctx.Post(async (object state) => await action(), null);
        return Task.CompletedTask;
    }
```

### Configuration

Blazor WebAssembly Standalone template with .Net 8.0.0
Windows 10  x64
.Net 8.0.100
Tested in Chrome 119.0.6045.200 and Firefox 120.0

### Other information

I came across this issue while helping answer a question on StackOverflow [How do child threads talk to the main (UI) thread in blazor webassembly (multithreading mode)](https://stackoverflow.com/questions/77590469/how-do-child-threads-talk-to-the-main-ui-thread-in-blazor-webassembly-multith)

### PR DESCRIPTION
**Pull request by pavelsavara**
This PR implements `WebAssemblyDispatcher` which will dispatch the call to `Component.InvokeAsync` back to main thread, where all the rendering/JS interop/networking could happen.

Context: with `<WasmEnableThreads>true</WasmEnableThreads>` we could use thread pool in C#. 

Added new `src/Components/WebAssembly/testassets/ThreadingApp` 
- which is almost vanilla Blazor Wasm template, but with threads enabled. 
- On Counter page it uses timer and thread pool continuation to increase the count and then `InvokeAsync` to render it.
- On FetchData page we test that Http client could be also used from thread pool.

Notes:
- server side `RendererSynchronizationContext` is running jobs on multiple threads
- WASM MT `JSSynchronizationContext` is running jobs always in single thread
- both `RendererSynchronizationContextDispatcher` and `WebAssemblyDispatcher` can synchronously run jobs out of order!
- `RendererSynchronizationContextDispatcher` checks `SynchronizationContext.Current` which could propagate to multiple threads
- `WebAssemblyDispatcher` checks explicit thread, because of the JS objects thread affinity.
- both can throw exceptions synchronously or set exception to the `Task`
- `RendererSynchronizationContext` has `UnhandledExceptionEventHandler`
- `WebAssemblyDispatcher` always propagates the exception to the caller.

Contributes to https://github.com/dotnet/runtime/issues/85592
Fixes https://github.com/dotnet/aspnetcore/issues/48768
Fixes https://github.com/dotnet/runtime/issues/95547
Previous attempt https://github.com/dotnet/aspnetcore/pull/48991

### CODE REVIEW

**Comment by amcasey** [comment]
Superficially, it looks like the tests got stuck here
```
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.Wait() Line 2634	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)	Unknown
 	Microsoft.AspNetCore.Components.Web.dll!Microsoft.AspNetCore.Components.RenderTree.WebRenderer.Dispose(bool disposing)	Unknown
 	Microsoft.AspNetCore.Components.WebAssembly.dll!Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.Dispose(bool disposing)	Unknown
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose.AnonymousMethod__0()	Unknown
 	Microsoft.AspNetCore.Components.WebAssembly.dll!Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyDispatcher.InvokeAsync.AnonymousMethod__4_0(object o)	Unknown
```

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+{
+    public static readonly Dispatcher Instance = new WebAssemblyDispatcher();
+    private readonly SynchronizationContext _mainSyncContext;
+
+    private WebAssemblyDispatcher()
+    {
+        Debug.Assert(Environment.CurrentManagedThreadId == 1); // WebAssemblyDispatcher should be initialized on the main thread.
+
+        // capture the JSSynchronizationContext from the main thread, which runtime already installed.
+        _mainSyncContext = SynchronizationContext.Current!;
```
Comment (kg) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs:22]: should we ! this instead of asserting that it's not null? someone could have switched it

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+
+        return tcs.Task;
+    }
+
+    public override Task<TResult> InvokeAsync<TResult>(Func<TResult> workItem)
+    {
+        ArgumentNullException.ThrowIfNull(workItem);
+        if (CheckAccess())
+        {
+            return Task.FromResult(workItem());
```
Comment (kg) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs:68]: this means if workItem throws, it will just bubble out instead of wrapping the exception in the Task return value. Is that intended? It feels like it would be better if exceptions always propagated out through the task

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+            // send me to the thread pool
+            await Task.Delay(10).ConfigureAwait(false);
+            StateHasChanged(); // render should throw
+        }
+        catch(Exception ex)
+        {
+            exc=ex;
+            Console.WriteLine(ex.Message);
+        }
+        if (exc == null || exc.Message != "The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.")
```
Comment (kg) [inline src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:42]: this message will probably get localized, right? could we assert on something else about it, like maybe that it's a specific type of exception?

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+        var t = new Thread(() => {
+            tcs.SetResult(Thread.CurrentThread.ManagedThreadId);
+        });
+        t.Start();
+        var newThreadId = await tcs.Task;
+        if (newThreadId == 1){
+            throw new Exception("We should be on new thread in the callback!");
+        }
+
+        new Timer(async (state) =>
```
Comment (kg) [inline src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:58]: isn't this timer going to get randomly finalized since it's not being stored in a field? i'd prefer to see it get rooted

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs (hunk 1 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs:22]: Relevant discussion was on previous attempt here https://github.com/dotnet/aspnetcore/pull/48991#discussion_r1258087940

My understanding is that if people install another `SynchronizationContext` than `JSSynchronizationContext` it's up to them to make it work.

I could stop asserting the `JSSynchronizationContext` by name to allow it. What do you think ?

`JSSynchronizationContext` is not public API so I could not re-install it here.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs (hunk 2 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs:68]: This is intentional for consistency with https://github.com/dotnet/aspnetcore/blob/0ed0bcdbfd0e0ca1617179e495ef893e36cb332c/src/Components/Components/src/Rendering/RendererSynchronizationContextDispatcher.cs#L46

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor (hunk 3 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:42]: All the E2E unit tests run in US locale. There are also other places with the same assert. I unified the style to match others closely.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs (hunk 1 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs]: I simplified the code and added comments.

**Comment by pavelsavara** [comment]
> ```
>  	System.Private.CoreLib.dll!System.Threading.Tasks.Task.Wait() Line 2634	C#
>  	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)	
> ```

In `Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostTest.DisposeAsync_CanDisposeAfterCallingRunAsync`

Hmmm, this is not ideal and we will have to solve it.

**Comment by kg** [comment]
> > ```
> >  	System.Private.CoreLib.dll!System.Threading.Tasks.Task.Wait() Line 2634	C#
> >  	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)	
> > ```
> 
> In `Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostTest.DisposeAsync_CanDisposeAfterCallingRunAsync`
> 
> Hmmm, this is not ideal and we will have to solve it.

Seems like it should be IAsyncDisposable

**Comment by pavelsavara** [comment]
@amcasey could you please help me to troubleshoot it ?

- it seems to me this is running the `Microsoft.AspNetCore.Components.WebAssembly.Tests.csproj` on CoreCLR, not really Mono WASM in browser. Correct ?
- how did you find the stack trace ?
- how do I reproduce it ?

many thanks!

**Comment by pavelsavara** [comment]
What should happen with `src\Components\WebView\Samples\PhotinoPlatform\src\PhotinoSynchronizationContext.cs` ? Is that relevant to WASM ?

**Comment by pavelsavara** [comment]
It's using `Xunit.Sdk.AsyncTestSyncContext` which triggers usage of `WebAssemblyDispatcher` instead of previous `NullDispatcher`.
I will fix some problems with locking and dispose pattern.

**Comment by amcasey** [comment]
> how did you find the stack trace ? I'm looking into [CI here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=495727&view=ms.vss-test-web.build-test-results-tab&runId=11517412&resultId=123897&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab) and can't find it.

There's an Artifacts tab in the AzDO view, but I'm not sure who has access.  I pulled the trace out of a dump artifact.

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+
+    WeatherForecast[] forecasts;
+    DateTime startDate;
+
+    protected override async Task OnParametersSetAsync()
+    {
+        startDate = StartDate.GetValueOrDefault(DateTime.Now);
+
+        // send me to the thread pool, next line HTTP should work anyway
+        await Task.Delay(10).ConfigureAwait(false);
```
Comment (javiercn) [inline src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor:57]: This pattern is not supported in Blazor. When we see users do something like this, we tell them it's not supported. It makes the callback leave the Blazor sync context (on server and now on wasm) which we don't consider valid.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs [hunk 6]
```diff
@@ -22,12 +22,21 @@ namespace Microsoft.AspNetCore.Components.WebAssembly.Rendering;
...
 
     public WebAssemblyRenderer(IServiceProvider serviceProvider, ILoggerFactory loggerFactory, JSComponentInterop jsComponentInterop)
         : base(serviceProvider, loggerFactory, DefaultWebAssemblyJSRuntime.Instance.ReadJsonSerializerOptions(), jsComponentInterop)
     {
         _logger = loggerFactory.CreateLogger<WebAssemblyRenderer>();
 
+        // if SynchronizationContext.Current is null, it means we are on the single-threaded runtime
+        // otherwise capture the JSSynchronizationContext from the main thread, which runtime already installed.
+        // if user installed SynchronizationContext different from JSSynchronizationContext, they need to make sure the behavior is consistent with JSSynchronizationContext.
+        var currentCtx = SynchronizationContext.Current;
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:35]: Instead of capturing the context here, it might make more sense to capture the context earlier during the program execution and flow it here. Some options:
* ModuleInitializer: Might be too son.
* WebAssemblyHostbuilder: This is pretty much the first line in the program for a blazor app, so there's a very narrow window for the user to override this.

I don't think we care about supporting a custom synchronization context that is not the JS one.

Comment (pavelsavara) [reply src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs:35]: Added `WebAssemblyHostBuilder.InitializeWebAssemblyRenderer`

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor (hunk 5 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor:57]: I will make it more explicit threadpool task

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs [hunk 7]
```diff
@@ -176,6 +179,15 @@ private WebAssemblyHostEnvironment InitializeEnvironment(IInternalJSImportMethod
         return hostEnvironment;
     }
 
+    private static void InitializeWebAssemblyRenderer()
+    {
+        // capture the JSSynchronizationContext from the main thread, which runtime already installed.
+        // if SynchronizationContext.Current is null, it means we are on the single-threaded runtime
+        // if user somehow installed SynchronizationContext different from JSSynchronizationContext, they need to make sure the behavior is consistent with JSSynchronizationContext.
+        WebAssemblyDispatcher._mainSynchronizationContext = SynchronizationContext.Current;
+        WebAssemblyDispatcher._mainManagedThreadId = Environment.CurrentManagedThreadId;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs:188]: While it would be unusual to instantiate more than one `WebAssemblyHostBuilder`, it is possible (you can call `WebAssemblyHostBuilder.CreateDefault()` more than once). The logic here looks like it would overwrite these static fields if you instantiated one from a background thread.

Would it be worth either skipping these assignments if they are already assigned (e.g., with `??=`), or throwing if you try to instantiate a `WebAssemblyHostBuilder` from a background thread?

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs [hunk 8]
```diff
@@ -0,0 +1,158 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace Microsoft.AspNetCore.Components.WebAssembly.Rendering;
+
+// When Blazor is deployed with multi-threaded runtime, WebAssemblyDispatcher will help to dispatch all Blazor JS interop calls to the main thread.
+// This is necessary because all JS objects have thread affinity. They are only available on the thread (WebWorker) which created them.
+// Also DOM is only available on the main (browser) thread.
+// Because all of the Dispatcher.InvokeAsync methods return Task, we don't need to propagate errors via OnUnhandledException handler
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyDispatcher.cs:9]: > Because all of the Dispatcher.InvokeAsync methods return Task, we don't need to propagate errors via OnUnhandledException handler

What about if a delegate passed to `Dispatcher.InvokeAsync` throws synchronously? Can you confirm the exception behavior will be the same as for `Dispatcher.InvokeAsync` on the single-threaded runtime and on the Blazor Server multi-threaded runtime?

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+        currentCount++;
+    }
+
+    protected override async Task OnInitializedAsync()
+    {
+        if (!OperatingSystem.IsBrowser())
+        {
+            return;
+        }
+
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:26]:
```suggestion
        if (!OperatingSystem.IsBrowser())
        {
            return;
        }

```

Not sure we need to check this. Is there some reason for thinking this app might get run in another way?

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+    protected override async Task OnParametersSetAsync()
+    {
+        startDate = StartDate.GetValueOrDefault(DateTime.Now);
+        var url = $"sample-data/weather.json?date={startDate.ToString("yyyy-MM-dd")}";
+        using var req = new HttpRequestMessage(HttpMethod.Get, url);
+        req.SetBrowserResponseStreamingEnabled(true);
+
+        // send the request from the UI thread
+        var pr = Http.SendAsync(req, HttpCompletionOption.ResponseHeadersRead);
+        using var response = await pr;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor:63]:
```suggestion
        using var response = await Http.SendAsync(req, HttpCompletionOption.ResponseHeadersRead);
```

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor:63]: Also can I check: does the multithreaded runtime support performing HttpClient requests entirely on a background thread, without having to dispatch to the UI thread at all?

File: src/Components/test/E2ETest/Tests/ThreadingAppTest.cs [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+    {
+        // Navigate to "Counter"
+        Browser.Exists(By.LinkText("Counter")).Click();
+        Assert.Equal("Counter", Browser.Exists(By.TagName("h1")).Text);
+
+        var countDisplayElement = Browser.Exists(By.CssSelector("h1 + p"));
+
+        // wait and see timer increase
+        await Task.Delay(500);
+        Assert.NotEqual("Current count: 0", countDisplayElement.Text);
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/Tests/ThreadingAppTest.cs:78]: This looks like a race condition that could mean the test is flaky. It's always possible the browser takes longer than 500ms to do this even if we think it should complete in < 100ms.

The normal way we make these tests reliable is to use the wait-assertions, e.g.: something like

```suggestion
        Browser.NotEqual("Current count: 0", () => countDisplayElement.Text);
```

This will wait until the assertion becomes true, or eventually time out with an error after about 10 seconds if it never becomes true.

File: src/Components/test/E2ETest/Tests/ThreadingAppTest.cs [hunk 12]
```diff
@@ -0,0 +1,130 @@
...
+    }
+
+    [Fact]
+    public async Task HasCounterPage()
+    {
+        // Navigate to "Counter"
+        Browser.Exists(By.LinkText("Counter")).Click();
+        Assert.Equal("Counter", Browser.Exists(By.TagName("h1")).Text);
+
+        var countDisplayElement = Browser.Exists(By.CssSelector("h1 + p"));
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/Tests/ThreadingAppTest.cs:74]: If we're going to check that the text changes below, we need to also check its initial value otherwise the test could pass falsely because someone rephrased the text in the test app, e.g.:

```suggestion
        var countDisplayElement = Browser.Exists(By.CssSelector("h1 + p"));
        Browser.Equal("Current count: 0", () => countDisplayElement.Text);
```

However you also need to change the test app so that it does not start the timer until the test explicitly takes a gesture to do so (e.g., by clicking a button), otherwise the test could be flaky since the timer might fire before this line.

I know it might seem like this is a bit demanding but we've had years of refining our techniques to make the E2E tests actually reliable and it does require following these kinds of patterns. The alternative is having tests that are each individually 99.99% reliable and in practice that's just not enough to keep the builds passing :)

**Comment by SteveSandersonMS** [comment]
> Why does the RendererSynchronizationContextDispatcher use UnhandledExceptionEventHandler rather than to propagate the error to the caller ? Is there benefit doing it this way ?

I'm not sure that's correct. `RendererSynchronizationContextDispatcher` does propagate exceptions to the caller by calling `state.Completion.SetException(exception)`. However, what happens if **that** call throws? That is, if the caller's exception-handling continuation itself throws.

If I'm reading it correctly, if the caller's exception-handling continuation throws, then there's nobody else to report the exception to, so it's now an unhandled exception, so we use the `UnhandledExceptionEventHandler`.

It looks like `WebAssemblyDispatcher` doesn't have any equivalent to this. Is that right?

**Comment by SteveSandersonMS** [comment]
I notice one big difference between how you've approached things vs the existing code is:

 * In the existing code, the dispatcher is trivial and just calls `InvokeAsync` on the sync context without any other real logic (beside short-circuiting if `CheckAccess() == true`). All the sophistication is inside the sync context class.
 * In your new code, all the sophistication is inside the dispatcher.

Having the scheduling logic take place inside the sync context makes more sense to me because that's what will get called to schedule the continuation each time some async work yields. Having it inside the dispatcher makes it a bit less clear to me how we can be sure the continuations will run in the right place. I appreciate it may be correct but am just a bit less clear on it.

Could you clarify why it was better to put the sophistication inside the dispatcher inside of inside the sync context like the existing code?

**Comment by SteveSandersonMS** [comment]
I guess arguably the way to make this code more equivalent to the existing logic would be if you added an `InvokeAsync` to `JSSynchronizationContext` that handles most of this sophistication, and then `WebAssemblyDispatcher` would just call that.

Whether or not this is desirable depends most on who is most likely to want to modify this behavior in the future, and whether it's really Blazor-specific. Reading the logic in `WebAssemblyDispatcher`, it doesn't really seem Blazor-specific to me, so it seems more likely that the runtime team would benefit from owning and controlling that logic in the long run. So maybe it would be advantageous to follow this pattern of having an `InvokeAsync` on `JSSyncContext`. I know that would have to be exposed as public API though. Is that practical, or you think this would be a bad idea?

**Comment by SteveSandersonMS** [comment]
> both RendererSynchronizationContextDispatcher and WebAssemblyDispatcher can synchronously run jobs out of order!

That's true only in the sense that, if you call `InvokeAsync` while you're already on the sync context, we short-circuit and run the work synchronously, right? This is important because we don't want `InvokeAsync` to come at a large extra cost - developers should feel free to call it whenever it might be required, without having to write their own short-circuiting logic around it to avoid unnecessary costs from scheduling.

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor (hunk 10 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/FetchData.razor:63]: I does it badly on current runtime main, but I have PR in progress and eventually, it will just work.

**Comment by pavelsavara** [comment]
> > both RendererSynchronizationContextDispatcher and WebAssemblyDispatcher can synchronously run jobs out of order!
> 
> That's true only in the sense that, if you call `InvokeAsync` while you're already on the sync context, we short-circuit and run the work synchronously, right?

Right, the difference is that server sync context could be installed and executed on many threads. Which is fine there, only thing which matters on the server is only-one-at-a-time. On WASM, there is strong thread affinity to only one thread, so we could not shortcut based on installed sync context, but only based on actual thread.

File: src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor (hunk 9 above)
Comment (pavelsavara) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:26]: `OnInitializedAsync()` could also run on the server side, right ? And the rest of the code is not relevant on the server side.

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/testassets/ThreadingApp/Pages/Counter.razor:26]: I thought this whole app was set up to run on WebAssembly, so I didn't think any part of it would ever run on the server.

**Comment by pavelsavara** [comment]
>     * In your new code, a lot of that sophistication (i.e., mapping of `InvokeAsync` semantics to sync context send/post semantics) is inside the dispatcher.
> Could you clarify why it was better to put the sophistication inside the dispatcher inside of inside the sync context like the existing code? My guess is it's about not having to make `JSSyncContext` into public API.

The extra sophistication you speak about, should be compared with extra methods `RendererSynchronizationContext.InvokeAsync` which are not part of the regular `SynchronizationContext` API. That is Blazor specific extension.

> I guess arguably the way to make this code more equivalent to the existing logic would be if you added an `InvokeAsync` to `JSSynchronizationContext` that handles most of this sophistication, and then `WebAssemblyDispatcher` would just call that.

I agree that the developer experience of using public API of `SynchronizationContext` is far from ideal in the world of `async`/`await`/`Task`.
That's what `InvokeAsync` solves for Blazor, in somewhat Blazor specific way.

> Whether or not this is desirable depends most on who is most likely to want to modify this behavior in the future, and whether it's really Blazor-specific. 

If we wanted to have better API for the `SynchronizationContext` + `Task` scenarios, that would be different project than this.
I also think it may have different API signatures than the public API of Blazor.

**Comment by pavelsavara** [comment]
> I'm not sure that's correct. `RendererSynchronizationContextDispatcher` does propagate exceptions to the caller by calling `state.Completion.SetException(exception)`. However, what happens if **that** call throws? That is, if the caller's exception-handling continuation itself throws.

Do we know if this actually ever happens ? 
`WebAssemblyDispatcher` uses `TaskCompletionSource.SetException` which in my opinion only throws if the same task was already completed/failed before.

We can use `TaskCompletionSource.TrySetException`, but I think we don't have scenario where both branches are executed.

> It looks like `WebAssemblyDispatcher` doesn't have any equivalent to this. Is that right?

I think it doesn't need to be there.

But I can add extra try/catch layer to `WebAssemblyDispatcher` and forward it to `UnhandledExceptionEventHandler`
Should I do that, just to be on the safe side ? @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
To get a better sense of the compatibility level with existing code, I was hoping to try running the existing suite of E2E tests with the multithreaded wasm runtime. (Note that I only hope to do this as a one-off manual run, not as something to run on every build in CI). However I'm not sure what's required to enable that.

What I did:

 * In `src\Components\test\testassets\BasicTestApp\BasicTestApp.csproj`, added `<WasmEnableThreads>true</WasmEnableThreads>`
 * In `src\Components\WebAssembly\DevServer\src\Server\Startup.cs`, inside `Configure`, added:
    ```cs
    app.Use(async (ctx, next) =>
    {
        // Browser multi-threaded runtime requires cross-origin policy headers to enable SharedArrayBuffer.
        ctx.Response.Headers.Append("Cross-Origin-Embedder-Policy", "require-corp");
        ctx.Response.Headers.Append("Cross-Origin-Opener-Policy", "same-origin");
        await next(ctx);
    });
    ```
 * Ran an existing Blazor WebAssembly E2E test (arbitrarily, I chose `FormsTest.CanHaveModelLevelValidationErrors`)

However at runtime the app doesn't start, as it hits these errors which appear in the browser console:

```
MONO_WASM [0xdbdfc-main]: Error in bindings_init Can't find method System.Runtime.InteropServices.JavaScript.JavaScriptExports.InstallMainSynchronizationContext
xt @ dotnet.runtime.9.0.0-alpha.1.24063.6.a0dyicyyig.js:3
Ad @ dotnet.runtime.9.0.0-alpha.1.24063.6.a0dyicyyig.js:3
(anonymous) @ dotnet.runtime.9.0.0-alpha.1.24063.6.a0dyicyyig.js:3
dotnet.runtime.9.0.0-alpha.1.24063.6.a0dyicyyig.js:3

MONO_WASM [0xdbdfc-main]: onRuntimeInitializedAsync() failed Can't find method System.Runtime.InteropServices.JavaScript.JavaScriptExports.InstallMainSynchronizationContext
```

Are there some additional steps needed to enable the multithreaded runtime properly? Do you know why it would be unable to find these methods?

**Comment by SteveSandersonMS** [comment]
> But I can add extra try/catch layer to WebAssemblyDispatcher and forward it to UnhandledExceptionEventHandler
Should I do that, just to be on the safe side ? @SteveSandersonMS

If we don't know of a specific reason why it would make a difference, then TBH I'd prefer not to add extra logic for that. If we need to tweak some low-level error handling behavior later then we can do so.

**Comment by SteveSandersonMS** [comment]
> Maybe you need clean/rebuild the test app ?

I'll try. But if that fixes it, wouldn't it mean there's a framework/SDK bug? Developers should only have to run the "build" gesture to get an up-to-date output.

**Comment by javiercn** [comment]
> I'll try. But if that fixes it, wouldn't it mean there's a framework/SDK bug? Developers should only have to run the "build" gesture to get an up-to-date output.

If you are using 17.9.x beware of VS accelerated builds might be getting in the way.

**Comment by SteveSandersonMS** [comment]
Update: yes, removing `bin` and `obj` did fix it. I don't know whether VS Accelerated Build is involved in causing this. Wasn't it disabled at the SDK level for WebAssembly projects?

**Comment by javiercn** [comment]
@SteveSandersonMS yes, but I did that like last week, it probably hasn't reached here yet.

**Comment by pavelsavara** [comment]
I'm glad you tested this @SteveSandersonMS, thank you.

>    `SignalRClientTest` all fail. Unsure why - it just seems not to get messages back from the server. Should SignalR Client do something differently to work with the MT runtime?

I expect this to fix or improve with https://github.com/dotnet/runtime/pull/96618
I also created https://github.com/dotnet/runtime/issues/97085 for us to cover it with integration test.
By design, there should not be anything special in Blazor or user code for that. Let's keep eye on this.

>    `ThreadingAppTest.CounterPageCanUseThreads` fails for me locally (Expected: Not "Current count: 0", Actual:   "Current count: 0"). Maybe you already fixed it and I didn't get the latest code yet.

Yeah, I merged your suggestion from GH and only then added the button to trigger it in next commit.

>     * `ComponentRenderingTest.CanDispatchAsyncWorkToSyncContext` fails:
>       * Expected: First Second Third Fourth Fifth
>       * Actual:   First Third Second Fourth Fifth

Synchronous dispatch of `RendererSynchronizationContext` is meant to be  just perf optimization, right ?
With behavioral consequences.

Making assumptions on if you are or are not on the right thread when you `InvokeAsync` in user code would be bad practice, I think. 

Also in MT, you can't know if any other thread is making the queue busy at any time (X).

But I can imagine there are existing code-bases in the wild which work this way and it may bite them.

>    Technically I suppose we could check if the UI thread is idle, and if so, block the caller until the callback yields. But that's really complicated and it's unclear why we'd want to offer this guarantee.

That would have to be `SynchronizationContext.Send` instead of `Post`. 
And how to detect it's idle ?
For the UI thread if could mean multiple things, because there are multiple queues of work.
Even `JSSynchronizationContext` queue could have items/jobs unrelated to Blazor in it.

A) If we wanted to check that `JSSynchronizationContext` queue of work is empty, we would have to have some API for it.
B) We could also keep track of pending item count on the new `WebAssemblyDispatcher`. It seems easy to do.


>  So in summary I suspect the difference in behavior for this particular test is by design. Do you agree?

I like consistency, which would mean B)

But I don't like the sync dispatch assumption especially because (X). That said I agree and prefer
**C) we just fix the test.**

@javiercn what do you think ?

I would like to note, that this PR is probably not the last bit.
I will be experimenting with way how to offload as many jobs to threadpool from the UI thread.
**UI thread needs to stay idle** for [reasons](https://github.com/dotnet/designs/pull/301).

There are 2 possible ways how I could do it.
1) light-weight way. Hoping that it will be enough to fend off any deadlocks. 
   - Blazor change in which we offload all UI events like onClick etc to thread pool.
   - Maybe something with continuations from HTTP/WS network events. Run continuations in the TP.
2) the deputy design, which will completely prohibit you from running your main managed thread in the UI thread.
   - this will have broader architectural impact and also perf impact

How this is relevant: 
- there will be almost always cross-thread dispatch in `WebAssemblyDispatcher` with async processing by UI thread.
- it will make assumptions about which thread you are running on even more risky.

**Comment by pavelsavara** [comment]
> B) We could also keep track of pending item count on the new `WebAssemblyDispatcher`. It seems easy to do.

We would have to also prevent other threads from posting jobs in the meantime, as a race condition.

**Comment by SteveSandersonMS** [comment]
Cool, thanks for your feedback.

> [About SignalR Client] I expect this to fix or improve with https://github.com/dotnet/runtime/pull/96618

Great. I'll ignore this aspect then, since it's not Blazor specific, and we will assume the runtime will deal with whatever's necessary to make SignalR Client continue working.

> But I don't like the sync dispatch assumption especially because (X). That said I agree and prefer
C) we just fix the test.

Totally fine with me. We don't actually have to change the test because it's not going to run on the MT runtime. I only made a local change to enable a one-time run, but there's no plan to extend the CI run to do all the E2E tests on both single-threaded and multithreaded runtimes.

I agree overall that the synchronous-dispatch-if-idle behavior is best regarded as a perf optimization, not a guaranteed behavior. It totally makes sense for the MT runtime *not* to do that, because it would be so much more complicated for it.

**Review by SteveSandersonMS — APPROVED** [review]
Excellent work! Thanks for being so thorough with the details.

File: src/Components/Components/src/RenderTree/Renderer.cs [hunk 13]
```diff
@@ -1102,17 +1103,35 @@ private void HandleExceptionViaErrorBoundary(Exception error, ComponentState? er
     /// <param name="disposing"><see langword="true"/> if this method is being invoked by <see cref="IDisposable.Dispose"/>, otherwise <see langword="false"/>.</param>
     protected virtual void Dispose(bool disposing)
     {
+        lock (_lockObject)
+        {
+            if (_rendererIsDisposed)
+            {
+                return;
+            }
+        }
```
Comment (javiercn) [inline src/Components/Components/src/RenderTree/Renderer.cs:1112]: Why do we need this lock here. The renderer should always run inside the sync context. Is there anything failing otherwise?

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: Good point. This dispose method already deals with detecting whether or not we're on the sync context and dispatching to it if not. So it looks like the `if (_rendererIsDisposed)` check could simply be moved into that region, e.g., just before we assign `_rendererIsDisposed = true;` below.

Comment (pavelsavara) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: It do extra closure allocation and cross-thread dispatch even if the object was already disposed. Or if it was disposed from multiple threads at the same time. And it would become asynchronous.

The synchronous `done.Wait();` is way to deadlock. Especially ugly if this happens on finalizer thread or UI thread.

So quitting synchronously as soon as possible is preferable to saving one lock.

You have unit test which is testing this path on CoreCLR 😲

Comment (javiercn) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: Nobody dispatches the renderer, we own it.

Comment (javiercn) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: > It would do extra closure allocation and cross-thread dispatch even if the object was already disposed.

I don't think we care about the allocation here.

> You have unit test which is testing this path on CoreCLR 😲

I think this is likely a vestige from before the DI container implemented async disposal. AFAIK, (and @SteveSandersonMS can correct me) no code should be calling Dispose on the renderer.

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: > Nobody disposes the renderer, we own it. Nobody else but the framework can get a hold to it.

While that's often the case, it's not always the case. We also have `StaticHtmlRenderer`/`HtmlRenderer` that are intended for use directly from apps/libraries, plus people are always free to just subclass `Renderer` and use it in whatever way they want.

Comment (pavelsavara) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: `DisposeCallsComponentDisposeOnSyncContext` does `renderer.Dispose()` and it's running on CoreCLR threadpool, I think. I had trouble with it.

Comment (pavelsavara) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: > > It would do extra closure allocation and cross-thread dispatch even if the object was already disposed.
> 
> I don't think we care about the allocation here.

Okay, the asynchrony was the main point.

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: Perhaps it would be worth adding a 1-sentence comment to the code indicating why we're going to the trouble of locking here when there's no need to do that in other places.

Comment (pavelsavara) [reply src/Components/Components/src/RenderTree/Renderer.cs:1112]: If we are confident this should be executed on sync context, we can make it throw in `if (!Dispatcher.CheckAccess())` instead of the dispatch.
