### PR TITLE
Fix nullref when getting struct from feature collection and it isn't present

### LINKED ISSUE #46939: FeatureCollection can throw NRE with structs
This code is not supposed to throw an exception but return `null`. However, when the type is a struct then it will throw an NRE.

https://github.com/dotnet/aspnetcore/blob/6647d80ab886b8616e5b34812853e00358c93ce5/src/Extensions/Features/src/FeatureCollection.cs#L118-L121

The compiler calls [UnBox](https://source.dot.net/#System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs,525) which shouldn't be invoked with a `null` object.

Should the type have the `class` constraint? 
Should this case be handled? 
An analyzer limitation?

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/46939

I believe `if (typeof(TFeature).IsValueType)` is intrinsic which should mean the JIT will optimize this like crazy and be a noop in the common class case. Did a quick microbenchmark to check and it showed no difference.

### CODE REVIEW

File: src/Extensions/Features/src/FeatureCollection.cs [hunk 1]
```diff
@@ -117,6 +117,15 @@ IEnumerator IEnumerable.GetEnumerator()
     /// <inheritdoc />
     public TFeature? Get<TFeature>()
     {
+        if (typeof(TFeature).IsValueType)
+        {
+            var feature = this[typeof(TFeature)];
+            if (feature is null && Nullable.GetUnderlyingType(typeof(TFeature)) == null)
+            {
+                throw new InvalidOperationException();
```
Comment (amcasey) [inline src/Extensions/Features/src/FeatureCollection.cs:125]: `KeyNotFoundException`?

Comment (amcasey) [reply src/Extensions/Features/src/FeatureCollection.cs:125]: Either that or an error message.

File: src/Extensions/Features/test/FeatureCollectionTests.cs [hunk 2]
```diff
@@ -44,4 +45,61 @@ public void SetNullValueRemoves()
...
+    }
+
+    [Fact]
+    public void GetNullableStructFeatureWhenSetWithNonNullableStruct()
+    {
+        var interfaces = new FeatureCollection();
+        var value = 20;
+        interfaces.Set(value);
+
+        Assert.Null(interfaces.Get<int?>());
```
Comment (amcasey) [inline src/Extensions/Features/test/FeatureCollectionTests.cs:83]: Feels a little weird that `int` and `int?` are stored separately, but I assume it doesn't matter in practice.

File: src/Extensions/Features/src/FeatureCollection.cs [hunk 3]
```diff
@@ -117,6 +117,15 @@ IEnumerator IEnumerable.GetEnumerator()
     /// <inheritdoc />
     public TFeature? Get<TFeature>()
     {
+        if (typeof(TFeature).IsValueType)
+        {
+            var feature = this[typeof(TFeature)];
+            if (feature is null && Nullable.GetUnderlyingType(typeof(TFeature)) == null)
```
[the remark this answers is not in the document]
Comment (BrennanConroy) [reply src/Extensions/Features/src/FeatureCollection.cs:123]: 😆 `is null`

**Comment by JamesNK** [comment]
Random thought, what happens if someone asks for a struct, but the struct is nullable?

```cs
var i = context.Features.Get<int?>();
```
Is that saying:
1. Give me the type registered as `int?`, but if it isn't registered then error. Or,
2. Give me the type registered as `int`, but if it isn't registered then return `int?` with a value of null.

I'm guessing 1 is what we have at the moment and what we probably want.

**Comment by JamesNK** [comment]
```cs
var isStructRegistered = context.Features[typeof(int)] is not null;
```
For checking if a struct value is present, I think the code above works.

File: src/Extensions/Features/test/FeatureCollectionTests.cs (hunk 2 above)
Comment (JamesNK) [reply src/Extensions/Features/test/FeatureCollectionTests.cs:83]: The key is the type in the feature collection.

We could unwrap `Nullable<T>` on get/set, but no one has asked for it, and it feels like something that is a little too clever that will cause unanticipated problems later.

**Comment by BrennanConroy** [comment]
> Give me the type registered as int?, but if it isn't registered then error

Almost, it returns null if it isn't registered because we can return a null struct then. It only errors if you use a non-nullable struct and it's not registered.

> var isStructRegistered = context.Features[typeof(int)] is not null;
For checking if a struct value is present, I think the code above works.

I don't understand what you're trying to say.

**Comment by JamesNK** [comment]
I thinking out loud if there is a way for someone to check if a struct feature is registered. The usual pattern of `context.Feature.Get<IMyFeature>() is not null` won't work. They need to use the `Type` indexer. It returns the feature typed as an object, but it was probably already typed as an object when stored by the feature collection.

**Review by captainsafia — COMMENTED** [review]
LGTM although I'm not a SME.

@JamesNK's recommendation of using `context.Features[typeof(Foo)]` to check if a feature is registered makes sense.

Also, this would required a breaking change notice for the new behavior, yes?

File: src/Extensions/Features/src/FeatureCollection.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/Extensions/Features/src/FeatureCollection.cs]: Error message added, and incorporated James' musings into the message.

File: src/Extensions/Features/src/FeatureCollection.cs [hunk 4]
```diff
@@ -117,6 +117,16 @@ IEnumerator IEnumerable.GetEnumerator()
     /// <inheritdoc />
     public TFeature? Get<TFeature>()
     {
+        if (typeof(TFeature).IsValueType)
+        {
+            var feature = this[typeof(TFeature)];
+            if (feature is null && Nullable.GetUnderlyingType(typeof(TFeature)) is null)
+            {
+                throw new InvalidOperationException($"{typeof(TFeature).FullName} does not exist in the feature collection " +
+                $"and because it is a struct we can't return null. Use 'featureCollection[typeof({typeof(TFeature).FullName})] is not null' to check if it exists.");
```
Comment (JamesNK) [inline src/Extensions/Features/src/FeatureCollection.cs:126]:
```suggestion
                throw new InvalidOperationException(
                    $"{typeof(TFeature).FullName} does not exist in the feature collection " +
                    $"and because it is a struct the method can't return null. Use 'featureCollection[typeof({typeof(TFeature).FullName})] is not null' to check if the feature exists.");
```

File: src/Extensions/Features/test/FeatureCollectionTests.cs [hunk 5]
```diff
@@ -44,4 +45,62 @@ public void SetNullValueRemoves()
...
     }
+
+    [Fact]
+    public void GetMissingStructFeatureThrows()
+    {
+        var interfaces = new FeatureCollection();
+
+        // Regression test: Used to throw NullReferenceException because it tried to unbox a null object to a struct
+        var ex = Assert.Throws<InvalidOperationException>(() => interfaces.Get<int>());
+        Assert.Equal("System.Int32 does not exist in the feature collection and because it is a struct we can't return null. Use 'featureCollection[typeof(System.Int32)] is not null' to check if it exists.", ex.Message);
```
Comment (JamesNK) [inline src/Extensions/Features/test/FeatureCollectionTests.cs:56]:
```suggestion
        Assert.Equal("System.Int32 does not exist in the feature collection and because it is a struct the method can't return null. Use 'featureCollection[typeof(System.Int32)] is not null' to check if the feature exists.", ex.Message);
```

**Review by JamesNK — APPROVED** [review]

File: src/Extensions/Features/src/FeatureCollection.cs (hunk 4 above)
Comment (JamesNK) [reply src/Extensions/Features/src/FeatureCollection.cs:126]: "we can't return null" in the exception is unusual. Changed it to "the method can't return null"
