### PR TITLE
[Blazor] Enables the client to initiate blazor server-side renders

### LINKED ISSUE #12795: [Blazor] Multiple entry-point components in MVC/RazorPages apps does not work
## Describe the bug
*This issue is produced from the discussion in #12630*

Currently in preview-7 you can embed Blazor components in an MVC/RazorPages app by using `endpoints.MapBlazorHub();` and `@(await Html.RenderComponentAsync<Component1>())`.

However with statefull prerendering being removed in #12630, you will have to use the explicit mapping of components, like `endpoints.MapBlazorHub<Counter>("counter");`.

 That would be ok, except that when you add multiple component registrations, the initialization code in `blazor.server.js` throws exceptions because it is trying to find **all** of the registered components in the current page/view.

## How to reproduce
Consider the following scenario:

1. Create a new mvc app
2. Create 2 blazor components: `Component1` and `Component2`
3. Go to **/Home/Index.cshtml** and add the following:
```xml
<component1>@(await Html.RenderStaticComponentAsync<Component1>())</component1>
```
4. Go to **/Home/Privacy.cshtml** and add the following:
```xml
<component2>@(await Html.RenderStaticComponentAsync<Component2>())</component1>
```
5. Add the blazor requirements in _Layout.cshtml:
```html
<head>
<!-- code ommited -->
   <base href="~/" />
<!-- code ommited -->
</head>
<body>
<!-- code ommited -->
   <script src="_framework/blazor.server.js"></script>
</body>
```
6. Add the following to `ConfigureServices` in `Startup.cs`
`services.AddServerSideBlazor();`
7. And finally, add component mapping in `Configure`
```cs
 endpoints.MapBlazorHub<Component1>("component1")
                         .AddComponent(typeof(Component2), "component2");
```

If you try to navigate to /Home/Index or /Home/Privacy you will see the following errors in the console:

**Home.cshtml**
image

**Privacy.cshtml**
image

If you change the hub registration to 
```cs
endpoints.MapBlazorHub();
```
AND you change the components' rendering to
```
@(await Html.RenderComponentAsync<Component1>())
@(await Html.RenderComponentAsync<Component2>())
```

Then everything works fine (in preview-7). However this is going away, according to #12630
This fix is essential to support existing MVC and Razor Pages projects.

**PS**: A similar error occurs if you try to do the same in Client-Side blazor (wasm), which I have already opened an issue for in #12061, (although it got closed)

### PR DESCRIPTION
**Pull request by javiercn**
* Remove the need to register components.
* Removes all overloads of MapComponentHub that takes a component type.
* Adds a RenderMode to define how to render a component.
  * HTML: Renders the component as static HTML.
  * Server: Renders a placeholder for the component so that the client can start a blazor application.
  * ServerPrerender: Prerenders the component and includes a marker before an after so that a blazor application can be started.

Fixes #12795

### CODE REVIEW

File: src/Components/Server/src/ComponentHub.cs [hunk 1]
```diff
@@ -72,7 +72,7 @@ public override Task OnDisconnectedAsync(Exception exception)
             return _circuitRegistry.DisconnectAsync(circuitHost, Context.ConnectionId);
         }
 
-        public async ValueTask<string> StartCircuit(string baseUri, string uri)
+        public async ValueTask<string> StartCircuit(string baseUri, string uri, string serializedDescriptors)
```
Comment (javiercn) [inline src/Components/Server/src/ComponentHub.cs]: We can change this in the future to take just the first component and add an additional hub method `RenderComponent` where we render components after the first one. That will better support scenarios with arguments.

File: src/Components/Server/src/ComponentHub.cs [hunk 2]
```diff
@@ -136,7 +128,7 @@ public async ValueTask<string> StartCircuit(string baseUri, string uri)
                 // If the circuit fails to initialize synchronously we can notify the client immediately
                 // and shut down the connection.
                 Log.CircuitInitializationFailed(_logger, ex);
-                await NotifyClientError(Clients.Caller, "The circuit failed to initialize.");
+                await NotifyClientError(Clients.Caller, GetClientErrorMessage(ex, "The circuit failed to initialize."));
```
Comment (javiercn) [inline src/Components/Server/src/ComponentHub.cs]: We weren't respecting error details on this exception.

File: src/Components/Server/ref/Microsoft.AspNetCore.Components.Server.netcoreapp3.0.cs [hunk 3]
```diff
@@ -8,20 +8,12 @@ public sealed partial class ComponentEndpointConventionBuilder : Microsoft.AspNe
...
+        public static Microsoft.AspNetCore.Builder.ComponentEndpointConventionBuilder MapBlazorHub(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints) { throw null; }
+        public static Microsoft.AspNetCore.Builder.ComponentEndpointConventionBuilder MapBlazorHub(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, System.Action<Microsoft.AspNetCore.Http.Connections.HttpConnectionDispatcherOptions> configureOptions) { throw null; }
+        public static Microsoft.AspNetCore.Builder.ComponentEndpointConventionBuilder MapBlazorHub(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, string path) { throw null; }
+        public static Microsoft.AspNetCore.Builder.ComponentEndpointConventionBuilder MapBlazorHub(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, string path, System.Action<Microsoft.AspNetCore.Http.Connections.HttpConnectionDispatcherOptions> configureOptions) { throw null; }
```
Comment (rynowak) [inline src/Components/Server/ref/Microsoft.AspNetCore.Components.Server.netcoreapp3.0.cs]: 👏 👏 👏 👏 👏 👏 👏 👏

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs [hunk 4]
```diff
@@ -5,31 +5,33 @@
...
-using Microsoft.AspNetCore.Http;
 using Microsoft.Extensions.DependencyInjection;
 using Microsoft.Extensions.Logging;
 using Microsoft.Extensions.Options;
 using Microsoft.JSInterop;
 
 namespace Microsoft.AspNetCore.Components.Server.Circuits
 {
-    internal class DefaultCircuitFactory : CircuitFactory
+    internal class DefaultCircuitFactory
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: rename this to circuit factory if you're removing the base class 😆

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs [hunk 5]
```diff
@@ -5,31 +5,33 @@
...
     {
         private readonly IServiceScopeFactory _scopeFactory;
         private readonly ILoggerFactory _loggerFactory;
         private readonly CircuitIdFactory _circuitIdFactory;
         private readonly CircuitOptions _options;
         private readonly ILogger _logger;
 
+        public ComponentDescriptorSerializer DescriptorSerializer { get; }
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: This is bizzare. Is this a service? What do we get out of makign this a public property of part of the implementation?

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs [hunk 6]
```diff
@@ -38,16 +40,17 @@ internal class DefaultCircuitFactory : CircuitFactory
...
+            string serializedComponentRecords,
             CircuitClientProxy client,
             string baseUri,
             string uri,
             ClaimsPrincipal user)
         {
-            // We do as much intialization as possible eagerly in this method, which makes the error handling
-            // story much simpler. If we throw from here, it's handled inside the initial hub method.
-            var components = ResolveComponentMetadata(httpContext);
+            if (!DescriptorSerializer.TryDeserializeComponentDescriptorCollection(serializedComponentRecords, out var components))
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: Does it make sense to do this in the caller? IIRC this method has one caller. We added a new dependency here just so we could throw an exception from this method.

This seems like it would gel really well with the [other validations](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/ComponentHub.cs#L90).

I also like the current invariant that this method doesn't fail, and doesn't have input that needs validation.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 7]
```diff
@@ -64,10 +61,7 @@ public Task AddComponentAsync(Type componentType, string domElementSelector)
             var component = InstantiateComponent(componentType);
             var componentId = AssignRootComponentId(component);
 
-            var attachComponentTask = _jsRuntime.InvokeAsync<object>(
-                "Blazor._internal.attachRootComponentToElement",
-                domElementSelector,
-                componentId);
+            var attachComponentTask = _client.SendAsync("JS.AttachComponent", componentId, domElementSelector);
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: noice. This seems like an improvement.

File: src/Components/Server/src/ComponentHub.cs (hunk 1 above)
Comment (rynowak) [reply src/Components/Server/src/ComponentHub.cs]: Is the idea right now that you run into a physical limit based on the size of this message (24kb I think?). Do you know how many components it would take to reach that? obvi depends on the length of names, but can you estimate something reasonable and try this?

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (rynowak) [reply src/Components/Server/src/ComponentHub.cs]: We weren't doing that because there's no user code that runs inside this try/catch block 😆  

After the comment at L104, it was expected that everything would succeed unless something is seriously wrong.

It was intentional before your changes, and based on my other feedback, I'm not sure it needs to change.

File: src/Components/Server/src/ComponentHub.cs [hunk 8]
```diff
@@ -259,11 +251,21 @@ private void SetCircuit(CircuitHost circuitHost)
 
         private static Task NotifyClientError(IClientProxy client, string error) => client.SendAsync("JS.Error", error);
 
-        private static class Log
+        private string GetClientErrorMessage(Exception exception, string additionalInformation = null)
```
Comment (rynowak) [inline src/Components/Server/src/ComponentHub.cs]: Does this duplicate something we have elsewhere?

As a detail, we don't currently respond with exception details anywhere in this class, because the catch blocks here *never* catch exceptions from user code (LMK if I'm wrong) 😀

File: src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj [hunk 9]
```diff
@@ -65,6 +65,14 @@
     <Compile Include="$(MessagePackRoot)SequencePool.cs" LinkBase="BlazorPack\MessagePack" />
     <Compile Include="$(MessagePackRoot)SequenceReader.cs" LinkBase="BlazorPack\MessagePack" />
     <Compile Include="$(MessagePackRoot)SequenceReaderExtensions.cs" LinkBase="BlazorPack\MessagePack" />
+
+    <!-- Shared descriptor infrastructure with MVC -->
+    <Compile Include="$(RepoRoot)src\Shared\Components\ComponentDescriptor.cs" LinkBase="Descriptors" />
+    <Compile Include="$(RepoRoot)src\Shared\Components\ComponentDescriptorInstance.cs" LinkBase="Descriptors" />
+    <Compile Include="$(RepoRoot)src\Shared\Components\ComponentDescriptorSerializer.cs" LinkBase="Descriptors" />
+    <Compile Include="$(RepoRoot)src\Shared\Components\ComponentDescriptorSerializer.Deserialize.cs" LinkBase="Descriptors" />
+    <Compile Include="$(RepoRoot)src\Shared\Components\ComponentMarker.cs" LinkBase="Descriptors" />
```
Comment (rynowak) [inline src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj]: > LinkBase="Descriptors"

Do we need this? We try to have folders match namespaces.

File: src/Components/Web.JS/src/Boot.Server.ts [hunk 10]
```diff
@@ -27,16 +28,23 @@ async function boot(userOptions?: Partial<BlazorOptions>): Promise<void> {
   options.reconnectionHandler = options.reconnectionHandler || window['Blazor'].defaultReconnectionHandler;
   logger.log(LogLevel.Information, 'Starting up blazor server-side application.');
 
-  const initialConnection = await initializeConnection(options, logger);
-  const circuit = await startCircuit(initialConnection);
+  const components = discoverComponents(document);
+  const circuit = new CircuitDescriptor(components);
+
+  const initialConnection = await initializeConnection(options, logger, circuit);
```
Comment (rynowak) [inline src/Components/Web.JS/src/Boot.Server.ts]: It seems a little weird to me that we pass in the circuit here so that we can call methods on it. I don't have much of a better idea than defining a *callbacks* object to pass in, so I guess I'll leave it up to. 

This factoring led me to believe that the circuit had some role in opening the connection, and it doesn't.

File: src/Components/Web.JS/src/Boot.Server.ts [hunk 11]
```diff
@@ -27,16 +28,23 @@ async function boot(userOptions?: Partial<BlazorOptions>): Promise<void> {
...
+  const circuitStarted = await circuit.startCircuit(initialConnection);
+  if (!circuitStarted) {
+    logger.log(LogLevel.Information, 'Failed to start the circuit.');
```
Comment (rynowak) [inline src/Components/Web.JS/src/Boot.Server.ts]: Is information right for this? For instance we have test infrastructure that will bail if the browser logs errors. It would be nice if this check could cause tests to fail-fast.

File: src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts [hunk 12]
```diff
@@ -1,22 +1,288 @@
...
+      this.currentElement = this.childNodes[this.currentIndex];
+      return true;
+    } else {
+      this.currentElement = undefined;
+      return false;
+    }
+  }
+}
+
+
```
Comment (rynowak) [inline src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts]: I'm not really reviewing this part in detail because I'm betting it's really similar to the code we had in preveiew7. LMK if this needs a thorough look.

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts [hunk 13]
```diff
@@ -55,8 +55,10 @@ export function toLogicalRootCommentElement(start: Comment, end: Comment): Logic
   const children = getLogicalChildrenArray(parentLogicalElement);
   Array.from(parent.childNodes).forEach(n => children.push(n as unknown as LogicalElement));
   start[logicalParentPropname] = parentLogicalElement;
-  start[logicalEndSiblingPropname] = end;
-  toLogicalElement(end, /* allowExistingcontents */ true);
+  if (end) {
```
Comment (rynowak) [inline src/Components/Web.JS/src/Rendering/LogicalElements.ts]: What does this change do? Does this need a comment explaining when it occurs?

File: src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml [hunk 14]
```diff
@@ -12,7 +12,7 @@
     <link href="css/site.css" rel="stylesheet" />
 </head>
 <body>
-    <app>@(await Html.RenderComponentAsync<App>(new { Name = "Guest" }))</app>
+    <app>@(await Html.RenderComponentAsync<App>(new { Name = "Guest" }, RenderMode.Server))</app>
```
Comment (rynowak) [inline src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml]: Per our discussion, I would expect this to throw because it's non-static and it takes arguments.

Comment (rynowak) [reply src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml]: Per our dicussion, I would expect the arguments to be the second argument. Yeah, that's meta.

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 15]
```diff
@@ -37,30 +39,94 @@ public static class HtmlHelperComponentExtensions
...
         {
             if (htmlHelper == null)
             {
                 throw new ArgumentNullException(nameof(htmlHelper));
             }
 
-            var httpContext = htmlHelper.ViewContext.HttpContext;
-            var serviceProvider = httpContext.RequestServices;
-            var prerenderer = serviceProvider.GetRequiredService<StaticComponentRenderer>();
+            if (renderMode == default)
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: Per our discussion, I would expect this to not be the case? 😁

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 16]
```diff
@@ -37,30 +39,94 @@ public static class HtmlHelperComponentExtensions
...
                 ParameterView.FromDictionary(HtmlHelper.ObjectToDictionary(parameters));
 
+            var context = htmlHelper.ViewContext.HttpContext;
+            switch (renderMode)
+            {
+                case RenderMode.Server:
+                    return NonPrerenderedBlazorComponent(context, typeof(TComponent), parametersCollection);
+                case RenderMode.ServerPrerendered:
+                    return await PrerenderedBlazorComponentAsync(context, typeof(TComponent), parametersCollection);
+                case RenderMode.Html:
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: I'd really prefer this to be called static. Two of these options output html.

File: src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs [hunk 17]
```diff
@@ -1,26 +1,30 @@
...
-        }
+            : this(Array.Empty<string>(), componentResult, Array.Empty<string>()) { }
+
+        public ComponentHtmlContent(IEnumerable<string> preamble, IEnumerable<string> componentResult, IEnumerable<string> epilogue) =>
+            (_preamble, _componentResult, _epilogue) = (preamble, componentResult, epilogue);
 
         public void WriteTo(TextWriter writer, HtmlEncoder encoder)
         {
-            foreach (var element in _componentResult)
+            foreach (var element in _preamble.Concat(_componentResult).Concat(_epilogue))
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs]: nice.

File: src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs [hunk 18]
```diff
@@ -1,26 +1,30 @@
...
+        private readonly IEnumerable<string> _epilogue;
 
         public ComponentHtmlContent(IEnumerable<string> componentResult)
-        {
-            _componentResult = componentResult;
-        }
+            : this(Array.Empty<string>(), componentResult, Array.Empty<string>()) { }
+
+        public ComponentHtmlContent(IEnumerable<string> preamble, IEnumerable<string> componentResult, IEnumerable<string> epilogue) =>
+            (_preamble, _componentResult, _epilogue) = (preamble, componentResult, epilogue);
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs]: why is this style better than braces and statements? Does it generate the same code?

I'm seeing this show up more and more as you touch things, and I'm not sure it's without tradeoffs.

File: src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj [hunk 19]
```diff
@@ -26,4 +26,11 @@ Microsoft.AspNetCore.Mvc.ViewComponent</Description>
     <Reference Include="Microsoft.AspNetCore.Components.Authorization" />
   </ItemGroup>
 
+  <ItemGroup>
+    <Compile Include="..\..\..\Shared\Components\ComponentDescriptorSerializer.cs" />
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj]: I think we some msbuild variables that point to this? Like `SharedRoot`?

File: src/Mvc/Mvc.ViewFeatures/src/RenderMode.cs [hunk 20]
```diff
@@ -0,0 +1,32 @@
...
+    /// </remarks>
+    public enum RenderMode
+    {
+        /// <summary>
+        /// Renders the component into static HTML.
+        /// </summary>
+        Html = 1,
+
+        /// <summary>
+        /// Renders a marker for a Blazor server-side application.
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/RenderMode.cs]: I think it's worth elaborating here that this just renders the marker, and doesn't include any of the component's output.

File: src/Shared/Components/ComponentDescriptorInstance.cs [hunk 21]
```diff
@@ -0,0 +1,30 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+namespace Microsoft.AspNetCore.Components
+{
+    // The DTO that we data-protect and include into any
+    // generated component marker and that allows the client
+    // to bootstrap a blazor server-side application.
+    internal struct ComponentDescriptorInstance
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorInstance.cs]: `ComponentDescriptorInstance` -> `ComponentMarker`?

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 22]
```diff
@@ -0,0 +1,215 @@
...
+using System.Text.Json;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components
+{
+    // ComponentDescriptorSerializer is an abstraction shared by both MVC and Blazor
+    // This file holds the definition used by Blazor to deserialize descriptors.
+    internal partial class ComponentDescriptorSerializer
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Rename the file to match please :)

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 23]
```diff
@@ -0,0 +1,215 @@
...
+using System.Runtime.InteropServices;
+using System.Security.Cryptography;
+using System.Text.Json;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components
+{
+    // ComponentDescriptorSerializer is an abstraction shared by both MVC and Blazor
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: nit: not an abstraction, it just a thing.

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 24]
```diff
@@ -0,0 +1,215 @@
...
+            RootComponentTypeCache rootComponentTypeCache)
+        {
+            DataProtector = dataProtectionProvider.CreateProtector(DataProtectionProviderPurpose);
+            Logger = logger;
+            RootComponentTypeCache = rootComponentTypeCache;
+        }
+
+        public ILogger<ComponentDescriptorSerializer> Logger { get; }
+
+        public RootComponentTypeCache RootComponentTypeCache { get; }
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Do these really make sense as public properties of this class?

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 25]
```diff
@@ -0,0 +1,215 @@
...
+
+        public bool TryDeserializeComponentDescriptorCollection(string serializedComponentRecords, out List<ComponentDescriptor> descriptors)
+        {
+            var markers = JsonSerializer.Deserialize<IEnumerable<ComponentMarker>>(serializedComponentRecords, _jsonSerializationOptions);
+            descriptors = new List<ComponentDescriptor>();
+            int lastSequence = -1;
+
+            var previousInstance = new ComponentDescriptorInstance();
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: This is why I suggested a btter name for this class. Here we have `ComponentDescriptor` and `ComponentDiscriptorInstance` getting to know each other.

What about ParsedComponentMarker since ComponentMarker is taken?

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 26]
```diff
@@ -0,0 +1,215 @@
...
+                var (descriptor, instance) = DeserializeComponentDescriptor(marker);
+                if (descriptor == null)
+                {
+                    // We failed to deserialize the component descriptor for some reason.
+                    descriptors.Clear();
+                    return false;
+                }
+
+                // We force our client to send the descriptors in order so that we do minimal work.
+                if (lastSequence != -1 && lastSequence != instance.Sequence - 1)
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: I'd really like to understand if this is important, or even safe.

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 27]
```diff
@@ -0,0 +1,215 @@
...
+                    !CryptographicOperations.FixedTimeEquals(
+                        MemoryMarshal.AsBytes(previousInstance.InvocationId.AsSpan()),
+                        MemoryMarshal.AsBytes(instance.InvocationId.AsSpan())))
+                {
+                    Log.MismatchedInvocationId(Logger, previousInstance.InvocationId, instance.InvocationId);
+                    return false;
+                }
+
+                // As described below, we build a chain of descriptors to prevent being flooded by
+                // descriptors from a client not behaving properly.
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Well we can't be totally flooded right due to max message size? If that's the concern it seems like we could mitigate it in a few ways.

File: src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs [hunk 28]
```diff
@@ -0,0 +1,121 @@
...
+
+        public ComponentMarker SerializeInvocation(HttpContext context, Type type, bool prerendered)
+        {
+            var (sequence, descriptor) = CreateSerializedComponentDescriptor(context, type);
+            return prerendered ? ComponentMarker.Prerendered(sequence, descriptor) : ComponentMarker.NonPrerendered(sequence, descriptor);
+        }
+
+        private ComponentDescriptorInvocationSequence GetOrCreateInvocationIdentifier(HttpContext context)
+        {
+            if (!context.Items.TryGetValue(ComponentSequenceKey, out var sequence))
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs]: This is kinda unfortunate that we need to rely on `.Items` for this feature to work correctly no?

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 22 above)
Comment (rynowak) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: nevermind. I see what you did here 👍

File: src/Shared/Components/ComponentDescriptorSerializer.cs [hunk 29]
```diff
@@ -0,0 +1,66 @@
...
+            new JsonSerializerOptions
+            {
+                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
+                PropertyNameCaseInsensitive = true,
+                IgnoreNullValues = true
+            };
+
+        public IDataProtector DataProtector { get; }
+    }
+}
```
Comment (rynowak) [inline src/Shared/Components/ComponentDescriptorSerializer.cs]: FYI I'm not reviewing this code in super-detail r/n. I want to get real answers to some of the security-related requirements before digging in deep.

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: This was just me `ctrl+.` my way to victory. I'll make it a readonly field

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs [hunk 30]
```diff
@@ -38,16 +40,17 @@ internal class DefaultCircuitFactory : CircuitFactory
             _logger = _loggerFactory.CreateLogger<DefaultCircuitFactory>();
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: Is there a reason why we do all these nullchecks here? Can we simply get rid of them?

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: Ok, I've moved it out.

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: Ok, I'll revert it then and I'll add a comment here for reference.

File: src/Components/Server/src/ComponentHub.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: I checked and we only have a single try..catch. I removed the code supporting this from componenthub

File: src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj]: I removed these from here. Most of these things are in Microsoft.AspNetCore.Components (as I didn't want to add .Server because it's referenced by MVC too). I've removed the LinkBase

File: src/Components/Web.JS/src/Boot.Server.ts (hunk 10 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.ts]: i tried the callback approach before and it was cumbersome. This is a pragmatic balance I think.

File: src/Components/Web.JS/src/Boot.Server.ts (hunk 11 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.ts]: Switched to error

File: src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts (hunk 12 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts]: Yes. I changed the comment prefix from M.A.Components to simply Blazor and cleaned up a bit iterating through the comments (by using the componentcommentiterator) but otherwise it should be pretty similar. 

I also plan to cover this with JS tests. to validate things work.

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts (hunk 13 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: We didn't clean this up when we removed the prerendering support. This is only adding support for non-prerendered server components that only have a start comment tag (No end is necessary as they don't wrap any prerendered content)

File: src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml (hunk 14 above)
Comment (javiercn) [reply src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml]: Yes, I haven't made the tests work yet, so I just made whatever necessary for them to compile. I've added a check to throw if you pass arguments.

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: I removed it from here.

File: src/Components/Server/src/ComponentHub.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: The default message size is 32Kb, each component is about 500 bytes based on just looking at the length in the startup method, so you can render about 65 components without parameters. This size might be reduced a bit, but estimate that between 100 and 200 tops, and that's without parameters.

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts (hunk 13 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Added a comment.

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 15 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: got rid of this, now it throws on the switch

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 16 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: Renamed to static

File: src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs (hunk 18 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/Infrastructure/ComponentHtmlContent.cs]: It's more succinct and it makes it obvious that you are just bulk assigning the parameters to fields. I think its more idiomatic when used with small objects like this one. I normally use it for readonly structs/types and DTOs.

ILSpy decompiles it to just assignments.

This is the IL it produces if you are curious. As you can see there's no actual tuple involved here:
```
.method public hidebysig specialname rtspecialname 
        instance void  .ctor(class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> preamble,
                             class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> componentResult,
                             class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> epilogue) cil managed
{
  // Code size       35 (0x23)
  .maxstack  2
  .locals init (class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> V_0,
           class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> V_1,
           class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> V_2)
  IL_0000:  ldarg.0
  IL_0001:  call       instance void [System.Runtime]System.Object::.ctor()
  IL_0006:  nop
  IL_0007:  ldarg.1
  IL_0008:  stloc.0
  IL_0009:  ldarg.2
  IL_000a:  stloc.1
  IL_000b:  ldarg.3
  IL_000c:  stloc.2
  IL_000d:  ldarg.0
  IL_000e:  ldloc.0
  IL_000f:  stfld      class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentHtmlContent::_preamble
  IL_0014:  ldarg.0
  IL_0015:  ldloc.1
  IL_0016:  stfld      class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentHtmlContent::_componentResult
  IL_001b:  ldarg.0
  IL_001c:  ldloc.2
  IL_001d:  stfld      class [System.Runtime]System.Collections.Generic.IEnumerable`1<string> Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentHtmlContent::_epilogue
  IL_0022:  ret
} // end of method ComponentHtmlContent::.ctor
```

File: src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj (hunk 19 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj]: I switched this to use RepoRoot, SharedRoot is a thing of the past I believe. Arcade doesn't have that concept.

File: src/Shared/Components/ComponentDescriptorInstance.cs (hunk 21 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorInstance.cs]: I renamed this and all its friends to ServerComponent and ServerComponentSerializer

Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorInstance.cs]: image

I've also reduced the shared code just to the DTOs and shared settings
image

Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorInstance.cs]: In fact, I split the classes in two and renamed ServerComponentSerializer to ServerComponentSerializationSettings and it just contains the jsonoptions and the dataprotection purpose

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 23 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Removed the comment, this class has just become ServerComponentSerializationSettings

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 24 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Replaced them with private readonly fields. In general I go for property for these things because it doesn't matter (the class is already internal) and the IDE fights me with readonly fields as it adds a `this.` and doesn't prefix the fields with `_` which is annoying because I have to go and manually fix those things.

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 25 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: I renamed this and all its friends to ServerComponent and ServerComponentSerializer and so on.

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 26 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Having a sequence number allows the server to uniquely identify each rendered component. This prevents the client from simply sending the same descriptor multiple times to cause the server to render the component multiple times on a single connection. 

For example, if there was no component sequence, I could do as follows:
* Send a request to the main page to generate  a valid descriptor.
* Create an array with as many copies of that descriptor as can fit in 32K.
* Open a connection to the server.
* Send that payload descriptor to the server and force it to render as many components as there are in the array.

The sequence number prevents a client from doing that, as a client can only render as many descriptors as the server generated in the first place. To put it in different words, this prevents individual descriptor replay attacks.

If you were to trick the server into generating a large amount of components in the first place (by an application introduced bug), you could ask the server to render at most that number of components, but no more. We (Steve and I) think that that is a legitimate answer and that it's a bug in the app. It can happen if you are not careful and for example render a root component for each element in a list and don't establish a limit, but in practical terms we don't expect this to be a common case. (Specially based on the fact that you can't currently render parameters).

What we expect is that you tipically render a few components in different parts of a page and this mechanism automatically limits the number of components to what the server rendered. As a last resort/fallback mechanism you are going to be limited by the signalr message size, but that's a limit that can be lifted, so we want something smarter and more adjustable like this.

Less important, the sequence number also allows the server to bail early for invalid data. If you include a descriptor that can't be unprotected or is out of sequence we detect it as soon as possible without having to potentially parse and unprotect the entire list of descriptors.

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs [hunk 31]
```diff
@@ -0,0 +1,215 @@
...
+                    Log.OutOfSequenceDescriptor(Logger, lastSequence, instance.Sequence);
+                    descriptors.Clear();
+                    return false;
+                }
+
+                if (lastSequence != -1 &&
+                    !CryptographicOperations.FixedTimeEquals(
+                        MemoryMarshal.AsBytes(previousInstance.InvocationId.AsSpan()),
+                        MemoryMarshal.AsBytes(instance.InvocationId.AsSpan())))
+                {
```
Comment (javiercn) [inline src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: I believe we can actually perform a regular comparison here. This is all protected data not susceptible to user input, so at best, sending valid descriptors an attacker could identify that the payload in their descriptor is a prefix of the payload in the other descriptor, but given that they don't have control over the input (they don't know their InvocationId nor the one in the other descriptor and can't generate payloads) its in practical terms impossible for them to exploit that for anything

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 27 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Max message size is the worst case scenario, we can do way better than that, limiting the amount of rendered components to those generated as part of an HTTP response by the app. Which will be a way lower number, more predictable and app dependent, so the app decides on a per request basis how many components are acceptable to render. with MAX message size being the only limitation in the worst case scenario.

File: src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs (hunk 28 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs]: I can replace it with a scoped service. What is your concern about using .Items?

File: src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs [hunk 32]
```diff
@@ -0,0 +1,121 @@
...
+            }
+        }
+
+        private class ComponentDescriptorInvocationSequence
+        {
+            private static readonly RandomNumberGenerator _randomNumberGenerator = RandomNumberGenerator.Create();
+
+            public ComponentDescriptorInvocationSequence()
+            {
+                Span<byte> bytes = stackalloc byte[128];
```
Comment (javiercn) [inline src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs]: This actually needs to be 32 (256 bit)

File: src/Shared/Components/ComponentDescriptorSerializer.cs (hunk 29 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.cs]: I set up a meeting to go over this

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs [hunk 33]
```diff
@@ -0,0 +1,253 @@
...
+using System.Collections.Generic;
+using System.Runtime.InteropServices;
+using System.Security.Cryptography;
+using System.Text.Json;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components.Server
+{
+    // Shared settings for serializing and deserializing server components
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: remove this line

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs [hunk 34]
```diff
@@ -0,0 +1,253 @@
...
+    // * We ensure that a client can't just send an infinite amount of components to render.
+    // * We ensure that we do the minimal amount of work in the case of an invalid sequence of descriptors.
+    //
+    // For example:
+    // A client can't just send 100 component markers and force us to process them if the server didn't generate those 100 markers.
+    //  * If a marker is out of sequence we will fail early, so we process at most n-1 markers.
+    //  * If a marker has the right sequence but the invocation ID is different we will fail at that point. We know for sure that the
+    //    component wasn't render as part of the same response.
+    //  * If a marker can't be unprotected we will fail early. We know that the marker was tampered with and can't be trusted.
+    internal class ServerComponentDeserializer
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: I duped the comment here and in the deserializer because there's no good place to put it.

File: src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs [hunk 35]
```diff
@@ -175,6 +175,10 @@ internal static void AddViewServices(IServiceCollection services)
 
             services.TryAddSingleton<IJsonHelper, SystemTextJsonHelper>();
 
+            // Component services for Blazor server-side interop
+            // These are all shared sources located at /src/Shared/Components
+            services.TryAddSingleton<ServerComponentSerializer>();
```
Comment (javiercn) [inline src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs]: This comment is out of date

File: src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj [hunk 36]
```diff
@@ -1,11 +1,13 @@
...
-Microsoft.AspNetCore.Mvc.Controller
-Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute
-Microsoft.AspNetCore.Mvc.ViewComponent</Description>
+    <Description>
+      ASP.NET Core MVC view rendering features. Contains common types used in most MVC applications as well as view rendering features such as view engines, views, view components, and HTML helpers.
+      Commonly used types:
+      Microsoft.AspNetCore.Mvc.Controller
+      Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute
+      Microsoft.AspNetCore.Mvc.ViewComponent
+    </Description>
```
Comment (javiercn) [inline src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj]: This was just VS doing its thing. I'm not gonna fight it.

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs [hunk 37]
```diff
@@ -0,0 +1,162 @@
...
+using System.Collections.Generic;
+using System.Security.Cryptography;
+using System.Text.Json;
+using Microsoft.AspNetCore.Components;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.AspNetCore.Http;
+
+namespace Microsoft.AspNetCore.Mvc.ViewFeatures
+{
+    // Shared settings for serializing and deserializing server components
```
Comment (javiercn) [inline src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: nit: remove this line

File: src/Components/Server/src/ComponentHub.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: done

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: done

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: done

File: src/Components/Server/src/ComponentHub.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/Server/src/ComponentHub.cs]: removed

File: src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml (hunk 14 above)
Comment (javiercn) [reply src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml]: Updated to make the tests work.

File: src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj (hunk 19 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/Microsoft.AspNetCore.Mvc.ViewFeatures.csproj]: done

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 26 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: Discussed offline with @GrabYourPitchforks

**Comment by javiercn** [comment]
@rynowak 

:up: :date:

Addressed all the feedback. It's missing some tests that I'm going to add tomorrow morning, but other than that it should be in very good shape.

File: src/Components/Server/src/Circuits/CircuitFactory.cs [hunk 38]
```diff
@@ -1,18 +1,114 @@
...
+        public CircuitFactory(
+            IServiceScopeFactory scopeFactory,
+            ILoggerFactory loggerFactory,
+            CircuitIdFactory circuitIdFactory,
+            IOptions<CircuitOptions> options)
+        {
+            _scopeFactory = scopeFactory ?? throw new ArgumentNullException(nameof(scopeFactory));
+            _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
+            _circuitIdFactory = circuitIdFactory ?? throw new ArgumentNullException(nameof(circuitIdFactory));
+            _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitFactory.cs]: Suggest getting rid of this `?.` It's really easy to use options in tests.

File: src/Components/Server/src/Circuits/CircuitFactory.cs [hunk 39]
```diff
@@ -1,18 +1,114 @@
...
+            // Initialize per - circuit data that services need
+            (circuitHost.Services.GetRequiredService<ICircuitAccessor>() as DefaultCircuitAccessor).Circuit = circuitHost.Circuit;
+            circuitHost.SetCircuitUser(user);
+
+            return circuitHost;
+        }
+
+        private static class Log
+        {
+            private static readonly Action<ILogger, string, string, Exception> _createdConnectedCircuit =
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitFactory.cs]: Is this logging used?

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs [hunk 40]
```diff
@@ -0,0 +1,254 @@
...
+using System.Text.Json;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components.Server
+{
+    // Shared settings for serializing and deserializing server components
+    // **Component descriptor protocol**
+    // MVC serializes one or more components as comments in HTML.
+    // Each comment is in the form <!-- Blazor: <<Json>> -->
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: nitpick, include an example of the json... `{ type: ..., sequence:... }` and so on.

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs [hunk 41]
```diff
@@ -0,0 +1,254 @@
...
+        private readonly ServerComponentTypeCache _rootComponentTypeCache;
+
+        public ServerComponentDeserializer(
+            IDataProtectionProvider dataProtectionProvider,
+            ILogger<ServerComponentDeserializer> logger,
+            ServerComponentTypeCache rootComponentTypeCache)
+        {
+            _dataProtector = dataProtectionProvider
+                .CreateProtector(ServerComponentSerializationSettings.DataProtectionProviderPurpose)
+                .ToTimeLimitedDataProtector(); // We need the DP to be a TimeLimitedDP otherwise we can't unprotect the data.
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: comment doesn't make a super ton of sense. Maybe explain why we choose this in the first place?

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs [hunk 42]
```diff
@@ -0,0 +1,254 @@
...
+            catch (Exception e)
+            {
+                Log.FailedToUnprotectDescriptor(_logger, e);
+                return default;
+            }
+
+            ServerComponent descriptorInstance;
+            try
+            {
+                descriptorInstance = JsonSerializer.Deserialize<ServerComponent>(
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: Can we pick a better name than this? there's descriptor and descriptor instance again.

File: src/Components/Web.JS/src/Boot.Server.ts [hunk 43]
```diff
@@ -27,16 +28,28 @@ async function boot(userOptions?: Partial<BlazorOptions>): Promise<void> {
...
       // We can't reconnect after a failure, so exit early.
       return false;
     }
 
-    const reconnection = existingConnection || await initializeConnection(options, logger);
+    const reconnection = existingConnection || await initializeConnection(options, logger, circuit);
+    if (reconnection.state !== signalR.HubConnectionState.Connected) {
+      logger.log(LogLevel.Information, 'Reconnection attempt failed. Unable to connect to the server.');
+      return false;
+    }
```
Comment (rynowak) [inline src/Components/Web.JS/src/Boot.Server.ts]: This `if` block was removed by some changes that are pretty recent by @NTaylorMullen - signalR actually throws for you so this would never run.

File: src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs [hunk 44]
```diff
@@ -23,7 +23,7 @@ namespace Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests
 {
     public class ComponentHubReliabilityTest : IClassFixture<AspNetSiteServerFixture>, IDisposable
     {
-        private static readonly TimeSpan DefaultLatencyTimeout = TimeSpan.FromSeconds(Debugger.IsAttached ? 60 : 10);
+        private static readonly TimeSpan DefaultLatencyTimeout = TimeSpan.FromSeconds(Debugger.IsAttached ? 300 : 10);
```
Comment (rynowak) [inline src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs]: Why not pick like a SUPER high number?

File: src/Components/test/testassets/BasicTestApp/wwwroot/index.html [hunk 45]
```diff
@@ -30,6 +30,11 @@
             // Load either blazor.webassembly.js or blazor.server.js depending
             // on the hash part of the URL. This is just to give a way for the
             // test runner to make the selection.
+            if (location.hash === '#server') {
+                location.hash = '';
+                document.cookie = '__blazor_execution_mode=server';
```
Comment (rynowak) [inline src/Components/test/testassets/BasicTestApp/wwwroot/index.html]: Does this break other tests that use cookies?

File: src/Components/test/testassets/Ignitor/BlazorClient.cs [hunk 46]
```diff
@@ -293,21 +294,11 @@ public async Task<bool> ConnectAsync(Uri uri, bool prerendered, bool connectAuto
...
-                return result;
-            }
-            else
-            {
-                await ExpectRenderBatch(
-                    async () => CircuitId = await HubConnection.InvokeAsync<string>("StartCircuit", uri, uri),
-                    TimeSpan.FromSeconds(10));
-                return CircuitId != null;
-            }
+            var descriptor = await GetPrerenderDescriptors(uri);
```
Comment (rynowak) [inline src/Components/test/testassets/Ignitor/BlazorClient.cs]: `descriptors`?

File: src/Components/test/testassets/Ignitor/BlazorClient.cs [hunk 47]
```diff
@@ -293,21 +294,11 @@ public async Task<bool> ConnectAsync(Uri uri, bool prerendered, bool connectAuto
...
+            await ExpectRenderBatch(
+                async () => CircuitId = await HubConnection.InvokeAsync<string>("StartCircuit", uri, uri, descriptor),
+                TimeSpan.FromSeconds(10));
```
Comment (rynowak) [inline src/Components/test/testassets/Ignitor/BlazorClient.cs]: Is there something configurable we can use? Doesn't this class have a property for timeouts? Or just not pass one here and it behaves reasonably?

File: src/Components/test/testassets/TestServer/Pages/_ServerHost.cshtml [hunk 48]
```diff
@@ -0,0 +1,39 @@
+@page ""
+<!DOCTYPE html>
+<html>
+<head>
```
Comment (rynowak) [inline src/Components/test/testassets/TestServer/Pages/_ServerHost.cshtml]: What's motivating us to add a new entry point here?

File: src/Components/test/testassets/TestServer/Startup.cs [hunk 49]
```diff
@@ -82,16 +79,30 @@ public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
...
+                    {
+                        child.UseRouting();
+                        child.UseEndpoints(childEndpoints =>
+                        {
+                            childEndpoints.MapBlazorHub();
+                            childEndpoints.MapFallbackToPage("/_ServerHost");
+                        });
+                    });
+
+                app.MapWhen(ctx => !ctx.Request.Query.ContainsKey("__blazor_execution_mode"),
```
Comment (rynowak) [inline src/Components/test/testassets/TestServer/Startup.cs]: This is really kinda gross. I think we need to have some discussion before making a change like this. I don't want to see us keep evolving our testing strategy without careful consideration.

File: src/Mvc/Mvc.ViewFeatures/ref/Microsoft.AspNetCore.Mvc.ViewFeatures.netcoreapp3.0.cs [hunk 50]
```diff
@@ -610,6 +610,12 @@ public partial class MvcForm : System.IDisposable
         public void EndForm() { }
         protected virtual void GenerateEndForm() { }
     }
+    public enum RenderMode
+    {
+        Static = 1,
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/ref/Microsoft.AspNetCore.Mvc.ViewFeatures.netcoreapp3.0.cs]: Start at 0? Why not?

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 51]
```diff
@@ -37,30 +39,85 @@ public static class HtmlHelperComponentExtensions
...
+            {
+                RenderMode.Server => NonPrerenderedBlazorComponent(context, typeof(TComponent), GetPrameterCollection(parameters)),
+                RenderMode.ServerPrerendered => await PrerenderedBlazorComponentAsync(context, typeof(TComponent), GetPrameterCollection(parameters)),
+                RenderMode.Static => await StaticComponentAsync(context, typeof(TComponent), GetPrameterCollection(parameters)),
+                _ => throw new ArgumentException("Invalid render mode", nameof(renderMode)),
+            };
+        }
 
-            var parametersCollection = parameters == null ?
+        private static ParameterView GetPrameterCollection(object parameters) => parameters == null ?
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: `GetParameterCollection`

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 52]
```diff
@@ -37,30 +39,85 @@ public static class HtmlHelperComponentExtensions
...
-                typeof(TComponent));
+                context,
+                type);
 
             return new ComponentHtmlContent(result);
         }
+
+        private static async Task<IHtmlContent> PrerenderedBlazorComponentAsync(HttpContext context, Type type, ParameterView parametersCollection)
+        {
+            if (parametersCollection.GetEnumerator().MoveNext())
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: You could simplify this by passing in the dictionary to these methods and creating the parameter view inside

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 53]
```diff
@@ -37,30 +39,85 @@ public static class HtmlHelperComponentExtensions
...
             }
 
-            var httpContext = htmlHelper.ViewContext.HttpContext;
-            var serviceProvider = httpContext.RequestServices;
-            var prerenderer = serviceProvider.GetRequiredService<StaticComponentRenderer>();
+            var context = htmlHelper.ViewContext.HttpContext;
+            return renderMode switch
+            {
+                RenderMode.Server => NonPrerenderedBlazorComponent(context, typeof(TComponent), GetPrameterCollection(parameters)),
+                RenderMode.ServerPrerendered => await PrerenderedBlazorComponentAsync(context, typeof(TComponent), GetPrameterCollection(parameters)),
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: nipick - remove blazor from these method names. it doesn't add any additional clarity

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs [hunk 54]
```diff
@@ -37,30 +39,85 @@ public static class HtmlHelperComponentExtensions
...
+        private static IHtmlContent NonPrerenderedBlazorComponent(HttpContext context, Type type, ParameterView parametersCollection)
+        {
+            if (parametersCollection.GetEnumerator().MoveNext())
+            {
+                throw new InvalidOperationException("Server components with parameters are not supported.");
+            }
+
+            var serviceProvider = context.RequestServices;
+            var invocationSerializer = serviceProvider.GetRequiredService<ServerComponentSerializer>();
+            var currentInvocation = invocationSerializer.SerializeInvocation(context, type, prerendered:false);
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: nit: space

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs [hunk 55]
```diff
@@ -0,0 +1,162 @@
...
+using System.Collections.Generic;
+using System.Security.Cryptography;
+using System.Text.Json;
+using Microsoft.AspNetCore.Components;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.AspNetCore.Http;
+
+namespace Microsoft.AspNetCore.Mvc.ViewFeatures
+{
+    // **Component descriptor protocol**
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: Is this all duplicated? I think it would be better to have one big comment, and then just mention where to find that from the other class.

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs [hunk 56]
```diff
@@ -0,0 +1,162 @@
...
+            var (sequence, serverComponent) = CreateSerializedServerComponent(context, type);
+            return prerendered ? ServerComponentMarker.Prerendered(sequence, serverComponent) : ServerComponentMarker.NonPrerendered(sequence, serverComponent);
+        }
+
+        private ServerComponentInvocationSequence GetOrCreateInvocationIdentifier(HttpContext context)
+        {
+            if (!context.Items.TryGetValue(ComponentSequenceKey, out var sequence))
+            {
+                var newSequence = new ServerComponentInvocationSequence();
+                context.Items.Add(ComponentSequenceKey, newSequence);
```
Comment (rynowak) [inline src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: I'm worried about this still. How would this work when something like the error handling middleware is in use? Do we clear items?

**Review by rynowak — COMMENTED** [review]
I've given this a look, and I'm fairly happy with what I'm seeing in the product code.

I don't really get what's going on with some of these test changes, and I think it deserves more dicussion.

**Comment by rynowak** [comment]
I also want to know if we can find a better way than relying on `HttpContext.Items`.

File: src/Shared/Components/ServerComponent.cs [hunk 57]
```diff
@@ -0,0 +1,32 @@
...
+    {
+        public ServerComponent(
+            int sequence,
+            string assemblyName,
+            string typeName,
+            Guid invocationId) =>
+            (Sequence, AssemblyName, TypeName, InvocationId) = (sequence, assemblyName, typeName, invocationId);
+
+        // The order in which this component was rendered
+        public int Sequence { get; set; }
```
Comment (pranavkm) [inline src/Shared/Components/ServerComponent.cs]: Why is this mutable?

File: src/Shared/Components/ServerComponentMarker.cs [hunk 58]
```diff
@@ -0,0 +1,60 @@
...
+        }
+
+        // The order in which this component was rendered/produced
+        // on the server. It matches the number on the descriptor
+        // and is used to prevent an infinite amount of components
+        // from being rendered from the client-side.
+        public int? Sequence { get; set; }
+
+        // The marker type. Right now "server" is the only valid value.
+        public string Type { get; set; }
```
Comment (pranavkm) [inline src/Shared/Components/ServerComponentMarker.cs]: Why do we need this?

File: src/Shared/Components/ServerComponent.cs (hunk 57 above)
Comment (javiercn) [reply src/Shared/Components/ServerComponent.cs]: Needs to be JSON deserialized.

File: src/Shared/Components/ServerComponentMarker.cs (hunk 58 above)
Comment (javiercn) [reply src/Shared/Components/ServerComponentMarker.cs]: We want to leave room to support something like "client" in the future.

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs (hunk 42 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: Yes, it should be serverComponent. There is a bit of leftover from the rename

File: src/Components/Web.JS/src/Boot.Server.ts (hunk 43 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.ts]: My bad, bad merge

File: src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs (hunk 44 above)
Comment (javiercn) [reply src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs]: I'll do Int32.MaxValue

File: src/Components/test/testassets/BasicTestApp/wwwroot/index.html (hunk 45 above)
Comment (javiercn) [reply src/Components/test/testassets/BasicTestApp/wwwroot/index.html]: Nope, that's why I picked the cookie name

File: src/Components/test/testassets/Ignitor/BlazorClient.cs (hunk 47 above)
Comment (javiercn) [reply src/Components/test/testassets/Ignitor/BlazorClient.cs]: We used to default to 500ms which wasn't enough apparently for StartCircuit to succeed

File: src/Components/test/testassets/TestServer/Pages/_ServerHost.cshtml (hunk 48 above)
Comment (javiercn) [reply src/Components/test/testassets/TestServer/Pages/_ServerHost.cshtml]: We can't render server-side components unless we have some server-side code (razor page) as the entry point.

File: src/Components/test/testassets/TestServer/Startup.cs (hunk 49 above)
Comment (javiercn) [reply src/Components/test/testassets/TestServer/Startup.cs]: We need two different entry points as the server-side components can't be rendered from static html.

Tests use the hash, but unfortunately that doesn't get send to the server. I tried to swiching to a query string but that was causing other test problems. 

The cookie is the cheapest thing we can do to discriminate between server-side and client-side. The way it works is as follows.

Test opens a browser instance for the first time:
* There's no cookie, so it goes to index.html
* Index.html checks the #server hash
* If present, 
   * Removes the hash
  * Adds the cookie to the browser session.
  * Refreshes the page.
* From there on the rest of the requests go through the server endpoint.

I filed an issue with suggested improvements. Given where we are, I suggest we tackle them in the following weeks. This is not urgent and we can use the following weeks to implement a proper approach without rushing.
https://github.com/aspnet/AspNetCore/issues/13186

File: src/Mvc/Mvc.ViewFeatures/ref/Microsoft.AspNetCore.Mvc.ViewFeatures.netcoreapp3.0.cs (hunk 50 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/ref/Microsoft.AspNetCore.Mvc.ViewFeatures.netcoreapp3.0.cs]: I don't want to allow `default` being passed to the method calls.

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs (hunk 56 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: How do you propose we solve this?

I'm not sure what middleware you are referring to `UseStatusCodeWithReExecute`?. In general, re-executing the request is problematic no matter what approach you take.

You get the same services and the same httpcontext. Any 'scoped' service will not be clean and we can do two things. 
* Not support re-executing the request. (Relatively rare).
* Create a "Page" scope from MVC somewhere accessible to the HTML helper, like the ViewContext.
  * Whenever we render a top level page/view we "create" the scope and we track it as part of the items in the context or a scoped service.
  * If the request gets re-executed then it gets "reset".
 * If we use a scoped service for this then we can simply resolve it when we are going to render a page and initialize it.

File: src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs (hunk 28 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs]: Ok, so I have an alternative for this. I added an `internal IDictionary<object,object> Items` property to ViewContext. The idea is that it is tied to the lifetime of the viewcontext and the children spawn from it and that its meant to be scoped to the page/view/viewcomponent being executed.

I checked all the callsites of the viewcontext ctor to make sure we would keep the same viewcontext for the scope of the page/view/viewcomponent being rendered.

It adds an allocation per page/view/viewcomponent which I think is acceptable. Currently I lazily initialize it, but in practical terms the dictionary will always be allocated as it needs to be shared between parent viewcontext and childrenviewcontext whenever a new childviewcontext gets constructed (which is pretty much anytime you render a partial, layout or similar, so always).

I made the property an IDictionary<object,object> because I didn't want to put something super specific to blazor server-side components into ViewContext. If we wanted to avoid the allocation alltogether we could simply add a property for the sequence generator there as internal, but that feels like bad coupling.

I think the dictionary approach is the best even if we add 1 allocation per view/page/viewcomponent result as is idiomatic (similar to HttpContext.Items) and generally useful even outside of this context (For example for a script manager like primitive). We could consider making it public if we think is generally useful.

For this, I think this approach strikes a balance between practical and decoupled.

File: src/Shared/Components/ComponentDescriptorSerializer.cs (hunk 29 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.cs]: We reviewed this with Levi and got some feedback, but we were already putting all the measures in place.

File: src/Components/Server/src/Circuits/DefaultCircuitFactory.cs (hunk 30 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/DefaultCircuitFactory.cs]: just got rid of all the unnecessary nullchecks

File: src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs (hunk 31 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Deserialize.cs]: We agreed we don't need to do it this way

File: src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs (hunk 32 above)
Comment (javiercn) [reply src/Shared/Components/ComponentDescriptorSerializer.Serialize.cs]: We got this down to 16

File: src/Components/Server/src/Circuits/CircuitFactory.cs (hunk 38 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitFactory.cs]: Got rid of all the null checking in here. We don't need it

File: src/Components/Server/src/Circuits/CircuitFactory.cs (hunk 39 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitFactory.cs]: this one is, the one below not. I've updated it.

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs (hunk 40 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: Added a sample

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs (hunk 41 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: Clarified the comment

File: src/Components/Server/src/Circuits/ServerComponentDeserializer.cs (hunk 42 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/ServerComponentDeserializer.cs]: updated the names

File: src/Components/test/testassets/Ignitor/BlazorClient.cs (hunk 47 above)
Comment (javiercn) [reply src/Components/test/testassets/Ignitor/BlazorClient.cs]: Added a property specifically to control this

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 52 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: I want to avoid the allocation when parameters == null, checking on parameterView is cheap thanks to the struct enum optimization

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 51 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: fixed

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 53 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: Replaced blazor with server

File: src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs (hunk 54 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/HtmlHelperComponentExtensions.cs]: formatted

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs (hunk 55 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: Made a "pointer" from here to "ServerComponentDeserializer.cs"

File: src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs (hunk 56 above)
Comment (javiercn) [reply src/Mvc/Mvc.ViewFeatures/src/ServerComponentSerializer.cs]: I solved this as described https://github.com/aspnet/AspNetCore/pull/13147#discussion_r314686256

**Review by rynowak — APPROVED** [review]
We discussed offline about the test changes here, and why changing *something* is necessary. Basically since it's no longer possible to host server-side components in static HTML we haven't change how the server-side tests work.

@javiercn - has some ideas about what we should do here to try to and make this simpler in the future. Right now what's here isn't great - there are like 3 different strategies in use. He's going to follow up after we close down preview 9.

File: src/Components/Server/src/Circuits/CircuitFactory.cs (hunk 38 above)
Comment (rynowak) [reply src/Components/Server/src/Circuits/CircuitFactory.cs]: There are a lot of things we don't need in life 😆 Shoes, iced coffee, iguanas...

I've been in the habit of putting null checks in constructors because it keeps people from getting lazy in tests. There were a bunch of cases where I've seen people (in general, not pointing a finger at you) passing null into constructors of things in tests - because on the code path that they're testing it's not required. This usually blows up in someone's face when they have to refactor the code.
