### PR TITLE
[release/7.0] Hot reload: Acknowledge Blazor component parameter removal

### LINKED ISSUE #31272: Components don't reset their received parameters during hot reload updates
It's a bit unusual to remove a parameter value that you're passing to a child component, but if you do, our upcoming hot-reload-refresh mechanism doesn't yet account for it.

Repro: In the default project template, in `Index.razor`, change this:

```razor
<SurveyPrompt Title="How is Blazor working for you?" />
```

... to this:

```razor
<SurveyPrompt />
```

No change will show up in the UI. This is because the existing `SurveyPrompt` instance already has a value for its `Title` property. Failing to supply a new value just means that the old one doesn't get overwritten.

### Expected resolution

We can't control how all `IComponent` types deal with the removal of an incoming parameter value, but for `ComponentBase` at least, we can add some logic to `SetParametersAsync` that checks the `IsHotReload` flag and, if found, runs through some new code path to `default`-out all of its `[Parameter]` properties before receiving the new set from its parent.

### Severity

Low. I don't think this is a common scenario at all.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# [release/7.0] Hot reload: Acknowledge Blazor component parameter removal

If a parameter value was removed from a component during a hot reload edit, the component would retain the previously-supplied value. This PR fixes the issue by reinstantiating a component when a hot reload edit removes one of its parameters.

## Description

One approach to solving this bug could be to directly `default`-out all parameter properties before applying the new set of parameter values. The main problem with that is any custom construction logic initializing properties to their default values will be skipped. This can be fine in some cases, but even some of our E2E test pages would throw exceptions or break in other ways when _any_ hot reload change was applied using this approach.

Thus, with the changes in this PR, a component will get completely disposed and reinstantiated when a component parameter removal is detected during hot reload. This allows the component's construction logic to correctly reset parameter property values.

Fixes #31272

## Customer Impact

Certain types of code edits require the customer to either rebuild their project or refresh the webpage in order for the changes to be applied. Expanding the range of edits that a customer can make to their code without requiring manual refreshing/rebuilding makes Hot Reload a larger productivity booster. Supporting the live removal of Blazor component parameters is a step in that direction.

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

This PR adds a single additional code path to the rendering logic, and it only applies for hot reload scenarios. New automated tests have been added for the logic determining when that new code path should be taken (i.e., detecting when component parameters have been removed).

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

File: src/Components/Components/test/ParameterViewTest.cs [hunk 1]
```diff
@@ -402,6 +402,172 @@ public void Clone_ParameterPreservesOrder()
...
+
+        // Act
+        var hasRemovedDirectParameters = newParameters.HasRemovedDirectParameters(oldParameters);
+
+        // Assert
+        Assert.True(hasRemovedDirectParameters);
+    }
+
+    [Fact]
+    public void HasRemovedDirectParameters_ParametersSwapped()
```
Comment (javiercn) [inline src/Components/Components/test/ParameterViewTest.cs:546]: What happens if you have multiple parameters with the same name that are swapped?

**Review by javiercn — COMMENTED** [review]
Looks great so far, I have a minor question, but that's it.

File: src/Components/Components/test/ParameterViewTest.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/Components/Components/test/ParameterViewTest.cs:546]: In that case, `HasRemovedDirectParameters()` returns `false`, but the component would still update as it would for any other hot reload update (we just wouldn't treat it as a parameter removal, which is fine because no parameter is getting removed).

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs [hunk 2]
```diff
@@ -699,11 +660,50 @@ private static int NextSiblingIndex(in RenderTreeFrame frame, int frameIndex)
...
+                        // We do this using two mechanisms - we call SetParametersAsync even if the parameters
+                        // are unchanged and we ignore ComponentBase.ShouldRender.
+                        // Furthermore, when a hot reload edit removes component parameters, the component should be
+                        // disposed and reinstantiated. This allows the component's construction logic to correctly
+                        // re-initialize the removed parameter properties.
+
+                        var oldParameters = new ParameterView(ParameterViewLifetime.Unbound, oldTree, oldFrameIndex);
+                        var newParametersLifetime = new ParameterViewLifetime(diffContext.BatchBuilder);
+                        var newParameters = new ParameterView(newParametersLifetime, newTree, newFrameIndex);
+                        var isHotReload = HotReloadManager.Default.MetadataUpdateSupported && diffContext.Renderer.IsRenderingOnMetadataUpdate;
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:684]: I wonder if it would make sense to add `IsHotReload` as a flag on `DiffContext` so it can be evaluated just once at the start of each diff process, instead of once for each component we're retaining.

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs [hunk 3]
```diff
@@ -699,11 +660,50 @@ private static int NextSiblingIndex(in RenderTreeFrame frame, int frameIndex)
...
+                            newFrame.ComponentStateField = componentState;
+                            newFrame.ComponentIdField = componentState.ComponentId;
+
+                            if (!newParameters.DefinitelyEquals(oldParameters) || isHotReload)
+                            {
+                                componentState.SetDirectParameters(newParameters);
+                            }
+
+                            diffContext.SiblingIndex++;
+                        }
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:706]: I'm curious about the reasoning for inlining all of this logic. Does it reduce evaluations meaningfully? If so then fine :)

The `AppendDiffEntriesForFramesWithSameSequence` method is pretty giant now so if the new logic could be extracted without cost that could help with readability, but not a big deal.

**Comment by SteveSandersonMS** [comment]
The overall approach here looks good to me 👍

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:684]: Is that going to have a meaningful performance impact? (this is stripped away in production isn't it?)

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:684]: Oh yeah, good point.

In fact that might be a reason why *not* making a separate flag is better, i.e., depending on how smart the trimmer is about static analysis. For example, whether:

```cs
if (someValueThatTheTrimmerWillEvaluateAsFalse)
{
   // ...
}
```

and 

```cs
var shouldDoStuff = someValueThatTheTrimmerWillEvaluateAsFalse;
if (shouldDoStuff)
{
   // ...
}
```

... are actually equivalent, or whether the first is better because the entire `if(false)` is eliminated. I see that the earlier version of this code by Pranav did inline the trimmer-replacable value into the `if` test. Further, I don't know how smart the interpreter is about detecting and eliding `if(false)` blocks during its MSIL->interp-instructions pass.

In this case it's probably not something to worry about, just an interesting thought.

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs (hunk 3 above)
Comment (MackinnonBuck) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:706]: This was something I debated with myself before settling on inlining the logic. My thought process was something like:

* We only want to increment `diffContext.SiblingIndex` if the component is not getting removed, and the logic determining whether that happens would be in the `UpdateRetainedChildComponent()` helper method.
* Moving `diffContext.SiblingIndex++` to the helper method makes it less obvious that it's happening at all, especially since it's incremented inline in the other `case`s
* We _could_ turn `UpdateRetainedChildComponent()` into `TryUpdateRetainedChildComponent()` and use the return value to determine whether to increment the sibling index inline, but this seems a bit overkill (and that pattern isn't used elsewhere in this file)
* The `case` for `RenderTreeframeType.Element` is already even longer than the new `case` for `RenderTreeFrameType.Component` (excluding the comment), so it might be best just to inline everything to avoid the problem of finely separating what stays inline and what doesn't

Definitely open to having my mind changed, though!

Comment (SteveSandersonMS) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:706]: OK, sounds totally fine. It's clear you've thought it through well so let's go with what you're saying!

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
@Pilchie Would you be able to take a look at this? It's ready to be merged.

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2[
