### PR TITLE
Avoid using invalid content type for ValidationProblemDetails

### LINKED ISSUE #36557: Minimal APIs should return the standard media type for Problem Details responses
Minimal APIs that return the result of calling `Microsoft.AspNetCore.Http.Results.ValidationProblem` get a response media type of `application/validationproblem+json` which is [not compliant with the RFC7807 spec](https://datatracker.ietf.org/doc/html/rfc7807#section-3) that they're based on. The media type should be `application/problem+json`.

MVC has the same incorrect behavior but has since it was introduced in 2.x (see #36560).

We should fix this behavior in .NET 6.0 before final release.

### LINKED ISSUE #36560: MVC actions returning Problem Details should return the standard media type for Problem Details responses
MVC actions that return the result of calling `ControllerBase.ValidationProblem` get a response media type of `application/validationproblem+json` which is [not compliant with the RFC7807 spec](https://datatracker.ietf.org/doc/html/rfc7807#section-3) that they're based on. The media type should be `application/problem+json`.

We should be using the standard media type. Given this has been the behavior of MVC since the feature was introduced in 2.x, we might want to consider mitigations to address potential compatibility issues, e.g. an option to configure the media type, the ability to set the media type at the time of generating the response, etc.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/36560 
Closes https://github.com/dotnet/aspnetcore/issues/36557.

The OpenAPI extension methods assume an `application/validationproblem+json` content type but the results object represnet a different result.

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

File: src/Http/Routing/src/Builder/OpenApiDelegateEndpointConventionBuilderExtensions.cs [hunk 1]
```diff
@@ -109,15 +109,15 @@ public static DelegateEndpointConventionBuilder ExcludeFromDescription(this Dele
...
+        /// <param name="contentType">The response content type. Defaults to "application/problem+json".</param>
         /// <returns>A <see cref="DelegateEndpointConventionBuilder"/> that can be used to further customize the endpoint.</returns>
         public static DelegateEndpointConventionBuilder ProducesValidationProblem(this DelegateEndpointConventionBuilder builder,
             int statusCode = StatusCodes.Status400BadRequest,
             string? contentType = null)
         {
             if (string.IsNullOrEmpty(contentType))
             {
-                contentType = "application/validationproblem+json";
+                contentType = "application/problem+json";
```
Comment (pranavkm) [inline src/Http/Routing/src/Builder/OpenApiDelegateEndpointConventionBuilderExtensions.cs:120]: Is MVC also affected by this? Could we also fix it while we're addressing this?

**Review by BrennanConroy — APPROVED** [review]

File: src/Http/Routing/src/Builder/OpenApiDelegateEndpointConventionBuilderExtensions.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Routing/src/Builder/OpenApiDelegateEndpointConventionBuilderExtensions.cs:120]: AFAICT, MVC isn't affected by this as far as I can tell. The `ControllerBase.ValidationProblem` method uses the `application/problem+json` content type and the `ProducesResponseType` attribute expects that users pass the content type for when they specify a `typeof(ValidationProblemDetails)` hence the fix for the test case below.
