### PR TITLE
Don't re-use DefaultHttpContext if IHttpContextAccessor is in use

### LINKED ISSUE #14975: IHttpContextAccessor cannot be used reliably in some scenarios
The `IHttpContextAccessor` is used to access the `HttpContext` during the current request 
from components that were not given an explicit reference.

The typical use case is something like this:

```C#
public interface IUserAccessor
{
    ClaimsPrincipal User { get; }
}

public class UserAccessor : IUserAccessor
{
    private readonly IHttpContextAccessor _contextAccessor;
    public UserAccessor(IHttpContextAccessor contextAccessor)
    {
        _contextAccessor = contextAccessor;
    }

    public ClaimsPrincipal User => _contextAccessor.HttpContext?.User;
}
```

The `IUserAccessor` can now be used from components without a direct dependency on the `HttpContext`.

The `IHttpContextAccessor` can be used in 3 ways:

1. During the http request. `IHttpContextAccessor.HttpContext` returns a valid value. 👍  
2. Outside of the http request scope. `IHttpContextAccessor.HttpContext` returns `null`. 👍 
3. In a context that starts on the request scope and executes beyond the scope of the request. `IHttpContextAccessor.HttpContext` can return `null`, it can throw an `ObjectDisposedException` on property access, or it can return the wrong value (values from the next request). This is equivalent to holding onto the `HttpContext` past the request lifetime. 👎 

3 is a little hard to visualize so here's a coding pattern that demonstrates the issue:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication361
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<Service>();
            services.AddHttpContextAccessor();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, Service service)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    context.Items["x"] = "something useful";
                    
                    await Task.WhenAny(service.SomethingSlowAsync(), Task.Delay(1000));

                    await context.Response.WriteAsync("Hello World!");
                });
            });
        }
    }

    public class Service
    {
        private readonly IHttpContextAccessor _accessor;

        public Service(IHttpContextAccessor accessor)
        {
            _accessor = accessor;
        }

        public async Task SomethingSlowAsync()
        {
            await Task.Delay(1500);

            // There's a data race here because this can be cleaned up at any time
            if (_accessor.HttpContext != null)
            {
                // Even though we did the null check above, it may have changed by the time we access the value we wanted.
                var x = _accessor.HttpContext.Items["x"];
            }
        }
    }
}
```

In the above example `Service.SomethingSlowAsync()` is performing an asynchronous operation that will take 1.5 seconds (faked with `Task.Delay(1500)`) then using the `IHttpContextAccessor` to get some information set in earlier code. The code that runs during the request waits on `service.SomethingSlowAsync()` for 1 second before finishing the request.

Even though the code in `SomethingSlowAsync` is checking that `IHttpContextAccessor.HttpContext` returns `null`, that logic ends up running in parallel with the completion of the http request. As a result, there's a data race between the null check and the code using the `HttpContext`.

Even though this pattern falls into the *don't use the `HttpContext` after the request is over* bucket of problems, this pattern tends to come up alot when logging. Typically, some loggers will try to use `IHttpContextAccessor.HttpContext` to add per request information to the logs (which is better done with logging scopes) and ApplicationInsights makes this easier with the `ITelemetryInitiaizer` abstraction.

Options:
1. Do nothing. We write more docs and show why this pattern is bad and how to work around it.
2. Lock everything all the time. Doesn't seem viable and will affect performance.
3. Return a proxy object from the `IHttpContextAccessor.HttpContext` that will copy all request data just before the request ends (headers, path, method, items). Not very pay for play, needs to allocate several proxy objects per request.

### PR DESCRIPTION
**Pull request by davidfowl**
- Consumers may still get null or an ODE but will never end up with data from a different request.
- Make sure an ODE is thrown from all properties on HttpContext after the request is over.

Fixes #14975 

cc @benaadams

### CODE REVIEW

File: src/Hosting/Hosting/test/HostingApplicationDiagnosticsTests.cs [hunk 1]
```diff
@@ -0,0 +1,532 @@
...
+using System.Linq;
+using System.Reflection;
+using System.Threading.Tasks;
+using Microsoft.AspNetCore.Http;
+using Microsoft.AspNetCore.Http.Features;
+using Microsoft.Extensions.Logging;
+using Moq;
+using Xunit;
+
+namespace Microsoft.AspNetCore.Hosting.Tests
```
Comment (davidfowl) [inline src/Hosting/Hosting/test/HostingApplicationDiagnosticsTests.cs]: These aren't new but I renamed files (my bad).
- HostingApplicationDiagnosticsTests used to be HostingApplicationTests
- HostingApplicationTests contain the new tests

Comment (benaadams) [reply src/Hosting/Hosting/test/HostingApplicationDiagnosticsTests.cs]: I uses `git mv ` to ensure it git picks up file renames

**Review by benaadams — APPROVED** [review]
Oh that's nice :)

File: src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs [hunk 2]
```diff
@@ -71,11 +71,15 @@ public void Dispose(HttpContext httpContext)
             }
         }
 
-        internal void Dispose(DefaultHttpContext httpContext)
+        internal void Dispose(DefaultHttpContext httpContext, out bool usedHttpContextAccessor)
```
Comment (Tratcher) [inline src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs]: Why is this an out param rather than just a property on the class? The code in this method does not influence the result, _httpContextAccessor always has or does not have a value.

Comment (davidfowl) [reply src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs]: True.

**Comment by davidfowl** [comment]
@anurse, this is something we should patch in the 3.1 timeframe

**Review by Tratcher — APPROVED** [review]

**Comment by anurse** [comment]
Who approved this for 3.1?

**Comment by davidfowl** [comment]
@anurse nobody, it's in master

**Comment by anurse** [comment]
Horp, missed that sorry :)

**Comment by davidfowl** [comment]
I still think we should backport this to 3.1. I'll open an issue (or can I just do a PR?)

**Comment by Pilchie** [comment]
PR is fine.

**Comment by ldwedari** [comment]
If possible, this should be backported to 2.1 and 2.2 as soon as possible. It pottentially can cause serious issues to existing applications with wrong impersonation.

**Comment by davidfowl** [comment]
This never existed on 2.2 and 2.1 that’s a different issue.

**Comment by ldwedari** [comment]
> This never existed on 2.2 and 2.1 that’s a different issue.
@davidfowl I created [this demonstration](https://github.com/ldwedari/DotNetCore2_1DataRaceDemonstrator) based on the code that you posted in https://github.com/dotnet/aspnetcore/issues/14975.
In 2.1.19 (master branch) there is a data race. But in 3.1.5 (TestWithNetCore3_1 branch) I cannot see it happening.

Is my test wrong? If it is correct Does this actually happens in 3.1.5?

**Comment by ldwedari** [comment]
Just a clarification. I cannot reproduce the data race issue with HttpContext in asp.net core 2.2. But it does occur with all versions of 2.1.

**Comment by davidfowl** [comment]
@ldwedari This is using IIS or Kestrel?

**Comment by ldwedari** [comment]
@davidfowl Kestrel

**Comment by davidfowl** [comment]
I had to dig into the code archives to remember the 2.1 behavior. In 2.1 we never cleared the HttpContext state after the request is over which means its entirely possible to get values from the next request since the HttpContext points to the same feature collection when using Kestrel on the same connection.
