### PR TITLE
Increase logs and delays in CanLaunchPhotinoWebViewAndClickButton

### LINKED ISSUE #54017: Failing test CanLaunchPhotinoWebViewAndClickButton in 8.0 on Windows.Amd64.Server.2022
## Failing Test(s)

Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton

## Error Message

```text
Assert.Contains() Failure
Not found: Test passed? True
In value:  Current directory: C:hwAD38093FwA0AB0935e
Current assembly: C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.dll
Adding new native path: C:hwAD38093FwA0AB0935e
untimeswin-x64
ative
New PATH env var: C:hwAD38093FwA0AB0935e
untimeswin-x64
ative;C:hwAD38093FwA0AB0935e;C:hwAD38093Fpdotnet-cli;C:python3Scripts;C:python3;C:Windowssystem32;C:Windows;C:WindowsSystem32Wbem;C:WindowsSystem32WindowsPowerShell1.0;C:WindowsSystem32OpenSSH;C:Program Filesdotnet;C:UsersVMAdminAppDataLocalMicrosoftWindowsApps;;C:Debuggersd;C:Program FilesDocker;C:Users
unnerAppDataLocalMicrosoftWindowsApps;C:hwAD38093FwA0AB0935e
odein
Found 348 files in this app:
C:hwAD38093FwA0AB0935eCastle.Core.dll
C:hwAD38093FwA0AB0935edefault.runner.json
C:hwAD38093FwA0AB0935eDirectory.Build.props
C:hwAD38093FwA0AB0935eDirectory.Build.targets
C:hwAD38093FwA0AB0935edotnet-dump.exe
C:hwAD38093FwA0AB0935edotnet-ef.exe
C:hwAD38093FwA0AB0935edotnet-serve.exe
C:hwAD38093FwA0AB0935eDownload.ps1
C:hwAD38093FwA0AB0935eglobal.json
C:hwAD38093FwA0AB0935eInstallJdk.ps1
C:hwAD38093FwA0AB0935einstalljdk.sh
C:hwAD38093FwA0AB0935eInstallNode.ps1
C:hwAD38093FwA0AB0935einstallnode.sh
C:hwAD38093FwA0AB0935einstallPlaywrightReqs.ps1
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Forms.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Forms.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Forms.xml
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Web.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Web.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.Web.xml
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.Photino.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.Photino.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.Photino.xml
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebView.xml
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.deps.json
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.exe
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.WebViewE2E.Test.runtimeconfig.json
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Components.xml
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Testing.dll
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Testing.pdb
C:hwAD38093FwA0AB0935eMicrosoft.AspNetCore.Testing.xml
C:hwAD38093FwA0AB0935eMicrosoft.CodeCoverage.props
C:hwAD38093FwA0AB0935eMicrosoft.CodeCoverage.targets
C:hwAD38093FwA0AB0935eMicrosoft.Diagnostics.Runtime.dll
C:hwAD38093FwA0AB0935eMicrosoft.DotNet.RemoteExecutor.dll
C:hwAD38093FwA0AB0935eMicrosoft.Extensions.Configuration.Abstractions.dll
C:hwAD38093FwA0AB0935eMicrosoft.Extensions.Configuration.Binder.dll
C:hwAD38093FwA0AB0935eMicrosoft.Extensions.Configuration.dll
C:hwAD38093FwA0AB0935eMicrosoft.Extensions.Configuration.FileExtensions.dll
C:hwAD38093FwA0AB0935eMicrosoft.Extensions.Configuration.Json.dll
C:hwAD38093FwA0AB0935eMic


```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton() in /_/src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs:line 46
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
2024-02-13T09:50:36.2485170Z [xUnit.net 00:00:00.93]     Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton [FAIL]
2024-02-13T09:50:36.2488686Z [xUnit.net 00:00:00.93]       Assert.Contains() Failure
2024-02-13T09:50:36.2491137Z [xUnit.net 00:00:00.93]       Not found: Test passed? True
2024-02-13T09:50:36.2493559Z [xUnit.net 00:00:00.93]       In value:  Current directory: C:\h\w\AD38093F\w\A0AB0935\e
2024-02-13T09:50:36.2495891Z [xUnit.net 00:00:00.93]                  Current assembly: C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.dll
2024-02-13T09:50:36.2499067Z [xUnit.net 00:00:00.93]                  Adding new native path: C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-x64\native
2024-02-13T09:50:36.2502248Z [xUnit.net 00:00:00.93]                  New PATH env var: C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-x64\native;C:\h\w\AD38093F\w\A0AB0935\e;C:\h\w\AD38093F\p\dotnet-cli;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\VMAdmin\AppData\Local\Microsoft\WindowsApps;;C:\Debuggers\x64;C:\Program Files\Docker;C:\Users\runner\AppData\Local\Microsoft\WindowsApps;C:\h\w\AD38093F\w\A0AB0935\e\node\bin
2024-02-13T09:50:36.2544645Z [xUnit.net 00:00:00.93]                  Found 348 files in this app:
2024-02-13T09:50:36.2547941Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\Castle.Core.dll
2024-02-13T09:50:36.2551906Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\default.runner.json
2024-02-13T09:50:36.2554648Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\Directory.Build.props
2024-02-13T09:50:36.2557216Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\Directory.Build.targets
2024-02-13T09:50:36.2560282Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\dotnet-dump.exe
2024-02-13T09:50:36.2562910Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\dotnet-ef.exe
2024-02-13T09:50:36.2565672Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\dotnet-serve.exe
2024-02-13T09:50:36.2567949Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\Download.ps1
2024-02-13T09:50:36.2570215Z [xUnit.net 00:00:00.93]                  	C:\h\w\AD38093F\w\A0AB0935\e\global.json
2024-02-13T09:50:36.2573122Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstallJdk.ps1
2024-02-13T09:50:36.2575464Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\installjdk.sh
2024-02-13T09:50:36.2577947Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstallNode.ps1
2024-02-13T09:50:36.2580368Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\installnode.sh
2024-02-13T09:50:36.2582630Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\installPlaywrightReqs.ps1
2024-02-13T09:50:36.2585282Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.dll
2024-02-13T09:50:36.2587800Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Forms.dll
2024-02-13T09:50:36.2590740Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Forms.pdb
2024-02-13T09:50:36.2593116Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Forms.xml
2024-02-13T09:50:36.2595448Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.pdb
2024-02-13T09:50:36.2598339Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Web.dll
2024-02-13T09:50:36.2601534Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Web.pdb
2024-02-13T09:50:36.2603921Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.Web.xml
2024-02-13T09:50:36.2606538Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.dll
2024-02-13T09:50:36.2609649Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.pdb
2024-02-13T09:50:36.2612898Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.Photino.dll
2024-02-13T09:50:36.2615181Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.Photino.pdb
2024-02-13T09:50:36.2617456Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.Photino.xml
2024-02-13T09:50:36.2620365Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebView.xml
2024-02-13T09:50:36.2622850Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.deps.json
2024-02-13T09:50:36.2625643Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.dll
2024-02-13T09:50:36.2628128Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.exe
2024-02-13T09:50:36.2630768Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.pdb
2024-02-13T09:50:36.2633193Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.runtimeconfig.json
2024-02-13T09:50:36.2635342Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Components.xml
2024-02-13T09:50:36.2637708Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Testing.dll
2024-02-13T09:50:36.2640598Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Testing.pdb
2024-02-13T09:50:36.2643139Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.AspNetCore.Testing.xml
2024-02-13T09:50:36.2645342Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.CodeCoverage.props
2024-02-13T09:50:36.2647913Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.CodeCoverage.targets
2024-02-13T09:50:36.2650531Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Diagnostics.Runtime.dll
2024-02-13T09:50:36.2653077Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.DotNet.RemoteExecutor.dll
2024-02-13T09:50:36.2655320Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Configuration.Abstractions.dll
2024-02-13T09:50:36.2658107Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Configuration.Binder.dll
2024-02-13T09:50:36.2660958Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Configuration.dll
2024-02-13T09:50:36.2663276Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Configuration.FileExtensions.dll
2024-02-13T09:50:36.2665489Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Configuration.Json.dll
2024-02-13T09:50:36.2673132Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.DependencyInjection.Abstractions.dll
2024-02-13T09:50:36.2675854Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.DependencyInjection.dll
2024-02-13T09:50:36.2678790Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Abstractions.dll
2024-02-13T09:50:36.2681732Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Composite.dll
2024-02-13T09:50:36.2684229Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Embedded.dll
2024-02-13T09:50:36.2686966Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Embedded.pdb
2024-02-13T09:50:36.2689442Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Embedded.xml
2024-02-13T09:50:36.2692009Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileProviders.Physical.dll
2024-02-13T09:50:36.2694755Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.FileSystemGlobbing.dll
2024-02-13T09:50:36.2697331Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Logging.Abstractions.dll
2024-02-13T09:50:36.2699992Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Logging.Configuration.dll
2024-02-13T09:50:36.2702929Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Logging.Console.dll
2024-02-13T09:50:36.2705428Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Logging.dll
2024-02-13T09:50:36.2708482Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Options.ConfigurationExtensions.dll
2024-02-13T09:50:36.2711063Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Options.dll
2024-02-13T09:50:36.2713740Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.Extensions.Primitives.dll
2024-02-13T09:50:36.2716732Z [xUnit.net 00:00:00.94]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.JSInterop.dll
2024-02-13T09:50:36.2719105Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.JSInterop.pdb
2024-02-13T09:50:36.2721559Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.JSInterop.xml
2024-02-13T09:50:36.2724224Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.TestPlatform.CommunicationUtilities.dll
2024-02-13T09:50:36.2726981Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.TestPlatform.CoreUtilities.dll
2024-02-13T09:50:36.2729958Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.TestPlatform.CrossPlatEngine.dll
2024-02-13T09:50:36.2732475Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.TestPlatform.PlatformAbstractions.dll
2024-02-13T09:50:36.2734956Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.TestPlatform.Utilities.dll
2024-02-13T09:50:36.2737291Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.CodeCoverage.Shim.dll
2024-02-13T09:50:36.2740220Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.Coverage.Core.dll
2024-02-13T09:50:36.2742570Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.Coverage.Instrumentation.dll
2024-02-13T09:50:36.2745114Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.Coverage.Interprocess.dll
2024-02-13T09:50:36.2747539Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.TestPlatform.Common.dll
2024-02-13T09:50:36.2750176Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestAdapter.dll
2024-02-13T09:50:36.2752641Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.TestPlatform.Extension.Xunit.Xml.TestLogger.dll
2024-02-13T09:50:36.2754943Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll
2024-02-13T09:50:36.2757142Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Microsoft.VisualStudio.TraceDataCollector.dll
2024-02-13T09:50:36.2760440Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Mono.Cecil.dll
2024-02-13T09:50:36.2762834Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Mono.Cecil.Pdb.dll
2024-02-13T09:50:36.2765084Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Moq.dll
2024-02-13T09:50:36.2767540Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Newtonsoft.Json.dll
2024-02-13T09:50:36.2770265Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\NuGet.config
2024-02-13T09:50:36.2772627Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\NuGet.Frameworks.dll
2024-02-13T09:50:36.2775156Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\Photino.NET.dll
2024-02-13T09:50:36.2778142Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\README.md
2024-02-13T09:50:36.2780591Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\RunPowershell.cmd
2024-02-13T09:50:36.2782870Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtests.cmd
2024-02-13T09:50:36.2785758Z [xUnit.net 00:00:00.95]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtests.sh
2024-02-13T09:50:36.2790467Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\Serilog.dll
2024-02-13T09:50:36.2814387Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\Serilog.Extensions.Logging.dll
2024-02-13T09:50:36.2817232Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\Serilog.Sinks.File.dll
2024-02-13T09:50:36.2819640Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\System.IO.Pipelines.dll
2024-02-13T09:50:36.2822366Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\testhost.dll
2024-02-13T09:50:36.2824771Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\testhost.exe
2024-02-13T09:50:36.2827296Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\ThirdPartyNotices.txt
2024-02-13T09:50:36.2829861Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.abstractions.dll
2024-02-13T09:50:36.2832070Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.assert.dll
2024-02-13T09:50:36.2834737Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.core.dll
2024-02-13T09:50:36.2837306Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.execution.dotnet.dll
2024-02-13T09:50:36.2839713Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.runner.json
2024-02-13T09:50:36.2842311Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.runner.reporters.netcoreapp10.dll
2024-02-13T09:50:36.2844667Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.runner.utility.netcoreapp10.dll
2024-02-13T09:50:36.2847232Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\xunit.runner.visualstudio.dotnetcore.testadapter.dll
2024-02-13T09:50:36.2850308Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\_Imports.razor
2024-02-13T09:50:36.2852942Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\.dotnet\8.0.101.aspNetCertificateSentinel
2024-02-13T09:50:36.2855550Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\.dotnet\8.0.101.dotnetFirstUseSentinel
2024-02-13T09:50:36.2857900Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\.dotnet\8.0.101.toolpath.sentinel
2024-02-13T09:50:36.2860565Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\CodeCoverage.config
2024-02-13T09:50:36.2863405Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\CodeCoverage.exe
2024-02-13T09:50:36.2865611Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\codecoveragemessages.dll
2024-02-13T09:50:36.2867995Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\covrun32.dll
2024-02-13T09:50:36.2876827Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\msdia140.dll
2024-02-13T09:50:36.2880363Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\msvcdis140.dll
2024-02-13T09:50:36.2882964Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\msvcp140.dll
2024-02-13T09:50:36.2885432Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\msvcp140_atomic_wait.dll
2024-02-13T09:50:36.2887749Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\VanguardInstrumentationProfiler_x86.config
2024-02-13T09:50:36.2890557Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\vcruntime140.dll
2024-02-13T09:50:36.2892956Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2895685Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2898157Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2901093Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2903575Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2906114Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\cs\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2909104Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2911415Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2914313Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2916575Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2919093Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2922284Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\de\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2924750Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2927261Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2929796Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2933121Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2936018Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2938496Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\es\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2940862Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2943415Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2945686Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2948735Z [xUnit.net 00:00:00.96]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2951598Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2954181Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\fr\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2956522Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2959462Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2962190Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2964900Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2967382Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2970105Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\it\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2972698Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2975126Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2977664Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2980739Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2983129Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.2985632Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ja\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.2988611Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.2991305Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.2994025Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.2996440Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.2998641Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3001415Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ko\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3003954Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\mssql\InstallSqlServerLocalDB.ps1
2024-02-13T09:50:36.3006503Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\Pages\TestPage.razor
2024-02-13T09:50:36.3009844Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3012289Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3014583Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3017763Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3020145Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3022506Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pl\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3024812Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3027185Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3029668Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3032192Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3034490Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3036673Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\pt-BR\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3040094Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3042424Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3045096Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3048237Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3050904Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3053861Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\ru\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3056489Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3059128Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3061540Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3063731Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3066154Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3069052Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\tr\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3071738Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\wwwroot\webviewtesthost.html
2024-02-13T09:50:36.3073662Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3075214Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3076891Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3078447Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3080216Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3081856Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hans\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3083391Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.TestPlatform.CommunicationUtilities.resources.dll
2024-02-13T09:50:36.3084991Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.TestPlatform.CoreUtilities.resources.dll
2024-02-13T09:50:36.3086505Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.TestPlatform.CrossPlatEngine.resources.dll
2024-02-13T09:50:36.3088119Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.VisualStudio.TestPlatform.Common.resources.dll
2024-02-13T09:50:36.3089917Z [xUnit.net 00:00:00.97]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
2024-02-13T09:50:36.3091457Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\zh-Hant\Microsoft.VisualStudio.TraceDataCollector.resources.dll
2024-02-13T09:50:36.3093030Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\CodeCoverage.exe
2024-02-13T09:50:36.3094597Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\covrun64.dll
2024-02-13T09:50:36.3096204Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\msdia140.dll
2024-02-13T09:50:36.3097779Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\msvcdis140.dll
2024-02-13T09:50:36.3099810Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\msvcp140.dll
2024-02-13T09:50:36.3102312Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\msvcp140_atomic_wait.dll
2024-02-13T09:50:36.3104589Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\VanguardInstrumentationProfiler_x64.config
2024-02-13T09:50:36.3107073Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\vcruntime140.dll
2024-02-13T09:50:36.3108803Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\amd64\vcruntime140_1.dll
2024-02-13T09:50:36.3110519Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\CodeCoverage\coreclr\Microsoft.VisualStudio.CodeCoverage.Shim.dll
2024-02-13T09:50:36.3112100Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\eng\common\pipeline-logging-functions.ps1
2024-02-13T09:50:36.3113651Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\eng\common\pipeline-logging-functions.sh
2024-02-13T09:50:36.3115291Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\eng\common\tools.ps1
2024-02-13T09:50:36.3116802Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\eng\common\tools.sh
2024-02-13T09:50:36.3118376Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\x64\MicrosoftInstrumentationEngine_x64.dll
2024-02-13T09:50:36.3120174Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\x86\MicrosoftInstrumentationEngine_x86.dll
2024-02-13T09:50:36.3121695Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\wwwroot\css\app.css
2024-02-13T09:50:36.3123325Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\project.assets.json
2024-02-13T09:50:36.3124940Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\project.assets.json
2024-02-13T09:50:36.3126564Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\project.assets.json
2024-02-13T09:50:36.3128149Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\alpine\x64\libCoverageInstrumentationMethod.so
2024-02-13T09:50:36.3129868Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\alpine\x64\libInstrumentationEngine.so
2024-02-13T09:50:36.3131611Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\alpine\x64\ProductionBreakpoints_x64.config
2024-02-13T09:50:36.3133218Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\ubuntu\x64\libCoverageInstrumentationMethod.so
2024-02-13T09:50:36.3134742Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\ubuntu\x64\libInstrumentationEngine.so
2024-02-13T09:50:36.3136394Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\InstrumentationEngine\ubuntu\x64\ProductionBreakpoints_x64.config
2024-02-13T09:50:36.3138145Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\linux-x64\native\Photino.Native.so
2024-02-13T09:50:36.3140050Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\osx-arm64\native\Photino.Native.dylib
2024-02-13T09:50:36.3141867Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\osx-x64\native\Photino.Native.dylib
2024-02-13T09:50:36.3143463Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-arm64\native\Photino.Native.dll
2024-02-13T09:50:36.3145021Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-arm64\native\WebView2Loader.dll
2024-02-13T09:50:36.3146581Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-x64\native\Photino.Native.dll
2024-02-13T09:50:36.3148092Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\runtimes\win-x64\native\WebView2Loader.dll
2024-02-13T09:50:36.3149876Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\artifacts\log\Microsoft.AspNetCore.Components.WebViewE2E.Test\net8.0\global.log
2024-02-13T09:50:36.3151403Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\.nupkg.metadata
2024-02-13T09:50:36.3152990Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\.signature.p7s
2024-02-13T09:50:36.3154525Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\dotnet-dump.8.0.510501.nupkg
2024-02-13T09:50:36.3156030Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\dotnet-dump.8.0.510501.nupkg.sha512
2024-02-13T09:50:36.3157581Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\dotnet-dump.nupkg
2024-02-13T09:50:36.3159223Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\dotnet-dump.nuspec
2024-02-13T09:50:36.3160922Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\Icon.png
2024-02-13T09:50:36.3162527Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\.nupkg.metadata
2024-02-13T09:50:36.3164052Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\.signature.p7s
2024-02-13T09:50:36.3165657Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\dotnet-ef.8.0.1.nupkg
2024-02-13T09:50:36.3167191Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\dotnet-ef.8.0.1.nupkg.sha512
2024-02-13T09:50:36.3169023Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\dotnet-ef.nupkg
2024-02-13T09:50:36.3170667Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\dotnet-ef.nuspec
2024-02-13T09:50:36.3172255Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\Icon.png
2024-02-13T09:50:36.3173826Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\.nupkg.metadata
2024-02-13T09:50:36.3175342Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\.signature.p7s
2024-02-13T09:50:36.3176912Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\dotnet-serve.1.10.172.nupkg
2024-02-13T09:50:36.3178413Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\dotnet-serve.1.10.172.nupkg.sha512
2024-02-13T09:50:36.3180122Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\dotnet-serve.nupkg
2024-02-13T09:50:36.3181706Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\dotnet-serve.nuspec
2024-02-13T09:50:36.3183243Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\README.md
2024-02-13T09:50:36.3184851Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\dotnet-dump.deps.json
2024-02-13T09:50:36.3186415Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\dotnet-dump.dll
2024-02-13T09:50:36.3187973Z [xUnit.net 00:00:00.98]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\dotnet-dump.pdb
2024-02-13T09:50:36.3189713Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\dotnet-dump.runtimeconfig.json
2024-02-13T09:50:36.3191204Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\DotnetToolSettings.xml
2024-02-13T09:50:36.3192788Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.dll
2024-02-13T09:50:36.3194329Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.Implementation.dll
2024-02-13T09:50:36.3195887Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.Implementation.pdb
2024-02-13T09:50:36.3197486Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.Implementation.xml
2024-02-13T09:50:36.3199210Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.pdb
2024-02-13T09:50:36.3200888Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.DebugServices.xml
2024-02-13T09:50:36.3202397Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.ExtensionCommands.dll
2024-02-13T09:50:36.3203946Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.ExtensionCommands.pdb
2024-02-13T09:50:36.3206049Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.ExtensionCommands.xml
2024-02-13T09:50:36.3207624Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.NETCore.Client.dll
2024-02-13T09:50:36.3209504Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.NETCore.Client.pdb
2024-02-13T09:50:36.3211994Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.NETCore.Client.xml
2024-02-13T09:50:36.3213621Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.Repl.dll
2024-02-13T09:50:36.3215196Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.Repl.pdb
2024-02-13T09:50:36.3216692Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.Repl.xml
2024-02-13T09:50:36.3218314Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Diagnostics.Runtime.dll
2024-02-13T09:50:36.3220123Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.DependencyInjection.Abstractions.dll
2024-02-13T09:50:36.3221690Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.DependencyInjection.dll
2024-02-13T09:50:36.3223247Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.Logging.Abstractions.dll
2024-02-13T09:50:36.3224757Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.Logging.dll
2024-02-13T09:50:36.3226306Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.Options.dll
2024-02-13T09:50:36.3227880Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.Extensions.Primitives.dll
2024-02-13T09:50:36.3229769Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.FileFormats.dll
2024-02-13T09:50:36.3231330Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\Microsoft.SymbolStore.dll
2024-02-13T09:50:36.3232815Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\SOS.Hosting.dll
2024-02-13T09:50:36.3234631Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\SOS.Hosting.pdb
2024-02-13T09:50:36.3236166Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\SOS.InstallHelper.dll
2024-02-13T09:50:36.3237721Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\SOS.InstallHelper.pdb
2024-02-13T09:50:36.3239397Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\System.CommandLine.dll
2024-02-13T09:50:36.3241035Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\System.Text.Json.dll
2024-02-13T09:50:36.3242558Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\dotnet-ef.deps.json
2024-02-13T09:50:36.3244045Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\dotnet-ef.dll
2024-02-13T09:50:36.3245597Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\dotnet-ef.exe
2024-02-13T09:50:36.3247136Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\dotnet-ef.runtimeconfig.json
2024-02-13T09:50:36.3248665Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\DotnetToolSettings.xml
2024-02-13T09:50:36.3250523Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\ef.runtimeconfig.json
2024-02-13T09:50:36.3252115Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\BouncyCastle.Crypto.dll
2024-02-13T09:50:36.3253687Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\dotnet-serve.deps.json
2024-02-13T09:50:36.3255233Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\dotnet-serve.dll
2024-02-13T09:50:36.3256737Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\dotnet-serve.runtimeconfig.json
2024-02-13T09:50:36.3258300Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\DotNetConfig.dll
2024-02-13T09:50:36.3260040Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\DotnetToolSettings.xml
2024-02-13T09:50:36.3261576Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\McMaster.Extensions.CommandLineUtils.dll
2024-02-13T09:50:36.3263212Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-serve\1.10.172\dotnet-serve\1.10.172\tools\net6.0\any\Yarp.ReverseProxy.dll
2024-02-13T09:50:36.3264705Z [xUnit.net 00:00:00.99]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm\libsos.so
2024-02-13T09:50:36.3266300Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm\libsosplugin.so
2024-02-13T09:50:36.3267809Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm\sosdocsunix.txt
2024-02-13T09:50:36.3269558Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm64\libsos.so
2024-02-13T09:50:36.3271200Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm64\libsosplugin.so
2024-02-13T09:50:36.3272697Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-arm64\sosdocsunix.txt
2024-02-13T09:50:36.3274374Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm\libsos.so
2024-02-13T09:50:36.3275868Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm\libsosplugin.so
2024-02-13T09:50:36.3277420Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm\sosdocsunix.txt
2024-02-13T09:50:36.3279075Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm64\libsos.so
2024-02-13T09:50:36.3280608Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm64\libsosplugin.so
2024-02-13T09:50:36.3282183Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-arm64\sosdocsunix.txt
2024-02-13T09:50:36.3283667Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-x64\libsos.so
2024-02-13T09:50:36.3285299Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-x64\libsosplugin.so
2024-02-13T09:50:36.3286859Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-musl-x64\sosdocsunix.txt
2024-02-13T09:50:36.3288363Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-x64\libsos.so
2024-02-13T09:50:36.3290144Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-x64\libsosplugin.so
2024-02-13T09:50:36.3291727Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\linux-x64\sosdocsunix.txt
2024-02-13T09:50:36.3293319Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-arm64\libsos.dylib
2024-02-13T09:50:36.3295265Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-arm64\libsosplugin.dylib
2024-02-13T09:50:36.3297005Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-arm64\sosdocsunix.txt
2024-02-13T09:50:36.3298894Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-x64\libsos.dylib
2024-02-13T09:50:36.3301566Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-x64\libsosplugin.dylib
2024-02-13T09:50:36.3303228Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\osx-x64\sosdocsunix.txt
2024-02-13T09:50:36.3304838Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-arm\Microsoft.DiaSymReader.Native.arm.dll
2024-02-13T09:50:36.3306374Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-arm\sos.dll
2024-02-13T09:50:36.3307976Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-arm64\Microsoft.DiaSymReader.Native.arm64.dll
2024-02-13T09:50:36.3309849Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-arm64\sos.dll
2024-02-13T09:50:36.3311445Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-x64\Microsoft.DiaSymReader.Native.amd64.dll
2024-02-13T09:50:36.3312996Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-x64\sos.dll
2024-02-13T09:50:36.3314530Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-x86\Microsoft.DiaSymReader.Native.x86.dll
2024-02-13T09:50:36.3316147Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\win-x86\sos.dll
2024-02-13T09:50:36.3317682Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\shims\osx-x64\dotnet-dump
2024-02-13T09:50:36.3319453Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\shims\win-arm\dotnet-dump.exe
2024-02-13T09:50:36.3321078Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\shims\win-x64\dotnet-dump.exe
2024-02-13T09:50:36.3322627Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-dump\8.0.510501\dotnet-dump\8.0.510501\tools\net6.0\any\shims\win-x86\dotnet-dump.exe
2024-02-13T09:50:36.3324238Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\shims\win-arm64\dotnet-ef.exe
2024-02-13T09:50:36.3325744Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\shims\win-x64\dotnet-ef.exe
2024-02-13T09:50:36.3327352Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\shims\win-x86\dotnet-ef.exe
2024-02-13T09:50:36.3329146Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\net461\any\ef.exe
2024-02-13T09:50:36.3330811Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\net461\win-arm64\ef.exe
2024-02-13T09:50:36.3332348Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\net461\win-x86\ef.exe
2024-02-13T09:50:36.3333877Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\netcoreapp2.0\any\ef.dll
2024-02-13T09:50:36.3335426Z [xUnit.net 00:00:01.00]                  	C:\h\w\AD38093F\w\A0AB0935\e\.store\dotnet-ef\8.0.1\dotnet-ef\8.0.1\tools\net8.0\any\tools\netcoreapp2.0\any\ef.runtimeconfig.json
2024-02-13T09:50:36.3337027Z [xUnit.net 00:00:01.00]                  Creating BlazorWindow...
2024-02-13T09:50:36.3338628Z [xUnit.net 00:00:01.00]                  Hooking exception handler...
2024-02-13T09:50:36.3340292Z [xUnit.net 00:00:01.00]                  Setting up root components...
2024-02-13T09:50:36.3341776Z [xUnit.net 00:00:01.00]                  Running window...
2024-02-13T09:50:36.3343386Z [xUnit.net 00:00:01.00]                  RegisterWebMessageReceivedHandler...
2024-02-13T09:50:36.3345020Z [xUnit.net 00:00:01.00]                  Photino.NET: "Hello, world!".Load(http://0.0.0.0/subdir/)
2024-02-13T09:50:36.3346525Z [xUnit.net 00:00:01.00]                  Starting Photino window...
2024-02-13T09:50:36.3348133Z [xUnit.net 00:00:01.00]                  
2024-02-13T09:50:36.3349815Z [xUnit.net 00:00:01.00]       Stack Trace:
2024-02-13T09:50:36.3351475Z [xUnit.net 00:00:01.01]         /_/src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs(46,0): at Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton()
2024-02-13T09:50:36.3352986Z [xUnit.net 00:00:01.01]         --- End of stack trace from previous location ---
2024-02-13T09:50:37.6295156Z   Passed AlwaysTestTests.SuccessfulTests.GuaranteedUnquarantinedTest [2 ms]
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=564148&view=results

### PR DESCRIPTION
**Pull request by Eilon**
Really not sure what's causing the failure, especially because it fails so rarely. It seems unlikely it's a product bug (in Blazor code), so it seems more likely it's a problem with either the test infrastructure (e.g. slow machines?), or something to do with WebView2.

So if this passes on CI, then I suggest we merge this change and see what happens. And if it fails again in the future then we try additional things, such as a full retry within the test (e.g. if certain parts fail to even load, retry the whole test from scratch).

Fixes #54017

### CODE REVIEW

File: src/Components/WebView/test/E2ETest/BasicBlazorHybridTest.cs [hunk 1]
```diff
@@ -18,21 +18,21 @@ public void Run()
         // Note: This test produces *a lot* of debug output to aid when debugging failures. The only output
         // that is necessary for the functioning of this test is the "Test passed" at the end of this method.
 
-        Console.WriteLine($"Current directory: {Environment.CurrentDirectory}");
-        Console.WriteLine($"Current assembly: {typeof(Program).Assembly.Location}");
+        Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}] Current directory: {Environment.CurrentDirectory}");
```
Comment (Eilon) [inline src/Components/WebView/test/E2ETest/BasicBlazorHybridTest.cs:21]: All these DateTime.Now's are so that each *line* within the log has the actual time it was generated. Otherwise all the lines get written out to the xUnit log at the same time and thus all have the same timestamp, which isn't useful if you're trying to see how long it took between lines.

File: src/Components/WebView/test/E2ETest/BasicBlazorHybridTest.cs [hunk 2]
```diff
@@ -153,16 +157,16 @@ public void Run()
...
 
         // This line is what's required for the test to be considered as passed. The xUnit test in WebViewManagerE2ETests checks
         // that this reports success and that decides if the test is pass/fail.
-        Console.WriteLine($"Test passed? {testPassed}");
+        Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}] Test passed? {testPassed}");
     }
 
     const int MaxWaitTimes = 30;
-    const int WaitTimeInMS = 250;
+    const int WaitTimeInMS = 1000;
```
Comment (Eilon) [inline src/Components/WebView/test/E2ETest/BasicBlazorHybridTest.cs:169]: Increase delay time for this retry to hopefully help improve success rate.

File: src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs [hunk 3]
```diff
@@ -39,7 +40,9 @@ public async Task CanLaunchPhotinoWebViewAndClickButton()
 
         var testProgramOutput = photinoProcess.StandardOutput.ReadToEnd();
 
-        await photinoProcess.WaitForExitAsync().TimeoutAfter(TimeSpan.FromSeconds(30));
+        await photinoProcess.WaitForExitAsync().TimeoutAfter(TimeSpan.FromSeconds(60));
+
+        output.WriteLine(testProgramOutput);
```
Comment (Eilon) [inline src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs:45]: Always log the test output even on successful runs to help compare successful runs to failed runs (in case it turns out to be a machine slowness issue).

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by wtgodbe** [comment]
> can you please merge this test-only change?

Branches are closed now, we have to wait until they open at the beginning of April (even if the change is test-only, any new commits will trigger new dependency flow, which will disrupt the in-process servicing build)
