### PR TITLE
Fix fetch request in data-enhance-nav="false" for same-page anchors

### LINKED ISSUE #63396: data-enhance-nav="false" still triggers fetch calls for same-page anchors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When data-enhance-nav="false" is set on the navigation container, clicking an anchor tag that references an element on the same page (e.g., / → /#contact-us) still triggers an unnecessary fetch call.

This is inconsistent with the documented/expected behavior where disabling enhanced navigation should prevent such fetches and allow normal browser navigation/scrolling to anchors.

**Steps to Reproduce**

1. Add a navigation list with data-enhance-nav="false".
2. On the home page /, click an anchor tag pointing to an element on the same page, such as /#contact-us.
3. Observe in network tab that a fetch request is still made.

**Actual Behavior**

- Fetch calls are triggered even when navigating to an anchor within the same page.

**Expected Behavior**

- With data-enhance-nav="false", navigation to same-page anchors (/#section-id) should not trigger any fetch calls.
- The browser should handle it natively and just scroll to the element.
- Only full page navigations (e.g., /download) should cause a reload. (which is working fine)

**Additional Notes**

When data-enhance-nav="true":

- It correctly sends fetch calls for separate pages (e.g., /download). (which is working fine)
- It does not send fetch calls for same-page anchor navigation. (which is working fine)

When data-enhance-nav="false":

- It works correctly for separate pages (full reload). (which is working fine)
- But incorrectly still sends fetch calls for same-page anchors. (this is where the issue is)

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.203

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dariatiurina**
# Fix fetch request in data-enhance-nav="false" for same-page anchors

## Description

This pull request enhances the navigation logic to better handle hash-only changes in URLs, ensuring that navigation to anchors within the same page does not trigger a full page reload or unnecessary fetch requests. It introduces a utility function to detect hash-only changes and updates the navigation handler to leverage this, improving performance and user experience. Additional end-to-end tests and markup updates verify and demonstrate the new behavior.

### Changes:
* Added the `isHashOnlyChange` utility function in `NavigationUtils.ts` to detect when a navigation event only changes the hash fragment, avoiding unnecessary page loads.
* Updated the `onPopState` handler in `NavigationEnhancement.ts` to use `isHashOnlyChange`, preventing enhanced navigation logic from running when only the hash changes.
* Added a new end-to-end test in `EnhancedNavigationTest.cs` to verify that non-enhanced navigation to a hash does not trigger a page fetch, ensuring the scroll behavior works as expected without unnecessary network activity.

Fixes #63396

### CODE REVIEW

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 1]
```diff
@@ -52,6 +52,17 @@ export function isSamePageWithHash(absoluteHref: string): boolean {
   return url.hash !== '' && location.origin === url.origin && location.pathname === url.pathname && location.search === url.search;
 }
 
+export function isHashOnlyChange(oldUrl: string, newUrl: string): boolean {
```
Comment (ilonatommy) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts]: This is partially duplicating `isSamePageWithHash` in the meaning: I believe we could use your `isHashOnlyChange` in the place we're using `isSamePageWithHash` currently and remove `isSamePageWithHash`, to not to keep two very similar methods.
I would rather call the final method `isSameUrlWithDifferentHash` or `urlsDifferOnlyWithHash`. Using `change` in the name could imply that the method changes something.

**Review by ilonatommy — COMMENTED** [review]
We have the link scenaro covered in the test (`<a/>` element).
Let's also make sure that other cases work as expected:
- Programmatic navigation (<button @onclick="@(() => NavigationManager.NavigateTo(ulr#otherHash))">)
- `NavLink` navigation (`<NavLink href="ulr#otherHash">`)
- POST navigation, a form that uses custom `onsumbit` method with redirection to "ulr#otherHash" and disables enhanced nav. A variation on: https://github.com/dotnet/aspnetcore/blob/2cd7fb4901bfe710f2cf0ab23e411d7f7ef5f364/src/Components/test/testassets/TestContentPackage/NotFound/ComponentThatPostsNotFound.razor.

**Comment by dariatiurina** [comment]
> We have the link scenaro covered in the test (`<a/>` element). Let's also make sure that other cases work as expected:
> 
> * Programmatic navigation (<button @OnClick="@(() => NavigationManager.NavigateTo(ulr#otherHash))">)
> * `NavLink` navigation (`<NavLink href="ulr#otherHash">`)
> * POST navigation, a form that uses custom `onsumbit` method with redirection to "ulr#otherHash" and disables enhanced nav. A variation on: https://github.com/dotnet/aspnetcore/blob/2cd7fb4901bfe710f2cf0ab23e411d7f7ef5f364/src/Components/test/testassets/TestContentPackage/NotFound/ComponentThatPostsNotFound.razor.

NavigateTo behaves differently from `<a/>` and `<NavLink/>` with enhanced navigation, so this bug does not affect them.

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 2]
```diff
@@ -47,9 +47,15 @@ export function isWithinBaseUriSpace(href: string) {
...
 
-export function isSamePageWithHash(absoluteHref: string): boolean {
-  const url = new URL(absoluteHref);
-  return url.hash !== '' && location.origin === url.origin && location.pathname === url.pathname && location.search === url.search;
+export function isSameUrlWithDifferentHash(oldUrl: string, newUrl: string): boolean {
+  try {
+    const a = new URL(oldUrl);
+    const b = new URL(newUrl);
+    return a.origin === b.origin && a.pathname === b.pathname
+      && a.search === b.search && b.hash !== '';
```
Comment (javiercn) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts]: How is this correct? This is just checking whether the new url has a hash, but it it's not checking that it has a different hash.

If a is `https://www.example.com/path?query=value#something` and b is `https://www.example.com/path?query=value#something` that function will return true, when the hash is the same, isn't it?

Also, what's with the `try..catch` here.

Comment (dariatiurina) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts]: > How is this correct? This is just checking whether the new url has a hash, but it it's not checking that it has a different hash.
> 
> If a is `https://www.example.com/path?query=value#something` and b is `https://www.example.com/path?query=value#something` that function will return true, when the hash is the same, isn't it?
> 
> Also, what's with the `try..catch` here.

`try..catch` was to catch error during the conversion, but I see that `isForSamePath` in the same file doesn't care about those errors, so I will remove `try..catch`

About different hash - naming problem. Sorry. This is basically the same function as was before, just added a second url instead of location. I will rename it as it was before `isSamePageWithHash`

**Review by javiercn — APPROVED** [review]
