### PR TITLE
Do not cache 304 responses

### LINKED ISSUE #23345: HTTP 304 response when using Http.sys for a request that should return a 200
### Describe the bug
Basically when requesting static files from a ASP.NET Core 3.1 web app without the appropriate request headers (If-None-Match for eg), I get an HTTP 304, incorrectly. This can come into a client that never had the file in the first place, causing a failure to load.

### To Reproduce

1) run the app locally but using httpsys as the web server
2) make a call to a static file that returns an ETag and a 200
3) make a subsequent call to the same with the ETag on the If-None-Match and get a 304
4) stop sending the ETag and verify you're still getting 304s

request looks like
```
GET https://.../vendor.5b4c15ae6ced0e36f7d3.js HTTP/1.1
User-Agent: PostmanRuntime/7.25.0
Accept: */*
Host: ...
Accept-Encoding: gzip, deflate, br
```

and response looks like
```
HTTP/1.1 304 Not Modified
Cache-Control: public, max-age=31536000
Content-Type: application/javascript
Last-Modified: Wed, 24 Jun 2020 16:55:03 GMT
Accept-Ranges: bytes
ETag: "1d64a48345b98c8"
Server: *** Microsoft-HTTPAPI/2.0
Request-Context: appId=cid-v1:49d13409-b199-43ea-a259-e4893160bf92
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Security-Policy: frame-ancestors https: http: ; script-src 'self' ...
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: master-only;
Referrer-Policy: same-origin
Date: Wed, 24 Jun 2020 21:34:26 GMT
```
### Further technical details
- ASP.NET Core version: 3.1

### PR DESCRIPTION
**Pull request by Tratcher**
Fixes #23345 A 304 response is supposed to have the same headers as its associated 200 response, including Cache-Control, but the 304 response itself should not be cached. Otherwise Http.Sys will serve the 304 response to all requests without checking conditional headers like If-None-Match.

@ricmrodrigues

### CODE REVIEW

File: src/Servers/HttpSys/test/FunctionalTests/ResponseCachingTests.cs [hunk 1]
```diff
@@ -85,6 +85,27 @@ public async Task Caching_WithoutContentType_NotCached()
...
+                // 304 responses are not themselves cachable. Their cache header mirrors the resource's original cache header.
+                httpContext.Response.StatusCode = StatusCodes.Status304NotModified;
+                httpContext.Response.ContentType = "some/thing"; // Http.Sys requires content-type for caching
+                httpContext.Response.Headers["x-request-count"] = (requestCount++).ToString();
+                httpContext.Response.Headers["Cache-Control"] = "public, max-age=10";
+                httpContext.Response.ContentLength = 10;
+                return httpContext.Response.Body.WriteAsync(new byte[10], 0, 10);
+            }))
+            {
+                address += Guid.NewGuid().ToString(); // Avoid cache collisions for failed tests.
```
Comment (halter73) [inline src/Servers/HttpSys/test/FunctionalTests/ResponseCachingTests.cs:103]: Why does this test do this, but not the following test?

File: src/Servers/HttpSys/src/FeatureContext.cs [hunk 2]
```diff
@@ -635,6 +635,13 @@ private void ConsiderEnablingResponseCache()
         private static TimeSpan? GetCacheTtl(RequestContext requestContext)
         {
             var response = requestContext.Response;
+            // A 304 response is supposed to have the same headers as its associated 200 response, including Cache-Control, but the 304 response itself
+            // should not be cached. Otherwise Http.Sys will serve the 304 response to all requests without checking conditional headers like If-None-Match.
+            if (response.StatusCode == StatusCodes.Status304NotModified)
```
Comment (halter73) [inline src/Servers/HttpSys/src/FeatureContext.cs:640]: So HTTP.Sys doesn't use the If-None-Match header as part of the cache lookup key. Can that be configured somehow?

Comment (Tratcher) [reply src/Servers/HttpSys/src/FeatureContext.cs:640]: No, and no.

**Review by halter73 — APPROVED** [review]

**Review by jkotalik — APPROVED** [review]

File: src/Servers/HttpSys/test/FunctionalTests/ResponseCachingTests.cs (hunk 1 above)
Comment (Tratcher) [reply src/Servers/HttpSys/test/FunctionalTests/ResponseCachingTests.cs:104]: There's no way to clear the cache between tests, this helps avoid collisions. Not sure why only half the tests have them, I'll add them to the other half.
