### PR TITLE
[Blazor] Avoid validating antiforgery for non form data content types

### LINKED ISSUE #55582: .NET 8 Blazor - Static Rendering, AntiForgery and Incorrect Content-Type: Exceptions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a public website built on Blazor which uses Static Rendering (https://www.oqtane.org). When running this site in production there are bots which will attempt to send POST requests to site pages. When this occurs it raises an exception which is logged to my error logging infrastructure - which is creating a lot of log entries.

I have done some further investigation and was able to reproduce on a standard Blazor Web app generated from the template.

If you make an empty POST request (ie. using POSTMAN) to a Static Server rendered endpoint and that endpoint has Antiforgery disabled:

```
@using Microsoft.AspNetCore.Antiforgery;
@attribute [RequireAntiforgeryToken(required: false)]
```

Blazor will call:

RazorComponentEndpointInvoker.cs which calls ValidateRequestAsync()

It evaluates the Antiforgerytoken settings and if Antiforgery is disabled for the endpoint, it logs a Debug message:

"The endpoint disabled antiforgery token validation."

and continues on and eventually calls:

```
await context.Request.ReadFormAs()
```

which invokes FormFeature.cs which eventually calls InnerReadFormAsync() and the following logic is invoked:

```if (!HasFormContentType)
{
    throw new InvalidOperationException("Incorrect Content-Type: " + _request.ContentType);
}
```

which throws an exception:

```
System.InvalidOperationException: Incorrect Content-Type: 
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.ValidateRequestAsync(HttpContext context, IAntiforgery antiforgery)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BlazorApp18.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Users\shaun\source\repos\BlazorApp18\BlazorApp18\ExceptionMiddleware.cs:line 16
```

The HTTP response returned has status 200 OK

However...

if the endpoint does have Antiforgery enabled, Blazor returns a response of 400 Bad Request with content of:

"A valid antiforgery token was not provided with the request. Add an antiforgery token, or disable antiforgery validation for this endpoint."

and does not raise an exception.

I believe the behavior should be consistent in both scenarios, and should not raise an Exception.

### Expected Behavior

A POST request can be sent to a page rendered with Static Rendering which does not have Antiforgery enabled, and it will not throw an exception.

### Steps To Reproduce

Create a standard Blazor Web App. Disable anti-forgery on the Home page. Add exception middleware to catch unhandled exceptions. Use POSTMAN to send a POST request to the Home page. Catch the exception.

### Exceptions (if any)

System.InvalidOperationException: Incorrect Content-Type: 
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.ValidateRequestAsync(HttpContext context, IAntiforgery antiforgery)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BlazorApp18.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Users\shaun\source\repos\BlazorApp18\BlazorApp18\ExceptionMiddleware.cs:line 16

### .NET Version

8.0.4 (latest SDK installed in production)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by javiercn**
Sends bad request if content-type is not valid (like application/json)

Fixes https://github.com/dotnet/aspnetcore/issues/55582

### CODE REVIEW

File: src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs [hunk 1]
```diff
@@ -163,11 +163,22 @@ private async Task<RequestValidationState> ValidateRequestAsync(HttpContext cont
...
             context.Features.Get<IExceptionHandlerFeature>() == null;
 
+
         if (processPost)
         {
-            var valid = false;
+            if (!context.Request.HasFormContentType)
+            {
+                context.Response.StatusCode = StatusCodes.Status400BadRequest;
+                if (context.RequestServices.GetService<IHostEnvironment>()?.IsDevelopment() == true)
```
Comment (SteveSandersonMS) [inline src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:172]: There's some logic in `EndpointHtmlRenderer.Streaming.cs` like this:

```cs
        var env = httpContext.RequestServices.GetRequiredService<IWebHostEnvironment>();
        var options = httpContext.RequestServices.GetRequiredService<IOptions<RazorComponentsServiceOptions>>();
        var showDetailedErrors = env.IsDevelopment() || options.Value.DetailedErrors;
```

I guess we should use a similar condition here, and maybe it could be factored out into a common place.

Comment (javiercn) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:172]: This is why I hate partial classes, but good call

Comment (javiercn) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:172]: I've factored out the code, and put it in a static method, I can't think of a good place to put that logic, so I'm going to just randomly leave it inside EndpointHtmlRenderer and use it in the invoker, if we go through this code again, we can do a clean-up pass.

Comment (SteveSandersonMS) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:171]: Wouldn't we also use `ShouldShowDetailedErrors` as the condition for whether to emit `The request has an incorrect Content-type.` to the response here, instead of `IsDevelopment` on line 171?

File: src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs [hunk 2]
```diff
@@ -205,7 +215,7 @@ private async Task<RequestValidationState> ValidateRequestAsync(HttpContext cont
             {
                 context.Response.StatusCode = StatusCodes.Status400BadRequest;
 
-                if (context.RequestServices.GetService<IHostEnvironment>()?.IsDevelopment() == true)
+                if (EndpointHtmlRenderer.ShouldShowDetailedErrors(context))
```
Comment (SteveSandersonMS) [inline src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:218]: I didn't spot this before but it's good you've updated it

File: src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs:171]: Yes, I updated it in the wrong place

**Review by SteveSandersonMS — APPROVED** [review]
Great!

File: src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs [hunk 3]
```diff
@@ -165,7 +164,9 @@ private async Task<RequestValidationState> ValidateRequestAsync(HttpContext cont
 
         if (processPost)
         {
-            if (!context.Request.HasFormContentType)
```
Comment (javiercn) [inline src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs]: @captainsafia I think this was triggered by the antiforgery middleware, I believe we should revisit this to avoid throwing and instead return false. It's surprising otherwise and might break existing code, do you have thoughts?

Comment (captainsafia) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs]: I think you might be talking about the exception that gets thrown [here](https://source.dot.net/#Microsoft.AspNetCore.Http/Features/FormFeature.cs,189)). If so, I'm a little cautious about changing this behavior given its in the FormFeature shared across the stack as opposed to just being in anti-forgery middleware.

We don't eagerly validate the content type in the anti-forgery middleware (although we could) then we wouldn't fall through to the exception in the FormFeature.

Comment (javiercn) [reply src/Components/Endpoints/src/RazorComponentEndpointInvoker.cs]: I might have been confused and thought the issue might have been related to antiforgery, since I saw an exception pop right before.

I'll take another quick look at it and see if I repro it in a simpler way. I throught it was the thing where we poisoned the IFormFeature that was throwing, but I can't find it right now.
