### PR TITLE
EndpointMiddleware does not invoke endpoint

### LINKED ISSUE #10649: EndpointMiddleware will not work if SuppressCheckForUnhandledSecurityMetadata is true
When `RouteOptions.SuppressCheckForUnhandledSecurityMetadata` is set to true, `EndpointMiddleware` would not execute any Endpoint.

I think the reason is `EndpointMiddleware` must skip checking for Auth and Cors Middleware, instead of return a CompletedTask.

This is the current code
```
if (_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
{
    // User opted out of this check.
    return Task.CompletedTask;
}

if (endpoint.Metadata.GetMetadata<IAuthorizeData>() != null &&
!httpContext.Items.ContainsKey(AuthorizationMiddlewareInvokedKey))
{
    ThrowMissingAuthMiddlewareException(endpoint);
}

if (endpoint.Metadata.GetMetadata<ICorsMetadata>() != null &&
!httpContext.Items.ContainsKey(CorsMiddlewareInvokedKey))
{
    ThrowMissingCorsMiddlewareException(endpoint);
}
```

I think change it to this would solve the issue
```
if (!_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
{
    if (endpoint.Metadata.GetMetadata<IAuthorizeData>() != null &&
    !httpContext.Items.ContainsKey(AuthorizationMiddlewareInvokedKey))
    {
        ThrowMissingAuthMiddlewareException(endpoint);
    }

    if (endpoint.Metadata.GetMetadata<ICorsMetadata>() != null &&
    !httpContext.Items.ContainsKey(CorsMiddlewareInvokedKey))
    {
        ThrowMissingCorsMiddlewareException(endpoint);
    }
}
```

### PR DESCRIPTION
**Pull request by rynowak**
Fixes: #10649

The bug is that the endpoint delegate is not invoked when
SuppressCheckForUnhandledSecurityMetadata is set to true. This option is
provided so that can you suppress the security checks done by routing,
but right now what it does is suppress the entire middleware.

We had tests for the supression cases, but they didn't actually validate
that the middleware did any work, just that we don't throw. Fixed that.

/cc @Kahbazi

### CODE REVIEW

**Comment by Kahbazi** [comment]
Since `Invoke_WithEndpoint_DoesNotThrowIfUnhandledCorsAttributesWereFound_ButSuppressedViaOptions` and `Invoke_WithEndpoint_WorksIfCorsMetadataWasFound_AndCorsMiddlewareInvoked` is changed, should `Invoke_WithEndpoint_DoesNotThrowIfUnhandledAuthAttributesWereFound_ButSuppressedViaOptions` and `Invoke_WithEndpoint_WorksIfAuthAttributesWereFound_AndAuthMiddlewareInvoked` also change?

**Comment by rynowak** [comment]
Ah, you're right. I missed that one. I'm going to go ahead and update all of these tests to run the endpoint and verify it.

**Comment by rynowak** [comment]
I've hardened these tests to make the expectations clearer about what delegates run and what don't.

File: src/Http/Routing/src/EndpointMiddleware.cs [hunk 1]
```diff
@@ -36,22 +36,19 @@ public Task Invoke(HttpContext httpContext)
             var endpoint = httpContext.Features.Get<IEndpointFeature>()?.Endpoint;
             if (endpoint?.RequestDelegate != null)
             {
-                if (_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
+                if (!_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
```
Comment (pranavkm) [inline src/Http/Routing/src/EndpointMiddleware.cs]: Oops

**Review by pranavkm — APPROVED** [review]
