### PR TITLE
Fix loading dotnet user-jwts config

### LINKED ISSUE #58996: .NET 9: `dotnet user-jwts` not working
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I followed the [MSDN](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-9.0&tabs=windows) and upon sending the HTTP Request with the Bearer token, the server returns 401. The `WWW-Authenticate` response header shows `Bearer error="invalid_token", error_description="The signature key was not found"`.

### Expected Behavior

Server returns 200.

### Steps To Reproduce

Followed the exact steps in the [MSDN](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-9.0&tabs=windows)

### Exceptions (if any)

_No response_

### .NET Version

9.0.100

### Anything else?

RID: win-arm64
It used to work on .NET 8.

### PR DESCRIPTION
**Pull request by halter73**
Fixes #58996

### CODE REVIEW

File: src/Security/Authentication/JwtBearer/src/JwtBearerConfigureOptions.cs [hunk 1]
```diff
@@ -72,7 +72,7 @@ public void Configure(string? name, JwtBearerOptions options)
             ValidAudiences = audiences,
             ValidAudience = audience,
             ValidateIssuerSigningKey = true,
-            IssuerSigningKeys = GetIssuerSigningKeys(configSection, issuers),
+            IssuerSigningKeys = GetIssuerSigningKeys(configSection, [issuer, ..issuers]),
```
Comment (captainsafia) [inline src/Security/Authentication/JwtBearer/src/JwtBearerConfigureOptions.cs:75]: The fact that we didn't pass the standalone issuer here was always a bug, correct?

Comment (halter73) [reply src/Security/Authentication/JwtBearer/src/JwtBearerConfigureOptions.cs:75]: It was a regression caused in .NET 9 by #52821. I plan to backport this once approved.

**Review by captainsafia — APPROVED** [review]
