### PR TITLE
Fix #5055 use of page parameter

### LINKED ISSUE #5055: Generating URL with page parameter fails with new endpoint routing (regression from 2.1)
This appears to be a regression due to the new endpoint routing system in 2.2. As per aspnet/Mvc#7876, using parameter names `action` and `page` is somewhat difficult, however using a `page` parameter inside an MVC action or using an `action` parameter inside of a Razor page does work fine. At least it did.

With endpoint routing activated (through the MVC compatibility switch `CompatibilityVersion.Version_2_2`), generating an action link that has a `page` parameter will now fail **iff** Razor pages exist in the same project.

#### Without Razor pages
1. Create new 2.2 application from standard MVC template.
2. Add an action to the `HomeController`:
    ```c#
    public IActionResult Test(int page)
    {
        return Json(new
        {
            Url = Url.Action(nameof(Test), new { page = 123 }),
            Page = page,
        });
    }
    ```
3. Launch the application and open `http://localhost:5000/Home/Test?page=4`
4. Observe the result which shows a generated URL `/Home/Test?page=123`.

#### Add Razor pages
5. Now, create a Razor page at `Pages/Foo.cshtml` with the contents `@page`.
6. Launch the application and open the previous URL again.
7. Observe that the generated URL is now `null`.

#### Disable endpoint routing
8. Disable endpoint routing by changing the `AddMvc()` call in `Startup` to set the compatibility level switch back to 2.1:
    ```c#
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
    ```
9. Launch the application and open the previous URL again.
10. Observe that the URL is generated properly again.

---

As you can see, endpoint routing breaks the URL generation here although the target URL exists just fine and although it also can be used properly the whole time (note that the JSON response always includes the passed `page` value). The mere presence of Razor pages should not make the URL generation treat any `page` parameter in a special way here.

### PR DESCRIPTION
**Pull request by rynowak**
This change introduces some new heuristics to make it easier to use
'page' or other resevered parameter names as parameters in URL
generation.

--

The main change here is to allow the link generation tree to *ignore* a
value passed in to URL generation when it conflicts with an endpoint's
required values.

The main concern of this feature area is "how do we tell whether you are
linking to an action or a page?". Routing attempts to do the right thing
will requiring very little from the user in terms of expressing intent.

In this case, we try to tell the difference between an attempt to generate
a link to an action due to the presence of the 'action' parameter and
absence of the 'page' parameter. This obviously doesn't work when you
want to use 'page' as a non-reserved parameter in an action. The same
case occurs for pages, but users are already used to the idea that
'action' is a reserved word in MVC.

We can loosen this restriction when the value that's supplied for 'page'
is known not to be any existing value of the 'page' route value.

This approach seems somewhat reasonable but has many of the problems inherent
to this area. When it fails (the value you want to use for 'page' causes
a conflict) - it's going to be esoteric and hard to understand.

### CODE REVIEW

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs [hunk 1]
```diff
@@ -91,7 +108,20 @@ public IList<OutboundMatchResult> GetMatches(RouteValueDictionary values, RouteV
...
+                        // If an explicitly specified value doesn't match any branch, then speculatively walk the
+                        // "null" path if the value doesn't match any known value.
+                        //
+                        // This can happen when linking from a page <-> action. We want to be
+                        // able to use "page" and "action" as normal route parameters.
+                        var knownValues = _knownValues[key];
+                        if (!knownValues.Contains(value ?? string.Empty) && criterion.Branches.TryGetValue(string.Empty, out branch))
+                        {
+                            Walk(results, values, ambientValues, branch, quality + 0.01m);
+                        }
```
Comment (rynowak) [inline src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: This is the gist of the fix. Each approach has problems. This kind of feature as at-odds with the algorithmic requirements of routing so it's going to require esoteric heuristics to improve this.

=====

A few things we could try:

1. (in this pr) check 'page' against known values to prevent ambiguity
1. allow the tree to ignore 'page' and rely on ordering - changes the behavior when you have a link fail to generate
1. remove 'page' from required values of an action

I went with approach once because I don't like the drawbacks of 2. I don't want to impact the majority cases by changing how it behaves when you fail to generate a link when linking from a page to an action.

Imagine you're trying to like an action: `{ action = "Buy", controller = "Store" }` with template `/Store/Buy/{productId?}`. you are on page `/Foo/Bar` and you supply the route values `{ action = "Buy", controller = "Store" }` - but no productId. If we did option 2, then both your action *and your current page* would be candidates. Since you failed to supply productId, the action would fail to generate, and you'd get `/Foo/Bar?action=Buy&controller=Store` instead.

This is why I did option 1. 

Option 3 is totally busto because it makes ambient value invalidation stop working when you like from a page to an action. Yuck.

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs [hunk 2]
```diff
@@ -139,6 +169,12 @@ private class OutboundMatchResultComparer : IComparer<OutboundMatchResult>
 
             public int Compare(OutboundMatchResult x, OutboundMatchResult y)
             {
+                if (x.Quality != y.Quality)
+                {
+                    // Reversed because higher is better
+                    return y.Quality.CompareTo(x.Quality);
+                }
```
Comment (rynowak) [inline src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: I made this change while pursuing option 2, I don't think it's needed for anything so I could revert it once we decide what to do.

File: src/Http/Routing/test/UnitTests/Internal/LinkGenerationDecisionTreeTest.cs [hunk 3]
```diff
@@ -340,6 +340,385 @@ public void SelectMultipleEntries_BothMatch_OrderedByTemplate()
...
+
+            var context = CreateContext(new { page = "/Store/Buy", action = "Index", }, new { controller = "Home", action = "Index", page = "16", });
+
+            // Act
+            var matches = tree.GetMatches(context.Values, context.AmbientValues).Select(m => m.Match).ToList();
+
+            // Assert
+            Assert.Empty(matches);
+        }
+
```
Comment (rynowak) [inline src/Http/Routing/test/UnitTests/Internal/LinkGenerationDecisionTreeTest.cs]: Note: I didn't make any attempt to address the problem of writing a conventional route that uses `{page}` as a parameter. I'm not sure this can really be solved.

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs [hunk 4]
```diff
@@ -91,7 +108,20 @@ public IList<OutboundMatchResult> GetMatches(RouteValueDictionary values, RouteV
                 {
                     if (criterion.Branches.TryGetValue(value ?? string.Empty, out var branch))
                     {
-                        Walk(results, values, ambientValues, branch, isFallbackPath);
+                        Walk(results, values, ambientValues, branch, quality + 1m);
```
Comment (JamesNK) [inline src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: Change the quality modifier values to const fields

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs (hunk 1 above)
Comment (JamesNK) [reply src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: Makes sense. I think I tried option 3 before realizing I was out of my depth 😄

**Review by JamesNK — COMMENTED** [review]
Looks good to me.

Add the original issue's scenario as a functional test

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs (hunk 4 above)
Comment (rynowak) [reply src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: obsolete, they are gone completely

**Comment by rynowak** [comment]
@JamesNK - resolved your feedback, can you take a quick look?

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs [hunk 5]
```diff
@@ -35,7 +52,7 @@ public IList<OutboundMatchResult> GetMatches(RouteValueDictionary values, RouteV
             if (_root.Matches.Count > 0 || _root.Criteria.Count > 0)
             {
                 var results = new List<OutboundMatchResult>();
-                Walk(results, values, ambientValues ?? EmptyAmbientValues, _root, isFallbackPath: false);
+                Walk(results, values, ambientValues ?? EmptyAmbientValues, _root, isFallbackpath: false);
```
Comment (JamesNK) [inline src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: nit: wasn't it more correct before?

**Review by JamesNK — APPROVED** [review]

File: src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs (hunk 5 above)
Comment (rynowak) [reply src/Http/Routing/src/Internal/LinkGenerationDecisionTree.cs]: Oh, this is showing up as a rename. I'll fix it rq.

**Review by dougbu — COMMENTED** [review]
I don't see anything in this PR that I'm a code owner for. Am I missing something?

**Comment by rynowak** [comment]
@dougbu I dunno mang 🤷‍♂️

**Comment by rynowak** [comment]
@mkArtakMSFT this should be ready now
