### PR TITLE
Fix for: Minimal APIs and controllers treat header arrays differently

### LINKED ISSUE #54978: Minimal APIs and controllers treat header arrays differently
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Passing  comma-separated list of values to the header is treated differently by controller action and Minimal API endpoint during binding to array. For controller action they are parsed as separate values while for Minimal APIs - as single one:
Controller action:
image

Minimal API:

image

### Expected Behavior

Should behave the same way.

### Steps To Reproduce

Create controller with action:

    [HttpGet]
    public IActionResult Get([FromHeader] string[] hs) => Ok(new { Test = hs});

And minimal API endpoint:
```
app.MapGet("/test_h", ([FromHeader] string[] hs) => new {Test = hs});
```

And pass request header `hs: 1,2,3`

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by smnsht**
# Fix for: Minimal APIs and controllers treat header arrays differently #54978

Alter BindParameterFromProperty(...) method

## Description
The root cause of the issue is in `GetValueFromProperty(...)` behavior - it returns an Expression that evaluates `httpContext.Request.Headers[key]`. What we want, is to call `httpContext.Request.Headers.GetCommaSeparatedValues(key) `when the source is "header" and [FromHeader] is attached to an array.

GetCommaSeparatedValues(key) is an extension method, implemented as ParsingHelpers.GetHeaderSplit(IHeaderDictionary, string)

Fixes #54978

### CODE REVIEW

**Comment by BrennanConroy** [comment]
There is an active [PR for this](https://github.com/dotnet/aspnetcore/pull/55803) that has gone through some review and iterations.

If you want to work on this bug you should check with the original PR author and see if they aren't going to work on their fix anymore so that you can take over.

**Comment by smnsht** [comment]
@BrennanConroy 
My bad. Should I delete my PR?

**Comment by smnsht** [comment]
My bad. 

I've asked him just now.

**Comment by BrennanConroy** [comment]
Thanks for checking with them, looks like you're good to go.

I'd recommend taking a look at their PR and the reviews that took place to get an idea of what the current change might be missing.

**Comment by smnsht** [comment]
> I'd recommend taking a look at their PR and the reviews that took place to get an idea of what the current change might be missing.



1. I think a unit test with IEnumerable<string> (other PR) should not be added. This code could not be compiled

dotnet 8.0 - screenshot
image

**Confirmation would be appreciated**

2. I see there are changes in RequestDelegateGenerator.cs in other PR. I don't know yet why this change is needed, but I noticed it was explicitly requested by the maintainer. My current understanding is that I should figure this out and properly implement it.

**Confirmation would be appreciated**

**Comment by captainsafia** [comment]
> I see there are changes in RequestDelegateGenerator.cs in other PR. I don't know yet why this change is needed, but I noticed it was explicitly requested by the maintainer. My current understanding is that I should figure this out and properly implement it.

The Request Delegate Generator is the source generator implementation that compiles arbitrary delegates to RequestDelegates when you are using native AoT. The behavior between the source generator and non-source generator based implementations should be the same which is why I provided that feedback.

> I think a unit test with IEnumerable (other PR) should not be added. This code could not be compiled

This error comes from our analyzers. We'll probably want to update them so they account for the expanded support.

Also, FWIW, I do think it is probably sufficient for us to just support arrays in this binding since that's what we do elsewhere for parameters.

**Comment by smnsht** [comment]
@captainsafia 
Thanks. Going to fix that.

**Review by Jayuu22 — APPROVED** [review]

File: src/submodules/googletest
Comment (captainsafia) [inline src/submodules/googletest:1]: You'll want to revert the changes in this submodule before we're able to merge this.

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs [hunk 1]
```diff
@@ -788,4 +788,23 @@ public async Task RequestDelegatePopulatesFromOptionalFormParameterStringArray()
 
         Assert.Equal<string[]>(["hello", "bye"], (string[])httpContext.Items["message"]);
     }
+
+    [Theory]
+    [InlineData("""app.MapGet("/", ([FromHeader(Name = "q")] string[]? arr) => arr);""", "",      "[]")]
+    [InlineData("""app.MapGet("/", ([FromHeader(Name = "q")] string[]? arr) => arr);""", "a,b,c", "[\"a\",\"b\",\"c\"]")]
+    [InlineData("""app.MapGet("/", ([FromHeader(Name = "q")] int[]? arr) => arr);""",    "1,2,3", "[1,2,3]")]
+    public async Task RequestDelegateGenerator_FromHeader_CommaSeparatedValues(string source, string headerContent, string expectedBody)
```
Comment (captainsafia) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs:796]: If you move this test case to `RequestDelegateCreationTests.Arrays.cs` we'll get coverage for both compile-time and run-time code gen with a single test case.

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/Baselines/MapAction_ExplicitHeader_ComplexTypeArrayParam.generated.txt [hunk 2]
```diff
@@ -138,7 +138,7 @@ namespace Microsoft.AspNetCore.Http.Generated
                 {
                     var wasParamCheckFailure = false;
                     // Endpoint Parameter: p (Type = Microsoft.AspNetCore.Http.Generators.Tests.ParsableTodo[], IsOptional = False, IsParsable = True, IsArray = True, Source = Header)
-                    var p_raw = httpContext.Request.Headers["p"];
+                    var p_raw = httpContext.Request.Headers.GetCommaSeparatedValues("p");
```
Comment (captainsafia) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/Baselines/MapAction_ExplicitHeader_ComplexTypeArrayParam.generated.txt:141]: Nice use of the extension method here!

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 3]
```diff
@@ -1955,8 +1955,18 @@ private static Expression BindParameterFromExpression(
                 Expression.Convert(Expression.Constant(parameter.DefaultValue), parameter.ParameterType)));
     }
 
-    private static Expression BindParameterFromProperty(ParameterInfo parameter, MemberExpression property, PropertyInfo itemProperty, string key, RequestDelegateFactoryContext factoryContext, string source) =>
-        BindParameterFromValue(parameter, GetValueFromProperty(property, itemProperty, key, GetExpressionType(parameter.ParameterType)), factoryContext, source);
+    private static Expression BindParameterFromProperty(ParameterInfo parameter, MemberExpression property, PropertyInfo itemProperty, string key, RequestDelegateFactoryContext factoryContext, string source)
+    {
+        var expressionType = GetExpressionType(parameter.ParameterType);
```
Comment (captainsafia) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1960]: Are string arrays the only type that we need to handle here? Does MVC support serializing `int[]` from the header for example?

**Review by captainsafia — COMMENTED** [review]
Looking good! Left a few comments inline.

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs (hunk 1 above)
Comment (smnsht) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs]: @captainsafia 
moved

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 3 above)
Comment (smnsht) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs]: @captainsafia 

When examining `var expressionType` I am bearing in mind that only `typeof(string[])` will return from `GetExpressionType(parameter.ParameterType)` for any array. 

In other words, the line
`var valueExpression = (source == "header" && expressionType == typeof(string[]))`

Is equivalent to

`var valueExpression = (source == "header" && parameter.ParameterType.IsArray)`


I altered the code to the second version.

File: src/submodules/googletest
Comment (smnsht) [reply src/submodules/googletest:1]: @captainsafia 
Embarrassing to say, but I don't know how to revert those changes.

I've created another branch, and merged current into it, except submodules. 

Here is the draft: [github.com/dotnet/aspnetcore/pull/58592](https://github.com/dotnet/aspnetcore/pull/58592)

​Could that be the solution?

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 4]
```diff
@@ -1955,8 +1955,17 @@ private static Expression BindParameterFromExpression(
                 Expression.Convert(Expression.Constant(parameter.DefaultValue), parameter.ParameterType)));
     }
 
-    private static Expression BindParameterFromProperty(ParameterInfo parameter, MemberExpression property, PropertyInfo itemProperty, string key, RequestDelegateFactoryContext factoryContext, string source) =>
-        BindParameterFromValue(parameter, GetValueFromProperty(property, itemProperty, key, GetExpressionType(parameter.ParameterType)), factoryContext, source);
+    private static Expression BindParameterFromProperty(ParameterInfo parameter, MemberExpression property, PropertyInfo itemProperty, string key, RequestDelegateFactoryContext factoryContext, string source)
+    {
+        var valueExpression = (source == "header" && parameter.ParameterType.IsArray)
+            ? Expression.Call(
+                typeof(ParsingHelpers).GetMethod(nameof(ParsingHelpers.GetHeaderSplit), BindingFlags.Public | BindingFlags.Static, [typeof(IHeaderDictionary), typeof(string)])!,
```
Comment (captainsafia) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1962]: Nit: consider caching this at the top of the file as the other `MethodInfo` definitions.

**Review by captainsafia — APPROVED** [review]
Looks good overall! Left one small comment inline that we can use as a way to rekick the stale build for this change.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 4 above)
Comment (smnsht) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1962]: I will do this in February.
