### PR TITLE
Virtualization supports variable-height items

### LINKED ISSUE #25058: Blazor - support variable height items in Virtualize component
When create a listview of **similarly** sized items, it's very hard to virtualise this in most web frameworks currently. It'd be great for Blazor to provide an out of the box solution that is able to render a virtual list of items, and account for it's position in the list as items are rendered. Most of my implementations of lists are of items that don't vary in size all that greatly, i.e. an extra line or two of text per item due to some wrapping.

This would need to be able to handle data updates over time, so it shouldn't remember the size of the item when it goes back out of the view port and if the item is in the viewport it should account for the change in size after an update while assuming an approximate size for the not currently visible items.

My concept is to try to have the scroll bar managing the item number through the list rather than the absolute x position, then to show the item at the top that matches closest to that by %, if snapping the items makes this easier that may be an approach.

Basically you'd know the items sizes currently in the viewport, and as the user scrolls, the overall size of the view port would adjust based on the currently visible items actual size + the amount of items above * approx size + the amount of items below * approx size.

This is done well in Xamarin, but that is a non web framework so I guess it's a little easier to control the outcome.

### LINKED ISSUE #59354: Blazor Virtualize Feature Bug with Scaled Elements Causing Scroll Errors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When enabling the Virtualize feature in Blazor, if an element is set with scale, scrolling the table displays errors, resulting in flickering.

This issue was observed after Chrome version 128, likely due to the standardized CSS zoom property causing Blazor Virtualize feature to miscalculate heights.

### Expected Behavior

The table should scroll smoothly without any visual distortions, even when elements are scaled.

### Steps To Reproduce

Open https://aspnet.github.io/quickgridsamples/virtualizing

Set the body element's scale style to 0.75

Scroll the table and observe the visual errors.

### Exceptions (if any)

_No response_

### .NET Version

.net 9 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ilonatommy**
Design doc:
https://github.com/dotnet/aspnetcore/issues/65158

Visualization of how the sample works with the initial implementation (scrolling with the scroll & jumps with Ctrl + Home or Ctrl + End):

https://github.com/user-attachments/assets/6011f1a5-0b94-4d08-97cf-4c4f802d9961

### Tested scenarios

<details>

1) Dynamic Height Changes After Initial Render - :white_check_mark: covered, test added (`DynamicContent_ItemHeightChangesUpdateLayout`)

2)  Window/Container Resize - :white_check_mark: covered, tests added (`VariableHeight_ContainerResizeWorks`)

3) Extreme Height Variance - :white_check_mark: covered, tests changed to cover x100 variation.

4) Scroll Position Stability (Sticky Bottom) - ❌ Out of scope of this PR, for a follow up, see [plan](https://github.com/dotnet/aspnetcore/issues/65158#issuecomment-3847778719).

5) `ItemsProvider` with Variable Heights - :white_check_mark: covered, async tests added, slow big load tested manually (see the video)

https://github.com/user-attachments/assets/73b73a92-b7a5-49ec-a255-f0a4abab38fa

6) CSS Transform/Scale on Container - ❌ partially, transform is covered in `VariableHeightAsync_CanScrollThroughItems`
We have `getCumulativeScaleFactor()` but it only checks transform matrix. Other CSS that affects layout (zoom, perspective) are not handled, the are delegated to https://github.com/dotnet/aspnetcore/pull/64013.

7) RTL (Right-to-Left) Layout - :white_check_mark: covered in `VariableHeightAsync_CanScrollThroughItems`

8) Horizontal Virtualization Interaction ❌ Out of scope

9) Placeholder Height Mismatch -  :white_check_mark: covered by the walking average that only initially falls back to `ItemSize`

10) Empty or Single-Item Lists -  :white_check_mark: covered in `VariableHeightAsync_SmallItemCountsWork`

11) Items Collection Mutations - :white_check_mark: covered, added test `VariableHeightAsync_CollectionMutationWorks`

12) Test on Multiple Browsers :white_check_mark:
Tested on Chrome, Firefox, and WebKit — all browsers behave consistently for virtualization: same visible item counts, exact scroll position accuracy, and integer pixel height measurements. The only notable difference is WebKit's 2x device pixel ratio (simulating Retina), which results in one additional sub-pixel item being rendered (22 vs 21).

</details>

Fixes https://github.com/dotnet/aspnetcore/issues/25058, 
Fixes https://github.com/dotnet/aspnetcore/issues/64029,
Fixes https://github.com/dotnet/aspnetcore/issues/59354.

### CODE REVIEW

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 1]
```diff
@@ -112,7 +116,7 @@ public sealed class Virtualize<TItem> : ComponentBase, IVirtualizeJsCallbacks, I
     /// in the page.
     /// </summary>
     [Parameter]
-    public int OverscanCount { get; set; } = 3;
+    public int OverscanCount { get; set; } = 15;
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs:125]: This was a change planned in the design issue, see: https://github.com/dotnet/aspnetcore/issues/65158#issuecomment-3823077385.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 2]
```diff
@@ -28,6 +29,41 @@ function findClosestScrollContainer(element: HTMLElement | null): HTMLElement |
...
+
+  let current = spacerBefore.nextElementSibling;
+
+  while (current && current !== spacerAfter) {
+    const rect = current.getBoundingClientRect();
+    heights.push(rect.height / scaleFactor);
+    current = current.nextElementSibling;
+  }
+
+  return heights;
```
Comment (dariatiurina) [inline src/Components/Web.JS/src/Virtualize.ts]: How does this impact the speed? Going through every element we see between spacers and also calculating every element's scale factor seems like a lot of calculations per request.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 3]
```diff
@@ -28,6 +29,41 @@ function findClosestScrollContainer(element: HTMLElement | null): HTMLElement |
...
+    const transform = style.transform;
+    if (transform && transform !== 'none') {
+      // Parse the scale from the transform matrix
+      const match = transform.match(/matrix\(([^,]+)/);
+      if (match) {
+        scale *= parseFloat(match[1]);
+      }
+    }
+    element = element.parentElement;
+  }
```
Comment (dariatiurina) [inline src/Components/Web.JS/src/Virtualize.ts]: We should also check for `zoom` and `scale` properties, which are different from the `transform`.

Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: Zoom and scale are in the separate PR, in https://github.com/dotnet/aspnetcore/pull/64013. I added active issue to tests checking css resize other than `transform`. Do you prefer to close that PR and implement the fix straight here?

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 4]
```diff
@@ -691,4 +704,600 @@ private static void ScrollLeftToEnd(IWebDriver Browser, IWebElement elem)
...
+        // Scroll down
+        var js = (IJavaScriptExecutor)Browser;
+        js.ExecuteScript("arguments[0].scrollTop = 100", container);
+
+        // Wait for scroll to take effect
+        Browser.True(() => (long)js.ExecuteScript("return arguments[0].scrollTop", container) >= 100);
+
+        // After scrolling, verify that items still render (component didn't break)
+        Browser.True(() => GetElementCount(container, ".variable-height-item") > 0);
+    }
```
Comment (dariatiurina) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs]: Isn't this test just a smaller copy of the `VariableHeight_CanScrollThroughAllItems`?

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 5]
```diff
@@ -691,4 +704,600 @@ private static void ScrollLeftToEnd(IWebDriver Browser, IWebElement elem)
...
+        });
+        CollectVisibleIndices();
+
+        // Verify we saw all 100 items (indices 0-99)
+        Assert.Equal(100, seenIndices.Count);
+        for (int i = 0; i < 100; i++)
+        {
+            Assert.Contains(i, seenIndices);
+        }
+    }
```
Comment (dariatiurina) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs]: Can we add check here that the upper element does not gets reversed (e.g. 2 -> 1), while scrolling down.

**Comment by ilonatommy** [comment]
`QuickGrid_SupportsVariableHeightRows` failures are caused by https://github.com/dotnet/aspnetcore/issues/64029.
Source of problem: `OnAfterSpacerVisible` forces scroll down always when the after-spacer is visible. Even on first render when we go from 0 items loaded to N items, we trigger the scroll.
Fix: The scroll should not happen on first render.

File: src/Components/Web.JS/src/Virtualize.ts (hunk 3 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: Solved in https://github.com/dotnet/aspnetcore/pull/64964/commits/545e5ab489e2eeb1473a98c99481d6768de27a33. The pass through DOM was replaced with dividing physical height (`getBoundingClientRect().height`) by logical height (`HTMLElement.offsetHeight`). That gives us effective scale in O(1).

File: src/Components/Web.JS/src/Virtualize.ts (hunk 2 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: After the scale calculation update where we calculate it once per batch, the only concern from this comment that is still valid is "going through each element between spacers". 

Typically, these will be ~10-50 elements. Each `getBoundingClientRect()` is O(1) when layout is stable and the reads do not contain any writes (e.g. `item.getBoundingClientRect()` with `item.style.height = newValue` in a loop) because the browser should batch the calculations - do them once per layout and cache.

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 6]
```diff
@@ -292,16 +296,36 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
...
+
+    private void ProcessMeasurements(float[]? itemHeights)
+    {
+        if (itemHeights is not { Length: > 0 })
+        {
+            return;
+        }
+
+        _totalMeasuredHeight += itemHeights.Sum();
+        _measuredItemCount += itemHeights.Length;
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: `getScaleFactor` in JS already checks for finite numbers. Height=0 is taken care of by `CalculateItemDistribution`. Resolved.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 7]
```diff
@@ -81,29 +135,55 @@ function init(dotNetHelper: DotNet.DotNetObject, spacerBefore: HTMLElement, spac
...
+    const { heights: measurements, scaleFactor } = measureRenderedItems(spacerBefore);
+
+    // To compute the ItemSize, work out the separation between the two spacers. We can't just measure an individual element
+    // because each conceptual item could be made from multiple elements. Using getBoundingClientRect allows for the size to be
+    // a fractional value. It's important not to add or subtract any such fractional values (e.g., to subtract the 'top' of
+    // one item from the 'bottom' of another to get the distance between them) because floating point errors would cause
+    // scrolling glitches.
+    rangeBetweenSpacers.setStartAfter(spacerBefore);
+    rangeBetweenSpacers.setEndBefore(spacerAfter);
+    const spacerSeparation = rangeBetweenSpacers.getBoundingClientRect().height / scaleFactor;
```
Comment (ilonatommy) [inline src/Components/Web.JS/src/Virtualize.ts:326]: Moving the calculations that are common for both spacers out of the loop to optimize.

**Comment by ilonatommy** [comment]
The jump is real for cases with css transformations. We can test it deterministically only on WASM in E2E test. Captured in slow motion with zoom 200%:

https://github.com/user-attachments/assets/0ac05e94-7161-454a-aad3-fb14c5133a37

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 8]
```diff
@@ -112,7 +118,7 @@ public sealed class Virtualize<TItem> : ComponentBase, IVirtualizeJsCallbacks, I
     /// in the page.
     /// </summary>
     [Parameter]
-    public int OverscanCount { get; set; } = 3;
+    public int OverscanCount { get; set; } = 15;
```
Comment (ilonatommy) [inline src/Components/Web/src/Virtualization/Virtualize.cs:125]: ToDo: `QuicGrid` also has `OverscanCount`, make sure the new value is inlined in both.

File: src/Components/test/E2ETest/ServerExecutionTests/TestSubclasses.cs [hunk 9]
```diff
@@ -90,6 +90,24 @@ public ServerVirtualizationTest(BrowserFixture browserFixture, ToggleExecutionMo
...
+    [InlineData(100, 100, 200)]
+    [InlineData(75, 75, 75)]
+    [InlineData(150, 150, 150)]
+    public override void VariableHeightAsync_CanScrollWithoutFlashing(int transformScalePercent, int cssZoomPercent, int cssScalePercent)
+    {
+        // Intentionally empty - skipped via Theory(Skip) attribute above.
+        _ = transformScalePercent;
+        _ = cssZoomPercent;
+        _ = cssScalePercent;
+    }
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerExecutionTests/TestSubclasses.cs]: Not sure how you are "detecting" flashing, but one option here to avoid unreliability, is to use a MutationObserver to log changes to a given dom subtree, or an intersection observer to do the same thing. You can perform the interactions and then read "the log" afterwards to validate it does what you expect.

Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerExecutionTests/TestSubclasses.cs]: Doesn't `MutationObserver` observe only changes to DOM? How can it see that something that is in DOM just shifted up/down a few pixels if no new load to DOM was triggered?

Comment (javiercn) [reply src/Components/test/E2ETest/ServerExecutionTests/TestSubclasses.cs]: It was one potential option, another option could be `IntersectionObserver` or scroll events. What I was trying to get at, is the strategy. Setup a callback with a relevant DOM event, and capture information when it gets triggered as opposed to trying to check against a DOM element if that was giving you problems.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 8 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs:125]: After reconsideration, `QuickGrid` items are heavier than Virtualization items. Having N columns, overscan of 15 would load 30xN hidden items to DOM.

Higher overscan matters most when variance between item heights are extreme (e.g. x100) and we have few visible items. I think we can assume grids do not meet these conditions. Leaving the default overscan in `QuickGrid`.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 10]
```diff
@@ -81,29 +180,113 @@ function init(dotNetHelper: DotNet.DotNetObject, spacerBefore: HTMLElement, spac
...
+      return;
+    }
+
+    const { heights: measurements, scaleFactor } = measureRenderedItems(spacerBefore, spacerAfter);
+
+    // To compute the ItemSize, work out the separation between the two spacers. We can't just measure an individual element
+    // because each conceptual item could be made from multiple elements. Using getBoundingClientRect allows for the size to be
+    // a fractional value. It's important not to add or subtract any such fractional values (e.g., to subtract the 'top' of
+    // one item from the 'bottom' of another to get the distance between them) because floating point errors would cause
+    // scrolling glitches.
```
Comment (dariatiurina) [inline src/Components/Web.JS/src/Virtualize.ts]: You say in this comment `It's important not to add or subtract any such fractional values` but then later use `const spacerSize = (entry.intersectionRect.top - entry.boundingClientRect.top) / scaleFactor;`. Is this comment a legacy one that needs to be revised?

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 11]
```diff
@@ -257,10 +274,14 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
...
 
-            // Render the loaded items.
+            // Render the loaded items, each wrapped in an element for JS measurement.
             foreach (var item in itemsToShow)
             {
+                builder.OpenElement(_lastRenderedItemCount, ItemWrapperElement);
+                builder.AddAttribute(1, "data-virtualize-item", true);
+                builder.SetKey(item);
                 _itemTemplate(item)(builder);
+                builder.CloseElement();
```
Comment (oroztocil) [inline src/Components/Web/src/Virtualization/Virtualize.cs]: I don't know how much we care about these things, but the additional wrapper element might break existing CSS rules. E.g.:

```css
/* Before: this worked */
.my-container > .item { ... }

/* After: .item is now grandchild, not direct child */
.my-container > div[data-virtualize-item] > .item { ... }
```

Do we document such a change? At least mention it in the `ItemContent`/`ChildContent` XML comment..?

I guess we do not want to make the added element opt-outable, right?

File: src/Components/Web.JS/src/Virtualize.ts [hunk 12]
```diff
@@ -28,12 +30,44 @@ function findClosestScrollContainer(element: HTMLElement | null): HTMLElement |
...
+}
+
+interface MeasurementResult {
+  heights: number[];
+  scaleFactor: number;
+}
+
+function measureRenderedItems(spacerBefore: HTMLElement, spacerAfter: HTMLElement): MeasurementResult {
+  const scaleFactor = getScaleFactor(spacerBefore, spacerAfter);
+  const items = spacerBefore.parentElement?.querySelectorAll<HTMLElement>('[data-virtualize-item]');
```
Comment (oroztocil) [inline src/Components/Web.JS/src/Virtualize.ts]: Can there be nested Virtualize components? If yes, this would pick all item elements in the subtree, including the ones from the nested component.

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 13]
```diff
@@ -59,6 +59,12 @@ public sealed class Virtualize<TItem> : ComponentBase, IVirtualizeJsCallbacks, I
 
     private bool _loading;
 
+    internal float _totalMeasuredHeight;
+
+    internal int _measuredItemCount;
+
+    internal bool _pendingScrollToBottom;
```
Comment (oroztocil) [inline src/Components/Web/src/Virtualization/Virtualize.cs:70]: Non-private mutable fields - read as internal just in tests? Could this be refactored?

File: src/Components/Web.JS/src/Virtualize.ts [hunk 14]
```diff
@@ -50,14 +84,79 @@ function init(dotNetHelper: DotNet.DotNetObject, spacerBefore: HTMLElement, spac
...
+    } else {
+      stopObservingContainer();
+    }
+  });
+
+  function startObservingContainer(): void {
+    if (observingContainer) return;
+    observingContainer = true;
+    if (spacerBefore.parentElement) {
+      containerObserver.observe(spacerBefore.parentElement, { childList: true, subtree: true, attributes: true });
```
Comment (oroztocil) [inline src/Components/Web.JS/src/Virtualize.ts]: Does this need `subtree: true` and/or `attributes: true`? Is not detecting changes to the `childList` on the container enough for the logic? If yes, we could save a little perf hit from the observer.

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 15]
```diff
@@ -148,6 +157,8 @@ public async Task RefreshDataAsync()
         // We don't auto-render after this operation because in the typical use case, the
         // host component calls this from one of its lifecycle methods, and will naturally
         // re-render afterwards anyway. It's not desirable to re-render twice.
+        _totalMeasuredHeight = 0;
+        _measuredItemCount = 0;
         await RefreshDataCoreAsync(renderOnSuccess: false);
```
Comment (oroztocil) [inline src/Components/Web/src/Virtualization/Virtualize.cs:163]: After refresh, `GetItemHeight()` falls back to `_itemSize` (the computed item size from the last spacer separation) rather than `ItemSize` (the user-provided default). If the previous `_itemSize` was computed from stale data, the initial estimate after refresh might be wrong. Consider resetting `_itemSize = ItemSize` as well.

File: src/Components/Web/test/Virtualization/VirtualizeTest.cs [hunk 16]
```diff
@@ -92,13 +93,616 @@ public async Task Virtualize_DispatchesExceptionsFromItemsProviderThroughRendere
...
+            callbacks.OnAfterSpacerVisible(0f, 500f, 500f, new float[] { 50f, 50f, 50f }));
+
+        await renderer.Dispatcher.InvokeAsync(() =>
+            callbacks.OnBeforeSpacerVisible(5000f, 500f, 500f, new float[] { 50f, 50f }));
+
+        Assert.Contains(requests, r => r.StartIndex > 0);
+    }
+
+    [Fact]
+    public async Task Virtualize_NaNMeasurementsDoNotCrashComponent()
```
Comment (oroztocil) [inline src/Components/Web/test/Virtualization/VirtualizeTest.cs:276]: Could/should we also test that NaN measurement do not pollute the running average (making it also NaN)? Or is that guaranteed when the logic does not crash?

**Review by oroztocil — COMMENTED** [review]
Adding some minor/nit comments. I can take a deeper look later.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 11 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Making it opt-out would mean disabling variable height feature. I don't think we would like to support two modes: fixed and variable items one.
It is indeed a breaking change that needs documentation. XML comment looks like a good idea, I don't see any common breaking changes doc. @javiercn?

File: src/Components/Web.JS/src/Virtualize.ts (hunk 12 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: This looks niche but we have pre-existing `VirtualizationBimodal` with "Virtualization bimodal/nested/large" -> I conclude it's a supported scenario. That one works:

https://github.com/user-attachments/assets/a659edf6-a475-4276-8f1e-ff678f8dddf5

I will try to find a case where it would break.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 13 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs:70]: Yes, they are internal for test purposes. This is a pattern we use for unit tests that should access internal state and rendered output would not catch that.

File: src/Components/Web.JS/src/Virtualize.ts (hunk 12 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: I added a check for "too many items loaded" to `NestedVirtualize_BothRenderIndependently` that exercises fixed height items and a new test `NestedVariableHeight_OuterMeasurementsNotPollutedByInner` that does same for variable height items.

File: src/Components/Web.JS/src/Virtualize.ts (hunk 14 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: There are cases when watching only `childList` would not be enough, e.g. when spacer goes from non-zero height to 0 (converges). If we relied on `childList` only, it would work for additions/removals cases, nothing else.
Convergence code matters most in cases when an averaged-heighed placeholders load their much-more-than-average-height contents with a delay.

File: src/Components/Web/test/Virtualization/VirtualizeTest.cs (hunk 16 above)
Comment (ilonatommy) [reply src/Components/Web/test/Virtualization/VirtualizeTest.cs:276]: The code is guaranteed not to crash because JS has the check for `Number.isFinite` but it's doing that check on accumulated measurements. That can be improved, we can check each measurement for NaN.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 15 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs:163]: If we clean the `_itemSize` then scroll position will be lost. Refresh is used e.g. when new chat messages arrive. If you allow to forget the previous average size, each new message will scroll the view up, driving the reader crazy 😉 

Refreshing to load completely new data from 0-Nth, e.g. to switch between Products to Users in the same virtualization instance, is not a proper way to use virtualization. `ItemsProvider` should be changed to achieve this, not refresh the data.

File: src/Components/Web.JS/src/Virtualize.ts (hunk 10 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: Thank you. The problem here is that the old comment explains why `spacerSeparation` uses a single Range `rect` instead of summing individual element sizes. In the new code it still avoids floating point operations but we have a new code: `spacerSize` calculation that takes this risk.

I tried to check in the first place if we can avoid the floating point errors and calculate `spacerSize` in a different way but I don't see any option for that. However, the +-1 erorrs that spacer calculations can have should be consumed by the over scan elements loaded in advance

I updated the comment to be more clear.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 11 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Created a breaking change issue for this: https://github.com/dotnet/docs/issues/52315.

File: src/Components/test/testassets/BasicTestApp/QuickGridTest/QuickGridVariableHeightComponent.razor [hunk 17]
```diff
@@ -0,0 +1,77 @@
...
+    private bool _dataLoaded;
+
+    int ItemsProviderCallCount = 0;
+
+    protected override void OnInitialized()
+    {
+        variableHeightProvider = async request =>
+        {
+            await Task.Yield();
+            Interlocked.Increment(ref ItemsProviderCallCount);
```
Comment (javiercn) [inline src/Components/test/testassets/BasicTestApp/QuickGridTest/QuickGridVariableHeightComponent.razor]: You don't need interlocked. You can just do `ItemsProviderCallCount++`

File: src/Components/test/testassets/BasicTestApp/VirtualizationVariableHeightAsync.razor [hunk 18]
```diff
@@ -0,0 +1,200 @@
+<p>
+    Variable Height Items with Async ItemsProvider:<br />
+    <label><input id="toggle-autoload" type="checkbox" checked="@autoLoad" @onchange="ToggleAutoLoad" /> Auto-load items</label>
```
Comment (javiercn) [inline src/Components/test/testassets/BasicTestApp/VirtualizationVariableHeightAsync.razor:9]: For tests as "complex" as these ones, it's good to provide a high-level description of the test scenario at the top of the file. Either as a comment or just some `<p>` if it doesn't impact the test. I'm breaking my head a bit to reason through the tests

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 19]
```diff
@@ -292,48 +314,71 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
...
+        }
 
-        // Since we know the before spacer is now visible, we absolutely have to slide the window up
-        // by at least one element. If we're not doing that, the previous item size info we had must
-        // have been wrong, so just move along by one in that case to trigger an update and apply the
-        // new size info.
-        if (itemsBefore == _itemsBefore && itemsBefore > 0)
+        _totalMeasuredHeight += itemHeights.Sum();
+        _measuredItemCount += itemHeights.Length;
+        return true;
```
Comment (javiercn) [inline src/Components/Web/src/Virtualization/Virtualize.cs]: We send the itemHeights are immediately aggregated and then thrown away. Instead of sending an array between JS and .NET can we compute the sum and the length and send that to .NET instead?

File: src/Components/Web.JS/src/Virtualize.ts [hunk 20]
```diff
@@ -56,14 +91,79 @@ function init(dotNetHelper: DotNet.DotNetObject, spacerBefore: HTMLElement, spac
   intersectionObserver.observe(spacerBefore);
   intersectionObserver.observe(spacerAfter);
 
+  let observingContainer = false;
+
   const mutationObserverBefore = createSpacerMutationObserver(spacerBefore);
   const mutationObserverAfter = createSpacerMutationObserver(spacerAfter);
 
+  const containerObserver = new MutationObserver((): void => {
```
Comment (javiercn) [inline src/Components/Web.JS/src/Virtualize.ts]: Is there a reason why we can't use a ResizeObserver for this?

Comment (javiercn) [reply src/Components/Web.JS/src/Virtualize.ts]: I think the current convergence mechanism is using too broad a signal.

Right now, the sticky top/bottom behavior is effectively driven by a container-wide `MutationObserver` in [Virtualize.ts](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web.JS/src/Virtualize.ts#L99), which gets turned on from [startObservingContainer](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web.JS/src/Virtualize.ts#L114) when we enter the top/bottom convergence paths in [onSpacerAfterVisible](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web.JS/src/Virtualize.ts#L215) and [onSpacerBeforeVisible](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web.JS/src/Virtualize.ts#L236).

I think we can make this both narrower and more correct without changing the rendered markup:

1. Keep the existing `IntersectionObserver` only for the initial trigger when a spacer becomes relevant, as in [processIntersectionEntries](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web.JS/src/Virtualize.ts#L257).
2. Replace the broad container `MutationObserver` with `ResizeObserver` on:
   - the active spacer
   - each currently realized direct child element
3. After the initial push to top or bottom, any subsequent push should happen because either:
   - the spacer resized, or
   - one of the realized elements resized
4. Refresh the observed realized-element set after `Virtualize` rerenders from the .NET side in [Virtualize.cs](https://github.com/ilonatommy/aspnetcore/blob/fix-25058-variable-height/src/Components/Web/src/Virtualization/Virtualize.cs#L214).

In other words: the thing we actually care about is geometry changing, not arbitrary subtree mutation. `ResizeObserver` maps directly to that. `IntersectionObserver` can do the initial push, and `ResizeObserver` can drive the follow-up pushes while we converge.

This would let us remove a lot of the current mutation-driven behavior, avoid reacting to unrelated subtree churn, and keep the implementation aligned with the real reason we need to re-push: the measured layout changed.

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 21]
```diff
@@ -257,10 +275,14 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
 
             builder.OpenRegion(5);
 
-            // Render the loaded items.
+            // Render the loaded items, each wrapped in an element for JS measurement.
             foreach (var item in itemsToShow)
             {
+                builder.OpenElement(_lastRenderedItemCount, ItemWrapperElement);
```
Comment (javiercn) [inline src/Components/Web/src/Virtualization/Virtualize.cs]: What is this meant to achieve? This is considered an "anti-pattern" for the diffing algorithm. Any reason why this couldn't just receive `0`? (But beyond that, introducing a wrapper element is a breaking change, it's not something that we should do unless we have a forcing reason to do so).

Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Index should start from `0`, correct.

> What is this meant to achieve?

We have to measure the elements in JS somehow. Without wrapping virtualization item, we cannot tell where they begin and finish because `itemTemplate` is defined by the user and can be anything. It can e.g. render 2 root elements. If we choose to walk the DOM siblings from one spacer to the other instead of selecting the wrapping element, we will treat these 2 elements as 2 separate items -> polluting the average.

 It is a breaking change, indeed https://github.com/dotnet/aspnetcore/pull/64964#discussion_r2924096449.

Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Is using comments a good alternative "wrapper" here? We are relying on comments in streaming. That would not break anyone.

Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Addressed in https://github.com/dotnet/aspnetcore/pull/64964/commits/5b12a885f53ce0d6e3a5a9b991844d774c8f02c1.

Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Reverted after hitting failures [log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1341161/logs/14). It needs more investigation.

File: src/Components/Web.JS/src/Virtualize.ts (hunk 20 above)
Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: Addressed in https://github.com/dotnet/aspnetcore/pull/64964/commits/a1b9614743c374d4f2175c76a346e57bf7053211.

Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: This broke WASM scrolling tests [log](https://[dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1342574/logs/14](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/1342574/logs/14)), investigating.

Comment (ilonatommy) [reply src/Components/Web.JS/src/Virtualize.ts]: Should be fixed with https://github.com/dotnet/aspnetcore/pull/64964/commits/a0dd4435a09dd752ce099692219c53de517b687f.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 21 above)
Comment (ilonatommy) [reply src/Components/Web/src/Virtualization/Virtualize.cs]: Fixed in https://github.com/dotnet/aspnetcore/pull/64964/changes/4e7a9b119dda82576bec7a230cf4fd13cdc291e7, https://github.com/dotnet/aspnetcore/pull/64964/changes/29b11481bd310f97eb40e7705a7eefc92be98318.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 22]
```diff
@@ -28,6 +32,49 @@ function findClosestScrollContainer(element: HTMLElement | null): HTMLElement |
...
+
+  // Measure total height from first to last delimiter. Using a single Range
+  // naturally includes any table border-spacing between rows.
+  const heightCount = delimiters.length - 1;
+  const range = document.createRange();
+  range.setStartAfter(delimiters[0]);
+  range.setEndBefore(delimiters[delimiters.length - 1]);
+  const heightSum = range.getBoundingClientRect().height / scaleFactor;
+
+  return { heightSum, heightCount, scaleFactor };
```
Comment (javiercn) [inline src/Components/Web.JS/src/Virtualize.ts:75]: Here we can probably just emit a comment at the end of the virtualize render cycle with the total item count. We don't need to know the boundaries between individual items themselves

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 23]
```diff
@@ -692,6 +737,1097 @@ private static void ScrollLeftToEnd(IWebDriver Browser, IWebElement elem)
...
+                    }
+                    
+                    if (currentTopItemIndex !== null) {
+                        previousTopItemIndex = currentTopItemIndex;
+                    }
+                    maxIndexSeen = Math.max(maxIndexSeen, getMaxIndex());
+                }
+                
+                done({ success: true, maxIndexSeen });
+            })();";
```
Comment (javiercn) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs:1383]: Nit: stuff like this deserves to be on a helper and have some comment about what its doing

**Review by javiercn — APPROVED** [review]
Absolutely fantastic. Awesome job on the thorough set of E2E test coverage for different display modes and other CSS elements that can impact the behavior of virtualize.

**Comment by ilonatommy** [comment]
/ba-g failures of signalR tests and functional tests are not connected, they fail also on other PRs
