### PR TITLE
Cache request values when hosting metrics are enabled

### LINKED ISSUE #55280: http.server.active_requests metric incorrect when behind TLS-terminating load balancer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With aspnetcore hosted behind a TLS terminating load balancer and `ForwardedHeadersMiddleware` configured with `XForwardedProto` the metric for http.server.active_requests is incorrectly handled.

The ForwardedHeadersMiddleware is changing the value of `HttpContext.Request.Scheme` from `http` to `https` but this occurs after the `HostingMetrics` class has recorded the request start using `scheme=http`

At the end of the request, it records the request ending, this time with `scheme=https`

The end result is that the UpDownCounter is incremented by 1 with scheme=http, and decremented by 1 with scheme=https making a mess of the metrics after a period of running you end up with metrics like:

```
http.server.active_requests{ http_request_method="GET", url_scheme="http"} = 100
http.server.active_requests{ http_request_method="GET", url_scheme="https"} = -100
```

### Expected Behavior

The metric needs to be incremented/decremented with a consistent scheme.

In this instance `http` probably makes the most sense

### Steps To Reproduce

https://github.com/petedishman/metrics-bug contains a project that reproduces the error

- Run the project `dotnet run`
- view metrics at `http://localhost:81/metrics`
- Make a request like a load balancer: `invoke-webrequest -Uri http://localhost:81/ -Headers @{'X-Forwarded-For' = '127.0.0.1'; 'X-Forwarded-Proto' = 'https';}`
- refresh metrics and see `http_server_active_requests` values

### Exceptions (if any)

_No response_

### .NET Version

8.0.200

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/55280

Hosting metrics use data on `HttpContext` when writing tag values. For example, the HTTP method of a request is metadata when writing metrics.

However, the context is mutable, which means that someone can modify the values used by hosting metrics during the request pipeline. This has the worst impact on the active requests counter, which depends on tags being the same for the start and the end of the request. If tags don't match then you end up with two dimensions, one going up and the other going down:

```
http.server.active_requests{ http_request_method="GET", url_scheme="http"} = 100
http.server.active_requests{ http_request_method="GET", url_scheme="https"} = -100
```

Fix is to stash the initial values on the context (this PR puts them on the metrics tags feature which is on the context) when the request starts and then use the stashed values at the end of the request.

There is slightly more memory used per request when metrics are enabled (3 additional fields), and no impact when metrics are disabled.

### CODE REVIEW

**Review by mgravell — APPROVED** [review]
LGTM

File: src/Hosting/Hosting/src/Internal/HttpMetricsTagsFeature.cs [hunk 1]
```diff
@@ -10,4 +10,19 @@ internal sealed class HttpMetricsTagsFeature : IHttpMetricsTagsFeature
...
 
     public List<KeyValuePair<string, object?>> TagsList { get; } = new List<KeyValuePair<string, object?>>();
+
+    // Cache request values when request starts. These are used when writing metrics when the request ends.
+    // This ensures that the tags match between the start and end of the request.
+    public string? Method { get; set; }
+    public string? Scheme { get; set; }
+    public string? Protocol { get; set; }
+
+    public void Reset()
```
Comment (BrennanConroy) [inline src/Hosting/Hosting/src/Internal/HttpMetricsTagsFeature.cs:20]: Unused?

**Review by BrennanConroy — APPROVED** [review]

File: src/Hosting/Hosting/src/Internal/HttpMetricsTagsFeature.cs (hunk 1 above)
Comment (JamesNK) [reply src/Hosting/Hosting/src/Internal/HttpMetricsTagsFeature.cs:20]: Thanks, I meant for this to be used to clear out cached values.
