### PR TITLE
Apply hosting environment via command line args

### LINKED ISSUE #33889: WebApplicationFactory<T> does not default to Development environment with minimal hosting
### Describe the bug

Compared to the use cases for `IHostBuilder` and `IWebHostBuilder`, `WebApplicationFactory<T>` does not set the default environment for the application under test to `Development` when the code path for minimal hosting is used.

https://github.com/dotnet/aspnetcore/blob/9a451a36297f5e24f40b08ce59bfdb1f8f287ea0/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L383

https://github.com/dotnet/aspnetcore/blob/dbf84eaa5a8f79947647ad64a785d39e7cd23afe/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L402

https://github.com/dotnet/aspnetcore/blob/dbf84eaa5a8f79947647ad64a785d39e7cd23afe/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L152-L178

Adding the missing line itself does not seem to work though, possibly related to #33876 - ~I've got some tests from debugging this locally I'll push up into a PR shortly~ see #33890.

### To Reproduce

Inspect the `IHostEnvironment.EnvironmentName` property in, for example, the [`HelloWorld`](https://github.com/dotnet/aspnetcore/blob/9a451a36297f5e24f40b08ce59bfdb1f8f287ea0/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs#L21-L32) test.

https://github.com/dotnet/aspnetcore/blob/9a451a36297f5e24f40b08ce59bfdb1f8f287ea0/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs#L21-L32

### Further technical details

* ASP.NET Core `6.0.0-preview.6.21323.4`
* .NET SDK `6.0.100-preview.6.21324.1`
* Visual Studio 2022 17.0.0 Preview 1.1

### PR DESCRIPTION
**Pull request by davidfowl**
- This makes sure that the entire application can see changes to host configuration (env, content root etc).
- Added tests to verify those scenarios
- One caveat is that the application can still override the test values manually (fore.g not passing the args)

Fixes https://github.com/dotnet/aspnetcore/issues/33889

### CODE REVIEW

File: src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs [hunk 1]
```diff
@@ -89,23 +102,75 @@ public async Task ActionReturningMoreThanOneResult_NotFound()
...
+        public async Task Configuration_Can_Be_Overridden()
         {
+            // Arrange
+            var fixture = _fixture.WithWebHostBuilder(builder =>
+            {
+                builder.ConfigureAppConfiguration(builder =>
+                {
+                    var config = new[]
+                    {
+                        KeyValuePair.Create("Greeting", "Bonjour tout le monde"),
```
Comment (martincostello) [inline src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs:140]: You kept it 😄

File: src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs [hunk 2]
```diff
@@ -38,8 +40,18 @@ public DeferredHostBuilder()
...
         public IHost Build()
         {
+            // Hosting configuration is being provided by args so that
+            // we can impact WebApplicationBuilder based applications.
+            var args = new List<string>();
+
+            // Transform the host configuration into command line arguments
+            foreach (var section in _hostConfiguration.GetChildren())
+            {
+                args.Add($"--{section.Key}={section.Value}");
```
Comment (martincostello) [inline src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: Does this need to worry about escaping anything if there's a funky key with a space in it or something?

Comment (davidfowl) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: I think it needs to handle complex keys as well. I'm guessing that scenario might be broken as well.

Comment (davidfowl) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs]: I don't know that I need to handle spaces since the args are already in their own array element. https://source.dot.net/#Microsoft.Extensions.Configuration.CommandLine/CommandLineConfigurationProvider.cs,99f51fe8a25ff886

Comment (martincostello) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs]: Cool - I thought I'd just mention it in case there was some nuance to it somewhere 👍

File: src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs [hunk 3]
```diff
@@ -1,30 +1,37 @@
-// Licensed to the .NET Foundation under one or more agreements.
-// The .NET Foundation licenses this file to you under the MIT license.
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
```
Comment (pranavkm) [inline src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs:2]: Undo

File: src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs [hunk 4]
```diff
@@ -38,8 +40,18 @@ public DeferredHostBuilder()
...
         public IHost Build()
         {
+            // Hosting configuration is being provided by args so that
+            // we can impact WebApplicationBuilder based applications.
+            var args = new List<string>();
+
+            // Transform the host configuration into command line arguments
+            foreach (var (key, value) in _hostConfiguration.AsEnumerable())
+            {
+                args.Add($"--{key}={value}");
```
Comment (pranavkm) [inline src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: Do we need to do any fancy escaping for `value`? Like can values have spaces which would break config parsing? I'm not super familiar with this area

File: src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs [hunk 5]
```diff
@@ -159,6 +159,7 @@ private void EnsureServer()
             if (builder is null)
             {
                 var deferredHostBuilder = new DeferredHostBuilder();
+                deferredHostBuilder.UseEnvironment(Environments.Development);
```
Comment (pranavkm) [inline src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:162]: What's this about?

**Review by pranavkm — COMMENTED** [review]
I'm not familiar enough with this area to sign off. @halter73 could you look at this?

File: src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs (hunk 5 above)
Comment (davidfowl) [reply src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:162]: This is the bug being fixed. We do it in the other 2 cases but not in this one 
1. https://github.com/dotnet/aspnetcore/blob/18a926850f7374248e687ee64390e7f10514403f/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L384
2. https://github.com/dotnet/aspnetcore/blob/18a926850f7374248e687ee64390e7f10514403f/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L403

File: src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs (hunk 4 above)
Comment (davidfowl) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: I don't see how it breaks given how the [parsing works](https://github.com/dotnet/runtime/blob/cf52b7e38d28b7e28358cee052effe0ed47efb2e/src/libraries/Microsoft.Extensions.Configuration.CommandLine/src/CommandLineConfigurationProvider.cs#L44). We're not parsing the command line string, we're parsing each arg. 

I also don't see a way to escape `-` or `/` so that might be the only problem.

File: src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs (hunk 3 above)
Comment (davidfowl) [inline src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs:2]:
```suggestion
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
```

File: src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs (hunk 4 above)
Comment (halter73) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: An `=` in the key would also mess this up, right? I'm not sure how realistic that is.

**Review by halter73 — APPROVED** [review]

File: src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs (hunk 4 above)
Comment (halter73) [reply src/Mvc/Mvc.Testing/src/DeferredHostBuilder.cs:50]: > I also don't see a way to escape - or / so that might be the only problem.

You could always base64 encode/decode. Stripping and adding back the `=` padding characters might be a pain though.
