### PR TITLE
[SignalR] Ignore ODE with AsyncEnumerables

### LINKED ISSUE #28241: SignalR Stream is will throw when combined with ToObservable from IX.net, and the stream completes.
```
public class FooHub : Hub
{
    public IAsyncEnumerable<int> Foo()
    {
        return AsyncEnumerable.Empty<int>();
    }
}

public static class Program
{
    public async Task Main()
    {
         await new HubConnectionBuilder()
              .WithUrl(....)
             .Build()
             .StreamAsync(nameof(FooHub.Foo))
             .ToObservable()
            .Do(x => Console.WriteLine(x))
            .ToTask();
    }
}

```
This will throw an exception of CancellationTokenSource ObjectDisposedException.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/28241

### CODE REVIEW

File: src/SignalR/common/Shared/AsyncEnumerableAdapters.cs [hunk 1]
```diff
@@ -66,7 +67,16 @@ public IAsyncEnumerator<TResult> GetAsyncEnumerator(CancellationToken cancellati
...
-                        ((CancellationTokenSource)ctsState).Cancel();
+                        try
+                        {
+                            ((CancellationTokenSource)ctsState).Cancel();
+                        }
+                        catch (ObjectDisposedException)
+                        {
+                            // cancellationToken is passed in by the user, and if they call cancel after the
+                            // enumerator is finished but before the enumerator is disposed
+                            // then _cts might already be disposed by our wrapping code
```
Comment (halter73) [inline src/SignalR/common/Shared/AsyncEnumerableAdapters.cs:78]: I don't think we should be throwing first-chance exceptions for a fairly common usage pattern. Can we combine MakeCancelableTypedAsyncEnumerable with CastIAsyncEnumerable in a way that ensures the registration is always disposed before CastIAsyncEnumerable disposes the CTS? The current layering makes it difficult, but if those were combined it should be easy enough.

We could also consider not disposing the CTS at all, but I'd prefer disposing it if it's straightforward enough.

Comment (BrennanConroy) [reply src/SignalR/common/Shared/AsyncEnumerableAdapters.cs]: I went with the second option as fixing the layering will probably lead to a lot of duplicate code. And layering asyncenumerables on top of each other started annoying me 😆

**Review by halter73 — APPROVED** [review]
