### PR TITLE
[Blazor] Avoid fetching new page content when only the hash changes

### LINKED ISSUE #52583: Blazor: Let browser handle hash change
## Background and Motivation

As I can see there are 3 cases with hash:
a. Navigate to a hash on a **different** page. That was addressed in #8393 
b. Blazor uses hash for page navigation. That is #6175 .
c. Navigate to a hash on the **current** page. 

This request is to address the latter.

As I can see there are 3 behaviors that a developer might want:

1. Let the browser deal with it.
2. DOM event listener for `popstate` or `hashchange` and handle navigation event via javascript.
3. SSR (current)

The current behavior for `blazor.web.js` is pretty broken IMHO: Blazor makes a full intercept and a full SSR and then uses the feature from #8393 to navigate to the element.

From the point of view of Blazor 1 and 2 are identical in the fact that if Blazor does nothing, that is the default browser behavior.

## Proposed API

Add `ignoreHashNavigationOnSamePage` to `SsrStartOptions`.

Alternatively, respect `<meta name="ignoreHashNavigationOnSamePage" />` (or something similar), so the individual page can handle it through `<HeadContent>`.

Alternatively, my preferred behavior: make it the default (It makes no sense to do a SSR on same-page hash change).

## Risks

There might be someone somewhere that actually reads url hash server-side.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
## Avoid fetching new page content when only the hash changes

Fixes an issue where a page request is made after clicking a link that only updates the hash part of the URL.

The PR fixes the bug by updating the behavior to match what browsers do by default - if the hash is the only part of the URL that changes, scroll to the element with the ID of the new hash.

This was already implemented correctly for interactive routing, so this PR updates enhanced navigation to share the same logic.

Fixes #52583

### CODE REVIEW

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 1]
```diff
@@ -47,6 +47,32 @@ export function isWithinBaseUriSpace(href: string) {
...
+
+export function scrollToElement(identifier: string): boolean {
+  const element = document.getElementById(identifier);
+
+  if (element) {
+    element.scrollIntoView();
+    return true;
+  }
+
+  return false;
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts:73]: Is the return value used somewhere? Just reading this PR it doesn't appear to be.

I know you're inheriting existing code here, but while it's being looked on it looks like it could be a lot more streamlined, e.g.:

```ts
export function scrollToElement(identifier: string) {
    document.getElementById(identifier)?.scrollIntoView();
}
```

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor [hunk 2]
```diff
@@ -1,12 +1,18 @@
...
+@inject NavigationManager NavigationManager
 
 <PageTitle>Page for scrolling to hash</PageTitle>
 
 <h1>Scroll to hash</h1>
 
 <p>If you scroll down a long way, you'll find more content. We add it asynchronously via streaming rendering.</p>
 
+<p>
+    <a id="scroll-anchor" href="nav/scroll-to-hash#some-content">Scroll via anchor</a>
```
Comment (halter73) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor:12]: Nit:

```suggestion
    <a id="scroll-anchor" href="#some-content">Scroll via anchor</a>
```

I assume this also works correctly, but I think hash-only links are more common when on the same page. Or we could test both.

**Review by halter73 — APPROVED** [review]

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor (hunk 2 above)
Comment (MackinnonBuck) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor:12]: This was what I tried initially... but that link would be resolved relative to the base href, which is "/subdir/" for this app, so this would become `subdir/#some-content`, which isn't right.

This behavior surprised me initially, because I thought `#` links might be an exception to resolving relative links by the base href (the [MDN Docs](https://developer.mozilla.org/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#document_fragments) were somewhat ambiguous in that regard). I figured it might be a bug with how we were handling links starting with `#`, but I was able to repro the same behavior with normal HTML.

Comment (SteveSandersonMS) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor:12]: Oh very interesting. I also expected `#...` to be resolved against the current page, and didn't realise it would just append to `document.baseUri`.

I wonder if we should consider adding a `NavigationManager.GetUriWithHash(...)` just like we have `NavigationManager.GetUriWithQueryParameter(...)`. Otherwise it must be really inconvenient to use same-page anchors at all.

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 3]
```diff
@@ -47,6 +47,25 @@ export function isWithinBaseUriSpace(href: string) {
   && (nextChar === '' || nextChar === '/' || nextChar === '?' || nextChar === '#');
 }
 
+export function isSamePageWithHash(absoluteHref: string): boolean {
+  const hashIndex = absoluteHref.indexOf('#');
+  return hashIndex > -1 && location.href.replace(location.hash, '') === absoluteHref.substring(0, hashIndex);
+}
```
Comment (javiercn) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts:53]: We should stop doing stuff like this and start using new URL(absoluteHref) for performing comparisons against the individual pieces that we care about.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts:53]: Yeah the `.replace` technique is really weird, and quite hard to reason about whether it's really correct. I think it is, but it takes time to think through what happens in cases like "current page is `#abc#abc` and you navigate to `#abc`" - it does work but only because of the weirdness that JS's string.replace only replaces the first match, not all matches.

**Review by javiercn — APPROVED** [review]
Looks good to me, but let's address the URL comparison bit.

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor (hunk 2 above)
Comment (MackinnonBuck) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/EnhancedNav/PageForScrollingToHash.razor:12]: https://github.com/dotnet/aspnetcore/issues/53499
