### PR TITLE
Automatically UseDeveloperExceptionPage in WebApplication

### LINKED ISSUE #34548: WebApplicationBuilder should register the developer exception page in the pipeline by default for Development environment
The `WebApplicationBuilder` should automatically register the `DeveloperExceptionPageMiddleware` in the pipeline by default. The middleware should be added before any other middleware in the pipeline and only when the current environment is development, i.e. when `IWebHostEnvironment.IsDevlopment() == true`.

The empty web template should be updated as part of this to remove the existing lines of code that explicitly add the middleware to the pipeline from the application, e.g.:

``` diff
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

-if (app.Environment.IsDevelopment())
-{
-    app.UseDeveloperExceptionPage();
-}

app.MapGet("/", "Hello World");

app.Run();
```

### PR DESCRIPTION
**Pull request by halter73**
Fixes #34548

The corresponding spa-templates changes are at https://github.com/dotnet/spa-templates/pull/5

### CODE REVIEW

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 1]
```diff
@@ -112,6 +112,11 @@ private void ConfigureApplication(WebHostBuilderContext context, IApplicationBui
         {
             Debug.Assert(_builtApplication is not null);
 
+            if (Environment.IsDevelopment())
```
Comment (davidfowl) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:115]: This should use `context.Environment`

Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:115]: I was thinking about that. `Environment` is the source of truth. That's what we pass to all the callbacks that take a `WebHostBuilderContext` or `HostBuilderContext`. It's also the `IWebHostEnvironment` service and soon to be the `IHostEnvironment`.

Of course, if we do everything right, these should be in synchronized. But if they don't match, `context.Environment` would be different from what nearly all of the rest of the environment-based logic in app uses.

Comment (pranavkm) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:115]: How cool is @Tratcher with doing this? He's been very unsupportive of using `IsDevelopment` in the framework. Also to add a data point, we often get users confused about why their static web assets don't work correctly when they pick a different env name (e.g. `Dev`)

**Review by pranavkm — APPROVED** [review]
Changes look fine. Just making sure we sort out the moral conundrum.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 1 above)
Comment (Tratcher) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:115]: Concerns noted at https://github.com/dotnet/aspnetcore/issues/34548#issuecomment-883537130. At least in this case people can always call UseDeveloperExceptionPage themselves, this is only a fallback.

Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:115]: I'm making a change where it will be, but it isn't right now and can't be source of truth at this point either. Code can mutate the environment later.

Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:115]:
```suggestion
            if (context.Environment.IsDevelopment())
```

File: src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Program.cs [hunk 2]
```diff
@@ -25,7 +25,9 @@
 #if (IndividualLocalAuth)
 using Company.WebApplication1.Data;
 #endif
+#if (OrganizationalAuth || IndividualB2CAuth || IndividualLocalAuth || MultiOrgAuth || GenerateGraph)
```
Comment (halter73) [inline src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Program.cs:28]: This fixes this:

image

I don't like how this needs to be kept in sync with the reset of the `using` `#if`'s, but I don't see a better way.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 3]
```diff
@@ -112,6 +112,11 @@ private void ConfigureApplication(WebHostBuilderContext context, IApplicationBui
         {
             Debug.Assert(_builtApplication is not null);
 
+            if (context.Environment.IsDevelopment())
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:115]:
```suggestion
            if (context.HostingEnvironment.IsDevelopment())
```
