### PR TITLE
Fix event and JS component args serialization

### LINKED ISSUE #34338: Custom event args cannot include byte arrays or DotNetObject instances
~~This is a small bug introduced recently (by me, I think) due to an optimization.~~ **Update**: No, after investigation, I realise this was never supported, because the event dispatch was not via JS interop (on Server and WebView).

Our updated logic for dispatching events now does its own JSON serialization (so it can do its own UTF8 encoding, so the .NET side doesn't have to convert UTF8->String->UTF8). The logic looks like `const utf8 = textEncoder.encode(JSON.stringify(data));`

This is inconsistent with how the serialization works for JS interop, in that JS interop uses its own arg replacer that deals with things like formatting `DotNetObject` or `Uint8Array`.

We do actually have an E2E test showing you can include special types in the event payload, but unluckily, it happens to be `IJSObjectReference` that happens to serialize into the right shape using `JSON.stringify` alone.

### Fixing this

... should be very simple. We export some new function `stringifyAsArgs` or similar onto JS interop's `DotNet`, and call that instead of `JSON.stringify`.

Better still, we should bake in this "I want to send it as UTF8 bytes" pattern, since we're using it in multiple places. We could export a special type `Utf8BytesParameter` from `DotNet` that changes the serialization rule for that parameter.

**Update**: No, those suggestions are nonsense. The second one doesn't make sense because we're not sending the message via JS interop, so there's nothing to implement this. The first one is bad because it breaks the layering and means we wouldn't be able to guarantee that things like `byte[]` messages correctly appear just before corresponding JS interop calls. A bigger solution is needed.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes https://github.com/dotnet/aspnetcore/issues/34338

The issue was that event dispatch did not get sent via JS interop, but instead had different custom transports for each of the hosting platforms. As a result, features like sending byte arrays and DotNetObjectReference did not work, because they are features of JS interop.

The solution here is a pretty significant set of refactorings that replace the three platform-specific event dispatch mechanisms with a new single mechanism based on JS interop. It also means we can consolidate and simplify a lot of the implementation. For example:

 * The `InitializeJSComponentSupportAsync` APIs and the three platform-specific implementations are all gone
 * We no longer need to use shared source for all the WebEventData stuff - it's now all just internal to Web
 * We no longer manually JSON-serialize-and-UTF8-encode the args for events or JS root component parameters - these are now just regular JS interop parameters

So, **this PR removes more lines than it adds 🎉**. But it is still a lot of change!

This change also means we can now send byte arrays and DotNetObjectReference as parameters to JS root components, since I've also re-platted that onto this new JSinterop-based thing.

The only user-visible behavioral change apart from the new functionality is that Blazor Server no longer has extra custom log messages related to events, since events are now just JS interop calls. I don't think this is a loss.

### Testing

I have updated the E2E test app but haven't yet updated the Selenium test scripts. Working on that next.

### CODE REVIEW

File: src/Components/Components/src/ParameterViewBuilder.cs [hunk 1]
```diff
@@ -44,10 +44,6 @@ public void Add(string name, object? value)
         /// <returns>The <see cref="ParameterView" />.</returns>
         public ParameterView ToParameterView()
         {
-            // Since this is internal, we should expect the usage to always be correct,
-            // i.e. the given count should match the number of 'Add' calls.
-            Debug.Assert(_frames[0].ElementSubtreeLengthField == _frames.Length);
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/ParameterViewBuilder.cs:49]: This check was unhelpful because the capacity needs to be understood as a *max* capacity, not a guarantee that it will be filled entirely. I realised that if the JS-side code tries to supply `undefined`, because of JSON serialization conventions, that parameter would be omitted, so it's possible for the number of supplied parameters to be less than the total count.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 2]
```diff
@@ -105,11 +105,6 @@ public Task InitializeAsync(ProtectedPrerenderComponentApplicationStore store, C
                     await OnCircuitOpenedAsync(cancellationToken);
                     await OnConnectionUpAsync(cancellationToken);
 
-                    // From this point onwards, JavaScript code can add root components if configured
-                    await Renderer.InitializeJSComponentSupportAsync(
-                        _options.RootComponents.JSComponents,
-                        JSRuntime.ReadJsonSerializerOptions());
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHost.cs:111]: This kind of initialization is now done from the `WebRenderer` constructor instead, so it's common to all.

File: src/Components/Server/src/Circuits/CircuitJSComponentInterop.cs [hunk 3]
```diff
@@ -9,29 +9,20 @@
 
 namespace Microsoft.AspNetCore.Components.Server.Circuits
 {
-    /// <summary>
-    /// Intended for framework use only. Not supported for use from application code.
-    /// </summary>
-    [EditorBrowsable(EditorBrowsableState.Never)]
-    public class CircuitJSComponentInterop : JSComponentInterop
+    internal class CircuitJSComponentInterop : JSComponentInterop
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitJSComponentInterop.cs:12]: This no longer needs to be public because it's no longer called *directly* through JS interop. It's now called via the new `WebRendererInteropMethods` thing.

File: src/Components/Web/src/JSComponents/JSComponentInterop.cs [hunk 4]
```diff
@@ -93,8 +75,7 @@ public virtual int AddRootComponent(string identifier, string domElementSelector
         /// <summary>
         /// For framework use only.
         /// </summary>
-        [JSInvokable]
-        public void SetRootComponentParameters(int componentId, int parameterCount, byte[] parametersJsonUtf8)
+        protected internal void SetRootComponentParameters(int componentId, int parameterCount, JsonElement parametersJson, JsonSerializerOptions jsonOptions)
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/JSComponents/JSComponentInterop.cs:78]: The changes in this method are all because the parameters now arrive as a `JsonElement` instead of a `byte[]`, because JS interop can supply a `JsonElement` natively without us having to manually do anything at either end.

File: src/Components/Web/src/WebEventDescriptor.cs [hunk 5]
```diff
@@ -18,11 +18,6 @@ public sealed class WebEventDescriptor
         // This class represents the first half of the parsing process.
         // It's public only because it's part of the signature of a [JSInvokable] method.
 
-        /// <summary>
-        /// For framework use only.
-        /// </summary>
-        public int BrowserRendererId { get; set; }
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/WebEventDescriptor.cs:24]: This is gone because the `BrowserRendererId` used to be how WebAssembly would distinguish events for different renderers. That's no longer needed because there's now a separate DotNetObjectReference representing the interop methods for each renderer.

File: src/Components/Web/src/WebRenderer.cs [hunk 6]
```diff
@@ -51,15 +76,57 @@ protected internal int AddRootComponent([DynamicallyAccessedMembers(Component)]
...
+            public int AddRootComponent(string identifier, string domElementSelector)
+                => _jsComponentInterop.AddRootComponent(identifier, domElementSelector);
+
+            [JSInvokable]
+            public void SetRootComponentParameters(int componentId, int parameterCount, JsonElement parametersJson)
+                => _jsComponentInterop.SetRootComponentParameters(componentId, parameterCount, parametersJson, _jsonOptions);
+
+            [JSInvokable]
+            public void RemoveRootComponent(int componentId)
+                => _jsComponentInterop.RemoveRootComponent(componentId);
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/WebRenderer.cs:129]: TODO: Change the linking config so that the JS component interop methods can get trimmed if you didn't add any JS root components.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs [hunk 7]
```diff
@@ -181,6 +181,15 @@ private static void EndInvokeDotNetAfterTask(Task task, JSRuntime jsRuntime, in
...
                 throw;
             }
+            finally
+            {
+                // We require the invoked method to retrieve any pending byte arrays synchronously. If we didn't,
+                // we wouldn't be able to have overlapping async calls. As a way to enforce this, we clear the
+                // pending byte arrays synchronously after the call. This also helps because the recipient isn't
+                // required to consume all the pending byte arrays, since it's legal for the JS data model to contain
+                // more data than the .NET data model (like overposting)
+                jsRuntime.ByteArraysToBeRevived.Clear();
```
Comment (SteveSandersonMS) [inline src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:191]: Previously we cleared this set *before* invoking the user code via JS interop. But now we do it synchronously after. This is to allow the callee to retrieve byte arrays during custom deserialization. I don't think there are any drawbacks to this change.

File: src/Components/Web/src/WebRenderer.cs [hunk 8]
```diff
@@ -51,15 +76,57 @@ protected internal int AddRootComponent([DynamicallyAccessedMembers(Component)]
...
+            [DynamicDependency(DynamicallyAccessedMemberTypes.PublicMethods, typeof(WebRendererInteropMethods))]
+            public WebRendererInteropMethods(WebRenderer renderer, JsonSerializerOptions jsonOptions, JSComponentInterop jsComponentInterop)
+            {
+                _renderer = renderer;
+                _jsonOptions = jsonOptions;
+                _jsComponentInterop = jsComponentInterop;
+            }
+
+            [JSInvokable]
+            public Task DispatchEventAsync(JsonElement eventDescriptor, JsonElement eventArgs)
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/WebRenderer.cs:110]: The fact that we can receive `JsonElement` as JS interop params is a cool thing I hadn't even realised would work before. It works because STJ will natively supply a `JsonElement` if you ask it to deserialize to that type.

This means that anywhere we need to do custom deserialization, we don't actually need to have manual-serialize-and-write-to-UTF8-array code on the JS side, as we can simply send normal params from JS and receive them as `JsonElement` on the .NET side. This simplifies things a lot.

File: src/Components/Web/src/WebRenderer.cs [hunk 9]
```diff
@@ -18,18 +18,43 @@ namespace Microsoft.AspNetCore.Components.RenderTree
...
 
         /// <summary>
         /// Constructs an instance of <see cref="WebRenderer"/>.
         /// </summary>
         /// <param name="serviceProvider">The <see cref="IServiceProvider"/> to be used when initializing components.</param>
         /// <param name="loggerFactory">The <see cref="ILoggerFactory"/>.</param>
-        public WebRenderer(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
+        /// <param name="jsonOptions">The <see cref="JsonSerializerOptions"/>.</param>
+        /// <param name="jsComponentInterop">The <see cref="JSComponentInterop"/>.</param>
+        public WebRenderer(
```
Comment (pranavkm) [inline src/Components/Web/src/WebRenderer.cs:30]: You'll have to uncomment https://github.com/dotnet/aspnetcore/blob/main/Directory.Build.props#L18-L23 to get the analyzer to run in VS.

File: src/Components/Web/src/WebRenderer.cs [hunk 10]
```diff
@@ -51,15 +76,57 @@ protected internal int AddRootComponent([DynamicallyAccessedMembers(Component)]
...
+        /// <inheritdoc />
+        protected override void Dispose(bool disposing)
+        {
+            if (disposing)
+            {
+                _interopMethodsReference.Dispose();
+            }
+
+            base.Dispose(disposing);
+        }
```
Comment (pranavkm) [inline src/Components/Web/src/WebRenderer.cs:88]: For a change, we actually have an `unmanaged` resource (the DotNetObjectReference). If you really wanted you could use the Dispose pattern.

File: src/Components/Web/src/WebRenderer.cs [hunk 11]
```diff
@@ -51,15 +76,57 @@ protected internal int AddRootComponent([DynamicallyAccessedMembers(Component)]
...
         /// <summary>
-        /// Enables support for adding, updating, and removing root components from JavaScript.
+        /// A collection of JS invokable methods that the JS-side code can use when it needs to
+        /// make calls in the context of a particular renderer. This object is never exposed to
+        /// .NET code so is only reachable via JS.
         /// </summary>
-        /// <param name="interop">The object that provides JS-callable methods for adding, updating, and removing root components.</param>
-        /// <returns>A task representing the completion of the operation.</returns>
-        protected ValueTask InitializeJSComponentSupportAsync(JSComponentInterop interop)
+        private class WebRendererInteropMethods
```
Comment (pranavkm) [inline src/Components/Web/src/WebRenderer.cs:95]:
```suggestion
        private sealed class WebRendererInteropMethods
```

File: src/Components/Server/src/ComponentHub.cs [hunk 12]
```diff
@@ -242,21 +242,6 @@ public async ValueTask<bool> ReceiveJSDataChunk(long streamId, long chunkId, byt
             return await circuitHost.ReceiveJSDataChunk(streamId, chunkId, chunk, error);
         }
 
-        public async ValueTask DispatchBrowserEvent(JsonElement eventInfo)
```
Comment (pranavkm) [inline src/Components/Server/src/ComponentHub.cs:245]: Removing this method gives me a pause - I can't find the history for this change (it ends at this PR - https://github.com/dotnet/aspnetcore/pull/12250), but I vaguely recall we used to plumb events thru JSInterop but special cased it at as a perf optimization. Are we losing out on those benefits as part of this change?

Comment (SteveSandersonMS) [reply src/Components/Server/src/ComponentHub.cs:245]: The only difference we had before by not using JS interop was more scenario-specific logs, which I don't think are very consequential.

But the more fundamental issue is that is *has* to go via JS interop if we want it to also have JS interop features like transporting `byte[]` or DotNetObjectReference.

Comment (SteveSandersonMS) [reply src/Components/Server/src/ComponentHub.cs:245]: As for perf, it's not going to be meaningfully different because even before this change, we were JSON-serializing the data before sending it over BlazorPack, which is still equivalent to what JS interop does.

Comment (SteveSandersonMS) [reply src/Components/Server/src/ComponentHub.cs:245]: Update: I should be clearer about this because there *is* some extra cost in going through JS interop, but (1) it's the same as we had in 5.0, so not a regression - just not an improvement either, and (2) this sets us up to improve it further in the future if we want.

Overview for Blazor Server:

| Version | How event dispatch worked | Summary of transformations |
| --- | --- | --- |
| 5.0 | JS sent JSON strings; .NET received .NET strings then called STJ to build .NET objects | JS JSON string -> Encode as UTF8 for wire -> Decode as .NET string for hub method -> Encode as UTF8 for JSON parsing -> .NET EventData object |
| 6.0-pre7 | JS sent UTF8-encoded bytes; .NET received bytes then called STJ to build .NET objects | JS JSON string -> Encode as UTF8 for wire -> Receive as UTF8 on hub method -> JSON parse to .NET EventData object |
| This PR | JS sends JSON strings; .NET receives .NET strings then our JS interop code serializes as UTF8 and our custom deserialization logic processes the JsonElement over it | JS JSON string -> Encode as UTF8 for wire -> Decode as .NET string for hub method -> JSInterop does own UTF8 encoding and passes that to STJ -> JsonElement -> .NET EventData object |

So in effect, this PR removes an optimization we had previously added in a 6.0 preview and takes us back to the same perf characteristics we had in 5.0 and before, in that it goes back to passing the data via a .NET string representation instead of staying as UTF8 all the way through.

Of course it would be nice if we didn't have to go through that extra representation, but it's fundamental to how JS interop is defined in terms of exchanging strings (JS strings and .NET strings, not UTF8 bytes). But the good news it that following the layering properly like this PR does means we can improve that layering in the future and would automatically get benefits here. We could eliminate the .NET string representation entirely, as suggested at https://github.com/dotnet/aspnetcore/issues/35065.

File: src/Components/Web/src/WebRenderer.cs (hunk 6 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/WebRenderer.cs:129]: Done

**Review by pranavkm — APPROVED** [review]
