### PR TITLE
`IHttpRequestBodyDetectionFeature` for HTTP/3 GET requests

### LINKED ISSUE #58753: `IHttpRequestBodyDetectionFeature` returns true for GET requests with HTTP/3
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Unlike with HTTP/2, the HTTP/3 implementation does not check for `ReceivedEmptyRequestBody` when creating the message body, which means the body detection feature returns `true` even for requests without one.

https://github.com/dotnet/aspnetcore/blob/46ea84f2c3c53c51935210d794975dcfa024ee4e/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L194-L211

https://github.com/dotnet/aspnetcore/blob/46ea84f2c3c53c51935210d794975dcfa024ee4e/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs#L947-L959

### Expected Behavior

`IHttpRequestBodyDetectionFeature` returns `false` for requests where it's known from the start that there is no body.

### Steps To Reproduce

- Send an HTTP/3 GET request to Kestrel
- Check `IHttpRequestBodyDetectionFeature.CanHaveBody`

### Exceptions (if any)

N/A

### .NET Version

_No response_

### Anything else?

Hit in YARP when downgrading HTTP/3 requests to HTTP/1.1: https://github.com/microsoft/reverse-proxy/issues/2644.

### PR DESCRIPTION
**Pull request by ladeak**
# `IHttpRequestBodyDetectionFeature` for HTTP/3 GET requests

`IHttpRequestBodyDetectionFeature` returns false for HTTP/3 (bodyless) GET requests

## Description

- Implementation follows the HTTP/2 structure.
- Updated `IHttpRequestBodyDetectionFeature` to include HTTP/3 descriptions for the `END_STREAM` flag.
- In `Http3Stream` modified request body handling logic to return zero length content body instance when there endstream flag is set. It also completes the message body for empty requests, so that the `RequestBodyPipe.Reader` is closed (needs to be closed, so that when the stream is reused by the pool, the Pipe is reset which requires closed reader) - not sure if this is the best place to do this.
- Added unit test `CanHaveBody_ReturnsFalseWithoutRequestBody` to validate behavior when no request body is present.

Fixes #58753

### CODE REVIEW

**Comment by BrennanConroy** [comment]
> It also completes the message body for empty requests, so that the RequestBodyPipe.Reader is closed (needs to be closed, so that when the stream is reused by the pool, the Pipe is reset which requires closed reader) - not sure if this is the best place to do this.

`Http2Stream` doesn't do this. It relies on the calling code the cleanup the `MessageBody`. Is there a reason this is different from the `Http2Stream` impl?

**Comment by ladeak** [comment]
@BrennanConroy - I will follow up on that.

**Comment by ladeak** [comment]
@BrennanConroy I addressed your concern.

**Comment by ladeak** [comment]
@BrennanConroy could you review the changes?

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs [hunk 1]
```diff
@@ -559,7 +571,7 @@ private void CompleteStream(bool errored)
 
             TryClose();
         }
-
+        RequestBodyPipe.Reader.Complete();
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs:575]:
```suggestion

        RequestBodyPipe.Reader.Complete();

```

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs [hunk 2]
```diff
@@ -928,7 +940,7 @@ private Task ProcessDataFrameAsync(in ReadOnlySequence<byte> payload)
             {
                 return Task.CompletedTask;
             }
-
+            _requestBodyStarted = true;
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs:946]:
```suggestion

            _requestBodyStarted = true;

```

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs [hunk 3]
```diff
@@ -3291,6 +3291,32 @@ public async Task Control_FrameParsingSingleByteAtATimeWorks()
...
+        {
+            new KeyValuePair<string, string>(InternalHeaderNames.Method, "GET"),
+            new KeyValuePair<string, string>(InternalHeaderNames.Path, "/"),
+            new KeyValuePair<string, string>(InternalHeaderNames.Scheme, "http"),
+            new KeyValuePair<string, string>(InternalHeaderNames.Authority, "localhost:80"),
+        };
+
+        var requestStream = await Http3Api.InitializeConnectionAndStreamsAsync(context =>
+        {
+            Assert.Equal(!endstream, context.Features.Get<IHttpRequestBodyDetectionFeature>().CanHaveBody);
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs]:
```suggestion
            Assert.False(endstream, context.Features.Get<IHttpRequestBodyDetectionFeature>().CanHaveBody);
```

**Review by BrennanConroy — APPROVED** [review]

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs (hunk 3 above)
Comment (ladeak) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs]: Addressed by using `NotEqual`.

Comment (BrennanConroy) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs]: Whoops 😆
