### PR TITLE
RequestAbort token stays the same after abort

### LINKED ISSUE #42547: RequestAborted token should stay identical once retrieved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The HttpContext.RequestAborted token cannot be reread after it was triggered.

The relevant code lives here:

https://github.com/dotnet/aspnetcore/blob/b9fcd82fe9d0883e9828864a8e8b2231f469254f/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L285-L295

There are two scenario's to consider:

1. _connectionAborted is true and _abortedCts was never allocated, this should stay as is today, as an optimization.
2. _connectionAborted is true but `_abortedCts` was also already allocated, this should instead return `_abortedCts.Token`, not `CancellationToken(true)`.

The behavior today is problematic is because it hinders filtering out any `OperationCancelledException` caused by a cancelled request. And in our case we need to distinguish between it and other causes. As it stands we need to capture and flow the token as another parameter to the relevant exception filtering code while it also has access to the HttpContext, where it should just be able to reread RequestAborted.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/42547

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 1]
```diff
@@ -465,7 +465,6 @@ private void CancelRequestAbortedTokenCallback()
                 if (_abortedCts != null && !_preventRequestAbortedCancellation)
                 {
                     localAbortCts = _abortedCts;
-                    _abortedCts = null;
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:468]: Note that this change means the CTS isn't cleared on abort. It will be disposed when the HttpProtocol type is reset.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:468]: If this is a problem, a separate field could be added to save the CT while clearing the CTS.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:468]: I think this is an improvement rather than a problem. The reason we couldn't dispose it here is because we didn't want to get ODEs when middleware accessed it when it was still running. Reset() is only called between middleware invocations.

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
It took this long for one person to realize that the post-Abort CT and pre-abort CT were any different. I think it's fine not to backport.
