### PR TITLE
InvalidOperationException when decompressed data exceeds request body size limit

### LINKED ISSUE #61723: InvalidOperationException when decompressed data exceeds request body size limit
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using the request decompression middleware and the compressed body is below the request body size limit, but the decompressed body exceeds it, the request fails with an `InvalidOperationException` and returns HTTP Status 500 instead of 413 (Content Too Large).

Without compression or if the compressed body already exceeds the limit, this internally causes a `BadHttpRequestException` with StatusCode 413 which can properly be handled in a middleware. I would expect the same behaviour here instead of an `InvalidOperationException` which cannot be handled properly.

The `SizeLimitedStream` that throws the exception was introduced as part of #40279 .

### Expected Behavior

Same behaviour as without compression, meaning a `BadHttpRequestException` with StatusCode 413.

### Steps To Reproduce

```
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRequestDecompression();

builder.WebHost.ConfigureKestrel(serverOptions =>
{
    serverOptions.Limits.MaxRequestBodySize = 30;
});

var app = builder.Build();
app.UseRequestDecompression();
app.MapPost("/", ([FromBody]string foo) => foo);
app.Run();
```

Then run:

```
echo '"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"' | gzip | curl -v -i --data-binary @- -H "Content-Encoding: gzip" -H "Content-Type: application/json" http://localhost:5146/
```

which results in:

```
* Host localhost:5146 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:5146...
* Connected to localhost (::1) port 5146
* using HTTP/1.x
> POST / HTTP/1.1
> Host: localhost:5146
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Encoding: gzip
> Content-Type: application/json
> Content-Length: 26
>
* upload completely sent off: 26 bytes
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Date: Mon, 28 Apr 2025 13:16:25 GMT
Date: Mon, 28 Apr 2025 13:16:25 GMT
< Server: Kestrel
Server: Kestrel
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
<

System.InvalidOperationException: The maximum number of bytes have been read.
   at SizeLimitedStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream utf8Json, CancellationToken cancellationToken, Boolean fillBuffer)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync(HttpRequest request, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync(HttpRequest request, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForJson>g__TryReadBodyAsync|102_0(HttpContext httpContext, Type bodyType, String parameterTypeName, String parameterName, Boolean allowEmptyRequestBody, Boolean throwOnBadRequest, JsonTypeInfo jsonTypeInfo)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeCore(HttpContext context, Stream decompressionStream)
   at Microsoft.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeCore(HttpContext context, Stream decompressionStream)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: localhost:5146
User-Agent: curl/8.11.0
Content-Type: application/json
Content-Length: 26
* Connection #0 to host localhost left intact
```

### Exceptions (if any)

```
System.InvalidOperationException: The maximum number of bytes have been read.
   at SizeLimitedStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream utf8Json, CancellationToken cancellationToken, Boolean fillBuffer)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync(HttpRequest request, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync(HttpRequest request, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForJson>g__TryReadBodyAsync|102_0(HttpContext httpContext, Type bodyType, String parameterTypeName, String parameterName, Boolean allowEmptyRequestBody, Boolean throwOnBadRequest, JsonTypeInfo jsonTypeInfo)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeCore(HttpContext context, Stream decompressionStream)
   at Microsoft.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeCore(HttpContext context, Stream decompressionStream)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

10.0.100-preview.3.25201.16

### Anything else?

Reproducible with .NET 9.0.4 and .NET 10 Preview 3 .

### PR DESCRIPTION
**Pull request by feiyun0112**
fix #61723

### CODE REVIEW

File: src/Shared/SizeLimitedStream.cs [hunk 1]
```diff
@@ -48,7 +49,14 @@ public override int Read(byte[] buffer, int offset, int count)
...
         if (_totalBytesRead > _sizeLimit)
         {
-            throw new InvalidOperationException("The maximum number of bytes have been read.");
+            if (_handleSizeLimit != null)
+            {
+                _handleSizeLimit(_totalBytesRead, _sizeLimit.Value);
+            }
+            else
+            {
+                throw new InvalidOperationException("The maximum number of bytes have been read.");
```
Comment (gfoidl) [inline src/Shared/SizeLimitedStream.cs:58]: Should this message include `_sizeLimit.Value`, so it's aids diagnosing the error?

File: src/Middleware/RequestDecompression/src/RequestDecompressionMiddleware.cs [hunk 2]
```diff
@@ -62,7 +62,9 @@ private async Task InvokeCore(HttpContext context, Stream decompressionStream)
                 context.GetEndpoint()?.Metadata?.GetMetadata<IRequestSizeLimitMetadata>()?.MaxRequestBodySize
                     ?? context.Features.Get<IHttpMaxRequestBodySizeFeature>()?.MaxRequestBodySize;
 
-            context.Request.Body = new SizeLimitedStream(decompressionStream, sizeLimit);
+            context.Request.Body = new SizeLimitedStream(decompressionStream, sizeLimit, (long totalBytesRead, long sizeLimit) => throw new BadHttpRequestException(
+                    $"The request's Content-Length {totalBytesRead} is larger than the request body size limit {sizeLimit}.",
```
Comment (mus65) [inline src/Middleware/RequestDecompression/src/RequestDecompressionMiddleware.cs:66]: This error message is imho confusing since the Content-Length actually doesn't exceeed the limit, only the decompressed body does (if the Content-Length already exceeded the limit, it wouldn't even get to this middleware).

Also using `totalBytesRead` here doesn't seem helpful here since it's just a random value that is slightly above the `sizeLimit`. The actual decompressed length is unknown here.

```suggestion
                    $"The decompressed request body is larger than the request body size limit {sizeLimit}.",
```

File: src/Shared/SizeLimitedStream.cs (hunk 1 above)
Comment (feiyun0112) [reply src/Shared/SizeLimitedStream.cs:58]: "The maximum number of bytes have been read." is the original message, i did not change it

File: src/Shared/SizeLimitedStream.cs [hunk 3]
```diff
@@ -5,15 +5,16 @@ internal sealed class SizeLimitedStream : Stream
 {
     private readonly Stream _innerStream;
     private readonly long? _sizeLimit;
-
+    private readonly Action<long, long>? _handleSizeLimit;
```
Comment (BrennanConroy) [inline src/Shared/SizeLimitedStream.cs:8]: Put `#nullable enable` after the license header

File: src/Middleware/RequestDecompression/src/RequestDecompressionMiddleware.cs [hunk 4]
```diff
@@ -62,7 +62,9 @@ private async Task InvokeCore(HttpContext context, Stream decompressionStream)
                 context.GetEndpoint()?.Metadata?.GetMetadata<IRequestSizeLimitMetadata>()?.MaxRequestBodySize
                     ?? context.Features.Get<IHttpMaxRequestBodySizeFeature>()?.MaxRequestBodySize;
 
-            context.Request.Body = new SizeLimitedStream(decompressionStream, sizeLimit);
+            context.Request.Body = new SizeLimitedStream(decompressionStream, sizeLimit, (long totalBytesRead, long sizeLimit) => throw new BadHttpRequestException(
```
Comment (BrennanConroy) [inline src/Middleware/RequestDecompression/src/RequestDecompressionMiddleware.cs:65]:
```suggestion
            context.Request.Body = new SizeLimitedStream(decompressionStream, sizeLimit, static (long sizeLimit) => throw new BadHttpRequestException(
```

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks for the fix @feiyun0112 !
