### PR TITLE
[SignalR] Fix DataProtection with parallel tests

### LINKED ISSUE #21249: Flaky test: StreamAsyncTest
https://dev.azure.com/dnceng/public/_build/results?buildId=618367&view=ms.vss-test-web.build-test-results-tab&runId=19368302&resultId=120247&paneView=debug:
```
System.Exception : 1 error(s) logged.

Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider - ErrorOccurredWhileReadingKeyRing - An error occurred while reading the key ring.
System.IO.IOException: The process cannot access the file 'C:\Users\runner\AppData\Local\ASP.NET\DataProtection-Keys\key-707d128d-35c7-4ab3-8173-093088ee5613.xml' because it is being used by another process.

at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.File.OpenRead(String path)
at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath) in //src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 102
at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext() in //src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 83
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements() in //src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 68
at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys() in //src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs:line 152
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in //src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 64
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in //src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 110
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now) in //src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 273
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh) in //src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 205
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing() in //src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 149
at Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService.StartAsync(CancellationToken token) in //src/DataProtection/DataProtection/src/Internal/DataProtectionHostedService.cs:line 35
```

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/21249

Replaces https://github.com/dotnet/aspnetcore/pull/21252

Our functional tests spin up a server per test. Since tests can run in parallel, it was possible for 2 tests to start at the same time, and during the server startup DataProtection will either find a key or create one and write it to file. This could cause issues with one of the servers writing the file while the other tries to read it resulting in a failure.

### CODE REVIEW

File: src/SignalR/clients/csharp/Client/test/FunctionalTests/Startup.cs [hunk 1]
```diff
@@ -49,6 +51,11 @@ public void ConfigureServices(IServiceCollection services)
                                 IssuerSigningKey = SecurityKey
                             };
                     });
+
+            // Since tests run in parallel, it's possible multiple servers will startup and read files being written by another test
+            // Use a unique directory per server to avoid this collision
+            services.AddDataProtection()
+                .PersistKeysToFileSystem(Directory.CreateDirectory(Path.GetRandomFileName()));
```
Comment (halter73) [inline src/SignalR/clients/csharp/Client/test/FunctionalTests/Startup.cs:58]: Is this directory created in the CI agent's working directory so it's cleaned up automatically?

Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Client/test/FunctionalTests/Startup.cs:58]: It was locally. Haven't looked at the CI logs yet.

Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Client/test/FunctionalTests/Startup.cs:58]: DataProtection file placed at `/datadisks/disk1/work/B72C09B7/w/A7CD0956/e/gx2nq0by.eg5/key-423cc81a-aa77-44aa-958b-f873f764b388.xml` and the working directory is `/datadisks/disk1/work/B72C09B7/w/A7CD0956/e`

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Nice! This one saves me some build ops work 😄
