### PR TITLE
Fix nearly all CS1591

### LINKED ISSUE #27538: More API docs
Looks like there are more API docs that need to be added for the following:

- Azure
  - [x] Microsoft.AspNetCore.AzureAppServicesIntegration @BrennanConroy 
- Caching
  - [x] Microsoft.Extensions.Caching.StackExchangeRedis @juntaoluo
  - [x] Microsoft.Extensions.Caching.SqlServer @juntaoluo
- DataProtection:
  - [x] Microsoft.AspNetCore.DataProtection @pranavkm
- Features
  - [x] Microsoft.AspNetCore.JsonPatch @SteveSandersonMS 
- Http
  - [x] Microsoft.Net.Http.Headers @pranavkm
  - [x] Microsoft.AspNetCore.Http @pranavkm
  - [x] Microsoft.AspNetCore.Http.Extensions @pranavkm
  - [x] Microsoft.AspNetCore.Http.Features @pranavkm
  - [x] Microsoft.AspNetCore.Owin @JamesNK 
  - [x] Microsoft.AspNetCore.WebUtilities @pranavkm
- JSInterop
  - [x] Microsoft.JSInterop @pranavkm
- ObjectPool
  - [x] Microsoft.Extensions.ObjectPool @pranavkm
- Razor
  - [x] Microsoft.AspNetCore.Razor @TanayParikh 
- Security
  - [x] Microsoft.AspNetCore.Authentication.Twitter @HaoK 
- Server
  - [x] Microsoft.AspNetCore.Connections.Abstractions @halter73 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Core @sebastienros 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic @sebastienros 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets @sebastienros 
- SignalR
  - [x] Microsoft.AspNetCore.SignalR.Specification.Tests @BrennanConroy 
- WebEncoders
  - [x] Microsoft.Extensions.WebEncoders @JunTaoLuo

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/27538

### CODE REVIEW

**Comment by pranavkm** [comment]
Bonus 💯 points if you find the doc bug.

File: src/Razor/Razor/src/TagHelpers/HtmlAttributeValueStyle.cs [hunk 1]
```diff
@@ -1,12 +1,30 @@
-﻿// Licensed to the .NET Foundation under one or more agreements.
+// Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
 
 namespace Microsoft.AspNetCore.Razor.TagHelpers;
 
+/// <summary>
+/// Determines how a HTML attribute value appears in markup.
```
Comment (BrennanConroy) [inline src/Razor/Razor/src/TagHelpers/HtmlAttributeValueStyle.cs:7]:
```suggestion
/// Determines how an HTML attribute value appears in markup.
```

I'm not a grammar expert, but I think this should be 'an'

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 2]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
...
+    /// </summary>
     Auto,
+
+    /// <summary>
+    /// Better than UDP.
+    /// </summary>
     Tcp,
+
+    /// <summary>
+    /// Carries water when not burst.
```
Comment (BrennanConroy) [inline src/Servers/Connections.Abstractions/src/FileHandleType.cs:22]: :/

File: src/Servers/Kestrel/Core/src/HttpProtocols.cs [hunk 3]
```diff
@@ -9,10 +9,33 @@ namespace Microsoft.AspNetCore.Server.Kestrel.Core;
...
+    /// </summary>
     Http1AndHttp2 = Http1 | Http2,
+
+    /// <summary>
+    /// The HTTP/3.0 protocol version.
+    /// </summary>
     Http3 = 0x4,
+
+    /// <summary>
+    /// The <see cref="Http1"/>, <see cref="Http2"/> and <see cref="Http3"/> protocol versions.
```
Comment (sharwell) [inline src/Servers/Kestrel/Core/src/HttpProtocols.cs:38]:
```suggestion
    /// The <see cref="Http1"/>, <see cref="Http2"/>, and <see cref="Http3"/> protocol versions.
```

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpMethod.cs [hunk 4]
```diff
@@ -3,19 +3,75 @@
...
+/// <summary>
+/// This API supports framework infrastructure and is not intended to be used
+/// directly from application code.
+/// </summary>
 public enum HttpMethod : byte
 {
+    /// <summary>
+    /// This API supports framework infrastructure and is not intended to be used
+    /// directly from application code.
+    /// </summary>
```
Comment (sharwell) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpMethod.cs:15]: 💡 Consider using `<inheritdoc />` for this

```suggestion
    /// <inheritdoc cref="HttpMethod" />
```

Comment (sharwell) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpMethod.cs:15]: You can also create a type specifically for this purpose, and then link all documentation to it for elements to have consistent wording.

File: src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs [hunk 5]
```diff
@@ -9,10 +9,15 @@
...
 /// <summary>
-/// Quic <see cref="IWebHostBuilder"/> extensions.
+/// <see cref="IWebHostBuilder" /> extension methods to configure the Quic transport to be used by Kestrel.
 /// </summary>
 public static class WebHostBuilderQuicExtensions
 {
+    /// <summary>
+    /// Specify Quic as the transport to be used by Kestrel.
+    /// </summary>
+    /// <param name="hostBuilder">The <see cref="IWebHostBuilder"/>. to configure.</param>
```
Comment (sharwell) [inline src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs:19]:
```suggestion
    /// <param name="hostBuilder">The <see cref="IWebHostBuilder"/> to configure.</param>
```

File: src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs [hunk 6]
```diff
@@ -9,10 +9,15 @@
...
+    /// <returns>The <see cref="IWebHostBuilder"/>.</returns>
```
Comment (sharwell) [inline src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs:20]: 💭 Maybe make this directly reference the parameter to show that it's a specific instance and not just an arbitrary instance of the type?

```suggestion
    /// <returns>Returns <paramref name="hostBuilder"/>.</returns>
```

File: src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs [hunk 7]
```diff
@@ -26,6 +31,12 @@ public static IWebHostBuilder UseQuic(this IWebHostBuilder hostBuilder)
         return hostBuilder;
     }
 
+    /// <summary>
+    /// Specify Quic as the transport to be used by Kestrel.
+    /// </summary>
+    /// <param name="hostBuilder">The <see cref="IWebHostBuilder"/>. to configure.</param>
```
Comment (sharwell) [inline src/Servers/Kestrel/Transport.Quic/src/WebHostBuilderQuicExtensions.cs:37]:
```suggestion
    /// <param name="hostBuilder">The <see cref="IWebHostBuilder"/> to configure.</param>
```

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 8]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
...
+    /// </summary>
     Pipe
```
Comment (sharwell) [inline src/Servers/Connections.Abstractions/src/FileHandleType.cs:24]: Maybe want to revisit these

**Review by Tratcher — CHANGES_REQUESTED** [review]

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 9]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
...
 public enum FileHandleType
 {
+    /// <summary>
+    /// Not a manual.
+    /// </summary>
     Auto,
+
+    /// <summary>
+    /// Better than UDP.
+    /// </summary>
```
[the remark this answers is not in the document]
Comment (pranavkm) [reply src/Servers/Connections.Abstractions/src/FileHandleType.cs:18]: Could you suggest doc comments for this? I have no idea what any of these mean.

[the remark this answers is not in the document]
Comment (Tratcher) [reply src/Servers/Connections.Abstractions/src/FileHandleType.cs:18]: `FileHandleEndPoint` stores this, but it never seems to be used @halter73 ?

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpMethod.cs (hunk 4 above)
Comment (pranavkm) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpMethod.cs:15]: I'll do this the next time around. It's more work now to update, but thanks for the suggestion 👍🏽

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 10]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
 /// </summary>
 public enum FileHandleType
 {
+    /// <summary>
+    /// Not a manual.
```
Comment (pranavkm) [inline src/Servers/Connections.Abstractions/src/FileHandleType.cs:12]:
```suggestion
    /// This API is unused and no longer supported.
```

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 11]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
...
+    /// </summary>
     Auto,
+
+    /// <summary>
+    /// Better than UDP.
```
Comment (pranavkm) [inline src/Servers/Connections.Abstractions/src/FileHandleType.cs:17]:
```suggestion
    /// This API is unused and no longer supported.
```

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs (hunk 2 above)
Comment (pranavkm) [reply src/Servers/Connections.Abstractions/src/FileHandleType.cs:22]:
```suggestion
    /// This API is unused and no longer supported.
```

File: src/Servers/Connections.Abstractions/src/FileHandleType.cs [hunk 12]
```diff
@@ -8,7 +8,18 @@ namespace Microsoft.AspNetCore.Connections;
 /// </summary>
 public enum FileHandleType
 {
+    /// <summary>
+    /// This API is unused and no longer supported.
```
Comment (pranavkm) [inline src/Servers/Connections.Abstractions/src/FileHandleType.cs:12]: FYI @Tratcher  / @halter73. Doesn't appear to be used. David thought this might have been specific to Libuv.

**Review by JamesNK — APPROVED** [review]

**Review by Tratcher — APPROVED** [review]
