### PR TITLE
Fix selecting empty values in dropdown. Fixes #17735

### LINKED ISSUE #17735: <option value=""> incorrectly omits value attribute
### Bug
<option value="">[Select]</option> becomes <option>[Select]</option> on the client thus eliminating the ability to select "nothing" as a value in a drop down. 

### To Reproduce

``` TestComponent.razor

<div><input id="tbx" value="@MyValue"  /></div>
<div>
    <select id="ddlAdm1" @onchange="@OnMyValChange" value="@MyValue">
        <option value="">[Select]</option>
        <option value="1">One</option>
        <option value="2">Two</option>
    </select>
</div>

@code {
    [Parameter] public string MyValue { get; set; }

    protected void OnMyValChange(ChangeEventArgs e)
    {
        MyValue = e.Value.ToString();
    }
}

```
Produces

``` HTML

<div><input id="tbx"></div><!--!-->
    <div>
        <!--!-->
        <select id="ddlTest">
            <!--!-->
            <option>[Select]</option><!--!-->
            <option value="1">One</option><!--!-->
            <option value="2">Two</option><!--!-->
        </select><!--!-->
    </div>
```

This causes selecting the first line to put "[Select]" in the "tbx" input box.

### Version Info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

Visual Studio 2019

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Note that this is to go into master, because it affects both Server and WebAssembly hosting models.

We could then:

 * Leave it to ship in 5.0
 * Or ship it as a patch
 * Or cherry-pick it across to `blazor-wasm` and ship it there first

I don't mind strongly which of these happens. We might want to be guided by the amount of customer demand for this to determine whether it's worth putting out as a patch.

### CODE REVIEW

File: src/Components/Web.JS/src/Rendering/BrowserRenderer.ts [hunk 1]
```diff
@@ -372,7 +372,7 @@ export class BrowserRenderer {
       }
       case 'OPTION': {
         const value = attributeFrame ? frameReader.attributeValue(attributeFrame) : null;
-        if (value) {
+        if (value || value === '') {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Rendering/BrowserRenderer.ts]: This line is the fix. Everything else in this PR is test and build stuff.

**Review by javiercn — APPROVED** [review]
Pretty straight forward. Good fix!
