### PR TITLE
Actually fix the CopyToAsync this time 

### LINKED ISSUE #24032: FileBufferingReadStream CopyToAsync Performance problem.
When buffering a response using FileBufferingReadStream: initially, the stream's Position and Length are both 0. Based on the code in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L160-L188, CopyToAsync chooses a buffer size of 1. 

When the stream is say, 16KB, this triggers a FileStream.GetLengthInternal() call 16,384 times and causes a big CPU spike for requests that are buffered to disk. 

Please see attached profiler trace.
GetLengthInternal

We are currently solving this issue by calling the overload of CopyToAsync that accepts an explicit buffer size (we chose 16KB).

### PR DESCRIPTION
**Pull request by davidfowl**
- Hard code the 4K buffer length for CopyToAsync
- Write a test this time :D

Fixes #24032

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
Nice catch @Tratcher.

File: src/Http/WebUtilities/test/FileBufferingReadStreamTests.cs [hunk 1]
```diff
@@ -486,5 +495,22 @@ private static string GetCurrentDirectory()
         {
             return AppContext.BaseDirectory;
         }
+
+        private class NumberOfWritesMemoryStream : MemoryStream
+        {
+            public int NumberOfWrites { get; set; }
+
+            public override void Write(byte[] buffer, int offset, int count)
```
Comment (halter73) [inline src/Http/WebUtilities/test/FileBufferingReadStreamTests.cs:503]: Maybe this should just derive from stream and write to a MemoryStream member. Then you won't have to worry about this breaking because base.Write() someday starts calling Write(ReadOnlySpan) or something like that.

**Review by Tratcher — APPROVED** [review]
