### PR TITLE
fix FIPS enabled context header creation in ManagedAuthenticatedEncryptor

### LINKED ISSUE #64597: ASP.NET Core Data Protection has cryptographic errors on Ubuntu 22.04 with FIPS enabled
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

ASP.NET Core applications that use the Data Protection APIs (e.g. by using the session middleware), fail with cryptographic operation errors on Ubuntu 22.04 if FIPS mode is enabled. The same code works fine with .NET 8.

### Expected Behavior

The application should work and not produce cryptographic operation errors.

### Preparation
 
* Install VM with Ubuntu 22.04.5 LTS. Minimal install is sufficient. Link to installer ISO: https://releases.ubuntu.com/jammy/ubuntu-22.04.5-desktop-amd64.iso
* Update the system: `sudo apt update && sudo apt upgrade`
* Add the .NET backports PPA: `sudo add-apt-repository ppa:dotnet/backports`
* Install .NET 10 SDK: `sudo apt install dotnet-sdk-10.0`
* Create a minimal webapi project:
    ```sh
    mkdir DotnetFipsIssue
    cd DotnetFipsIssue
    dotnet new webapi
    ```
* Modify `Program.cs` as follows:
    ```csharp
    // Right after: var builder = WebApplication.CreateBuilder(args);
    builder.Services
      .AddDistributedMemoryCache()
      .AddSession();

    // SNIP ... SNAP

    // Right after: var app = builder.Build();
    app.UseSession();
    ```

### Test without FIPS enabled

* Start the application: `dotnet run --launch-profile https`
* From another terminal, call: `curl -k https://localhost:5000/weatherforecast`
  (replace with the correct port as displayed by the `dotnet run` command)
* Observe that the `curl` command displays the weather forecast as expected and
  the application runs without errors.

### Test with FIPS enabled

* Now attach the VM to Ubuntu Pro and enable FIPS mode:
    ```sh
    sudo pro attach --no-auto-enable
    sudo pro enable fips-updates
    ```
* Once completed successfully, reboot the VM: `sudo reboot`
* After the reboot, verify that FIPS mode is enabled:
    ```sh
    cat /proc/sys/crypto/fips_enabled
    ```
  It should return `1`.
* Start the application again:
    ```sh
    cd DotnetFipsIssue
    dotnet run --launch-profile https
    ```
* Observe that the application displays a lot of warnings related to cryptographic operations, starting with:
    ```
    warn: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[12]
          Key {75b3f7e0-199b-439b-a57c-22ca16d0ea3e} is ineligible to be the default key because its CreateEncryptor method failed after the maximum number of retries.
          System.AggregateException: One or more errors occurred. (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.) (Error occurred during a cryptographic operation.)
           ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
             at Interop.Crypto.HmacOneShot(IntPtr type, ReadOnlySpan`1 key, ReadOnlySpan`1 source, Span`1 destination)
    # SNIP ... SNAP
    ```
* From another terminal, call: `curl -k https://localhost:5000/weatherforecast`
  (replace with the correct port as displayed by the `dotnet run` command)
* Observe that the `curl` command fails, displaying the developer error details and that the application logs show:
    ```
    fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
         at Microsoft.AspNetCore.DataProtection.SP800_108.ManagedSP800_108_CTR_HMACSHA512.DeriveKeys(ReadOnlySpan`1 kdk, ReadOnlySpan`1 label, ReadOnlySpan`1 contextHeader, ReadOnlySpan`1 contextData, Span`1 operationSubkey, Span`1 validationSubkey, HashAlgorithm prf)
         at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.CreateContextHeader()
         at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor..ctor(Secret keyDerivationKey, Func`1 symmetricAlgorithmFactory, Int32 symmetricAlgorithmKeySizeInBytes, Func`1 validationAlgorithmFactory, IManagedGenRandom genRandom)
         at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory.CreateAuthenticatedEncryptorInstance(ISecret secret, ManagedAuthenticatedEncryptorConfiguration configuration)
         at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.AuthenticatedEncryptorFactory.CreateAuthenticatedEncryptorInstance(ISecret secret, AuthenticatedEncryptorConfiguration authenticatedConfiguration)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.Key.CreateEncryptor()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
         at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
    ```

### Exceptions (if any)

```
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
     at Microsoft.AspNetCore.DataProtection.SP800_108.ManagedSP800_108_CTR_HMACSHA512.DeriveKeys(ReadOnlySpan`1 kdk, ReadOnlySpan`1 label, ReadOnlySpan`1 contextHeader, ReadOnlySpan`1 contextData, Span`1 operationSubkey, Span`1 validationSubkey, HashAlgorithm prf)
     at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.CreateContextHeader()
     at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor..ctor(Secret keyDerivationKey, Func`1 symmetricAlgorithmFactory, Int32 symmetricAlgorithmKeySizeInBytes, Func`1 validationAlgorithmFactory, IManagedGenRandom genRandom)
     at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory.CreateAuthenticatedEncryptorInstance(ISecret secret, ManagedAuthenticatedEncryptorConfiguration configuration)
     at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.AuthenticatedEncryptorFactory.CreateAuthenticatedEncryptorInstance(ISecret secret, AuthenticatedEncryptorConfiguration authenticatedConfiguration)
     at Microsoft.AspNetCore.DataProtection.KeyManagement.Key.CreateEncryptor()
     at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
     at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
     at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
     at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)
     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
     at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

10.0.100

### Anything else?

* .NET SDK version: `10.0.100`
* Output of `dotnet --info`:
    ```
    .NET SDK:
     Version:           10.0.100
     Commit:            b0f34d51fc
     Workload version:  10.0.100-manifests.4eab3e0f
     MSBuild version:   18.0.2+b0f34d51f
    
    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  22.04
     OS Platform: Linux
     RID:         ubuntu.22.04-x64
     Base Path:   /usr/lib/dotnet/sdk/10.0.100/
    
    .NET workloads installed:
    There are no installed workloads to display.
    Configured to use workload sets when installing new manifests.
    No workload sets are installed. Run "dotnet workload restore" to install a workload set.
    
    Host:
      Version:      10.0.0
      Architecture: x64
      Commit:       b0f34d51fc
    
    .NET SDKs installed:
      10.0.100 [/usr/lib/dotnet/sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 10.0.0 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 10.0.0 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
    
    Other architectures found:
      None
    
    Environment variables:
      DOTNET_BUNDLE_EXTRACT_BASE_DIR           [/home/mwild/.cache/dotnet_bundle_extract]
    
    global.json file:
      Not found
    
    Learn more:
      https://aka.ms/dotnet/info
    
    Download .NET:
      https://aka.ms/dotnet/download
    ```

### PR DESCRIPTION
**Pull request by DeagleGross**
When initializing `ManagedAuthenticatedEncryptor` we are calling `CreateContextHeader()` in the constructor, and during that call we invoke `ManagedSP800_108_CTR_HMACSHA512.DeriveKeys(kdk: EMPTY_ARRAY, ...)` with the kdk of empty array value.

In https://github.com/dotnet/aspnetcore/pull/59424 we improved the allocations in NET10 on this path by eventually calling 
```
var success = HMACSHA512.TryHashData(kdk, prfInput, prfOutput, out var bytesWritten);
``` 

Unfortunately, for FIPS environment, `HMACSHA512.TryHashData` fails when kdk provided is less than 14 bytes. Current fix ensures, that if kdk is less than 14 bytes, then we will go with using prf and allocating the buffer. It is not on a hotpath, and for most cases kdk is bigger than 14 bytes ([its 64 bytes](https://github.com/dotnet/aspnetcore/blob/7328bdb6f0cf94168f5d4133122f3734a0bb1f24/src/DataProtection/DataProtection/src/AuthenticatedEncryption/ConfigurationModel/AlgorithmConfiguration.cs#L11)), so it will not impact performance nearly anyhow.

here is the sample app to prove that 14 bytes is the minimum for FIPS environment:
```csharp
using System.Security.Cryptography;

Console.WriteLine($"FIPS Enabled: {File.ReadAllText("/proc/sys/crypto/fips_enabled").Trim()}");

Span<byte> data = stackalloc byte[64];
Span<byte> output = stackalloc byte[64];

for (int keyLength = 0; keyLength <= 20; keyLength++)
{
    byte[] key = new byte[keyLength];
    try
    {
        bool success = HMACSHA512.TryHashData(key, data, output, out int bytesWritten);
        Console.WriteLine($"Key length {keyLength,2} bytes: Success");
    }
    catch (CryptographicException ex1)
    {
        // Try the instance-based approach as fallback
        try
        {
            using var hmac = new HMACSHA512(key);
            hmac.ComputeHash(data.ToArray());
            Console.WriteLine($"Key length {keyLength,2} bytes: Static failed, Instance works - \"{ex1.Message}\"");
        }
        catch (Exception ex2)
        {
            Console.WriteLine($"Key length {keyLength,2} bytes: Both failed - Static: \"{ex1.Message}\", Instance: \"{ex2.Message}\"");
        }
    }
}
```
and i can see the change of results happening specifically around 14 bytes length. Also documented in this [NIST SP 800-131A Rev 2.](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf):
> Keys less than 112 bits in length are disallowed for HMAC generation.
The use of key lengths ≥ 112 bits is acceptable for HMAC generation.

Fixes #64597

### CODE REVIEW

File: src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs [hunk 1]
```diff
@@ -31,8 +31,30 @@ public static void DeriveKeys(
...
+    /// <see href="https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf"/>
+    /// </remarks>
+    private const int FipsMinimumKeyLengthInBytes = 14;
+
     public static void DeriveKeys(ReadOnlySpan<byte> kdk, ReadOnlySpan<byte> label, ReadOnlySpan<byte> contextHeader, ReadOnlySpan<byte> contextData, Span<byte> operationSubkey, Span<byte> validationSubkey)
-        => DeriveKeys(kdk, label, contextHeader, contextData, operationSubkey, validationSubkey, prf: null);
+    {
+        if (kdk.Length < FipsMinimumKeyLengthInBytes)
+        {
+            using var prf = new HMACSHA512(kdk.ToArray());
```
Comment (adityamandaleeka) [inline src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs]: It wasn't immediately clear to me why this makes it okay. Maybe add a comment explaining how this ctor pads the key, which satisfies the FIPS requirement?

**Review by adityamandaleeka — APPROVED** [review]
LGTM modulo my comment and Copilot's

File: src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs [hunk 2]
```diff
@@ -101,9 +123,17 @@ private static void DeriveKeys(
...
-                Debug.Assert(success);
-                Debug.Assert(bytesWritten == prfOutputSizeInBytes);
+                if (prf is not null)
+                {
+                    var prfOutputArray = prf.ComputeHash(prfInputArray ?? prfInput.ToArray());
+                    prfOutputArray.CopyTo(prfOutput);
+                }
+                else
+                {
+                    var success = HMACSHA512.TryHashData(kdk, prfInput, prfOutput, out var bytesWritten);
```
[the remark this answers is not in the document]
Comment (DeagleGross) [reply src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs:138]: wrong suggestion; not same NET version of code flow here

File: src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs (hunk 1 above)
Comment (DeagleGross) [reply src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs]: added comment

File: src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs [hunk 3]
```diff
@@ -31,8 +31,32 @@ public static void DeriveKeys(
...
+    /// Keys less than 112 bits in length are disallowed for HMAC generation.
+    /// The use of key lengths ≥ 112 bits is acceptable for HMAC generation.
+    /// <see href="https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf"/>
+    /// </remarks>
+    private const int FipsMinimumKeyLengthInBytes = 14;
+
     public static void DeriveKeys(ReadOnlySpan<byte> kdk, ReadOnlySpan<byte> label, ReadOnlySpan<byte> contextHeader, ReadOnlySpan<byte> contextData, Span<byte> operationSubkey, Span<byte> validationSubkey)
-        => DeriveKeys(kdk, label, contextHeader, contextData, operationSubkey, validationSubkey, prf: null);
+    {
+        if (kdk.Length < FipsMinimumKeyLengthInBytes)
```
Comment (bartonjs) [inline src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs:48]:
```C#
if (kdk.Length < FipsMinimumKeyLengthInBytes)
{
    Span<byte> zeroExtended = stackalloc byte[FipsMinimumKeyLengthInBytes];
    zeroExtend.Clear();
    kdk.CopyTo(zeroExtend);
    return DeriveKeys(zeroExtend, ...);
}
```

HMAC keys shorter than the algorithm's (internal) block size are zero-appended, so just doing that up front will give the same answer.

We clearly do that for the instance method.  I don't remember if we explicitly decided not to do it for the statics, or if it's just that it used to not be enforced by OSSL in their "FIPS mode" and now it is.

Comment (DeagleGross) [reply src/DataProtection/DataProtection/src/SP800_108/ManagedSP800_108_CTR_HMACSHA512.cs:48]: thanks for the insight Jeremy! I've changed the code as you suggested
