### PR TITLE
Include the exception when logging in WebAssemblyErrorBoundaryLogger

### LINKED ISSUE #39039: Using Custom ILogger with ErrorBoundary produces exception = null
I have a blazor webassembly project with a custom ILogger that worked fine. However, after I used the new ErrorBoundary, the public void Log<TState> method of the ILogger is called with logLever = Error and a null exception. 

```razor
 <ErrorBoundary @ref ="errorBoundary">
        <ChildContent>
            @Body
        </ChildContent>
        <ErrorContent Context="ex">  
             <div class="alert alert-danger alert-dismissible fade show m-3" role="alert" style="display:flex; z-index:99999;">
                 <div style="justify-content:flex-start;flex:10;"> <strong>Error:</strong>@ex.Message  </div>
                 <div style="justify-content:flex-end;flex:1"><a href="@CurrentPath" class="reload"  style="float:right;cursor:pointer;" >Reload <span class="material-icons" title="refresh"> refresh </span> </a> </div>                        
            </div>           
        </ErrorContent>
    </ErrorBoundary>
```

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/39039

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

File: src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyErrorBoundaryLogger.cs [hunk 1]
```diff
@@ -21,7 +19,7 @@ public ValueTask LogErrorAsync(Exception exception)
     {
         // For, client-side code, all internal state is visible to the end user. We can just
         // log directly to the console.
-        _errorBoundaryLogger.LogError(exception.ToString());
+        _errorBoundaryLogger.LogError(exception.ToString(), exception);
```
Comment (campersau) [inline src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyErrorBoundaryLogger.cs:22]: I think this is wrong, as the `exception` comes before the `message`. See #39223
