### PR TITLE
Use ImpersonationToken for IIS Windows Auth

### LINKED ISSUE #54175: AspNetCoreModuleV2: Windows Authentication (IIS, NTLM) not working when TokenImpersonationLevel is "Identification"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We run some ASP.NET Core services using In-process hosting with IIS and we use Windows Authentication.
We also use [CoreWCF](https://github.com/CoreWCF/CoreWCF) because we have some legacy clients that we still need to support.

It seems that old clients using .NET Framework cannot authenticate anymore. I found [this comment](https://github.com/CoreWCF/CoreWCF/issues/757#issuecomment-1468887924) that describes the same issue.

I analyzed the issue and it seems that it is caused by using [GetPrimaryToken here.](https://github.com/dotnet/aspnetcore/blob/32c9ec8d9c4b7f7f544cfb39dbf31f30a860d585/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/managedexports.cpp#L516) GetPrimaryToken() is also used [in Out-of-process hosting](https://github.com/dotnet/aspnetcore/blob/32c9ec8d9c4b7f7f544cfb39dbf31f30a860d585/src/Servers/IIS/AspNetCoreModuleV2/OutOfProcessRequestHandler/forwardinghandler.cpp#L822).

I don't know if this is really an issue but shouldn't [GetImpersonationToken](https://learn.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/ihttpuser-getimpersonationtoken-method) be used instead? GetPrimaryToken() returns 0 when authenticating with TokenImpersonationLevel.Identification. It is not 0 when TokenImpersonationLevel.Impersonation is used.
GetImpersonationToken() seems to return a handle to a token of the user making the HTTP request.

### Expected Behavior

Client applications that use .NET Framework must not be changed in order for Windows Authentication to work.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

- We don't have this problem when we use [HTTP.sys web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-8.0#configure-the-aspnet-core-app-to-use-httpsys)
- As we have to use IIS, I developed a native IIS module (as a workaround) that sets the IHttpUser and forwards the calls of GetPrimartyToken() to GetImpersonationToken() for WCF calls.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Closes https://github.com/dotnet/aspnetcore/issues/54175

The doc comments on [`GetPrimaryToken`](https://learn.microsoft.com/iis/web-development-reference/native-code-api-reference/ihttptokenentry-getprimarytoken-method) and [`GetImpersonationToken`](https://learn.microsoft.com/iis/web-development-reference/native-code-api-reference/ihttpuser-getimpersonationtoken-method) are next to useless so can't really comment on the difference between them. However, did look at the old .NET FX IIS code and it was using `GetImpersonationToken` so I feel a bit better about this change.

Looks like the same sort of issue is filed on corewcf as well https://github.com/CoreWCF/CoreWCF/issues/757
cc @mconnew

### CODE REVIEW

**Comment by amcasey** [comment]
What can we do to build confidence here?  It sounds like there's no expert to ask, but maybe we could have a feature flag in case it turns out to have been a mistake?  How would we / an app author know that it was a mistake?

File: src/Servers/IIS/IIS/test/Common.FunctionalTests/WindowsAuthTests.cs [hunk 1]
```diff
@@ -58,4 +60,51 @@ public async Task WindowsAuthTest(TestVariant variant)
...
+                TokenImpersonationLevel.Anonymous
+            };
+
+        foreach (var impersonationLevel in impersonationLevels)
+        {
+            // TokenImpersonationLevel is not supported by HttpClient so we need to use HttpWebRequest to test it.
+#pragma warning disable SYSLIB0014 // Type or member is obsolete
+            var request = HttpWebRequest.CreateHttp($"{deploymentResult.HttpClient.BaseAddress}Auth");
+#pragma warning restore SYSLIB0014 // Type or member is obsolete
+            request.ImpersonationLevel = impersonationLevel;
```
Comment (mconnew) [inline src/Servers/IIS/IIS/test/Common.FunctionalTests/WindowsAuthTests.cs:91]: I was going to say ImpersonationLevel isn't supported, but went to check the source code in case anything has changed and was surprised to see that they use reflection to enable it for HttpWebRequest, even though HttpClientHandler/SocketsHttpHandler don't expose the api. Time to open an issue as this is an important missing feature that WCF needs.

**Comment by mconnew** [comment]
@amcasey, I took a look at how this value is used in the rest of the code. The only opportunity to fail is when a WindowsIdentity instance is created in the aspnetcore side of things. That class checks the handle is a valid user access token handle before duplicating it internally, during construction. It's constructed on either HttpContext creation (in process), or at invocation of an incoming request (out of process). Either way, if this code does something which breaks things, requests won't even get dispatched, and you'll probably get a 500 response as the request will fail very early on.

**Review by amcasey — APPROVED** [review]

**Comment by leonverschuren** [comment]
@BrennanConroy any updates? Can we get this merged?

**Comment by etemi** [comment]
Is there any chance that this will be merged for the .NET 10 release?

File: src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/RequiresIISAttribute.cs [hunk 2]
```diff
@@ -136,7 +136,7 @@ public RequiresIISAttribute(IISCapability capabilities)
                 IsMet &= available;
                 if (!available)
                 {
-                    SkipReason += $"The machine does have {module.Capability} available.";
+                    SkipReason += $"The machine does not have {module.Capability} available.";
```
Comment (adityamandaleeka) [inline src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/RequiresIISAttribute.cs:139]: 😆

**Review by adityamandaleeka — APPROVED** [review]

**Comment by petersladek** [comment]
@BrennanConroy Given this is going to be fixed in .net 10, is there any chance that kind of related issue [ANCM should forward the mapped Identity instead of the client certificate after IIS Client Cert Mapping Auth](https://github.com/dotnet/aspnetcore/issues/42896) will be fixed too in .net 10?
