### PR TITLE
[Blazor] Form mapping support for select multiple, logging, DataMember and other improvements/cleanups

### LINKED ISSUE #50464: Race condition in shared form mapping resolution logic
This behavior can be reproed with the benchmarks available at https://github.com/aspnet/Benchmarks/pull/1900.

Repro:

```
crank --config ./src/BenchmarksApps/Mvc/benchmarks.mvcjson.yml --scenario MapActionEchoTodoFormMapping --profile aspnet-perf-lin --profile short --application.framework net8.0 --application.source.branchOrCommit safia/fromform-tes
```

Exceptions:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IC", Request id "0HMTAABU203IC:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IE", Request id "0HMTAABU203IE:00000001": An unhandled exception was thrown by the application.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.RemoveAt(Int32 index)
         at System.Collections.Generic.List`1.Remove(T item)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IL", Request id "0HMTAABU203IL:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IF", Request id "0HMTAABU203IF:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203II", Request id "0HMTAABU203II:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IH", Request id "0HMTAABU203IH:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IM", Request id "0HMTAABU203IM:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot end a resolution graph while one is not in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.EndResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203IG", Request id "0HMTAABU203IG:00000001": An unhandled exception was thrown by the application.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.RemoveAt(Int32 index)
         at System.Collections.Generic.List`1.Remove(T item)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTAABU203ID", Request id "0HMTAABU203ID:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Cannot begin a new resolution graph while one is already in progress.
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.FormMetadataContext.BeginResolveGraph()
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata.FormDataMetadataFactory.GetOrCreateMetadataFor(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.ComplexTypeConverterFactory.CanConvert(Type type, FormDataMapperOptions options)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.CreateConverter(Type type, FormDataMapperOptions options)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapperOptions.ResolveConverter[T]()
         at lambda_method3(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass103_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

### PR DESCRIPTION
**Pull request by javiercn**
* Support binding multiple values for a given form key for primitive collections (select multiple is the use case).
* Add logging and more tests to our metadata factory
* Add support for `DataMember` in the expression formatter.
* Add an expression cache for simple member access expressions in `FieldIdentifier`

Fixes #50464, #49753, #49468, #49744, #50376

### CODE REVIEW

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs [hunk 1]
```diff
@@ -2,31 +2,50 @@
...
+                return default;
             }
-
-            // Always return the result, even if it has failures. This is because we do not want
-            // to loose the data that we were able to deserialize.
-            return result;
+        }
+        catch (Exception)
+        {
+            Log.CannotResolveConverter(options.Logger, typeof(T));
```
Comment (captainsafia) [inline src/Components/Endpoints/src/FormMapping/FormDataMapper.cs:29]: Can we log the exception here?

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs [hunk 2]
```diff
@@ -2,31 +2,50 @@
...
+
+        // Always return the result, even if it has failures. This is because we do not want
+        // to loose the data that we were able to deserialize.
+        return result;
+    }
+
+    private static partial class Log
+    {
+        [LoggerMessage(1, LogLevel.Warning, "Cannot resolve converter for type '{Type}'.", EventName = "CannotResolveConverter")]
+        public static partial void CannotResolveConverter(ILogger logger, Type type);
```
Comment (captainsafia) [inline src/Components/Endpoints/src/FormMapping/FormDataMapper.cs:49]:
```suggestion
        public static partial void CannotResolveConverter(ILogger logger, Type type, Exception exception);
```

File: src/Components/Endpoints/src/FormMapping/Metadata/FormDataMetadataFactory.cs [hunk 3]
```diff
@@ -7,162 +7,246 @@
 using System.Runtime.CompilerServices;
 using System.Runtime.Serialization;
 using Microsoft.Extensions.Internal;
+using Microsoft.Extensions.Logging;
 
 namespace Microsoft.AspNetCore.Components.Endpoints.FormMapping.Metadata;
 
-internal class FormDataMetadataFactory(List<IFormDataConverterFactory> factories)
+internal partial class FormDataMetadataFactory(List<IFormDataConverterFactory> factories, Extensions.Logging.ILoggerFactory loggerFactory)
```
Comment (captainsafia) [inline src/Components/Endpoints/src/FormMapping/Metadata/FormDataMetadataFactory.cs:14]:
```suggestion
internal partial class FormDataMetadataFactory(List<IFormDataConverterFactory> factories, ILoggerFactory loggerFactory)
```

File: src/Components/Endpoints/test/Binding/FormDataMapperTests.cs [hunk 4]
```diff
@@ -10,6 +10,7 @@
 using System.Globalization;
 using System.Runtime.Serialization;
 using Microsoft.Extensions.Primitives;
+using Newtonsoft.Json.Linq;
```
Comment (captainsafia) [inline src/Components/Endpoints/test/Binding/FormDataMapperTests.cs:13]:
```suggestion
```
😲

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs [hunk 5]
```diff
@@ -2,31 +2,50 @@
...
         FormDataReader reader,
         FormDataMapperOptions options)
     {
+        FormDataConverter<T>? converter;
         try
         {
-            var converter = options.ResolveConverter<T>();
-            if (converter.TryRead(ref reader, typeof(T), options, out var result, out _))
+            converter = options.ResolveConverter<T>();
+            if (converter == null)
```
Comment (captainsafia) [inline src/Components/Endpoints/src/FormMapping/FormDataMapper.cs:21]: Should we update the nullability of `FormDataMapperOptions.ResolverConverter` to indicate that it may return null?

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs [hunk 6]
```diff
@@ -2,31 +2,50 @@
...
-            // Always return the result, even if it has failures. This is because we do not want
-            // to loose the data that we were able to deserialize.
-            return result;
+        }
+        catch (Exception)
+        {
+            Log.CannotResolveConverter(options.Logger, typeof(T));
+            return default;
         }
         finally
```
Comment (captainsafia) [inline src/Components/Endpoints/src/FormMapping/FormDataMapper.cs:32]: This `finally` block seems redundant?

**Review by captainsafia — APPROVED** [review]

File: src/Components/Endpoints/test/Binding/FormDataMapperTests.cs (hunk 4 above)
Comment (javiercn) [reply src/Components/Endpoints/test/Binding/FormDataMapperTests.cs]: I hate the auto add namespace from VS precisely for this.

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs (hunk 5 above)
Comment (javiercn) [reply src/Components/Endpoints/src/FormMapping/FormDataMapper.cs:21]: I've updated it

File: src/Components/Endpoints/src/FormMapping/FormDataMapper.cs (hunk 2 above)
Comment (javiercn) [reply src/Components/Endpoints/src/FormMapping/FormDataMapper.cs]: Updated

File: src/Components/Endpoints/src/DependencyInjection/RazorComponentsServiceCollectionExtensions.cs [hunk 7]
```diff
@@ -61,7 +61,8 @@ public static IRazorComponentsBuilder AddRazorComponents(this IServiceCollection
         services.TryAddScoped<ComponentStatePersistenceManager>();
         services.TryAddScoped<PersistentComponentState>(sp => sp.GetRequiredService<ComponentStatePersistenceManager>().State);
         services.TryAddScoped<IErrorBoundaryLogger, PrerenderingErrorBoundaryLogger>();
-        services.TryAddEnumerable(ServiceDescriptor.Singleton<IConfigureOptions<RazorComponentsEndpointOptions>, RazorComponentsEndpointsDetailedErrorsConfiguration>());
+        services.ConfigureOptions<DefaultRazorComponentsServerOptionsConfiguration>();
+        //services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<RazorComponentsServerOptions>, DefaultRazorComponentsServerOptionsConfiguration>());
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Endpoints/src/DependencyInjection/RazorComponentsServiceCollectionExtensions.cs]: Good catch, this was just leftover

**Comment by javiercn** [comment]
@mkArtak can you merge? The only complain here is about a public API change that we did as part of API review
