### PR TITLE
SupplyParameterFromTempData support for Blazor

### LINKED ISSUE #49683: Blazor TempData
MVC & Razor Pages have a TempData feature that you can use to store some data that is intended to be read in a future request. We should consider adding something similar for Blazor server-side rendering.

For example, the default Identity UI makes use of TempData in variety of scenarios. We need some way to replicate this functionality.

### LINKED ISSUE #65039: TempData design proposal
## Summary

Enables developers to persist temporary data between HTTP requests in Blazor SSR using TempData with read-once semantics. Provides an API with pluggable storage backends (cookies by default, session as alternative) that automatically manages data lifecycle without requiring custom solutions or interactivity modes.

## Motivation and goals

Right now in the Blazor SSR there is a gap in the storage in-between requests (see https://github.com/dotnet/aspnetcore/issues/49683). Currently to store data in-between requests, users are supposed to create their own solutions even for the simplest of the situations (e.g. success page after redirect) or use interactivity to escape the problem altogether. We already have multiple solutions for this problem in the MVC that we can use as a template. TempData is one of them that allows users to persist values in-between requests. 

TempData provides short-lived, server-side storage that survives exactly one additional HTTP request (read-once semantics) or more, if the user wants to do so. By default it is write-read-delete, but there is an option to read it without deletion. It's specifically designed for redirect scenarios where data needs to pass from one request to another but should not persist longer.

## In scope

- Automatically delete data after being read, with opt-in retention via `Peek()` and `Keep()` methods.
- TempData works out-of-the-box with cookie storage when calling `AddRazorComponents()`.
- Support both cookie-based (default) and session-based storage providers.
- Support primitives, DateTime, Guid, enums, and collections (arrays, List<T>, Dictionary<string, T>).
- Automatic lifecycle management (no manual save/load needed).

## Out of scope

- Support for user-defined classes or custom object serialization is not a goal. Only JSON-serializable primitives and collections are supported.
- Using both cookie and session storage simultaneously is not supported. Developers must choose one storage mechanism per application.
- TempData is designed for SSR scenarios only. Support for Blazor WebAssembly and Blazor Server is excluded as they have different state management patterns.
- Pluggable serialization providers beyond the built-in JSON serializer are not supported.

## Risks / unknowns

- **Cookie Size Limits:** browsers enforce 4KB cookie limits. Developers storing large amounts of data may exceed this limit, causing silent data loss or HTTP 400 errors. *Mitigation:* use `ChunkingCookieManager` to automatically split cookies across multiple cookie headers and recommendation to use session storage for larger data needs.

- **Session Affinity Requirements:** Session storage requires sticky sessions in load-balanced environments. Without it, users may lose data mid-flow. *Mitigation:* clear documentation that session storage requires session affinity or distributed cache and recommendations for using cookies for stateless deployments.

## Examples

**Basic form with flash messages:**
```razor
@page "/my-form"
@inject NavigationManager NavigationManager

<p id="message">@_message</p>

<form method="post" @formname="MyForm" @onsubmit="HandleSubmit">
    <AntiforgeryToken />
    <input type="text" name="Name" />
    <button type="submit">Submit</button>
</form>

@code {
    [CascadingParameter]
    public ITempData? TempData { get; set; }

    private string? _message;

    protected override void OnInitialized()
    {
        // Get removes the value after reading (one-time use)
        _message = TempData?.Get("Message") as string ?? "No message";
    }

    private void HandleSubmit()
    {
        // Set success message
        TempData!["Message"] = "Form submitted successfully!";
        
        // Redirect - message will be available on next request
        NavigationManager.NavigateTo("/my-form", forceLoad: true);
    }
}
```

**Reading without consuming (Peek):**
```razor
@code {
    protected override void OnInitialized()
    {
        // Peek reads without removing - value available on next request too
        var notification = TempData?.Peek("Notification") as string;
    }
}
```

**Keeping values for another request:**
```razor
@code {
    protected override void OnInitialized()
    {
        var message = TempData?.Get("Message") as string;
        
        // Keep this specific value for one more request
        TempData?.Keep("Message");
        
        // Or keep all values
        TempData?.Keep();
    }
}
```

### Overview

TempData is automatically enabled when calling `AddRazorComponents()` and provided to components as a cascading value. It uses pluggable storage backends (cookies by default, with session storage as an alternative) and implements read-once semantics where values are automatically removed after being read unless explicitly retained.

### Storage Providers

Developers can choose between two storage mechanisms:

#### Cookie-Based Storage (Default)

Cookie storage works out-of-the-box without additional configuration. The implementation:
- Serializes data to JSON and encrypts it using ASP.NET Core Data Protection APIs
- Stores encrypted data in a cookie named `.AspNetCore.Components.TempData`
- Automatically handles cookie chunking for larger payloads

**Configuration:**
```csharp
// Default - no configuration needed
builder.Services.AddRazorComponents();

// Optional: Customize cookie settings
builder.Services.AddCookieTempDataValueProvider(options =>
{
    options.Cookie.Name = ".MyApp.TempData";
    options.Cookie.SameSite = SameSiteMode.Strict;
});
```

#### Session Storage

Session storage is available for scenarios requiring larger data storage or when cookies are undesirable:
- Requires explicit session state configuration
- No practical size limits (within session constraints)
- Requires sticky sessions in load-balanced environments

**Configuration:**
```csharp
builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession();
builder.Services.AddSessionStorageTempDataValueProvider();

app.UseSession();
```

### Component Access

TempData is provided as a cascading value, making it accessible throughout the component hierarchy without explicit injection:

```razor
@code {
    [CascadingParameter]
    public ITempData? TempData { get; set; }
}
```

### API Design

The `ITempData` interface extends `IDictionary<string, object?>` for familiarity with MVC developers, while adding specialized methods for controlling retention:

```csharp
public interface ITempData : IDictionary<string, object?>
{
    object? Get(string key);      // Read and mark for deletion
    object? Peek(string key);     // Read without marking for deletion
    void Keep();                  // Retain all values for next request
    void Keep(string key);        // Retain specific value for next request
}
```

### Read-Once Semantics

TempData implements automatic cleanup to prevent stale data:

1. **On Load**: All values from storage are marked as "retained" (available for this request)
2. **On Access**: `Get()` removes the retention marker; `Peek()` preserves it
3. **On Save**: Only retained values are persisted to storage
4. **Developer Control**: `Keep()` re-adds retention markers to override automatic deletion

This ensures data persists exactly as long as needed without manual cleanup.

### Supported Data Types

TempData supports JSON-serializable types:
- **Primitives**: `string`, `int`, `bool`, `double`, `decimal`, etc.
- **Common Types**: `Guid`, `DateTime`, `DateTimeOffset`, `TimeSpan`, `Uri`.
- **Collections**: Arrays, `List<T>`, `Dictionary<string, T>` where T is a supported type that was mentioned before.
- **Enums**: All enum types.

Complex user-defined types are not supported to keep the API predictable and prevent serialization issues. An exception is thrown at save time if unsupported types are detected.

### Key Design Decisions

- **Cascading Value vs. Injection:** provide TempData as a cascading value rather than requiring `@inject` in every component. This makes TempData accessible throughout the component tree without explicit injection, similar to how `HttpContext` is provided. Components that don't use TempData don't need to declare it.

- **Cookie as Default:** use cookie storage by default, with session storage as opt-in. This matches MVC TempData behavior for easier migration, works without additional configuration (session requires middleware setup), suitable for most scenarios (flash messages, PRG pattern).

- **Lazy Loading:** only load TempData from storage when first accessed by a component. This avoids unnecessary cookie parsing or session lookups for requests that don't use TempData, improving performance for components that don't need temporary data.

- **Case-Insensitive Keys:** keys are case-insensitive (`TempData["message"]` == `TempData["Message"]`), preventing subtle bugs from casing differences.

### Request Lifecycle Integration

TempData integrates with the request pipeline through:

1. **Automatic Registration**: Registered as a cascading value when `AddRazorComponents()` is called
2. **Lazy Loading**: Storage access deferred until first use
3. **Automatic Save**: Values persisted via `Response.OnStarting` callback, ensuring data is saved even if components don't explicitly trigger persistence
4. **Single Instance**: One TempData instance per request, stored in `HttpContext.Items`

This design ensures TempData "just works" without requiring explicit lifecycle management from developers.

### No Compile-Time Type Safety
TempData stores `object?` values, requiring runtime casting: `var name = TempData["Name"] as string`. There's no IntelliSense or type checking, increasing likelihood of runtime errors compared to strongly-typed alternatives.

### Cookie Size Constraints
The default cookie storage has a ~4KB browser limit. While chunking helps, developers storing large datasets must switch to session storage, which introduces session affinity requirements.

### Session Storage Complexity
Session storage requires additional middleware configuration (`AddSession()`, `UseSession()`), distributed cache setup for scaled deployments, and sticky sessions for load balancing. This adds deployment and operational complexity.

## Considered Alternatives

The alternative that was considered was the `[SupplyParameterFromTempData]` attribute that would have worked similar to the `[SupplyParameterFromQuery]`. It was rejected due to not being robust and flexible enough. This approach did not allow for an easy-to-use `Peek()` and `Keep()` as well as a clear dictionary-like interface.

### PR DESCRIPTION
**Pull request by dariatiurina**
# SupplyParameterFromTempData

## Summary

Provides `[SupplyParameterFromTempData]` attribute for Blazor SSR components to read and write TempData values, consistent with `[SupplyParameterFromQuery]` and `[SupplyParameterFromForm]` patterns.

## Motivation

While TempData is accessible via the `[CascadingParameter] ITempData` approach, many scenarios only need simple read/write of a single value. The attribute-based approach:
- Reduces boilerplate for common use cases
- Provides consistency with existing `SupplyParameterFrom*` attributes
- Enables automatic two-way binding without manual `TempData["key"]` access

### Attribute

```csharp
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public sealed class SupplyParameterFromTempDataAttribute : CascadingParameterAttributeBase
{
    /// Gets or sets the TempData key. If not specified, the property name will be used.
    public string? Name { get; set; }

    internal override bool SingleDelivery => false;
}
```

### Framework abstractions

Two new types enable attribute-driven cascading value suppliers without building a full `ICascadingValueSupplier` from scratch:

**`CascadingParameterSubscription`** — a new public abstract base class representing an active subscription to a cascading parameter:
```csharp
public abstract class CascadingParameterSubscription : IDisposable
{
    public abstract object? GetCurrentValue();
    public abstract void Dispose();
}
```

**`CascadingParameterValueProvider<TAttribute>`** — an internal generic `ICascadingValueSupplier` that manages subscriptions for a given attribute type. Consumers provide a factory `Func<ComponentState, TAttribute, CascadingParameterInfo, CascadingParameterSubscription>` and the provider handles `CanSupplyValue`, `GetCurrentValue`, `Subscribe`, and `Unsubscribe` by delegating to subscription instances keyed by `(ComponentState, PropertyName)`.

**`TryAddCascadingValueSupplier<TAttribute>`** — a new public extension method on `IServiceCollection` that registers a `CascadingParameterValueProvider<TAttribute>` using `TryAddEnumerable`:
```csharp
public static IServiceCollection TryAddCascadingValueSupplier<TAttribute>(
    this IServiceCollection serviceCollection,
    Func<IServiceProvider, Func<ComponentState, TAttribute, CascadingParameterInfo, CascadingParameterSubscription>> subscribeFactory)
    where TAttribute : CascadingParameterAttributeBase;
```

### TempDataCascadingValueSupplier

The internal `TempDataCascadingValueSupplier` class bridges the cascading value provider and the underlying TempData store:

- **`SetRequestContext(HttpContext)`** — wires the supplier to the current request.
- **`CreateSubscription(ComponentState, SupplyParameterFromTempDataAttribute, CascadingParameterInfo)`** — uses reflection (`PropertyGetter`) to create a property getter for the decorated property, registers a value callback, and returns a `TempDataSubscription`.
- **`RegisterValueCallback(string, Func<object?>)`** — stores a getter invoked at persist time. Throws `InvalidOperationException` for duplicate keys.
- **`PersistValues(ITempData)`** — iterates all registered callbacks, reads current property values, and writes them into TempData. Callback exceptions are caught, logged, and do not prevent other keys from being persisted.
- **`DeleteValueCallback(string)`** — removes a registered callback (called on component unsubscribe to prevent memory leaks).

### TempDataSubscription

The nested `TempDataSubscription` class (inside `TempDataCascadingValueSupplier`) implements value retrieval directly:

- **First call to `GetCurrentValue()`**: reads from TempData via `_owner.GetTempData()` using `ITempData.Get()` semantics (marks for deletion). Handles enum conversion (`int` → enum via `Enum.ToObject`), type mismatches (returns `null`), and deserialization errors (caught, logged, returns `null`).
- **Subsequent calls to `GetCurrentValue()`**: returns the component's current property value via the stored getter, avoiding overriding modifications the component made during rendering.

### Lifecycle

1. **Initialize**: `TempDataCascadingValueSupplier.SetRequestContext(HttpContext)` is called during `EndpointHtmlRenderer.InitializeStandardComponentServicesAsync`, wiring the supplier to the current request.
2. **Subscribe**: When a component renders, `CascadingParameterValueProvider<TAttribute>` calls `TempDataCascadingValueSupplier.CreateSubscription()`, which uses reflection to build a property getter and registers a callback via `RegisterValueCallback()`.
3. **First delivery**: `TempDataSubscription.GetCurrentValue()` reads from TempData using `Get()` semantics (marks for deletion). Enum values stored as `int` are converted to the target enum type. Type mismatches and deserialization errors are caught and logged, returning `null`.
4. **Subsequent reads**: After the first delivery, `GetCurrentValue()` returns the component's current property value to avoid overwriting changes made by the component during rendering.
5. **Persist**: When `TempDataService.Save()` is called, it invokes `TempDataCascadingValueSupplier.PersistValues(tempData)`, which iterates all registered callbacks, reads the current property values from the components, and writes them back into TempData.
6. **Unsubscribe**: When a component is disposed, `TempDataSubscription.Dispose()` calls `DeleteValueCallback()` to remove the registered callback.

### Implementation details

- **Case-insensitive callbacks**: The internal callback dictionary uses `StringComparer.OrdinalIgnoreCase`.
- **Duplicate key guard**: `RegisterValueCallback` throws `InvalidOperationException` if a callback is already registered for the same key — multiple components cannot bind to the same TempData key.
- **TempData resolution**: `TempDataCascadingValueSupplier.GetTempData()` reads the `ITempData` instance from `HttpContext.Items` using the static `TempDataProviderServiceCollectionExtensions.HttpContextItemKey` sentinel — the same single instance used by the cascading parameter approach.
- **Type safety**: Enum values stored as `int` are converted via `Enum.ToObject`. If the stored value's type is not assignable to the target type, `null` is returned instead of throwing.
- **Error logging**: Two log events — `TempDataPersistFail` (callback exception during persist) and `TempDataDeserializeFail` (exception during read).

### Registration

Automatically enabled when calling `AddRazorComponents()`:

```csharp
services.TryAddScoped<TempDataCascadingValueSupplier>();
services.TryAddCascadingValueSupplier<SupplyParameterFromTempDataAttribute>(
    sp => sp.GetRequiredService<TempDataCascadingValueSupplier>().CreateSubscription);
```

## Usage

**Basic:**
```razor
@code {
    [SupplyParameterFromTempData]
    public string? Message { get; set; }
}
```

**Custom key:**
```razor
@code {
    [SupplyParameterFromTempData(Name = "flash_message")]
    public string? Message { get; set; }
}
```

**Form with redirect:**
```razor
@page "/form"

<p>@Message</p>

<form method="post" @formname="SetMessage" @onsubmit="Submit">
    <AntiforgeryToken />
    <button type="submit">Submit</button>
</form>

@code {
    [SupplyParameterFromTempData]
    public string? Message { get; set; }

    void Submit()
    {
        Message = "Success!";
        NavigationManager.NavigateTo("/form", forceLoad: true);
    }
}
```

## Testing

- **Unit tests** (`TempDataCascadingValueSupplierTest.cs`, 8 tests): Covers `RegisterValueCallback` (add, duplicate key guard), `PersistValues` (single/multiple keys, null values, callback exceptions, case-insensitivity), and `DeleteValueCallback`.
- **Unit tests** (`TempDataSubscriptionTest.cs`, 13 tests): Covers `GetCurrentValue` (null cases, missing keys, case-insensitivity, enum conversion, nullable enum, type mismatches, deserialization errors, first-delivery semantics), and `CreateSubscription` integration with the supplier.
- **E2E tests**: `SupplyParameterFromTempDataReadsAndSavesValues` added to both `TempDataCookieTest` and `TempDataSessionStorageTest`, verifying read/write roundtrip through the attribute.

## Out of scope

- `Peek()` and `Keep()` semantics — use `[CascadingParameter] ITempData` for advanced control
- Custom serialization

## Risks

- **Callback ordering**: When a component uses both `TempData["key"]` directly and `[SupplyParameterFromTempData]` for the same key, the final persisted value depends on execution order. *Mitigation*: Document that mixing approaches for the same key is unsupported.

Fixes #49683
Fixes #65039

### CODE REVIEW

File: src/Components/Components/src/ITempDataValueMapper.cs
Comment (javiercn) [inline src/Components/Components/src/ITempDataValueMapper.cs:1]: Does this need to live here as opposed to in endpoints?

File: src/Components/Components/src/SupplyParameterFromTempDataServiceCollectionExtensions.cs
Comment (javiercn) [inline src/Components/Components/src/SupplyParameterFromTempDataServiceCollectionExtensions.cs:1]: Can this move to Endpoints?

File: src/Components/Components/src/SupplyParameterFromTempDataValueProvider.cs
Comment (javiercn) [inline src/Components/Components/src/SupplyParameterFromTempDataValueProvider.cs:1]: Can this move to endpoints?

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/TempData/TempDataComponent.razor
Comment (javiercn) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/TempData/TempDataComponent.razor:1]: Does setting the property causes it to be saved to temp data for the next navigation?

Comment (dariatiurina) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/TempData/TempDataComponent.razor:1]: Yes. But reading through this property always goes through `Get()` so it only persists once.

File: src/Components/Endpoints/src/TempData/TempDataValueMapper.cs [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    {
+        _logger = logger;
+    }
+
+    internal void SetRequestContext(HttpContext httpContext)
+    {
+        _httpContext = httpContext;
+    }
+
+    public object? GetValue(string tempDataKey, Type type)
```
Comment (ilonatommy) [inline src/Components/Endpoints/src/TempData/TempDataValueMapper.cs]: `type` param is unused, why?

File: src/Components/Endpoints/src/Rendering/EndpointComponentState.cs [hunk 2]
```diff
@@ -47,7 +47,7 @@ public EndpointComponentState(Renderer renderer, int componentId, IComponent com
 
     public bool StreamRendering { get; }
 
-    protected override object? GetComponentKey()
+    protected internal override object? GetComponentKey()
```
Comment (ilonatommy) [inline src/Components/Endpoints/src/Rendering/EndpointComponentState.cs]: This `ResolveComponentForRenderMode` and `GetComponentRenderMode` and `Assets` changed the visibility. I don't see them used in any unit tests, isn't it leftover from development?

File: src/Components/Endpoints/src/TempData/TempDataValueMapper.cs [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+            object? value = null;
+            foreach (var valueGetter in callbacks)
+            {
+                try
+                {
+                    var candidateValue = valueGetter();
+                    if (candidateValue is not null)
+                    {
+                        value = candidateValue;
+                        break;
```
Comment (ilonatommy) [inline src/Components/Endpoints/src/TempData/TempDataValueMapper.cs]: Can multiple components use same TempData key?

Comment (ilonatommy) [reply src/Components/Endpoints/src/TempData/TempDataValueMapper.cs]: Stale, resolving.

File: src/Components/Endpoints/src/TempData/TempDataValueMapper.cs [hunk 4]
```diff
@@ -0,0 +1,104 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Text.Json;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components.Endpoints;
+
+internal partial class TempDataValueMapper : ITempDataValueMapper
```
Comment (ilonatommy) [inline src/Components/Endpoints/src/TempData/TempDataValueMapper.cs]: Can you name a scenario where someone would want to implement a custom `ITempDataValueMapper` or
use `ITempDataValueMapper` directly without `SupplyParameterFromTempDataValueProvider`? I cannot think of any. I think we can simplify the implementation.

`TempDataValueMapper` and `ITempDataValueMapper` have 3 unrelated responsibilities: getting value, managing callbacks and being DI injection point. We could merge it into `SupplyParameterFromTempDataValueProvider` that would have the responsibility of supplying the values to compoennts that declare `[SupplyParameterFromTempData]`, reading, subscribing etc would be just implementation details of that responsibility.

That would shrink the volume of new public APIs and would make it easier to read the code. It would require removing `TempDataValueMapper` and `ITempDataValueMapper`, moving `PersistValues` and `GetTempData` to `SupplyParameterFromTempDataValueProvider` together with subscription bits. + updating the registration to `services.TryAddScoped<SupplyParameterFromTempDataValueProvider>();`

File: src/Components/Endpoints/src/TempData/SupplyParameterFromTempDataAttribute.cs [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace Microsoft.AspNetCore.Components.Endpoints;
+
+/// <summary>
+/// Indicates that the value of the associated property should be supplied from
+/// the TempData with the specified name.
+/// </summary>
+[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
+public sealed class SupplyParameterFromTempDataAttribute : CascadingParameterAttributeBase
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/SupplyParameterFromTempDataAttribute.cs]: We likely need to move the attribute to Components.Web. Otherwise, razor class libraries can't use it.

**Review by javiercn — COMMENTED** [review]
Thanks for pushing through this. 

Overall looks good, but the ITempDataValueMapper in components is a symptom that something is missing here. I've poked a bit around it and I'd like to suggest an alternative shape for the design that I think keeps the same behavior while reducing what we add to `Microsoft.AspNetCore.Components` and making the pattern more reusable. Happy to discuss further if any of this doesn't seem worthwhile.

---

The main thing I noticed is that `ITempDataValueMapper` ends up being a public type in the base Components library solely to serve as a seam between the Components and Endpoints assemblies. It carries a three-method protocol (`GetValue`, `RegisterValueCallback`, `DeleteValueCallback`) where the ordering is implicit, and none of it means anything outside TempData specifically. I wonder if we could avoid putting that in the base library entirely.

My suggestion is to introduce two small general-purpose types instead:

**`CascadingParameterSubscription`** — a public abstract class that represents one component's subscription to a cascading value source. It pairs value retrieval with cleanup in a single object:

```csharp
public abstract class CascadingParameterSubscription : IDisposable
{
    public abstract object? GetCurrentValue();
    public abstract void Dispose();
}
```

**`AddCascadingValueSupplier<TAttribute>`** — a new overload on `CascadingValueServiceCollectionExtensions` that wires up a scoped `ICascadingValueSupplier` for any attribute type via a subscribe factory:

```csharp
public static IServiceCollection AddCascadingValueSupplier<TAttribute>(
    this IServiceCollection serviceCollection,
    Func<IServiceProvider, Func<ComponentState, TAttribute, CascadingParameterInfo, CascadingParameterSubscription>> subscribeFactoryResolver)
    where TAttribute : CascadingParameterAttributeBase
```

The internal plumbing (`CascadingParameterValueProvider<TAttribute>`) holds a `Dictionary<ComponentState, CascadingParameterSubscription>` and just routes the framework's lifecycle calls through to the factory:

```csharp
void ICascadingValueSupplier.Subscribe(ComponentState subscriber, in CascadingParameterInfo parameterInfo)
    => _subscriptions[subscriber] = _subscribeFactory(subscriber, (TAttribute)parameterInfo.Attribute, parameterInfo);

object? ICascadingValueSupplier.GetCurrentValue(object? key, in CascadingParameterInfo parameterInfo)
    => key is ComponentState s && _subscriptions.TryGetValue(s, out var sub) ? sub.GetCurrentValue() : null;

void ICascadingValueSupplier.Unsubscribe(ComponentState subscriber, in CascadingParameterInfo parameterInfo)
    { if (_subscriptions.Remove(subscriber, out var sub)) sub.Dispose(); }
```

On the Endpoints side, `TempDataCascadingValueSupplier` (renamed from `TempDataValueMapper`) doesn't need to implement any interface at all. All the reflection, property getter construction, and HTTP context access stays inside one class in the Endpoints assembly. The only thing it exposes is a `CreateSubscription` method. The concrete subscription is a small private nested class:

```csharp
private sealed class TempDataSubscription : CascadingParameterSubscription
{
    public override object? GetCurrentValue() => _owner.GetValue(_key, _propertyType);
    public override void Dispose() => _owner._registeredValues.Remove(_key);
}
```

I'd also move `SupplyParameterFromTempDataAttribute` to `Microsoft.AspNetCore.Components.Web`, since it only makes sense in an HTTP context and the base library targets non-HTTP environments too (Blazor WASM, MAUI Hybrid). The registration then becomes:

```csharp
services.TryAddScoped<TempDataCascadingValueSupplier>();
services.AddCascadingValueSupplier<SupplyParameterFromTempDataAttribute>(
    sp => sp.GetRequiredService<TempDataCascadingValueSupplier>().CreateSubscription);
```

---

A few reasons I think this shape is worth considering:

- The public API addition to `Microsoft.AspNetCore.Components` shrinks to just `CascadingParameterSubscription` and the `AddCascadingValueSupplier` overload — neither of which is TempData-specific.
- `ITempDataValueMapper` and `SupplyParameterFromTempDataServiceCollectionExtensions` go away entirely.
- The Components base library no longer needs to know about value callbacks, key deletion, or anything else that belongs to the TempData implementation.
- Any future per-component cascading parameter attribute (say, `[SupplyParameterFromSessionData]`) could reuse `AddCascadingValueSupplier` and `CascadingParameterSubscription` without needing a new interface, a new extension class, or access to the internal `ICascadingValueSupplier`.

Let me know what you think!

File: src/Components/Endpoints/src/TempData/TempDataValueMapper.cs (hunk 4 above)
Comment (dariatiurina) [reply src/Components/Endpoints/src/TempData/TempDataValueMapper.cs]: Changed the design, not applicable anymore

**Review by ilonatommy — APPROVED** [review]
It looks very good. If we really wanted to change something, my test coverage report shows no tests for `CreateSubscription`.

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+    internal CascadingParameterSubscription CreateSubscription(
+        ComponentState componentState,
+        SupplyParameterFromTempDataAttribute attribute,
+        CascadingParameterInfo parameterInfo)
+    {
+        var tempDataKey = attribute.Name ?? parameterInfo.PropertyName;
+        var componentType = componentState.Component.GetType();
+        var propertyInfo = componentType.GetProperty(
+            parameterInfo.PropertyName,
+            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: Look for PropertyGetter and PropertySetter, we should use those.

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+        this.RegisterValueCallback(tempDataKey, () =>
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: nit: no this

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 8]
```diff
@@ -0,0 +1,166 @@
...
+using Microsoft.AspNetCore.Components.Web;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Components.Endpoints;
+
+internal partial class TempDataCascadingValueSupplier
+{
+    private HttpContext? _httpContext;
+    private readonly Dictionary<string, Func<object?>> _valueCallbacks = new(StringComparer.OrdinalIgnoreCase);
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs:18]: You probably want to store the subscription here, and move the code from GetValue into the Subscription and have GetValue here simply look up the subscription and call that code.

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 9]
```diff
@@ -0,0 +1,166 @@
...
+                return null;
+            }
+
+            return value;
+        }
+        catch (Exception ex)
+        {
+            Log.TempDataDeserializeFail(_logger, ex);
+            return null;
+        }
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: If you move this into the tempdata subscription, you can do all the logic for computing the underlying value and in the constructor so the validation doesn't run every time get value is called.

Here you only retrieve the subscription and call subscription.GetValue(key, tempdata)

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+
+    private ITempData? GetTempData()
+    {
+        if (_httpContext is null)
+        {
+            return null;
+        }
+
+        var key = typeof(ITempData);
+        if (_httpContext.Items.TryGetValue(key, out var tempDataObj) && tempDataObj is ITempData tempData)
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: Normally for this dictionary a private object is used as the key, kind of like a 'symbol' in javascript, so that people without access to the symbol can't get the value

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
+        this.RegisterValueCallback(tempDataKey, () =>
+        {
+            var value = propertyInfo?.GetValue(componentState.Component);
+            return value;
+        });
+        return new TempDataSubscription(this, tempDataKey, parameterInfo.PropertyType);
+    }
+
+    internal object? GetValue(string tempDataKey, Type targetType)
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: This implementation works if the component only receives parameters once. If you are into a situation where a component renders twice, and someone has set the value for the temp data property (to save a new value) it will be overriden.

You can force it doing something like this:
```parent.razor
<child Value="@counter">

@code{
private int counter = 0;

OnInitialized()
{
  await Task.Yield();
  counter++;
}
```

and within child, use the value provider, capture the initial value within on initialized, set it to something else, and then see the final value. the replaced value should have been overriden.

(This is the same problem persistent component state had).

Once you reproduce this, try and use SingleDelivery (like form does) or we will have to replicate the same logic here.

**Review by javiercn — COMMENTED** [review]
Looks great so far!

I have some smaller comments, and I need to take a look at some of the unit tests, but otherwise, it looks good.

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs (hunk 6 above)
Comment (dariatiurina) [reply src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: We can't use them in Endpoints. They are internal to Components. We can move them to Shared if that's acceptable?

File: src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs [hunk 12]
```diff
@@ -52,6 +53,24 @@ public static IServiceCollection AddCascadingValue<TValue>(
...
+    /// <summary>
+    /// Adds a cascading value supplier to the <paramref name="serviceCollection"/>. This allows supplying cascading values based on custom attributes, which can be used to support multiple cascading values of the same type with different matching criteria.
+    /// </summary>
+    /// <typeparam name="TAttribute">The attribute type.</typeparam>
+    /// <param name="serviceCollection">The <see cref="IServiceCollection"/>.</param>
+    /// <param name="subscribeFactory">A callback that supplies a <see cref="CascadingParameterSubscription"/> that handles subscriptions for attribute.</param>
+    /// <returns>The <see cref="IServiceCollection"/>.</returns>
+    public static IServiceCollection TryAddCascadingValueSupplier<TAttribute>(
+        this IServiceCollection serviceCollection,
+        Func<IServiceProvider, Func<ComponentState, TAttribute, CascadingParameterInfo, CascadingParameterSubscription>> subscribeFactory)
```
Comment (oroztocil) [inline src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs:65]: This is a public API and a top-level `IServiceCollection` extension that uses `ComponentState` in its signature. While `ComponentState` is also public, it is in the `Rendering` namespace and is explicitly documented as being an internal implementation detail of `Renderer`. Is that intentional? (@javiercn)

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 13]
```diff
@@ -0,0 +1,165 @@
...
+        ComponentState componentState,
+        SupplyParameterFromTempDataAttribute attribute,
+        CascadingParameterInfo parameterInfo)
+    {
+        var tempDataKey = attribute.Name ?? parameterInfo.PropertyName;
+        var componentType = componentState.Component.GetType();
+        var propertyInfo = componentType.GetProperty(
+            parameterInfo.PropertyName,
+            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
+        var getter = new PropertyGetter(componentType, propertyInfo!);
```
Comment (oroztocil) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs:39]: How often is `CreateSubscription` called and how expensive are these property getters? Could/should they be cached per `(componentType, propertyName)`?

File: src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs [hunk 14]
```diff
@@ -0,0 +1,165 @@
...
+    internal CascadingParameterSubscription CreateSubscription(
+        ComponentState componentState,
+        SupplyParameterFromTempDataAttribute attribute,
+        CascadingParameterInfo parameterInfo)
+    {
+        var tempDataKey = attribute.Name ?? parameterInfo.PropertyName;
+        var componentType = componentState.Component.GetType();
+        var propertyInfo = componentType.GetProperty(
+            parameterInfo.PropertyName,
+            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
```
Comment (javiercn) [inline src/Components/Endpoints/src/TempData/TempDataCascadingValueSupplier.cs]: This need to be cached (similar to how we do [ComponentProperties](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Reflection/ComponentProperties.cs)).

We also have helpers for "finding" the properties we should reuse here.

Not blocking, but need to be addressed before RTM

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs (hunk 12 above)
Comment (javiercn) [reply src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs:65]: It's a trade-off between this and having to put TempData and all other similar concepts in Components. The main consumers for this are other libraries on the stack, and while I don't love it. The alternative of having to put the attribute on a core assembly and a bunch of the infrastructure there, is worse.

The key tension here is that hosts, lack the ability to define their own host specific cascading values that aren't top level (AddCascadingValue exists, but it's a single value (like we do for HttpContext))

We can review what we use componentstate for (we use it as a key) and consider doing something else (like wrapping it into a struct and call it something like StateKey) but I don't think we get much out of it.

Comment (javiercn) [reply src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs:65]: The tradeoff is what we do in persistent component state and what we would need to also do in SupplyParameterFromSession, so we will end up with N host specific method registrations in the core assembly. With this approach, the hosts can register them in their setups using this common method.

Comment (oroztocil) [reply src/Components/Components/src/CascadingValueServiceCollectionExtensions.cs:65]: Sounds reasonable. Thanks for the explanation 👍
