### PR TITLE
JS components extensibility for custom elements or other SPA-framework-specific plugins

### LINKED ISSUE #34743: CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime failure
## Failing Test(s)

- CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime

## Error Message

```text
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: block\r\nActual:   none\r\n          ↑ (pos 0)

```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.AssertGlobalErrorState(Boolean hasGlobalError) in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 193
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime() in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 87
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1259700&view=results

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This adds enough extensibility to the new JS components system that external packages can plug in support for working with other technologies. I have a work-in-progress implementation of a "custom elements" support package separately.

What this entails:

1. Ensuring that the core rendering behaviors are compatible with rendering into a shadow DOM. There's no rule that says custom elements have to have a shadow DOM, but we want to support that if people want to do it.
2. Enhancing the JS components feature to have a concept of an optional "JS initializer function" for each JS component. This is a JavaScript function (located using the same lookup that we use for JS interop) that:
    * Receives the `name` and `parameters` metadata for each associated JS component
    * Does whatever it wants to integrate that with another technology. For example, it could call `customElements.register(...)`, or it could configure a 3rd-party SPA framework to know about the Blazor component and render it via `Blazor.rootComponents.add(...)` etc.

Tests in progress.

### CODE REVIEW

File: src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Program.cs [hunk 1]
```diff
@@ -11,6 +11,7 @@
 using Microsoft.AspNetCore.Authorization;
 #endif
 using Microsoft.AspNetCore.Components;
+using Microsoft.AspNetCore.Components.Web;
```
Comment (SteveSandersonMS) [inline src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Program.cs:14]: This comes out of some previous API review decisions. We wanted the builder APIs for JS components to move into `Microsoft.AspNetCore.Components.Web`, and so we now need references to that namespace in the project templates. The WebAssembly one already has it, so it just needs to be added here.

**Comment by javiercn** [comment]
Looks great so far, is this missing tests?

**Comment by SteveSandersonMS** [comment]
Finishing the tests off now. (Mentioned in PR description above 😄 )

**Comment by SteveSandersonMS** [comment]
@javiercn OK, ready now! The E2E tests are all here now.

**Review by javiercn — APPROVED** [review]
Looks fantastic!

**Comment by BrennanConroy** [comment]
Needs API review?

**Comment by SteveSandersonMS** [comment]
@BrennanConroy Yes, good point. It’s a minor change from what we had before but yes.

File: src/Components/Web/src/JSComponents/JSComponentConfigurationExtensions.cs [hunk 2]
```diff
@@ -7,19 +7,55 @@
...
-            => configuration.JSComponents.Add(identifier, typeof(TComponent));
+            => RegisterForJavaScript(configuration, typeof(TComponent), identifier);
+
+        /// <summary>
+        /// Marks the specified component type as allowed for instantiation from JavaScript.
+        /// </summary>
+        /// <typeparam name="TComponent">The component type.</typeparam>
+        /// <param name="configuration">The <see cref="IJSComponentConfiguration"/>.</param>
+        /// <param name="identifier">A unique identifier for the component type that will be used by JavaScript code.</param>
+        /// <param name="javaScriptInitializer">Specifies an optional identifier for a JavaScript function that will be called to register the custom element.</param>
```
Comment (pranavkm) [inline src/Components/Web/src/JSComponents/JSComponentConfigurationExtensions.cs:36]: API review feedback: Remove the term `optional` from the docs since the parameter isn't really optional. Same for line  56
