### PR TITLE
Normalize the content root and improve errors

### LINKED ISSUE #36416: WebApplicationBuilder does not canonicalize the --contentRoot argument
### Describe the bug

If a custom content root is specified via the `--contentRoot` command-line argument to a application using WebApplicationBuilder, the user-provider path is not canonicalized before use.

```sh
> dotnet run -- --contentRoot=.\..\.
Building...
ContentRoot Path: C:\Coding\martincostello\MinimalApisRepros\bin\Debug\net6.0\.\..\.
```

Running without the argument produces the following:

```sh
> dotnet run
Building...
ContentRoot Path: C:\Coding\martincostello\MinimalApisRepros
Environment CurrentDirectory: C:\Coding\martincostello\MinimalApisRepros
```

In the above example I would expect the `ContentRootPath` value to be _either_ `C:\Coding\martincostello\MinimalApisRepros\bin\Debug` or `C:\Coding\martincostello`.

I'm not sure if the intended behaviour is to resolve relative to the current directory, or the assembly location. If the former then it's wrong and not canonicalized, if the latter then it's just not canonicalized.

### To Reproduce

Build and run the following application with the command `dotnet run -- --contentRoot=.\..\.`.

```csharp
var builder = WebApplication.CreateBuilder(args);
Console.WriteLine($"ContentRoot Path: {builder.Environment.ContentRootPath}");
Console.WriteLine($"Environment CurrentDirectory: {Environment.CurrentDirectory}");
```

### Further technical details

.NET SDK version `6.0.100-rc.1.21460.8`

### LINKED ISSUE #36876: Unhandled exception. System.NotSupportedException: The environment changed. Changing the host configuration is not supported
### Describe the bug

Changing development environment in Minimal API throw exception in `6.0.100-rc.1.21463.6`.

```
Unhandled exception. System.NotSupportedException: The environment changed. Changing the host configuration is not supported
   at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureHostConfiguration(Action`1 configureDelegate)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseEnvironment(IHostBuilder hostBuilder, String environment)
   at Program.<Main>$(String[] args) in C:\GitHub\practical-aspnetcore\projects\net6\web-application-builder-3\src\Program.cs:line 8
```

### To Reproduce

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using System;

WebApplicationBuilder builder = WebApplication.CreateBuilder();
builder.Host.UseEnvironment(Environments.Development);

var app = builder.Build();
app.Run(async context =>
{
    await context.Response.WriteAsync(@"hello world");
});

app.Run();
```

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by davidfowl**
## Description

Today users can call methods on the `IHostBuilder` or `IWebHostBuilder` to change various hosting settings and the new `WebApplicationBuilder` will detect settings that can't be changed and throw an exception. This affects a number of scenarios that used to work but it's made worse because the comparison of some of those settings are directories are done without canonicalization. On top of that, it the exception message isn't clear on what action to take, nor does it provide show what values have changed. 

- When trying to compare content root paths, make sure the paths are normalized before doing so. Today we throw too aggressively when libraries try to set the content root, even if that would have resulted in a no-op. This change normalizes the initial path and the attempted path before doing the comparison.
- We also improve the error message when the user tries to change the host settings, directing them to the correct API to use instead.

## Customer Impact

A couple of customers have complained but one of the mainline scenarios, hosting ASP.NET Core in a windows service, is currently broken on .NET 6. There are several workarounds, but the cleanest one doesn't involve code changes but not canonicalizing the directories makes it harder to use.

## Regression?
- [x] Yes
- [ ] No

## Risk
- [ ] High
- [ ] Medium
- [x] Low

## Verification
- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A

Fixes #36876
Fixes #36416
Improves #36979

### CODE REVIEW

File: src/DefaultBuilder/src/ContentRootHelpers.cs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace Microsoft.AspNetCore
+{
+    internal class ContentRootHelpers
```
Comment (pranavkm) [inline src/DefaultBuilder/src/ContentRootHelpers.cs:6]: ContentRootResolver or something like that? Helpers is a bad name. Also static

**Comment by davidfowl** [comment]
cc @Pilchie

**Review by pranavkm — APPROVED** [review]

File: src/DefaultBuilder/src/ContentRootHelpers.cs (hunk 1 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/ContentRootHelpers.cs:6]: Or Utils 😉 . Thanks @rynowak

**Comment by davidfowl** [comment]
@pranavkm what would you expect:

`MyApp  --contentRoot .`  to do? It tries to use . as the folder name and considers it different from the folder itself. That does seem like an issue right?

**Review by halter73 — APPROVED** [review]

**Comment by davidfowl** [comment]
Getting a failure on linux only:

```
System.NotSupportedException : The content root changed from "/var/folders/0g/62hgl73n3lz39zqvf6rwm1wr0000gy/T/ea697ec3-93ed-4239-80bb-a200a9948ab2/" to "/var/folders/0g/62hgl73n3lz39zqvf6rwm1wr0000gy/T/ea697ec3-93ed-4239-80bb-a200a9948ab2/". Changing the host configuration using WebApplicationBuilder.Host is not supported. Use WebApplication.CreateBuilder(WebApplicationOptions) instead.
```

**Comment by davidfowl** [comment]
I found the issue, looks like a test issue.

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 2]
```diff
@@ -300,6 +300,54 @@ public void WebApplicationBuilderWebHostSettingsThatAffectTheHostCannotBeModifie
...
+            Directory.CreateDirectory(contentRoot);
+
+            try
+            {
+                var builder = WebApplication.CreateBuilder(new WebApplicationOptions
+                {
+                    ContentRootPath = contentRoot
+                });
+
+                builder.Host.UseContentRoot(contentRoot + "\\");
```
Comment (davidfowl) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:316]:
```suggestion
                builder.Host.UseContentRoot(contentRoot + Path.DirectorySeparatorChar);
```

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 3]
```diff
@@ -300,6 +300,54 @@ public void WebApplicationBuilderWebHostSettingsThatAffectTheHostCannotBeModifie
...
+                builder.Host.UseContentRoot(contentRoot.ToUpperInvariant());
+                builder.Host.UseContentRoot(contentRoot.ToLowerInvariant());
+
+                builder.WebHost.UseContentRoot(contentRoot + "\\");
```
Comment (davidfowl) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:320]:
```suggestion
                builder.WebHost.UseContentRoot(contentRoot + Path.DirectorySeparatorChar);
```

**Review by captainsafia — APPROVED** [review]

**Comment by davidfowl** [comment]
This is approved.

cc @dotnet/aspnet-build

**Comment by dougbu** [comment]
Changed `Servicing-consider` to `Servicing-approved` based on email
