### PR TITLE
[Form data mapping] Support for mapping URIs from form data

### LINKED ISSUE #51072: Form post failed to bind to Uri property in Blazor web app
When I try to post a form and bind to a model with a `Uri` property it fails to bind. This is a pretty common scenario - I hit this when working on the BestForYouRecipes demo app.

### PR DESCRIPTION
**Pull request by javiercn**
Adds a special case to handle URIs when maping form data from the request.

## Description

We don't special case URI for deserializing form data to objects on the server and URI values are treated as a complex type instead of primitive type and when the system tries to deserialize them it can't.

Fixes #51072

## Customer Impact

If a model is a URI or a type that contains a URI property, the request will fail to deserialize the form data into an object.

## Regression?

- [ ] Yes
- [X] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [X] Low

URIs don't implement `IParsable<Uri>` and need to be handled specifically in the form mapping pipeline.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Components/Endpoints/src/FormMapping/Converters/UriFormDataConverter.cs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+    [RequiresDynamicCode(FormMappingHelpers.RequiresDynamicCodeMessage)]
+    [RequiresUnreferencedCode(FormMappingHelpers.RequiresUnreferencedCodeMessage)]
+    internal override bool TryRead(ref FormDataReader context, Type type, FormDataMapperOptions options, out Uri? result, out bool found)
+    {
+        found = context.TryGetValue(out var value);
+        if (!found)
+        {
+            result = default;
+            return true;
```
Comment (SteveSandersonMS) [inline src/Components/Endpoints/src/FormMapping/Converters/UriFormDataConverter.cs:38]: Returning `true` in this case is surprising and seems like the opposite of what the `TryXXX` pattern normally does, but as long as you're following the pattern correctly for `FormDataConverter<T>` then I guess it's correct.

**Review by SteveSandersonMS — APPROVED** [review]
