### PR TITLE
[Blazor] Fix WebView renderer not correctly dispatching browser events

### LINKED ISSUE #16609: [regression/8.0.100-preview.7.23376.3] .NET Maui Blazor App throws "No interop methods are registered for renderer" javascript exception
### Description

When creating a new .NET Maui Blazor App in `8.0.100-preview.7.23376.3` and running it results in the following javascript exception when navigating or clicking on the counter button.

Open the dev tools to see the exception:

```
blazor.webview.js:1  Uncaught Error: No interop methods are registered for renderer 0
    at k (blazor.webview.js:1:13290)
    at blazor.webview.js:1:13196
    at T (blazor.webview.js:1:13379)
    at N (blazor.webview.js:1:13170)
    at x.dispatchGlobalEventToAllElements (blazor.webview.js:1:15755)
    at x.onGlobalEvent (blazor.webview.js:1:14948)
```

### Steps to Reproduce

1. Create a new .NET Maui Blazor App and target .NET 8 preview (`8.0.100-preview.7.23376.3`)
2. Run the app on e.g. `Windows Machine`
3. Open the dev tools
4. Navigate through the menu and you notice the exception
5. But its easiest to see on the `Counter` page and clicking the `Click Me` button

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.100-preview.7.23376.3

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows, and others

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```
blazor.webview.js:1  Uncaught Error: No interop methods are registered for renderer 0
    at k (blazor.webview.js:1:13290)
    at blazor.webview.js:1:13196
    at T (blazor.webview.js:1:13379)
    at N (blazor.webview.js:1:13170)
    at x.dispatchGlobalEventToAllElements (blazor.webview.js:1:15755)
    at x.onGlobalEvent (blazor.webview.js:1:14948)
```

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Fix WebView renderer not correctly dispatching browser events

Fixes an issue where Blazor Hybrid throws an exception when a browser event gets emitted. This results in console errors upon user interaction.

Fixes dotnet/maui/issues/16609

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]
LGTM! Have we verified there aren't regressions in other APIs that fallback to RenderId=0?

**Comment by MackinnonBuck** [comment]
@captainsafia Hopefully, all cases that fallback to a renderer ID of 0 have been eliminated. I've scanned the source for remaining cases, but it looks like they should all be addressed now. The root of the problem was that for one method, `rendererId` was optional when it should have been required. Had it been required, the TypeScript compiler would have caught the bug earlier.

**Review by Eilon — APPROVED** [review]
I literally watched you make the fix, so I approve 😁

File: src/Components/Web.JS/src/Rendering/Renderer.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function attachRootComponentToLogicalElement(browserRendererId: number, l
   browserRenderer.attachRootComponentToLogicalElement(componentId, logicalElement, appendContent);
 }
 
-export function attachRootComponentToElement(elementSelector: string, componentId: number, browserRendererId?: number): void {
+export function attachRootComponentToElement(elementSelector: string, componentId: number, browserRendererId: number): void {
```
Comment (campersau) [inline src/Components/Web.JS/src/Rendering/Renderer.ts:27]: Since browserRenderId is now required could the fallback to 0 in line 47 be removed?
`browserRendererId || 0`

Comment (MackinnonBuck) [reply src/Components/Web.JS/src/Rendering/Renderer.ts:27]: Yeah, it could be. I can remove it the next time I touch this area, but feel free to open a PR if you feel inclined :)
