### PR TITLE
`HttpNavigationManager` no longer uses `NavigationException`

### LINKED ISSUE #59451: Reconcile NavigationManager behavior to no longer use NavigationException
The behavior NavigationManager exhibits is different in SSR rendering than it is on other interactive modes. In particular, SSR relies on throwing an exception that gets captured by the framework to convert the error into a redirect.

This behavior leads to a poor user experience where users debugging their apps typically see the debugger break when this exception is thrown and incorrectly believe that there is an error/bug on the framework.

In addition to this, code that exists after a call to `NavigateTo` will continue to execute on interactive render modes but will abruptly stop in SSR scenarios.

The solution for this involves a breaking change, but the number of issues that the current behavior produces justifies such change. We should stop throwing an exception during SSR and instead signal the underlying renderer that a redirection has been requested. We should continue to execute the current ongoing synchronous render batch until completion and, once it finishes, we should dispose the existing renderer and trigger the redirect. This will align the behavior with what happens in other platforms, but we should also have a suite of tests that capture these behaviors across render modes to ensure a consistent experience.

For backcompat reasons we will include an AppContext switch that will continue to throw the exception in case someone needs it.

### PR DESCRIPTION
**Pull request by ilonatommy**
## Description

- Guard throwing `NavigationException` with `AppContext` switch. Naming updates are welcome.
- Keep `catch`es it in the places where they are, without `AppContext`.
- Add an event listener that triggers `httpContext` redirection.
- Test for no interactivity SSR (`HttpNavigationManager`) and interactivity SSR (`RemoteNavigationManager`) scenarios.
- Removal of "routing/not-found-ssr" etc, they don't exist and should not be on `Routing test cases` page.
- Fix stopping render mechanism: base class should know about the stop signal, otherwise it will keep editing the render queue during the batch processing, effectively ignoring the stop signal.

Fixes #59451

### CODE REVIEW

File: src/Components/Components/src/NavigationManager.cs [hunk 1]
```diff
@@ -61,6 +61,18 @@ public event EventHandler<NotFoundEventArgs> OnNotFound
...
+    /// <summary>
+    /// Gets a value indicating whether navigation exceptions should be thrown during navigation.
+    /// </summary>
+    /// <remarks>
+    /// This property is controlled by the AppContext switch
+    /// <c>Microsoft.AspNetCore.Components.Endpoints.HttpNavigationManager.EnableThrowNavigationException</c>.
+    /// When enabled, navigation operations may throw exceptions for debugging or testing purposes.
+    /// </remarks>
+    protected static bool ThrowNavigationException =>
+        AppContext.TryGetSwitch(EnableThrowNavigationException, out var switchValue) && switchValue;
```
Comment (javiercn) [inline src/Components/Components/src/NavigationManager.cs:75]: This should not go in `NavigationManager`

Comment (javiercn) [reply src/Components/Components/src/NavigationManager.cs:75]: I imagine you are putting it here because you want to "reuse" it. However, in this case its better to just duplicate the code in each of the individual classes

File: src/Components/Endpoints/test/RazorComponentResultTest.cs [hunk 2]
```diff
@@ -510,6 +510,14 @@ class FakeDataProtector : IDataProtector
...
     class FakeNavigationManager : NavigationManager, IHostEnvironmentNavigationManager
     {
+        private EventHandler<NavigationEventArgs> _onNavigateTo;
+
+        public event EventHandler<NavigationEventArgs> OnNavigateTo
+        {
+            add => _onNavigateTo += value;
+            remove => _onNavigateTo -= value;
+        }
+
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/Endpoints/test/RazorComponentResultTest.cs:520]: It might. `location` param can be used as `uri` and invoking the location changed event on interactive scenarios should not conflict with each other. It's worth trying

File: src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.cs [hunk 3]
```diff
@@ -135,6 +139,11 @@ internal async Task InitializeStandardComponentServicesAsync(
         }
     }
 
+    private void OnNavigateTo(object? sender, NavigationEventArgs args)
+    {
+        _httpContext.Response.Redirect(args.Uri);
+    }
```
Comment (javiercn) [inline src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.cs:145]: I'm not sure this is enough. We need to do something like what we do in the NotFound case, where we stop further renders, as they are not going to be used.

Also, in the case the response has started (streaming rendering), we can't start a redirect this way

Comment (ilonatommy) [reply src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.cs]: We can't do the same as in `NotFound` either, that would result in an infinite loop.
1) Allow managing flow by exception only for this case to break the infinite loop. Minus: one edge case will still annoy developers.
2) Inject a refresh `meta http-equiv`  refresh tag into the response. Minus: cannot be cancelled, is implemented on browser level -> the implementation might differ from http redirection.

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/SSRRedirectionStreaming.razor [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+<p id="test-info">Click submit to navigate to home</p>
+<form method="post" @onsubmit="Submit" @formname="MyUniqueFormName">
+    <AntiforgeryToken />
+    <button type="submit" id="redirectButton" class="btn btn-primary">Redirect</button>
+</form>
+
+@code {
+    private async Task Submit()
+    {
+        await Task.Delay(1000); // Simulate some async work to let the streaming begin
```
Comment (javiercn) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/SSRRedirectionStreaming.razor:15]:
```suggestion
        await Task.Yield();
```

Whenever we introduce delays like this we slow down the entire test suite and these delays compound over our big collections. There are two ways to handle this:
* Use `Task.Yield()` if you are not checking any intermediate content.
* Otherwise, use a TaskCompletionSource and use a separate Http request to the server to complete it (using http client from the test, there are some tests that do this)

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/RoutingTestCases.razor [hunk 5]
```diff
@@ -24,12 +24,6 @@
         <a href="routing/complex-segment(value)">Complex segments</a>
     </li>
     <li>
-        <a href="routing/not-found-ssr">Not found page for Static Server Rendering</a>
-    </li>
-    <li>
-        <a href="routing/not-found-webassembly">Not found page for Interactive WebAssembly rendering</a>
-    </li>
-    <li>
-        <a href="routing/not-found-server">Not found page for Interactive Server rendering</a>
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/RoutingTestCases.razor:33]: Yes, this paths do not exist (not under `routing`), I forgot to clean it up after the previous PR moved these tests to `WasmMinimal`.

File: src/Components/Server/src/Circuits/RemoteNavigationManager.cs [hunk 6]
```diff
@@ -88,7 +91,21 @@ protected override void NavigateToCore(string uri, NavigationOptions options)
...
+            }
+            else
+            {
+                if (!IsInternalUri(absoluteUriString))
+                {
+                    // it's an external navigation, avoid Uri validation exception
+                    BaseUri = GetBaseUriFromAbsoluteUri(absoluteUriString);
+                }
+                Uri = absoluteUriString;
+                NotifyLocationChanged(isInterceptedLink: false);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/Server/src/Circuits/RemoteNavigationManager.cs:106]: Yes, `Uri` setter in Nav manager has 
https://github.com/dotnet/aspnetcore/blob/335de67d0b94805e96ae70c5b93bafd49f5e9efe/src/Components/Components/src/NavigationManager.cs#L105

**Comment by ilonatommy** [comment]
`Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.PrerenderingTest.CanRedirectDuringPrerendering` failures are connected with the fact that we are not stopping the renderer effectively:
if the stopping occurred in prerendering, it will be valid for prerendering only and in the main rendering, `_rendererIsStopped` will already be false. We have to find an effective way to communicate the pause between the calls of `BeginRenderingComponent`.

**Comment by ilonatommy** [comment]
Using the "waiting" queue is not an answer - it blocks rendering because most of the render items is added when `_isBatchInProgress=true`. A better solution is to implement a mechanism that will prevent from adding new items to the queue after we signaled the stop of rendering.
Changes: 
In the previous version, we could not trigger a new queue processing if the signal was sent but we were able to edit the ongoing processing.
In the new version, we cannot edit the queue if the signal was sent but we have to edit the Renderer API to add the method that will signal the stop in the base class.

File: src/Components/Components/src/RenderTree/Renderer.cs [hunk 7]
```diff
@@ -658,6 +659,12 @@ internal void AddToRenderQueue(int componentId, RenderFragment renderFragment)
     {
         Dispatcher.AssertAccess();
 
+        if (_rendererIsStopped)
+        {
+            // Once we're stopped, we'll disregard further attempts to queue anything
+            return;
+        }
+
```
Comment (javiercn) [inline src/Components/Components/src/RenderTree/Renderer.cs:667]: I think we should do this inside `https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs#L736` which can be overriden by `EndpointHtmlRenderer` and save ourselves having the public API `SignalRendererToFinishRendering`

Comment (ilonatommy) [reply src/Components/Components/src/RenderTree/Renderer.cs:667]: if we do as you propose, the queue will keep being edited during the processing (line 676 below). That was why I added a new public API, to prevent new Enqueue() when we already sent the `stop` signal.

**Review by javiercn — APPROVED** [review]
Looks great, I have some minor feedback about the public API, but let's not block on it for preview 4.

I think we also want to capture some concrete behaviors as part of the Renderer tests to make sure we don't regress them in the future, but we don't have to wait on that for this to go in.

Thanks for persevering through this change!
