### PR TITLE
macOS dev-certs - Handle keychain paths with spaces

### LINKED ISSUE #42887: error while saving the HTTPS developer certificate (M1 Mac)- security: SecKeychainItemImport: Unknown format in import.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting an error when running the command:  dotnet dev-certs https  on my M1 Mac.

dotnet dev-certs https -v
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from LocalMachine\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[8] Filtered certificates: no certificates
[9] Excluded certificates: no certificates
[0] Event 16 was called with 1 argument(s), but it is defined with 0 parameter(s).
[16] 
[17] Generating HTTPS development certificate.
[18] Finished generating HTTPS development certificate.
[20] Saving certificate '800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE - CN=localhost - Valid from 2022-07-24 17:34:51Z to 2023-07-24 17:34:51Z - IsHttpsDevelopmentCertificate: true - IsExportable: true' to store CurrentUser\My.
[54] Importing the certificate 800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE - CN=localhost - Valid from 2022-07-24 17:34:51Z to 2023-07-24 17:34:51Z - IsHttpsDevelopmentCertificate: true - IsExportable: true to the keychain '/Volumes/Crucial 2TB/martinsteer/Library/Keychains/login.keychain-db'.
[56] An error has occurred while importing the certificate to the keychain: 1.
[22] An error has occurred saving the certificate: System.InvalidOperationException: There was an error importing the certificate into the user key chain '800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE'.

security: SecKeychainItemImport: Unknown format in import.

   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.SaveCertificateCore(X509Certificate2 certificate, StoreName storeName, StoreLocation storeLocation)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.SaveCertificate(X509Certificate2 certificate)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).

### Expected Behavior

Expected the certificate to be created.

### Steps To Reproduce

1. Install .Net 6 on macOS Monterey 12.4, Apple M1
2. run command, dotnet dev-certs https -v

### Exceptions (if any)

As shown in the bug description

### .NET Version

6.0.302

### Anything else?

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix https://github.com/dotnet/aspnetcore/issues/42887

As seen in the linked issue, users may have their macOS home directory set to a non-standard path which could include spaces. We should include quotes around the paths when running the `security` commands so that they get parsed properly.

I know this is a very uncommon setup, but I'm still surprised this is the first case we've heard of this :smile:.

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Review by HaoK — APPROVED** [review]

File: src/Shared/CertificateGeneration/MacOSCertificateManager.cs [hunk 1]
```diff
@@ -29,18 +31,18 @@ internal sealed class MacOSCertificateManager : CertificateManager
...
     // Note: This operation will require user authentication.
     private const string MacOSTrustCertificateCommandLine = "security";
-    private static readonly string MacOSTrustCertificateCommandLineArguments = $"add-trusted-cert -p basic -p ssl -k {MacOSUserKeychain} ";
+    private static readonly string MacOSTrustCertificateCommandLineArguments = $"add-trusted-cert -p basic -p ssl -k \"{MacOSUserKeychain}\" ";
 
     // Import a pkcs12 certificate into the user keychain using the unwrapping passphrase {1}, and
     // allow any application to access the imported key without warning.
     private const string MacOSAddCertificateToKeyChainCommandLine = "security";
-    private static readonly string MacOSAddCertificateToKeyChainCommandLineArgumentsFormat = "import {0} -k " + MacOSUserKeychain + " -t cert -f pkcs12 -P {1} -A";
+    private static readonly string MacOSAddCertificateToKeyChainCommandLineArgumentsFormat = "import {0} -k \"" + MacOSUserKeychain + "\" -t cert -f pkcs12 -P {1} -A";
```
Comment (halter73) [inline src/Shared/CertificateGeneration/MacOSCertificateManager.cs:45]: `{0}` is a path too, just a temporary file, right? Is it possible for the tmp dir to ever have a space? It feels better to quote all paths as a general rule.

Comment (adityamandaleeka) [reply src/Shared/CertificateGeneration/MacOSCertificateManager.cs:45]: Under the hood, `$TMPDIR` is used to get the temp path, which macOS sets up in `/private/var` with a symlink in `/var/folders/...`. This should hold regardless of where the `$HOME` is.

But I guess in theory someone could redefine `$TMPDIR` so I'll go ahead and guard that path too.

**Review by halter73 — APPROVED** [review]
