### PR TITLE
Fix a write past the end of buffer in IntegerEncoder

### LINKED ISSUE #10913: HPACK multi-byte integer encoding writes past end of buffer
The HPACK integer encoder will write past the end of a too-short buffer when encoding an integer into multiple bytes, on line 47 below:

https://github.com/aspnet/AspNetCore/blob/9cd2ad15ff2a306bab9894dc7c1926c196b3fa2e/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/IntegerEncoder.cs#L36-L47

### PR DESCRIPTION
**Pull request by scalablecory**
Resolves #10913

Fixes a write past end of buffer when an integer requires multiple bytes to encode, and the buffer does not have enough space. Adds a test to confirm this.
Add some basic asserts to constrain parameters to HPACK spec.
Add some additional tests.

### CODE REVIEW

**Comment by scalablecory** [comment]
CI failures are in unrelated code.

File: src/Servers/Kestrel/Core/test/HPackIntegerTests.cs [hunk 1]
```diff
@@ -35,5 +37,55 @@ public void IntegerEncoderDecoderRoundtrips()
                 }
             }
         }
+
+        [Theory]
+        [MemberData(nameof(IntegerCodecSamples))]
+        public void EncodeSamples(int value, int bits, byte[] expectedResult)
+        {
+            Span<byte> actualResult = new byte[64];
```
Comment (jkotalik) [inline src/Servers/Kestrel/Core/test/HPackIntegerTests.cs]: nit: I think this and `DecodeSamples` are a bit redundant with IntegerEncoderDecoderRoundtrips. I believe the combinations you listed would eventually be tested. the only difference is that you are verifying the expectedResult.

**Review by jkotalik — APPROVED** [review]

**Comment by jkotalik** [comment]
Thanks!
