### PR TITLE
Fix Kestrel psuedo header reuse

### LINKED ISSUE #38581: Pseudo header string reuse broken in .NET 6
Pseudo headers were filtered out of HTTP/2 and HTTP/3 requests with this PR - https://github.com/dotnet/aspnetcore/pull/36166

Unfortunately, the way they are filtered out - setting the header properties to default removes the bits AND the value - means string reuse no longer happens for those headers. e.g. `:authority = localhost:80` allocates `localhost:80` for every request.

I think the better way to filter these headers is to add a special method that clears their bits. We do something similar for some response headers: https://github.com/dotnet/aspnetcore/blob/13a460820e90c8f3e90eb4fdbbb3de671389bf0c/src/Servers/Kestrel/shared/KnownHeaders.cs#L1165-L1168

@Tratcher @halter73 @wtgodbe

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/38581

### CODE REVIEW

**Comment by JamesNK** [comment]
FYI @adityamandaleeka

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestHeaders.cs [hunk 1]
```diff
@@ -59,11 +60,14 @@ protected override void ClearFast()
         else
         {
             // If we are reusing headers, store the currently set headers for comparison later
-            _previousBits = _bits;
+            // Psuedo header bits were cleared at the start of a request to hide from the user.
+            // Keep those values for reuse.
+            _previousBits = _bits | _psuedoBits;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestHeaders.cs:65]: Not including some the pseudo headers in `_bits` means that their values don't get cleared when `!ReuseHeaderValues`. It looks like we currently have a similar issue with `ClearInvalidH2H3Headers()`, but at least those are response headers that should never be proxied, so that's only a problem for buggy apps.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestHeaders.cs:65]: Does this fix what you mentioned?

```diff
if (!ReuseHeaderValues)
{
    // If we aren't reusing headers clear them all
-   Clear(_bits);
+   Clear(_bits | _psudeoBits);
}
```

**Comment by sebastienros** [comment]
Is `psuedo` a thing or did you mean `pseudo` ?

**Review by Tratcher — APPROVED** [review]

File: src/Servers/Kestrel/Core/test/HttpRequestHeadersTests.cs [hunk 2]
```diff
@@ -112,6 +113,23 @@ public void EntriesCanBeEnumeratedAfterResets()
...
+        const BindingFlags privateFlags = BindingFlags.NonPublic | BindingFlags.Instance;
+
+        HttpRequestHeaders headers = new HttpRequestHeaders(reuseHeaderValues: false);
+        headers.HeaderMethod = "GET";
+        headers.ClearPseudoRequestHeaders();
+        headers.Reset();
+
+        // Hacky but required because header references is private.
+        var headerReferences = typeof(HttpRequestHeaders).GetField("_headers", privateFlags).GetValue(headers);
+        var methodValue = (StringValues)headerReferences.GetType().GetField("_Method").GetValue(headerReferences);
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/test/HttpRequestHeadersTests.cs:128]: @halter73 @Tratcher yolo?

The alternative is change the `HttpRequestHeaders.HeaderReferences` struct from private to internal and adding a method to get it on `HttpRequestHeaders`.

Comment (Tratcher) [reply src/Servers/Kestrel/Core/test/HttpRequestHeadersTests.cs:128]: *shrug* I don't care about reflection in a test.
