### PR TITLE
[7.0] Close connections on client cert failures 

### LINKED ISSUE #41369: Kestrel's GetClientCertificateAsync caches failures
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/bf03cee1625eb74939b28ea6b79b4a994b926421/src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs#L120

The client cert negotiation task is cached because the operation is normally only valid once per connection. However, a few failures are recoverable and request processing can continue, but GetClientCertificateAsync will continue to report the cached error on subsequent requests.

Challenge: Kestrel can't tell which errors are recoverable.

Workaround: The application can call HttpContext.Connection.RequestClose() if GetClientCertificateAsync fails. This will cause a graceful closure of the connection after the current request and avoid the negative caching.

### Expected Behavior

Since we can't know which errors are recoverable, if GetClientCertificateAsync fails then mark the connection as !keepalive to avoid negative caching. This will also skip expensive draining logic for POST requests.

Are there any exceptions thrown from GetClientCertificateAsync where we shouldn't close the connection?

### Steps To Reproduce

One way to reproduce this is to POST data without `Expect: 100-continue` and call GetClientCertificateAsync before reading the request body. If data is already available in the SslStream buffers then it fails immediately with the exception below. If you then read the request body processing can continue to the next request but GetClientCertificateAsync continues to throw the old exception.

### Exceptions (if any)

System.InvalidOperationException: Client stream needs to be drained before renegotiation.
   at System.Net.Security.SslStream.RenegotiateAsync[TIOAdapter](TIOAdapter adapter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.TlsConnectionFeature.GetClientCertificateAsyncCore(CancellationToken cancellationToken)

### .NET Version

6.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Tratcher**
Mark the connection for closure if an error occurs while requesting the client certificate.

## Description

Requesting a client certificate after an HTTP request has arrived requires renegotiating the TLS session. Kestrel caches the result for the lifetime of the connection because the operation shouldn't be performed more than once. Renegotiation requires that the TCP connection be clear of request data. If a client cert is requested for a POST request with a large body it will fail because there is still request data in the pipe. However, that failure is recoverable if the data gets drained later, but subsequent requests could be stuck with the cached error.

Because Kestrel doesn't know which errors are recoverable, it should treat all renegotiation errors as non-recoverable by gracefully closing the connection.

I was also able to clean up some adjacent tests for issues that had already been fixed elsewhere.

Fixes #41369

## Customer Impact

This came from an internal partner. It required significant investigation to understand why requests on a given connection were failing. They are able to work around it in 6.0 using the same RequestClose API, but asked us to make this the default behavior to avoid such investigations in the future.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This matches the workaround being used.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs [hunk 1]
```diff
@@ -122,7 +129,19 @@ public int KeyExchangeStrength
...
+        try
+        {
+            await _sslStream.NegotiateClientCertificateAsync(cancellationToken);
+        }
+        catch (Exception)
+        {
+            // We can't tell which exceptions are fatal or recoverable. Consider them all fatal
+            // and close the connection to avoid over-caching. This allows recovery by starting
+            // a new connection https://github.com/dotnet/aspnetcore/issues/41369
+            _context.Features.Get<IConnectionLifetimeNotificationFeature>()?.RequestClose();
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:141]: Why graceful?

Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:141]: The app is still able to send a HTTP response for the current request in most cases. The issue the customer hit was the next request being affected by the cached error.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:141]: Should add that as a comment.

File: src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs [hunk 2]
```diff
@@ -122,7 +129,19 @@ public int KeyExchangeStrength
 
     private async Task<X509Certificate2?> GetClientCertificateAsyncCore(CancellationToken cancellationToken)
     {
-        await _sslStream.NegotiateClientCertificateAsync(cancellationToken);
+        try
+        {
+            await _sslStream.NegotiateClientCertificateAsync(cancellationToken);
+        }
+        catch (Exception)
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:136]: nit
```suggestion
        catch
```

File: src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs [hunk 3]
```diff
@@ -122,7 +129,20 @@ public int KeyExchangeStrength
...
+        {
+            await _sslStream.NegotiateClientCertificateAsync(cancellationToken);
+        }
+        catch
+        {
+            // We can't tell which exceptions are fatal or recoverable. Consider them all fatal
+            // and close the connection to avoid over-caching and affecting future requests on this connection.
+            // This allows recovery by starting a new connection. The close is graceful to allow the server to
+            // send an error response like 401. https://github.com/dotnet/aspnetcore/issues/41369
+            _context.Features.Get<IConnectionLifetimeNotificationFeature>()?.RequestClose();
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:142]: Nit: It's not really fatal if you can still write a response. We should log something if IConnectionLifetimeNotificationFeature is somehow missing.

```suggestion
            // We can't tell which exceptions are fatal or recoverable. Consider them all recoverable only given a new connection
            // and close the connection gracefully to avoid over-caching and affecting future requests on this connection.
            // This allows recovery by starting a new connection. The close is graceful to allow the server to
            // send an error response like 401. https://github.com/dotnet/aspnetcore/issues/41369
            _context.Features.Get<IConnectionLifetimeNotificationFeature>()?.RequestClose();
```

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs (hunk 3 above)
Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs:142]: > We should log something if IConnectionLifetimeNotificationFeature is somehow missing.

That seems unlikely outside of tests? Maybe custom transports?

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2 assuming CI passes.

**Comment by Tratcher** [comment]
@dotnet/aspnet-admins please merge.

**Comment by dougbu** [comment]
@brunolins16 not sure what's going on but I've seen a few `Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit` failures in release/6.0 and release/7.0 in the components-e2e pipeline. It happened again for this PR.
