### PR TITLE
Fix issues with hosting startups

### LINKED ISSUE #35956: In-app IHostingStartup instances are not discovered/run when --applicationName is passed via args to WebApplication.CreateBuilder, e.g. from test projects
Using build:
```
SDK 6.0.100-rc.1.21427.28
Host 6.0.0-rc.1.21426.17
Microsoft.AspNetCore.App 6.0.0-rc.1.21427.16
Microsoft.NETCore.App 6.0.0-rc.1.21426.17
```

1. Create an empty web project, e.g. `dotnet new web`
2. Add an `IHostingStartup` class to the project and register it via the assembly attribute:
  ``` c#
  [assembly:HostingStartup(typeof(MyHostingStartup))]
  namespace MyTestWebApp;
  public class MyHostingStartup : IHostingStartup
  {
      public void Configure(IWebHostBuilder builder)
      {
          var test = "Test string";
      }
  }
  ```
3. Debug the web project and ensure that `MyHostingStartup.Configure` is called
4. Add an xUnit test project to the solution, e.g. `dotnet new xunit`
5. Add a reference to the web project to the test project, e.g. `dotnet add reference Path/MyTestProject.csproj`
6. Set internals visible to in the web project so the test project can see internal types, e.g. in the MyTestWebApp.csproj file:
  ``` xml
  <ItemGroup>
    <InternalsVisibleTo Include="MyTestWebApp.Tests" />
  </ItemGroup>
  ```
7. Add a test that uses `WebApplicationFactory` to send a request to the web project, e.g.:
  ``` c#
  using System.Net;
  using Microsoft.AspNetCore.Mvc.Testing;
  using Microsoft.Extensions.DependencyInjection;
  using Microsoft.Extensions.Hosting;
  using Xunit;
  
  namespace MyTestWebApp.Tests
  {
      public class HostingStartupTest
      {
          [Fact]
          public async Task Root_Responds_OK()
          {
              await using var application = new MyWebApplication();
              
              var client = application.CreateClient();
              var response = await client.GetAsync("/");
  
              Assert.Equal(HttpStatusCode.OK, response.StatusCode);
          }
  
          class MyWebApplication : WebApplicationFactory<Program>
          {
              protected override IHost CreateHost(IHostBuilder builder)
              {
                  // Add mock/test services to the builder here
  
                  return base.CreateHost(builder);
              }
          }
      }
  }
  ```
8. Debug the test and see that the `MyHostingStartup.Configure` method is not called

### PR DESCRIPTION
**Pull request by davidfowl**
- When the WebApplications's application name is specified we need to set the it on the internal web host builder so that hosting startups can see the new name. This allows the logic to find hosting startups in the specified application name instead of the entry assembly. When running inside of test projects, the entry assembly is always the test host, that's why it showed it when running tests.
- Added tests

Fixes #35956

### CODE REVIEW

File: src/DefaultBuilder/src/WebApplicationOptions.cs [hunk 1]
```diff
@@ -64,5 +64,38 @@ internal void ApplyHostConfiguration(IConfigurationBuilder builder)
...
         }
+
+        internal void ApplyApplicationName(IWebHostBuilder webHostBuilder)
+        {
+            string? applicationName = null;
+
+            if (ApplicationName is not null)
+            {
+                applicationName = ApplicationName;
+            }
```
Comment (BrennanConroy) [inline src/DefaultBuilder/src/WebApplicationOptions.cs:75]: nit:
```suggestion
            var applicationName = ApplicationName;
```

File: src/DefaultBuilder/src/WebApplicationOptions.cs [hunk 2]
```diff
@@ -64,5 +64,38 @@ internal void ApplyHostConfiguration(IConfigurationBuilder builder)
...
+
+            // We need to "parse" the args here since
+            // we need to set the application name via UseSetting
+            if (Args is not null)
+            {
+                var config = new ConfigurationBuilder()
+                        .AddCommandLine(Args)
+                        .Build();
+
+                applicationName = config[WebHostDefaults.ApplicationKey];
```
Comment (BrennanConroy) [inline src/DefaultBuilder/src/WebApplicationOptions.cs:85]: Should this null check before setting?

File: src/DefaultBuilder/src/WebApplicationOptions.cs [hunk 3]
```diff
@@ -64,5 +64,38 @@ internal void ApplyHostConfiguration(IConfigurationBuilder builder)
...
+            string? applicationName = null;
+
+            if (ApplicationName is not null)
+            {
+                applicationName = ApplicationName;
+            }
+
+            // We need to "parse" the args here since
+            // we need to set the application name via UseSetting
+            if (Args is not null)
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationOptions.cs:79]: Why does `Args["applicationName"]` override `ApplicationName`?

File: src/DefaultBuilder/src/WebApplicationOptions.cs (hunk 2 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:85]: No, args overrides the property.

File: src/DefaultBuilder/src/WebApplicationOptions.cs (hunk 3 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:79]: I thought we had args win over the property. I'll swap it back.

Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:79]: 👍 We already try applying explicit options after args [here](https://github.com/dotnet/aspnetcore/blob/1fc592c683c97411b7e6ff6116370d6106f0c330/src/DefaultBuilder/src/WebApplicationBuilder.cs#L77-L78).

File: src/DefaultBuilder/src/WebApplicationOptions.cs (hunk 2 above)
Comment (BrennanConroy) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:85]: If args doesn't have ApplicationKey wont it return null?

Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:80]: The order is now fixed so this doesn't matter now 😄

File: src/DefaultBuilder/src/WebApplicationOptions.cs (hunk 3 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:74]: Fixed.

File: src/DefaultBuilder/src/WebApplicationOptions.cs [hunk 4]
```diff
@@ -64,5 +64,39 @@ internal void ApplyHostConfiguration(IConfigurationBuilder builder)
...
+            if (ApplicationName is not null)
+            {
+                applicationName = ApplicationName;
+            }
+
+            if (applicationName is not null)
+            {
+                webHostBuilder.UseSetting(WebHostDefaults.ApplicationKey, applicationName);
+            }
+        }
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationOptions.cs:100]: Nit: You don't have build config if ApplicationName is not null. And I think it'd be cleaner to move the `Assembly.GetEntryAssembly()?.GetName()?.Name` fallback into this method so you see the whole picture.

```suggestion
        internal void ApplyApplicationName(IWebHostBuilder webHostBuilder)
        {
            // ApplicationName overrides everything else
            string? applicationName = ApplicationName;

            // Fall back to args if ApplicationName wasn't specified
            if (applicationName is null && Args is not null)
            {
                var config = new ConfigurationBuilder()
                        .AddCommandLine(Args)
                        .Build();

                applicationName = config[WebHostDefaults.ApplicationKey];

                // This isn't super important since we're not adding any disposable sources
                // but just in case
                (config as IDisposable)?.Dispose();
            }

            // Lastly fall back to the entry Assembly name.
            applicationName ??= Assembly.GetEntryAssembly()?.GetName()?.Name ?? string.Empty;

            webHostBuilder.UseSetting(WebHostDefaults.ApplicationKey, applicationName);
        }
```

**Review by halter73 — APPROVED** [review]

File: src/DefaultBuilder/src/WebApplicationOptions.cs (hunk 4 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:100]: I didn't try/test this. If you take it we should remove the call to `webHostBuilder.UseSetting(WebHostDefaults.ApplicationKey, ...)` in WebApplicationBuilder of course.

Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationOptions.cs:100]: This has args overriding the application name. I like the change overall though.
