### PR TITLE
Use navigator.userAgentData in Javascript Mono Debugger 

### LINKED ISSUE #37128: Blazor Exception - navigator.userAgent and CSS
### Describe the bug
I get an exception and I'm not able to figure out the cause, I suspect CSS:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
blazor.server.js:1

### To Reproduce

Minimum repo can be found at https://valstekt.com/assets/public_docs/shop/myshop.zip

### Further technical details
- Microsoft.AspNetCore.App 5 for developing a Blazor Server-side web app

### PR DESCRIPTION
**Pull request by rogihee**
Use the new navigator.userAgentData in favor of window.chrome / navigator.platform / navigator.userAgent. Avoids an warning a user gets in the Issues tab when using the Mono Debugger (see picture). Added a fallback for Edge/Chrome 80-90 using the previous code.

image

## Description
As can be seen in the screenshot, starting with Chrome 101 the amount of information will be reduced in the User Agent string. We are at 99 so maybe it's time to do something about it :-). 

Implementation notes:
- Add a minimal Typescript definition for the userAgentData as the PR for the DOM definition has not been merged yet.
- Note that the "brands" array was only added in Chrome 84, so the code has extra check if this array exists before falling back. 
- Fallbacks could be removed but that would basically be dropping support for Chrome < 90.
- The `platform` value differs from navigator or userAgentData, e.g. 'Win32' vs 'Windows'. For macOS the case insensitive match should cover both cases, but its good to keep in mind. 

Some resources used:
- https://caniuse.com/?search=userAgentData
- https://wicg.github.io/ua-client-hints/
- https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1028/
- https://medium.com/naver-fe-platform/prepare-for-client-hints-freezing-user-agent-9c0ea1ddd02c

Fixes #37128

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @rogihee.
@SteveSandersonMS can you please review this? Thanks!

File: src/Components/Web.JS/src/Platform/Mono/MonoDebugger.ts [hunk 1]
```diff
@@ -3,23 +3,27 @@
...
 import { WebAssemblyResourceLoader } from '../WebAssemblyResourceLoader';
 
+const navigatorUA = navigator as MonoNavigatorUserAgent;
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
-const currentBrowserIsChrome = (window as any).chrome
-  && navigator.userAgent.indexOf('Edge') < 0; // Edge pretends to be Chrome
+const currentBrowserIsChromeOrEdge = navigatorUA.userAgentData && navigatorUA.userAgentData.brands ?
+     (navigatorUA.userAgentData.brands.some(b => b.brand === 'Google Chrome') ||
+      navigatorUA.userAgentData.brands.some(b => b.brand === 'Microsoft Edge'))
+      : (window as any).chrome && navigator.userAgent.indexOf('Edge') < 0; // Edge pretends to be Chrome
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Platform/Mono/MonoDebugger.ts:11]: Just a suggestion to make it more readable:

```suggestion
const brands = navigatorUA.userAgentData && navigatorUA.userAgentData.brands;
const currentBrowserIsChromeOrEdge = brands
  ? brands .some(b => b.brand === 'Google Chrome' || b.brand === 'Microsoft Edge')
  : (window as any).chrome;
```

I'm not sure we should still be concerned with `navigator.userAgent.indexOf('Edge')` because modern Edge doesn't include the string `Edge` in its useragent (it has `Edg` instead to avoid these checks). And very old versions of Edge aren't really a concern any more for development time.

Comment (rogihee) [reply src/Components/Web.JS/src/Platform/Mono/MonoDebugger.ts]: Thanks Steve for the review, I have addressed your feedback accordingly (I hope).

**Review by SteveSandersonMS — APPROVED** [review]
Great, thanks!
