### PR TITLE
[Blazor] More auth fixes

### LINKED ISSUE #19053: [Blazor][Wasm] Investigate alternatives to loading the blazor app when inside a hidden iframe

### LINKED ISSUE #20492: WASM 3.2 pre 3 template - When deleting an account user stays logged in until browser refresh
### Describe the bug
When deleting your account using the latest preview of Blazor Wasm (Hosted with Individual auth) after redirect you are still showing as logged in. After a browser refresh you are correctly showing as logged out.

### To Reproduce

dotnet new blazorwasm -au Individual --hosted

Register > Confirm > Login > Play Around > Click username > Click Personal Data > Click Delete Data

You are returned to app but the header bar still shows your user name as being logged in.

### Further technical details

Template version Blazor 3.2 preview 3
SDK 3.1.201

### PR DESCRIPTION
**Pull request by javiercn**
Follow up from https://github.com/dotnet/aspnetcore/issues/19966
 
Being able to customize the user during the authentication process as well as to control the flow of the authentication once the core authentication flow has a great importance when building applications using remote authentication protocols. It enables developers to:
* Enrich the user claims with data outside of the scope of the identity provider.
  * To add additional claims that might drive the UI.
  * To define roles for the user that are outside of those of the IdP.
* Collect additional information specific to the application that might be required for it to work.
* Prevent the authenticated user from accessing parts of the UI he's not allowed to.
  * (This is just an optimization of the UX, security must always be done server-side)

### Goals/Decission drivers
* We want the authentication decissions to be centralized in one place within the UI, as this makes it easier to enforce the full authentication flow.
* We want the process of customizing the authenticated user simple, ideally it is done in one place.
* We want to separate the process of generating the authenticated user from the process of making authorization decissions.

### Candidate solutions
* Do nothing and tell developers to override `GetUserAsync` on RemoteAuthenticationService.
* Include a callback in RemoteAuthenticatorViewCore to customize the user.
* Include a callback in RemoteAuthenticationOptions to customize the user.
* Define a new abstraction for generating the final authenticated user.

## Define a new abstraction for generating the final authenticated user
I decided to implement a new abstraction to make it easier to customize the user being authenticated. This abstraction, `UserFactory<RemoteUserAccount>` handles mapping the user from the definition that the `RemoteAuthenticationService` provides into the `ClaimsPrincipal` that it is later on, used by the application.

### Trade-offs

Adding a new primitive for mapping the user offers a single place where the mapping process can take place and allows developers to use normal extensibility mechanisms like dependency injection and so on in order to provision any service that they need to use to produce the final user. 

It allows developers to focus on the mapping process without interfering with how or when the user is updated, which is a complicated process and can be handled by the framework.

It offers developers a natural place to implement caching strategies and other optimizations that might be required to implement the mapping process efficiently.

It introduces a new concept that users must understand, although this is not necessary until the user needs to be customized, given that a reasonable default implementation is provided.

It makes it complicated to inject some dependencies that make use of the `IAccessTokenProvider` since it is part of the `RemoteAuthenticationService` and injecting it would produce a cyclical dependency. This is mitigated in the default implementation by offering the IAccessTokenProvider as a property, which is supplied through an `IAccessTokenProviderAccessor` that delays the resolution until the property is first accessed. This makes sure that any custom implementation is encouraged to offer a suitable construction for dependency injection.

Finally, this option completely separates the mapping of the user from any other mechanic relate to the authentication process and enables decissions about the authentication flow to be taken at a later stage based on claims defined in the user, which gives developers the option to make those flows context sensitive.

### Do nothing and tell developers to override `GetUserAsync` on RemoteAuthenticationService
In this option we would ask the users to override and customize RemoteAuthenticationService to produce the actual user and register their implementation in the dependency injection container.

#### Trade-offs
This option is cheap in terms of cost (free) but it offers a poor user experience and sets customers up for failure. The main reasons for this are:
* It is not easy to wire-up a RemoteAuthenticationService into the DI container as the same instance needs to be shared in different contexts. (AuthenticationStateProvider, IAccessTokenProvider, etc.).
* It forces users to re-implement all the caching logic that the RemoteAuthenticationService offers to cache the user, limiting the amount of JS interop calls that happen to check the user status.
* It establishes a tight contract between the RemoteAuthenticationService and the underlying AuthenticationService, which at the moment is just an implementation detail of the RemoteAuthenticationService.

### Include a callback in RemoteAuthenticatorViewCore to customize the user
In this option we would define an event callback inside `RemoteAuthenticatorViewCore` that gets called when the user is authenticated. 
#### Trade-offs
It would allow developers to write code in their Authentication.razor page that can access DI services in a way they are used to.

The main drawbacks for this approach are that `RemoteAuthenticatorViewCore` already handles many concerns and tacking an additional one to it just increases the complexity and makes it harder for users to understand it.

It forces that callback to be passed down through all the layers down to the RemoteAuthenticationService.

It can't be made to work as the mapping must be able to produce users even when a RemoteAuthenticatorViewCore is not part of the page. 

### Include a callback in RemoteAuthenticationOptions to customize the user
In this option we would include a callback in RemoteAuthenticationOptions that developers can set to customize the user.

#### Trade-offs

It is the best option for simple cases, since it makes it trivial to perform easy modifications. However, when more complex scenarios present themselves it sets up users for failure since it doesn't compose well, doesn't have a mechanism to resolve dependencies nor to hold on to other state for caching purposes and so on.

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 1]
```diff
@@ -63,12 +63,32 @@ export interface AuthorizeService {
...
     constructor(userManager: UserManager) {
         this._userManager = userManager;
     }
 
+    async trySilentSignIn() {
+        if (!this._intialSilentSignIn) {
+            this._intialSilentSignIn = (async () => {
+                try {
+                    await this._userManager.signinSilent();
+                    return;
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:76]: Do you need this?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 2]
```diff
@@ -63,12 +63,32 @@ export interface AuthorizeService {
...
+        }
+
+        return this._intialSilentSignIn;
+    }
+
     async getUser() {
+        if (window.parent == window && !window.opener && !window.frameElement &&
+            !location.href.startsWith(this._userManager.settings.redirect_uri!)) {
+            // If we are not inside a hidden iframe, try authenticating silently.
+            await AuthenticationService.instance.trySilentSignIn();
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:89]: What are the consequences of doing this unconditionally?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 3]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
     public static async init(settings: UserManagerSettings & AuthorizeServiceSettings) {
         // Multiple initializations can start concurrently and we want to avoid that.
         // In order to do so, we create an initialization promise and the first call to init
         // tries to initialize the app and sets up a promise other calls can await on.
         if (!AuthenticationService._initialized) {
-            this._initialized = (async () => {
-                const userManager = await this.createUserManager(settings);
+            AuthenticationService._initialized = AuthenticationService.InitializeCore(settings);
+
+            await AuthenticationService._initialized;
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:287]: Couldn't the calling code await this? Why does it need to be awaited as part of initialization?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 4]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
+    static _pendingOperations: { [key: string]: Promise<AuthenticationResult> | undefined } = {}
 
     public static async init(settings: UserManagerSettings & AuthorizeServiceSettings) {
         // Multiple initializations can start concurrently and we want to avoid that.
         // In order to do so, we create an initialization promise and the first call to init
         // tries to initialize the app and sets up a promise other calls can await on.
         if (!AuthenticationService._initialized) {
-            this._initialized = (async () => {
-                const userManager = await this.createUserManager(settings);
+            AuthenticationService._initialized = AuthenticationService.InitializeCore(settings);
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:285]: Isn't caching this incorrect if `settings` is different between two calls?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 5]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
+    }
+
+    private static async InitializeCore(settings?: UserManagerSettings & AuthorizeServiceSettings) {
+        let finalSettings = settings || AuthenticationService.resolveCachedSettings();
+        if (!settings && finalSettings) {
+            const userManager = AuthenticationService.createUserManagerCore(finalSettings);
+
+            if (window.parent != window && !window.opener && (window.frameElement &&
+                location.href.startsWith(userManager.settings.redirect_uri!))) {
+                // If we are inside a hidden iframe, try completing the sign in early.
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:304]: Need some explanation as to why this is important.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 6]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
                 AuthenticationService.instance = new OidcAuthorizeService(userManager);
-            })();
+                AuthenticationService._initialized = (async (): Promise<void> => {
+                    await AuthenticationService.instance.completeSignIn(location.href);
+                    return;
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:308]: ?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs [hunk 7]
```diff
@@ -0,0 +1,18 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+using Microsoft.Extensions.DependencyInjection;
+
+namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication.Internal
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs:7]: 👎

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 8]
```diff
@@ -42,6 +42,11 @@ public class RemoteAuthenticationService<TRemoteAuthenticationState, TProviderOp
         /// </summary>
         protected readonly NavigationManager _navigation;
 
+        /// <summary>
+        /// The <see cref="UserFactory{TAccount}"/> to map accounts to <see cref="ClaimsPrincipal"/>.
+        /// </summary>
+        protected readonly UserFactory<TAccount> _userFactory;
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:48]: Should this be a property? It's really odd to see underscores in the ref API

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 9]
```diff
@@ -74,7 +81,9 @@ public class RemoteAuthenticationService<TRemoteAuthenticationState, TProviderOp
             var result = internalResult.Convert();
             if (result.Status == RemoteAuthenticationStatus.Success)
             {
-                UpdateUser(GetUser());
+                var getUserTask = GetUser();
+                await getUserTask;
+                UpdateUser(getUserTask);
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:86]: This seems problematic. `GetUser` returns a `ValueTask<T>` which appears to be [awaited multiple times](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask-1?view=netcore-3.1#remarks)

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs [hunk 10]
```diff
@@ -0,0 +1,59 @@
...
+            options.RoleClaim) : new ClaimsIdentity();
+
+            if (account != null)
+            {
+                foreach (var kvp in account.AdditionalProperties)
+                {
+                    var name = kvp.Key;
+                    var value = kvp.Value;
+                    if (value != null ||
+                        (value is JsonElement element && element.ValueKind != JsonValueKind.Undefined && element.ValueKind != JsonValueKind.Null))
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs:49]: `if (value.TryGetString(out var stringValue)` if `value is JsonElement`

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+            RemoteAuthenticationUserOptions options)
+        {
+            var identity = account != null ? new ClaimsIdentity(
+            options.AuthenticationType,
+            options.NameClaim,
+            options.RoleClaim) : new ClaimsIdentity();
+
+            if (account != null)
+            {
+                foreach (var kvp in account.AdditionalProperties)
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs:44]: You could make `AdditionalProperties : IDictionary<string, JsonElement>`. No reason it's `object`

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj [hunk 12]
```diff
@@ -21,4 +21,8 @@
     <ProjectReference Include="..\Wasm.Authentication.Shared\Wasm.Authentication.Shared.csproj" />
   </ItemGroup>
 
+  <ItemGroup>
+    <Folder Include="Data\Migrations\" />
```
Comment (pranavkm) [inline src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj:25]: Need this?

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/StateService.cs [hunk 13]
```diff
@@ -0,0 +1,16 @@
...
+using System.Linq;
+using System.Threading.Tasks;
+
+namespace Wasm.Authentication.Client
+{
+    public class StateService
+    {
+        private string _state;
+
+        public string GetCurrentState() => _state != null ? _state : (_state = Guid.NewGuid().ToString());
```
Comment (rynowak) [inline src/Components/WebAssembly/testassets/Wasm.Authentication.Client/StateService.cs:12]: `GetCurrrentState() => (_state ??= Guid.NewGuid().ToString())` 😆

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs [hunk 14]
```diff
@@ -0,0 +1,23 @@
...
+    /// <remarks>
+    /// The information in this type will be use to produce a <see cref="System.Security.Claims.ClaimsPrincipal"/> for the application.
+    /// </remarks>
+    public class RemoteUserAccount
+    {
+        /// <summary>
+        /// Gets or sets properties not explicitly mapped about the user.
+        /// </summary>
+        [JsonExtensionData]
+        public IDictionary<string, object> AdditionalProperties { get; set; }
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs:21]: Is there a reason we couldn't deserialize a `IDictionary<string, string>` instead? Usually `JsonExtensionData` is useful if you have other properties on the type that you want to deserialize.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs [hunk 15]
```diff
@@ -0,0 +1,20 @@
...
+    /// It may be changed or removed without notice in any release.
+    /// </summary>
+    public interface IAccessTokenProviderAccessor
+    {
+        /// <summary>
+        /// This is an internal API that supports the Microsoft.AspNetCore.Components.WebAssembly.Authentication
+        /// infrastructure and not subject to the same compatibility standards as public APIs.
+        /// It may be changed or removed without notice in any release.
+        /// </summary>
+        IAccessTokenProvider TokenProvider { get; }
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs:18]: I'm not really certain what this is used for. I can only spot where it's used in tests.

What am I missing? Or is this really only for unit testing?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs [hunk 16]
```diff
@@ -0,0 +1,19 @@
...
+using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
+
+namespace Microsoft.Extensions.DependencyInjection
+{
+    /// <summary>
+    /// An interface for configuring remote authentication services.
+    /// </summary>
+    /// <typeparam name="TRemoteAuthenticationState">The remote authentication state type.</typeparam>
+    /// <typeparam name="TAccount">The account type.</typeparam>
+    public interface IRemoteAuthenticationBuilder<TRemoteAuthenticationState, TAccount>
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs:13]: What's the purpose of these generic type parameters? They don't seem to be used anywhere inside the interface. Could they be removed?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 17]
```diff
@@ -63,12 +63,32 @@ export interface AuthorizeService {
...
     }
 
+    async trySilentSignIn() {
+        if (!this._intialSilentSignIn) {
+            this._intialSilentSignIn = (async () => {
+                try {
+                    await this._userManager.signinSilent();
+                    return;
+                } catch (e) {
+                }
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:78]: Should we be logging something here maybe? I'm not sure under what circumatances we'd have an exception, but maybe this could make debugging harder.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:287]: Agreed. It seems like this line has no effect and could be removed.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 18]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
+        }
+
+        return AuthenticationService._initialized;
+    }
+
+    public static handleCallback() {
+        return AuthenticationService.InitializeCore();
+    }
+
+    private static async InitializeCore(settings?: UserManagerSettings & AuthorizeServiceSettings) {
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:297]:
```suggestion
    private static async initializeCore(settings?: UserManagerSettings & AuthorizeServiceSettings) {
```

(plus related updates)

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 19]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
+        let finalSettings = settings || AuthenticationService.resolveCachedSettings();
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:298]:
```suggestion
        const finalSettings = settings || AuthenticationService.resolveCachedSettings();
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 20]
```diff
@@ -253,21 +273,61 @@ class OidcAuthorizeService implements AuthorizeService {
...
 
-        await this._initialized;
+    private static resolveCachedSettings(): UserManagerSettings | undefined {
+        let finalSettings: UserManagerSettings | undefined;
+        const cachedSettings = window.sessionStorage.getItem(`${AuthenticationService._infrastructureKey}.CachedAuthSettings`);
+        if (cachedSettings) {
+            finalSettings = JSON.parse(cachedSettings);
+        }
+
+        return finalSettings;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:330]: This logic seems weird. It looks like it reduces to something like the following. Could you check it?

```suggestion
        const cachedSettings = window.sessionStorage.getItem(`${AuthenticationService._infrastructureKey}.CachedAuthSettings`);
        return cachedSettings ? JSON.parse(cachedSettings) : undefined;
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 21]
```diff
@@ -282,16 +342,30 @@ export class AuthenticationService {
...
     }
 
-    public static completeSignIn(url: string) {
-        return AuthenticationService.instance.completeSignIn(url);
+    public static async completeSignIn(url: string) {
+        let operation = this._pendingOperations[url];
+        if (!operation) {
+            operation = AuthenticationService.instance.completeSignIn(url);
+            await operation;
+            this._pendingOperations[url] = undefined;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:350]:
```suggestion
            delete this._pendingOperations[url];
```

Not certain if this is what you want, but it would be leaking memory otherwise. I know it's hard to imagine someone do this so many times that would cause a problem.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 22]
```diff
@@ -282,16 +342,30 @@ export class AuthenticationService {
...
     }
 
-    public static completeSignOut(url: string) {
-        return AuthenticationService.instance.completeSignOut(url);
+    public static async completeSignOut(url: string) {
+        let operation = this._pendingOperations[url];
+        if (!operation) {
+            operation = AuthenticationService.instance.completeSignOut(url);
+            await operation;
+            this._pendingOperations[url] = undefined;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:365]:
```suggestion
            delete this._pendingOperations[url];
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs (hunk 14 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs:21]: I think the expected usage pattern is that people subclass `RemoteUserAccount` to define their own properties that should get deserialized and for which they have particular logic.

Then, the remaining properties get hoovered up by the framework into `AdditionalProperties` (though I don't know what the framework does with them).

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs [hunk 23]
```diff
@@ -0,0 +1,17 @@
...
+{
+    internal class RemoteAuthenticationBuilder<TRemoteAuthenticationState, TAccount>
+        : IRemoteAuthenticationBuilder<TRemoteAuthenticationState, TAccount>
+        where TRemoteAuthenticationState : RemoteAuthenticationState
+        where TAccount : RemoteUserAccount
+    {
+        public RemoteAuthenticationBuilder(IServiceCollection services) => Services = services;
+
+        public IServiceCollection Services { get; }
+    }
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs:16]: Do we need to have the `IRemoteAuthenticationBuilder` interface? This seems like an unopinionated enough concrete type that we could make it `public` and not have the interface. Is there any reason why a different top-level implementation of the interface would ever exist?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs [hunk 24]
```diff
@@ -0,0 +1,55 @@
...
+    {
+        /// <summary>
+        /// Replaces the existing <see cref="UserFactory{TAccount}"/> with the user factory defined by <typeparamref name="TUserFactory"/>.
+        /// </summary>
+        /// <typeparam name="TRemoteAuthenticationState">The remote authentication state.</typeparam>
+        /// <typeparam name="TAccount">The account type.</typeparam>
+        /// <typeparam name="TUserFactory">The new user factory type.</typeparam>
+        /// <param name="builder">The <see cref="IRemoteAuthenticationBuilder{TRemoteAuthenticationState, TAccount}"/>.</param>
+        /// <returns>The <see cref="IRemoteAuthenticationBuilder{TRemoteAuthenticationState, TAccount}"/>.</returns>
+        public static IRemoteAuthenticationBuilder<TRemoteAuthenticationState, TAccount> AddUserFactory<TRemoteAuthenticationState, TAccount, TUserFactory>(
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs:22]: Should this be called `SetUserFactory`?

It appears that you can only have one, so `Add` is misleading.

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs:22]: Same for the other overloads below of course.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs [hunk 25]
```diff
@@ -0,0 +1,18 @@
...
+{
+    internal class AccessTokenProviderAccessor : IAccessTokenProviderAccessor
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs:9]: As with the comment about `IAccessTokenProviderAccessor`, I haven't spotted what this is used for. If you could clarify what consumes this feature that would be great.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 8 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:48]: Looks like it should be `private`. I don't see any subclasses consuming it (and if they did, then it should definitely be a property).

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 9 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:86]: Well spotted

File: src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs [hunk 26]
```diff
@@ -412,9 +466,16 @@ private void EnsureDatabaseCreated(IServiceProvider services)
...
-            Browser.FindElement(By.LinkText("Home")).Click();
+            try
+            {
+                // Make the tests run faster by navigating back to the home page when we are done
+                // If we don't, then the next test will reload the whole page before it starts
+                Browser.FindElement(By.LinkText("Home")).Click();
+            }
+            catch
+            {
+                // We don't care if this step fails.
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:477]: How or why could that step fail?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs [hunk 27]
```diff
@@ -0,0 +1,20 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication.Internal
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs:4]: This discussion came up with @SteveSandersonMS on the initial PR. We use .Internal in other places on Blazor. I'm just keeping consistency with what we've done in Blazor.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs:18]: This is to solve a cyclical dependency in the design. The AuthenticationService is the one handling all the communication with JavaScript to retrieve tokens from the underlying JS layer as well as handling the auth flows and updating the user. 

I wanted to separate the piece where the user is mapped from the results of the interop call to the ClaimsPrincipal (which is the user factory). As a result, the AuthenticationService has a dependency on the UserFactory, which gets injected.

That in turn, prevents users from injecting an `IAccessTokenProvider` in their implementation since that creates a cyclical dependency. After thinking about it, I decided that the best way to support this scenario (which I think it is important) and to avoid doing something more complicated or not as intuitive was to solve the problem in the base class.

The idea is that UserFactory injects the IAccessTokenProviderAccessor and that it exposes the ITokenProvider as a property that gets computed lazily. That has two main effects:
* Users creating a custom factory don't have to figure out the details as they are forced to provide a suitable constructor when extending the class.
* User's don't run into a weird DI error when they try to inject an IAccessTokenProvider instance themselves, since they don't have the need because the base class already offers it for convenience.

The accessor breaks the cyclical dependency and remains a small implementation detail.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs (hunk 16 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs:13]: We need to flow the generic parameters so that we can guarantee that extension methods that build on top remain type-safe, so for example if you customize the UserFactory to use a custom CustomUserFactory<CustomAccount> you can't call `AddUserFactory<CustomUserFactory<CustomAccount>>` on a `services.AddOidc(options => {...} )` call that is configured to use the base account type.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 2 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:89]: The underlying auth implementation uses a hidden iframe to perform multiple "silent" operations. We don't want to spam requests to the server in case the Blazor app gets loaded within a hidden iframe.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 4 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:285]: Not sure what you mean. The authentication service gets initialized only once when the app loads and the settings get reused only in scenarios where we are handling callbacks silently.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 5 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:304]: Added an explanatory comment

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs (hunk 14 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteUserAccount.cs:21]: Steve is right, the idea here is that we want to allow people to create their own account types to represent the information specific to their auth providers and have a strongly typed model, while at the same time we provide a basic experience that just shoves everything into a property bag.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs (hunk 23 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs:16]: This is consistent with the way it is done in ASP.NET Core, although to be fair, there are some differences between different areas of ASP.NET Core too. I followed the approach that MVC and other areas I'm familiar with follow (and we had a discussion at the beginning of asp.net core to homogenize this, which resulted in me doing some changes across the stack).

That said, if you feel strongly about it, I'm happy to just use a base class for this.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs (hunk 24 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs:22]: I followed the language Identity uses to keep consistency and they call these things 'AddUserManager` and so on. I might be nittpicking, but we haven't used `Set` ever in our APIs in this space. I'm just trying to be consistent with the previous art.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs (hunk 25 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs:9]: I answered [here](https://github.com/dotnet/aspnetcore/pull/20192/files#r402616175). The main goal is to make it easy to consume the `IAccessTokenProvider` from the UserFactory since that's a common thing and it's the lesser of evils.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs (hunk 7 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs:7]: Same comment as above.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:48]: Made all of them a Property. I don't want subclasses having to define their own backing storage, given that they are already forced to inject them on the constructor. As a result the best answer is to make them properties.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:86]: Thanks, I've changed this to be a Task.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs (hunk 11 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs:44]: I don't want the additional properties to be tied to JSON. The attribute is harmless, but putting the type in there coerces alternative implementations.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs (hunk 10 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs:49]: There is no TryGetString method in JsonElement.
image

File: src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs (hunk 26 above)
Comment (javiercn) [reply src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:477]: We don't need to do this anymore as we are using a different isolation context per test now, which ultimately results in a much better and stable experience. I've taken this out.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs (hunk 10 above)
Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/UserFactory.cs:49]: you're right. I was full of 💩

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 1 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: removed

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 3 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: removed

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 6 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:313]: Added an explanatory comment

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj (hunk 12 above)
Comment (javiercn) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj]: removed

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/StateService.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Client/StateService.cs]: updated

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 17 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:80]: I added a comment, but in essence the answer is that it can fail if the user is not logged in on the underlying IdP.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 18 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: done

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 19 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: done

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 20 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: done

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 22 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts]: done

File: src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs (hunk 26 above)
Comment (javiercn) [reply src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs]: removed

**Comment by javiercn** [comment]
🆙 📅

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs (hunk 15 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs:18]: Would it be reasonable then to make `IAccessTokenProvider` a regular `public` and supported API? It's a really simple interface. Is there any harm in supporting it?

I know we prefer not to make things public if unnecessary, but it seems like this does potentially show up in user code  ("they are forced to provide a suitable constructor when extending the class") so it's only fair to make it public.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs (hunk 16 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IRemoteAuthenticationBuilder.cs:13]: OK, understood. Thanks for clarifying!

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 17 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:80]: It's unfortunate that there's isn't a `trySigninSilent` to distinguish legit sign-in failures from system exceptions. But if this is beyond our control, no problem.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs (hunk 23 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilder.cs:16]: I don't feel strongly about it.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs (hunk 24 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticationBuilderExtensions.cs:22]: OK, it's not something I'm massively troubled by. It does seem a touch odd but then arguably people should understand that one one such factory can be in effect (it's meaningless to chain them), so the "add" terminology isn't going to throw anyone off track too far.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs (hunk 25 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccessTokenProviderAccessor.cs:9]: Understood now - thanks

**Review by SteveSandersonMS — APPROVED** [review]
Excellent!

File: src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/IAccessTokenProviderAccessor.cs:18]: I'm going to tackle this as a potential change in the post API review cleanups

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 17 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:80]: We can check the error message, but there is no point in it, since this is an optimistic optimization. It is not going to mask any error since if you have a system exception it will show up when you try to log in the regular way.
