### PR TITLE
Invalidate Cached WASM Auth Token on Authentication State Change

### LINKED ISSUE #35888: Blazor WASM AuthorizationMessageHandler caches AccessToken even after user has changed
### Describe the bug
The Blazor WASM `AuthorizationMessageHandler` stores the last AccessToken and will update it only if the AccessToken will expire in less than 5 minutes. If the user changes in between the old access token will still be used. Related code: 

https://github.com/dotnet/aspnetcore/blob/6e0fd83fea170d8efab8820cc5a318cfffa2847a/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs#L53
 
The `AuthorizationMessageHandler` should react to the `AuthenticationStateChanged` of the `AuthenticationStateProvider` and remove the last cached token.

### To Reproduce
Log in to a Blazor WASM application that uses the `AuthorizationMessageHandler` , log out and log in with another user. The access token from the first user will be used.

### Further technical details
- All Blazor WASM versions

### PR DESCRIPTION
**Pull request by TanayParikh**
Fixes: https://github.com/dotnet/aspnetcore/issues/35888

This _should_ work. I'm unable to validate it as for some reason the `AuthenticationStateChanged` event is never invoked (should be invoked on sign in/out). I'm assuming this is some issue with the debugger. I've validated that the event does in fact attach (line 44).

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs [hunk 1]
```diff
@@ -36,6 +37,12 @@ public class AuthorizationMessageHandler : DelegatingHandler
         {
             _provider = provider;
             _navigation = navigation;
+
+            // Invalidate the cached _lastToken when the authentication state changes
+            if (_provider is AuthenticationStateProvider authStateProvider)
+            {
+                authStateProvider.AuthenticationStateChanged += _ => { _lastToken = null; };
+            }
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs:45]: Looks great, however you need to implement IDisposable to unsubscribe from the event, otherwise this results in a memory leak over time.

Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs]: https://github.com/dotnet/aspnetcore/pull/36358/commits/8d9a5cc61834c658e3b4046fe14c4ac328c62ba3

Will require an API change though. If I can get an approval for the PR I'll look into getting API approval. Given the minor API change, I believe it shouldn't be an issue.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs [hunk 2]
```diff
@@ -36,6 +38,13 @@ public class AuthorizationMessageHandler : DelegatingHandler
         {
             _provider = provider;
             _navigation = navigation;
+
+            // Invalidate the cached _lastToken when the authentication state changes
+            if (_provider is AuthenticationStateProvider authStateProvider)
+            {
+                _authenticationStateChangedHandler = _ => { _lastToken = null; };
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs:45]: You could have done this without the field by creating a method and assigning the method group instead, for future reference. But I'm ok if you leave it as is.

**Review by javiercn — APPROVED** [review]

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs (hunk 1 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs]: Actually, we may be able to get around the public API by doing https://github.com/dotnet/aspnetcore/pull/36358/commits/e2351d3df4c1fb12eeeeaa1d3559f40392a1fc2d. Thoughts?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs [hunk 3]
```diff
@@ -16,10 +13,11 @@ namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication
     /// Access tokens will only be added when the request URI is within one of the base addresses configured using
     /// <see cref="ConfigureHandler(IEnumerable{string}, IEnumerable{string}, string)"/>.
     /// </summary>
-    public class AuthorizationMessageHandler : DelegatingHandler
+    public class AuthorizationMessageHandler : DelegatingHandler, IDisposable
```
Comment (campersau) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs:16]: [`HttpMessageHandler`](https://github.com/dotnet/runtime/blob/91f43669bbd6bdf1ba760a6eaa4e42c2794c5f08/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageHandler.cs#L12) from which [`DelegatingHandler`](https://github.com/dotnet/runtime/blob/91f43669bbd6bdf1ba760a6eaa4e42c2794c5f08/src/libraries/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L13) inherits already implements `IDisposable` so you could just override the existing [`protected virtual void Dispose(bool disposing)`](https://github.com/dotnet/runtime/blob/91f43669bbd6bdf1ba760a6eaa4e42c2794c5f08/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageHandler.cs#L31) method.

Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs:16]: That's what I'd originally done prior to https://github.com/dotnet/aspnetcore/pull/36358/commits/e2351d3df4c1fb12eeeeaa1d3559f40392a1fc2d. The issue with that approach is it requires adding a new public API, which at this stage of the release is a bit tougher.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs [hunk 4]
```diff
@@ -120,5 +125,15 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
...
         }
+
+
+        void IDisposable.Dispose()
+        {
+            if (_provider is AuthenticationStateProvider authStateProvider)
+            {
+                authStateProvider.AuthenticationStateChanged -= _authenticationStateChangedHandler;
+            }
+            Dispose(disposing: true);
```
Comment (TanayParikh) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs:136]: Defaulted this to true.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs (hunk 1 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AuthorizationMessageHandler.cs]: (Discussed offline, good to merge now)
