### PR TITLE
HttpSys request headers Keys and Count both allocate

### LINKED ISSUE #44627: HttpSys request headers Keys and Count both allocate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Offline report:

Found a strange allocation stack. Source code:
```
        public static bool TryExtractSingleValueHeader(
            IHeaderDictionary requestHeaders,
            string headerName,
            out string headerValue)
        {
            headerValue = string.Empty; 

            if (requestHeaders == null || requestHeaders.Keys.Count == 0)
            {
                return false;
            }

            var incomingHeaderValues = requestHeaders[headerName];

            // There may be multiple values, we will pick the first one.
            if (incomingHeaderValues.Count > 0)
            {
                headerValue = incomingHeaderValues[0];
                return true;
            }
            return false;
        }
```
So where is the LINQ expression? It’s here:
 
```
// Microsoft.AspNetCore.HttpSys.Internal.RequestHeaders
public ICollection<string> Keys
{
    get
    {
        return this.PropertiesKeys().Concat(this.Extra.Keys).ToArray<string>();
    }
}
```
 
For classes like Dictionary<K, V>, getting key collection is cheap because you because you just need to pay for a small key collection object once per dictionary (it will be reused forever). But this here has a super expensive implementation, so do not call it unless you’re willing and able to pay for it.

The strange thing is string allocation is the biggest here:

image

We do not need to get into the details why strings need to be allocated, because we can just remove the check.

It’s worse than that, the entire Extra headers collection is lazily loaded.
https://github.com/dotnet/aspnetcore/blob/14dc33c0a203b010ef0a8eb01a5f638199571728/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L33-L39

IDictionary.Count is also bad
https://github.com/dotnet/aspnetcore/blob/14dc33c0a203b010ef0a8eb01a5f638199571728/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L93-L96

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ladeak**
# HttpSys request headers Keys and Count both allocate

Currently Count and Keys allocate strings and arrays and enumerables. This change intends to reduce the cost of allocation.

## Description

RequestHeaders's Key and Count has a new implementation. Count is allocation free, while Keys allocate the string for the unknown header keys and a list for the results.
RequestHeader.Generated.cs has a new HeaderKeys returned as ReadOnlySpan<byte> for accessing the known keys - by avoiding allocation with enumerator or a static list.
RequestHeader.Generated.tt is updated, however it does not seem be set up to generate the RequestHeader.Generated.cs file.
NativeRequestContext provides new implementation to access the header keys and count.
Added tests to cover changes, it mocks a memory segment that is normally pinned and passed by IIS.

Considered caching the Keys (as the unknown header names are re-allocated every call). However, it could make sense to re-use the cached values in the Extra property getter too, but that would engage further refactoring.

**EDIT (2022.11.19):**

Note, that the RequestHeader.ResetFlags() method is used for the benchmakrs only. It does not clear cached values, just clears the flags indicating that a value is set.

## Performance Measurements

**EDIT (Updated 2022.11.19):**

Before:

```
// * Summary *

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.22621
12th Gen Intel Core i7-1255U, 1 CPU, 12 logical and 10 physical cores
.NET SDK=8.0.100-alpha.1.22531.1
  [Host]     : .NET 8.0.0 (8.0.22.55109), X64 RyuJIT
  DefaultJob : .NET 8.0.0 (8.0.22.52901), X64 RyuJIT

Server=True

|            Method |        Job |     Toolchain | RunStrategy |       Mean |    Error |   StdDev |        Op/s |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------ |----------- |-------------- |------------ |-----------:|---------:|---------:|------------:|-------:|-------:|------:|----------:|
| CountSingleHeader | DefaultJob |       Default |     Default |   460.3 ns |  2.58 ns |  2.42 ns | 2,172,472.5 | 0.0277 |      - |     - |     176 B |
| CountLargeHeaders | DefaultJob |       Default |     Default | 3,558.5 ns | 19.03 ns | 17.80 ns |   281,017.5 | 1.4381 | 0.0305 |     - |   9,032 B |
|  KeysSingleHeader | DefaultJob |       Default |     Default |   541.2 ns |  2.64 ns |  2.21 ns | 1,847,804.1 | 0.0544 |      - |     - |     344 B |
|  KeysLargeHeaders | DefaultJob |       Default |     Default | 3,859.1 ns | 22.89 ns | 20.29 ns |   259,128.9 | 1.5335 | 0.0763 |     - |   9,648 B |
```

After (see final results in the comments).

```
|            Method |        Job |     Toolchain | RunStrategy |       Mean |   Error |  StdDev |        Op/s |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------ |----------- |-------------- |------------ |-----------:|--------:|--------:|------------:|-------:|-------:|------:|----------:|
| CountSingleHeader | DefaultJob |       Default |     Default |   213.9 ns | 0.60 ns | 0.50 ns | 4,676,068.2 |      - |      - |     - |         - |
| CountLargeHeaders | DefaultJob |       Default |     Default |   213.3 ns | 0.51 ns | 0.43 ns | 4,689,144.1 |      - |      - |     - |         - |
|  KeysSingleHeader | DefaultJob |       Default |     Default |   427.7 ns | 2.71 ns | 2.53 ns | 2,338,190.7 | 0.0048 |      - |     - |      32 B |
|  KeysLargeHeaders | DefaultJob |       Default |     Default | 1,278.5 ns | 5.73 ns | 5.08 ns |   782,195.9 | 0.4425 | 0.0095 |     - |   2,776 B |
```

## Questions

Open question: should we consider re-implementing ContainsKey to gain performance benefits?
**EDIT (2022.11.19):** will keep it out of scope this PR.

Fixes #44627

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Could you include the microbenchmark in the PR? We like to keep those for future use 😃 
Put it in /HttpSys/perf/Microbenchmarks like https://github.com/dotnet/aspnetcore/tree/main/src/Servers/Kestrel/perf/Microbenchmarks

**Comment by Tratcher** [comment]
Please address the complication error.

> src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs(105,16): error CS0102: (NETCORE_ENGINEERING_TELEMETRY=Build) The type 'RequestHeaders' already contains a definition for 'Count'

**Comment by Tratcher** [comment]
> RequestHeader.Generated.tt is updated, however it does not seem be set up to generate the RequestHeader.Generated.cs file.

See https://github.com/dotnet/aspnetcore/pull/44860#issuecomment-1318233600

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs [hunk 1]
```diff
@@ -391,8 +506,8 @@ private void GetUnknownHeadersHelper(IDictionary<string, StringValues> unknownHe
                 }
                 pUnknownHeader++;
             }
+            }
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:509]: ? Formatting

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 2]
```diff
@@ -82,7 +79,17 @@ public bool ContainsKey(string key)
 
     public ICollection<string> Keys
     {
-        get { return PropertiesKeys().Concat(Extra.Keys).ToArray(); }
+        get
+        {
+            var destination = new string[Count];
+            Span<byte> observedKnownHeaders = stackalloc byte[HeaderKeys.Length];
+            int observedKnownHeadersCount = _requestMemoryBlob.GetKeys(HeaderKeys, observedKnownHeaders, destination);
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:86]: This doesn't account for the headers collection being modified like in https://github.com/dotnet/aspnetcore/pull/44860. A removed header will still be listed in keys, and an added header won't be. This might need to build on the logic being added for the other PR.

Count has the same issue.

Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:86]: Good point. I'll wait for that PR

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs (hunk 1 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:509]: That looks weird, I did not change this line and it looks ok in my editor. Double checking.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 2 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:86]: Only known headers are removable?

**Comment by ladeak** [comment]
I submitted the benchmarks. In my original benchmarks I actually reused a captured `NativeMemory` - which meant I had 3 KB byte array in the source. I updated these benchmarks to use the same method to create the native memory as the tests. The benchmark results are still the same magnitude
However, as pointed out header removal is not considered in my changes, that will invalidate the above benchmarks, and I will run (and attach their results) once the current implementation is fixed.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 2 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs]: This should be resolved now.

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 3]
```diff
@@ -209,5 +209,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+            (byte)<#=prop.ID#>,
+<# } #>
+        };
+
+        private string GetHeaderKeyName(HttpSysRequestHeader header) => header switch
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => HeaderNames.<#=prop.Name#>,
+<# } #>
+            _ => header.ToString()
```
Comment (ladeak) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:225]: I could not decide if throwing an exception or returning this string here is the better choice.

**Comment by ladeak** [comment]
@Tratcher and @BrennanConroy please review changes.

**Comment by Tratcher** [comment]
FYI: https://github.com/dotnet/aspnetcore/pull/45250

**Comment by Tratcher** [comment]
Have you rebased on https://github.com/dotnet/aspnetcore/pull/44860 yet? It has new infrastructure that might be helpful here. Also https://github.com/dotnet/aspnetcore/pull/45250.

**Comment by ladeak** [comment]
Yes, I have rebased, but eventually not used that infra. Although that simplified two of the tests (did not need to workaround removed header's)

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 4]
```diff
@@ -213,5 +213,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+        };
+
+        private bool IsOverridenKey(HttpSysRequestHeader header) => header switch
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:232]: IsRead

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 5]
```diff
@@ -213,5 +213,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => <#=IsRead(prop.Index)#>,
+<# } #>
+            _ => false,
+        };
+
+        private bool HasValue(HttpSysRequestHeader header) => header switch
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:240]: HasKnownHeader

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 6]
```diff
@@ -213,5 +213,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => _<#=prop.Name#> != StringValues.Empty,
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: You should move some of the other checks in here. E.g. 
https://github.com/dotnet/aspnetcore/blob/ceffcc9f6db99bab0c53785912411706988410db/src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt#L171-L172

Then PropertiesTryRemove could call this API too.

IsOverridenKey wouldn't be needed if that check was consolidated in here.

**Review by Tratcher — COMMENTED** [review]
You've got the right idea. I see a few places the code could be consolidated.

For your other questions:

> Below condition (screen shot 1) will only take care of performance until the value is read. If the value is read then there is a performance problem because  allocating a string(screenshot 2) just to check if it's there  . Please correct me if I am wrong?

Your second screenshot is not an allocation just for the check, that StringValues already has the allocated value, if any. IsRead only returns true if the allocation already happened.

> b)  Why _Connection.Count returns false and Connection.Count returns true (Underscore is the difference).  Because the Connection property returns _Connection.

_Connection is the field for storing the value, but the Connection property will laizy read/allocate the value from native if it hasn't been read yet. E.g. if you check _Connection after Connection they should have the same value.

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt (hunk 4 above)
Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:232]: ack

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 7]
```diff
@@ -213,5 +213,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
             }
 <# } #>
         }
+
+        private ReadOnlySpan<byte> HeaderKeys => new byte[]
```
[the remark this answers is not in the document]
Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:217]: ack

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt (hunk 3 above)
Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:229]: ack, updating

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt (hunk 5 above)
Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:240]: ack

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs [hunk 8]
```diff
@@ -375,6 +375,108 @@ private bool HasKnowHeaderHelper(HttpSysRequestHeader header, long fixup, HttpAp
         return value;
     }
 
+    internal void GetKnownKeys(ReadOnlySpan<byte> expectedHeaders, Span<bool> observedHeaders)
```
[the remark this answers is not in the document]
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:378]: Do you suggest to rename it or to use HasKnownHeader instead? The reason I added this method is to push the for loop that iterates over all headers to here (less method calls, fixing and `if`s to decide if the structure is pinned etc.), but happy to use HasKnownHeader instead.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 9]
```diff
@@ -240,4 +265,38 @@ public IEnumerable<string> GetValues(string key)
...
+            {
+                observedHeaders[observedHeadersCount++] = GetHeaderKeyName(header);
+            }
+        }
+        return observedHeadersCount;
+    }
+
+    private int GetKnownHeadersCount(ReadOnlySpan<byte> expectedHeaders)
+    {
+        Span<bool> nativeHeaders = stackalloc bool[expectedHeaders.Length];
```
[the remark this answers is not in the document]
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:288]: ack

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt (hunk 6 above)
Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: very good point. Is checking the Count better to comparing against `StringValues.Empty`?

Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: > Is checking the Count `<#=prop.Name#>.Count > 0` better to comparing against `StringValues.Empty`?

They should be functionally the same, and 0 is shorter 😁

Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: I was considering perf, I would _assume_ `StringValues.Empty`, I will measure it.

Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: https://github.com/dotnet/runtime/blob/4deccc02588990626180eaa812e63603d6c2790e/src/libraries/Microsoft.Extensions.Primitives/src/StringValues.cs#L526-L530

Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:243]: Ok, Count it is :)

**Comment by ladeak** [comment]
I pushed an update, but it is getting late here. Let me run re-run the performance tests tomorrow.

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 10]
```diff
@@ -213,5 +212,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+
+        private string GetHeaderKeyName(HttpSysRequestHeader header) => header switch
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => HeaderNames.<#=prop.Name#>,
+<# } #>
+            _ => throw new NotImplementedException()
+        };
+
+        private bool IsRead(HttpSysRequestHeader header) => header switch
```
Comment (ladeak) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:231]: I think i can remove this now.

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt [hunk 11]
```diff
@@ -213,5 +212,36 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => <#=IsRead(prop.Index)#>,
+<# } #>
+            _ => throw new NotImplementedException()
+        };
+
+        private bool IsKnownHeaderSet(HttpSysRequestHeader header) => header switch
```
Comment (ladeak) [inline src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:239]: Maybe `IsKnownHeaderPresent` is a better name?

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 12]
```diff
@@ -240,4 +265,32 @@ public IEnumerable<string> GetValues(string key)
         }
         return HeaderParser.Empty;
     }
+
+    private int GetKnownHeadersWithValue(ReadOnlySpan<byte> expectedHeaders, Span<string> observedHeaders)
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:269]: GetKnownHeadersKeys

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 13]
```diff
@@ -87,7 +84,23 @@ public bool ContainsKey(string key)
 
     public ICollection<string> Keys
     {
-        get { return PropertiesKeys().Concat(Extra.Keys).ToArray(); }
+        get
+        {
+            var destination = new string[Count];
+            int knownHeadersCount = GetKnownHeadersWithValue(HeaderKeys, destination);
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:90]: HeaderKeys doesn't need to be passed in here, it can be referenced directly.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 14]
```diff
@@ -97,7 +110,12 @@ public ICollection<string> Keys
 
     public int Count
     {
-        get { return PropertiesKeys().Count() + Extra.Count; }
+        get
+        {
+            int count = GetKnownHeadersCount(HeaderKeys);
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:115]: HeaderKeys doesn't need to be passed in here either

File: src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt (hunk 11 above)
Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:239]: I still like HasKnownHeader, but that's ambiguous with the other new one. Oh, you don't need the other one anymore, it's only called here. You can inline the `_requestMemoryBlob.HasKnownHeader(header)` call and get rid of the other method.

Comment (ladeak) [reply src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt:239]: ack

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 12 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:269]: ack

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 14 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:115]: ack

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt [hunk 15]
```diff
@@ -213,5 +212,28 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
...
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => HeaderNames.<#=prop.Name#>,
+<# } #>
+            _ => throw new NotImplementedException()
+        };
+
+        private bool HasKnownHeader(HttpSysRequestHeader header) => header switch
+        {
+<# foreach(var prop in props) { #>
+            <#=prop.ID#> => <#=IsRead(prop.Index)#> ? _<#=prop.Name#>.Count > 0 : _requestMemoryBlob.HasKnownHeader(<#=prop.ID#>),
```
Comment (ladeak) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt:234]: Note, that I am using `_<#=prop.Name#>.Count > 0` here (with underscore prefix), and previously _PropertiesTryRemove_ method has been using without the underscore:

```csharp
(<#=IsRead(prop.Index)#> && <#=prop.Name#>.Count > 0)
  || (!<#=IsRead(prop.Index)#> && HasKnownHeader(<#=prop.ID#>))
```

**Comment by ladeak** [comment]
@Tratcher I have rebased to include your latest changes. I addressed all comments. I fixed some space/tabs styling in the .tt file, and re-run the performance tests.

However, it seems some of the Mean execution times got worse.

```// * Summary *

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.22621
12th Gen Intel Core i7-1255U, 1 CPU, 12 logical and 10 physical cores
.NET SDK=8.0.100-alpha.1.22531.1
  [Host]     : .NET 8.0.0 (8.0.22.57309), X64 RyuJIT
  DefaultJob : .NET 8.0.0 (8.0.22.52901), X64 RyuJIT

Server=True

|            Method |        Job |     Toolchain | RunStrategy |       Mean |    Error |   StdDev |        Op/s |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------ |----------- |-------------- |------------ |-----------:|---------:|---------:|------------:|-------:|-------:|------:|----------:|
| CountSingleHeader | DefaultJob |       Default |     Default |   437.7 ns |  7.07 ns |  5.90 ns | 2,284,739.0 |      - |      - |     - |         - |
| CountLargeHeaders | DefaultJob |       Default |     Default |   473.1 ns |  9.33 ns | 16.10 ns | 2,113,551.5 |      - |      - |     - |         - |
|  KeysSingleHeader | DefaultJob |       Default |     Default | 1,040.6 ns | 20.85 ns | 31.21 ns |   960,987.4 | 0.0038 |      - |     - |      32 B |
|  KeysLargeHeaders | DefaultJob |       Default |     Default | 1,851.2 ns | 13.13 ns | 12.28 ns |   540,190.3 | 0.4425 | 0.0095 |     - |   2,776 B |
```

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs [hunk 16]
```diff
@@ -375,6 +375,79 @@ private bool HasKnowHeaderHelper(HttpSysRequestHeader header, long fixup, HttpAp
...
+        var pUnknownHeader = (HttpApiTypes.HTTP_UNKNOWN_HEADER*)(fixup + (byte*)request->Headers.pUnknownHeaders);
+        for (int index = 0; index < request->Headers.UnknownHeaderCount; index++)
+        {
+            // For unknown headers, when header value is empty, RawValueLength will be 0 and
+            // pRawValue will be null.
+            if (pUnknownHeader->pName != null && pUnknownHeader->NameLength > 0)
+            {
+                count++;
+            }
+            pUnknownHeader++;
```
Comment (ladeak) [inline src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:446]: I wonder if using ref byte-s and Unsafe.As / Unsafe.Add could be beneficial here?

**Comment by BrennanConroy** [comment]
Something broke in your latest changes, but since you force-pushed I can't tell what it was.

**Comment by ladeak** [comment]
I had to rebase because of conflicts with https://github.com/dotnet/aspnetcore/pull/45250

**Comment by ladeak** [comment]
The current performance results:

```
|            Method |        Job |     Toolchain | RunStrategy |       Mean |    Error |   StdDev |        Op/s |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------ |----------- |-------------- |------------ |-----------:|---------:|---------:|------------:|-------:|-------:|------:|----------:|
| CountSingleHeader | DefaultJob |       Default |     Default |   403.7 ns |  7.95 ns |  8.83 ns | 2,476,942.2 |      - |      - |     - |         - |
| CountLargeHeaders | DefaultJob |       Default |     Default |   441.2 ns |  3.54 ns |  3.32 ns | 2,266,582.1 |      - |      - |     - |         - |
|  KeysSingleHeader | DefaultJob |       Default |     Default |   916.0 ns | 15.29 ns | 23.36 ns | 1,091,654.4 | 0.0048 |      - |     - |      32 B |
|  KeysLargeHeaders | DefaultJob |       Default |     Default | 1,800.9 ns | 14.42 ns | 13.49 ns |   555,283.7 | 0.4425 | 0.0095 |     - |   2,776 B |
```

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt [hunk 17]
```diff
@@ -113,7 +113,7 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
                         return <#=prop.Name#>.Count > 0;
                     }
 <# } #>
-                    break;
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt:116]: Formatting? Revert these

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 18]
```diff
@@ -240,4 +260,36 @@ public IEnumerable<string> GetValues(string key)
...
+            keys = keys.Slice(1);
+        }
+        return observedHeadersCount;
+    }
+
+    private int GetKnownHeadersCount()
+    {
+        int observedHeadersCount = 0;
+        var keys = HeaderKeys;
+        while (keys.Length > 0)
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:284]: Why not use a for loop? Slice is an unusual pattern when you're consuming data in order.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt [hunk 19]
```diff
@@ -168,17 +168,16 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
 <# foreach(var prop in length) { #>
                     if (string.Equals(key, HeaderNames.<#=prop.Name#>, StringComparison.Ordinal))
                     {
-                        if ((<#=IsRead(prop.Index)#> && <#=prop.Name#>.Count > 0)
-                            || (!<#=IsRead(prop.Index)#> && HasKnownHeader(<#=prop.ID#>)))
-                        {
+                         if (HasKnownHeader(<#=prop.ID#>))
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt:171]:
```suggestion
                        if (HasKnownHeader(<#=prop.ID#>))                            
```

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt [hunk 20]
```diff
@@ -168,17 +168,16 @@ namespace Microsoft.AspNetCore.HttpSys.Internal
 <# foreach(var prop in length) { #>
                     if (string.Equals(key, HeaderNames.<#=prop.Name#>, StringComparison.Ordinal))
                     {
-                        if ((<#=IsRead(prop.Index)#> && <#=prop.Name#>.Count > 0)
-                            || (!<#=IsRead(prop.Index)#> && HasKnownHeader(<#=prop.ID#>)))
-                        {
+                         if (HasKnownHeader(<#=prop.ID#>))                            
+                        {
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt:172]:
```suggestion
                        {
```

File: src/Servers/HttpSys/test/FunctionalTests/RequestHeaderTests.cs [hunk 21]
```diff
@@ -174,6 +182,407 @@ public async Task RequestHeaders_ClientSendTransferEncodingAndContentLength_Cont
...
+        {
+            { "X-UnknownHeader-0", "0" },
+            { "My-UnknownHeader-1", "1" },
+            { "X-UnknownHeader-2", "2" }
+        };
+        await SendRequestAsync(address, headerDictionary);
+    }
+
+    [ConditionalFact]
+    public unsafe void RequestHeaders_PooledMemory_ReturnsKnownHeadersKeys()
```
Comment (Tratcher) [inline src/Servers/HttpSys/test/FunctionalTests/RequestHeaderTests.cs:239]: Nice tests. Can you move any that don't touch the network over to 
https://github.com/dotnet/aspnetcore/tree/main/src/Servers/HttpSys/test/Tests

They might not need to be conditional either.

**Review by Tratcher — APPROVED** [review]
Looks like everything is working, nice job.
A few comments on formatting and this should be ready to go.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 18 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:284]: I will revert to for loop. I generally like the idea that I have to index into 0 always.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt (hunk 17 above)
Comment (ladeak) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.Generated.tt:116]: reverting

**Comment by ladeak** [comment]
@Tratcher I am sorry, but I ended up force pushing against my original intentions :(

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks for working through this

**Comment by Tratcher** [comment]
This may have caused a regression in the following test:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=96807&view=ms.vss-test-web.build-test-results-tab&runId=2055890&resultId=100028&paneView=debug

Investigating.

**Comment by ladeak** [comment]
Let me know how I can help.

**Comment by Tratcher** [comment]
Nevermind, the new error is related to hostfxr even trying to load the app, that shouldn't be related to any changes here. This was just the first occurance.

**Comment by ladeak** [comment]
Thank you for looking into.
