### PR TITLE
Fix uncompressed scenarios with DisableBuffering 

### LINKED ISSUE #36960: Brotli compression + disable response buffering for plain text yields incorrect response body
### Describe the bug

If using Brotli compression in combination with disabling response buffering, plain text written to the response stream seems to not be encoded correctly.

### To Reproduce

Project demonstrating problem:
https://github.com/jander-msft/repros/tree/main/CompressedUnbufferedResponse

Run net6.0 web project and navigate to /test route. It should return "Hello", but it returns a handful of unprintable characters with "Hello" in the middle of it.

Running the netcoreapp3.1 build output with the same steps works as expected.

netcoreapp3.1 response in hex: `EF BB BF 48 65 6C 6C 6F 21 0A`
net6.0 response in hex: `0B 01 80 EF BB BF 30 00 08 48 65 6C 6C 6F 21 0A 03`

Note the extra `0B 01 80` prefix, the extra `30 00 08` after the BOM, and the extra `03` postfix.

Either removing the Brotli compression OR removing the disabling of the response buffering does fix the issue.

### Further technical details
ASP.NET Core version: 6.0.0-rc.1.21451.13

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.413 [C:\Program Files (x86)\dotnet\sdk]
  5.0.401 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by Tratcher**
Contributes to #36960

The compression provider is created so long as the client's request allows compression.  The compression stream should only be created if the response content-type is compressible. 

DisableBuffering for uncompressed responses was regressed by https://github.com/dotnet/aspnetcore/pull/28464/. If you called DisableBuffering then the compression stream would still get created but none of the compression headers would be set so the client wouldn't decompress.

The fix is to only create the compression stream if ShouldCompressResponse is true.

This should be backported to 6.0.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

File: src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs [hunk 1]
```diff
@@ -201,7 +201,7 @@ public override async ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, Cancella
             }
         }
 
-        private void InitializeCompressionHeaders()
+        private ICompressionProvider? InitializeCompressionHeaders()
```
Comment (HaoK) [inline src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:204]: nit: maybe rename this GetCompressionProvider since now it returns the provider, maybe add a short comment saying why it would return null (compression not enabled, etc)

**Review by HaoK — APPROVED** [review]

File: src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs (hunk 1 above)
Comment (Tratcher) [reply src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:204]: Renaming it would be misleading, it's main job is to set the headers. I will add a comment about the return value.

File: src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs [hunk 2]
```diff
@@ -244,11 +252,11 @@ private void OnWrite()
             {
                 _compressionChecked = true;
 
-                InitializeCompressionHeaders();
+                var compressionProvider = InitializeCompressionHeaders();
 
-                if (_compressionProvider != null)
```
Comment (Pilchie) [inline src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:249]: Does this leave a field that is never initialized now?

Comment (Tratcher) [reply src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:249]: This wasn't where it was initialized, only consumed. It's initialized over here:
https://github.com/dotnet/aspnetcore/blob/59baa0d6f93022e87cc82faaf0433fe3513a38a9/src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs#L269

The _compressionProvider field exists because there are two code paths that might cause it to be created, OnWrite and DisableBuffering, and we don't want to create it twice.

Comment (Pilchie) [reply src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:249]: But now the field is never assigned in OnWrite, so it will be created twice?

Comment (Pilchie) [reply src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:249]: Ah, I see - it `ResolveCompressionProvider` is called from `InitialializeCompressionHeader`, so it does end up being the same instance.

Comment (Tratcher) [reply src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:249]: It's assignment hasn't changed, that happens in ResolveCompressionProvider via:
- OnWrite()
  - InitializeCompressionHeaders();
    - ResolveCompressionProvider();

The alternate code path is:
- DisableBuffering()
  - ResolveCompressionProvider();
