### PR TITLE
[TS Client] Fix CompletionMessage result when passing false or null

### LINKED ISSUE #45168: ISingleClientProxy.InvokeAsync<T> throwing System.Exception upon receiving return value from client invocations using messagepack protocol
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upon receiving a result value from client invocation, ISingleClientProxy.InvokeAsync<T> will throw a generic System.Exception exception. The exception is only thrown when using messagepack protocol. 

### Expected Behavior

No exceptions thrown when receiving return value from client invocation.

### Steps To Reproduce

The issue can be reproduced with a minimal modified ChatHub project here: 
https://github.com/steamedbuns/SignalRMessagePackInvoke.git

See `ChatHub` class for location of exception.
See `chat.js` for client implementation.

### Exceptions (if any)

```
System.Exception
  HResult=0x80131500
  Message=Exception of type 'System.Exception' was thrown.
  Source=Microsoft.AspNetCore.SignalR.Core
  StackTrace:
   at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.<InvokeConnectionAsync>d__23`1.MoveNext()
   at Microsoft.AspNetCore.SignalR.Internal.HubCallerClients.SingleClientProxy.<InvokeCoreAsync>d__3`1.MoveNext()
   at SignalRInvoke.Hubs.ChatHub.<InvokeMessage>d__0.MoveNext() in C:\Development\test_projects\SignalRInvoke\SignalRInvoke\Hubs\ChatHub.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]
    SignalRInvoke.Hubs.ChatHub.InvokeMessage(string, string) in ChatHub.cs
```

### .NET Version

7.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/45168

Our check for if a result existed for a completion message didn't handle `false` or `null` results.

### CODE REVIEW

**Comment by campersau** [comment]
Or other javascript falsy values like `""` and `0` I guess.

**Comment by BrennanConroy** [comment]
> Or other javascript falsy values like `""` and `0` I guess.

Isn't javascript great... 😆

**Review by adityamandaleeka — APPROVED** [review]

File: src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts [hunk 1]
```diff
@@ -284,7 +284,8 @@ export class MessagePackHubProtocol implements IHubProtocol {
     }
 
     private _writeCompletion(completionMessage: CompletionMessage): ArrayBuffer {
-        const resultKind = completionMessage.error ? this._errorResult : completionMessage.result ? this._nonVoidResult : this._voidResult;
+        const resultKind = completionMessage.error ? this._errorResult :
```
Comment (halter73) [inline src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts:287]: What if `completionMessage.error` is an empty string instead of `undefined` or `null`? Should that be treated as an error result still?

Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts:287]: Yeah, any non-null value should be considered an error. I don't think there is anyway today for an empty string to be set, but even if it was that should be considered an error.
In theory we should throw for both error and result being set, but since I want to backport this change, and we control the creation of completion messages it would basically only be an assert, I'm not going to add that.

**Comment by amcasey** [comment]
Offline sign-off from @halter73
