### PR TITLE
Make Kestrel config case-insensitive for certificates

### LINKED ISSUE #21494: Kestrel config should be case insensitive
I discovered this issue while working on investigating some of our tests. Essentially Kestrel won't pick up the certificate if the casing doesn't exactly match what it expects. I was observing the issue here

This is the change that I made to our tests:
https://github.com/dotnet/aspnetcore/pull/21493/files#diff-f6ac04d303881c9012a20f9fe4cc2621L73-L75

This is where I think the issue is:
https://github.com/dotnet/aspnetcore/blob/4ebf695a98bcc76343df1f3be76ae583735584e9/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs#L338

This is my reasoning/evidence to argue that this should be case insensitive:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#configuration-keys-and-values

In essence we tell our customers that config is case-insensitive but this piece seems to not be so, so I consider that a bug. The experience is bad because it just doesn't work and you don't get any hint of what's going on.

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempts to resolve https://github.com/dotnet/aspnetcore/issues/21494

### CODE REVIEW

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs [hunk 1]
```diff
@@ -253,6 +253,38 @@ public void ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent()
...
+            }
+            finally
+            {
+                if (File.Exists(GetCertificatePath()))
+                {
+                    File.Delete(GetCertificatePath());
+                }
+            }
+        }
+
```
Comment (wtgodbe) [inline src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:287]: This test fails without the change to ConfigurationReader.cs

**Review by BrennanConroy — APPROVED** [review]
Add a test that multiple certs with the same name throws?
"Development" vs "DEVELOPMENT"

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs [hunk 2]
```diff
@@ -253,6 +253,38 @@ public void ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent()
             }
         }
 
+        [Fact]
+        public void ConfigureEndpointDevelopmentCertificateIsCaseInsensitive()
```
Comment (Tratcher) [inline src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:257]: Since the change was in ConfigurationReader, you can probobly write a more targeted test in ConfigurationReaderTests. That would let you avoid some of this overhead like writing a cert to file.
https://github.com/dotnet/aspnetcore/blob/fa20111e47774b6c08f82a1f0c6373cc30e99a83/src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs

Comment (halter73) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:257]: Good idea. I try to avoid file I/O (or really any I/O) in Kestrel tests if at all possible.

File: src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs [hunk 3]
```diff
@@ -68,6 +68,39 @@ public void ReadCertificatesSection_ReturnsCollection()
...
+        public void ReadCertificatesSection_ThrowsOnCaseInsensitiveDuplicate()
+        {
+            var exception = Assert.Throws<ArgumentException>(() => 
+                new ConfigurationBuilder().AddInMemoryCollection(new[]
+                {
+                    new KeyValuePair<string, string>("Certificates:filecert:Password", "certpassword"),
+                    new KeyValuePair<string, string>("Certificates:FILECERT:Password", "certpassword"),
+                }).Build());
+
+            Assert.Contains("An item with the same key has already been added", exception.Message);
```
Comment (wtgodbe) [inline src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs:101]: This string is in Kestrel/Core/src/CoreStrings.resx - would it better to add a reference to that resource file to the .csproj?

**Comment by wtgodbe** [comment]
Updated

**Review by Tratcher — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs (hunk 3 above)
Comment (halter73) [reply src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs:101]: CoreStrings is already InternalsVisibleTo to this project you just need to add a using for Microsoft.AspNetCore.Server.Kestrel.Core.

File: src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs [hunk 4]
```diff
@@ -68,6 +68,39 @@ public void ReadCertificatesSection_ReturnsCollection()
             Assert.True(storeCert.AllowInvalid);
         }
 
+        [Fact]
+        public void ReadCertificatesSection_IsCaseInsensitive()
+        {
+            var config = new ConfigurationBuilder().AddInMemoryCollection(new[]
+            {
+                new KeyValuePair<string, string>("Certificates:filecert:Path", "/path/cert.pfx"),
+                new KeyValuePair<string, string>("Certificates:FILECERT:Password", "certpassword"),
```
Comment (halter73) [inline src/Servers/Kestrel/Kestrel/test/ConfigurationReaderTests.cs:77]: This should still pass if the entire key is UPPERCASE, right? I know this PR only changes the dictionary comparer, but I see no reason not to verify the rest of it case insensitive while we're at it.
