### PR TITLE
Fully qualify type names for services when resolving in RequestDelegateGenerator

### LINKED ISSUE #58633: `FromKeyedServices` Causes Generated Code to Fail to Compile
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

With the request delegate generator enabled, injecting a keyed service which is defined in a namespace "Http" will cause the request delegate generator to generate code that doesn't compile.

The call to `GetRequiredKeyedService` doesn't `global`-root its type parameter, so it looks for the injected service in the "Microsoft.AspNetCore.Http" namespace:

```c#
var e_local = httpContext.RequestServices.GetRequiredKeyedService<Http.ExampleService>("example");
```

### Expected Behavior

The code compiles and retrieves the injected service by key.

### Steps To Reproduce

I've committed [a reproduction](https://github.com/chrisoverzero/keyed-service-http-repro). I've also committed the generated code, and the place where the error occurs is line 115 of "Generated/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs"

### Exceptions (if any)

None.

### .NET Version

9.0.100-rc.2.24474.11

### Anything else?

<details>

<summary>

`dotnet --info` shows:

</summary>

```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.82b7fac4
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100-rc.2.24474.11/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: arm64
  Commit:       990ebf52fc

.NET SDKs installed:
  6.0.417 [/usr/local/share/dotnet/sdk]
  6.0.418 [/usr/local/share/dotnet/sdk]
  7.0.404 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.3.24204.13 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.6.24328.19 [/usr/local/share/dotnet/sdk]
  9.0.100-rc.1.24452.12 [/usr/local/share/dotnet/sdk]
  9.0.100-rc.2.24474.11 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.3.24172.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

</details>

### PR DESCRIPTION
**Pull request by chrisoverzero**
# Fully Qualify Type Names When Resolving in RDG

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

These two places correspond to resolution of a service from DI when attributed with `FromServicesAttribute` or with
`FromKeyedServicesAttribute`. When the type name of the service is not fully qualified, the generator can generate code which fails to compile.

## Description

For example, given a service `ExampleService` in namespace `Http`, the generator can generate code to resolve an instance of such a service like this:

```c#
var e_local = httpContext.RequestServices.GetRequiredKeyedService<Http.ExampleService>("example");
```

…but `Microsoft.AspNetCore.Http` is a nearer match for the reference to "Http", so the compiler will look for a type
`Microsoft.AspNetCore.Http.ExampleService` (which doesn't exist – at least, not at time of writing), and compilation will fail.

Fixes #58633

### CODE REVIEW

File: src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/EndpointParameterEmitter.cs [hunk 1]
```diff
@@ -404,8 +404,8 @@ internal static void EmitKeyedServiceParameterPreparation(this EndpointParameter
         codeWriter.EndBlock();
 
         var assigningCode = endpointParameter.IsOptional ?
-            $"httpContext.RequestServices.GetKeyedService<{endpointParameter.Type}>({endpointParameter.KeyedServiceKey});" :
-            $"httpContext.RequestServices.GetRequiredKeyedService<{endpointParameter.Type}>({endpointParameter.KeyedServiceKey})";
+            $"httpContext.RequestServices.GetKeyedService<{endpointParameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>({endpointParameter.KeyedServiceKey});" :
```
Comment (captainsafia) [inline src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/EndpointParameterEmitter.cs:407]:
```suggestion
            $"httpContext.RequestServices.GetKeyedService<{endpointParameter.Type.ToDisplayString(EmitterConstants.DisplayFormat)}>({endpointParameter.KeyedServiceKey});" :
```

We have a predefined SymbolFormat that's used elsewhere for fully-qualified types that we can use here.

**Review by captainsafia — COMMENTED** [review]
Thanks for opening a PR for this! I left one recommendation inline.

Also -- any chance we can add test coverage for this?

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs [hunk 2]
```diff
@@ -287,6 +287,7 @@ internal static string GetMapActionString(string sources, string className = "Te
 using Microsoft.AspNetCore.Http.Generators.Tests;
 using Microsoft.Extensions.Primitives;
 using Microsoft.Extensions.DependencyInjection;
+using Http;
```
Comment (captainsafia) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs:290]:
```suggestion
```

I think we can remove this?

**Review by captainsafia — APPROVED** [review]
Looks good overall! Left one small comment about a possibly unneeded using in the base class for tests.

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs (hunk 2 above)
Comment (chrisoverzero) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs:290]: If I remove that line, the new tests fail to compile.

The test is whether the request delegate generator generates compilable code when a service from the namespace "Http" is explicitly requested from DI. There doesn't seem to be a way to add to that list of imports per-test, so I had to add it to the universal template.

I could alternatively `global`ly qualify the type in the source string in `RequestDelegateGeneratesCompilableCodeForServiceInNamespaceHttp` and `RequestDelegateGeneratesCompilableCodeForKeyedServiceInNamespaceHttp`, but that felt worse to me. I'll do it at your advisement, of course.

Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs:290]: Ah! 🤦🏽‍♀️ I failed to realize that this is the imports for the test code, not the imports for the file. All good here!

**Comment by chrisoverzero** [comment]
The failures here look unrelated. Is there a way to kick the build off again, or is this waiting for something?

**Comment by captainsafia** [comment]
> The failures here look unrelated. Is there a way to kick the build off again, or is this waiting for something?

Our builds can be flakey sometimes. I've just kicked it to hopefully get this through. 🤞🏽
