### PR TITLE
Fix the code to ignore parameters from incorrect locations

### LINKED ISSUE #42483: Parameters from body or forms should not be generated as OpenApiParameters
Fix me:

https://github.com/dotnet/aspnetcore/blob/f4f4835635a812cfe24b724b8a1c4aab6cee8705/src/OpenApi/src/OpenApiGenerator.cs#L369-L372

### PR DESCRIPTION
**Pull request by anhthidao**
# Fix the code to ignore parameters that are not from header/query/route/path

Fixes #42483

### CODE REVIEW

File: src/OpenApi/src/OpenApiGenerator.cs [hunk 1]
```diff
@@ -417,29 +413,29 @@ private List<OpenApiParameter> GetOpenApiParameters(MethodInfo methodInfo, Endpo
         return openApiParameterContent;
     }
 
-    private (bool isBodyOrForm, ParameterLocation? locatedIn) GetOpenApiParameterLocation(ParameterInfo parameter, RoutePattern pattern, bool disableInferredBody)
+    private (bool isBodyOrForm, ParameterLocation? locatedIn, bool isParameter) GetOpenApiParameterLocation(ParameterInfo parameter, RoutePattern pattern, bool disableInferredBody)
```
Comment (halter73) [inline src/OpenApi/src/OpenApiGenerator.cs:416]: Is it necessary to add `isParameter` to the tuple? It seems like it's always equivalent to `locatedIn is not null`.

File: src/OpenApi/test/OpenApiGeneratorTests.cs [hunk 2]
```diff
@@ -88,17 +88,17 @@ static void AssertCustomRequestFormat(OpenApiOperation operation)
         }
 
         AssertCustomRequestFormat(GetOpenApiOperation(
-            [Consumes("application/custom")] (InferredJsonClass fromBody) => { }));
+            [Consumes("application/custom")] ([FromQuery] int foo) => { }));
 
         AssertCustomRequestFormat(GetOpenApiOperation(
-            [Consumes("application/custom")] ([FromBody] int fromBody) => { }));
```
Comment (halter73) [inline src/OpenApi/test/OpenApiGeneratorTests.cs:94]: Can we update this test just to assert there are no parameters, but keep the test route handlers the same?

File: src/OpenApi/test/OpenApiGeneratorTests.cs [hunk 3]
```diff
@@ -88,17 +88,17 @@ static void AssertCustomRequestFormat(OpenApiOperation operation)
...
     }
 
     [Fact]
     public void AddsMultipleRequestFormatsFromMetadata()
     {
         var operation = GetOpenApiOperation(
-            [Consumes("application/custom0", "application/custom1")] (InferredJsonClass fromBody) => { });
+            [Consumes("application/custom0", "application/custom1")] (int foo) => { });
 
         var request = Assert.Single(operation.Parameters);
```
Comment (halter73) [inline src/OpenApi/test/OpenApiGeneratorTests.cs:103]:
```suggestion
        var request = Assert.Empty(operation.Parameters);
```

Let's keep the route handler the same here too.

**Review by halter73 — COMMENTED** [review]
Looking good so far.

File: src/OpenApi/src/OpenApiGenerator.cs [hunk 4]
```diff
@@ -359,16 +359,12 @@ private List<OpenApiParameter> GetOpenApiParameters(MethodInfo methodInfo, Endpo
...
             }
 
-            var (isBodyOrFormParameter, parameterLocation) = GetOpenApiParameterLocation(parameter, pattern, disableInferredBody);
+            var (_, parameterLocation) = GetOpenApiParameterLocation(parameter, pattern, disableInferredBody);
 
-            // If the parameter isn't something that would be populated in RequestBody
-            // or doesn't have a valid ParameterLocation, then it must be a service
-            // parameter that we can ignore.
-            if (!isBodyOrFormParameter && parameterLocation is null)
+            if (parameterLocation is null)
```
Comment (captainsafia) [inline src/OpenApi/src/OpenApiGenerator.cs:364]: Let's keep a code comment in here that makes it clear we only populate `OpenApiParameters` with a parameter if it has a valid location.

File: src/OpenApi/test/OpenApiGeneratorTests.cs [hunk 5]
```diff
@@ -771,6 +764,22 @@ public void HandlesEndpointWithMultipleResponses()
...
+    [Fact]
+    public void OnlyAddParametersWithCorrectLocations()
+    {
+        var operation = GetOpenApiOperation(([FromBody] int fromBody, [FromRoute] int fromRoute, [FromServices] int fromServices) => { });
+
+        Assert.Single(operation.Parameters);
+    }
+
+    [Fact]
+    public void DoNotAddParametersWithTypeIFormFile()
```
Comment (captainsafia) [inline src/OpenApi/test/OpenApiGeneratorTests.cs:776]: You might be able to add the check for empty `operation.Parameters` in `AddsFromFormParameterAsFormFile` instead of adding a new test.

File: src/OpenApi/test/OpenApiGeneratorTests.cs [hunk 6]
```diff
@@ -336,7 +337,7 @@ static void AssertBodyParameter(OpenApiOperation operation, string expectedName,
     public void AddsMultipleParameters()
     {
         var operation = GetOpenApiOperation(([FromRoute] int foo, int bar, InferredJsonClass fromBody) => { });
-        Assert.Equal(3, operation.Parameters.Count);
+        Assert.Equal(2, operation.Parameters.Count);
```
Comment (captainsafia) [inline src/OpenApi/test/OpenApiGeneratorTests.cs:340]: Great! This test change does a great job reflecting the original bug that was fixed here.

File: src/OpenApi/test/OpenApiGeneratorTests.cs [hunk 7]
```diff
@@ -82,9 +82,9 @@ public void AddsRequestFormatFromMetadata()
     {
         static void AssertCustomRequestFormat(OpenApiOperation operation)
         {
-            var request = Assert.Single(operation.Parameters);
-            var content = Assert.Single(request.Content);
-            Assert.Equal("application/custom", content.Key);
+            Assert.Empty(operation.Parameters);
```
Comment (captainsafia) [inline src/OpenApi/test/OpenApiGeneratorTests.cs:85]: Supr nit: for additional confidence here what do you think about adding a `Assert.Empty(parameter)` where applicable if we are asserting on `operation.RequestBody`. For example, like here:

https://github.com/dotnet/aspnetcore/blob/5249c1fcc2a923494ef0082d99540eed4ca49d0c/src/OpenApi/test/OpenApiGeneratorTests.cs#L727

**Review by captainsafia — COMMENTED** [review]
Looking good so far! The remaining comments are largely about tests/code comments but the code related to the bug fix looks good.

**Review by captainsafia — APPROVED** [review]
