### PR TITLE
Use ArgumentException.ThrowIfNullOrEmpty and ThrowIfNullOrWhitespace

### LINKED ISSUE #48185: Use ArgumentException.ThrowIfNullOrWhitespace
implemented in https://github.com/dotnet/runtime/pull/86007 and should flow here in a few days.

similar effort for ThrowIfNull https://github.com/dotnet/aspnetcore/issues/43482

there have been several of these throw helpers added in the core libraries this release, maybe there's others that are relevant to us. perhaps someone would like to take a look?

### LINKED ISSUE #50665: Use ArgumentException.ThrowIfNullOrEmpty
## Background and Motivation

Creating this new issue for changes related to ArgumentException.ThrowIfNullOrEmpty helper specifically, in order to keep it separate from #48185 and make the changes more easily reviewable

Similar to https://github.com/dotnet/runtime/pull/64357.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #48185.
Fixes #50665.

### CODE REVIEW

**Comment by joegoldman2** [comment]
I am not sure to understand this error: `##[error]src/Shared/ThrowHelpers/ArgumentThrowHelper.cs(60,5): error CS8777: (NETCORE_ENGINEERING_TELEMETRY=Build) Parameter 'argument' must have a non-null value when exiting.`. I'm open to suggestions if anyone has an idea.

**Comment by joegoldman2** [comment]
I'm not sure to understand this error: `##[error]src/Shared/ThrowHelpers/ArgumentThrowHelper.cs(60,5): error CS8777: (NETCORE_ENGINEERING_TELEMETRY=Build) Parameter 'argument' must have a non-null value when exiting.`.
I'm open to suggestions if anyone has any idea.

**Comment by joegoldman2** [comment]
> I'm not sure to understand this error: `##[error]src/Shared/ThrowHelpers/ArgumentThrowHelper.cs(60,5): error CS8777: (NETCORE_ENGINEERING_TELEMETRY=Build) Parameter 'argument' must have a non-null value when exiting.`. I'm open to suggestions if anyone has any idea.

This issue has been fixed. The build failures seem unrelated. This PR is ready to be reviewed.

File: src/Components/Components/src/CascadingValue.cs [hunk 1]
```diff
@@ -76,10 +76,7 @@ public Task SetParametersAsync(ParameterView parameters)
             else if (parameter.Name.Equals(nameof(Name), StringComparison.OrdinalIgnoreCase))
             {
                 Name = (string)parameter.Value;
-                if (string.IsNullOrEmpty(Name))
-                {
-                    throw new ArgumentException($"The parameter '{nameof(Name)}' for component '{nameof(CascadingValue<TValue>)}' does not allow null or empty values.");
```
Comment (halter73) [inline src/Components/Components/src/CascadingValue.cs:81]: This was clearer with the old exception message. `parameter.Name` is not null. `parameter.Name == "Name"` and `string.IsNullOrEmpty(parameter.Value)`.

Let's only replace messages where the new message is at least as good or better.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs [hunk 2]
```diff
@@ -350,15 +350,8 @@ public static void ReceiveByteArray(JSRuntime jsRuntime, int id, byte[] data)
 
     private static (MethodInfo, Type[]) GetCachedMethodInfo(AssemblyKey assemblyKey, string methodIdentifier)
     {
-        if (string.IsNullOrWhiteSpace(assemblyKey.AssemblyName))
-        {
-            throw new ArgumentException($"Property '{nameof(AssemblyKey.AssemblyName)}' cannot be null, empty, or whitespace.", nameof(assemblyKey));
```
Comment (halter73) [inline src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:355]: Nit: `Property '{nameof(AssemblyKey.AssemblyName)}'` is slightly clearer than just `nameof(AssemblyKey.AssemblyName)` because it makes clearer that the property and not the paremeter itself is null. I know `AssemblyKey` cannot be null since it's a struct, but people running into this exception might not. `'{nameof(AssemblyKey)}.{nameof(AssemblyKey.AssemblyName)}'` would be even better.

I think everything else between `CascadingValue<TValue>.SetParametersAsync` and here in the PR looks fine even if it changes the wording slightly because it's more obvious what's invalid.

File: src/Logging.AzureAppServices/src/AzureBlobLoggerOptions.cs [hunk 3]
```diff
@@ -21,10 +22,7 @@ public string BlobName
         get { return _blobName; }
         set
         {
-            if (string.IsNullOrEmpty(value))
-            {
-                throw new ArgumentException($"{nameof(BlobName)} must be non-empty string.", nameof(value));
-            }
+            ArgumentThrowHelper.ThrowIfNullOrEmpty(value);
```
Comment (halter73) [inline src/Logging.AzureAppServices/src/AzureBlobLoggerOptions.cs:25]: 👍 I'm okay with using `value` instead of the property name in property setters since the stack trace should make it clear what `value` means in this context.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @joegoldman2.
Many of these changes are reasonable, but there are some cases, where the change will result in the thrown exception having less information than it would originally. There are also a few cases, where it seems the exception messages supported localization and your change removes that. Let's make sure we don't do that - and we stick to the original code in these cases. Would you mind updating your code to exclude these cases?

File: src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs [hunk 4]
```diff
@@ -50,28 +50,20 @@ public ForwardedHeadersMiddleware(RequestDelegate next, ILoggerFactory loggerFac
...
         _logger = loggerFactory.CreateLogger<ForwardedHeadersMiddleware>();
         _next = next;
 
         PreProcessHosts();
-
-        static void EnsureOptionNotNullorWhitespace(string value, string propertyName)
-        {
-            if (string.IsNullOrWhiteSpace(value))
-            {
-                throw new ArgumentException($"options.{propertyName} is required", nameof(options));
```
Comment (halter73) [inline src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs:72]: Given that this is thrown form a constructor that has non-options parameters, the old message was far clearer because at least it mentions "options".

File: src/Middleware/ResponseCaching/src/ResponseCachingFeature.cs [hunk 5]
```diff
@@ -21,10 +21,7 @@ public class ResponseCachingFeature : IResponseCachingFeature
             {
                 for (var i = 0; i < value.Length; i++)
                 {
-                    if (string.IsNullOrEmpty(value[i]))
-                    {
-                        throw new ArgumentException($"When {nameof(value)} contains more than one value, it cannot contain a null or empty value.", nameof(value));
```
Comment (halter73) [inline src/Middleware/ResponseCaching/src/ResponseCachingFeature.cs:26]: The new exception message is now one of the following:

> System.ArgumentNullException: Value cannot be null. (Parameter 'values[i]')
> System.ArgumentException: The value cannot be an empty string. (Parameter 'values[x]')

That leaves out the important detail that null or empty values are allowed if there's only one value in the array. Please revert this.

File: src/Middleware/Spa/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs [hunk 6]
```diff
@@ -27,15 +27,8 @@ internal static class AngularCliMiddleware
         var pkgManagerCommand = spaBuilder.Options.PackageManagerCommand;
         var sourcePath = spaBuilder.Options.SourcePath;
         var devServerPort = spaBuilder.Options.DevServerPort;
-        if (string.IsNullOrEmpty(sourcePath))
-        {
-            throw new ArgumentException("Property 'SourcePath' cannot be null or empty", nameof(spaBuilder));
```
Comment (halter73) [inline src/Middleware/Spa/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs:32]: The new exception message is now:

> System.ArgumentNullException: Value cannot be null. (Parameter 'sourcePath')

As with `CascadingValue<TValue>.SetParametersAsync`, it's worth calling out that 'SourcePath' is a property.

The new message references `sourcePath` which comes from a local variable and does not match the casing of any part of the public API. We should never be passing local variable names into these `ArgumentException` helpers.

Property names are okay only if that matches what we were doing before, since at least that's not making things worse. But here, the old message was better since it did message that it was a "Property" that was null.

If I missed other places where I missed we're making the exception message less detailed, please revert those too.

File: src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs [hunk 7]
```diff
@@ -27,15 +27,8 @@ internal static class ReactDevelopmentServerMiddleware
         var pkgManagerCommand = spaBuilder.Options.PackageManagerCommand;
         var sourcePath = spaBuilder.Options.SourcePath;
         var devServerPort = spaBuilder.Options.DevServerPort;
-        if (string.IsNullOrEmpty(sourcePath))
-        {
-            throw new ArgumentException("Property 'SourcePath' cannot be null or empty", nameof(spaBuilder));
```
Comment (halter73) [inline src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs:32]: Revert this too.

File: src/Mvc/Mvc.Core/src/ActionConstraints/HttpMethodActionConstraint.cs [hunk 8]
```diff
@@ -36,10 +36,7 @@ public HttpMethodActionConstraint(IEnumerable<string> httpMethods)
 
         foreach (var method in httpMethods)
         {
-            if (string.IsNullOrEmpty(method))
-            {
-                throw new ArgumentException("httpMethod cannot be null or empty");
-            }
+            ArgumentException.ThrowIfNullOrEmpty(method);
```
Comment (halter73) [inline src/Mvc/Mvc.Core/src/ActionConstraints/HttpMethodActionConstraint.cs:39]: We should never reference local variables when using these throw helpers. The old message wasn't that great either though. This would be better:

```suggestion
            if (string.IsNullOrEmpty(method))
            {
                throw new ArgumentException($"{nameof(httpMethods) cannot contain null or empty strings.");
            }
```

**Review by halter73 — COMMENTED** [review]
Thanks a lot! This looks like 99% goodness. I just want to revert a few of the changes that make the exception messages a little less clear.

File: src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs (hunk 4 above)
Comment (joegoldman2) [reply src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs:72]: With `ArgumentException.ThrowIfNullOrWhiteSpace(options.Value.ForwardedForHeaderName)`, the entire expression is captured as parameter name and "options" is mentioned: 

```
System.ArgumentNullException: Value cannot be null. (Parameter 'options.Value.ForwardedForHeaderName')
     at System.ArgumentNullException.Throw(String paramName)
     at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
     at System.ArgumentException.ThrowNullOrWhiteSpaceException(String argument, String paramName)
     at System.ArgumentException.ThrowIfNullOrWhiteSpace(String argument, String paramName)
     at ForwardedHeadersMiddleware..ctor(RequestDelegate next, ILoggerFactory loggerFactory, IOptions`1 options)
```

Do you still want me to revert this change?

File: src/Components/Components/src/CascadingValue.cs (hunk 1 above)
Comment (joegoldman2) [reply src/Components/Components/src/CascadingValue.cs:81]: Fair enough, I reverted this change.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs (hunk 2 above)
Comment (joegoldman2) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:355]: I understand the point but since the entire expression will be captured as parameter name, I think it's clear enough that it's a property:

`System.ArgumentNullException: Value cannot be null. (Parameter 'assemblyKey.AssemblyName')`

Do you still want me to revert this one?

**Comment by joegoldman2** [comment]
> Many of these changes are reasonable, but there are some cases, where the change will result in the thrown exception having less information than it would originally.

I tend to disagree with this tbh, for several reasons:

1. The value in the resource file I deleted is equal to "Value cannot be null or empty." and this value is very close to the one used when using `ArgumentException.ThrowIfNullOrEmpty`. The value in the resource file does not provide any additional information.

2. With this pattern: 

```cs
if (string.IsNullOrEmpty(xyz))
{
     throw new ArgumentException(Resources.Argument_NullOrEmpty, nameof(xyz));
}
```

It is always an `ArgumentException` that is thrown, regardless of whether the value is null or empty. Using, `ArgumentException.ThrowIfNullOrEmpty`, the "correct" exception is thrown depending on whether the string is null or empty.
With a null value: `System.ArgumentNullException: Value cannot be null. (Parameter 'xyz')`.
With an empty value: `System.ArgumentException: The value cannot be an empty string. (Parameter 'xyz')`

File: src/Mvc/Mvc.Core/src/ActionConstraints/HttpMethodActionConstraint.cs (hunk 8 above)
Comment (joegoldman2) [reply src/Mvc/Mvc.Core/src/ActionConstraints/HttpMethodActionConstraint.cs:39]: Done!

File: src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs (hunk 7 above)
Comment (joegoldman2) [reply src/Middleware/Spa/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs:32]: Done!

File: src/Middleware/Spa/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs (hunk 6 above)
Comment (joegoldman2) [reply src/Middleware/Spa/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs:32]: Reverted!

File: src/Middleware/ResponseCaching/src/ResponseCachingFeature.cs (hunk 5 above)
Comment (joegoldman2) [reply src/Middleware/ResponseCaching/src/ResponseCachingFeature.cs:26]: Reverted!

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs (hunk 2 above)
Comment (halter73) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:355]: No need to revert. Thanks for pushing back since the new message is clearer than I assumed. And thanks for doing all this work!

**Review by halter73 — APPROVED** [review]
Thank you for doing this!
