### PR TITLE
Fix streaming into nonstreaming outlet

### LINKED ISSUE #50804: Section outlet doesn't update when section content is rendered with streaming rendering
Repro steps:

- Install .NET 8 RC1
- Create a Blazor Web App
- In MainLayout.razor add a `SectionOutlet` in the top row: 

```razor
<div class="top-row px-4">
    <SectionOutlet SectionName="top-row" />
    <a href="https://learn.microsoft.com/aspnet/core/" target="_blank">About</a>
</div>
```

- In Weather.razor add a `SectionContent`:

```razor
<SectionContent SectionName="top-row">
    @forecasts?[0].Summary
</SectionContent>
```

- Run the app and browse to the weather page

Expected result: The weather forecast summary for the next day renders in the top row.
Actual result: The top row is empty.
Workaround: Disable streaming rendering on the weather page.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Fix streaming into nonstreaming outlet

Makes an edge case with streaming SSR and SectionOutlet work correctly

## Description

A bug was discovered when combining streaming SSR and `<SectionOutlet>` in a particular way (i.e., streaming *directly* into the `<SectionContent>`, not via any child component, when connected to a `<SectionOutlet>` that itself is nonstreaming). In this case the streamed content would not appear in the UI.

This PR makes this situation behave the same as other uses of streaming/sections, including the existing case of streaming via a child component to a nonstreaming outlet which is what our E2E tests already covered and already worked correctly.

Fixes #50804

## Customer Impact

Without this fix, developers wanting to use sections with streaming SSR would find in some cases that it doesn't work. A workaround exists (move the streaming content to a child component) but with this fix, it simply works as intended in the first place.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

It's only a change to how we decide which streamed components to emit content for, so it can only affect this one functional area. The code change is just to account for a case we hadn't considered before.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Components/test/E2ETest/ServerRenderingTests/StreamingRenderingTest.cs [hunk 1]
```diff
@@ -268,4 +268,11 @@ public async void StopsProcessingStreamingOutputFromPreviousRequestAfterEnhanced
         // Tidy up
         await new HttpClient().GetAsync(endResponseUrl);
     }
+
+    [Fact]
+    public void CanStreamDirectlyIntoSectionContentConnectedToNonStreamingOutlet()
+    {
+        Navigate($"{ServerPathBase}/streaming-with-sections");
+        Browser.Equal("This is some streaming content", () => Browser.Exists(By.Id("streaming-message")).Text);
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/StreamingRenderingTest.cs:276]: Is my understanding correct here that at no point we want to see "Is streaming..."?

Comment (SteveSandersonMS) [reply src/Components/test/E2ETest/ServerRenderingTests/StreamingRenderingTest.cs:276]: That does happen, but observing that in the test isn't necessary to validate that the bug is fixed and the feature works. Before the bug was fixed, you'd never see the final "This is some streaming content" message at all, and now you do.

**Review by javiercn — APPROVED** [review]
