### PR TITLE
Scrub extension properties in OpenAPI document during serialization

### LINKED ISSUE #56541: Schema get duplicated for every request in open-api
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0-preview.6.24320.4" />

If you modify the WeatherForecast sample with the following model
```c#
public class WeatherForecast
{
    public DateOnly Date { get; set; }

    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

    public string? Summary { get; set; }

    public IList<string> Names { get; set; } = [];
    public List<TestClass> Tests { get; set; } = [];
    public TestClass? Test { get; set; }
}

public class TestClass
{
    public string? Name { get; set; }
    public IList<string> Names { get; set; } = [];
}```

First request every thing works fine, but if you refresh the schema file multiple times, a new model is generated for every request

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Banan | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfWeatherForecast2"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfWeatherForecast2"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfWeatherForecast2"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ArrayOfWeatherForecast": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/WeatherForecast"
        }
      },
      "ArrayOfWeatherForecast2": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/WeatherForecast2"
        }
      },
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32"
          },
          "summary": {
            "type": "string",
            "nullable": true
          },
          "names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "tests": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "nullable": true
                },
                "names": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "test": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "nullable": true
              },
              "names": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "nullable": true
          }
        }
      },
      "WeatherForecast2": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32"
          },
          "summary": {
            "type": "string",
            "nullable": true
          },
          "names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "tests": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "nullable": true
                },
                "names": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "test": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "nullable": true
              },
              "names": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "nullable": true
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "WeatherForecast"
    }
  ]
}
```

### Expected Behavior

The schema should be the same for every request

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

9.0.0-preview.6.24320.4

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/56541.

The bug reported above occurs because `x-schema-id` metadata is scrubbed from the in-memory model before serialization which causes the comparison to fail between the same schema with and without an ID scrubbed. To fix this, we change the implementation to avoid scrubbing data from the in-memory model and instead rely on scrubbing at the serialization layer so the in-memory model is always consistent.

Changes in this PR consist of:

- A new `IOpenApiAny` implementation that implements a no-op `Write` method to support representing values that don't serialize themselves to disk.
- An implement of `OpenApiJsonWriter` that implements a custom `WritePropertyName` to avoid serializing keys associated with in-memory attributes (`x-schema-id` and `x-aspnetcore-id`) from the outgoing document.

In the long-term, I'd hope that this implementation will be further simplified by the new APIs that I am proposing in `Microsoft.OpenApi` to support a truly in-memory metadata collection in the OpenAPI object model (see https://github.com/microsoft/OpenAPI.NET/issues/1719). This should allow us to use the metadata collection for book-keeping without having to worry about omitting them from serialization ourselves.

### CODE REVIEW

File: src/OpenApi/test/Transformers/Implementations/OpenApiSchemaReferenceTransformerTests.cs [hunk 1]
```diff
@@ -289,4 +289,58 @@ public async Task TypeModifiedWithSchemaTransformerMapsToDifferentReferenceId()
...
+            //         "items": {
+            //           "$ref": "#/components/schemas/Todo"
+            //         }
+            //       }
+            //     }
+            //   }
+            // }
+
+            // Both list types should point to the same reference ID
+            Assert.Equal("ArrayOfTodo", requestBodySchema.Reference.Id);
```
Comment (BrennanConroy) [inline src/OpenApi/test/Transformers/Implementations/OpenApiSchemaReferenceTransformerTests.cs:337]: To test my understanding, this would have been `ArrayOfTodo2` in the buggy case?

**Review by BrennanConroy — APPROVED** [review]
