### PR TITLE
HttpSys log correct statuscode when application throws

### LINKED ISSUE #42218: Unhandled exception in request still logs `Request finished ... 200`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the HttpSys server, an unhandled exception from the request pipeline causes the logging to log "request finished with 200 OK", but the request returns the expected 500 to the browser.

This behavior is particularly bad when paired with application insights logging. The app insights logs contain a "successful" request telemetry, when this request actually failed.

Example Log:
```
...
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
fail: Microsoft.AspNetCore.Server.HttpSys.HttpSysListener[6]
      ProcessRequestAsync
      System.Exception: Exception of type 'System.Exception' was thrown.
         at aspnetrepro.Startup.<>c.<Configure>b__1_0(HttpContext ctx, Func`1 next) in D:\aspnetrepro\aspnet-bad-request-log\Program.cs:line 41
         at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
         at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
         at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
         at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 200 - - 39.6126ms
```

### Expected Behavior

All requests log the status code they actually return to the browser

### Steps To Reproduce

Clone this repo https://github.com/alexperovich/aspnet-bad-request-log, `dotnet run`, then open the browser.

### Exceptions (if any)

_No response_

### .NET Version

6.0.301

### Anything else?

vs and vscode

dotnet --info output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by campersau**
# HttpSys log correct statuscode when application throws

`application.DisposeContext` should be called after setting the status code when an application exception is thrown.
This is also mentioned in Kestrel:
https://github.com/dotnet/aspnetcore/blob/8897c2947e985fbfcea06ed67427dc10644024e0/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L728-L730

Fixes #42218

### CODE REVIEW

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs [hunk 1]
```diff
@@ -254,7 +254,6 @@ protected void SetFatalResponse(int status)
     {
         Response.StatusCode = status;
         Response.ContentLength = 0;
-        Dispose();
```
Comment (davidfowl) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:257]: Is this called from other places that are now not disposing the context?

Comment (campersau) [reply src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:257]: Yes, it is now called explicitly in all other places:
- https://github.com/dotnet/aspnetcore/pull/42223/files#diff-a78e961f758bf8f4f795410ae852718a6d31dec5599d398f12ffd4c58034d33eR35
- https://github.com/dotnet/aspnetcore/pull/42223/files#diff-a78e961f758bf8f4f795410ae852718a6d31dec5599d398f12ffd4c58034d33eR99

**Comment by JamesNK** [comment]
Can this be unit-tested? It's subtle behavior and easy to regress.

File: src/Servers/test/FunctionalTests/HelloWorldTest.cs [hunk 2]
```diff
@@ -108,4 +109,70 @@ public async Task HelloWorld(TestVariant variant)
...
+                    return deploymentResult.HttpClient.GetAsync("/throwexception");
+                }, logger, deploymentResult.HostShutdownToken))
+                {
+                    Assert.Equal(HttpStatusCode.InternalServerError, response.StatusCode);
+
+                    var body = await response.Content.ReadAsStringAsync();
+                    Assert.Empty(body);
+                }
+
+                await Task.Delay(50); // wait a bit for the server to finish the request
```
Comment (BrennanConroy) [inline src/Servers/test/FunctionalTests/HelloWorldTest.cs:171]: We try to avoid doing arbitrary delays like this. Slower machines or machines running lots of tests at once could need longer than 50ms.

Would shutting down the server and waiting for that to complete be a better alternative?

Comment (campersau) [reply src/Servers/test/FunctionalTests/HelloWorldTest.cs]: Thanks for the suggestion, yes that works.

File: src/Servers/test/FunctionalTests/HelloWorldTest.cs [hunk 3]
```diff
@@ -108,4 +109,68 @@ public async Task HelloWorld(TestVariant variant)
...
+            .WithAllArchitectures();
+
+    [ConditionalTheory]
+    [MemberData(nameof(SelfHostTestVariants))]
+    public async Task ApplicationException(TestVariant variant)
+    {
+        var testName = $"ApplicationException_{variant.Server}_{variant.Tfm}_{variant.Architecture}_{variant.ApplicationType}";
+        using (StartLog(out var loggerFactory,
+            variant.Server == ServerType.Nginx ? LogLevel.Trace : LogLevel.Debug, // https://github.com/aspnet/ServerTests/issues/144
+            testName))
```
Comment (Tratcher) [inline src/Servers/test/FunctionalTests/HelloWorldTest.cs:127]: Nginx isn't used for this test.
```suggestion
        using (StartLog(out var loggerFactory, LogLevel.Debug, testName))
```

File: src/Servers/test/FunctionalTests/HelloWorldTest.cs [hunk 4]
```diff
@@ -108,4 +109,68 @@ public async Task HelloWorld(TestVariant variant)
...
+            if (variant.Server == ServerType.Nginx)
+            {
+                deploymentParameters.ServerConfigTemplateContent = Helpers.GetNginxConfigContent("nginx.conf");
+            }
+
+            if (variant.Server == ServerType.IISExpress)
+            {
+                deploymentParameters.EnvironmentVariables[DebugEnvironmentVariable] = "console";
+            }
+
```
Comment (Tratcher) [inline src/Servers/test/FunctionalTests/HelloWorldTest.cs:145]: Not relevant to this test
```suggestion
```

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks
