### PR TITLE
Kestrel Content-Length handling changes

### LINKED ISSUE #42956: Fix Kestrel's Content-Length handling for 1xx, 204 and 205 responses and CONNECT requests
### Describe the bug

The spec forbids Content-Length headers on 1xx and 204 responses and on 2xx responses to CONNECT requests. Kestrel should not allow responses to violate this spec.

> A server MUST NOT send a Content-Length header field in any response with a status code of [1xx (Informational)](https://httpwg.org/specs/rfc7231.html#status.1xx) or [204 (No Content)](https://httpwg.org/specs/rfc7231.html#status.204). A server MUST NOT send a Content-Length header field in any [2xx (Successful)](https://httpwg.org/specs/rfc7231.html#status.2xx) response to a CONNECT request ([Section 4.3.6](https://httpwg.org/specs/rfc7231.html#CONNECT) of [[RFC7231]](https://httpwg.org/specs/rfc7230.html#RFC7231)).

https://httpwg.org/specs/rfc7230.html#rfc.section.3.3.2

Furthermore, Kestrel should reject non-zero Content-Length headers on 205 responses considering it disallows writing 205 responses with non-empty bodies and the spec requires this (or an empty chunked body or closing the connection but we use `Content-Length: 0` because it performs better):

> Since the 205 status code implies that no additional content will be provided, a server MUST NOT generate a payload in a 205 response. In other words, a server MUST do one of the following for a 205 response: a) indicate a zero-length body for the response by including a [Content-Length](https://httpwg.org/specs/rfc7230.html#header.content-length) header field with a value of 0; b) indicate a zero-length payload for the response by including a [Transfer-Encoding](https://httpwg.org/specs/rfc7230.html#header.transfer-encoding) header field with a value of chunked and a message body consisting of a single chunk of zero-length; or, c) close the connection immediately after sending the blank line terminating the header section.

https://httpwg.org/specs/rfc7231.html#rfc.section.6.3.6

https://github.com/dotnet/aspnetcore/blob/c2cba55ca149ab3bd3fadcf97b9d16a74f561111/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1305-L1310

But we also need to make sure that manually setting a non-zero Content-Lenth response header for any of the kinds of responses mentioned above (except 304s) fail since it can never be valid.

Prior discussion: https://github.com/dotnet/aspnetcore/issues/40882#issuecomment-1082247240 and https://github.com/microsoft/reverse-proxy/issues/1762.

### Expected Behavior

Kestrel should throw before flushing invalid Content-Length headers [like it already does for Transfer-Encoding](https://github.com/dotnet/aspnetcore/blob/c2cba55ca149ab3bd3fadcf97b9d16a74f561111/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1149-L1152).

Maybe just warning log is justified instead of throwing if the header was `Content-Lenth: 0` and it should have simply been omitted, but setting a non-zero Content-Length header on a response that doesn't allow it should always throw.

We need to be careful to still allow Content-Length headers for 304 responses since it is allowed even though it "SHOULD NOT" be generated.

> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a [200 (OK)](https://httpwg.org/specs/rfc7231.html#status.200) response to the same request: [Cache-Control](https://httpwg.org/specs/rfc7234.html#header.cache-control), [Content-Location](https://httpwg.org/specs/rfc7231.html#header.content-location), [Date](https://httpwg.org/specs/rfc7231.html#header.date), [ETag](https://httpwg.org/specs/rfc7232.html#header.etag), [Expires](https://httpwg.org/specs/rfc7234.html#header.expires), and [Vary](https://httpwg.org/specs/rfc7231.html#header.vary).
> 
> Since the goal of a 304 response is to minimize information transfer when the recipient already has one or more cached representations, a sender SHOULD NOT generate representation metadata other than the above listed fields unless said metadata exists for the purpose of guiding cache updates (e.g., [Last-Modified](https://httpwg.org/specs/rfc7232.html#header.last-modified) might be useful if the response does not have an [ETag](https://httpwg.org/specs/rfc7232.html#header.etag) field).

https://httpwg.org/specs/rfc7232.html#rfc.section.4.1

### PR DESCRIPTION
**Pull request by adityamandaleeka**
This includes two changes to how we handle Content-Length on responses:

- Forbid the inclusion of the Content-Length header on 1xx, 204 responses, or any 2xx responses to a CONNECT request.
- Forbid non-zero Content-Length for 205 responses.

Fixes https://github.com/dotnet/aspnetcore/issues/42956

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 1]
```diff
@@ -1219,6 +1233,28 @@ private HttpResponseHeaders CreateResponseHeaders(bool appCompleted)
...
+    private bool CanIncludeResponseContentLengthHeader()
+    {
+        // Section 4.3.6 of RFC7231
+        if (Is1xxCode(StatusCode) || StatusCode == StatusCodes.Status204NoContent)
+        {
+            // A server MUST NOT send a Content-Length header field in any response
+            // with a status code of 1xx (Informational) or 204 (No Content).
+            return false;
+        }
+        else if (Method == HttpMethod.Connect && Is2xxCode(StatusCode))
```
Comment (HaoK) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1245]: nit: single if with additional `|| (Method == HttpMethod.Connect && Is2xxCode(StatusCode))` ?

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs [hunk 2]
```diff
@@ -591,6 +591,160 @@ public async Task ContentLengthZeroSetOn205Response()
...
+    [InlineData(StatusCodes.Status205ResetContent)]
+    [InlineData(StatusCodes.Status206PartialContent)]
+    [InlineData(StatusCodes.Status207MultiStatus)]
+    [InlineData(StatusCodes.Status208AlreadyReported)]
+    [InlineData(StatusCodes.Status226IMUsed)]
+    public async Task AttemptingToWriteContentLengthFailsFor2xxResponsesOnConnect(int statusCode)
+    {
+        var responseWriteTcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
+
+        await using (var server = new TestServer(async httpContext =>
```
Comment (HaoK) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:679]: Is this test basically identical to AttemptingToWriteContentLengthFailsFor1xxAnd204Responses above except CONNECT is hardcoded instead of `{method}` in one place?  If so maybe we can have a helper to share, similar comment wit hAttemptingToWriteNonzeroContentLengthFailsFor205Response, seems like statusCode and method are the variables and everything else is the same?

**Review by HaoK — APPROVED** [review]
Looks good except some minor nits

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs (hunk 1 above)
Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1245]: Only if `Method == HttpMethod.Connect && Is2xxCode(StatusCode)` is moved to a local `Is2xxConnect()` local function or something. I don't like nested parens in conditions.

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs (hunk 2 above)
Comment (adityamandaleeka) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:649]: Deduplicated the first two tests. Left the nonzero content length one alone since it also has a different error message that it expects.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs (hunk 1 above)
Comment (adityamandaleeka) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1244]: Yea, I chose to do it this way because of readability (and it makes it clear which comments belong to each part). Will keep it as-is unless there's strong objection.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 3]
```diff
@@ -1219,6 +1232,28 @@ private HttpResponseHeaders CreateResponseHeaders(bool appCompleted)
...
+        {
+            // A server MUST NOT send a Content-Length header field in any 2xx
+            // (Successful) response to a CONNECT request.
+            return false;
+        }
+
+        return true;
+
+        static bool Is1xxCode(int code) => code >= StatusCodes.Status100Continue && code < StatusCodes.Status200OK;
+        static bool Is2xxCode(int code) => code >= StatusCodes.Status200OK && code < StatusCodes.Status300MultipleChoices;
```
Comment (gfoidl) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1254]:
```suggestion
        static bool Is1xxCode(int code) => code is >= StatusCodes.Status100Continue and < StatusCodes.Status200OK;
        static bool Is2xxCode(int code) => code is >= StatusCodes.Status200OK and < StatusCodes.Status300MultipleChoices;
```
Cf. https://github.com/dotnet/roslyn/issues/60534 -- Roslyn can produce optimized code with the pattern matching by using an `uint`-cast that saves one comparison at runtime. Hopefully this will be implemented soon 😉
