### PR TITLE
Made changes to FileBufferWriteStream

### LINKED ISSUE #21187: JsonResult with Newtonsoft.Json results in synchronous IO in large responses
### Describe the bug
I am utilizing [Ben.BlockingDetector](https://github.com/benaadams/Ben.BlockingDetector) package to identify and resolve any synchronous blockers in my app. I have found a scenario where my API is buffering the response to disk, which is resulting in a synchronous IO call.

The response data of the request is 62KB. I am returning a new `JsonResult(myObj)`. I've found when intentionally clearing one of the large properties on the response, it takes me down to 12KB and no buffering takes place. 

### To Reproduce
Enable Newtonsoft.Json for serialization and return a large object.
```
services
    .AddMvc()
    .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
    .AddNewtonsoftJson(delegate (MvcNewtonsoftJsonOptions op)
    {
        op.SerializerSettings.Converters.Add(new StringEnumConverter());
        op.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
    });
```

Create an endpoint (this returns ~65KB)
```
[HttpGet]
[AllowAnonymous]
[Route("/largeresponse")]
public IActionResult LargeResponse()
{
    return new JsonResult(new {d = Enumerable.Range(0, 150).Select(i => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." )});
}
```

Install [Ben.BlockingDetector](https://github.com/benaadams/Ben.BlockingDetector), and observe output.
```
      Blocking method has been invoked and blocked, this can lead to threadpool starvation.
         at System.Threading.Tasks.TplEventSource.TaskWaitBegin(Int32 OriginatingTaskSchedulerID, Int32 OriginatingTaskID, Int32 TaskID, TaskWaitBehavior Behavior, Int32 ContinueWithTaskID)
         at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
         at Microsoft.AspNetCore.WebUtilities.PagedByteBuffer.MoveTo(Stream stream)
         at Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternal(Boolean flushEncoder)
         at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(String value)
         at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
         at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
         at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
         at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
         at Microsoft.AspNetCore.Mvc.NewtonsoftJson.NewtonsoftJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
```

### Further technical details
```
C:\Users\timga>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- VS2019 16.4.2

I originally posted this issue in the BlockingDetector project.
https://github.com/benaadams/Ben.BlockingDetector/issues/14

### PR DESCRIPTION
**Pull request by davidfowl**
- Make the internal FileStream write only
- Make a new readable stream over the same file in DrainBufferAsync to copy data to the buffer.
- Added an overload to DrainBufferAsync into a PipeWriter and use this overload in the 2 formatters in MVC. This should reduce the amount of copying from the internal buffer and reduces pinning (since these buffers are already pinned)

Fixes #21187 

PS: I can split this PR into 2 commits so that the overloads are added in the second commit.

I haven't run any performance tests as yet (do we have any @pranavkm?)

### CODE REVIEW

**Comment by Tratcher** [comment]
MVC test failures for the affected callers: https://dev.azure.com/dnceng/public/_build/results?buildId=618468&view=ms.vss-test-web.build-test-results-tab&runId=19372370&resultId=112570&paneView=debug

**Review by Tratcher — APPROVED** [review]
Better. The tradeoff now is that anyone calling WriteAsync will block synchronously.

**Comment by pranavkm** [comment]
Can you send an email for the api-review please?

File: src/Http/WebUtilities/src/FileBufferingWriteStream.cs [hunk 1]
```diff
@@ -184,9 +186,31 @@ public async Task DrainBufferAsync(Stream destination, CancellationToken cancell
             // unspooled content. Copy the FileStream content first when available.
             if (FileStream != null)
             {
-                FileStream.Position = 0;
-                await FileStream.CopyToAsync(destination, cancellationToken);
+                // We make a new stream for async reads from disk and async writes to the destination
```
Comment (pranavkm) [inline src/Http/WebUtilities/src/FileBufferingWriteStream.cs:189]: `Fil
```suggestion
                // Using sync APIs on a `FileStream` initialized with `useAsync: true` results in poor performance. Consequently, we intiialize the `FileStream` instance without async and use a new stream for async reads from disk
```

**Review by pranavkm — APPROVED** [review]
I don't get the PipeStream changes, but :shipit:

File: src/Http/WebUtilities/src/FileBufferingWriteStream.cs [hunk 2]
```diff
@@ -184,9 +186,31 @@ public async Task DrainBufferAsync(Stream destination, CancellationToken cancell
...
+                await using var readStream = new FileStream(FileStream.Name, FileMode.Open, FileAccess.Read, FileShare.Delete | FileShare.ReadWrite, bufferSize: 1, useAsync: true);
 
+                await readStream.CopyToAsync(destination, cancellationToken);
+
+                // This is created with delete on close
+                await FileStream.DisposeAsync();
```
Comment (pentp) [inline src/Http/WebUtilities/src/FileBufferingWriteStream.cs:195]: You don't need to keep the original FileStream/handle open if you use delete-on-close - the read stream can use the file normally as long as it needs (the actual filesystem level deletion happens after all handles are closed). So this could be moved before CopyToAsync.

File: src/Http/WebUtilities/src/FileBufferingWriteStream.cs [hunk 3]
```diff
@@ -227,10 +251,10 @@ private void EnsureFileStream()
                 FileStream = new FileStream(
                     tempFileName,
                     FileMode.Create,
-                    FileAccess.ReadWrite,
-                    FileShare.Delete,
+                    FileAccess.Write,
+                    FileShare.Delete | FileShare.ReadWrite,
```
Comment (pentp) [inline src/Http/WebUtilities/src/FileBufferingWriteStream.cs:255]: Could use just `FileShare.Read` here to avoid the possibility of something modifying or deleting the file before the read stream is opened.

Comment (davidfowl) [reply src/Http/WebUtilities/src/FileBufferingWriteStream.cs:255]: I don't think that's a real concern but if that works sure.

File: src/Http/WebUtilities/src/FileBufferingWriteStream.cs (hunk 2 above)
Comment (davidfowl) [reply src/Http/WebUtilities/src/FileBufferingWriteStream.cs:195]: I left the behavior as it was.

Comment (davidfowl) [reply src/Http/WebUtilities/src/FileBufferingWriteStream.cs:195]: Ah I see what you're saying, does it matter though?

**Comment by davidfowl** [comment]
@pranavkm help me understand why this test is important: XmlSerializerOutputFormatterDoesntFlushOutputStream

File: src/Http/WebUtilities/src/FileBufferingWriteStream.cs (hunk 2 above)
Comment (pentp) [reply src/Http/WebUtilities/src/FileBufferingWriteStream.cs:195]: Not sure if it's important, but this would just release the object earlier and in case CopyToAsync throws the behavior would be different. But in that case neither the old or new logic is deterministic, so it probably doesn't matter.

**Comment by pranavkm** [comment]
It's trying to verify we do not write chunked responses to the output stream:  https://github.com/aspnet/Mvc/issues/958, https://github.com/aspnet/Mvc/issues/972, https://github.com/dotnet/aspnetcore/commit/e40dbcaebf7541ab5513412aa6405e2911f567b6.

**Comment by davidfowl** [comment]
> It's trying to verify we do not write chunked responses to the output stream: aspnet/Mvc#958, aspnet/Mvc#972, e40dbca.

So a couple of problems I see with these tests:
- Flushing != chunked encoding, if you flush before setting the content length then it will chunk
- Chunking is moot for HTTP/2

File: src/Mvc/Mvc.Formatters.Xml/test/XmlSerializerOutputFormatterTest.cs [hunk 4]
```diff
@@ -403,18 +403,20 @@ public void CanWriteResult_ReturnsExpectedValueForObjectType(object input, Type
...
             var outputFormatterContext = GetOutputFormatterContext(sampleInput, sampleInput.GetType());
 
             var response = outputFormatterContext.HttpContext.Response;
-            response.Body = FlushReportingStream.GetThrowingStream();
+            response.Body = Stream.Null;
 
             // Act & Assert
             await formatter.WriteAsync(outputFormatterContext);
+
+            Assert.NotNull(outputFormatterContext.HttpContext.Response.ContentLength);
```
Comment (pranavkm) [inline src/Mvc/Mvc.Formatters.Xml/test/XmlSerializerOutputFormatterTest.cs:419]: 👍

**Comment by Tratcher** [comment]
Patch candidate? We haven't found good workarounds.

**Comment by davidfowl** [comment]
Yep. I’ll have to make another change that doesn’t include the new API

**Comment by rynowak** [comment]
> It's trying to verify we do not write chunked responses to the output stream

I think it's actually verifying that we don't call the **sync** overload of flush and block. OR this is a test we don't need anymore. In the early days of project-k (last time someone worked on XML) the semantics of things changed often, so we had tests for a lot of micro-details like this.

**Comment by davidfowl** [comment]
> I think it's actually verifying that we don't call the sync overload of flush and block. OR this is a test we don't need anymore. In the early days of project-k (last time someone worked on XML) the semantics of things changed often, so we had tests for a lot of micro-details like this.

It throws for both Flush and FlushAsync.

**Comment by rynowak** [comment]
yeah we probably don't need the test anymore :)
