### PR TITLE
Fix URL building for SPA proxying

### LINKED ISSUE #31229: Hosting Multiple (React) SPAs in Asp.Net Core for development.
This might start off sounding like a general usage question; however there have been multiple SO posts that mention this topic in one way or another.

[Notable example #1](https://stackoverflow.com/questions/64013772/how-to-host-multiple-react-spa-apps-on-a-single-asp-net-core-site)

[Notable example #2](https://stackoverflow.com/questions/48216929/how-to-configure-asp-net-core-server-routing-for-multiple-spas-hosted-with-spase?noredirect=1&lq=1)

I also realize the tremendous amount of work it takes to handle more serious issues, so thank you for reading.

I am simply attempting to figure out how to host multiple (in this case, React) SPA's using either `App.UseProxyToSpaDevelopmentServer` or `App.UseReactDevelopmentServer` for development.

Previously, I worked together a solution of building (`npm run build`) each SPA and constructing a custom StaticFilesProvider that would serve them up. Obviously this build process takes quite a while and I would like to be able to use something like `App.UseProxyToSpaDevelopmentServer` to take advantage of hot-reloading, etc.

I have put together a basic demo repo that illustrates the problem I am experiencing. It is linked at the bottom of this ticket.

For clarity, here is my Startup.cs class:

```cs
public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
   
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseRouting();
            
            app.Map("/spa1", spa1 =>
            {
                if (env.IsDevelopment())
                {
                    spa1.UseSpa(spa =>
                    {         
                        spa.Options.SourcePath = Path.Join(env.ContentRootPath, "spa1");
                        spa.UseProxyToSpaDevelopmentServer("http://localhost:3001/");
                    });
                }
            });

            app.Map("/spa2", spa2 =>
            {
                if (env.IsDevelopment())
                {
                    spa2.UseSpa(spa =>
                    {         
                        spa.Options.SourcePath = Path.Join(env.ContentRootPath, "spa2");
                        spa.UseProxyToSpaDevelopmentServer("http://localhost:3002/");
                    });
                }
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
            });
        }
    }
```

When I use `UseProxyToSpaDevelopmentServer`, I start my SPAs separately (on port 3001 and 3002 for /spa1 and /spa2 respectively). I then start my .NET app, which boots as normal. I then navigate to the desired SPA endpoint (say `http://localhost:5001/spa1`). When inspecting the browser, I see that my static content (I.e.,`https://localhost:5001/spa1/static/js/bundle.js `) all have 200 status codes, but there are MIME type errors printed out to the console:
> The script from “https://localhost:5001/spa1/static/js/bundle.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.

[Here is a link to the reproduce repo](https://github.com/spencer741/HostingMultipleReactAspNetCore)

It *feels* like I am just overlooking something; however, if I am not, perhaps this is something that could be further documented? (I wouldn't mind at all helping with that process if needed).

Thanks again for all of the work making awesome open source software!

### PR DESCRIPTION
**Pull request by varsi94**
# Fix URL building for SPA proxying

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Fix URL building when proxying to a host where the SPA is not on the root URL

## Description

If the SPA proxy is not listening on the root url (e.g. http://localhost:3000/spa), then the path segments are ignored when sending the request to the development server. This path segment is prepended to the URL, if there's any.

Fixes #31229

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck please talk to Javier about this if you have any questions, and then review this PR. Thanks!

**Comment by Tratcher** [comment]
Want to fix https://github.com/dotnet/aspnetcore/issues/43662 while you're at it? It's likely on the same line.

**Comment by varsi94** [comment]
@Tratcher Fixed #43662 as well.

File: src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs [hunk 1]
```diff
@@ -70,7 +70,7 @@ public static HttpClient CreateHttpClientForProxy(TimeSpan requestTimeout)
         var baseUri = await baseUriTask;
         var targetUri = new Uri(
             baseUri,
-            context.Request.Path + context.Request.QueryString);
+            "/" + (baseUri.AbsolutePath + context.Request.Path).TrimStart('/') + context.Request.QueryString);
```
Comment (Tratcher) [inline src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs:73]: Sorry, Trim wasn't the solution recommended in the issue, that would remove multipe slashes and not preserve the user intent.

> A period . needs to be prefixed to the relative URI to avoid this behaviour.

I didn't realize there was a competing PR here https://github.com/dotnet/aspnetcore/pull/43663/files. They were going to conflict regardless. You can revert to your original fix and we'll sort it out on the other PR.

Comment (varsi94) [reply src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs:73]: @Tratcher that PR would also fix #31229 if the base URL has a slash as a suffix like:
`spa.UseProxyToSpaDevelopmentServer("http://localhost:3001/spa/");`

If we want to support the case when the URL is given like without the slash at the end (http://localhost:3001/spa), then we should go with this:
```csharp
        var targetUri = new Uri(
            baseUri.ToString().EndsWith("/") ? baseUri : new Uri(baseUri + "/"),
            "." + context.Request.Path + context.Request.QueryString);
```

**Comment by Tratcher** [comment]
@MackinnonBuck can you do some manual testing for both of these bugs? It doesn't look like there's any automated tests for this.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43407) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43407) before we can accept your contribution.<br/><br/>:x: varsi94 [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43407)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=43407) it.</sub>

**Comment by varsi94** [comment]
> @MackinnonBuck can you do some manual testing for both of these bugs? It doesn't look like there's any automated tests for this.

I have added some, you can check. @MackinnonBuck  @Tratcher

File: src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs [hunk 2]
```diff
@@ -68,9 +68,10 @@ public static HttpClient CreateHttpClientForProxy(TimeSpan requestTimeout)
         // when proxying to Angular CLI middleware: we won't know what port it's listening
         // on until it finishes starting up.
         var baseUri = await baseUriTask;
-        var targetUri = new Uri(
-            baseUri,
-            context.Request.Path + context.Request.QueryString);
+        var targetUri = new Uri(baseUri,
+			baseUri.AbsoluteUri
+			+ (baseUri.AbsoluteUri.EndsWith("/", StringComparison.OrdinalIgnoreCase) ? context.Request.Path.ToString().Substring(1) : context.Request.Path)
```
Comment (MackinnonBuck) [inline src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs:73]: What happens if `context.Request.Path` is empty? Can we add a test case for that?

Would it work to just trim the trailing "/" characters off the end of `baseUri.AbsoluteUri`, since `context.Request.Path` is [guaranteed](https://github.com/dotnet/aspnetcore/blob/8eadd8f7e2b46387ea6f121a8d9f9bf003cf3f2c/src/Http/Http.Abstractions/src/PathString.cs#L35) to start with a `/` if it's non-empty?

**Review by MackinnonBuck — COMMENTED** [review]
Just now getting to this - I have one piece of feedback but otherwise it looks great!

Thanks for your contribution @varsi94!

File: src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs (hunk 2 above)
Comment (MackinnonBuck) [reply src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs:73]: Also, can we use the `Uri` constructor overload that takes a single URI string? It looks like we're treating the `relativeUri` parameter as the base URI anyway.

Comment (varsi94) [reply src/Middleware/Spa/SpaServices.Extensions/src/Proxying/SpaProxy.cs]: @MackinnonBuck Good catch! I have made these changes, thanks for the feedback.

**Review by MackinnonBuck — APPROVED** [review]
🎉
