### PR TITLE
Better implementation of EventCallback.Equals

### LINKED ISSUE #53361: EventCallback.Equals is not giving correct results
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We noticed after upgrading our blazor application to .net 8.0 that some EventCallback keep being modified. Eventhough the value was the same, the same target component, the same method.
The generated code that renders the component seems to fabricate a new MulticastDelegate, having the same Type, Target and Method. The implementation of EventCallback uses Object.ReferenceEquals, so it concludes it is different every render. 
 

### Expected Behavior

The component should see EventCallbacks as equal when the delegate and Target are the same. MulticastDelegate has the Equals method overridden, so use that instead of ReferenceEquals.

### Steps To Reproduce

I will make a PR with a fix

### Exceptions (if any)

_No response_

### .NET Version

8.0.101

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JelleHissink**
We noticed after upgrading our blazor application to .net 8.0 that some EventCallback keep being modified. Eventhough the value was the same, the same target component, the same method.

The generated code that renders the component seems to fabricate a new MulticastDelegate, having the same Type, Target and Method. The implementation of EventCallback uses Object.ReferenceEquals, so it concludes it is different every render.

Fixes https://github.com/dotnet/aspnetcore/issues/53361

# NOTE
I recreated this because I have some difficulties changing the pr to go to main (#53362)

### CODE REVIEW

**Comment by JelleHissink** [comment]
I did not manage to get the whole testsuite running on my machine. If there is somebody else who could take this on that would be great.

File: src/Components/Components/src/EventCallback.cs [hunk 1]
```diff
@@ -80,5 +80,5 @@ public override int GetHashCode()
     public override bool Equals(object? obj)
         => obj is EventCallback other
         && ReferenceEquals(Receiver, other.Receiver)
-        && ReferenceEquals(Delegate, other.Delegate);
+        && (Delegate?.Equals(other.Delegate) ?? (other.Delegate == null));
```
Comment (huoyaoyuan) [inline src/Components/Components/src/EventCallback.cs:83]: `object.Equals(a, b)` performs null handling and delegates to `a.Equals(b)`.

**Review by javiercn — APPROVED** [review]

**Comment by JelleHissink** [comment]
Thanks for picking this up!
