### PR TITLE
Do not generate Content for request parameters in OpenAPI

### LINKED ISSUE #45365: [Minimal API] Incorrect OpenAPI definition of path, query and header parameters when there is a body and we're using WithOpenApi extension method
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This problem is related to https://github.com/dotnet/aspnetcore/issues/45305, but I have opened a new issue because I have identified a more generic scenario that involves it.

Let's consider the following endpoint:

```
app.MapPost("/api/sample/{id:guid}", (string id, [FromHeader] int number, bool boolean, Input input) =>
{
    return TypedResults.Ok();
});

public record class Input(Guid id, int Number);
```

This produces a **swagger.json** definition that contains, among the others:

```
{
  "name": "id",
  "in": "path",
  "required": true,
  "style": "simple",
  "schema": {
    "type": "string"
  }
}
```

If, however, I add the `WithOpenApi` extension method to the endpoint, **swagger.json** becomes:

```
{
  "name": "id",
  "in": "path",
  "required": true,
  "style": "simple",
  "schema": {
    "type": "string"
  },
  "content": {
    "application/json": { }
  }
}
```

A new section **content** has been inserted in the definition, and it totally messes the documentation. This happens only if the endpoint contains also a body parameter. The only solution I have found is to create an `OperationFilter` that manually resets the `Content` property:

```
internal class ResetContentOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (operation.Parameters?.Any() ?? false)
        {
            foreach (var parameter in operation.Parameters)
            {
                if (parameter.In is ParameterLocation.Query or ParameterLocation.Path or ParameterLocation.Header)
                {
                    parameter.Content = null;
                }
            }
        }
    }
}
```

### Expected Behavior

**content** section should not be added to path, query and header parameters definition if I have an endpoint that contains also a body parameter and I'm using the `WithOpenApi` extension method.

### Steps To Reproduce

Minimal repro here: https://github.com/marcominerva/OpenApiParameterIssue.

### Exceptions (if any)

_No response_

### .NET Version

7.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/45365.

OpenAPI parameters source from the route/query/header do not need to have the `Content` property defined as long as a `Schema` is generated. In this case, the schema is generated in Swashbuckle so we don't need to produce content attributes for them. This fix is a backport candidate.

cc: @marcominerva

### CODE REVIEW

File: src/OpenApi/src/OpenApiGenerator.cs [hunk 1]
```diff
@@ -384,7 +384,6 @@ private List<OpenApiParameter> GetOpenApiParameters(MethodInfo methodInfo, Endpo
             {
                 Name = name,
                 In = parameterLocation,
-                Content = GetOpenApiParameterContent(metadata),
```
Comment (halter73) [inline src/OpenApi/src/OpenApiGenerator.cs:387]: Is the idea that endpoint `IAcceptsMetadata` should only influence the `RequestBody` and never any `Parameters`?

Adding the same `Content` to all parameters seems bad, but it seems odd that no `OpenApiParameter` ever has any `Content`. It kind of makes sense because there's no `ParameterLocation` for the body and `OpenApiRequestBody` exists, but then what's the purpose of  `OpenApiParameter.Content`?

**Review by halter73 — APPROVED** [review]

File: src/OpenApi/src/OpenApiGenerator.cs (hunk 1 above)
Comment (captainsafia) [reply src/OpenApi/src/OpenApiGenerator.cs:387]: > Edit. I found a sample. It seems like it's if you actually want to do something like accept json in a query string. Weird.

Chatted with @baywet about this. So for 99% of scenarios, the formats that are available for parameters sourced from routes/headers/etc. are going to be described by the `style` and `explode` property (see [this](https://swagger.io/docs/specification/serialization/)).

`Content` is really meant to describe inputs/outputs that are more suited to serialization (request body and response) but is reused here for the 1% of scenarios where people are defining some custom serialization, like the example you shared with queries that look like `?coordiantes={lat:45,long:46}`. For those scenarios, it probably makes sense to have users describe that specification themselves.

Most importantly, it looks like producing this content for the scenarios where it is _not_ needed causes a buggy path in the Swagger UI that causes hangs if you send certain types of inputs through. :/
