### PR TITLE
[Blazor][Fixes #8003] Improves reconnects when the client doesn't perform graceful disconnects

### LINKED ISSUE #8003: Allow robust reconnects when client do not perform graceful disconnects
The renderer goes in a “buffering” mode when the client disconnects and spits it back out once it reconnects. In the most common case where the client has a transient network failure, this is what it would look like:

 ```txt
Connection
    | Send diff 1
    | Send diff 2
    | Send diff 3
Disconnected (client network error)
    | Send diff 4
    | Send diff 5
SignalR OnDisconnected is executed
   | Buffer diff 6 
Client reconnected
   | Send diff 6
   | Send diff 7
 ```

SignalR \ Kestrel do not complain if a websocket send failed due to a client error. Consequently, there will be a gap where the server thinks it successfully sent the diffs to the client, but it ended up in the ether. 
 
The fix for this will be that we're going to queue the render batches on the server, and hold onto them until the client can `ACK` each one.

### PR DESCRIPTION
**Pull request by javiercn**
* Allows the server to accept acks with a higher sequence number than
  the first queued pending render and caches up to it.
* Makes the client send acks for previous render batches.
* Makes the client repeat acks for errored render batches if it keeps
  receiving new render batches.
* Client awaits sending acks to ensure that they get send in order.

### CODE REVIEW

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 1]
```diff
@@ -5,6 +5,7 @@
 using System.Collections.Concurrent;
 using System.IO;
 using System.Linq;
+using System.Security.Cryptography.Xml;
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: ???

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 2]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
                 return;
             }
 
+            // When clients send acks we know for sure they received and applied the batch.
+            // We send batches right away, and queue them until we receive an ACK.
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
            // We send batches right away, and hold them in memory until we receive an ACK.
```

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 3]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // If one or more client ACKs get lost we might receive an ack for a higher batch.
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
            // If one or more client ACKs get lost (e.g., with long polling, client->server delivery is not guaranteed) we might receive an ack for a higher batch.
```

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 4]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // We confirm all previous batches at that point (because receiving an ack is guarantee
+            // from the client that it has received and successfully applied all batches up to that point).
+
+            // If receive an ack for a previously rendered batch, its an error, as the messages are
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
            // If receive an ack for a previously acknowledged batch, its an error, as the messages are
```

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 5]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // guranteed to be delivered in order, so a message for a render batch of 2 will never arrive
+            // after a message for a render batch for 3.
+            // If that were to be the case, it would just be enough to relax the checks here and simply skip
+            // the message.
+
+            // A batch might get lost when we send it to the client. If the client receives a newer batch when
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
            // A batch might get lost when we send it to the client, because the client might disconnect before receiving and processing it.
            // In this case, once it reconnects the server will re-send any unacknowledged batches, some of which the
            // client might have received and even believe it did send back an acknowledgement for. The client handles
            // those by re-acknowledging.
```

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 6]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // it was expecting a previous batch, it can simply force a reconnection.
+
             // Even though we're not on the renderer sync context here, it's safe to assume ordered execution of the following
             // line (i.e., matching the order in which we received batch completion messages) based on the fact that SignalR
             // synchronizes calls to hub methods. That is, it won't issue more than one call to this method from the same hub
             // at the same time on different threads.
-            if (!PendingRenderBatches.TryDequeue(out var entry) || entry.BatchId != incomingBatchId)
+            if (!PendingRenderBatches.TryPeek(out var entry) || incomingBatchId < entry.BatchId)
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: What do you think about renaming the `PendingRenderBatches` queue to `UnacknowledgedRenderBatches`?

I think that does match its actual purpose and is a lot clearer (because if they are just "pending", what aspect of them is "pending" - sending, processing, acknowledgement?)

Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]:
```suggestion
            if (!PendingRenderBatches.TryPeek(out var nextUnacknowledgedBatch) || incomingBatchId < nextUnacknowledgedBatch.BatchId)
```

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 7]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
             {
                 HandleException(
                     new InvalidOperationException($"Received a notification for a rendered batch when not expecting it. Batch id '{incomingBatchId}'."));
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Is the following message more precise?

```suggestion
                    new InvalidOperationException($"Received a duplicate ACK for batch id '{incomingBatchId}'."));
```

If this statement does match the scenario, let's go for the more informative message.

And do you agree there's no possible *legitimate* scenario where a server receives a duplicate ACK? I'm struggling to think of a proof that the server can't receive a duplicate ACK, given that the client will ACK as many times as the server re-sends. For this to be robust, we're relying on guaranteed ordering of delivery not just within one SignalR connection but across successive connections established around reconnection.

If we're unable to reason precisely about this, let's consider just no-opping if we receive a duplicate ACK. We know it doesn't leave either side of the wire in a bad state.

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Also, should the exception type be whatever special internal exception type means "this can be triggered by bad external input so only log it as debug"?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 8]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+                    ProcessPendingBatch(errorMessageOrNull, entry);
                 }
-                else
+
+                if (lastBatchId < incomingBatchId)
                 {
-                    Log.CompletingBatchWithError(_logger, entry.BatchId, errorMessageOrNull);
+                    Log.ReceivedUnexpectedBatchId(_logger, incomingBatchId, lastBatchId);
+                    HandleException(
+                        new InvalidOperationException($"Received an acknowledgement for batch with id '{incomingBatchId}' when the last batch produced was '{lastBatchId}'."));
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Also should be logged as debug, I think

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: In fact, is it enough to let `HandleException` log it? This will give us two log entries, won't it?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 9]
```diff
@@ -203,28 +204,62 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
             else
             {
-                if (errorMessageOrNull == null)
+                var lastBatchId = entry.BatchId;
+                // Order is important here so that we don't prematurely dequeue the last entry
+                while (PendingRenderBatches.TryPeek(out entry) && entry.BatchId <= incomingBatchId)
                 {
-                    Log.CompletingBatchWithoutError(_logger, entry.BatchId);
+                    lastBatchId = entry.BatchId;
+                    PendingRenderBatches.TryDequeue(out _);
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Nit: this is a bit funky. Could this become:

```suggestion
                    entry = PendingRenderBatches.Dequeue();
```

... since we know there's a value there (no need to `Try...`), and also change L235 to `TryPeek` into a temporary variable instead of overwriting `entry`? That way we know we're only overwriting `entry` with things we actually want to process and don't need to take an extra step to update the state of the queue.

File: src/Components/Web.JS/src/Platform/Circuits/RenderQueue.ts [hunk 10]
```diff
@@ -8,6 +8,8 @@ export default class RenderQueue {
 
   private nextBatchId = 2;
 
+  private lastError?: string;
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Platform/Circuits/RenderQueue.ts]: Consider renaming to `fatalError` since it's not tracking "the most recent" error but rather just one.

File: src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs [hunk 11]
```diff
@@ -445,7 +445,7 @@ public async Task DispatchingEventsWithInvalidEventHandlerId()
             Assert.Contains(
                 logEvents,
                 e => e.eventIdName == "DispatchEventFailedToDispatchEvent" && e.logLevel == LogLevel.Debug &&
-                     e.exception is ArgumentException ae && ae.Message.Contains("There is no event handler with ID -1"));
+                     e.exception is ArgumentException ae && ae.Message.Contains("There is no event handler with ID 1"));
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs]: I'm unsure why this is changing. Could you clarify?

Comment (SteveSandersonMS) [reply src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs]: Oh wait I guess it's my fault after the switch to `ulong`, but I did run all the E2E tests locally. Any idea why it's failing for you now but didn't for me before?

**Review by SteveSandersonMS — COMMENTED** [review]
This looks good, but really hard to be sure about E2E correctness. I guess we're already doing the best we can to simulate these scenarios in unit tests.

Hope you don't mind the big slew of suggestions of changes to comments. It's because the scenarios are very subtle and I'm trying to be sure we're making it as obvious as possible to our future selves based on what we're thinking right now.

I posted a couple of questions too, but I think this is pretty close to being ready to go already!

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: This is visual studio autonamespace complete thingy that leaves garbage all over the place. I'll remove.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Agree. Will do

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 7 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: There are a bunch of places where we need to do that, so I'm not trying to tackle it as part of this PR. I want to go through the code-base and find all the places this happens.

If we decide to NOOP (which i'm ok with) then we don't need to use a special exception here.

Overall, this space is a "nightmare" to reason about.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: ConcurrentQueue doesn't have a Dequeue method.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 8 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Yep, but we want to terminate the circuit, and I want to do that change as part of the warning cleanups change. We might be able to get rid of the log statement.

File: src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs (hunk 11 above)
Comment (javiercn) [reply src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs]: Likely because I put this change on the dependency update PR, because fixing the breaking changes from extensions in there was more cumbersome, when the PR for that was already signed off.

We didn't catch it because the PR got rebased and we don't run E2E tests on the CI :(

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 12]
```diff
@@ -208,39 +208,64 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // those by re-acknowledging.
+            // it was expecting a previous batch, it can simply force a reconnection.
+
             // Even though we're not on the renderer sync context here, it's safe to assume ordered execution of the following
             // line (i.e., matching the order in which we received batch completion messages) based on the fact that SignalR
             // synchronizes calls to hub methods. That is, it won't issue more than one call to this method from the same hub
             // at the same time on different threads.
-            if (!PendingRenderBatches.TryDequeue(out var entry))
+
+            if (!PendingRenderBatches.TryPeek(out var nextUnacknowledgedBatch) || incomingBatchId < nextUnacknowledgedBatch.BatchId)
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Do we need to special case when TryPeek returns false, but the batch id is larger than the next batch id we would generate? Is that the same as going out of sync?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (pranavkm) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Does this run in the sync context? If not, this isn't thread safe.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 13]
```diff
@@ -208,39 +208,64 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
             {
-                HandleException(
-                    new InvalidOperationException($"Received a notification for a rendered batch when not expecting it. Batch id '{incomingBatchId}'."));
+                Log.ReceivedDuplicateBatchAck(_logger, incomingBatchId);
             }
             else
             {
-                entry.Data.Dispose();
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Where did this go?

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: I don't think it does. But its easy to change and probably more correct. @SteveSandersonMS are you ok if we put the call to OnRenderCompleted inside the sync context?

File: src/Components/Web.JS/src/Platform/Circuits/RenderQueue.ts (hunk 10 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Platform/Circuits/RenderQueue.ts]: done

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 12 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: It's impossible to know unless we keep track of the last batch id that was acknowledged on the class.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: I thought we needed this because we were dequeuing the entry before we could know we could get rid of it. Is that not the case?

Shouldn't we have a test for this? I ran all the tests and nothing failed 😕

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Actually, read the comment above

            // Even though we're not on the renderer sync context here, it's safe to assume ordered execution of the following
            // line (i.e., matching the order in which we received batch completion messages) based on the fact that SignalR
            // synchronizes calls to hub methods. That is, it won't issue more than one call to this method from the same hub
            // at the same time on different threads.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 12 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: I'm happy with how things are right now.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: I re-added the check

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: I think we can change this to be a simple queue, but don't want to do it right now. Is that ok? we can file an issue and do it later.

**Comment by javiercn** [comment]
> Hope you don't mind the big slew of suggestions of changes to comments. It's because the scenarios are very subtle and I'm trying to be sure we're making it as obvious as possible to our future selves based on what we're thinking right now.

I appreciate it! It takes extra effort sometimes to find the right words when its not your mother tongue, so I'm happy about all suggestions 😄

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 9 above)
Comment (pranavkm) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: Ahh, SignalR's sync context 👍. That would help

**Review by pranavkm — APPROVED** [review]

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 14]
```diff
@@ -208,39 +208,65 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
...
+            // guranteed to be delivered in order, so a message for a render batch of 2 will never arrive
+            // after a message for a render batch for 3.
+            // If that were to be the case, it would just be enough to relax the checks here and simply skip
+            // the message.
+
+            // A batch might get lost when we send it to the client, because the client might disconnect before receiving and processing it.
+            // In this case, once it reconnects the server will re-send any unacknowledged batches, some of which the
+            // client might have received and even believe it did send back an acknowledgement for. The client handles
+            // those by re-acknowledging.
+            // it was expecting a previous batch, it can simply force a reconnection.
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: L277 is left over from an earlier version of this comment block and can be removed

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 15]
```diff
@@ -208,39 +208,65 @@ public void OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
                 return;
             }
 
+            // When clients send acks we know for sure they received and applied the batch.
+            // We send batches right away, and hold them in memory until we receive an ACK.
+            // If one or more client ACKs get lost (e.g., with long polling, client->server delivery is not guaranteed) we might receive an ack for a higher batch.
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Nit: long line (though please only fix if you're fixing other stuff here too)

**Review by SteveSandersonMS — APPROVED** [review]
Great!

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 14 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: done

File: src/Components/Server/src/Circuits/RemoteRenderer.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/RemoteRenderer.cs]: done

**Comment by javiercn** [comment]
@aspnet/build code check keeps failing even though blazor.server.js is up to date. Can you assist here?

**Comment by SteveSandersonMS** [comment]
When I was in that situation, I found I had to rebuild SignalR’s JS client before rebuilding Web.JS. Or at least that seemed to work one time - not claiming it’s always the fix!

**Comment by javiercn** [comment]
> When I was in that situation, I found I had to rebuild SignalR’s JS client before rebuilding Web.JS. Or at least that seemed to work one time - not claiming it’s always the fix!

Thanks! that got it past it
