### PR TITLE
Make TLS & QUIC Pay-for-Play (Redux)

### LINKED ISSUE #46681: Reduce the size cost of unused protocol support
We know there are use cases for Kestrel where things like HTTP/2 or /3, or even HTTPS, aren't necessary. For instance, you may not want HTTPS for a server that's run behind a TLS-terminated proxy.

Today, a published app that doesn't use TLS still carries around some extra dependencies that are used only for TLS support. We should explore what we can do to minimize this cost.

### LINKED ISSUE #47567: Introduce trim-friendly APIs for controlling HTTPS Configuration support
## Background and Motivation

Not being able to trim HTTPS and QUIC support from apps that don't use them causes a very large size increase (~1MB on Windows and ~4MB on Linux).  To be able to prove to the trim analyzer that they're not used, we need new code paths that statically do or do not reference the code we want to trim.

Context: #46681.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace Microsoft.AspNetCore.Hosting;

public static class WebHostBuilderKestrelExtensions
{
+    /// <summary>
+    /// In <see cref="UseKestrelSlim(IWebHostBuilder)"/> scenarios, it may be necessary to explicitly
+    /// opt in to certain HTTPS functionality.  For example, if <code>ASPNETCORE_URLS</code> includes
+    /// an <code>https://</code> address, <see cref="UseHttpsConfiguration"/> will enable configuration
+    /// of HTTPS on that endpoint.
+    ///
+    /// Has no effect in <see cref="UseKestrel(IWebHostBuilder)"/> scenarios.
+    /// </summary>
+    public static IWebHostBuilder UseHttpsConfiguration(this IWebHostBuilder hostBuilder)

+    /// <summary>
+    /// Specify Kestrel as the server to be used by the web host.
+    /// Includes less automatic functionality <see cref="UseKestrel(IWebHostBuilder)"/> to make trimming more effective
+    /// (e.g. for Native AOT scenarios).  If the host ends up depending on some of the absent functionality, a best-effort
+    /// attempt will be made to enable it on-demand.  Failing that, an instructive error will be reported.
+    /// </summary>
+    public static IWebHostBuilder UseKestrelCore(this IWebHostBuilder hostBuilder)
+    public static IWebHostBuilder UseKestrelCore(this IWebHostBuilder hostBuilder, Action<KestrelServerOptions> options)
+    public static IWebHostBuilder UseKestrelCore(this IWebHostBuilder hostBuilder, Action<WebHostBuilderContext, KestrelServerOptions> configureOptions)
}
```

Note that the corresponding method for opting in to quic support already exists.

```diff
namespace Microsoft.AspNetCore.Hosting;

public static class WebHostBuilderQuicExtensions
{
    public static IWebHostBuilder UseQuic(this IWebHostBuilder hostBuilder)
}
```

## Usage Examples

```csharp
var builder = WebApplication.CreateSlimBuilder(args); // Calls UseKestrelCore
builder.WebHost.UseHttpsConfiguration();
builder.WebHost.UseQuic();
```

## Alternative Designs

Another approach would be to disable _more_ things to make the behavior clearer.
For example, we could disable _all_ HTTPS functionality and call this API `UseHttps` (or similar).
We decided against doing this since our goal was not to provide guard rails but to improve trimming.
Instead, we make needing to call `UseHttpsConfiguration` as rare as possible (by calling it ourselves, when possible).

## Risks

The phrase "https configuration" has no intuitive meaning and the comments barely clarify.
This was by-design, since few users should need to call it and they should be prompted to do so by specialized error messages.
There is a risk that, not understanding its purpose, people will call it "just in case", hurting trimming perf.

The "core" in "UseKestrelCore" isn't related to either .NET Core or ASP.NET Core, which could cause some confusion.

### PR DESCRIPTION
**Pull request by amcasey**
Based on the feedback on #47209, I've prepared this substantially different approach.  Whereas #47209 focuses on providing a describable set of restrictions and guardrails to prevent their violation, this PR focuses on making a best effort to improve trimmed size while breaking as few scenarios as possible.

What's disabled when you create a slim builder?  You'll find out at bind-time if you crossed the line and a helpful error message will tell you the one-liner (either `IWebHostBuilder.UseHttpsConfiguration` or `IWebHostBuilder.UseQuic`) to add to fix it.  What does that mean, in practice?  Kestrel won't call `UseHttps` on your behalf - in particular, setting your URL to `https` won't "just work" - and there won't be any QUIC transports.

Presently, `IWebHostBuilder.UseQuic` doesn't imply `IWebHostBuilder.UseHttpsConfiguration`, but it could if we're willing to slightly clutter the public API (i.e. with a marker service in Connection.Abstractions).

There are exactly two new DI services, both internal:
1. `IHttpsConfigurationHelper` is always present, but throws until it is explicitly enabled.
2. `IEnabler` is a declarative way to enable `IHttpsConfigurationHelper` (vs a method call).  I suspect there's a better way to do this in DI, but I'm not familiar enough with the available APIs.

There are two new public APIs (plus overloads):
1. `UseKestrelSlim` (name TBD) doesn't call `UseQuic` or `IHttpsConfigurationHelper.Enable`.
2. `UseHttpsConfiguration` (effectively) calls `IHttpsConfiguration.Enable`.

I have more validation to do, but the trimmed size is as in #47209 and the tests pass.

Fixes #47567 
Fixes #46681

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @halter73 @JamesNK This potentially replaces #47209.  I believe it incorporates the feedback provided on that PR.

File: src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Security.Cryptography.X509Certificates;
+using Microsoft.AspNetCore.Server.Kestrel.Core.Internal;
+using Microsoft.AspNetCore.Server.Kestrel.Https;
+
+namespace Microsoft.AspNetCore.Server.Kestrel.Core;
+
+internal interface ITlsConfigurationLoader
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs:10]: This could be flattened into `IHttpsConfigurationHelper`, if that seems more consistent.

File: src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs [hunk 2]
```diff
@@ -55,6 +55,11 @@ public HttpsConnectionAdapterOptions()
     /// </summary>
     public Func<ConnectionContext?, string?, X509Certificate2?>? ServerCertificateSelector { get; set; }
 
+    /// <summary>
+    /// Convenient shorthand for a common check.
+    /// </summary>
+    internal bool HasServerCertificateOrSelector => ServerCertificate is not null || ServerCertificateSelector is not null;
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs:61]: This is unrelated, it just tidied up a bunch of checks.

File: src/DefaultBuilder/src/WebHost.cs [hunk 3]
```diff
@@ -235,7 +235,7 @@ internal static void ConfigureWebDefaults(IWebHostBuilder builder)
 
     internal static void ConfigureWebDefaultsCore(IWebHostBuilder builder, Action<IServiceCollection>? configureRouting = null)
     {
-        builder.UseKestrel((builderContext, options) =>
+        builder.UseKestrelSlim((builderContext, options) =>
```
Comment (amcasey) [inline src/DefaultBuilder/src/WebHost.cs:238]: This time, I added all the overloads of `UseKestrelSlim`.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 4]
```diff
@@ -163,35 +163,22 @@ public static ListenOptions UseHttps(this ListenOptions listenOptions, Action<Ht
     {
         ArgumentNullException.ThrowIfNull(configureOptions);
 
+        // We consider calls to `UseHttps` to be a clear expression of user intent to pull in HTTPS configuration support
+        listenOptions.KestrelServerOptions.EnableHttpsConfiguration();
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:167]: Note that I _didn't_ do this for the overloads below that explicitly say they don't consume/respect configuration.

File: src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+using Microsoft.AspNetCore.Server.Kestrel.Core.Internal;
+using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates;
+using Microsoft.AspNetCore.Server.Kestrel.Https;
+using Microsoft.AspNetCore.Server.Kestrel.Https.Internal;
+using Microsoft.Extensions.Hosting;
+using Microsoft.Extensions.Logging;
+
+namespace Microsoft.AspNetCore.Server.Kestrel.Core;
+
+internal sealed class TlsConfigurationLoader : ITlsConfigurationLoader
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs:18]: I believe this is unmodified from the first PR.

File: src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+        }
+        public override CancellationToken ConnectionClosed
+        {
+            get => _inner.ConnectionClosed;
+            set => _inner.ConnectionClosed = value;
+        }
+        public override ValueTask DisposeAsync() => _inner.DisposeAsync();
+    }
+
+    // TODO (acasey): Make this public and move it to Connection.Abstractions for use in UseQuic?
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs:172]: This was how I thought we might couple `UseQuic` and `UseHttpsConfiguration`.  It might require duplicating the code for the concrete type.  I'm hoping there's a better way to express this deferred enablement that will be better suited to sharing across assembly boundaries.

**Comment by amcasey** [comment]
I did manage to get the template tests to run locally, but they pass.  I'll keep investigating, but I don't expect a substantial product change (i.e. I think it's safe to review).

**Comment by amcasey** [comment]
The remaining test failure appears to be induced by my logging code, so I'm ignoring it for now.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+
+namespace Microsoft.AspNetCore.Server.Kestrel.Core;
+
+internal interface IHttpsConfigurationHelper
+{
+    bool IsEnabled { get; }
+    void Enable(
+        IHostEnvironment hostEnvironment,
+        ILogger<KestrelServer> serverLogger,
+        ILogger<HttpsConnectionMiddleware> httpsLogger);
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs:17]: Initialize instead of Enabled?

e.g. `IsInitialized` and `Initialize(...)`

File: src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs (hunk 1 above)
Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs:10]: I'm curious why made them separate interfaces? Is it logic that was in two locations?

`UseHttps` method on each interface seems weird.

File: src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs [hunk 8]
```diff
@@ -183,7 +190,8 @@ async Task OnBind(ListenOptions options, CancellationToken onBindCancellationTok
                 // Quic isn't registered if it's not supported, throw if we can't fall back to 1 or 2
                 if (hasHttp3 && _multiplexedTransportFactories.Count == 0 && !(hasHttp1 || hasHttp2))
                 {
-                    throw new InvalidOperationException("This platform doesn't support QUIC or HTTP/3.");
+                    // TODO (acasey): is this good enough of should we track whether UseQuic was called?
+                    throw new InvalidOperationException("This platform doesn't support QUIC or HTTP/3.  Alternatively, you may need to call `UseQuic` on `IWebHostBuilder` to enable it");
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:194]:
```suggestion
                    throw new InvalidOperationException("Unable to bind an HTTP/3 endpoint. This could be because QUIC has not been configured using UseQuic, or the platform doesn't support QUIC or HTTP/3.");
```
It would be nice if there was a way to figure out if UseQuic has been called, but it isn't supported, to provide a more useful error message here.

File: src/Servers/Kestrel/Core/src/KestrelServer.cs [hunk 9]
```diff
@@ -57,4 +60,26 @@ public void Dispose()
     {
         _innerKestrelServer.Dispose();
     }
+
+    private sealed class SimpleHttpsConfigurationHelper : IHttpsConfigurationHelper
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/KestrelServer.cs:64]: I did the exact same thing in my metrics PR. It's annoying that a thing designed for DI - Kestrel - has a way of creating it without DI.

@Tratcher @halter73 @davidfowl Do we know how popular this type is? Could we mark it as obsolete and make it internal in the future?

File: src/Servers/Kestrel/Core/src/KestrelServerOptions.cs [hunk 10]
```diff
@@ -250,11 +250,13 @@ internal void ApplyHttpsDefaults(HttpsConnectionAdapterOptions httpsOptions)
 
     internal void ApplyDefaultCertificate(HttpsConnectionAdapterOptions httpsOptions)
     {
-        if (httpsOptions.ServerCertificate != null || httpsOptions.ServerCertificateSelector != null)
+        if (httpsOptions.HasServerCertificateOrSelector)
         {
             return;
         }
 
+        Debug.Assert(ApplicationServices.GetRequiredService<IHttpsConfigurationHelper>().IsEnabled);
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:258]:
```suggestion
        Debug.Assert(ApplicationServices.GetRequiredService<IHttpsConfigurationHelper>().IsEnabled, "HTTPS must be enabled.");
```

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs [hunk 11]
```diff
@@ -18,6 +18,22 @@ namespace Microsoft.AspNetCore.Hosting;
...
+    /// <param name="hostBuilder"></param>
+    /// <returns></returns>
+    public static IWebHostBuilder UseHttpsConfiguration(this IWebHostBuilder hostBuilder)
+    {
+        HttpsConfigurationHelper.Logger.WriteLine("UseHttpsConfiguration");
+        return hostBuilder.ConfigureServices(services =>
+        {
+            // TODO (acasey): Is there a way we can just call Enable?
+            HttpsConfigurationHelper.Logger.WriteLine("UseHttpsConfiguration::ConfigureServices");
+            services.AddSingleton<HttpsConfigurationHelper.IEnabler, HttpsConfigurationHelper.Enabler>();
```
Comment (JamesNK) [inline src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:33]: If Enabler is registered in DI then `HttpsConfigurationHelper` ctor with IEnabler parameter is used.
If Enabler isn't registered in DI then `HttpsConfigurationHelper` parameterless ctor is used.

Do I understand that right?

File: src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+        public static void WriteLine(string msg)
+        {
+            _builder.AppendLine(msg);
+        }
+
+        public static string GetLog()
+        {
+            return _builder.ToString();
+        }
+    }
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs:225]: Why not write to ILogger? Lots of tests pass the ITestOutputHelper to the logger and then write all the test logs to output.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs:225]: I like the idea of having good logs captured from HTTP/TLS types. IMO Kestrel doesn't log enough during startup today.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs:225]: This was just a hack to debug some test failures, but I'm totally on board with adding more real logging.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/HttpsConfigurationHelper.cs:225]: Sorry for not leaving a comment on the type.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs (hunk 7 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs:17]: I'm fine either way.

File: src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs (hunk 1 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs:10]: It's mostly an artifact of the many revisions this change has gone through.  The `UseHttps` method on the interface is badly named, but I couldn't think of a better one.  It is substantially different from the one on `IHttpsConfigurationHelper`.

**Comment by amcasey** [comment]
Force push drops all debugging commits and, hopefully, fixes CI.

File: src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs (hunk 1 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ITlsConfigurationLoader.cs]: The class still encapsulates some state nicely, but I've merged the interfaces.

File: src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs (hunk 5 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs]: This is still mostly true, though it no longer implements the interface and a couple names and return types changed in trivial ways.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs (hunk 7 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/IHttpsConfigurationHelper.cs]: Done.

File: src/Servers/Kestrel/Core/src/KestrelServerOptions.cs (hunk 10 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: Personally, I don't usually add an assert message the location identifies the problem, but maybe this helps with telemetry or something?

Comment (BrennanConroy) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: Debug.Assert will only show up during local development and CI runs. If this is an error case we think users can get to then it shouldn't be a Debug.Assert. If this is only an error case where we programmed something wrong in kestrel while working on some feature/bug fix, then Debug.Assert is good.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: It would indicate a programming error.  All current code paths satisfy the assert.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: I assume you brought it up because of the comment.  It was intended as guidance to whoever has to debug when we introduce that programming error in the future.  Happy to reword if it's unclear.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: Rephrased.

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs [hunk 13]
```diff
@@ -71,6 +112,26 @@ public static IWebHostBuilder UseKestrel(this IWebHostBuilder hostBuilder, Actio
         return hostBuilder.UseKestrel().ConfigureKestrel(options);
     }
 
+    /// <summary>
+    /// Specify Kestrel as the server to be used by the web host.
+    /// Includes less automatic functionality <see cref="UseKestrel(IWebHostBuilder, Action{KestrelServerOptions})"/> to make trimming more effective
```
Comment (adityamandaleeka) [inline src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:117]: here too
```suggestion
    /// Includes less automatic functionality than <see cref="UseKestrel(IWebHostBuilder, Action{KestrelServerOptions})"/> to make trimming more effective
```

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs [hunk 14]
```diff
@@ -107,6 +168,24 @@ public static IWebHostBuilder UseKestrel(this IWebHostBuilder hostBuilder, Actio
         return hostBuilder.UseKestrel().ConfigureKestrel(configureOptions);
     }
 
+    /// <summary>
+    /// Specify Kestrel as the server to be used by the web host.
+    /// Includes less automatic functionality <see cref="UseKestrel(IWebHostBuilder, Action{WebHostBuilderContext, KestrelServerOptions})"/> to make trimming more effective
```
Comment (adityamandaleeka) [inline src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:173]:
```suggestion
    /// Includes less automatic functionality than <see cref="UseKestrel(IWebHostBuilder, Action{WebHostBuilderContext, KestrelServerOptions})"/> to make trimming more effective
```

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs [hunk 15]
```diff
@@ -71,6 +112,26 @@ public static IWebHostBuilder UseKestrel(this IWebHostBuilder hostBuilder, Actio
         return hostBuilder.UseKestrel().ConfigureKestrel(options);
     }
 
+    /// <summary>
+    /// Specify Kestrel as the server to be used by the web host.
+    /// Includes less automatic functionality <see cref="UseKestrel(IWebHostBuilder, Action{KestrelServerOptions})"/> to make trimming more effective
+    /// (e.g. for Native AOT scenarios).  If the host ends up depending on some of the absent functionality, a best-effort
+    /// attempt will be made to enable it on-demand.  Failing that, an instructive error will be reported.
```
Comment (adityamandaleeka) [inline src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:119]: I wonder how many people will stumble upon this doc comment when they're starting out and not have enough context to know what native AOT is or when the error will be reported (build time vs run time). May be worth linking to a native AOT doc? Or specify the extra detail in a <remarks> section.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+
+    /// <summary>
+    /// Replaces the implementations off all other methods with functioning (as opposed to throwing) versions.
+    /// </summary>
+    void Initialize(
+        IHostEnvironment hostEnvironment,
+        ILogger<KestrelServer> serverLogger,
+        ILogger<HttpsConnectionMiddleware> httpsLogger);
+
+    #region For KestrelConfigurationLoader
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs:36]: We don't use regions anywhere....

File: src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs [hunk 17]
```diff
@@ -24,26 +16,24 @@ namespace Microsoft.AspNetCore.Server.Kestrel;
 /// </summary>
 public class KestrelConfigurationLoader
 {
+    private readonly IHttpsConfigurationService _HttpsConfigurationService;
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs:19]: nit: lower case for fields.
```suggestion
    private readonly IHttpsConfigurationService _httpsConfigurationService;
```

File: src/Servers/Kestrel/Core/src/KestrelServer.cs [hunk 18]
```diff
@@ -57,4 +62,44 @@ public void Dispose()
...
+        public ListenOptions UseHttpsWithSni(ListenOptions listenOptions, HttpsConnectionAdapterOptions httpsOptions, EndpointConfig endpoint)
+        {
+            throw new NotImplementedException(); // Not actually required by this impl
+        }
+
+        public CertificateAndConfig? LoadDefaultCertificate(ConfigurationReader configurationReader)
+        {
+            throw new NotImplementedException(); // Not actually required by this impl
+        }
+    }
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/KestrelServer.cs:104]: I feel like I'm missing something. This is saying that these methods aren't called when KestrelServer is newed up manually?

File: src/Servers/Kestrel/Core/src/KestrelServerOptions.cs [hunk 19]
```diff
@@ -278,6 +282,19 @@ internal void ApplyDefaultCertificate(HttpsConnectionAdapterOptions httpsOptions
...
+    {
+        var HttpsConfigurationService = ApplicationServices.GetRequiredService<IHttpsConfigurationService>();
+
+        if (!HttpsConfigurationService.IsInitialized)
+        {
+            var hostEnvironment = ApplicationServices.GetRequiredService<IHostEnvironment>();
+            var logger = ApplicationServices.GetRequiredService<ILogger<KestrelServer>>();
+            var httpsLogger = ApplicationServices.GetRequiredService<ILogger<HttpsConnectionMiddleware>>();
+            HttpsConfigurationService.Initialize(hostEnvironment, logger, httpsLogger);
+        }
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:295]: Usually, there's a single call to some entry point service that resolved dependencies. This feels *very* manual. Is there a way to avoid these checks to `IsInitialized` or does that happen opportunistically in various places?

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs [hunk 20]
```diff
@@ -0,0 +1,81 @@
...
+    /// </summary>
+    /// <returns>Updated <see cref="ListenOptions"/> for convenient chaining.</returns>
+    ListenOptions UseHttpsWithDefaults(ListenOptions listenOptions);
+    #endregion
+}
+
+/// <summary>
+/// A <see cref="Certificate"/>-<see cref="CertificateConfig"/> pair.
+/// </summary>
+internal record CertificateAndConfig(X509Certificate2 Certificate, CertificateConfig CertificateConfig);
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs:81]: We should avoid the blot of records in the codebase.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs:81]: +1. More info https://github.com/dotnet/aspnetcore/issues/45859

File: src/Servers/Kestrel/Core/src/KestrelServer.cs (hunk 18 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServer.cs:104]: Correct, `KestrelServer` and `KestrelServerImpl` only pass the `IHttpsConfigurationService` to `TransportManager` and `AddressBinder`, so they don't need the parts of the interface that are exclusively for `KestrelConfigurationLoader`.

File: src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs (hunk 17 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs:19]: I have no idea how that happened in so many places, but I think I caught them all.

File: src/Servers/Kestrel/Core/src/KestrelServerOptions.cs (hunk 19 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:295]: This is the pattern I came up with for making it possible to light up this functionality _either_ during DI setup or afterwards (esp when calling `ListenOptions.UseHttps`).  Alternatives welcome.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs (hunk 16 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs]: Moved this context into `<remarks>`.

File: src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs (hunk 20 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/IHttpsConfigurationService.cs]: Now a `readonly struct`.

File: src/Servers/Kestrel/Core/src/KestrelServerOptions.cs (hunk 19 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/KestrelServerOptions.cs]: To elaborate a bit, there's always an `IHttpsConfigurationService`, but all of its methods throw unless you either register an `HttpsConfigurationService.IInitializer` (as in `UseHttpsConfiguration`) or explicitly invoke `Initialize` (as here, in service of `ListenOptions.UseHttps`).

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs (hunk 15 above)
Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:119]: The exception happens during binding, but I'm assuming that's not a widely understood term (at least, by new users).  Would it be appropriate to describe it as "when `Build()` is invoked on the builder" (I think I have to be vague about which builder?)?

What doc did you have in mind for the link?  There's https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/, but (a) it's the top search result for "native aot" and (b) it says "It is currently not supported with ASP.NET Core". 😆

**Comment by amcasey** [comment]
Some tweak along the way broke trimming.  Looking...

**Comment by amcasey** [comment]
Force push is a trivial rebase

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs (hunk 15 above)
Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:119]: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0 seems like the right page, though it will need an aka.ms link.

**Review by adityamandaleeka — APPROVED** [review]

**Review by adityamandaleeka — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 4 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:167]: Added a test documenting this behavior.

File: src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs (hunk 15 above)
Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/src/WebHostBuilderKestrelExtensions.cs:120]: Updated the comment with the link and a comment about when the exception is thrown.

**Comment by amcasey** [comment]
Looks like I was once again sabotaged by my local dev certs.  I'll update the tests.

**Comment by amcasey** [comment]
Force push is a squash and a rebase on `main` (mostly a merge with #46834).

**Comment by JamesNK** [comment]
I played around a bit on a branch - https://github.com/dotnet/aspnetcore/commit/6e106373bdcb4aff906f87f2e138d92f1032cda2

MemberNotNull can definitely be used to remove some bangs.
Can TlsConfigurationLoad be passed from DI, or does that bring in types we don't want?
Is it possible to write a test to verify that TLS and friends are trimmed when not enabled? We have benchmarks that measure size, but something that will be caught in CI is needed. Otherwise, I think this will be too easy to regress accidentally.

File: src/Servers/Kestrel/Core/src/CoreStrings.resx [hunk 21]
```diff
@@ -722,4 +722,7 @@ For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?l
   <data name="FailedToBindToIPv6Any" xml:space="preserve">
     <value>Failed to bind to http://[::]:{port} (IPv6Any).</value>
   </data>
-</root>
\ No newline at end of file
+  <data name="NeedHttpsConfiguration" xml:space="preserve">
+    <value>Call UseHttpsConfiguration() on IWebHostBuilder to enable this functionality.</value>
```
[the remark this answers is not in the document]
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/CoreStrings.resx:726]: That string is going to look a lot like the stack frame below "EnsureInitialized" - I was expecting that to be sufficient.  Does the error message need to be standalone?  (e.g. maybe locks don't include the stack?)

**Comment by JamesNK** [comment]
You also need the `Debug.Assert` calls from my branch to fix the new warnings.

If it's very easy to undo this improvement, we need unit tests. @eerhardt does dotnet/runtime have a way to assert types aren't accidentally being brought in that we could use? Would publishing an app with native AOT and then doing Type.GetType(xxx) work?

File: src/Servers/Kestrel/Core/src/CoreStrings.resx (hunk 21 above)
[the remark this answers is not in the document]
Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/CoreStrings.resx]: It's sufficient, but is it great? 😋

**Review by JamesNK — APPROVED** [review]
LGTM.

Need a way to automate testing this to prevent accidentally regressing the next time we need to change TLS cert logic.

This will be non-trivial. Can happen in a follow-up PR.

File: src/Servers/Kestrel/Core/test/KestrelServerTests.cs [hunk 22]
```diff
@@ -287,10 +293,20 @@ public void ConstructorWithNullTransportFactoryThrows()
...
+                serviceProvider.GetRequiredService<IHostEnvironment>(),
+                serviceProvider.GetRequiredService<ILogger<KestrelServer>>(),
+                serviceProvider.GetRequiredService<ILogger<HttpsConnectionMiddleware>>());
+        }
+	
         return new KestrelServerImpl(
             Options.Create<KestrelServerOptions>(options),
             transportFactories,
             multiplexedFactories,
+			httpsConfigurationService,
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/test/KestrelServerTests.cs:309]:
```suggestion
            httpsConfigurationService,
```

Comment (amcasey) [reply src/Servers/Kestrel/Core/test/KestrelServerTests.cs]: Huh, that must have been from a merge.  Thanks!

**Comment by eerhardt** [comment]
> You also need the `Debug.Assert` calls from my branch to fix the new warnings.
> 
> If it's very easy to undo this improvement, we need unit tests. @eerhardt does dotnet/runtime have a way to assert types aren't accidentally being brought in that we could use? Would publishing an app with native AOT and then doing Type.GetType(xxx) work?

Yes, we do that in 2 places (that I know of) in dotnet/runtime:

Invariant Globalization:

https://github.com/dotnet/runtime/blob/e4743ec9474728f2b4e120fd70a3f729e9204c32/src/libraries/System.Runtime/tests/TrimmingTests/InvariantGlobalizationTrue.cs#L31-L67

System.Text.Json:

https://github.com/dotnet/runtime/blob/e4743ec9474728f2b4e120fd70a3f729e9204c32/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/TrimmingTests/IsReflectionEnabledByDefaultFalse.cs#L54-L66

Note there is a bit of infrastructure to support this. We have a "TrimmingTests" leg that publishes all these EXE projects for trimming. And then we execute the published executable and ensure the exit code is `100`. If it isn't, the test fails. That is all captured here:

https://github.com/dotnet/runtime/blob/e4743ec9474728f2b4e120fd70a3f729e9204c32/eng/testing/linker/trimmingTests.targets#L151

Note that ASP.NET has a backup system (https://github.com/aspnet/Benchmarks/tree/main/src/BenchmarksApps) which publish fully trimmed apps and measure the output size. We also have a regression bot that logs an issue if those apps increase by more than 2%.

**Comment by eerhardt** [comment]
image

image
