### PR TITLE
HTTP/3: Add IStreamAbortFeature

### LINKED ISSUE #31970: HTTP/3: Handle server completing request before reading all the request body
See https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1-15

Should log and send H3_NO_ERROR to the client to stop sending the request body.

To do:
- [ ] QUIC abort is only sent to client
- [x] Request frame process loop exits
- [x] OnStreamComplete is called for request stream

### LINKED ISSUE #33575: HTTP/3: Support aborting one direction of a stream
QUIC supports aborting one direction of a stream. For example:

https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1-15

> A server can send a complete response prior to the client sending an entire request if the response does not depend on any portion of the request that has not been sent and received. **When the server does not need to receive the remainder of the request, it MAY abort reading the request stream, send a complete response, and cleanly close the sending part of the stream.** The error code H3_NO_ERROR SHOULD be used when requesting that the client stop sending on the request stream.

System.Net.Quic is adding `QuicStream.Abort(int protocolError, QuicAbortDirection direction);`

In our abstractions we have a `ConnectionContext.Abort(ConnectionAbortedException abortReason);` method.

We could add an abort overload on ConnectionContext. Another option is to specify the direction like we are with the error code, using a feature. Like there is `IProtocolErrorCodeFeature`, we could add an `IProtocolErrorDirectionFeature`.

@halter73 @Tratcher @davidfowl

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/31970
Fixes https://github.com/dotnet/aspnetcore/issues/33575

HTTP/3 streams support aborting individual sides of a connection stream. Feature is so HTTP layer can abort reading/writing in transport layer.

Args:
* `errorCode` is sent to the peer. long is used because it is variable length.
* Exception is used to complete transport pipes.

Example usage:

The client is uploading data to the server in an HTTP/3 request. The server completes `RequestDelegate` (i.e. user app code) without reading all of the data. HTTP/3 layer in the server will gracefully finish writing the response and abort reading the request. The abort tells the client it can stop uploading.

```cs
namespace Microsoft.AspNetCore.Connections.Features
{
    /// <summary>
    /// Supports aborting individual sides of a connection stream.
    /// </summary>
    public interface IStreamAbortFeature
    {
        /// <summary>
        /// Abort the read side of the connection stream.
        /// </summary>
        /// <param name="errorCode">The error code to send with the abort.</param>
        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the read side of the connection stream.</param>
        void AbortRead(long errorCode, ConnectionAbortedException abortReason);

        /// <summary>
        /// Abort the write side of the connection stream.
        /// </summary>
        /// <param name="errorCode">The error code to send with the abort.</param>
        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the write side of the connection stream.</param>
        void AbortWrite(long errorCode, ConnectionAbortedException abortReason);
    }
}
```

### CODE REVIEW

File: src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+        /// <param name="errorCode">The error code to send with the abort.</param>
+        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the read side of the connection stream.</param>
+        void AbortRead(long errorCode, ConnectionAbortedException abortReason);
+
+        /// <summary>
+        /// Abort the write side of the connection stream.
+        /// </summary>
+        /// <param name="errorCode">The error code to send with the abort.</param>
+        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the write side of the connection stream.</param>
+        void AbortWrite(long errorCode, ConnectionAbortedException abortReason);
```
Comment (JamesNK) [inline src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs:23]: In HTTP/3 the read and write sides of the stream can be aborted independently. An error code is sent with these aborts.

I followed the pattern of `ConnectionContext.Abort(ConnectionAbortedException abortReason)` which uses the exception to pass in a reason. The reason isn't sent to the peer in HTTP/3 and is only used by logging. It can be removed if we don't think passing a reason adds value.

**Comment by JamesNK** [comment]
@halter73 @Tratcher

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs [hunk 2]
```diff
@@ -87,6 +87,7 @@ public void Initialize(Http3StreamContext context)
 
             _errorCodeFeature = _context.ConnectionFeatures.Get<IProtocolErrorCodeFeature>()!;
             _streamIdFeature = _context.ConnectionFeatures.Get<IStreamIdFeature>()!;
+			_streamAbortFeature = _context.ConnectionFeatures.Get<IStreamAbortFeature>()!;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs:90]:
```suggestion
            _streamAbortFeature = _context.ConnectionFeatures.Get<IStreamAbortFeature>()!;
```

File: src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs [hunk 3]
```diff
@@ -399,6 +399,38 @@ public override void Abort(ConnectionAbortedException abortReason)
             Output.CancelPendingRead();
         }
 
+        public void AbortRead(long errorCode, ConnectionAbortedException abortReason)
+        {
+            lock (_shutdownLock)
+            {
+                if (_stream.CanRead)
+                {
+                    _log.StreamAbortRead(this, abortReason.Message);
```
Comment (halter73) [inline src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs:408]: If there's an active reader, can we throw this ConnectionAbortedException from the current read similar to what we do with SocketConnection?

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs [hunk 4]
```diff
@@ -370,18 +371,15 @@ private void CompleteStream(bool errored)
...
                     // https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1-15
                     // When the server does not need to receive the remainder of the request, it MAY abort reading
                     // the request stream, send a complete response, and cleanly close the sending part of the stream.
                     // The error code H3_NO_ERROR SHOULD be used when requesting that the client stop sending on the
                     // request stream.
-
-                    // TODO(JamesNK): Abort the read half of the stream with H3_NO_ERROR
-                    // https://github.com/dotnet/aspnetcore/issues/33575
-
+                    _streamAbortFeature.AbortRead((long)Http3ErrorCode.NoError, new ConnectionAbortedException("The application completed without reading the entire request body."));
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs:382]: If the application completed, it's done writing too, right? Can we just fully close the stream?

Or does this happen *only* when the body PipeReader was completed? If that's the case, maybe the message should say "The application stopped reading the request body." or something.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs [hunk 5]
```diff
@@ -2489,8 +2489,8 @@ public async Task MaxRequestBodySize_ContentLengthOver_413()
 
             await requestStream.OnStreamCompletedTask.DefaultTimeout();
 
-            // TODO(JamesNK): Check for abort of request side of stream after https://github.com/dotnet/aspnetcore/issues/31970
             Assert.Contains(LogMessages, m => m.Message.Contains("the application completed without reading the entire request body."));
+            Assert.Equal("The application completed without reading the entire request body.", requestStream.AbortReadException.Message);
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs:2493]: Does this effectively get logged twice now? I'm okay with it if it's different categories and they're both debug level. Just checking.

File: src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs [hunk 6]
```diff
@@ -404,32 +404,33 @@ internal ValueTask<Http3RequestStream> CreateRequestStream(Http3RequestHeaderHan
...
         internal TaskCompletionSource _onStreamCompletedTcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
         internal TaskCompletionSource _onHeaderReceivedTcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
 
-        internal ConnectionContext StreamContext { get; }
-        internal IProtocolErrorCodeFeature _protocolErrorCodeFeature;
+        internal TestStreamContext StreamContext { get; }
         internal DuplexPipe.DuplexPipePair _pair;
         internal Http3InMemory _testBase;
         internal Http3Connection _connection;
         public long BytesReceived { get; private set; }
```
Comment (Tratcher) [inline src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:417]: Style: the mixing of properties and fields here is pretty strange.

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs (hunk 4 above)
Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs:382]: > If the application completed, it's done writing too, right? Can we just fully close the stream?

The HTTP/3 spec says a server should abort reading if the server has completed processing.

> Or does this happen only when the body PipeReader was completed? If that's the case, maybe the message should say "The application stopped reading the request body." or something.

I have reused the logging message that the HTTP layer reports when a request is completed without reading the request body. It accurately describes why we're aborting reading.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs (hunk 5 above)
Comment (JamesNK) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs:2493]: It's logged once at the HTTP layer and once and the transport layer.

File: src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs (hunk 3 above)
Comment (JamesNK) [reply src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs:408]: I'll add a test and see what happens.

File: src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs (hunk 1 above)
Comment (JamesNK) [reply src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs:23]: Do thumbs up mean keep the exception? 😄

**Review by halter73 — APPROVED** [review]

File: src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+    /// <summary>
+    /// Supports aborting individual sides of a connection stream.
+    /// </summary>
+    public interface IStreamAbortFeature
+    {
+        /// <summary>
+        /// Abort the read side of the connection stream.
+        /// </summary>
+        /// <param name="errorCode">The error code to send with the abort.</param>
+        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the read side of the connection stream.</param>
```
Comment (adityamandaleeka) [inline src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs:15]: Get rid of "optional" on these.

Comment (adityamandaleeka) [inline src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs:15]:
```suggestion
        /// <param name="abortReason">A <see cref="ConnectionAbortedException"/> describing the reason to abort the read side of the connection stream.</param>
```

File: src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+        void AbortRead(long errorCode, ConnectionAbortedException abortReason);
+
+        /// <summary>
+        /// Abort the write side of the connection stream.
+        /// </summary>
+        /// <param name="errorCode">The error code to send with the abort.</param>
+        /// <param name="abortReason">An optional <see cref="ConnectionAbortedException"/> describing the reason to abort the write side of the connection stream.</param>
```
Comment (adityamandaleeka) [inline src/Servers/Connections.Abstractions/src/Features/IStreamAbortFeature.cs:22]:
```suggestion
        /// <param name="abortReason">A <see cref="ConnectionAbortedException"/> describing the reason to abort the write side of the connection stream.</param>
```
