### PR TITLE
.NET Web Worker template update to Blazor Web Worker template

### LINKED ISSUE #65937: .NET Web Worker template cleanup
Some cleanup items for the .NET Web Worker template:

- Remove the license headers from generated template files
- Remove or condense the heavy XML doc comments on WebWorkerClient
- The DisposeAsync method in WebWorkerClient catches a JSDisconnectedException with the comment "Circuit disconnected, worker is already gone", but circuits are specific to Blazor Server- 
- Consider adding an initialization timeout for the worker in case the runtime fails to load silently.
- The parseIfJson logic in dotnet-web-worker-client.js seems potentially problematic if a worker method returns a string that happens to look like JSON. Consider either always deserializing or never parsing.
- Consider adding an InvokeVoidAsync method to WebWorkerClient

### PR DESCRIPTION
**Pull request by ilonatommy**
> - Remove the license headers from generated template files
> - Remove or condense the heavy XML doc comments on WebWorkerClient
> - The DisposeAsync method in WebWorkerClient catches a JSDisconnectedException with the comment "Circuit disconnected, worker is already gone", but circuits are specific to Blazor Server- 

Done in https://github.com/dotnet/aspnetcore/pull/66070/changes/efc73fbcff5bd8e8bc10974c58d2cc04ec6ef81c. See https://github.com/dotnet/aspnetcore/issues/65937#issuecomment-4153679157

> - Consider adding an initialization timeout for the worker in case the runtime fails to load silently.

If we do it for `create` we could also do it for `invoke`, they have similar level of risk. If user's exported method never resolves, it will also hang forever. We should align both to use cancellation tokens and timeouts.
Done in https://github.com/dotnet/aspnetcore/pull/66070/changes/2119dd8fdaf80241dfc813bdfc9112ce105169b0.

> - The parseIfJson logic in dotnet-web-worker-client.js seems potentially problematic if a worker method returns a string that happens to look like JSON. Consider either always deserializing or never parsing.

Done in https://github.com/dotnet/aspnetcore/pull/66070/changes/4d00bab946bb1f8cfafe3abc2816fc8d67d95401. See: https://github.com/dotnet/aspnetcore/issues/65937#issuecomment-4154104132.

> - Consider adding an InvokeVoidAsync method to WebWorkerClient

Done in https://github.com/dotnet/aspnetcore/pull/66070/changes/036d9cf52352371b3307d24ffdcabde577ecf4f8.

> This invocation pattern seems very specific to the host app being a Blazor WebAssembly app. Could we make the .NET Web Worker independent of Blazor?

After offline discussion we decided to make the supported template more Blazor-focused, with default support of web worker running the C# code located in web worker project (not only in the host project). This update contains:
- Changing the name to Blazor Web Worker class library template (most of the changes in this PR is moving files around after the rename).
- Changing the templating engine command to `dotnet new blazorwebworker`.
- Adding `assemblyName` parameter to initialization method that is populated by default with web worker's assembly name in `WebWorkerClient`. In JS we load exports from both: host project and from web worker project.
- Adding a very simple C# file with JSExported method, `WorkerMethods.cs`. It's a boilerplate for removal but blazor web template also ships such an easy-to-remove files like `Counter.razor`. That file documents how to call exported method from host project and shows the place where to embed other methods for the web worker.
- An integral part of this update is a pending change to docs that would adjust our React&WebWorker article and Blazor&WebWorker articles. It will be done after this PR is merged.

Fixes #65937

### CODE REVIEW

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/WebWorkerClient.cs [hunk 1]
```diff
@@ -1,95 +1,54 @@
...
+//     {
+//         [JSExport]
+//         public static string Process(string input) => $"Processed: {input}";
+//     }
+//
+// Example usage:
+//
+//     var worker = await WebWorkerClient.CreateAsync(JSRuntime);
+//     var result = await worker.InvokeAsync<string>("MyApp.MyWorker.Process", ["Hello"]);
+
```
Comment (danroth27) [inline src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/WebWorkerClient.cs]: Instead of this comment on the `WebWorkerClient` class, I suggest a simplified comment on the `InvokeAsync` method below.

```suggestion
```

File: src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWebWorker-CSharp/WebWorkerClient.cs [hunk 2]
```diff
@@ -1,95 +1,54 @@
...
-    /// </summary>
-    /// <typeparam name="TResult">The type of the result.</typeparam>
-    /// <param name="method">Full method path: "Namespace.ClassName.MethodName"</param>
-    /// <param name="args">Arguments to pass to the method.</param>
-    /// <param name="cancellationToken">Token to cancel the operation.</param>
-    /// <returns>The result from the worker method.</returns>
-    /// <exception cref="OperationCanceledException">Thrown if the operation is canceled.</exception>
-    /// <exception cref="JSException">Thrown if the worker method throws an exception.</exception>
-    public async Task<TResult> InvokeAsync<TResult>(string method, object[] args, CancellationToken cancellationToken = default)
+    public async Task<TResult> InvokeAsync<TResult>(string method, object[] args, int timeoutMs = DefaultTimeoutMs, CancellationToken cancellationToken = default)
```
Comment (danroth27) [inline src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWebWorker-CSharp/WebWorkerClient.cs:25]:
```suggestion
    // Invokes a [JSExport] method from the web worker.
    // The method string is the fully qualified path: "AssemblyName.ClassName.MethodName".
    // Arguments and return values must be primitive types or strings.
    public async Task<TResult> InvokeAsync<TResult>(string method, object[] args, int timeoutMs = DefaultTimeoutMs, CancellationToken cancellationToken = default)
```

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js [hunk 3]
```diff
@@ -43,18 +47,29 @@ class DotnetWebWorkerClient {
...
+        return withTimeout(invoke, timeoutMs, `Worker method '${method}' timed out`).catch(err => {
+            const id = this.#requestId;
+            if (this.#pendingRequests[id]) {
+                delete this.#pendingRequests[id];
+            }
+            throw err;
+        });
     }
 
     #parseIfJson(value) {
```
Comment (danroth27) [inline src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: I still think this opportunistic JSON parsing behavior is problematic. I assume you still have to manually serialize the return value and the method arguments still have to be primitive types. I think it would be more consistent and less confusing if we just clearly stated that only primitive types and strings are supported for arguments and return values. Any serialization/deserialization is up to the user to handle.

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker.js
Comment (danroth27) [inline src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker.js:7]: This invocation pattern seems very specific to the host app being a Blazor WebAssembly app. Could we make the .NET Web Worker independent of Blazor? For example, what if you wanted to invoke the .NET Web Worker from a JS app that isn't using Blazor like Copilot Studio currently does?

**Review by danroth27 — CHANGES_REQUESTED** [review]
Looks good! A few comments.

File: src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWebWorker-CSharp/.template.config/template.json [hunk 4]
```diff
@@ -3,17 +3,18 @@
...
     "WebAssembly",
     "Worker",
     "Library"
   ],
-  "name": ".NET Web Worker",
+  "name": "Blazor Web Worker",
   "generatorVersions": "[1.0.0.0-*)",
-  "description": "A project for creating a class library that runs .NET code in a Web Worker.",
-  "groupIdentity": "Microsoft.Web.Worker",
+  "description": "A project for creating a Blazor class library that runs .NET code in a Web Worker.",
```
Comment (danroth27) [inline src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWebWorker-CSharp/.template.config/template.json]: There really isn't such a thing as a "Blazor class library".

```suggestion
  "description": "A project for creating a class library that runs .NET code on a web worker from a Blazor app.",
```

The current design of the template also requires that the host Blazor app uses WebAssembly, correct? Should we add that requirement to the description? Some options:

- "A project for creating a class library that runs .NET code on a web worker from a Blazor WebAssembly app."
- "A project for creating a class library that runs .NET code on a web worker from a Blazor WebAssembly or Blazor Web app."
- "A project for creating a class library that runs .NET code on a web worker from a Blazor WebAssembly or Blazor Web app that uses interactive WebAssembly rendering." 😝

**Review by javiercn — APPROVED** [review]
LGTM

**Review by danroth27 — APPROVED** [review]
LGTM
