### PR TITLE
Set EndpointName and DisplayName given method name in endpoints

### LINKED ISSUE #35435: Improve reporting for duplicate route names in minimal APIs
Currently, if you have the following application in minimal APIs:

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapGet("/", () => "Hello World!");
SomeComponent(app);
void SomeComponent(IEndpointRouteBuilder app)
{
app.MapGet("/", (string name) => $"Hello there {name}");
}
app.Run();
```

You will get the following stacktrace:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:



/ HTTP: GET
/ HTTP: GET
at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Which is not helpful because we use the route pattern as the display name in our exceptions.

We need to figure out a way to provide a display name with more data to the user:

- The name of the delegate associated with the endpoint if possible
- The lambda signature
- The lambda

### PR DESCRIPTION
**Pull request by captainsafia**
## Description

Adds support for automatically setting the name of an endpoint given the name of the method used as a delegate. For example:

```csharp
app.MapGet("/hello", HelloWorld")
```

will produce `HelloWorld` as an endpoint name.

The method name is also incorporated into the display name to make it easier for users to debug issues with routes.

Old display name: /hello HTTP: GET
New display name: HTTP: GET /hello => HelloWorld

## Customer Impact

The changes in this PR make it easier for users to interact with the OpenAPI improvements that were shipped in RC1. They also make it easier for users to debug issues related to duplicate route names by improving the display name used to represent routes.

Screen Shot 2021-08-17 at 9 22 19 PM

## Regression?
- [ ] Yes
- [X] No

## Risk
- [ ] High
- [ ] Medium
- [X] Low

Changes here are isolated to minimal APIs and are part of new changes that were introduced in rc1.

## Verification
- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [X] N/A

Fixes https://github.com/dotnet/aspnetcore/issues/35435 and https://github.com/dotnet/aspnetcore/issues/34540.

### CODE REVIEW

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs [hunk 1]
```diff
@@ -184,6 +186,25 @@ public static class MinimalActionEndpointRouteBuilderExtensions
...
+                {
+                    builder.Metadata.Add(new EndpointNameMetadata(endpointName));
+                    builder.Metadata.Add(new RouteNameMetadata(endpointName));
+                    builder.DisplayName = $"{builder.DisplayName} => {endpointName}";
+                }
+                else
+                {
+                    builder.Metadata.Add(new EndpointNameMetadata(action.Method.Name));
+                    builder.Metadata.Add(new RouteNameMetadata(action.Method.Name));
+                    builder.DisplayName = $"{builder.DisplayName} => {endpointName}";
```
Comment (campersau) [inline src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:204]: Should this use `action.Method.Name` this instead?

```suggestion
                    builder.DisplayName = $"{builder.DisplayName} => {action.Method.Name}";
```

If so you could also dedupe this code:

```c#
if (!GeneratedNameParser.TryParseLocalFunctionName(action.Method.Name, out var endpointName))
    endpointName = action.Method.Name;

builder.Metadata.Add(new EndpointNameMetadata(endpointName));
builder.Metadata.Add(new RouteNameMetadata(endpointName));
builder.DisplayName = $"{builder.DisplayName} => {endpointName}";
```

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs [hunk 2]
```diff
@@ -184,6 +187,21 @@ public static class MinimalActionEndpointRouteBuilderExtensions
...
+            if (action.Target == null || !TypeHelper.IsCompilerGenerated(action.Method.Name))
+            {
+                if (!GeneratedNameParser.TryParseLocalFunctionName(action.Method.Name, out var endpointName))
+                {
+                    endpointName = action.Method.Name;
+                }
+
+                builder.Metadata.Add(new EndpointNameMetadata(endpointName));
+                builder.Metadata.Add(new RouteNameMetadata(endpointName));
+                builder.DisplayName = $"{builder.DisplayName} => {endpointName}";
```
Comment (BrennanConroy) [inline src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:202]: Missing test(s) for the new display name format?
I don't see any with the form
`HTTP: GET /hello => HelloWorld`

File: src/Shared/RoslynUtils/TypeHelper.cs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+        /// Checks to see if a given type is compiler generated.
+        /// <remarks>
+        /// The compiler doesn't always annotate every time it generates with the
+        /// CompilerGeneratedAttribute so sometimes we have to check if the type's
+        /// identifier represents a generated type. Follows the same heuristics seen
+        /// in https://github.com/dotnet/roslyn/blob/b57c1f89c1483da8704cde7b535a20fd029748db/src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/GeneratedMetadataNames.cs#L19
+        /// </remarks>
+        /// </summary>
+        /// <param name="type">The type to evaluate. Can be null if evaluating only on name. </param>
+        /// <param name="name">The identifier associated wit the type.</param>
```
Comment (BrennanConroy) [inline src/Shared/RoslynUtils/TypeHelper.cs:18]:
```suggestion
        /// <param name="name">The identifier associated with the type.</param>
```

File: src/Shared/RoslynUtils/TypeHelper.cs [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+        /// <returns><see langword="true" /> if <paramref name="type"/> is compiler generated
+        /// or <paramref name="name"/> represents a compiler generated identifier.</returns>
+        internal static bool IsCompilerGenerated(string name, Type? type = null)
+        {
+            return (type is Type  && Attribute.IsDefined(type, typeof(CompilerGeneratedAttribute)))
```
Comment (BrennanConroy) [inline src/Shared/RoslynUtils/TypeHelper.cs:23]:
```suggestion
            return (type is Type && Attribute.IsDefined(type, typeof(CompilerGeneratedAttribute)))
```

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs [hunk 5]
```diff
@@ -184,6 +187,21 @@ public static class MinimalActionEndpointRouteBuilderExtensions
...
+            // be filtered that way.
+            if (action.Target == null || !TypeHelper.IsCompilerGenerated(action.Method.Name))
+            {
+                if (!GeneratedNameParser.TryParseLocalFunctionName(action.Method.Name, out var endpointName))
+                {
+                    endpointName = action.Method.Name;
+                }
+
+                builder.Metadata.Add(new EndpointNameMetadata(endpointName));
+                builder.Metadata.Add(new RouteNameMetadata(endpointName));
```
Comment (BrennanConroy) [inline src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:201]: Also don't see tests for this metadata item

**Review by BrennanConroy — APPROVED** [review]
Nice 👍

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs (hunk 2 above)
Comment (captainsafia) [reply src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:202]: Good note! I modified the existing tests but not the new ones. Will add `DisplayName` checks to the new tests.

File: src/Shared/RoslynUtils/TypeHelper.cs [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace System.Runtime.CompilerServices
+{
+    internal static class TypeHelper
+    {
+        /// <summary>
+        /// Checks to see if a given type is compiler generated.
+        /// <remarks>
+        /// The compiler doesn't always annotate every time it generates with the
```
Comment (tmat) [inline src/Shared/RoslynUtils/TypeHelper.cs:11]: >The compiler doesn't always annotate every time it generates with the [](http://example.com/codeflow?start=12&length=69)

If you also check the attribute on containing types you shouldn't need to check for the generated name pattern.

File: src/Shared/RoslynUtils/GeneratedNameParser.cs [hunk 7]
```diff
@@ -0,0 +1,31 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Diagnostics.CodeAnalysis;
+
+// This code is a stop-gapp and exists to address the issues with extracting
```
Comment (tmat) [inline src/Shared/RoslynUtils/GeneratedNameParser.cs:6]: >gapp [](http://example.com/codeflow?start=23&length=4)

typo

File: src/Shared/RoslynUtils/TypeHelper.cs (hunk 6 above)
Comment (tmat) [reply src/Shared/RoslynUtils/TypeHelper.cs:11]: Check the member itself first, then containing type, then its containing type, etc.

File: src/Shared/RoslynUtils/GeneratedNameParser.cs [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+    {
+        /// <summary>
+        /// Parses generated local function name out of a generated method name.
+        /// </summary>
+        internal static bool TryParseLocalFunctionName(string generatedName, [NotNullWhen(true)] out string? originalName)
+        {
+            originalName = null;
+
+            var startIndex = generatedName.LastIndexOf(">g__", StringComparison.OrdinalIgnoreCase);
+            var endIndex = generatedName.LastIndexOf("|", StringComparison.OrdinalIgnoreCase);
```
Comment (cston) [inline src/Shared/RoslynUtils/GeneratedNameParser.cs:21]:
```suggestion
            var startIndex = generatedName.LastIndexOf(">g__", StringComparison.Ordinal);
            var endIndex = generatedName.LastIndexOf("|", StringComparison.Ordinal);
```

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs [hunk 9]
```diff
@@ -184,6 +187,21 @@ public static class MinimalActionEndpointRouteBuilderExtensions
             // Add MethodInfo as metadata to assist with OpenAPI generation for the endpoint.
             builder.Metadata.Add(action.Method);
 
+            // Methods defined in a top-level program are generated as statics so the delegate
+            // target will be null. Inline lambdas are compiler generated properties so they can
```
Comment (cston) [inline src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:191]: >properties [](http://example.com/codeflow?start=74&length=10)

Should this be "compiler generated methods"?

File: src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs [hunk 10]
```diff
@@ -359,6 +359,84 @@ public void MapFallbackWithoutPath_BuildsEndpointWithLowestRouteOrder()
...
+
+            var dataSource = GetBuilderEndpointDataSource(builder);
+            // Trigger Endpoint build by calling getter.
+            var endpoint = Assert.Single(dataSource.Endpoints);
+
+            var endpointName = endpoint.Metadata.GetMetadata<IEndpointNameMetadata>();
+            Assert.Null(endpointName);
+        }
+
         class FromRoute : Attribute, IFromRouteMetadata
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs:440]: Add a test for a method on a class.

Comment (captainsafia) [reply src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs:440]: Isn't `MapMethod_SetsEndpointNameForMethodGroup` sufficient for that?

Comment (davidfowl) [reply src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs:440]: It occurs to me that all methods have to exist on classes 😄. Yes, you're right.

File: src/Shared/RoslynUtils/TypeHelper.cs [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+        /// with the CompilerGenerated attribute. We walk up the declaring types until
+        /// we find a CompilerGenerated attribute or declare the type as not compiler
+        /// generated otherwise.
+        /// </remarks>
+        /// </summary>
+        /// <param name="type">The type to evaluate.</param>
+        /// <returns><see langword="true" /> if <paramref name="type"/> is compiler generated.</returns>
+        internal static bool IsCompilerGeneratedType(Type? type = null)
+        {
+            if (type is Type)
```
Comment (davidfowl) [inline src/Shared/RoslynUtils/TypeHelper.cs:23]: nit:

```suggestion
            if (type is not null)
```

File: src/Shared/RoslynUtils/TypeHelper.cs [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+            {
+                return Attribute.IsDefined(type, typeof(CompilerGeneratedAttribute)) || IsCompilerGeneratedType(type.DeclaringType);
```
Comment (davidfowl) [inline src/Shared/RoslynUtils/TypeHelper.cs:25]: The recursion here is beautiful

**Review by davidfowl — APPROVED** [review]
Just nits but this looks good

**Comment by captainsafia** [comment]
@davidfowl Since you're filling in as M2 while Kevin is out, want to apply the `Servicing-Approved` label if you're good with merging.

cc: @wtgodbe Need your help merging once it's all clear.

**Comment by BrennanConroy** [comment]
Don't forget to forward port to main, it wont be automatic.

File: src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs [hunk 13]
```diff
@@ -359,6 +359,84 @@ public void MapFallbackWithoutPath_BuildsEndpointWithLowestRouteOrder()
...
 
+        [Fact]
+        // This test scenario simulates methods defined in a top-level program
+        // which are compiler generated. We currently do some manually parsing leveraging
+        // code in Roslyn to support this scenario. More info at https://github.com/dotnet/roslyn/issues/55651.
+        public void MapMethod_DoesNotEndpointNameForInnerMethod()
+        {
+            var name = "InnerGetString";
+            var builder = new DefaultEndpointRouteBuilder(new ApplicationBuilder(new EmptyServiceProvdier()));
+            string InnerGetString() => "TestString";
```
Comment (halter73) [inline src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs:370]:
```suggestion
            var testString = "TestString";
            string InnerGetString() => testString;
```

This breaks the test. I think it's because the `MethodInfo` in this case `IsCompilerGeneratedMethod` but it has a non-null `Target`.

**Review by halter73 — CHANGES_REQUESTED** [review]
I think we need to check if the method is a local function before excluding it for being compiler generated.

File: src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs [hunk 14]
```diff
@@ -184,6 +187,21 @@ public static class MinimalActionEndpointRouteBuilderExtensions
...
+            // be filtered that way.
+            if (action.Target == null || !TypeHelper.IsCompilerGeneratedMethod(action.Method))
+            {
+                if (!GeneratedNameParser.TryParseLocalFunctionName(action.Method.Name, out var endpointName))
+                {
+                    endpointName = action.Method.Name;
+                }
```
Comment (halter73) [inline src/Http/Routing/src/Builder/MinimalActionEndpointRouteBuilderExtensions.cs:198]:
```suggestion
            if (GeneratedNameParser.TryParseLocalFunctionName(action.Method.Name, out var endpointName)
                || !TypeHelper.IsCompilerGeneratedMethod(action.Method))
            {
                endpointName ??= action.Method.Name;
```

File: src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs (hunk 13 above)
Comment (captainsafia) [reply src/Http/Routing/test/UnitTests/Builder/MinimalActionEndpointRouteBuilderExtensionsTest.cs:370]: Good catch! I think the `action.Target == null` isn't really needed now that the `IsCompilerGeneratedMethod` check does the work of walking up the declaring types to check to see if a method is declared. I was incorrectly using `action.Target == null` to check for local functions.

**Review by halter73 — APPROVED** [review]

**Review by tmat — APPROVED** [review]
:shipit:
