### PR TITLE
Fix WebWorker template failing in published Blazor WASM apps

### LINKED ISSUE #65820: There is an error "Unhandled exception rendering component: Worker encountered an error" in browser console when running the published WebWorker with Blazor WASM app
**REGRESSION INFO**  Also repro on 11.0 Preview 3

**INSTALL STEPS**
1. Clean Win11 x64 23h2 ENU
2. Install the .NET 11.0 preview 2

**Platform**
- [x] Windows
- [ ] macOS
- [x] Linux

**Repro Steps**
1. Open a normal Command Prompt
2. Create a Blazor WebAssembly Standalone App with a WebWorker library
  ```
  dotnet new blazorwasm -n MyApp
  dotnet new webworker -n MyWebWorker
  ```
3. Add a project reference from the Blazor app to the WebWorker library:
  ```
  cd MyApp
  dotnet add reference ../MyWebWorker/MyWebWorker.csproj
```
4. Open .csproj of Blazor WebAssembly app and add the following inside the existing <PropertyGroup>:
`<AllowUnsafeBlocks>true</AllowUnsafeBlocks>`
5. Create a Myworker.cs file in the Blazor WebAssembly app
    ```
    using System.Runtime.InteropServices.JavaScript;
    using System.Runtime.Versioning;
    using System.Text.Json;
    
    namespace MyApp
    {
        [SupportedOSPlatform("browser")]
        public static partial class MyWorker
        {
            [JSExport]
            public static string Greet(string name) => $"Hello, {name}!";
            [JSExport]
            public static string GetUsers()
            {
                var users = new List<User> { new("Alice", 30), new("Bob", 25) };
                return JsonSerializer.Serialize(users);  // Serialize before returning
            }
        }
        public record User(string Name, int Age);
    }
    ```
6. In the Home.razor file, add the following code.
    ```
    @inject IJSRuntime JSRuntime
    @using MyWebWorker
    
    @code {
        protected override async Task OnInitializedAsync()
        {
            await using var worker = await WebWorkerClient.CreateAsync(JSRuntime);
            
            Console.WriteLine("Worker created?");
            
            var greeting = await worker.InvokeAsync<string>("MyApp.MyWorker.Greet", ["World"]);
            var users = await worker.InvokeAsync<List<User>>("MyApp.MyWorker.GetUsers", []);
        }
    }
    ```
7. Install the `dotnet-serve `tool
  `dotnet tool install --global dotnet-serve`

8. Publish the application to folder:
  `dotnet publish -c Release`

9. Go to the publish output directory and run `dotnet-serve -S`:
    ```
    cd bin\Release\net11.0\publish\wwwroot
    dotnet-serve -S
    ```
10. Open a browser and navigate to the URL 

**Note:**
1. This issue also repro when publish to Azure.
1. This issue does not repro when `dotnet run`

**Actual Result**

Image

**Error Log**
```
blazor.webassembly.u5pmnvwhn0.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Worker encountered an error
      Error: Worker encountered an error
          at Worker.<anonymous> (https://localhost:52806/_content/MyWebWorker/dotnet-web-worker-client.js:18:24)
Microsoft.JSInterop.JSException: Worker encountered an error
Error: Worker encountered an error
    at Worker.<anonymous> (https://localhost:52806/_content/MyWebWorker/dotnet-web-worker-client.js:18:24)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__23`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=11.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at MyWebWorker.WebWorkerClient.CreateAsync(IJSRuntime jsRuntime)
   at MyWebWorker.WebWorkerClient.CreateAsync(IJSRuntime jsRuntime)
   at MyApp.Pages.Home.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task, ComponentState)
Ht @ blazor.webassembly.u5pmnvwhn0.js:1
(anonymous) @ dotnet.runtime.6ti4e6r1z8.js:3
xc @ dotnet.runtime.6ti4e6r1z8.js:3
$func297 @ dotnet.native.xsq86oz5fc.wasm:0x1f8dc
$func221 @ dotnet.native.xsq86oz5fc.wasm:0x1cbdd
$func212 @ dotnet.native.xsq86oz5fc.wasm:0xed2c
$func255 @ dotnet.native.xsq86oz5fc.wasm:0x1dab9
$func3227 @ dotnet.native.xsq86oz5fc.wasm:0xf1e2d
$func2552 @ dotnet.native.xsq86oz5fc.wasm:0xc77a9
$func2557 @ dotnet.native.xsq86oz5fc.wasm:0xc7fa1
$func2581 @ dotnet.native.xsq86oz5fc.wasm:0xca671
$mono_wasm_invoke_jsexport @ dotnet.native.xsq86oz5fc.wasm:0xade1
gn @ dotnet.runtime.6ti4e6r1z8.js:3
(anonymous) @ dotnet.runtime.6ti4e6r1z8.js:3
endInvokeJSFromDotNet @ blazor.webassembly.u5pmnvwhn0.js:1
beginInvokeJSFromDotNet @ blazor.webassembly.u5pmnvwhn0.js:1
```

<details><summary>Command output</summary>

```text
C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot>dotnet-serve -S
Starting server, serving .
Listening on any IP:
  https://localhost:58282

Press CTRL+C to exit
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/ - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/index.html'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\index.html'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/index.html - 200 2380 text/html 16.8757ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.16gzhwgk74.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/MyApp.styles.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/lib/bootstrap/dist/css/bootstrap.min.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/css/app.css - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/blazor.webassembly.u5pmnvwhn0.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/.well-known/appspecific/com.chrome.devtools.json - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/app.css'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\css\app.css'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/dotnet.16gzhwgk74.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\dotnet.16gzhwgk74.js'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/blazor.webassembly.u5pmnvwhn0.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\blazor.webassembly.u5pmnvwhn0.js'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/MyApp.styles.css'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\MyApp.styles.css'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/.well-known/appspecific/com.chrome.devtools.json - 404 - text/html 1.0803ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/lib/bootstrap/dist/css/bootstrap.min.css'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/MyApp.styles.css - 200 4653 text/css 13.8831ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/blazor.webassembly.u5pmnvwhn0.js - 200 71399 text/javascript 13.5684ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/css/app.css - 200 4174 text/css 13.8724ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/lib/bootstrap/dist/css/bootstrap.min.css - 200 232803 text/css 13.9282ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.16gzhwgk74.js - 200 51318 text/javascript 18.8118ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:58282/.well-known/appspecific/com.chrome.devtools.json, Response status code: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.native.xsq86oz5fc.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.native.jqnrqcmp41.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.runtime.6ti4e6r1z8.js - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/dotnet.native.jqnrqcmp41.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\dotnet.native.jqnrqcmp41.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.native.jqnrqcmp41.js - 200 144761 text/javascript 6.2220ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/dotnet.runtime.6ti4e6r1z8.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\dotnet.runtime.6ti4e6r1z8.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.runtime.6ti4e6r1z8.js - 200 195921 text/javascript 6.7235ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Runtime.InteropServices.JavaScript.mg7wfpld9e.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.lcg1gftchg.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Private.CoreLib.1vdt141fmw.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.Web.i7tltwtm1t.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.WebAssembly.4gpmjgorjh.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.phib19uyzk.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.EnvironmentVariables.9mqtai7c9y.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.Json.5oy18zbh6o.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.Abstractions.aayihhhxhu.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Runtime.InteropServices.JavaScript.mg7wfpld9e.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Runtime.InteropServices.JavaScript.mg7wfpld9e.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Runtime.InteropServices.JavaScript.mg7wfpld9e.wasm - 200 43797 application/wasm 6.2449ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Diagnostics.pzqx2nvtb9.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.DependencyInjection.4z37har4tz.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.DependencyInjection.Abstractions.28tae9fsp3.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Configuration.phib19uyzk.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Configuration.phib19uyzk.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Configuration.Abstractions.aayihhhxhu.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Configuration.Abstractions.aayihhhxhu.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Configuration.Json.5oy18zbh6o.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Configuration.Json.5oy18zbh6o.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Configuration.EnvironmentVariables.9mqtai7c9y.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Configuration.EnvironmentVariables.9mqtai7c9y.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.AspNetCore.Components.Web.i7tltwtm1t.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.AspNetCore.Components.Web.i7tltwtm1t.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.EnvironmentVariables.9mqtai7c9y.wasm - 200 10005 application/wasm 4.4691ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.Json.5oy18zbh6o.wasm - 200 10005 application/wasm 4.3979ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.phib19uyzk.wasm - 200 8981 application/wasm 4.5092ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Configuration.Abstractions.aayihhhxhu.wasm - 200 6933 application/wasm 4.4475ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.Web.i7tltwtm1t.wasm - 200 63253 application/wasm 8.1562ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Diagnostics.Abstractions.w7yw8eqnqo.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Hosting.Abstractions.t9p127yvf2.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Logging.nrvqtt7o00.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Logging.Abstractions.kiiyeitua8.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Diagnostics.pzqx2nvtb9.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Diagnostics.pzqx2nvtb9.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Diagnostics.pzqx2nvtb9.wasm - 200 15637 application/wasm 2.4235ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.DependencyInjection.Abstractions.28tae9fsp3.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.DependencyInjection.Abstractions.28tae9fsp3.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Primitives.sc9mmwdrte.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Options.fq3vkawfer.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.JSInterop.cnhkqkscni.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/Microsoft.JSInterop.WebAssembly.tzst4j5q7q.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Diagnostics.Abstractions.w7yw8eqnqo.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Diagnostics.Abstractions.w7yw8eqnqo.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Diagnostics.Abstractions.w7yw8eqnqo.wasm - 200 8469 application/wasm 10.3947ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Hosting.Abstractions.t9p127yvf2.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Hosting.Abstractions.t9p127yvf2.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Hosting.Abstractions.t9p127yvf2.wasm - 200 5397 application/wasm 10.4549ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Logging.nrvqtt7o00.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Logging.nrvqtt7o00.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Logging.nrvqtt7o00.wasm - 200 17685 application/wasm 10.5544ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.DependencyInjection.4z37har4tz.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.DependencyInjection.4z37har4tz.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.DependencyInjection.4z37har4tz.wasm - 200 46869 application/wasm 12.6716ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Logging.Abstractions.kiiyeitua8.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Logging.Abstractions.kiiyeitua8.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Logging.Abstractions.kiiyeitua8.wasm - 200 28949 application/wasm 10.8991ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.DependencyInjection.Abstractions.28tae9fsp3.wasm - 200 26901 application/wasm 13.3261ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Options.fq3vkawfer.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Options.fq3vkawfer.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Options.fq3vkawfer.wasm - 200 20245 application/wasm 2.6654ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.AspNetCore.Components.WebAssembly.4gpmjgorjh.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.AspNetCore.Components.WebAssembly.4gpmjgorjh.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.JSInterop.WebAssembly.tzst4j5q7q.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.JSInterop.WebAssembly.tzst4j5q7q.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.JSInterop.WebAssembly.tzst4j5q7q.wasm - 200 12053 application/wasm 2.6221ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.Extensions.Primitives.sc9mmwdrte.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.Extensions.Primitives.sc9mmwdrte.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.WebAssembly.4gpmjgorjh.wasm - 200 124693 application/wasm 22.2491ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.Extensions.Primitives.sc9mmwdrte.wasm - 200 11541 application/wasm 2.8024ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.JSInterop.cnhkqkscni.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.JSInterop.cnhkqkscni.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.JSInterop.cnhkqkscni.wasm - 200 45845 application/wasm 3.0135ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/Microsoft.AspNetCore.Components.lcg1gftchg.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\Microsoft.AspNetCore.Components.lcg1gftchg.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/Microsoft.AspNetCore.Components.lcg1gftchg.wasm - 200 264469 application/wasm 23.5802ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Collections.Concurrent.z2pmuey88b.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Collections.49tro9q7da.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Collections.Immutable.yz5497hs09.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.ComponentModel.wvxriojdvg.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Console.z8vtcycl1u.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Diagnostics.DiagnosticSource.mbtifhpqkf.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Memory.4uzeecvv79.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.IO.Pipelines.fhb6t19vdo.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Net.Http.Json.ceyy37p1tl.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Linq.waj81srvkr.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Collections.Concurrent.z2pmuey88b.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Collections.Concurrent.z2pmuey88b.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Collections.Concurrent.z2pmuey88b.wasm - 200 5909 application/wasm 1.8619ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Collections.Immutable.yz5497hs09.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Collections.Immutable.yz5497hs09.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Collections.Immutable.yz5497hs09.wasm - 200 51477 application/wasm 2.4031ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.ComponentModel.wvxriojdvg.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.ComponentModel.wvxriojdvg.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Net.Http.8lrd1h6zyw.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.ComponentModel.wvxriojdvg.wasm - 200 4885 application/wasm 2.4621ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Net.Primitives.0dcdqtachx.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Console.z8vtcycl1u.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Console.z8vtcycl1u.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Console.z8vtcycl1u.wasm - 200 14613 application/wasm 2.4081ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Collections.49tro9q7da.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Collections.49tro9q7da.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Private.Uri.8559thd91z.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Collections.49tro9q7da.wasm - 200 22293 application/wasm 2.6070ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Memory.4uzeecvv79.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Memory.4uzeecvv79.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Memory.4uzeecvv79.wasm - 200 14613 application/wasm 2.4431ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Runtime.n5qa5mzvxi.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.IO.Pipelines.fhb6t19vdo.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.IO.Pipelines.fhb6t19vdo.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.IO.Pipelines.fhb6t19vdo.wasm - 200 5909 application/wasm 2.4666ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Linq.waj81srvkr.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Linq.waj81srvkr.wasm'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Net.Http.Json.ceyy37p1tl.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Net.Http.Json.ceyy37p1tl.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Linq.waj81srvkr.wasm - 200 27925 application/wasm 2.4930ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Net.Http.Json.ceyy37p1tl.wasm - 200 17685 application/wasm 2.5719ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Diagnostics.DiagnosticSource.mbtifhpqkf.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Diagnostics.DiagnosticSource.mbtifhpqkf.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Diagnostics.DiagnosticSource.mbtifhpqkf.wasm - 200 64277 application/wasm 3.2240ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Net.Primitives.0dcdqtachx.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Net.Primitives.0dcdqtachx.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Net.Primitives.0dcdqtachx.wasm - 200 7445 application/wasm 1.4593ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Runtime.n5qa5mzvxi.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Runtime.n5qa5mzvxi.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Runtime.n5qa5mzvxi.wasm - 200 6933 application/wasm 1.4105ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Private.Uri.8559thd91z.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Private.Uri.8559thd91z.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Private.Uri.8559thd91z.wasm - 200 65301 application/wasm 2.3507ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Text.Encodings.Web.d54w33olst.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Security.Cryptography.k1fe8qw45w.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Text.Json.y1fw5m6rzd.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/System.Text.RegularExpressions.6o0ilumla5.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/MyWebWorker.akb8rlkz99.wasm - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/MyApp.lz80zum168.wasm - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Net.Http.8lrd1h6zyw.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Net.Http.8lrd1h6zyw.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/icudt_EFIGS.xyuimhy3ww.dat - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Net.Http.8lrd1h6zyw.wasm - 200 136469 application/wasm 3.1250ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Text.Encodings.Web.d54w33olst.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Text.Encodings.Web.d54w33olst.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Text.Encodings.Web.d54w33olst.wasm - 200 30485 application/wasm 1.5464ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Security.Cryptography.k1fe8qw45w.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Security.Cryptography.k1fe8qw45w.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Security.Cryptography.k1fe8qw45w.wasm - 200 21269 application/wasm 1.7423ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/MyWebWorker.akb8rlkz99.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\MyWebWorker.akb8rlkz99.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/MyWebWorker.akb8rlkz99.wasm - 200 7957 application/wasm 1.5951ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Text.RegularExpressions.6o0ilumla5.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Text.RegularExpressions.6o0ilumla5.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Text.RegularExpressions.6o0ilumla5.wasm - 200 16149 application/wasm 1.8651ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/MyApp.lz80zum168.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\MyApp.lz80zum168.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/MyApp.lz80zum168.wasm - 200 24853 application/wasm 1.7586ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Text.Json.y1fw5m6rzd.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Text.Json.y1fw5m6rzd.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Text.Json.y1fw5m6rzd.wasm - 200 380693 application/wasm 6.6394ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/icudt_EFIGS.xyuimhy3ww.dat'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\icudt_EFIGS.xyuimhy3ww.dat'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/icudt_EFIGS.xyuimhy3ww.dat - 200 621712 application/dat 12.0243ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/System.Private.CoreLib.1vdt141fmw.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\System.Private.CoreLib.1vdt141fmw.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/System.Private.CoreLib.1vdt141fmw.wasm - 200 1678101 application/wasm 43.6825ms
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/dotnet.native.xsq86oz5fc.wasm'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_framework\dotnet.native.xsq86oz5fc.wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.native.xsq86oz5fc.wasm - 200 3125726 application/wasm 66.7656ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/lib/bootstrap/dist/css/bootstrap.min.css.map - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.runtime.js.map - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.runtime.js.map - 404 - text/html 0.5740ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:58282/_framework/dotnet.runtime.js.map, Response status code: 404
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/lib/bootstrap/dist/css/bootstrap.min.css.map'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/lib/bootstrap/dist/css/bootstrap.min.css.map - 200 589892 text/plain 9.4482ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/favicon.png - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.png'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\favicon.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/favicon.png - 200 1148 image/png 1.8177ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_content/MyWebWorker/dotnet-web-worker-client.js - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_content/MyWebWorker/dotnet-web-worker-client.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_content\MyWebWorker\dotnet-web-worker-client.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_content/MyWebWorker/dotnet-web-worker-client.js - 200 2958 text/javascript 4.1616ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_content/MyWebWorker/dotnet-web-worker.js - - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_content/MyWebWorker/dotnet-web-worker.js'. Physical path: 'C:\Users\v-xinyfe\MyApp\bin\Release\net11.0\publish\wwwroot\_content\MyWebWorker\dotnet-web-worker.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_content/MyWebWorker/dotnet-web-worker.js - 200 1548 text/javascript 0.9616ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:58282/_framework/dotnet.js - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:58282/_framework/dotnet.js - 404 - text/html 1.0197ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:58282/_framework/dotnet.js, Response status code: 404
``

### PR DESCRIPTION
**Pull request by ilonatommy**
## Web Workers do not inherit the page's import map, causing fingerprinted asset resolution to fail. 

During dotnet publish, Blazor WebAssembly apps fingerprint framework JavaScript files. The non-fingerprinted files do not exist in the published output. `index.html` contains an ES Module Import Map that maps the old names to the new ones. It did not fail on `dotnet run` (`WebWorkerTemplate_CanInvokeMethods`) because then we do not fingerprint.

Web Workers are separate JavaScript execution contexts. Per [HTML spec](https://html.spec.whatwg.org/multipage/workers.html) they do not inherit parent page's import map. There is an issue with proposal of fixing it: https://github.com/whatwg/html/issues/8173. but without much activity.

## Description

 **`dotnet-web-worker-client.js`** - Uses [`import.meta.resolve()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve) on the main thread to resolve `_framework/dotnet.js` through the browser's native import map resolution.
  The resolved (fingerprinted) URL is passed to the Worker via `postMessage`. No DOM parsing or JSON manipulation needed.

   **`dotnet-web-worker.js`** - Replaces static `import { dotnet } from '../../_framework/dotnet.js'` with message-driven initialization using dynamic `import()` with the resolved URL.

   `import.meta.resolve()` is supported in Chrome 105+, Firefox 106+, Safari 16.4+.

This PR is adding tests that run published app.

Fixes #65820

### CODE REVIEW

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js [hunk 1]
```diff
@@ -30,9 +30,26 @@ class DotnetWebWorkerClient {
...
 
+    static #resolveDotnetJsUrl() {
+        let resolvedPath = '_framework/dotnet.js';
+        const importMapEl = document.querySelector('script[type="importmap"]');
+        if (importMapEl) {
+            const map = JSON.parse(importMapEl.textContent);
+            const imports = map.imports || {};
+            const url = imports['./_framework/dotnet.js'] || imports['_framework/dotnet.js'] || imports['./dotnet.js'];
+            if (url) {
+                resolvedPath = url.replace(/^\.\//, '');
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: Checking for empty import map is better than try-catch.

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js [hunk 2]
```diff
@@ -30,9 +30,27 @@ class DotnetWebWorkerClient {
...
             });
+
+            const dotnetJsUrl = DotnetWebWorkerClient.#resolveDotnetJsUrl();
+            worker.postMessage({ type: 'init', dotnetJsUrl });
         });
     }
 
+    static #resolveDotnetJsUrl() {
+        let resolvedPath = '_framework/dotnet.js';
+        const importMapEl = document.querySelector('script[type="importmap"]');
```
Comment (maraf) [inline src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: I don't think we should go this path, although I don't have much alternatives. I have two concerts
- JSON manipulation of the importmap
- URL resolution

Comment (maraf) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: My best bet so far would be to force use of server-worker in this scenario.
(or import the server-worker-assets directly into the main document and read the assets from there).

Comment (maraf) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: Alternatively we could suggest to use js bundler in this scenario

Comment (pavelsavara) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: We can also emit the map into boot config

Comment (maraf) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: That wouldn't help if we don't know how to resolve `dotnet.js`, would it?
We would have to have an API accessible on main document to make it useful right?

Comment (pavelsavara) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker-client.js]: The for dotnet.js in UI thread the importmap works. So you load dotnet.js and ask it for config.

File: src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker.js [hunk 3]
```diff
@@ -1,23 +1,30 @@
...
+        const { getAssemblyExports, getConfig } = await dotnet.create();
+        const assemblyName = getConfig().mainAssemblyName;
+        workerExports = await getAssemblyExports(assemblyName);
+        self.postMessage({ type: "ready" });
+    } catch (err) {
+        const errorMessage = err?.message ?? String(err);
+        startupError = errorMessage;
+        console.error("[Worker] Failed to initialize .NET:", err);
+        self.postMessage({ type: "ready", error: errorMessage });
+    }
```
Comment (javiercn) [inline src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker.js:19]: The approach looks good to me. 

Is there anything we think we will need other than dotnet.js?

Comment (ilonatommy) [reply src/ProjectTemplates/Web.ProjectTemplates/content/WebWorker-CSharp/wwwroot/dotnet-web-worker.js:19]: Only items in `_framework` dir are hard fingerprinted. Worker script url is hardcoded but it's not in `_framework` and same about user's own modules. I can't think about any other file we would have to treat this way.

**Review by javiercn — APPROVED** [review]

**Review by maraf — APPROVED** [review]
