### PR TITLE
Avoid pausing circuit simultaneously with disposing of it

### LINKED ISSUE #61178: Known Build Error: error : Cannot create a file when that file already exists.
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=995186&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc
Build error leg or test failing: Build / Build: Windows x64/x86/arm64 / Build x64
Pull request: https://github.com/dotnet/aspnetcore/pull/61011

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "error : Cannot create a file when that file already exists.",
  "ErrorPattern": "",
  "BuildRetry": true,
  "ExcludeConsoleLog": true
}
```

### PR DESCRIPTION
**Pull request by ilonatommy**
# Prevent scope-related operations on disposed circuit

```
 ---&gt; System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
 at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitPersistenceManager.PauseCircuitAsync(CircuitHost circuit, Boolean saveStateToClient, CancellationToken cancellation) in /home/vsts/work/1/s/src/Components/Server/src/Circuits/CircuitPersistenceManager.cs:line 25
```

## Description

The problem occurs only when we try to pause the circuit after it was already disposed. It can happen in scenarios:
- Race between eviction and pausing.
- Race between termination and pausing.
- Race between two pauses.

The test call these actions synchronously (they await), so that the reproduction is stable. The real race was observed on CI with a frequency of ~20 hits per week. 

## Fix

- All disposal actions happen on a single-threaded dispatcher: 
https://github.com/dotnet/aspnetcore/blob/0f963e9f2bdb6428f50f1448670874ae1e0b2f26/src/Components/Server/src/Circuits/CircuitHost.cs#L200
Wrapping pause logic in the dispatcher invoke prevents it from running concurrently with disposal that comes from e.g. termination or eviction.
~~- Even if pause will not run concurrently with disposal, it can still run just after disposal happened - see the tests. To prevent it from trying to discover services in a disposed DI scope, we check `CircuitHost` disposal flag.~~ removed after the discussion - I could not find any evidence that pause can happen after disposal in real life.

Fixes - let's keep it open for some time: #62672

Frequency of failures on CI before this fix for reference:
image

### CODE REVIEW

**Comment by ilonatommy** [comment]
e2e on 3rd run passed, re-merging

File: src/Components/Server/src/Circuits/CircuitPersistenceManager.cs [hunk 1]
```diff
@@ -21,26 +21,34 @@ internal partial class CircuitPersistenceManager(
...
-        var collector = new CircuitPersistenceManagerCollector(circuitOptions, serverComponentSerializer, circuit.Renderer);
-        using var subscription = persistenceManager.State.RegisterOnPersisting(
-            collector.PersistRootComponents,
-            RenderMode.InteractiveServer);
+        await circuit.Renderer.Dispatcher.InvokeAsync(async () =>
+        {
+            if (circuit.IsDisposed())
+            {
+                return;
+            }
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitPersistenceManager.cs]: We shouldn't need to guard against double disposal. If we have this issue, there's a bug somewhere else

File: src/Components/Server/test/Circuits/CircuitRegistryTest.cs [hunk 2]
```diff
@@ -678,4 +689,148 @@ private static (CircuitRegistry Registry, TestCircuitPersistenceProvider Provide
...
+        var persistenceProvider = new TestCircuitPersistenceProvider();
+        var registry = new TestCircuitRegistry(circuitIdFactory, options, persistenceProvider);
+        registry.Register(circuitHost);
+
+        // First pause should be successful
+        await registry.PauseAndDisposeCircuitHost(circuitHost, saveStateToClient: true);
+
+        // Second pause - it will try to resolve services from the DI scope that is already disposed
+        await registry.PauseAndDisposeCircuitHost(circuitHost, saveStateToClient: true);
+    }
```
Comment (javiercn) [inline src/Components/Server/test/Circuits/CircuitRegistryTest.cs]: We shouldn't have this test. Calling pause multiple times is not a thing we expect to happen, we shouldn't test for it, we should preclude it from happening.

File: src/Components/Server/test/Circuits/CircuitRegistryTest.cs [hunk 3]
```diff
@@ -678,4 +689,148 @@ private static (CircuitRegistry Registry, TestCircuitPersistenceProvider Provide
...
+        var persistenceProvider = new TestCircuitPersistenceProvider();
+        var registry = new TestCircuitRegistry(circuitIdFactory, options, persistenceProvider);
+        registry.Register(circuitHost);
+
+        // First simulate eviction by calling the same method that eviction calls
+        await registry.SimulateEvictionAndDispose(circuitHost);
+
+        // Then try to pause - it will try to resolve services from the DI scope that is already disposed
+        await registry.PauseAndDisposeCircuitHost(circuitHost, saveStateToClient: true);
+    }
```
Comment (javiercn) [inline src/Components/Server/test/Circuits/CircuitRegistryTest.cs]: I don't think this can happen in real life. The memory cache will evict the entry "atomically" and then run the eviction callback. For that to happen the circuit needs to be in the `Disconnected` pool.

`PauseCircuitAsync` will only run for connected circuits `https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/Circuits/CircuitRegistry.cs#L318-L337` and a circuit can't be in the connected and disconnected states simultaneously (there's a critical section for it).

Comment (ilonatommy) [reply src/Components/Server/test/Circuits/CircuitRegistryTest.cs:757]: Is the last scenario, pause after termination possible?

File: src/Components/Server/test/Circuits/CircuitRegistryTest.cs (hunk 2 above)
Comment (ilonatommy) [reply src/Components/Server/test/Circuits/CircuitRegistryTest.cs]: Why is pausing a fire and forget operation:
https://github.com/ilonatommy/aspnetcore/blob/407f7ce33be2d944a538db9fbbb05a02a1f7fdd6/src/Components/Server/src/ComponentHub.cs#L424?

Comment (ilonatommy) [reply src/Components/Server/test/Circuits/CircuitRegistryTest.cs]: You probably mean that only client can call it and that it is guarding the next calls with a lot of "if disconnected" etc and that we call the pause only internally. Let's then go a few levels higher and use multiple `javascript.ExecuteScript("Blazor.pauseCircuit()");` instead of direct `PauseAndDisposeCircuitHost`. If I won't force it to reproduce the problem, the test will be removed.

File: src/Components/Server/src/Circuits/CircuitPersistenceManager.cs (hunk 1 above)
Comment (ilonatommy) [reply src/Components/Server/src/Circuits/CircuitPersistenceManager.cs]: We have this problem in a very specific environment, with forced GC and reloads of page. What's more I hit in on CI only. How can I tell which situation from the possible scenarios I found is the true offender?

File: src/Components/Server/test/Circuits/CircuitRegistryTest.cs (hunk 2 above)
Comment (ilonatommy) [reply src/Components/Server/test/Circuits/CircuitRegistryTest.cs]: Neither pausing on repeat nor pause + reconnect + GC collection did not reproduce the original problem. Because I don't have any proof that dispatcher alone is not enough, I will remove other changes, including tests (they would fail without `IsDisposed` check), merge the simplest fix and observe the CI.

**Review by javiercn — APPROVED** [review]

**Comment by pavelsavara** [comment]
nice
