### PR TITLE
Observe more mutations to configuration and services

### LINKED ISSUE #33876: WebApplication does not observe changes made with WebApplicationFactory<T> in tests
### Describe the bug

When using `WebApplicationFactory`/`WebApplication` in conjunction with `WebApplicationFactory<T>` for integration tests, the `WebApplication` created by `WebApplicationFactory` does not observe configuration changes made to the `IWebHostBuilder` by `WebApplicationFactory<T>`.

First, if the configuration is changed using `ConfigureAppConfiguration()`, the changes are not visible in the `IConfiguration` resolved by the `WebApplication`. This applies to adding new sources as well as clearing the existing sources. In both cases, the original configuration remains with the built application, and the changes applied for the tests by the `WebApplicationFactory<T>` are not visible to the application.

Calling `serviceProvider.GetServices<IConfiguration>().Count()` within the application returns a value of `2`. It appears that both two `IConfiguration` implementations, one for the web host and another for `WebApplication` are registered with the service provider, with the `WebApplication` one being resolved by calls to `GetService<IConfiguration>()` meaning that the changes are not observed.

This can be worked around by using `ConfigureServices()` to clear the duplicate registration to leave the one required by the tests:

```csharp
builder.ConfigureServices(services =>
{
    var descriptors = services.Where(p => p.ServiceType == typeof(IConfiguration)).ToList();
    services.Remove(descriptors[1]);
});
```

Secondly, changes to the content root are not observed by the application. If `UseContentRoot()` is used to change the directory to serve content by `WebApplicationFactory<T>`, the change is not visible to the `WebApplication` instance, which continues to use the path associated with where the test process was launched from.

This causes static content to not be found when requested.

### To Reproduce

An application that reproduces this issue is available at https://github.com/martincostello/WebApplicationFactory-Config-Issues. To reproduce the issue:

1. Clone `https://github.com/martincostello/WebApplicationFactory-Config-Issues.git`
2. Run `build.ps1`

The following test failures are then observed:

1. The `Can_Override_Configuration` test fails because the original value of `Value` is used from configuration (`"a"`) instead of the one overridden by the tests (`"b"`).
2. The `Can_Override_ContentRoot` tests fails because a 404 is returned due to the application being unable to find the `test.txt` file to serve the static content.
3. The `Can_Remove_Configuration` test fails because the original value of `Value` is used from configuration (`"a"`) instead of an empty value of `""` because all of the configuration sources were removed.

Running the application under the debugger in Visual Studio 2022 and requesting the `/api` or `/test.txt` resources in a browser show the application works as expected when run outside of the test project.

Similarly the `Application_Returns_Defaults` test also works correctly as no overrides are provided.

### Further technical details

- .NET SDK: `6.0.100-preview.6.21324.1` (I tried to use the latest preview 7 build but had issues running it in Visual Studio 2022)
- Visual Studio 2022 Preview 1.1

### PR DESCRIPTION
**Pull request by davidfowl**
- When using WebApplicationFactory with the WebApplicationFactory, mutations are made very late that aren't observable via the WebApplicationBuilder.Configuration nor  WebApplicationBuilder.Services. The configuration tries to be the source of truth but more sources are added it can't see, the same with the service collection (though that is more rare). To fix this, the strategy is to use the initial service collection and configuration as data that will feed into the final IConfigurationBuilder and IServiceCollection, and then "update" these properties to point back to the final configuration and service collection. Results in the properties on the builder being consistent (from a data POV) with the built application.
- Added tests that mimic what the WebApplicationFactory does but using the diagnostic source to capture the right events for the right host and mutate the IHostBuilder.

Fixes https://github.com/dotnet/aspnetcore/issues/33876

### CODE REVIEW

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 1]
```diff
@@ -101,11 +100,66 @@ internal WebApplicationBuilder(Assembly? callingAssembly, string[]? args = null)
         /// <returns>A configured <see cref="WebApplication"/>.</returns>
         public WebApplication Build()
         {
+            // Copy the configuration sources into the final IConfigurationBuilder
+            _hostBuilder.ConfigureHostConfiguration(builder =>
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:104]: Does it matter this was moved out of ConfigureWebHost? Is there something specific these callbacks need to run before?

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 2]
```diff
@@ -101,11 +100,66 @@ internal WebApplicationBuilder(Assembly? callingAssembly, string[]? args = null)
...
+            {
+                foreach (var source in ((IConfigurationBuilder)Configuration).Sources)
+                {
+                    builder.Sources.Add(source);
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:108]: I'm sad we lose the ability to observe changes to sources post-build.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 3]
```diff
@@ -101,11 +100,66 @@ internal WebApplicationBuilder(Assembly? callingAssembly, string[]? args = null)
...
+                {
+                    services.Add(s);
+                }
+
+                // Add any services to the user visible service collection so that they are observable
+                // just in case users capture the Services property. Orchard does this to get a "blueprint"
+                // of the service collection
+
+                // Clear the original collection.
+                _services.Clear();
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:145]: Why is this necessary when we unreference the original collection on the next line?

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 4]
```diff
@@ -101,11 +100,66 @@ internal WebApplicationBuilder(Assembly? callingAssembly, string[]? args = null)
...
+            });
+
+            // Run the other callbacks on the final host builder
+            _deferredHostBuilder.RunDeferredCallbacks(_hostBuilder);
+
+            _builtApplication = new WebApplication(_hostBuilder.Build());
+
+            // Make builder.Configuration match the final configuration. To do that
+            // we clear the sources and add the built configuration as a source
+            ((IConfigurationBuilder)Configuration).Sources.Clear();
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:159]: So we just lose the added configuration if a deferred callback adds a source? I'm hoping to eliminate the deferred callback completely though. We've already inlined most of them.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs [hunk 5]
```diff
@@ -71,7 +70,7 @@ internal WebApplicationBuilder(Assembly? callingAssembly, string[]? args = null)
         /// <summary>
         /// A collection of services for the application to compose. This is useful for adding user provided or framework provided services.
         /// </summary>
-        public IServiceCollection Services { get; } = new ServiceCollection();
+        public IServiceCollection Services { get; } = default!;
```
Comment (halter73) [inline src/DefaultBuilder/src/WebApplicationBuilder.cs:73]:
```suggestion
        public IServiceCollection Services { get; }
```

You can do this since it's set in the ctor, right?

Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:73]: It was complaining in the IDE but maybe it was just laggy.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 4 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:159]: You can't, look at the tests, it has no way of getting visibility into what happens after these callbacks.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 3 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:145]: It's good hygene.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 2 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:108]: We probably need to make sure that works.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 1 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:104]: I just don't see why it needs to run inside of ConfigureWebHost

Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:104]: Fair.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 2 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:108]: I should have added a test case for it, but I was worried you'd balk at requiring that behavior. I didn't think you'd merge it so quickly 😅

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 4 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:159]: For some reason I was thinking this was pre-build even though Build() is only a couple line up.

File: src/DefaultBuilder/src/WebApplicationBuilder.cs (hunk 2 above)
Comment (davidfowl) [reply src/DefaultBuilder/src/WebApplicationBuilder.cs:110]: Actually it works fine.

**Review by halter73 — APPROVED** [review]
