### PR TITLE
http.sys: Allow configuring HTTP_AUTH_EX_FLAGs as options

### LINKED ISSUE #13634: Multiple 401 when using Windows authentication on HTTP.sys
### Describe the bug
The 401 WWW-Negotiate challenge happens for each request.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Set up HTTP.Sys with `options.Authentication.Schemes = Microsoft.AspNetCore.Server.HttpSys.AuthenticationSchemes.Negotiate;`
3. Run Fiddler to intercept requests
4. Use a client to perform a GET

### Expected behavior
The 401 WWW-Negotiate challenge happens only the first time.

### Additional context
It looks like when using IIS it is possible to configure `authPersistNonNTLM=true` to achieve this. See [https://blogs.msdn.microsoft.com/dsnotes/2014/02/11/iis-how-to-reduce-multiple-authentication-or-multiple-401-while-using-kerberos-for-authentication/](this link)

### Side note
Performing the 401 challenge means more requests, more traffic, less performance.

### PR DESCRIPTION
**Pull request by evgenykotkov**
# http.sys: Allow configuring HTTP_AUTH_EX_FLAGs as options

## Description

The native HTTP.sys API offers two extended authentication flags:

- [`HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING`](https://learn.microsoft.com/en-us/windows/win32/api/http/ns-http-http_server_authentication_info) and
- [`HTTP_AUTH_EX_FLAG_CAPTURE_CREDENTIAL`](https://learn.microsoft.com/en-us/windows/win32/api/http/ns-http-http_server_authentication_info)

that can be used by users to fine-tune their Windows authentication setups.

For instance, the `HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING` flag can be used to avoid having to authenticate every request and make the authentication session-based, thus reducing the overall number of requests and improving the high-latency scenarios.  Enabling it can be used to achieve the same behavior as with the `authPersistNonNTLM` option in IIS.

#### Change details:

- The groundwork change c50346d52569c318f6a1 fixes an existing issue in the definition/layout of the `HTTP_SERVER_AUTHENTICATION_INFO` interop structure.

- The core change 7489786de9e65730ad45 exposes both flags as options in the authentication manager.  Because setting the extended flags requires a different property type (`HttpServerExtendedAuthenticationProperty`), we take additional precaution to only use that property type if we actually have the extended flags to set, and use the original `HttpServerAuthenticationProperty` otherwise.

Fixes #13634

API proposal: #51990

### CODE REVIEW

**Comment by evgenykotkov** [comment]
> @evgenykotkov please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```

@dotnet-policy-service agree

**Comment by Tratcher** [comment]
FYI https://github.com/dotnet/aspnetcore/pull/50685/files#diff-9ef7d6eddeed6c08a6095b72475b87bc6b8b84b2b657ad07d407f9feb44f232c removes the need for pre-defined interop structs.

**Comment by Tratcher** [comment]
@blowdart

**Review by blowdart — APPROVED** [review]
Cached in the comments is vague.

Cached for how long?

**Comment by Tratcher** [comment]
I think this is the same as
https://github.com/dotnet/aspnetcore/blob/0fe51bd16abaf925d3dbb43f6c213be9bab9d3c6/src/Security/Authentication/Negotiate/src/NegotiateOptions.cs#L22-L27

File: src/Servers/HttpSys/src/AuthenticationManager.cs [hunk 1]
```diff
@@ -63,6 +63,19 @@ public bool AllowAnonymous
     /// </summary>
     public string? AuthenticationDisplayName { get; set; }
 
+    /// <summary>
+    /// If true, the Kerberos authentication credentials are cached. Kerberos or Negotiate
```
Comment (amcasey) [inline src/Servers/HttpSys/src/AuthenticationManager.cs:67]: I agree with @blowdart that it would be nice to give some indication of the lifetime of the cached credentials.

File: src/Servers/HttpSys/src/AuthenticationManager.cs [hunk 2]
```diff
@@ -63,6 +63,19 @@ public bool AllowAnonymous
...
+    /// authentication must be enabled. The default is false.
+    /// </summary>
+    public bool EnableKerberosCredentialCaching { get; set; }
+
+    /// <summary>
+    /// If true, the server captures the caller's credentials and uses them for Kerberos
+    /// or Negotiate authentication. Kerberos or Negotiate authentication must be enabled.
+    /// The default is false.
+    /// </summary>
+    public bool CaptureCredential { get; set; }
```
Comment (amcasey) [inline src/Servers/HttpSys/src/AuthenticationManager.cs:77]: I know we're mirroring an underlying API, but it seems like this should be "CaptureCredentials".

File: src/Servers/HttpSys/src/AuthenticationManager.cs [hunk 3]
```diff
@@ -87,18 +100,41 @@ private unsafe void SetUrlGroupSecurity()
...
-            // Kerberos auth sharing (off by default?) HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING
             // Mutual Auth - ReceiveMutualAuth
             // Digest domain and realm - HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS
             // Basic realm - HTTP_SERVER_AUTHENTICATION_BASIC_PARAMS
 
+            HttpApiTypes.HTTP_SERVER_PROPERTY property;
+            if (authInfo.ExFlags != HttpApiTypes.HTTP_AUTH_EX_FLAGS.NONE)
+            {
+                // We need to modify extended fields such as ExFlags, set the extended auth property.
+                property = HttpApiTypes.HTTP_SERVER_PROPERTY.HttpServerExtendedAuthenticationProperty;
```
Comment (amcasey) [inline src/Servers/HttpSys/src/AuthenticationManager.cs:127]: Do I understand correctly that this is a superset of `HttpServerAuthenticationProperty` and that's why the new `setProperty` call replaces the old one, rather than following it?

File: src/Servers/HttpSys/src/PublicAPI.Unshipped.txt [hunk 4]
```diff
@@ -36,3 +36,7 @@ Microsoft.AspNetCore.Server.HttpSys.IHttpSysRequestTimingFeature
 Microsoft.AspNetCore.Server.HttpSys.IHttpSysRequestTimingFeature.Timestamps.get -> System.ReadOnlySpan<long>
 Microsoft.AspNetCore.Server.HttpSys.IHttpSysRequestTimingFeature.TryGetElapsedTime(Microsoft.AspNetCore.Server.HttpSys.HttpSysRequestTimingType startingTimestampType, Microsoft.AspNetCore.Server.HttpSys.HttpSysRequestTimingType endingTimestampType, out System.TimeSpan elapsed) -> bool
 Microsoft.AspNetCore.Server.HttpSys.IHttpSysRequestTimingFeature.TryGetTimestamp(Microsoft.AspNetCore.Server.HttpSys.HttpSysRequestTimingType timestampType, out long timestamp) -> bool
+Microsoft.AspNetCore.Server.HttpSys.AuthenticationManager.CaptureCredential.get -> bool
```
Comment (amcasey) [inline src/Servers/HttpSys/src/PublicAPI.Unshipped.txt:39]: As @Tratcher pointed out, we'll need an API [issue](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=) for this.  Please link to this PR.

File: src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs [hunk 5]
```diff
@@ -400,6 +400,60 @@ public async Task AuthTypes_DisableAutomaticAuthentication(AuthenticationSchemes
...
+    {
+        using (var server = Utilities.CreateDynamicHost(out var address, options =>
+        {
+            options.Authentication.Schemes = authType;
+            options.Authentication.AllowAnonymous = DenyAnoymous;
+            options.Authentication.EnableKerberosCredentialCaching = true;
+        },
+        httpContext =>
+        {
+            // There doesn't seem to be a simple way of testing the `EnableKerberosCredentialCaching`
```
Comment (amcasey) [inline src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs:417]: I would have guessed there was a feature exposing the properties.  @Tratcher?

File: src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs [hunk 6]
```diff
@@ -599,10 +599,10 @@ internal struct HTTP_SERVER_AUTHENTICATION_INFO
     {
         internal HTTP_FLAGS Flags;
         internal HTTP_AUTH_TYPES AuthSchemes;
-        internal bool ReceiveMutualAuth;
-        internal bool ReceiveContextHandle;
-        internal bool DisableNTLMCredentialCaching;
-        internal ulong ExFlags;
+        internal byte ReceiveMutualAuth;
```
Comment (amcasey) [inline src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs:602]: I'd prefer to retain at least a comment indicating that it's boolean.

**Review by amcasey — COMMENTED** [review]
Please have a look at the merge conflicts.

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 2 above)
Comment (Tratcher) [reply src/Servers/HttpSys/src/AuthenticationManager.cs:77]: `CaptureProcessCredentials`

File: src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs (hunk 5 above)
Comment (Tratcher) [reply src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs:417]: There wouldn't be any meaningful properties. You'd have to check for things like the lack of an auth header on subsequent requests, while still having an authenticated user.

**Comment by evgenykotkov** [comment]
> Please have a look at the merge conflicts.

Done.

(With 7f18f8fea5c8e2efc26050f0815f8c911bb26ff1, the groundwork change c50346d52569c318f6a198f03d9e0a517cda8abe is no longer required, so I rebased the core change as bf884dca362eaf09c65f5d6591a39af8e36159e6.)

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 1 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: > I agree with @blowdart that it would be nice to give some indication of the lifetime of the cached credentials.

I made a slight adjustment of the docstring in db5b58074c51ee297c1ff5d2ec67bcf0c6a40515 to address this part. What do you think about the new description?

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 2 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: In 39edd844a70e4bc990fbaefd20f05f39e1cfdcd5, I went with the `CaptureCredentials` name for this option. Please let me know if it works for you.

File: src/Servers/HttpSys/src/PublicAPI.Unshipped.txt (hunk 4 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/PublicAPI.Unshipped.txt]: Will do.

File: src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs (hunk 5 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs:417]: > There wouldn't be any meaningful properties. You'd have to check for things like the lack of an auth header on subsequent requests, while still having an authenticated user.

The problem with meaningfully testing this option is that it needs a multi-machine setup in the AD, so that Kerberos would kick in. Because if the client is just looping back to itself, auth will happen through NTLM.

This might [change in the future](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-evolution-of-windows-authentication/ba-p/3926848) with the introduction of the local KDC. But for now I don't think there is a reliable way testing the full scenario, so I decided to go with a simple smoke test.

File: src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs (hunk 6 above)
Comment (evgenykotkov) [reply src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs]: > I'd prefer to retain at least a comment indicating that it's boolean.

With 7f18f8fea5c8e2efc26050f0815f8c911bb26ff1, this change seems to be no longer necessary for `main`.

However, since c50346d52569c318f6a198f03d9e0a517cda8abe seems to fix a rather significant issue with an invalid structure layout/size, is it something that should be backported to stable branches?

Please let me know if that is the case, and whether you'd want me to handle that with a separate PR or in any other convenient way.

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 3 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: > Do I understand correctly that this is a superset of `HttpServerAuthenticationProperty` and that's why the new `setProperty` call replaces the old one, rather than following it?

Yes, `HttpServerExtendedAuthenticationProperty` should set both the general authentication properties and the extended flags, so there's no need to chain calls — at least, this is what I observed in my experiments.

There aren't too many public examples that use this API, but for an independent confirmation I found a rather recent [proof-of-concept for the privilege escalation vulnerability in HTTP.sys](https://bugs.chromium.org/p/project-zero/issues/detail?id=2346) that configures all authentication options with a single `SetUrlGroupProperty(HttpServerExtendedAuthenticationProperty, …)` call.

File: src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs (hunk 6 above)
Comment (Tratcher) [reply src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs]: Can you demonstrate any negative effects from the old structure? We've not had any complaints here.

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 1 above)
Comment (amcasey) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: To confirm, that's "subsequent anonymous requests _on the same connection_"?

File: src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs (hunk 5 above)
Comment (amcasey) [reply src/Servers/HttpSys/test/FunctionalTests/AuthenticationTests.cs:417]: Oh, I thought getting to the property was the hard part.  If it requires a bunch of environment setup, then fair enough.

File: src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs (hunk 6 above)
Comment (evgenykotkov) [reply src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs]: > Can you demonstrate any negative effects from the old structure? We've not had any complaints here.

In my x64 environment, the native size of the structure is:
```
sizeof(HTTP_SERVER_AUTHENTICATION_INFO) == 64
```

In the same environment, the size of the interop structure before the fix is:
```
Marshal.SizeOf<HttpApiTypes.HTTP_SERVER_AUTHENTICATION_INFO> == 80
```

In turn, this means that:
1. The field layout is wrong after the `AuthSchemes` field
2. An invalid (larger) size is passed during the call to `HttpSetUrlGroupProperty()`

Maybe 1. hasn't been causing any practical issues because the current version of the code didn't change any structure fields after the `AuthSchemes`. But I would still say that 2. is quite significant just by itself: the behavior when passing an invalid size to the `HttpSetUrlGroupProperty()` function seems to be unspecified, and could have easily resulted in an error or even a crash.

In my environment the call seems to succeed, so from that perspective this remains a theoretical issue, but, to be precise, there is a chance that this behavior may change in the future or may differ depending on the OS version — I haven't checked that in detail.

-----

For reference, here is the native definition of the related typedefs and the structure itself:
```
typedef BYTE  BOOLEAN;
typedef unsigned char UCHAR;

typedef struct _HTTP_SERVER_AUTHENTICATION_INFO
{
    HTTP_PROPERTY_FLAGS Flags;

    ULONG AuthSchemes;

    BOOLEAN ReceiveMutualAuth;
    BOOLEAN ReceiveContextHandle;
    BOOLEAN DisableNTLMCredentialCaching;

    UCHAR   ExFlags;

    HTTP_SERVER_AUTHENTICATION_DIGEST_PARAMS DigestParams;
    HTTP_SERVER_AUTHENTICATION_BASIC_PARAMS  BasicParams;

} HTTP_SERVER_AUTHENTICATION_INFO, *PHTTP_SERVER_AUTHENTICATION_INFO;
```

Comment (Tratcher) [reply src/Shared/HttpSys/NativeInterop/HttpApiTypes.cs]: Ok, we won't consider backporting it without a repro of a functional issue. For now it's enough that the issue is gone in main.

File: src/Servers/HttpSys/src/AuthenticationManager.cs (hunk 1 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: > To confirm, that's "subsequent anonymous requests _on the same connection_"?

Yes. I tweaked the docstring accordingly in e2a327a6df7cec7ac7df37b59ff81e0f9309a89b.

File: src/Servers/HttpSys/src/PublicAPI.Unshipped.txt (hunk 4 above)
Comment (evgenykotkov) [reply src/Servers/HttpSys/src/PublicAPI.Unshipped.txt]: > As @Tratcher pointed out, we'll need an API [issue](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=) for this. Please link to this PR.

I created an API proposal: https://github.com/dotnet/aspnetcore/issues/51990

(For some reason it didn't get labeled as an `(api-suggestion)`, although I think I used an appropriate template. Could you  help me with adjusting that?)

**Comment by amcasey** [comment]
I think we're just waiting for an API review.

**Comment by amcasey** [comment]
API review asked for a rename.  Otherwise, we should be good to go.

**Comment by evgenykotkov** [comment]
> API review asked for a rename. Otherwise, we should be good to go.

Based on the discussion in https://github.com/dotnet/aspnetcore/issues/51990, I kept the original names and made a couple of tweaks to the docstrings.

(The CI run failed, but the failure looks unrelated and seems to happen in `main` as well, for example as in https://github.com/dotnet/aspnetcore/runs/21235887912)

File: src/Servers/HttpSys/src/AuthenticationManager.cs [hunk 7]
```diff
@@ -63,6 +64,25 @@ public bool AllowAnonymous
...
+    /// If true, the Kerberos authentication credentials are persisted per connection
+    /// and re-used for subsequent anonymous requests on the same connection.
+    /// Kerberos or Negotiate authentication must be enabled. The default is false.
+    /// This option maps to the native HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING flag.
+    /// <see href="https://learn.microsoft.com/en-us/windows/win32/api/http/ns-http-http_server_authentication_info"/>
+    /// </summary>
+    public bool EnableKerberosCredentialCaching { get; set; }
+
+    /// <summary>
+    /// If true, the server captures the current caller's credentials and impersonates
```
Comment (amcasey) [inline src/Servers/HttpSys/src/AuthenticationManager.cs:77]: This isn't my area of expertise, but I understood from @halter73's [comment](https://github.com/dotnet/aspnetcore/issues/51990#issuecomment-1832617112) that "current" was a confusing description of which credentials would be captured and that we should say something about using the host's credentials.  It seems like maybe you've said that in the next sentence, but then I'm not sure how to reconcile it with the first.  Maybe they could be combined?

> If true, credentials are captured from the security context of the thread that performs host initialization and used during Kerberos or Negotiate authentication.

Again, I don't actually know what that sentence means, I'm just comparing the text of multiple explanations. :wink:

Comment (amcasey) [reply src/Servers/HttpSys/src/AuthenticationManager.cs:77]: I like it!  Thanks for the explanation!

Comment (evgenykotkov) [reply src/Servers/HttpSys/src/AuthenticationManager.cs]: Committed in https://github.com/dotnet/aspnetcore/commit/a2885d991de74bce088652f5711dd1e8b0116ec8, thanks!

**Review by amcasey — APPROVED** [review]
