### PR TITLE
Fix race condition in EventTest.PreventDefault_DoNotApplyByDefault

### LINKED ISSUE #62533: Quarantine Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerEventTest.PreventDefault_DotNotApplyByDefault
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerEventTest.PreventDefault_DotNotApplyByDefault

## Error Message

```text
Assert.Contains() Failure: Sub-string not found
String:    "http://127.0.0.1:46631/subdir"
Not found: "about:blank"
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.PreventDefault_DotNotApplyByDefault() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/EventTest.cs:line 285
   at InvokeStub_EventTest.PreventDefault_DotNotApplyByDefault(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>

## Logs

<details>

```text
N/A
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082259&view=logs&j=5c945968-3a2e-573b-5d84-9df2797877cd&t=9b5db1c9-6a37-5ace-21ee-0f4c6c556658&s=d654deb9-056d-50a2-1717-90c08683d50a
https://dev.azure.com/dnceng-public/public/_build/results?buildId=1082259&view=logs&j=fe94c0c9-bb8c-5d6f-3b51-887173cc2f5c&t=b4bd3469-f776-5941-b623-568498d38bde&s=96ac2280-8cb4-5df5-99de-dd2da759617d

### PR DESCRIPTION
**Pull request by oroztocil**
The quarantined test was flaky due to a race condition. The assert failed when the test driver did not manage to change the URL in time.

I used a script to execute the test in a loop (on an M2 Mac):

- Before the change the test failed in 44/300 runs.
- After the change the test failed in 0/300 runs.

Fixes #62533

### CODE REVIEW

File: src/Components/test/E2ETest/Tests/EventTest.cs [hunk 1]
```diff
@@ -278,12 +278,14 @@ public void PreventDefault_AppliesToFormOnSubmitHandlers()
...
-    public void PreventDefault_DotNotApplyByDefault()
+    public void PreventDefault_DoNotApplyByDefault()
     {
         var appElement = Browser.MountTestComponent<EventPreventDefaultComponent>();
         appElement.FindElement(By.Id("form-2-button")).Click();
-        Assert.Contains("about:blank", Browser.Url);
+
+        // The URL should change because the submit event is not prevented
+        var wait = new WebDriverWait(Browser, TimeSpan.FromSeconds(3));
+        wait.Until(driver => driver.Url.Contains("about:blank"));
```
Comment (javiercn) [inline src/Components/test/E2ETest/Tests/EventTest.cs]: Check the extensions on `Browser` they centralize things like the wait times and stuff like that, it might be better to use those.

Comment (oroztocil) [reply src/Components/test/E2ETest/Tests/EventTest.cs]: Thanks for the suggestion. I looked into the existing extensions and did not find one that would cover this kind of wait, so I added one. Is it ok like this?

File: src/Components/test/E2ETest/Tests/EventTest.cs [hunk 2]
```diff
@@ -284,8 +284,7 @@ public void PreventDefault_DoNotApplyByDefault()
         appElement.FindElement(By.Id("form-2-button")).Click();
 
         // The URL should change because the submit event is not prevented
-        var wait = new WebDriverWait(Browser, TimeSpan.FromSeconds(3));
-        wait.Until(driver => driver.Url.Contains("about:blank"));
+        Browser.WaitForUrlToContain("about:blank");
```
Comment (javiercn) [inline src/Components/test/E2ETest/Tests/EventTest.cs]: I think so? But you can also search for Browser.Url usages and you might find an existing pattern.

**Review by javiercn — APPROVED** [review]
Another suggestion, but that's it

File: src/Components/test/E2ETest/Tests/EventTest.cs (hunk 2 above)
Comment (oroztocil) [reply src/Components/test/E2ETest/Tests/EventTest.cs]: Ok, there should be implicit waits for this with 'Browser.Contains' or 'Browser.True'. (I see now what extensions you meant.)

Comment (oroztocil) [reply src/Components/test/E2ETest/Tests/EventTest.cs]: I reverted the unneeded extension method.
