### PR TITLE
Signal IsCompleted from Response.BodyWriter after abort

### LINKED ISSUE #32331: After RequestAborted, Response.BodyWriter does not signal IsCompleted/IsCanceled
### Describe the bug
When RequestAborted occurs, code using Response.BodyWriter will not realize that the pipe is closed because **the pipe will silently discard writes** instead of signaling completion/cancellation.

Explicitly doing `BodyWriter.CancelPendingFlush()` is something of a workaround but if done after `RequestAborted` it only works under IIS Express, not when running standalone via Kestrel.

|                                              | IIS Express               | WebApp1.exe               |
|----------------------------------------------|---------------------------|---------------------------|
| RequestAborted -> FlushResult.IsCompleted    | No                        | No                        |
| CancelPendingFlush -> FlushResult.IsCanceled | Yes                       | No                        |
| WriteAsync() after request handler returns   | ObjectDisposedException   | InvalidOperationException |

My expectation is that at minimum `.IsCompleted` is true after request is aborted. I would strongly prefer `.CancelPendingFlush()` to still also signal `.IsCanceled` in such a case.

If the request handler method ends, PipeWriter will throw `ObjectDisposedException` or `InvalidOperationException` in any case, preventing this from being a resource leak but the lack of working IsCanceled or IsCompleted signaling in this situation does complicate writing clean code because of the extra wiring needed to "manually" detect end of response in the write loop before the request handler method ends - I would much prefer to wait for the write loop to tell my request handler when it is done and use that as my signal to end the request handler.

Tested with HTTP1, though I see similar code paths also in HTTP2 and HTTP3 implementations (`if (_streamCompleted) return default;` in `FlushAsync()`).

### To Reproduce
```csharp
[HttpGet]
public async Task Get()
{
    var writeLoop = Task.Run(() => WriteLoopAsync(Response.BodyWriter));

    // CancelPendingFlush() here has no effect except when started via IIS Express.
    using var registration = HttpContext.RequestAborted.Register(() => Response.BodyWriter.CancelPendingFlush());

    await writeLoop;
}

private async Task WriteLoopAsync(PipeWriter writer)
{
    var payload = Encoding.UTF8.GetBytes("hello, web browser" + new string(' ', 512) + "\n");

    while (true)
    {
        var result = await writer.WriteAsync(payload);

        if (result.IsCompleted || result.IsCanceled)
        {
            // The idea is to reach this point if the body writer pipe ends (either because of RequestAborted or other reason).
            // This is not reached on RequestAborted, though. The write loop keeps "successfully" writing.
            return;
        }

        await Task.Delay(TimeSpan.FromSeconds(1));
    }
}
```

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by senbar**
# After RequestAborted, Response.BodyWriter does not signal IsCompleted/IsCanceled

**In Progress!** - IIS fix in progress
Change logic returning FlushResult when interacting with OutputProducer to be more consistent. 
For now Changes fix only Kestrel case, with IIS I have problems debugging and can't find routine responsible for creating FlushResults

## Description

Add logic for keeping track of if output producer pending flush was canceled. Modify FlushResult returned by FlushAsync to retun IsCompleted and IsCanceled for if stream was completed and stream had pending flush canceled respectively. I implemented it on http 1 2 3 and have written tests for them. I am not sure if tests are in the correct classes so feel free to correct me here.

Fixes #32331

### CODE REVIEW

**Comment by senbar** [comment]
> This looks good at first glance. Why is this still a draft?

I think this only fixes the issue in kestrel case. Or does ISS express use kestrel namespace because to be honest I couldn't find the code responsible for writing to response stream in IIS namespace

**Comment by halter73** [comment]
Here's probably the code you should be looking at for IIS:

- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs#L155-L215
- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs#L279-L286
- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/IIS/IIS/src/Core/OutputProducer.cs#L53-L67

I haven't looked into what changes actually need to be made. If you get stuck on the IIS stuff, I'd be happy to just take the Kestrel stuff for now.

Thanks!

**Comment by halter73** [comment]
I think I see the issue. The problem is that IIS is still using a `StreamPipeWriter` which basically doesn't support `IsCompleted`. We might be able to fix this with a change to `StreamPipeWriter` in the https://github.com/dotnet/runtime repo. Or maybe we could consider exposing the `OutputProducer`s inner `PipeWriter` more directly. That'd probably be a lot of work though.

https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs#L185-L196

Is there anything else you think needs done on the Kestrel side before merging this?

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs [hunk 1]
```diff
@@ -143,7 +144,11 @@ public ValueTask<FlushResult> FlushAsync(CancellationToken cancellationToken = d
         {
             if (_pipeWriterCompleted)
             {
-                return default;
+                return new ValueTask<FlushResult>(new FlushResult(false, true));
+            }
+            if (_pendingFlushCanceled)
+            {
+                return new ValueTask<FlushResult>(new FlushResult(true, false));
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs:151]: Okay, so there is an issue with this. `CancelPendingFlush()` (and `CancelPendingRead()` FWIW) is not terminal. After returning the first `FlushResult`, it should be possible to flush again normally without it being immediately canceled.

Also, `CancelPendingFlush()` can be called before or during an ongoing flush. It should not prevent a flush from happening even if it's called first. It should just cause the flush to immediately return with a cancelled `FlushResult`. Then next call to `FlushAsync()` shouldn't return a cancelled `FlushResult` unless `CancelPendingFlush()` was called again.

I think this part should have been taken care of already by the call to `_pipeWriter.CancelPendingFlush();` Is it possible this was already behaving correctly, but the intended behavior wasn't well understood?

**Comment by senbar** [comment]
No, Kestrel part is implemented correctly I hope.

File: src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs [hunk 2]
```diff
@@ -54,6 +54,61 @@ public async Task WritesNoopAfterConnectionCloses()
...
+
+        await socketOutput.WriteDataAsync(new byte[] { 1, 2, 3, 4 }, default);
+        var successResult = await socketOutput.FlushAsync();
+        Assert.False(successResult.IsCanceled);
+
+        // Close
+        socketOutput.CancelPendingFlush();
+
+        await socketOutput.WriteDataAsync(new byte[] { 1, 2, 3, 4 }, default);
+        var cancelResult = await socketOutput.FlushAsync();
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs:105]:
```suggestion
        var cancelResult = await socketOutput.WriteDataToPipeAsync(new byte[] { 1, 2, 3, 4 }, default);
```

This was effectively double flushing before because it was calling the internal `WriteDataAsync` API that's called by `HttpResponse.Body` rather than `WriteDataToPipeAsync` that's called by `HttpRessponse.BodyWriter`.

I wonder if this is why you weren't seeing canceled `FlushResult`s  before this change. The second flush shouldn't be canceled as I mentioned earlier.

**Comment by halter73** [comment]
I think we should add functional tests to the following classes to verify the end to end.

- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs
- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs
- https://github.com/dotnet/aspnetcore/blob/82e6b60edbeb9c247d6e2b82ea69306eefb613f4/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs (hunk 1 above)
Comment (senbar) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs:151]: So i think the problem is that PipeFlusher either forgets that it has been cancelled or doesn't return correctly. I will look into that, converting this PR to draft for now

File: src/Servers/Kestrel/Core/test/Http1/Http1ConnectionTests.cs [hunk 3]
```diff
@@ -696,6 +696,38 @@ public async Task RequestAbortedTokenIsResetBeforeLastWriteAsyncWithContentLengt
...
+        var payload = Encoding.UTF8.GetBytes("hello, web browser" + new string(' ', 512) + "\n");
+        var writer = _application.Output;
+
+        var successResult= await writer.WriteAsync(payload);
+        Assert.False(successResult.IsCompleted);
+
+        _http1Connection.Abort(new ConnectionAbortedException());
+        var failResult= await _http1Connection.FlushPipeAsync(new CancellationToken());
+        Assert.True(failResult.IsCompleted);
+    }
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/Http1/Http1ConnectionTests.cs:711]: Nit:

```suggestion
    }

```

Can you also fix the formatting of the `=` signs in `var failResult= await _http1Connection.FlushPipeAsync(new CancellationToken());` and elsewhere?

File: src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs [hunk 4]
```diff
@@ -54,6 +54,64 @@ public async Task WritesNoopAfterConnectionCloses()
...
+        // Close
+        socketOutput.Dispose();
+
+        await socketOutput.WriteDataAsync(new byte[] { 1, 2, 3, 4 }, default);
+        var cancelResult = await socketOutput.FlushAsync();
+        Assert.True(cancelResult.IsCompleted);
+
+        socketOutput.Pipe.Writer.Complete();
+        socketOutput.Pipe.Reader.Complete();
+    }
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs:83]:
```suggestion
    }

```

File: src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs [hunk 5]
```diff
@@ -54,6 +54,64 @@ public async Task WritesNoopAfterConnectionCloses()
...
+        await socketOutput.WriteDataAsync(new byte[] { 1, 2, 3, 4 }, default);
+        var successResult = await socketOutput.FlushAsync();
+        Assert.False(successResult.IsCompleted);
+
+        // Close
+        socketOutput.Dispose();
+
+        await socketOutput.WriteDataAsync(new byte[] { 1, 2, 3, 4 }, default);
+        var cancelResult = await socketOutput.FlushAsync();
+        Assert.True(cancelResult.IsCompleted);
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/Http1/Http1OutputProducerTests.cs:79]:
```suggestion
        var completedResult = await socketOutput.FlushAsync();
        Assert.True(completedResult.IsCompleted);
```

**Review by halter73 — APPROVED** [review]
The tests look great! Thanks for doing this!

I just have a few formatting nits. There are a few other places in the tests that don't have a space before `=` that I didn't comment on.

**Comment by halter73** [comment]
> Should I leave the connection tests in or delete them?

Sorry for the slow response. Please, leave them. Thanks again @senbar

**Comment by senbar** [comment]
Thanks for code review @halter73 :) Fixed cosmetic changes, I am too used to IDE correcting these for me

**Comment by halter73** [comment]
Thanks again @senbar!
