### PR TITLE
ALWAYS include the Vary Accept-Encoding header when response compression is enabled

### LINKED ISSUE #48008: ALWAYS include the `Vary: Accept-Encoding` header when response compression is enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the response compression middleware only adds a `Vary: Accept-Encoding` header to the response, if and only if the request contains an `Accept-Encoding` header.

**This is wrong.** The `Vary: Accept-Encoding` header should be included in the response regardless of whether or not `Accept-Encoding` was part of the original request. This is because otherwise, if the very first request is one without the `Accept-Encoding` header (and by extension there is no `Vary: Accept-Encoding` in the response), an HTTP cache would not know that if a subsequent request came in that _did_ include an `Accept-Encoding` header, it should NOT use the previous cache entry to satisfy that request.

The value of the `Vary` header shouldn't be 'conditional' (for a request to the same URL). That's incorrect behavior and would cause issues especially with proxy caches (e.g. CDNs).

This principle is something that was explicitly pointed out in [this article by Fastly](https://www.fastly.com/blog/best-practices-using-vary-header#:~:text=Vary%3A%20Accept%2DEncoding**-,Note%20that%20the%20Vary%20header%20is%20present%20in%20the%20response%20regardless%20of%20whether%20or%20not%20compression%20is%20used.,-Why%20is%20this) — which is also mentioned in the [MDN page for `Vary`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary#see_also).

### Expected Behavior

The `Vary: Accept-Encoding` header should be included in every response whose `Content-Type` MIME type is supported by the response compression middleware, regardless of the presence of `Accept-Encoding` in the request.

This same principle also applies to any middleware that might add a value to the `Vary` header of the response, there could be some others in the ASP.NET Core codebase as well, although the response compression middleware is the one I stumbled into.

The relevant piece of code seems to be the following:
https://github.com/dotnet/aspnetcore/blob/86817b0c9fbb9b730bf3ce63da34b75570ee5696/src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs#L202-L225

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pedrobsaila**
# ALWAYS include the Vary Accept-Encoding header when response compression is enabled

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

ALWAYS include the Vary Accept-Encoding header when response compression is enabled

Fixes #48008

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@pedrobsaila Sorry for the longer-than-usual delay for getting things reviewed. This is still on our radar.

**Comment by pedrobsaila** [comment]
> Sorry for the longer-than-usual delay for getting things reviewed. This is still on our radar.

no worries

File: src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs [hunk 1]
```diff
@@ -218,12 +216,6 @@ public virtual bool ShouldCompressResponse(HttpContext context)
     /// <inheritdoc />
     public bool CheckRequestAcceptsCompression(HttpContext context)
```
Comment (BrennanConroy) [inline src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: While I like the simplicity of this change, it essentially makes `CheckRequestAcceptsCompression` useless, and the logs for requests without accept-encoding are a bit odd.

It might be better to change the ResponseCompressionMiddleware to handle including the vary header when not compressing the response.

Comment (pedrobsaila) [reply src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: I see there is another reviewed PR trying to fix the same issue, should I continue working on this PR o close it ?

Comment (BrennanConroy) [reply src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: I would prefer continuing with the fix on this PR if you're interested.

Comment (pedrobsaila) [reply src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: I duplicated the code from ResponseCompressionBody that sets Vary header in ResponseCompressionMiddleware. Should I move that code to the provider inside a new method so I can call it from both the body and middleware without duplication ?

Comment (BrennanConroy) [reply src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: > Should I move that code to the provider inside a new method so I can call it from both the body and middleware without duplication ?

Yeah that would be good, maybe something like `bool ShouldCompressResponseCommon(IResponseCompressionProvider, HttpConext)`?

Comment (BrennanConroy) [reply src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs:220]: Oh, sorry I didn't see you said move to the provider. We don't need any new public API surface for this, just make it a static private method and call it from both the middleware and `ResponseCompressionBody`

File: src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs [hunk 2]
```diff
@@ -34,13 +34,32 @@ public ResponseCompressionMiddleware(RequestDelegate next, IResponseCompressionP
     /// </summary>
     /// <param name="context">The <see cref="HttpContext"/>.</param>
     /// <returns>A task that represents the execution of this middleware.</returns>
-    public Task Invoke(HttpContext context)
+    public async Task Invoke(HttpContext context)
     {
         if (!_provider.CheckRequestAcceptsCompression(context))
         {
-            return _next(context);
+            var originalResponseFeature = context.Features.Get<IHttpResponseFeature>();
```
Comment (BrennanConroy) [inline src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs]: Should use `GetRequiredFeature` so we don't need the `Debug.Assert` and if somehow the feature isn't present, we'll get a nicer error than a `NullReferenceException`.

File: src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs [hunk 3]
```diff
@@ -34,13 +34,32 @@ public ResponseCompressionMiddleware(RequestDelegate next, IResponseCompressionP
...
+            Debug.Assert(originalResponseFeature != null);
+            originalResponseFeature.OnStarting(OnStartingResponseHandler, context);
+
+            try
+            {
+                await _next(context);
+            }
+            finally
+            {
+                context.Features.Set(originalResponseFeature);
```
Comment (BrennanConroy) [inline src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs]: This doesn't seem needed? We aren't changing the feature that's set on the `HttpContext`.

Can also remove `async` if we remove this.

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks for sticking with this @pedrobsaila!
