### PR TITLE
Fix preserving messages for stateful reconnect with backplane

### LINKED ISSUE #55575: Stateful reconnect doesn't work as expected when using Redis backplane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Stateful reconnect requires that both client and server calculate the same sequence Id so when the reconnect happen they can resume on the right message, but when using Redis as backplane a different code path is used, which ends up causing some messages not being accounted for in the server side and creating a discrepancy that leads to lost messages on reconnect.
The whole sequence Id calculation happens in MessageBuffer class, which increases the Id every time an invocation message is sent (in WriteAsyncCore), skipping the count otherwise. 

The problem is that when using Redis, the message comes as a SerializedHubMessage using a constructor that doesn't set the Message property, so when MessageBuffer tries to determine if it's an invocation message, `is` operator returns false as the message is null, and thus this message doesn't increment the sequence Id.
On the client side is read correctly, identified as an Invocation, and increments the sequence Id, create a discrepancy that will essentially break stateful reconnect.

### Expected Behavior

Sequence Id is kept in sync in both client side and server side. This is critical for stateful reconnect to work properly.

### Steps To Reproduce

1. Create a new SignalR core project, with Redis backplane.
2. Enable stateful reconnect on both client and server.
3. Send a message to all users (or a group), so it's sent through the backplane.
4. Observe how _totalMessageCount in MessageBuffer in server side is not incremented with SerializedHubMessage coming from Redis backplane.

### Exceptions (if any)

_No response_

### .NET Version

8.0.3

### Anything else?

The issue is pretty easy to spot once you know where to look.

Observe here how MessageBuffer.cs:124 expects Message property to be not null.
image

Observe here the constructor in SerializedHubMessage.cs:27 that is used by Redis backplane. No assignment of Message property.
image

Observe here how MessageBuffer.cs:161 checks message using `is` operator that will yield false as it is null, not incrementing the sequence Id as it should have.
image

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/55575

Changed `MessageBuffer.WriteAsync` methods to use the hub message type since that's the only information we're using in the method. And updated the `SerializedHubMessage` usage to assume we're sending a `HubInvocationMessage` since that's the only message type we currently use with `SerializedHubMessage`.

Updated tests:
* [`src/SignalR/server/SignalR/test/Microsoft.AspNetCore.SignalR.Tests/Internal/MessageBufferTests.cs`](diffhunk://#diff-a2a124e86f8258d8976412c33c8dcb74c6815ae284e3d6eb31c66c2ea258c4edR173-R228): Added a regression test to ensure unacknowledged serialized messages are resent on reconnect.

* [`src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs`](diffhunk://#diff-91d56b5d60716bde43cc90862fd23895195c4effe5fe6fc3365f34e38583f8e6L216-R312): Added a new E2E stateful reconnect test to verify that messages are preserved during reconnects and introduced a `WebSocketWrapper` class to simulate ungraceful closures. [[1]](diffhunk://#diff-91d56b5d60716bde43cc90862fd23895195c4effe5fe6fc3365f34e38583f8e6L216-R312) [[2]](diffhunk://#diff-91d56b5d60716bde43cc90862fd23895195c4effe5fe6fc3365f34e38583f8e6R326-R327) [[3]](diffhunk://#diff-91d56b5d60716bde43cc90862fd23895195c4effe5fe6fc3365f34e38583f8e6R356-R418)

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
Do we want to backport this?

**Comment by BrennanConroy** [comment]
Yeah, looks like a decent number of people have hit this.

File: src/SignalR/common/Shared/MessageBuffer.cs [hunk 1]
```diff
@@ -121,15 +121,16 @@ private async Task RunTimer()
 
     public ValueTask<FlushResult> WriteAsync(SerializedHubMessage hubMessage, CancellationToken cancellationToken)
     {
-        return WriteAsyncCore(hubMessage.Message!, hubMessage.GetSerializedMessage(_protocol), cancellationToken);
+        // Default to HubInvocationMessage as that's the only type we use SerializedHubMessage for currently. Should harden this in the future.
+        return WriteAsyncCore(hubMessage.Message?.GetType() ?? typeof(HubInvocationMessage), hubMessage.GetSerializedMessage(_protocol), cancellationToken);
```
Comment (halter73) [inline src/SignalR/common/Shared/MessageBuffer.cs:125]:
```suggestion
        return WriteAsyncCore(typeof(HubInvocationMessage), hubMessage.GetSerializedMessage(_protocol), cancellationToken);
```

If we're really confident with what the comment is saying, why not change it to the above? We could add a Debug.Assert that `hubMessage.Message is null || hubMessage.Message.GetType() == typeof(HubInvocationMessage)`.

File: src/SignalR/common/Shared/MessageBuffer.cs [hunk 2]
```diff
@@ -121,15 +121,16 @@ private async Task RunTimer()
 
     public ValueTask<FlushResult> WriteAsync(SerializedHubMessage hubMessage, CancellationToken cancellationToken)
     {
-        return WriteAsyncCore(hubMessage.Message!, hubMessage.GetSerializedMessage(_protocol), cancellationToken);
+        // Default to HubInvocationMessage as that's the only type we use SerializedHubMessage for currently. Should harden this in the future.
```
Comment (BrennanConroy) [inline src/SignalR/common/Shared/MessageBuffer.cs:124]:
```suggestion
        // Default to HubInvocationMessage as that's the only type we use SerializedHubMessage for currently when Message is null. Should harden this in the future.
```
