### PR TITLE
Follow-up for cancellation of navigation events in Blazor

### LINKED ISSUE #42877: [Blazor] Enable cancellation of navigation events
## Background and Motivation

The ability to asynchronously delay/cancel navigations in Blazor has been a [very popular ask](https://github.com/dotnet/aspnetcore/issues/14962) from the community. Such a feature would allow Blazor developers to implement custom navigation prompts, save changes before navigating, or silently cancel navigations. There was a [previous attempt](https://github.com/dotnet/aspnetcore/issues/40149) to solve this problem in a limited fashion by using `window.confirm()` to display a built-in browser prompt that lets the user confirm navigations. This approach works well for simple cases, but community feedback indicated a desire for a more flexible mechanism, namely a "location changing" event enabling asynchronous callbacks to decide whether a navigation should be allowed or cancelled.

## Proposed API

We provide new APIs on `NavigationManager` to add and remove "location changing" handlers that run when an "internal" navigation is initiated. These handlers are given a `LocationChangingContext` that provides information about the ongoing navigation in addition to a `PreventNavigation()` method that prevents the navigation from continuing when invoked. There can be multiple handlers registered that get executed in parallel, where any handler may prevent the navigation.

In addition, we also provide a `<NavigationLock/>` component that wraps the new `NavigationManager` APIs. It includes an option for showing a browser prompt for confirming "external" navigations. Note that external navigations will not cause "location changing" handlers to get invoked. This is because the `beforeunload` event (used to determine if a prompt should display before navigating) must return synchronously, so the result from an asynchronous JS -> .NET callback cannot be utilized.

**Note**: _These changes have already been implemented in #42638. A follow-up PR will address any API review feedback._

**Note**: All of the following APIs are purely additive. I didn't use the `+ ...` diff format because then you don't get syntax highlighting. `NavigationManager` is an existing class and all of the members listed here are new. The other two classes are entirely new.

```cs
namespace Microsoft.AspNetCore.Components;

public abstract class NavigationManager
{
    /// <summary>
    /// Adds a handler to process incoming navigation events.
    /// </summary>
    /// <param name="locationChangingHandler">The handler to process incoming navigation events.</param>
    public void AddLocationChangingHandler(Func<LocationChangingContext, ValueTask> locationChangingHandler);

    /// <summary>
    /// Removes a previously-added location changing handler.
    /// </summary>
    /// <param name="locationChangingHandler">The handler to remove.</param>
    public void RemoveLocationChangingHandler(Func<LocationChangingContext, ValueTask> locationChangingHandler);

    /// <summary>
    /// Notifies the registered handlers of the current location change.
    /// </summary>
    /// <param name="uri">The destination URI. This can be absolute, or relative to the base URI.</param>
    /// <param name="state">The state associated with the target history entry.</param>
    /// <param name="isNavigationIntercepted">Whether this navigation was intercepted from a link.</param>
    /// <returns>A <see cref="ValueTask{TResult}"/> representing the completion of the operation. If the result is <see langword="true"/>, the navigation should continue.</returns>
    protected ValueTask<bool> NotifyLocationChangingAsync(string uri, string? state, bool isNavigationIntercepted);

    /// <summary>
    /// Invokes the provided <paramref name="handler"/>, passing it the given <paramref name="context"/>.
    /// This method can be overridden to analyze the state of the handler task even after
    /// <see cref="NotifyLocationChangingAsync(string, string?, bool)"/> completes. For example, this can be useful for
    /// processing exceptions thrown from handlers that continue running after the navigation ends.
    /// </summary>
    /// <param name="handler">The handler to invoke.</param>
    /// <param name="context">The context to pass to the handler.</param>
    /// <returns></returns>
    protected virtual ValueTask InvokeLocationChangingHandlerAsync(Func<LocationChangingContext, ValueTask> handler, LocationChangingContext context);

    /// <summary>
    /// Sets whether navigation is currently locked. If it is, then implementations should not update <see cref="Uri"/> and call
    /// <see cref="NotifyLocationChanged(bool)"/> until they have first confirmed the navigation by calling
    /// <see cref="NotifyLocationChangingAsync(string, string?, bool)"/>.
    /// </summary>
    /// <param name="value">Whether navigation is currently locked.</param>
    protected virtual void SetNavigationLockState(bool value);
}
```

```cs
namespace Microsoft.AspNetCore.Components.Routing;

/// <summary>
/// Contains context for a change to the browser's current location.
/// </summary>
public class LocationChangingContext
{
    /// <summary>
    /// Gets the target location.
    /// </summary>
    public string TargetLocation { get; }

    /// <summary>
    /// Gets the state associated with the target history entry.
    /// </summary>
    public string? HistoryEntryState { get; }

    /// <summary>
    /// Gets whether this navigation was intercepted from a link.
    /// </summary>
    public bool IsNavigationIntercepted { get; }

    /// <summary>
    /// Gets a <see cref="System.Threading.CancellationToken"/> that can be used to determine if this navigation was canceled
    /// (for example, because the user has triggered a different navigation).
    /// </summary>
    public CancellationToken CancellationToken { get; }

    /// <summary>
    /// Prevents this navigation from continuing.
    /// </summary>
    public void PreventNavigation();
}

/// <summary>
/// A component that can be used to intercept navigation events. 
/// </summary>
public class NavigationLock : IComponent, IAsyncDisposable
{
    /// <summary>
    /// Gets or sets a callback to be invoked when an internal navigation event occurs.
    /// </summary>
    public EventCallback<LocationChangingContext> OnBeforeInternalNavigation { get; set; }

    /// <summary>
    /// Gets or sets whether a browser dialog should prompt the user to either confirm or cancel
    /// external navigations.
    /// </summary>
    public bool ConfirmExternalNavigation { get; set; }
}
```

### `<NavigationLock/>` Component

```razor
@inject IJSRuntime JSRuntime

<NavigationLock OnBeforeInternalNavigation="OnBeforeInternalNavigation" ConfirmExternalNavigation="true" />

@code {
    private async Task OnBeforeInternalNavigation(LocationChangingContext context)
    {
        // This just displays the built-in browser confirm dialog, but you can display a custom prompt
        // for internal navigations if you want.
        var isConfirmed = await JSRuntime.InvokeAsync<bool>("confirm", "Are you sure you want to continue?");

        if (!isConfirmed)
        {
            context.PreventNavigation();
        }
    }
}
```

### `NavigationManager` APIs

Useful in cases where the lifetime of a navigation lock is not constrained to the lifetime of a specific Blazor component.

## Risks

The implementation of this feature is quite involved (see #42638), and its asynchronous nature makes handling cases like overlapping navigations very non-trivial. However, we have ample test coverage for these scenarios, so we're reasonably confident in what we have. Code that doesn't use this feature won't be impacted by its existence; the entire "location changing" step is skipped unless there are handlers registered.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Follow-up for cancellation of navigation events in Blazor

This PR applies the changes discussed in the API review issue #42877.

## Description

Functionality remains almost completely the same as it did before, but now the API has changed in accordance with the API review for this feature. I'll point out any differences in behavior by commenting on this PR.

Fixes #42877

### CODE REVIEW

File: src/Components/Server/src/Circuits/RemoteNavigationManager.cs [hunk 1]
```diff
@@ -109,28 +109,18 @@ async Task PerformNavigationAsync()
             }
             catch (Exception ex)
             {
-                // We shouldn't ever reach this since exceptions thrown from handlers are caught in InvokeLocationChangingHandlerAsync.
+                // We shouldn't ever reach this since exceptions thrown from handlers are handled in HandleLocationChangingHandlerException.
                 // But if some other exception gets thrown, we still want to know about it.
                 Log.NavigationFailed(_logger, uri, ex);
+                UnhandledException.Invoke(this, ex);
```
Comment (campersau) [inline src/Components/Server/src/Circuits/RemoteNavigationManager.cs:115]: Does this also require a `null` check?

```suggestion
                UnhandledException?.Invoke(this, ex);
```

File: src/Components/Components/src/NavigationManager.cs [hunk 2]
```diff
@@ -335,12 +341,6 @@ protected async ValueTask<bool> NotifyLocationChangingAsync(string uri, string?
                     {
                         var handlerTask = InvokeLocationChangingHandlerAsync(locationChangingHandlersCopy[i], context);
 
-                        if (handlerTask.IsFaulted)
-                        {
-                            await handlerTask;
-                            return false; // Unreachable because the previous line will throw.
-                        }
-
```
Comment (MackinnonBuck) [inline src/Components/Components/src/NavigationManager.cs:343]: I've removed this logic because exceptions are now caught in `InvokeLocationChangingAsync` and handled via `HandleLocationChangingHandlerException`. In the Blazor Server case, this will end up terminating the circuit anyway. In the Blazor WebAssembly case where the exception is not treated as "fatal", we don't want to end up in a situation where we're surfacing the exception to both the caller of this method _and_ via `HandleLocationChangingHandlerException`. We could just remove the `await handlerTask` and still return early, but then we are deliberately overriding whatever cancellation decision the other handlers are destined to make. Hence the removal of this block entirely.

File: src/Components/Components/test/NavigationManagerTest.cs [hunk 3]
```diff
@@ -659,101 +660,63 @@ async ValueTask HandleLocationChanging(LocationChangingContext context)
     }
 
     [Fact]
-    public async Task LocationChangingHandlers_CanBubbleUpExceptionsSynchronously_WhenOneHandlerIsRegistered()
```
Comment (MackinnonBuck) [inline src/Components/Components/test/NavigationManagerTest.cs:662]: Tests verifying that exceptions bubble up through `NotifyLocationChangingAsync()` are no longer relevant because they're now handled in `HandleLocationChangingHandlerException()` instead. If we kept this original behavior, we would risk surfacing the exception in more than once place and logging more than once for the same exception.

To replace these tests, I've added some others that verify that `HandleLocationChangingHandlerException()` is properly invoked and exceptions are _not_ bubbled through `NotifyLocationChangingAsync()`.

**Review by halter73 — APPROVED** [review]

File: src/Components/Components/src/NavigationManager.cs [hunk 4]
```diff
@@ -398,17 +392,30 @@ protected async ValueTask<bool> NotifyLocationChangingAsync(string uri, string?
...
-    /// <param name="handler">The handler to invoke.</param>
-    /// <param name="context">The context to pass to the handler.</param>
-    /// <returns></returns>
-    protected virtual ValueTask InvokeLocationChangingHandlerAsync(Func<LocationChangingContext, ValueTask> handler, LocationChangingContext context)
-        => handler(context);
+    /// <param name="ex">The exception to handle.</param>
+    /// <param name="context">The context passed to the handler.</param>
+    protected virtual void HandleLocationChangingHandlerException(Exception ex, LocationChangingContext context)
+    {
+    }
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/NavigationManager.cs:418]: Would it work to have this throw by default? For example, `throw new InvalidOperation("NavigationManager subclasses must override HandleLocationChangingHandlerException in order to support navigation cancellation.")`

The intention is that subclasses are meant to override this if they will ever get into a situation where it might be called, isn't it? We don't want people to forget to do that and then just be ignoring exceptions without knowing about it.

I don't know whether throwing from here will result in the exception showing up, or whether it just gets swallowed above!

File: src/Components/Components/src/NavigationManager.cs [hunk 5]
```diff
@@ -420,10 +427,10 @@ protected virtual void SetNavigationLockState(bool value)
         => throw new NotSupportedException($"To support navigation locks, {GetType().Name} must override {nameof(SetNavigationLockState)}");
 
     /// <summary>
-    /// Adds a handler to process incoming navigation events.
+    /// Registers a handler to process incoming navigation events.
     /// </summary>
     /// <param name="locationChangingHandler">The handler to process incoming navigation events.</param>
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/NavigationManager.cs:432]: Technically there should be a `<returns>...</returns>` part of these XML docs now.

**Review by SteveSandersonMS — APPROVED** [review]
Nice one!

I added a couple of minor suggestions but besides that I think this feature looks all wrapped up :)

File: src/Components/Components/src/NavigationManager.cs (hunk 4 above)
Comment (MackinnonBuck) [reply src/Components/Components/src/NavigationManager.cs:418]: Sure, this seems good. It's just not guaranteed that `NavigationManager` subclass implementors would see this exception, because in order to see it they would need to:
1. Wrap the call to `NotifyLocationChangingAsync()` in a try/catch and do something useful to surface the exception.
2. Test the case where exceptions are thrown from location changing handlers.

Furthermore, exceptions thrown from `HandleLocationChangingHandlerException()` won't get caught for handlers that throw after `NotifyLocationChangingAsync()` returns.

That said, this does still seem like an improvement over swallowing exceptions silently by default.
