### PR TITLE
Ignore identical types when loading routable components

### LINKED ISSUE #38882: Duplicating Router.AppAssembly in AdditionalAssemblies causes confusing error
If you list the Router's `AppAssembly` the `AdditionalAssemblies` property then you get somewhat bizarre errors when you load the app.

```
<Router AppAssembly="@typeof(App).Assembly"
    AdditionalAssemblies="new[]{typeof(App).Assembly}">
   ...
```

This is what you see in a Blazor WebAssembly app in the browser console logs:

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)
window.Module.s.printErr @ blazor.webassembly.js:1
Te._internal.dotNetCriticalError @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.tj42mwroj7.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.tj42mwroj7.js:1
managed_BINDINGS_SetTaskSourceResult @ managed_BINDINGS_SetTaskSourceResult:17
(anonymous) @ dotnet.6.0.0.tj42mwroj7.js:1
Promise.then (async)
_wrap_js_thenable_as_task @ dotnet.6.0.0.tj42mwroj7.js:1
_js_to_mono_obj @ dotnet.6.0.0.tj42mwroj7.js:1
js_to_mono_obj @ dotnet.6.0.0.tj42mwroj7.js:1
Te._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0.tj42mwroj7.js:1
$func2588 @ 00945abe:0x8065b
$func2307 @ 00945abe:0x689a7
$func7015 @ 00945abe:0x17bac4
$func6830 @ 00945abe:0x172bc5
$func3524 @ 00945abe:0xb47cc
$func675 @ 00945abe:0x16602
$fb @ 00945abe:0x16f60e
Module._mono_wasm_invoke_method @ dotnet.6.0.0.tj42mwroj7.js:1
_call_method_with_converted_args @ dotnet.6.0.0.tj42mwroj7.js:1
call_method @ dotnet.6.0.0.tj42mwroj7.js:1
(anonymous) @ dotnet.6.0.0.tj42mwroj7.js:1
call_assembly_entry_point @ dotnet.6.0.0.tj42mwroj7.js:1
callEntryPoint @ blazor.webassembly.js:1
St @ blazor.webassembly.js:1
async function (async)
St @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An item with the same key has already been added. Key: BlazorApp3.Pages.Counter
System.ArgumentException: An item with the same key has already been added. Key: BlazorApp3.Pages.Counter
   at System.Collections.Generic.Dictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryInsert(Type key, String[] value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Add(Type key, String[] value)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(List`1 componentTypes)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey)
   at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass62_0.<RunOnNavigateAsync>b__1(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

Note that duplicating various additional assemblies in the list causes no harm and is just ignored:

```
<Router AppAssembly="@typeof(App).Assembly"
    AdditionalAssemblies="new[]{typeof(RazorClassLibrary1.Component2).Assembly, typeof(RazorClassLibrary1.Component2).Assembly}">
...
```

It would be nice to either ignore the duplicate assembly (meh), or perhaps have a better error message stating that the main app assembly can't be an additional assembly.

### PR DESCRIPTION
**Pull request by Silverdark**
# Ignore identical types when loading routable components

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Instead of using a `List` of types, I replaced it with a `HashSet` so that no duplicate entries are allowed when the routable components are loaded.

This issue does happen, if you specify the same assembly for the `AppAssembly` and the `AdditionalAssemblies`. It does not happen if you specify the same assembly multiple times for `AdditionalAssemblies`, as this is already a `HashSet`.

Fixes #38882

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=39129) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=39129) before we can accept your contribution.<br/><br/>:x: Silverdark [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=39129)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=39129) it.</sub>

**Comment by Silverdark** [comment]
Just checked the failing test actions

> Using member 'System.Reflection.Assembly.ExportedTypes.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.

I really don't know why, but this occurs only when using the `HashSet`. When I replace it with a simple `Contains` condition, the tests are working fine (locally). For me this is strange, as in both cases `assembly.ExportedTypes` will be used.

```csharp
foreach (var type in assembly.ExportedTypes)
{
    if (typeof(IComponent).IsAssignableFrom(type) && type.IsDefined(typeof(RouteAttribute)))
    {
        if (!routeableComponents.Contains(type)) // <-- This part here
        {
            routeableComponents.Add(type);
        }
    }
}
```

File: src/Components/Components/src/Routing/RouteTableFactory.cs [hunk 1]
```diff
@@ -56,7 +56,10 @@ static void GetRouteableComponents(List<Type> routeableComponents, Assembly asse
             {
                 if (typeof(IComponent).IsAssignableFrom(type) && type.IsDefined(typeof(RouteAttribute)))
                 {
-                    routeableComponents.Add(type);
+                    if (!routeableComponents.Contains(type))
```
Comment (pranavkm) [inline src/Components/Components/src/Routing/RouteTableFactory.cs:59]: This is going to do a linear scan isn't it? Could you tell me what the error was when you used a HashSet instead? 

An alternative fix is to de-dupe AppAssembly and AdditionalAssemblies. Essentially you could check on line 44 if `assembly != routeKey.AppAssembly` before calling `GetRouteableComponents`

Comment (Silverdark) [reply src/Components/Components/src/Routing/RouteTableFactory.cs]: > Could you tell me what the error was when you used a HashSet instead?

The tests are failing with the following reason ([example in Azure DevOps](https://dev.azure.com/dnceng/public/_build/results?buildId=1521937&view=logs&j=5ac7b393-e840-5549-7fb4-a4479af8e7e3&t=29df2fa2-0d20-51bd-e85a-8b546e86c529&l=1506)):

> Using member 'System.Reflection.Assembly.ExportedTypes.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.

I just replaced the `List` with a `HashSet` and adjusted other references in the [commit](https://github.com/dotnet/aspnetcore/pull/39129/commits/bbb9dbe1ef7085e2e820b4d4d51045398749ed5f), but it was failing.

> An alternative fix is to de-dupe AppAssembly and AdditionalAssemblies.

This would also be possible, will change the PR to that solution.

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Thanks!
