### PR TITLE
Unify publish/test mvc.testing functionality + switch to helix for mvc functional tests

### LINKED ISSUE #10423: [Helix] enable Microsoft.AspNetCore.Mvc.FunctionalTests
src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj

This test project does not work in Helix and is currently disabled because it has a dependency on the layout of the source code in this repo.

Recommendation for updating: see aspnet/Extensions#1697

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/dotnet/aspnetcore/issues/27296
Fixes https://github.com/dotnet/aspnetcore/issues/10423

This PR is looking into the running tests in the publish directory (aka helix style) path

Current state/open questions:
- Adds a ForPublish bool to the build task which allows customization of the expected publish outputs (assumption that the AppDomain.BaseDirectory would work).
- When running dotnet test Mvc.FunctionalTests.dll, it can't seem to find any tests to run, I'm not sure if there are some differences in MVC's functional tests as compared to the identity functional tests which are similar style but currently work when directly run after publishing (and are helix enabled), the main difference is it only has a single website which it copies the views/deps file during publish: see https://github.com/dotnet/aspnetcore/blob/master/src/Identity/test/Identity.FunctionalTests/Microsoft.AspNetCore.Identity.FunctionalTests.csproj#L60
- Currently after running dotnet publish on Mvc functionals, it dumps all the website dll/pdbs into the base publish directory, is that what we want?  Or should each content root end up in its own subdirectory?

@javiercn @pranavkm @captainsafia

### CODE REVIEW

**Comment by HaoK** [comment]
Also it looks like one wrinkle in the publish side of things that the build piece doesn't have, is exactly how to easily package up the various test websites.  It'd be nice if we don't have to do one of those clunky publish assets blocks (like in Identity functionals) per test website for MVC functionals to work.

**Comment by HaoK** [comment]
@captainsafia we might need to revisit the logic we use to gather dependencies too, as the manifest seems to be including everything, not just websites, for example the manifest contains all of the AspNetCore assemblies which doesn't seem like something we should be putting into the manifest

**Comment by captainsafia** [comment]
> @captainsafia we might need to revisit the logic we use to gather dependencies too, as the manifest seems to be including everything, not just websites, for example the manifest contains all of the AspNetCore assemblies which doesn't seem like something we should be putting into the manifest, i.e.:

@javiercn and @pranavkm might have a better intuition on whether this is done intentionally or of it is problematic. We didn't change the logic that computes `ContentRootReferences` as part of the last PR or this one so this has likely been the behavior for a while. Given this and since it is part of a public API, I think it's fine to keep the same behavior.

**Comment by HaoK** [comment]
So some progress, with the latest changes I'm able to publish and run dotnet test locally in the publish output, and all but 12 tests pass.

The first thing I had to do, was make all the error websites that had compilation errors compile, or dotnet publish on the functional test project would fail.  This mostly meant the ErrorPageMiddleware and RazorBuildTests had to be corrected, so those failures are expected.  The other set of failures seem to be HtmlGenerationTets which now have a different path from what the assertions expect, I'm not sure what's going on there.

**Comment by HaoK** [comment]
It looks like I was able to get away with simply specifying the content root as the publish base directory and copying all the .deps.json files of all the website directories in a publish post step into the publish dir, and that makes things mostly just work

**Comment by HaoK** [comment]
> In CI or locally? I recall I've been able to run locally...

I'm simulating what helix does by dotnet publish then running dotnet test against the dll in the publish directory, dotnet test in the sources works (as that's the existing build/dev/non helix scenario)

File: src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs [hunk 1]
```diff
@@ -117,7 +117,7 @@ public async Task CompilationFailuresFromViewImportsAreListed()
             // Arrange
             var expectedMessage = "The type or namespace name &#x27;NamespaceDoesNotExist&#x27; could not be found ("
                 + "are you missing a using directive or an assembly reference?)";
-            var expectedCompilationContent = "public class Views_ErrorFromViewImports_Index : "
+            var expectedCompilationContent = "Views_ErrorFromViewImports_Index : "
```
Comment (HaoK) [inline src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs:120]: This is another bit of weirdness, when running in the publish directory, the name of the generated class has a leading _, i.e. "_Views_", so a hack is trimming the expected to eliminate the public class part...  @pranavkm any ideas why this difference might occur when running from the publish directory (as opposed to in the sources)

File: src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs [hunk 2]
```diff
@@ -96,6 +108,50 @@ public async Task EnumValues_SerializeCorrectly()
             Assert.Equal($"Vrijdag{Environment.NewLine}Month: FirstOne", response, ignoreLineEndingDifferences: true);
         }
 
+        [ConditionalTheory]
+        [MemberData(nameof(WebPagesDataNonHelix))]
+        [SkipOnHelix("https://github.com/dotnet/aspnetcore/issues/10423")]
+        public async Task HtmlGenerationWebSite_GeneratesExpectedResultsNotReadyForHelix(string action, string antiforgeryPath)
```
Comment (HaoK) [inline src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:114]: Note: I'm splitting out the 2 scenarios which currently don't work on helix from this main PR, and we can look into reenabling these in a follow up PR since its just 3 tests

**Comment by HaoK** [comment]
Functional tests are all passing on helix now!  Had to skip a few tests for now, will follow up with a separate PR to look into reenabling link/script tags.

File: src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs (hunk 1 above)
Comment (pranavkm) [reply src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs:120]: It's possible that the ContentRoot is missing a trailing slash. for e.g

```
Content Root: /foo/bar
View: /foo/bar/Views/Index.cshtml

Relative path: /Views/Index.cshtml
```

which would result in the underscore.

File: src/Mvc/samples/MvcSandbox/MvcSandbox.csproj [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
   <PropertyGroup>
     <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
+    <PreserveCompilationContext>true</PreserveCompilationContext>
```
Comment (pranavkm) [inline src/Mvc/samples/MvcSandbox/MvcSandbox.csproj:5]: Do you need this? We're not testing runtime compilation with the sandbox

File: src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets [hunk 4]
```diff
@@ -46,6 +46,16 @@
     </ItemGroup>
   </Target>
 
+  <Target Name="_GeneratePublishTestManifest" BeforeTargets="Publish" DependsOnTargets="_ResolveMvcTestProjectReferences">
+    <ItemGroup>
+      <_ManifestProjects Include="%(_ContentRootProjectReferences.FusionName)">
+        <ContentRoot>$([System.IO.Path]::GetDirectoryName(%(_ContentRootProjectReferences.MSBuildSourceProjectFile)))</ContentRoot>
```
Comment (pranavkm) [inline src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets:52]: Could this be `~`? Then you wouldn't need an extra property in the task.

File: src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets [hunk 5]
```diff
@@ -46,6 +46,16 @@
     </ItemGroup>
   </Target>
 
+  <Target Name="_GeneratePublishTestManifest" BeforeTargets="Publish" DependsOnTargets="_ResolveMvcTestProjectReferences">
+    <ItemGroup>
+      <_ManifestProjects Include="%(_ContentRootProjectReferences.FusionName)">
```
Comment (pranavkm) [inline src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets:51]: You might want to use a different item name. e.g. `_PublishManfestProject` or something like that. The current itemgroup would have elements added as part of `PrepareResources`

File: src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs [hunk 6]
```diff
@@ -192,7 +192,8 @@ private string GetContentRootFromFile(string file)
             var key = typeof(TEntryPoint).Assembly.GetName().FullName;
             try
             {
-                return data[key];
+                // For publish scenarios, ~ should be expanded to the base directory
+                return data[key].Replace("~", AppContext.BaseDirectory);
```
Comment (pranavkm) [inline src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:196]: Should this perform an exact match (look exactly for `~`)? I would also consider using `TryGetValue`. It's weird that it attempts to catch an exception

```C#
if (!data.TryGetValue(key, out var contentRoot))
{
   throw new KeyNotFoundException($"Could not find content root for project '{key}' in test manifest file '{file}'");
}

if (contentRoot == "~")
{
    contentRoot = AppContext.BaseDirectory;
}
```

File: src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets (hunk 4 above)
Comment (HaoK) [reply src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets:52]: Good point, this used to do something like `~/assemblyname` but now that everything is flat in the base dir, its no longer needed

File: src/Mvc/samples/MvcSandbox/MvcSandbox.csproj (hunk 3 above)
Comment (HaoK) [reply src/Mvc/samples/MvcSandbox/MvcSandbox.csproj:5]: We need this just to get the deps file over which is required by the WebApplicationFactory which throws if its not found... :shrug:

File: src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs (hunk 1 above)
Comment (HaoK) [reply src/Mvc/test/Mvc.FunctionalTests/ErrorPageTests.cs:120]: Ok I will try setting the content root to ~/ and see if this is fixed

File: src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs [hunk 7]
```diff
@@ -118,26 +114,34 @@ public async Task HtmlGenerationWebSite_GeneratesExpectedResults(string action,
...
+                    expectedContent = string.Format(CultureInfo.InvariantCulture, expectedContent, forgeryToken);
+                    Assert.Equal(expectedContent.Trim(), responseContent, ignoreLineEndingDifferences: true);
+                }
             }
         }
 
+        [ConditionalTheory]
+        [InlineData("Link", null)]
+        [InlineData("Script", null)]
+        [SkipOnHelix("https://github.com/dotnet/aspnetcore/issues/10423")]
```
Comment (pranavkm) [inline src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:141]: Not going to block, but does this work now that the content root is correct? Just in case that caused these tests to weird out.

**Review by pranavkm — APPROVED** [review]

**Review by pranavkm — APPROVED** [review]

File: src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs (hunk 7 above)
Comment (HaoK) [reply src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:141]: Ah good point, I will try that in the next iteration, I need to try running these on the arm queues too anyways before merging, since I vaguely recall functional tests like this not working at all on arm queues due to some publishing quirks

Comment (HaoK) [reply src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:141]: Looks like the content root can't have a trailing '/' as the FileProviders throw with that appended.  Is there a different place where we can add the / so the file resolution stuff deals with it properly?

File: .azure/pipelines/helix-matrix.yml [hunk 8]
```diff
@@ -1,5 +1,9 @@
 # We only want to run full helix matrix on master
-pr: none
```
Comment (HaoK) [inline .azure/pipelines/helix-matrix.yml:2]: revert before merge

File: src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj [hunk 9]
```diff
@@ -60,4 +58,31 @@
...
+      <_PublishFiles Include="$(ArtifactsBinDir)RazorPagesWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\RazorPagesWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)RazorWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\RazorWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)SecurityWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\SecurityWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)SimpleWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\SimpleWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)TagHelpersWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\TagHelpersWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)VersioningWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\VersioningWebSite.deps.json" />
+      <_PublishFiles Include="$(ArtifactsBinDir)XmlFormattersWebSite\$(Configuration)\$(DefaultNetCoreTargetFramework)\XmlFormattersWebSite.deps.json" />
+    </ItemGroup>
+    <Copy SourceFiles="@(_PublishFiles)" DestinationFolder="$(PublishDir)" />
```
Comment (javiercn) [inline src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj:85]: Is there no other way to do this?

I would like this to work without any hacks on the project. Ideally Mvc.Testing should take care of this since part of the goal of changing it is to enable customers to do the same things we do.

Comment (HaoK) [reply src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj:85]: That would be ideal indeed, do you have any suggestions to make this work?  Should the build task when publishing harvest all the deps and copy them to the publish directory?  That's basically the only step missing right now.

Comment (HaoK) [reply src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj:85]: Test failures on arm look unrelated so I'm going to get the first iteration of this PR in which at least gets things running on helix, Identity functional tests already have this hack to copy over stuff, the next PR will address this and fixing the script/link tests that are disabled

**Comment by HaoK** [comment]
Merging this as first checkpoint as it gets Functional tests onto helix, will follow up with a new PR addressing test failures and trying to get rid of the publish crud in csproj
