### PR TITLE
Use System.Text.Json's source generated code to deserialize WebEvents

### LINKED ISSUE #32357: System.InvalidOperationException when using touch events (TouchEventArgs) in Blazor with ASP.NET Core in .NET 6 Preview 3
### Describe the bug
When ASP.NET Core in .NET 6 Preview 3 tries to deserialize the browsers "TouchEventArgs" a System.InvalidOperationException is thrown.

### To Reproduce
I created a basic blazor webassembly app with .NET 6 preview 3 and hooked up an 'ontouchmove' event handler in the MainLayout.razor to log the ClientX Position of the touch event. This works perfectly when starting from debugger or 'dotnet watch' and simulating touch event by using e.g. Chrome dev tools.

When I publish the app to github pages or use another static file server I get an InvalidOperationException whenever blazor tries to parse the TouchEventArgs (this happens whenever I "touch around" on the page).

I tested and reproduced this bug with Chrome, Edge and Firefox.
Note: In Firefox sometimes the console does not output the error right away (nor the console log that should be visible). Refreshing Firefox wiht Ctrl + F5 make the exception appear (after "touching around" again).

The published page is available here: https://lambrech.github.io/BasicBlazorWebAssemblyPwaGithubPagesApp/
Code can be found here: https://github.com/lambrech/BasicBlazorWebAssemblyPwaGithubPagesApp

FYI: I tested this with .NET 5 and it works even after publishing.

### Exceptions (if any)
Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '1'.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.AspNetCore.Components.Web.TouchPoint Path: $.touches[0] | LineNumber: 0 | BytePositionInLine: 24.
 ---> System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute, Microsoft.AspNetCore.Components.Web.TouchPoint
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.Web.TouchPoint, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchPoint& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.TouchPoint, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchPoint& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2[[Microsoft.AspNetCore.Components.Web.TouchPoint[], Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.Web.TouchPoint, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchPoint[]& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.TouchPoint[], Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchPoint[]& value)
   at System.Text.Json.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.Web.TouchPoint[], Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.Web.TouchEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchEventArgs& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.TouchEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TouchEventArgs& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.TouchEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TouchEventArgs](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TouchEventArgs](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TouchEventArgs](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TouchEventArgs](String json, JsonSerializerOptions options)
   at Microsoft.AspNetCore.Components.Web.WebEventData.Deserialize[TouchEventArgs](String json)
   at Microsoft.AspNetCore.Components.Web.WebEventData.TryDeserializeStandardWebEventArgs(String eventName, String eventArgsJson, EventArgs& eventArgs)
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, UInt64 eventHandlerId, String eventName, String eventArgsJson)
   Exception_EndOfInnerExceptionStack
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, UInt64 eventHandlerId, String eventName, String eventArgsJson)
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer renderer, WebEventDescriptor eventDescriptor, String eventArgsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.DispatchEvent(WebEventDescriptor eventDescriptor, String eventArgsJson)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)

### Further technical details
- ASP.NET Core version: .NET 6 Preview 3

### PR DESCRIPTION
**Pull request by pranavkm**
Also address missing "type" property on TouchEvent

Fixes https://github.com/dotnet/aspnetcore/issues/32357

### CODE REVIEW

File: src/Components/Shared/src/WebEventData.cs [hunk 1]
```diff
@@ -218,13 +250,12 @@ private static bool TryDeserializeStandardWebEventArgs(string eventName, string
             return null;
         }
 
-        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "The correct members are preserved by DynamicDependencies.")]
         // This should use JSON source generation
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventData.cs:253]: You can remove this comment now

File: src/Components/Shared/src/WebEventData.cs [hunk 2]
```diff
@@ -243,5 +274,25 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
             }
             return changeArgs;
         }
+
+#nullable disable
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventData.cs:278]: Why is this necessary?

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs [hunk 3]
```diff
@@ -35,7 +38,12 @@ public static Task DispatchEvent(WebEventDescriptor eventDescriptor, string even
         {
             var renderer = RendererRegistry.Find(eventDescriptor.BrowserRendererId);
             var jsonSerializerOptions = DefaultWebAssemblyJSRuntime.Instance.ReadJsonSerializerOptions();
-            var webEvent = WebEventData.Parse(renderer, jsonSerializerOptions, eventDescriptor, eventArgsJson);
+
+            // JsonSerializerOptions are tightly bound to the JsonContext. Cache it on first use using a copy
+            // of the serializer settings.
+            _jsonContext ??= new(new JsonSerializerOptions(jsonSerializerOptions));
```
Comment (eerhardt) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:44]: Why the double wrapped JsonSerializerOptions?

File: src/Components/Shared/src/WebEventData.cs (hunk 2 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:278]: The file is shared between 3 projects which have different nullability enforcements. This causes issues with the source generated files. Turning it off seems like an easy workaround for the time being.

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs (hunk 3 above)
Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:44]: It looks like if you call `new JsonContext(jsonSerializerOptions)` it's tied to that instance of JsonContext. We use these serializer options extensively for other serialization and I wanted to leave the default one "untouched".

Comment (eerhardt) [reply src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:44]: Might be good to add that as a comment.

File: src/Components/Shared/src/WebEventData.cs (hunk 2 above)
Comment (eerhardt) [reply src/Components/Shared/src/WebEventData.cs:278]: Might be good to add that as a comment.

File: src/Components/Shared/src/WebEventData.cs [hunk 4]
```diff
@@ -60,28 +85,35 @@ private WebEventData(int browserRendererId, ulong eventHandlerId, EventFieldInfo
...
-                if (TryDeserializeStandardWebEventArgs(eventName, eventArgsJson, out var eventArgs))
+                if (TryDeserializeStandardWebEventArgs(eventName, eventArgsJson, jsonSerializerContext, out var eventArgs))
                 {
                     return eventArgs;
                 }
 
                 // For custom events, the args type is determined from the associated delegate
                 var eventArgsType = renderer.GetEventArgsType(eventHandlerId);
-                return (EventArgs)JsonSerializer.Deserialize(eventArgsJson, eventArgsType, jsonSerializerOptions)!;
+                return (EventArgs)JsonSerializer.Deserialize(eventArgsJson, eventArgsType, jsonSerializerContext.Options)!;
```
Comment (layomia) [inline src/Components/Shared/src/WebEventData.cs:104]: Why's an options instance passed here instead of the context?

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs (hunk 3 above)
Comment (eerhardt) [reply src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:44]: cc @layomia - any concerns here that the `JsonSerializerOptions` object gets mutated when passed to a `new JsonContext`?

File: src/Components/Shared/src/WebEventData.cs (hunk 4 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:104]: In this case, the types being deserialized are user types and don't appear in the Blazor's internal context. Having to flow the user's context here would have been one of the sticking points in this API since a user would be responsible for ensuring arbitrary events that appear in their app as well as arbitrary libraries they reference are present in the context they can provide to Blazor.

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs (hunk 3 above)
Comment (layomia) [reply src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:44]: We have discussed allowing a one to many relationship between one options instance and multiple context instances, which would make using the `jsonSerializerOptions` itself possible. I'll bring it up in the next review so we can close on it.

However, it would still be optimal to make an options instance immutable (wrt serialization configuration, e.g. `PropertyNameCaseInsensitive`) once it has been bound with one or more context instances so that we can initialize the metadata reliably (knowing that the options won't change).

File: src/Components/Shared/src/WebEventData.cs (hunk 4 above)
Comment (layomia) [reply src/Components/Shared/src/WebEventData.cs:104]: > a user would be responsible for ensuring arbitrary events that appear in their app as well as arbitrary libraries they reference are present in the context they can provide to Blazor

For users in the ecosystem that are motivated enough, could we encourage library authors expose context types for events that they define, and then users could union their context types either manually or with a new API that we can provide?

Comment (layomia) [reply src/Components/Shared/src/WebEventData.cs:104]: Also, if the event types are public, then users could indicate them as `JsonSerializable` in their own assemblies and the gen'd context  would contain all the needed event types. This way there's no reliance of lib authors exposing their context type soon after .NET 6.0.

Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:104]: We'll work on custom events as a follow up.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 5]
```diff
@@ -24,6 +25,7 @@ internal class CircuitHost : IAsyncDisposable
         private readonly ILogger _logger;
         private bool _initialized;
         private bool _disposed;
+        private JsonSourceGeneration.JsonContext _jsonContext;
```
Comment (eerhardt) [inline src/Components/Server/src/Circuits/CircuitHost.cs:28]: In `JSInteropMethods`, you made the JsonContext `static`, but here and in `IpcReceiver` it is an instance based field. Was there a reason for the difference?

**Review by eerhardt — APPROVED** [review]
This looks good to me.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 5 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: @eerhardt Are we allowed to treat `JsonSourceGeneration.JsonContext` as thread-safe?

Possibly that's the reason for the distinction but I'm not sure. @pranavkm can confirm!

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: Oh actually I think I see why it's done like this.

Each circuit has its own distinct `ElementReferenceJsonConverter` instance because it's hooked up to some state within the circuit (a circuit-local sequence of IDs so you don't disclose info about other circuits). This means the JSON serialization options are per-circuit, which in turn means the JSON context is now per-circuit.

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: Also note that `JSInteropMethods` is within the WebAssembly project, so it's not part of the Blazor Server circuits concept and can freely make things `static` (it's a single-user environment that doesn't have to hide info about other users).

File: src/Components/Shared/src/WebEventData.cs [hunk 6]
```diff
@@ -244,5 +273,28 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
             }
             return changeArgs;
         }
+
+#nullable disable
+        // WebView has different nullability settings compared to Server and WebAssembly
+        // which weirds out JSON's nullability for these types. Disable nullability for this contract
+        // until we can update everything to haave uniform nullability.
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/WebEventData.cs:280]: That's unexpected and awkward. Is it just a mistake we made, or do you think there's a reason we wanted it to be different?

File: src/Components/Server/src/JsonContext.cs [hunk 7]
```diff
@@ -0,0 +1,12 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System.Text.Json.Serialization;
+using Microsoft.AspNetCore.Components.Web;
+
+namespace Microsoft.AspNetCore.Components.Server.JsonSourceGeneration
+{
+    internal partial class JsonContext : JsonSerializerContext, WebEventData.IWebEventJsonSerializerContext
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/JsonContext.cs:9]: Is this just to make sure we don't pass the wrong context type (since they all have the same name and are hard to distinguish in source code), or for a more complex reason?

File: src/Components/Shared/src/WebEventData.cs [hunk 8]
```diff
@@ -6,21 +6,42 @@
...
+[assembly: JsonSerializable(typeof(ClipboardEventArgs))]
+[assembly: JsonSerializable(typeof(DragEventArgs))]
+[assembly: JsonSerializable(typeof(ErrorEventArgs))]
+[assembly: JsonSerializable(typeof(FocusEventArgs))]
+[assembly: JsonSerializable(typeof(KeyboardEventArgs))]
+[assembly: JsonSerializable(typeof(MouseEventArgs))]
+[assembly: JsonSerializable(typeof(PointerEventArgs))]
+[assembly: JsonSerializable(typeof(ProgressEventArgs))]
+[assembly: JsonSerializable(typeof(TouchEventArgs))]
+[assembly: JsonSerializable(typeof(WheelEventArgs))]
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/WebEventData.cs:27]: I thought we now had support for putting this attribute on the type itself. Is that not the case? Or do you consider it preferable to put it on the assembly for some reason?

File: src/Components/WebView/WebView/src/IpcReceiver.cs [hunk 9]
```diff
@@ -89,7 +91,10 @@ private Task DispatchBrowserEventAsync(PageContext pageContext, string eventDesc
         {
             var renderer = pageContext.Renderer;
             var jsonSerializerOptions = pageContext.JSRuntime.ReadJsonSerializerOptions();
-            var webEventData = WebEventData.Parse(renderer, jsonSerializerOptions, eventDescriptor, eventArgs);
+            // JsonSerializerOptions are tightly bound to the JsonContext. Cache it on first use using a copy
+            // of the serializer settings.
+            _jsonContext ??= new(new JsonSerializerOptions(jsonSerializerOptions));
```
Comment (SteveSandersonMS) [inline src/Components/WebView/WebView/src/IpcReceiver.cs:96]: This seems slightly suboptimal in that it's calling `pageContext.JSRuntime.ReadJsonSerializerOptions()` even when a value is already cached for `_jsonContext`.

Could it skip that call in that case? Same for the other places where this pattern is used.

File: src/Components/test/testassets/BasicTestApp/TouchEventComponent.razor [hunk 10]
```diff
@@ -7,7 +7,8 @@
         Output: <span id="output">@message</span>
     </p>
     <p>
-        <button @ontouchstart=OnTouch
+        <button id="touch_input"
+                @ontouchstart=OnTouch
```
Comment (SteveSandersonMS) [inline src/Components/test/testassets/BasicTestApp/TouchEventComponent.razor:11]: Nice

File: src/Components/WebView/WebView/src/IpcReceiver.cs (hunk 9 above)
Comment (SteveSandersonMS) [reply src/Components/WebView/WebView/src/IpcReceiver.cs:96]: e.g., something like this, which it seems you already do in other places:

```cs
// var jsonSerializerOptions = pageContext.JSRuntime.ReadJsonSerializerOptions(); // Can be removed
_jsonContext ??= new(new JsonSerializerOptions(pageContext.JSRuntime.ReadJsonSerializerOptions()));
```

**Review by SteveSandersonMS — APPROVED** [review]

File: src/Components/Shared/src/WebEventData.cs (hunk 8 above)
Comment (layomia) [reply src/Components/Shared/src/WebEventData.cs:27]: Following API review on Friday (https://github.com/dotnet/runtime/issues/51945#issuecomment-841456779). We're updating the design such that the user provides a partial context class as a kick off for source generation, rather than generating one for them out of the ether. This will come in preview 5, so it might be better for this PR to wait (to get new bits and also so we can get your feedback)...

> - Instead of generating a single JsonContext type per assembly, we should let the user define the JsonContext type (controlling namespace, type name, etc.) and apply the assembly level attributes to this type and have the generator fill in the body of the body. This allows the user to have multiple different JSON options for different types in a single assembly, e.g.
Fabrikam.Telemetry.TelemetryJsonContext
Fabrikam.Shopping.ShoppingJsonContext

With this model, your context definition might look like this:

```cs
[JsonSerializable(typeof(WebEventDescriptor))]
[JsonSerializable(typeof(EventArgs))]
[JsonSerializable(typeof(ChangeEventArgs))]
...
partial class WebEventDataJsonContext: JsonSerializerContext {}
```

The `JsonSerializable` attribute is now applied to context `class`es only. If we allow it directly on a contract type, then we'd have to include generated source for the type in every context definition across all assemblies. I imagine this would be undesirable in many scenarios.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 5 above)
Comment (layomia) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: > Are we allowed to treat JsonSourceGeneration.JsonContext as thread-safe?

The intent is that it is thread-safe & any issues here would be addressed.

Comment (pranavkm) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: Yeah, this isn't about thread safety. Like @SteveSandersonMS said, the JsonSerializerOptions are circuit-scoped in Blazor server, consequently the context has to be too.

File: src/Components/Shared/src/WebEventData.cs (hunk 6 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:280]: I think it might have been an oversight - the WebView2 project have nullable=annotations. My hope is to make all source projects have nullable=enabled in p6: https://github.com/dotnet/aspnetcore/pull/32742.

File: src/Components/Server/src/JsonContext.cs (hunk 7 above)
Comment (pranavkm) [reply src/Components/Server/src/JsonContext.cs:9]: You get slightly better typing with this approach. In the absence of this, you have to call `JsonSerializer.Serialize(string, Type, JsonContext)` which would result in a runtime error if the `JsonContext` does not know of the type. 

With this contract, the shared contract is in defined in WebEventData.cs and lets you do `JsonSerializer.Serialize<MyType>(string, JsonPropertyInfo<MyType>)` which feels a bit nicer.

File: src/Components/Shared/src/WebEventData.cs (hunk 8 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:27]: Oh neat. I might wait for this update to land before merging this change in. 

> This will come in preview 5

Did you mean preview 6 since p5 locks down soon

Comment (layomia) [reply src/Components/Shared/src/WebEventData.cs:27]: > Did you mean preview 6 since p5 locks down soon

It's easier for me to include it in the PR for https://github.com/dotnet/runtime/issues/51945 which is targeted for P5. I've notified folks on the runtime end that I might need a couple more days and go through ask-mode to backport it.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 5 above)
Comment (eerhardt) [reply src/Components/Server/src/Circuits/CircuitHost.cs:28]: Makes sense. Thanks for the explanation.

File: src/Components/Shared/src/WebEventData.cs [hunk 11]
```diff
@@ -245,4 +258,22 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
             return changeArgs;
         }
     }
+
+    [JsonSerializable(typeof(WebEventDescriptor), GenerationMode = JsonSourceGenerationMode.Serialization)]
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventData.cs:262]: @layomia - using `JsonSourceGenerationMode.Serialization` means we only generate the "fast path" and not the "metadata".

What does this mean when we only support serialization right now, and not deserialization? Does it mean for deserialization it falls back to Reflection.Emit based deserialization?

File: src/Components/Shared/src/WebEventJsonContext.cs [hunk 12]
```diff
@@ -0,0 +1,10 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System.Text.Json.Serialization;
+using Microsoft.AspNetCore.Components.RenderTree;
+
+namespace Microsoft.AspNetCore.Components.Web
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventJsonContext.cs:7]: Do we need this file?

File: src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.WarningSuppressions.xml [hunk 13]
```diff
@@ -17,7 +17,7 @@
       <argument>ILLink</argument>
       <argument>IL2026</argument>
       <property name="Scope">member</property>
-      <property name="Target">M:Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Microsoft.AspNetCore.Components.RenderTree.Renderer,System.Text.Json.JsonSerializerOptions,System.UInt64,System.String,System.String)</property>
+      <property name="Target">M:Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Microsoft.AspNetCore.Components.RenderTree.Renderer,Microsoft.AspNetCore.Components.Web.WebEventJsonContext,System.UInt64,System.String,System.String)</property>
```
Comment (eerhardt) [inline src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.WarningSuppressions.xml:20]: Is this entry still needed? I don't see what this method is doing that RequiresUnreferencedCode.

Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.WarningSuppressions.xml:20]: I haven't gotten around to making this work for the deserialization of custom event args. That continues to use the reflection-based Serialize overload.

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs [hunk 14]
```diff
@@ -35,7 +38,15 @@ public static Task DispatchEvent(WebEventDescriptor eventDescriptor, string even
         {
             var renderer = RendererRegistry.Find(eventDescriptor.BrowserRendererId);
             var jsonSerializerOptions = DefaultWebAssemblyJSRuntime.Instance.ReadJsonSerializerOptions();
-            var webEvent = WebEventData.Parse(renderer, jsonSerializerOptions, eventDescriptor, eventArgsJson);
+
+            // JsonSerializerOptions are tightly bound to the JsonContext. Cache it on first use using a copy
+            // of the serializer settings.
+            if (_jsonContext is null)
+            {
+                _jsonContext = new(new JsonSerializerOptions(jsonSerializerOptions));
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:46]: Can we move the `ReadJsonSerializerOptions` call inside this `if` block so it's only done once? Super minor detail I know, but helps to clarify that we only respect its value the first time, and it can't change after.

File: src/Components/WebView/WebView/src/IpcReceiver.cs [hunk 15]
```diff
@@ -89,7 +91,14 @@ private Task DispatchBrowserEventAsync(PageContext pageContext, string eventDesc
         {
             var renderer = pageContext.Renderer;
             var jsonSerializerOptions = pageContext.JSRuntime.ReadJsonSerializerOptions();
-            var webEventData = WebEventData.Parse(renderer, jsonSerializerOptions, eventDescriptor, eventArgs);
+            // JsonSerializerOptions are tightly bound to the JsonContext. Cache it on first use using a copy
+            // of the serializer settings.
+            if (_jsonContext is null)
+            {
+                _jsonContext = new(new JsonSerializerOptions(jsonSerializerOptions));
```
Comment (SteveSandersonMS) [inline src/Components/WebView/WebView/src/IpcReceiver.cs:98]: Same here about moving the `ReadJsonSerializerOptions` call.

**Review by SteveSandersonMS — APPROVED** [review]
Nice!

**Comment by SteveSandersonMS** [comment]
@pranavkm Is there already an issue filed about handling this for custom event args?

File: src/Components/Shared/src/WebEventData.cs (hunk 11 above)
Comment (layomia) [reply src/Components/Shared/src/WebEventData.cs]: To use generated code for deserialization and avoiding Ref.Emit today, the setting would need to be `JsonSourceGenerationMode.MetadataAndSerialization`. The serializer would fallback to generated code that references setters and getters directly.

To make configuration here cleaner, we could change the enum to a flags enum:

```cs
[Flags]
public enum JsonSourceGenerationMode
{
  Unspecified = 0,
  Metadata = 1,
  Serialization = 2,
  Deserialization = 4, // Future
}
```

When we have fast-path logic for both read and write, the preferred setting for simple scenarios would be `Serialization | Deserialization`.

File: src/Components/Shared/src/WebEventData.cs [hunk 16]
```diff
@@ -245,4 +258,22 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
             return changeArgs;
         }
     }
+
+    [JsonSerializable(typeof(WebEventDescriptor), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(WebEventDescriptor), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
```
Comment (layomia) [inline src/Components/Shared/src/WebEventData.cs:263]: nit: this is a duplicate of the LOC above. Probably an error case the generator should catch since the mode could be different and the intention would be unclear. We'd throw or use last-one-wins..

File: src/Components/Shared/src/WebEventData.cs [hunk 17]
```diff
@@ -245,4 +258,22 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
...
+    [JsonSerializable(typeof(DragEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(ErrorEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(FocusEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(KeyboardEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(MouseEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(PointerEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(ProgressEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(TouchEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(WheelEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    internal sealed partial class WebEventJsonContext : JsonSerializerContext
```
Comment (layomia) [inline src/Components/Shared/src/WebEventData.cs:276]: It looks like it would be cleaner to have a global `JsonSourceGenerationMode` option per context:

```cs
public class JsonSourceGenerationModeAttribute : JsonAttribute
{
    public JsonSourceGenerationModeAttribute(JsonSourceGenerationMode mode) { }
}
```

Building on https://github.com/dotnet/aspnetcore/pull/32374#discussion_r646622868, we'd have

```cs
[JsonSourceGenerationMode(JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
[JsonSerializable(typeof(WebEventDescriptor)]
[JsonSerializable(typeof(EventArgs)]
internal sealed partial class WebEventJsonContext : JsonSerializerContext
{
}
```

`[JsonSerializable]` instances with an `Unspecified` mode would fallback to the context-global mode.

File: src/Components/Shared/src/WebEventData.cs [hunk 18]
```diff
@@ -245,4 +258,22 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
             return changeArgs;
         }
     }
+
+    [JsonSerializable(typeof(WebEventDescriptor), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
```
Comment (eerhardt) [inline src/Components/Shared/src/WebEventData.cs:262]: Is there a reason you aren't just letting it default the "GenerationMode"?

```suggestion
    [JsonSerializable(typeof(WebEventDescriptor)]
```

File: src/Components/Shared/src/WebEventData.cs [hunk 19]
```diff
@@ -245,4 +258,22 @@ private static ChangeEventArgs DeserializeChangeEventArgs(string eventArgsJson)
...
+    [JsonSerializable(typeof(ClipboardEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(DragEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(ErrorEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(FocusEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(KeyboardEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(MouseEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(PointerEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(ProgressEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(TouchEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
+    [JsonSerializable(typeof(WheelEventArgs), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
```
Comment (pranavkm) [inline src/Components/Shared/src/WebEventData.cs:275]:
```suggestion
    [JsonSerializable(typeof(WebEventDescriptor))]
    [JsonSerializable(typeof(WebEventDescriptor))]
    [JsonSerializable(typeof(EventArgs))]
    [JsonSerializable(typeof(ChangeEventArgs))]
    [JsonSerializable(typeof(ClipboardEventArgs))]
    [JsonSerializable(typeof(DragEventArgs))]
    [JsonSerializable(typeof(ErrorEventArgs))]
    [JsonSerializable(typeof(FocusEventArgs))]
    [JsonSerializable(typeof(KeyboardEventArgs))]
    [JsonSerializable(typeof(MouseEventArgs))]
    [JsonSerializable(typeof(PointerEventArgs))]
    [JsonSerializable(typeof(ProgressEventArgs))]
    [JsonSerializable(typeof(TouchEventArgs))]
    [JsonSerializable(typeof(WheelEventArgs))]
```

File: src/Components/Shared/src/WebEventData.cs (hunk 17 above)
Comment (pranavkm) [reply src/Components/Shared/src/WebEventData.cs:276]: That does seem like a better alternative. It feels unusual to want fine-grained control over the serialization behavior on a per-type basis. That said, I imagine most users wouldn't really configure this since the extra IL for serialization isn't really noticeable.

File: src/Components/WebView/WebView/src/IpcReceiver.cs [hunk 20]
```diff
@@ -89,7 +91,14 @@ private Task DispatchBrowserEventAsync(PageContext pageContext, string eventDesc
         {
             var renderer = pageContext.Renderer;
             var jsonSerializerOptions = pageContext.JSRuntime.ReadJsonSerializerOptions();
```
Comment (pranavkm) [inline src/Components/WebView/WebView/src/IpcReceiver.cs:93]:
```suggestion
```

File: src/Components/WebView/WebView/src/IpcReceiver.cs (hunk 15 above)
Comment (pranavkm) [reply src/Components/WebView/WebView/src/IpcReceiver.cs:98]:
```suggestion
                var jsonSerializerOptions = pageContext.JSRuntime.ReadJsonSerializerOptions();
                _jsonContext = new(new JsonSerializerOptions(jsonSerializerOptions));
```

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs [hunk 21]
```diff
@@ -35,7 +38,15 @@ public static Task DispatchEvent(WebEventDescriptor eventDescriptor, string even
         {
             var renderer = RendererRegistry.Find(eventDescriptor.BrowserRendererId);
             var jsonSerializerOptions = DefaultWebAssemblyJSRuntime.Instance.ReadJsonSerializerOptions();
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:40]:
```suggestion
```

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs (hunk 14 above)
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/JSInteropMethods.cs:46]:
```suggestion
                var jsonSerializerOptions = DefaultWebAssemblyJSRuntime.Instance.ReadJsonSerializerOptions();
                _jsonContext = new(new JsonSerializerOptions(jsonSerializerOptions));
```
