### PR TITLE
Suppress log when request is cancelled

### LINKED ISSUE #8696: Wrong error logging when a client cancels the request
### Describe the bug
When a client cancels the web request(closing a browser for instance) the request is cancelled with a help of the `CancelationToken`. Everything works fine but this log line is written into the log file:
```
2019-03-19T08:37:13.093+00:00 [17] ERR Microsoft.AspNetCore.Server.HttpSys.HttpSysListener [/main] - ResponseStream::Dispose; Fewer bytes were written than were specified in the Content-Length.
```

The reason is this line in the `ResponseBody` class: https://github.com/aspnet/AspNetCore/blob/5f4be179e3bf6d88a53667935fc5c4bd2d71988c/src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs#L131

This line is executed when a server calls Dispose on the `ResponseBody` instance and in general it is good have this check. But now it should have a distinction between the normal flow and the flow when a client is not connected anymore.

### To Reproduce
--

### Expected behavior
There should not be an error log like this:
```
2019-03-19T08:37:13.093+00:00 [17] ERR Microsoft.AspNetCore.Server.HttpSys.HttpSysListener [/main] - ResponseStream::Dispose; Fewer bytes were written than were specified in the Content-Length.
```

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes #8696

### CODE REVIEW

File: src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs [hunk 1]
```diff
@@ -127,8 +127,11 @@ private unsafe void FlushInternal(bool endOfRequest, ArraySegment<byte> data = n
             if (endOfRequest && _leftToWrite > 0)
             {
                 _requestContext.Abort();
-                // This is logged rather than thrown because it is too late for an exception to be visible in user code.
-                LogHelper.LogError(Logger, "ResponseStream::Dispose", "Fewer bytes were written than were specified in the Content-Length.");
+                if (!RequestContext.DisconnectToken.IsCancellationRequested)
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: This check will always give the same result because Abort cancels the token, you'd never get the log now.
https://github.com/aspnet/AspNetCore/blob/78b9b2e23e7709cef6659b11e7e0b266f7a1089f/src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs#L172
At the very least it should be reversed to log before Aborting.
You also need to consider the lazy creation logic for DisconnectToken. If nobody requested the token before it was cancelled you might end up with an uncancellable token.
https://github.com/aspnet/AspNetCore/blob/78b9b2e23e7709cef6659b11e7e0b266f7a1089f/src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs#L47
There might be room for improvement there, such as ensuring a token created after cancellation is created in the canceled state.

**Review by Tratcher — CHANGES_REQUESTED** [review]

File: src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs (hunk 1 above)
Comment (Kahbazi) [reply src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: I put the logging before Abort and as you said I need to make some changes on DisconnectToken.

I used this code

```
CancellationTokenSource cts = new CancellationTokenSource();
string address;
using (Utilities.CreateHttpServer(out address, async httpContext =>
{
    httpContext.Response.Headers["Content-length"] = " 30 ";
    await httpContext.Response.Body.WriteAsync(new byte[10], 0, 10);
    cts.Cancel();
}))
{
    using (HttpClient client = new HttpClient())
    {
        await client.GetAsync(address, cts.Token);
    }
}
```
to hit the FlushInternal and check DisconnectToken. In this scenario if I skip this if statement 
https://github.com/aspnet/AspNetCore/blob/78b9b2e23e7709cef6659b11e7e0b266f7a1089f/src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs#L55
I would get the correct cancellation token, but I couldn't figure out what condition I should add or remove from if statement, to make this work.

What I'm about to suggest is probably wrong since it changes the result on this test
https://github.com/aspnet/AspNetCore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Servers/HttpSys/test/FunctionalTests/Listener/ServerTests.cs#L49
and may also have other consequences that I'm not aware of, but is it possible to swap `_disposed = true;` and  `FlushInternal(endOfRequest: true);`
https://github.com/aspnet/AspNetCore/blob/320c4b055656b88240cd198b2f40f1f5f0f4ccb3/src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs#L672-L673

Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: If you swap _disposed and FlushInternal you'd have to make sure to handle error conditions from FlushInternal such that _disposed still gets set. E.g. put the dispose in a finally block.

Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: Actually that might not be an issue. FlushInternal calls Abort which sets _disposed.

File: src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs [hunk 2]
```diff
@@ -126,9 +126,12 @@ private unsafe void FlushInternal(bool endOfRequest, ArraySegment<byte> data = n
             var flags = ComputeLeftToWrite(data.Count, endOfRequest);
             if (endOfRequest && _leftToWrite > 0)
             {
+                if (!RequestContext.DisconnectToken.IsCancellationRequested)
+                {
+                    // This is logged rather than thrown because it is too late for an exception to be visible in user code.
+                    LogHelper.LogError(Logger, "ResponseStream::Dispose", "Fewer bytes were written than were specified in the Content-Length.");
```
Comment (jkotalik) [inline src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: @Kahbazi can you write a unit test to verify this behavior? Or is there a race and it makes it hard to write a test.

Comment (Tratcher) [reply src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs]: I plan to try some manual verification before merging this. I don't know if DisconnectToken.IsCancellationRequested is consistent enough in these scenarios for this to work as expected.

**Review by Tratcher — APPROVED** [review]
This works at least as well as DisconnectToken. There's room for future improvement in DisconnectToken where requesting it for the first time after the disconnect returns an uncancellable token rather than a cancelled one.

**Comment by Tratcher** [comment]
Thanks
