### PR TITLE
Fix null reference errors in tests

### LINKED ISSUE #22992: Fix `nullable` warnings when building test code
``` text
UsePathBaseExtensionsTests.cs(57,62): warning CS8613: Nullability of reference types in return type of 'IDictionary<string, object> ApplicationBuilderWrapper.Properties.get' doesn't match implicitly implemented member 'IDictionary<string, object?> IApplicationBuilder.Properties.get'. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
UseWhenExtensionsTests.cs(114,60): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(51,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(52,72): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(66,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(78,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(90,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPredicateMiddlewareTests.cs(102,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(42,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(43,72): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(60,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(88,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(116,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(132,92): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(146,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(168,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
MapPathMiddlewareTests.cs(182,67): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
UsePathBaseExtensionsTests.cs(166,60): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
UsePathBaseExtensionsTests.cs(57,62): warning CS8619: Nullability of reference types in value of type 'IDictionary<string, object?>' doesn't match target type 'IDictionary<string, object>'. [...\src\Http\Http.Abstractions\test\Microsoft.AspNetCore.Http.Abstractions.Tests.csproj]
DefaultAntiforgeryTokenStoreTest.cs(167,40): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.Test.csproj]
DefaultAntiforgeryTokenStoreTest.cs(194,40): warning CS8625: Cannot convert null literal to non-nullable reference type. [...\src\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.Test.csproj]
```

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/22992

### CODE REVIEW

**Comment by pranavkm** [comment]
I'm half tempted to turn off nullability warnings from tests. They are useful to help "figure out" the implementation at times, but not particularly high value. We could consider that if this is a recurrent problem.

File: src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs [hunk 1]
```diff
@@ -39,8 +39,8 @@ private static void UseNotImplemented(IApplicationBuilder app)
         [Fact]
         public void NullArguments_ArgumentNullException()
         {
-            var builder = new ApplicationBuilder(serviceProvider: null);
-            var noMiddleware = new ApplicationBuilder(serviceProvider: null).Build();
+            var builder = new ApplicationBuilder(serviceProvider: null!);
+            var noMiddleware = new ApplicationBuilder(serviceProvider: null!).Build();
```
Comment (dougbu) [inline src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs:43]: Suggestion only: Seem to be working around the nullability of this constructor parameter a fair amount. Might be easier to either provide a default constructor or allow `null` in this constructor for testing purposes. Either way, shouldn't need to change the type of the `ApplicationServices` property (though it's odd the `ApplicationBuilder` properties aren't nullable given `GetProperty(...)` can return `null`).

**Review by dougbu — APPROVED** [review]
Eight warnings from tasks outside `msbuild`. Wahoo 🥇

File: src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs (hunk 1 above)
Comment (pranavkm) [reply src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs:43]: @Tratcher, what do you think? https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http/src/Builder/ApplicationBuilder.cs#L22

Comment (pranavkm) [reply src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs:43]: I guess I can do that in a follow up. Let's get this PR in

Comment (Tratcher) [reply src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs:43]: The API is very inconsistent.

1. Adding a parameterless constructor would simplify usage in tests.
2. ApplicationServices_Get should return a static no-op instance rather than null.
3. ServerFeatures should also return a read-only no-op instance.

Comment (pranavkm) [reply src/Http/Http.Abstractions/test/MapPathMiddlewareTests.cs:43]: Captured this in a separate feedback. https://github.com/dotnet/aspnetcore/issues/23232.
