### PR TITLE
Fix StackOverflowException in RoutePatternAnalyzer

### LINKED ISSUE #48097: RoutePatternAnalyzer causes stack overflow on C# file with a lot of string operations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A file with a lot of string `+` operations (generated code) causes a stack overflow in the route pattern analyzer.

https://github.com/dotnet/aspnetcore/blob/a5833f771a387df53bb0cc71a99c36e5b38c728d/src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs#L52

### Expected Behavior

clean compile

### Steps To Reproduce

```
git clone https://github.com/timmydo/dotnet8p3analyzer1.git
cd dotnet8p3analyzer1
dotnet build
```

### Exceptions (if any)

```
$ dotnet build
MSBuild version 17.6.0-preview-23174-01+e7de13307 for .NET
  Determining projects to restore...
  Restored D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj (in 83 ms).
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\tmp\t2\dotnet8p3analy
zer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : Stack overflow. [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : Repeat 1425 times: [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : -------------------------------- [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error :    at Microsoft.AspNetCore.Analyzers.RouteEmbeddedLanguage.RoutePatternAnalyzer.Analyze(Microsoft.CodeAnalysis.Diagnostics.SemanticModelAnalysisContext, Microsoft.C
odeAnalysis.SyntaxNode, Microsoft.AspNetCore.App.Analyzers.Infrastructure.WellKnownTypes, Microsoft.AspNetCore.App.Analyzers.Infrastructure.RouteUsageCache, System.Threading.CancellationToken) [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : -------------------------------- [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\Roslyn\Microsoft.CSharp.Core.targets(80,5): error :    at Microsoft.AspNetCore.Analyzers.RouteEmbeddedLanguage.RoutePatternAnalyzer.AnalyzeSemanticModel(Microsoft.CodeAnalysis.Diagnostics.SemanticModelAnalysisContext
) [D:\tmp\t2\dotnet8p3analyzer1\dotnet8p3.csproj]
```

### .NET Version

8.0.100-preview.3.23178.7

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/48097

Change semantic model analysis to use a `Stack<T>` instead of recursion. This removes the possibility of running out of stack and causing a stack overflow in files with deeply nested node graphs.

### CODE REVIEW

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs [hunk 1]
```diff
@@ -31,94 +31,96 @@ private void AnalyzeSemanticModel(SemanticModelAnalysisContext context)
...
         {
-            if (child.IsNode)
-            {
-                Analyze(context, child.AsNode()!, wellKnownTypes, routeUsageCache, cancellationToken);
-            }
-            else
+            cancellationToken.ThrowIfCancellationRequested();
+            var current = stack.Pop();
+
+            foreach (var child in current.ChildNodesAndTokens())
```
Comment (cston) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: >foreach (var child in current.ChildNodesAndTokens()) [](http://example.com/codeflow?start=12&length=52)

It looks like the analysis is only interested in tokens, so the loops could be replaced with `foreach (var token in root.DescendantTokens()) { ... }`.

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: The code I added follows what the Regex analyzer does. I investigated why the regex analyzer doesn't use `DecendantTokens`. I think it could have, but the recently added `FilteredSpans` check wouldn't work with the helper method:

https://github.com/dotnet/roslyn/blob/4dcbb0bdb9f7630fec6ce81b311525ef974fd4b0/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs#L63-L64

It looks like `FilteredSpans` has only just been made public. aspnetcore probably won't update to bits with it until after .NET 8. I'd like to leave the method as is so using FilteredSpans in the future is possible.

Btw, what are filtered spans? I'm guessing it's an optimization but I'd be interested if you could point me at an example of it.

**Review by mitchdenny — APPROVED** [review]

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs (hunk 1 above)
Comment (cston) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: Adding @mavasani for the question on filtered spans.

Comment (mavasani) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: FilterSpan is the new API added on analysis context types when computing diagnostics for lightbulb. This allows expensive analyzers to optimize their performance based on the span within the tree for which diagnostics are being computed. If the analyzer ignores this span, the analyzer driver will filter the reported diagnostics outside this span, there should be no functional impact of ignoring this filter span.

**Review by amcasey — APPROVED** [review]

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs (hunk 1 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: This analyzer is expensive. Do you recommend eventually using filter span [like other analyzers are doing](https://github.com/dotnet/roslyn/blob/4dcbb0bdb9f7630fec6ce81b311525ef974fd4b0/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs#L63-L64)?

Comment (mavasani) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: Definitely - all SemanticModelAnalysisContext callbacks should respect the filter span. I plan to write a meta-analyzer in Microsoft.CodeAnalysis.Analyzers package to recommend the same. These analyzers are known to be the biggest beneficiaries of this API on lightbulb path.

Comment (jaredpar) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: I do not understand why `DescendantTokens` is in compatible with `FilteredSpans`. It can be implemented by passing down the predicate correct? Having every analyzer / generator out there build their own stack for navigating the tree to scan tokens is **not** the right solution.

@333fred

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:45]: I see there is a `DescendantTokens` overload that takes a span: https://github.com/dotnet/roslyn/blob/252def9efa028af3f0562929b4b0e8a74dcd3124/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs#L1049

I looks like checks content overlaps.

I think this would work (assuming FilterSpan was available):

```cs
foreach (var item in root.DescendantTokens(context.FilterSpan))
{
    cancellationToken.ThrowIfCancellationRequested();

    AnalyzeToken(context, routeUsageCache, item, cancellationToken);
}
```

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs [hunk 2]
```diff
@@ -31,94 +31,81 @@ private void AnalyzeSemanticModel(SemanticModelAnalysisContext context)
         var cancellationToken = context.CancellationToken;
 
         var root = syntaxTree.GetRoot(cancellationToken);
-        var wellKnownTypes = WellKnownTypes.GetOrCreate(context.SemanticModel.Compilation);
         var routeUsageCache = RouteUsageCache.GetOrCreate(context.SemanticModel.Compilation);
-        Analyze(context, root, wellKnownTypes, routeUsageCache, cancellationToken);
+
+        foreach (var item in root.DescendantTokens())
```
Comment (JamesNK) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/RoutePatternAnalyzer.cs:36]:
```suggestion
        // Update to use FilterSpan when available. See https://github.com/dotnet/aspnetcore/issues/48157
        foreach (var item in root.DescendantTokens())
```
