### PR TITLE
[Blazor] Update bind:set,after runtime apis

### LINKED ISSUE #43195: `bind:after` with asynchronous method causes multiple renders when done.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we use bind:after with an asynchronous method then that invokes multiple renders once the method is done. An example of this could be the following sample razor page.
```razor
<input @bind=@_myText @bind:after="AsynchronousTask" />

@code {
    private string _myText = "Start Value";

    private async Task AsynchronousTask()
    {
        await Task.Delay(4000);
    }

    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine("rendered!");
    }
}
```

### Expected Behavior

If we observe the console output we would expect it log `"rendered!"` 3 times.
- 1 time when the page loads.
- 1 time when `_myText` is updated.
- 1 time when the async task finishes.

What we actually see is that it logs `"rendered!"` 5 times.
- 1 time when the page loads.
- 1 time when `_myText` is updated.
- 3 times when the async task finishes.

### Steps To Reproduce

I have made the following repo that reproduces this behavior:
https://github.com/KristofferStrube/BlazorNet7bindAfterRenderSample

You can test this without building it yourself as it is hosted on Github Pages here:
https://kristofferstrube.github.io/BlazorNet7bindAfterRenderSample/

### Exceptions (if any)

_No response_

### .NET Version

7.0.100-preview.7.22377.5

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by javiercn**
# Updates the runtime helper APIs the compiler will use with bind:get, bind:set, and bind:after.

## Description

There is a full technical description of the issue all the way down the issue for all the details.

The TL;DR is that due to the way we decided to implement this feature, customers can run into situations where their components render many more times than expected, which results in confusion and performance degradation.

This was due to the fact that we chose to rely on EventCallback to implement this feature and we did not realize there were some side effects associated with it.

The APIs we are adding bypass the whole EventCallback infrastructure (simplifying the implementation too) and fix the issue.

Fixes #43195

## Customer Impact

Low performance, unexpected behavior. 

The reason it is important to fix this issue is because it is the result of feedback from the previews and since it involves the razor compiler, we won't be able to easily fix it in the future without introducing a breaking behavior change.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [x] Medium
- [ ] Low

The only reason this is medium and not low is because it has a sibling PR on the razor-compiler to update it to use the new methods.

## Verification

- [ ] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----
<summary>

# Complete description and detailed technical analisys

<details>

# bind get, set, after changes

There was an oversight on the initial design of bind get, set, after. We decided to piggyback on the EventCallback infrastructure to simplify the implementation as the runtime helpers that we already have provide support for coercing functions and actions into an event callback (typed or untyped).

Unfortunately, that has an additional unintended side-effect. The runtime helpers that the compiler uses for creating EventCallback have logic in them to select a "receiver" for the callback. If the callback target implements IHandleEvent, it gets chosen as the receiver. Otherwise, the explicit receiver passed in is used.

The issue is that when the receiver implements IHandleEvent, the EventCallback infrastrucure will call `receiver.HandleEventAsync(evt)`. In the most common implementation (ComponentBase) this will in turn call `StateHasChanged()` internally up to two times (at the end of the sync and async work).

The result of this is that when using bind get, set, after `StateHasChanged` will be called more than it is needed, which surprises users and can cause unintended performance problems and other side effects.

The solution for this unfortunately, involves updating the runtime helper APIs for this scenario as well as the compiler to generate new code that consumes these new APIs.

We can piggyback on EventCallback APIs, but since we need to author new APIs, it is best to avoid this altogether. 

Before we go into details on the concrete APIs we will recap the list of supported scenarios.

## Binding to elements

In this case we are binding to a DOM event.

```html
<input @bind="_val" />
```

```csharp
private string _val = "";
```

### Generated callback code

```csharp
factory.CreateBinder(this, __value => _val == __value, _val)
```

CreateBinder has overloads for the different primitive types we support binding and each overload can receive either an Action<T> or an EventCallback<T> that was added as part of the support we did for bind get, set, after.

## Binding to components

In this case we have a "parent" component and a "child" component where the "parent" component is binding to a pair of properties in the child component (for example Value and ValueChanged). ValueChanged can have two different types: `Action<T>`, `EventCallback<T>`.

### Child component

```csharp
[Parameter] public string Value { get; set; }

[Parameter] public EventCallback<string> ValueChanged { get; set; }
```

### Parent component

```csharp
<Child @bind-Value="_value" />
```

### Generated code (EventCallback<T>)

```csharp
EventCallback.Factory.Create<string>(this, RuntimeHelpers.CreateInferredEventCallback(this, __value => _myVal = __value, _myVal));
```

In this case, we use a helper `CreateInferredEventCallback` to convert the function to the right type of event callback, since writing the generic signature is complicated when we have generic type arguments.

### Generated code (Action<T>)

```csharp
(Action<string>)(__value => _myVal = __value)
```

In this case, we emit a type cast.

## Bind to elements using set or after

In this scenario you are allowed to provide a callback which can be an `Action<T>`, a `Func<T, Task>` or an `EventCallback<T>` for bind:set or an `Action`, a `Func<Task>` or an `EventCallback` for `bind:after`.

### Bind to elements using bind:set

```html
<input @bind:get="_val" @bind:set="(value) => {_val = value; DoSomething(); }" />
```

In this scenario we update the generated code to create a setter ourselves, and since we can't know if what the user provides is a function, an action or an explicit EventCallback, we use the `CreateInferredEventCallback` overloads to coerce everything into an `EventCallback<T>`.

```csharp
factory.CreateBinder(
  this,
  RuntimeHelpers.CreateInferredEventCallback(
    this,
    (value) => {_val = value; DoSomething(); },
    _val),
  _val);
```

### Bind to elements using bind:after

```html
<input @bind:get="_val" @bind:after="() => { DoSomething(); }" />
```

In this scenario things are even more complicated as we need to compose a setter that invokes the after function.

```csharp
factory.CreateBinder(
  this,
  RuntimeHelpers.CreateInferredEventCallback(
    this,
    (__value) => { 
        _val = __value;
        return EventCallback.Factory.Create(() => { DoSomething(); }).InvokeAsync();
    },
    _val),
  _val);
```

The issue then becomes that the event callback at `EventCallback.Factory.Create(() => { DoSomething(); })` as well as the `RuntimeHelpers.CreateInferredEventCallback` that wraps it, do more work than they should do. (As described above, they don't just invoke the callback, they'll call IHandleEvent.HandleEvent on the receiver if present)

As a result, we want to tweak the generated code as follows. Instead of using CreateInferredEventCallback, we are going to use a new helper CreateInferredBindSetter with the following signature and two overloads:
* `Func<TValue, Task> CreateInferredBindSetter<TValue>(Action<TValue> setter, TValue value)`
* `Func<TValue, Task> CreateInferredBindSetter<TValue>(Func<TValue, Task> setter, TValue value)`

We use these two overloads because we do not know when we receive a setter expression whether it is a Task returning function or not.

We will remove the EventCallback<T> based runtime APIs that we added as part of the feature as we do not need them.

We will avoid using CreateEventCallback for BindAfter as we already have `InvokeAsynchronousDelegate` to coalesce bind:after expressions and invoke them.

# Generated code before

## Element bind get, set

```html
<input type="text" @bind:get="_value" @bind:set="(value) => _value = value" />
```

```csharp
__builder.AddAttribute(2, "value", global::Microsoft.AspNetCore.Components.BindConverter.FormatValue(
      _value
));
__builder.AddAttribute(
  3,
  "onchange",
  global::Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(
    this,
    global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
      this, 
      callback: (value) => _value = value,
      value: _value),
      _value));

__builder.SetUpdatesAttributeName("value");
```

## Element bind after

```html
<input type="text" @bind="_value" @bind:after="() => {}" />
```

```csharp
__builder.AddAttribute(7, "value", global::Microsoft.AspNetCore.Components.BindConverter.FormatValue(
        _value
));

__builder.AddAttribute(
  8,
  "onchange",
  global::Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(
      this,
      global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
          this,
          callback: __value => { 
              _value = __value;
              return global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(
                  this,
                  callback: () => {}).InvokeAsync();
              },
          value: _value),
      _value));
__builder.SetUpdatesAttributeName("value");
```

### Child component
```csharp
@code {
    public string Value { get; set; } = "";
    public EventCallback<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", 
     Value
);
__builder.AddAttribute(
  2,
  "ValueChanged",
  global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
      this,
      global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
        this,
        callback: __value => {
            Value = __value;
            return global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(
                this,
                callback: () => { }).InvokeAsync(); 
            },
        value: Value),
        Value));
```

### Child component
```csharp
@code {
    public string Value { get; set; } = "";
    public EventCallback<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", 
    Value
);
__builder.AddAttribute(
  2,
  "ValueChanged",
  global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
      this,
      value => Value = value,
      Value));
__builder.CloseComponent();
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Func<string, Task> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Func<System.String, System.Threading.Tasks.Task>)(async __value => {
        Value = __value;
        await global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.InvokeAsynchronousDelegate(() => { });
    }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Func<string, Task> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Func<System.String, System.Threading.Tasks.Task>)((value) => { return Task.CompletedTask; }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Action<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Action<System.String>)(__value => {
        Value = __value;
        global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.InvokeSynchronousDelegate(() => { });
    }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Action<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Action<System.String>)((value) => { Value = value; }));
```

# Generated code after

## Element bind get, set

```html
<input type="text" @bind:get="_value" @bind:set="(value) => _value = value" />
```

```csharp
__builder.AddAttribute(2, "value", global::Microsoft.AspNetCore.Components.BindConverter.FormatValue(
      _value
));
__builder.AddAttribute(
  3,
  "onchange",
  global::Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(
    this,
    global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredBindSetter(
      callback: (value) => _value = value,
      value: _value),
      _value));

__builder.SetUpdatesAttributeName("value");
```

## Element bind after

```html
<input type="text" @bind="_value" @bind:after="() => {}" />
```

```csharp
__builder.AddAttribute(7, "value", global::Microsoft.AspNetCore.Components.BindConverter.FormatValue(
        _value
));

__builder.AddAttribute(
  8,
  "onchange",
  global::Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(
      this,
      global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredBindSetter(
          callback: __value => { 
              _value = __value;
              return InvokeAsynchronousDelegate(() => { });
          },
          _value),
      _value);
__builder.SetUpdatesAttributeName("value");
```

### Child component
```csharp
@code {
    public string Value { get; set; } = "";
    public EventCallback<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", 
     Value
);
__builder.AddAttribute(
  2,
  "ValueChanged",
  global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(
      this,
      global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredBindSetter(
        callback: __value => {
            Value = __value;
            return InvokeAsynchronousDelegate(() => { }); 
            },
        value: Value),
      Value));
```

### Child component
```csharp
@code {
    public string Value { get; set; } = "";
    public EventCallback<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", 
    Value
);
__builder.AddAttribute(
  2,
  "ValueChanged",
  global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredBindSetter(
      this,
      value => Value = value,
      Value));
__builder.CloseComponent();
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Func<string, Task> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Func<System.String, System.Threading.Tasks.Task>)(async __value => {
        Value = __value;
        await global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.InvokeAsynchronousDelegate(() => { });
    }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Func<string, Task> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Func<System.String, System.Threading.Tasks.Task>)((value) => { return Task.CompletedTask; }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Action<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value="Value" @bind-Value:after="() => { }" />
```

### Generated code
```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Action<System.String>)(__value => {
        Value = __value;
        global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.InvokeSynchronousDelegate(() => { });
    }));
```

### Child component
```csharp
@code {
    [Parameter] public string Value { get; set; } = "";
    [Parameter] public Action<string> ValueChanged { get; set; }
}
```

### Parent component
```html
<ChildComponent @bind-Value:get="Value" @bind-Value:set="value => Value = value" />
```

### Generated code

```csharp
__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
    Value
));
__builder.AddAttribute(
    2,
    "ValueChanged",
    (global::System.Action<System.String>)((value) => { Value = value; }));
```
</details>
</summary>

### CODE REVIEW

File: src/Components/Components/src/EventCallbackFactoryBinderExtensions.cs [hunk 1]
```diff
@@ -1379,10 +1379,10 @@ public static class EventCallbackFactoryBinderExtensions
         return factory.Create<ChangeEventArgs>(receiver, callback);
     }
 
-    private static EventCallback<ChangeEventArgs> CreateBinderCore<T>(
+    private static EventCallback<ChangeEventArgs> CreateBinderCoreAsync<T>(
```
Comment (MackinnonBuck) [inline src/Components/Components/src/EventCallbackFactoryBinderExtensions.cs:1382]: Why the `Async` suffix?

Comment (javiercn) [reply src/Components/Components/src/EventCallbackFactoryBinderExtensions.cs:1382]: The compiler can't decide the right overload otherwise.

**Review by MackinnonBuck — APPROVED** [review]

**Review by TanayParikh — COMMENTED** [review]
:shipit: 🎉
