### PR TITLE
Require CancellationToken for client results (and fix cancel closing connection)

### LINKED ISSUE #43054: Canceled client result can result in connection being closed
Using the new client results feature in SignalR, if you pass in a cancellation token to `InvokeAsync` and cancel it, the server-side will properly clean-up the call, but the client-side will still send a result it produces one which will result in the HubProtocol serializer throwing when trying to resolve the type to deserialize the response to (as the server-side doesn't know about the invocation anymore). When the HubProtocol throws the connection is closed because we have to assume the connections pipe is no longer usable (partial reads etc.).

https://github.com/dotnet/aspnetcore/blob/bf02bf2325f4752dd8a28c17d420e01961219f91/src/SignalR/server/Core/src/Internal/HubConnectionBinder.cs#L24-L30

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/43054

For other types like StreamItem and Invocations we create `StreamBindingFailureMessage` and `InvocationBindingFailureMessage` respectively in the hub protocols when a failure occurs. We might want to do something similar here, but since it's late in RC1 I think we should opt for not adding a new public class and instead ignore the result value of completion messages in this scenario.

~~Additionally, this change adds a default timeout of 30 seconds to client result calls. This is done at the `HubLifetimeManager` layer because we aren't able to control all call sites of `proxy.InvokeAsync`. This is also an option that could potentially result in new API (`DefaultClientResultTimeout` or something). But again, late in RC1 that might be hard to swing. Users can pass in their own `CancellationToken` if they want to customize how long they will wait for a result, and this will override the 30 second default.~~

Went with requiring user to pass in a `CancellationToken` to suggest that they think about cancellation when using the feature.

### CODE REVIEW

File: src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs [hunk 1]
```diff
@@ -419,7 +422,17 @@ public override async Task<T> InvokeConnectionAsync<T>(string connectionId, stri
         // Needs to be unique across servers, easiest way to do that is prefix with connection ID.
         var invocationId = $"{connectionId}{Interlocked.Increment(ref _lastInvocationId)}";
 
-        using var _ = CancellationTokenUtils.CreateLinkedToken(cancellationToken,
+        CancellationTokenSource? cts = null;
+        // Add a default timeout if one isn't provided
+        if (!cancellationToken.CanBeCanceled)
+        {
+            cts = _cancellationTokenSourcePool.Rent();
+            cts.CancelAfter(TimeSpan.FromSeconds(30));
```
Comment (davidfowl) [inline src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:430]: 1 minute

Comment (davidfowl) [reply src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:430]: grrr. configurable.

Comment (BrennanConroy) [reply src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:430]: See PR description. Why 1 minute?

File: src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs [hunk 2]
```diff
@@ -22,6 +23,8 @@ namespace Microsoft.AspNetCore.SignalR.StackExchangeRedis;
 /// <typeparam name="THub">The type of <see cref="Hub"/> to manage connections for.</typeparam>
 public class RedisHubLifetimeManager<THub> : HubLifetimeManager<THub>, IDisposable where THub : Hub
 {
+    private static readonly CancellationTokenSourcePool _cancellationTokenSourcePool = new();
```
Comment (halter73) [inline src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:26]: This is pretty tricky. I suspect there will be more implementors of `InvokeConnectionAsync` than callers. I'm not sure though. If that's true, should we just move the default timeout to `SingleClientProxy`?

File: src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs [hunk 3]
```diff
@@ -230,8 +230,27 @@ public ReadOnlyMemory<byte> GetMessageBytes(HubMessage message)
...
+                                {
+                                    returnType = binder.GetReturnType(invocationId);
+                                }
+                                // GetReturnType throws if invocationId not found, this can be caused by the server canceling a client-result but the client still sending a result
+                                // For now let's ignore the failure and skip parsing the result, server will log that the result wasn't expected anymore and ignore the message
+                                // In the future we may want a CompletionBindingFailureMessage that we can flow to the dispatcher for handling
+                                catch (Exception)
+                                {
+                                    returnType = null;
+                                }
```
Comment (JamesNK) [inline src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs:244]: Nit: Add a central TryGetReturnType helper to avoid duplicating this bit of code

File: src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs [hunk 4]
```diff
@@ -341,7 +343,18 @@ public override async Task<T> InvokeConnectionAsync<T>(string connectionId, stri
...
 
         var invocationId = Interlocked.Increment(ref _lastInvocationId).ToString(NumberFormatInfo.InvariantInfo);
-        using var _ = CancellationTokenUtils.CreateLinkedToken(cancellationToken,
+
+        CancellationTokenSource? cts = null;
+        // Add a default timeout if one isn't provided
+        if (!cancellationToken.CanBeCanceled)
+        {
+            cts = _cancellationTokenSourcePool.Rent();
+            cts.CancelAfter(TimeSpan.FromSeconds(30));
```
Comment (JamesNK) [inline src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs:352]: What stops this timer?

Comment (BrennanConroy) [reply src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs:352]: The dispose via `using` on line 356 first calls `TryReset` which will cleanup the timer, if that fails it will dispose the cts.

Comment (JamesNK) [reply src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs:352]: Ok. Consider adding a comment for other people reading the source.

**Comment by BrennanConroy** [comment]
Changed to remove the default timeout and require passing in a `CancellationToken`.

**Review by halter73 — APPROVED** [review]
I think it makes sense to try to force people to think about cancellation. Making them explicitly pass in `CancellationToken.None`/`default` seems like a reasonable way to do this. And we could add a default later if we really wanted to, right?

Anyway, let's update #43054 with the API proposal so more people can discuss.

**Comment by davidfowl** [comment]
> And we could add a default later if we really wanted to, right?

With the current API I don't think so.

**Comment by BrennanConroy** [comment]
> > And we could add a default later if we really wanted to, right?
> 
> With the current API I don't think so.

We could add an option to set a default, but our default would need to be infinite 😄

**Comment by BrennanConroy** [comment]
@dotnet/aspnet-admins could I get a merge please? Code check is failing due to approved unshipped file changes.

**Comment by dougbu** [comment]
@adityamandaleeka is this approved for RC1❔

File: src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs [hunk 5]
```diff
@@ -209,21 +209,29 @@ public ReadOnlyMemory<byte> GetMessageBytes(HubMessage message)
...
                                         {
-                                            var token = JToken.Load(reader);
-                                            result = GetRawResult(token);
+                                            reader.Skip();
+                                            result = null;
                                         }
                                         else
                                         {
-                                            result = PayloadSerializer.Deserialize(reader, returnType);
+
```
Comment (adityamandaleeka) [inline src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs:220]: nit: extra line

**Comment by adityamandaleeka** [comment]
Approved, this prevents a potentially bad disconnect issue in new 7.0 work.

File: src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs (hunk 5 above)
Comment (BrennanConroy) [inline src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs:220]:
```suggestion
```

**Comment by dougbu** [comment]
Will complain the auto-squish didn't work and that'll hopefully remind me to merge this 😄

**Comment by BrennanConroy** [comment]
Ok, now it's ready.

**Comment by adityamandaleeka** [comment]
Looks like @dougbu or @wtgodbe have to merge this since it's technically red.

**Comment by dougbu** [comment]
You could have done the JIT thing @adityamandaleeka but pinging me was fine, especially because my thought that auto-squish would complain when a build failed didn't pan out😀

**Comment by adityamandaleeka** [comment]
That's a big hammer and I want to be sparing in my use of it :smile:
