### PR TITLE
Use reset event in Kestrel heartbeat to quickly stop thread

### LINKED ISSUE #47600: Exit Kestrel heartbeat thread immediately on stop
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Noticed in https://github.com/dotnet/aspnetcore/pull/47580

Kestrel creates a thread and sleeps for a second in its heartbeat:

https://github.com/dotnet/aspnetcore/blob/f295d1f75cd79c6b3abd4f27b8f4b14a58186e7a/src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs

When Kestrel stops there isn't a way to immediately stop the thread. `Thread.Sleep` doesn't have cancellation.

We could change it to an AutoResetEvent + OneWait(interval). When Kestrel stops the event can be triggered and exit immediately.

However, one thing to consider is making the heartbeat as reliable as possible. `Thread.Sleep` vs waiting on and event handle + timeout might have different behavior if the server is under heavy load.

### Expected Behavior

The heartbeat thread immediately exits when Kestrel is stopped.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/47600

Replace `Thread.Sleep(1000)` with `ManualResetEventSlim`.

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 1]
```diff
@@ -71,17 +73,35 @@ internal void OnHeartbeat()
...
+        // Stop heart beat and immediately exit wait interval.
         _stopped = true;
-        // Don't block waiting for the thread to exit
+        _stopWaitHandle.Set();
+
+        // Wait for heartbeat thread to finish.
+        // Should either be immediate or a short delay while heartbeat callbacks complete.
+        if (_timerThread.IsAlive)
+        {
+            _timerThread.Join();
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:104]: The thread should exit quickly now that delay is interrupted. Removes the chance of heartbeat running while Kestrel is disposed.

**Review by Tratcher — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 2]
```diff
@@ -71,17 +73,35 @@ internal void OnHeartbeat()
...
+
         while (!_stopped)
         {
             OnHeartbeat();
-            Thread.Sleep(_interval);
+
+            if (_stopWaitHandle.WaitOne(_interval))
+            {
+                return;
+            }
```
Comment (danmoseley) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:90]: I guess you could just do this, and add a check for _stopped at the top of OnHeartbeat.
```c#
    private void TimerLoop()
    {
        // Starting the heartbeat immediately triggers OnHeartbeat.
        // Initial delay to avoid running heartbeat again from timer thread.
        while (!_stopped)
        {
            if (_stopWaitHandle.WaitOne(_interval))
            {
                return;
            }

            OnHeartbeat();
      }
   }
```

Comment (danmoseley) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:90]: actually, why do you need `_stopped` any more?

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs]: You're right that it's pretty redundant here. `_stopped` it's also used to suppress logging errors from the heartbeat as the server shuts down.

Better behavior is to completely stop the heartbeat before starting shutdown. Can eliminate `_stopped` once that is done.

**Comment by JamesNK** [comment]
@mconnew This PR updates Kestrel heartbeat to exit immediately and stop before Kestrel starts shutting down. That removes the need to use `_stopped` to suppress error from heartbeat that you added.

Can you take a look and check that your original issue is still solved?

**Comment by JamesNK** [comment]
@Tratcher I moved heartbeat stop to the start of shutdown. Can you double check this is ok?

**Comment by mconnew** [comment]
@JamesNK, it looks like it should resolve it as Dispose() won't return until it will no longer call OnHeartbeat. There's nothing preventing a later change bringing the issue back though as OnHeartbeat is internal so callable. In the catch block you could call WaitOne with a timeout of 0. You can then check the true/false value that's immediately returned to know if it's been set and still avoid logging. That would also enable you to keep the unit test you've removed.

Also, why not ManualResetEventSlim? ManualResetEvent allocates a native win32 handle and the Slim variant is all managed.

**Comment by JamesNK** [comment]
> OnHeartbeat is internal so callable

OnHeartbeat is only internal for unit tests. It won't be called after the heartbeat is disposed.

> Also, why not ManualResetEventSlim? ManualResetEvent allocates a native win32 handle and the Slim variant is all managed.

I read that slim implementation offers an advantage for short wait times, which doesn't apply here.

**Comment by danmoseley** [comment]
> In .NET Core and .NET 5+, the default spin-waiting duration is short: on the order of 10s of microseconds, depending on platform and processor. If you expect wait times to be much longer than that, you can still use this class instead of [ManualResetEvent](https://learn.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent?view=net-7.0) (perhaps configured with less or no spin-waiting). However, the performance benefit would likely be only marginal.

So it sounds like it doesn't matter that much, but indeed it should avoid creating the OS object unless you explicitly fetch `WaitObject` on it, as far as I can see.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 3]
```diff
@@ -62,26 +63,30 @@ internal void OnHeartbeat()
...
     public void Dispose()
     {
-        _stopped = true;
-        // Don't block waiting for the thread to exit
+        // Stop heart beat and immediately exit wait interval.
+        _stopWaitHandle.Set();
+
+        // Wait for heartbeat thread to finish.
+        // Should either be immediate or a short delay while heartbeat callbacks complete.
+        if (_timerThread.IsAlive)
```
Comment (danmoseley) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:87]: total nit, I think IsAlive is redundant here.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 4]
```diff
@@ -24,6 +24,7 @@ public Heartbeat(IHeartbeatHandler[] callbacks, ISystemClock systemClock, IDebug
         _debugger = debugger;
         _trace = trace;
         _interval = Interval;
+        _stopWaitHandle = new ManualResetEvent(false);
```
Comment (danmoseley) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:27]: aside, is "Kestrel Timer" the best name? that's pretty generic. "Kestrel Heartbeat" ? feel free to ignore.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs (hunk 3 above)
Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:87]: Some unit tests call dispose without calling start. `Thread.Join` breaks if the thread isn't started.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs (hunk 4 above)
Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:27]: Yeah, the name isn't great. I would change it but, the name shows up in tooling. Someone might depend on the name being "Kestrel Timer".

**Comment by JamesNK** [comment]
PR updated to use `ManualResetEventSlim`. Set spin count to zero as we're waiting a long time (1 sec) between heartbeats. Spinning would be wasted CPU.

Added a test for the heartbeat loop. Previously wasn't tested.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs [hunk 5]
```diff
@@ -15,15 +16,17 @@ internal sealed class Heartbeat : IDisposable
...
-    public Heartbeat(IHeartbeatHandler[] callbacks, ISystemClock systemClock, IDebugger debugger, KestrelTrace trace)
+    public Heartbeat(IHeartbeatHandler[] callbacks, ISystemClock systemClock, IDebugger debugger, KestrelTrace trace, TimeSpan interval)
     {
         _callbacks = callbacks;
         _systemClock = systemClock;
         _debugger = debugger;
         _trace = trace;
-        _interval = Interval;
+        _interval = interval;
+        // Wait time is long so don't try to spin to exit early. Would just wait CPU time.
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs:28]:
```suggestion
        // Wait time is long, so don't try to spin to exit early. Spinning would waste CPU time.
```

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs (hunk 4 above)
Comment (danmoseley) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/Heartbeat.cs]: It does show in tooling, but I've named (and probably renamed) numerous threads in the core libraries that do and nobody seemed to have an issue -- while perhaps you could write a script (around cordbg?) that uses it, not sure people do.

Having said that I don't care either way.
