### PR TITLE
Fix Validation SG for Blazor Wasm SDK projects

### LINKED ISSUE #63670: ValidatableType complex modal validation not working Blazor Web Assembly (Standalone) 10 RC1
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi Team, 

As per as Microsoft documentation, I had created two sample projects, one in Blazor Web App and Blazor WebAssembly Standalone application. 

 [ValidatableType] validation attribute for complex modal validation is working as expected in Blazor Web App 10.0 RC1 but not working in Blazor Web Assembly 10.0 RC1. 

is it know issue? 

### Expected Behavior

In Blazor Web Assembly also complex Modal validation should work.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-rc.1.25451.107

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by oroztocil**
The PR solves two issues that prevent the new validation from working in Blazor Wasm SDK projects:

- The `Microsoft.Extensions.Validation` NuGet package needs to include the source generator, so that it is available in Blazor Wasm SDK projects (which are not based on the ASP.NET Core runtime pack, unlike the Web SDK projects).
- The various checks for "well-known types" throw when the types are not found in the assemblies (e.g. `Microsoft.AspNetCore.Http.Abstractions` is not present in Blazor Wasm SDK projects). To avoid the need to refactor larger portion of the existing code, the PR solves this by returning a type symbol for a dummy type instead of throwing. This type symbol is then used in place of the missing types and comparisons against it always return false, thus providing the same outer behavior.
    - Idea: We could differentiate between "required" well-known types for which we would throw if not present in the compiled assemblies, and "optional" well-known types for which we would use this trick with a dummy type, or something functionally equivalent.

Fixes #63670

### CODE REVIEW

File: src/Shared/RoslynUtils/WellKnownTypes.cs [hunk 1]
```diff
@@ -51,6 +52,7 @@ private WellKnownTypes(Compilation compilation)
     {
         _lazyWellKnownTypes = new INamedTypeSymbol?[WellKnownTypeData.WellKnownTypeNames.Length];
         _compilation = compilation;
+        _missingTypeSymbol = compilation.GetTypeByMetadataName(typeof(MissingType).FullName!)!;
```
Comment (captainsafia) [inline src/Shared/RoslynUtils/WellKnownTypes.cs]: I wonder if we should consider reusing SpecialType.None as the fallback in this case as Roslyn does in their WellKnownType implementation ([ref](https://github.com/dotnet/roslyn/blob/322037893f72b11ce30cb14bb1727798f0a7eb4a/src/Compilers/Core/Portable/WellKnownTypes.cs#L19)). That let's us reuse an existing concept instead of defining out own marker type.

Comment (oroztocil) [reply src/Shared/RoslynUtils/WellKnownTypes.cs]: `Compilation.GetSpecialType` throws out-of-range exception if you try to resolve `INamedTypeSymbol` for `SpecialType.None`. The way `CodeAnalysis.WellKnownTypes` is set up in Roslyn, there is no actual type symbol associated with an unknown type. So if I am not overlooking something, we can't use it as a marker type for our purposes.

**Review by captainsafia — APPROVED** [review]
LGTM! The WellKnownTypes are shared across all our analyzers.

I imagine the material impact here is that scenarios that previously threw exceptions/gold-barred will now fail silently assuming the logic where the symbol comparisons happen is sane.

Some smoke testing on our framework analyzers should give us confidence here.

**Comment by oroztocil** [comment]
Based on offline discussion with @captainsafia I updated the PR so that other analyzers are not affected by the change in type symbol retrieval logic.

I added the `WellKnownTypes.GetOptional` method that does not throw for missing types but returns the symbol for a special marker type. This is used by the Validation generator where needed to ensure compatibility with the Blazor Wasm SDK.

The existing `WellKnownTypes.Get` method keeps the same throwing behavior as before.
