### PR TITLE
[SignalR TS] Fix permanent Disconnecting state

### LINKED ISSUE #30839: [TS] HubConnection stuck in Disconnecting state
### Describe the bug
After I wake up my PC from sleep, the WebSocket connection gets terminated (which is OK). Sometimes it cannot be restarted and then `HubConnection.state` becomes `Disconnecting` forever:
* `.start()` always throws *Cannot start a HubConnection that is not in the 'Disconnected' state.*
* `.stop()` returns a promise which doesn't resolve ever.

---
Logs after waking up the PC from sleep:

image

---
Internals of the corrupted `HubConnection`:

image

### Exceptions (if any)
```
Error: Cannot start a HubConnection that is not in the 'Disconnected' state.
    at e.<anonymous> (2.1fa56808.chunk.js:formatted:42032)
    at 2.1fa56808.chunk.js:formatted:41930
    at Object.next (2.1fa56808.chunk.js:formatted:41943)
    at 2.1fa56808.chunk.js:formatted:41850
    at new Promise (<anonymous>)
    at C (2.1fa56808.chunk.js:formatted:41829)
    at e.startWithStateTransitions (2.1fa56808.chunk.js:formatted:42026)
    at e.start (2.1fa56808.chunk.js:formatted:42021)
    at e.<anonymous> (SignalRService.ts:39)
    at s (2.1fa56808.chunk.js:formatted:60817)
```

### Further technical details
- Chrome 89.0.4389.72
- @microsoft/signalr 5.0.3
- Azure Functions V3 
- Azure SignalR service in "Serverless" mode.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/30839

### CODE REVIEW

File: src/SignalR/clients/ts/signalr/src/HubConnection.ts [hunk 1]
```diff
@@ -769,6 +769,7 @@ export class HubConnection {
 
                 if (this._connectionState !== HubConnectionState.Reconnecting) {
                     this._logger.log(LogLevel.Debug, "Connection left the reconnecting state during reconnect attempt. Done reconnecting.");
+                    this._completeClose();
```
Comment (BrennanConroy) [inline src/SignalR/clients/ts/signalr/src/HubConnection.ts:772]: We do the same thing in the .NET client
https://github.com/dotnet/aspnetcore/blob/a3316184b39c0f4e0f4e5646ff4a9f2e369f6d0b/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1398

File: src/SignalR/clients/ts/signalr/src/HttpConnection.ts [hunk 2]
```diff
@@ -470,6 +470,8 @@ export class HttpConnection implements IConnection {
 
         if (this._connectionState === ConnectionState.Disconnected) {
             this._logger.log(LogLevel.Debug, `Call to HttpConnection.stopConnection(${error}) was ignored because the connection is already in the disconnected state.`);
+            // Make sure HttpConnection.stop() won't be blocked on the promise
+            this._stopPromiseResolver();
```
Comment (halter73) [inline src/SignalR/clients/ts/signalr/src/HttpConnection.ts:474]: At this point, start() has already failed and transitioned the connection to ConnectionState.Disconnected which means the connection could theoretically be restarted and stopped by the time this is run causing this to resolve a subsequent call to stop() incorrectly. I think we should remove the following call to `this._stopConnection()` while keeping the log for diagnostic purposes:

https://github.com/dotnet/aspnetcore/blob/614908248d20c4a1572d1a3bbc7a997d12be9d01/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L216-L219

and just call `this._stopPromiseResolver();` in the `_startInternal()` catch before returning the rejected promise:

https://github.com/dotnet/aspnetcore/blob/614908248d20c4a1572d1a3bbc7a997d12be9d01/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L294-L299

File: src/SignalR/clients/ts/signalr/src/HubConnection.ts (hunk 1 above)
Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/HubConnection.ts:772]: That's not exactly the same thing. The analogous code in the JS client is the following:

https://github.com/dotnet/aspnetcore/blob/brecon/tsdisconnect/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L269-L280 


I think the change to have `_startInternal()`  call `_stopPromiseResolver()` in its catch block before returning is enough to fix this.

File: src/SignalR/clients/ts/signalr/src/HttpConnection.ts (hunk 2 above)
Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr/src/HttpConnection.ts:474]: >the connection could theoretically be restarted and stopped by the time this is run causing this to resolve a subsequent call to stop() incorrectly.

I don't think it can, but even if it could, the connection is in the disconnected state already so calling this in the worst case will do nothing.

> just call `this._stopPromiseResolver();` in the `_startInternal()` catch before returning the rejected promise

That's probably fine. Have to check for undefined, but that's ok.

> I think we should remove the following call to `this._stopConnection()` while keeping the log for diagnostic purposes

Hmm interesting, my biggest concern with that is `_stopConnection` cleans up some fields, but I don't think any of them will be set if the transport isn't set. And it gets rid of some extraneous logs if you hit that code path :+1:

File: src/SignalR/clients/ts/signalr/src/HubConnection.ts (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/clients/ts/signalr/src/HubConnection.ts:772]: > That's not exactly the same thing.

I think it is, I linked to the Reconnect code in HubConnection.cs which aligns with the Reconnect code being changed in HubConnection.ts, you're linking to stop which is different.

> I think the change to have `_startInternal()` call `_stopPromiseResolver()` in its catch block before returning is enough to fix this.

It isn't, they are at two different layers, the `_stopPromiseResolver` code is for closing the HttpConnection. HubConnection will still be in a bad state unless we call `_completeClose`.

Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/HubConnection.ts:772]: There's no exactly equivalent code to the following in the TS client.

https://github.com/dotnet/aspnetcore/blob/a3316184b39c0f4e0f4e5646ff4a9f2e369f6d0b/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1398

In .NET, we have to handle the OperationCanceledException after cancelling StopCts before we can complete the Task returned by Stop(). In TS, `clearTimeout(this._reconnectDelayHandle)` means no more code runs in the reconnect loop, not even error handling code, so we can return a completed promise from stop() directly which we do.

> It isn't, they are at two different layers, the `_stopPromiseResolver` code is for closing the HttpConnection. HubConnection will still be in a bad state unless we call `_completeClose`.

`this._completeClose()` is called before `return Promise.resolve()` when there's a `this._reconnectDelayHandle`. I'm talking about the same layer. There's a `_startInternal()` [in HttpConnection too](https://github.com/dotnet/aspnetcore/blob/614908248d20c4a1572d1a3bbc7a997d12be9d01/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L294-L299). A failed start of `HttpConnection` shouldn't leave anything in a bad state.

File: src/SignalR/clients/ts/signalr/src/HttpConnection.ts (hunk 2 above)
Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/HttpConnection.ts:474]: > so calling this in the worst case will do nothing.

I don't think so. Like I said

>  the connection could theoretically be restarted and stopped by the time this is run causing this to resolve a subsequent call to stop() incorrectly.

**Review by halter73 — APPROVED** [review]

File: src/SignalR/clients/ts/signalr/src/HttpConnection.ts (hunk 2 above)
Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/HttpConnection.ts]: Talked offline. This is important not for when the reconnect delay is canceled but for when a reconnect attempt fails simultaneously with a call to HubConnection.stop().

File: src/SignalR/clients/ts/signalr/src/HubConnection.ts (hunk 1 above)
Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/HubConnection.ts]: Talked offline. This is important not for when the reconnect delay is canceled but for when a reconnect attempt fails simultaneously with a call to HubConnection.stop().
