### PR TITLE
Fix duplicate route detection of actions with route parameters

### LINKED ISSUE #49777: ASP0023 Ambiguous route warning when targeting .NET 8 and using token [action] or [controller] in [Http*] or [Route] attributes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When targeting .NET 8 preview 6 and using token [action] or [controller] in [Http*] or [Route] attributes on a controller method, an ASP0023 warning is emitted which is a new behaviour that wasn't observed in .NET 7.

If you ignore the warnings, the code will run and the endpoints can be called and return the expected responses for their respective verbs.

### Expected Behavior

No warning generated

### Steps To Reproduce

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();

var app = builder.Build();
app.MapControllers();
app.Run();

[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet("[action]")]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet("[action]")]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

### Exceptions (if any)

No response

### .NET Version

8.0.100-preview.6.23330.14

### Anything else?

```
╰─ dotnet --info                                                                                                                                                                           ─╯
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 8.0.100-preview.6
   Manifest Version:    8.0.0-preview.6.23329.7/8.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\WorkloadManifest.json
   Install Type:              Msi
 [wasm-tools-net6]
   Installation Source: SDK 8.0.100-preview.6
   Manifest Version:    8.0.0-preview.6.23329.7/8.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.workload.mono.toolchain.net6\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/49777

A previous fix handled the situation where `[action]` replacement tokens in a route could cause false positives. Using a replacement token for `[action]` is recommended by our docs, but `{action}` can do the same thing.

This PR fixes `{action}` route tokens in the route analyzer.

Example:
```cs
[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet("{action}")]
    public IActionResult GetTime() => Ok(DateTime.Now.ToString("HH:mm:ss"));
    
    [HttpGet("{action}")]
    public IActionResult GetDate() => Ok(DateTime.Now.ToString("yyyy-MM-dd"));
}
```

### CODE REVIEW

**Comment by JamesNK** [comment]
ping @captainsafia @mitchdenny @javiercn 

Could someone please review? The changes are simple. I'd like to backport this at the next opportunity and don't want to leave a PR open for a long time.

File: src/Framework/AspNetCoreAnalyzers/test/Mvc/DetectAmbiguousActionRoutesTest.cs [hunk 1]
```diff
@@ -318,6 +318,284 @@ static void Main(string[] args)
         await VerifyCS.VerifyAnalyzerAsync(source);
     }
 
+    [Fact]
+    public async Task ActionRouteToken_DifferentActionNames_NoDiagnostics()
```
Comment (captainsafia) [inline src/Framework/AspNetCoreAnalyzers/test/Mvc/DetectAmbiguousActionRoutesTest.cs:322]: Should we add a test that covers one route using `[action]` and another using `{action}`?

**Review by captainsafia — APPROVED** [review]
LGTM! One non-blocking comment on tests.

File: src/Framework/AspNetCoreAnalyzers/test/Mvc/DetectAmbiguousActionRoutesTest.cs (hunk 1 above)
Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/test/Mvc/DetectAmbiguousActionRoutesTest.cs:322]: What kind of sick person would do that? I love it.

Comment (JamesNK) [reply src/Framework/AspNetCoreAnalyzers/test/Mvc/DetectAmbiguousActionRoutesTest.cs:322]: I looked at this and the test isn't necessary. `HttpGet("[action]")` and `HttpGet("{action}")` aren't flagged as ambiguous because the routes are different.

Technically they should be ambiguous, but realistically no one will ever do this. The analyzer will stick with the pattern of being conservative about what it reports and not handle this situation.

**Review by javiercn — COMMENTED** [review]
Looks good to me.
