### PR TITLE
Endpoint filter pipeline now returns EmptyHttpResult in case of 400 BadRequest

### LINKED ISSUE #45040: Invoking endpoint filter but not handler on argument error causes VoidTaskResult to be written to the response body
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A serialized VoidTaskResult is written to the _HttpResponse.Body_ when an endpoint filter is used and the endpoint fails argument validation.

**Reason behind the issue**
The reasons this occurs is because the pipeline will return a _ValueTask.FromResult\<object\>(Task.CompletedTask)_ when the HttpContext.Response.StatusCode is 400 as seen below, this will then be serialized to Json when _AddResponseWritingToMethodCall_ detects that the return type is _ValueTask\<object\>_ and call the method chain _ExecuteValueTaskOfObject_ > _ExecuteAwaitedReturn_ > _WriteJsonResponse_

```C#
var filteredInvocation = Expression.Lambda<EndpointFilterDelegate>(
            Expression.Condition(
                Expression.GreaterThanOrEqual(FilterContextHttpContextStatusCodeExpr, Expression.Constant(400)),
                CompletedValueTaskExpr,
                handlerInvocation),
            FilterContextExpr).Compile();
```

An existing unit test (_RequestDelegateFactory_InvokesFiltersButNotHandler_OnArgumentError_) would catch this issue if it checked that the _HttpContext.Response.Body_ should be empty at the end of the test.

**Possible solution**
The easiest solution I have found is just to check if the value in _ExecuteAwaitedReturn_ is of type Task.Completed as seen in the last else if statement below, and skip the JSON serialization.

Thoughts?

```C#
private static Task ExecuteAwaitedReturn(object obj, HttpContext httpContext)
{
    // Terminal built ins
    if (obj is IResult result)
    {
        return ExecuteResultWriteResponse(result, httpContext);
    }
    else if (obj is string stringValue)
    {
        SetPlaintextContentType(httpContext);
        return httpContext.Response.WriteAsync(stringValue);
    }
    else if (obj != Task.CompletedTask)
    {
        // Otherwise, we JSON serialize when we reach the terminal state
        return WriteJsonResponse(httpContext.Response, obj);
    }
    return Task.CompletedTask;
}
```

### Expected Behavior

I would expect to get a 400 status code without a response body, this is the behavior you get when no endpoint filter is defined.

### Steps To Reproduce

1. Create the application described below
2. Go to the endpoint without defining the query parameter (e.g., http://localhost:5001)
3. The following result should be observed:
```JSON
{"result":{},"id":41,"exception":null,"status":5,"isCanceled":false,"isCompleted":true,"isCompletedSuccessfully":true,"creationOptions":0,"asyncState":null,"isFaulted":false}
```

**Application**
```C#
var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<RouteHandlerOptions>(o => o.ThrowOnBadRequest = false);
var app = builder.Build();
app.MapGet("/", (string name) => $"Hello, {name}!")
   .AddEndpointFilter(async (context, next) =>
   {
       return await next(context);
   });
app.Run();
```

### Exceptions (if any)

_No response_

### .NET Version

7.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Oskarsson**
## Description

The endpoint filter pipeline will now return an EmptyHttpResult instance instead of ValueTask<object>(Task.CompletedTask) when the status code is greater or equal to 400 to prevent the returned task from being serialized and written to the response body.

Before:
```C#
if (httpContext.Response.StatusCode >= 400)
{
  return new ValueTask<object>(Task.CompletedTask);
}
```

After:
```C#
if (httpContext.Response.StatusCode >= 400)
{
  return new ValueTask<object>(EmptyHttpResult.Instance);
}
```

Fixes #45040

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45073) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45073) before we can accept your contribution.<br/><br/>:x: Oskarsson [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=45073)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=45073) it.</sub>

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -92,7 +92,7 @@ public static partial class RequestDelegateFactory
     private static readonly MemberExpression FormFilesExpr = Expression.Property(FormExpr, typeof(IFormCollection).GetProperty(nameof(IFormCollection.Files))!);
     private static readonly MemberExpression StatusCodeExpr = Expression.Property(HttpResponseExpr, typeof(HttpResponse).GetProperty(nameof(HttpResponse.StatusCode))!);
     private static readonly MemberExpression CompletedTaskExpr = Expression.Property(null, (PropertyInfo)GetMemberInfo<Func<Task>>(() => Task.CompletedTask));
-    private static readonly NewExpression CompletedValueTaskExpr = Expression.New(typeof(ValueTask<object>).GetConstructor(new[] { typeof(Task) })!, CompletedTaskExpr);
+    private static readonly ConstantExpression EmptyResultValueTaskExpr = Expression.Constant(new ValueTask<object?>(EmptyHttpResult.Instance));
```
Comment (captainsafia) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:95]: To avoid adding to https://github.com/dotnet/aspnetcore/issues/41435, can we use an alternative syntax for this? You can check out [the diff in this PR](https://github.com/dotnet/aspnetcore/pull/43380/files#diff-f38f5cec66cf8010067587a59799e7aeb620388d108d0c58e63aa23849eb6eebR102-R104) for an example.

Comment (Oskarsson) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs]: We can definitely replace it with the new expression instead. I noticed you included one of the changes already in your PR that uses the same expression so feel free to include the change for this issue in your PR instead to prevent conflicts, otherwise the change is now done here.

**Review by captainsafia — APPROVED** [review]
