### PR TITLE
Fix HTTP/2 tests that use HttpClient and H2C

### LINKED ISSUE #24902: Re-enable failing H2C tests
### Describe the bug
Most (10 of 12) gRPC tests started failing in https://dev.azure.com/dnceng/public/_build/results?buildId=769894, the validation build for a dependency update from dotnet/runtime and dotnet/efcore (#24876). Skipping all tests in that PR. They will need to be investigated and re-enabled.

Note this is likely a product issue and not just a test problem.

### To Reproduce
Re-enable one of the tests mentioning this bug. Watch it fail.

### Exceptions (if any)
For example&hellip;
``` text
[xUnit.net 00:00:09.39]       Client process output:
[xUnit.net 00:00:09.39]       ======================================
[xUnit.net 00:00:09.39]       Application started.
[xUnit.net 00:00:09.39]       NetCoreAppVersion: 5.0.0-rc.1.20412.8+0db8ecbea291c09cfd84d7f33ea049f5c0cec94f
[xUnit.net 00:00:09.39]       Use TLS: False
[xUnit.net 00:00:09.39]       Use Test CA: False
[xUnit.net 00:00:09.39]       Client type: httpclient
[xUnit.net 00:00:09.39]       Server host: localhost
[xUnit.net 00:00:09.39]       Server port: 38719
[xUnit.net 00:00:09.39]       running special_status_message
[xUnit.net 00:00:09.39]       [40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Starting gRPC call. Method type: 'Unary', URI: 'http://localhost:38719/grpc.testing.TestService/UnaryCall'.
[xUnit.net 00:00:09.39]       [40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[18]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Sending message.
[xUnit.net 00:00:09.39]       [40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[21]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Serialized 'Grpc.Testing.SimpleRequest' to 68 byte message.
[xUnit.net 00:00:09.39]       [40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[19]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Message sent.
[xUnit.net 00:00:09.39]       [41m[30mfail[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[6]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Error starting gRPC call.
[xUnit.net 00:00:09.39]             System.Net.Http.HttpRequestException: An error occurred while sending the request.
[xUnit.net 00:00:09.39]              ---> System.IO.IOException: The response ended prematurely.
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpConnection.FillAsync(Boolean async)
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:09.39]                --- End of inner exception stack trace ---
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:09.39]                at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:09.39]                at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:09.39]                at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
[xUnit.net 00:00:09.39]                at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
[xUnit.net 00:00:09.39]       [40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[8]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             gRPC call canceled.
[xUnit.net 00:00:09.39]       [41m[30mfail[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[3]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call: An error occurred while sending the request.'.
[xUnit.net 00:00:09.39]       [40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[4]
[xUnit.net 00:00:09.39]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:09.39]             Finished gRPC call.
[xUnit.net 00:00:09.39]       ERROR: Unhandled exception. System.InvalidOperationException: Expected Unknown but got Internal.
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.Assert.AreEqual(Object expected, Object actual) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\Assert.cs:line 47
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.InteropClient.RunSpecialStatusMessageAsync(TestServiceClient client) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\InteropClient.cs:line 676
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.InteropClient.RunTestCaseAsync(IChannelWrapper channel, ClientOptions options) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\InteropClient.cs:line 267
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.InteropClient.Run() in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\InteropClient.cs:line 139
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.InteropClient.<>c.<Run>b__7_1(ClientOptions options) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\InteropClient.cs:line 131
[xUnit.net 00:00:09.39]       ERROR:    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.InteropClient.Run(String[] args) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\InteropClient.cs:line 119
[xUnit.net 00:00:09.39]       ERROR:    at InteropTestsClient.Program.Main(String[] args) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropClient\Program.cs:line 33
```

### Further technical details
See @JamesNK's comments: https://github.com/dotnet/aspnetcore/pull/24876#issuecomment-673775545

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/24902

### CODE REVIEW

File: src/Grpc/test/testassets/InteropClient/InteropClient.cs [hunk 1]
```diff
@@ -179,7 +180,19 @@ private async Task<IChannelWrapper> HttpClientCreateChannel()
             return new GrpcChannelWrapper(channel);
         }
 
-        private bool IsHttpClient() => string.Equals(options.ClientType, "httpclient", StringComparison.OrdinalIgnoreCase);
+        // TODO(JamesNK): This type can be removed in the future when Grpc.Net.Client sets VersionPolicy automatically
```
Comment (Tratcher) [inline src/Grpc/test/testassets/InteropClient/InteropClient.cs:183]: Link to issue in gRPC.

File: src/Grpc/test/testassets/InteropClient/InteropClient.cs [hunk 2]
```diff
@@ -179,7 +180,19 @@ private async Task<IChannelWrapper> HttpClientCreateChannel()
...
+        private class VersionPolicyHandler : DelegatingHandler
+        {
+            public VersionPolicyHandler(HttpMessageHandler innerHandler) : base(innerHandler)
+            {
+            }
+
+            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
+            {
+                request.VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
```
Comment (Tratcher) [inline src/Grpc/test/testassets/InteropClient/InteropClient.cs:192]: You plan on using Exact in gRPC, no?
```suggestion
                request.VersionPolicy = HttpVersionPolicy.RequestVersionExact;
```

File: src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs [hunk 3]
```diff
@@ -1612,6 +1601,7 @@ private static HttpClient CreateClient()
             handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
             var client = new HttpClient(handler);
             client.DefaultRequestVersion = HttpVersion.Version20;
+            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
```
Comment (Tratcher) [inline src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:1604]:
```suggestion
            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
```

File: src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs [hunk 4]
```diff
@@ -1621,6 +1611,7 @@ private static HttpRequestMessage CreateRequestMessage(HttpMethod method, string
             {
                 Version = HttpVersion.Version20,
                 Content = content,
+                VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher,
```
Comment (Tratcher) [inline src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:1614]:
```suggestion
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
```

**Review by Tratcher — APPROVED** [review]

File: src/Grpc/test/testassets/InteropClient/InteropClient.cs (hunk 2 above)
Comment (JamesNK) [reply src/Grpc/test/testassets/InteropClient/InteropClient.cs:192]: Theoretically gRPC should work with HTTP/3 so OrHigher seems like the best choice.

File: src/Grpc/test/InteropTests/InteropTests.cs [hunk 5]
```diff
@@ -25,7 +25,7 @@ public InteropTests(ITestOutputHelper output)
             _output = output;
         }
 
-        [Fact(Skip= "https://github.com/dotnet/aspnetcore/issues/24902")]
+        [Fact]
```
Comment (dougbu) [inline src/Grpc/test/InteropTests/InteropTests.cs:28]: Question only: Should these tests be quarantined for now❔

File: src/Grpc/test/testassets/InteropClient/InteropClient.cs [hunk 6]
```diff
@@ -179,7 +180,20 @@ private async Task<IChannelWrapper> HttpClientCreateChannel()
             return new GrpcChannelWrapper(channel);
         }
 
-        private bool IsHttpClient() => string.Equals(options.ClientType, "httpclient", StringComparison.OrdinalIgnoreCase);
+        // TODO(JamesNK): This type can be removed in the future when Grpc.Net.Client sets VersionPolicy automatically.
+        // https://github.com/grpc/grpc-dotnet/pull/987
+        private class VersionPolicyHandler : DelegatingHandler
```
Comment (dougbu) [inline src/Grpc/test/testassets/InteropClient/InteropClient.cs:185]: nit: Don't we put inner classes at the bottom of our files❔

File: src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs [hunk 7]
```diff
@@ -25,38 +25,27 @@ namespace Interop.FunctionalTests
     /// <summary>
     /// This tests interop with System.Net.Http.HttpClient (SocketHttpHandler) using HTTP/2 (H2 and H2C)
     /// </summary>
-    // Attributes are here to avoid testing http. Remove when https://github.com/dotnet/aspnetcore/issues/24902 is resolved.
-    [OSSkipCondition(OperatingSystems.MacOSX, SkipReason="https://github.com/dotnet/aspnetcore/issues/24902")]
-    [MinimumOSVersion(OperatingSystems.Windows, WindowsVersions.Win10, SkipReason="https://github.com/dotnet/aspnetcore/issues/24902")]
     public class HttpClientHttp2InteropTests : LoggedTest
```
Comment (dougbu) [inline src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:28]: Question only: Should these tests be quarantined for now❔

Comment (JamesNK) [reply src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:28]: Famous last words: it should just work 😄

File: src/Grpc/test/testassets/InteropClient/InteropClient.cs (hunk 6 above)
Comment (JamesNK) [reply src/Grpc/test/testassets/InteropClient/InteropClient.cs:185]: I agree, but this class is temporary. It will disappear in a few days.

File: src/Grpc/test/InteropTests/InteropTests.cs (hunk 5 above)
Comment (JamesNK) [reply src/Grpc/test/InteropTests/InteropTests.cs:28]: Famous last words: it should just work 😄
