### PR TITLE
[Blazor] `OwningComponentBase` Dispose method in .NET 10 gets back the original behavior

### LINKED ISSUE #64669: [Blazor] OwningComponentBase Dispose method in .NET 10 differs from .NET9
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a Blazor Web App, I am using Razor components that inherit `OwningComponentBase`. Inside of these components, I am overriding the `Dispose(bool disposing)`-method as such (example):

```
@inherits OwningComponentBase

<h3>Test</h3>

@code {
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            Console.WriteLine("disposing test component");
        }

        base.Dispose(disposing);
    }
}
```

Previously, in .NET 9, upon closing the component (for example by having a boolean to show/hide), the `Dispose` method is invoked, and `disposing == true`, which ultimately triggers the `Console.WriteLine("disposing test component");`. This is the expected behavior.

However, after upgrading to .NET 10, the value of `disposing` is no longer `true` but `false`. Resulting in breaking changes in code (anything in the disposing conditional check is no longer executed).

I was unable to find any reference to this in the breaking changes of NET 10, neither in the change log. All I could find was the following in the "What's new"-section, which does not mention anything about this change:

> OwningComponentBase now implements IAsyncDisposable
[OwningComponentBase](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-10.0#utility-base-component-classes-to-manage-a-di-scope) now includes support for asynchronous disposal, improving resource management. There are new DisposeAsync and DisposeAsyncCore methods with an updated Dispose method to handle both synchronous and asynchronous disposal of the service scope.

I consider this to be a major breaking change that is not documented at all. Was this the intended behavior or is this a bug? If it was intended, this has not been documented and this can cause serious memory leaks.

PS: I also tried this with 2 out-of-the-box Blazor projects, one in .NET 9 and the other in .NET 10. Please, find them attached.

[BlazorApp5.zip](https://github.com/user-attachments/files/23964159/BlazorApp5.zip)
[BlazorApp6.zip](https://github.com/user-attachments/files/23964160/BlazorApp6.zip)

### Expected Behavior

The `OwningComponentBase`'s `Dispose`-method should have the value of `disposing` being set to `true` in .NET 10 such as it was in .NET 9.

### Steps To Reproduce

- Run both projects (one is .NET 9, the other .NET 10).
- Click the button to show the test component.
- Click the button to hide the test component.
- The console will show the statement in the `disposing == true` clause only in the .NET 9 version.

### Exceptions (if any)

_No response_

### .NET Version

10

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/aspnetcore/issues/64669.

In .NET 9, when a Blazor component was disposed, it called `IDisposable.Dispose()` which invoked `Dispose(bool disposing)` with `disposing=true`. In .NET 10, after PR #62583 added `IAsyncDisposable` support, the Blazor framework started calling `IAsyncDisposable.DisposeAsync()` instead. Following the standard .NET dispose pattern, `DisposeAsync()` called `Dispose(false)` to avoid double-disposal of managed resources. This broke user code that overrode `Dispose(bool disposing)` and expected `disposing=true` when the component was being cleaned up, causing any logic inside `if (disposing) { ... }` blocks to no longer execute. The fix ensures `Dispose(true)` is called from `DisposeAsync()` to maintain backward compatibility while still properly handling async disposal of the service scope.

# Changes
- Call `Dispose(true)` from `DisposeAsync()` to ensure user overrides of `Dispose(bool disposing)` receive [disposing=true], maintaining backward compatibility with .NET 9 behavior.
- Removed `IsDisposed = true` from `DisposeAsyncCore()]` - the responsibility of setting this flag is in the `Dispose(bool disposing)` method to avoid duplication and ensure consistency whether disposal happens via sync or async path.

# Tests

- **`DisposeAsync_CallsDispose_WithDisposingTrue`** - Verifies that `DisposeAsync()` passes `disposing=true` to user overrides of `Dispose(bool disposing)`, which is the core fix for issue.
- **`DisposeAsync_ThenDispose_IsIdempotent`** - Ensures that calling both `DisposeAsync()` and `Dispose()` doesn't cause double-disposal of resources, proving the implementation is safe for multiple disposal calls.
- **`ComplexComponent_DisposesResourcesOnlyWhenDisposingIsTrue`** - Demonstrates that with the fix (`disposing=true`), components with non-trivial disposal logic (timers, cancellation tokens, events) properly clean up managed resources.

### CODE REVIEW

File: src/Components/Components/src/OwningComponentBase.cs [hunk 1]
```diff
@@ -69,12 +69,15 @@ protected virtual void Dispose(bool disposing)
...
     async ValueTask IAsyncDisposable.DisposeAsync()
     {
-        await DisposeAsyncCore().ConfigureAwait(false);
-
-        Dispose(disposing: false);
+        if (!IsDisposed)
+        {
+            await DisposeAsyncCore().ConfigureAwait(false);
+            
+            Dispose(disposing: true);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/Components/src/OwningComponentBase.cs]: @copilot, ok, wrap it

File: src/Components/Components/src/OwningComponentBase.cs [hunk 2]
```diff
@@ -84,13 +86,11 @@ async ValueTask IAsyncDisposable.DisposeAsync()
     /// <returns>A task that represents the asynchronous dispose operation.</returns>
     protected virtual async ValueTask DisposeAsyncCore()
     {
-        if (!IsDisposed && _scope.HasValue)
```
Comment (oroztocil) [inline src/Components/Components/src/OwningComponentBase.cs:87]: Shouldn't the `IsDisposed` check remain here for safety? Since this code is already released, somone might have some combination of `Dispose` and `DisposeAsyncCore` overrides that expect the check to be performed here and the fix would break them.

(The same issue might apply to setting `IsDisposed = true;` that is removed from below. But I don't know if there is a good way to deal with that. The fact that the flag was being set in both `virtual DisposeAsyncCore` and `virtual Dispose(bool)` makes things inherently messy.)

**Review by oroztocil — COMMENTED** [review]
Do we have any components with non-trivial dispose logic on hand? So that we could check that they do not break after change (with double dispose, not executing some code that was executed before, etc.)?

File: src/Components/Components/src/OwningComponentBase.cs (hunk 2 above)
Comment (ilonatommy) [reply src/Components/Components/src/OwningComponentBase.cs:87]: > Shouldn't the `IsDisposed` check remain here for safety? Since this code is already released, somone might have some combination of `Dispose` and `DisposeAsyncCore` overrides that expect the check to be performed here and the fix would break them.

True, it does not hurt to keep the condition from safety reasons.

Comment (ilonatommy) [reply src/Components/Components/src/OwningComponentBase.cs:87]: > (The same issue might apply to setting `IsDisposed = true;` that is removed from below. But I don't know if there is a good way to deal with that. The fact that the flag was being set in both `virtual DisposeAsyncCore` and `virtual Dispose(bool)` makes things inherently messy.)

We cannot restore flag setting in the current state, it would block user code running. It would get us in a situation like this:

DisposeAsync->DisposeAsyncCore->sets true
DisposeAsync->Dispose(true)->condition not entered

Yes, it is messy.

However, flag setting removal, in contrast to condition removal, does not have a potential to break existing users' code.

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/OwningComponentBase.cs [hunk 3]
```diff
@@ -69,12 +69,20 @@ protected virtual void Dispose(bool disposing)
         }
     }
 
-    /// <inhertidoc />
+    /// <inheritdoc />
     async ValueTask IAsyncDisposable.DisposeAsync()
     {
-        await DisposeAsyncCore().ConfigureAwait(false);
-
-        Dispose(disposing: false);
```
Comment (javiercn) [inline src/Components/Components/src/OwningComponentBase.cs:77]: Shouldn't the fix just be `Dispose(disposing: true)` here?

File: src/Components/Components/src/OwningComponentBase.cs [hunk 4]
```diff
@@ -69,12 +69,20 @@ protected virtual void Dispose(bool disposing)
...
+        {
+            try
+            {
+                await DisposeAsyncCore().ConfigureAwait(false);
+            }
+            finally
+            {
+                Dispose(disposing: true);
+            }
+        }
```
Comment (javiercn) [inline src/Components/Components/src/OwningComponentBase.cs]: Not sure why we need the if here, that's already covered inside `DisposeAsyncCore`, same with the `try_finally`. It's overkill.

**Review by javiercn — CHANGES_REQUESTED** [review]
Some further thoughts

File: src/Components/Components/src/OwningComponentBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Components/src/OwningComponentBase.cs]: We shouldn't overcomplicate this. If you override `DisposeAsync` our guidance should be that you do everything inside `DisposeAsyncCore`. The default logic should only handle the case where you are overriding `Dispose` and not anything else.

**Comment by javiercn** [comment]
We don't have to protect against double Dispose; the framework is responsible for correctly disposing the components only Once. Ideally we should just be passing Dispose(disposing: true) instead of false.

File: src/Components/Components/src/OwningComponentBase.cs (hunk 4 above)
Comment (ilonatommy) [reply src/Components/Components/src/OwningComponentBase.cs]: Do we then expect `Dispose` not to be called if user has their own implementation of `DisposeAsyncCore` that threw an exception?

Comment (javiercn) [reply src/Components/Components/src/OwningComponentBase.cs]: It's generally weird to implement both and we would recommend people implementing either of them but not both at the same time. It's unfortunate that there are two implementations, it's an artifact of the fact that one was introduced several years after the other.

In general, the recommendation is to implement the one that you need to, there's no reason to implement both.

**Review by javiercn — APPROVED** [review]

**Review by maraf — APPROVED** [review]

File: src/Components/Components/src/OwningComponentBase.cs [hunk 5]
```diff
@@ -89,8 +89,6 @@ protected virtual async ValueTask DisposeAsyncCore()
             await _scope.Value.DisposeAsync().ConfigureAwait(false);
             _scope = null;
```
Comment (leveyp94-hash) [inline src/Components/Components/src/OwningComponentBase.cs]: Full time and will
