### PR TITLE
Fix HttpSys, setting HttpRequest.ContentLength causes two headers to be enumerated

### LINKED ISSUE #31735: IIS in-proc, setting HttpRequest.ContentLength causes two headers to be enumerated
### Describe the bug

RE: https://github.com/microsoft/reverse-proxy/issues/899. When a user is rewriting and replacing the request body they also update the Content-Length to match. This is important because they're going to proxy the request to 3rd party.

Problem: After setting the HttpRequest.ContentLength property, enumerating the request headers returns both the new and old headers as separate enumeration entries.

This does not reproduce on Kestrel. Check HttpSys (shared code).

### To Reproduce

Send a POST request with a Content-Length and body.

In a middleware, read that body, replace it, and set the new Content-Length. Enumerate the request headers.

```C#
var ms = new MemoryStream(Encoding.UTF8.GetBytes("new body"));
context.Request.ContentLength = ms.Length;
// Workaround
// context.Request.Headers[HeaderNames.ContentLength] = ms.Length.ToString(CultureInfo.InvariantCulture);

// var cl = context.Request.Headers[HeaderNames.ContentLength];

foreach (var header in context.Request.Headers)
{
    var name = header.Key;
    var value = header.Value;
}

context.Request.Body = ms;
```

Expected:
The new Content-Length header is present in the enumeration.

Actual:
The enumerator returns two distinct Content-Length entries, one with the old value and one with the new.
( "Content-Length", [ "3" ] )
( "Content-Length", [ "17" ] )

Note it's _not_ one entry with two values ( "Content-Length", [ "3", "17" ] ).

Workaround: Set the Content-Length via the string indexer instead of the property.
`context.Request.Headers[HeaderNames.ContentLength] = ms.Length.ToString(CultureInfo.InvariantCulture);`

### Further technical details
- .NET 5
- 5.0.201 SDK
- Visual Studio 2019

### PR DESCRIPTION
**Pull request by fvoronin**
**Fix HttpSys, setting HttpRequest.ContentLength causes two headers to be enumerated**
For `RequestHeaders` class, inside `IHeaderDictionary` implementated methods, use other `IHeaderDictionary` implementations instead of own methods.

Fixes #31735

### CODE REVIEW

**Comment by Tratcher** [comment]
Thanks for the PR. Can you briefly explain how this fixes the problem?

**Comment by fvoronin** [comment]
The `RequestHeaders` implementation involves 2 sets of http-headers: _predefined_ - generated for general http-headers: "Accept-Encoding", "Content-Length", "Cookie", "Keep-Alive" etc (see [RequestHeaders.Generated.tt](https://github.com/dotnet/aspnetcore/blob/6868d7fb664facb03373d85f222280b248ed105a/src/Servers/HttpSys/src/RequestProcessing/RequestHeaders.Generated.tt)), and extensible _user defined_ (property `Extra: IDictionary<string, StringValues>`). Iterating over the http headers consists of traversing these two sets.

When we read the http-header value by key through the indexer, we first search the first preset header set, and if the value was not found, we search the second set.

When we set the value of the http-header by key through the indexer, if it is a new http-header that is not in both sets, the corresponding item will be added to the _user defined_ `Extra` set.

The problems start when we set the value of the http-header with a well-known name from the first set.

In `RequestHeaders` there are a couple of methods to read and write http-header values with indexed access by header name - own and `IHeaderDictionary` implementation.

And the point is that the implementation of such methods for `IHeaderDictionary` takes into account the two-component nature of the general collection of http-headers, and extends the _user defined_ set only if there are no values in the _predefined_ set:
https://github.com/dotnet/aspnetcore/blob/6868d7fb664facb03373d85f222280b248ed105a/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L206-L228

And its own implementation of the write-by-index method always writes to the _user defined_ set, even if there are values in the _predefined_ set:
https://github.com/dotnet/aspnetcore/blob/6868d7fb664facb03373d85f222280b248ed105a/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L186-L204

Writing to the `ContentLenght` property is nothing more than setting the http-header value by the `Content-Length` key. And here it all depends on which implementation to use.

**Comment by Tratcher** [comment]
Oh, I see. The setter on the local indexer is broken. The getter checks properties and Extra, but the setter only sets to Extra.
https://github.com/dotnet/aspnetcore/blob/232785ceb876c5eb3d3d6dbabbcedc934521c853/src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs#L186-L204

The ContentLength property is the only place this indexer's setter is used. 

It looks like the setter on `IHeaderDictionary.this[string key]` isn't quite right either, it doesn't do the remove-on-empty check.

Can you fix the root issue by unifying `IHeaderDictionary.this[string key]` and `this[string key]` into one implementation? It doesn't look like we need the IHeaderDictionary explicit implementation. The combine setter would first check for empty values and call remove, else it would try setting via properties, else extra.

**Comment by fvoronin** [comment]
> Can you fix the root issue

I'd love to do it.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs [hunk 1]
```diff
@@ -171,7 +171,7 @@ public bool TryGetValue(string key, out StringValues value)
                         throw new ArgumentOutOfRangeException("value", value.Value, "Cannot be negative.");
                     }
                     _contentLengthText = HeaderUtilities.FormatNonNegativeInt64(value.Value);
-                    this[HttpKnownHeaderNames.ContentLength] = _contentLengthText;
+                    ((IHeaderDictionary)this)[HttpKnownHeaderNames.ContentLength] = _contentLengthText;
```
Comment (Tratcher) [inline src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:174]: These casts can be reverted that you've fixed the indexer, right?

**Review by Tratcher — APPROVED** [review]
Looks good if the tests pass.

File: src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs (hunk 1 above)
Comment (fvoronin) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:174]: Yep. My first think was that inside explicit implementation of `IHeaderDictionary.ContentLength` we should use explicit calls, but now i think that its doesn't mater in this case. Thanks.

Rolling back, did I get that right?

Comment (Tratcher) [reply src/Shared/HttpSys/RequestProcessing/RequestHeaders.cs:174]: There is only one indexer now, there's no need to use the IHeaderDictionary prefix. Yes, please remove it.

**Comment by Tratcher** [comment]
Thanks!
