### PR TITLE
Fix: Inconsistent certificate chain handling between endpoint and default configuration

### LINKED ISSUE #60709: Kestrel inconsistent certificate chain handling between endpoint and default configuration
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

On Kestrel server, there is inconsistent behavior configuring certificates per endpoint versus in the “Default” configuration. The discrepancy occurs when specifying a certificate file containing a chain of certificates where the chain is not included in the system's trust store.

I tested this on Windows, Mac, and Ubuntu using certificate files of the form:
```
server_certificate.crt:
-----BEGIN CERTIFICATE-----
<leaf>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<intermediate>
-----END CERTIFICATE-----
```
```
server_key.key
-----BEGIN EC PRIVATE KEY-----
<key>
-----END EC PRIVATE KEY-----
```
The files were generated using step CLI, and none of the root or intermediate certificates were in the system trust store initially. For each of the following, I removed the certificates from the trust store before each test.
#### If a certificate file is specified in an endpoint's configuration section, Kestrel will:
  - Output the full certificate chain in its TLS response
  - Add the intermediate certificate to the Windows certificate store if it is not already present.

```
appsettings.json:
{
  "Kestrel": {
    "Endpoints": {
      "UsingEndpointConfiguration": {
        "Url": "https://localhost:5000",
        "Certificate": {
          "Path": "server_certificate.crt",
          "KeyPath": "server_key.key"
        }
      },
      "UsingDefaultConfiguration": {
        "Url": "https://localhost:5001",
      }
    },
    "Certificates": {
      "Default":{
        "Path":"server_certificate.crt",
        "KeyPath": "server_key.key"
      }
    }
  }
}
```
`openssl s_client -connect localhost:5000 -showcerts` and `openssl s_client -connect localhost:5001 -showcerts`  correctly responds with a full certificate chain as specified in `server_certificate.crt`.

The intermediate will also be added to the Windows Certificate Store if it is not present.

#### If the certificate file is specified only in the default configuration section:
  - The chain is **not** presented if it is not already in the Windows certificate store.
  - The intermediate certificate is **not** added to the store.
```
{
  "Kestrel": {
    "Endpoints": {
      "UsingDefaultConfiguration": {
        "Url": "https://localhost:5000"
      }
    },
    "Certificates": {
      "Default":{
        "Path":"server_certificate.crt",
        "KeyPath": "server_key.key"
      }
    }
  }
}
```
`openssl s_client -connect localhost:5000 -showcerts` only responds with the leaf certificate specified in `server_certificate.crt`, and the intermediate is not added to the certificate store.

#### If a certificate file is specified in an endpoint's configuration section, Kestrel will:
  - Output the full certificate chain in its TLS response for that endpoint. We will receive the full chain from the following configuration.

```
appsettings.json:
{
  "Kestrel": {
    "Endpoints": {
      "UsingEndpointConfiguration": {
        "Url": "https://localhost:5000",
        "Certificate": {
          "Path": "server_certificate.crt",
          "KeyPath": "server_key.key"
        }
      }
    }
  }
}
```
#### If the certificate file is specified in the default configuration section:
- The certificate chain is **not** presented by endpoints using the default configuration, regardless of if it is specified for other endpoints.
```
appsettings.json:
{
  "Kestrel": {
    "Endpoints": {
      "UsingEndpointConfiguration": {
        "Url": "https://localhost:5000",
        "Certificate": {
          "Path": "server_certificate.crt",
          "KeyPath": "server_key.key"
        }
      },
      "UsingDefaultConfiguration": {
        "Url": "https://localhost:5001",
      }
    },
    "Certificates": {
      "Default":{
        "Path":"server_certificate.crt",
        "KeyPath": "server_key.key"
      }
    }
  }
}
```
`openssl s_client -connect localhost:5001 -showcerts` will only present us the leaf certificate.

#### Behavior on Ubuntu:

- The behavior observed on Ubuntu is the same as on MacOS.

#### Relevant Code Snippet

This behavior appears to be caused by this [line](https://github.com/dotnet/aspnetcore/blob/7f26caa86f90cb81efa98839c57417ef3d4d8154/src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs#L131) in `TlsConfigurationLoader.cs`:
```
 var (defaultCert, _ /* cert chain */) = _certificateConfigLoader.LoadCertificate(defaultCertConfig, "Default");
```

 which does not process the full certificate chain when it is used in the default configuration section. As a result, the subsequent [call](https://github.com/dotnet/aspnetcore/blob/7f26caa86f90cb81efa98839c57417ef3d4d8154/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L108) to `SslStreamCertificateContext.Create` does not add the full certificate chain:
 ```
 _serverCertificateContext = SslStreamCertificateContext.Create(certificate, additionalCertificates: options.ServerCertificateChain);
 ```
 On Mac and Ubuntu this means the chain is never presented on endpoints using the default configuration.

 On Windows, `SslStreamCertificateContext.Create` adds intermediates specified in the call to the Windows Certificate Store if they are not already present. This means if the certificate chain has been specified on an endpoint level configuration, it will be added to the Windows trust store, and subsequently any endpoints specified using the default configuration will also have their full chain presented. 
 
 However, if the file is *only* specified on the default configuration, the chain will be thrown out and never added to the trust store from this call, so any endpoints using the default configuration will only present their leaf certificates.

### Expected Behavior

The behavior when specifying the certificate file in an individual endpoint’s configuration should have identical behavior to endpoints using the default configuration. The full certificate chain should be included for endpoints using the default configuration when possible.

### Steps To Reproduce

1. Generate some certificates using `step` CLI or similar CA such as Hashicorp Vault, where intermediates are not in the system trust store
2. Create a minimal dotnet app, for example: [repo](https://github.com/jnjudge1/dotnetcerttest2)
3. Run the app, then `openssl s_client -connect localhost:5000 -showcerts`, and observe the certificate chain

### Exceptions (if any)

_No response_

### .NET Version

9.0.103

### Anything else?

IDE: VSCode 1.97.2
### Tools 
step cli: https://github.com/smallstep/cli

### PR DESCRIPTION
**Pull request by jnjudge1**
# Fix: Inconsistent certificate chain handling between endpoint and default configuration

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Changes Kestrel configuration to process default certificate loading configurations the same as per endpoint configurations. With this change, certificates specified in the default configuration section will have their chains presented on the server even if their intermediates are not present in the system certificate store.

### IHttpsConfigurationService.cs:
- Changed to add the `CertificateChain` property onto the internal `CertificateAndConfig` struct, necessary for passing cert chain from `TlsConfigurationLoader` to `KestrelConfigurationLoader`.

### TlsConfigurationLoader.cs:
- Changed to use the certificate chain from the loaded default certificate to return a `CertificateAndConfig` object with the chain specified if the chain is not null.

### KestrelConfigurationLoader.cs:
- Changed to add an internal `DefaultCertificateChain` property for specifying the default certificate chain to load on endpoints in `KestrelServerOptions.ApplyDefaultCertificate`.

### KestrelServerOptions.cs:
- Changed to get the default certificate chain specified in `KestrelConfigurationLoader` and set the `ServerCertificateChain` property on the `httpsOptions` for an endpoint.

Fixes #60709

### CODE REVIEW

**Comment by jnjudge1** [comment]
> @jnjudge1 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by martincostello** [comment]
FYI changing something like certificate handling this is almost certainly going to need tests to get accepted, particularly as it's a bug fix.

File: src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs [hunk 1]
```diff
@@ -128,9 +128,12 @@ public ListenOptions UseHttpsWithSni(
     {
         if (configurationReader.Certificates.TryGetValue("Default", out var defaultCertConfig))
         {
-            var (defaultCert, _ /* cert chain */) = _certificateConfigLoader.LoadCertificate(defaultCertConfig, "Default");
+            var (defaultCert, defaultCertChain) = _certificateConfigLoader.LoadCertificate(defaultCertConfig, "Default");
             if (defaultCert != null)
             {
+                if(defaultCertChain != null){
```
Comment (gfoidl) [inline src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs:134]:
```suggestion
                if (defaultCertChain != null)
                {
```

**Comment by jnjudge1** [comment]
> FYI changing something like certificate handling this is almost certainly going to need tests to get accepted, particularly as it's a bug fix.

Thanks for your feedback @martincostello ! I've added a test that fails on main but succeeds with this change.

File: src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs (hunk 1 above)
Comment (jnjudge1) [reply src/Servers/Kestrel/Core/src/TlsConfigurationLoader.cs]: Thank you for your feedback @gfoidl , I've gone ahead and formatted the files in this PR.

**Review by BrennanConroy — APPROVED** [review]
Nice find and appreciate the fix as well! Comments are just code cleanup nits.

It looks like it was probably an oversight when the cert chain work was done, don't see any reference as to why we ignored the chain which makes me think it was meant to be temporary and then forgotten about.

**Comment by jnjudge1** [comment]
> Nice find and appreciate the fix as well! Comments are just code cleanup nits.
> 
> It looks like it was probably an oversight when the cert chain work was done, don't see any reference as to why we ignored the chain which makes me think it was meant to be temporary and then forgotten about.

Thanks @BrennanConroy ! That makes sense, happy to help here. I've gone back and resolved those nits, if all looks good please merge when possible. Thank you!

**Comment by adityamandaleeka** [comment]
Great work @jnjudge1!
