### PR TITLE
Fixed nullable annotation.

### LINKED ISSUE #28919: Wrong nullable annotations on ITicketStore.RetrieveAsync
The interface [ITicketStore](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/src/ITicketStore.cs) should have `Task<AuthenticationTicket?>` return type for method `RetrieveAsync`. The service using this method [expects](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L157-L158) that it could return null. Also, the only sample implementation in this repository, [MemoryCache](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/samples/CookieSessionSample/MemoryCacheTicketStore.cs#L42-L47), clearly can return null from its method.

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Fixes https://github.com/dotnet/aspnetcore/issues/28919

### CODE REVIEW

File: src/Security/Authentication/Cookies/src/ITicketStore.cs [hunk 1]
```diff
@@ -31,7 +31,7 @@ public interface ITicketStore
         /// </summary>
         /// <param name="key">The key associated with the identity.</param>
         /// <returns>The identity associated with the given key, or if not found.</returns>
```
Comment (JamesNK) [inline src/Security/Authentication/Cookies/src/ITicketStore.cs:33]:
```suggestion
        /// <returns>The identity associated with the given key, or <c>null</c> if not found.</returns>
```

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
Thanks for the PR! Looks good to me.

**Comment by MCCshreyas** [comment]
Thanks @JamesNK for fixing comment and merging PR! 
It's just morning here on my side! ☺️😁
