### PR TITLE
[wasm][debugger] Support NO_PROXY": "localhost" in launchSettings.json

### LINKED ISSUE #88051: Blazor Wasm debugging with a proxy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure where/how to get an answer from this.  WASM Hosted debugs successfully on my personal computer.  However working in an enterprise environment that uses a proxy there is a problem.  I created a vanilla Blazor WASM Hosted project using the VS template.  
launchSettings.json has the
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
lines

When I F5 for debug I get (I have used square brackets to replace sensitive values):

 Content root path: [MY PATH]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[ENTERPRISE_PROXY].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   
The only thing (and I don't know that it is a thing) is that the proxy in my machine's Environment Variable has port 80 specified (the :80 suffix) which I don't see in the error message.

What can resolve this debugging issue?

### Expected Behavior

Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Steps To Reproduce

Within an enterprise using a proxy
Create Blazor WASM hosted project using standard template.
Press F5, run in debug mode

### Exceptions (if any)

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7086
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5007
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\...\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\
got exception System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://[...].com/' failed with status code '403'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()

C:\Users\[...]\repos\BlazorWasmVanilla\BlazorWasmVanilla\Server\bin\Debug\net6.0\BlazorWasmVanilla.Server.exe (process 35192) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

### .NET Version

Tried with .Net 6 and .Net 7

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
Fixes https://github.com/dotnet/runtime/issues/88051
Depends on https://github.com/dotnet/runtime/pull/88884

### CODE REVIEW

**Comment by thaystg** [comment]
@mkArtakMSFT who can help me to review this one?

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs [hunk 1]
```diff
@@ -46,11 +46,12 @@ private static async Task<string> LaunchAndGetUrl(IServiceProvider serviceProvid
         var executablePath = LocateDebugProxyExecutable(environment);
         var muxerPath = DotNetMuxer.MuxerPathOrDefault();
         var ownerPid = Environment.ProcessId;
-
+        var noProxyEnvVar = Environment.GetEnvironmentVariable("NO_PROXY");
```
Comment (radical) [inline src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:49]: The name needs a prefix I think otherwise it seems too generic.

Also, the name sounds like it is a bool even though it isn't.

Comment (thaystg) [reply src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:49]: It looks like this is something almost stardard, that is why I followed the name and the format:
https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/
Also this is mentioned in Blazor documentation:
https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser

Comment (radical) [reply src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:49]: Ignore me please 😃

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs [hunk 2]
```diff
@@ -46,11 +46,12 @@ private static async Task<string> LaunchAndGetUrl(IServiceProvider serviceProvid
...
+        var ignoreProxyForLocalAddress = (noProxyEnvVar is not null && (noProxyEnvVar.Equals("localhost") || noProxyEnvVar.Equals("127.0.0.1"))) ? "--IgnoreProxyForLocalAddress True" : "";
```
Comment (mkArtakMSFT) [inline src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:50]: What if there is some other value assigned to the NO_PROXY variable?
The current logic simply ignores it, without any log or warning. Maybe at least worth logging a message about it so that customers who choose to use some custom value know what's going on from logs ?

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @thaystg !
