### PR TITLE
Use TryParse and BindAsync methods from interfaces

### LINKED ISSUE #36935: Support finding & calling static TryParse/BindAsync methods for parameter binding of RequestDelegateFactory parameters from interfaces implemented by the target parameter type
In #36663 we made the change to support finding `TryParse` and `BindAsync` methods from types inherited by the parameter type. We also support finding these methods on interfaces that the parameter type implements (either directly or inherited). This allows for the bind logic to be easily shared between different type hierarchies, without having to have it in the actual hierarchy itself, or implemented via a wrapper generic type.

e.g.
``` c#
app.MapPost("/widget", (CreateWidgetDTO dto) =>
{
    // Use the dto
});

public interface ICompositeSourceBinder<T>
{
    // typeof(T) must equal ParameterInfo.Type otherwise we throw
    public static T BindAsync(HttpContext context, ParameterInfo parameter)
    {
        // Use reflection to bind the properties on T
    }
}

public class CreateWidgetDTO : MyBaseType, ICompositeSourceBinder<CreateWidgetDTO>
{
    [FromRoute]
    public string? Name { get; set; }

    [FromQuery]
    public int Id { get; set; }
}
```

Console app of pseudo-logic:
``` c#
using System.Reflection;

var targetType = typeof(PleaseBindMe);
var bindMethod = FindBindMethod(targetType);

Console.WriteLine(bindMethod switch { MethodInfo mi => $"Found a matching method to bind to {targetType} on {mi.DeclaringType?.Name}", _ => "No method found" });

if (bindMethod != null)
{
    ParameterInfo? parameter = null;
    var result = bindMethod.Invoke(null, new object?[] { new BindContext(), parameter }) as PleaseBindMe;
    Console.WriteLine(result switch
    {
        PleaseBindMe pbm => $"Successfully called Bind method, value of `{nameof(PleaseBindMe.StringProperty)}` is \"{pbm.StringProperty}\"",
        _ => throw new InvalidOperationException("Problem calling Bind method")
    });
}

MethodInfo? FindBindMethod(Type type)
{
    var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy)
        .Union(type.GetInterfaces().SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy)))
        .Where(m => m.ReturnType == type && HasRequiredParameters(m))
        .ToList();

    return methods.Count switch
    {
        > 1 => throw new InvalidOperationException($"Ambiguous method matches, found {methods.Count} potential methods"),
        1 => methods[0],
        _ => null
    };
}

bool HasRequiredParameters(MethodInfo method)
{
    var parameters = method.GetParameters();
    
    if (parameters.Length != 2)
    {
        return false;
    }

    if (parameters[0].ParameterType != typeof(BindContext)
        || parameters[1].ParameterType != typeof(ParameterInfo))
    {
        return false;
    }

    return true;
}

interface IBindMe<T> where T : IBindMe<T>, new()
{
    public static T? Bind(BindContext context, ParameterInfo parameter)
    {
        var output = new T();

        if (output != null)
        {
            // Leave fingerprint on the first string property
            var stringProp = output.GetType().GetProperties().FirstOrDefault(p =>
                p.PropertyType == typeof(string) && p.GetIndexParameters().Length == 0);

            if (stringProp != null)
            {
                var currentValue = stringProp.GetValue(output) as string;
                stringProp.SetValue(output, $"{currentValue}{(string.IsNullOrEmpty(currentValue) ? "" : " ")}[Bound via {nameof(IBindMe<T>)}]");
            }
        }

        return output;
    }
}

interface INotBinding
{
    public static object? Bind()
    {
        return null;
    }
}

interface IPleaseBindMeBinder
{
    public static PleaseBindMe? Bind(BindContext context, ParameterInfo parameter)
    {
        return new PleaseBindMe();
    }
}

class PleaseBindMe : IBindMe<PleaseBindMe>, INotBinding
    // Uncomment following line to cause bind method ambiguity
    //, IPleaseBindMeBinder
{
    public string? StringProperty { get; set; }
}

class BindContext { }
```

### PR DESCRIPTION
**Pull request by halter73**
This PR searches the interfaces implemented by minimal route handler parameter types for TryParse and BindAsync if no methods are found directly on the type hierarchy first.

As mentioned in #36935, the motivation is to allow the bind logic to be easily shared between different type hierarchies meaning that DTOs can inherit from other classes unrelated to binding. Here's the sample from the issue:

``` c#
app.MapPost("/widget", (CreateWidgetDTO dto) =>
{
    // Use the dto
});

public interface ICompositeSourceBinder<T>
{
    // typeof(T) must equal ParameterInfo.Type otherwise we throw
    public static T BindAsync(HttpContext context, ParameterInfo parameter)
    {
        // Use reflection to bind the properties on T
    }
}

public class CreateWidgetDTO : MyBaseType, ICompositeSourceBinder<CreateWidgetDTO>
{
    [FromRoute]
    public string? Name { get; set; }

    [FromQuery]
    public int Id { get; set; }
}
```

Fixes #36935

### CODE REVIEW

File: src/Shared/ParameterBindingMethodCache.cs [hunk 1]
```diff
@@ -249,6 +249,60 @@ public bool HasTryParseMethod(ParameterInfo parameter)
...
+            {
+                return methodInfo;
+            }
+
+            var candidateInterfaceMethodInfo = default(MethodInfo);
+
+            // Check all interfaces for implementations. Fail if there are duplicates.
+            foreach (var implementedInterface in type.GetInterfaces())
+            {
+                var interfaceMethod = implementedInterface.GetMethod(name, BindingFlags.Public | BindingFlags.Static, parameterTypes);
```
Comment (DamianEdwards) [inline src/Shared/ParameterBindingMethodCache.cs:268]: what happens in the case an interface implements another? Should we be passing `BindingFlags.FlattenHierarchy` here too or does it not apply to interfaces?

Comment (DamianEdwards) [reply src/Shared/ParameterBindingMethodCache.cs:268]: Actually I don't think it matters as the call to `GetInterfaces` gets all interfaces inherited or implemented so that effectively flattens the interface hierarchy up front.

Comment (DamianEdwards) [reply src/Shared/ParameterBindingMethodCache.cs:268]: I now see you even have a test for this, lovely!

**Review by DamianEdwards — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]
