### PR TITLE
Fix nullability context handling in RDG

### LINKED ISSUE #54020: [9.0-preview.1] Request Delegate Generator emits nullable annotations when Nullable Reference Types not enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If an application does not use nullable reference types but does use the request delegate generator, the application fails to compile due to RDG emitting code with nullable annotations.

### Expected Behavior

RDG does not emit nullable annotations if the project does not use nullable reference types.

### Steps To Reproduce

- Clone the [martincostello/SignInWithAppleSample](https://github.com/martincostello/SignInWithAppleSample) repository.
- Checkout the https://github.com/martincostello/SignInWithAppleSample/commit/4c6ea88a1d6e8f79a63685cbfc4678994c902796 commit.
- Run `dotnet build` from the root of the repository.

### Exceptions (if any)

Example error:

```console
❯ dotnet build
MSBuild version 17.10.0-preview-24101-01+07fd5d51f for .NET
Restore complete (1.0s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  SignInWithApple failed with errors (1.3s)
    C:\Coding\martincostello\SignInWithAppleSample\src\SignInWithApple\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(281,32): error CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source. [C:\Coding\martincostello\SignInWithAppleSample\src\SignInWithApple\SignInWithApple.csproj]
```

### .NET Version

9.0.100-preview.1.24101.2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/54020.

### CODE REVIEW

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs [hunk 1]
```diff
@@ -672,6 +672,7 @@ public static IEndpointRouteBuilder MapPost(this IEndpointRouteBuilder app, int
     public async Task TestHandlingOfGenericWithNullableReferenceTypes()
     {
         var source = """
+#nullable enable
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs:675]: Is this the only test that tests nullability in user code 😮
Kind of surprising.

Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs:675]: @BrennanConroy The other tests do use nullable annotations but they make use of the source template that is in the base class which enables it there:

https://github.com/dotnet/aspnetcore/blob/2c0ee4c870556d823ea5a0b35a8ba1b8ae81142c/src/Http/Http.Extensions/test/RequestDelegateGenerator/RequestDelegateCreationTestBase.cs#L268

**Review by BrennanConroy — APPROVED** [review]
