### PR TITLE
Use fullpath for WebRootPath in WebApplicationBuilder

### LINKED ISSUE #33795: WebApplicationBuilder.WebHost.UseWebRoot(string) throws given a relative path
```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseWebRoot("www");
```

```
> dotnet run
Building...
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters) in Microsoft.Extensions.FileProviders.Physical.dll:token 0x600001b+0x28
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root) in Microsoft.Extensions.FileProviders.Physical.dll:token 0x600001a+0x0
   at Microsoft.AspNetCore.Builder.WebHostEnvironment.ResolveFileProviders(IConfiguration configuration) in Microsoft.AspNetCore.dll:token 0x6000071+0x19
   at Microsoft.AspNetCore.Builder.ConfigureWebHostBuilder.UseSetting(String key, String value) in Microsoft.AspNetCore.dll:token 0x600003c+0x91
   at Microsoft.AspNetCore.Hosting.HostingAbstractionsWebHostBuilderExtensions.UseWebRoot(IWebHostBuilder hostBuilder, String webRoot) in Microsoft.AspNetCore.Hosting.Abstractions.dll:token 0x600000d+0xe
   at <Program>$.<Main>$(String[] args) in C:\dev\halter73\swagger\Minimal\Program.cs:line 6
```

On a "real" `IWebHostBuilder`, relative paths are supported and appear to be treated relative to the `I(Web)HostEnvironment.ContentRootPath`.

**Note**: No ArgumentException is only thrown if a `www` exists in the current working directory because of [this check](https://github.com/dotnet/aspnetcore/blob/e858e3dabbe8b9e0cbd8b6f57fcd7a5652984252/src/DefaultBuilder/src/WebHostEnvironment.cs#L98-L101). Both the `Directory.Exists` check and `PhysicalFileProvider` should work on the same normalized path.

### PR DESCRIPTION
**Pull request by captainsafia**
Fixes https://github.com/dotnet/aspnetcore/issues/33795.

### CODE REVIEW

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 1]
```diff
@@ -106,13 +105,35 @@ public void ResolveFileProviders(IConfiguration configuration)
             }
         }
 
+        private string ResolveWebRootPath(string webRootPath, string contentRootPath)
+        {
+            if (string.IsNullOrEmpty(webRootPath))
+            {
+                return contentRootPath;
```
Comment (Tratcher) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:112]: Shouldn't this be Path.GetFullPath(contentRootPath)?

Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:112]: Yep -- good call!

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 2]
```diff
@@ -106,13 +105,35 @@ public void ResolveFileProviders(IConfiguration configuration)
...
 
         public IFileProvider WebRootFileProvider { get; set; }
-        public string WebRootPath { get; set; }
+
+        // Mimick the setting used in HostingEnvironment
+        private string _webRootPath = default!;
+        public string WebRootPath
+        {
+            get => _webRootPath;
+            set => _webRootPath = ResolveWebRootPath(value, ContentRootPath);
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:136]: What is this mimicking exactly? Does any other `IWebHostEnvironment` not set the `WebRootPath` to exactly what it's assigned to?

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 3]
```diff
@@ -81,6 +78,8 @@ internal void CopyPropertiesTo(IWebHostEnvironment destination)
             destination.ApplicationName = ApplicationName;
             destination.EnvironmentName = EnvironmentName;
 
+            ResolveFileProviders(new Configuration());
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:81]: Should we skip this if the FileProviders aren't still the NullFileProvider?

**Comment by halter73** [comment]
Can we add a WebApplicationFunctionalTests that verifies something along the lines of:

```c#
var builder = WebApplication.CreateBuilder();
builder.Environment.WebRootPath = "www";
var app = builder.Build();
var env = app.Services.GetRequiredService<IWebHostEnvironment>();

// Something that verifies that WebRootPath and WebRootFileProvider is what we expect.

```

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 3 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:81]: I'm thinking setting ContentRootPath/WebRootPath should reset their respective IFileProviders though.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 2 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: I think we do need to update WebRootPath, but we should probably only do it when we call `WebApplicationBuilder.Build()`. I haven't looked into it super deeply, so I could probably be convinced otherwise.

It looks like the ContentRootPath can also be relative to the executing assembly. When I use the generic host and write something like this:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseContentRoot("www");
        webBuilder.UseWebRoot("www");
        webBuilder.UseStartup<Startup>();
    });
```

I get this output:

```
C:\dev\halter73\swagger\WebApi webroot ↑1  ~4 ?1 ❯ dotnet run
...
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\halter73\swagger\WebApi\bin\Debug\net6.0\www
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/www.html - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/www.html'. Physical path: 'C:\dev\halter73\swagger\WebApi\bin\Debug\net6.0\www\www\www.html'
...
```

This seems to indicate to me that the content root is relative to `Path.GetDirectoryName(Assembly.GetEntryAssembly().Location)` (or maybe `GetExecutingAssembly()`). @Tratcher do you know where this logic is?

Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: I think the logic for setting the `ContentRootPath` is located here:

https://github.com/dotnet/aspnetcore/blob/2383d442acf041d65ffb90e4f1cd9a5bbafc01e3/src/Hosting/Hosting/src/WebHostBuilder.cs#L266-L269

The call made to the `Initialize` combines the `ContentRootPath` when setting the `WebRootPath`.

https://github.com/dotnet/aspnetcore/blob/0ae054093c772562ab6c71a042c5d018aa715309/src/Hosting/Hosting/src/Internal/HostingEnvironmentExtensions.cs#L87-L99

Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: > I think we do need to update WebRootPath, but we should probably only do it when we call WebApplicationBuilder.Build(). I haven't looked into it super deeply, so I could probably be convinced otherwise.

I'm assuming you refer to [this](https://github.com/dotnet/aspnetcore/blob/2383d442acf041d65ffb90e4f1cd9a5bbafc01e3/src/DefaultBuilder/src/WebApplicationBuilder.cs#L106). With that approach, we'd end up doing the full-path resolution in:

https://github.com/dotnet/aspnetcore/blob/2383d442acf041d65ffb90e4f1cd9a5bbafc01e3/src/DefaultBuilder/src/ConfigureWebHostBuilder.cs#L74

Since the invocation path is WebApplication.Build => ConfigureWebHost => ApplySettings => UseSetting.

https://github.com/dotnet/aspnetcore/blob/2383d442acf041d65ffb90e4f1cd9a5bbafc01e3/src/DefaultBuilder/src/ConfigureWebHostBuilder.cs#L97-L100

But doing it here wouldn't account for the scenario where we want to support users setting the `WebRootPath` directly via `builder.Environment.WebRootPath = "foo"`.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 3 above)
Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:81]: Yep -- that makes sense.

I'm thinking we might want to get rid of the `ResolveFileProviders` method entirely and just set the providers for `ContentRootPath`/`WebRootPath` in their respective setters.

Also, should we do this:

```diff
- public IFileProvider ContentRootFileProvider { get; set; }
+ public IFileProvider ContentRootFileProvider { get; private set; }
```

E.g. is there a scenario where a user would want to set the file provider independent of the path?

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 2 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: Could we call ResolveFileProviders at the start of ApplyEnvironmentSettings to handle that?

Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: And then ResolveFileProviders would include the ResolveWebRootPath/ResolveContentRootPath logic.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 3 above)
Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:81]: I think we should keep `ResolveFileProviders` and have it call into `ResolveWebRootPath`.

> E.g. is there a scenario where a user would want to set the file provider independent of the path?

I could see there being some sort of custom IFileProvider scenario where you set a real path than then manually set a IFileProvider that has better caching or something. That's what concerns me about resetting. Theoretically, someone could set these properties in the opposite order.

**Comment by captainsafia** [comment]
⬆️ 📅 

- Add test scenario recommended in https://github.com/dotnet/aspnetcore/pull/34140#issuecomment-875151495
- Set providers when paths are set and remove `ResolveFileProviders`
- Throw exception if providers are set before paths are

**Comment by halter73** [comment]
What happens if you set a relative path for the web root then set a relative path for the content root? Can we add a test where both the content root and web root are set relatively?

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 4]
```diff
@@ -100,19 +93,81 @@ public void ResolveFileProviders(IConfiguration configuration)
...
+        // ContentRootPath and WebRootPath are set to default! on
+        // initialization to match the behavior in HostingEnvironment.
+        private string _contentRootPath = default!;
+        public string ContentRootPath
+        {
+            get => _contentRootPath;
+            set
+            {
+                _contentRootPath = value;
+                if (Directory.Exists(_contentRootPath))
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:137]: Shouldn't we have logic like what you pointed to in https://github.com/dotnet/aspnetcore/pull/34140#discussion_r664953734 to handle a relative content root path?

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 5]
```diff
@@ -313,6 +313,30 @@ public void WebApplicationBuilder_CanClearDefaultLoggers()
...
+            }
+            else
+            {
+                builder.WebHost.UseWebRoot(webRootPath);
+                Assert.Equal(webRootPath, builder.WebHost.GetSetting("webroot"));
+            }
+
+            
+            var app = builder.Build();
+            Assert.Equal(fullWebRootPath, app.Environment.WebRootPath);
```
Comment (halter73) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:337]: Can we add a WebApplicationFunctionalTests that checks we have a working PhysicalFileProvider too?

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 6]
```diff
@@ -100,19 +93,81 @@ public void ResolveFileProviders(IConfiguration configuration)
...
 
-        public IFileProvider ContentRootFileProvider { get; set; }
-        public string ContentRootPath { get; set; }
+        private IFileProvider _contentRootFileProvider = NullFileProvider;
+        public IFileProvider ContentRootFileProvider
+        {
+            get => _contentRootFileProvider;
+            set
+            {
+                if (_contentRootPath == default(string))
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:107]: Nit:

```suggestion
                if (_contentRootPath is null)
```

If we keep this check, we should add a test for it. I'm not sure we need it though. `_contentRootPath` is set by the ctor, and this doesn't catch all the ways the file provider and path could become out of sync anyway.

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 7]
```diff
@@ -100,19 +93,81 @@ public void ResolveFileProviders(IConfiguration configuration)
...
+            }
+        }
+
+        private string _webRootPath = default!;
+        public string WebRootPath
+        {
+            get => _webRootPath;
+            set
+            {
+                _webRootPath = ResolveWebRootPath(value, ContentRootPath ?? Directory.GetCurrentDirectory());
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:150]: Should we just set ContentRootPath to Directory.GetCurrentDirectory() if it's not set at this point?

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 8]
```diff
@@ -100,19 +93,81 @@ public void ResolveFileProviders(IConfiguration configuration)
...
+                    _webRootFileProvider = new PhysicalFileProvider(_webRootPath);
+                }
+            }
+        }
+
+        private string ResolveWebRootPath(string webRootPath, string contentRootPath)
+        {
+            if (string.IsNullOrEmpty(webRootPath))
+            {
+                return Path.GetFullPath(contentRootPath);
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:162]: If you call `IWebHostBuilder.UseSetting(WebHostDefaults.WebRootKey, null)` with the generic host does the web root become the content root? This seems very dangerous because we don't know what sensitive files might be in the content root that might now be served by static files or something. We should definitely have test cases for these kind of scenarios.

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 9]
```diff
@@ -100,19 +93,81 @@ public void ResolveFileProviders(IConfiguration configuration)
...
-                StaticWebAssetsLoader.UseStaticWebAssets(this, configuration);
-            }
         }
 
         public string ApplicationName { get; set; }
         public string EnvironmentName { get; set; }
 
-        public IFileProvider ContentRootFileProvider { get; set; }
-        public string ContentRootPath { get; set; }
+        private IFileProvider _contentRootFileProvider = NullFileProvider;
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:101]: Nit: put private fields above the constructor.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 6 above)
Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: Per our discussion, we're removing this check to account for edge cases that would not be accounted for. This means that it's up to the user to ensure that the provider and path are consistent but it's not likely the user will intentionally misset the provider here.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 8 above)
Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: Updated this to no-op if the user attempts to set the `WebRootPath` to null. This matches the behavior in the current `GenericHostBuilder` as well.

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs (hunk 5 above)
Comment (captainsafia) [reply src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:337]: This is validated in `WebHostEnvironmentTests.SettingPathsSetsContentProviders` now. Not a full end-to-end test but validates that the providers are updated when the path is.

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 4 above)
Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:128]: Done.

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 10]
```diff
@@ -15,44 +16,47 @@ internal class WebHostEnvironment : IWebHostEnvironment
...
+        private IFileProvider _webRootFileProvider = NullFileProvider;
+        // ContentRootPath and WebRootPath are set to default! on
+        // initialization to match the behavior in HostingEnvironment.
+        private string _contentRootPath = default!;
+        private string _webRootPath = default!;
+
         public WebHostEnvironment(Assembly? callingAssembly)
         {
-            ContentRootPath = Directory.GetCurrentDirectory();
+            ContentRootPath = AppContext.BaseDirectory;
```
Comment (captainsafia) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:28]: @halter73 On closer examination of the code, it looks like the existing builder actually sets the `ContentRootPath` to `AppContext.BaseDirectory` by default.

https://github.com/dotnet/aspnetcore/blob/cb9ed02a31b7ea5c8ce8b0f54c5230d9a904739c/src/Hosting/Hosting/src/WebHostBuilder.cs#L266

`ResolveContentRootPath` will set the content root to `AppContext.BaseDirectory` if the user doesn't provide a path in the options.

Given this, I think it is sensible to set the root path to AppContext.BaseDirectory by default.

Comment (halter73) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:28]: I'm not sure the current builder just uses `AppContext.BaseDirectory`, but I haven't traced through all the logic. Here's what I see in a sample app though:

```C#
using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace WebApi
{
	public class Program
	{
		public static void Main(string[] args)
		{
            Console.WriteLine($"AppContext.BaseDirectory: {AppContext.BaseDirectory}");
			CreateHostBuilder(args).Build().Run();
		}

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
    }
}
```

Output:

```
C:\dev\halter73\swagger\WebApi webroot ↑2  ~2 ❯ dotnet run
Building...
AppContext.BaseDirectory: C:\dev\halter73\swagger\WebApi\bin\Debug\net6.0\
...
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\halter73\swagger\WebApi
```

Now if I set a relative path, it *does* seem to use `AppContext.BaseDirectory`:

If I add the following line to the `.ConfigureWebHostDefaults` callback

```C#
webBuilder.UseContentRoot("MyContentRoot");
```

Output:

```
C:\dev\halter73\swagger\WebApi webroot ↑2  ~2 ❯ dotnet run
Building...
AppContext.BaseDirectory: C:\dev\halter73\swagger\WebApi\bin\Debug\net6.0\
...
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\halter73\swagger\WebApi\bin\Debug\net6.0\MyContentRoot
```

This will fail with a `DirectoryNotFoundException` if `bin\Debug\net6.0\MyContentRoot` doesn't exist. I don't like this behavior and would like to make it more consistent for `WebApplicationBuilder` than it is for the generic host. I'm not positive what the generic host is using when you don't try to set a relative path for the content root.

Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs]: We're sticking to the current behavior per offline discussion.

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs [hunk 11]
```diff
@@ -58,16 +60,94 @@ public void ApplyEnvironmentSettingsUsesTheCorrectKeysAndProperties()
...
+        [Fact]
+        public void SetContentRootAfterRelativeWebRoot()
+        {
+            var environment = new WebHostEnvironment();
+            var webRootPath = "/some-relative-path";
+            var tempPath = Path.GetTempPath();
+
+            environment.WebRootPath = webRootPath;
+
+            Assert.Equal(Path.Combine(AppContext.BaseDirectory, webRootPath), environment.WebRootPath);
```
Comment (halter73) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs:142]: This is only because it's using the test constructor, right? Since the ContentRoot hasn't been set to a relative path at this point, I think this should still be relative to `Directory.GetCurrentDirectory();`. I think we should change this test to just call the `WebHostEnvironment(Assembly? callingAssembly)` ctor to verify we don't regress that.

**Review by halter73 — APPROVED** [review]

File: src/DefaultBuilder/src/WebHostEnvironment.cs [hunk 12]
```diff
@@ -100,19 +100,67 @@ public void ResolveFileProviders(IConfiguration configuration)
...
+                }
+            }
+        }
+
+        public string WebRootPath
+        {
+            get => _webRootPath;
+            set
+            {
+                if (!string.IsNullOrEmpty(value))
```
Comment (halter73) [inline src/DefaultBuilder/src/WebHostEnvironment.cs:140]: I think we need a test case for 

```
builder.WebHost.UseWebRoot("MyWebRoot");
builder.WebHost.UseWebRoot("");
```

It looks like the WebRoot will stay "MyWebRoot" because of this, but with the generic host it would reset to it's default value of "wwwroot".

**Review by halter73 — CHANGES_REQUESTED** [review]

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs [hunk 13]
```diff
@@ -58,16 +60,94 @@ public void ApplyEnvironmentSettingsUsesTheCorrectKeysAndProperties()
...
+
+            // Setting the ContentRootPath after setting a relative WebRootPath
+            // does not modify the WebRootPath
+            environment.ContentRootPath = tempPath;
```
Comment (halter73) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs:146]: I changed my mind about this. I think we do need to preserve the relative web root path and re-ResolvePathToRoot when the ContentRootPath changes in order to keep the behavior consistent with the generic host when you call UseWebRoot() before UseContentRoot().

File: src/DefaultBuilder/src/WebHostEnvironment.cs (hunk 12 above)
Comment (captainsafia) [reply src/DefaultBuilder/src/WebHostEnvironment.cs:140]: `CannotUnsetPaths` covers since this scenario since we handle the null/empty string case together. This test case currently assumes that setting a path to null/empty string will no-op so we'll have to change the behavior here to mimic what `ContentRootPath` does (fall back to some default).

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs [hunk 14]
```diff
@@ -58,16 +60,94 @@ public void ApplyEnvironmentSettingsUsesTheCorrectKeysAndProperties()
...
+            environment.WebRootPath = webRootPath;
+
+            Assert.Equal(Path.Combine(AppContext.BaseDirectory, webRootPath), environment.WebRootPath);
+            Assert.Equal(Directory.GetCurrentDirectory(), environment.ContentRootPath);
+
+            // Setting the ContentRootPath after setting a relative WebRootPath
+            environment.ContentRootPath = tempPath;
+
+            Assert.Equal(tempPath, environment.ContentRootPath);
+            Assert.Equal(Path.Combine(tempPath, webRootPath), environment.WebRootPath);
```
Comment (halter73) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebHostEnvironmentTests.cs:150]: Can we verify that the PhysicalFileProviders have the correct `Root` in this test too?

**Review by halter73 — APPROVED** [review]
