### PR TITLE
Fixed bug in NavigationManager.GetUriWithQueryParameter(s) to include uri with hash string

### LINKED ISSUE #44204: [Blazor] The `NavigationManager.GetUriWithQueryParameter()` method returns inappropriate URL when the current URL has a hash string
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the current URL has a hash string like a `https://localhost:5001/#foo`, calling the method `NavigationManager.GetUriWithQueryParameter("key" "value")` will return the URL that ends with the query string, like a "https://localhost:5001/#foo?key=value". (it doesn't end with the hash string.)

If the Blazor application navigates to that URL which is a bit odd, the Blazor app still works as expected, but in the JavaScript world, the `location.hash` return `#foo?value=abc` (it is not `#foo`), and the `location.search` returns an empty string (it is not `?key=value`).

### Expected Behavior

The method `NavigationManager.GetUriWithQueryParameter("key" "value")` should return the URL `https://localhost:5001/?key=value#foo` (it ends with the hash string) when the current URL is `https://localhost:5001/#foo`.

### Steps To Reproduce

Please see the sample Blazor WebAssembly app project I attached below.
 
[📦GetUriWithQueryParameterWithHash.zip](https://github.com/dotnet/aspnetcore/files/9656133/GetUriWithQueryParameterWithHash.zip)

That sample project is a multi-target project for `net6.0` and `net7.0`. That sample project will show you what is the problem, and the problem can be reproduced on both .NET versions.

image

### Exceptions (if any)

_No response_

### .NET Version

7.0.100-rc.1.22431.12

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fixed bug in NavigationManager.GetUriWithQueryParameter(s) to include uri with hash string

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

1. Fixed NavigationManager.GetUriWithQueryParameter(s) methods: included case when uri has hash string
2. Added test cases where uri has hash string to NavigationManagerTests 
3. Removed duplicate test from NavigationManagerTests

Fixes #44204

### CODE REVIEW

File: src/Components/Components/src/NavigationManagerExtensions.cs [hunk 1]
```diff
@@ -649,14 +657,25 @@ private static string GetUriWithRemovedQueryParameter(string uri, string name)
...
+        return newQueryStringBuilder.GetUriWithQueryString();
     }
 
     private static string GetUriWithAppendedQueryParameters(
         string uriWithoutQueryString,
         IReadOnlyDictionary<string, object?> parameters)
     {
-        var builder = new QueryStringBuilder(uriWithoutQueryString);
+        var uriWithoutQueryStringAndHash = uriWithoutQueryString;
+        var hash = "";
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/NavigationManagerExtensions.cs:668]: Instead of `hash` being a `string`, could it be a `ReadOnlySpan<char>`? If it was populated using `uriWithoutQueryString.AsSpan()[hashStartIndex..]` then it wouldn't cause any heap allocations.

Same for the other `hash` variable inside `GetUriWithAppendedQueryParameter`, and the call to `uriWithoutQueryStringAndHash.Substring`

File: src/Components/Components/test/NavigationManagerTest.cs [hunk 2]
```diff
@@ -60,24 +62,6 @@ public void Initialize_ThrowsForInvalidBaseRelativePaths(string baseUri, string
...
-
-        var ex = Assert.Throws<ArgumentException>(() =>
-        {
-            navigationManager.ToBaseRelativePath(absoluteUri);
-        });
-
-        Assert.Equal(
-            $"The URI '{absoluteUri}' is not contained by the base URI '{baseUri}'.",
-            ex.Message);
-    }
```
Comment (SteveSandersonMS) [inline src/Components/Components/test/NavigationManagerTest.cs:79]: Should this test be removed, or is this for some kind of work-in-progress reason? If it's being removed for real, could you clarify why? I'm just not sure why it would be affected by this PR :)

**Comment by SteveSandersonMS** [comment]
This is looking great!

File: src/Components/Components/test/NavigationManagerTest.cs (hunk 2 above)
Comment (surayya-MS) [reply src/Components/Components/test/NavigationManagerTest.cs:79]: When going through NavigationManagerTests I noticed that Uri_ThrowsForInvalidBaseRelativePaths is exact same as the one after it ToBaseRelativePath_ThrowsForInvalidBaseRelativePaths. The only difference is the name. I decided to keep ToBaseRelativePath_ThrowsForInvalidBaseRelativePaths since its name is more descriptive.

Comment (SteveSandersonMS) [reply src/Components/Components/test/NavigationManagerTest.cs:79]: Ah great, well spotted! Thanks for sorting that out.

File: src/Components/Components/src/NavigationManagerExtensions.cs [hunk 3]
```diff
@@ -649,14 +656,30 @@ private static string GetUriWithRemovedQueryParameter(string uri, string name)
...
+            uriWithoutQueryStringAndHash = uriWithoutQueryString;
+            hash = "";
+        }
+        else
+        {
+            uriWithoutQueryStringAndHash = uriWithoutQueryString.AsSpan(0, hashStartIndex);
+            hash = uriWithoutQueryString.AsSpan(hashStartIndex);
+        }
+
+        var builder = new QueryStringBuilder(uriWithoutQueryStringAndHash, hash: hash.ToString());
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/NavigationManagerExtensions.cs:682]: If we call `hash.ToString()` here, it will allocate a string which makes the use of `ReadOnlySpan<char>` redundant. Perhaps it's unavoidable, and if so, sorry for the misleading suggestion about `ReadOnlySpan<char>`!

However, one other possibility: does it work to *not* pass `hash` to the `QueryStringBuilder` constructor at all? Instead, there could be a new method on `QueryStringBuilder` like `AppendHash(ReadOnlySpan<char> hash)` which gets called just before `GetUriWithQueryString`. That also avoids another allocation (the one caused by the concatenation `_builder.ToString() + _hash`). Does that work?

I know it might seem fussy to be doing all these tricks to avoid a couple of allocations! It's only for low-level APIs that might be called hundreds of times per request that we tend to focus so much on it.

Comment (SteveSandersonMS) [reply src/Components/Components/src/NavigationManagerExtensions.cs:682]: That is a great point to raise and would absolutely be something we would need to deal with if `QueryStringBuilder` was public API. But since in this case it's private API (and especially because it's scoped to this one file, so we don't even have to reason about other usages across the codebase), we don't have to worry too hard about incorrect usage patterns.

If you want to add a check that the methods aren't called in the wrong order that's fine, but TBH I'd be completely fine with not doing that and simply relying on the caller doing things correctly since we know that's just us. If we ever get this wrong in the future, we'll know about it because we'll get incorrect results.

**Review by SteveSandersonMS — APPROVED** [review]
Looks great! Nice job on keeping this clear and understandable.
