### PR TITLE
Don't generate Action links to non-Action named endpoints

### LINKED ISSUE #35592: Html.ActionLink() returns incorrect URL when Minimal Action with Name metadata in use
### Describe the bug

If MVC and Minimal Actions are used together when an action has `WithName()` associated with it, links generated by `Html.ActionLink()` return the wrong URL.

In the below repo that replicates this issue, when a `MapGet()` minimal API is added that has name metadata added using `WithName("Foo")`, links generated using `ActionLink()` are for endpoint mapped, rather than the intended MVC action.

### To Reproduce

Clone the repo here and follow the instructions in the README: https://github.com/martincostello/MvcLinkGenerationRepro

### Further technical details

.NET SDK: `6.0.100-rc.1.21420.39`
ASP.NET Core: `6.0.0-rc.1.21420.16`

### PR DESCRIPTION
**Pull request by halter73**
Prior to this change, given routes defined as follows

```C#
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

// The same thing would happen without .WithName("Foo") if a named
// method or local function was passed to MapGet() instead of a lambda.
app.MapGet("/something", () => "something").WithName("Foo");
```

`@Url.Action("Privacy", "Home")` in a view would produce a link to `/something?action=Privacy&controller=Home` instead of `/Home/Privacy` as expected.

This happened because endpoints with `IRouteNameMetadata` defined would end up in the `AllMatches` despite not having any `RoutePattern.RequiredValues` causing it to match any attempt to generate an action link without a specified route name.

Endpoints without neither `IRouteNameMetadata` defined nor `RoutePattern.RequiredValues` were already excluded from `AllMatches` which is likely why we didn't see this before. Even in .NET 5, if you defined an endpoint as follows, you'd experience the same link generation issue:

```C#
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");

    endpoints.MapGet("/something", context => Task.CompletedTask)
        .WithMetadata(new RouteNameMetadata("Foo"));
});
```

I assume this wasn't noticed before because it was rare to add `RouteNameMetadata` to non-Controller endpoints.

I had to fix a bunch of existing unit tests that were relying on this buggy behavior to get matches by adding the `RequiredValues` to controller endpoints that MVC normally adds automatically.

Fixes #35592

### CODE REVIEW

**Comment by halter73** [comment]
I plan to backport this to rc2

**Comment by pranavkm** [comment]
@javiercn / @JamesNK could I have one of you look at this? The tests look very thorough, but I'm not familiar with this code.

**Comment by javiercn** [comment]
I will tomorrow morning

**Review by javiercn — COMMENTED** [review]
Took a quick look.

Looks inline with the fix we discussed, I'll spend some more time on it tomorrow to think about scenarios in case we missed anything

File: src/Http/Routing/test/UnitTests/RouteValuesAddressSchemeTest.cs [hunk 1]
```diff
@@ -335,19 +334,66 @@ public void FindEndpoints_AlwaysReturnsEndpointsByRouteName_IgnoringMissingRequi
...
+            var endpoint = CreateEndpoint(
+                "api/orders/{id}",
+                defaults: new { controller = "Orders", action = "GetById" },
+                routeName: "a");
+
+            // Act
+            var addressScheme = CreateAddressScheme(endpoint);
+
+            // Assert
+            Assert.Empty(addressScheme.State.MatchesWithRequiredValues);
```
Comment (rynowak) [inline src/Http/Routing/test/UnitTests/RouteValuesAddressSchemeTest.cs:373]: 👍

**Review by rynowak — APPROVED** [review]

**Review by javiercn — APPROVED** [review]
