### PR TITLE
Fixed the ErrorBoundary multiple errors bug

### LINKED ISSUE #39814: Blazor doesn't render ErrorBoundary's ErrorContent when there are two different exceptions inside it's ChildContent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ErrorBoundary renders nothing when there are two different errors inside it's ChildContent.

### Expected Behavior

ErrorBoundary renders exception information.

### Steps To Reproduce

App.razor

````
<ErrorBoundary>
    <ChildContent>
        <ComponentWithError />
    </ChildContent>
    <ErrorContent>
        <div style="background: red">@context</div>
    </ErrorContent>
</ErrorBoundary>
````

ComponentWithError.razor
````
@{
    throw new Exception("error2");
}

@code
{
    protected override async Task OnInitializedAsync()
    {
        throw new Exception("error");
    }
}
````

### Exceptions (if any)

_No response_

### .NET Version

6.0.101

### Anything else?

I originally ran into this problem when I misspelled the parameter name in the inner component of ````ComponentWithError````:
````<ComponentWithoutProp BadProp=1 />````
Which throws an exception by itself.

Also with exception inside ````void OnInitialized()```` everything works fine.

### PR DESCRIPTION
**Pull request by dariatiurina**
# Fixed the ErrorBoundary multiple errors bug

## Description

This pull request enhances error handling in Blazor components, especially around error boundaries and faulted tasks during component initialization and rendering. It introduces new tests and supporting components to ensure that exceptions thrown in lifecycle methods or during rendering are correctly captured by error boundaries, and that error boundaries can handle multiple simultaneous errors.

### Changes:
* Modified `ComponentBase` to avoid calling `StateHasChanged` when the initialization task is faulted, preventing unnecessary state updates after errors.
* Added new test in `ComponentBaseTest.cs` to verify that error boundary capture exceptions from faulted tasks in `OnInitializedAsync` and during rendering, and that these errors are surfaced correctly.
* Introduced `TestErrorBoundary` and `TestComponentErrorBuildRenderTree` test components to simulate and verify error boundary behavior with faulted tasks and rendering errors.
 
Fixes #39814

### CODE REVIEW

File: src/Components/Components/test/ComponentBaseTest.cs [hunk 1]
```diff
@@ -372,6 +372,37 @@ public async Task DoesNotRenderAfterOnInitAsyncTaskIsCancelledUsingCancellationT
...
+        // Act
+        var rootComponentId = renderer.AssignRootComponentId(rootComponent);
+        await renderer.RenderRootComponentAsync(rootComponentId);
+
+        // Assert
+        Assert.NotNull(capturedBoundary);
+        Assert.NotNull(capturedBoundary!.ReceivedException);
+        Assert.Equal(typeof(InvalidTimeZoneException), capturedBoundary!.ReceivedException.GetType());
+    }
+
```
Comment (javiercn) [inline src/Components/Components/test/ComponentBaseTest.cs:406]: Can we add a test for `ComponentBase` to capture the new behavior without ErrorBoundary? (That StateHasChanged doesn't get invoked with a faulted task)

Are there other similar cases that we need to look for? (Like CallOnParametersSetAsync) https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs#L320-L322

**Review by javiercn — APPROVED** [review]
Looks great, minor comments about a case we missed and a couple extra tests to capture the new behavior.

Good job!

**Comment by ScarletKuro** [comment]
~~This probably should be marked as breaking change, see https://github.com/MudBlazor/MudBlazor/pull/12098#issuecomment-3524346901
This change affects userspace, since some frameworks depended on the previous behavior, which effectively made it a feature rather than a bug. This change should be documented in https://learn.microsoft.com/en-us/dotnet/core/compatibility/10.0 if there are no plans to reverse it.~~

UPD: Was thing change that broke things for us https://github.com/dotnet/aspnetcore/issues/64203

**Comment by javiercn** [comment]
@ScarletKuro please file a new issue with the problem. We won't effectively track comments on closed PRs. Please also detail the concrete use case in which this change represents a problem with MudBlazor
