### PR TITLE
[TS Client] Catch exception in onreceive and close connection 

### LINKED ISSUE #13276: SignalR Error: Cannot send data if the connection is not in the 'Connected' State
### Describe the bug
Fast navigating between pages returns an Error: Cannot send data if the connection is not in the 'Connected' State

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Run code from this repo https://github.com/RenetConsulting/angularcore.net (or go to this website https://open-source.azurewebsites.net/home)
3. go to page **blogs**
4. go to page **home**
5. then use this code
```
history.back();
console.log('back');
setTimeout(()=> {
	history.forward(); 
	console.log('forward');
}, 4);
```
6. you will see 
```
ERROR Error: Uncaught (in promise): Error: Cannot send data if the connection is not in the 'Connected' State.
Error: Cannot send data if the connection is not in the 'Connected' State.
    at HttpConnection.push../node_modules/@aspnet/signalr/dist/esm/HttpConnection.js.HttpConnection.send (HttpConnection.js:101)
    at HubConnection.push../node_modules/@aspnet/signalr/dist/esm/HubConnection.js.HubConnection.sendMessage (HubConnection.js:199)
    at HubConnection.<anonymous> (HubConnection.js:116)
    at step (HubConnection.js:33)
    at Object.next (HubConnection.js:14)
    at fulfilled (HubConnection.js:5)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:26255)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at resolvePromise (zone.js:852)
    at zone.js:762
    at fulfilled (HubConnection.js:5)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:26255)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:910
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26246)
```

and this one
```
ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (zone.js:852)
    at HubConnection.handshakeRejecter (zone.js:762)
    at HubConnection.push../node_modules/@aspnet/signalr/dist/esm/HubConnection.js.HubConnection.connectionClosed (HubConnection.js:460)
    at HttpConnection.HubConnection.connection.onclose (HubConnection.js:66)
    at HttpConnection.push../node_modules/@aspnet/signalr/dist/esm/HttpConnection.js.HttpConnection.stopConnection (HttpConnection.js:407)
    at WebSocketTransport.transport.onclose (HttpConnection.js:221)
    at WebSocketTransport.push../node_modules/@aspnet/signalr/dist/esm/WebSocketTransport.js.WebSocketTransport.close (WebSocketTransport.js:146)
    at WebSocketTransport.push../node_modules/@aspnet/signalr/dist/esm/WebSocketTransport.js.WebSocketTransport.stop (WebSocketTransport.js:134)
    at HttpConnection.<anonymous> (HttpConnection.js:129)
    at step (HttpConnection.js:33)
```

### Expected behavior
Not to have the error

### Screenshots

image

### Additional context
In my opinion, the problem happens when data returns from the server but the client is already disconnected from server subscriptions. The error won't appear when I slowly navigate between pages (home and blogs, for example, go to page blogs wait until a message appears ``Information: SSE connected to`` in the console then go to another page).

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes #13276

Before, if the `onreceive` callback threw you could get an unhandled promise exception.

### CODE REVIEW

File: src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts [hunk 1]
```diff
@@ -131,15 +136,23 @@ export class WebSocketTransport implements ITransport {
...
+    private close(event?: CloseEvent | Error): void {
         // webSocket will be null if the transport did not start successfully
         this.logger.log(LogLevel.Trace, "(WebSockets transport) socket closed.");
         if (this.onclose) {
-            if (event && (event.wasClean === false || event.code !== 1000)) {
+            if (this.isCloseEvent(event) && (event.wasClean === false || event.code !== 1000)) {
                 this.onclose(new Error(`WebSocket closed with status code: ${event.code} (${event.reason}).`));
             } else {
-                this.onclose();
+                if (event instanceof Error) {
```
Comment (halter73) [inline src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts]: Nit: this could be an `else if`.

**Review by halter73 — APPROVED** [review]
