### PR TITLE
Always fill passed in buffer in StreamFillBufferExtensions

### LINKED ISSUE #34947: CanReadAndWriteWithAsyncConnectionMiddleware
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests.CanReadAndWriteWithAsyncConnectionMiddleware

## Error Message

```text
Assert.Equal() Failure
↓ (pos 75)
Expected: ···750 09:51:25 GMT

Hello World!
Actual:   ···750 09:51:25 GMT

lo World!���
↑ (pos 75)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests.CanReadAndWriteWithAsyncConnectionMiddleware(RequestDelegate requestDelegate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ConnectionMiddlewareTests.cs:line 83
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests.CanReadAndWriteWithAsyncConnectionMiddleware(RequestDelegate requestDelegate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ConnectionMiddlewareTests.cs:line 89
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test CanReadAndWriteWithAsyncConnectionMiddleware-Microsoft.AspNetCore.Http.RequestDelegate at 2021-08-02T14:50:03
[0.001s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:0
[0.002s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly InMemory.FunctionalTests
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /datadisks/disk1/work/9D11085F/w/9C6708E5/e/
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMALOJ655K30" accepted.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMALOJ655K30" started.
[0.002s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 POST http:/// - 12
[0.002s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMALOJ655K30", Request id "0HMALOJ655K30:00000002": started reading request body.
[0.003s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMALOJ655K30", Request id "0HMALOJ655K30:00000002": done reading request body.
[0.003s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 POST http:/// - 12 - 200 - - 0.2072ms
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMALOJ655K30" disconnecting.
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMALOJ655K30" stopped.
[0.077s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[0.077s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.077s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[0.304s] [Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
                                     ↓ (pos 75)
Expected: ···750 09:51:25 GMT\r\n\r\nHello World!
Actual:   ···750 09:51:25 GMT\r\n\r\nlo World!\0\0\0
                                     ↑ (pos 75)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests.CanReadAndWriteWithAsyncConnectionMiddleware(RequestDelegate requestDelegate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ConnectionMiddlewareTests.cs:line 83
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ConnectionMiddlewareTests.CanReadAndWriteWithAsyncConnectionMiddleware(RequestDelegate requestDelegate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ConnectionMiddlewareTests.cs:line 89
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[0.305s] [TestLifetime] [Information] Finished test CanReadAndWriteWithAsyncConnectionMiddleware-Microsoft.AspNetCore.Http.RequestDelegate in 0.3041502s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1271314

### LINKED ISSUE #34992: Quarantine Failing Linux Tests
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet

## Error Message

```text
Assert.Equal() Failure
↓ (pos 75)
Expected: ···807 11:57:47 GMT

Goodbye
Actual:   ···807 11:57:47 GMT

e������
↑ (pos 75)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 751
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 757
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.000s] [TestLifetime] [Information] Starting test Http10KeepAliveNotHonoredIfResponseContentLengthNotSet at 2021-08-03T12:51:57
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:0
[0.002s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly InMemory.FunctionalTests
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /root/helix/work/workitem/
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" accepted.
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" started.
[0.003s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 GET http:/// - -
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" completed keep alive response.
[0.003s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 GET http:/// - - - 200 0 - 0.1069ms
[0.035s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 POST http:/// - 7
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMAMFLPJRFGN", Request id "0HMAMFLPJRFGN:00000003": started reading request body.
[0.037s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMAMFLPJRFGN", Request id "0HMAMFLPJRFGN:00000003": done reading request body.
[0.038s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 POST http:/// - 7 - 200 - - 3.0973ms
[0.038s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" disconnecting.
[0.038s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" stopped.
[0.038s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[0.038s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.039s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[0.116s] [Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
                                     ↓ (pos 75)
Expected: ···807 11:57:47 GMT\r\n\r\nGoodbye
Actual:   ···807 11:57:47 GMT\r\n\r\ne\0\0\0\0\0\0
                                     ↑ (pos 75)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 751
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 757
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.117s] [TestLifetime] [Information] Finished test Http10KeepAliveNotHonoredIfResponseContentLengthNotSet in 0.1162396s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1272938&view=ms.vss-test-web.build-test-results-tab&runId=37646266&resultId=107222&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by halter73**
The returned `byte[]` was always correct, but the passed-in `buffer` argument was not being filled correctly when there were multiple reads since it was effectively turned into a scratch buffer. This caused some flakiness in older tests.

I've change all the methods to not return `byte[]` and changed all the callsites using the returned `byte[]` to use the passed-in `buffer` instead to keep the implementation simpler and to reduce the likelihood that it ever goes into a half-broken state again.

Fixes #34992
Fixes #34947

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs [hunk 1]
```diff
@@ -702,7 +702,7 @@ private void AddSegment(int sizeHint = 0)
             {
                 // Get a new buffer using the minimum segment size, unless the size hint is larger than a single segment.
                 // Also, the size cannot be larger than the MaxBufferSize of the MemoryPool
-                var owner = _memoryPool.Rent(Math.Min(sizeHint, _memoryPool.MaxBufferSize));
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs:705]: revert?

File: src/Servers/Kestrel/shared/test/StreamFillBufferExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+            {
+                read = await stream.ReadAsync(buffer, offset, buffer.Length - offset, cancellationToken);
+                offset += read;
+            } while (read != 0 && offset < buffer.Length);
+
+            Assert.Equal(buffer.Length, offset);
+        }
+
+        public static async Task<int> ReadAtLeastLengthAsync(this Stream stream, int length, byte[] buffer, CancellationToken cancellationToken = default)
+        {
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/shared/test/StreamFillBufferExtensions.cs:43]: nit: this one can share code with FillEntireBufferAsync if we use a sliced buffer if we change to use `Memory<byte>`

**Review by BrennanConroy — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs (hunk 1 above)
Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs:705]: I figured I'd just stick it in this PR because it's not big enough for its own. Look at line 701.

File: src/Servers/Kestrel/Transport.Quic/test/QuicConnectionContextTests.cs [hunk 3]
```diff
@@ -100,7 +100,8 @@ public async Task AcceptAsync_ClientStartsAndStopsBidirectionStream_ServerAccept
             serverStream.Transport.Input.AdvanceTo(read.Buffer.End);
 
             // Read data from server.
-            var data = await clientStream.ReadAtLeastLengthAsync(TestData.Length).DefaultTimeout();
```
Comment (JamesNK) [inline src/Servers/Kestrel/Transport.Quic/test/QuicConnectionContextTests.cs:103]: I'm using `ReadAtLeastLengthAsync` on purpose. I don't want to read an exact amount. I want stream to give me the expected amount of data but leave the door open to the stream returning more.

There is a bug in HttpClient's response stream that only shows up when you call ReadAsync and ask to read more data that is available.

**Review by JamesNK — CHANGES_REQUESTED** [review]
Woops! Good find.

Isn't the fix to always test the returned data, and not test the passed in buffer?

File: src/Servers/Kestrel/Transport.Quic/test/QuicConnectionContextTests.cs (hunk 3 above)
Comment (halter73) [reply src/Servers/Kestrel/Transport.Quic/test/QuicConnectionContextTests.cs:103]: I know. That's not this test though. I kept your test demonstrating the bug in HttpClient's response stream passing in a larger buffer than needed. See [here](https://github.com/dotnet/aspnetcore/pull/35003/files#diff-69bd98bd920bf41ec1df4627369cfb21d6429e4c6eb75255a8b64b5a0d7476a7R217). I don't see the benefit of returning the buffer rather than passing it in. The caller usually has a better idea of the appropriate buffer size and it doesn't really complicate the call sites.

**Review by JamesNK — APPROVED** [review]
I liked my methods more for various reasons I and I'll change my code back to using some form of them in the future without changing tests that test the buffer.

I won't block this PR though.
