### PR TITLE
Set ContentLength for TestHost

### LINKED ISSUE #18463: HttpRequest.ContentLength is null when using TestHost
### Describe the bug
⚠️**Update: I'm no longer taking this approach and inspecting the Content-Length header's value, we found a much better way with help from David Fowler, but the issue is still valid. For reproducability, I've branched the commit at the time [here](https://github.com/benmccallum/server/tree/reproduction/content-length-null).**

Apologies if I'm completely wrong here. ~Over [here](https://github.com/graphql-dotnet/server/pull/299)~ I'm upgrading a middleware to 3.x and `System.Text.Json`.

I'm trying to optimize a deserialization from the `HttpRequest.Body` by pre-allocating a buffer using the shared array pool given `HttpRequest.ContentLength`. ~See [here](https://github.com/graphql-dotnet/server/pull/299/files#diff-ac7510c8f01dee59e580e042d943bd62R19).~ Problem is, when our integration tests run, which use `HttpClient.PostAsync(..., new StringContent(...))` to post to a TestHost, the `Content-Length` header is always null. 

Is this is a limitation of the test host, or a bug? I guess I could write a unit test the specific internals of that function.

### To Reproduce
1. Clone ~PR~branch linked above.
1. Put a breakpoint in `GraphQLHttpMiddleware` in the JsonContentType case of the switch statement.
1. Test Explorer > Samples.Server.Tests (netcoreapp3.1) > right-click "Single_Query..." and Debug.
1. Breakpoint will be hit and `httpRequest.ContentLength` will be null.

### Further technical details
- ASP.NET Core version: 3.1.0
- Include the output of `dotnet --info`
image
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Community 2019 v16.4.3

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/18463

### CODE REVIEW

File: src/Hosting/TestHost/src/ClientHandler.cs [hunk 1]
```diff
@@ -117,6 +117,13 @@ internal ClientHandler(PathString pathBase, ApplicationWrapper application)
                     {
                         req.Headers.Append(header.Key, string.Join(" ", header.Value));
                     }
+                    else if (string.Equals(header.Key, HeaderNames.ContentLength, StringComparison.OrdinalIgnoreCase))
+                    {
+                        if (int.TryParse(header.Value.First(), out var contentLength))
```
Comment (campersau) [inline src/Hosting/TestHost/src/ClientHandler.cs:122]: Could be a `long` I guess.
```suggestion
                        if (long.TryParse(header.Value.First(), out var contentLength))
```

File: src/Hosting/TestHost/src/ClientHandler.cs [hunk 2]
```diff
@@ -117,6 +117,13 @@ internal ClientHandler(PathString pathBase, ApplicationWrapper application)
                     {
                         req.Headers.Append(header.Key, string.Join(" ", header.Value));
                     }
+                    else if (string.Equals(header.Key, HeaderNames.ContentLength, StringComparison.OrdinalIgnoreCase))
+                    {
+                        if (long.TryParse(header.Value.First(), out var contentLength))
+                        {
+                            req.ContentLength = contentLength;
+                        }
+                    }
```
Comment (Tratcher) [inline src/Hosting/TestHost/src/ClientHandler.cs:126]: This shouldn't have affected the behavior, the Asp.Net ContentLength property is already read from the header. You should get the same test results if you remove this section. Does the test fail before adding this and pass after?

The expected workaround was reading System.Net.Http's ContentLength property because it has the side-effect of generating the header. https://github.com/dotnet/aspnetcore/issues/18463#issuecomment-613804982

Comment (Kahbazi) [reply src/Hosting/TestHost/src/ClientHandler.cs]: > Does the test fail before adding this and pass after? 

Yes, but I changed the code as you said. Reading the property would set the header. Now if there's no body on the request the `ContentLength` is Zero. Is this the expected behavior?

File: src/Hosting/TestHost/test/ClientHandlerTests.cs [hunk 3]
```diff
@@ -103,6 +104,36 @@ public Task UserAgentHeaderWorks()
...
+
+            return httpClient.PostAsync("http://example.com", content);
+        }
+
+        [Fact]
+        public Task ContentLengthWithNoBodyWorks()
+        {
+            var handler = new ClientHandler(new PathString(""), new DummyApplication(context =>
+            {
+                Assert.Equal(0, context.Request.ContentLength);
```
Comment (Tratcher) [inline src/Hosting/TestHost/test/ClientHandlerTests.cs:128]: Interesting. Because TestServer defaults to a StreamContent(Stream.Null), and Stream.Null's default length is 0, all requests that don't specify a body will get `Content-Length: 0`.
https://github.com/dotnet/aspnetcore/blob/5980ad813e0044421b13ea70431452505262e946/src/Hosting/TestHost/src/ClientHandler.cs#L69

Comment (Tratcher) [reply src/Hosting/TestHost/test/ClientHandlerTests.cs:128]: Can you add a test where the client intentionally sets Transfer-Encoding: chunked? We don't want to automatically add a content-length in that scenario.

Comment (Kahbazi) [reply src/Hosting/TestHost/test/ClientHandlerTests.cs:129]: Setting `Transfer-Encoding: chunked` for `ByteArrayContent` didn't do anything, the ContentLength was still 0.
But creating a content which return `false` on `TryComputeLength` would make `ContentLength` null. Is this good enough?

**Review by Tratcher — APPROVED** [review]
I expect we'll churn on this more as part of https://github.com/dotnet/aspnetcore/issues/24175, but this is good for now.

**Comment by Tratcher** [comment]
Thanks
