### PR TITLE
Don't log status messages for debug proxy. Fixes #35292

### LINKED ISSUE #35292: UseWebAssemblyDebugging causes strange log messages
If you run the Blazor WebAssembly "hosted" project, and manually add the following lines to work around https://github.com/aspnet/AspNetCore-ManualTests/issues/814#issuecomment-897673794:

```cs
if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
}
```

... and then run with F5 inside VS 2022 Preview 4, the log output looks like this:

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7278
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5278
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\path\to\app\Server
Hosting environment: Production
Content root path: C:\path\to\app\Server
Now listening on: http://127.0.0.1:55048
Application started. Press Ctrl+C to shut down.
```

This is really confusing because it says the hosting environment is `Development` **and** `Production`, and that we're listening on 3 different ports.

I think what's happening is that the debug proxy is logging its own "app startup" message, but this is bad because it's confusing - I really thought it was running in Production mode for a while, and went down a wrong path with some debugging. We should stop it from logging this wrong info.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
A simple fix for #35292.

### CODE REVIEW

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs [hunk 1]
```diff
@@ -110,6 +117,24 @@ private static void PassThroughConsoleOutput(Process process)
         {
             process.OutputDataReceived += (sender, eventArgs) =>
             {
+                // It's confusing if the debug proxy emits its own startup status messages, because the developer
+                // may think the ports/environment/paths refer to their actual application. So we want to suppress
+                // them, but we can't stop the debug proxy app from emitting the messages entirely (e.g., via
+                // SuppressStatusMessages) because we need the "Now listening on" one to detect the chosen port.
```
Comment (javiercn) [inline src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:123]: Is this because it runs with an unknown port?

**Review by javiercn — APPROVED** [review]

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:123]: I think the child process picks one at runtime based on availability.
