### PR TITLE
Fix RedisCache update that breaks usage against older redis servers 

### LINKED ISSUE #38715: RedisCache update in .NET 6 breaks usage against older redis servers
Timeline:

- redis 2.0 had `HSET key field value` for setting individual hash fields, and `HMSET key field value [field value ...]` for setting multiple hash fields (against the same key); as you can see, there's a lot of overlap here
- redis 4.0 observes this redundancy, and adds `HSET key field value [field value ...]`, and also *marks `HMSET` as deprecated*, although it still works fine
- `RedisCache` wants to set a hash with 3 fields against a single key; historically it has used `HMSET` for this (via Lua)
- .NET 6 switches to using the non-deprecated `HSET` API

Impact:

For users targeting redis versions that lack the varadic `HSET` (so: versions before 4.0), it simply doesn't work, manifesting in a `RedisServerException`:

> Wrong number of args calling Redis command From Lua script

Suggestions:

1. check the redis server version (APIs exist on SE-Redis for this) before deciding which to use
2. or, just use `HMSET`; it hasn't gone anywhere, and is honestly: unlikely to go anywhere
3. make 3 simple calls to `HSET`, which would work everywhere and still be contiguous (thanks to the single-threaded core) - although I confess that this is inelegant

A complicating factor is that the [Redis-64](https://www.nuget.org/packages/Redis-64) port of Redis on Windows by Microsoft (now abandoned): stops at 3.0.503. Alternatives for Windows hosting are WSL or Memurai (commercial), or containers such as Docker. This means that some folks have (perhaps unwisely) stagnated on v3, wanting to keep things simple.

Links:

- relevant .NET 6 change: [here](https://github.com/dotnet/aspnetcore/commit/bf4d9b9bd0d11e4e46924e4e09014580ec1a1449)
- [existing aspnetcore bug](https://github.com/dotnet/aspnetcore/issues/33628), ccing @JunTaoLuo who closed it (I can't comment on the existing one)
- [customer impact](https://github.com/StackExchange/StackExchange.Redis/issues/1904) (being reported in the SE-Redis library)

### PR DESCRIPTION
**Pull request by Tratcher**
# Fix RedisCache update that breaks usage against older redis servers

Add version checks and alternate API calls to support older redis versions

## Description

6.0 changed from calling a deprecated redis API to a new one. Unfortunately the new API doesn't work on unsupported versions of redis which are still in common use.

Fixes #38715

## Customer Impact

Unblocks customers stuck using old versions of redis.

## Regression?

- [x] Yes
- [ ] No

In 6.0

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Restoring the prior behavior

## Verification

- [x] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Caching/StackExchangeRedis/src/RedisCache.cs [hunk 1]
```diff
@@ -16,26 +16,41 @@ namespace Microsoft.Extensions.Caching.StackExchangeRedis
...
+        // But HSET doesn't allows multiple field/value pairs for Redis prior 4.0.
+
         // KEYS[1] = = key
         // ARGV[1] = absolute-expiration - ticks as long (-1 for none)
         // ARGV[2] = sliding-expiration - ticks as long (-1 for none)
         // ARGV[3] = relative-expiration (long, in seconds, -1 for none) - Min(absolute-expiration - Now, sliding-expiration)
         // ARGV[4] = data - byte[]
         // this order should not change LUA script depends on it
-        private const string SetScript = (@"
+        private const string SetScriptPerExtendedSetCommand = (@"
```
Comment (halter73) [inline src/Caching/StackExchangeRedis/src/RedisCache.cs:32]: Nit: I think we might have given this the wrong name in the original PR. https://github.com/dotnet/aspnetcore/pull/38860#discussion_r766255157.

**Review by NickCraver — APPROVED** [review]
Not sure mine counts but backport looks good :+1:

**Review by halter73 — APPROVED** [review]

**Comment by Tratcher** [comment]
@dotnet/aspnet-build please merge.

**Comment by Joseph-Anthony-King** [comment]
Hello team, I'm currently working on a .NET6 project using the latest versions of StackExchange.Redis and Redis Server 6.2.6 and I'm receiving the following error:

`ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script`

I believe this change is meant to address this issue and I see it's merged... is a release pending?

Thank you,
Joe

**Comment by dougbu** [comment]
@Joseph-Anthony-King yes, the 6.0.2 release contains this fix and should be available soon. Please watch for announcements or check <https://dotnet.microsoft.com/en-us/download/dotnet/6.0> occasionally.

**Comment by Joseph-Anthony-King** [comment]
Very cool, thank you for the update @dougbu !
