### PR TITLE
Remove Entrypoint Invoker

### LINKED ISSUE #30600: Replace EntryPointInvoker in Blazor WebAssembly with code in the runtime
.NET WASM has an API to invoke the entry point: `mono_call_assembly_entry_point`. We previously used it, but moved away from it since it did not support `MainAsync` at that point.  This has since been fixed so there's no reason for us to continue using our implementation. Here's the PR that made the change: https://github.com/dotnet/aspnetcore/commit/3a93704737cceb38c4d51ae03075cf4eaad81b23. We would essentially want to undo the source changes, but keep the tests.

### LINKED ISSUE #31148: Remove dependency on System.Console in default Blazor WASM app
There is a single place in a Blazor WASM app that references `System.Console`:

https://github.com/dotnet/aspnetcore/blob/26a88e0f20edf862d80b49eacbb6e2c0b5520a1d/src/Components/WebAssembly/WebAssembly/src/Hosting/EntrypointInvoker.cs#L84-L88

This place is the main entry point for the application, and it catches all exceptions and writes them to the console. Since it is the only place that references `System.Console` in the application, if we can change this code to not reference `System.Console`, the whole `System.Console.dll` assembly can be removed, which is currently at 6KB .br compressed.

One idea on how to remove this is to use Mono's built-in functionality for invoking the Main entrypoint instead of having that functionality in ASP.NET.

cc @lewing @pranavkm @captainsafia @marek-safar

### PR DESCRIPTION
**Pull request by TanayParikh**
Replaces the custom `EntrypointInvoker` in favor of runtime's `call_assembly_entrypoint` which now supports `MainAsync`.

Fixes: https://github.com/dotnet/aspnetcore/issues/30600
Fixes: https://github.com/dotnet/aspnetcore/issues/31148

### CODE REVIEW

File: src/Components/.gitignore [hunk 1]
```diff
@@ -0,0 +1 @@
+**/Samples/**/.vscode/*
```
Comment (TanayParikh) [inline src/Components/.gitignore:1]: Ignores:
Screen Shot 2021-04-13 at 11 09 14 AM

File: src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts [hunk 2]
```diff
@@ -54,16 +54,13 @@ export const monoPlatform: Platform = {
...
+  callEntryPoint: function callEntryPoint(assemblyName: string) : Promise<any> {
     // Currently we disregard the return value from the entrypoint, whether it's sync or async.
     // In the future, we might want Blazor.start to return a Promise<Promise<value>>, where the
     // outer promise reflects the startup process, and the inner one reflects the possibly-async
     // .NET entrypoint method.
-    const invokeEntrypoint = bindStaticMethod('Microsoft.AspNetCore.Components.WebAssembly', 'Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker', 'InvokeEntrypoint');
-    // Note we're passing in null because passing arrays is problematic until https://github.com/mono/mono/issues/18245 is resolved.
-    invokeEntrypoint(assemblyName, null);
+    const emptyArray = [ [ ] ];
+    return BINDING.call_assembly_entry_point(assemblyName, emptyArray, undefined);
```
Comment (TanayParikh) [inline src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:63]: The `emptyArray` is the part I was unsure about given the original `EntrypointInvoker` set the args [based on the entrypoint parameters](https://github.com/dotnet/aspnetcore/pull/31769/files#diff-fb97fa9739af7e185d6cce1478623749e70827a919ebb889efe0f94519628f04L27). Does anyone know if this is still required?

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs [hunk 3]
```diff
@@ -68,7 +67,7 @@ public sealed class WebAssemblyHost : IAsyncDisposable
         /// </summary>
         public IServiceProvider Services => _scope.ServiceProvider;
 
-        internal WebAssemblyCultureProvider CultureProvider { get; set; } = WebAssemblyCultureProvider.Instance!;
+        internal WebAssemblyCultureProvider CultureProvider => WebAssemblyCultureProvider.Instance!;
```
Comment (TanayParikh) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:70]: Thanks @pranavkm & @javiercn!

Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:70]: We only seem to use this in one place (within run async core).

How about we remove the property and just do
```csharp
var cultureProvider = WebAssemblyCultureProvider.Instance;
```
in the method where it is used?

**Review by javiercn — APPROVED** [review]
Looks great!

only some minor feedback

File: src/Components/WebAssembly/WebAssembly/test/Hosting/EntrypointInvokerTest.cs [hunk 4]
```diff
@@ -1,153 +0,0 @@
-// Copyright (c) .NET Foundation. All rights reserved.
```
Comment (HaoK) [inline src/Components/WebAssembly/WebAssembly/test/Hosting/EntrypointInvokerTest.cs:1]: Do we want to keep/tweak these tests to make sure things still work the same? Or are these behaviors/tests covered already elsewhere?

Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly/test/Hosting/EntrypointInvokerTest.cs:1]: We have E2E tests validating this.

Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly/test/Hosting/EntrypointInvokerTest.cs:1]: I don't believe these tests should be necessary any longer as they were meant to test out the functionality of the `EntrypointInvoker` specifically, which has now been removed. The core logic of finding the assembly and entrypoint is now handled on the runtime layer. Note; we do still have the E2E tests for the functionality: https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/StartupErrorNotificationTest.cs

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs (hunk 3 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:70]: Just realized this won't be possible as we need to keep the property (setter) for use with testing (https://github.com/dotnet/aspnetcore/pull/31769/checks?check_run_id=2336355144)

Comment (TanayParikh) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs]: I believe https://github.com/dotnet/aspnetcore/pull/31769/commits/dd72fbc6811ae1cb57293b3b9128b3e4a599a90e should resolve this.

File: src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts (hunk 2 above)
Comment (pranavkm) [reply src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:63]: There's also a `MONO.mono_call_assembly_entry_point` API. Maybe that's preferable to the BINDING API? @lewing ?

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs [hunk 5]
```diff
@@ -48,7 +48,6 @@ public sealed class WebAssemblyHost : IAsyncDisposable
             string? persistedState)
         {
             // To ensure JS-invoked methods don't get linked out, have a reference to their enclosing types
-            GC.KeepAlive(typeof(EntrypointInvoker));
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:51]: FYI @eerhardt

Comment (eerhardt) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:51]: This should also resolve https://github.com/dotnet/aspnetcore/issues/31148 since it is getting rid of the last call to `Console` in a default Blazor WASM app.

**Comment by pranavkm** [comment]
LoadingApp_DynamicallySetLanguageThrows looks like an actual test failure.

File: src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts (hunk 2 above)
Comment (lewing) [reply src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:63]: I'd copy what is in the link, so pass "m" as the last arg and skip the signature lookup. `[[]]` should be fine in any case but doing as runtime-test.js does will allow `[["arg0", "arg1"]]` to actually pass to `Main(string[])`

Comment (TanayParikh) [reply src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:63]: Thanks, updating with:
```suggestion
    const emptyArray = [ [ ] ];
    return BINDING.call_assembly_entry_point(assemblyName, emptyArray, "m");
```

Just to confirm, the second arg should be left as is, or are you suggesting to change it somehow as well?

Comment (lewing) [reply src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts]: That should be safe for all cases. You would only need to change it if you wanted to pass actual arguments to Main.

File: src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts [hunk 6]
```diff
@@ -54,16 +54,19 @@ export const monoPlatform: Platform = {
     });
   },
 
-  callEntryPoint: function callEntryPoint(assemblyName: string) {
-    // Instead of using Module.mono_call_assembly_entry_point, we have our own logic for invoking
-    // the entrypoint which adds support for async main.
+  callEntryPoint: async function callEntryPoint(assemblyName: string) : Promise<any> {
     // Currently we disregard the return value from the entrypoint, whether it's sync or async.
```
Comment (pranavkm) [inline src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:58]: This comment could be deleted. It's no longer correct.

**Review by pranavkm — APPROVED** [review]

**Review by lewing — APPROVED** [review]
image
nice work!

File: src/Components/Web.JS/src/Boot.WebAssembly.ts [hunk 7]
```diff
@@ -119,7 +119,7 @@ async function boot(options?: Partial<WebAssemblyStartOptions>): Promise<void> {
   }
 
   // Start up the application
-  platform.callEntryPoint(resourceLoader.bootConfig.entryAssembly);
+  await platform.callEntryPoint(resourceLoader.bootConfig.entryAssembly);
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Boot.WebAssembly.ts:122]: @TanayParikh @pranavkm Does this change the semantics of app startup? It depends on how `BINDING.call_assembly_entry_point`, which I can't guess from reading the diff.

I thought that, previously, calling `Blazor.start` would return a promise that resolves when the .NET code begins running. Is that still how it behaves, or does it now resolve only when `MainAsync`'s task completes?

Comment (TanayParikh) [reply src/Components/Web.JS/src/Boot.WebAssembly.ts:122]: This seems to be related to the functionality of `BINDING.call_assembly_entry_point` specifically. Pinging @lewing for more context on this given https://github.com/dotnet/runtime/pull/44045.

Comment (lewing) [reply src/Components/Web.JS/src/Boot.WebAssembly.ts:122]: @SteveSandersonMS is correct, successfully awaiting that task should give you the exit code, control will return as soon as it can, given that the runtime is currently singly threaded.  If your model expects control to yield here before the runtime has exited, don't await the entry point promise.  That said, any guarantees that the entry point will yield at a specific point is probably weak.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Boot.WebAssembly.ts:122]: Thanks @lewing 

In this case, this PR is a breaking change we should fix before preview 4 ships. @TanayParikh I'll follow up by email to coordinate.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Boot.WebAssembly.ts:122]: https://github.com/dotnet/aspnetcore/issues/31971
