### PR TITLE
[8.0] Critical fix to output cache; remove OutputCacheEntry recycling

### LINKED ISSUE #51009: Content-Length mismatch randomly on high troughput when using StackExchange Redis Output Caching
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using StackExchange Redis Output Caching we randomly get an error:
```
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 5468).
```
We analyzed the key value, and we see that the Content-Length is not part of the cache, this means that this 5468 is calculated from the cached entry, but for some reason, the response is not written and this error appears.  

Output caching with Memory works without this issue. 

### Expected Behavior

No System.InvalidOperationException happening.

### Steps To Reproduce

For the test, we created an Apache JMeter test with 10, 25, and 50 threads calling the API each of the tests contained this error.
We could reproduce the issue when using Output caching on the Debug level, only in the environment with the Docker container connecting to the Redis database.

### Exceptions (if any)

_No response_

### .NET Version

8.0.0-rc.2.23466.4

### Anything else?

Host:
  Version:      8.0.0-rc.2.23466.4
  Architecture: x64
  Commit:       287c10d253
  RID:          linux-musl-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rtm.23468.24 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23466.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by mgravell**
# Critical fix to output cache

Output cache shared buffer in the "multiple people requesting same page" path released prematurely, leading to empty responses.

## Description

Part of net8 work in the output-cache middleware was to reduce allocations; one aspect of this was buffer recycling in the `OutputCacheEntry`, however a late discovery is that this recycling can impact separate requests, due to the `Task` reuse between requests when using "locking" mode (see `_requestDispatcher.ScheduleAsync`). This means that some requests (as a race condition) can get empty responses if the `OutputCacheEntry` was already recycled.

There is no risk of buffer bleed between responses (so: no infosec issue), but: empty responses is a critical failure and must be addressed.

Given the late stage of net8, it is proposed to simply drop the buffer recycling aspect; this puts `OutputCacheEntry` back *exactly where it is in net7*, so this choice is not a regression: we just lose something we wanted to add. We can revisit this when we have time to do this safely, in net9 and possibly back-ported to net8 as a service release. A brief investigation using counting was attempted, but this was not immediately successful, and I'd rather have minimum risk.

A new test shows the failure, and now passes.

Fixes #51009 (note that despite the title, this issue is not specific to any particular output-cache provider)

## Customer Impact

Without the fix, empty responses are possible

## Regression?

- [x] Yes
- [ ] No

[If yes, specify the version the behavior has regressed from]

net7.0, net8 preview 6

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Resolution chosen with minimal risk rather than perfect solution in mind, that sacrifices some potential buffer reuse; we plan to
implement full buffer reuse by restructuring the shared result cache, allowing us to correctly track active usage, but this is
beyond what we will do "now". This work will be in net9 and optionally backported to a net8 servicing release (tbd).

## Verification

- [ ] Manual (required)
- [x] Automated - new test

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs [hunk 1]
```diff
@@ -72,25 +71,6 @@ internal void SetBody(ReadOnlySequence<byte> value, bool recycleBuffers)
...
     }
 
-    public void Dispose()
-    {
-        var headers = Headers;
-        var body = Body;
-        Headers = default;
-        Body = default;
-        Recycle(headers);
-        RecyclableReadOnlySequenceSegment.RecycleChain(body, _recycleBuffers);
```
Comment (captainsafia) [inline src/Middleware/OutputCaching/src/OutputCacheEntry.cs:82]: Is the `_recycleBuffers` property still in use? Can be removed if not.

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs [hunk 2]
```diff
@@ -69,26 +66,9 @@ public bool TryFindHeader(string key, out StringValues values)
...
-        // ^^ note that this only recycles the chain, not the actual buffers
-    }
-
-    private static void Recycle<T>(ReadOnlyMemory<T> value)
-    {
-        if (MemoryMarshal.TryGetArray<T>(value, out var segment) && segment.Array is { Length: > 0 })
-        {
-            ArrayPool<T>.Shared.Return(segment.Array);
-        }
+        _ = recycleBuffers; // satisfy IDE0060
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: We set `recycleBuffers` to true in one case
https://github.com/dotnet/aspnetcore/blob/9922772d07a7f4d21d2becdb00fb5a206b9807cc/src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs#L431
Are we now adding unnecessary strain on the ArrayPool by not returning that memory?

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs [hunk 3]
```diff
@@ -69,26 +66,9 @@ public bool TryFindHeader(string key, out StringValues values)
...
-        _recycleBuffers = recycleBuffers;
-    }
-
-    public void Dispose()
-    {
-        var headers = Headers;
-        var body = Body;
-        Headers = default;
-        Body = default;
-        Recycle(headers);
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/src/OutputCacheEntry.cs:81]: This is also memory coming from the ArrayPool that we're no longer returning?

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs (hunk 2 above)
Comment (mgravell) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: array pool doesn't care about non-returned buffers - they'll just GC

Comment (BrennanConroy) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: Sure, but if you drain the array pool it becomes expensive to get an array from the pool. We saw this recently with the IdentityModel package where they weren't disposing an object that had rented memory from the array pool and so it was GCed instead of returned, but then the array pool became empty and it was very expensive to rent new arrays from the pool.

**Comment by danmoseley** [comment]
Is there any other testing (not specific to this issue) that might be worth doing on this component just to give us more confidence in shipping it? (It seems you just reverted this one part).
Not suggesting there's other issues but it seems like an opportunity to double check ourselves.

File: src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs [hunk 4]
```diff
@@ -200,6 +200,7 @@ private async Task InvokeAwaited(HttpContext httpContext, IReadOnlyList<IOutputC
         {
             // avoid recycling in unknown outcomes, especially re concurrent buffer access thru cancellation
             hasException = true;
+            throw;
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs:203]: Should add a regression test

Comment (mgravell) [reply src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs:203]: yeah, I was planning to - [have an initial test](https://github.com/dotnet/aspnetcore/pull/51067/commits/135c4fa9fd9688c57840b78a3fb713ab8e22cf19), but it manifests contrary to my expectations (i.e. we see an actual exception rather than a 5xx http); I'm going to check this test against the "before I touched anything" state, to see if this is just an artefact of the test harness

Comment (mgravell) [reply src/Middleware/OutputCaching/src/OutputCacheMiddleware.cs:203]: tested at `b362c450058d7fe3279ffdcc1f6e40beaf828967` (which is "before") - behaviour is identical there, i.e. yes, I think that's a feature of the test harness (presumably we're hooking at a level that doesn't include the global fault loop)

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs (hunk 2 above)
Comment (mgravell) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: @BrennanConroy right; but if we don't want to leak buffers, we need to either a: implement ref-counting, or b: fetch the memory from somewhere else, and drop *that* on the floor; I had a stab at the ref-counting originally, and ironically: it was that damned missing `throw;` that caused that experiment to fail; we can implement it; consider: https://github.com/dotnet/aspnetcore/pull/51131/files

but... that's what I was saying is a bit more "fun"; is it worth deferring that to service release 1 ?

Comment (danmoseley) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: am I understanding correctly though that this takes us back to .NET 7? if so, then it's apparently shippable quality. or is this a place where we will be introducing something new.

Comment (BrennanConroy) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: > am I understanding correctly though that this takes us back to .NET 7? 

The PR as is doesn't take us all the way back to .NET 7. In .NET 7 we just allocated. This PR reverts to an in-between state, we call `ArrayPool.Rent` but don't call `ArrayPool.Return`.

I think we should either
* run a quick perf test to see if it causes issues 
* just remove ArrayPool.Rent and allocate
* Fix ArrayPool usage (there is a draft PR by Marc for this)

Comment (danmoseley) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:69]: your judgement, but I'd err towards minimum risk given we have no more previews. .NET 7 was successful.

File: src/Middleware/OutputCaching/src/OutputCacheEntry.cs (hunk 3 above)
Comment (mgravell) [reply src/Middleware/OutputCaching/src/OutputCacheEntry.cs:81]: resolved https://github.com/dotnet/aspnetcore/pull/51067/commits/0275ad28f4b4b8e5985c71d9f61a889f9c5386ce

**Review by BrennanConroy — APPROVED** [review]
While looking around the code I noticed we never use `IOutputCacheBufferStore.TryGetAsync`, was this intentional? Is there an issue to follow up and make use of it?

**Comment by adityamandaleeka** [comment]
Test failure looked like an unrelated timeout so I kicked it again, but including the error here for reference:

```
2023-10-09T15:24:12.7383324Z  | [30.021s] Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests Error: Test threw an exception.
2023-10-09T15:24:12.7383424Z  | System.TimeoutException: The operation has timed out.
2023-10-09T15:24:12.7383449Z  |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
2023-10-09T15:24:12.7383472Z  |    at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs:line 111
2023-10-09T15:24:12.7383523Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-10-09T15:24:12.7383607Z  | --- End of stack trace from previous location ---
2023-10-09T15:24:12.7383640Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-10-09T15:24:12.7383669Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-10-09T15:24:12.7383694Z  | [30.022s] TestLifetime Information: Finished test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-ServerSentEvents-json in 30.021229s
2023-10-09T15:24:12.7383719Z 
```

**Comment by adityamandaleeka** [comment]
Approved over email.
