### PR TITLE
Fix ProducesResponseType's Description not being set for Minimal API's when attribute and inferred types aren't an exact match

### LINKED ISSUE #60518: Description parameter of ProducesResponseTypeAttribute does not work in minimal API app
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

A Description parameter was added to ProducesResponseTypeAttribute in .NET 10 to set the `description` field of the response in the generated OpenAPI document. This works fine in a controller-based app but does not seem to work in a Minimal API app.

### Expected Behavior

The ProducesResponseTypeAttribute, when placed on the delegate parameter of a minimal API app endpoint, should add a description to the response in the generated API.

```csharp
app.MapGet("/weatherforecast",
[ProducesResponseType<IEnumerable<WeatherForecast>>(StatusCodes.Status200OK, Description = "The service is healthy.")]
() =>
{
```

### Steps To Reproduce

I've reproduced the problem in the project in this repo:

https://github.com/mikekistler/ResponseDescription

The problem exists for both the OpenAPI generated at build time and the OpenAPI served from the /openapi/v1.json endpoint.

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-preview.1.25104.26

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sander1095**
# Fix ProducesResponseType's Description not being set for Minimal API's when attribute and inferred types aren't an exact match

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Fix ProducesResponseType Description matching for inheritance/interface compatibility

## Description

I contributed a new `Description` property to ASP.NET Core's `ProducesResponseType`  in [an earlier preview release](https://github.com/dotnet/aspnetcore/pull/58193) of .NET 10.

Currently, `ProducesResponseType` attributes for Minimal API only match response types using strict equality comparison (`==`). This causes the attribute descriptions to be ignored when there's a valid type compatibility relationship between the attribute type and the inferred return type.

For example:

```csharp
[ProducesResponseType<IEnumerable<string>>(200, Description = "List of items")]
() => TypedResults.Ok(new List<string>())
```

In this case, the description "List of items" is lost because `IEnumerable<string> != List<string>`, even though `List<string>` implements `IEnumerable<string>`.

We can fix this by doing a better check:

```csharp
// Before: Only exact type matches
if (responseType.Type == attributeType)

// After: Allow inheritance/interface compatibility  
if (responseType.Type == attributeType || 
    attributeType.IsAssignableFrom(responseType.Type) || 
    responseType.Type.IsAssignableFrom(attributeType))
```

This supports the following scenarios:

- Interface implementations (IEnumerable<T> ↔ List<T>)
- Inheritance relationships (BaseClass ↔ DerivedClass)
- Collection type hierarchies (IReadOnlyList<T> ↔ ReadOnlyCollection<T>)

While this works, there are some possible downsides to this approach, and more complex type differences between the attribute type and inferred type aren't handled by this code. See the PR comments for more information and discussions.

Fixes #60518

### CODE REVIEW

**Comment by sander1095** [comment]
TODO:

- [x] Add PR description
- [x] Check what controllers do if you specify `IEnumerable<BaseClass>` in an attribute, and return `List<ClassThatInheritsBaseClass>`. Minimal API needs the same behavior, and we might need to add more tests.
- [x] Check what controllers do when you specify IReadOnlyList<> but you return ICollection, and also the same way around. This isn't a direct assignment, so we want the same behavior in Minimal API's. 
- [x] Check what controllers do if you specify List<> in attribute, but return IEnumeable. This PR would make it work in Minimal API's, but we want to do what controllers do.
- [x] Write a comment about the pros and cons of the current approach (Bidirectional checks, object vs string, etc..)
- [x] Create PR for https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0#response-description-on-producesresponsetype-for-api-controllers as this now would support Description
- [x] Also fix the formatting in https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0#microsoftaspnetcoreopenapi-added-to-the-aspnet-core-web-api-native-aot-template

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 1]
```diff
@@ -322,6 +322,7 @@ private static void AddSupportedResponseTypes(
         Type returnType,
         EndpointMetadataCollection endpointMetadata)
     {
+        System.Diagnostics.Debugger.Break();
```
Comment (sander1095) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: I need to delete this line!

**Comment by sander1095** [comment]
@captainsafia @halter73 

I've identified scenarios that currently fail but could potentially work with deeper type analysis. Should these be supported?

Example: Attribute specifies `List<BaseClass>`, endpoint returns `IEnumerable<DerivedClass>`

```csharp
[ProducesResponseType<List<BaseClass>>(200, Description = "Items")]
() => new List<DerivedClass>().AsEnumerable()
```
- Outer type: List vs IEnumerable ✅ (handled by current fix)
- Inner type: BaseClass vs DerivedClass ❌ (would require recursive generic type analysis)

Trade-offs of supporting this:

- ✅ More comprehensive type matching
- ❌ Complex reflection logic for nested generics
- ❌ Potential AOT compatibility issues (Would need to be investigated)
- ❌ Performance impact from deep type analysis

Should I implement recursive generic type compatibility checking, or is the current collection-level matching sufficient? Keep in mind that this PR is only relevant for Minimal API's, and that `[ProducesResponseType]` with Minimal API's isn't recommended by the ASP.NET Core team, as using TypedResults/Extension Methods/OpenAPI transformers are "better"

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 2]
```diff
@@ -404,15 +404,28 @@ private static void AddSupportedResponseTypes(
...
+
+        static bool TypesAreCompatible(Type? apiResponseType, Type? metadaType)
+        {
+            // We need to a special check for cases where the inferred type is different than the one specified in attributes.
+            // For example, an endpoint that defines [ProducesResponseType<IEnumerable<WeatherForecast>>],
+            // but the endpoint returns weatherForecasts.ToList(). Because List<> is a different type than IEnumerable<>, it would incorrectly return false.
+            // Currently, we do a "simple" bidirectional check to see if the types are assignable to each other.
+            // This isn't very thorough, but it works for most cases.
+            // For more information, check the related bug: https://github.com/dotnet/aspnetcore/issues/60518
+            return apiResponseType == metadaType ||
```
Comment (sander1095) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: ## Potential Downsides of Bidirectional Type Compatibility

While the bidirectional approach (`Type.IsAssignableFrom()` in both directions) solves the immediate problem, there are some trade-offs to consider:

### 1. Over-Matching Risk
The bidirectional check could match unintended type relationships:

```csharp
[ProducesResponseType<object>(200, Description = "Any object")]
() => TypedResults.Ok("specific string")
```

Since object.IsAssignableFrom(string) is true, this would incorrectly match and use the generic "Any object" description instead of inferring a more specific string response description.


### 2. Ambiguous Inheritance Scenarios
With complex inheritance hierarchies, the matching might be too permissive:

```
[ProducesResponseType<BaseClass>(200, Description = "Base description")]
[ProducesResponseType<DerivedClass>(200, Description = "Derived description")]  
() => TypedResults.Ok(new DerivedClass())
```

## Alternative:  Unidirectional Approach

A more conservative approach would only check if the attribute type is assignable from the inferred type:

```
// Only allow: attribute type ← inferred type (inheritance/interface direction)
if (attributeType.IsAssignableFrom(responseType.Type))
```

This would:

- ✅ Handle IEnumerable<T> ← List<T> (the main use case)
- ✅ Handle BaseClass ← DerivedClass
- ❌ Prevent List<T> ← IEnumerable<T> (less common scenario)
- ✅ Avoid most over-matching issues

@captainsafia @halter73 
Should we switch to the more conservative unidirectional approach, or are the current bidirectional benefits worth the potential edge case risks?

The bidirectional approach handles more scenarios but could be "too smart" in some cases.

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 3]
```diff
@@ -404,15 +404,28 @@ private static void AddSupportedResponseTypes(
             string? matchingDescription = null;
             foreach (var metadata in responseMetadataTypes)
             {
-                if (metadata.StatusCode == apiResponseType.StatusCode &&
-                    metadata.Type == apiResponseType.Type &&
-                    metadata.Description is not null)
+                if (metadata?.StatusCode == apiResponseType?.StatusCode &&
```
Comment (captainsafia) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: Is there a reason for the nullability check here? It seems like both `metadata` and `apiResponseType` are guaranteed to be non-null unless our existing annotations are wrong.

File: src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs [hunk 4]
```diff
@@ -331,6 +331,158 @@ public void AddsResponseDescription()
...
+        Assert.Equal(200, okResponseType.StatusCode);
+        Assert.Equal(typeof(IEnumerable<BaseClass>), okResponseType.Type); // We use IEnumerable<BaseClass> as the inferred type has higher priority than those set by metadata (attributes)
+        Assert.Equal(typeof(IEnumerable<BaseClass>), okResponseType.ModelMetadata?.ModelType);
+        Assert.Equal(expectedOkDescription, okResponseType.Description);
+
+        var createdOkFormat = Assert.Single(okResponseType.ApiResponseFormats);
+        Assert.Equal("application/json", createdOkFormat.MediaType);
+    }
+
+    [Fact]
```
Comment (captainsafia) [inline src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs]: Do we have a test that documents the behavior of something like:

```csharp
[ProducesResponseType(typeof(UserDto), 200)]
Get() => TypedResults.Ok(new UserDto());

```

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs (hunk 2 above)
Comment (captainsafia) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: IMO, I think the conservative approach is better here. It's more common for the type defined in the attribute to be more specific than the type inferred by the delegate or defined as the return type so most scenarios would be covered by this check.

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs (hunk 3 above)
Comment (sander1095) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: I agree. During development I got errors about them being necessary. I also disagreed with you, but added them to remove the errors.

I tried removing them again and now everything works, so I've committed this change. Consider them removed!

File: src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs (hunk 4 above)
Comment (sander1095) [reply src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs]: Yes, `EndpointMetadataAPiDescriptionProviderTest.cs` has multiple test cases that tests this:

- `AddsMultipleResponseFormatsFromMetadataWithIResult`
- `AddsResponseDescription`
- `AddsResponseDescription_UsesLastOne`
- `AddsMultipleResponseFormatsFromMetadataWithAwaitableIResult`

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs (hunk 2 above)
Comment (sander1095) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: Done!

**Comment by sander1095** [comment]
@wtgodbe My apologies for requesting a review, my finger must have slipped. Feel free to ignore!

**Review by captainsafia — APPROVED** [review]
