### PR TITLE
Remove IsAvailable check on CommitAsync.

### LINKED ISSUE #42009: DistributedSession always loads session in CommitAsync even when session is not modified
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As part of https://github.com/dotnet/aspnetcore/pull/26098/commits/f99b482fe0ac72958d7bc5ed88e956fb62971c09 code is `DistributedSession.CommitsAsync` was modified to check `IsAvailable`. 

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L263

`IsAvailable` always loads session from backing store and loads it in synchronous way.
https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L96

On the other hand `SessionMiddleware` always calls `DistributedSession.CommitAsync` to save session. This means that in 6.0 session is **always loaded** even if application code did not touch it at all. In case of using Redis as backing store this incurs two Redis calls on each RazorPage rendered.  

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/SessionMiddleware.cs#L119

In the past (5.0) when session was not touched `DistributedSession._isModified` prevented session data from being loaded when session was not modified.

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Middleware/Session/src/DistributedSession.cs#L274

@pranavkm Could you tell why `IsAvailable` was moved?

### Expected Behavior

Don't loading session data from backing store when session data is not modified by app code.

### .NET Version

6.0.300

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix https://github.com/dotnet/aspnetcore/issues/42009

I did some archaeology into how we ended up adding this check. I _think_ (but am not certain yet) this was added because [one of the incremental states](https://github.com/dotnet/aspnetcore/pull/26098/commits/12d5f37b3725d46bed4dd40a1ae32e88f73cbe14#diff-143902782fe943cbff15b8d422e2996896dfef96590ff2b7058bc50056322544L126) of #26098 had a null-forgiving operator on the `IdBytes` getter. `IdBytes` could return null if `IsAvailable` wasn't set.

This led to the addition of the `if (!IsAvailable)` check in `Serialize` which was subsequently moved to `CommitAsync` based on [this comment](https://github.com/dotnet/aspnetcore/pull/26098/#discussion_r508667599).

However, the `IdBytes` getter was changed to make its result non-null:

https://github.com/dotnet/aspnetcore/blob/bf02bf2325f4752dd8a28c17d420e01961219f91/src/Middleware/Session/src/DistributedSession.cs#L119-L131

Assuming this was the concern that led to the `IsAvailable` check being added to `CommitAsync`, I think we're okay to remove it. I'd like another pair of eyes on this though.

### CODE REVIEW

File: src/Middleware/Session/src/DistributedSession.cs [hunk 1]
```diff
@@ -262,12 +262,6 @@ public async Task LoadAsync(CancellationToken cancellationToken = default)
     /// <inheritdoc />
     public async Task CommitAsync(CancellationToken cancellationToken = default)
     {
-        if (!IsAvailable)
```
Comment (BrennanConroy) [inline src/Middleware/Session/src/DistributedSession.cs:265]:
```
// use field to avoid loading the session via IsAvailable property
if (!_isAvailable)
```
?

Comment (adityamandaleeka) [reply src/Middleware/Session/src/DistributedSession.cs:265]: Not sure we want that; if `_isAvailable` wasn't set, it could be that we never attempted to load it. The current code attempts to load in that case.

Comment (halter73) [reply src/Middleware/Session/src/DistributedSession.cs:265]: Why would we remove this check in `CommitAsync` but not in `Set`?

Comment (adityamandaleeka) [reply src/Middleware/Session/src/DistributedSession.cs:265]: `Set` always depends on `IsAvailable`, but `CommitAsync` might not need to load the session if `_isModified` isn't true. The `IsAvailable` check was added in `CommitAsync` during the nullability work but I don't see why it's necessary now.

Comment (halter73) [reply src/Middleware/Session/src/DistributedSession.cs:265]: I see. And it could force sync-over-async as well. Yuck!

**Review by halter73 — APPROVED** [review]

**Review by Tratcher — APPROVED** [review]

**Comment by csturm83** [comment]
@adityamandaleeka Will this regression fix be back ported to .NET 6 (LTS) ?

**Comment by adityamandaleeka** [comment]
@csturm83 It doesn't seem severe enough for a 6.0 backport, but we could consider it if there's a compelling use case that's broken.

**Comment by csturm83** [comment]
@adityamandaleeka Between the unexpected/undocumented behavior change (exiting early vs. throwing an exception), consistency/symmetry with LoadAsync exceptional behavior, performance hit of potential extra deserialization, synch over async, etc. - in my opinion, it seems worth it. 

That, and it's a relatively focused change that restores documented behavior and expectations (addresses a regression).

**Comment by Tratcher** [comment]
@csturm83 backporting is expensive and risky, a bug must have high impact and no viable workaround. While in-efficient, it's not clear that this bug is causing a blocking issue for you?

**Comment by Alex-Covecube** [comment]
Just wanted to let you guys know that the _IsAvailable_ call you're discussing was causing massive CPU load on our servers.

**Scenario:** 

We originally used MongoDB for our _IDistributedCache_ implementation, and that worked well for a while when our traffic was low. As our server load grew we started moving our code to Redis with the expectation of reducing overhead.

Imagine our surprise when Redis actually consumed an order of magnitude more CPU on the web servers than the previous MongoDB implementation. We used the StackExchange Redis driver with Microsoft.Extensions.Caching.StackExchangeRedis for the ASP.NET Core integration, really standard stuff.

To make a long story short, after much analysis it turns out that having _IsAvailable_ in _CommitAsync_ (_DistributedSession_ class) forces the Redis driver to do a sync get on every page load, and apparently StackExchange Redis is not that efficient with sync calls.

Solutions tried:
- Increase the number of threads for the socket thread pool on StackExchange Redis in the hopes of making enough threads available for more sync calls.
- Completely replace _Microsoft.Extensions.Caching.StackExchangeRedis_ with a custom _IDistributedCache_.
- **Completely reimplement the entire _DistributedSession : ISession_, and remove the _IsAvailable_ call in _CommitAsync_.**

Only the last option worked well enough to actually decrease load on the web servers to approximately what we saw with the older MongoDB implementation.

To me, it seems like this issue can cause a massive performance drop under pretty common circumstances. Especially given that the official docs recommend the exact setup that we had (https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed)

**Comment by csturm83** [comment]
@Tratcher see @Alex-Covecube 's comment above (wasn't sure if comments on closed issues generate notification without an @ mention). Silent performance traps that can spike CPU usage could be costly.

For those of us in enterprise tied to LTS releases, it would be a shame to have to wait until 8.0 for this regression fix.

**Comment by adityamandaleeka** [comment]
@Alex-Covecube thanks for letting us know. I've reopened the issue for backport consideration.
