### PR TITLE
Nullability in SignalR

### LINKED ISSUE #25612: NullReferenceException in SignalR's DefaultHubDispatcher
`DefaultHubDispatcher` calls [`DisposeAsync`](https://github.com/dotnet/aspnetcore/blob/v5.0.0-preview.8.20414.8/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L139) on a null reference if `IServiceScopeFactory.CreateScope` throws an exception [here](https://github.com/dotnet/aspnetcore/blob/v5.0.0-preview.8.20414.8/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L114), so `NullReferenceException` is thrown from the `finally` block, overwriting the original exception. This happens when the application is stopping and dispatcher methods are called after `IServiceProvider` is disposed.

### LINKED ISSUE #28954: Wrong nullable annotations on IHubProtocol.TryParseMessage in SignalR
The interface [IHubProtocol](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/SignalR/common/SignalR.Common/src/Protocol/IHubProtocol.cs#L38) should have `HubMessage?` type for its `out` parameter `message`. Existing implementations like [JsonHubProtocol](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L91), [MessagePackHubProtocol](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/SignalR/common/Protocols.MessagePack/src/Protocol/MessagePackHubProtocol.cs#L64) return null from this method.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/25612
Fixes https://github.com/dotnet/aspnetcore/issues/28954

### CODE REVIEW

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 1]
```diff
@@ -116,7 +116,7 @@ internal StreamTracker StreamTracker
         /// <summary>
         /// Gets the user for this connection.
         /// </summary>
-        public virtual ClaimsPrincipal? User => Features.Get<IConnectionUserFeature>()?.User;
+        public virtual ClaimsPrincipal User => Features.Get<IConnectionUserFeature>()?.User ?? new ClaimsPrincipal();
```
Comment (BrennanConroy) [inline src/SignalR/server/Core/src/HubConnectionContext.cs:119]: Not sure what to do here. Cache the `User`?

The reason I'm not keeping it null is because it's nicer to deal with an empty `ClaimsPrincipal` than a null one. An empty one will not be authenticated in any way or have any claims. The Auth types we use don't have null annotations for the user as the expectation is that you'll at least pass an empty one.

Comment (JamesNK) [reply src/SignalR/server/Core/src/HubConnectionContext.cs:119]: Assign blank `ClaimsPrincipal` to underlying `IConnectionUserFeature` when the property is accessed?

**Comment by JamesNK** [comment]
Will review when PR is out of draft 🥇

File: src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.InvokeAsyncGeneric.cs [hunk 2]
```diff
@@ -43,7 +43,7 @@ public static Task<TResult> InvokeAsync<TResult>(this HubConnection hubConnectio
         /// The <see cref="Task{TResult}.Result"/> property returns a <typeparamref name="TResult"/> for the hub method return value.
         /// </returns>
         [SuppressMessage("ApiDesign", "RS0026:Do not add multiple overloads with optional parameters", Justification = "Required to maintain compatibility")]
-        public static Task<TResult> InvokeAsync<TResult>(this HubConnection hubConnection, string methodName, object arg1, CancellationToken cancellationToken = default)
+        public static Task<TResult> InvokeAsync<TResult>(this HubConnection hubConnection, string methodName, object? arg1, CancellationToken cancellationToken = default)
```
Comment (pranavkm) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.InvokeAsyncGeneric.cs:46]: Should these be `Task<TResult?>`

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs [hunk 3]
```diff
@@ -302,7 +303,7 @@ private async Task DisposeAsyncCore()
 
         private async Task SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
         {
-            var uri = _httpConnectionOptions.Url;
+            var uri = _httpConnectionOptions.Url!;
```
Comment (pranavkm) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:306]: Seen this twice so far. Should this be property be made non-null?

File: src/SignalR/common/Shared/MemoryBufferWriter.cs [hunk 4]
```diff
@@ -145,6 +146,7 @@ public override Task CopyToAsync(Stream destination, int bufferSize, Cancellatio
             return CopyToSlowAsync(destination);
         }
 
+        [MemberNotNull("_currentSegment")]
```
Comment (pranavkm) [inline src/SignalR/common/Shared/MemoryBufferWriter.cs:149]:
```suggestion
        [MemberNotNull(nameof(_currentSegment))]
```

File: src/SignalR/common/Shared/SystemTextJsonExtensions.cs [hunk 5]
```diff
@@ -80,7 +78,7 @@ public static bool ReadAsBoolean(this ref Utf8JsonReader reader, string property
                 throw new InvalidDataException($"Expected '{propertyName}' to be of type {JsonTokenType.String}.");
             }
 
-            return reader.GetString();
+            return reader.GetString()!;
```
Comment (pranavkm) [inline src/SignalR/common/Shared/SystemTextJsonExtensions.cs:81]: Now that's just a lie

Comment (BrennanConroy) [reply src/SignalR/common/Shared/SystemTextJsonExtensions.cs:81]: No it isn't, we check above that the token type is a string. If the string is null it would have token type null.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs (hunk 3 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:306]: Is there a way to make a property non-null when it isn't assigned in the ctor? I guess setting it to string.Empty is a workaround.

Comment (pranavkm) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:306]: `public string Url { get; set; } = default!;` is something we do fairly commonly.

File: src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.InvokeAsyncGeneric.cs (hunk 2 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.InvokeAsyncGeneric.cs:46]: I don't think so? That would force callers to always handle null even if they never expect it to be null. If they use a nullable for `TResult` then that means they expect a null value and should handle it, and the compiler will let them know that. So seems better to let the user decide.

Comment (pranavkm) [reply src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.InvokeAsyncGeneric.cs:46]: Fair enough. It's effectively the same choice we made with JSInterop. But we also do not provide any guarantees against it which is crummy.

File: src/SignalR/server/Core/src/HubConnectionContext.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/server/Core/src/HubConnectionContext.cs:119]: The `IConnectionUserFeature` could come from anyone (in theory), and the interface allows a null user. Plus the interface itself could not be on the connection.

File: src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs [hunk 6]
```diff
@@ -635,23 +635,23 @@ async Task OnStreamCanceled(InvocationRequest irq)
...
-            Dictionary<string, object> readers = null;
+            Dictionary<string, object>? readers = null;
             streamIds = null;
-            var newArgs = new List<object>(args.Length);
+            var newArgs = new List<object?>(args.Length);
 
             for (var i = 0; i < args.Length; i++)
             {
-                if (args[i] != null && ReflectionHelper.IsStreamingType(args[i].GetType()))
+                if (args[i] != null && ReflectionHelper.IsStreamingType(args[i]!.GetType()))
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:646]:
```suggestion
                if (args[i] is {} arg && ReflectionHelper.IsStreamingType(arg.GetType()))
```
For ultimate @pranavkm points 🐴 

(I think this works)

File: src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs [hunk 7]
```diff
@@ -635,23 +635,23 @@ async Task OnStreamCanceled(InvocationRequest irq)
...
                 {
                     if (readers == null)
                     {
                         readers = new Dictionary<string, object>();
                     }
 
                     var id = connectionState.GetNextId();
-                    readers[id] = args[i];
+                    readers[id] = args[i]!;
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:654]:
```suggestion
                    readers[id] = arg;
```

File: src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.cs [hunk 8]
```diff
@@ -98,7 +98,7 @@ public static IDisposable On<T1>(this HubConnection hubConnection, string method
 
             return hubConnection.On(methodName,
                 new[] { typeof(T1), typeof(T2), typeof(T3) },
-                args => handler((T1)args[0], (T2)args[1], (T3)args[2]));
+                args => handler((T1)args[0]!, (T2)args[1]!, (T3)args[2]!));
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.cs:101]: Hmm, I wonder if there is a better way to avoid all these bangs.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs [hunk 9]
```diff
@@ -75,14 +74,16 @@ public override IDuplexPipe Transport
         /// If the connection was created with <see cref="HttpConnectionOptions.SkipNegotiation"/> set to <c>true</c>
         /// then the connection ID will be <c>null</c>.
         /// </remarks>
-        public override string ConnectionId
+        public override string? ConnectionId
         {
+#pragma warning disable CS8764 // Nullability of return type doesn't match overridden member (possibly because of nullability attributes).
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:79]: Should ConnectionId be made nullable on ConnectionContext?

File: src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/LongPollingTransport.cs [hunk 10]
```diff
@@ -73,7 +71,7 @@ private async Task ProcessAsync(Uri url)
         {
             // Start sending and polling (ask for binary if the server supports it)
             var receiving = Poll(url, _transportCts.Token);
-            var sending = SendUtils.SendMessages(url, _application, _httpClient, _logger);
+            var sending = SendUtils.SendMessages(url, _application!, _httpClient, _logger);
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/LongPollingTransport.cs:74]: To make `_application` not null wherever you use it in this method, you can add `Debug.Assert(_application != null)` at the start of the method.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/ServerSentEventsTransport.cs [hunk 11]
```diff
@@ -94,7 +94,7 @@ private async Task ProcessAsync(Uri url, HttpResponseMessage response)
         {
             // Start sending and polling (ask for binary if the server supports it)
             var receiving = ProcessEventStream(response, _transportCts.Token);
-            var sending = SendUtils.SendMessages(url, _application, _httpClient, _logger, _inputCts.Token);
+            var sending = SendUtils.SendMessages(url, _application!, _httpClient, _logger, _inputCts.Token);
```
Comment (JamesNK) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/ServerSentEventsTransport.cs:97]: Consider Debug.Assert on _application.

Repeat for other usages in transports.

File: src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs [hunk 12]
```diff
@@ -64,8 +62,14 @@ internal class HttpConnectionContext : ConnectionContext,
         /// <param name="connectionId"></param>
         /// <param name="connectionToken"></param>
         /// <param name="logger"></param>
-        public HttpConnectionContext(string connectionId, string connectionToken, ILogger logger)
+        /// <param name="transport"></param>
+        /// <param name="application"></param>
```
Comment (JamesNK) [inline src/SignalR/common/Http.Connections/src/Internal/HttpConnectionContext.cs:66]: Could you get rid of these? Type is internal now.

File: src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs [hunk 13]
```diff
@@ -179,7 +178,7 @@ private HubMessage ParseMessage(ReadOnlySequence<byte> input, IInvocationBinder
                                 reader.Read();
                                 while (reader.TokenType != JsonTokenType.EndArray)
                                 {
-                                    newStreamIds.Add(reader.GetString());
+                                    newStreamIds.Add(reader.GetString() ?? throw new InvalidDataException($"Null value for {StreamIdsPropertyName} is not valid."));
```
Comment (JamesNK) [inline src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs:181]: nit

```suggestion
                                    newStreamIds.Add(reader.GetString() ?? throw new InvalidDataException($"Null value for '{StreamIdsPropertyName}' is not valid."));
```

File: src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs [hunk 14]
```diff
@@ -179,7 +179,7 @@ private HubMessage ParseMessage(Utf8BufferTextReader textReader, IInvocationBind
                                         reader.Read();
                                         while (reader.TokenType != JsonToken.EndArray)
                                         {
-                                            newStreamIds.Add(reader.Value?.ToString());
+                                            newStreamIds.Add(reader.Value?.ToString() ?? throw new InvalidDataException($"Null value for {StreamIdsPropertyName} is not valid."));
```
Comment (JamesNK) [inline src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs:182]:
```suggestion
                                            newStreamIds.Add(reader.Value?.ToString() ?? throw new InvalidDataException($"Null value for '{StreamIdsPropertyName}' is not valid."));
```

File: src/SignalR/common/Shared/Utf8BufferTextWriter.cs [hunk 15]
```diff
@@ -83,9 +81,12 @@ public override void Write(char[] buffer, int index, int count)
             WriteInternal(buffer.AsSpan(index, count));
         }
 
-        public override void Write(char[] buffer)
+        public override void Write(char[]? buffer)
```
Comment (JamesNK) [inline src/SignalR/common/Shared/Utf8BufferTextWriter.cs:84]: Huh, weird that `TextWriter.Write(char[])` allows a nullable array.

File: src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs [hunk 16]
```diff
@@ -80,12 +80,12 @@ public override Task RemoveFromGroupAsync(string connectionId, string groupName,
         }
 
         /// <inheritdoc />
-        public override Task SendAllAsync(string methodName, object?[]? args, CancellationToken cancellationToken = default)
+        public override Task SendAllAsync(string methodName, object?[] args, CancellationToken cancellationToken = default)
```
Comment (JamesNK) [inline src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs:83]: Is this a change from .NET 5? There is an aspnetcore annoucement issue for nullability changes.

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 17]
```diff
@@ -116,7 +117,17 @@ internal StreamTracker StreamTracker
...
         /// Gets the user for this connection.
         /// </summary>
-        public virtual ClaimsPrincipal? User => Features.Get<IConnectionUserFeature>()?.User;
+        public virtual ClaimsPrincipal User
+        {
+            get
+            {
+                if (_user is null)
+                {
+                    _user = Features.Get<IConnectionUserFeature>()?.User ?? new ClaimsPrincipal();
```
Comment (JamesNK) [inline src/SignalR/server/Core/src/HubConnectionContext.cs:126]: 👍

File: src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs [hunk 18]
```diff
@@ -74,12 +72,10 @@ internal partial class DefaultHubDispatcher<THub> : HubDispatcher<THub> where TH
 
         public override async Task OnConnectedAsync(HubConnectionContext connection)
         {
-            IServiceScope scope = null;
+            IServiceScope scope = _serviceScopeFactory.CreateScope();
```
Comment (JamesNK) [inline src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:75]:
```suggestion
            var scope = _serviceScopeFactory.CreateScope();
```

image

File: src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs [hunk 19]
```diff
@@ -107,14 +103,12 @@ public override async Task OnConnectedAsync(HubConnectionContext connection)
             }
         }
 
-        public override async Task OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
+        public override async Task OnDisconnectedAsync(HubConnectionContext connection, Exception? exception)
         {
-            IServiceScope scope = null;
+            IServiceScope scope = _serviceScopeFactory.CreateScope();
```
Comment (JamesNK) [inline src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:108]:
```suggestion
            var scope = _serviceScopeFactory.CreateScope();
```

File: eng/targets/CSharp.Common.targets [hunk 20]
```diff
@@ -80,7 +80,8 @@
 
         SuppressNullableAttributesImport to disable. Used when attributes are already present from another project because of InternalsVisibleTo.
      -->
-    <When Condition="'$(Nullable)' != '' AND '$(SuppressNullableAttributesImport)' != 'true' AND ('$(TargetFrameworkIdentifier)' == '.NETStandard' OR '$(TargetFrameworkIdentifier)' == '.NETFramework')">
+    <When Condition="'$(Nullable)' != '' AND '$(SuppressNullableAttributesImport)' != 'true' AND (('$(TargetFrameworkIdentifier)' == '.NETStandard' AND $([MSBuild]::VersionLessThanOrEquals('$(TargetFrameworkVersion)', '2.0')))
+        OR '$(TargetFrameworkIdentifier)' == '.NETFramework')">
```
Comment (halter73) [inline eng/targets/CSharp.Common.targets:84]: Nit:

```suggestion
    <When Condition="'$(Nullable)' != '' AND '$(SuppressNullableAttributesImport)' != 'true' AND
        (('$(TargetFrameworkIdentifier)' == '.NETStandard' AND $([MSBuild]::VersionLessThanOrEquals('$(TargetFrameworkVersion)', '2.0'))) OR '$(TargetFrameworkIdentifier)' == '.NETFramework')">
```

File: src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs [hunk 21]
```diff
@@ -1259,14 +1259,14 @@ async Task StartProcessingInvocationMessages(ChannelReader<InvocationMessage> in
...
-            return _state.CurrentConnectionStateUnsynchronized.RunTimerActions();
+            return _state.CurrentConnectionStateUnsynchronized!.RunTimerActions();
         }
 
         // Internal for testing
         internal void OnServerTimeout()
         {
             // Don't bother acquiring the connection lock. This is only called from tests.
-            _state.CurrentConnectionStateUnsynchronized.OnServerTimeout();
+            _state.CurrentConnectionStateUnsynchronized!.OnServerTimeout();
```
Comment (halter73) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:1269]: Could this result in a NullReferenceException? Given that the caller acquires the connection lock after calling OnServerTimeout, it sure looks like it could.

https://github.com/dotnet/aspnetcore/blob/5c0693f9418788e59a5d70dab9536719a84aff00/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1850-L1857

Any method that references CurrentConnectionStateUnsynchronized without locking because it assumed the caller did so on it's behalf should have `Unsynchronized` in its name and probably call `_state.AssertInConnectionLock()`.

Comment (halter73) [reply src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:1269]: Nvm. The comment was right about it being only called from tests. There are multiple OnServerTimeout() methods in the same file.

File: src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs [hunk 22]
```diff
@@ -2012,10 +2012,10 @@ public async Task<ConnectionState> WaitForActiveConnectionAsync(string methodNam
                 return CurrentConnectionStateUnsynchronized;
             }
 
-            public void ReleaseConnectionLock([CallerMemberName] string memberName = null,
-                [CallerFilePath] string filePath = null, [CallerLineNumber] int lineNumber = 0)
+            public void ReleaseConnectionLock([CallerMemberName] string? memberName = null,
+                [CallerFilePath] string? filePath = null, [CallerLineNumber] int lineNumber = 0)
             {
-                Log.ReleasingConnectionLock(_logger, memberName, filePath, lineNumber);
+                Log.ReleasingConnectionLock(_logger, memberName!, filePath!, lineNumber);
```
Comment (halter73) [inline src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:2018]: It might better to just make these `string?` in `LoggerMessage.Define` to avoid `!` fatigue (where `!` is so common we stop paying much attention to them).

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs (hunk 9 above)
Comment (halter73) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:79]: I really think that people should be able to rely on `ConnectionContext.ConnectionId` being non-null. I'm thinking this should just throw if someone tries to access this property before `StartAsync()` completes.

This implementation of `ConnectionContext.ConnectionId` is already a bit odd in that its setter throws, so I don't think throwing from the getter when the connection hasn't started is a big deal.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs [hunk 23]
```diff
@@ -669,11 +670,11 @@ private static bool IsWebSocketsSupported()
 
         private async Task<NegotiationResponse> GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
         {
-            var negotiationResponse = await NegotiateAsync(uri, _httpClient, _logger, cancellationToken);
+            var negotiationResponse = await NegotiateAsync(uri, _httpClient!, _logger, cancellationToken);
             // If the negotiationVersion is greater than zero then we know that the negotiation response contains a
             // connectionToken that will be required to conenct. Otherwise we just set the connectionId and the
             // connectionToken on the client to the same value.
-            _connectionId = negotiationResponse.ConnectionId;
+            _connectionId = negotiationResponse.ConnectionId!;
```
Comment (halter73) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:677]: Would it be better to throw if there's no ConnectionId in the negotiate response?

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs [hunk 24]
```diff
@@ -100,7 +99,7 @@ public CookieContainer Cookies
         /// <summary>
         /// Gets or sets the URL used to send HTTP requests.
         /// </summary>
-        public Uri Url { get; set; }
+        public Uri Url { get; set; } = default!;
```
Comment (halter73) [inline src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]:
```csharp


var httpConnectionOptions = new HttpConnectionOptions();
var urlString = httpConnectionOptions.Url.ToString();
```

The above throws, right? If so, I think this should be marked nullable. I might feel differently if it was super common for developer to call the HttpConnectionOptions.Url getter and in practice it was always set, but expect most developers only use the setter.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs (hunk 23 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:677]: It already does in `NegotiateProtocol.ParseResponse`
https://github.com/dotnet/aspnetcore/blob/65bcc540fb7ad86124128b123ea4aa52e8c6dd9c/src/SignalR/common/Http.Connections.Common/src/NegotiateProtocol.cs#L227

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs (hunk 9 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs:79]: > people should be able to rely on `ConnectionContext.ConnectionId` being non-null

It's not just if you access it before starting, if you skip negotiation then this will be null as well.

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs (hunk 24 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: The reason I changed it was because of "`!` fatigue", everywhere we access this property internally it will be non-null
https://github.com/dotnet/aspnetcore/blob/e737b6e15b2dea82d91777645a224df498eec6ec/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionFactory.cs#L59-L61

Comment (halter73) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: I do appreciate trying to avoid "`!` fatigue" but I don't think that's enough of a reason to misrepresent the nullability of a public property. We could add an internal non-nullable property that mirrors Url and throws if it is null as a sanity check to avoid the fatigue.

Comment (JamesNK) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: We do this in places where something *could* be null, but for all typical usage it won't be.

e.g. https://github.com/dotnet/aspnetcore/blob/a08aa2dd318956d5b7295561d9423252f6071a52/src/Hosting/Abstractions/src/WebHostBuilderContext.cs

Comment (halter73) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: Right, that's why I said this initially:

> I might feel differently if it was super common for developer to call the HttpConnectionOptions.Url getter and in practice it was always set, but I expect most developers just call WithUrl() and never touch this property.

File: src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs (hunk 16 above)
Comment (BrennanConroy) [reply src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs:83]: This is an API change, however passing null would have thrown

File: src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs (hunk 24 above)
Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: > I expect most developers just call WithUrl() and never touch this property

Right, that makes it less of an issue if we lie with the API.

Comment (halter73) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: I would argue that if it's not a huge issue either way, we should default to no lying with the API.

Comment (BrennanConroy) [reply src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnectionOptions.cs:102]: I'll try out a private member so we can avoid using `!` everywhere in HttpConnection then.

**Review by halter73 — APPROVED** [review]

**Review by JunTaoLuo — APPROVED** [review]
