### PR TITLE
[Blazor] Allow cascading value subscribers to get added and removed during change notification

### LINKED ISSUE #53075: [Blazor WASM] Upgrading project to .NET 8 and breaks [Authorize] Attribute
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whom it may concerned,

My project is upgrading to Net 8 and using `@attribute [Authorize]`. when I logged out and called NotifyAuthenticationStateChanged method by using CustomAuthenticationStateProvider and then it threw an exception, please see below:

**Razor Page**
`@attribute [Authorize]`
...

**Code behind:**
-  ClaimsPrincipal anonymous = new(new ClaimsIdentity());
-  NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(anonymous)));
-  return Task.CompletedTask;

**Exception:**
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.<>c__DisplayClass10_0[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<NotifyChangedAsync>b__0()
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.NullDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.CascadingValueSource`1[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].NotifyChangedAsync()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].NotifyChangedAsync(Task`1 newValue)
   at Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions.AuthenticationStateCascadingValueSource.HandleAuthenticationStateChanged(Task`1 newAuthStateTask)
```

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

NET 8

### Anything else?

_No response_

### LINKED ISSUE #56741: CascadingValueSource crashes because subscriber are added asynchronously
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In cascading value source in the function [NotifyChangedAsync](https://source.dot.net/Microsoft.AspNetCore.Components/R/f0dc3cb82472303a.html)() the subscribers are enumerated using a foreach loop. The loop starts an asynchronous task for every subscriber to notify it. If you now have a subscriber like an AuthorizeView (for CascadingAuthenticationState which was added via services.AddCascadingAuthenticationState()) which hosts controls that again have AuthorizeViews or other controls that subscribe this CascadingValue as child content, the subscriber collection is changed asynchronously and you get the "Collection was modified; enumeration operation may not execute." exception. In my eyes the collections need to be copied before you enumerate so this code block gets safe. I will revert to the old school CascadingAuthenticationState control until this is fixed. This bug was added in .NET 8 and crashes/affects many projects as you will find googling. 

### Expected Behavior

Enumeration of the collection in a async/parallel/thread safe way and not getting exceptions if you nest controls that use the same cascading value.

### Steps To Reproduce

Use AddCascadingAuthenticationState and nest some AuthorizeViews.

### Exceptions (if any)

  Exception Message: Collection was modified; enumeration operation may not execute.
      Exception StackTrace:
            at bool System.Collections.Generic.List<T>+Enumerator.MoveNextRare()
            at Task Microsoft.AspNetCore.Components.CascadingValueSource<TValue>.NotifyChangedAsync()+() => { }
            at Task Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
            at Task Microsoft.AspNetCore.Components.CascadingValueSource<TValue>.NotifyChangedAsync()
            at void Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions+AuthenticationStateCascadingValueSource.HandleAuthenticationStateChanged(Task<AuthenticationState> newAuthStateTask)

### .NET Version

8.0.302

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# [Blazor] Allow cascading value subscribers to get added and removed during change notification

Updates cascading value change notification logic to operate on a copy of the subscriber list to avoid cases where the list could get mutated during enumeration.

Fixes #56741
Fixes #53075

### CODE REVIEW

File: src/Components/Components/src/CascadingValueSource.cs [hunk 1]
```diff
@@ -96,7 +96,8 @@ public Task NotifyChangedAsync()
             {
                 tasks.Add(dispatcher.InvokeAsync(() =>
                 {
-                    foreach (var subscriber in subscribers)
+                    Span<ComponentState> subscribersCopy = [.. subscribers];
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/CascadingValueSource.cs:99]: Does the use of `Span` here help in some way? I just did a small check with decompiling a console app and it looks like this is equivalent to:

```cs
Span<ComponentState> subscribersCopy = new Span<ComponentState>(list.ToArray());
```

In other words the code has the same allocation behavior as:

```cs
var subscribersCopy = list.ToArray();
```

I'm not aware of a nonallocating way to copy the list (since it's a reference type, `stackalloc` isn't on offer) besides using an array pool. Unless C# has added something new here that I missed. While array pooling would avoid the allocation, it's not necessarily a net gain in perf since it introduces cross-thread contention, and a single gen0 allocation is pretty low impact anyway.

So altogether, if you did the `Span` and `[.. subscribers]` as a matter of stylistic preference over `.ToArray()` that's fine. I'm only raising this point because many other devs might *think* modern C# is doing something magic with `Span` and `[.. subscribers]` but it appears not, and `.ToArray()` could avoid any such confusion.

Comment (javiercn) [reply src/Components/Components/src/CascadingValueSource.cs:99]: `ToArray()` sounds better here, IMO. More straightforward.

**Review by javiercn — APPROVED** [review]
Looks good to me.

File: src/Components/Components/src/CascadingValueSource.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/Components/Components/src/CascadingValueSource.cs:99]: Thanks for looking into that @SteveSandersonMS - I was going to do some analysis on that this morning (didn't get to it yesterday), but it looks like you beat me to it 🙂 

I'll switch to `.ToArray()`.

Comment (MackinnonBuck) [reply src/Components/Components/src/CascadingValueSource.cs]: Just did a quick check, and it looks like if the `Span<>` is known to be a fixed length then the compiler can store its elements on the stack (by generating a struct with `[InlineArray]`). This obviously doesn't apply to this case, but we can still manually create an `InlineArray` up to some fixed amount before falling back on `.ToArray()`.

I've updated the implementation to do this.
