### PR TITLE
Fix root '<PageTitle>' not working when a default, static '<title>' is provided

### LINKED ISSUE #35973: .NET 6, Preview 7: Setting title in WASM App
### Describe the bug
I tested the new feature in preview 7 that is supposed to let you set the title of a page dynamically. I tested this in a client-only WASM app, without a server. Unfortunately, I did not find a way to make this work. I suspect a bug, but cannot be certain that I am using this new feature correctly.

### To Reproduce
Repo: https://repos.tsommer.org/thorsten/BugWASMTitle

As you can see in [line 12 of `Program.cs`](https://repos.tsommer.org/thorsten/BugWASMTitle/src/branch/main/BlazorApp/Program.cs#L12), I enabled the `HeadOutlet` option, as mentioned in [your blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/#modify-html-head-content-from-blazor-components).

At the [`index.html`, line 7,](https://repos.tsommer.org/thorsten/BugWASMTitle/src/branch/main/BlazorApp/wwwroot/index.html#L7) I set the title to "Loading...". Your blog post does not mentioned this. I assumed the title tag is necessary in order to get a valid HTML document in the first place.

Finally, I try to set the title out [of the `MainLayout.razor`, line 3,](https://repos.tsommer.org/thorsten/BugWASMTitle/src/branch/main/BlazorApp/Shared/MainLayout.razor#L3) to "Another title". When I start the app, the title never changes and stays at "Loading..."

Is this might related to issue https://github.com/dotnet/aspnetcore/issues/35363?

### Exceptions
No exceptions.

### Further technical details
- ASP.NET Core 6.0, Preview 7
- JetBrains Rider 2021.2.1 macOS ARM64

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.5
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### PR DESCRIPTION
**Pull request by MackinnonBuck**
**Fix root `<PageTitle>` not working when a default, static `<title>` is provided**
There was an issue in which the root `<PageTitle>`, if rendered just after the application started, would not change the title of the page if a static `<title>` was provided in `index.html`. This PR fixes the issue.

**PR Description**
The problem arose because `HeadOutlet` wouldn't render the default title until it was determined from the statically-rendered title. This gave other `<PageTitle>` components the opportunity to render first, incorrectly serving as the default page title. When the _true_ default title finally rendered, it took priority over the developer-provided `<PageTitle>` (which was rendered first), making it appear to have no effect.

I've added a new `SectionContent` parameter, `IsDefaultContent`. When `true`, the registered section content will take lower priority than all other existing content. This allows the `HeadOutlet` to ensure its own `SectionContent` for the default title will have the lowest priority.

An alternative I considered was to always render the `SectionContent` for the default title, but only render the `<title>` element when the default title is actually determined. This sometimes works, but it breaks in cases like prerendering because `<PageTitle>` elements in the "app" root component still get rendered first.

Fixes #35973

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

File: src/Components/Components/src/Sections/SectionContent.cs [hunk 1]
```diff
@@ -12,11 +12,17 @@ internal class SectionContent : ISectionContentProvider, IComponent, IDisposable
...
 
         /// <summary>
-        /// Gets or sets the name that determines which <see cref="SectionOutlet"/> instances will render
+        /// Gets or sets the name that determines which <see cref="SectionOutlet"/> instance will render
         /// the content of this instance.
         /// </summary>
         [Parameter] public string Name { get; set; } = default!;
 
+        /// <summary>
+        /// Gets or sets whether this component should provide the default content for the target
```
Comment (pranavkm) [inline src/Components/Components/src/Sections/SectionContent.cs:21]: Not that I mind this change - but could we this is always true (given that there's only one thing that provides it today)?

Comment (MackinnonBuck) [reply src/Components/Components/src/Sections/SectionContent.cs:21]: `SectionContent` is also used in `PageTitle`: https://github.com/dotnet/aspnetcore/blob/cfc5aff291178c05f297ea7169aad35340a7a5f8/src/Components/Web/src/Head/PageTitle.cs#L23

It doesn't specify `IsDefaultContent` because it's `false` for every case other than the default title, which is rendered by `HeadOutlet`.

Am I understanding the suggestion correctly?
