### PR TITLE
Resolve relative JSON schema references in root schema

### LINKED ISSUE #61194: Empty OpenApi schema is generated for type referenced multiple times as generic argument
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

For `T` referenced from multiple `List<T>` properties, the generated schema for `T` is empty.
```csharp
class Config
{
    public List<Item> Items1 { get; set; }
    public List<Item> Items2 { get; set; }
}
class Item
{
    public string Value { get; set; }
}
```
`Item` gets an empty schema.

### Expected Behavior

The schema should look like this:

```json
      "Config": {
        "type": "object",
        "properties": {
          "items1": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Item"
            }
          }
        }
      },
      "Item": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        }
```

### Steps To Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-preview.4.25176.5" />
  </ItemGroup>

</Project>
```
```csharp
using System.Collections.Generic;
using Microsoft.AspNetCore.OpenApi;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenApi();
var app = builder.Build();

app.MapGet("/get", () => new Config
{
    Items1 = new()
});

app.MapOpenApi("/");
app.Run();

class Config
{
    public List<Item> Items1 { get; set; }
    public List<Item> Items2 { get; set; }
}
class Item
{
    public string Value { get; set; }
}
```

The generated schema has:
```json
      "Config": {
        "type": "object",
        "properties": {
          "items1": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Item"
            }
          },
          "items2": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Item"
            }
          }
        }
      },
      "Item": { }
```

Removing one of the `List<Item>` properties fixes it.

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/61194.

This PR fixes a host of issues with generic types or types that appear multiple times in the type hierarchy by fully resolving the relative references in schemas that are generated by JsonSchemaExporter to inlined schemas to avoid generating invalid refs.

 Before (Unresolved References)
```
  {
    "type": "object",
    "properties": {
      "parent": {
        "$ref": "#/properties/parent/properties/tags"
      },
      "items": {
        "type": "array",
        "items": {
          "$ref": "#/properties/items/items"
        }
      }
    }
  }
```

 After (Resolved References)

```
  {
    "type": "object",
    "properties": {
      "parent": {
        "type": "object",
        "properties": {
          "tags": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "nullable": true
            },
            "lang": {
              "type": "string",
              "nullable": true
            }
          }
        }
      }
    }
  }
```

### CODE REVIEW

**Comment by martincostello** [comment]
If you pull #63095 into this branch, do the two failing tests now pass?

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 1]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+        var schema = JsonSchemaExporter.GetJsonSchemaAsNode(_jsonSerializerOptions, key.Type, _configuration);
+        return ResolveReferences(schema, schema);
+    }
+
+    private static JsonNode ResolveReferences(JsonNode node, JsonNode rootSchema)
+    {
+        return ResolveReferencesRecursive(node, rootSchema, []);
+    }
+
+    private static JsonNode ResolveReferencesRecursive(JsonNode node, JsonNode rootSchema, HashSet<string> visitedRefs)
```
Comment (martincostello) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]: Does this need something to stop an infinite loop happening? IIRC, there's other bits of the code that do recursion that do something like _"this is the 64th time I'm calling this, so that's too much - stop"_.

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 2]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+        {
+            throw new InvalidOperationException("Reference path cannot be null or empty.");
+        }
+
+        if (!refPath.StartsWith(OpenApiConstants.RefPrefix, StringComparison.Ordinal))
+        {
+            throw new InvalidOperationException($"Only fragment references (starting with '{OpenApiConstants.RefPrefix}') are supported. Found: {refPath}");
+        }
+
+        var path = refPath.TrimStart('#').TrimStart('/');
```
Comment (martincostello) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]: Could use the [`TrimStart(params ReadOnlySpan<char>)`](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs,2410) overload?

```suggestion
        var path = refPath.TrimStart('#', '/');
```

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 3]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+            var segment = segments[i];
+            if (current is JsonObject currentObject)
+            {
+                if (currentObject.TryGetPropertyValue(segment, out var nextNode) && nextNode != null)
+                {
+                    current = nextNode;
+                }
+                else
+                {
+                    var partialPath = string.Join("/", segments.Take(i + 1));
```
Comment (martincostello) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]:
```suggestion
                    var partialPath = string.Join('/', segments.Take(i + 1));
```

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 4]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+                    throw new InvalidOperationException($"Failed to resolve reference '{refPath}': path segment '{segment}' not found at '#{partialPath}'");
+                }
+            }
+            else
+            {
+                var partialPath = string.Join("/", segments.Take(i));
```
Comment (martincostello) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]:
```suggestion
                var partialPath = string.Join('/', segments.Take(i));
```

**Comment by captainsafia** [comment]
> If you pull #63095 into this branch, do the two failing tests now pass?

OpenApiDocumentReferencesAreValid passes. OpenApiDocumentIsValid fails because of the path issue that you're fixing in that PR (thanks!)

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 5]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+                visitedRefs.Add(refString);
+
+                try
+                {
+                    // Resolve the reference path to the actual schema content
+                    // to avoid relative references
+                    var resolvedNode = ResolveReference(refString, rootSchema);
+                    if (resolvedNode != null)
+                    {
+                        return resolvedNode.DeepClone();
```
[the remark this answers is not in the document]
Comment (captainsafia) [reply src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:486]: Yes, but unfortunately, we need to deep-clone here and elsewhere since we are copying JsonNode's and STJ enforces a one-parent rule on nodes. If we set without cloning, we'll get a bunch of `System.InvalidOperationException : The node already has a parent.` exceptions.

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs (hunk 1 above)
Comment (captainsafia) [reply src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]: For handling recursion, we rely on things being caught by JsonSchemaExporter before the schema is returned to us. Tests like `ThrowsForOverlyNestedSchemas` and `SupportsDeeplyNestedSchemaWithConfiguredMaxDepth` cover this. I don't think there's any _new_ recursion issues that get introduced here and the logic for tracking visited refs is probably sufficient for this scenario?

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 6]
```diff
@@ -457,5 +457,138 @@ private async Task InnerApplySchemaTransformersAsync(IOpenApiSchema inputSchema,
...
+                refNode is JsonValue refValue &&
+                refValue.TryGetValue<string>(out var refString) &&
+                refString.StartsWith(OpenApiConstants.RefPrefix, StringComparison.Ordinal))
+            {
+                if (visitedRefs.Contains(refString))
+                {
+                    return node;
+                }
+
+                visitedRefs.Add(refString);
```
Comment (BrennanConroy) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]: This set doesn't seem to actually do anything? This is the only place you add to it and the `refString` is removed at line 504 without ever having used the set again.

Comment (captainsafia) [reply src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs]: Ah yeah, we don't need this since STJ handles recursive references in its own implementation.

**Review by BrennanConroy — APPROVED** [review]
