### PR TITLE
[Blazor] [Fixes #11847] Renderer.DispatchEventAsync throws null reference exception if event handler throws synchronously

### LINKED ISSUE #11847: Renderer.DispatchEventAsync throws null reference exception if event handler throws synchronously
From https://github.com/aspnet/AspNetCore/issues/11791

If an event handler throws synchronously, there's a bug in Renderer.DispatchEventAsync. The `task` variable is left with a `null` value, which then throws a nullref exception in `GetErrorHandledTask`.

The correct behavior would be to still treat this as a circuit-terminating exception, but report the real exception and don't have the nullref. Currently I believe it logs both the real exception *and* the subsequent nullref.

### PR DESCRIPTION
**Pull request by javiercn**
* Returns after handling the exception.
* Adds a unit test and an E2E test to validate expected behavior.

### CODE REVIEW

File: src/Components/Components/src/Rendering/Renderer.cs [hunk 1]
```diff
@@ -235,6 +235,7 @@ public virtual Task DispatchEventAsync(ulong eventHandlerId, EventFieldInfo fiel
             catch (Exception e)
             {
                 HandleException(e);
+                return Task.CompletedTask;
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/Rendering/Renderer.cs]: This is a bit of a nitpick, but I'd be tempted to replace lines 237 and 238 with:

```cs
// Treat synchronous exceptions the same as async ones
task = Task.FromException(ex);
```

... and then continue. It means we have fewer code paths to reason about. I think the behavior would be the same.

Do you have any view on this? Totally fine to do it whichever way you prefer, of course!

Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/Renderer.cs]: I know my version would allocate more. I'm not super worried about that since this is an error path anyway, but it's up to you.

File: src/Components/Components/test/RendererTest.cs [hunk 2]
```diff
@@ -486,6 +486,40 @@ public async Task CanDispatchEventsToTopLevelComponents()
...
+
+            // Act/Assert: Event can be fired
+            var eventArgs = new UIEventArgs();
+            var renderTask = renderer.DispatchEventAsync(eventHandlerId, eventArgs);
+            Assert.True(renderTask.IsCompletedSuccessfully);
+
+            var exception = Assert.Single(renderer.HandledExceptions);
+            Assert.Equal("Error", exception.Message);
+
+            await renderTask; // Does not throw
```
Comment (SteveSandersonMS) [inline src/Components/Components/test/RendererTest.cs]: Seems like this duplicates L515

File: src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs [hunk 3]
```diff
@@ -4,6 +4,7 @@
 using System;
 using System.Collections.Generic;
 using System.Linq;
+using System.Net;
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs]: Is this needed? I suspect not but can't easily verify from the diff alone :)

**Review by SteveSandersonMS — APPROVED** [review]
Great!

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/Renderer.cs]: I'm curious, what's the advantage other than it goes through the same code path. I feel this is more straightforward, but I want to know if there's something I'm missing.

File: src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs]: Probably not, thanks to visual studio 😄 doing its thing.
