### PR TITLE
Run entire E2E test with consistent enhanced navigation suppression setting

### LINKED ISSUE #60875: Quarantine EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(enableStreaming: True, useEnhancedNavigation: True, programmaticNavigation: False)

## Error Message

```text
System.Exception : Failed to execute script after 3 retries.
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.Components.E2ETest.WebDriverExtensions.GetElementPositionWithRetry(IWebDriver browser, String elementId, Int32 retryCount, Int32 delayBetweenRetriesMs) in /home/vsts/work/1/s/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs:line 69
at Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(Boolean enableStreaming, Boolean useEnhancedNavigation, Boolean programmaticNavigation) in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs:line 694
at InvokeStub_EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
</details>

## Logs

<details>

```text

```
</details>

## Build

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=975768&view=results

### PR DESCRIPTION
**Pull request by ilonatommy**
# Suppress enhanced navigation once per test

Enhanced navigation suppression was per page, after navigating away we were falling back to enhanced navigation, regardless of the test settings. It's because we were treating the storage as temporary measure where we were setting the suppression flag and instantly removing it after reading it in blazor start function. For tests that never navigated away (did not re-trigger blazor boot function) it was enough but for other ones, not.

## Description

- The enhanced navigation suppression flag is saved in the storage for the entire test runtime.
- To avoid usage of the flag by multiple tests, we always try to clean the session storage from it on disposal.
- Consecutive navigations in the test will run with same settings as the first page load.
- This PR fixed order of actions: we should navigate to a page only after the suppression method got called.
- It also enabled tests that got disabled because of issues with enhanced navigation suppression.
- Session storage has to be available if we want to suppress enhanced navigation. If a developer wrote a test that is not navigating to any page and chose to skip the automatic navigation in `EnhancedNavigationTestUtil.SuppressEnhancedNavigation`, they will get an exception like:
```
Failed to read the 'sessionStorage' property from 'Window': Access 
```
`SuppressEnhancedNavigation` appends to the exception message an instruction how to fix this situation.
- To be able to clean the `sessionStorage`, we have to have access to it. It's accessible only on loaded pages, so we chose the index page as the secure place for conducting the cleanup. To assure we're at the correct location we're checking for "session-storage-anchor" tag, adding it to test projects.
- This PR is changing expectations of test apps that got broken during development because they were not looking for a specific html element ID but for an element type (h1/p) etc. The selectors got more precise.
- Executing JS script to find the location of an element was infrequently failing and was blocked by the same quarantine issue. This PR changes the location finding method to rely less on JS, more on selenium tooling.

Fixes #60875

### CODE REVIEW

File: src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs [hunk 1]
```diff
@@ -31,6 +32,12 @@ public void Navigate(string relativeUrl)
         Browser.Navigate(_serverFixture.RootUri, relativeUrl);
     }
 
+    public override async Task DisposeAsync()
+    {
+        EnhancedNavigationTestUtil.CleanEnhancedNavigationSuppression(this);
```
[the remark this answers is not in the document]
Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: I want it to throw, it should signal to the test developer that maybe they should not pass `skipNavigation=true`.

File: src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs [hunk 2]
```diff
@@ -40,7 +40,7 @@ protected override void InitializeAsyncCore()
     {
         Navigate(ServerPathBase);
         Browser.MountTestComponent<GracefulTermination>();
-        Browser.Equal("Graceful Termination", () => Browser.Exists(By.TagName("h1")).Text);
+        Browser.Equal("Graceful Termination", () => Browser.Exists(By.CssSelector("app h1")).Text);
```
Comment (ilonatommy) [inline src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs:43]: This is still the same element, we just select it more precisely, not to confuse it with the h1 that is not embedded in `<app>`.

File: src/Components/test/testassets/BasicTestApp/Index.razor [hunk 3]
```diff
@@ -1,6 +1,9 @@
 ﻿@using Microsoft.AspNetCore.Components.Rendering
 @using System.Web
 @inject NavigationManager NavigationManager
+
+<h1>Hello</h1>
```
Comment (ilonatommy) [inline src/Components/test/testassets/BasicTestApp/Index.razor]: Used in the enhanced navigation suppression method to check if session storage has conditions to get cleaned properly (page got loaded).

**Comment by ilonatommy** [comment]
One more thing to fix - the less frequent failure that happens when using `GetElementPositionWithRetry`:
```
 Failed Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(enableStreaming: True, useEnhancedNavigation: True, programmaticNavigation: True) [4 s]
  Error Message:
   System.Exception : Failed to execute script to get position for element 'do-programmatic-navigation' after 3 retries. Debug log: Attempt 1: JavaScriptException - javascript error: Cannot read properties of null (reading 'getBoundingClientRect')
  (Session info: chrome=139.0.7258.66). Attempt 2: JavaScriptException - javascript error: Cannot read properties of null (reading 'getBoundingClientRect')
  (Session info: chrome=139.0.7258.66). Attempt 3: JavaScriptException - javascript error: Cannot read properties of null (reading 'getBoundingClientRect')
  (Session info: chrome=139.0.7258.66). 
  Stack Trace:
     at Microsoft.AspNetCore.Components.E2ETest.WebDriverExtensions.GetElementPositionWithRetry(IWebDriver browser, String elementId, Int32 retryCount, Int32 delayBetweenRetriesMs) in /home/vsts/work/1/s/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs:line 74
   at Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(Boolean enableStreaming, Boolean useEnhancedNavigation, Boolean programmaticNavigation) in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs:line 707
   at InvokeStub_EnhancedNavigationTest.EnhancedNavigationScrollBehavesSameAsBrowserOnNavigation(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

edit:
✅Done

File: src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs (hunk 1 above)
Comment (oroztocil) [inline src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: Naive question: Is there a world where a test crashes and the enhanced navigation suppression flag is not cleaned up and that has a flaky effect on other tests? Or is that avoided by each test appending different IDs to the flag in the session storage?

Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: That depends on the type of failure. Disposal method should run after each test, regardless of the result.

In case the failure was connected with browser getting disconnected/crashed etc, then we loose the connection to the old instance, that is, the old session storage values are gone, we don't need to worry about them. The following tests should have a fresh instance created by selenium (with a clean storage).

It's not really a matter of test id because we don't grant test id unless the test wants to suppress enhanced nav. So it's not true that each test has their ID, only suppressing tests have them. I was initially trying an approach of granting it for every test, in `InitializeAsync` but it resulted in problems with browser crashing on redirecting to the safe location to set the storage. Maybe I could reconsider that approach now, I did not take detailed notes what was the blocker there.

Comment (oroztocil) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: Thanks for the detailed explanation!

**Comment by ilonatommy** [comment]
I missed one test to be fixed:
```
 Failed Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.PrerenderingTest.CanUseJSInteropFromOnAfterRenderAsync [1 ms]
  Error Message:
   OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure: Collection was empty
   at Xunit.Assert.NotEmpty(IEnumerable collection) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 539
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass21_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/fbab61cc46724c0487172d8f671234b0.png'
Encountered browser errors
[2025-08-28T11:28:28Z] [Severe] chrome-error://chromewebdata/ - Failed to load resource: the server responded with a status of 404 ()Page content:
<head>
  <meta charset="utf-8">
  <meta name="color-scheme" content="light dark">
  <meta name="theme-color" content="#fff">
  <meta name="viewport" content="width=device-width, initial-scale=1.0,
                                 maximum-scale=1.0, user-scalable=no">
  <title>127.0.0.1</title>
  <style>/* Copyright 2017 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file. */

a {
  color: var(--link-color);
}
```

but there's a bigger problem: if we grant ID to each test (with navigation to origin at the test start etc, the tests run time prolongs significantly. It's `Duration: 1 h 40 m` with the corrected approach, while granting ID only to tests with supression was `Duration: 48 m 46 s` and on other PRs with not related changes, e.g. [log](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131188&view=logs&j=fe94c0c9-bb8c-5d6f-3b51-887173cc2f5c&t=b4bd3469-f776-5941-b623-568498d38bde) it's `Duration: 46 m 30 s`.

From this reason, I will revert to the previous approach, instead of fixing the last failing test.

File: src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs (hunk 1 above)
Comment (javiercn) [inline src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: Isn't there a way to do this only on tests relying on Enhanced navigation? This essentially adds a tax to every new test we add, when most of them don't use enhanced navigation

File: src/Components/test/testassets/BasicTestApp/Index.razor [hunk 4]
```diff
@@ -1,7 +1,9 @@
 ﻿@using Microsoft.AspNetCore.Components.Rendering
 @using System.Web
 @inject NavigationManager NavigationManager
+
 <div id="test-selector">
+    <h1 style="margin: 0; padding: 0; line-height: 1;">Hello</h1>
```
Comment (javiercn) [inline src/Components/test/testassets/BasicTestApp/Index.razor]: What is this for?

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs [hunk 5]
```diff
@@ -20,16 +20,87 @@ public static void SuppressEnhancedNavigation<TServerFixture>(ServerTestBase<TSe
...
+
+    private static void NavigateToOrigin<TServerFixture>(ServerTestBase<TServerFixture> fixture)
+        where TServerFixture : ServerFixture
+    {
+        // Navigate to the test origin to ensure the browser is on the correct state to access sessionStorage
+        fixture.Navigate($"{fixture.ServerPathBase}/");
+        fixture.Browser.Equal("Hello", () => fixture.Browser.Exists(By.TagName("h1")).Text);
+    }
+
+    private static string GrantTestId(IWebDriver browser)
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs]: `Grant` is somewhat and odd choice. Maybe just `Create/Generate/CreateAndSet`

File: src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs [hunk 6]
```diff
@@ -45,27 +41,33 @@ public static void WaitForElementToBeVisible(this IWebDriver browser, By by, int
...
-                }
+                browser.WaitForElementToBeVisible(By.Id(elementId));
+                var element = browser.FindElement(By.Id(elementId));
+                var elementLocation = element.Location.Y;
+
+                // Get scroll position using JavaScript (this is less likely to fail than element positioning)
+                var jsExecutor = (IJavaScriptExecutor)browser;
+                var scrollY = (long)jsExecutor.ExecuteScript("return window.scrollY");
+
+                return elementLocation + scrollY;
```
Comment (javiercn) [inline src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs]: Is this correct?
```
element.Location.Y (in Selenium) already gives you the Y position of the element relative to the top of the document, not the viewport.
window.scrollY is the number of pixels the document has been scrolled vertically.
Adding them together double-counts the scroll, resulting in an incorrect value.
```

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs [hunk 7]
```diff
@@ -20,16 +20,87 @@ public static void SuppressEnhancedNavigation<TServerFixture>(ServerTestBase<TSe
...
+            return;
+        }
+    }
+
+    private static void NavigateToOrigin<TServerFixture>(ServerTestBase<TServerFixture> fixture)
+        where TServerFixture : ServerFixture
+    {
+        // Navigate to the test origin to ensure the browser is on the correct state to access sessionStorage
+        fixture.Navigate($"{fixture.ServerPathBase}/");
+        fixture.Browser.Equal("Hello", () => fixture.Browser.Exists(By.TagName("h1")).Text);
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs]: Ah, now I see what the `Hello` bit was for. Use an `id` to locate the element and make the id name meaningful?

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs [hunk 8]
```diff
@@ -20,16 +20,87 @@ public static void SuppressEnhancedNavigation<TServerFixture>(ServerTestBase<TSe
...
+                testId = GrantTestId(browser);
+            }
+
+            ((IJavaScriptExecutor)browser).ExecuteScript($"sessionStorage.setItem('suppress-enhanced-navigation-{testId}', 'true')");
+
+            var suppressEnhancedNavigation = ((IJavaScriptExecutor)browser).ExecuteScript($"return sessionStorage.getItem('suppress-enhanced-navigation-{testId}');");
+            Assert.True(suppressEnhancedNavigation is not null && (string)suppressEnhancedNavigation == "true",
+                "Expected 'suppress-enhanced-navigation' to be set in sessionStorage.");
         }
     }
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:44]: If instead of grabbing the test id locally and storing it on session storage you create one and return it from this method (maybe you store it in a local variable or a field in the class) then you shouldn't need to set it within session storage.

You can pass the `test-id` to any method that needs to use it to clear things up later. It's good that we are "randomizing" the `suppress-enhanced-navigation-` bit, but we still run the risk of polluting the state if we rely on a well-known test-id key.

The other thing is that if we always use an "ephemeral" id that we only store in a field/local variable then we don't ever need to do cleanup.

**Review by javiercn — COMMENTED** [review]
The general approach looks good. I have some thoughts on things we can potentially tweak.

File: src/Components/test/testassets/BasicTestApp/Index.razor (hunk 4 above)
Comment (ilonatommy) [reply src/Components/test/testassets/BasicTestApp/Index.razor]: Leftover from the anchor, should be removed, good catch.
No, this is not a leftover, it's "reverted too much".

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs (hunk 7 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs]: Ugh, reverting the changes reverted the id-based approach as well. Yes, that should be doing `fixture.Browser.Exists(By.Id("session-storage-anchor"));`

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs (hunk 8 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:44]: We are setting it in the storage, so that the apps that are run by selenium can access it, so here:
`src/Components/test/testassets/Components.TestServer/RazorComponents/App.razor`
and here:
`src/Components/test/testassets/Components.TestServer/RazorComponents/Root.razor`.
This access has to happen before we spin up blazor, I don't see a way how to replace it with a value in a class that both: E2E and these startup files have access to.

The "ephemerallity" of the test id is not guaranteed - imagine a scenario where we run:
- test with enhanced nav suppression - we're granting test ID, it runs without enhanced nav, but then the cleanup somehow fails without crashing the existing browser instance but also without cleaning the storage;
- after that a test that wants enhanced nav to be on runs - storage is still populated with old values and we're not granting new ID for tests that run without suppression (doing it for each prolonged running ~2 times), so this test things that it should start blazor with 
```
Blazor.start({
                ssr: {
                    disableDomPreservation: true,
                },
```
and, logically fails the expectations contained in it.

From what I know, we are sharing browser instance across the fixture. In such a setup cleaning is important.

File: src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs (hunk 6 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs]: True, the docs in the code:
```
    // Summary:
    //     Gets a System.Drawing.Point object containing the coordinates of the upper-left
    //     corner of this element relative to the upper-left corner of the page.
    //
    // Exceptions:
    //   T:OpenQA.Selenium.StaleElementReferenceException:
    //     Thrown when the target element is no longer valid in the document DOM.
    Point Location { get; }
```

Changing., that's even better, it removes all JS from this method.

File: src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs (hunk 1 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: We can add this cleanup only for those existing tests, right.

But who will guarantee that new tests that will be added will have this cleanup added by the developer? How can we detect they did not clean and throw, if we won't check the storage contents?

Not cleaning does not have to fail at once, it depends on the test order - if all tests in the fixture that suppress enhanced nav would run last, there will be no failures, the developer will not notice that they forgot to clean.

Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: A bit awkward idea: 
because we run sequentially, `EnhancedNavigationTestUtil` can have a flag set only if we wrote anything to the storage and we could first check that flag, before trying to access the storage. So we do run cleanup for everyone, just cut it short in case there was no suppression done.

Comment (ilonatommy) [reply src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:37]: After rethinking, it's not as awkward as I thought, applying it.

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs (hunk 8 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:44]: Or maybe you meant "JS variable"? We could try communicating to the browser that enhanced nav is suppressed by setting e.g. `window._enhancedNavigationSuppressed` and then reading it in the test application. However it has a big minus: it's getting cleaned on full page load and we want to keep the same settings through the test, regardless of the actions we perform.

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs [hunk 9]
```diff
@@ -20,16 +22,76 @@ public static void SuppressEnhancedNavigation<TServerFixture>(ServerTestBase<TSe
...
+            // Browser session is no longer valid (e.g., browser was closed)
+            // Session storage is automatically cleared when browser closes, so cleanup is already done
+            // This is expected in some tests, so we silently return
+            return;
+        }
+        finally
+        {
+            _isSuppressed = false;
+        }
+    }
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:85]: Rather than doing this. Can we check `Browser.SessionId == null` and just return? Another option might be `Browser.WindowHandles`

Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:85]: We can try. This was added because we have failures in tests that close the browser intentionally, it should be easy to check if `Browser.SessionId == null` works for them.

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs [hunk 10]
```diff
@@ -20,16 +22,76 @@ public static void SuppressEnhancedNavigation<TServerFixture>(ServerTestBase<TSe
...
+
+    private static void NavigateToOrigin<TServerFixture>(ServerTestBase<TServerFixture> fixture)
+        where TServerFixture : ServerFixture
+    {
+        // Navigate to the test origin to ensure the browser is on the correct state to access sessionStorage
+        fixture.Navigate($"{fixture.ServerPathBase}/");
+        fixture.Browser.Exists(By.Id("session-storage-anchor"));
```
Comment (javiercn) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:92]: Can we find a better name for the id (since its used across multiple contexts). I don't think it should have `anchor` on it, since that has a very specific meaning in our context (an `a` tag).

Maybe something like `session-storage-marker` or something like that rather than anchor.

**Review by javiercn — APPROVED** [review]
Couple of comments but looks great besides that!

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs (hunk 10 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:92]: I'm fine with marker, I did not like anchor either but could not come up with anything better. Thanks!

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs (hunk 9 above)
Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTestUtil.cs:85]: `Browser.SessionId` does not exist. We can cast browser to driver instance but then..the session id exists even when there are no windows handlers and the browser is closed.
Referencing `WindowsHandles` or `CurrentWindowHandle` when the session is out creates the exact exception that we were catching.
I don't see a good replacement for the exception flow.
