### PR TITLE
Move ComponentHubReliability tests to unit and E2E tests

### LINKED ISSUE #19666: ComponentHubReliabilityTest are unreliable
```
Microsoft.AspNetCore.SignalR.HubException : Unable to complete handshake with the server due to an error: Handshake was canceled.
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1057
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 433
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 441
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 255
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /_/src/SignalR/common/Shared/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 232
   at Ignitor.BlazorClient.ConnectAsync(Uri uri, Boolean connectAutomatically) in /_/src/Components/Ignitor/src/BlazorClient.cs:line 359
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ComponentHubReliabilityTest.ComponentLifecycleMethodThrowsExceptionTerminatesTheCircuit(String id) in /_/src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs:line 295
--- End of stack trace from previous location -
```

### PR DESCRIPTION
**Pull request by captainsafia**
Fixes https://github.com/dotnet/aspnetcore/issues/19666

* Make `CircuitFactory.CreateCircuitHostAsync` virtual to allow mocking in unit tests. This method does the bulk of the work around initializing a circuit host and setting up the dependent services. 
* Make `ComponentHub` method unsealed and make certain methods virtual. This is done to make it easier to mock out parts of the API that are responsible for setting up connections.
* Move some tests into a separate E2E test project and move others to the new `ComponentHubTest` unit tests.

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

File: src/Components/Server/src/ComponentHub.cs [hunk 1]
```diff
@@ -275,12 +277,27 @@ private async ValueTask<CircuitHost> GetActiveCircuitAsync([CallerMemberName] st
             return circuitHost;
         }
 
-        private CircuitHost GetCircuit()
+        // We wrap the `TryDeserializeComponentDescriptorCollection` call in a virtual method here
+        // to support mocking in tests. SignalR does not support having a public method with an out
+        // parameter defined on the hub so we return the desired values in a tuple.
+        public virtual (bool, List<ComponentDescriptor>)  DeserializeComponentDescriptor(string serializedComponentRecords)
```
Comment (BrennanConroy) [inline src/Components/Server/src/ComponentHub.cs:283]: public methods on hubs are public api that clients can call. I don't think you want clients calling these methods, so it should be internal with IVT for tests.

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+using Microsoft.Extensions.DependencyInjection;
+using Microsoft.Extensions.Logging;
+using Microsoft.Extensions.Options;
+using Microsoft.JSInterop;
+
+namespace Microsoft.AspNetCore.Components.Server.Circuits
+{
+    internal class CircuitHandleRegistry : ICircuitHandleRegistry
+    {
+        private Dictionary<object, CircuitHandle> _circuitHandles = new();
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:21]: Minor nitpick:

```suggestion
        private readonly Dictionary<object, CircuitHandle> _circuitHandles = new();
```

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+        public CircuitHandle GetCircuitHandle(object circuitKey)
+        {
+            if (_circuitHandles.ContainsKey(circuitKey))
+            {
+                return _circuitHandles[circuitKey];
+            }
+            return null;;
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:29]:
```suggestion

            return null;
```

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+{
+    internal class CircuitHandleRegistry : ICircuitHandleRegistry
+    {
+        private Dictionary<object, CircuitHandle> _circuitHandles = new();
+
+        public CircuitHandle GetCircuitHandle(object circuitKey)
+        {
+            if (_circuitHandles.ContainsKey(circuitKey))
+            {
+                return _circuitHandles[circuitKey];
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:27]: This is also a minor nitpick, but we're doing two dictionary lookups here where probably one would suffice. Could this logic use `TryGetValue` (or whatever it's called) instead?

File: src/Components/Server/src/Circuits/ICircuitFactory.cs [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+using Microsoft.Extensions.DependencyInjection;
+using Microsoft.Extensions.Logging;
+using Microsoft.Extensions.Options;
+using Microsoft.JSInterop;
+
+namespace Microsoft.AspNetCore.Components.Server.Circuits
+{
+    internal interface ICircuitFactory
+    {
+        public ValueTask<CircuitHost> CreateCircuitHostAsync(
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/ICircuitFactory.cs:21]:
```suggestion
        ValueTask<CircuitHost> CreateCircuitHostAsync(
```

File: src/Components/Server/src/Circuits/ICircuitHandleRegistry.cs [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+
+namespace Microsoft.AspNetCore.Components.Server.Circuits
+{
+    internal interface ICircuitHandleRegistry
+    {
+        public CircuitHandle GetCircuitHandle(object circuitKey);
+
+        public CircuitHost GetCircuit(object circuitKey);
+
+        public void SetCircuit(object circuitKey, CircuitHost circuitHost);
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/ICircuitHandleRegistry.cs:25]: TBH I didn't realise that `public` is now a valid modifier on interface members, but I see it now is :)

Since none of our other interface definitions use `public` like this, would it be preferable to remove those modifiers? Don't mind strongly.

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/ICircuitHandleRegistry.cs:25]: Also on `IServerComponentDeserializer`

File: src/Components/Server/src/ComponentHub.cs [hunk 7]
```diff
@@ -34,29 +35,32 @@ namespace Microsoft.AspNetCore.Components.Server
     // needs access to the circuit/application state to unblock the message loop. Using async in our
     // Hub methods allows us to ensure message delivery to the client before we abort the connection
     // in error cases.
-    internal sealed class ComponentHub : Hub
+    internal class ComponentHub : Hub
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/ComponentHub.cs:38]: Can this be resealed now?

File: src/Components/Server/src/ComponentHub.cs [hunk 8]
```diff
@@ -2,6 +2,7 @@
 // Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 
 using System;
+using System.Collections.Generic;
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/ComponentHub.cs:5]: Just checking this is still required after the refactoring.

File: src/Components/Server/test/Circuits/ComponentHubTest.cs [hunk 9]
```diff
@@ -0,0 +1,209 @@
...
+            }
+
+            public CircuitHost GetCircuit(object circuitKey)
+            {
+                if (circuitSet)
+                {
+                    var serviceScope = new Mock<IServiceScope>();
+                    var circuitHost = TestCircuitHost.Create(
+                        serviceScope: new AsyncServiceScope(serviceScope.Object));
+                    return circuitHost;
```
Comment (SteveSandersonMS) [inline src/Components/Server/test/Circuits/ComponentHubTest.cs:163]: I'm not as familiar with the flow of these tests as you are, but is there any value in validating that the `circuitKey` is correct? For example storing the value supplied on the `SetCircuit` call and using that to decide whether to return `null` or not from here.

No big deal.

File: src/Components/Server/test/Circuits/ComponentHubTest.cs [hunk 10]
```diff
@@ -0,0 +1,209 @@
...
+        private class TestCircuitFactory : ICircuitFactory
+        {
+            public TestCircuitFactory(
+            IServiceScopeFactory scopeFactory,
+            ILoggerFactory loggerFactory,
+            CircuitIdFactory circuitIdFactory,
+            IOptions<CircuitOptions> options) { }
+
+            // We override the default `CreateCircuitHostAsync` so we can mock around
+            // the work of initializing a host and all its service dependencies.
```
Comment (SteveSandersonMS) [inline src/Components/Server/test/Circuits/ComponentHubTest.cs:193]:
```suggestion
            // We override the default `CreateCircuitHostAsync` so we can mock around
            // the work of initializing a host and all its service dependencies.
```

I think the comment is obsolete now we're not overriding a virtual method.

File: src/Components/Server/test/Circuits/ComponentHubTest.cs [hunk 11]
```diff
@@ -0,0 +1,209 @@
...
+            public async ValueTask<CircuitHost> CreateCircuitHostAsync(
+                IReadOnlyList<ComponentDescriptor> components,
+                CircuitClientProxy client,
+                string baseUri,
+                string uri,
+                ClaimsPrincipal user,
+                IComponentApplicationStateStore store)
+            {
+                await Task.Delay(0);
```
Comment (SteveSandersonMS) [inline src/Components/Server/test/Circuits/ComponentHubTest.cs:202]: If this is still required, could you add a comment to clarify why? It raises alarms otherwise.

For example would it work to make this method not `async` and return `Task.FromResult(circuitHost)` instead?

**Review by SteveSandersonMS — APPROVED** [review]
This is great. Thanks very much for going through the process of making it more amenable to unit testing. I know that was extra steps but the end result tells a much clearer story about itself now.

File: src/Components/Server/test/Circuits/ComponentHubTest.cs (hunk 11 above)
Comment (captainsafia) [reply src/Components/Server/test/Circuits/ComponentHubTest.cs]: It's not needed. This was just me typing the fewest characters possible to make things go away in dev.

File: src/Components/Server/test/Circuits/ComponentHubTest.cs (hunk 9 above)
Comment (captainsafia) [reply src/Components/Server/test/Circuits/ComponentHubTest.cs:163]: For this particular case, I don't believe it provides a ton of value.

The circuit key is computed on a per-connection basis (so essentially on per circuit) so in real world scenarios it's not likely to be incorrect since there's only ever one value.

That and we don't really fully exercise the per-connection logic in this scenario. If there were issues with this codepath, they'd show up as failing server-side tests.

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+using Microsoft.AspNetCore.Components.Routing;
+using Microsoft.AspNetCore.DataProtection;
+using Microsoft.Extensions.DependencyInjection;
+using Microsoft.Extensions.Logging;
+using Microsoft.Extensions.Options;
+using Microsoft.JSInterop;
+
+namespace Microsoft.AspNetCore.Components.Server.Circuits
+{
+    internal class CircuitHandleRegistry : ICircuitHandleRegistry
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:19]:
```suggestion
    internal sealed class CircuitHandleRegistry : ICircuitHandleRegistry
```

File: src/Components/Server/src/Circuits/CircuitFactory.cs [hunk 13]
```diff
@@ -16,7 +16,7 @@
 
 namespace Microsoft.AspNetCore.Components.Server.Circuits
 {
-    internal class CircuitFactory
+    internal class CircuitFactory : ICircuitFactory
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/CircuitFactory.cs:19]:
```suggestion
    internal sealed class CircuitFactory : ICircuitFactory
```

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+    {
+        public CircuitHandle GetCircuitHandle(IDictionary<object, object?>   circuitHandles, object circuitKey)
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:21]:
```suggestion
        public CircuitHandle GetCircuitHandle(IDictionary<object, object?>circuitHandles, object circuitKey)
```

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs [hunk 15]
```diff
@@ -0,0 +1,46 @@
...
+        {
+            if (circuitHandles.TryGetValue(circuitKey, out var circuitHandle))
+            {
+                return (CircuitHandle) circuitHandle;
+            }
+            
+            return null;;
+        }
+
+        public CircuitHost GetCircuit(IDictionary<object, object?>   circuitHandles, object circuitKey)
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:31]:
```suggestion
        public CircuitHost GetCircuit(IDictionary<object, object?> circuitHandles, object circuitKey)
```

File: src/Components/Server/src/Circuits/CircuitHandleRegistry.cs (hunk 12 above)
Comment (pranavkm) [reply src/Components/Server/src/Circuits/CircuitHandleRegistry.cs:19]: this type's like a glorified dictionary accessor. Do we really need it? (I haven't seen the rest of the PR as yet.)

File: src/Components/Server/src/ComponentHub.cs [hunk 16]
```diff
@@ -69,7 +72,7 @@ public override Task OnDisconnectedAsync(Exception exception)
         {
             // If the CircuitHost is gone now this isn't an error. This could happen if the disconnect
             // if the result of well behaving client hanging up after an unhandled exception.
-            var circuitHost = GetCircuit();
+            var circuitHost = _circuitHandleRegistry.GetCircuit(Context.Items, CircuitKey);
```
Comment (pranavkm) [inline src/Components/Server/src/ComponentHub.cs:75]: Couldn't we configure Context.Items instead of introducing the registry?

File: src/Components/Server/test/Circuits/ComponentHubTest.cs [hunk 17]
```diff
@@ -0,0 +1,208 @@
...
+            var (mockClientProxy, hub) = InitializeComponentHub();
+            var circuitSecret = await hub.StartCircuit("https://localhost:5000", "https://localhost:5000/subdir", "{}", null);
+            Assert.NotNull(circuitSecret);
+
+            var circuit2Secret = await hub.StartCircuit("https://localhost:5000", "https://localhost:5000/subdir", "{}", null);
+            Assert.Null(circuit2Secret);
+
+            var errorMessage = "The circuit host '.*?' has already been initialized.";
+            mockClientProxy.Verify(m => m.SendCoreAsync("JS.Error", It.Is<object[]>(s => Regex.Match((string)s[0], errorMessage).Success), It.IsAny<CancellationToken>()), Times.Once());
+
```
Comment (pranavkm) [inline src/Components/Server/test/Circuits/ComponentHubTest.cs:41]:
```suggestion
```

File: src/Components/Server/src/ComponentHub.cs (hunk 16 above)
Comment (captainsafia) [reply src/Components/Server/src/ComponentHub.cs:75]: The original intent here was to have an injected type that we could mock in the tests to avoid actually have to created a circuit instance. This originally started out as a singleton service with its own internal dictionary. However, that doesn't work because `Context.Items` is set up to correctly exist at a connection scope so I set up the registry as a wrapper around `Context.Items` with the ability to override in the code.

It's not possible for us to configure `Context.Items` directly in the test since the setting/getting happens entirely within the `StartCircuit` invocation so it's not possible to set up/tear down ahead of time.
