### PR TITLE
Fix HttpResponseStreamWriter

### LINKED ISSUE #18972: Possible bug in pull request #18451
### Describe the bug

New Write/WriteLine/WriteAsync/WriteLineAsync ReadOnlySpan/ReadOnlyMemory overloads
in HttpResponseStreamWriter.cs will not write all data if the data exceeds internal buffer. 

See code from pull request (#18451) with my comments:

        public override void Write(ReadOnlySpan<char> value)
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(HttpResponseStreamWriter));
            }
            var written = 0;
            while (written < value.Length)
            {
                if (_charBufferCount == _charBufferSize)
                {
                    FlushInternal(flushEncoder: false);
                }

                written = CopyToCharBuffer(value);

                if (written < value.Length)
                {
                   value = value.Slice(written);
                   // if "written" >= value.Length 
                   // then we will exit loop and last chunk will not be copied
                   // to fix this we should reset "written" after each Slice
                }
            };
     }

The same problem exists in WriteAsyncAwaited(ReadOnlyMemory<char> value)

### Further technical details
- ASP.NET Core version

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/dotnet/aspnetcore/issues/18972. There was also another Debug.Assert being fired every time, so I changed WriteAsyncAwaited to WriteAsync to keep the invariant in tact.

### CODE REVIEW

File: src/Http/WebUtilities/src/HttpResponseStreamWriter.cs [hunk 1]
```diff
@@ -136,7 +136,7 @@ public override void Write(ReadOnlySpan<char> value)
             }
 
             var written = 0;
-            while (written < value.Length)
+            while (true)
```
Comment (halter73) [inline src/Http/WebUtilities/src/HttpResponseStreamWriter.cs]: I like keeping the terminating condition in the loop condition. Right now, it looks like `written` should be cumulative since it's defined outside of the loop, but really it's just that size of the last chunk that was written.

I would do `var remaining = value.length;` instead of `var written = 0;`, and then make `while (remaining > 0)` the loop condition. Then you can just put `remaining -= written` after `var written = CopyToCharBuffer(value);` and keep everything else the same as it was. I think that makes it much easier to see what's going on.

File: src/Http/WebUtilities/src/HttpResponseStreamWriter.cs [hunk 2]
```diff
@@ -290,7 +292,6 @@ private async Task WriteAsyncAwaited(string value)
             var count = value.Length;
 
             Debug.Assert(count > 0);
-            Debug.Assert(_charBufferSize - _charBufferCount < count);
```
Comment (halter73) [inline src/Http/WebUtilities/src/HttpResponseStreamWriter.cs]: We can keep this assert now, right?

**Review by halter73 — APPROVED** [review]
