### PR TITLE
Fix null ref in UrlGroup.Dispose due to logger not set

### LINKED ISSUE #26982: HttpSysRequestDelegationFeature - DelegationRule throws NullReferenceException on Dispose
### Describe the bug
When disposing a DelegationRule, if the call to HttpCloseUrlGroup within UrlGroup.Dispose() fails then a NullReferenceException happens because _logger is not initialized in the constructor used by the HttpSysRequestDelegationFeature.

### To Reproduce

```c#
namespace Sample
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            var delegator = app.ServerFeatures.Get<IServerDelegationFeature>();
            var rule = delegator.CreateDelegationRule("DefaultAppPool", "http://*:80/");
            rule.Dispose();
        }
    }
}
```

### Exceptions (if any)

```
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'logger'))
---> System.ArgumentNullException: Value cannot be null. (Parameter 'logger')
at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, EventId eventId, String message, Object[] args)
at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.Dispose()
at Microsoft.AspNetCore.Server.HttpSys.DelegationRule.Dispose()
```

### PR DESCRIPTION
**Pull request by NGloreous**
Summary of the changes (Less than 80 chars)
 - Fixing #26982 by passing the logger through to the new version of the UrlGroup constructor used by the HttpSysRequestDelegationFeature.
 - Also fixing a null ref case I hit while calling DelegateRequest when passing a null DelegationRule, yes my bad but should probably do the check :)

### CODE REVIEW

**Comment by Tratcher** [comment]
And re-target to the master branch please? I don't expect this to get approved for 5.0 at this point. We might be able to backport it for servicing later.

**Comment by NGloreous** [comment]
@shirhatti CLA signed.

@Tratcher updated to point to master. I wasn't quite sure what the process was to get this patched for 5.

File: src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs [hunk 1]
```diff
@@ -38,8 +38,10 @@ internal unsafe UrlGroup(ServerSession serverSession, ILogger logger)
             Id = urlGroupId;
         }
 
-        internal unsafe UrlGroup(RequestQueue requestQueue, UrlPrefix url)
+        internal unsafe UrlGroup(RequestQueue requestQueue, UrlPrefix url, ILogger logger)
         {
+            _logger = logger;
```
Comment (BrennanConroy) [inline src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs:43]: Make `_logger` readonly so it has to be set in a constructor.

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs [hunk 2]
```diff
@@ -326,6 +326,10 @@ private void SetFatalResponse(int status)
 
         internal unsafe void Delegate(DelegationRule destination)
         {
+            if (destination == null)
```
Comment (pranavkm) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:329]: Nullability should do a better job of validating this. Could we remove this check given that it's a non-public API?

Comment (NGloreous) [reply src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:329]: @pranavkm HttpSys.FeatureContext.DelegateRequest which is public calls this method directly. I could move this check over there but figured it made more sense here since this is where it's used. 

I don't quite get your point about nullability.

**Comment by shirhatti** [comment]
> I wasn't quite sure what the process was to get this patched for 5.

It's too late to get this patched for 5. Given that there's an obvious workaround it won't meet the bar

**Comment by NGloreous** [comment]
@shirhatti what's the work around? If there are any issues in Dispose they will result in a null ref and no ability to have insight into the actual error.

**Comment by shirhatti** [comment]
@NGloreous Can you rebase to fix the merge conflicts?

**Review by shirhatti — APPROVED** [review]

**Comment by NGloreous** [comment]
> @NGloreous Can you rebase to fix the merge conflicts?

@shirhatti done.

**Review by Tratcher — APPROVED** [review]
