### PR TITLE
Fix 'HeadOutlet' getting trimmed away for Blazor WebAssembly prerendered apps after publish

### LINKED ISSUE #35363: Blazor: PreRender WASM: PageTitle/HeadContent not updated on publish
### Describe the bug
.Net 6 Preview 7
PageTitle and Head content does not update when navigating between pages after Publish.

> Note: It works as expected when developing (e.g. `dotnet run --project .\Server\`).

This is running WebAssembly PreRendering.

### To Reproduce
Repo to recreate
https://github.com/srpeirce/blazor-pagetitle-bug-net6-7

```
dotnet publish -c Release
Server\bin\Release\net6.0\publish\HeadFail.Server.exe
```

Open 
image

❌ Click Counter - Doesn't Update Page title
image

Additional:
Refreshing page, the title is updated.
image

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d
  
```

### PR DESCRIPTION
**Pull request by MackinnonBuck**
**Fix `HeadOutlet` getting trimmed away for Blazor WebAssembly prerendered apps after publish**
The `HeadOutlet` component was getting trimmed away in published ASP.NET Core hosted Blazor WebAssembly prerendered apps. This caused `<HeadContent>` and  `<PageTitle>` to take effect _only_ during prerendering.

**PR Description**
Added a `[DynamicDependency]` on `WebAssemblyHostBuilder.CreateDefault` to prevent `HeadOutlet` from getting trimmed away.

Fixes #35363

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs [hunk 1]
```diff
@@ -39,6 +39,7 @@ public sealed class WebAssemblyHostBuilder
         /// <returns>A <see cref="WebAssemblyHostBuilder"/>.</returns>
         [DynamicDependency(nameof(JSInteropMethods.NotifyLocationChanged), typeof(JSInteropMethods))]
         [DynamicDependency(JsonSerialized, typeof(WebEventDescriptor))]
+        [DynamicDependency(Component, typeof(HeadOutlet))]
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs:42]: Could I bother you to

a) Add the comment from your PR here?
b) Possibly update the WebAssembly pre-rendering scenario to include the HeadComponent?

The interesting thing is that the WebAssembly pre-rendering would run in to the same issue with all components in the framework if they happen to be root components. I can think of too many that would qualify for one, but it's something to be cognizant of when designing new ones. 


FYI @javiercn / @SteveSandersonMS

Comment (MackinnonBuck) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs]: Since this type of bug could be possible with any arbitrary root component not referenced in the client-side build, I wonder if it could be worth it to throw a meaningful exception when a prerendered component type could not be found in its assembly. If we come up with an intuitive workaround, the exception message could also provide info about that.

Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs]: >  if it could be worth it to throw a meaningful exception when a prerendered component type could not be found in its assembly

That seems like a good idea. We wouldn't have spent that long scratching our heads if things had failed noisily. @javiercn how do you feel about this? I imagine the change would be in the code that rehydrates from WebAssembly pre-rendering.

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs]: Agreed it would be good if we can do that.

We can afford a bit of extra overhead (for example, explicitly calling `Type.GetType` or whatever to see if we know about the type) in the code that rehydrates since it's a one-time cost during startup rather than being part of the core rendering loop.

File: src/Components/WebAssembly/testassets/WasmPrerendered.Client/WasmPrerendered.Client.csproj [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+  </PropertyGroup>
+
+  <ItemGroup>
+    <Reference Include="Microsoft.AspNetCore.Components.WebAssembly" />
+  </ItemGroup>
+
+  <ItemGroup>
+    <Folder Include="wwwroot\" />
+  </ItemGroup>
+
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/testassets/WasmPrerendered.Client/WasmPrerendered.Client.csproj:14]: I think this block might not be required, but maybe there's some subtlety I'm missing. Also it doesn't matter, so feel free to leave it if you have more important things to focus on!

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/testassets/WasmPrerendered.Client/WasmPrerendered.Client.csproj:14]: Also on the subject of not-very-important feedback, if the names of these folders/projects had an extra `.` in them (e.g., `Wasm.Prerendered.Client/Wasm.Prerendered.Client.csproj `) that would align with the existing `Wasm.Authentication.*` folders/projects.

Again, this is not important so please only react to it if you really want to!

**Review by SteveSandersonMS — APPROVED** [review]
Looks great - thanks for sorting this out!
