### PR TITLE
[Blazor] Update `WebAssembly.DevServer` to serve the `Blazor-Environment` header

### LINKED ISSUE #57941: Blazor WebAssembly Standalone App targeting .net 9 runs in production mode when started from VS in debug mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I create new Blazor WebAssembly Standalone App template project in Visual Studio 17.12.0 Preview 2.0, targeting .net 9 using the 9.0.100-rc.1.24452.12 version of .net SDK

Then I slightly change the 'Home' page in the 'Pages' folder of the project to display the environment as follows:

```
@page "/"
@using Microsoft.AspNetCore.Components.WebAssembly.Hosting
@inject IWebAssemblyHostEnvironment Env

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<p>Environment: @Env.Environment</p>
```

Now, when I run the project in VS debug mode, I get this result

image

indicating, that the project runs as in production environment (not correct IMO), even though the generated launchSettings.json sets the 'ASPNETCORE_ENVIRONMENT' as 'Development'

```
"https": {
  "commandName": "Project",
  "dotnetRunMessages": true,
  "launchBrowser": true,
  "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
  "applicationUrl": "https://localhost:7299;http://localhost:5176",
  "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development"
  }
}
```
When I follow the exact steps in the same Visual Studio using the same .net SDK version  with the only difference - targeting .net 8 (instead of .net 9) I get this:

image

The environment is 'Development' which I tend to consider as correct behavior

### Expected Behavior

Running Blazor WebAssembly Standalone App project from VS in 'debug' mode with

```"ASPNETCORE_ENVIRONMENT": "Development"```

set in launchSettings.json

should set the environment to 'Development' instead to 'Production'

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.100-rc.1.24452.12

### Anything else?

.NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.67cd1eb6
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64

### PR DESCRIPTION
**Pull request by MackinnonBuck**
Since the dev server no longer calls `UseBlazorFrameworkFiles()`, we need to manually add the `Blazor-Environment` header when applicable.

Fixes #57941

### CODE REVIEW

File: src/Components/WebAssembly/DevServer/src/Server/Startup.cs [hunk 1]
```diff
@@ -29,27 +30,29 @@ public static void Configure(IApplicationBuilder app, IConfiguration configurati
...
+        var applyCopHeaders = configuration.GetValue<bool>("ApplyCopHeaders");
 
-        if (applyCopHeaders)
+        app.Use(async (ctx, next) =>
         {
-            app.Use(async (ctx, next) =>
+            if (ctx.Request.Path.StartsWithSegments("/_framework") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.server.js") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.web.js"))
             {
-                if (ctx.Request.Path.StartsWithSegments("/_framework") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.server.js") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.web.js"))
+                ctx.Response.Headers.Append("Blazor-Environment", webHostEnvironment.EnvironmentName);
```
Comment (javiercn) [inline src/Components/WebAssembly/DevServer/src/Server/Startup.cs:40]: Can we just send it when `blazor.boot.json`?

**Review by javiercn — APPROVED** [review]

**Review by mkArtakMSFT — APPROVED** [review]

File: src/Components/WebAssembly/DevServer/src/Server/Startup.cs [hunk 2]
```diff
@@ -29,27 +30,28 @@ public static void Configure(IApplicationBuilder app, IConfiguration configurati
...
-            app.Use(async (ctx, next) =>
+            if (ctx.Request.Path.StartsWithSegments("/_framework/blazor.boot.json"))
             {
-                if (ctx.Request.Path.StartsWithSegments("/_framework") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.server.js") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.web.js"))
+                ctx.Response.Headers.Append("Blazor-Environment", webHostEnvironment.EnvironmentName);
+            }
+            else if (applyCopHeaders && ctx.Request.Path.StartsWithSegments("/_framework") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.server.js") && !ctx.Request.Path.StartsWithSegments("/_framework/blazor.web.js"))
+            {
+                var fileExtension = Path.GetExtension(ctx.Request.Path);
+                if (string.Equals(fileExtension, ".js", StringComparison.Ordinal))
```
Comment (halter73) [inline src/Components/WebAssembly/DevServer/src/Server/Startup.cs:45]: Why didn't an analyzer catch this previously? Also, it's more consistent to ignore case.

```suggestion
                if (string.Equals(fileExtension, ".js", StringComparison.OrdinalIgnoreCase))
```

I can't think of a reason a request would come in with an uppercase `.JS` extension, but file extensions generally are case insensitive, and the dev server would still serve the correct file. `StartsWithSegments` also defaults to `OrdinalIgnoreCase`.

**Review by halter73 — APPROVED** [review]

File: src/Components/WebAssembly/DevServer/src/Server/Startup.cs (hunk 2 above)
Comment (MackinnonBuck) [reply src/Components/WebAssembly/DevServer/src/Server/Startup.cs]: There was a diagnostic for this, but the severity was "info" which is probably why it was missed initially.
