### PR TITLE
Fix HttpLoggingMiddleware Request/Response bodies logging in case of stream being closed by a subsequent middleware

### LINKED ISSUE #61489: HttpLogging drops Request/Response bodies if Stream has been closed
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The [`HttpLoggingMiddleware`](HttpLoggingMiddleware) logs empty request/response bodies in case the subsequent middleware closes the corresponding stream. For example, `CoreWCF` does that for the `BasicHttpBinding`.

```
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody: [Only partially consumed by app]
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[4]
      ResponseBody:
```

### Expected Behavior

Request and Response bodies are being logged whether the stream has been closed or not.

### Steps To Reproduce

1. Create an empty Web application
2. Change `Logging:LogLevel:Microsoft.AspNetCore` to `Information` in `appsettings*.json`
3. Put the following code in the `Program.cs`
```
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpLogging(options => options.LoggingFields = HttpLoggingFields.All);
var app = builder.Build();

app.UseHttpLogging();

app.Run(async context =>
{
    var buffer = new byte[context.Request.ContentLength!.Value];
    await context.Request.Body.ReadExactlyAsync(buffer, 0, buffer.Length);
    context.Request.Body.Close(); // (1) Close the request body stream
    
    context.Response.ContentType = "text/plain";
    await context.Response.Body.WriteAsync(buffer);
    context.Response.Body.Close(); // (2) Close the response body stream
});

await app.StartAsync();

var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri(app.Urls.First());
var response = await httpClient.PostAsync("/", new StringContent("LOOK FOR THIS IN THE LOGS"));
app.Logger.LogInformation("Response received: {response}, body: {body}", response, response.Content.ReadAsStringAsync().GetAwaiter().GetResult());

await app.StopAsync();
```
4. Run the app
5. Observe that `HttpLoggingMiddleware` doesn't log neither Request nor Response bodies:
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5082
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\immediate\WebApplication2
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5082/ - text/plain;+charset=utf-8 25
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      Protocol: HTTP/1.1
      Method: POST
      Scheme: http
      PathBase: 
      Path: /
      Host: localhost:5082
      Content-Type: text/plain; charset=utf-8
      Content-Length: 25
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[2]
      Response:
      StatusCode: 200
      Content-Type: text/plain
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody: [Only partially consumed by app]
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[4]
      ResponseBody:
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[8]
      Duration: 11.3532ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5082/ - 200 - text/plain 22.4930ms
info: WebApplication2[0]
      Response received: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Mon, 14 Apr 2025 13:28:05 GMT
        Server: Kestrel
        Transfer-Encoding: chunked
        Content-Type: text/plain
      }, body: LOOK FOR THIS IN THE LOGS
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Process finished with exit code 0.
```

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-preview.4.25207.10

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ExtraClock**
# Fix HttpLoggingMiddleware Request/Response bodies logging in case of stream being closed by a subsequent middleware (#61489)

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Preserve buffer contents until it is consumed by the `HttpLoggingMiddleware`

## Description

Fixes #61489

When the subsequent middleware closes request/response stream, the `BufferingStream` calls `Reset` which leads to an empty body being logged.

The request stream might be closed if the subsequent middleware follows the `ContentLength` header to sense the end of the stream (instead of reading it to the end).

The response stream might be closed without any additional preconditions, just because the subsequent middleware decided to do so.

A real-life example of such a middleware is `CoreWCF` `BasicHttpBinding`: [inputStream.Close](https://github.com/CoreWCF/CoreWCF/blob/067f83b490332120f45ec9064dd7d1fa555ba65d/src/CoreWCF.Http/src/CoreWCF/Channels/HttpChannelHelpers.cs#L151), [_outputStream.Close](https://github.com/CoreWCF/CoreWCF/blob/067f83b490332120f45ec9064dd7d1fa555ba65d/src/CoreWCF.Http/src/CoreWCF/Channels/HttpChannelHelpers.cs#L544)

### CODE REVIEW

**Comment by ExtraClock** [comment]
@dotnet-policy-service agree

**Comment by ExtraClock** [comment]
Hi @BrennanConroy ! Is there a chance for this PR to make it into the v10 release? Since it's my first PR, I'm not sure if there is any additional action I have to take to move this thing forward.

File: src/Middleware/HttpLogging/src/RequestBufferingStream.cs [hunk 1]
```diff
@@ -138,6 +139,25 @@ public void LogRequestBody(HttpLoggingInterceptorContext logContext)
...
+    {
+        var result = _bodyBeforeClose ?? GetString(_encoding);
+        // Reset the value after its consumption to preserve GetString(encoding) behavior
+        _bodyBeforeClose = null;
+        return result;
+    }
+
+    public override void Close()
+    {
+        if (!HasLogged)
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/RequestBufferingStream.cs:152]: Can we pass `HttpLoggingInterceptorContext` into the ctor like we do for the response stream and then check if body logging is enabled before getting the string?

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs [hunk 2]
```diff
@@ -188,7 +189,27 @@ public void LogResponseBody(HttpLoggingInterceptorContext logContext)
...
+
+    private string GetStringInternal()
+    {
+        var result = _bodyBeforeClose ?? GetString(_encoding!);
+        // Reset the value after its consumption to preserve GetString(encoding) behavior
+        _bodyBeforeClose = null;
+        return result;
+    }
+
+    public override void Close()
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:204]: `Stream.Dispose()` calls `Close()` which could then re-create the string just to throw it away. Maybe we should set `_logBody` to false once one of the `LogResponseBody()` methods is called.

I think the request stream impl is fine, but we should double-check and maybe add a comment about the assumption.

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs [hunk 3]
```diff
@@ -390,6 +390,46 @@ public async Task RequestBodyCopyToAsyncWorks(string expected)
...
+        var middleware = CreateMiddleware(
+            async c =>
+            {
+                var arr = new byte[4096];
+                var contentLengthBytesLeft = c.Request.Body.Length;
+
+                // (1) The subsequent middleware reads right up to the buffer size (guided by the ContentLength header)
+                while (contentLengthBytesLeft > 0)
+                {
+                    var res = await c.Request.Body.ReadAsync(arr, 0, (int)Math.Min(arr.Length, contentLengthBytesLeft));
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:409]: nit?
```suggestion
                    var res = await c.Request.Body.ReadAsync(arr, 0, arr.Length);
```

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs [hunk 4]
```diff
@@ -1155,6 +1195,32 @@ public async Task StartAsyncResponseHeadersLogged()
...
+            },
+            options);
+
+        var httpContext = new DefaultHttpContext();
+
+        await middleware.Invoke(httpContext);
+
+        Assert.Contains(TestSink.Writes, w => w.Message.Contains(expected));
+    }
+
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:1223]: Could we add a test for `options.CombineLogs = true` and both Request and Response?

File: src/Middleware/HttpLogging/src/RequestBufferingStream.cs (hunk 1 above)
Comment (ExtraClock) [reply src/Middleware/HttpLogging/src/RequestBufferingStream.cs:152]: Unlike response stream, the request stream is created only if request body logging is enabled.
Refer to [HttpLoggingMiddleware.cs#L97](https://github.com/dotnet/aspnetcore/blob/2edb8c84fa5e64ff7877f11e0f181f0419c039c9/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L97), [L107](https://github.com/dotnet/aspnetcore/blob/2edb8c84fa5e64ff7877f11e0f181f0419c039c9/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L107), [L153-L176](https://github.com/dotnet/aspnetcore/blob/2edb8c84fa5e64ff7877f11e0f181f0419c039c9/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L153-L176)

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs (hunk 2 above)
Comment (ExtraClock) [reply src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:207]: Basically it's going to fetch an interned empty string (refer to [BufferingStream.cs#L57](https://github.com/dotnet/aspnetcore/blob/2edb8c84fa5e64ff7877f11e0f181f0419c039c9/src/Middleware/HttpLogging/src/BufferingStream.cs#L57)), but I agree that it's better to protect this code from this kind of opportunity. I'm going to add `_hasLogged` similar to the request stream implementation, as resetting `_logBody` to `false` feels a bit unintuitive for a future reader.

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs (hunk 4 above)
Comment (ExtraClock) [reply src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:1223]: Done

**Comment by ExtraClock** [comment]
@BrennanConroy , thanks for your feedback. I addressed your comments, please take a look.

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks for the fix @ExtraClock !
