### PR TITLE
Fix up handling for awaitable IResults in ApiExplorer

### LINKED ISSUE #56975: [9.0-preview7] Response schema being returned as IResult
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Updating from version `9.0.0-preview.7.24372.9` to `9.0.0-preview.7.24373.9` of `Microsoft.AspNetCore.OpenApi`, `[ProducesResponseType]` seems to have stopped working and instead of the correct response type for an API endpoint, `IResult` is returned instead.

Here's the document:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "London Travel",
    "description": "London Travel is an Amazon Alexa skill for checking the status for travel in London.",
    "termsOfService": "https://londontravel.martincostello.com/terms-of-service/",
    "contact": {
      "name": "Martin Costello",
      "url": "https://github.com/martincostello/alexa-london-travel-site"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": ""
  },
  "servers": [
    {
      "url": "https://localhost"
    }
  ],
  "paths": {
    "/api/preferences": {
      "get": {
        "tags": [
          "LondonTravel.Site"
        ],
        "summary": "Gets a user's preferences.",
        "description": "Gets the preferences for a user associated with an access token.",
        "operationId": "GetApiPreferences",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The authorization header.",
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The preferences associated with the provided access token.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IResult"
                }
              }
            }
          },
          "401": {
            "description": "A valid access token was not provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "statusCode": 401,
                  "message": "Unauthorized.",
                  "requestId": "0HKT0TM6UJASI",
                  "details": [
                    "Only the Bearer authorization scheme is supported."
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ErrorResponse": {
        "required": [
          "statusCode",
          "message",
          "requestId",
          "details"
        ],
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "integer",
            "description": "The HTTP status code.",
            "format": "int32"
          },
          "message": {
            "type": "string",
            "description": "The error message."
          },
          "requestId": {
            "type": "string",
            "description": "The request Id."
          },
          "details": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The error details, if any."
          }
        },
        "description": "Represents an error from an API resource."
      },
      "IResult": {
        "type": "object"
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "description": "Access token authentication using a bearer token.",
        "scheme": "bearer",
        "bearerFormat": "Opaque token"
      }
    }
  },
  "security": [
    {
      "Bearer": [ ]
    }
  ],
  "tags": [
    {
      "name": "LondonTravel.Site"
    }
  ]
}
```

### Expected Behavior

A schema for `PreferencesResponse` should be returned.

### Steps To Reproduce

1. Clone https://github.com/martincostello/alexa-london-travel-site/pull/2633/commits/2a6df23ddcbb1e9a552daaac543aed53cfaedbec
2. Start the app
3. Browser the OpenAPI document returned by `/openapi/api.json`

### Exceptions (if any)

_No response_

### .NET Version

9.0.100-preview.7.24374.2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/56975.

I introduced in a regression in https://github.com/dotnet/aspnetcore/commit/8da6daa1cd377f58b332d8402484e1e727e7d9cc that meant that `IResult` types (which don't expose any metadata) were erroneously inserted into `ApiResponseTypes`. This regression wasn't caught because the test cases that existed optimized for void-returning awaitables and didn't factor in result types that implemented `IEndpointMetadataProvider`.

To resolve this issue, I've made some changes to treat `IResult`-types directly in the response and those included in metadata as void responses that should not map to `ApiResponseType`s. I also included additional tests for handling of typed results in ApiExplorer.

### CODE REVIEW

File: src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs [hunk 1]
```diff
@@ -228,6 +228,13 @@ private static List<IApiResponseMetadataProvider> GetResponseMetadataAttributes(
 
         foreach (var metadata in responseMetadata)
         {
+            // `IResult` metadata inserted for awaitable types should
```
Comment (amcasey) [inline src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs:231]: I can't tell from this comment whether `IResult` _only_ appears because we inserted it.  Is there a case where it's present legitimately and we shouldn't skip it?

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 2]
```diff
@@ -338,6 +332,14 @@ private static ParameterDescriptor CreateParameterDescriptor(ParameterInfo param
         var defaultErrorType = errorMetadata?.Type ?? typeof(void);
         var contentTypes = new MediaTypeCollection();
 
+        // If the return type is an IResult or an awaitable IResult, then we should treat it as a void return type
```
Comment (amcasey) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:335]: How are we detecting that "awaitable IResult"?  (Does that mean something other than `Task<IResult>`?)

File: src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs (hunk 1 above)
Comment (captainsafia) [reply src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs:231]: It's theoritically feasible that IResult could appear there if someone manually insert it by doing something like:

```csharp
app.MapGet()
	.Produces<IResult>("application/json");
```

In either case, it still stands that `IResult` doesn't provide us with type information specific enough to include in the response type information.

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs (hunk 2 above)
Comment (captainsafia) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:335]: It's detected the code generation layer that inserts the metadata. In this case, there's a slight distinciton in behavior.

When using static code gen (RDG), minimal APIs only detects awaitable types that are either `ValueTask` or `Task`.

When using dynamic code gen (RDF), we used the `CoercedAwaitableInfo` API which uses reflection to check if the target type implements all the required properties for an awaitable type.

https://github.com/dotnet/aspnetcore/blob/27f2a011a4211118552dfb8f38d36e8629267d2b/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1027-L1038

File: src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs (hunk 1 above)
Comment (amcasey) [reply src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs:231]: What about something like "`IResult` (usually inserted for awaitable types) isn't useful..."?

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs (hunk 2 above)
Comment (amcasey) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:335]: As we discussed offline, `responseType` has already been unwrapped. 👍

**Review by amcasey — APPROVED** [review]
