### PR TITLE
Fix <component> tag helpers being siblings. Fixes #17851

### LINKED ISSUE #17851: Multiple <component> tag helpers in same element interfere with each other
It seems that when you use multiple `<component />` tag helpers side-by-side, e.g.,:

```cshtml
    <app style="display:block">
        <component type="typeof(Something)" render-mode="Server" />
        <component type="typeof(AnotherThing)" render-mode="Server" />
    </app>
```

... then they can disrupt each others' rendering and lead to corrupted UI updates. See the repro at https://github.com/aspnet/AspNetCore/issues/17570

My guess is that our JS-side code that converts the `<!--Blazor:...-->` comments into a `LogicalElement` isn't setting it up correctly, and perhaps has the logical elements both hooked up to the physical DOM parent as if they were its only child.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is a fix for #17851. The problem was that when converting the output from `<component>` into a live tree of logical elements, we were re-initializing the parent for each sibling, thereby destroying the state set up by preceding siblings.

It could have been done as (pretty much) a one-liner change, but I've tweaked a bit more here to make the flow more explicit and remove some redundant steps. The core part of the fix is the `if` test that I commented with `If it's already a logical element, leave it alone`.

I haven't yet figured out whether it makes sense to have an E2E test for this specifically. We already have E2E coverage, and the conditions needed to manifest a bug here are quite obscure. I'll try to see if I can come up with a simple enough case that makes sense.

### CODE REVIEW

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts [hunk 1]
```diff
@@ -52,15 +52,13 @@ export function toLogicalRootCommentElement(start: Comment, end: Comment): Logic
 
   const parent = start.parentNode;
   const parentLogicalElement = toLogicalElement(parent, /* allow existing contents */ true);
-  const children = getLogicalChildrenArray(parentLogicalElement);
-  Array.from(parent.childNodes).forEach(n => children.push(n as unknown as LogicalElement));
```
Comment (rynowak) [inline src/Components/Web.JS/src/Rendering/LogicalElements.ts]: is this just cleanup? I don't see `children` used anywhere.

**Review by rynowak — APPROVED** [review]

File: src/Components/Web.JS/src/Rendering/LogicalElements.ts (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: This logic is populating the "logical children array" with the physical children during init. It's needed so the logical element is correctly initialized. The `children` variable here is not used later, but the array it references might be.

Previously it was handled as a standalone special case, but I changed this to be part of the `toLogicalElement` since that's the shared initialization code path.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Rendering/LogicalElements.ts]: Update: no longer changing this. It's simpler to leave it as it was.

**Review by rynowak — APPROVED** [review]
