### PR TITLE
Using DictionaryKeyPolicy during ProblemDetails.Errors conversion to JSON

### LINKED ISSUE #17999: Reopen 7439 - ModelState json serialization should be camel cased
### Describe the bug
The issue [7439](https://github.com/aspnet/AspNetCore/issues/7439) was not completely addressed, the bot blocked the issue from commenting, but I think this main problem should be addressed:

As is, Net Core responds almost everything as camel case, except for model validations, which I think is odd:

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|706e0133-46db8fce16cb675d.",
  "errors": {
    "Email": [
      "The Email field is not a valid e-mail address."
    ],
    "Password": [
      "The field Password must be a string or array type with a minimum length of '8'."
    ]
  }
}
```

As you see, all the properties are camel case but the field names, a workaround is to use `CustomProblemDetailsFactory` from the comment in the same issue.

### To Reproduce
Create a project and a controller with a model with validations.

Make sure the controller is annotated with `[ApiController]`, so validation is handled automatically.

Example:

```
    [Authorize]
    [ApiController]
    [Route("Api/Address/[controller]")]
    public class ColonyController : Controller
    {
        
        [HttpPost]
        [Route("[action]")]
        public Task<int> Create([FromBody]ColonyToAddDto colonyToAddDto)
        {
            return Task.FromResult(0);
        }
    }
```

With the model

```
    public class ColonyToAddDto
    {
        [Required]
        [StringLength(300, MinimumLength = 3)]
        public string Name { get; set; }
        [Range(1, 99999)]
        public int PostalCode { get; set; }
        [Range(1, double.PositiveInfinity)]
        public int MunicipalityId { get; set; }
    }
```

### Further technical details
- ASP.NET Core version 3.1

### PR DESCRIPTION
**Pull request by brunolins16**
# Using DictionaryKeyPolicy during ProblemDetails.Errors conversion to JSON

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Adding a call to `options!.DictionaryKeyPolicy.ConvertName` during the `WriteProblemDetails`

## Description

With this change the `HttpValidationProblemDetailsJsonConverter` will rely on the configured `JsonSerializerOptions` to convert the `ProblemDetails.Errors` property to JSON.

The `JsonSerializerOptions` could be configured with the following code:

 ```
services.AddControllers().AddJsonOptions(options => 
{ 
     options.JsonSerializerOptions.DictionaryKeyPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
 });
```

After the change the following results are expected:

### Model State errors

- **Name** - "The Name field is required."
- **PostalCode** - "The field PostalCode must be between 1 and 99999."
- **SubClass.Test1** - "The field Test1 must be between 1 and 10."

### Without option

``` json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-16743847660da7bda8bae57cb9266ab9-5318f21ebc12e9fb-00",
    "errors": {
        "Name": [
            "The Name field is required."
        ],
        "PostalCode": [
            "The field PostalCode must be between 1 and 99999."
        ],
        "SubClass.Test1": [
            "The field Test1 must be between 1 and 10."
        ]
    }
}
```

### With `camelCase` option

``` json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-66c52afd589aa7c8b7ffcbbdf847c992-c02ee1425c580f24-00",
    "errors": {
        "name": [
            "The Name field is required."
        ],
        "postalCode": [
            "The field PostalCode must be between 1 and 99999."
        ],
        "subClass.Test1": [
            "The field Test1 must be between 1 and 10."
        ]
    }
}

```
#17999

### CODE REVIEW

File: src/Shared/HttpValidationProblemDetailsJsonConverter.cs [hunk 1]
```diff
@@ -60,10 +61,26 @@ public static void WriteProblemDetails(Utf8JsonWriter writer, HttpValidationProb
...
         ProblemDetailsJsonConverter.WriteProblemDetails(writer, value, options);
 
+        static string ConvertName(string name, JsonSerializerOptions options)
+        {
+            if (string.IsNullOrEmpty(name) || options?.DictionaryKeyPolicy == null)
+            {
+                return name;
+            }
+
+            var tokens = name.Split(propertySeparator);
```
Comment (pranavkm) [inline src/Shared/HttpValidationProblemDetailsJsonConverter.cs:71]: This looks a bit suspicious. - why do we need to split these? What happens if we don't?

File: src/Shared/HttpValidationProblemDetailsJsonConverter.cs [hunk 2]
```diff
@@ -60,10 +61,26 @@ public static void WriteProblemDetails(Utf8JsonWriter writer, HttpValidationProb
...
+            for (var i = 0; i < tokens.Length; i++)
+            {
+                tokens[i] = options!.DictionaryKeyPolicy.ConvertName(tokens[i]);
+            }
+
+            return string.Join(propertySeparator, tokens);
+        }
+
         writer.WriteStartObject(Errors);
```
Comment (pranavkm) [inline src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: An alternative is to replace this section with a call `JsonSerializer.Serialize(writer, Errors, options)`. That way we're no longer in the business of serializing dictionaries.

File: src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs [hunk 3]
```diff
@@ -135,4 +136,63 @@ public void ReadUsingJsonSerializerWorks()
...
+            Status = 400
+        };
+
+        // Act
+        var converter = new ValidationProblemDetailsJsonConverter();
+        using MemoryStream stream = new();
+        using Utf8JsonWriter writer = new(stream);
+
+        var options = new JsonOptions().JsonSerializerOptions;
+        options.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
```
Comment (halter73) [inline src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs:186]: This should be the default for `JsonOptions` since it uses `JsonSerializerDefaults.Web`, right?

File: src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs [hunk 4]
```diff
@@ -4,6 +4,7 @@
 using System.Linq;
 using System.Text;
 using System.Text.Json;
+
```
Comment (halter73) [inline src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs:7]:
```suggestion
```

File: src/Shared/HttpValidationProblemDetailsJsonConverter.cs (hunk 1 above)
Comment (halter73) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:71]: I'd be impressed if it still worked. I don't think it's too common for JSON properties to have a `.` in them. Worth checking though.

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:71]: I checked and it did not work, only the first part is converted to camelCase.

File: src/Shared/HttpValidationProblemDetailsJsonConverter.cs (hunk 2 above)
Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: I really do prefer that. Let me give a try because I was trying to keep the code with the minimal changes

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: But i think we will end up with the same issue because of the `.`

File: src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs (hunk 4 above)
Comment (brunolins16) [reply src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs:7]: using System.Text;
using System.Text.Json; 

These are not global usings in this project and they are required for the `System.Text.Encoding` and `System.Text.Json.Utf8JsonReader`

Comment (brunolins16) [reply src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs:7]: However, I can remove `System.Linq` and `Xunit`

File: src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs (hunk 3 above)
Comment (brunolins16) [reply src/Mvc/Mvc.Core/test/Infrastructure/ValidationProblemDetailsJsonConverterTest.cs:186]: I don't think so, based on the source code

https://github.com/dotnet/runtime/blob/27226f631ff5e6019b7da78d350636a6e964aa3c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L147

it will set the `_jsonPropertyNamingPolicy` but not the `_dictionaryKeyPolicy`

File: src/Shared/HttpValidationProblemDetailsJsonConverter.cs (hunk 2 above)
Comment (pranavkm) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: It might be worthwhile trying to make that a S.T.J feature (a new dictionary policy)? The error keys are entirely opaque to the framework, so trying to interpret them as Json paths or .NET object paths by default feels a bit problematic.

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: @pranavkm , i didn't get exactly what you mean about S.T.J feature, sorry about that. The idea is not interpreting the keys as Json Paths, what I am doing is just splitting the text, convert each word to camelCase and join it again. Basically, string manipulation

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: I updated the code to use the JsonSerializer directly, instead of the for + string manipulation, but as expected the results are not right:

Expected:
```json
{
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "property": [
      "error0"
    ],
    "twoWords": [
      "error1"
    ],
    **"topLevelProperty.propertyName"**: [
      "error2"
    ]
  }
}

```
Actual result:
```json
{
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "property": [
      "error0"
    ],
    "twoWords": [
      "error1"
    ],
    **"topLevelProperty.PropertyName"**: [
      "error2"
    ]
  }
}
```

Comment (halter73) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: I'm not sure it's a common enough use case to warrant a S.T.J feature. Do you know of anywhere else we would use it?

Comment (pranavkm) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: Sorry, I'm having a hard time figuring out why we're messing with these keys. Let's say I do this:

```C#
new ValidationProblemDetails
{
   Errors: 
   { 
      ["3.2.Alpha"] = "Some Error"
    }
}
```

Why are we choosing to rewrite the key? Keys are entirely opaque to the framework - they may happen to look like .NET member accessors, but that doesn't mean we should arbitrarily transform them. If System.Text.Json had a feature that said transform all keys to have an arbitrary format and the user configured it feels correct because you opted in. I'm having a hard time trying to see why we would try to do something special here, and why doing that is pertinent.

Comment (halter73) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: > Why are we choosing to rewrite the key? Keys are entirely opaque to the framework - they may happen to look like .NET member accessors, but that doesn't mean we should arbitrarily transform them.

I think this is a reasonable argument for not adding this feature to System.Text.Json. However, based on the amount of feedback on the issue, this seems to be clearly the default behavior customers want from `ValidationProblemDetails.Errors` when using camelCased JSON properties.

The original issue mentioned nothing about the `DictionaryKeyPolicy`. To most people, the fact that the `ValidationProblemDetails.Errors` is a dictionary is merely an implementation detail. They just want the error keys to look like JSON member accessors. Later comments merely point out that a `DictionaryKeyPolicy` couldn't even be used to work around the current behavior.

I don't we should be using `DictionaryKeyPolicy` to gate this behavior especially if we're going to camelCase after every `.` meaning we're not really following any built-in `DictionaryKeyPolicy` to begin with. It would probably be better to continue to ignore the `DictionaryKeyPolicy` in here and gate this on the `PropertyNamingPolicy` instead. It might be *technically* wrong, but it behaves the way people want it to. That said, it would make this change more breaking.

https://github.com/dotnet/aspnetcore/issues/17999#issuecomment-810913391

Comment (pranavkm) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: Is using the DictionaryKeyPolicy but not changing it to do more an option? Users could definitely modify their app to achieve the "right" behavior. I imagine the easiest way for them would be to override `ControllerBase.ValidationProblem` to tweak how the errors dictionary is populated.

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: You both know the source code way more than me and I am probably missing some important facts, so, with this disclaimer :) I would say that based on the issue the full camelCase (after every `.`) is the only behavior accepted and I totally agree that use the `DictionaryKeyPolicy` may not be the best option since we are looking to a behavior not covered by the CamelCase policy.

Also, using the `ControllerBase.ValidationProblem` could be a workaround for users, on the other hand, in my opinion they already had one (rewrite the Converter https://github.com/dotnet/aspnetcore/issues/17999#issuecomment-598241620) that can be applied global instead of changing every controller class to inherit from a new class or override the method every time.

I know that may have already too many options, but one suggestion is not use any of the `System.Text.Json.JsonSerializerOptions`(`DictionaryKeyPolicy` or `PropertyNamingPolicy`) and instead just add a new option to the `Microsoft.AspNetCore.Mvc.JsonOptions`, something like:

``` c#
services.AddControllers().AddJsonOptions(options => 
 {
    options.ModelStateErrorsCamelCase = true
 });
```

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: Just to add an information about the `S.T.J.JsonCamelCaseNamingPolicy` the fact that the second part, after the `.` in my example, is not getting converted to camel case does not have anything related to the `.`. Basically, the method has the following condition that will `break` the `for` operation and skip the next words conversion.

https://github.com/dotnet/runtime/blob/69d75858e0d0d9577b286e0b2aeabc62cd3e383e/src/libraries/System.Text.Json/Common/JsonCamelCaseNamingPolicy.cs#L36
``` c#
if (i == 1 && !char.IsUpper(chars[i]))
{
   break;
}
```

Comment (brunolins16) [reply src/Shared/HttpValidationProblemDetailsJsonConverter.cs:80]: With that, I think updating the code to using the built-in S.T.J feature and not do the full camel case might be the most correct approach to be consistent with the rest of the framework even if that is not exactly the behavior expected by customers but in this case it will, at least, not be expected anywhere we are converting to JSON a dictionary in ASP.NET.

@pranavkm/ @halter73, is that make sense?

**Review by pranavkm — APPROVED** [review]
Cool by me. @brunolins16 if you'd like you could bring this up with @bradygaster during triage and get his take, but I'm happy to sign off on this.

**Review by halter73 — APPROVED** [review]
I think this is an improvement over the current behavior, but I do not think we should close #17999 with this PR because it doesn't solve ["the more general problem here is that model validation errors only include the C# property path, rather than the original input path"](https://github.com/dotnet/aspnetcore/issues/17999#issuecomment-810918926) which is what the issue is really about.

**Comment by brunolins16** [comment]
> I think this is an improvement over the current behavior, but I do not think we should close #17999 with this PR because it doesn't solve ["the more general problem here is that model validation errors only include the C# property path, rather than the original input path"](https://github.com/dotnet/aspnetcore/issues/17999#issuecomment-810918926) which is what the issue is really about.

@halter73 i think it does solve, as much as possible, the initial issue asked in the #17999, however, I totally agree that the more important issue, mentioned in the comment thread, is not resolved but for that I would prefer to add a new issue to discuss more, since I did not touch anything related to that in this PR.
