### PR TITLE
Intermittent System.NullReferenceException thrown at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting #40267

### LINKED ISSUE #40267: Intermittent System.NullReferenceException thrown at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We started to see from time to time this exception being thrown: 

|ERROR|thread-30|Microsoft.AspNetCore.Server.Kestrel| Connection id "0HMFGIT90VKL0", Request id "0HMFGIT90VKL0:00000009": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.<>c.<.cctor>b__12_0(Object state)

This happens intermittently, without any reasons and I can't figure out why is this exception being thrown and what's the root cause. We saw this happening on multiple endpoints. When running a performance test, one request out of 10k requests fails with with this exception. Our application runs on AKS.

### Expected Behavior

Not seeing this exception.

### Steps To Reproduce

_No response_

### Exceptions (if any)

022-02-15 15:25:43.5627|ERROR|thread-30|Platform.Service.ExceptionHandling.ExceptionHandlingMiddleware| An exception was caught in generic exception handler System.ObjectDisposedException: The response has been aborted due to an unhandled application exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.<>c.<.cctor>b__12_0(Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|226_0(HttpProtocol protocol, Stack`1 events)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Platform.Clients.Common.Partitions.PartitionStateMiddleware.Invoke(HttpContext context, IPartitionAccessService partitionAccessService) in /datavolume/agent/_work/16/s/Common/Platform.Clients/Platform.Clients/Common/Partitions/PartitionStateMiddleware.cs:line 34
   at Platform.Clients.Common.Partitions.PartitionMiddleware.Invoke(HttpContext context, IPartitionResolutionStrategy partitionResolutionStrategy) in /datavolume/agent/_work/16/s/Common/Platform.Clients/Platform.Clients/Common/Partitions/PartitionMiddleware.cs:line 24
   at Platform.Service.ExceptionHandling.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext) in /datavolume/agent/_work/16/s/Common/Platform.Service.ExceptionHandling/ExceptionHandlingMiddleware.cs:line 31

### .NET Version

net6.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by asususu**
# Intermittent System.NullReferenceException thrown at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting #40267

**Check List**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

 Null check added to the OnStarting method of Data filter 

Fixes 
#40267

### CODE REVIEW

File: src/Mvc/Mvc.ViewFeatures/src/Filters/SaveTempDataFilter.cs [hunk 1]
```diff
@@ -50,7 +50,7 @@ public void OnResourceExecuting(ResourceExecutingContext context)
     private static Task OnStarting(HttpContext httpContext)
     {
         var saveTempDataContext = GetTempDataContext(httpContext);
-        if (saveTempDataContext.RequestHasUnhandledException)
+        if (saveTempDataContext == null || saveTempDataContext.RequestHasUnhandledException)
```
Comment (pranavkm) [inline src/Mvc/Mvc.ViewFeatures/src/Filters/SaveTempDataFilter.cs:53]:
```suggestion
        if (saveTempDataContext is null || saveTempDataContext.RequestHasUnhandledException)
```

**Review by pranavkm — APPROVED** [review]
