### PR TITLE
Fix #19991 Made TestHost fail when Response Flush is called with AllowSynchronossIO being dissabled

### LINKED ISSUE #19991: TestServer's ResponseBodyWriterStream's Flush should fail if SynchronousIO is not enabled
### Describe the bug
When SyncronousIO is not enabled, [Kestrel's HttpResponseStream's synchronous Flush method](https://github.com/dotnet/aspnetcore/blob/7def10277abbb3086c4ee00e369faf6aa27d676a/src/Servers/Kestrel/Core/src/Internal/Http/HttpResponseStream.cs#L50) fails with an exception. [TestServer's ResponseBodyWriterStream's synchronous Flush](https://github.com/dotnet/aspnetcore/blob/7def10277abbb3086c4ee00e369faf6aa27d676a/src/Hosting/TestHost/src/ResponseBodyWriterStream.cs#L47) does not fail in same conditions. This causes TestServer to produce different behavior from Kestrel's.

This can create false positives in tests using TestServer.

Interestingly, IIS behaves same as TestServer, not Kestrel. Which of these should be correct behavior of synchronous Flush method?

### To Reproduce
Demonstration code : https://github.com/Euphoric/TestServerFlushDemonstration

### Further technical details
- ASP.NET Core version : 3.1.2

### PR DESCRIPTION
**Pull request by Euphoric**
TestHost behaves differently than Kestrel, when Response's synchronous Flush is called. Kestrel fails with an InvalidOperationException, while TestHost works properly. This change should make the two behave the same way.

If any tests fail because of this change, it means the same code would fail running in Kestrel.

Addresses #19991

### CODE REVIEW

File: src/Hosting/TestHost/test/ResponseBodyTests.cs [hunk 1]
```diff
@@ -46,6 +48,80 @@ public async Task BodyWriter_StartAsyncGetMemoryAdvance_AutoCompleted()
             Assert.Equal(length, bytes.Length);
         }
 
+        [Fact]
+        public async Task BodyStream_fails_synchronous_write_when_not_enabled()
```
Comment (Tratcher) [inline src/Hosting/TestHost/test/ResponseBodyTests.cs]: Please follow the naming convention here. `BodyStream_SyncDisabled_WriteThrows`

**Review by Tratcher — CHANGES_REQUESTED** [review]
Looks like this caused several failures in other TestServer tests. There are also failures in ResponseCompression. Please take a look.
https://dev.azure.com/dnceng/public/_build/results?buildId=568952&view=ms.vss-test-web.build-test-results-tab&runId=17857014&resultId=100431&paneView=debug

File: src/Hosting/TestHost/test/ResponseBodyTests.cs (hunk 1 above)
Comment (Euphoric) [reply src/Hosting/TestHost/test/ResponseBodyTests.cs]: Thank you. Wasn't aware that there was naming convention. I looked around at other tests and found there are multiple naming conventions.

**Comment by Euphoric** [comment]
I fixed the tests, but it seems there is some instability failing the build?

File: src/Middleware/ResponseCompression/test/ResponseCompressionMiddlewareTest.cs [hunk 2]
```diff
@@ -592,7 +592,7 @@ public async Task FlushHeaders_SendsHeaders_Compresses(string encoding, int expe
                     {
                         context.Response.Headers[HeaderNames.ContentMD5] = "MD5";
                         context.Response.ContentType = TextPlain;
-                        context.Response.Body.Flush();
+                        await context.Response.Body.FlushAsync();
```
Comment (Tratcher) [inline src/Middleware/ResponseCompression/test/ResponseCompressionMiddlewareTest.cs]: The next test already covers FlushAsync. This test should opt into sync IO so it can test Flush.

Comment (Euphoric) [reply src/Middleware/ResponseCompression/test/ResponseCompressionMiddlewareTest.cs]: Thanks. Should have paid more attention here.
Do you think I should do the same for the other tests. Eg. copy them and create both synchronous and async versions?

Comment (Tratcher) [reply src/Middleware/ResponseCompression/test/ResponseCompressionMiddlewareTest.cs]: I'm not as concerned about them, their code paths are much simpler. Compression is several layers deep so it's more important that we test both code paths.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks
