### PR TITLE
[blazor] fix multiple calls to OnConnectionDownAsync

### LINKED ISSUE #62219: Metric for connected circuits drops to zero when a client disconnects
When I look at the aspnetcore.components.circuit.connected metric for a default Blazor Web App in the .NET Aspire dashboard, the count initially reflects the number of connected clients but then drops to zero when a client disconnects and stays at zero even if more connected circuits are created.

Repro steps:
- Install .NET SDK  10.0.100-preview.5.25277.114
- Create a default Blazor Web app
- Retarget the app to net9.0 and add .NET Aspire orchestration
- Target the app back to net10.0
- Add the `Microsoft.AspNetCore.Components.Server.Circuits` meter in Extensions.cs
- Run the app and view the traces in the Aspire dashboard
- In the app browse to the Counter page in two separate tabs
- The number of active and connected circuits should show as 2
- Close one of the tabs

Expected result: The number of connected circuits drops to 1
Actual result: The number of connected circuits drops to zero and stays at zero even if you open additional tabs to create more connected circuits.

### PR DESCRIPTION
**Pull request by pavelsavara**
- don't call `CircuitHost.OnConnectionDownAsync()` from `CircuitHost.DisposeAsync()` if it's not connected
- don't call `_circuitConnectedCounter.Add` from `CircuitMetrics.OnCircuitDown`
- fix unit test

Fixes https://github.com/dotnet/aspnetcore/issues/62219

image

### CODE REVIEW

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 1]
```diff
@@ -209,7 +209,10 @@ await Renderer.Dispatcher.InvokeAsync(async () =>
 
             try
             {
-                await OnConnectionDownAsync(CancellationToken.None);
+                if (this.Client.Connected)
+                {
+                    await OnConnectionDownAsync(CancellationToken.None);
+                }
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: I don't think this is the right change to fix the metric issue. It's changing an existing behavior of the system that users might be relying on.

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: this event is called twice. That's a bug not a feature

Comment (ilonatommy) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: What is causing the 2nd call?

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: The proper event is `Hub.OnDisconnect()`

`CircuitHost.OnConnectionDownAsync()` is called from `CircuitHost.DisposeAsync()` regardless if it's connected or not, creating dis-balance. 

Image

Image

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: @javiercn does this make sense or you have another proposal for the fix ?

Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: I think it makes sense, but I think it might not be potentially right to just check `Client.Connected`. 

I might be wrong, but I suspect there are two paths that we care about.
* Hub.OnDisconnect which I imagine calls client.SetDisconnected and then eventually calls dispose?
* The other one is when we terminate the circuit (client navigates away or closes the tab) gracefully.
  * https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/CircuitDisconnectMiddleware.cs

So, I think that if we check on this, we run the risk of not running the handlers during termination. We might need to mark the host as terminating or something similar to differentiate between the two cases and choose when to run the handlers.

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: I just tested the "close tab" and "navigate to non-interactive page". Both behave as expected, that is, they call the event once.

Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: Terminate it's not being fired in those cases.
* Close tab will likely don't cause `unload` to fire.
* `navigate to non-interactive page` 
  * It takes a bit of time for the client to start the circuit disposal.
  * If for some reason it's not happening, it's also a bug.

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/CircuitDisconnectMiddleware.cs#L81-L87

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/Circuits/CircuitRegistry.cs#L391

If we check for the circuit to be connected it won't fire when we want to eagerly terminate the circuit.

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: Maybe we need to call that event from places that call `circuitHost.Client.SetDisconnected()` rather than relying that `circuitHost.DisposeAsync()` would always call it.

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: Also I'm not sure that the new `PauseAndDisposeCircuitHost` is calling `SetDisconnected()`

Comment (pavelsavara) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: I made the calls to `OnConnectionDownAsync` more explicit now, instead of relying on the `DisposeAsync`.

@javiercn please review again.

File: src/Components/Server/src/Circuits/CircuitRegistry.cs [hunk 2]
```diff
@@ -135,12 +135,12 @@ protected virtual bool DisconnectCore(CircuitHost circuitHost, string connection
...
         Debug.Assert(result, "This operation operates inside of a lock. We expect the previously inspected value to be still here.");
 
-        circuitHost.Client.SetDisconnected();
+        var previouslyConnected = circuitHost.SetDisconnected();
         RegisterDisconnectedCircuit(circuitHost);
 
         Log.CircuitMarkedDisconnected(_logger, circuitId);
 
-        return true;
+        return previouslyConnected;
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitRegistry.cs]: In which situation can `circuitHost.SetDisconnected()` return false now from within disconnect core?

File: src/Components/Server/src/Circuits/CircuitRegistry.cs [hunk 3]
```diff
@@ -309,6 +309,11 @@ private Task PauseAndDisposeCircuitEntry(DisconnectedCircuitEntry entry)
 
     private async Task PauseAndDisposeCircuitHost(CircuitHost circuitHost, bool saveStateToClient)
     {
+        if (circuitHost.SetDisconnected())
+        {
+            await circuitHost.Renderer.Dispatcher.InvokeAsync(() => circuitHost.OnConnectionDownAsync(default));
+        }
+
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitRegistry.cs]: This is too early to be doing this.

`CircuitPersistenceManager` needs to send the state to the client and needs a connected circuit to do that.

Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitRegistry.cs]: Also, persisting state should happen before `OnConnectionDown`.

**Review by javiercn — COMMENTED** [review]
Rather than restructure the code in the current way. Isn't it simpler and safer to make `OnConnectionDown` "idempotent"? Keeping a flag when you run it and resetting it with `OnConnectionUp`.

That way we save ourselves the trouble of having to worry about when `OnConnectionDown` should run and the change is localized into a single file and can be easily tested.

I worry that the current approach introduces subtle behavior changes and require us to carefully consider the correctness of all the locations where we are now explicitly handling the callbacks.

**Comment by pavelsavara** [comment]
> Rather than restructure the code in the current way. Isn't it simpler and safer to make `OnConnectionDown` "idempotent"? Keeping a flag when you run it and resetting it with `OnConnectionUp`.

`CircuitHost.Client.Connected` could be such flag. The problem is that we don't maintain it properly in all scenarios.
I attempted to fix the `PauseAndDisposeCircuitHost` but I agree that this is fragile is there are other scenarios which I missed.

Also the `OnConnectionDown` event doesn't reset it. But should it ?

If we rather introduce a new flag, should it be `bool CircuitHost.OnConnectionDownFired` ?

> That way we save ourselves the trouble of having to worry about when `OnConnectionDown` should run and the change is localized into a single file and can be easily tested.

Do you mean that we only fire `OnConnectionDown` on when the flag is true ? Or you mean that metrics would not be counted when the flag is down.

> I worry that the current approach introduces subtle behavior changes and require us to carefully consider the correctness of all the locations where we are now explicitly handling the callbacks.

In other words, do you want to fix double-firing of `OnConnectionDown` for other subscribers or keep the current behavior.

Anyway, I'll give it a try with a new flag and I'll improve the fix for `PauseAndDisposeCircuitHost`

**Review by javiercn — APPROVED** [review]
