### PR TITLE
Skip indexer properties in validation source generator

### LINKED ISSUE #65424: Validations in minimal APIs fails on several types from System.Text.Json
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

With data annotation based validation enabled in minimal APIs, the validation subsystem throws an unhandled exception if it encounters a request that is a `JsonElement` or `JsonDocument` or is a type that contains a public property with one of those types.

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Property 'this[]' not found on type 'JsonElement'.
```

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-10.0#validation-support-in-minimal-apis

### Expected Behavior

I expect these types to be acceptable, as is, I need to change the request or request property type to `string` or maybe `BinaryData` and perform serialization in the endpoint handler or accept the raw `HttpRequest.Body` stream.

### Steps To Reproduce

```csharp
builder.Services.AddValidation();

app.MapPost("/test", ([FromBody] JsonElement request) => 
{
    // ...
});
```

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Property 'this[]' not found on type 'JsonElement'.
         at Microsoft.Extensions.Validation.ValidatablePropertyInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateMembersAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatablePropertyInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateMembersAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatablePropertyInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateMembersAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableTypeInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.Extensions.Validation.ValidatableParameterInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Validation.ValidationEndpointFilterFactory.<>c__DisplayClass1_0.<<Create>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
```

### .NET Version

.NET 10

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fixes #65424

The validation source generator crashes at runtime when encountering types with indexers (e.g. `JsonElement`, `Dictionary<K,V>`) used as minimal API endpoint parameters with `AddValidation()` enabled.

The source generator discovers validatable members by iterating `typeSymbol.GetMembers().OfType<IPropertySymbol>()`, but Roslyn exposes C# indexers (`this[int index]`) as `IPropertySymbol` with `Name = "this[]"`. The generator emits these as `ValidatablePropertyInfo` entries. At runtime, `ValidatablePropertyInfo.ValidateAsync` calls `DeclaringType.GetProperty("this[]")`, which returns null because reflection names indexers `"Item"`, causing:

```
System.InvalidOperationException: Property 'this[]' not found on type 'JsonElement'.
```

Confirmed this by decompiling the generated assembly, which showed:
```csharp
new GeneratedValidatablePropertyInfo(
    typeof(JsonElement), typeof(JsonElement), "this[]", "this[]")
```

## Fix

Added `member.IsIndexer` to the existing skip checks in `ExtractValidatableMembers`. Indexers represent parameterized access patterns, not data properties — they aren't meaningful targets for data annotation validation.

## Testing

- Added `SkipsIndexerPropertiesOnTypes` test verifying `JsonElement` works as both a direct parameter and a property on another type, and that validation still runs on non-indexer properties of the containing type.
- Updated `CanValidateParameters` snapshot — `Dictionary<string, TestService>` was previously emitted solely due to its indexer, which would crash at runtime. It's now correctly excluded.
- All 27 generator tests pass.

### CODE REVIEW

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs [hunk 1]
```diff
@@ -210,9 +210,10 @@ internal ImmutableArray<ValidatableProperty> ExtractValidatableMembers(ITypeSymb
         // Handle properties for classes and any properties not handled by the constructor
         foreach (var member in typeSymbol.GetMembers().OfType<IPropertySymbol>())
         {
-            // Skip compiler generated properties and properties already processed via
+            // Skip compiler generated properties, indexers, and properties already processed via
             // the record processing logic above.
             if (member.IsImplicitlyDeclared
```
Comment (DeagleGross) [inline src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs:215]: There is an "interesting" method at PropertyHelper:
https://github.com/dotnet/aspnetcore/blob/45f8aea27cef1b52f2237d17f54839c54b5f9a71/src/Shared/PropertyHelper/PropertyHelper.cs#L537-L555

According to it, we should also skip some other cases:

1. Static members
```csharp
public class Foo
{
    [Required]
    public static string Bar { get; set; } // generator would emit this, runtime would crash
}
```

2. Write-only members
```csharp
public class Foo
{
    [Required]
    public string Secret { set => _secret = value; }
}
```

3. No public getter 
```csharp
public int X { internal get; set; }
```

Should we cover them here as well?
```suggestion
if (member.IsImplicitlyDeclared
    || member.IsIndexer
    || member.IsStatic // STATIC
    || member.IsWriteOnly // THIS AND 3 LINES BELOW CHECK ACCESSIBILITY 
    || member.GetMethod is null
    || member.GetMethod.DeclaredAccessibility is not Accessibility.Public
    || member.IsEqualityContract(wellKnownTypes)
    || resolvedRecordProperty.Contains(member, SymbolEqualityComparer.Default))
{
    continue;
}
```

**Review by DeagleGross — APPROVED** [review]
Nice fix!

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs (hunk 1 above)
Comment (adityamandaleeka) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs:215]: I implemented this locally and tried it out, but it feels like these cases are a bit contrived. But that said, I can't see a reason not to do the fix so I guess I'll push it.

**Comment by adityamandaleeka** [comment]
http2 CI failure is unrelated. Opened #65454 to fix that flakiness.

**Comment by adityamandaleeka** [comment]
This PR is hitting all the flaky tests. Another PR: https://github.com/dotnet/aspnetcore/pull/65456
