### PR TITLE
Make InputRadioGroup preserve child elements

### LINKED ISSUE #31610: InputRadioGroup does not support state preservation for child content
### Describe the bug

A `InputRadioGroup` will _always_ re-render all children and does not support state preservation at all.
The consequence of this, is that focus within a InputRadioGroup will not be retained.

### To Reproduce

https://gist.github.com/Sebazzz/dc33bb9e984774407aa9b9644f356cca

Run and click the button. You will see that the child components of the radio button will show a new date, indicating a re-render happens.

### Further technical details
- ASP.NET Core version: 5.0

This happens because in `OnParametersSet` always a new `_context` is initialized:

https://github.com/dotnet/aspnetcore/blob/368fa1df576be483a8f1e77ecd890ff5d08fef1b/src/Components/Web/src/Forms/InputRadioGroup.cs#L32-L39

In the rendering procedure, this is used as a key value. Always being a new instance, the children will always be deleted and new children created:

https://github.com/dotnet/aspnetcore/blob/368fa1df576be483a8f1e77ecd890ff5d08fef1b/src/Components/Web/src/Forms/InputRadioGroup.cs#L42-L47

### Possible fix

`_context` should be initialized once in the `OnInitialized` *or* only be changed if the groupname or other parameters change.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes #31610 and #39145, and supersedes https://github.com/dotnet/aspnetcore/pull/39208

@MariovanZeist - thanks so much for contributing #39208. I hope you don't mind me coming up with a slightly different solution in this PR. The reasons I wanted to do it differently are:

 * The approach in #39208 is to create a custom system of registering for notification to be re-rendered when an ancestor changes. This happens to be equivalent to what CascadingValue does natively when `IsFixed` is false, so simply by removing the `IsFixed=true` we get the desired behavior without needing a new mechanism.
 * There isn't really any perf drawback to removing the IsFixed=true. Descendants have to be notified to re-render one way or another, because their actual output must change if they become (de)selected. Prior to this fix, the mechanism used `@key` to recreate the entire child hierarchy every time, whereas now it retains the child hierarchy and just triggers the appropriate re-rendering.

The fix could have been reduced to removing these two lines from `InputRadioGroup`:

```cs
        builder.SetKey(_context);
        builder.AddAttribute(1, "IsFixed", true);
```

However, in this PR I also chose to reduce allocations by not creating a new `InputRadioContext` on every render, and instead retaining the existing instance and mutating it in place. It's not particularly complicated to do that but did add quite a few extra changes to the PR diff.

As far as I know, this produces the desired behavior and works as well as the PR at #39208. I verified that it also passes the E2E tests supplied in that PR. But @MariovanZeist, if you have any concerns that the approach here doesn't meet your goals, please let me know!

### CODE REVIEW

File: src/Components/Web/src/Forms/AttributeUtilities.cs [hunk 1]
```diff
@@ -7,7 +7,7 @@ namespace Microsoft.AspNetCore.Components.Forms;
 
 internal static class AttributeUtilities
 {
-    public static string CombineClassNames(IReadOnlyDictionary<string, object>? additionalAttributes, string classNames)
+    public static string? CombineClassNames(IReadOnlyDictionary<string, object>? additionalAttributes, string? classNames)
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/AttributeUtilities.cs:10]: The nullability changes here and below are just because this code actually does work fine with a null `classNames`, and the new code benefits by not having to do a `?? string.Empty`.

File: src/Components/Web/src/Forms/InputRadioContext.cs [hunk 2]
```diff
@@ -8,48 +8,22 @@ namespace Microsoft.AspNetCore.Components.Forms;
 /// </summary>
 internal class InputRadioContext
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/InputRadioContext.cs:9]: I've made this internal type more mutable so that we can retain and update existing instances instead of instantiating a new one on every render.

File: src/Components/Web/src/Forms/InputRadioGroup.cs [hunk 3]
```diff
@@ -30,21 +30,33 @@ public class InputRadioGroup<[DynamicallyAccessedMembers(DynamicallyAccessedMemb
     /// <inheritdoc />
     protected override void OnParametersSet()
     {
-        var groupName = !string.IsNullOrEmpty(Name) ? Name : _defaultGroupName;
-        var fieldClass = EditContext?.FieldCssClass(FieldIdentifier) ?? string.Empty;
-        var changeEventCallback = EventCallback.Factory.CreateBinder<string?>(this, __value => CurrentValueAsString = __value, CurrentValueAsString);
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/InputRadioGroup.cs:35]: We can also avoid creating a new delegate here on every render.

File: src/Components/Web/src/Forms/InputRadioContext.cs (hunk 2 above)
Comment (pranavkm) [reply src/Components/Web/src/Forms/InputRadioContext.cs:9]:
```suggestion
internal sealed class InputRadioContext
```

since it helps the runtime be cleverer with callvirts and such. We need an analyzer for this

File: src/Components/Web/src/Forms/InputRadioGroup.cs [hunk 4]
```diff
@@ -30,21 +30,33 @@ public class InputRadioGroup<[DynamicallyAccessedMembers(DynamicallyAccessedMemb
...
+        else if (_context.ParentContext != CascadedContext)
+        {
+            // This should never be possible in any known usage pattern, but if it happens, we want to know
+            throw new InvalidOperationException("An InputRadioGroup cannot change context after creation");
+        }
 
-        _context = new InputRadioContext(CascadedContext, groupName, CurrentValue, fieldClass, changeEventCallback);
+        // Mutate the InputRadioContext instance in place. Since this is a non-fixed cascading parameter, the descendant
+        // InputRadio/InputRadioGroup components will get notified to re-render and will see the new values.
+        _context.GroupName = !string.IsNullOrEmpty(Name) ? Name : _defaultGroupName;
```
Comment (pranavkm) [inline src/Components/Web/src/Forms/InputRadioGroup.cs:47]: Could you walk me thru how this work? Wouldn't this mean the old and new cascading parameter values are the same instance and so are always the same?

**Comment by MariovanZeist** [comment]
@SteveSandersonMS I prefer this solution over mine, as it's cleaner
I didn't know of this particular _"side effect"_ of having ``IsFixed`` set to ``false``
I guess due to:
https://github.com/dotnet/aspnetcore/blob/6f5aeb71eabbe19155bede07ab029d06a3459d22/src/Components/Components/src/CascadingValue.cs#L125-L128

Always good to learn something new.

All concerns addressed in my PR are also addressed here

File: src/Components/Web/src/Forms/InputRadioGroup.cs (hunk 4 above)
Comment (MariovanZeist) [reply src/Components/Web/src/Forms/InputRadioGroup.cs:47]: @pranavkm 
The cascading parameter values are indeed the same, but because of ``IsFixed`` now being set to false, it will have subscribers. 
When the ``SetParametersAsync(ParameterView parameters)`` of the CascadingValue is called the following code is run

https://github.com/dotnet/aspnetcore/blob/6f5aeb71eabbe19155bede07ab029d06a3459d22/src/Components/Components/src/CascadingValue.cs#L125-L128

And due to the fact that ``ChangeDetection.MayHaveChanged`` will return true for any class parameter,  due to ``NotifySubscribers`` it will eventually end up calling ``IComponent.SetParametersAsync(ParameterView parameters)`` on every ``InputRadio`` component, forcing it to rerender.

Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputRadioGroup.cs:47]: +1 to everything @MariovanZeist said

And to emphasise, this is not some obscure behaviour we’re now relying on, it’s central to how parameter passing and cascaded parameter notifications work. Any possibly-mutable type is always regarded as possibly-changed and hence triggers a re-render.

**Review by javiercn — APPROVED** [review]
