### PR TITLE
Fix response code description in Minimal APIs

### LINKED ISSUE #45192: Incorrect OpenApi documentation in Minimal API when using WithOpenApi extension method
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using .NET 7.0. I have created a Minimal API with the following endpoint:

```
app.MapDelete("api/people/{id:int}", Results<NoContent, NotFound> (int id) =>
{
    return id > 0 ? TypedResults.NoContent() : TypedResults.NotFound();
});
```

This produces the following page in Swagger:

image

In particular, the description of the 404 response is correctly "Not Found".

However, if I add the `WithOpenApi` extension method to the endpoint, like this:

```
app.MapDelete("api/people/{id:int}", Results<NoContent, NotFound> (int id) =>
{
    return id > 0 ? TypedResults.NoContent() : TypedResults.NotFound();
})
.WithOpenApi(operation =>
{
    operation.Summary = "Deletes a person given the ID";
    operation.Description = "If the person does not exist, a 404 response is returned";
    return operation;
});
```

I obtain this:

image

So, the 404 response now has the description "Client error", which is incorrect.

### Expected Behavior

The description of 404 response should be "Not Found" even when I use the `WithOpenApi` extension method.

### Steps To Reproduce

Minimal repro here:  https://github.com/marcominerva/OpenApiIssue.

### Exceptions (if any)

_No response_

### .NET Version

7.0.100

### Anything else?

Visual Studio 2022 17.4.1

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### PR DESCRIPTION
**Pull request by marcominerva**
# Fix response code description when using WithOpenApi in Minimal APIs

When using `WithOpenApi` extension method, the response code description is incorrectly set, for example:

image

In this case, the description for 404 response should be "Not Found". This PR fixes the issue by returning the standard reason phrase for each status code, as defined at: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml.

Fixes #45192

### CODE REVIEW

File: src/OpenApi/src/OpenApiGenerator.cs [hunk 1]
```diff
@@ -31,6 +31,76 @@ internal sealed class OpenApiGenerator
 
     internal static readonly ParameterBindingMethodCache ParameterBindingMethodCache = new();
 
+    private static readonly Dictionary<int, string> Phrases = new()
```
Comment (davidfowl) [inline src/OpenApi/src/OpenApiGenerator.cs:34]: This is built in https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.reasonphrases.getreasonphrase?view=aspnetcore-7.0#microsoft-aspnetcore-webutilities-reasonphrases-getreasonphrase(system-int32)

File: src/OpenApi/src/OpenApiGenerator.cs [hunk 2]
```diff
@@ -212,23 +282,8 @@ private static OpenApiResponses GetOpenApiResponses(MethodInfo method, EndpointM
...
-            '1' => "Information",
-            '2' => "Success",
-            '3' => "Redirection",
-            '4' => "Client error",
-            '5' => "Server error",
-            _ => string.Empty,
-        };
-    }
+    private static string GetResponseDescription(int statusCode)
+        => Phrases.TryGetValue(statusCode, out var phrase) ? phrase : string.Empty;
```
Comment (davidfowl) [inline src/OpenApi/src/OpenApiGenerator.cs:286]:
```suggestion
        => ReasonPhrases.GetReasonPhrase(statusCode);
```

**Review by captainsafia — APPROVED** [review]
