### PR TITLE
Fix FileLoggerProcessorTests

### LINKED ISSUE #34982: Failing Test `HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange`
## Failing Test(s)

- Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange

## Error Message

```text
Assert.Equal() Failure
↓ (pos 0)
Expected: Message two

Actual:

↑ (pos 0)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange() in /_/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs:line 386
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[xUnit.net 00:00:02.26]     Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange [FAIL]
[xUnit.net 00:00:02.26]       Assert.Equal() Failure
[xUnit.net 00:00:02.26]                 â†“ (pos 0)
[xUnit.net 00:00:02.26]       Expected: Message two\n
[xUnit.net 00:00:02.26]       Actual:   
[xUnit.net 00:00:02.26]                 â†‘ (pos 0)
[xUnit.net 00:00:02.26]       Stack Trace:
[xUnit.net 00:00:02.26]         /_/src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs(386,0): at Microsoft.AspNetCore.HttpLogging.FileLoggerProcessorTests.WritesToNewFileOnOptionsChange()
[xUnit.net 00:00:02.26]         --- End of stack trace from previous location ---
[xUnit.net 00:00:03.08]   Finished:    Microsoft.AspNetCore.HttpLogging.Tests

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1272695&view=ms.vss-test-web.build-test-results-tab&runId=37642180&resultId=108945&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by wtgodbe**
Should fix https://github.com/dotnet/aspnetcore/issues/34982, https://github.com/dotnet/aspnetcore/issues/34986

These tests wait for a file to _exist_ before disposing the `FileLoggerProcessor`, but the file exists before it gets written to, so the tests could dispose the logger before it writes, causing the tests to fail. Changing them so they wait until the file exists & has content before disposing. Running these in a loop locally to see if they still fail for me, won't merge this until that's green.

@BrennanConroy remind me of the process here - just mark the 2 test issues "test-fixed" & build-ops will unquarantine after a month if they haven't failed?

### CODE REVIEW

**Comment by BrennanConroy** [comment]
> just mark the 2 test issues "test-fixed" & build-ops will unquarantine after a month if they haven't failed?

Yep, mark them, leave them open, and someone should check them in 30 days.

File: src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs [hunk 1]
```diff
@@ -46,7 +46,7 @@ await using (var logger = new FileLoggerProcessor(new OptionsWrapperMonitor<W3CL
                     // Pause for a bit before disposing so logger can finish logging
                     try
                     {
-                        await WaitForFile(fileName).DefaultTimeout();
+                        await WaitForFile(fileName, 11).DefaultTimeout();
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/test/FileLoggerProcessorTests.cs:49]: Not a huge fan of magic numbers, even if it's a test. Could we extract the message into a variable then string.Length it instead? That way someone doesn't accidentally change the message without updating this value in the future.

And do this for all the tests if you think it's a good idea.

**Review by BrennanConroy — APPROVED** [review]
