### PR TITLE
Give error if the root component is interactive. Fixes #48847

### LINKED ISSUE #48847: Give error if SSR root component has prerendering explicitly disabled
By default, the root component will be SSR-only, which is OK. And if someone marks it with rendermode Server or WebAssembly, it will prerender by default, which is also OK.

**But** if they use `@rendermode new ServerRenderMode(prerender: false)` (or the equivalent for `WebAssemblyRenderMode`) then the initial HTML will just be a marker tag (because no content is being prerendered). This can't do anything useful because then no `<script>` tag can be rendered, and hence the interactive mode can't start anyway.

We can detect this case and throw a clear exception. We just need the `EndpointHtmlRenderer` to explicitly look at the rendermode it's using for the root component and reject it if it disables prerendering.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
For reasoning, see https://github.com/dotnet/aspnetcore/issues/48793#issuecomment-1600922315

Since this is purely a client-side error (and it would already have been an error before; this just changes the error text that comes out) I'm not prioritizing adding an explicit E2E test for it.

### CODE REVIEW

File: src/Components/Endpoints/src/RazorComponentEndpointHost.cs [hunk 1]
```diff
@@ -19,7 +19,6 @@ internal class RazorComponentEndpointHost : IComponent
 {
     private RenderHandle _renderHandle;
 
-    [Parameter] public IComponentRenderMode? RenderMode { get; set; }
```
Comment (SteveSandersonMS) [inline src/Components/Endpoints/src/RazorComponentEndpointHost.cs:22]: This is some unrelated cleanup. This component type is `internal` and we were not actually using this parameter, and it wouldn't be valid to have a root-level rendermode anyway, so it doesn't make sense to leave this vestigial code in place.

**Review by surayya-MS — APPROVED** [review]
Looks good to me

**Review by javiercn — APPROVED** [review]
