### PR TITLE
[Static web assets] Fix casing issues during parsing

### LINKED ISSUE #35328: Blazor hosted project with static folder in different cases
### Describe the bug
In Blazor webassembly hosted project, if the client side has a folder with lowercase name and the server side has a static  uppercase folder name the project will fail on runtime saying System.ArgumentException: 'An item with the same key has already been added. Key: Img'

It worked fine on preview 6 an earlier.

imagen

### To Reproduce
I've uploaded a repo with this issue. Just need to execute the server project. 
https://github.com/CrahunGit/BlazorStaticUppercaseFolders

We will close this issue if:
The case should not be taken account on static folders. It just should be need to merge their contents.

### Exceptions (if any)
System.ArgumentException: 'An item with the same key has already been added. Key: Img'

### Further technical details
- ASP.NET Core version 6 preview 7
- Include the output of `dotnet --info`
SDK de .NET (que refleje cualquier global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual studio 2022 Version 17.0.0 Preview 3.0

### PR DESCRIPTION
**Pull request by javiercn**
Fixes #35328

Static web assets generates a manifest that creates a "virtual file system" that maps content from different folders/locations into the app. That manifest is built as a tree that we parse at runtime and use to map the different file requests to the underlying files.

Each node of the tree represents a folder/file in the path of the "file system". The issue is that when we generate he manifest, we need to preserve all the details about the casing because we don't know the final environment where the app is going to run (for example, within WSL or Docker, where the build has happened on Windows, (this is how tooling works))

This produces the problem that we have a manifest with multiple entries that are case insensitive, and that when we try to parse on windows, nodes that only differ on casing need to be "merged" into a single node.

This doesn't create ambiguity because we already have a process that validates at build time that we don't produce a manifest where more than one asset can target a given request path

### CODE REVIEW

File: src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs [hunk 1]
```diff
@@ -367,9 +366,58 @@ private sealed class OSBasedCaseConverter : JsonConverter<Dictionary<string, Sta
...
+
+                static void MergeChildren(
+                    IDictionary<string, StaticWebAssetNode> newChildren,
+                    IDictionary<string, StaticWebAssetNode> existing)
+                {
+                    foreach (var (key, value) in newChildren)
+                    {
+                        if (!existing.TryGetValue(key, out var existingNode))
+                        {
+                            existing.Add(key, value);
```
Comment (javiercn) [inline src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs:382]: Just point out that while this fix might look a bit "involved", we'll take this branch 99.99% of the time

Comment (SteveSandersonMS) [reply src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs:382]: The logic looks totally reasonable to me.

There might be a case for moving it into some `static` method on `StaticWebAssetNode` itself (e.g., called `CombineMatchingPaths` or `NormalizePaths` or similar. The reason is that, any time anyone adds any new properties to `StaticWebAssetNode`, they would have to update this logic to know how to merge those new properties. But how would they discover that this logic exists? Unless it's in the same place where they have to add the new properties, chances are they won't realise they have to do that.

**Review by SteveSandersonMS — APPROVED** [review]
Looks good. Thanks for fixing this!

File: src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs (hunk 1 above)
Comment (javiercn) [reply src/Shared/StaticWebAssets/ManifestStaticWebAssetFileProvider.cs:382]: I see what you mean.

I'm going to leave it as is for the time being, mostly because I think it's unlikely we'll need to add more properties to it, since it would mean we are doing a big change again (and I would expect at that point to be covered by a test involving casing).
