### PR TITLE
Changed initial culture detection

### LINKED ISSUE #37258: Error about "dynamic culture change while sharding ICU data" no longer always appears in 6.0
Repro:

 * Create a Blazor WebAssembly application
 * Update `Program.cs` to contain:

```cs
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.DefaultThreadCurrentUICulture =
    Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = new CultureInfo("ja-JP");

// ... and now everything that was already there
var builder = WebAssemblyHostBuilder.CreateDefault(args);
// ... etc
```

 * If you want, also test displaying something in this culture by adding to `Index.razor` the output `@((123.45).ToString("c"))`

Expected:

 * On startup, should give the error *Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.*
 * Actual, no error, and the value `@((123.45).ToString("c"))` is rendered as `123 JPY` (i.e., no `¥` symbol)

**This is a regression since 5.0.** If you do the same with the 5.0 SDK, it will produce the error.

However, if you modify the order of the source code to this:

```cs
var builder = WebAssemblyHostBuilder.CreateDefault(args);

CultureInfo.DefaultThreadCurrentCulture = CultureInfo.DefaultThreadCurrentUICulture =
    Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = new CultureInfo("ja-JP");

// ... and now everything that was already there
```

... then it *does* produce the correct error on 6.0. So it seems we've changed how the culture change detection works and made it less robust.

### PR DESCRIPTION
**Pull request by dariatiurina**
# Changed initial culture detection

## Description:

This pull request introduces support for retrieving and managing the application's culture information throughout the Blazor WebAssembly stack. The main changes include adding a new method for accessing the application culture from both JavaScript and .NET, updating initialization logic to use this value, and ensuring the culture can be accessed and tested consistently.

## Logic behind change:

The previously introduced method of checking the initial culture of the application was flawed. In the meaning, it held the culture that was set after before `WebAssemblyHostBuilder.CreateDefault(args)` run as initial. It was not correct. We should assume that culture that runtime detected as default. The additional change in runtime (https://github.com/dotnet/runtime/pull/119269) was made to make this fix possible. 

We as well checked the differences between initial UI culture and the current UI culture, which is not correct, because browser and JS do not divide between UI culture and culture. Therefore some unprompted errors could've been thrown. 

### Changes:
* Added a new method `getApplicationCulture` and implemented it in the runtime configuration setup, allowing JavaScript to expose the application's culture to .NET. 
* Updated initialization logic in `WebAssemblyCultureProvider` to use the culture provided by JavaScript, falling back to invariant culture if unavailable. 
* Extended the `IInternalJSImportMethods` interface and its implementation to include the new `GetApplicationCulture` method, enabling .NET code to retrieve the culture via interop. 
* Modified culture change detection logic to only check for changes in `CurrentCulture` and not `CurrentUICulture`, refining the conditions under which an exception is thrown for unsupported culture changes.

Fixes #37258

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Review by maraf — APPROVED** [review]

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs [hunk 1]
```diff
@@ -32,7 +32,7 @@ internal WebAssemblyCultureProvider(CultureInfo initialCulture, CultureInfo init
     internal static void Initialize()
     {
         Instance = new WebAssemblyCultureProvider(
-            initialCulture: CultureInfo.CurrentCulture,
+            initialCulture: CultureInfo.GetCultureInfo(WebAssemblyCultureProviderInterop.GetApplicationCulture() ?? CultureInfo.InvariantCulture.Name),
             initialUICulture: CultureInfo.CurrentUICulture);
```
Comment (ilonatommy) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: I'm thinking if we shouldn't remove `initialUICulture` from this constructor. It's internal only, currently it's not used anywhere and is a relict of the misconception in previous [PR](https://github.com/dotnet/aspnetcore/pull/31769) that was changing the way we're loading the entry point. Is that correct?

**Review by ilonatommy — APPROVED** [review]
Good job with finding a clean way of passing the config value to the managed code!

We have to wait for the runtime PR to be propagated, other than this and the minor comment, it's perfect.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs (hunk 1 above)
Comment (dariatiurina) [reply src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs]: It is used in the tests, but I will clean it up. Thanks for review! @ilonatommy
