### PR TITLE
[Blazor] Clear caches on HotReload

### LINKED ISSUE #43780: Consider invalidating ComponentProperties cache when Hot Reload triggers metadata update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This cache might need to be invalidated after Hot Reload applies a change since it caches information about properties that can change during the update:
https://source.dot.net/#Microsoft.AspNetCore.Components/Reflection/ComponentProperties.cs,18

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maraf**
Clear more caches when HotReload deltas are applied.

- ComponentProperties (affected by https://github.com/dotnet/runtime/issues/75154)
- DefaultComponentActivator (cleared from renderer, but not sufficient for RazorComponentResult)
- ComponentFactory (cleared from renderer, but not sufficient for RazorComponentResult)
- BindConverter.FormatterDelegateCache
- BindConverter.ParserDelegateCache
- AttributeAuthorizeDataCache
- PersistentStateValueProvider
- EventArgsTypeCache
- RouteTable
- EndpointComponentState

Fixes https://github.com/dotnet/aspnetcore/issues/43780

### CODE REVIEW

File: src/Components/Components/src/Reflection/ComponentProperties.cs [hunk 1]
```diff
@@ -5,12 +5,15 @@
...
 using System.Linq;
 using System.Reflection;
+using Microsoft.AspNetCore.Components.HotReload;
 using static Microsoft.AspNetCore.Internal.LinkerFlags;
 
 namespace Microsoft.AspNetCore.Components.Reflection;
 
 internal static class ComponentProperties
 {
+    static ComponentProperties() => HotReloadManager.Default.OnDeltaApplied += ClearCache;
```
Comment (lewing) [inline src/Components/Components/src/Reflection/ComponentProperties.cs]:
```suggestion
    static ComponentProperties()
    {
        if (HotReloadManager.Default.MetadataUpdateSupported)
        {
            HotReloadManager.Default.OnDeltaApplied += ClearCache;
        }
    }
```

Comment (maraf) [reply src/Components/Components/src/Reflection/ComponentProperties.cs]: We can unify on pattern with check. Currently it's like 50:50

File: src/Components/Shared/src/ExpressionFormatting/ExpressionFormatter.cs [hunk 2]
```diff
@@ -14,7 +14,10 @@ internal static class ExpressionFormatter
 {
     static ExpressionFormatter()
     {
```
[the remark this answers is not in the document]
Comment (maraf) [reply src/Components/Shared/src/ExpressionFormatting/ExpressionFormatter.cs:16]: There is a new line 🤔

File: src/Components/Forms/src/FieldIdentifier.cs [hunk 3]
```diff
@@ -20,7 +20,10 @@ namespace Microsoft.AspNetCore.Components.Forms;
 
     static FieldIdentifier()
     {
```
[the remark this answers is not in the document]
Comment (maraf) [reply src/Components/Forms/src/FieldIdentifier.cs:22]: There is a new line 🤔

**Review by lewing — APPROVED** [review]

**Comment by maraf** [comment]
/ba-g Failure is https://github.com/dotnet/aspnetcore/issues/62672

File: src/Components/Shared/src/ExpressionFormatting/ExpressionFormatter.cs [hunk 4]
```diff
@@ -14,7 +14,10 @@ internal static class ExpressionFormatter
...
-        HotReloadManager.Default.OnDeltaApplied += ClearCache;
+        if (HotReloadManager.Default.MetadataUpdateSupported)
+        {
+            HotReloadManager.Default.OnDeltaApplied += ClearCache;
+        }
```
Comment (javiercn) [inline src/Components/Shared/src/ExpressionFormatting/ExpressionFormatter.cs:20]: nit: is there a reason to check for support instead of just adding the event handler?
