### PR TITLE
HostingLogScope now logs RequestPath as Request.BasePath+Request.Path

### LINKED ISSUE #8942: HostingLogScope should include Request.BasePath
When logging the request path the `HostingLogScope` should also include the`HttpContext.Request.BasePath`. 

At the moment only `HttpContext.Request.Path` is logged. This leads to the unexpected behavior that the URL triggering the request is not necessarily equal to the request path logged. This is the case if for example the `UsePathBaseMiddleware` is used.

I expected the request path logged to always be equal to the triggering URL.

In my opinion both `Path` and `BasePath` should be logged. Either as two separate fields or as concatenation.

### PR DESCRIPTION
**Pull request by penenkel**
fixes #8942

### CODE REVIEW

File: src/Hosting/Hosting/src/Internal/HostingLoggerExtensions.cs [hunk 1]
```diff
@@ -132,7 +132,7 @@ public int Count
             public HostingLogScope(HttpContext httpContext, string correlationId)
             {
                 _traceIdentifier = httpContext.TraceIdentifier;
-                _path = httpContext.Request.Path.ToString();
+                _path = (httpContext.Request.PathBase+httpContext.Request.Path).ToString();
```
Comment (davidfowl) [inline src/Hosting/Hosting/src/Internal/HostingLoggerExtensions.cs]: This always ends up allocating a string. I suggest checking for an empty `PathBase`:

```
_path = (httpContext.Request.PathBase.HasValue ? httpContext.Request.PathBase + httpContext.Request.Path : httpContext.Request.Path).ToString();
```

The majority of request do not have a PathBase.

**Review by Tratcher — APPROVED** [review]

**Comment by davidfowl** [comment]
I just forced a re-run

**Comment by Tratcher** [comment]
Thanks
