### PR TITLE
Fix DefaultProblemDetailsWriter polymorphism

### LINKED ISSUE #45680: DefaultProblemDetailsWriter does not serialize HttpValidationProblemDetails.Errors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Setting `ProblemDetailsContext.ProblemDetails` to an instance of `HttpValidationProblemDetails` and subsequently passing that context instance to `ProblemDetailsService.WriteAsync` does not write out the error details contained on `HttpValidationProblemDetails.Errors`.

This is possibly caused by the fact that [`DefaultProblemDetailsWriter` uses an internal `JsonSerializerContext` if no extensions are added to the problem details instance](https://github.com/dotnet/aspnetcore/blob/2b63a5fc7fee6944af03723767be2335f1d9bf9c/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L54-L71), and that JSON context is only decorated to support the `ProblemDetails` type.

### Expected Behavior

Using `ProblemDetailsService` to write out an `HttpValidationProblemDetails` should include the errors in the resultant JSON content.

### Steps To Reproduce

Create an endpoint filter that will use the `IProblemDetailsService` to write out the JSON content if an endpoint returns `ProblemHttpResult` or `ProblemDetails` directly:

```csharp
public class ProblemDetailsServiceEndpointFilter : IEndpointFilter
{
    public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
        => await next(context) switch
        {
            ProblemHttpResult problemHttpResult => new ProblemDetailsServiceAwareResult(problemHttpResult.StatusCode, problemHttpResult.ProblemDetails),
            ProblemDetails problemDetails => new ProblemDetailsServiceAwareResult(null, problemDetails),
            { } result => result,
            null => null
        };

    private class ProblemDetailsServiceAwareResult : IResult, IValueHttpResult, IValueHttpResult<ProblemDetails>
    {
        private readonly int? _statusCode;

        public ProblemDetailsServiceAwareResult(int? statusCode, ProblemDetails problemDetails)
        {
            _statusCode = statusCode ?? problemDetails.Status;
            Value = problemDetails;
        }

        public ProblemDetails Value { get; }

        object? IValueHttpResult.Value => Value;

        public async Task ExecuteAsync(HttpContext httpContext)
        {
            if (httpContext.RequestServices.GetService<IProblemDetailsService>() is IProblemDetailsService problemDetailsService)
            {
                if (_statusCode is { } statusCode)
                {
                    httpContext.Response.StatusCode = statusCode;
                }
                await problemDetailsService.WriteAsync(new()
                {
                    HttpContext = httpContext,
                    ProblemDetails = Value
                });
            }
        }
    }
}
```

Add two endpoints that return `Results.ValidationProblem`, one with the filter and one without:

```csharp
app.MapGet("/test", () =>
{
    var dict = new Dictionary<string, string[]>();
    dict.Add("Value1", new[] { "Problem 1", "Problem 2" });

    return Results.ValidationProblem(dict);
});

var general = app.MapGroup("").AddEndpointFilter(new ProblemDetailsServiceEndpointFilter());

general.MapGet("/testfiltered", () =>
{
    var dict = new Dictionary<string, string[]>();
    dict.Add("Value1", new[] { "Problem 1", "Problem 2" });

    return Results.ValidationProblem(dict);
});
```

Make requests to both endpoints and observe that the filtered endpoint doesn't include the error details.

### Exceptions (if any)

_No response_

### .NET Version

7.0.200-preview.22605.5

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by brunolins16**
Fix #45680

### CODE REVIEW

File: src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs [hunk 1]
```diff
@@ -59,26 +65,43 @@ public ValueTask WriteAsync(ProblemDetailsContext context)
...
         return new ValueTask(httpContext.Response.WriteAsJsonAsync(
                         context.ProblemDetails,
-                        options: null,
+                        _serializerOptions.GetTypeInfo(problemDetailsType),
                         contentType: "application/problem+json"));
+
+        ValueTask WriteKnownProblemDetailsAsync(ProblemDetailsContext context)
+        {
+            // Use source generation serialization in two scenarios:
+            // 1. There are no extensions. Source generation is faster and works well with trimming.
```
Comment (brunolins16) [inline src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:84]: Not a fan using the internal context but, since converters are internal, I will keep as is until PD AOT support is better discussed.

File: src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs [hunk 2]
```diff
@@ -47,6 +50,126 @@ public async Task WriteAsync_Works()
         Assert.Equal(expectedProblem.Instance, problemDetails.Instance);
     }
 
+    [Fact]
+    public async Task WriteAsync_Works_WithKnownDerivedProblemDetails()
```
Comment (halter73) [inline src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs:54]: Nit:

```suggestion
    public async Task WriteAsync_Works_WithHttpValidationProblemDetails()
```

**Review by halter73 — APPROVED** [review]

File: src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs [hunk 3]
```diff
@@ -39,6 +41,15 @@ public static IServiceCollection AddProblemDetails(this IServiceCollection servi
         services.TryAddSingleton<IProblemDetailsService, ProblemDetailsService>();
         services.TryAddEnumerable(ServiceDescriptor.Singleton<IProblemDetailsWriter, DefaultProblemDetailsWriter>());
 
+        services.PostConfigure<JsonOptions>((options) =>
+        {
+            if (options.SerializerOptions.TypeInfoResolver is not null)
+            {
+                // Combine the current resolver with our internal problem details context
+                options.SerializerOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(options.SerializerOptions.TypeInfoResolver, ProblemDetailsJsonContext.Default);
```
Comment (davidfowl) [inline src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs]: Does combine handle null?

File: src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs [hunk 4]
```diff
@@ -39,6 +41,15 @@ public static IServiceCollection AddProblemDetails(this IServiceCollection servi
         services.TryAddSingleton<IProblemDetailsService, ProblemDetailsService>();
         services.TryAddEnumerable(ServiceDescriptor.Singleton<IProblemDetailsWriter, DefaultProblemDetailsWriter>());
 
+        services.PostConfigure<JsonOptions>((options) =>
```
Comment (davidfowl) [inline src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs]: nit: 
```suggestion
        services.PostConfigure<JsonOptions>(options =>
```

File: src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs [hunk 5]
```diff
@@ -39,6 +41,15 @@ public static IServiceCollection AddProblemDetails(this IServiceCollection servi
...
+        {
+            if (options.SerializerOptions.TypeInfoResolver is not null)
```
Comment (JamesNK) [inline src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs]: What happens if TypeInfoResolver is null?

Also, what happens if `AddProblemDetails` is called multiple times?

File: src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs [hunk 6]
```diff
@@ -15,11 +13,22 @@ internal sealed partial class DefaultProblemDetailsWriter : IProblemDetailsWrite
...
     private readonly ProblemDetailsOptions _options;
+    private readonly JsonSerializerOptions _serializerOptions;
 
-    public DefaultProblemDetailsWriter(IOptions<ProblemDetailsOptions> options)
+    public DefaultProblemDetailsWriter(IOptions<ProblemDetailsOptions> options, IOptions<JsonOptions> jsonOptions)
     {
         _options = options.Value;
+        _serializerOptions = new JsonSerializerOptions(jsonOptions.Value.SerializerOptions);
+
+        if (_serializerOptions.TypeInfoResolver is not null)
```
Comment (JamesNK) [inline src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: What happens if TypeInfoResolver is null?

Comment (brunolins16) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: In `non-aot scenario` it will use the reflection-based resolver, so, we don't really need to include our internal context. In `AOT` scenario, unless your application only serializes `Problem Details`, it should not be null and if it is null not adding our internal context seems might be bad but probably it will fail elsewhere first. Make sense?

Comment (JamesNK) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: But it seems to me that if `TypeInfoResolver` is null then this type can't work. Should there be a check that if IsDynamicCodeSupported is false and `TypeInfoResolver` is null then error?

I think a comment here would be useful for future devs.

Comment (brunolins16) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: Interesting idea. Do you think error is enough or should we set our context in this case? I believe setting our context could hide the configuration issue and make it harder to understand.

Comment (JamesNK) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: I don't know. If the problem is configuration, then IMO throwing here with a helpful error message is better than pretending things are ok and then later failing when serialization happens with an obscure error message.

Comment (brunolins16) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs:25]: @JamesNK  I have been thinking about this and maybe we shouldn't throw during the configuration because it could be too earlier to make sure a problem details will not be able to be serializer. I am saying that because in a situation where the user added a custom `IProblemDetailsWriter` that could serializer a `ProblemDetails` in a different format (eg, `XML`) throwing because the `JsonContext` was not configured correctly might be wrong. What do you think?

File: src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs [hunk 7]
```diff
@@ -38,6 +41,19 @@ public static IServiceCollection AddProblemDetails(this IServiceCollection servi
...
         services.TryAddSingleton<IProblemDetailsService, ProblemDetailsService>();
         services.TryAddEnumerable(ServiceDescriptor.Singleton<IProblemDetailsWriter, DefaultProblemDetailsWriter>());
+        services.PostConfigure<JsonOptions>(options =>
+        {
+            if (options.SerializerOptions.TypeInfoResolver is not null)
+            {
+                if (options.SerializerOptions.IsReadOnly)
+                {
+                    options.SerializerOptions = new(options.SerializerOptions);
+                }
```
Comment (brunolins16) [inline src/Http/Http.Extensions/src/ProblemDetailsServiceCollectionExtensions.cs:51]: This is needed because of https://github.com/dotnet/runtime/issues/80527.

File: src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs (hunk 6 above)
Comment (davidfowl) [reply src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs]: I agree with @brunolins16, I don't think we should throw because the TypeInfoResolver is null. That shouldn't come from this code. Feels like something more top level and central as a whole. Its part of the "how does the user know they need to set a context" in the first place.

File: src/Http/Http.Extensions/src/ProblemDetailsJsonContext.cs [hunk 8]
```diff
@@ -0,0 +1,17 @@
...
+using System.Text.Json;
+using Microsoft.AspNetCore.Mvc;
+
+namespace Microsoft.AspNetCore.Http;
+
+[JsonSerializable(typeof(ProblemDetails))]
+[JsonSerializable(typeof(HttpValidationProblemDetails))]
+// Additional values are specified on JsonSerializerContext to support some values for extensions.
+// For example, the DeveloperExceptionMiddleware serializes its complex type to JsonElement, which problem details then needs to serialize.
+[JsonSerializable(typeof(JsonElement))]
```
Comment (davidfowl) [inline src/Http/Http.Extensions/src/ProblemDetailsJsonContext.cs:14]: This should be removed eventually.

**Review by davidfowl — APPROVED** [review]
