### PR TITLE
Cookie Auth: Fix bug with ticket store

### LINKED ISSUE #41516: Cookie authentication handler calls `SessionStore.RenewAsync()` on sign in with expired session.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `CookieAuthenticationHandler` will call `Options.SessionStore.RemoveAsync(_sessionKey, ...)` during authentication as part of `ReadCookieTicket()` if the ticket loaded from the SessionStore is expired.

If during the same request we attempt to sign in again, the `HandleSignInAsync()` will call `Options.SessionStore.RenewAsync(_sessionKey, ...);`.

Depending on the SessionStore implementation, RenewAsync might throw an exception if it expects the session to still exist at the time it is called.

This appears to be caused by the changes from https://github.com/dotnet/aspnetcore/pull/22732, attempting to fix https://github.com/dotnet/aspnetcore/issues/22135.

The only workaround I can think of is to design the implementation of RenewAsync such that it adds back the session if it no longer exists. Is this assumption correct? Is this even safe?

### Expected Behavior

After calling `Options.SessionStore.RemoveAsync(_sessionKey, ...)`, the private `_sessionKey` field ought to be reset to null. This way a new session is correctly stored on sign in.

### Steps To Reproduce

1. Sign in with cookie authentication.
2. Wait for the ticket to expired.
3. Execute a request which calls SignIn for cookie authentication, and attempts to renew the expired session.

### Exceptions (if any)

_No response_

### .NET Version

6.0.202

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/41516

Also adds 2 basic tests for the ticket store

### CODE REVIEW

File: src/Security/Authentication/test/CookieTests.cs [hunk 1]
```diff
@@ -147,6 +147,107 @@ public async Task SignInCausesDefaultCookieToBeCreated()
...
+        _clock.Add(TimeSpan.FromDays(60));
+
+        // Verify that a new session is generated with a new key
+        var transaction3 = await SendAsync(server, "http://example.com/signinalice", transaction1.CookieNameValue);
+
+        var transaction4 = await SendAsync(server, "http://example.com/me/Cookies", transaction3.CookieNameValue);
+
+        var key2 = Assert.Single(sessionStore.Store.Keys);
+        Assert.Equal("Alice", FindClaimValue(transaction4, ClaimTypes.Name));
+        Assert.NotEqual(key1, key2);
```
Comment (HaoK) [inline src/Security/Authentication/test/CookieTests.cs:216]: Note: this is the assertion for the bug, where without the fix, key1/key2 will be equal

**Review by Tratcher — APPROVED** [review]
