### PR TITLE
Address API review feedback for what was IApiEndpointMetadata

### LINKED ISSUE #62883: API Proposal for IApiEndpintMetadata
## Background and Motivation

This proposal introduces `IApiEndpointMetadata` as a new public API in ASP.NET Core. The goal is to provide a standardized metadata interface for identifying API endpoints. The primary use case is to avoid cookie login redirects for known API endpoints.

This metadata is automatically applied to endpoints in several scenarios:
- Endpoints using RDF/RDG that read a JSON request body or write a JSON response body.
- Endpoints attributed with `ApiController`.
- SignalR endpoints.
- Endpoints with `TypedResults` return types that are recognized as API-oriented.

This change aims to improve discoverability and handling of API endpoints in ASP.NET Core, particularly for scenarios like avoiding cookie login redirects for APIs.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

+ public interface IApiEndpointMetadata
+ {
+ }
```

No new attributes or extension methods are introduced in this PR, but the `IApiEndpointMetadata` interface is automatically assigned to qualifying endpoints.

## Usage Examples

```csharp
// Example: Checking for API endpoint metadata in middleware
public class ApiEndpointMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        var endpoint = context.GetEndpoint();
        if (endpoint?.Metadata.GetMetadata<IApiEndpointMetadata>() != null)
        {
            // This is an API endpoint, apply API-specific logic
        }
        await next(context);
    }
}

// Example: Custom endpoint definition
app.MapPost("/api/data", (MyData data) =>
{
    // This endpoint will automatically get IApiEndpointMetadata
    return Results.Json(data);
});
```

## Alternative Designs

- Alternative approaches considered include using attributes or extension methods to mark API endpoints, but the chosen design leverages automatic assignment based on endpoint characteristics.
- Compared to other ecosystems, this is similar to how frameworks like Spring Boot or Express.js identify API routes via metadata or decorators.

## Risks

- Automatic assignment of metadata may result in unexpected behavior if endpoints are misclassified.
- There is a minimal risk of breaking changes for existing middleware or components that inspect endpoint metadata.
- Potential performance impact due to additional metadata checks, though expected to be negligible.

### PR DESCRIPTION
**Pull request by halter73**
- We've now replaced IApiEndpointMetadata with IDisableCookieRedirectMetadata
- We also added IAllowCookieRedirectMetadata and corresponding extension methods
- We only added one attribute, [AllowCookieRedirect] for now, since [ApiController] adds IDisableCookieRedirectMetadata already
- Add's an AppContext swithc to revert to the old behavior and ignore metadata called "Microsoft.AspNetCore.Authentication.Cookies.IgnoreRedirectMetadata"

Fixes #62883

### CODE REVIEW

File: src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+
+        // Act
+        var result = builder.AllowCookieRedirect();
+
+        // Assert
+        Assert.Same(builder, result);
+    }
+
+    [Fact]
+    public void DisableCookieRedirect_WithMultipleCalls_AddsSingleMetadata()
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs]: It adds multiple though?

**Review by BrennanConroy — APPROVED** [review]

File: src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        var builder = new TestEndpointConventionBuilder();
+
+        // Act
+        builder.AllowCookieRedirect();
+        builder.AllowCookieRedirect();
+
+        // Assert
+        Assert.Equal(2, builder.Metadata.Count);
+        Assert.All(builder.Metadata, metadata => Assert.IsAssignableFrom<IAllowCookieRedirectMetadata>(metadata));
+    }
```
Comment (halter73) [inline src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs]:
```suggestion
```

File: src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs (hunk 1 above)
Comment (halter73) [reply src/Http/Http.Extensions/test/CookieRedirectEndpointConventionBuilderExtensionsTests.cs]: I removed the tests that do multiple calls. They aren't very interesting since the expected behavior is that it always adds metadata once per call.
