### PR TITLE
[MVC][Fixes #7576]HtmlHelperOptions.ClientValidationEnabled = false is ignored in Razor Pages

### LINKED ISSUE #7576: HtmlHelperOptions.ClientValidationEnabled = false is ignored
`services.AddMvc().AddViewOptions(o =>
            {
                if (_env.IsDevelopment())
                {
                    o.HtmlHelperOptions.ClientValidationEnabled = false;
                }
            })`
is currently not working on the register page of the asp.net identity template.

### PR DESCRIPTION
**Pull request by javiercn**
Changes it to resolve the right options

### CODE REVIEW

File: src/Mvc/Mvc.RazorPages/src/Infrastructure/PageActionInvokerProvider.cs [hunk 1]
```diff
@@ -52,7 +52,7 @@ internal class PageActionInvokerProvider : IActionInvokerProvider
             IModelBinderFactory modelBinderFactory,
             ITempDataDictionaryFactory tempDataFactory,
             IOptions<MvcOptions> mvcOptions,
-            IOptions<HtmlHelperOptions> htmlHelperOptions,
+            IOptions<MvcViewOptions> mvcViewOptions,
```
Comment (pranavkm) [inline src/Mvc/Mvc.RazorPages/src/Infrastructure/PageActionInvokerProvider.cs]: Could we get an E2E test for this so we don't inadvertently break it? We would have caught that this didn't work the first time around had we written one

Comment (javiercn) [reply src/Mvc/Mvc.RazorPages/src/Infrastructure/PageActionInvokerProvider.cs]: Added a test to make you happy.

File: src/Mvc/test/Mvc.FunctionalTests/ClientValidationOptionsTests.cs [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+using BasicWebSite;
+using Microsoft.AspNetCore.Hosting;
+using Xunit;
+
+namespace Microsoft.AspNetCore.Mvc.FunctionalTests
+{
+    public class ClientValidationOptionsTests : IClassFixture<MvcTestFixture<BasicWebSite.StartupClientValidationSettings>>
+    {
+        public ClientValidationOptionsTests(MvcTestFixture<StartupClientValidationSettings> fixture) => 
+            Fixture = fixture;
```
Comment (javiercn) [inline src/Mvc/test/Mvc.FunctionalTests/ClientValidationOptionsTests.cs]: How many pranav points do I get 4 this?

**Review by pranavkm — APPROVED** [review]
