### PR TITLE
Make Virtualize recover from having incorrect ItemSize info. Fixes #25915

### LINKED ISSUE #25915: Blazor Virtualize 22-25 items
extended Weatherservice to 500 records, added a ID property named Counter (incremented)
Changed fetchdata.razor

```
 <Virtualize Items="forecasts" Context="forecast">
                <ItemContent>
                    <tr @key="forecast.Counter">
                        <td>@forecast.Counter</td>
                        <td>@forecast.Date.ToShortDateString()</td>
                        <td>@forecast.TemperatureC</td>
                        <td>@forecast.TemperatureF</td>
                        <td>@forecast.Summary</td>
                    </tr>
                </ItemContent>
                <Placeholder>
                    <tr>
                        <td>Loading...</td>
                    </tr>
                </Placeholder>
            </Virtualize>
```

shows only 22-25 rows in Browser 

- ASP.NET Core version 5 5.0.100-rc.1.20452.10

- Version 16.8.0 Preview 3.0

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes #25915

## Description

If the new `<Virtualize>` component was given a slightly incorrect value for `ItemSize` (or if the default value of 50 was very close to the true value, but not exactly equal), then it could get stuck and fail to display new items while scrolling. This is because it would compute the new set of items to show, and the incorrect size info might tell it that it was already displaying the correct items (even though it's not), and then it would not update the UI.

## Customer impact

This has now been reported by about 4 different customers from preview usage. One example is https://github.com/dotnet/aspnetcore/issues/25915. Another is https://github.com/dotnet/aspnetcore/issues/25915.

Unless fixed, it means developers must work out and supply an exactly-correct value for `ItemSize`. This can be tricky to do because even if you put (say) `style="height: 50px"` on a table row, the browser might actually render it at (say) 48.89px due to border collapse CSS rules. Our goal for `<Virtualize>` was to spare developers from this pain by auto-detecting and fixing the height information. If we don't make that work in all cases, then sometimes the UI can get stuck.

One reason why customers hit this so often is due to an unlucky coincidence. The component's default `ItemSize` when not specified is 50px, and our default project template contains a table whose rows happen to be 48.89px high. This specific combination happens to trigger the problem. But of course it could happen with other sizes too if the true value and the given value are sufficiently close but not exactly equal.

## Regression

No, `<Virtualize>` is new in 5.0.

## Risk

The change is limited to the `<Virtualize>` component, so nothing else will be affected.

Theoretically this change could trigger some other unwanted behavior in `<Virtualize>`. However I've designed this solution to be as risk-averse as possible. We have good E2E test coverage plus manual verification.

There's a good argument that it's inevitable we have to fix this because so many customers are hitting it. It's safer to fix in 5.0 GA than in some later patch, because if it goes out in a patch, then it might land on production webservers before developers even see it running on their local machines.

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
cc @mkArtakMSFT We should consider this for 5.0.

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 1]
```diff
@@ -211,6 +212,33 @@ public void CanUseViewportAsContainer()
...
+            Browser.Equal(expectedInitialSpacerStyle, () => topSpacer.GetAttribute("style"));
+
+            // Scroll slowly, in increments of 50px at a time. At one point this would trigger a bug
+            // due to the incorrect item size, whereby it would not realise it's necessary to show more
+            // items because the first time the spacer became visible, the size calculation said that
+            // we're already showing all the items we need to show.
+            for (var pos = 0; pos < 1000; pos += 50)
+            {
+                Browser.ExecuteJavaScript($"document.getElementById('incorrect-size-container').scrollTop = {pos};");
+                await Task.Delay(200);
```
Comment (pranavkm) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs:233]: Is there a way to see if a specific item is visible instead? We've had trouble in the past where `Task.Delays` in the past where delays haven't been sufficient on slower CI machines.

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs [hunk 2]
```diff
@@ -211,6 +212,33 @@ public void CanUseViewportAsContainer()
...
+            Browser.MountTestComponent<VirtualizationComponent>();
+            var topSpacer = Browser.Exists(By.Id("incorrect-size-container")).FindElement(By.TagName("div"));
+            var expectedInitialSpacerStyle = "height: 0px;";
+
+            // Wait until items have been rendered.
+            Browser.True(() => GetItemCount() > 0);
+            Browser.Equal(expectedInitialSpacerStyle, () => topSpacer.GetAttribute("style"));
+
+            // Scroll slowly, in increments of 50px at a time. At one point this would trigger a bug
+            // due to the incorrect item size, whereby it would not realise it's necessary to show more
```
Comment (pranavkm) [inline src/Components/test/E2ETest/Tests/VirtualizationTest.cs:227]: > realise 

👏

**Review by pranavkm — APPROVED** [review]

File: src/Components/test/E2ETest/Tests/VirtualizationTest.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/test/E2ETest/Tests/VirtualizationTest.cs:233]: The delay isn't waiting for anything to happen in the UI, it's just representing the fact that as a user scrolls by dragging the mouse, it occurs as a series of steps. At some point in this series the bug occurs (if the fix wasn't in this PR), but it's not useful to specify at exactly what point.

**Comment by mkArtakMSFT** [comment]
This was approved by Tactics.
