### PR TITLE
Blazor WebAssembly & WebView JS to .NET Streaming Interop Support

### LINKED ISSUE #27862: Blazor Server & WebAssembly cannot read large file streams from client
### Describe the bug
I want to be able to read files from client browsers using blazor server-side. Using the <InputFile/> component, I choose some test file. If the file size is more than 2-3 GB, I cannot read it.
I am not trying to upload the whole file. You can see that from the sample page.

### To Reproduce
The clean template with just 1 file added
https://github.com/xPucTu4/BlazorUploadBug

You can create new blazor-server project and just add that file:
https://github.com/xPucTu4/BlazorUploadBug/blob/main/BlazorUploadBug/Pages/Upload.razor

### Exceptions (if any)
With file size of about 4GB:
Sometimes JSException with message "[object ProgressEvent]"
With file size of about 3GB there is no exception or any indications of errors.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### LINKED ISSUE #33638: Blazor Support Large File Uploads
I have a working Blazor Web Assembly app that uploads files to Azure Storage (server provides SAS token urls, client upload to that destination). This works a-ok for "small" files the size of a couple 100MBs. However, I now have a 6.8GB file that doesn't - I am using bog standard code along the lines of the documentation:

```
Azure.Response<BlobContentInfo> azresponse = await blobClient.UploadAsync(fileStream, new BlobUploadOptions()
{
  ProgressHandler = new Progress<long>((progress) =>
  {
     vm.ProgressBarPercentage = (int)(100.0 * progress / vm.InputFileSize);
     this.StateHasChanged();
  })
});
```

For this large file, it returns immediately and creates a zero byte file on Azure Storage. I then tried this:

```
 var x = new byte[200];
 int res = await fileStream.ReadAsync(x, 0, 100);
```

Surprisingly, `res` is `0` so I see why the storage library would create a 0 byte file... but I don't get why Blazor behaves that way. (Note: I didn't test to see at what file size this behavior kicks in). I also didn't see anything that would indicate any sort of error. The stream simply isn't returning data.

### PR DESCRIPTION
**Pull request by TanayParikh**
- Adds support for Blazor WebAssembly & WebView JS to .NET Streaming Interop
- Refactored the logic from `RemoteJSDataStream` into a shared `BaseJSDataStream` which is shared across the 3 platforms. Did this instead of putting it into `JSInterop` to avoid creating additional public APIs per Javier's recommendation. 
- TODO:
  - [x] WASM/WebView unhandled exceptions.
  - [x] WebView interop mechanism for `ReceiveJSDataChunk` needs to be refined (potential synchronization issue)
  - [x] Update WASM Baselines to fix CI: https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebAssembly/testassets/WasmLinkerTest
  - [x] WASM try different chunk sizes (will do this after everything else is approved)
  - [x] Tests still need to be refactored a bit to reflect `BaseJSDataStream` (will do this after everything else is approved)

Fixes: https://github.com/dotnet/aspnetcore/issues/33638
Fixes: https://github.com/dotnet/aspnetcore/issues/27862
Part of: https://github.com/dotnet/aspnetcore/issues/30289

### CODE REVIEW

File: src/Components/Web.JS/src/GlobalExports.ts [hunk 1]
```diff
@@ -49,6 +49,7 @@ interface IBlazor {
     dotNetCriticalError?: any
     getSatelliteAssemblies?: any,
     sendJSDataStream?: (data: any, streamId: string, chunkSize: number) => void,
+    sendJSDataStreamWebview?: (data: any, streamId: string, chunkSize: number, jsDataStream: any) => void,
```
Comment (TanayParikh) [inline src/Components/Web.JS/src/GlobalExports.ts:52]: This is so we can provide a `JSDataStream` `DotNetObjectReference` to call `ReceiveJSDataChunk` on.

File: src/Components/Web.JS/src/Platform/WebView/WebViewStreamingInterop.ts [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+                const nextChunkData = btoa(String.fromCharCode.apply(null, nextChunkByteArray as unknown as number[]));
+
+                const streamIsAlive = await jsDataStream.invokeMethodAsync('ReceiveData', chunkId, nextChunkData, null);
+
+                // Checks to see if we should continue streaming or if the stream has been cancelled/disposed.
+                if (!streamIsAlive) {
+                    break;
+                }
+
+                // send('ReceiveJSDataChunk', streamId, chunkId, nextChunkData, null);
```
Comment (TanayParikh) [inline src/Components/Web.JS/src/Platform/WebView/WebViewStreamingInterop.ts:25]: Using `DotNetObjectReference<JSDataStream>` vs the more traditional `send` via the `IpcSender`. This was done due to a potential synchronization issue in WebView (offline discussion).

File: src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs [hunk 3]
```diff
@@ -36,6 +35,8 @@ protected override async ValueTask<int> CopyFileDataIntoBuffer(long sourceOffset
                 SourceOffset = sourceOffset
             };
 
+            // We don't leverage the streaming mechanism directly as we want JavaScript to populate the 
+            // pre-allocated .NET memory.
```
Comment (TanayParikh) [inline src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs:39]: How important is this? Should we simplify this and just utilize streaming? This essentially works off of a `pull` model which breaks with the more `push` oriented way we do streaming elsewhere. This is why I avoided taking this approach with the `WebAssemblyJSDataStream.ReceiveData` to ensure implementation consistency & simplicity.

File: src/Components/WebView/WebView/src/Services/WebViewJSDataStream.cs [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+            _webviewJSRuntime = runtime;
+        }
+
+        protected override void RaiseUnhandledException(Exception exception)
+        {
+            _webviewJSRuntime.RaiseUnhandledException(exception);
+        }
+
+        [JSInvokable("ReceiveData")]
+        public Task<bool> ReceiveDataFromJS(long chunkId, byte[] chunk, string error)
```
Comment (TanayParikh) [inline src/Components/WebView/WebView/src/Services/WebViewJSDataStream.cs:62]:
```suggestion
        [JSInvokable("ReceiveJSDataChunk")]
        public Task<bool> ReceiveJSDataChunk(long chunkId, byte[] chunk, string error)
```

File: src/Components/Shared/src/BaseJSDataStream.cs [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+
+        public override async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
+        {
+            var linkedCancellationToken = GetLinkedCancellationToken(_streamCancellationToken, cancellationToken);
+            return await _pipeReaderStream.ReadAsync(buffer, linkedCancellationToken);
+        }
+
+        private static CancellationToken GetLinkedCancellationToken(CancellationToken a, CancellationToken b)
+        {
+            if (a.CanBeCanceled && b.CanBeCanceled)
```
Comment (pranavkm) [inline src/Components/Shared/src/BaseJSDataStream.cs:156]: `CreateLinkedTokenSource` already does this. You don't need to do this here.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs [hunk 6]
```diff
@@ -102,13 +101,29 @@ protected override void SendByteArray(int id, byte[] data)
...
                 default:
                     throw new InvalidOperationException($"Invalid result type '{resultType}'.");
             }
         }
 
+        private IJSStreamReference DeserializeJSStreamReference(string serializedStreamReference)
+        {
+            var receivedBytes = Encoding.UTF8.GetBytes(serializedStreamReference);
+            var reader = new Utf8JsonReader(receivedBytes);
+            var jsStreamReference = JsonSerializer.Deserialize<IJSStreamReference>(ref reader, JsonSerializerOptions);
```
Comment (pranavkm) [inline src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:117]: Why can't you call `JsonSerializer.Deserialize<IJSStreamReference>(serializedStreamReference, JsonSerializerOptions);`?

File: src/Components/Server/src/Circuits/RemoteJSDataStream.cs [hunk 7]
```diff
@@ -53,7 +41,7 @@ public static async Task<bool> ReceiveData(RemoteJSRuntime runtime, long streamI
                 Math.Min(maximumIncomingBytes, 50*1024) - 512 :
                 throw new ArgumentException($"SignalR MaximumIncomingBytes must be at least 1 kb.");
 
-            var streamId = runtime.RemoteJSDataStreamNextInstanceId++;
+            var streamId = runtime.JSDataStreamNextInstanceId++;
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/RemoteJSDataStream.cs:44]: Are all calls to this going thru the sync context (should we be concerned about concurrency at all here)?

File: src/Components/Shared/src/BaseJSDataStream.cs [hunk 8]
```diff
@@ -0,0 +1,198 @@
...
+
+#if COMPONENTS_SERVER
+namespace Microsoft.AspNetCore.Components.Server.Circuits
+#elif BLAZOR_WEBVIEW
+namespace Microsoft.AspNetCore.Components.WebView
+#elif BLAZOR_WEBASSEMBLY
+namespace Microsoft.AspNetCore.Components.WebAssembly.Infrastructure
+#endif
+{
+    internal abstract class BaseJSDataStream : Stream
```
Comment (pranavkm) [inline src/Components/Shared/src/BaseJSDataStream.cs:20]: An alternative to deriving would be to give this delegates that this type invokes (my guess is all you need is the Unhandled exception handler). It doesn't look like deriving from this type gives you any particular benefits.

File: src/Components/Server/src/Circuits/RemoteJSDataStream.cs (hunk 7 above)
Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSDataStream.cs:44]: Yes, [we're going through the sync context](https://github.com/dotnet/aspnetcore/blob/8adbdc6d2559d55469aeaf1feae8061df5c27af2/src/Components/Server/src/Circuits/CircuitHost.cs#L431-L434) so parallel invocations of `ReceiveData` should not be a factor (hence `++` instead of `Increment`.

File: src/Components/Shared/src/BaseJSDataStream.cs [hunk 9]
```diff
@@ -0,0 +1,198 @@
...
+using System;
+using System.Collections.Generic;
+using System.IO;
+using System.IO.Pipelines;
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.JSInterop;
+
+#if COMPONENTS_SERVER
+namespace Microsoft.AspNetCore.Components.Server.Circuits
```
[the remark this answers is not in the document]
Comment (TanayParikh) [reply src/Components/Shared/src/BaseJSDataStream.cs:13]: You're right there isn't really a point in doing this, I'll move this to:
```
namespace Microsoft.AspNetCore.Components
```

File: src/Components/Shared/src/BaseJSDataStream.cs (hunk 5 above)
Comment (TanayParikh) [reply src/Components/Shared/src/BaseJSDataStream.cs:156]: @BrennanConroy raised a concern in a prior PR about how `LinkedCancellationToken` always allocates. Reviewing [the source](https://github.com/dotnet/runtime/blob/fe9a54df8f4b5e6a2e4cafc0e4234a64e8c9cf8e/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L740-L786), that does appear to be the case.

**Comment by TanayParikh** [comment]
@javiercn @SteveSandersonMS could I please get a review, hoping to get it in for Preview 7.

File: src/Components/Shared/src/BaseJSDataStream.cs (hunk 8 above)
Comment (TanayParikh) [reply src/Components/Shared/src/BaseJSDataStream.cs:20]: Tried this out, however it seems to complicate things quote a bit for WebAssembly/WebView which use a `DotNetObjectReference` of the `Web{Assembly, View}JSDataStream` with platform specific implementations of `ReceiveJSDataChunk`.

File: src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.csproj [hunk 10]
```diff
@@ -7,6 +7,7 @@
     <!-- Workaround for https://github.com/dotnet/runtime/issues/52227 -->
     <NoWarn>$(NoWarn);CS8603</NoWarn>
     <GenerateDocumentationFile>true</GenerateDocumentationFile>
+    <DefineConstants>$(DefineConstants);BLAZOR_WEBASSEMBLY</DefineConstants>
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly/src/Microsoft.AspNetCore.Components.WebAssembly.csproj:10]: This no longer seems to be used.

```suggestion
```

File: src/Components/WebAssembly/WebAssembly/src/Infrastructure/WebAssemblyJSDataStream.cs [hunk 11]
```diff
@@ -0,0 +1,89 @@
...
+                // There is no data stream with the given identifier. It may have already been disposed.
+                // We notify JS that the stream has been cancelled/disposed.
+                return false;
+            }
+
+            var data = Array.Empty<byte>();
+            if (string.IsNullOrEmpty(error))
+            {
+                // Ideally this byte array would be transferred directly as a parameter on this
+                // call, however that's not currently possible due to: https://github.com/dotnet/runtime/issues/53378
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly/src/Infrastructure/WebAssemblyJSDataStream.cs:74]: I'm confused about this. I thought that https://github.com/dotnet/runtime/issues/53378 referred to an underlying issue in the runtime which, for `[JSInvokable]`, we've already implemented our own workaround. If that is the case, and since this is a `[JSInvokable]` method, why doesn't it work it receive a `byte[]` as a regular parameter here?

If this is the case, can we simplify things by unifying the implementation between webassembly and webview, since they both should just be able to build on the binary interop support?

Or am I missing something?

File: src/Components/Web.JS/src/Platform/WebView/WebViewStreamingInterop.ts [hunk 12]
```diff
@@ -0,0 +1,15 @@
+import { sendJSDataStreamUsingObjectReference } from "../../StreamingInterop";
+
+export async function sendJSDataStreamWebView(data: ArrayBufferView | Blob, streamId: number, chunkSize: number, dotnetStreamReference: any) {
+    async function send(streamId: number, chunkId: number, nextChunkData: Uint8Array | null, error: string | null): Promise<boolean> {
+        if (error) {
+            await dotnetStreamReference.invokeMethodAsync('ReceiveJSDataChunk', streamId, -1, '', error.toString());
+            return false;
+        }
+
+        const nextChunkDataStr = btoa(String.fromCharCode.apply(null, nextChunkData as unknown as number[]));
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Platform/WebView/WebViewStreamingInterop.ts:10]: Don't we have the ability to pass binary data without base64-encoding it now?

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Platform/WebView/WebViewStreamingInterop.ts:10]: I mean, I know the underlying implementation if JS interop for WebView will actually base64 encode it, but that's an internal implementation detail of jsObjectReference.invokeMethodAsync, isn't it?

File: src/Components/Web.JS/src/StreamingInterop.ts [hunk 13]
```diff
@@ -0,0 +1,54 @@
...
+        try {
+            const byteLength = data instanceof Blob ? data.size : data.byteLength;
+            let position = 0;
+            let chunkId = 0;
+
+            while (position < byteLength) {
+                const nextChunkSize = Math.min(chunkSize, byteLength - position);
+                let nextChunkData = await getNextChunk(data, position, nextChunkSize);
+
+                const streamIsAlive = await send(streamId, chunkId, nextChunkData, null);
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/StreamingInterop.ts:40]: At first I was surprised to see a push-based transfer mechanism for WebAssembly, because I would have expected this to completely block the UI thread until the transfer is complete. Does it not block the UI thread because, on the .NET side, it's feeding things into a `Pipe` which imposes backpressure?

TBH I would have expected a much simpler model to be pull-based for WebAssembly and WebView. The actual `Stream` instance could directly fetch an arbitrarily large block of data in a single chunk, whenever the .NET side tried to read from the stream. There would be no `Pipe` and much of the other orchestration logic would disappear completely. We wouldn't need to do anything tricky with layering to share logic between Server and WebAssembly/WebView, because the WebAssembly/WebView code would be very minimal and different from Server (though identical for the two of them).

Is that not possible, or do you think it's actually more complicated? Or is it worth trying?

File: src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs:39]: Thanks for the comment about using the pre-allocated memory. That does explain some of the implementation.

TBH, given the very significant amount of extra complexity this brings, and the fact that streaming transfer is not something that happens commonly on the perf-critical render path, I would definitely be inclined to simplify it and use the existing binary interop with a pull-based pattern. I suspect the code would be *so* much simpler (also as mentioned at https://github.com/dotnet/aspnetcore/pull/33986/files#r668047758).

If, in the long term, we discover that people have a need to squeeze even more GC-efficiency out of streaming transfer, we can put in optimizations at that point. Even with a pull based model we could make it populate preallocated buffers without much code changes. But until we get to the point of needing that, I would expect streaming transfer to perform perfectly well on top of the binary interop mechanism.

File: src/Components/Web.JS/src/StreamingInterop.ts (hunk 13 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/StreamingInterop.ts:40]: Also more comments about this at https://github.com/dotnet/aspnetcore/pull/33986/files#r668052504

**Comment by SteveSandersonMS** [comment]
@TanayParikh I'll hold off on reviewing more until we lock down on the push-vs-pull thing, because I suspect that could lead to a pretty radical change in the implementation (which would also hopefully be a lot simpler).

File: src/Components/Web/src/Forms/InputFile.cs [hunk 14]
```diff
@@ -82,9 +82,7 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
         }
 
         internal Stream OpenReadStream(BrowserFile file, long maxAllowedSize, CancellationToken cancellationToken)
-            => _jsUnmarshalledRuntime != null ?
-                new SharedBrowserFileStream(JSRuntime, _jsUnmarshalledRuntime, _inputFileElement, file) :
-                new RemoteBrowserFileStream(JSRuntime, _inputFileElement, file, Options.Value, maxAllowedSize, cancellationToken);
+            => new BrowserFileStream(JSRuntime, _inputFileElement, file, Options.Value, maxAllowedSize, cancellationToken);
```
Comment (TanayParikh) [inline src/Components/Web/src/Forms/InputFile.cs:85]: Technically, this could be a breaking change for WASM environments as previously we didn't enforce the `maxAllowedSize`. Given that this appears to be a bug, I'd classify this under "acceptable breaking changes to prevent future issues". Any objections?

File: src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs [hunk 15]
```diff
@@ -67,6 +87,39 @@ public override async ValueTask<int> ReadAsync(Memory<byte> buffer, Cancellation
             return bytesRead;
         }
 
-        protected abstract ValueTask<int> CopyFileDataIntoBuffer(long sourceOffset, Memory<byte> destination, CancellationToken cancellationToken);
+        private async Task<Stream> OpenReadStreamAsync(RemoteBrowserFileStreamOptions options, CancellationToken cancellationToken)
```
Comment (TanayParikh) [inline src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:90]: Technically we consume a [`RemoteBrowserFileStreamOptions`](https://source.dot.net/#Microsoft.AspNetCore.Components.Web/Forms/InputFile/RemoteBrowserFileStreamOptions.cs,1dc0517a518759e5), but I'm tempted to remove it to avoid the additional complexity / increase in "concept count". We're using pretty safe defaults for regular JSDataStreams and there may not be too much use of the file stream specific options. Any objections?

File: src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs (hunk 3 above)
Comment (TanayParikh) [reply src/Components/Web/src/Forms/InputFile/SharedBrowserFileStream.cs]: Thanks for the clarification, I'm inclined to agree in the interest of maintaining implementation simplicity. I've updated the `InputFile` implementation accordingly. It's much simpler now, doing away with `{Shared, Remote}BrowserFileStream` in favour of a standardized `BrowserFileStream` which simply using the underlying byte array interop mechanism. There are a couple of potential breaking changes, and I've left comments accordingly.

File: src/Components/Web.JS/src/StreamingInterop.ts (hunk 13 above)
Comment (TanayParikh) [reply src/Components/Web.JS/src/StreamingInterop.ts]: Thanks Steve for the review and comments, I've updated the implementation accordingly to utilize a pull based approach in which we pull from JS when the `JSDataStream.ReadAsync` is called.

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 16]
```diff
@@ -24,8 +24,8 @@ internal class RemoteJSRuntime : JSRuntime
         private readonly long _maximumIncomingBytes;
         private int _byteArraysToBeRevivedTotalBytes;
 
-        internal int RemoteJSDataStreamNextInstanceId;
-        internal readonly Dictionary<long, RemoteJSDataStream> RemoteJSDataStreamInstances = new();
+        internal int JSDataStreamNextInstanceId;
+        internal readonly Dictionary<long, RemoteJSDataStream> JSDataStreamInstances = new();
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:28]: Doesn't seem like these names need to change - they were pretty descriptive already

File: src/Components/Shared/src/BaseJSDataStream.cs [hunk 17]
```diff
@@ -0,0 +1,42 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+using System.IO;
+using System.Threading;
+
+namespace Microsoft.AspNetCore.Components
+{
+    internal abstract class BaseJSDataStream : Stream
+    {
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/BaseJSDataStream.cs:11]: TBH I don't think we get all that much from `BaseJSDataStream` versus inlining its code into the two subclasses. Might it be worth doing that just to avoid having another concept and name to keep track of?

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 18]
```diff
@@ -0,0 +1,75 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.JSInterop;
+
+namespace Microsoft.AspNetCore.Components
+{
+    internal sealed class DefaultJSDataStream : BaseJSDataStream
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/DefaultJSDataStream.cs:11]: Would it be possible to find a name other than *Default* for this? It would be ideal to have something more descriptive to indicate how it differs from the others.

Suggestion: `PullFromJSDataStream`

Would be good also to add a comment above this indicating more about it, e.g.:

```
/// <Summary>
/// A stream that pulls each chunk on demand using JavaScript interop. This implementation is used for
/// WebAssembly and WebView applications.
/// </Summary>
```

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 19]
```diff
@@ -0,0 +1,75 @@
...
+    {
+        private readonly JSRuntime _runtime;
+        private readonly IJSStreamReference _jsStreamReference;
+        private readonly CancellationToken _streamCancellationToken;
+        private long _offset;
+
+        internal static DefaultJSDataStream CreateJSDataStream(
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/DefaultJSDataStream.cs:18]: The type itself is `internal` anyway

```suggestion
        public static DefaultJSDataStream CreateJSDataStream(
```

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 20]
```diff
@@ -0,0 +1,75 @@
...
+
+            Array.Copy(sourceArray: bytesRead, sourceIndex: 0, destinationArray: buffer, destinationIndex: offset, length: bytesRead.Length);
+
+            return bytesRead.Length;
+        }
+
+        private async Task<byte[]> RequestDataFromJSAsync(int numBytesToRead)
+        {
+            numBytesToRead = (int)Math.Min(numBytesToRead, _totalLength - _offset);
+            var bytesRead = await _runtime.InvokeAsync<byte[]>("Blazor._internal.getJSDataStreamChunk", _jsStreamReference, _offset, numBytesToRead);
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/DefaultJSDataStream.cs:60]: It's really great that we can just do this now 👍

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 21]
```diff
@@ -0,0 +1,75 @@
...
+            _offset += bytesRead.Length;
+            return bytesRead;
```
Comment (SteveSandersonMS) [inline src/Components/Shared/src/DefaultJSDataStream.cs:62]: Is it worth asserting here that `bytesRead == numBytesToRead`? Assuming there's never a case where that should be false, would be good to throw if something weird is going on.

File: src/Components/Shared/src/BaseJSDataStream.cs (hunk 17 above)
Comment (pranavkm) [reply src/Components/Shared/src/BaseJSDataStream.cs:11]: Yeah, this is literally implementing `Stream`. I wouldn't add a new thing to the type hierarchy at this point.

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 22]
```diff
@@ -0,0 +1,75 @@
...
+
+        public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
+        {
+            var numBytesToRead = Math.Min(count, buffer.Length - offset);
+            var bytesRead = await RequestDataFromJSAsync(numBytesToRead);
+
+            Array.Copy(sourceArray: bytesRead, sourceIndex: 0, destinationArray: buffer, destinationIndex: offset, length: bytesRead.Length);
+
+            return bytesRead.Length;
+        }
```
Comment (pranavkm) [inline src/Components/Shared/src/DefaultJSDataStream.cs:55]:
```suggestion
        => await ReadAsync(buffer.AsMemory(offset, count), cancellationToken);
```

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 23]
```diff
@@ -0,0 +1,75 @@
...
+            _offset += bytesRead.Length;
+            return bytesRead;
+        }
+
+        public override async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
+        {
+            var bytesRead = await RequestDataFromJSAsync(buffer.Length);
+
+            var bytesReadMemoryBuffer = new Memory<byte>(bytesRead);
+            bytesReadMemoryBuffer.CopyTo(buffer);
```
Comment (pranavkm) [inline src/Components/Shared/src/DefaultJSDataStream.cs:70]:
```suggestion
            bytesReadMemoryBuffer.CopyTo(buffer.AsMemory(bytesRead));
```

File: src/Components/Shared/src/DefaultJSDataStream.cs [hunk 24]
```diff
@@ -0,0 +1,75 @@
...
+        {
+            var numBytesToRead = Math.Min(count, buffer.Length - offset);
+            var bytesRead = await RequestDataFromJSAsync(numBytesToRead);
+
+            Array.Copy(sourceArray: bytesRead, sourceIndex: 0, destinationArray: buffer, destinationIndex: offset, length: bytesRead.Length);
+
+            return bytesRead.Length;
+        }
+
+        private async Task<byte[]> RequestDataFromJSAsync(int numBytesToRead)
```
Comment (pranavkm) [inline src/Components/Shared/src/DefaultJSDataStream.cs:57]:
```suggestion
        private async ValueTask<byte[]> RequestDataFromJSAsync(int numBytesToRead)
```

File: src/Components/Web.JS/src/WasmInputFile.ts [hunk 25]
```diff
@@ -1,27 +0,0 @@
-import { monoPlatform } from './Platform/Mono/MonoPlatform';
-import { System_Array } from './Platform/Platform';
-import { InputFile, InputElement, getFileById } from './InputFile';
-
-export const WasmInputFile = {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/WasmInputFile.ts:5]: Very cool that we can get rid of this now!

File: src/Components/Web.JS/src/Boot.WebAssembly.ts [hunk 26]
```diff
@@ -43,7 +44,7 @@ async function boot(options?: Partial<WebAssemblyStartOptions>): Promise<void> {
     }
   });
 
-  Blazor._internal.InputFile = WasmInputFile;
+  Blazor._internal.InputFile = InputFile;
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Boot.WebAssembly.ts:47]: If the value for this is always the same on all hosting models now, could we move the assignment logic into `GlobalExports.ts` (like how it assigns `Blazor._internal.Virtualize`) so it doesn't have to be set separately in all three `Boot.*.ts` files?

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Boot.WebAssembly.ts:47]: Might be possible to do that for `Blazor._internal.getJSDataStreamChunk` too if the value is the same everywhere (even if it's not strictly needed on `Blazor._internal.*` on Server, since we do still use the code from the function on Server, so it's not like the js bundle would be getting any bigger)

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs [hunk 27]
```diff
@@ -102,13 +101,26 @@ protected override void SendByteArray(int id, byte[] data)
...
+                        ? throw new JSException(exception)
+                        : (TResult)(object)DeserializeJSStreamReference(serializedStreamReference);
                 default:
                     throw new InvalidOperationException($"Invalid result type '{resultType}'.");
             }
         }
 
+        private IJSStreamReference DeserializeJSStreamReference(string serializedStreamReference)
+        {
+            var jsStreamReference = JsonSerializer.Deserialize<IJSStreamReference>(serializedStreamReference, JsonSerializerOptions);
```
Comment (pranavkm) [inline src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:115]: Do we have a custom reader for this? In that case, you could use the UnconditionalSuppressMessageAttribute and suppress the warning saying this is not doing reflection.

File: src/Components/Web/src/Forms/InputFile.cs (hunk 14 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputFile.cs:85]: Interesting. That is a bit breaky. Are there particular future issues you're anticipating?

Technically we could - if we want - check if the OS is "browser" and change pass `long.MaxValue` or similar here in that case.

@javiercn @pranavkm Opinions?

Comment (pranavkm) [reply src/Components/Web/src/Forms/InputFile.cs:85]: On one hand, it's weird the option does not get used. At the same time, it's a bit unclear what the benefit of enforcing a size limit in WASM is. I'm cool with using MaxValue and documenting that the maxAllowedSize is ignored in WASM.

File: src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs (hunk 15 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:90]: It seems like we could probably get away with it, because:

 * It's not a source or binary breaking change (if we left `RemoteBrowserFileStreamOptions` in existence but marked it as `[Obsolete]`). It's only a change of behavior in that we'd now be ignoring those options and using the defaults from JS interop.
 * Very few people will likely have tried to customize this, and even if they have, we believe our new JS interop streaming defaults should be good for everyone, right?

If this is the case then I'd support marking `RemoteBrowserFileStreamOptions` as obsolete and no longer respecting it. @javiercn @pranavkm Opinions?

File: src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs [hunk 28]
```diff
@@ -67,6 +87,39 @@ public override async ValueTask<int> ReadAsync(Memory<byte> buffer, Cancellation
...
+                cancellationToken,
+                _inputFileElement,
+                _file.Id);
+
+            return await dataReference.OpenReadStreamAsync(
+                _maxAllowedSize,
+                cancellationToken: cancellationToken);
+        }
+
+        private async ValueTask<int> CopyFileDataIntoBuffer(long sourceOffset, Memory<byte> destination, CancellationToken cancellationToken)
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:103]: Is this still used? Who calls it? I see it was abstract before but can't work out in what way it would still be used.

Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:103]: Never mind, I see where it's called now.

File: src/Components/Web/src/Forms/InputFile.cs (hunk 14 above)
Comment (TanayParikh) [reply src/Components/Web/src/Forms/InputFile.cs:85]: > unclear what the benefit of enforcing a size limit in WASM is.

One potential use case is the developer only wants to process files <10MB as anything larger would not provide an optimal user experience / wouldn't make sense in the application context. This is where such a limit may be useful.

We can definitely just ignore the limit via `long.MaxValue` as Steve and Pranav suggest, just wanted to get consensus on the approach we take.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs (hunk 27 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:115]: Yes. I already put up:

https://github.com/dotnet/aspnetcore/pull/33986/files#diff-05d755169cd9aafe45f11033920fb3529925c0881ff6604dda66b48998f041a5R1-R11

Would that be sufficient, or did you have something else in mind?

File: src/Components/Web/src/Forms/InputFile.cs (hunk 14 above)
Comment (SteveSandersonMS) [reply src/Components/Web/src/Forms/InputFile.cs:85]: > One potential use case is the developer only wants to process files <10MB as anything larger would not provide an optimal user experience / wouldn't make sense in the application context.

I agree that's a valid scenario, but they wouldn't want to achieve that by getting an exception from us, would they? They can already check the size property on the `BrowserFile` instances. Then they don't have to take guesses about what sort of exception to catch (etc) to trigger their "sorry this is too big" UI.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs (hunk 27 above)
Comment (pranavkm) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:115]: So the way it works is that XML file is only meant to ignore these warnings when we run the WasmLinkTest and is meant for us to be a reminder to fix it. The attribute goes further and says this is not a real issue

File: src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs (hunk 15 above)
Comment (pranavkm) [reply src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:90]: > If this is the case then I'd support marking RemoteBrowserFileStreamOptions as obsolete and no longer respecting it. @javiercn @pranavkm Opinions?

Is either of you able to access chemweb.azurwebsites.net? That might give us some sense of how frequently this option gets used and perhaps changes our opinions.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs (hunk 27 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:115]: Gotcha, appreciate the details! 😄

File: src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs (hunk 15 above)
Comment (TanayParikh) [reply src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs:90]: Unfortunately not.

image

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs (hunk 27 above)
Comment (TanayParikh) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSRuntime.cs:115]: We have https://github.com/dotnet/aspnetcore/blob/c01f9e3844f17925bb7f1ae99eac772d19692be0/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/JSStreamReferenceJsonConverter.cs but it's in a different assembly, I assume that's not an issue for the unconditional suppression?

**Comment by TanayParikh** [comment]
Thanks all for the reviews, I've updated accordingly and added tests for the WASM/WebView data stream. If there aren't any other comments I'd like to get this merged Wednesday to ensure it makes it in for Preview 7 😄

File: src/Components/Web/src/Forms/InputFile/RemoteBrowserFileStreamOptions.cs [hunk 29]
```diff
@@ -23,11 +24,12 @@ public class RemoteBrowserFileStreamOptions
 
         /// <summary>
         /// Gets or sets the maximum internal buffer size for unread data sent over a SignalR circuit.
+        /// Default -1 represents the default Pipe pauseWriterThreshold in <see cref="System.IO.Pipelines.PipeOptions" />.
         /// <para>
         /// This only has an effect when using Blazor Server.
         /// </para>
         /// </summary>
-        public int MaxBufferSize { get; set; } = 1024 * 1024;
+        public int MaxBufferSize { get; set; } = -1;
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/InputFile/RemoteBrowserFileStreamOptions.cs:32]: Technically I guess this doesn't need to change if we're not using it any more, but doesn't matter :)

File: src/Components/Web/src/Forms/InputFile.cs [hunk 30]
```diff
@@ -82,9 +79,12 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
...
         internal Stream OpenReadStream(BrowserFile file, long maxAllowedSize, CancellationToken cancellationToken)
-            => _jsUnmarshalledRuntime != null ?
-                new SharedBrowserFileStream(JSRuntime, _jsUnmarshalledRuntime, _inputFileElement, file) :
-                new RemoteBrowserFileStream(JSRuntime, _inputFileElement, file, Options.Value, maxAllowedSize, cancellationToken);
+            => new BrowserFileStream(
+                JSRuntime,
+                _inputFileElement,
+                file,
+                _jsUnmarshalledRuntime == null ? maxAllowedSize : long.MaxValue, // Don't enforce the maxAllowedSize for WASM (to preserve legacy behavior).
+                cancellationToken);
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/InputFile.cs:87]: Do you know if there's an E2E test showing that the `maxAllowedSize` is enforced on server? Would be ideal to have one now there's conditional logic here (in case some time in the future `_jsUnmarshalledRuntime` somehow becomes nonnull on Server due to some unrelated change).

**Review by SteveSandersonMS — APPROVED** [review]
Awesome work @TanayParikh! This looks great to me.

File: src/Components/Web/src/Forms/InputFile.cs (hunk 30 above)
Comment (TanayParikh) [reply src/Components/Web/src/Forms/InputFile.cs:87]: So I looked into this, and it appears we already had that test:

https://github.com/dotnet/aspnetcore/blob/1395fa8574a574ca969463952d4c5e89e9febe89/src/Components/test/E2ETest/Tests/InputFileTest.cs#L186-L203

So why was `maxAllowedSize` being enforced? Because we had a higher level check (with the associated InputFile specific error message):

https://github.com/dotnet/aspnetcore/blob/1395fa8574a574ca969463952d4c5e89e9febe89/src/Components/Web/src/Forms/InputFile/BrowserFile.cs#L42-L45

Backing out this special casing.

**Comment by TanayParikh** [comment]
fyi/ Had to [change the WebView base64 serialization](https://github.com/dotnet/aspnetcore/pull/33986/commits/ea0de9bc8ebf08fd18264cca4dd7462688d35d9c) slightly due to stack overflow concerns on large byte arrays.

**Comment by TanayParikh** [comment]
CI passed but status isn't being reported for some reason. Could someone with admin rights please merge? @dotnet/aspnet-build 

https://dev.azure.com/dnceng/public/_build/results?buildId=1239168&view=results

**Comment by dougbu** [comment]
@TanayParikh all closing and reopening did was cancel the auto-merge and start another build that likely won't report back to GitHub either 😀

**Comment by TanayParikh** [comment]
> @TanayParikh all closing and reopening did was cancel the auto-merge and start another build that likely won't report back to GitHub either 😀

Thanks for merging. Wasn't sure why the CI status wasn't being reported to GitHub and figured closing/re-opening _may_ re-trigger the reporting (of the new CI run).
