### PR TITLE
Log time-taken more precisely

### LINKED ISSUE #35613: W3CLogging "time" not precise enough, leading to "time-taken" being significantly wrong
### Describe the bug
When using the new W3CLogging, I've noticed that the "time" field is only precise down to the second.  This does not match many other web servers, including IIS, which log times with millisecond precision. Also, the "time-taken" field is calculated based on this imprecision "time" value, thus leading to very inaccurate time-taken values in the logs.  For example, if a request comes in at 01:30:00.800 and takes 10 milliseconds to process, then the time-taken that is written to the logs is 810 milliseconds, not the expected 10 milliseconds

### To Reproduce

1. In VS 2022, create a new ASP.NET Core Web App, targetting .NET 6.0 (Preview)
2. In the Program.cs file, add the following immediately before `var app = builder.Build();`

`builder.Services.AddW3CLogging(logging =>
{
    logging.LoggingFields = Microsoft.AspNetCore.HttpLogging.W3CLoggingFields.All;
});`

Also add the following immediately after `var app = builder.Build();`

`app.UseW3CLogging();`

3. Run the application, refresh the page several times, and take a look at the resulting w3clog-*.txt file.   You'll note that the "time" column is formatted as hh:mm:ss, but no milliseconds, and that the time-taken is all over the place, even though we are hitting a very simple page that in actuality is taking under 100ms to process.

### Exceptions (if any)

No exception, just inaccurate time-taken values

### Further technical details
- ASP.NET Core version: .NET 6.0 preview 7
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS 2022 17.0.0 Preview 3.1

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes https://github.com/dotnet/aspnetcore/issues/35613

`time` is still logged to the second, but it's passed thru to `W3CLogger` with millisecond precision so we can more accurately calculate `time-taken`. Logs for the sample now generally have `time-taken` at under 1 millisecond, rather than how many milliseconds past the second the action occurred at.

### CODE REVIEW

File: src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs [hunk 1]
```diff
@@ -98,7 +98,9 @@ public async Task Invoke(HttpContext context)
 
             if (options.LoggingFields.HasFlag(W3CLoggingFields.Time))
             {
-                shouldLog |= AddToList(elements, _timeIndex, now.ToString("HH:mm:ss", CultureInfo.InvariantCulture));
+                // Start time will be logged to second precision, but we store it to millisecond precision so we can use it
+                // to calculate time-taken later.
+                shouldLog |= AddToList(elements, _timeIndex, now.ToString("HH:mm:ss.fff", CultureInfo.InvariantCulture));
```
Comment (halter73) [inline src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:103]: Can we calculate and set the final value for `_timeTakenIndex` in this middleware? That way we wouldn't have to parse this date and call substring on this later in `W3CLogger.Format(string[])`. We could also use `Environment.TickCount` to avoid misreporting the elapsed time if the system clock changes.

File: src/Middleware/HttpLogging/src/W3CLogger.cs [hunk 2]
```diff
@@ -51,11 +51,16 @@ private string Format(string[] elements)
...
             var time = elements[W3CLoggingMiddleware._timeIndex];
-            if (!string.IsNullOrEmpty(date) && !string.IsNullOrEmpty(time) && _loggingFields.HasFlag(W3CLoggingFields.TimeTaken))
+            if (!string.IsNullOrEmpty(time))
             {
-                DateTime start = DateTime.ParseExact(date + time, "yyyy-MM-ddHH:mm:ss", CultureInfo.InvariantCulture);
-                var elapsed = DateTime.UtcNow.Subtract(start);
-                elements[W3CLoggingMiddleware._timeTakenIndex] = elapsed.TotalMilliseconds.ToString(CultureInfo.InvariantCulture);
+                if (!string.IsNullOrEmpty(date) && _loggingFields.HasFlag(W3CLoggingFields.TimeTaken))
+                {
+                    DateTime start = DateTime.ParseExact(date + time, "yyyy-MM-ddHH:mm:ss.fff", CultureInfo.InvariantCulture);
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/W3CLogger.cs:58]:
```suggestion
                    var start = DateTime.ParseExact(date + time, "yyyy-MM-ddHH:mm:ss.fff", CultureInfo.InvariantCulture);
```

File: src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs (hunk 1 above)
Comment (wtgodbe) [reply src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:103]: Good idea

Comment (wtgodbe) [reply src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:103]: Looks like Environment.TickCount isn't as precise, it's in whole milliseconds so most request/response pairs log a time-taken of 0

Comment (halter73) [reply src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:103]: Wasn't this counting whole milliseconds before? Even if we continue using DateTime to calculate elapsed time, we should move where we calculate elapsed time. StopWatch might also be an option, but I'd want to be careful to avoid too many allocations.

Comment (Kahbazi) [reply src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:103]: > StopWatch might also be an option, but I'd want to be careful to avoid too many allocations.

`ValueStopWatch` could be used to avoid allocation.

**Comment by wtgodbe** [comment]
Updated for feedback. Time-taken is now calculated entirely in the middleware using `ValueStopWatch`. Added/changed tests to reflect that.

File: src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs [hunk 3]
```diff
@@ -91,6 +92,7 @@ public async Task Invoke(HttpContext context)
             bool shouldLog = false;
 
             var now = DateTime.UtcNow;
+            ValueStopwatch stopWatch = ValueStopwatch.StartNew();
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:95]:
```suggestion
            var stopWatch = ValueStopwatch.StartNew();
```

File: src/Middleware/HttpLogging/test/W3CLoggingMiddlewareTests.cs [hunk 4]
```diff
@@ -107,7 +107,42 @@ public async Task DefaultDoesNotLogOptionalFields()
...
+            Assert.Equal("#Version: 1.0", lines[0]);
+
+            Assert.StartsWith("#Start-Date: ", lines[1]);
+            var startDate = DateTime.Parse(lines[1].Substring(13), CultureInfo.InvariantCulture);
+            // Assert that the log was written in the last 10 seconds
+            Assert.True(now.Subtract(startDate).TotalSeconds < 10);
+
+            Assert.Equal("#Fields: time-taken", lines[2]);
+            // Time taken should be less than 10 milliseconds
+            Assert.True(Double.Parse(lines[3]) < 10);
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/test/W3CLoggingMiddlewareTests.cs:145]: I'm 99% sure that this test would fail on my machine. :sweat_smile:

File: src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs [hunk 5]
```diff
@@ -215,6 +217,11 @@ public async Task Invoke(HttpContext context)
                 shouldLog |= AddToList(elements, _protocolStatusIndex, response.StatusCode.ToString(CultureInfo.InvariantCulture));
             }
 
+            if (options.LoggingFields.HasFlag(W3CLoggingFields.TimeTaken))
+            {
+                shouldLog |= AddToList(elements, _timeTakenIndex, stopWatch.GetElapsedTime().TotalMilliseconds.ToString(CultureInfo.InvariantCulture));
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/W3CLoggingMiddleware.cs:222]: Is the fractional part needed?
```suggestion
                shouldLog |= AddToList(elements, _timeTakenIndex, stopWatch.GetElapsedTime().TotalMilliseconds.ToString("F0", CultureInfo.InvariantCulture));
```

File: src/Middleware/HttpLogging/test/W3CLoggingMiddlewareTests.cs (hunk 4 above)
Comment (wtgodbe) [reply src/Middleware/HttpLogging/test/W3CLoggingMiddlewareTests.cs:145]: I'll bump it up to 50

Comment (Tratcher) [reply src/Middleware/HttpLogging/test/W3CLoggingMiddlewareTests.cs]: Don't check for a specific value, just verify it parses.

**Review by Tratcher — APPROVED** [review]
