### PR TITLE
Fix duplicate error.type tags

### LINKED ISSUE #55159: Exception middlewares introduce duplicates of error.type diagnostic tags in some situations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In some specific situations exceptions can cause the `Microsoft.AspNetCore.Hosting,http.server.request.duration` metric to duplicate `error.type` tags. One such situation is throwing an exception in a handler after a websocket connection is closed, but there might be others.

This is devastating if downstream systems cannot handle tag duplication. E.g. with prometheus once tags are duplicated scraping fails completely, marking the service as down in prometheus. The only way to recover from this is restarting the service (until the issue reoccurs).

I found https://github.com/open-telemetry/opentelemetry-dotnet/issues/5199 reported against OTEL which sounds like it might describe the same problem caused in other ways.

### Expected Behavior

Regardless of in which situation an exception is thrown, the tags on the metrics should not be duplicated. Looking at the code this seems to be the intent of the implementation to begin with.

### Steps To Reproduce

1. Run the example application below using `dotnet run`
```cs
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.UseExceptionHandler(options => {}); // Exception handling middleware introduces duplicate tag
app.UseWebSockets();

app.MapGet("/", async (HttpContext context, CancellationToken ct) =>
{
    if (context.WebSockets.IsWebSocketRequest)
    {
        using var ws = await context.WebSockets.AcceptWebSocketAsync();
        await ws.CloseAsync(System.Net.WebSockets.WebSocketCloseStatus.NormalClosure, "done", ct);
        throw new InvalidOperationException("Throw after websocket request completion to produce the bug");
    }
});
app.Run();
```
2. Attach using `dotnet-counters collect -n DuplicateTagRepro Microsoft.AspNetCore.Hosting` (or any other tooling that allows seing the `Microsot.AspNetCore.Hosting` metrics.
3. Use a websocket client to request the endpoint. E.g. `wscat --connect localhost:5221/`
4. Observe that metrics now show `Microsoft.AspNetCore.Hosting,http.server.request.duration` metrics with duplicated `error.type=System.InvalidOperationException` tags

E.g. `Microsoft.AspNetCore.Hosting,http.server.request.duration (s)[error.type=System.InvalidOperationException;error.type=System.InvalidOperationException;error.type=System.InvalidOperationException;http.request.method=GET;http.response.status_code=101;http.route=/;network.protocol.version=1.1;url.scheme=http;Percentile=50]`

You will see one duplication per exception middleware. E.g. when running in Development mode the automatically added developer exception middleware will introduce another duplication.

### Exceptions (if any)

As expected (and correct), triggering the exception causes one or more exceptions related to unhandled exceptions:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Throw after websocket request completion
         at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\dev\experiments\DuplicateTagRepro\Program.cs:line 20
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN2U17KD956D", Request id "0HN2U17KD956D:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Throw after websocket request completion
         at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\dev\experiments\DuplicateTagRepro\Program.cs:line 20
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### .NET Version

8.0.200 or 9.0.100-preview.3.24204.13

### Anything else?

I reproduced this in dotnet 8.0.200 and the current preview 9.0.100-preview.3.24204.13.

At least one part in this duplication seems to be the unexpected presence of the exception in `HostingMetrics.RequestEnd`
https://github.com/dotnet/aspnetcore/blob/8486d31e24f30e3fa1809a95699a0adc16f448d7/src/Hosting/Hosting/src/Internal/HostingMetrics.cs#L72C1-L77C14
The comment there states, that if `ExceptionHandlerMiddleware` or `DeveloperExceptionMiddleware` is used, the `exception` variable should be `null`. However this is not the case with the reproducer above.

Other instances of the tag are introduced in the `ExceptionHandlerMiddlewareImpl` in
https://github.com/dotnet/aspnetcore/blob/8486d31e24f30e3fa1809a95699a0adc16f448d7/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs#L130
and `DeveloperExceptionPageMiddlewareImpl` in
https://github.com/dotnet/aspnetcore/blob/b83e1e159ef1bdfe638e36c8b00bc65ed2d1d857/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L128
Which call `DiagnosticsTelemetry.ReportUnhandledException` which adds the `error.type` tag into the `IHttpMetricsTagsFeature` `Tags` list. This is later given to `HostingMetrics.RequestEnd` as `customTag` entries.

This way a single record can have three identical `error.type` entries. One for each middleware and one by the `RequestEnd` function.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/55159

Duplicate metrics tags can break some telemetry tooling. It's possible to have ASP.NET Core add multiple `error.type` tags to a counter. That's bad and should be fixed.

`error.type` can be added by exception middleware and it can be added in hosting if there is an unhandled exception. That means there can be duplicates if:

* Exception handling middleware handles an exception (tag added in middleware) and then there is an unhandled exception afterwards (tag added in hosting)
* Two configured exception handling middleware instances. An error is thrown and is handled (tag added in middleware 1) and then afterwards another error is thrown and handled by the second middleware (tag added in middleware 2).

Fix by conditionally adding `error.type` to tag collection only if it isn't present, aka first value wins.

**Before (duplicate tags):**

image

**After (one tag):**

image

### CODE REVIEW

File: src/Shared/Metrics/MetricsExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+{
+    public static bool TryAddTag(this IHttpMetricsTagsFeature feature, string name, object? value)
+    {
+        var tags = feature.Tags;
+
+        // Tags is internally represented as a List<T>.
+        // Prefer looping through the list to avoid allocating an enumerator.
+        if (tags is List<KeyValuePair<string, object?>> list)
+        {
+            foreach (var tag in list)
```
Comment (amcasey) [inline src/Shared/Metrics/MetricsExtensions.cs:19]: It's been a while, but I think foreach might do this for all `IList`s.

File: src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerTest.cs [hunk 2]
```diff
@@ -965,4 +966,136 @@ public async Task UnhandledError_ExceptionNameTagAdded()
...
+        await instrumentCollector.WaitForMeasurementsAsync(minCount: 1).DefaultTimeout();
+
+        // Assert
+        Assert.Collection(
+            instrumentCollector.GetMeasurementSnapshot(),
+            m =>
+            {
+                Assert.True(m.Value > 0);
+                Assert.Equal(500, (int)m.Tags["http.response.status_code"]);
+                Assert.Equal("System.Exception", (string)m.Tags["error.type"]);
```
Comment (amcasey) [inline src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerTest.cs:1036]: What did this formerly do?  Did it throw because there were multiple?

**Review by amcasey — APPROVED** [review]

File: src/Shared/Metrics/MetricsExtensions.cs (hunk 1 above)
Comment (JamesNK) [reply src/Shared/Metrics/MetricsExtensions.cs:19]: I'm not sure what you mean. The type on the feature is `ICollection<T>` (IMO we should have made it `IList<T>` but took late now). A foreach will always allocate an enumerator, no?

File: src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerTest.cs (hunk 2 above)
Comment (JamesNK) [reply src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerTest.cs:1036]: Previously there would have been two `error_type` tags from metrics, however the `MetricCollector` stores value in a dictionary so it would have stored the last value.

We know the test is working because we want first wins, and the first error - `System.Exception` - is returned and not the second error - `System.InvalidOperationException`.

File: src/Shared/Metrics/MetricsExtensions.cs (hunk 1 above)
Comment (amcasey) [reply src/Shared/Metrics/MetricsExtensions.cs:19]: I misremembered - there's special handling for arrays and strings, but not for ILists.
