### PR TITLE
Blazor Web can use `BasePath` component instead of `<base href="">`

### LINKED ISSUE #6818: Blazor has case sensitive URLs when hosted in a Child Directory
(NOTE:  this report is in the context of "server-side" Blazor app hosting)

It is possible to host Blazor in a child directory by:

1)  Adding an app.Map() in the Startup.Configure() method of the host:

  **app.Map("/dashboard", child => { child.UseServerSideBlazor<DiskBounty.Dashboard.Startup>(); });**

and 

2) Changing the base href in the index.html of the Blazor App:

   **base hef="/dashboard/"** 

However, if you do this you can only use the casing of the base href to access your Blazor pages.  For example **/dashboard/counter** and **/dashboard/Counter** will work but **/Dashboard/counter** will not.   That is you must always specify 'dashboard' (in this example) within the URL in lower case.  This is a behavior difference to when the Blazor app is hosted in the root directory, where all urls are case _insensitive_. 

The error you get is:

**warn: Microsoft.AspNetCore.Blazor.Server.BlazorHub[0]
      Unhandled Server-Side exception
System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 1) ---> Microsoft.AspNetCore.Blazor.Browser.Rendering.RemoteRendererException: Error: No element is currently associated with component 1
   --- End of inner exception stack trace ---**

### PR DESCRIPTION
**Pull request by ilonatommy**
# Summary
Proposal addressing https://github.com/dotnet/aspnetcore/issues/6818 by introducing a reusable `BasePath` component that centralizes how Blazor apps compute their `<base>` URI when hosted under subpaths.

## Background
Routing case preservation for apps mounted at `/dashboard` or similar previously required manual `<base href>` edits or per-app JavaScript. Those workarounds were inconsistent across hosting models and easy to break during deployment. Moving the logic into the Endpoints package gives `Blazor Web` a single, framework-owned solution while standalone `WebAssembly` apps keep using their static `<base />`.

This gives developers a first-class, framework-supported answer instead of per-app workarounds mentioned throughout #6818.

### Public API
```c#
namespace Microsoft.AspNetCore.Components.Endpoints;

/// <summary>
/// Renders a &lt;base&gt; element whose <c>href</c> value matches the current request path base.
/// </summary>
public sealed class BasePath : IComponent
{
    // No public parameters; renders based on NavigationManager.BaseUri at runtime.
}
```

## Implementation Details
- `BasePath` implements `IComponent`, renders a `<base>` element via `RenderHandle`, and resolves the href from `NavigationManager.BaseUri`.
- Logic falls back to `/` if the base URI cannot be parsed, but otherwise mirrors both casing and multi-segment paths exposed by the endpoint pipeline.
- Emits the exact path reported by `NavigationManager`.
- The class lives in `src/Components/Endpoints/src/Routing/BasePath.cs` and will share the directory with future routing-related document helpers.

### Tests

The component is covered with unit tests and passed manual testing. Adding e2e test seems too heavy for this kind of change.

## API usage
```razor
@using Microsoft.AspNetCore.Components.Endpoints

<!-- Blazor Web layout -->
<head>
    <BasePath />
    <HeadOutlet />
</head>
```

Fixes https://github.com/dotnet/aspnetcore/issues/6818.

### CODE REVIEW

File: src/Components/Web/src/Head/BasePath.cs [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+using Microsoft.AspNetCore.Components.Rendering;
+using Microsoft.AspNetCore.Http;
+using Microsoft.Extensions.DependencyInjection;
+
+namespace Microsoft.AspNetCore.Components.Web;
+
+/// <summary>
+/// Renders a &lt;base&gt; element whose <c>href</c> value matches the current request path base.
+/// </summary>
+public sealed class BasePath : ComponentBase
```
Comment (javiercn) [inline src/Components/Web/src/Head/BasePath.cs]: Implement `IComponent` directly and use an explicit implementation. This doesn't need any of the ComponentBase behaviors and we don't nedd to have public API for this beyond the type name.

File: src/Components/Web/src/Head/BasePath.cs [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    /// <summary>
+    /// Gets or sets the fallback <c>href</c> value to use when the current request information isn't available.
+    /// </summary>
+    /// <example>
+    /// <code>
+    /// &lt;BasePath FallbackHref="/dashboard/" /&gt;
+    /// </code>
+    /// </example>
+    [Parameter]
+    public string? FallbackHref { get; set; }
```
Comment (javiercn) [inline src/Components/Web/src/Head/BasePath.cs]: We don't need to provide parameters for this component. If the developer wants to explicitly set the base path, they can use the `base` tag directly. The value this component adds is that it makes it match with `HttpContext.Request.PathBase` automatically.

File: src/Components/Web/src/Head/BasePath.cs [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+        var accessor = Services.GetService<IHttpContextAccessor>();
+        var contextPathBase = accessor?.HttpContext?.Request.PathBase;
+        if (contextPathBase.HasValue)
+        {
+            pathBase = contextPathBase.Value;
+            return true;
+        }
+
+        pathBase = null;
+        return false;
```
Comment (javiercn) [inline src/Components/Web/src/Head/BasePath.cs]: No HttpContextAccessor. `[CascadingParameter] HttpContext { get; set; }`, but since this is injecting NavigationManager, we should be able to retrieve the base path from the BasePath there.

File: src/Components/Web/src/Head/BasePath.cs [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+            ? absoluteUri.AbsolutePath
+            : value;
+
+        if (!normalizedValue.StartsWith('/'))
+        {
+            normalizedValue = "/" + normalizedValue;
+        }
+
+        return normalizedValue.EndsWith('/') ? normalizedValue : normalizedValue + "/";
+    }
```
Comment (javiercn) [inline src/Components/Web/src/Head/BasePath.cs]: Won't be needed since this comes from the value provided by `HttpContext` in the end.

File: src/Components/Web/src/Head/BasePath.cs (hunk 1 above)
Comment (javiercn) [inline src/Components/Web/src/Head/BasePath.cs]: This component needs to live in the `.Endpoints` assembly, not in Components.Web.

File: src/Components/Web/test/Microsoft.AspNetCore.Components.Web.Tests.csproj [hunk 5]
```diff
@@ -9,6 +9,7 @@
     <Reference Include="Microsoft.AspNetCore.Antiforgery" />
     <Reference Include="Microsoft.AspNetCore.Components" />
     <Reference Include="Microsoft.AspNetCore.Components.Web" />
+    <Reference Include="Microsoft.AspNetCore.Http" />
```
Comment (javiercn) [inline src/Components/Web/test/Microsoft.AspNetCore.Components.Web.Tests.csproj]: This dependency is not allowed in this assembly. It'll bring in the framework reference.

File: src/Components/Web/src/Microsoft.AspNetCore.Components.Web.csproj [hunk 6]
```diff
@@ -22,6 +22,7 @@
   <ItemGroup>
     <Reference Include="Microsoft.AspNetCore.Components" />
     <Reference Include="Microsoft.AspNetCore.Components.Forms" />
+    <Reference Include="Microsoft.AspNetCore.Http.Abstractions" />
```
Comment (javiercn) [inline src/Components/Web/src/Microsoft.AspNetCore.Components.Web.csproj]: This reference is not allowed here. It will bring the asp.net core framework reference and `Components.Web` doesn't reference stuff from ASP.NET Core.

**Review by javiercn — CHANGES_REQUESTED** [review]

File: src/Components/Endpoints/test/Microsoft.AspNetCore.Components.Endpoints.Tests.csproj [hunk 7]
```diff
@@ -8,6 +8,7 @@
   <ItemGroup>
     <Compile Include="..\..\Shared\test\AutoRenderComponent.cs" Link="TestComponents\AutoRenderComponent.cs" />
     <Compile Include="$(ComponentsSharedSourceRoot)src\WebRootComponentParameters.cs" Link="Shared\WebRootComponentParameters.cs" />
+    <Compile Include="$(ComponentsSharedSourceRoot)test\**\*.cs" LinkBase="Shared" />
```
Comment (ilonatommy) [inline src/Components/Endpoints/test/Microsoft.AspNetCore.Components.Endpoints.Tests.csproj:10]: This is for `TestRenderer`.

**Review by javiercn — APPROVED** [review]
Looks great.

I think we want to update our template with this too. One more thing is you want to give the component more coverage would be to replace the `base` tag on our `App.razor` files with this code.
