### PR TITLE
Fix Navigation for anchor inside <svg> element

### LINKED ISSUE #51440: data-enhance-nav=false is ignored on <svg> elements
Inside `NavigationEnhancement.ts`, the logic that decides whether to bypass enhanced nav based on the element clicked looks like:

```ts
  if (event.target instanceof HTMLElement && !enhancedNavigationIsEnabledForElement(event.target)) {
    return;
  }
```

It should say `Element` instead of `HTMLElement`, because `HTMLElement` excludes `SVGElement`. There is no reason why SVG elements should behave differently from HTML elements in this regard.

### LINKED ISSUE #51705: Enhanced Navigation doesn't work inside SVG element
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhanced Navigation doesn't work inside SVG element

### Expected Behavior

Should work unless `data-enhance-nav="false"` is specified

### Steps To Reproduce

1. Create new Blazor Web Template
2. Paste these lines in `Home.razor`
```razor
<svg width="400px" height="30px">
    <NavLink href="/counter">
        <text x="15" y="15" font-size="15">SVG data-enhance-nav</text>
    </NavLink>
</svg>

<br />

<svg width="400px" height="30px" data-enhance-nav="true">
    <NavLink href="/counter">
        <text x="15" y="15" font-size="15">SVG data-enhance-nav</text>
    </NavLink>
</svg>
```
3. Click on the links 

### Exceptions (if any)

_No response_

### .NET Version

8

## The problem

This breaks here:
https://github.com/dotnet/aspnetcore/blob/73e0b536d411a38c745b2a7ee5b04f04ee4fe6ea/src/Components/Web.JS/src/Services/NavigationUtils.ts#L105

The reason is that inside the context of `<svg>` element `tagName` of `<a>` is not `A` (uppercase) but `a` (lowercase). You can try it out here:
https://playcode.io/1643729

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fix Navigation for `<svg>` element

## Description

Fixes enhanced navigation inside `<svg>` element. More detailed description see in the issues.

Fixes #51705
Fixes #51440

### CODE REVIEW

**Review by MackinnonBuck — APPROVED** [review]
Looks good to me!

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 1]
```diff
@@ -112,16 +112,16 @@ function findAnchorTarget(event: MouseEvent): HTMLAnchorElement | null {
     // legacy browsers that don't support it by falling back on the older logic, even
     // though it won't work properly with ShadowDOM. This can be removed in the next
     // major release.
-    return findClosestAnchorAncestorLegacy(event.target as Element | null, 'A');
+    return findClosestAnchorAncestorLegacy(event.target as Element | null);
   }
 }
 
-function findClosestAnchorAncestorLegacy(element: Element | null, tagName: string) {
+function findClosestAnchorAncestorLegacy(element: Element | null) {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts:119]: I think we should just remove `findClosestAnchorAncestorLegacy` for 9.0. It's not required for any of our supported browsers now, as far as I know.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts:119]: That would also mean removing the `_blazorDisableComposedPath` support above.

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs [hunk 2]
```diff
@@ -114,7 +113,36 @@ public void EnhancedNavCanBeReenabledHierarchically()
...
+
+        var originalH1Elem = Browser.Exists(By.TagName("h1"));
+        Browser.Equal("Hello", () => originalH1Elem.Text);
+
+        Browser.Exists(By.TagName("nav")).FindElement(By.Id("svg-nav-link")).Click();
+
+        // Check we got there, and it did retain the <h1> element
+        Browser.Equal("Other", () => Browser.Exists(By.TagName("h1")).Text);
+        Assert.Equal("Other", originalH1Elem.Text);
+    }
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs:131]: Ideally there'd also be a test for "works inside SVG element" for regular client-side (interactive) nav as well, since that was also not working before and is also fixed by your change, if I'm reading the code correctly.

File: src/Components/Web.JS/src/Services/NavigationUtils.ts (hunk 1 above)
Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts]: Done

File: src/Components/Web.JS/src/Services/NavigationUtils.ts [hunk 3]
```diff
@@ -93,35 +93,19 @@ function canProcessAnchor(anchorTarget: HTMLAnchorElement) {
...
+  const path = event.composedPath && event.composedPath();
   if (path) {
     // This logic works with events that target elements within a shadow root,
     // as long as the shadow mode is 'open'. For closed shadows, we can't possibly
     // know what internal element was clicked.
     for (let i = 0; i < path.length; i++) {
       const candidate = path[i];
-      if (candidate instanceof Element && candidate.tagName === 'A') {
+      if (candidate instanceof HTMLAnchorElement || candidate instanceof SVGAElement) {
         return candidate as HTMLAnchorElement;
```
Comment (campersau) [inline src/Components/Web.JS/src/Services/NavigationUtils.ts:104]: So this can either be a `HTMLAnchorElement` or `SVGAElement` now. Should this method return `HTMLAnchorElement | SVGAElement | null` instead? Is the cast then still needed because of the `instanceof` checks before?

**Comment by sebastienros** [comment]
The Markdownlint step has been fixed in main. Running `/azp run` won't rerun it with these, assume this step is not blocking.

File: src/Components/Web.JS/src/Services/NavigationUtils.ts (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts:104]: I agree it is a bit dubious that the function claims to return `HTMLAnchorElement | null` if it actually returns `HTMLAnchorElement | SVGAElement | null`. However I don't know that it would make any difference in practice.

@surayya-MS Does it work to change the return type to be more accurate now, or does that force a lot of disruption to the caller?

**Review by SteveSandersonMS — APPROVED** [review]
Looks great!

Please do see the comment at https://github.com/dotnet/aspnetcore/pull/51706/files#r1374942427 in case that's also a minor detail that could be resolved without much trouble.

File: src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs (hunk 2 above)
Comment (surayya-MS) [reply src/Components/test/E2ETest/ServerRenderingTests/EnhancedNavigationTest.cs:131]: You are right. Click on anchor inside svg element doesn't get intercepted. I added the test

File: src/Components/Web.JS/src/Services/NavigationUtils.ts (hunk 3 above)
Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationUtils.ts]: I added `SVGAElement ` as return type too. Works fine
