### PR TITLE
Suppress CS1591 warnings for PublicTopLevelProgram.Generated.g.cs

### LINKED ISSUE #60683: [10.0-preview.1] CS1591 warnings-as-errors caused by Program class being exposed as public
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm in the middle of working on updating Swashbuckle.AspNetCore to support ASP.NET Core 10 and Microsoft.OpenApi v2 and stumbled into a compilation issue caused by [this new feature](https://github.com/dotnet/core/blob/main/release-notes/10.0/preview/preview1/aspnetcore.md#improvements-to-integration-testing-of-apps-with-top-level-statements).

We have a test project where warnings-as-errors is enabled as part of testing XML documentation support, and when targeting `net10.0` the project fails to compile with the following error:

```text
Missing XML comment for publicly visible type or member 'Program'
```

This is extra puzzling, as the `Program.cs` file [already has code to manually expose the class](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/446c522d496363fec3d4c759546f7ae2a7fe318c/test/WebSites/WebApi/Program.cs#L37-L45):

```csharp
namespace WebApi
{
    /// <summary>
    /// Expose the Program class for use with <c>WebApplicationFactory</c>
    /// </summary>
    public partial class Program
    {
    }
}
```

I guess the easiest way to resolve this would be to have the source generator emit a `#pragma` to silence the documentation warnings.

### Expected Behavior

The project compiles with no warnings/errors.

### Steps To Reproduce

Build the `WebApi` project from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/446c522d496363fec3d4c759546f7ae2a7fe318c without [this workaround](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/446c522d496363fec3d4c759546f7ae2a7fe318c/test/WebSites/WebApi/WebApi.csproj#L11-L14).

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-preview.1.25120.13

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by benhopkinstech**
## Description

- Suppress CS1591 compiler warnings for PublicTopLevelProgram.Generated.g.cs
- Added some additional tests surrounding namespaces

Fixes #60683

### CODE REVIEW

**Comment by benhopkinstech** [comment]
@dotnet-policy-service agree

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs [hunk 1]
```diff
@@ -10,30 +10,42 @@ namespace Microsoft.AspNetCore.SourceGenerators;
 [Generator]
 public class PublicProgramSourceGenerator : IIncrementalGenerator
 {
+    private const string Program = "Program";
     private const string PublicPartialProgramClassSource = """
 // <auto-generated />
+#pragma warning disable CS1591
```
Comment (captainsafia) [inline src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs:16]: I _don't_ think this is right here. AFAIK, analyzers shouldn't trigger on generated code.

In the past, I've noticed that the `// <auto-generated />` marker on the file isn't sufficient. We might also want to emit `[GeneratedCode]` here to mark this type as generated.

You can see how we do it for [the OpenAPI XML generator](https://github.com/dotnet/aspnetcore/blob/aa5687c0aa7a2600b5652da4cec2cbfba9e83314/src/OpenApi/gen/XmlCommentGenerator.Emitter.cs) and [the minimal API source generator](https://github.com/dotnet/aspnetcore/blob/aa5687c0aa7a2600b5652da4cec2cbfba9e83314/src/Http/Http.Extensions/gen/Microsoft.AspNetCore.Http.RequestDelegateGenerator/StaticRouteHandlerModel/StaticRouteHandlerModel.Emitter.cs).

**Comment by captainsafia** [comment]
@Youssef1313 Would appreciate your thoughts on this. It seems like there were some cases that the analyzer was false flagging earlier.

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs:16]: This is not an analyzer, it's a compile warning. There were discussions in dotnet/roslyn to special case that specific one for generated code, but I'm not sure if anything was done yet, or if any decision was taken.

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs [hunk 2]
```diff
@@ -10,30 +10,42 @@ namespace Microsoft.AspNetCore.SourceGenerators;
...
     {
         var internalGeneratedProgramClass = context.CompilationProvider.Select(static (compilation, cancellationToken) =>
+        {
+            // If there is a user-declared Program in a non-global namespace, skip generation
+            if (compilation.GetSymbolsWithName(Program, SymbolFilter.Type, cancellationToken)
+                .OfType<INamedTypeSymbol>()
+                .Any(symbol => !symbol.ContainingNamespace.IsGlobalNamespace))
+            {
+                return false;
+            }
```
Comment (Youssef1313) [inline src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs:31]: I feel like whether or not there is a class named `Program` in non-global-namespace is irrelevant? What's the use case that this change helps with?

File: src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs [hunk 3]
```diff
@@ -22,16 +22,25 @@ public async Task GeneratesSource_ProgramWithTopLevelStatements()
...
-    public async Task DoesNotGeneratesSource_IfProgramIsAlreadyPublic()
+    [Theory]
+    [InlineData("public partial class Program { }")]
+    [InlineData("""
+namespace Foo
+{
+    public partial class Program { }
+}
+""")]
+    public async Task DoesNotGeneratesSource_IfProgramIsAlreadyPublic(string declaration)
```
Comment (Youssef1313) [inline src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: I think this case *should* generate. The containing type of the entrypoint is *not* public in this case.

Because of the use of top-level statements, the compiler will synthesize a `Program` class in the global namespace. So, `Foo.Program` becomes irrelevant.

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 1 above)
Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs:16]: Projects that have `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in the .csproj will have the CS1591 compiler warning when the current generated code is output preventing building the solution

CS1591 looks as follows in this case
`Missing XML comment for publicly visible type or member 'Program'`

This `#pragma` should suppress this warning

File: src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs (hunk 3 above)
Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: It does seem a bit of a workaround and the analyzer ASP0027 doesn't pick this up for removal when it is within a user-defined namespace.

I don't think it is correct the user defining a namespace in this way and putting the Program within it but it has obviously worked for them prior to the auto generation logic.

The logic in `PublicTopLevelProgramGenerator.cs` prior to my change only fails on the `DoesNotGeneratesSource_IfProgramIsAlreadyPublic` and `DoesNotGeneratesSource_IfProgramDeclaresExplicitInternalAccess` namespace version of the tests, the rest of the namespace tests I have added passed successfully.

If we can agree on what this should be doing in this minimal API scenario where the user has defined a namespace I can adjust the logic and tests accordingly.

Comment (Youssef1313) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: I *think* the generator should still run in that case, as the user-defined Program class is completely unrelated to the entrypoint. It's just as any regular type. Maybe the analyzer should be relaxed in this case, if it's currently producing a diagnostic. @captainsafia What do you think?

Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: The analyzer is not producing a diagnostic in this case, so that is probably correct if the generator should be running in this case as per your comments

Comment (Youssef1313) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: If the generator is running in this case and the analyzer is not producing a diagnostic, then I'm not following on what the issue is

Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: Please see this [file](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/446c522d496363fec3d4c759546f7ae2a7fe318c/test/WebSites/WebApi/Program.cs#L37-L45) which gives an example.

The user has a Program declaration and xml comment within a namespace in the `Program.cs`. The user was receiving the CS1591 compiler warning after upgrading to net10 due to the code being generated in this scenario. They were under the impression they had a declaration already that contains the xml doc comment which caused some confusion.

This is probably how it should be acting based on your comments and we just require the `#pragma` on the generated code to suppress this warning.

We will await @captainsafia's comments.

Comment (Youssef1313) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs:41]: The #pragma warning disable change is good to me. But the change on whether or not the generation happens is questionable.

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 2 above)
Comment (captainsafia) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]: > He had a Program class that was in a user-declared namespace (with relevant xml doc comment) but the code was still getting generated and throwing the CS1591 compiler warning.

I don't think we got confirmation that this was indeed what was happening.

@martincostello Would you be able to verify if this source generator was triggering by settign `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` and seeing if you see a source file emitted?

File: src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs (hunk 3 above)
Comment (captainsafia) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs]: > The #pragma warning disable change is good to me. But the change on whether or not the generation happens is questionable.

I agree with this as well. I want to get more clarity on the exact repro (see https://github.com/dotnet/aspnetcore/pull/60727#discussion_r1979713937) before we make the other changes.

The analyzer and the source generator are two separate entities. There is a chance that the analyzer is not emitting a diagnostic for a given syntax structure but the source generator is emitting source code regardless.

Some additional tests in https://github.com/dotnet/aspnetcore/blob/1f82fa558dd7afb0ac94a43c7b80f40499bad98c/src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs should help us verify this.

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 2 above)
Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]: @captainsafia I have this sln cloned in the issue, I also needed to add 
`<CompilerGeneratedFilesOutputPath>...</CompilerGeneratedFilesOutputPath>` 
This has produced the below file so it is generating
`...\Microsoft.AspNetCore.App.SourceGenerators\Microsoft.AspNetCore.SourceGenerators.PublicProgramSourceGenerator\PublicTopLevelProgram.Generated.g.cs`

It is also confirmed by the tests that are in the latest changes

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 1 above)
Comment (benhopkinstech) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs:15]: Something important to note is that the project in the issue only has the CS1591 warning preventing the build due to them also having
`<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`
That being said we still don't want this warning to flag for the generated code when the below option is stated in the project
`<GenerateDocumentationFile>true</GenerateDocumentationFile>`

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs (hunk 2 above)
Comment (martincostello) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]: (If you still need me to try this out I can take a look tomorrow)

Comment (captainsafia) [reply src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]: @benhopkinstech Thanks for verifying this, Ben! @martincostello I think we're good to go here.

**Review by captainsafia — APPROVED** [review]

File: src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs (hunk 3 above)
Comment (Youssef1313) [reply src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs]: @captainsafia Not that I know of.
