### PR TITLE
Parsing extension-av on Set Cookie header

### LINKED ISSUE #22077: Parsing a cookie fails when there is an invalid key in the cookie value
### If cookie value contains `Discard` the entire cookie parsing yields an empty set

We are using `SetCookieHeaderValue.ParseList` (https://github.com/dotnet/aspnetcore/blob/master/src/Http/Headers/src/SetCookieHeaderValue.cs) to parse a Set-Cookie response. The http response from which the cookie is parsed is the following:

image

This `Discard` in there makes the entire parse return an empty list. If this `Discard` is removed, or it is replaced with `Secure`, parsing succeeds.

#### Unit test project based on `Microsoft.NET.Sdk.Web`

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

</Project>
```

#### Unit test code

```csharp
using Microsoft.Net.Http.Headers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CookieParserTest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            // Ok
            var cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/" });
            Assert.AreEqual(1, cookies.Count);

            // Ok
            cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/; Secure" });
            Assert.AreEqual(1, cookies.Count);

            // Fail
            cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/; Discard" });
            Assert.AreEqual(1, cookies.Count);
        }
    }
}
```

### Requires ASP.NET SDK
- Tested on ASP.NET Core version 3.1.4 (project is based on sdk `Microsoft.NET.Sdk.Web`)
- When using NuGet `Microsoft.Net.Http.Headers` 2.2.8 directly in a project based on `Microsoft.NET.Sdk` parsing is actually correct

### PR DESCRIPTION
**Pull request by ostorc**
This PR adds support for parsing extension-uv  and storing data retrieved from it.

Fixes #22077

### CODE REVIEW

File: src/Http/Headers/src/SetCookieHeaderValue.cs [hunk 1]
```diff
@@ -554,12 +580,13 @@ public override bool Equals(object obj)
                 && StringSegment.Equals(Path, other.Path, StringComparison.OrdinalIgnoreCase)
                 && Secure == other.Secure
                 && SameSite == other.SameSite
-                && HttpOnly == other.HttpOnly;
+                && HttpOnly == other.HttpOnly
+                && HeaderUtilities.AreEqualCollections(Extensions, other.Extensions);
```
Comment (Tratcher) [inline src/Http/Headers/src/SetCookieHeaderValue.cs:584]: Does this consider order of extensions?

**Review by Tratcher — COMMENTED** [review]
Seems like a good start. The tests will be the most telling for a change like this. Don't forget to update the reference assemblies.

File: src/Http/Headers/src/SetCookieHeaderValue.cs (hunk 1 above)
Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Changed that to consider order of extensions

Comment (Tratcher) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Sorry, I meant the opposite, order shouldn't matter.

Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Oh, I was thinking what you meant by that and chose the wrong option. I have reverted it back and changed the test for it.

Comment (Tratcher) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Yeah, I just meant to ask about the behavior of HeaderUtilities.AreEqualCollections.

Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Just to confirm things. The HeaderUtilities.AreEqualCollections is indeed checking if two unordered list have same content. It does it ing O(n*m) time, but since the number of extensions is not likely to reach any high number, so it doesn't really matter.

**Review by Tratcher — COMMENTED** [review]
A few style issues to address.

The commas are my biggest behavioral question though.

**Comment by BrennanConroy** [comment]
@ostorc Can you take a look at the feedback?

**Comment by shirhatti** [comment]
@ostorc Are you still working on this?

**Comment by ostorc** [comment]
Hi, I am sorry for the dealy. I had really busy week. I will finish changes today and update the PR.

File: src/Http/Headers/ref/Microsoft.Net.Http.Headers.netcoreapp.cs [hunk 2]
```diff
@@ -329,6 +329,7 @@ public partial class SetCookieHeaderValue
         public SetCookieHeaderValue(Microsoft.Extensions.Primitives.StringSegment name, Microsoft.Extensions.Primitives.StringSegment value) { }
         public Microsoft.Extensions.Primitives.StringSegment Domain { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
         public System.DateTimeOffset? Expires { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
+        public System.Collections.Generic.List<Microsoft.Extensions.Primitives.StringSegment> Extensions { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
```
[the remark this answers is not in the document]
Comment (ostorc) [reply src/Http/Headers/ref/Microsoft.Net.Http.Headers.netcoreapp.cs]: Fixed

File: src/Http/Headers/src/SetCookieHeaderValue.cs [hunk 3]
```diff
@@ -498,13 +525,13 @@ private static int GetSetCookieLength(StringSegment input, int startIndex, out S
...
-                    if (!ReadEqualsSign(input, ref offset))
-                    {
-                        return 0;
-                    }
-                    ReadToSemicolonOrEnd(input, ref offset);
+                    var tokenStart = offset - itemLength;
+                    ReadToSemicolonOrEnd(input, ref offset, includeComma: true);
+
+                    if (result.Extensions == null)
+                        result.Extensions = new List<StringSegment>();
```
[the remark this answers is not in the document]
Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Updated all cases

File: src/Http/Headers/src/SetCookieHeaderValue.cs [hunk 4]
```diff
@@ -523,14 +550,28 @@ private static bool ReadEqualsSign(StringSegment input, ref int offset)
             return true;
         }
 
-        private static StringSegment ReadToSemicolonOrEnd(StringSegment input, ref int offset)
+        private static StringSegment ReadToSemicolonOrEnd(StringSegment input, ref int offset, bool includeComma = false)
```
[the remark this answers is not in the document]
Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Changed default value to check comma too. Added new test data, which check all combinations of valid data and the test showed that this is needed change. Only exception is parsing of Expire, where in date may be comma.

File: src/Http/Headers/src/SetCookieHeaderValue.cs [hunk 5]
```diff
@@ -98,6 +99,8 @@ public StringSegment Value
 
         public bool HttpOnly { get; set; }
 
+        public List<StringSegment> Extensions { get; set; }
```
[the remark this answers is not in the document]
Comment (ostorc) [reply src/Http/Headers/src/SetCookieHeaderValue.cs]: Fixed that to:
```csharp
 public IList<StringSegment> Extensions { get; } = new List<StringSegment>();
```

**Review by Tratcher — APPROVED** [review]
Sorry, one merge conflict to resolve and I think you're done.

**Comment by ostorc** [comment]
Conflict resolved

**Comment by Tratcher** [comment]
Thanks
