### PR TITLE
Avoid trying to use _hotReloadAgent variable before it is initialized

### LINKED ISSUE #45190: CLI Hot reload for Blazor wasm still doesn't work in .NET 7
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

#40587 was supposed to be fixed in .NET 7 with https://github.com/dotnet/sdk/pull/27699. But there is still the same problem. Blazor wasm hot reload still breaks all the time

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

7.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thaystg**
Fixes https://github.com/dotnet/aspnetcore/issues/45190

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs [hunk 1]
```diff
@@ -50,14 +45,22 @@ internal static async Task InitializeAsync()
     [JSInvokable(nameof(ApplyHotReloadDelta))]
     public static void ApplyHotReloadDelta(string moduleIdString, byte[] metadataDelta, byte[] ilDelta, byte[] pdbBytes)
     {
+        // Analyzer has a bug where it doesn't handle ConditionalAttribute: https://github.com/dotnet/roslyn/issues/63464
+#pragma warning disable IDE0200 // Remove unnecessary lambda expression
+        if (_hotReloadAgent == null)
```
Comment (tmat) [inline src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: Shouldn't this be `Interlocked.CompareExchange` to avoid multiple threads ending up with different instances?

Comment (thaystg) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: I think that if it has multiple initialization, it is not an issue for the runtime.
But I will change as you suggested to avoid any issue.

File: src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs [hunk 2]
```diff
@@ -50,14 +45,19 @@ internal static async Task InitializeAsync()
     [JSInvokable(nameof(ApplyHotReloadDelta))]
     public static void ApplyHotReloadDelta(string moduleIdString, byte[] metadataDelta, byte[] ilDelta, byte[] pdbBytes)
     {
+        // Analyzer has a bug where it doesn't handle ConditionalAttribute: https://github.com/dotnet/roslyn/issues/63464
+#pragma warning disable IDE0200 // Remove unnecessary lambda expression
+        Interlocked.CompareExchange(ref _hotReloadAgent, new HotReloadAgent(m => Debug.WriteLine(m)), null);
```
Comment (mkArtakMSFT) [inline src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: Will a new HotReloadAgent be initialized even in case if the value shouldn't be replaced here? I assume the compiler is smart enough not to do that, but I'm not sure, hence my question.

Comment (mkArtakMSFT) [inline src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: Why does the initialization in the `InitializeAsync` method is not enough? Does the value gets discarded through some other codepath?

Comment (thaystg) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: As the InitializeAsync is an async method what was happening is that in a race condition before _hotReloadAgent is initialized on InitializeAsync it was trying to be used on ApplyHotReloadDelta method and throwing the NRE exception.

Comment (mkArtakMSFT) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: That sounds like a bug in the consuming code then, rather than here, isn't it? So the consumder then should just make sure they wait for the initialization before trying to apply changes.

Comment (thaystg) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: Interlocked.CompareExchange is thread safe and will avoid creating two HotReloadAgent in two different threads.
It compares two values for equality and, if they are equal, replaces the first value.

https://learn.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=net-7.0#system-threading-interlocked-compareexchange(system-object@-system-object-system-object)

Comment (thaystg) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: I'm not sure if it's possivel to check if InitializeAsync is done before calling the ApplyHotReloadDelta as it's called by dotnet watch.

image

**Review by mkArtakMSFT — APPROVED** [review]
Discussed my comments with @thaystg.
Looks like fixing the initialization code on the dotnet-watch is a compromise which had been thought about already.

File: src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs (hunk 2 above)
Comment (tmat) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: It is possible that there is an issue with initialization. I am not sure what exactly the initialization sequence for WASM is supposed to do. It'd be great if anyone knows and can review the code paths.

Comment (thaystg) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs:50]: Here is where InitializeAsync is called:
https://github.com/dotnet/aspnetcore/blob/6647d80ab886b8616e5b34812853e00358c93ce5/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs#L141

And here is where it's calling the applyHotReload function on JS from dotnet watch:
https://github.com/dotnet/sdk/blob/fbc089ea96f0187c31e9ae176278334c8d5defc6/src/BuiltInTools/BrowserRefresh/BlazorHotReload.js#L16

Which will call the ApplyHotReloadDelta on C# side:
https://github.com/dotnet/aspnetcore/blob/6647d80ab886b8616e5b34812853e00358c93ce5/src/Components/Web.JS/src/Boot.WebAssembly.ts#L48

I think there is no way to guarantee that InitializeAsync is done before calling the ApplyHotReloadDelta, I guess that this is the correct fix.

**Review by tmat — APPROVED** [review]
