### PR TITLE
Avoid cookie login redirects for known API endpoints

### LINKED ISSUE #9039: ApiController redirects to login page
### Describe the bug
When using ASP.NET Identity cookie authentication to protect a API controller that is decorated with the `ApiController` attribute and performing an unauthorized HTTP request, ASP.NET redirects to /Identity/Account/Login?ReturnUrl=%2Fapi%2FFoo instead of just returning a 401 Unauthorized status code and problem details in JSON format.

### To Reproduce
1. Configure ASP.NET Core to use ASP.NET Identity with default identity and default UI which uses cookies.
2. Create a API controller that you decorate with the `ApiController` attribute.
3. Perform a HTTP request (Content-Type can even be application/json) against the controller.

Using ASP.NET 2.2.
```cs
    [ApiController] // <-- I want this controller to behave like an API. 
    [Authorize]     // <-- Authenticate using cookies.
    [Route("api/[controller]")]
    public class FooController : ControllerBase
    {
        [HttpGet]
        public string Get()
        {
            return "string";
        }
    }
```

```cs
        public void ConfigureServices(IServiceCollection services)
        {
            /// ...
            services.AddDefaultIdentity<IdentityUser>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>();
            // ...
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // ...
            app.UseAuthentication();
            // ...
        }
```

### Expected behavior
I expected the API to behave as an API since I explicitly decorated the controller with the `ApiController` attribute.
I expected it to return the status code 401 Unauthorized.
Maybe with a link to: https://httpstatuses.com/401

### PR DESCRIPTION
**Pull request by halter73**
This adds IApiEndpointMetadata as new public API. It doesn't add any attributes or extension methods, but we do add it automatically for endpoints where RDF/RDG read a JSON request body or write a JSON response body. ApiController endpoints, SignalR endpoints and endpoints with TypedResults return-types that we know to be API-oriented also get this metadata automatically.

API Proposal: #62883

Fixes #9039

### CODE REVIEW

File: src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs [hunk 1]
```diff
@@ -125,6 +126,9 @@ public static ConnectionEndpointRouteBuilder MapConnections(this IEndpointRouteB
             {
                 e.Metadata.Add(data);
             }
+
+            // Add INonBrowserEndpointMetadata to indicate this is a non-browser endpoint (SignalR)
```
Comment (BrennanConroy) [inline src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs]:
```suggestion
            // Add IApiEndpointMetadata to indicate this is a non-browser endpoint (SignalR)
```

Comment (BrennanConroy) [reply src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs]: Wonder if there are any blazor endpoints that should also be marked?

Comment (halter73) [reply src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs]: One of the big reasons that I went with this approach rather than trying to detect fetch requests is because blazor will gracefully handle redirects during enhanced navigation. If we started returning 401s instead of redirecting, we'd break the default Blazor template with individual auth. We could special case blazor fetch requests to avoid this, but I thought it was indicative of the risk of defaulting to 401 for all fetch requests.

For the circuit endpoints, we already get the better behavior because if this change to the SignalR endpoints. It's possible that I'm missing some Blazor related API endpoints that don't get picked up automatically by the RDF/RDG changes (MapIdentityApi is an example of endpoints that get the metadata for free this way), but I'm not sure what they'd be off the top of my head. @javiercn @MackinnonBuck Do you have any suggestions?

**Review by captainsafia — APPROVED** [review]

File: src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/common/Http.Connections/src/ConnectionEndpointRouteBuilderExtensions.cs]: https://github.com/dotnet/aspnetcore/blob/bf1f642be9fe230fed38e10561d4aa9ed5859b8f/src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs#L78-L86

These are what I was thinking of @dotnet/aspnet-blazor-eng thoughts?
