### PR TITLE
XML doc for generated public partial Program class

### LINKED ISSUE #61783: Analyzer warning for missing XML doc on source-generated Program class
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Beginning with .NET 10 preview1, a source generator adds `public partial class Program` to a Program.cs file that uses top-level statements. This automates a step that developers previously had to do manually for integration testing of their apps.

But when the project is configured to `GenerateDocumentationFile`, this results in an odd analyzer warning on the first statement in Program.cs:

Image

But the warning cannot be resolved by adding an XML comment above this first statement (which is actually the fix suggested by Copilot):

Image

The only way I could find to resolve this is by adding `public partial class Program {};` at the end of the file with an XML comment on it.

Image

Oh ... there is another way, which is to suppress the analyzer warning for missing XML comment on the `public partial class Program;` statement:

Image

### Expected Behavior

I think statements added by source generators should not cause analyzer warnings. So I think the source generator in this case should add the suppression pragmas as shown above.

### Steps To Reproduce

Create a new .NET 10 webapi and then enable `GenerateDocumentationFile` in the project file.

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-preview.4.25229.110

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by benhopkinstech**
## Description

Replaced the suppression in favour of an XML doc on the auto-generated public partial Program class

@captainsafia as discussed in https://github.com/dotnet/aspnetcore/issues/61783#issuecomment-3071924326

Let me know if you would like any changes to the text

Fixes #61783

### CODE REVIEW

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs [hunk 1]
```diff
@@ -12,11 +12,12 @@ public class PublicProgramSourceGenerator : IIncrementalGenerator
 {
     private const string PublicPartialProgramClassSource = """
 // <auto-generated />
-#pragma warning disable CS1591
+/// <summary>
+/// Auto-generated public partial Program class for top-level statement apps
```
Comment (martincostello) [inline src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]: Just because I'm aware of a StyleCop rule somewhere that warns on docs that don't end with a full stop, and I'm not sure if this would trigger it or not.

```suggestion
/// Auto-generated public partial Program class for top-level statement apps.
```

File: src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs [hunk 2]
```diff
@@ -9,9 +9,10 @@ public class PublicTopLevelProgramGeneratorTests
 {
     private const string ExpectedGeneratedSource = """
 // <auto-generated />
-#pragma warning disable CS1591
+/// <summary>
+/// Auto-generated public partial Program class for top-level statement apps
```
Comment (martincostello) [inline src/Framework/AspNetCoreAnalyzers/test/SourceGenerators/PublicTopLevelProgramGeneratorTests.cs]:
```suggestion
/// Auto-generated public partial Program class for top-level statement apps.
```

File: src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs [hunk 3]
```diff
@@ -12,11 +12,12 @@ public class PublicProgramSourceGenerator : IIncrementalGenerator
...
 // <auto-generated />
-#pragma warning disable CS1591
+/// <summary>
+/// Auto-generated public partial Program class for top-level statement apps.
+/// </summary>
 public partial class Program { }
-#pragma warning restore CS1591
 """;
-
+
```
Comment (captainsafia) [inline src/Framework/AspNetCoreAnalyzers/src/SourceGenerators/PublicTopLevelProgramGenerator.cs]:
```suggestion

```

**Review by captainsafia — APPROVED** [review]
Thanks! 😄
