### PR TITLE
Fix #6102 - Intense CPU utilization on page change (#6542)

### LINKED ISSUE #6102: Memory Leak in new ASPNET 2.2 routing?
### Describe the bug
I was editing some Razor Pages (the `Project\Pages` kind) then refreshing the changes in Chrome (Version 71.0.3578.98). My dev loop is tight, so I make a small edit then refresh the page, and the change is visible in Chrome.

Eventually, I noticed my edits were not making their way to the browser. On a few occasions, I noticed waiting a longer time delay before refreshing the browser *sometimes* helped the situation. Eventually, though, edits would no longer make their way to the browser.

Originally, I was using `InProcess` but decided to switch to `OutOfProcess`, rebooted PC, and the same problem occurred. Somewhere between 15 minutes to 1 hour of constantly editing Razor Pages in Visual Studio, I begin to notice my edits not showing up in the browser.

With out of `OutOfProcess` enabled, I noticed, a massive **9.7 GB** memory usage in `dotnet.exe`

procexp64_2548

(later, trying to debug `dotnet.exe`, we're up at **27GB**)
devenv_2562

procexp64_2550

`dotnet.exe`:
screen_2567

As `dotnet.exe` consumes memory, there appears to be a few threads that pop off `coreclr_shutdown`. Not much to discern, but worth noting.

Next, I attached a VS debugger to `dotnet.exe`, broke into the debugger and landed in `Program.Main()`. None of my user code was running. **Continue & Pausing** the debugger multiple times did show one thread standing out. Specifically, **Thread 3952** playing around in the new ASPNET Core 22 routing code? `Microsoft.AspNetCore.Routing.DecisionTree`.

Specifically, `Array.Copy`, `DecisionTree.Resize` and `Capacity.set` seem to be popular destinations with **Thread 3952**. **Thread 3952** is the only thread that appears to be active during this memory leak.

devenv_2561
devenv_2560
devenv_2558
devenv_2557

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Edit somewhat complex Razor Pages for about 15 minutes to 1 hour in a tight dev loop.

### Expected behavior
I should be able to make edits in Razor Pages and see my changes in the browser without having to restart `IISExpress` or kill `dotnet.exe` manually or experience a memory leak during the editing experience.

#### Operating System
* Windows 7

#### IDE
* Visual Studio 15.9.4
```
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Also, here is **Process Monitor** monitoring file access during the memory leak event:
procmon64_2553

-----

I will continue to do more testing to see if I can narrow down the issue. Thanks for your help in advance.

Thanks,
Brian Chavez

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

### PR DESCRIPTION
**Pull request by rynowak**
#### Description 

https://github.com/aspnet/AspNetCore/issues/6543

The routing system in ASP.NET Core supports changing when a Razor Page is added, removed, or edited. 2.2.0 has a bug where the address table in Endpoint Routing subscribes to route table change notifications an additional time each time a change occurs. This means that each route table change is processed N additional times when it occurs - where N is the number of changes so far.
 
#### Customer Impact 

Developers can see high CPU and memory utilization when they make a change that triggers rebuilding of the route table (edit a Razor Page while the site is running). This will escalate over time as more changes are made until the application becomes unusable. Customers will primarily hit this in inner-loop development, but this can also happen in production. We know that many developers like to have recompilation available in production.
 
#### Regression? 

Yes, this is a bug in a new 2.2 feature. 
 
#### Risk

Low. The fix is to remove the offending line of code. Additional steps are taken to harden the code, and add `IDisposable` support so that infrastructure pieces unsubscribe from change notifications when disposed.

Since these changes are infrastructure, there is no impact in the user-visible behavior.

-------

The issue here was that every time a Razor Page changed, we would
subscribe an additional time to the endpoint change notifications. This
means that if you tweaked a page 30 times, we would update the address
table 31 times when you save the file. If you were doing a lot of editing
then this would grow to a really large amount of computation.

The fix is to use DataSourceDependentCache, which is an existing utility
type we developed for this purpose. I'm not sure why it wasn't being
used for this already. We're already using DataSourceDependentCache in a
bunch of other places, and it's well tested.

I also tweaked the stucture of this code to be more similar to
EndpointNameAddressScheme. This involved some test changes that all
seemed like good cleanup. The way this was being tested was a little
wonky.

(cherry picked from commit a5658a8c95c4f8868e7e6db54303f278d34efe87)

### CODE REVIEW

**Comment by rynowak** [comment]
This is a straightforward cherry-pick of the fix from master.

**Comment by JamesNK** [comment]
You need to put your description into the ship room template and tag with servicing consider 😋 

e.g. https://github.com/aspnet/AspNetCore/pull/6645

**Comment by rynowak** [comment]
Updated

File: src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs [hunk 1]
```diff
@@ -48,5 +52,41 @@ private Matcher CreateMatcher(IReadOnlyList<Endpoint> endpoints)
...
+                    }
+                }
+            }
+
+            public void Dispose()
+            {
+                lock (_lock)
+                {
+                    _cache?.Dispose();
+                    _cache = null;
```
[the remark this answers is not in the document]
Comment (rynowak) [reply src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs]: I don't think so because when you set `Cache` it would immediately dispose the value. This is really about the possibility that someone will dispose the services while the data source matcher is being initialized. There isn't any code that sets this value over and over.

**Review by JamesNK — APPROVED** [review]

File: src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (JamesNK) [reply src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs]: ok!

File: src/Http/Routing/src/DataSourceDependentCache.cs [hunk 2]
```diff
@@ -18,6 +18,9 @@ internal class DataSourceDependentCache<T> where T : class
         private object _lock;
```
Comment (mkArtakMSFT) [inline src/Http/Routing/src/DataSourceDependentCache.cs]: I would also mark this as `readonly`

File: src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs [hunk 3]
```diff
@@ -16,12 +15,17 @@ internal class DataSourceDependentMatcher : Matcher
...
             Func<MatcherBuilder> matcherBuilderFactory)
         {
             _matcherBuilderFactory = matcherBuilderFactory;
 
             _cache = new DataSourceDependentCache<Matcher>(dataSource, CreateMatcher);
             _cache.EnsureInitialized();
+
+            // This will Dispose the cache when the lifetime is disposed, this allows
+            // the service provider to manage the lifetime of the cache.
+            lifetime.Cache = _cache;
```
Comment (mkArtakMSFT) [inline src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs]: lifetime being null will result in NRE. That may be by design, just making sure it has been thought of.

File: src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs [hunk 4]
```diff
@@ -48,5 +52,41 @@ private Matcher CreateMatcher(IReadOnlyList<Endpoint> endpoints)
...
+            public DataSourceDependentCache<Matcher> Cache
+            {
+                get => _cache;
+                set
+                {
+                    lock (_lock)
+                    {
+                        if (_disposed)
+                        {
+                            value?.Dispose();
```
Comment (mkArtakMSFT) [inline src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs]: This will allow operating on a disposed instance. Should it rather throw an ObjectDisposedException in this case?

**Review by mkArtakMSFT — APPROVED** [review]
Just couple of notes to consider.

File: src/Http/Routing/src/DataSourceDependentCache.cs (hunk 2 above)
Comment (rynowak) [reply src/Http/Routing/src/DataSourceDependentCache.cs]: This is used with LazyIntialializer, it can't be readonly.

**Comment by natemcmaster** [comment]
Can you please update eng/PatchConfig.props to list the packages which need to ship an update?

**Comment by leecow** [comment]
Approved. Merge soon ;-)

**Comment by dougbu** [comment]
@rynowak I'm surprised you don't have merge conflicts because the 2.2.2 section already exists and contains a few rows. The changes otherwise look fine.

**Comment by mikaelm12** [comment]
>  I'm surprised you don't have merge conflicts because the 2.2.2 section already exists and contains a few rows.

Yeah, I figured you would need to rebase. Not sure why github isn't reporting a conflict there since there definitely are changes in the `PatchConfig.props` in the 2.2 branch.

**Comment by JamesNK** [comment]
A patch PR of mine will add `Microsoft.AspNetCore.Routing` to the file.

**Comment by rynowak** [comment]
I was also surprised not to see it. Should I rebase?

**Comment by mikaelm12** [comment]
James already added the package to the PatchConfig.props so you're change to it is no longer showing up. You could rebase to be safe but I don't think it's necessary.
