### PR TITLE
Fix link click interception in shadow roots

### LINKED ISSUE #27070: Blazor <a href> link in ShadowDOM causes page reload, correct way to redirect from href="javascript:"?
Hello AspNetCore Team,

I use a Html WebComponent for Navigation from our Design System which internally generates a

<a hef="SublinkA/SublinkB"

My browser shows me: localhost:55003/SublinkA/SublinkB as URL, localhost:55003 is my blazor webassembly page

If I press the <a> link, Blazor does not route internally but instead the page gets reloaded to the new location.

Now if I put the Link into Blazor-NavLink obviously blazor redirects the link correctly without reloading the whole page.

Now the < a href > gets generated inside an html webcomponent where I don't have any Blazor NavLinks
but I can pass any url for example

< a href="javascript:RedirectTheBlazorWay()">bla</ >
```

Now instead of calling in the href:
javascript:DotNet.invokeMethodAsync("RedirectTheBlazorWay", controlRef, "SublinkA/SublinkB")

And Registering:
    [JSInvokable("RedirectTheBlazorWay")]
    public Task RedirectTheBlazorWay(string url)
    {
        NavigationManager.NavigateTo(url, forceLoad: false);
        return Task.CompletedTask;
    }
```

where RedirectTheBlazorWay needs to be a non static method because otherwise I cannot inject the NavigationManager
is there an easy way to redirect inside the blazor page?

 Like javascript:DotNet.navigateTo(xyz)?

Or is there an error with my url that the link is not recognized as an local url.

Sorry if this was asked already but did not find any resources.
Just found this: https://chrissainty.com/an-in-depth-look-at-routing-in-blazor/

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is a fix for #27070, which we should consider for a patch.

#### Description

HTML `<a>` elements within shadow roots are invisible to the link click interception code. So when an end user clicks on a link that's inside the shadow root of a custom element, it triggers a full page load instead of a client-side navigation.

#### Customer Impact

Reported by a customer at #27070. There's no reasonable workaround (besides not using custom elements and shadow DOM).

The impact is that if you're using a library of custom HTML elements, which typically use ShadowDOM to render, then if you use them to produce any links, then those links will seem broken to the end user (as in, they trigger a full-page reload, destroying any app state in WebAssembly memory or discarding the Blazor Server circuit).

#### Regression?

No, this has always been the case. However, the use of custom elements and ShadowDOM is a growing area, especially as we try to guide customers to use custom elements like the FAST components.

The fact that this use case is growing in importance makes it relevant to consider patching rather than waiting a full year for 6.0.

We don't **have** to ship this in 5.0.1, but we should be prepared to ship it in a patch reasonably soon.

#### Risk

This changes the logic for processing clicks on all links, not just the ones in shadow roots. Although I'm not aware of any cases where the new logic might fail, and all our E2E tests pass, maybe I missed some case. It's unfortunate we don't have any opportunity to put this in front of customers any any preview form.

One possible mitigation would be putting this in `master` right away, and waiting until 5.0.2 (or later) to ship it as a patch, just in case anybody discovers problems in a 6.0 preview.

### CODE REVIEW

File: src/Components/Web.JS/src/Services/NavigationManager.ts [hunk 1]
```diff
@@ -122,12 +122,34 @@ export function toAbsoluteUri(relativeUri: string) {
...
+      if (candidate instanceof Element && candidate.tagName === 'A') {
+        return candidate as HTMLAnchorElement;
+      }
+    }
+    return null;
+  } else {
+    // Since we're adding use of composedPath in a patch, retain compatibility with any
+    // legacy browsers that don't support it by falling back on the older logic, even
+    // though it won't work properly with ShadowDOM. This can be removed in the next
+    // major release.
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationManager.ts:142]: AFAIK there aren't any supported browsers that don't support Event.composedPath.

The only reason I'm keeping the older logic as fallback is in case someone has somehow polyfilled enough to make Blazor Server 5.0 run on IE11, in which case we don't want this patch to create the need to add yet another polyfill. I doubt anyone is in that situation, but this is being super-cautious because patch.

**Review by captainsafia — APPROVED** [review]
LGTM!

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS let me know if you want me to merge this (in case you don't have permissions to do so).

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Would it work OK if we chose not to merge this for 5.0.1, but instead hold it back until a later patch?

There's not much urgency to do this in 5.0.1 and it would be good to get a couple of months of extra coverage (via merging it to `master`) before it goes out in a patch.
