### PR TITLE
Fix returning buffered data after stream is drained

### LINKED ISSUE #7448: StreamPipeReader should return the buffered data even after the Stream is done
### Describe the bug
The StreamPipeReader should return the buffered data from the stream even after the underlying Stream has been drained. 

### To Reproduce

```C#
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication101
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Use(async (context, next) =>
            {
                if (context.Request.ContentLength is null)
                {
                    await next();
                    return;
                }

                await context.Request.BufferAsync();

                await next();
            });

            app.UseRouting(routes =>
            {
                routes.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });

                routes.MapPost("/api/values", async context =>
                {
                    var result = await context.Request.BodyPipe.ReadAsync();
                    var buffer = result.Buffer;

                    var value = Encoding.UTF8.GetString(buffer.ToArray());

                    await context.Response.WriteAsync(value);
                });
            });
        }
    }

    public static class RequestBufferingExtensions
    {
        public static async Task BufferAsync(this HttpRequest request)
        {
            // Buffer the entire request body into the pipe
            while (true)
            {
                var result = await request.BodyPipe.ReadAsync(request.HttpContext.RequestAborted);
                var buffer = result.Buffer;

                if (result.IsCompleted)
                {
                    break;
                }

                request.BodyPipe.AdvanceTo(buffer.Start, buffer.End);
            }
        }
    }
}
```

The above code tries to buffer all of the pipe's contents middleware before the post body is processed. 

### Expected behavior
I expected to get the entire post body in /api/values, instead I get a 0 byte read.

### Screenshots
image

Notice the buffered bytes is non-zero but the buffer returned is empty.

### Additional context
latest build

### PR DESCRIPTION
**Pull request by davidfowl**
- Change TryRead to return the buffer if the Stream is completed

Fixes #7448

### CODE REVIEW

File: src/Http/Http/src/StreamPipeReader.cs [hunk 1]
```diff
@@ -251,7 +251,7 @@ public override async ValueTask<ReadResult> ReadAsync(CancellationToken cancella
 
                     if (length == 0)
                     {
-                        _isWriterCompleted = true;
+                        _isStreamCompleted = true;
```
Comment (jkotalik) [inline src/Http/Http/src/StreamPipeReader.cs]: nit: _isInnerStreamCompleted?

**Review by jkotalik — APPROVED** [review]

File: src/Http/Http/src/StreamPipeReader.cs (hunk 1 above)
Comment (davidfowl) [reply src/Http/Http/src/StreamPipeReader.cs]: What other stream is there?

Comment (jkotalik) [reply src/Http/Http/src/StreamPipeReader.cs]: fine.

**Review by pakrym — APPROVED** [review]
