### PR TITLE
Make sure `WebRootComponentManager` is initialized for dynamic JS roots

### LINKED ISSUE #64159: [Blazor] PersistentState attribute causes javascript rendered components to fail.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The [PersistentState] attribute causes javascript created components to fail, such as components exposed using:
```
.AddInteractiveServerComponents(o => o.RootComponents.RegisterForJavaScript<Counter>("blazor-counter"));
```
And then added to the page using:
```
Blazor.rootComponents.add(document.getElementById("app"), "blazor-counter", {});
```
This was tested on .NET 10 rc2.

### Expected Behavior

The PersistentState attribute (and the ability to persist and then recover state) should work for components created using the JavaScript APIs, such as when using Blazor inside existing websites, be they legacy WebForms, react, static HTML, etc.  Passing state from server PreRendered components is only once scenario and there is no reason not to expect this feature to work for Blazor components loaded from a vanilla HTML page.  That scenario is the bulk of our Blazor development work.

I would hope it is a minor 1-2 line fix (see the exception I am getting below).

### Steps To Reproduce

To reproduce use the Blazor template (or the older blazorserver template if preferred:
```dotnet new blazor```

In Program.cs change this:
```
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();
```
To this:
```
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents(o => o.RootComponents.RegisterForJavaScript<Counter>("blazor-counter"));
```
Note: Add required using at the top of Program.cs:
```
using Microsoft.AspNetCore.Components.Web;
using TestProject.Components.Pages;
```
Note: Make sure the project name is correct above.

Edit the Counter.razor component and make the actual counter state persistent like this:
```
    // private int currentCount = 0;
    [PersistentState] public int currentCount {get; set;}
```

Note: The project and counter page should work *correctly* including the working PersistentState feature if you launch the app and browse to the counter page.  Now lets try creating an instance from javascript.

Create a test.html page in the wwwroot directory:
```
<html>
<body>
  <div id="app">
  </div>
 
  <script src="_framework/blazor.server.js" autostart="false"></script>
  <script>
    Blazor.start().then(() => {
      Blazor.rootComponents.add(document.getElementById("app"), "blazor-counter", {});
    });
  </script>
</body>
</html>
```
This causes an "Object reference not set to an instance of an object", and it looks internally like AspNetCore is looking for a parent component.  You can see the full exception below in the "Exceptions" section.

I also tried wrapping the component in a "CounterWrapper.razor" component and loading that instead.  In this second (more esoteric) case the component did work, but then failed when pausing and resuming the circuit. using the new API.

### Exceptions (if any)

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'F1Ra7RWBZRxzwLBMocG21wmgWNjn8pnr4zuWeskWIC8'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.GetMarkerKey(RemoteComponentState remoteComponentState)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteComponentState.GetComponentKey()

### .NET Version

10.0.100-rc.2.25502.107

### Anything else?

Note that I used the blazor web template to demonstrate this issue, and then included the blazor.server.js script as recommended.  The blazor.web.js script in general does not support javascript rendered components yet (Microsoft has a note on this and an open issue).  I also tried an older *blazorserver* template, upgraded to .NET 10, but in both cases the same bug appeared.

This is unfortunate because it not only means the PersistentState feature is not working when used on a vanilla HTML page; but that even just inclusion of the PersistentState attribute in a component will break that component when used in a vanilla HTML page like this.  Hopefully this is just a 1 line fix?

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/aspnetcore/issues/64159.

## Source of the issue:

`_webRootComponentManager` is not defined in 
https://github.com/dotnet/aspnetcore/blob/10ef00003cabb87fb2c00355ad472147679a5f99/src/Components/Server/src/Circuits/RemoteRenderer.cs#L324

## How it typically works :

 `_webRootComponentManager` gets created when `CircuitHost` goes through
https://github.com/dotnet/aspnetcore/blob/10ef00003cabb87fb2c00355ad472147679a5f99/src/Components/Server/src/Circuits/CircuitHost.cs#L882

That is the normal flow for prerendered/SSR roots: the client sends an `UpdateRootComponents` message, `CircuitHost` materialises the operations, the manager is created, and every root component added in that batch is registered inside the manager’s dictionary.

## How it works with dynamic JS root:

- The root cames from JavaScript via `Blazor.rootComponents.add(...)`. That call hits `CircuitJSComponentInterop.AddRootComponent`, which simply calls `base.AddRootComponent(...)` on the renderer:
https://github.com/dotnet/aspnetcore/blob/6819df1c75e529d3ccd0a86854577451aa2e26f8/src/Components/Web.JS/src/Rendering/JSRootComponents.ts#L27
https://github.com/dotnet/aspnetcore/blob/10ef00003cabb87fb2c00355ad472147679a5f99/src/Components/Server/src/Circuits/CircuitJSComponentInterop.cs#L26
(`getRequiredManager` is not the manager we are interested in, it's only a set of interop methods available for a given component, see https://github.com/dotnet/aspnetcore/blob/6819df1c75e529d3ccd0a86854577451aa2e26f8/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L78)
- This bypasses the whole `CircuitHost.PerformRootComponentOperations` pipeline, so `_webRootComponentManager` never gets initialised and no entry is recorded for the new component.
- When the renderer later constructs `RemoteComponentState` for that JS-added root, `RemoteComponentState.GetComponentKey()` invokes `RemoteRenderer.GetMarkerKey(...)`. Because the manager had never been created on this code path, `_webRootComponentManager` was still null and the null-forgiving access `!` resulted in the `NullReferenceException`.

## Fix:
- Make sure the manager is initialized.

### CODE REVIEW

File: src/Components/test/E2ETest/Tests/StatePersistenceTest.cs [hunk 1]
```diff
@@ -355,6 +355,18 @@ private void RenderComponentsWithPersistentStateAndValidate(
             interactiveRuntime: interactiveRuntime);
     }
 
+    [Fact]
```
Comment (ilonatommy) [inline src/Components/test/E2ETest/Tests/StatePersistenceTest.cs]: This should be a theory that would test not only `RemoteRenderer` but also `WebAssemblyRenderer`.

File: src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs [hunk 2]
```diff
@@ -46,6 +46,7 @@ public WebAssemblyRenderer(IServiceProvider serviceProvider, ResourceAssetCollec
 
         ElementReferenceContext = DefaultWebAssemblyJSRuntime.Instance.ElementReferenceContext;
         DefaultWebAssemblyJSRuntime.Instance.OnUpdateRootComponents += OnUpdateRootComponents;
+        GetOrCreateWebRootComponentManager();
```
Comment (ilonatommy) [inline src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs]: `OnUpdateRootComponents` alrady calls `GetOrCreateWebRootComponentManager` so Wasm rendering does not need additional lazy-initialization,

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 3]
```diff
@@ -50,6 +50,7 @@ public RemoteRenderer(
         ResourceAssetCollection resourceCollection = null)
         : base(serviceProvider, loggerFactory, jsRuntime.ReadJsonSerializerOptions(), jsComponentInterop)
     {
+        jsComponentInterop.SetRenderer(this);
```
Comment (ilonatommy) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Maybe we should add `RemoteJSRuntime .Instance.OnUpdateRootComponents` handle same as it's done in `WebAssemblyRenderer`?

**Comment by ilonatommy** [comment]
The tests:
`Circuit_CanShutDownAndReInitializeMultipleTimes`, `DotNetObjectReference_CannotBeUsed_AfterCircuitShutsDown_AndANewCircuitIsInitialized`, `StateIsProvidedEveryTimeACircuitGetsCreated` fail not because of the framework changes but because of test project changes  to `RazorComponentEndpointsStartup.cs`:

```
 + options.RootComponents.RegisterForJavaScript<TestContentPackage.PersistentComponents.ComponentWithPersistentState>("dynamic-js-root-counter");
```

The failure happens on reinitialization after shutdown. The reinitialization process doesn't properly handle the case where JS components with persistent state are registered but not yet added to the circuit. The circuit seems to get "stuck" during reinitialization - it connects (WebSocket shows connected):
```
[2025-11-24T12:43:08Z] [Info] http://127.0.0.1:51676/subdir/_framework/blazor.web.crlaspqfcs.js 0:59500 "[2025-11-24T12:43:08.420Z] Information: WebSocket connected to ws://127.0.0.1:51676/subdir/_blazor?id=shfXstthdREtTim5LfjW8g."
```
the HTML shows the component markup, but the components never become interactive (`<span id="is-interactive-1">False</span>` never changes to True). This suggests the circuit initialization hangs or fails silently somewhere.. (?)

The question is: how adding `RegisterForJavaScript` (calling `enableJSRootComponents` on client etc) influences the way we detect interactivity?

**Comment by ilonatommy** [comment]
> The question is: how adding `RegisterForJavaScript` (calling `enableJSRootComponents` on client etc) influences the way we detect interactivity?

Calling `enableJSRootComponents` throws when called more than once which breaks the flow:
https://github.com/dotnet/aspnetcore/blob/da2e7e169aa20f3c9d52c5f839f1965a1c083a9b/src/Components/Web.JS/src/Rendering/JSRootComponents.ts#L126

~~@javiercn, I'm planning to remove that exception and replace it with no-op.~~

Edit:
the comment above the exception "This will only happen in very nonstandard cases where someone has multiple hosts." makes me think no-op is not a good solution. I will file a separate issue (https://github.com/dotnet/aspnetcore/issues/64523) and make a workaround for tests to have this PR fix the original problem only.

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 4]
```diff
@@ -321,9 +321,13 @@ protected override ComponentState CreateComponentState(int componentId, ICompone
...
-        return remoteComponentState.ParentComponentState != null ?
-            default :
-            _webRootComponentManager!.GetRootComponentKey(remoteComponentState.ComponentId);
+        if (remoteComponentState.ParentComponentState != null)
+        {
+            return default;
+        }
+
+        var webRootComponentManager = _webRootComponentManager ?? GetOrCreateWebRootComponentManager();
+        return webRootComponentManager.GetRootComponentKey(remoteComponentState.ComponentId);
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: Rather than doing this here, can we instead make sure that `Renderer.GetOrCreateWebRootComponentManager();` is called within https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/Circuits/CircuitHost.cs or `CircuitFactory.cs`?

**Review by javiercn — APPROVED** [review]
Looks great!
