### PR TITLE
[Blazor] Allow properties marked with both `[Parameter]` and `[SupplyParameterFromQuery]` to receive values directly

### LINKED ISSUE #48937: [dotnet-sdk-8.0.100-preview.6.23316.32] Blazor component property doesn't recognize [Parameter] attribute when setting [SupplyParameterFromQuery] attribute together
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When run the 3rd party app against the latest .NET 8 Preview 6 build, start from dotnet-sdk-8.0.100-preview.6.23316.32, when a Blazor compont property using both [Parameter] attribute and [SupplyParameterFromQuery] attribute, application will crash with "Unhandled exception rendering component: Object of type '{ComponentName}' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied." exception.

**Application Name**: BootstrapBlazor
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.6.23316.32
**App Github Link**: https://github.com/dotnetcore/BootstrapBlazor
**App & Source Location**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1839677

**Verify Scenarios: **
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23320.1: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23316.32: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23312.5: Pass
4. Windows10 21h2 x64 + dotnet-sdk-7.0.107(default): Pass

### Expected Behavior

Counter page load successful with "Test Data: testvalue" diaplayed on the page.

### Steps To Reproduce

Minimal Repro steps (Demo attached): [BlazorApp2.zip](https://github.com/dotnet/aspnetcore/files/11814373/BlazorApp2.zip)

1. Create a default Blazor server project.

2. Add a TestComponent.razor file under Shared folder with following code:
```
 @page "/test"
<div>
    <span>Test Data :</span> <span>@Text</span>
    <br />
</div>
@code {
    [Parameter]
    [SupplyParameterFromQuery] //if we remove this attribute, it will work
    public string? Text { get; set; }
}
```
3. Add following highlight line of code in Counter.razor page:
```
<p role="status">Current count: @currentCount</p>
<TestComponent Text="testvalue"></TestComponent>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```
4. Build the project.

5. Change the runtime.config file to let the app run against with dotnet-sdk-8.0.100-preview.6.23316.32
 ```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.6.23316.3"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0-preview.6.23316.5"
      }
    ], 
```
6. Launch the demo app.
7. Click Counter page.

### Exceptions (if any)

**Counter page load failed with following stack trace:**
```
 Unhandled exception rendering component: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
      System.InvalidOperationException: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForSettingCascadingParameterWithNonCascadingValue(Type targetType, String parameterName)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'r3zRfDbXCKtWWl5HgY-rIhkop6uqhszUu5CF9L6wgig'.
      System.InvalidOperationException: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForSettingCascadingParameterWithNonCascadingValue(Type targetType, String parameterName)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree, Dictionary`2 namedEventIndexes)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'r3zRfDbXCKtWWl5HgY-rIhkop6uqhszUu5CF9L6wgig'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree, Dictionary`2 namedEventIndexes)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
### .NET Version

8.0.100-preview.6.23316.32

@dotnet-actwx-bot @dotnet/compat

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Allow properties marked with both `[Parameter]` and `[SupplyParameterFromQuery]` to receive values directly

Fixes an issue where if a component parameter was marked with both `[Parameter]` and `[SupplyParameterFromQuery]`, a misleading exception message would be thrown when the parameter's value was set directly.

## Description

Since #48554 was merged, marking a component parameter with both `[Parameter]` and `[SupplyParameterFromQuery]` would cause the following exception to be thrown if the parameter was set directly:

```
Object of type 'MyComponent' has a property matching the name 'MyParameter', but it does not have [ParameterAttribute] applied.
```

This error is misleading, because the parameter _does_ have `ParameterAttribute` applied. The existing parameter setting logic had assumed that if a component's property was marked with a cascading parameter attribute, it must not have also had the `[Parameter]` attribute applied, hence the misleading error message. Since `[SupplyParameterFromQuery]` recently became a cascading parameter attribute, it inherited that behavior.

## Solution

This PR fixes the issue by allowing `[Parameter]` and `[SupplyParameterFromQuery]` to both exist on a single property without causing an exception to be thrown. If both direct and cascading parameter values are supplied, the direct parameter value is preferred.

Fixes #48937

### CODE REVIEW

File: src/Components/Components/src/Reflection/ComponentProperties.cs [hunk 1]
```diff
@@ -56,13 +56,22 @@ public static void SetProperties(in ParameterView parameters, object target)
...
                     throw null; // Unreachable
                 }
+                else if (parameter.Cascading && writer.AcceptsDirectParameters && writer.AcceptsCascadingParameters)
+                {
+                    // It's possible that the writer accepts both cascading and direct parameters. In that case,
+                    // we want to prefer the direct parameter, if it exists.
+                    if (parameters.HasDirectParameter(parameterName))
+                    {
+                        continue;
+                    }
```
Comment (javiercn) [inline src/Components/Components/src/Reflection/ComponentProperties.cs:73]: This is way more general behavior than what I expected.

In my view, we should just see where we are throwing the exception and special case it for supply from query parameters. We are doing this for back compat, we are not trying to create a new language/idiom.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Reflection/ComponentProperties.cs:73]: I agree. If we are able to limit this to just backcompat, I think we'll end up in a better place where we don't have the nonobviousness of needing priority rules to pick between cascading and direct parameters. I could be missing something, but perhaps the only change we need is:

 * When a direct parameter arrives, whether or not it matches a `[Parameter]` property, we continue to check if there's also `[SomeCascadingParameter]` on the target property. If there is:
   * **New behavior:** If it's `[SupplyParameterFromQuery]` and there is also `[Parameter]` on that property, we allow it and prefer the direct value for back-compat
   * Otherwise we throw like we did before

That might be the only case we have to deal with. It would mean that:

  * `[Parameter] [SupplyParameterFromQuery]` would accept both direct and cascaded values, preferring direct
  * `[Parameter] [SomeOtherCascadedParameter]` would never be useful, because it would throw if a direct parameter was received
  * `[AnyCascadedParameter]` on its own, including `[SupplyParameterFromQuery]`, could only receive cascaded values for the same reason (if a direct value was received at runtime, it would throw)

Does that sound right?

Comment (MackinnonBuck) [reply src/Components/Components/src/Reflection/ComponentProperties.cs]: That analysis seems right to me. My initial reasoning for not limiting the fix to just `[SupplyParameterFromQuery]` was that it felt weird to have something so special-cased in the core parameter setting logic. But I do acknowledge that it's a safer to not introduce fundamental new behavior in that area.

> When a direct parameter arrives and matches a `[Parameter]` property, we continue to check if there's also `[SomeCascadingParameter]` on the target property. If there is...

Yep, this logic seems right to me and is equivalent to what I've implemented (AFAICT), minus the part about checking the existence of `[SupplyParameterFromQuery]` specifically. In my commit addressing this feedback, the core parameter setting code (`ComponentProperites.SetProperties()`) is still attribute-agnostic, but I made a one-line change to `WritersForType` so that properties can only receive direct parameters if they don't have a `CascadingParameterAttribute`, unless that attribute is a `SupplyParameterFromQueryAttribute`.

**Review by javiercn — APPROVED** [review]
