### PR TITLE
Better exception for Generic methods on Hub

### LINKED ISSUE #6949: Generic Methods on SignalR Hubs Cause Poorly Worded Exceptions
### Describe the bug

When a SignalR hub contains generic public method members it will fail on SignalR registration. This itself is alright but the resulting exception is nonsense. It does not indicate the actual problem which leads to a goose chase for some people I'd imagine.

### To Reproduce

Register a SignalR hub with a generic public method.

### Expected behavior

A better exception message thrown when generic public methods are attempted to be registered by SignalR

### Additional context

Information I found related to this issue when searching: https://github.com/giraffe-fsharp/Giraffe/issues/295

I originally posted my findings in that issue. Definitely seems to be related to public generic method members.

Workarounds include making generic methods non-public.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/AspNetCore/issues/6949

### CODE REVIEW

File: src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs [hunk 1]
```diff
@@ -1327,6 +1327,19 @@ public async Task CannotCallDisposeMethodOnHub()
...
+        [Fact]
+        public void CannotHaveGenericMethodOnHub()
+        {
+            using (StartVerifiableLog())
+            {
+                var serviceProvider = HubConnectionHandlerTestUtils.CreateServiceProvider(null, LoggerFactory);
+
+                var exception = Assert.Throws<NotSupportedException>(() => serviceProvider.GetService<HubConnectionHandler<GenericMethodHub>>());
+
+                Assert.Equal("Method 'GenericMethod' is a generic method which is not supported on a Hub.", exception.Message);
```
Comment (halter73) [inline src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs]: How does this exception reported in a normal app? An error log?

Comment (BrennanConroy) [reply src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs]:
```
Application startup exception: System.NotSupportedException: Method 'M' is a generic method which is not supported on a Hub.
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods() in C:\GitHub\aspnetcore\src\SignalR\server\Core\src\Internal\DefaultHubDispatcher.cs:line 555
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, Boolean enableDetailedErrors, ILogger`1 logger) in C:\GitHub\aspnetcore\src\SignalR\server\Core\src\Internal\DefaultHubDispatcher.cs:line 37
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1..ctor(HubLifetimeManager`1 lifetimeManager, IHubProtocolResolver protocolResolver, IOptions`1 globalHubOptions, IOptions`1 hubOptions, ILoggerFactory loggerFactory, IUserIdProvider userIdProvider, IServiceScopeFactory serviceScopeFactory) in C:\GitHub\aspnetcore\src\SignalR\server\Core\src\HubConnectionHandler.cs:line 74
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   etc...
```

Comment (halter73) [reply src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs]: This won't break hubs with private or internal generic methods, right? Even if that's the case, technically this is a breaking change since it's possible that there are public generic Hub methods that were only called indirectly. Still think it's a worthwhile change. Not sure whether it warrants a breaking change announcement.

**Review by halter73 — APPROVED** [review]

File: src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs (hunk 1 above)
Comment (halter73) [reply src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs]: Nvm. I just looked at the issue again, and saw it was crashing at startup even previously. Carry on 😄
