### PR TITLE
Fix for issue #54500: Middleware keyed dependency injection

### LINKED ISSUE #54500: Keyed services fail to dependency inject into middleware
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It does not seem possible to get keyed services injected into middleware classes . Neither using constructor or Invoke/InvokeAsync argument injection. Attempting to do so results in a startup or invoke time exception respectively.

### Expected Behavior

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#service-lifetimes documents constructor as well as InvokeAsync using DI as well as constructor injection using keyed services for classes in DI.

As such the expectation is for DI on middleware to also work with keyed services.

### Steps To Reproduce

Execute the following code using `dotnet run`
```cs

class Program
{
    static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        builder.Services.AddKeyedSingleton<SomeClass>("test");
        builder.Services.AddSingleton<ObjectUsingKeyedSomeClass>();

        var app = builder.Build();
        app.UseMiddleware<MiddlewareUsingKeyedSomeClassConstructor>(); // Throws on startup
        app.UseMiddleware<MiddlewareUsingKeyedSomeClassInvoke>(); // Throws on invoke
        app.MapGet("/", ([FromKeyedServices("test")] SomeClass foo) => Results.Ok()); // Works
        app.MapGet("/2", (ObjectUsingKeyedSomeClass foo) => Results.Ok()); // Works
        app.Run();
    }
}

public class SomeClass { }
public class MiddlewareUsingKeyedSomeClassConstructor(RequestDelegate next, [FromKeyedServices("test")] SomeClass someClass)
{
    public async Task InvokeAsync(HttpContext context)
    {
        await next(context);
    }
}

public class MiddlewareUsingKeyedSomeClassInvoke(RequestDelegate next)
{
    public async Task InvokeAsync(HttpContext context, [FromKeyedServices("test")] SomeClass someClass)
    {
        await next(context);
    }
}

class ObjectUsingKeyedSomeClass([FromKeyedServices("test")] SomeClass someClass) {}
```

### Exceptions (if any)

`app.UseMiddleware<MiddlewareUsingKeyedSomeClassConstructor>(); // Throws on startup`
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: Unable to resolve service for type 'SomeClass' while attempting to activate 'MiddlewareUsingKeyedSomeClassConstructor'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

`app.UseMiddleware<MiddlewareUsingKeyedSomeClassInvoke>(); // Throws on invoke`
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Unable to resolve service for type 'SomeClass' while attempting to Invoke middleware 'MiddlewareUsingKeyedSomeClassInvoke'.
         at lambda_method1(Closure, Object, HttpContext, IServiceProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.200

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NicoBrabers**
# Middleware keyed dependency injection (fix for issue #54500)

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Added Microsoft.Extensions.DependencyInjection to Microsoft.AspNetCore.Http.Abstractions and utilized the ActivatorUtilities it provides to obtain a middleware instance. Also changed the ReflectionMiddlewareBinder to be able to handle keyed injection.

Fixes #54500

### CODE REVIEW

**Comment by NicoBrabers** [comment]
> @NicoBrabers please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree company="Progresity"

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 1]
```diff
@@ -215,13 +216,55 @@ public RequestDelegate CreateMiddleware(RequestDelegate next)
...
+            foreach (var attribute in parameterInfo.GetCustomAttributes(true))
+            {
+                if (attribute is FromKeyedServicesAttribute keyed)
+                {
+                    key = keyed.Key;
+                    return true;
+                }
+            }
+        }
+        key = null;
```
Comment (gfoidl) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:245]: Nit: insert blank line
```suggestion
        }
        
        key = null;
```

File: src/Http/Http.Abstractions/test/UsePathBaseExtensionsTests.cs [hunk 2]
```diff
@@ -238,6 +237,27 @@ private static HttpContext CreateRequest(string pathBase, string requestPath)
...
+            if (serviceType == typeof(IServiceProvider))
+            {
+                return this;
+            }
+
+            if (_services.TryGetValue(serviceType, out var value))
+            {
+                return value;
+            }
+            return null;
```
Comment (gfoidl) [inline src/Http/Http.Abstractions/test/UsePathBaseExtensionsTests.cs:260]:
```suggestion
            }
            
            return null;
```

**Review by gfoidl — COMMENTED** [review]
Two small nits.

File: src/Http/Http.Abstractions/test/UsePathBaseExtensionsTests.cs (hunk 2 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/test/UsePathBaseExtensionsTests.cs:260]: Actually, I'm pretty happy with the nit! I kept the DummyServiceProvider the same as in the UseMiddlewareTests class for consistency purposes, but disliked the format. Would you like me to make the same edit in the UseMiddlewareTests class?

**Comment by amcasey** [comment]
FYI @benjaminpetit @captainsafia

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 3]
```diff
@@ -215,13 +216,58 @@ public RequestDelegate CreateMiddleware(RequestDelegate next)
             methodArguments[0] = context;
             for (var i = 1; i < parameters.Length; i++)
             {
-                methodArguments[i] = GetService(serviceProvider, parameters[i].ParameterType, methodInfo.DeclaringType!);
+                var parameter = parameters[i];
+
+                var hasServiceKey = TryGetServiceKey(parameter, out object? key);
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:221]: This is going to happen on every single request, probably worth moving outside of the factory method since the data is the same for every single call.

Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: Hi Brennan, 

Thanks for your valuable feedback.

I've made some changes to reflect the feedback. I now precompute and cache the results for each parameter.

Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @BrennanConroy, I could eliminate the condition check (hasServiceKey ? GetKeyedService(...) : GetService(...)) as wel by compiling the method calls into delegates, and calling to the delegate directly within the factory. We'd probably be talking about microseconds though. The code might become slightly less readable though.

What's your opinion on the matter?

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 4]
```diff
@@ -209,19 +210,69 @@ public RequestDelegate CreateMiddleware(RequestDelegate next)
             }
         }
 
+        // Performance optimization: Precompute and cache the results for each parameter
+        var parameterData = new (bool hasServiceKey, object? key, Type parameterType, Type declaringType)[parameters.Length];
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:214]: You only really need to store an array of `object? key`. The other properties are already being captured by the closure and the check for whether to get a keyed service is `key == null ? GetService : GetKeyedService`.
https://github.com/dotnet/runtime/blob/26bcc1d12f895d654e24f7cbcfed466b6a34e65f/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L381

@benjaminpetit should we be throwing if `null` is passed in for key in `FromKeyedServices`?

Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:214]: @BrennanConroy, I'll change the logic according to your advice.

The reason as to why I've precomputed and cached the parameter- and declaringType is due to the fact that these are actually method calls to get the property value – twice since we'd be retrieving two values. As well as obtain the parameter from the parameters array. Since with the tuple we'd have direct memory access, I figured it would be performing better during high throughput applications.

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 5]
```diff
@@ -209,19 +210,70 @@ public RequestDelegate CreateMiddleware(RequestDelegate next)
...
 
             return (Task)methodInfo.Invoke(middleware, BindingFlags.DoNotWrapExceptions, binder: null, methodArguments, culture: null)!;
         };
     }
 
+    private static bool TryGetServiceKey(ParameterInfo parameterInfo, out object? key)
+    {
+        if (parameterInfo.CustomAttributes != null)
+        {
+            foreach (var attribute in parameterInfo.GetCustomAttributes(true))
```
Comment (captainsafia) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:242]: `parameterInfo.OfType<FromKeyedServicesAttribute>().FirstOrDefault()` might be more straightforward here.

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 6]
```diff
@@ -209,19 +210,70 @@ public RequestDelegate CreateMiddleware(RequestDelegate next)
...
+                var declaringType = methodInfo.DeclaringType!;
+
+                methodArguments[i] = key == null ? GetService(serviceProvider, parameterType, declaringType) : GetKeyedService(serviceProvider, key, parameterType, declaringType);
             }
 
             return (Task)methodInfo.Invoke(middleware, BindingFlags.DoNotWrapExceptions, binder: null, methodArguments, culture: null)!;
         };
     }
 
+    private static bool TryGetServiceKey(ParameterInfo parameterInfo, out object? key)
```
Comment (captainsafia) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:238]:
```suggestion
    private static bool TryGetServiceKey(ParameterInfo parameterInfo, [MemberNotNullWhen(true)] out object? key)
```

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs [hunk 7]
```diff
@@ -8,7 +8,7 @@
 using System.Runtime.CompilerServices;
 using Microsoft.AspNetCore.Http;
 using Microsoft.AspNetCore.Http.Abstractions;
-using Microsoft.Extensions.Internal;
+using Microsoft.Extensions.DependencyInjection;
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:11]: Is this so we use the DI version of ActivatorUtilities? Can we remove https://github.com/dotnet/aspnetcore/blob/dad78b3671b250c671e8711e49f53b6ddf21d5e0/src/Http/Http.Abstractions/src/Microsoft.AspNetCore.Http.Abstractions.csproj#L24 then?

File: src/Http/Http.Abstractions/test/UseMiddlewareTest.cs [hunk 8]
```diff
@@ -293,13 +379,27 @@ private class MiddlewareInjectInvokeNoService
         public Task Invoke(HttpContext context, object value) => Task.CompletedTask;
     }
 
+    private class MiddlewareKeyedInjectInvokeNoService
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/test/UseMiddlewareTest.cs:382]: Doesn't seem like this class is needed? Just use the other class and don't add services to DI?

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 4 above)
Comment (BrennanConroy) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: I love improving perf, so appreciate you thinking about that 😃 
But we probably shouldn't prematurely optimize without measuring. You can try it out in https://github.com/dotnet/aspnetcore/tree/main/src/Http/Http.Abstractions/perf/Microbenchmarks if you're up for it.

**Review by BrennanConroy — COMMENTED** [review]
The issue mentions adding support for constructor injection as well. Could you add a test for that?

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 7 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:11]: @BrennanConroy, yes indeed.

Already removed ActivatorUtilities from the project
image

Comment (BrennanConroy) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:11]: 😆 whoops, just looked at the repo instead of the PR when searching for that reference

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 4 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @BrennanConroy, totally up for it! Tomorrow though, I need some sleep first 🥱

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 7 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs:11]: Oops, o well, at least we're sure that it's been cleaned up!

File: src/Http/Http.Abstractions/test/UseMiddlewareTest.cs (hunk 8 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/test/UseMiddlewareTest.cs:382]: @BrennanConroy, hmm, appears to be the case. I'll double check it in the morning and adjust it accordingly.

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 5 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @captainsafia, I've taken your feedback into account and changed the method to be more straightforward. Also changed the Inherit parameter from true to false, to meet the ActivatorUtilities from the Microsoft.Extensions.DependencyInjections.Abstractions package.

https://github.com/dotnet/runtime/blob/0540ea54f3ab96ed02e22e242fe9064cbda2a63c/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L416

https://github.com/dotnet/runtime/blob/0540ea54f3ab96ed02e22e242fe9064cbda2a63c/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L749

https://github.com/dotnet/runtime/blob/0540ea54f3ab96ed02e22e242fe9064cbda2a63c/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ActivatorUtilities.cs#L532C3-L532C41

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 6 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @captainsafia, thanks for the feedback. I've implemented it together with some other changes. Would've used the "Commit suggestion" otherwise.

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 4 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @BrennanConroy, I've added some benchmarks, as well as the possible optimizations. It seems that precomputing and caching all the parameters is the most optimized option. 
[benchmarks.txt](https://github.com/dotnet/aspnetcore/files/15395939/benchmarks.txt)

I've also introduced a new optimization which would cache a delegate based on the GetService or GetKeyedService method call, however, calling to the cached delegate itself seems to have more overhead than the key check and direct access to the method.

Based on these benchmarks, should we go with the optimization to cache all the parameters rather than just the key? What's your opinion on the matter?

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 5 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @captainsafia, @BrennanConroy, the changes within this pull-request target main, and thus the .NET 9.0 version. If I'd want the changes to be available in the latest .NET 8.x.x version as well, what would the appropriate steps for me to take?

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 4 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @BrennanConroy I'm wondering about your follow up on the above.

File: src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs (hunk 5 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: @captainsafia, @BrennanConroy, any follow-up on my question above?

Comment (BrennanConroy) [reply src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs]: I don't think this is a backport candidate. This change is a feature, not fixing a major bug/regression introduced in 8.0.

**Comment by BrennanConroy** [comment]
The microbenchmark essentially duplicates the code in UseMiddleware. While that's fine for a one-off run, it's not great from a maintainability standpoint as we'd need to modify both the microbenchmark and the UseMiddleware code any time we make a change. I'm wondering if we can find a way to toggle whether we use reflection or not so that the microbenchmark just calls the UseMiddleware code directly.

**Comment by BrennanConroy** [comment]
Hey @NicoBrabers we're starting to wrap up 9.0, would love for this change to make it but not a fan of merging the microbenchmark code as-is (see https://github.com/dotnet/aspnetcore/pull/55722#issuecomment-2148030442). Could we remove it and leave everything else? At a minimum we have this PR history to show the microbenchmarking 😃

**Comment by NicoBrabers** [comment]
Hi @BrennanConroy, I've bought a new house, and I've just been away on a holiday, hence I haven't been able to further improve on the microbenchmarks. Would love to continue that in the future. 

I agree that for now it's best to remove the benchmarks and wrap it all up! Will do so tomorrow 👍🏼. I'll make sure to tag you after the changes have been made and pushed 👍🏼

**Comment by BrennanConroy** [comment]
Awesome thanks!

> I've bought a new house

And congrats 😃

**Comment by NicoBrabers** [comment]
> Awesome thanks!
> 
> > I've bought a new house
> 
> And congrats 😃

Thank you @BrennanConroy!

I've removed the microbenchmark code for now, the changes have been pushed.

**Comment by BrennanConroy** [comment]
> The issue mentions adding support for constructor injection as well. Could you add a test for that?

Looks like you didn't get around to this? Unless I just missed it 😆

**Comment by NicoBrabers** [comment]
> > The issue mentions adding support for constructor injection as well. Could you add a test for that?
> 
> Looks like you didn't get around to this? Unless I just missed it 😆

Hi @BrennanConroy, might have missed that comment, or forget about it later on. Will check it a.s.a.p.

**Comment by NicoBrabers** [comment]
> > The issue mentions adding support for constructor injection as well. Could you add a test for that?
> 
> Looks like you didn't get around to this? Unless I just missed it 😆

Hi @BrennanConroy, I've added additional unit-tests to test the constructor injection support.

File: src/Http/Http.Abstractions/src/Resources.resx [hunk 9]
```diff
@@ -162,4 +162,13 @@
   <data name="RouteValueDictionary_DuplicatePropertyName" xml:space="preserve">
     <value>The type '{0}' defines properties '{1}' and '{2}' which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons.</value>
   </data>
+  <data name="Exception_KeyedServicesNotSupported" xml:space="preserve">
+    <value>This service provider doesn't support keyed services.</value>
+  </data>
+  <data name="Exception_NoServiceRegistered" xml:space="preserve">
+    <value>No service for type '{0}' has been registered.</value>
+  </data>
+  <data name="Exception_ActivateMiddlewareNoService" xml:space="preserve">
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Resources.resx:171]: We shouldn't add resource strings that are only used by tests.

File: src/Http/Http.Abstractions/test/UseMiddlewareTest.cs [hunk 10]
```diff
@@ -130,6 +131,45 @@ public async Task UseMiddleware_ThrowsIfArgCantBeResolvedFromContainer()
...
+        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => app(new DefaultHttpContext()));
+        Assert.Equal(
+            Resources.FormatException_InvokeMiddlewareNoService(
+                typeof(IKeyedServiceProvider),
+                typeof(MiddlewareKeyedInjectInvoke)),
+            exception.Message);
+    }
+
+    [Fact]
+    public async Task UseMiddleware_ThrowsIfKeyedConstructorArgCantBeResolvedFromContainer()
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/test/UseMiddlewareTest.cs:149]:
```suggestion
    public void UseMiddleware_ThrowsIfKeyedConstructorArgCantBeResolvedFromContainer()
```

**Review by BrennanConroy — APPROVED** [review]

File: src/Http/Http.Abstractions/src/Resources.resx (hunk 9 above)
Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Resources.resx:171]: Ah, agreed, I'll remove it from the resource. Shall I add it as a constant to the testmethod?

Comment (BrennanConroy) [reply src/Http/Http.Abstractions/src/Resources.resx:171]: Inline is fine

Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Resources.resx]: I've pushed the changes 👍

File: src/Http/Http.Abstractions/src/Resources.resx [hunk 11]
```diff
@@ -162,4 +162,10 @@
   <data name="RouteValueDictionary_DuplicatePropertyName" xml:space="preserve">
     <value>The type '{0}' defines properties '{1}' and '{2}' which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons.</value>
   </data>
+  <data name="Exception_KeyedServicesNotSupported" xml:space="preserve">
+    <value>This service provider doesn't support keyed services.</value>
+  </data>
+  <data name="Exception_NoServiceRegistered" xml:space="preserve">
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Resources.resx:168]: Sorry, there is this one too 😢

Comment (NicoBrabers) [reply src/Http/Http.Abstractions/src/Resources.resx:168]: Hehe, don't sweat it, should've checked it. Will run by all resources 👍

**Comment by BrennanConroy** [comment]
Thanks @NicoBrabers !

**Comment by NicoBrabers** [comment]
> Thanks @NicoBrabers !

It's been a pleasure @BrennanConroy!
