### PR TITLE
Fixed the window update hangs

### LINKED ISSUE #41248: Quarantine InteropTests.InteropTests.ClientCompressedUnary
## Failing Test(s)

- InteropTests.InteropTests.ClientCompressedUnary

## Error Message

```text
System.InvalidOperationException : Error while running client process.
```

## Stacktrace

<details>

```text

```
</details>

## Logs

<details>

[console.7d6b1551.txt](https://github.com/dotnet/aspnetcore/files/8508274/console.7d6b1551.txt)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1723679&view=ms.vss-test-web.build-test-results-tab&runId=46765000&resultId=120261&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1723144&view=ms.vss-test-web.build-test-results-tab&runId=46752406&paneView=debug&resultId=120019

### PR DESCRIPTION
**Pull request by davidfowl**
- While computing how many bytes we needed to write, we were returning the remaining number of window bytes (for both the connection and stream windows). Since window updates happen concurrently with the write loop, it was possible to miss and not observe the window update depending on when the update happened in relation to the loop observing this state. We now look at the current state of the connection window and stream window before we decide to queue or wait for a window update under the appropriate locks.

Fixes #41248

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 1]
```diff
@@ -292,6 +260,37 @@ static bool HasStateFlag(Http2OutputProducer.State state, Http2OutputProducer.St
...
 
+    private bool TryQueueProducerForConnectionWindowUpdate(long actual, Http2OutputProducer producer)
+    {
+        lock (_windowUpdateLock)
+        {
+            // Check the connection window under a lock so that we don't miss window updates
+            if (_connectionWindow == 0)
+            {
+                // We have no more connection window, put this producer in a queue waiting for it to
+                // a window update to resume the connection.
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:271]:
```suggestion
                // We have no more connection window, put this producer in a queue waiting for
                // a window update to resume the connection.
```

File: src/Grpc/Interop/test/InteropTests/InteropTests.cs [hunk 2]
```diff
@@ -64,7 +64,6 @@ public InteropTests(ITestOutputHelper output)
     public Task UnimplementedMethod() => InteropTestCase("unimplemented_method");
 
     [Fact]
-    [QuarantinedTest("https://github.com/dotnet/aspnetcore/issues/41248")]
```
Comment (JamesNK) [inline src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: Policy is to leave it quarantined. Remove attribute after 30 days of passes

**Comment by JamesNK** [comment]
Is there anyway to unit test this? If it regresses we have some tests that become flaky, but it’s not an obvious break.

**Comment by davidfowl** [comment]
This is hard to unit test without adding lots of events that control exactly when things happen.

File: src/Grpc/Interop/test/InteropTests/InteropTests.cs (hunk 2 above)
Comment (davidfowl) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: Got it

File: src/Grpc/Interop/test/InteropTests/InteropTests.cs [hunk 3]
```diff
@@ -64,7 +64,6 @@ public InteropTests(ITestOutputHelper output)
     public Task UnimplementedMethod() => InteropTestCase("unimplemented_method");
 
     [Fact]
```
Comment (davidfowl) [inline src/Grpc/Interop/test/InteropTests/InteropTests.cs:66]:
```suggestion
    [Fact]
    [QuarantinedTest("https://github.com/dotnet/aspnetcore/issues/41248")]
```

File: src/Grpc/Interop/test/InteropTests/InteropTests.cs (hunk 2 above)
Comment (davidfowl) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: BUT this feels like one that we should un-quarantine since its my change that made it flaky.

Comment (Tratcher) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: Maybe if it were 100% repro before, and had a targeted test to say it was 100% fixed now. Right now we only *think* it's fixed 😁, hence staying quarantined.

Comment (davidfowl) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: It reprod 100% before on my machine.

Comment (BrennanConroy) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: It's just a general rule, but up to devs judgement if they strongly believe they know the cause and the fix.

Comment (davidfowl) [reply src/Grpc/Interop/test/InteropTests/InteropTests.cs:67]: Yea, I was able to repro locally 100%, debug and root cause the thing.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 4]
```diff
@@ -128,10 +128,10 @@ private async Task WriteToOutputPipe()
                     var buffer = readResult.Buffer;
 
                     // Check the stream window
-                    var (actual, remainingStream) = producer.ConsumeStreamWindow(buffer.Length);
+                    var actual = producer.ConsumeStreamWindow(buffer.Length);
 
                     // Now check the connection window
-                    (actual, var remainingConnection) = ConsumeConnectionWindow(actual);
+                    actual = ConsumeConnectionWindow(actual);
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:134]: Q: Are we leaking stream window bytes?
Setup: The stream has an available window of 50. The connection has an available window of 40. We try to write 50+ bytes. The steam window is consumed. The connection window is consumed, but then the buffer is sliced to 40 bytes. Are those 10 extra bytes credited back to the stream window for future writes?

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 5]
```diff
@@ -292,6 +260,37 @@ static bool HasStateFlag(Http2OutputProducer.State state, Http2OutputProducer.St
         _log.Http2ConnectionQueueProcessingCompleted(_connectionId);
     }
 
+    private bool TryQueueProducerForConnectionWindowUpdate(long actual, Http2OutputProducer producer)
+    {
+        lock (_windowUpdateLock)
+        {
+            // Check the connection window under a lock so that we don't miss window updates
+            if (_connectionWindow == 0)
```
[the remark this answers is not in the document]
Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:268]: I think only the stream window can go negative. That's because `SETTINGS_INITIAL_WINDOW_SIZE` can be decreased after the connection starts, but that only affects stream-level flow control. The connection window can only be updated with WINDOW_UPDATES which cannot be negative.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 4 above)
Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:134]: Good catch!

Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs]: Fixed. Please review.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:272]: Right!

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs [hunk 6]
```diff
@@ -1936,6 +1936,58 @@ public async Task DATA_Sent_DespiteStreamOutputFlowControl_IfEmptyAndEndsStream(
...
+    [Fact]
+    public async Task StreamWindow_BiggerThan_ConnectionWindow()
+    {
+        // This only affects the stream windows. The connection-level window is always initialized at 64KiB.
+        _clientSettings.InitialWindowSize = 16384 * 5;
+
+        await InitializeConnectionAsync(async context =>
+        {
+            var data = new byte[16384 * 4];
+            data.AsSpan().Fill(1);
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:1948]: Why are we filling the array with 1s? Doesn't `new byte[16384 * 4]` fit just inside the 64KiB connection window? Apparently it's one byte too large given the test, but I'm trying to understand why.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs [hunk 7]
```diff
@@ -1936,6 +1936,58 @@ public async Task DATA_Sent_DespiteStreamOutputFlowControl_IfEmptyAndEndsStream(
...
+        }
+
+        // Now we've consumed the entire connection window, and there's one more frame to write
+        await ExpectAsync(Http2FrameType.DATA,
+            withLength: 16383,
+            withFlags: (byte)(Http2DataFrameFlags.NONE),
+            withStreamId: 1).DefaultTimeout();
+
+        // Send more than enough bytes for the window update
+        await SendWindowUpdateAsync(0, (int)Http2PeerSettings.DefaultInitialWindowSize);
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:1974]: This works, right?

```suggestion
        await SendWindowUpdateAsync(0, 1);
```

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 8]
```diff
@@ -855,13 +858,19 @@ private ValueTask<FlushResult> TimeFlushUnsynchronizedAsync()
         return _flusher.FlushAsync(_minResponseDataRate, bytesWritten);
     }
 
-    private (long, long) ConsumeConnectionWindow(long bytes)
+    private long CheckConnectionWindow(long bytes)
+    {
+        lock (_windowUpdateLock)
+        {
+            return Math.Min(bytes, _connectionWindow);
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:865]: You could still consume the connection window here and avoid retaking the lock, right?

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs (hunk 6 above)
Comment (davidfowl) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:1948]: https://github.com/dotnet/aspnetcore/blob/46554c9183e7ebdda173edd03038f19ea7ac75d3/src/Shared/ServerInfrastructure/Http2/Http2PeerSettings.cs#L14

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 8 above)
Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:865]: I rather not update this state outside of the lock ever 😄. Maybe in preview5.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 9]
```diff
@@ -233,42 +237,10 @@ static bool HasStateFlag(Http2OutputProducer.State state, Http2OutputProducer.St
                     // When the window update is sent, the producer will be re-queued if needed.
                     else if (hasMoreData && !aborted && !waitingForWindowUpdates)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:238]: Can we simplify this by removing `waitingForWindowUpdates` since `TryScheduleNextWrite` will check this independently anyway? `waitingForWindowUpdates` only applies to stream window updates, right?

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs (hunk 6 above)
Comment (halter73) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:1948]: Right, it's *almost* 64KiB.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 8 above)
Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:865]: I'm suggesting just going back to the old version of ConsumeConnectionWindow more or less since you always consume what's returned from here (since you've already checked the stream window).

```
private long ConsumeConnectionWindow(long bytes)
{
    lock (_windowUpdateLock)
    {
        var actual = Math.Min(bytes, _connectionWindow);
        _connectionWindow -= actual;
        return actual;
    }
}

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 9 above)
Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:238]: waitingForWindowUpdates applies to both connection and stream window currently.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 8 above)
Comment (davidfowl) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:866]: I see, initially I had this but I decided to keep both consistent.
