### PR TITLE
Remove stack overflow in EndpointFilterInvocationContexts

### LINKED ISSUE #49284: Stack Overflow when using some EndpointFilterInvocationContext properties
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For the generated `EndpointFilterInvocationContext` types, for example `EndpointFilterInvocationContext<T0>`, some properties are implemented as if the `Arguments` property was a concrete `List<object>`, however it refers to itself.

These properties are:
* `IndexOf` - [here](https://github.com/dotnet/aspnetcore/blob/be566b1f4ed1ab24765a3a4a2d1751dc73e7fcfc/src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.cs#L92)
* `Contains` - [here](https://github.com/dotnet/aspnetcore/blob/be566b1f4ed1ab24765a3a4a2d1751dc73e7fcfc/src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.cs#L62)

Calling either of these two properties results in a stack overflow.

### Expected Behavior

The `Contains` and `IndexOf` methods should return accordingly.

### Steps To Reproduce

This can be reproduced with:
```csharp
var invocationContext = EndpointFilterInvocationContext.Create(null!, 1, 2, 3);
var index = invocationContext.Arguments.IndexOf(3); // 💥
```

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by slang25**
# Remove potential stack overflow in EndpointFilterInvocationContexts

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

This change replaces the infinite recursive behaviour of the properties on the `EndpointFilterInvocationContext` types, and implement the `Contains` and `IndexOf` method explicitly instead.

Fixes #49284

### CODE REVIEW

File: src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.cs
Comment (captainsafia) [inline src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.cs:1]: Can we add a test for this behavior?

Comment (slang25) [reply src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.cs:1]: Good call, done ✅

**Comment by davidfowl** [comment]
Why not implement these instead?

File: src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt [hunk 1]
```diff
@@ -73,7 +73,13 @@ internal sealed class EndpointFilterInvocationContext<<# foreach (var argumentCo
 
     public bool Contains(object? item)
     {
-        throw new NotSupportedException();
+        for (int i = 0; i < Arguments.Count; i++)
+        {
+            if (Arguments[i].Equals(item))
```
Comment (martincostello) [inline src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt:78]: Do you need to check that `Arguments[i]` isn't null here and below?

**Comment by slang25** [comment]
> Why not implement these instead?

Good point, I've just pushed an implementation 👍

File: src/Http/Http.Abstractions/test/EndpointFilterInvocationContextOfTTests.cs [hunk 2]
```diff
@@ -64,6 +56,16 @@ public void AllowsEnumerationOfParameters()
         Assert.Equal(4, enumeratedCount);
     }
 
+    [Fact]
+    public void HandlesIListReadOperations()
+    {
+        var context = new EndpointFilterInvocationContext<string, int, bool>(new DefaultHttpContext(), "This is a test", 42, false);
```
Comment (martincostello) [inline src/Http/Http.Abstractions/test/EndpointFilterInvocationContextOfTTests.cs:62]: I guess adding a nullable type with a value to the constructor here would validate my comment.

**Comment by adityamandaleeka** [comment]
@slang25 There's a whitespace mismatch that's causing a test to fail. Looks like you cleaned up some stray spaces on an empty line which it's not happy about 😆.

```
 Microsoft.AspNetCore.Http.Abstractions.Tests.EndpointFilterInvocationContextOfTTests.GeneratedCodeIsUpToDate [FAIL]
2023-07-10T10:14:57.7566156Z [xUnit.net 00:00:05.90]       Assert.Equal() Failure
2023-07-10T10:14:57.7592174Z [xUnit.net 00:00:05.90]                                          ↓ (pos 1189)
2023-07-10T10:14:57.7618665Z [xUnit.net 00:00:05.91]       Expected: ···Arg0 { get; set; }\r\n\r\n    public int Count => 1;\r\n\r\n    publi···
2023-07-10T10:14:57.7645943Z [xUnit.net 00:00:05.91]       Actual:   ···Arg0 { get; set; }\r\n    \r\n    public int Count => 1;\r\n\r\n    p···
2023-07-10T10:14:57.7673019Z [xUnit.net 00:00:05.91]                                          ↑ (pos 1189)
2023-07-10T10:14:57.7704214Z [xUnit.net 00:00:05.92]       Stack Trace:
2023-07-10T10:14:57.7735788Z [xUnit.net 00:00:05.92]         /_/src/Http/Http.Abstractions/test/EndpointFilterInvocationContextOfTTests.cs(96,0): at Microsoft.AspNetCore.Http.Abstractions.Tests.EndpointFilterInvocationContextOfTTests.GeneratedCodeIsUpToDate()
```

File: src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt [hunk 3]
```diff
@@ -52,8 +52,8 @@ internal sealed class EndpointFilterInvocationContext<<# foreach (var argumentCo
 
     public override IList<object?> Arguments => this;
 
-    <# foreach (var argumentCount in Enumerable.Range(0, arity)) { #>public T<#=argumentCount#> Arg<#=argumentCount#> { get; set; }
-    <# } #>
+<# foreach (var argumentCount in Enumerable.Range(0, arity)) { #>    public T<#=argumentCount#> Arg<#=argumentCount#> { get; set; }
+<# } #>
```
Comment (slang25) [inline src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt:56]: Just to explain this change, I'm on macOS and using either Rider or VSCode the editors immediately delete the whitespace from the generated files the moment I touch them, so this change makes editing them by hand less volatile.

Why am I editing the generated code by hand? Because when I try to use the tt generator it completely re-writes the file in a way that creates a massive diff (the header text is different for example).

Comment (martincostello) [reply src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt:56]: Might be worth at some point having the repo updated to use the [.NET 6 version](https://devblogs.microsoft.com/dotnet/t4-command-line-tool-for-dotnet/) of the tt generator - maybe that'll remove some of the xplat wonk (after an initial normalisation).

**Comment by slang25** [comment]
Thanks for your help @adityamandaleeka, I totally missed that.

File: src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt (hunk 3 above)
Comment (martincostello) [reply src/Http/Http.Abstractions/src/EndpointFilterInvocationContextOfT.Generated.tt:56]: #49382

**Comment by slang25** [comment]
close & open to trigger to re-run validation

**Review by captainsafia — APPROVED** [review]
