### PR TITLE
Minimal APIs - return string aren't setting content type header #33860

### LINKED ISSUE #33860: Minimal APIs - return string isn't setting content type header
### To Reproduce

- Create a new empty web application 
-  Add swagger UI 
- Run the application  go to  `https://localhost:5001/swagger/index.html`

image

### PR DESCRIPTION
**Pull request by rafikiassumani-msft**
**Set Content Type to Plain Text if ContextType Response header is not set**

This change will set the contextType response header to "text/plain; charset=utf-8" when the content-type response header is null or was not set. 

Addresses #33860

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=34285) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=34285) before we can accept your contribution.<br/><br/>:x: rafikiassumaniMSFT [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=34285)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=34285) it.</sub>

File: src/Http/Http.Abstractions/src/Extensions/ContentTypeConstants.cs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+namespace Microsoft.AspNetCore.Http
+{
+    internal static class ContentTypeConstants
+    {
+        public const string PlainTextContentType = "text/plain";
```
Comment (Tratcher) [inline src/Http/Http.Abstractions/src/Extensions/ContentTypeConstants.cs:8]: Unused?

File: src/Http/Http.Abstractions/src/Extensions/HttpResponseWritingExtensions.cs [hunk 2]
```diff
@@ -66,6 +66,11 @@ public static Task WriteAsync(this HttpResponse response, string text, Encoding
                 throw new ArgumentNullException(nameof(encoding));
             }
 
+            if(response.ContentType == null)
```
Comment (Tratcher) [inline src/Http/Http.Abstractions/src/Extensions/HttpResponseWritingExtensions.cs:69]: WriteAsync can be called multiple times, so this would fail the second time. This should move to the caller of WriteAsync.

File: src/Http/Http.Abstractions/test/HttpResponseWritingExtensionsTests.cs [hunk 3]
```diff
@@ -31,6 +31,15 @@ public async Task WritingText_MultipleWrites()
             Assert.Equal(22, context.Response.Body.Length);
         }
 
+        [Fact]
+        public async Task WritingText_When_ContentType_IsNull_SetPlainText()
+        {
+            HttpContext context = CreateRequest();
+            await context.Response.WriteAsync("Hello World");
+
+            Assert.Equal(ContentTypeConstants.PlainTextContentTypeWithCharset, context.Response.ContentType);
```
Comment (halter73) [inline src/Http/Http.Abstractions/test/HttpResponseWritingExtensionsTests.cs:40]: I do like keeping this as a negative test case asserting that `context.Response.ContentType` is *not* set by `Response.WriteAsync(string)` once we move this logic out to RequestDelegateFactory.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 4]
```diff
@@ -431,6 +437,17 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
             }
         }
 
+        private static ConditionalExpression HandleNullContentType()
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:440]: Nit:

```suggestion
        private static ConditionalExpression MaybeSetPlaintextContentType()
```

File: src/Http/Http.Extensions/src/ContentTypeConstants.cs [hunk 5]
```diff
@@ -0,0 +1,10 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+namespace Microsoft.AspNetCore.Http
+{
+    internal static class ContentTypeConstants
+    {
+        public const string PlainTextContentTypeWithCharset = "text/plain; charset=utf-8";
```
Comment (halter73) [inline src/Http/Http.Extensions/src/ContentTypeConstants.cs:8]: You can just make this private and put it directly in RequestDelegateFactory. We should probably write the test with the string literal anyway, because if we change this string, it will be a behavioral change that should cause tests to fail imo.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 6]
```diff
@@ -365,10 +366,10 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
                     // ExecuteTask<T>(action(..), httpContext);
                     else if (typeArg == typeof(string))
                     {
-                        return Expression.Call(
-                            ExecuteTaskOfStringMethod,
-                            methodCall,
-                            HttpContextExpr);
+                        var conditionalContentTypeExpr = HandleNullContentType();
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:369]: Nit: I don't see the benefit of `conditionalContentTypeExpr` local var. I'd just call the method where it's used.

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 7]
```diff
@@ -960,6 +960,61 @@ void TestAction(HttpResponse httpResponse)
...
+
+            Assert.Equal(ContentTypeConstants.PlainTextContentTypeWithCharset, httpContext.Response.ContentType);
+        }
+
+        [Fact]
+        public async Task RequestDelegateSetContentTypeWhenNullAndReturnTypeIsGenericOfTypeTask()
+        {
+            async Task<string> Plaintext()
+            {
+                var sayHelloTask = Task.Run(() =>
```
Comment (halter73) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:981]: We should just update the existing `RequestDelegateWritesComplexReturnValueAsJsonResponseBody` (and rename it) test to verify the httpContext.Response.ContentType, but in the future it's a more efficient to use `Task.FromResult` than `Task.Run` when the result is already available. Also, you can just return the Task directly from a non-async method instead of doing a `return await`.

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 8]
```diff
@@ -960,6 +960,61 @@ void TestAction(HttpResponse httpResponse)
...
+                return await sayHelloTask;
+            }
+            var httpContext = new DefaultHttpContext();
+
+            var requestDelegate = RequestDelegateFactory.Create((Func<ValueTask<string>>)Plaintext, new EmptyServiceProvider());
+
+            await requestDelegate(httpContext);
+
+            Assert.Equal(ContentTypeConstants.PlainTextContentTypeWithCharset, httpContext.Response.ContentType);
+        }
```
Comment (halter73) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:1016]: We should add a test cases for callbacks that set `HttpContext.Response.ContentType` before returning a `string/Task<string>/ValueTask<string>` verifying it doesn't get overwritten.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 9]
```diff
@@ -873,5 +888,13 @@ private static IResult EnsureRequestResultNotNull(IResult? result)
 
             return result;
         }
+
+        private static void SetContentType(HttpContext httpContext)
+        {
+            if (httpContext.Response.ContentType == null)
+            {
+                httpContext.Response.ContentType = PlainTextContentTypeWithCharset;
+            }
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:897]: Nit:

```suggestion
            httpContext.Response.ContentType ??= "text/plain; charset=utf-8";
```

File: src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs [hunk 10]
```diff
@@ -1140,6 +1140,21 @@ public async Task RequestDelegateWritesStringReturnValueAsJsonResponseBody(Deleg
...
+        public async Task RequestDelegateWritesStringReturnDoNotChangeContentType(Delegate @delegate)
+        {
+            var httpContext = new DefaultHttpContext();
+            httpContext.Response.ContentType = "application/json; charset=utf-8";
+
+            var requestDelegate = RequestDelegateFactory.Create(@delegate, new EmptyServiceProvider());
+
+            await requestDelegate(httpContext);
+
+            Assert.NotEqual("text/plain; charset=utf-8", httpContext.Response.ContentType);
```
Comment (halter73) [inline src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs:1157]: Nit:

```suggestion
            Assert.Equal("application/json; charset=utf-8", httpContext.Response.ContentType);
```

**Review by halter73 — APPROVED** [review]

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 11]
```diff
@@ -737,6 +742,14 @@ static async Task ExecuteAwaited(Task<string> task, HttpContext httpContext)
             return ExecuteAwaited(task!, httpContext);
         }
 
+        private static Task ExecuteWriteStringResponseAsync(HttpContext httpContext, string text)
+        {
+
+             SetContentType(httpContext);
+             return httpContext.Response.WriteAsync(text);
+
```
Comment (pranavkm) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:750]:
```suggestion
```

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 12]
```diff
@@ -56,6 +56,8 @@ public static partial class RequestDelegateFactory
 
         private static readonly BinaryExpression TempSourceStringNotNullExpr = Expression.NotEqual(TempSourceStringExpr, Expression.Constant(null));
 
+        private const string PlainTextContentTypeWithCharset = "text/plain; charset=utf-8";
+
```
Comment (pranavkm) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:60]:
```suggestion
```

If you're picking @halter73's other suggestion, this can be removed.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 13]
```diff
@@ -737,6 +742,14 @@ static async Task ExecuteAwaited(Task<string> task, HttpContext httpContext)
             return ExecuteAwaited(task!, httpContext);
         }
 
+        private static Task ExecuteWriteStringResponseAsync(HttpContext httpContext, string text)
+        {
+
```
Comment (pranavkm) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:747]:
```suggestion
```

**Review by pranavkm — APPROVED** [review]
I applied some of the suggestions for you to try and get this in before we branch.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 14]
```diff
@@ -694,6 +694,7 @@ private static async Task ExecuteObjectReturn(object? obj, HttpContext httpConte
             }
             else if (obj is string stringValue)
             {
+                SetContentType(httpContext);
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:697]:
```suggestion
                SetPlaintextContentType(httpContext);
```

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 15]
```diff
@@ -722,8 +723,10 @@ static async Task ExecuteAwaited(Task<T> task, HttpContext httpContext)
 
         private static Task ExecuteTaskOfString(Task<string?> task, HttpContext httpContext)
         {
-            EnsureRequestTaskNotNull(task);
 
+            SetContentType(httpContext);
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:727]:
```suggestion
            SetPlaintextContentType(httpContext);
```

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 16]
```diff
@@ -737,6 +740,12 @@ static async Task ExecuteAwaited(Task<string> task, HttpContext httpContext)
             return ExecuteAwaited(task!, httpContext);
         }
 
+        private static Task ExecuteWriteStringResponseAsync(HttpContext httpContext, string text)
+        {
+             SetContentType(httpContext);
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:745]:
```suggestion
             SetPlaintextContentType(httpContext);
```

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 17]
```diff
@@ -769,6 +778,8 @@ static async Task ExecuteAwaited(ValueTask<T> task, HttpContext httpContext)
 
         private static Task ExecuteValueTaskOfString(ValueTask<string?> task, HttpContext httpContext)
         {
+            SetContentType(httpContext);
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:781]:
```suggestion
            SetPlaintextContentType(httpContext);
```

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 18]
```diff
@@ -873,5 +884,10 @@ private static IResult EnsureRequestResultNotNull(IResult? result)
 
             return result;
         }
+
+        private static void SetContentType(HttpContext httpContext)
```
Comment (halter73) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:888]:
```suggestion
        private static void SetPlaintextContentType(HttpContext httpContext)
```
