### PR TITLE
Skip TlsHandshakeRejectsTlsLessThan12 on linux 

### LINKED ISSUE #26154: TlsHandshakeRejectsTlsLessThan12
Fails consistently on Debian.9.Arm64.Open Ubuntu.1804
```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
-------- Interop+Crypto+OpenSslCryptographicException : error:141640B5:SSL routines:tls_construct_client_hello:no ciphers available
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.TlsHandshakeRejectsTlsLessThan12() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs:line 57
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.TlsHandshakeRejectsTlsLessThan12() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs:line 68
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
----- Inner Stack Trace -----
```

This test currently has the 3rd highest failure rate, please prioritize.

### PR DESCRIPTION
**Pull request by Tratcher**
Fixes #26154 The runtime disabled all TLS 1.1 ciphers by default on linux so that explains why the test was failing. Marking the test as not supported on Linux.
I un-quarantined it because the test has been passing on Windows.

### CODE REVIEW

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs [hunk 1]
```diff
@@ -16,21 +16,19 @@
 using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2;
 using Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport;
 using Microsoft.AspNetCore.Testing;
-using Microsoft.Extensions.Logging.Testing;
 using Xunit;
 
 namespace Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2
 {
     [OSSkipCondition(OperatingSystems.MacOSX, SkipReason = "Missing SslStream ALPN support: https://github.com/dotnet/runtime/issues/27727")]
+    [OSSkipCondition(OperatingSystems.Linux, SkipReason = "TLS 1.1 ciphers are now disabled by default: https://github.com/dotnet/docs/issues/20842")]
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs:24]: Can we move all the skip conditions to the single test in this class? This is a good reason to skip the TlsHandshakeRejectsTlsLessThan12 test, but maybe not other TlsTests. It doesn't matter now, but this might be easy to miss if someone adds more tests to this class.

**Review by halter73 — APPROVED** [review]
