### PR TITLE
[Blazor] do not enhance form  when method = "dialog" or target != "_self"

### LINKED ISSUE #52017: Uncaught error when submitting enhanced form with method="dialog"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When submitting an enhanced form with `method="dialog"` (or button `formmethod="dialog"`) there is an error in the console:

form-method-dialog

### Expected Behavior

The form should not be enhanced in these cases and the warning should appear in the console saying something like "Form cannot be enhanced when method='dialog'."

### Steps To Reproduce

1. Create new Blazor Web app.
2. Add this to Home.razor:
```html
<form data-enhance method="dialog">
    <input type="submit" />
</form>
```
or
```html
<form data-enhance>
    <input type="submit" formmethod="dialog" />
</form>
```

3. Click "Submit"

### Exceptions (if any)

_No response_

### .NET Version

8

### Anything else?

_No response_

### LINKED ISSUE #52020: Blazor form should not be enhanced when target attribute is different than the default
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor form should not be enhanced when `target` is different that the default value `_self` ( or form button `formtarget` is different)

### Expected Behavior

The form should not be enhanced in these cases and the warning should appear in the console saying something like "Form cannot be enhanced when target is different from the default value."

### Steps To Reproduce

1. Create new Blazor Web app.
2. Add this to Home.razor:
```html
<form data-enhance target="_blank">
    <input type="submit" />
</form>
```
or
```html
<form data-enhance>
    <input type="submit" formtarget="_blank" />
</form>
```

3. Click "Submit"

### Exceptions (if any)

_No response_

### .NET Version

8

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surayya-MS**
# [Blazor] do not enhance form  when method = "dialog" or target != "_self"

Fixes #52017
Fixes #52020

### CODE REVIEW

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 1]
```diff
@@ -31,6 +33,7 @@ Note that we don't reference NavigationManager.ts from NavigationEnhancement.ts
 different bundles that only contain minimal content.
 */
 
+const logger = new ConsoleLogger(LogLevel.Warning);
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:36]: If we're going to unconditionally warn, could we use `console.warn` instead?

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 2]
```diff
@@ -116,13 +119,26 @@ function onDocumentSubmit(event: SubmitEvent) {
       return;
     }
 
+    const submitter = event.submitter as HTMLButtonElement;
+
+    if ((submitter && submitter.formMethod && submitter.formMethod === 'dialog') ||
+      formElem.method === 'dialog') {
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:125]:
```suggestion
    if (submitter?.formMethod === 'dialog' || formElem.method === 'dialog') {
```
You might have written it this way for better browser compatibility, but I believe the JS produced by this will desugar into effectively what you've written here. Even if it doesn't, I think we should be okay to use `?.` because every major browser has supported it [since 2020](https://caniuse.com/mdn-javascript_operators_optional_chaining).

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 3]
```diff
@@ -116,13 +119,26 @@ function onDocumentSubmit(event: SubmitEvent) {
...
+      logger.log(LogLevel.Warning, 'Form cannot be enhanced when method = "dialog".');
+      return;
+    }
+
+    if ((submitter && submitter.formTarget && submitter.formTarget !== '_self') ||
+      formElem.target !== '_self') {
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:131]:
```suggestion
    if (submitter?.formTarget !== '_self' || formElem.target !== '_self') {
```

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 4]
```diff
@@ -116,13 +119,26 @@ function onDocumentSubmit(event: SubmitEvent) {
       return;
     }
 
+    const submitter = event.submitter as HTMLButtonElement;
+
+    if ((submitter && submitter.formMethod && submitter.formMethod === 'dialog') ||
+      formElem.method === 'dialog') {
+      logger.log(LogLevel.Warning, 'Form cannot be enhanced when method = "dialog".');
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:126]: Nit:
```suggestion
      logger.log(LogLevel.Warning, 'A form cannot be enhanced when its method is "dialog".');
```

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 5]
```diff
@@ -116,13 +119,26 @@ function onDocumentSubmit(event: SubmitEvent) {
...
+      return;
+    }
+
+    if ((submitter && submitter.formTarget && submitter.formTarget !== '_self') ||
+      formElem.target !== '_self') {
+      logger.log(LogLevel.Warning, 'Form cannot be enhanced when target is different from the default value "_self".');
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:132]: Nit:
```suggestion
      logger.log(LogLevel.Warning, 'A form cannot be enhanced when its target is different from the default value "_self".');
```

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 6]
```diff
@@ -116,13 +119,26 @@ function onDocumentSubmit(event: SubmitEvent) {
       return;
     }
 
+    const submitter = event.submitter as HTMLButtonElement;
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:122]: Strictly speaking I'm not sure this is a valid downcast. A form could be submitted by something other than a button, e.g., you can have `<input type="image">` that triggers the form submit. Bear in mind that `as` in TypeScript just means "cast" (unlike in C#, where `as` has a different meaning because in C# it also does a runtime type check and supplies `null` if the type check is not satisfied).

Based on JS's loose typing the code would probably work anyway even in that case, but to communicate the intent more clearly, it may be clearer to avoid the downcast, and instead just do:

```ts
if (event.submitter?.getAttribute('formmethod') === 'dialog' || formElem.method === 'dialog') { ... }
```

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:122]: BTW I'm aware this downcast already existed in the code before, and was probably my mistake in writing an earlier version of this!

**Review by SteveSandersonMS — APPROVED** [review]
Some minor syntactical comments to resolve, but besides that the overall thing looks great!

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts (hunk 3 above)
Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:131]: Thank you for the suggestion!
I did not apply it because in case when there is no formtarget the first part `submitter?.formTarget !== '_self'` equals true. That is not the result I want. 
I changed it to `submitter?.formTarget ?? formElem.target) !== '_self'` instead.

Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:131]: Thank you for the suggestion!
I didn't apply it because when there is no `formtarget` then first part `submitter?.formTarget !== '_self'` equals true. 
Also, I found that `target` is not specified then `formElem.target` equals empty string.
