### PR TITLE
Date only and time only is not supported in blazor change detection for parameters

### LINKED ISSUE #49021: DateOnly and TimeOnly is not supported in Blazor change detection for parameters
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

DateOnly and TimeOnly is probably supported almost everywhere. Now it is time to add them to known immutable types here (similar to Guid):

https://github.com/dotnet/aspnetcore/blob/213eb282fc6d9ce07a1e0a1fbe526c297694ebf6/src/Components/Components/src/ChangeDetection.cs#L42-L45

GetTypeCode returns TypeCode.Object for both of them.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MattyLeslie**
# Add DateOnly and TimeOnly support in Blazor change detection

**Summary of the changes (Less than 80 chars)**
Add DateOnly and TimeOnly as known immutable types in Blazor change detection.

## Description

Updated the `ChangeDetection` class to include `DateOnly` and `TimeOnly` in the `IsKnownImmutableType` method. Introduced a caching mechanism to store immutability checks results using a `ConcurrentDictionary<T, U>` for performance optimization. Added support for hot reload to clear the cache when a hot reload event occurs.

Fixes #49021

### CODE REVIEW

**Comment by MattyLeslie** [comment]
@MackinnonBuck, may I please request a review for this.

File: src/Components/Components/src/ChangeDetection.cs [hunk 1]
```diff
@@ -41,6 +44,24 @@ public static bool MayHaveChanged<T1, T2>(T1 oldValue, T2 newValue)
...
+    public static void ClearImmutableTypeCache()
+    {
+        _immutableNonObjectTypesCache.Clear();
+    }
+
+    public static void HotReloadHandler()
+    {
+        ClearImmutableTypeCache();
+        OnHotReload?.Invoke();
+    }
```
Comment (MackinnonBuck) [inline src/Components/Components/src/ChangeDetection.cs:66]: It doesn't look like this hooks into the hot reload `OnDeltaApplied` event, so the cachce will never get cleared.

This can all probably be reduced down to something like what we do for RouteView: https://github.com/dotnet/aspnetcore/blob/870eec223cdb09e5ca8cfdc61bfd5fbc2ca9773b/src/Components/Components/src/RouteView.cs#L23-L29

**Review by MackinnonBuck — COMMENTED** [review]
Thanks @MattyLeslie! Looks good so far - just a few suggestions. Let me know if you'd like me to take it from here.

**Comment by MattyLeslie** [comment]
@MackinnonBuck If you're will to carry it over the line that would be great otherwise I'll address that feedback as soon as I get time.

**Review by MackinnonBuck — APPROVED** [review]
