### PR TITLE
Run InputDate E2E tests on WebAssembly only. Fixes #35018, #34884

### LINKED ISSUE #35018: Quarantining `InputDateInteractsWithEditContext_TimeInput`
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerFormsTest.InputDateInteractsWithEditContext_TimeInput

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: String[] ["The DepartureTime field must be a time."]
Actual:   String[] ["The DepartureTime field must be a time.", "The VisitMonth field must be a year and month."]
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\7792430a5d3e4494baadcc7f13ed0f09.png'
Encountered browser errors
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:34.075Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:34.117Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=vAqLkXaAw7XCETOZaJCYkg."
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:54.335Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:54.358Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=my9_k6eZtC37ZZuJhzduxA."
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:56.926Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:56.932Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=UeevRbfFHmSO3XWu2cAjng."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.481Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.487Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=fYi2IgiRg7sUTYTxjNzQXA."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.887Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.893Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=eWoyZ0KVXxAUeArMtCIuWA."
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:59.537Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:59.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 84
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.Tests.FormsTest.InputDateInteractsWithEditContext_TimeInput() in /_/src/Components/test/E2ETest/Tests/FormsTest.cs:line 272
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1273293&view=ms.vss-test-web.build-test-results-tab&runId=37656758&resultId=100181&paneView=debug

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Our `InputDate` E2E tests have been marked as `Skip` for a long time because, unlike all the other E2E tests, we couldn't find any way to make them totally reliable when running on Blazor Server. It appears to be something very special about how keyboard input interacts with asynchrony on those specific input types.

We've made multiple attempts to fix this in the past by changing how exactly we simulate user interaction, but roughly 1% flakiness remained.

Since it's better to at least have coverage for the behaviors on WebAssembly, this PR changes those specific tests into WebAssembly-specific ones.

### CODE REVIEW

File: src/Components/test/E2ETest/Tests/FormsInputDateTest.cs [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+
+        // Can become invalid
+        // Stricly speaking the following is equivalent to the empty state, because that's how incomplete input is represented
+        // We don't know of any way to produce a different (non-empty-equivalent) state using UI gestures, so there's nothing else to test
+        departureTimeInput.SendKeys($"20{Keys.Backspace}\t");
+        Browser.Equal("modified invalid", () => departureTimeInput.GetAttribute("class"));
+        Browser.Equal(new[] { "The DepartureTime field must be a time." }, messagesAccessor);
+    }
+
+    [Fact(Skip = "This functionality doesn't work on Edge/Chrome - tracked as https://github.com/dotnet/aspnetcore/issues/38471")]
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/Tests/FormsInputDateTest.cs:117]: This one remains skipped because it's genuinely broken behavior (#38471).

**Review by javiercn — APPROVED** [review]
LGTM

**Review by TanayParikh — APPROVED** [review]
