### PR TITLE
Re-run routing for implicit middlewares that require endpoints

### LINKED ISSUE #49654: Explicitly calling app.UseRouting() in Blazor Web App results in exception that antiforgery middleware is missing
If I add an explicit call to app.UseRouting() in a Blazor Web App, I get the following exception:

"Endpoint / (/) contains anti-forgery metadata, but a middleware was not found that supports anti-forgery."

Repro steps:

- Create a Blazor Web App
- Update Program.cs to call app.UseRouting() explicitly:

```csharp
app.UseRouting();
app.MapRazorComponents<App>();
```

- Run the app

Expected result: App runs without error
Actual result: Exception saying that the antiforgery middleware is required
Workaround: Adding the antiforgery middleware resolves the issue

.NET SDK version: 8.0.100-preview.7.23375.2

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/49654.

Auth-related middlewares set state on the HttpContext to indicate that they have run when an endpoint is available so that the endpoints middleware can warn if endpoints that should've been evaluated by the middleware have not been.

The WebApplicationBuilder registers a set of auth-related middlewares implicitly when their associated services are registered. When the user calls `UseRouting` explicitly in their application code, the middlewares are registered after and are not able to examine the endpoint set by the routing middleware.

A combination of these factors means that users receive erroneous warnings that auth-related middlewares have not run on endpoints when they have (as in the issue above).

To resolve this, we force routing to run in the middlewares that need to set state in reaction to it.

### CODE REVIEW

File: src/Antiforgery/src/AntiforgeryApplicationBuilderExtensions.cs [hunk 1]
```diff
@@ -24,6 +26,16 @@ public static IApplicationBuilder UseAntiforgery(this IApplicationBuilder builde
         builder.VerifyAntiforgeryServicesAreRegistered();
 
         builder.Properties[AntiforgeryMiddlewareSetKey] = true;
+
+        if (builder.Properties.TryGetValue(RerouteHelper.GlobalRouteBuilderKey, out var routeBuilder) && routeBuilder is not null)
```
Comment (JamesNK) [inline src/Antiforgery/src/AntiforgeryApplicationBuilderExtensions.cs:30]: Add a comment about what this is doing and why

File: src/Security/Authentication/Core/src/AuthAppBuilderExtensions.cs [hunk 2]
```diff
@@ -22,6 +24,17 @@ public static IApplicationBuilder UseAuthentication(this IApplicationBuilder app
         ArgumentNullException.ThrowIfNull(app);
 
         app.Properties[AuthenticationMiddlewareSetKey] = true;
+
+        if (app.Properties.TryGetValue(RerouteHelper.GlobalRouteBuilderKey, out var routeBuilder) && routeBuilder is not null)
```
Comment (JamesNK) [inline src/Security/Authentication/Core/src/AuthAppBuilderExtensions.cs:28]: Add a comment about what this is doing and why

File: src/Security/Authorization/Policy/src/AuthorizationAppBuilderExtensions.cs [hunk 3]
```diff
@@ -30,6 +32,21 @@ public static IApplicationBuilder UseAuthorization(this IApplicationBuilder app)
         VerifyServicesRegistered(app);
 
         app.Properties[AuthorizationMiddlewareSetKey] = true;
+
+        if (app.Properties.TryGetValue(RerouteHelper.GlobalRouteBuilderKey, out var routeBuilder) && routeBuilder is not null)
```
Comment (JamesNK) [inline src/Security/Authorization/Policy/src/AuthorizationAppBuilderExtensions.cs:36]: Add a comment about what this is doing and why

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 4]
```diff
@@ -2838,6 +2838,176 @@ public async Task DebugView_Endpoints_UseEndpoints_AvailableBeforeAndAfterStart(
...
+        await app.StartAsync();
+
+        var client = app.GetTestClient();
+        var response = await client.GetAsync("/?username=test");
+        response.EnsureSuccessStatusCode();
+        Assert.Equal("Hello test!", await response.Content.ReadAsStringAsync());
+
+        var endpointResponse = await client.GetAsync("/endpoint?username=test");
+        endpointResponse.EnsureSuccessStatusCode();
+        Assert.Equal("Hello test!", await endpointResponse.Content.ReadAsStringAsync());
```
Comment (BrennanConroy) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:2973]: nit: since the 2 endpoints output that same thing you can't tell if they both ran

**Review by BrennanConroy — COMMENTED** [review]
Missing antiforgery tests, and tests with explicit `UseAuth*` calls

**Review by BrennanConroy — APPROVED** [review]
Backport worthy?

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 5]
```diff
@@ -2697,7 +2699,7 @@ public void DebugView_UseMiddleware_HasMiddleware()
         // 3. Generated delegate name from app.Use(...)
         Assert.Collection(debugView.Middleware,
             m => Assert.Equal(typeof(MiddlewareWithInterface).FullName, m),
-            m => Assert.Equal("Microsoft.AspNetCore.Authentication.AuthenticationMiddleware", m),
+            m => Assert.StartsWith("Microsoft.AspNetCore.Builder.AuthAppBuilderExtensions", m),
```
[the remark this answers is not in the document]
Comment (captainsafia) [reply src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:2702]: Not sure exactly what you mean. I updated the check because I wanted to avoid having the generated name of the delegate-based middleware here. I think it stays mostly consistent but I wanted to avoid typing out the whole thing.

Also, it's a helpful indicator of what codepath you went through (re-routed middleware or plain middleware).

**Comment by captainsafia** [comment]
> Backport worthy?

I think so. I'll have to double check that it does repro in .NET 7 (probably) and author a separate bug fix for it. We can't backport directly since we made substantial changes to the WebApplicationBuilder in .NET 8.

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (BrennanConroy) [reply src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:2702]: I meant in the case of consumable data, can customers only see this in the debugger? Or should we treat it more like public API and try to have nicer names show up?
