### PR TITLE
Load configuration in UseHttps

### LINKED ISSUE #45801: Kestrel config behaves differently when set using env vars vs. in-code
I have a Web API application that I want to configure it to listen on an HTTPS port. The app is containerized and orchestrated using Docker compose.

I can configure it by setting the following env variable in `docker-compose`, which works as expected.

```yaml
services:
  webapi:
    environment:
      - ASPNETCORE_URLS=https://+:443
```

However, when I use the following approach as an alternative to setting the environment variable, it fails with the following error message.

```csharp
builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(
    address: IPAddress.Any,
        port: 443,
        configure: listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
            listenOptions.UseHttps();
        });
});
```

> Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

When I provide the filename and password to the SSL certificate file as the following, it works as expected.

```csharp
builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(
    address: IPAddress.Any,
        port: 443,
        configure: listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
            listenOptions.UseHttps("/root/.aspnet/https/cert.pfx", "Password");
        });
});
```

I assume setting the environment variable `ASPNETCORE_URLS` or calling `ConfigureKestrel` are equivalent, though, I am not sure what I am missing in the second approach. 

### Update 
I was previously getting the following error, which was related to mapping the port `443` to an incorrect port of the container.

> Detected a TLS handshake to an endpoint that does not have TLS enabled.

### PR DESCRIPTION
**Pull request by amcasey**
# Load configuration in UseHttps

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Load configuration in `UseHttps` so that configuration-based certs will be considered, if necessary.
    
Largely salvaged from #48056
Builds on #48137
Fixes #45801

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]
LGTM

File: src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs [hunk 1]
```diff
@@ -77,12 +77,6 @@ public HttpsConnectionAdapterOptions()
     /// </summary>
     public SslProtocols SslProtocols { get; set; }
 
-    /// <summary>
-    /// The protocols enabled on this endpoint.
-    /// </summary>
-    /// <remarks>Defaults to HTTP/1.x only.</remarks>
-    internal HttpProtocols HttpProtocols { get; set; }
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs:84]: ❤️

File: src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs [hunk 2]
```diff
@@ -422,6 +427,93 @@ public void UseKestrelCore_ConfigurationBased(bool useQuic)
...
+        Assert.Equal("Hello World", result);
+
+        Assert.True(ranCertificateValidation);
+
+        await host.StopAsync().DefaultTimeout();
+    }
+
+    ///<remarks>
+    /// This is something of a hack - we should actually be calling
+    /// <see cref="Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.TryGetCertificatePath"/>.
```
Comment (halter73) [inline src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:506]:
```suggestion
    /// <see cref="Microsoft.AspNetCore.Server.Kestrel.TlsConfigurationLoader.TryGetCertificatePath"/>.
```

And can we just make `TryGetCertificatePath` internal and call it from the test?

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 3]
```diff
@@ -166,6 +166,9 @@ public static ListenOptions UseHttps(this ListenOptions listenOptions, Action<Ht
         // We consider calls to `UseHttps` to be a clear expression of user intent to pull in HTTPS configuration support
         listenOptions.KestrelServerOptions.EnableHttpsConfiguration();
 
+        // If there's a configuration, load it so that the results will be available to ApplyDefaultCertificate
+        listenOptions.KestrelServerOptions.ConfigurationLoader?.LoadInternal();
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: Does this load the dev cert too? Are there additional console logs for that?

File: src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs (hunk 2 above)
Comment (amcasey) [reply src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:506]: I think we iterated on that a few times in the version of this change that made loading lazier and concluded this was the least bad option (as I recall, it couldn't be static and getting an instance with the correct state was also hacky).

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 3 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: Assuming you mean the one from the cert store (and not the magic docker one), I don't believe so, but I can double check.  And I'm not sure what you mean by "additional console logs"?

Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: In a prior release we'd changed the dev cert to delay-load from the cert store because if it loaded earlier then even apps with their own cert would get logs about the dev cert being loaded, and it was a startup time perf hit.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: This is not changing when any cert gets loaded. I might help find the default cert first and elide the cert store check, but the cert store would still be loaded later in `ApplyDefaultCertificate` as usual otherwise.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: I keep getting mixed up because of the number of moving parts (not to mention the number of iterations this change has been through), but I think it _can_ cause the cert to be loaded earlier.  However, unlike (what I understand of) the previous change, it will only do that in cases where it was going to be loaded regardless (except for the weird corner case where you add a cert to your config between `UseHttps` and `Bind`).

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:170]: Does that address your concerns, @Tratcher?
