### PR TITLE
[Blazor] Auto render mode improvements

### LINKED ISSUE #52154: [Blazor] Auto Render not working properly in .NET 8 and page locks until WebAssembly start
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I updated Visual Studio to the latest version 17.8.0 and created a Blazor app using Auto render mode With Dotnet 8. When I run the application and navigate to the Counter tab, the whole page locks up until the WebAssembly Start. I can't do anything or switch to another tab until the download Finished And WebAssembly Start, even though it happens quickly locally. This could cause problems in production where the download may take longer. It also goes against the purpose of Auto render mode.

### Expected Behavior

With auto render mode, the page should initially use server-side rendering. Once WebAssembly finishes downloading And Start, it can switch over seamlessly without locking up the page.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

NET 8 , Windows 10-64

### Anything else?

As you can see, the page is locked and prevents navigating to another tab.
lockPage

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Auto render mode improvements

Improves the Auto render mode so that components are more responsive and have a decreased initial time to interactivity when WebAssembly resources are not already cached.

## Description

This PR makes the following improvements:
* Removes the timeout for loading the boot config. This prevents Server interactivity from always being used when the connection quality is poor.
* Introduces a limit to the maximum parallel WebAssembly resource downloads when an Auto component initiates the startup of the WebAssembly runtime. This limit is set to 1 and overrides any user-specified limit.
* Fixes an issue where the circuit sometimes remains open even if WebAssembly gets selected for Auto interactivity.

Another potential improvement is to defer the start of WebAssembly resource downloading until after the circuit starts. However, we may want to consider this as an enhancement for .NET 9 rather than include it in a .NET 8 servicing release because it's a larger and riskier change.

I've been testing these improvements on a published site hosted on Azure to collect real-world measurements and verify that these changes improve things in the way we expect. I also provided a preview of these changes in https://github.com/dotnet/aspnetcore/issues/52154#issuecomment-1843535849 so that customers could try them out, and the feedback so far has been very positive.

Remaining work:
- [x] E2E tests
- [x] Continued real-world testing and validation on mobile scenarios

Fixes #52154

### CODE REVIEW

File: src/Components/Web.JS/src/Services/WebRootComponentManager.ts [hunk 1]
```diff
@@ -100,12 +99,18 @@ export class WebRootComponentManager implements DescriptorHandler, RootComponent
...
+    // activating the component yet. This is becuase WebAssembly resources
+    // may take a long time to load, so starting to load them now potentially reduces
+    // the time to interactvity.
+    if (descriptor.type === 'webassembly') {
       this.startLoadingWebAssemblyIfNotStarted();
+    } else if (descriptor.type === 'auto') {
+      // If the WebAssembly runtime starts downloading because an Auto component was added to
+      // the page, we limit the maximum number of parallel WebAssembly resource downloads to 1
+      // so that the performance of any Blazor Server circuit is minimally impacted.
+      this.startLoadingWebAssemblyIfNotStarted(/* maxParallelDownloadsOverride */ 1);
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/WebRootComponentManager.ts:113]: Does this mean if there's a combination of WebAssembly and Auto components on the page, the maxParallelDownloadsOverride value will end up being determined by which of them appeared first in the DOM?

If so that's slightly quirky but most likely not a problem in real life, as people will almost never mix both of those modes.

**Review by SteveSandersonMS — APPROVED** [review]
Looks great.

I thought before you mentioned we'd need a runtime change in order to be able to override the parallelism. Has that change been made now? Or did you find another way to do it?

File: src/Components/Web.JS/src/Services/WebRootComponentManager.ts (hunk 1 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Services/WebRootComponentManager.ts:113]: Agree with Steve here

**Review by javiercn — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
> I thought before you mentioned we'd need a runtime change in order to be able to override the parallelism. Has that change been made now? Or did you find another way to do it?

The merged runtime fix to enable this can be found [here](https://github.com/dotnet/runtime/pull/95793)

File: src/Components/Web.JS/src/Services/WebRootComponentManager.ts (hunk 1 above)
Comment (MackinnonBuck) [reply src/Components/Web.JS/src/Services/WebRootComponentManager.ts:113]: We might be able to partially mitigate this by changing this method to accept the full set of discovered `ComponentDescriptor`s all at once. Then if any descriptors have type `'webassembly'`, download WebAssembly resources with full (or user-specified) parallelism. Otherwise, if there are any `'auto'` descriptors, download WebAssembly resources with no parallelism. But considering that mixing 'auto' and 'webassembly' is an uncommon use case, and that it's preferable to keep servicing changes minimal, I would propose that we make any further adjustments in .NET 9.

Long-term, it might be preferable to be able to dynamically change the throttling amount so that if a WebAssembly component appears on the page after an Auto component already initiated the downloading of WebAssembly resources, we would switch to downloading with full parallelism, so the WebAssembly component becomes interactive as quickly as possible.

I'll open an issue to track this.

Comment (MackinnonBuck) [reply src/Components/Web.JS/src/Services/WebRootComponentManager.ts:113]: https://github.com/dotnet/aspnetcore/issues/53284

**Comment by ihorlazarenko** [comment]
I have tested auto render mode after fix and found it still useless in a few network's latency modes. When network connection is super fast(localhost for example) assemblies are loaded before any web socket connection starts. When connection is slow, loading of assemblies is slow and server rendering lags and both interrupt each other which influences in even worse UX(server rendering is laggier until web assembly cache is downloaded and web assembly load time is bigger). From my point of view strategy should be next: if dlls is not cache then use server rendering without interruption with loading of DLLs,  load dlls only when server rendering does not perform any network requests.

**Comment by SteveSandersonMS** [comment]
@ihorlazarenko Thanks for looking into it.

> When network connection is super fast(localhost for example) assemblies are loaded before any web socket connection starts.

To be honest that doesn't seem like a problem to me. Not sure what other behavior you'd want in that case.

> When connection is slow, loading of assemblies is slow and server rendering lags and both interrupt each other which influences in even worse UX

That does seem problematic but I thought that was one of the issues we specifically fixed. How do you know that the WebAssembly file loading is interrupting the WebSocket connection, as opposed to lag simply being caused by the connection being slow? The updated logic already limits the WebAssembly file loading to a single connection, so there should always be at least one other outbound connection slot available for the WebSocket connection.

> load dlls only when server rendering does not perform any network requests.

Server rendering is a WebSocket connection so it's hard to determine what is meant by "does not perform any network requests". There is always going to be a single network connection for the WebSocket connection, and it stays open for as long as you have an active circuit. The user can perform interactions at any moment, unpredictably, and when they do so we need to send and receive traffic ASAP to keep the UI responsive.

If there are specific ways you know of that the WebAssembly file loading can be deprioritized to minimize network impact please let us know. [The `fetch` API does have a `priority` option](https://developer.mozilla.org/en-US/docs/Web/API/fetch). I'm not certain how it would interact in practice but it might be something for us to try next depending on what other feedback we get on the improved Auto mode. Much of the other feedback so far has been positive, so perhaps in a lot of cases things will already work well.

**Comment by ihorlazarenko** [comment]
let me describe more concrete example. I have created solution from template where server project + counter page in client project.  Server project has static renderer with navigation and counter has auto renderer. I changed only rendering mode in counter page. First I disabled prerendering in counter and run in auto mode without prerendering in browser with "slow 3g" network option. After nearly 30-35 seconds page was rendered in interaction server mode(DLLs were loaded after 2 minutes) and while loading control was a little bit laggy(waiting for counter update after clicking). When I switched to pure server rendering without prerendering I got rendered page after 9-10 seconds without noticeable lags. So the difference between auto and server mode is 35 and 10 seconds for this connection. There is nearly the same proportion using another network speed. Why do not use only server rendering in auto mode until control was rendered at least first time?

**Comment by mikes-gh** [comment]
@MackinnonBuck I see this PR is labelled `9.0.preview1` Do we have to wait till November 24 for this much talked about net8.0 feature to work?

**Comment by MackinnonBuck** [comment]
@mikes-gh This is the PR targeting the `main` branch, but the same fix was taken in an internal PR and will be included in the upcoming 8.0.2 release.

**Comment by ihorlazarenko** [comment]
it still doesn't work in 8.0.2
