### PR TITLE
Don't send body in HEAD response when using PipeWriter.Advance before headers flushed

### LINKED ISSUE #59691: ASP.NET Core 9 sends response content for HTTP HEAD requests
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In .NET 8 (and I think earlier versions), returning an `IResult` that writes a response body would not actually write the body in response to HTTP HEAD requests, but this has changed in .NET 9. I couldn't find anything in the published change notes indicating that this is an intended change.

For example, with the program:
```csharp
var app = WebApplication.Create();

app.Map("/", () => Results.Ok(new { message = "ok!" }));

app.Run();
```

When running with .NET 8:
```
>curl --head http://localhost:5087
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Jan 2025 11:59:38 GMT
Server: Kestrel

>curl -X HEAD http://localhost:5087 -m 1
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the way you want. Consider using -I/--head instead.
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
```

The second invocation uses `-X HEAD` to make curl ignore all HTTP semantics regarding the HEAD method, and so times out waiting for a response body that never arrives (hence curl's big warning!)

But when running with .NET 9:
```
>curl --head http://localhost:5087
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Jan 2025 12:02:19 GMT
Server: Kestrel
Transfer-Encoding: chunked

>curl -X HEAD http://localhost:5087 -m 1
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the way you want. Consider using -I/--head instead.
{"message":"ok!"}
```

Note that the second invocation now succeeds, because the server included the response content. This violates [RFC 9110 9.3.2.](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2): `The HEAD method is identical to GET except that the server MUST NOT send content in the response.`

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0.101

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
Bug exposed/introduced by https://github.com/dotnet/aspnetcore/pull/8199

Fixes https://github.com/dotnet/aspnetcore/issues/59691

Reason this hasn't been found in the >5 years since the bug was introduced is that it requires using `PipeWriter.GetMemory(...)` + `PipeWriter.Advance(...)` before flushing the headers and using a HEAD request at the same time. This is very uncommon except for in .NET 9 where we made writing JSON responses use the `PipeWriter` which uses the `GetMemory` + `Advance` path.

The fix is to pass the `canWriteBody` parameter to `WriteDataWrittenBeforeHeaders` and only copy the bytes from previous `GetMemory` + `Advance` calls to the body if `canWriteBody` is true.

Edit: Removed `Transfer-Encoding: chunked` header from non-body responses.
~~**One additional change we might want to consider here**, is removing the `Transfer-Encoding: chunked` header from the HEAD response. We have [TransferEncodingNotSetOnHeadResponse](https://github.com/dotnet/aspnetcore/blob/1a23df0f96175d51940aec9306db3460d484da4d/src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs#L875) and [ManuallySettingTransferEncodingThrowsForHeadResponse](https://github.com/dotnet/aspnetcore/blob/1a23df0f96175d51940aec9306db3460d484da4d/src/Servers/Kestrel/Core/test/Http1/Http1ConnectionTests.cs#L628) which show us explicitly not letting the transfer encoding exist on a HEAD response, however according to the RFC 7231 section 4.3.2~~
> ~~The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   ([Section 3.3](https://www.rfc-editor.org/rfc/rfc7231#section-3.3)) MAY be omitted.~~

~~And https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding~~
> ~~When present on a response to a [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) request that has no body, it indicates the value that would have applied to the corresponding [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) message.~~

~~Both of which indicate it is perfectly fine to include the Transfer-Encoding header.~~

~~Looking at the history of why we added this restriction to Kestrel, we find https://github.com/aspnet/KestrelHttpServer/issues/952 which was about a browser request hanging when accessing an endpoint that responded with another non-body response in the form of a 304 and we just added the restriction to HEAD response as well since it is a non-body response.~~

### CODE REVIEW

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs [hunk 1]
```diff
@@ -1471,7 +1534,7 @@ public async Task HeadResponseBodyNotWrittenWithSyncWrite()
         await using (var server = new TestServer(async httpContext =>
         {
             httpContext.Response.ContentLength = 12;
-            await httpContext.Response.BodyWriter.WriteAsync(new Memory<byte>(Encoding.ASCII.GetBytes("hello, world"), 0, 12));
+            httpContext.Response.Body.Write(Encoding.ASCII.GetBytes("hello, world"), 0, 12);
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:1537]: https://github.com/dotnet/aspnetcore/pull/7110 removed the sync write which this test and `HeadResponseBodyNotWrittenWithSyncWrite` above were explicitly testing.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs [hunk 2]
```diff
@@ -1426,12 +1426,15 @@ await connection.Receive(
...
+
+                connection.ShutdownSend();
+                await connection.ReceiveEnd();
             }
         }
     }
 
     [Fact]
-    public async Task HeadResponseBodyNotWrittenWithAsyncWrite()
+    public async Task HeadResponseHeadersWrittenWithAsyncWriteBeforeAppCompletes()
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:1437]: https://github.com/aspnet/KestrelHttpServer/pull/1204 changed some of the HEAD response tests to only check the response headers are flushed and doesn't fully check that the body doesn't exist. So split the test into two for the flushed headers check, and the lack of body check.

**Review by mgravell — APPROVED** [review]
LGTM, interesting find!

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs [hunk 3]
```diff
@@ -545,6 +557,7 @@ public void Reset()
         _writeStreamSuffixCalled = false;
         _currentChunkMemoryUpdated = false;
         _startCalled = false;
+        _canWriteBody = true;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs:560]: I don't love splitting this state between `Http1OutputProducer` and `HttpProtocol`. Some of the usage in `HttpProtocol` now appears to be vestigial to me.

I know we're already sharing the `_autoChunk` state which is part of the problem. The other problem seems to be that neither `true` nor `false` is a good default state for either `_autoChunk` or `_canWriteBody` since we don't know what either will end up being until response headers are sent, but it's still possible to call into the `Http1OutputProducer` before then for buffering purposes. I think the better solution would be to combine `_autoChunk` and `_canWriteBody` into a 4-state enum. This probably would still have to be shared between `HttpProtocol` and `Http1OutputProducer` but at least it's only one field then.

Then we can continue to pass it via `WriteResponseHeaders` instead of adding a new `SetCanWriteBody` method.

```csharp
enum ResponseBodyMode
{
    Uninitialized,
    Disabled,
    Chunked,
    ContentLength
}
```

**Comment by halter73** [comment]
> Both of which indicate it is perfectly fine to include the Transfer-Encoding header.

I'm fine with changing the behavior here if we think it's better. At least, it seems well documented that it's supported. I don't really see the value in sending the behavior personally, but what we should ensure is that writing to the response Stream or BodyWriter behaves the same.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 4]
```diff
@@ -1161,9 +1159,9 @@ private HttpResponseHeaders CreateResponseHeaders(bool appCompleted)
         }
 
         // Set whether response can have body
-        _canWriteResponseBody = CanWriteResponseBody();
+        _responseBodyMode = CanWriteResponseBody() ? ResponseBodyMode.ContentLength : ResponseBodyMode.Disabled;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1162]: This is why I suggested an `Unitialized` state. It seems wrong to have the mode be `ContentLength` both here and after calling `Reset()` when we could ultimately end up auto-chunking.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 5]
```diff
@@ -1591,9 +1592,9 @@ public ValueTask<FlushResult> WritePipeAsync(ReadOnlyMemory<byte> data, Cancella
             VerifyAndUpdateWrite(data.Length);
         }
 
-        if (_canWriteResponseBody)
+        if (_responseBodyMode != ResponseBodyMode.Disabled)
         {
-            if (_autoChunk)
+            if (_responseBodyMode == ResponseBodyMode.Chunked)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1597]: Nit: Can this be refactored into a 3-case switch statement? Or maybe 4-case switch statement for the hopefully unreachable `Uninitialized` if we decide add that.

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 6]
```diff
@@ -1639,27 +1640,27 @@ private ValueTask<FlushResult> FirstWriteAsyncInternal(ReadOnlyMemory<byte> data
     {
         var responseHeaders = InitializeResponseFirstWrite(data.Length);
 
-        if (_canWriteResponseBody)
+        if (_responseBodyMode != ResponseBodyMode.Disabled)
         {
-            if (_autoChunk)
+            if (_responseBodyMode == ResponseBodyMode.Chunked)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1645]: Can this also be refactored into a switch statement?

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs [hunk 7]
```diff
@@ -1688,9 +1689,9 @@ public async ValueTask<FlushResult> WriteAsyncAwaited(Task initializeTask, ReadO
 
         // WriteAsyncAwaited is only called for the first write to the body.
         // Ensure headers are flushed if Write(Chunked)Async isn't called.
-        if (_canWriteResponseBody)
+        if (_responseBodyMode != ResponseBodyMode.Disabled)
         {
-            if (_autoChunk)
+            if (_responseBodyMode == ResponseBodyMode.Chunked)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:1694]: ditto

**Review by halter73 — APPROVED** [review]
Thanks for adding the `ResponseBodyMode`. It's a lot easier to follow in my opinion than the two bools. I think an `Uninitialized` state could make things even easier to follow, and switch statements over nested if/else blocks could improve things even more, but these are all style preferences. The change functionally looks solid.

**Review by halter73 — APPROVED** [review]
:heart:
