### PR TITLE
ASP0022 - Fix false positive for groups without using intermediate variables

### LINKED ISSUE #56115: ASP0022 - False positive without using intermediate variables with groups
The following reports 2 warnings ASP0022 lines 6 and 9:

```cs
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGroup("/v1/orders")
    .MapGet("/{id:int}", (int id) => { });

app.MapGroup("/v2/orders")
    .MapGet("/{id:int}", (int id) => { });

app.Run();
```

> [ASP0022] Route '/{id:int}' conflicts with another handler route. An HTTP request that matches multiple routes results in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints.

While with intermediate variables, there is no warning reported:

```cs
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

var group1 = app.MapGroup("/v1/orders");
group1.MapGet("/{id:int}", (int id) => { });

var group2 = app.MapGroup("/v2/orders");
group2.MapGet("/{id:int}", (int id) => { });

app.Run();
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #56115.

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

cc @JamesNK.

### CODE REVIEW

File: src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteHandlers/DetectAmbiguousRoutes.cs [hunk 1]
```diff
@@ -199,6 +214,28 @@ private static bool HasMatchingHttpMethods(ImmutableArray<string> httpMethods1,
...
+                return false;
+            }
+
+            for (var i = 0; i < arguments1.Length; i++)
+            {
+                var arg1 = arguments1[i];
+                var arg2 = arguments2[i];
+
+                if (arg1?.Parameter?.Name != arg2?.Parameter?.Name ||
+                    !Equals(arg1?.Value.ConstantValue.Value, arg2?.Value.ConstantValue.Value))
```
Comment (halter73) [inline src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteHandlers/DetectAmbiguousRoutes.cs:230]: Is this valid? What if the argument doesn't have a `ConstantValue`? What if it's different variables? The parameter name (unlike the argument name) will always be `prefix` for two calls to `MapGroup`, right?

Even if we compared argument names instead of parameter names, it could still be an argument that was reassigned. It feels like this should only return true if the arguments are the exact same constant values instead of assuming any list of arguments of the same length are equal unless they are different constant values.

**Comment by JamesNK** [comment]
Hi @joegoldman2

Thats for the PR. I hope you don't mind but I pushed some changes and added some tests. I started testing and looking through scenarios, and there was enough to change that I felt making code changes and explaining would be faster that explaining via comments.

Changes:

* Support local and parameter references when comparing builders and arguments
* Support named parameters when comparing arguments. Arguments can be out of order when someone does this: `app.MapGroup("group1")` vs `EndpointRouteBuilderExtensions.MapGroup(prefix: "group1", builder: app)`.
* Test for `RoutePattern`

**Comment by joegoldman2** [comment]
> I felt making code changes and explaining would be faster than explaining via comments.

You did right! Indeed the implementation seems more robust this way. Thank you for your review.

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
@halter73 Can you take another look?

**Review by halter73 — APPROVED** [review]

**Comment by JamesNK** [comment]
Since there is an easy workaround, and the problem is relatively rare, I think this will ship in .NET 9 and won't be backported to .NET 8. I don't think it meets the servicing bar.
