### PR TITLE
HttpLogging redaction and enrichment

### LINKED ISSUE #31844: HttpLogging redaction and enrichment
We need the ability to allow users to configure and customize what is logged for a request and response. For example if they would like to modify a header value that is logged to remove PII, or adding another key and value to the log.

Our current idea is to have a Func that people can implement that would take a context, and allow returning any KeyValuePair to be logged.

Currently, we were thinking of adding the extension point to where we log headers:

General API shape
```c#

Action<HttpLoggingContext> ModifyLog;

HttpLogContext
{
    HttpContext HttpContext { get; }
    List<KeyValuePair<string, string>> Logs { get; } // or maybe a dictionary
}
```

Example:

```C#
(httpLogContext) =>
{
   httpLogContext.Logs.Add(
       new KeyValuePair<string, string>(
           "RequestAborted", 
            httpLogContext.HttpContext.RequestAborted.IsCancellationRequested.ToString());
}
```

### LINKED ISSUE #49063: HttpLogger does not log RequestBody
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HttpLogging does not log the RequestBody when configured to do so.

### Expected Behavior

A log statement from HttpLogger with the actual body sent

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpLogging(c =>
{
  c.LoggingFields = HttpLoggingFields.RequestBody |
                    HttpLoggingFields.RequestPath |
                    HttpLoggingFields.ResponseBody;
});

var app = builder.Build();

app.UseHttpLogging();
app.MapPost("/", () => "Hello POST!");

app.Run();
```

### Exceptions (if any)

Any request having a body towards the POST endpoint at root results in a log statement that says the body is empty when it's not:

```
POST http://localhost:5145/ HTTP/1.1
User-Agent: vscode-restclient
Content-Type: text/plain
accept-encoding: gzip, deflate
content-length: 3

some text


HTTP/1.1 200 OK
Connection: close
Content-Type: text/plain; charset=utf-8
Date: Tue, 27 Jun 2023 22:13:05 GMT
Server: Kestrel
Transfer-Encoding: chunked

Hello POST!
```

```log
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5145/ text/plain 3
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      PathBase: 
      Path: /
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody:    👈 👈 
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[4]
      ResponseBody: Hello POST!
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5145/ text/plain 3 - 200 - text/plain;+charset=utf-8 0.4329ms
```

### .NET Version

7.0.203

### Anything else?

Microsoft.AspNetCore.App 7.0.5
VSCode / Rider

### LINKED ISSUE #49989: HttpLoggingMiddleware does not log RequestBody when body is consumed by copying to another stream
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When `HttpLoggingMiddleware` is enabled and `HttpContext.Request.Body` is consumed by copying to another stream (calling `CopyToAsync`) instead of reading, an empty `RequestBody` is logged after an endpoint is executed.

### Expected Behavior

Not empty request body is logged when calling `CopyToAsync`, e.g. when sending json body
```json
{
    "Response": "Test Response"
}
```
it should be logged as is.

### Steps To Reproduce

1. Simple Program.cs of ASP.NET Core project that copies request into memory stream and writes it back to response:

```csharp
using System.Text;
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpLogging(options => { options.LoggingFields = HttpLoggingFields.RequestBody; });

var app = builder.Build();

app.MapGet("/", async context =>
{
    // context.Request.EnableBuffering(); // Enabling buffering "fixes" the issue

    using var tempStream = new MemoryStream();
    await context.Request.Body.CopyToAsync(tempStream);

    var responseContent = Encoding.Default.GetString(tempStream.ToArray());
    await context.Response.WriteAsync(responseContent);
});

app.UseHttpLogging();
await app.RunAsync();
```

2. Send a request to `/` endpoint with some json body, e.g. `{ "Response": "Test Response" }`
3. Observe logs.

Logs:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:7255/ application/json 37
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody:
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:7255/ application/json 37 - 200 - - 38.6330ms
```

### Exceptions (if any)

Enabling buffering by uncommenting `context.Request.EnableBuffering();` line.

Logs in this case:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:7255/ application/json 37
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody: {
          "Response": "Test Response"
      }
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:7255/ application/json 37 - 200 - - 25.6788ms
```

Probably it happens because `FileBufferingReadStream` calls `ReadAsync` methods on the inner stream (in this case inner is `RequestBufferingStream`) in its `CopyToAsync` implementation. And `RequestBufferingStream`, when not wrapped, does not write anything in its buffer when `CopyToAsync` is called.

### .NET Version

7.0.203

### Anything else?

ASP.NET Core: 7.0.5
IDE: Visual Studio 2022, Rider

Also reproducible for .NET 6

### PR DESCRIPTION
**Pull request by Tratcher**
This adds extensibility to the logging middleware so that what gets logged can be granularly customized per request.

## Description

See the API review notes at https://github.com/dotnet/aspnetcore/issues/31844#issuecomment-1603418570

Fixes #31844, contributes to https://github.com/dotnet/extensions/pull/4330
Fixes #49989, CopyTo/Async not logging the request body.
Fixes #49063, Clarify when the request body is not fully logged.

IHttpLoggingInterceptor:
- This is a new interface that can have multiple instances registered and injected into the logging middleware. The callbacks run before the normal request/response logging and enable adjusting what should be logged per request, as well as adding custom fields.
- ValueTask OnRequestAsync(HttpLoggingInterceptorContext logContext);
- ValueTask OnResponseAsync(HttpLoggingInterceptorContext logContext);

Duration:
- This is a new field that can be logged, reported as milliseconds since the middleware first saw the request. This is logged once at the end of the response.

```
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[2]
      Response:
      Content-Type: RedactedHeader
      ResponseEnrichment: Stuff
      StatusCode: 200
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[8]
      Duration: 0.3027ms
```

Combine Logs:
`bool HttpLoggingOptions.CombineLogs { get; set; }` has been added to support writing one unified log of request, request body, response, and response body data at the end of the response. The extensions components require this.

Exception handling:
- The middleware has been updated to ensure that all data collected so far is logged even in the event of an exception thrown from the middleware pipeline. This is especially important for the new CombineLogs option since the request data won't have been logged before calling next. Note that since this middleware does not handle the exception, it does not log it so as to avoid duplicating it in the logs.

### CODE REVIEW

**Comment by Tratcher** [comment]
```
Checking for changes to API baseline files release/8.0
Found changes in 1 API baseline files
##[error]Detected modification to baseline API files. PublicAPI.Shipped.txt files should only be updated after a major release. See /docs/APIBaselines.md for more information.
error : Detected modification to baseline API files. PublicAPI.Shipped.txt files should only be updated after a major release. See /docs/APIBaselines.md for more information.
##[error]Modified API baseline files:
error : Modified API baseline files:
##[error]src/Middleware/HttpLogging/src/PublicAPI.Unshipped.txt
error : src/Middleware/HttpLogging/src/PublicAPI.Unshipped.txt
```

@wtgodbe any idea why it's complaining about modifying the Unshipped file? Is the release branch more strict about that?

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+    {
+        LoggingFields &= ~fields;
+    }
+
+    /// <summary>
+    /// Checks if the given field is currently enabled in <see cref="LoggingFields"/>
+    /// and disables it so that a custom log value can be provided instead.
+    /// </summary>
+    /// <param name="field">A single field flag to check.</param>
+    /// <returns>`true` if the field was enabled.</returns>
```
Comment (sebastienros) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:91]:
```suggestion
    /// <returns><see langword="true" /> if the field was enabled.</returns>
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+
+    /// <summary>
+    /// What parts of the request and response to log.
+    /// </summary>
+    public HttpLoggingFields LoggingFields { get; set; }
+
+    /// <summary>
+    /// Limits how much of the request body to log.
+    /// </summary>
+    public int RequestBodyLogLimit { get; set; }
```
Comment (sebastienros) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:35]: Should there be a default value like in dotnet/extensions?

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+        set => _httpContext = value ?? throw new ArgumentNullException(nameof(value));
+    }
+
+    /// <summary>
+    /// What parts of the request and response to log.
+    /// </summary>
+    public HttpLoggingFields LoggingFields { get; set; }
+
+    /// <summary>
+    /// Limits how much of the request body to log.
```
Comment (sebastienros) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:33]:
```suggestion
    /// Gets or sets the maximum number of bytes of the request body to log.
```

Just to be explicit about the unit (bytes).

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+    /// </summary>
+    public int RequestBodyLogLimit { get; set; }
+
+    /// <summary>
+    /// Limits how much of the response body to log.
```
Comment (sebastienros) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:38]:
```suggestion
    /// Gets or sets the maximum number of bytes of the response body to log.
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+    /// </summary>
+    public int ResponseBodyLogLimit { get; set; }
+
+    internal long StartTimestamp { get; set; }
+    internal TimeProvider TimeProvider { get; set; } = null!;
+
+    /// <summary>
+    /// The parameters to log.
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:46]: This should be much more descriptive. I have no idea what a parameter means right now. I will in a few minutes when I read the rest of the PR, but that indicates this needs to be better documented.

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+    /// </summary>
+    public IList<KeyValuePair<string, object?>> Parameters { get; } = new List<KeyValuePair<string, object?>>();
+
+    /// <summary>
+    /// Adds a parameter to the log context.
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:51]: This too

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 7]
```diff
@@ -129,9 +156,11 @@ private async Task InvokeInternal(HttpContext context)
                 }
             }
 
-            var httpRequestLog = new HttpRequestLog(list);
+            var httpRequestLog = new HttpRequestLog(logContext.Parameters);
 
             _logger.RequestLog(httpRequestLog);
+
+            logContext.Parameters.Clear();
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:163]: This is the only thing we're resetting between `OnRequestAsync` and `OnResponseAsync`. That is very unclear right now. I can modify what response fields are going to be logged during `OnRequestAsync` but I can't add arbitrary metadata to be logged for both request and response.

We should be very clear in the documentation and possibly reset all the properties on the context (although based on the tests it's intentional to be able to modify response flags).

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs (hunk 2 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:35]: The default is from HttpLoggingOptions.

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs (hunk 7 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:163]: > We should be very clear in the documentation and possibly reset all the properties on the context (although based on the tests it's intentional to be able to modify response flags).

Yes, being able to control the response log settings during the request callback is intentional, it lets people avoid duplicate checks.

I'll work on the docs.

File: src/Middleware/HttpLogging/src/BufferingStream.cs [hunk 8]
```diff
@@ -297,12 +290,48 @@ public override void EndWrite(IAsyncResult asyncResult)
 
     public override void CopyTo(Stream destination, int bufferSize)
     {
-        _innerStream.CopyTo(destination, bufferSize);
+        // Set a minimum buffer size of 4K since the base Stream implementation has weird behavior when the stream is
+        // seekable *and* the length is 0 (it passes in a buffer size of 1).
+        // See https://github.com/dotnet/runtime/blob/222415c56c9ea73530444768c0e68413eb374f5d/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L164-L184
```
[the remark this answers is not in the document]
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/BufferingStream.cs:295]: Ah, you're right, we don't need to override these. We just needed to get rid of the override that bypasses buffering. The bufferSize of 1 is a special case for seekable streams that didn't know their own length.
https://github.com/dotnet/runtime/blob/6882c0f6b5353babab435c8223f553a1981bbbec/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L142

File: eng/scripts/CodeCheck.ps1 [hunk 9]
```diff
@@ -253,7 +253,10 @@ try {
                     }
                 }
                 # Check for changes in Unshipped in servicing branches
-                if ($targetBranch -like 'release*' -and $targetBranch -notlike '*preview*' -and $file -like '*PublicAPI.Unshipped.txt') {
+                if ($targetBranch -like 'release*'
```
Comment (xakep139) [inline eng/scripts/CodeCheck.ps1:256]:
```suggestion
                if ($targetBranch -like 'release*' `
```

Applies to other lines below too

File: src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs [hunk 10]
```diff
@@ -0,0 +1,87 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Microsoft.AspNetCore.HttpLogging;
+
+namespace HttpLogging.Sample;
+
+internal class SampleHttpLoggingInterceptor : IHttpLoggingInterceptor
```
Comment (xakep139) [inline src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs:8]: Seal this class?

File: src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+{
+    public ValueTask OnRequestAsync(HttpLoggingInterceptorContext logContext)
+    {
+        // Compare to ExcludePathStartsWith
```
Comment (xakep139) [inline src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs:12]: Do we need to reference `ExcludePathStartsWith` here? I don't think that folks reviewing this sample should take into account https://github.com/dotnet/extensions/blob/a387e38dc927035db5492b47e9607867da7d5005/src/Libraries/Microsoft.AspNetCore.Telemetry.Middleware/Logging/LoggingOptions.cs#L216

Comment (xakep139) [reply src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs:12]: I presume this sample targets external audience, that might not be aware of `dotnet/extensions`

File: src/Middleware/HttpLogging/src/IHttpLoggingInterceptor.cs [hunk 12]
```diff
@@ -0,0 +1,32 @@
...
+/// Callbacks used to extend the HttpLogging middleware.
+/// </summary>
+public interface IHttpLoggingInterceptor
+{
+    /// <summary>
+    /// A callback to customize the logging of the request and response.
+    /// </summary>
+    /// <remarks>
+    /// This is called when the request is first received and can be used to configure both request and response options. All settings will carry over to
+    /// <see cref="OnResponseAsync(HttpLoggingInterceptorContext)"/>except the <see cref="HttpLoggingInterceptorContext.Parameters"/>
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/IHttpLoggingInterceptor.cs:16]:
```suggestion
    /// <see cref="OnResponseAsync(HttpLoggingInterceptorContext)"/> except the <see cref="HttpLoggingInterceptorContext.Parameters"/>
```

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs [hunk 13]
```diff
@@ -1272,14 +1509,87 @@ public async Task HttpLoggingExtensionCanModifyRequestAndResponseSizeOnEndpoint(
...
+        var initialResponse = await client.SendAsync(request);
+
+        var filteredLogs = TestSink.Writes.Where(w => w.LoggerName.Contains("HttpLogging"));
+        Assert.Contains(filteredLogs, w => w.Message.Contains("Request"));
+        Assert.DoesNotContain(filteredLogs, w => w.Message.Contains("Accept"));
+        Assert.Contains(filteredLogs, w => w.Message.Contains("StatusCode: 200"));
+        Assert.DoesNotContain(filteredLogs, w => w.Message.Contains("Content-Type: text/plain"));
+    }
+
+    private static DefaultHttpContext CreateRequest()
```
Comment (xakep139) [inline src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:1540]: Maybe something like `CreateContextWithRequest()`?

File: src/Middleware/HttpLogging/src/HttpRequestLog.cs [hunk 14]
```diff
@@ -8,12 +8,12 @@ namespace Microsoft.AspNetCore.HttpLogging;
...
 internal sealed class HttpRequestLog : IReadOnlyList<KeyValuePair<string, object?>>
 {
-    private readonly List<KeyValuePair<string, object?>> _keyValues;
+    private readonly IList<KeyValuePair<string, object?>> _keyValues;
     private string? _cachedToString;
 
     internal static readonly Func<object, Exception?, string> Callback = (state, exception) => ((HttpRequestLog)state).ToString();
 
-    public HttpRequestLog(List<KeyValuePair<string, object?>> keyValues)
+    public HttpRequestLog(IList<KeyValuePair<string, object?>> keyValues)
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpRequestLog.cs:16]: I remember @geeknoid mentioning that virtual calls are costly, here's a small benchmark that shows that moving from `List<T>` -> `IList<T>` is 12% worse that it's now: https://github.com/xakep139/IListVsListBench/tree/master/IListVsListBench

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs (hunk 2 above)
Comment (xakep139) [reply src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:47]: Can we highlight that in `<remarks>` section?

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 15]
```diff
@@ -0,0 +1,131 @@
...
+    public void Disable(HttpLoggingFields fields)
+    {
+        LoggingFields &= ~fields;
+    }
+
+    /// <summary>
+    /// Checks if any of the given fields are currently enabled in <see cref="LoggingFields"/>
+    /// and disables them so that a custom log value can be provided instead.
+    /// </summary>
+    /// <param name="fields">One or more field flag to check.</param>
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:103]:
```suggestion
    /// <param name="fields">One or more field flags to check.</param>
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+    /// <returns><see langword="true" /> if any of the fields were previously enabled.</returns>
+    public bool TryOverride(HttpLoggingFields fields)
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:105]: `TryDisable()` maybe?

File: src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs [hunk 17]
```diff
@@ -15,22 +17,37 @@ public static class HttpLoggingServicesExtensions
...
+    /// <summary>
+    /// Registers the given type as a <see cref="IHttpLoggingInterceptor"/> in the DI container.
+    /// </summary>
+    /// <typeparam name="T">A type that implements <see cref="IHttpLoggingInterceptor"/>.</typeparam>
+    /// <param name="services">The service collection.</param>
+    /// <returns>The original service collection for chaining.</returns>
+    public static IServiceCollection AddHttpLoggingInterceptor<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>
+        (this IServiceCollection services) where T : class, IHttpLoggingInterceptor
+    {
+        services.TryAddSingleton<IHttpLoggingInterceptor, T>();
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:41]: Does this allow adding multiple interceptors? Seems that it's not: https://dotnetfiddle.net/D5yzwP

File: src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs [hunk 18]
```diff
@@ -15,22 +17,37 @@ public static class HttpLoggingServicesExtensions
...
 
+    /// <summary>
+    /// Registers the given type as a <see cref="IHttpLoggingInterceptor"/> in the DI container.
+    /// </summary>
+    /// <typeparam name="T">A type that implements <see cref="IHttpLoggingInterceptor"/>.</typeparam>
+    /// <param name="services">The service collection.</param>
+    /// <returns>The original service collection for chaining.</returns>
+    public static IServiceCollection AddHttpLoggingInterceptor<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>
+        (this IServiceCollection services) where T : class, IHttpLoggingInterceptor
+    {
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:40]:
```suggestion
    {
        ArgumentNullException.ThrowIfNull(services);
```

File: src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs [hunk 19]
```diff
@@ -15,22 +17,37 @@ public static class HttpLoggingServicesExtensions
     /// </summary>
     /// <param name="services">The <see cref="IServiceCollection"/> for adding services.</param>
     /// <param name="configureOptions">A delegate to configure the <see cref="HttpLoggingOptions"/>.</param>
-    /// <returns></returns>
+    /// <returns>The original service collection for chaining.</returns>
     public static IServiceCollection AddHttpLogging(this IServiceCollection services, Action<HttpLoggingOptions> configureOptions)
```
Comment (xakep139) [inline src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:21]: Is it worth registering `HttpLoggingMiddleware` as a singleton here?

Comment (xakep139) [reply src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:21]: But it should implement `IMiddleware` in that case: https://source.dot.net/#Microsoft.AspNetCore.Http.Abstractions/Extensions/UseMiddlewareExtensions.cs,48

File: src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs (hunk 11 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/samples/HttpLogging.Sample/SampleHttpLoggingInterceptor.cs:12]: These samples are for our own usage. I have this one currently set up to mimic what we want to accomplish in extensions. I may clean out some of the references before merging.

File: src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs (hunk 13 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/test/HttpLoggingMiddlewareTests.cs:1540]: I'd rather keep it concise for test code.

File: src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs (hunk 18 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:40]: The extension methods handle this.

File: src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs (hunk 19 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs:21]: No, the IMiddleware approach is less efficient.

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 20]
```diff
@@ -150,57 +179,37 @@ private async Task InvokeInternal(HttpContext context)
...
-            {
-                var responseBody = responseBufferingStream.GetString(responseBufferingStream.Encoding);
-                if (!string.IsNullOrEmpty(responseBody))
-                {
-                    _logger.ResponseBody(responseBody);
-                }
-            }
+            responseBufferingStream?.LogResponseBody(logContext.IsAnyEnabled(HttpLoggingFields.Duration) ? logContext.GetDuration() : null);
         }
         finally
```
[the remark this answers is not in the document]
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:214]: Exception logging/handling is done by a different middleware.

File: src/Middleware/HttpLogging/src/HttpRequestLog.cs (hunk 14 above)
Comment (geeknoid) [reply src/Middleware/HttpLogging/src/HttpRequestLog.cs:16]: Does the CA1859 analyzer diagnostic enabled on this repo? It flags a bunch of cases where code can be upgraded to use concrete types in order to eliminate virtual or interface dispatch.

Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpRequestLog.cs]: Unlikely. In this case the collection is exposed publicly, so we want an abstraction there, but we can pass the concrete type here.

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs (hunk 2 above)
Comment (xakep139) [reply src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:57]: Thanks!

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs (hunk 20 above)
[the remark this answers is not in the document]
Comment (xakep139) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:214]: cc @klauco

**Comment by Tratcher** [comment]
@adityamandaleeka See the last commit for fixing #49063

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs [hunk 21]
```diff
@@ -111,49 +100,95 @@ private void CommonWrite(ReadOnlySpan<byte> span)
...
-        return base.FlushAsync(cancellationToken);
+        await OnFirstWriteAsync();
+        await base.FlushAsync(cancellationToken);
+    }
+
+    public void LogResponseBody(double? duration)
+    {
+        if (_logBody)
+        {
+            var requestBody = GetString(_encoding!);
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:182]: ?
```suggestion
            var responseBody = GetString(_encoding!);
```

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 22]
```diff
@@ -50,88 +54,115 @@ public Task Invoke(HttpContext context)
...
         {
-            var request = context.Request;
-            var list = new List<KeyValuePair<string, object?>>(
-                request.Headers.Count + DefaultRequestFieldsMinusHeaders);
+            logContext.ResponseBodyLogLimit = loggingAttribute.ResponseBodyLogLimit;
+        }
 
+        for (var i = 0; i < _interceptors.Length; i++)
+        {
+            await _interceptors[i].OnRequestAsync(logContext);
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:95]: Does this code need to be in try/finally in order to return the `LogContext` to the pool?

File: src/Middleware/HttpLogging/src/HttpLoggingExtensions.cs [hunk 23]
```diff
@@ -20,8 +20,8 @@ internal static partial class HttpLoggingExtensions
         exception: null,
         formatter: HttpResponseLog.Callback);
 
-    [LoggerMessage(3, LogLevel.Information, "RequestBody: {Body}", EventName = "RequestBody")]
-    public static partial void RequestBody(this ILogger logger, string body);
+    [LoggerMessage(3, LogLevel.Information, "RequestBody: {Body}{status}", EventName = "RequestBody")]
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingExtensions.cs:23]: Logging tokens should always be pascal case, e.g. `{Status}`.

Is the formatting right here? Should there be a space between body and status?

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 24]
```diff
@@ -0,0 +1,147 @@
...
+
+    /// <summary>
+    /// The request context.
+    /// </summary>
+    /// <remarks>
+    /// This property should not be set by user code except for testing purposes.
+    /// </remarks>
+    public HttpContext HttpContext
+    {
+        get => _httpContext ?? throw new InvalidOperationException("HttpContext was not initialized");
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:33]:
```suggestion
        get => _httpContext ?? throw new InvalidOperationException("HttpContext was not initialized.");
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 25]
```diff
@@ -0,0 +1,147 @@
...
+        // Public for 3rd party testing of interceptors.
+        // We'd make this a required constructor/init parameter but ObjectPool requires a parameterless constructor.
+        set => _httpContext = value ?? throw new ArgumentNullException(nameof(value));
+    }
+
+    /// <summary>
+    /// What parts of the request and response to log.
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:40]:
```suggestion
    /// Gets or sets what parts of the request and response to log.
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 26]
```diff
@@ -0,0 +1,147 @@
...
+    /// <see cref="HttpLoggingAttribute.ResponseBodyLogLimit"/>, or
+    /// <see cref="HttpLoggingEndpointConventionBuilderExtensions.WithHttpLogging{TBuilder}(TBuilder, HttpLoggingFields, int?, int?)"/>.
+    /// </remarks>
+    public int ResponseBodyLogLimit { get; set; }
+
+    internal long StartTimestamp { get; set; }
+    internal TimeProvider TimeProvider { get; set; } = null!;
+
+    /// <summary>
+    /// Data that will be logged as part of the request or response. Values specified in <see cref="LoggingFields"/>
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:73]:
```suggestion
    /// Gets parameters that will be logged as part of the request or response. Values specified in <see cref="LoggingFields"/>
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 27]
```diff
@@ -0,0 +1,147 @@
...
+    /// <param name="value">The parameter value.</param>
+    public void AddParameter(string key, object? value)
+    {
+        Parameters.Add(new(key, value));
+    }
+
+    /// <summary>
+    /// Adds the given fields to what's currently enabled in <see cref="LoggingFields"/>.
+    /// </summary>
+    /// <param name="fields"></param>
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:92]: Missing

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 28]
```diff
@@ -0,0 +1,147 @@
...
+    /// </summary>
+    public bool IsAnyEnabled(HttpLoggingFields fields)
+    {
+        return (LoggingFields & fields) != HttpLoggingFields.None;
+    }
+
+    /// <summary>
+    /// Removes the given fields from what's currently enabled in <see cref="LoggingFields"/>.
+    /// </summary>
+    /// <param name="fields"></param>
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:109]: Missing

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 29]
```diff
@@ -0,0 +1,147 @@
...
+    public void Enable(HttpLoggingFields fields)
+    {
+        LoggingFields |= fields;
+    }
+
+    /// <summary>
+    /// Checks if any of the given fields are currently enabled in <see cref="LoggingFields"/>.
+    /// </summary>
+    public bool IsAnyEnabled(HttpLoggingFields fields)
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:101]: Missing `<param name="fields">`

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 30]
```diff
@@ -0,0 +1,147 @@
...
+    public void Disable(HttpLoggingFields fields)
+    {
+        LoggingFields &= ~fields;
+    }
+
+    /// <summary>
+    /// Checks if any of the given fields are currently enabled in <see cref="LoggingFields"/>
+    /// and disables them so that a custom log value can be provided instead.
+    /// </summary>
+    /// <param name="fields">One or more field flags to check.</param>
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:119]:
```suggestion
    /// <param name="fields">One or more field flags to disable.</param>
```

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 31]
```diff
@@ -0,0 +1,147 @@
...
+    /// Removes the given fields from what's currently enabled in <see cref="LoggingFields"/>.
+    /// </summary>
+    /// <param name="fields"></param>
+    public void Disable(HttpLoggingFields fields)
+    {
+        LoggingFields &= ~fields;
+    }
+
+    /// <summary>
+    /// Checks if any of the given fields are currently enabled in <see cref="LoggingFields"/>
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:116]: IMO, rewrite the comment to focus on disabling. e.g. "Disable the specified fields if they are enabled."

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 32]
```diff
@@ -144,63 +184,43 @@ private async Task InvokeInternal(HttpContext context)
...
-                    loggableUpgradeFeature = new UpgradeFeatureLoggingDecorator(originalUpgradeFeature, response, options._internalResponseHeaders, loggingFields, _logger);
+                    loggableUpgradeFeature = new UpgradeFeatureLoggingDecorator(originalUpgradeFeature,
+                        logContext, options._internalResponseHeaders, _interceptors, _logger);
 
                     context.Features.Set<IHttpUpgradeFeature>(loggableUpgradeFeature);
                 }
             }
 
-            if (loggingFields.HasFlag(HttpLoggingFields.ResponseBody))
+            if (loggingFields.HasFlag(HttpLoggingFields.ResponseBody) || _interceptors.Length > 0)
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:200]: Why is the response body captured if there is an interceptor? Is there a situation where this wouldn't be wanted?

Add comment?

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 33]
```diff
@@ -0,0 +1,147 @@
...
+
+    internal long StartTimestamp { get; set; }
+    internal TimeProvider TimeProvider { get; set; } = null!;
+
+    /// <summary>
+    /// Data that will be logged as part of the request or response. Values specified in <see cref="LoggingFields"/>
+    /// will be added automatically after all interceptors run. These values are cleared after logging the request.
+    /// All other relevant settings will carry over to the response.
+    /// </summary>
+    public IList<KeyValuePair<string, object?>> Parameters { get; } = new List<KeyValuePair<string, object?>>();
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:77]: Add `InternalParameters` that is an `List<KeyValuePair<string, object?>>`. Internal code can access it to avoid interface overhead.

Then parameters becomes:
```cs
public IList<KeyValuePair<string, object?>> Parameters => InternalParameters;
```

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 34]
```diff
@@ -240,35 +263,56 @@ private static bool NotUpgradeableRequestOrRequestNotUpgraded(UpgradeFeatureLogg
...
         {
-            FilterHeaders(list, response.Headers, allowedResponseHeaders);
+            FilterHeaders(logContext, response.Headers, allowedResponseHeaders);
         }
 
-        if (list.Count > 0)
+        if (logContext.Parameters.Count > 0)
         {
-            var httpResponseLog = new HttpResponseLog(list);
+            var httpResponseLog = new HttpResponseLog((List<KeyValuePair<string, object?>>)logContext.Parameters);
```
Comment (JamesNK) [inline src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:309]:
```suggestion
            var httpResponseLog = new HttpResponseLog(logContext.InternalParameters);
```

File: src/Middleware/HttpLogging/src/HttpLoggingExtensions.cs (hunk 23 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingExtensions.cs:23]: The lack of space was intentional, the status is going to be something like [Truncated], and it will be empty in the common case.

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs (hunk 32 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:200]: The response body isn't captured until after interceptors run, but we need to hook it in advance so that an interceptor can decide to capture the body or not.

File: src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs [hunk 35]
```diff
@@ -0,0 +1,149 @@
...
+    /// </remarks>
+    public int ResponseBodyLogLimit { get; set; }
+
+    internal long StartTimestamp { get; set; }
+    internal TimeProvider TimeProvider { get; set; } = null!;
+    internal List<KeyValuePair<string, object?>> InternalParameters { get; } = new();
+
+    /// <summary>
+    /// Gets a list of parameters that will be logged as part of the request or response. Values specified in <see cref="LoggingFields"/>
+    /// will be added automatically after all interceptors run. These values are cleared after logging the request.
```
Comment (BrennanConroy) [inline src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs:75]: > Values specified in <see cref="LoggingFields"/> will be added automatically after all interceptors run. These values are cleared after logging the request.

This makes it sound like only the parameters added automatically after the interceptor are cleared, not all parameters.

**Review by BrennanConroy — APPROVED** [review]

**Comment by Tratcher** [comment]
I've updated the description to include two recent requirements changes based on feedback from the Extensions folks, CombineLogs and exception handling.

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs (hunk 32 above)
Comment (JamesNK) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:202]: That seems like a limitation of interceptors. Someone might want to redact fields with an interceptor, but an interceptor forces the body to be captured which can have a big performance overhead.

Have you considered a property on the interceptor interface to control whether the body is captured? `bool CanCaptureResponseBody` or `bool SuppressCaptureResponseBody`

Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:202]: We're not always capturing the response body, we're only shimming it so we can see when it starts and make the decision to capture it. This should not cause significant overhead.

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs [hunk 36]
```diff
@@ -111,49 +100,103 @@ private void CommonWrite(ReadOnlySpan<byte> span)
...
     {
-        OnFirstWrite();
-        return base.FlushAsync(cancellationToken);
+        await OnFirstWriteAsync();
+        await base.FlushAsync(cancellationToken);
+    }
+
+    public void LogResponseBody(double? duration)
+    {
+        if (_logBody)
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:180]: To be honest I haven't quite read the code for this class so I may be wrong, but by having this if statement does it mean that the `duration` get logged only if the response has a body?

Comment (Tratcher) [reply src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:180]: You're right. I just pushed a change to simplify how Duration is logged. E.g. it only happens once at the end of the response, and I don't combine it with the response body or headers.

File: src/Middleware/HttpLogging/src/HttpLog.cs [hunk 37]
```diff
@@ -6,16 +6,18 @@
...
     private string? _cachedToString;
 
-    internal static readonly Func<object, Exception?, string> Callback = (state, exception) => ((HttpRequestLog)state).ToString();
+    internal static readonly Func<object, Exception?, string> Callback = (state, exception) => ((HttpLog)state).ToString();
 
-    public HttpRequestLog(List<KeyValuePair<string, object?>> keyValues)
+    public HttpLog(List<KeyValuePair<string, object?>> keyValues, string title)
     {
         _keyValues = keyValues;
+        _title = title;
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/HttpLog.cs:20]: Does this `title` need to be returned in the `KeyValuePair` list too?

File: src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs [hunk 38]
```diff
@@ -50,88 +54,125 @@ public Task Invoke(HttpContext context)
...
-                }
-                else
-                {
-                    _logger.UnrecognizedMediaType("request");
-                }
-            }
+                _logger.RequestLog(httpRequestLog);
 
-            var httpRequestLog = new HttpRequestLog(list);
+                logContext.InternalParameters.Clear();
```
Comment (Kahbazi) [inline src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:149]: Based on the last commit, should this line be deleted?
https://github.com/dotnet/aspnetcore/blob/40e35f03e7410a7053d6d12570d9a7cbf78ac249/src/Middleware/HttpLogging/src/HttpLoggingInterceptorContext.cs#L141-L142

Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs:149]: Good catch

File: src/Middleware/HttpLogging/src/HttpLog.cs (hunk 37 above)
Comment (Tratcher) [reply src/Middleware/HttpLogging/src/HttpLog.cs:20]: No, if you're only consuming the KVP's then you can get the title from the event id.

**Comment by Tratcher** [comment]
@wtgodbe ready to merge.
