### PR TITLE
if actual bytes to be written is negative, set to zero

### LINKED ISSUE #47452: Decreasing the window size below the amount of data sent can prematurely abort the connection
The following error can occur in specific scenarios if the server has sent some data on a stream and the client updates the window size to some value below the amount already sent
```
Microsoft.AspNetCore.Server.Kestrel.Http2 Critical: The event loop in connection 0HMP8EQDO1NJO failed unexpectedly.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
    at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
    at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2FrameWriter.WriteToOutputPipe() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:line 139
```

### Method 1
For example, if the server sends 2 bytes with an initial window size of 3, then the client updates the window to be 1. The server will successfully have scheduled a new item to the output loop for processing:
https://github.com/dotnet/aspnetcore/blob/7aca30363667b13f80aae816dc9924de54284569/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L312-L314
But before it starts processing the item in
https://github.com/dotnet/aspnetcore/blob/c93d0d013b8f9e7baf2ae03fcc2fcade78687385/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L111-L117
The updated Window can be processed:
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L891-L897
Which will decrease the `_streamWindow` to a negative value, which will then fail the buffer slice at
https://github.com/dotnet/aspnetcore/blob/c93d0d013b8f9e7baf2ae03fcc2fcade78687385/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L131-L139

--------

### Method 2
Another way this can be hit is if `Stop` is called once the `_streamWindow` is negative, even if nothing has been scheduled yet, because it will call `Schedule` itself without any checks for `_streamWindow`
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L566-L583

--------

### Method 3
Doing multiple writes can also cause this, if the window update happens after the first write, but before the second one (or if it happens during the race between starting to process the second write and reading the settings as described in method 1).
This path also calls `Schedule` without a check for `_streamWindow`.
https://github.com/dotnet/aspnetcore/blob/ff6c5e7e3bc0a6cb9a033c9a295e1225a1065939/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L388-L407

---------

This following test will hit the issue in either the `Stop` path described in method 2 or the multi write path described in method 3.
```csharp
[Fact]
public async Task DecreaseWindowBelowCurrentSentAmount()
{
    const int windowSize = 3;
    _clientSettings.InitialWindowSize = windowSize;

    var tcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

    await InitializeConnectionAsync(async context =>
    {
        var bodyControlFeature = context.Features.Get<IHttpBodyControlFeature>();
        bodyControlFeature.AllowSynchronousIO = true;
        await context.Response.Body.WriteAsync(new byte[windowSize - 1], 0, windowSize - 1);
        await tcs.Task;
        context.Response.Body.Write(new byte[windowSize], 0, windowSize);
    });

    await StartStreamAsync(1, _browserRequestHeaders, endStream: true);

    await ExpectAsync(Http2FrameType.HEADERS,
        withLength: 32,
        withFlags: (byte)Http2HeadersFrameFlags.END_HEADERS,
        withStreamId: 1);

    // Decrease window size after server has already sent the current window - 1 size of data
    _clientSettings.InitialWindowSize = windowSize - 2;
    await SendSettingsAsync();

    await ExpectAsync(Http2FrameType.DATA,
        withLength: windowSize - 1,
        withFlags: (byte)Http2DataFrameFlags.NONE,
        withStreamId: 1);

    await ExpectAsync(Http2FrameType.SETTINGS,
        withLength: 0,
        withFlags: (byte)Http2DataFrameFlags.END_STREAM,
        withStreamId: 0);

    tcs.SetResult();

    await StopConnectionAsync(expectedLastStreamId: 1, ignoreNonGoAwayFrames: false);
}
```

### PR DESCRIPTION
**Pull request by bhaskarqlik**
# if actual bytes to be written is negative, set to zero

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Fixes [#47452](https://github.com/dotnet/aspnetcore/issues/47452)

When actual is zero, it will wait for stream window update.

### CODE REVIEW

**Comment by bhaskarqlik** [comment]
@dotnet-policy-service agree company="Qlik"

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 1]
```diff
@@ -198,6 +198,12 @@ private async Task WriteToOutputPipe()
                     // Now check the connection window
                     actual = CheckConnectionWindow(actual);
 
+                    // reset to zero, if negative
+                    if (actual < 0)
```
Comment (mgravell) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:202]: This does seem to fix it; it *feels* like we're powering over the real problem, though - like one of the values used in either CheckStreamWindow or CheckConnctionWindow is already at a value we should have clamped. Maybe I'm overthinking... I tend to do that, and this has the advantage of simplicity

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:202]: I vaguely recall that the spec allows the window size to go negative.  I do think it might be helpful to include a comment about when that can happen.

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:202]: Do we actually want to continue if it's negative/zero or should we short-circuit something?

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 2]
```diff
@@ -198,7 +198,9 @@ private async Task WriteToOutputPipe()
                     // Now check the connection window
                     actual = CheckConnectionWindow(actual);
 
-                    // reset to zero, if negative
+                    // actual is negative means window size has become negative
+                    // this can usually happen if the receiver decreases window size before receiving the previous data frame
+                    // in this case, reset to 0 and continue, no data will be set but will wait for window update
```
Comment (mgravell) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:203]: 👍 ; is "set" here "sent"?

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs (hunk 1 above)
Comment (bhaskarqlik) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:204]: @amcasey yes, when the window size becomes we (sender) should wait for window update from the receiver, by continuing the code flow will mark as waiting for window updates, as there are still more data to be written. This will also handle the case if the receiver aborts the connection without sending window update.
Added inline comment to describe the change

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:204]: Crucially, we're only setting a local to 0, right?  Not our actual window size state?

Comment (bhaskarqlik) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:204]: yes, that's correct, only the local is set to 0
the actual window size remains negative

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs [hunk 3]
```diff
@@ -198,6 +198,14 @@ private async Task WriteToOutputPipe()
                     // Now check the connection window
                     actual = CheckConnectionWindow(actual);
 
+                    // actual is negative means window size has become negative
+                    // this can usually happen if the receiver decreases window size before receiving the previous data frame
+                    // in this case, reset to 0 and continue, no data will be sent but will wait for window update
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:203]:
```suggestion
                    // in this case, reset to 0 and continue, no data will be sent but will wait for window update
                    // RFC 9113 section 6.9.2 specifically calls out that the window size can go negative.  As required,
                    // we continue to track the negative value but use 0 for the remainder of this write to avoid 
                    // out-of-range errors.
```

**Review by amcasey — APPROVED** [review]
I added a suggestion for a more detailed comment, but I don't feel strongly about it - feel free to ignore it if it's too much.

**Comment by amcasey** [comment]
Any remaining concerns @mgravell?

**Comment by bhaskarqlik** [comment]
@amcasey thanks for merging this
can we also back port this fix to 8.x release, let me know if I need to create a PR for it.

**Comment by amcasey** [comment]
@BrennanConroy @adityamandaleeka to consider for backporting

**Comment by Krish-1469** [comment]
> @BrennanConroy @adityamandaleeka to consider for backporting

Hi, 
We are also facing this issue with 8.0 , Can you please let us know when it is planned to be merged to 8.0 and to be released.

Thanks

**Comment by mgravell** [comment]
Backport isn't an automatic / "given"; however, the change is small, reasonably safe, and doesn't involve API, so it isn't a hard "no" either, and there's multiple people requesting it. I'll raise it with the team.
