### PR TITLE
Override base implementations of WriteLineAsync in HttpResponseStreamWriter

### LINKED ISSUE #38210: HttpResponseStreamWriter should override TextWriter.WriteLineAsync(string)
### Describe the bug

We have code generating a large response using a `TextWriter` which is an instance of `HttpResponseStreamWriter`. When the response gets large enough, the code starts failing with the following error:

```
Exception Type: System.InvalidOperationException
Error message: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(String value)
at <OUR CODE>
```

Interestingly, our code is failing on the following line:

```
await writer.WriteLineAsync($"...");
```

Digging in deeper, it seems like this fails because `HttpResponseStreamWriter` overrides `TextWriter.WriteLineAsync(ReadOnlyMemory<char>, CancellationToken)` and `TextWriter.WriteAsync(string)` but not `TextWriter.WriteLineAsync(string)`. It is missing a few other async overloads as well.

This feels like an oversight; it makes it difficult to properly use the `HttpResponseStreamWriter` for async writes because `WriteLineAsync(string)` is a gotcha.

### To Reproduce

Create a controller with the following endpoint:

		[HttpGet("repro")]
		public async Task<IActionResult> Repro()
		{
			await using var writer = new HttpResponseStreamWriter(this.Response.Body, Encoding.UTF8);
			await writer.WriteAsync(DateTime.Now.ToString());
			await writer.WriteLineAsync(new string('a', 20000)); // fails
                        // await writer.WriteLineAsync(new string('a', 20000).AsMemory()); // works
			return this.Ok();
		}

### Exceptions (if any)
```
Exception Type: System.InvalidOperationException
Error message: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternal(Boolean flushEncoder)
at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(String value)
at System.IO.TextWriter.WriteLine(String value)
at System.IO.TextWriter.<>c.<WriteLineAsync>b__65_0(Object state)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Further technical details
- ASP.NET Core version: 5
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2019
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

### PR DESCRIPTION
**Pull request by david-acker**
## Description

Currently, `HttpResponseStreamWriter` uses the base implementation for `WriteLineAsync(string)` inherited from `TextWriter`. However, this base implementation apparently makes use of some synchronous operations. 

As a result, when attempting to write a long string (~20,000+ characters) to an `HttpResponse` body with `HttpResponseStreamWriter.WriteLineAsync(string)`, a `System.InvalidOperationException` will be thrown unexpectedly due to the synchronous operations used in the base implementation. This PR adds a fully asynchronous override for `WriteLineAsync(string)` to address this issue.

Fixes #38210

### CODE REVIEW

**Comment by Tratcher** [comment]
So far so good. It looks like there are several overloads of WriteLineAsync that have a similar problem:
https://github.com/dotnet/runtime/blob/44387608aa85ed8ff5e08d3263ec14aab17c91f7/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs#L592-L604
https://github.com/dotnet/runtime/blob/44387608aa85ed8ff5e08d3263ec14aab17c91f7/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs#L639-L644

Can you test those as well?

**Comment by david-acker** [comment]
Will do!

File: src/Http/WebUtilities/src/HttpResponseStreamWriter.cs [hunk 1]
```diff
@@ -419,6 +419,107 @@ private async Task WriteLineAsyncAwaited(ReadOnlyMemory<char> value)
...
+        else
+        {
+            return WriteAsyncAwaited(values, index, count);
+        }
+    }
+
+    private async Task WriteLineAsyncAwaited(char[] values, int index, int count)
+    {
+        await WriteLineAsync(values, index, count);
+        await WriteLineAsync(NewLine);
```
Comment (Kahbazi) [inline src/Http/WebUtilities/src/HttpResponseStreamWriter.cs:454]: Is `WriteLineAsync` correct here!?
```suggestion
        await WriteAsync(values, index, count);
        await WriteAsync(NewLine);
```

Comment (Kahbazi) [inline src/Http/WebUtilities/src/HttpResponseStreamWriter.cs:454]: Is `WriteLineAsync` correct here!?
```suggestion
        await WriteAsync(values, index, count);
        await WriteAsync(NewLine);
```

Comment (david-acker) [reply src/Http/WebUtilities/src/HttpResponseStreamWriter.cs]: Ah, yeah that's incorrect. It should be `WriteAsync`.

**Comment by Tratcher** [comment]
Interesting build error. `src/Http/WebUtilities/src/HttpResponseStreamWriter.cs(385,26): error RS0027: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'WriteLineAsync' violates the backcompat requirement: 'Public API with optional parameter(s) should have the most parameters amongst its public overloads'. See 'https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md' for details.`

Since it's an override, I think that should be suppressed like WriteAsync does:
https://github.com/dotnet/aspnetcore/blob/0ff49cbe9f7caa5960f4e1d5abc39b50855c1cdd/src/Http/WebUtilities/src/HttpResponseStreamWriter.cs#L333-L334

**Review by Tratcher — APPROVED** [review]

**Review by Tratcher — APPROVED** [review]

**Comment by david-acker** [comment]
Fixed one spot where `WriteAsyncAwaited` was being called instead of `WriteLineAsyncAwaited` and added index and count arguments the char array overload tests so the correct overload was used.
