### PR TITLE
Avoid capturing the ExecutionContext in the DisconnectListener

### LINKED ISSUE #26128: System.ObjectDisposedException: IFeatureCollection has been disposed.
### Describe the bug
A few .NET Core applications running in the Azure Service Fabric cluster are crashing several times per day with the exception: `System.ObjectDisposedException: IFeatureCollection has been disposed.`

### To Reproduce

Unfortunately, I was not able to reproduce the issue on my machine. I suspect that might be caused by `IHttpContextAccessor` use in a singleton class. I am not capturing the `HttpContext` in a private field, nor using `async void` anywhere. I have ruled out all the bad practices mentioned in the guide by @davidfowl:

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field

### Exceptions (if any)
```
Application: service.exe
CoreCLR Version: 4.700.20.41105
.NET Core Version: 3.1.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Scheme()
   at Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(HttpRequest request)
   at IFBaltics.Hosting.WebHostRequestFiller.Fill(LogEventInfo logEventInfo)
   at Sysmsg.SysmsgLogCommand.Write()
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.HttpSys.DisconnectListener.<>c__DisplayClass7_0.<CreateDisconnectToken>b__0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPtr)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

### Further technical details
- ASP.NET Core version 3.1.8
- 	It was not possible to find any installed .NET Core SDKs
	Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
	  https://aka.ms/dotnet-download

	Host (useful for support):
	  Version: 3.1.8
	  Commit:  9c1330dedd

	.NET Core SDKs installed:
	  No SDKs were found.

	.NET Core runtimes installed:
	  Microsoft.AspNetCore.All 2.1.21 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.App 2.1.21 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 3.1.8 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.NETCore.App 2.1.21 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 3.1.8 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]

	To install additional .NET Core runtimes or SDKs:
	  https://aka.ms/dotnet-download
- Not dependant on the IDE.

### PR DESCRIPTION
**Pull request by davidfowl**
- The execution context is captured today when register for disconnect notifications. This can result in running logic that accesses async locals related to the request after the request has ended. We drop to use lower level APIs instead of the ThreadPoolBoundHandle in this case to avoid the capture (this usually affects logging that tries to capture request information). There's no need to capture the execution context here since the cancellation token already handles it.

Fixes #26128

### CODE REVIEW

File: src/Servers/HttpSys/src/NativeInterop/DisconnectListener.cs [hunk 1]
```diff
@@ -59,35 +56,39 @@ private ConnectionCancellation GetCreatedConnectionCancellation(ulong connection
...
-                (errorCode, numBytes, overlappedPtr) =>
+            var overlapped = new Overlapped
+            {
+                OffsetHigh = 0,
+                OffsetLow = 0
+            };
+
+            // We're not using boundHandle.AllocateNativeOverlapped here because we want to avoid capturing the ExecutionContext (see https://github.com/dotnet/runtime/issues/42549)
+            // Instead, we're going to use lower level APIs to get access to UnsafePack (which avoids the capture)
+            var nativeOverlapped = overlapped.UnsafePack((errorCode, numBytes, pOverlapped) =>
```
Comment (halter73) [inline src/Servers/HttpSys/src/NativeInterop/DisconnectListener.cs:73]: Can we add a version of SafeNativeOverlapped that doesn't take a ThreadPoolBoundHandle and instead just calls Overlapped.Free? It would feel safer given this was managed by a SafeHandle previously and the lifetime isn't super obvious.

Comment (davidfowl) [reply src/Servers/HttpSys/src/NativeInterop/DisconnectListener.cs:73]: Maybe in the backport but I don't think in 6.0. I'm actually not convinced we should be using safe handle here anyways.

**Review by Tratcher — APPROVED** [review]
This change is going to need targeted stress testing.

File: src/Servers/HttpSys/src/NativeInterop/DisconnectListener.cs (hunk 1 above)
Comment (davidfowl) [reply src/Servers/HttpSys/src/NativeInterop/DisconnectListener.cs:73]: I also feel pretty confident about this change mostly because we don't call dispose on the safe handle outside of this code.
