### PR TITLE
Make RedirectRule honor specified scheme

### LINKED ISSUE #41707: RedirectRule not respecting configured scheme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `Microsoft.AspNetCore.Rewrite` to configure a Redirect, the scheme configured in the redirect is ignored and replaced with the scheme that was used for the original request.  For example, a redirect rule to `http://www.example.com` will actually redirect to `https://www.example.com` if your endpoint was served over HTTPS, while a redirect rule to `https://www.example.com` will actually redirect to `http://www.example.com` if your endpoint was served over HTTP.

This was a breaking change for us on moving from .NET Core 3.1 to .NET 6.

The behaviour occurs at line 100 of [RedirectRule](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Rewrite/src/RedirectRule.cs), and appears to have been introduced in [this commit](https://github.com/dotnet/aspnetcore/commit/12a4ff6624bc00c1f551d4646a4f0a1c03fc401b) of 21st April 2021.

### Expected Behavior

The scheme configured in the redirect should be respected, as in .NET Core 3.1, to continue to allow redirects to URLs with a different scheme to the receiving endpoint.

### Steps To Reproduce

In ASP.NET Core middleware configuration/start-up (e.g. on the vanilla ASP.NET Core Web API template in Visual Studio):

```
var options = new RewriteOptions().AddRedirect("test", "http://www.example.com");
app.UseRewriter(options);
```

Now, when running locally over HTTPS, send a request to `https://localhost:[port]/test`.  An HTTP 302 is returned with the header `location: https://www.example.com`, despite the configuration.

Equivalently, replace `http://www.example.com` in the configuration with `https://www.example.com` and access over HTTP at `http://localhost:[port]/test`.  An HTTP 302 is returned with the header `location: http://www.example.com`, despite the configuration.

### Exceptions (if any)

_No response_

### .NET Version

6.0.203

### Anything else?

ASP.NET Core runtime version 6.0.5.

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix #41707

https://github.com/dotnet/aspnetcore/pull/28903 introduced a behavioral change in `RedirectRule` where the scheme used in a redirected request overrides the one specified in the redirect configuration.

This fixes that so we now honor the scheme specified in the redirect if there is one.

### CODE REVIEW

**Comment by ADBailey** [comment]
Looks good to me.  Thanks for the fast response and saving me the time to submit a pull request myself. :-)

File: src/Middleware/Rewrite/src/RedirectRule.cs [hunk 1]
```diff
@@ -97,7 +99,7 @@ public void ApplyRule(RewriteContext context)
                 }
 
                 encodedPath = host.HasValue
-                    ? UriHelper.BuildAbsolute(request.Scheme, host, pathBase, resolvedPath, resolvedQuery, default)
+                    ? UriHelper.BuildAbsolute(scheme ?? request.Scheme, host, pathBase, resolvedPath, resolvedQuery, default)
```
Comment (Tratcher) [inline src/Middleware/Rewrite/src/RedirectRule.cs:102]:
```suggestion
                    ? UriHelper.BuildAbsolute(scheme, host, pathBase, resolvedPath, resolvedQuery, default)
```

**Review by Tratcher — APPROVED** [review]

**Review by halter73 — APPROVED** [review]
