### PR TITLE
Return 400 bad request when IOException is thrown when ready form.

### LINKED ISSUE #47525: [Minimal API] Incorrect response when request body is too large
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using .NET 7.0.4 and I'm trying to change the `MaxRequestBodySize` property in Kestrel:

    var builder = WebApplication.CreateBuilder(args);
    
    builder.WebHost.ConfigureKestrel(options =>
    {
        options.Limits.MaxRequestBodySize = 1024;
    });

With this setting, if I use a classic Controller like this:

    [ApiController]
    [Route("api/[controller]")]
    [Produces(MediaTypeNames.Application.Json)]
    public class UploadController : ControllerBase
    {
        [HttpPost("with_controller")]
        public IActionResult Upload(IFormFile file) => NoContent();
    }

When I try to upload a file larger that 1024 bytes, I obtain the following error:

    {
      "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
      "title": "One or more validation errors occurred.",
      "status": 400,
      "traceId": "00-5392ad98781087812b2bba29374a2a21-ce7ed0cde6248257-00",
      "errors": {
        "": [
          "Failed to read the request form. Request body too large. The max request body size is 1024 bytes."
        ]
      }
    }

However, if I use a Minimal API endpoint:

`app.MapPost("api/upload/with_minimalapi", (IFormFile file) => TypedResults.NoContent());`

And try to upload the same file that excedees 1024 bytes, I obtain a 200 OK response:

image

### Expected Behavior

The Minimal API endpoint should return a 400 Bad Request response, like the Controller.

### Steps To Reproduce

Minimal repro: https://github.com/marcominerva/UploadMaxSizeIssue

### Exceptions (if any)

_No response_

### .NET Version

7.0.202

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mitchdenny**
Fixes https://github.com/dotnet/aspnetcore/issues/47525

Currently if someone uploads a file and that file exceeds what is specified in `KestrelServerOptions` an `IOException` will be thrown when we attempt to read from the HTTP stream. However, the request delegate that we produce silently swallows this and results in the HTTP response being 200 which is obviously problematic.

This change tweaks the logic such that if an `IOException` is raised, it is returned as a 400 bad request. This PR addresses the issue linked above, but we probably need to satisfy ourselves that this is the correct response. Some questions:

Is 400 the right response here? Would it make more sense to throw a more specific exception out of Kestrel (and other servers) and return a 413?

Somewhat related, when FormOptions is specified, we can specify a maximum body size for the form, when we do that we get a 400 error - should this be a 413 instead also?

```
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to read parameter "IFormFile file" from the request body as form.
 ---> System.IO.InvalidDataException: Multipart body length limit 50 exceeded.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read) in C:\Code\dotnet\aspnetcore\src\Http\WebUtilities\src\MultipartReaderStream.cs:line 150
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in C:\Code\dotnet\aspnetcore\src\Http\WebUtilities\src\MultipartReaderStream.cs:line 238
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in C:\Code\dotnet\aspnetcore\src\Http\WebUtilities\src\FileBufferingReadStream.cs:line 344
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken) in C:\Code\dotnet\aspnetcore\src\Http\WebUtilities\src\StreamHelperExtensions.cs:line 62
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken) in C:\Code\dotnet\aspnetcore\src\Http\Http\src\Features\FormFeature.cs:line 206
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<HandleRequestBodyAndCompileRequestDelegateForForm>g__TryReadFormAsync|96_0(HttpContext httpContext, String parameterTypeName, String parameterName, Boolean throwOnBadRequest) in C:\Code\dotnet\aspnetcore\src\Http\Http.Extensions\src\RequestDelegateFactory.cs:line 1420
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.InvalidFormRequestBody(HttpContext httpContext, String parameterTypeName, String parameterName, Exception exception, Boolean shouldThrow) in C:\Code\dotnet\aspnetcore\src\Http\Http.Extensions\src\RequestDelegateFactory.cs:line 2468
```

### CODE REVIEW

**Comment by Tratcher** [comment]
> Is 400 the right response here? Would it make more sense to throw a more specific exception out of Kestrel (and other servers) and return a 413?

The actual exception is a BadHttpRequestException : IOException right? That includes a status code you can set on the response.

For other IOExceptions, 400 seems fine.

> Somewhat related, when FormOptions is specified, we can specify a maximum body size for the form, when we do that we get a 400 error - should this be a 413 instead also?

The InvalidDataException could be thrown for several reasons, not just size issues. If we wanted to communicate more information we'd have to put it into the IDE's data collection, or make a new derived exception.

**Comment by captainsafia** [comment]
> The actual exception is a BadHttpRequestException : IOException right? That includes a status code you can set on the response.

This particular codepath doesn't use a `BadHttpRequestException` since it handles `IOExceptions` emitted during exception process which abort request handling instead of indicating that the response itself that was read isn't valid.

@mitchdenny's recommendation here:

>  Would it make more sense to throw a more specific exception out of Kestrel (and other servers) and return a 413?

would allow us to return a 4xx style error for the specific case where the IOException was triggered because it didn't match the constraints set in the Kestrel config.

As to the general question of whether we should throw more specific exceptions from the underlying APIs (Kestrel/form-processing) and return 413s, I worry that the cost of additional APIs/logic in the underlying layer might not be worth the benefit.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -1308,6 +1308,7 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
                 catch (IOException ex)
```
Comment (Tratcher) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1308]: Discussed offline w/Safia. You should be able to add another catch block here for BadHttpRequestException and use the StatusCode it provides.

Comment (mitchdenny) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1308]: Thought this might be where we land. I'll make the change.

**Comment by mitchdenny** [comment]
@captainsafia @Tratcher updated PR to handle BadHttpRequestException specifically AND use the status code stored on the exception. For now, I'm filtering the exception for just the 413 scenarios as I'd like to be able to backport this change if possible since I think this bug represents a possible data loss scenario for folks - hence being as conservative as possible.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 2]
```diff
@@ -1305,6 +1305,12 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
...
                 }
+                catch (BadHttpRequestException ex) when (ex.StatusCode == StatusCodes.Status413RequestEntityTooLarge)
+                {
+                    Log.RequestBodyIOException(httpContext, ex);
+                    httpContext.Response.StatusCode = ex.StatusCode;
+                    return (null, false);
+                }
                 catch (IOException ex)
                 {
                     Log.RequestBodyIOException(httpContext, ex);
```
Comment (Tratcher) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1316]: IOException should still set a non-default status code like if it's not going to be propagated, otherwise there are probably similar ways to hit the same issue.

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 3]
```diff
@@ -1305,6 +1305,12 @@ private static Expression AddResponseWritingToMethodCall(Expression methodCall,
                 {
                     bodyValue = await httpContext.Request.ReadFromJsonAsync(jsonTypeInfo);
                 }
+                catch (BadHttpRequestException ex) when (ex.StatusCode == StatusCodes.Status413RequestEntityTooLarge)
```
Comment (Tratcher) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1308]: I understand wanting to be conservative in servicing, but this seems overkill. We trust the exceptions thrown by the server or we don't, that shouldn't vary by status code.

Comment (captainsafia) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:1308]: > We trust the exceptions thrown by the server or we don't, that shouldn't vary by status code.

This is a valid point. I was definitely cautious about changing the response behavior for a large swath of exception scenarios but it's valid that RDF shouldn't be setting status codes differently from what Kestrel is doing.

Comment (mitchdenny) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs]: Updated based on feedback. Minor thought on style ... thoughts on doing something like this in the existing catch block:

```csharp
httpContext.Response.StatusCode = ex is BadHttpRequestException bad ? bad.StatusCode : StatusCodes.Status400BadRequest;
```

My instinct is no -- even though the code is a bit repetitive I think its clearer.

**Review by captainsafia — APPROVED** [review]
LGTM pending the IDE2000 fix.
