### PR TITLE
Fixed rendering of self closing elements

### LINKED ISSUE #46183: [Blazor] InputText component renders invalid html
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The default blazor component [InputText](https://github.com/dotnet/aspnetcore/blob/cbb4916ecc63785267a750a78b42f3a769230509/src/Components/Web/src/Forms/InputText.cs) is rendered as ``<input id="test"></input>``, which is invalid html according to specification, as ``<input>`` is a void element. It must not have a closing tag.

### Expected Behavior

Output html should be valid according to W3C specification, thus the generated tag should be ``<input id="test">``.

### Steps To Reproduce

A minimum working example can be found here: https://github.com/janbensch/InputTest. It was created by using the default template for a Blazor server application, provided in Visual Studio 17.4.4 with .NET 7. The lone changes were done in the file Index.razor by adding the InputText component. Everything else was generated by Visual Studio by default.

### Exceptions (if any)

_No response_

### .NET Version

7.0.102

### Anything else?

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.307 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fixed rendering of self closing elements

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Self closing elements were rendering incorrectly.
Example `<input value=""some value"></input>` but should be `<input value=""some value" />`

Fixes #46183

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Could you add a test case to show what happen if there's a supposedly self-closing element but somebody *does* supply child content for it? For example, `<meta>Something</meta>`. I'm concerned the updated logic might produce something malformed like `<meta>Something />`. I know that would not be a 100% HTML-compliant scenario but HTML is pretty forgiving so people might do this, and we don't want to produce malformed markup in any scenario.

I think the rule should be something like: elements are rendered as self-closing if they are in `SelfClosingElements` *and* no child content was rendered.

The previous logic tried to account for that but it looks like the bug is that it failed to account for `ElementReferenceCapture` frames (let me know if I'm misreading this). If that is the case, an alternative would be just to change `RenderAttributes` so that it skips `ElementReferenceCapture` as if they are no-op frames. Then the `remainingElements` value would be zero for `InputText` and it would correctly render as self-closing.

If you prefer to keep your approach to solving this that's totally fine with me, but we should allow for the case where child content is supplied.

Of course, I might be misreading any of this so please let me know if I've got this wrong.

File: src/Mvc/Mvc.ViewFeatures/src/RazorComponents/HtmlRenderer.cs [hunk 1]
```diff
@@ -228,6 +228,12 @@ private int RenderChildren(HtmlRenderingContext context, ArrayRange<RenderTreeFr
         {
             var candidateIndex = position + i;
             ref var frame = ref frames.Array[candidateIndex];
+
+            if (frame.FrameType == RenderTreeFrameType.ElementReferenceCapture)
```
Comment (SteveSandersonMS) [inline src/Mvc/Mvc.ViewFeatures/src/RazorComponents/HtmlRenderer.cs:232]: Could we move this check inside the branch below? That is, we only need to check if it's `ElementReferenceCapture` once we've already observed that it's *not* `RenderTreeFrameType.Attribute`. Then no extra checks will occur on most cycles.

**Review by SteveSandersonMS — APPROVED** [review]
Great!
