### PR TITLE
Use Array.Empty for parameterless filters

### LINKED ISSUE #41705: Filters that don't have any parameters shouldn't allocate an empty array
We should be using `Array.Empty<object>()` in this situation.

```C#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => {    });
.AddFilter((context, next) =>
{
    return next(context);
});

app.Run();
```

image

|Type|Allocations|Bytes|Average Size \(Bytes\)|
|-|-|-|-|
| + System.Object\[\]|21,987|667,536|30.36|
|\| - System.Object\[0\]|21,003|504,072|24|

|Function Name|Allocations|Bytes|Module Name|
|-|-|-|-|
| + dynamicClass.lambda\_method2\(00007FFA03556EC0, object, 00007FFA03071310\)|21,001|504,024|anonymously hosted dynamicmethods assembly|
|\| + Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke\(Microsoft.AspNetCore.Http.HttpContext\)|21,001|504,024|microsoft.aspnetcore.routing.il|
|\|\| + Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke\(Microsoft.AspNetCore.Http.HttpContext\)|21,001|504,024|microsoft.aspnetcore.routing.il|
|\|\|\| + Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke\(\)|21,001|504,024|microsoft.aspnetcore.diagnostics.il|
|\|\|\|\| + System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start\<T\>\(T\)|21,001|504,024|System.Private.CoreLib.il|
|\|\|\|\|\| + Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke\(Microsoft.AspNetCore.Http.HttpContext\)|21,001|504,024|microsoft.aspnetcore.diagnostics.il|

cc @captainsafia

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/41705

**Validation**

```csharp
app.MapGet("/", () => "Look ma! No params.")
    .AddFilter((c, n) => n(c));
```

```ps
> 1..1000 | % { curl http://localhost:5000 }
```
**Before Change**
|Type|Allocations|
|-|-|
| + System.Object\[\]|1,698|
|\| - System.Object\[0\]|1,003|

**After Change**
|Type|Allocations|
|-|-|
| + System.Object\[\]|702|
|\| - System.Object\[0\]|2|

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -388,9 +389,12 @@ private static Expression CreateRouteHandlerInvocationContextBase(FactoryContext
         // In the event that a constructor matching the arity of the
         // provided parameters is not found, we fall back to using the
         // non-generic implementation of RouteHandlerInvocationContext.
+        Expression paramArray = factoryContext.BoxedArgs.Length > 0
+            ? Expression.NewArrayInit(typeof(object), factoryContext.BoxedArgs)
+            : Expression.Call(ArrayEmptyMethod.MakeGenericMethod(new Type[] { typeof(object) }));
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:394]: Shouldn't MakeGenericMethod be hoisted to the stored MethodInfo so we use the same one for every filter factory?
