### PR TITLE
Fix radio button reset after submitting enhanced form

### LINKED ISSUE #51429: Radio button checked property not reset after enhanced form request
Repro steps:

- Create a Blazor Web App
- In Home.razor add:

```html
<form data-enhance>
    <input type="radio" />
    <button>Submit</button>
</form>
```

- Select the radio button and then submit the form

Expected result: The radio button is not selected after the form is submitted.
Actual result: The radio button is still selected.
Workaround: Remove `data-enhance` to make the form request no longer enhanced.

For comparison, if you change the input type to checkbox and do the same test, the checkbox does get unselected after submitting the form even with enhanced form handling enabled.

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fix radio button reset after submitting enhanced form

## Description
This PR fixes resetting radio button checked property after submitting an enhanced form.

```html
<form data-enhance>
    <input type="radio" />
    <button>Submit</button>
</form>
```
Workaround is to remove `data-enhance` attribute.

Fixes #51429

## Customer Impact

Without this change customers will have bad experience using enhanced form that contains radio button. Radio button won't get reset after submitting the form.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This is a minor change. We have similar logic for checkbox approved  https://github.com/dotnet/aspnetcore/pull/50991. There are unit and e2e tests for this change.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 1]
```diff
@@ -140,6 +140,7 @@ function onDocumentSubmit(event: SubmitEvent) {
     }
 
     performEnhancedPageLoad(url.toString(), /* interceptedLink */ false, fetchOptions);
+    formElem.reset();
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:143]: This is very different from the kind of solution I was expecting, and TBH am not sure if it's valid. Doesn't this cause the form to instantly revert to its default state? If so that would be a bug, as it would flash back to being blank while the async form submission is in process. And if the POST request fails, the entire form state would be lost.

The approach I was expecting was to add another case to the DOM sync logic in https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/DomMerging/DomSync.ts. There's already a special case for checkboxes at https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/DomMerging/DomSync.ts#L351, so my guess (which I haven't verified and could be wrong) is that a similar special case is needed for radio buttons.

There's a unit test for checkboxes at https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/test/DomSync.test.ts#L472, so hopefully it would be possible to create an equivalent test for radio buttons, showing that it fails with the existing implementation but passes after updating the `DomSync.ts` logic.

This approach avoids resetting the form completely and hence won't discard the user's data from the DOM.

File: src/Components/Web.JS/test/DomSync.test.ts [hunk 2]
```diff
@@ -485,6 +485,22 @@ describe('DomSync', () => {
     expect(checkboxElem.value).toBe('second');
   });
 
+  test('should handle radio buttons with value attribute', () => {
+    // Checkboxes require even more special-case handling because their 'value' attribute
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/test/DomSync.test.ts:489]:
```suggestion
    // Radio buttons require even more special-case handling because their 'value' attribute
```

File: src/Components/Web.JS/src/Rendering/DomMerging/DomSync.ts [hunk 3]
```diff
@@ -354,11 +354,11 @@ function ensureEditableValueSynchronized(destination: Element, value: any) {
   } else if (destination instanceof HTMLSelectElement && destination.selectedIndex !== value) {
     destination.selectedIndex = value as number;
   } else if (destination instanceof HTMLInputElement) {
-    if (destination.type === 'checkbox') {
+    if (destination.type === 'checkbox' || destination.type === 'radio') {
       if (destination.checked !== value) {
         destination.checked = value as boolean;
       }
-    } else if (destination.value !== value) {
+    }  else if (destination.value !== value) {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Rendering/DomMerging/DomSync.ts:361]:
```suggestion
    } else if (destination.value !== value) {
```

**Review by SteveSandersonMS — APPROVED** [review]
The updated fix looks great!

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts (hunk 1 above)
Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts]: Thank you @SteveSandersonMS !
I investigated further the files you mentioned and found out that the same fix as for checkbox won't work for radio button.
I then tracked where exactly checkbox gets updated value on checked attribute https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/DomMerging/DomSync.ts#L371 and applied same thing for radio button. 
After this change the current bug was fixed, however the bug you mentioned appeared. https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/test/DomSync.test.ts#L472 similar test for radio button was failing. I applied the fix you suggested and everything worked.
Since the logic for resetting checkbox and radio button is the same, I added checkbox to my e2e for enhanced form too.

**Comment by mkArtakMSFT** [comment]
@surayya-MS the reason for this error is described here: https://github.com/dotnet/aspnetcore/pull/36832#issuecomment-961875264
Please follow the instructions there and try it out yourself - should be fixed.

**Comment by AlexKovynev** [comment]
@mkArtakMSFT @surayya-MS maybe cherry-pick?:)

**Comment by surayya-MS** [comment]
@AlexKovynev FYI, the release/8.0 branch has been closed for GA for a while now. These fixes are candidates for the first patch. That is why I didn't hurry to backport them sooner.
