### PR TITLE
ResponseCompression: set Content-Encoding and Vary headers for HEAD requests

### LINKED ISSUE #24844: Different response headers for GET/HEAD when using response compression middleware
### Describe the bug
When response compression middleware is used and a GET/HEAD request is made with Accept-Encoding header set as "gzip", the response to GET request contains the Content-Encoding header with value "gzip" and no Content-Length header but the response to HEAD request contains no Content-Encoding header with Content-Length header value as the uncompressed content length.

### To Reproduce
[Git repo](https://github.com/akashsax14/dotnet_response_comp_bug) for reproducer
1. Run the ASP.NET Core application using ResponseCompBug launch profile
2. Open postman or similar api testing application and make the following requests with Accept-Encoding header as gzip
     - GET https://localhost:5001/api/values
     - HEAD https://localhost:5001/api/values
3. Expect to get same headers for GET and HEAD but are not

### Further technical details
- ASP.NET Core version : 2.2
- Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by alefranz**
Currently the compression related headers are missing for HEAD responses that, correctly, do not include a body, as the middleware emit those headers when working on the body.

This change ensure that those headers are generated even for head request without a response body.

I've played a bit on how to extract the required functionality out of the` OnWrite` method and this looked like the cleaner approach that also limited the size of the change.

Fixes #24844

@Tratcher I've followed your suggestion on the issue on where to insert the logic

### CODE REVIEW

File: src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs [hunk 1]
```diff
@@ -232,40 +238,49 @@ public override async Task WriteAsync(byte[] buffer, int offset, int count, Canc
             }
         }
 
-        private void OnWrite()
+        private void InitializeCompression()
```
Comment (Tratcher) [inline src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:241]:
```suggestion
        private void InitializeCompressionHeaders()
```
To clarify this doesn't set up the body.

File: src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs [hunk 2]
```diff
@@ -59,6 +59,12 @@ internal async Task FinishCompressionAsync()
             {
                 await _compressionStream.DisposeAsync();
             }
+
+            // Adds the compression headers for HEAD requests even if the body was not used.
+            if (HttpMethods.IsHead(_context.Request.Method) && !_compressionChecked)
```
Comment (Tratcher) [inline src/Middleware/ResponseCompression/src/ResponseCompressionBody.cs:64]: Since most responses will have a body and set _compressionChecked, it's better to check that condition first.
```suggestion
            if (!_compressionChecked && HttpMethods.IsHead(_context.Request.Method))
```

**Review by Tratcher — COMMENTED** [review]
Only minor comments.

**Comment by alefranz** [comment]
Thanks @Tratcher , nice suggestions!
I've updated it.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks
