### PR TITLE
Resolve change token leak in Blazor hot reload

### LINKED ISSUE #52757: Hot reload becomes very slow with dotnet watch and Blazor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm making a Blazor app with .NET 8.0.100 and try to use the Hot Reload functionality of the `dotnet watch` command.

It works fine at first, then usually after a few minutes of usage it becomes increasingly slow and can take up to minutes to detect a change in the code. It looks like the time to detect a change is approximately doubled each time (see screenshot below).

image

### Expected Behavior

Relatively fast detection of changes and browser refresh when using `dotnet watch`.

### Steps To Reproduce

- Create a new Blazor project with `dotnet new blazor`
- Try to make a page with `dotnet watch` on Ubuntu using a terminal

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

I tried using different browsers but the problem remained.

### **IDE**
VS Code 1.85.0

### **dotnet --info output**
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

### PR DESCRIPTION
**Pull request by jacdavis**
Description
The blazor hotreload service and end point data source are leaking change token on each iteration. By the 15th or 20th iteration, dotnet watch begins to slow significantly and quickly starts failing to apply. 

There is a clear cache static method that is expected to be implemented by the hot reload extension model. This method was not being implemented for the blazor version of this service. This adds that callback and forwards it to the data source to dispose the last change token in a thread safe manner.  Also cleaned up a few other smaller missing dispose calls in this scenario. 

Note that I wouldn't normally expose a static event in this way, but these two classes already have this existing pattern. Also, they are both singleton instances that stay alive once created. So I am not unadvising the static event in a dispose method (there is no appropriate time to dispose of either)

Fixes #52757 Hot reload becomes very slow with dotnet watch and Blazor
https://github.com/dotnet/aspnetcore/issues/52757

### CODE REVIEW

File: src/Components/Endpoints/src/Builder/RazorComponentEndpointDataSource.cs [hunk 1]
```diff
@@ -139,9 +141,26 @@ private void UpdateEndpoints()
...
             _changeToken = new CancellationChangeToken(_cancellationTokenSource.Token);
             oldCancellationTokenSource?.Cancel();
+            oldCancellationTokenSource?.Dispose();
             if (_hotReloadService is { MetadataUpdateSupported : true })
             {
-                ChangeToken.OnChange(_hotReloadService.GetChangeToken, UpdateEndpoints);
+                if (_disposable != null)
+                {
+                    _disposable?.Dispose();
+                }
```
Comment (MackinnonBuck) [inline src/Components/Endpoints/src/Builder/RazorComponentEndpointDataSource.cs:150]:
```suggestion
                _disposable?.Dispose();
```

File: src/Components/Endpoints/src/Builder/RazorComponentEndpointDataSource.cs [hunk 2]
```diff
@@ -139,9 +141,26 @@ private void UpdateEndpoints()
...
+ 
+    public void OnHotReloadClearCache(Type[]? types)
+    {
+        lock (_lock)
+        {
+            if (_disposable != null)
+            {
+                _disposable?.Dispose();
+                _disposable = null;
             }
```
Comment (MackinnonBuck) [inline src/Components/Endpoints/src/Builder/RazorComponentEndpointDataSource.cs:164]: (because the `?.` already handles the null check)
```suggestion
            _disposable?.Dispose();
            _disposable = null;
```

**Review by MackinnonBuck — APPROVED** [review]
This looks great, just a couple small suggestions
