### PR TITLE
[release/7.0] Fix NavigationLock prerendering

### LINKED ISSUE #43724: NavigationLock with ConfirmExternalNavigation throws exception when prerendering
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I add a NavigationLock component with ConfirmExternalNavigations to a BlazorServer app I get an exception during prerendering.

### Expected Behavior

Prerendering works when using NavigationLock with ConfirmExternalNavigations.

### Steps To Reproduce

- Create a new Blazor Server app
- Add `<NavigationLock ConfirmExternalNavigations />` to Index.razor
- Run the app

### Exceptions (if any)

InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

### .NET Version

7.0.100-rc.1.22429.3

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Fix `NavigationLock` prerendering

Fixes a bug that caused `<NavigationLock />` to throw an exception during prerendering if its `ConfirmExternalNavigation` parameter is set to `true`.

## Description

This bug was caused by `<NavigationLock />` attempting to perform JS interop calls during prerendering. This fix moves these JS interop calls to the `OnAfterRenderAsync()` method, which does not get called during prerendering. This PR also adds an E2E test verifying that `<NavigationLock />` works correctly when prerendering is enabled.

Fixes #43724

## Customer Impact

The ability to cancel navigation events is a feature that the community has shown [significant interest](https://github.com/dotnet/aspnetcore/issues/14962) in. With it finally landing in .NET 7, we want this feature to be supported in as many scenarios as possible. The bug that this PR fixes would in many cases force customers to choose between enabling prerendering and using the `<NavigationLock />` component.

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

We have extensive existing test coverage. New automated tests have been added for the scenario that this PR fixes.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

File: src/Components/Web/src/Routing/NavigationLock.cs [hunk 1]
```diff
@@ -9,13 +9,12 @@ namespace Microsoft.AspNetCore.Components.Routing;
 /// <summary>
 /// A component that can be used to intercept navigation events. 
 /// </summary>
-public sealed class NavigationLock : IComponent, IAsyncDisposable
+public sealed class NavigationLock : ComponentBase, IAsyncDisposable
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Routing/NavigationLock.cs:12]: The change of base class is a public API change - not a super scary one but a real one nonetheless.

Is this because the complexity is higher if implementing `IHandleAfterRender` etc?

Comment (MackinnonBuck) [reply src/Components/Web/src/Routing/NavigationLock.cs:12]: Right, I did this to reduce the complexity of this class and reuse the existing logic in `ComponentBase`.

Do you think there are any disadvantages to changing the base class to `ComponentBase` rather than implementing `IHandleAfterRender` (which is also technically a public API change)? This type is already `sealed` so there's no risk of breaking derived types, and it still implements `IComponent` via `ComponentBase`. I could be missing something but to me it seems like both options have similar significance.

Comment (SteveSandersonMS) [reply src/Components/Web/src/Routing/NavigationLock.cs:12]: I agree it's not much of a difference, so if you think it's more maintainable on `ComponentBase` that's fine with me.

Where possible I've tried to build the baked-in components on `IComponent` as a way of minimizing API surface and to retain strong proof that Blazor doesn't accidentally start relying on *all* components being built on `ComponentBase`. However it's not worth doing that if `NavigationLock` ends up being harder to maintain that way.

Comment (MackinnonBuck) [reply src/Components/Web/src/Routing/NavigationLock.cs:12]: > Where possible I've tried to build the baked-in components on `IComponent` as a way of minimizing API surface and to retain strong proof that Blazor doesn't accidentally start relying on all components being built on `ComponentBase`.

That seems fair, and I anticipate the complexity increase of implementing `IHandleAfterRender` manually should be insignificant. I'll give that approach a shot.

File: src/Components/Web/src/Routing/NavigationLock.cs [hunk 2]
```diff
@@ -38,26 +38,45 @@ public sealed class NavigationLock : IComponent, IAsyncDisposable
...
+            {
+                ConfirmExternalNavigation = (bool)parameter.Value;
+            }
+            else
+            {
+                throw new ArgumentException($"The component '{nameof(NavigationLock)}' does not accept a parameter with the name '{parameter.Name}'.");
+            }
+        }
 
-        parameters.SetParameterProperties(this);
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Routing/NavigationLock.cs:48]: I guess I'm missing something basic here, but why replace `SetParameterProperties` with the logic above? Isn't it equivalent?

Comment (MackinnonBuck) [reply src/Components/Web/src/Routing/NavigationLock.cs:48]: It is equivalent, but I noticed that other types implementing `IComponent` directly had similar logic, presumably for perf reasons. But I'm happy to change it back if you think it's worth reducing the size of the changes in this PR.

Comment (SteveSandersonMS) [reply src/Components/Web/src/Routing/NavigationLock.cs:48]: OK that's fine - I just wanted to understand and was unsure if this reflected some behavioral change. LGTM.

File: src/Components/Web/src/Routing/NavigationLock.cs [hunk 3]
```diff
@@ -38,26 +38,45 @@ public sealed class NavigationLock : IComponent, IAsyncDisposable
...
+        var lastHasLocationChangingHandler = _locationChangingRegistration is not null;
+        var hasLocationChangingHandler = OnBeforeInternalNavigation.HasDelegate;
+        if (lastHasLocationChangingHandler != hasLocationChangingHandler)
         {
             _locationChangingRegistration?.Dispose();
-            _locationChangingRegistration = hasOnBeforeInternalNavigationCallback
+            _locationChangingRegistration = hasLocationChangingHandler
                 ? NavigationManager.RegisterLocationChangingHandler(OnLocationChanging)
                 : null;
         }
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Routing/NavigationLock.cs:76]: It's not necessarily a problem, but it seems a bit unusual to trigger rendering unconditionally, and then be doing all this state management during `OnAfterRenderAsync`.

Would it work to update these fields during `SetParametersAsync` and then only trigger a render (and hence the after-render callback) during the rare case when we need to make the JS interop call because the flag has changed?

BTW this is not a big deal at all, so if you feel you have more urgent things to focus on, I'm happy to sign off on the implementation as it stands here. Totally up to you whether you want to tweak this further.

**Review by SteveSandersonMS — APPROVED** [review]
Approving now to ensure you're not blocked, given that the implementation looks completely sufficient already. If you want to make any further tweaks as discussed I'm happy to re-review but that's up to you.

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck Thanks for the update - this looks great! Re-approving :)

File: src/Components/Web/src/Routing/NavigationLock.cs (hunk 3 above)
Comment (MackinnonBuck) [reply src/Components/Web/src/Routing/NavigationLock.cs:83]: This makes sense. I just changed the logic to only re-render when the parameter values change.

However, I decided to keep some of the state management logic in `OnAfterRenderAsync()` in order to minimize the separation between updating the fields tracking the "last applied" parameter values and actually applying the parameter values (e.g. making JS interop calls). I figured that would minimize the chance for some incorrect code path to be taken in between updating fields from `SetParametersAsync()` and applying them in `OnAfterRenderAsync()`.
