### PR TITLE
JSInterop: Enable returning null for a nullable value type

### LINKED ISSUE #30366: jsRuntime.InvokeAsync can't return null as Nullable<Guid>
### Describe the bug

Looks very similar to !10565 :

I'm trying to read a Guid from local storage, so I go `return jsRuntime.InvokeAsync<Guid?>("localStorage.getItem", key);`.
When there is a guid, this works fine. 
But if there isn't a guid, I get this exception:
`System.InvalidCastException: Null object cannot be converted to a value type.`

Am I supposed to box my guid or what?

### To Reproduce

Make a Blazor WASM project. 
Add `jsRuntime.InvokeAsync<Guid?>("localStorage.getItem", key);` somewhere. init of Index.razor should be fine (in my project it happens somewhere 3 levels down asynchronously).
Execute.

### Exceptions (if any)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: Null object cannot be converted to a value type.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Null object cannot be converted to a value type.. See InnerException for more details.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.JSInterop.Infrastructure.TaskGenericsUtil.TcsResultSetter`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(Object tcs, Object result)
   at Microsoft.JSInterop.Infrastructure.TaskGenericsUtil.SetTaskCompletionSourceResult(Object taskCompletionSource, Object result)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TeamBuilder_Website.Services.LocalStorage.<Get>d__3`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TeamBuilder_Website.Services.AppState.RetrieveStoredToken()
   at TeamBuilder_Website.Services.AppState.<.ctor>b__13_0()
   at TeamBuilder_Website.Services.AppState.WaitForInit()
   at TeamBuilder_Website.Services.AccountService.TryLoginFromStoredToken()
   at TeamBuilder_Website.Services.AccountService.IsAuthorized(Guid loginToken)
   at TeamBuilder_Website.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
### Further technical details
- SDK: Microsoft.NET.Sdk.BlazorWebAssembly
- Target framework: net5.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2019 Version 16.8.4

### PR DESCRIPTION
**Pull request by Regenhardt**
# JSInterop: Enable returning null for a nullable value type

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

When a result value is null, and the return type is a nullable value type, Convert.ChangeType throws instead of returning the null value, so in case off null this now uses null directly.

Fixes #30366

### CODE REVIEW

**Comment by Regenhardt** [comment]
Pushed a draft of what I wanted the tests to look like, gotta figure out the test fixture stuff too.

**Comment by Regenhardt** [comment]
Ok I kinda figured out how the tests are supposed to work. Just have to install jdk now to test locally.

**Comment by Regenhardt** [comment]
Figured it out, tests are green now.

**Comment by Regenhardt** [comment]
Alternative: use `result == default` instead of `result == null && default(T) == null` as it might be slightly faster?

**Comment by Regenhardt** [comment]
Ready for review.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs [hunk 1]
```diff
@@ -89,7 +89,9 @@ public void SetResult(object tcs, object? result)
             // If necessary, attempt a cast
             var typedResult = result is T resultT
                 ? resultT
-                : (T)Convert.ChangeType(result, typeof(T), CultureInfo.InvariantCulture)!;
+                : result == null && default(T) == null // ChangeType can't convert null to value types
```
Comment (pavelsavara) [inline src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs:92]: It seems OK to me. 

@oroztocil please review

Comment (hez2010) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs:92]: Why `default(T) == null` instead of `typeof(T).IsValueType`?
`IsValueType` is an intrinsic that will be folded by the compiler.

Comment (javiercn) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs:92]: > typeof(T).IsGenericType && typeof(T).GetGenericTypeDefinition() == typeof(Nullable<>)

This seems like a better option to me

**Review by javiercn — CHANGES_REQUESTED** [review]
We should go with the alternative implementation that @hez2010 suggested.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs (hunk 1 above)
Comment (Regenhardt) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs]: @hez2010 I didn't know about intrinsics and folding, and honestly still don't entirely understand it. I changed it to check for the generic type.

**Comment by Regenhardt** [comment]
I'm back from vacation and updated the branch, ready for review.

File: src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs (hunk 1 above)
Comment (javiercn) [reply src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs]: > and honestly still don't entirely understand it

The git is able to detect that the expression will be constant for a given T and it's able to optimize it entirely when it generates the machine code for a given T. For example, if you have something like `T = int`, it's able to know that the condition will always evaluate to `false` and it can then use that information to simplify the check (and in this case, unconditionally select one branch or another))

**Review by javiercn — APPROVED** [review]

**Review by oroztocil — APPROVED** [review]

**Comment by javiercn** [comment]
@Regenhardt thanks for the contribution!
