### PR TITLE
Expose the original status code in StatusCodeReExecuteFeature

### LINKED ISSUE #46538: Expose the original status code in StatusCodeReExecuteFeature
## Background and Motivation

Motivated by #40518: when the `UseStatusCodePagesWithReExecute` middleware requests a page handled by the `UseStaticFiles` middleware, the status code is clobbered and replaced with 200.  Retaining and exposing it on `StatusCodeReExecuteFeature` makes it possible for users to restore it.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Diagnostics;

public interface IStatusCodeReExecuteFeature
{
+    /// <summary>
+    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
+    /// </summary>
+    int OriginalStatusCode { get; set; }
}

public class StatusCodeReExecuteFeature : IStatusCodeReExecuteFeature
{
+    /// <inheritdoc/>
+    int OriginalStatusCode { get; set; }
}
```

## Usage Examples

```csharp
app.UseStaticFiles(new StaticFileOptions
{
    OnPrepareResponse = responseContext =>
    {
        var context = responseContext.Context;
        if (context.Response.StatusCode == StatusCodes.Status200OK &&
            context.Features[typeof(IStatusCodeReExecuteFeature)] is IStatusCodeReExecuteFeature statusCodeFeature)
        {
            context.Response.StatusCode = statusCodeFeature.OriginalStatusCode;
        }
    }
});
```

## Alternative Designs

```csharp
    /// <summary>
    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
    /// Returns 0 if the concrete type does not provide its own implementation.
    /// </summary>
    int OriginalStatusCode
    {
        get => 0;
        set => throw new NotSupportedException();
    }
```

This version won't break existing implementors of `IStatusCodeReExecuteFeature`, but it has the downside that the caller needs to know to check for `0` (or `null` if we prefer that as a sentinel value).

We could also drop the setter entirely, since there's no real justification for having one, other than that the other interface properties do.

## Risks

This is the first member of `IStatusCodeReExecuteFeature` populated from the response, rather than the request, which might make it surprising to consumers.

### PR DESCRIPTION
**Pull request by amcasey**
# Expose the original status code in StatusCodeReExecuteFeature

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Expose the original status code in `StatusCodeReExecuteFeature`

## Description

Expose the original status code in `StatusCodeReExecuteFeature` so that it can be used in places like `StaticFileOptions.OnPrepareResponse`.

With this change it will be possible to write code like

```csharp
app.UseStaticFiles(new StaticFileOptions
{
    OnPrepareResponse = responseContext =>
    {
        var context = responseContext.Context;
        if (context.Response.StatusCode == StatusCodes.Status200OK &&
            context.Features[typeof(IStatusCodeReExecuteFeature)] is IStatusCodeReExecuteFeature statusCodeFeature)
        {
            context.Response.StatusCode = statusCodeFeature.OriginalStatusCode;
        }
    }
});
```

Fixes #46538

### CODE REVIEW

File: src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs [hunk 1]
```diff
@@ -28,6 +28,11 @@ public interface IStatusCodeReExecuteFeature
     /// </summary>
     string? OriginalQueryString { get; set; }
 
+    /// <summary>
+    /// The <see cref="HttpResponse.StatusCode"/> of the original response.
+    /// </summary>
+    int OriginalStatusCode { get; set; }
```
Comment (Tratcher) [inline src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs:34]: Can this be done in a non-breaking way with DIM's? Not sure how to do that with properties, but the doc claims it's possible.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods
```suggestion
    public int OriginalStatusCode { get; set; } = StatusCodes.Status200Ok;
```

**Review by Tratcher — COMMENTED** [review]
Tests?

File: src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs (hunk 1 above)
Comment (amcasey) [reply src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs:34]: Would it be better to make it nullable?  200 would be confusing in scenarios where the original status code was something else.

Comment (amcasey) [reply src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs:34]: I guess you could use -1 or something if you were _really_ opposed to boxing.

Comment (amcasey) [reply src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs:34]: Also, do people really implement this interface?  How would they use their own implementations?

Comment (amcasey) [reply src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs:34]: I've updated the API proposal.

**Comment by amcasey** [comment]
Force push is a trivial rebase.  API Review changes to follow.

File: src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs (hunk 1 above)
Comment (amcasey) [reply src/Middleware/Diagnostics.Abstractions/src/IStatusCodeReExecuteFeature.cs]: We decided to make it throw.

**Comment by amcasey** [comment]
> Tests?

There aren't any for `IStatusCodeReExecuteFeature`, AFAICT.

File: src/Middleware/Diagnostics/src/StatusCodePage/StatusCodeReExecuteFeature.cs [hunk 2]
```diff
@@ -18,6 +18,9 @@ public class StatusCodeReExecuteFeature : IStatusCodeReExecuteFeature
     /// <inheritdoc/>
     public string? OriginalQueryString { get; set; }
 
+    /// <inheritdoc/>
+    public int OriginalStatusCode { get; set; }
```
Comment (amcasey) [inline src/Middleware/Diagnostics/src/StatusCodePage/StatusCodeReExecuteFeature.cs:22]:
```suggestion
    public int OriginalStatusCode { get; internal set; }
```

File: src/Middleware/Diagnostics/src/PublicAPI.Unshipped.txt [hunk 3]
```diff
@@ -1 +1,3 @@
 #nullable enable
+Microsoft.AspNetCore.Diagnostics.StatusCodeReExecuteFeature.OriginalStatusCode.get -> int
+Microsoft.AspNetCore.Diagnostics.StatusCodeReExecuteFeature.OriginalStatusCode.set -> void
```
Comment (amcasey) [inline src/Middleware/Diagnostics/src/PublicAPI.Unshipped.txt:3]:
```suggestion
```

**Review by BrennanConroy — APPROVED** [review]
