### PR TITLE
Preserve user provided Auth header when access token factory not provided

### LINKED ISSUE #40307: Can't pass headers from browser (typescript) to hub (.NET Core 6)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently using Angular with @microsoft/signalr^6.2.0, and backend with .NET Core 6.0.

I'm trying to pass authentication headers, but I don't receive any.

Won't work with a custom HttpClient neither "headers" attribute.

I'm using LongPolling, since it won't work with WebSockets.

image

image

image

**Received headers on debug.**

image

### Expected Behavior

The headers should be received on the backend.

### Steps To Reproduce

The prints above showed the whole process, a simple code.

### Exceptions (if any)

No exceptions, I just received no headers in the backend.

### .NET Version

6.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/40307

### CODE REVIEW

File: src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts [hunk 1]
```diff
@@ -95,33 +94,29 @@ export class LongPollingTransport implements ITransport {
...
         }
-        if (token) {
-            request.headers[HeaderNames.Authorization] = `Bearer ${token}`;
-            return;
-        }
-        if (request.headers[HeaderNames.Authorization]) {
-            delete request.headers[HeaderNames.Authorization];
+        if (this._accessTokenFactory) {
+            const token = await this._accessTokenFactory();
+            if (token) {
```
Comment (halter73) [inline src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts:103]:
```suggestion
            if (token === undefined) {
```

Although, I hope no one is really using something falsy like `0` or `null` as their access token.

Comment (halter73) [reply src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts:103]: I see this is old behavior and we want to delete the header in the `""` case. It might be slightly better to check for `""` or `undefined`, but it's clearly not a big deal.

**Review by halter73 — APPROVED** [review]

**Comment by davidfowl** [comment]
Nice catch!

File: src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts [hunk 2]
```diff
@@ -95,33 +94,29 @@ export class LongPollingTransport implements ITransport {
...
+                request.headers[HeaderNames.Authorization] = `Bearer ${token}`
+            } else {
+                if (request.headers[HeaderNames.Authorization]) {
+                    delete request.headers[HeaderNames.Authorization];
+                }
+            }
         }
+
+        return;
```
Comment (campersau) [inline src/SignalR/clients/ts/signalr/src/LongPollingTransport.ts:112]: Is the empty `return` needed here?

```suggestion
```
