### PR TITLE
Handle object disposed race on shutdown in IIS

### LINKED ISSUE #26330: Flaky test "ReaderThrowsCanceledException"
```
Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: ConcurrentQueue<WriteContext> [WriteContext { EventId = 0, Exception = null, Formatter = Func3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IIS.FunctionalTests.Te"..., LogLevel = Debug, ... }, WriteContext { EventId = Starting, Exception = null, Formatter = Func3 { ... }, LoggerName = "Microsoft.Extensions.Hosting.Internal.Host", LogLevel = Debug, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func3 { ... }, LoggerName = "Microsoft.AspNetCore.Hosting.Diagnostics", LogLevel = Debug, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func3 { ... }, LoggerName = "Microsoft.Hosting.Lifetime", LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.Hosting.Lifetime", LogLevel = Information, ... }, ...]
```

```
at Microsoft.AspNetCore.Server.IIS.FunctionalTests.StrictTestServerTests.Dispose() in /_/src/Servers/IIS/IIS/test/IIS.Tests/StrictTestServerTests.cs:line 17
at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

<details>
<summary>logs</summary>

```
[0.001s] [TestLifetime] [Information] Starting test ReaderThrowsCanceledException at 2020-09-25T05:53:51
[0.019s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Method: GET, RequestUri: 'http://localhost:51890/start', Version: 1.1, Content: <null>, Headers:
{
}
[0.023s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.023s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly IIS.Tests
[0.023s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.024s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.024s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\AE530982\w\ADB70987\e\.
[0.024s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.024s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 GET http://localhost:51890/start - -
[0.025s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-IIS/10.0
  Date: Fri, 25 Sep 2020 05:53:51 GMT
  Content-Length: 4
}
[0.025s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 GET http://localhost:51890/start - - - 200 - - 0.2916ms
[0.025s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Done
[0.026s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 POST http://localhost/ - 1
[0.027s] [Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer] [Debug] Connection ID "18230571293206380588" disconnecting.
[0.027s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 POST http://localhost/ - 1 - 200 - - 1.1802ms
[0.138s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.140s] [Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer] [Error] Unexpected exception in IISHttpServer.OnRequestsDrained.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.http_stop_calls_into_managed(NativeSafeHandle pInProcessApplication)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.OnRequestsDrained(IntPtr serverContext) in /_/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs:line 255
[1.161s] [TestLifetime] [Information] Finished test ReaderThrowsCanceledException in 1.1596375s
```
</details>

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/dotnet/aspnetcore/issues/26330.

There is a race on shutdown which will call a method with a SafeHandle that has already been disposed. This is because a call from native in managed code has the potential to be called at the same time as server dispose.

There are a few potential ways to fix this:
1. Lock inside of the object to check if we have already disposed before calling into native. This slightly defeats the purpose of the safe handle though. It's what I went with here as it seemed the simplest.
2. Delay disposing if there is an active call from native into managed. This may be difficult though as we'd need to manage state on who will eventually be disposing.
3. Figure out a way to unregister the callback that would call from native into managed. This is also difficult as there may still be active calls from managed into native when doing this check, and only tightens the race.

### CODE REVIEW

File: src/Servers/IIS/IIS/src/Core/IISNativeApplication.cs [hunk 1]
```diff
@@ -9,6 +9,7 @@ namespace Microsoft.AspNetCore.Server.IIS.Core
     internal class IISNativeApplication
     {
         private readonly NativeSafeHandle _nativeApplication;
+        private object _sync = new object();
```
Comment (campersau) [inline src/Servers/IIS/IIS/src/Core/IISNativeApplication.cs:12]:
```suggestion
        private readonly object _sync = new object();
```

**Review by Tratcher — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]
Retroactive approve

**Comment by jkotalik** [comment]
thx
