### PR TITLE
Error when Http/1.0 attempts to upgrade

### LINKED ISSUE #32674: Improve WebSocket failure on HTTP/1.0
Hello, 

In our environment, we cannot make websocket connection in aspnetcore signalR application hosted in IIS (InProcess) and behind reverse proxy (NGINX). 
The TCP connection is reset from IIS (or something else) and the protocol cannot be upgraded to proxy and client receives 502
Bad Gateway, then signalR fallbacks to eventStream. 
Here is the TCP dump.

TCPDump

Here is detailed info for our environment: 
AspnetCore SignalR application is hosted in IIS(in process)
dotnet --info: 
  Version: 5.0.4
  Commit:  f27d337295
IP: 192.168.8.100

The reverse proxy is NGINX hosted in Red Hat Enterprise Linux 8.3 - IP: 192.168.8.101
here is the NGINX configuration 

```
http {
    map $http_connection $connection_upgrade {
        "~*Upgrade" $http_connection;
        default keep-alive;
    }
}

server {
    listen       443 ssl http2;

    root         /usr/share/nginx/html;
    
    error_log /var/log/nginx/error.log warn;
    
    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    location /DashboardHub {
        
        proxy_cache off;
        proxy_buffering off;
        proxy_read_timeout 100s;
	proxy_set_header Host $host;
	proxy_pass http://upstream80;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
    	proxy_set_header X-ClientCert $ssl_client_escaped_cert;
        proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Connection "";
    	proxy_pass http://upstream80;
    	proxy_redirect off;
	client_max_body_size 12M;
	proxy_http_version 1.1;
    }
    
}
```

What I have tried so far: 

1. If we connect to the application directly to IIS from browser everything is working as expected. The app is opening web socket connection and everything is ok. 
2. If we direct the browser through NGINX the app is working, but the browser cannot open websocket connection and the HTTP  status is 502. It then fallbacks to SSE. 
3. If we forward the traffic from NGINX directly to kestrel (start the application as console app) skipping IIS it is also working. 

I have turned FRT in IIS and there is something strange: 
68. GENERAL_RESPONSE_HEADERS Headers="Upgrade: websocket
Server: Microsoft-IIS/10.0
Sec-WebSocket-Accept: rdM3H8k1KPmD/f8HhyLCIw4vpng=
Connection: Upgrade
" 11:49:07.650 

69. GENERAL_FLUSH_RESPONSE_END BytesSent="0", ErrorCode="The parameter is incorrect.
 (0x80070057)" 11:49:07.650 
 
70. ANCM_INPROC_REQUEST_DISCONNECT  11:49:07.650 

71. GENERAL_READ_ENTITY_START  11:49:07.650 

72. GENERAL_READ_ENTITY_END BytesReceived="0", ErrorCode="The specified network name is no longer available.
 (0x80070040)" 

here is complete tcpdump file with two dumps from Failed Request Tracing. One with the failing request from the proxy, and one from a working one.
[Data.zip](https://github.com/dotnet/aspnetcore/files/6478780/Data.zip)

Thank you !

### PR DESCRIPTION
**Pull request by BrennanConroy**
Want to check if this is the behavior we like and then will apply it to IIS too.
Also, what's the reason we don't want to do it in Kestrel?

Fixes https://github.com/dotnet/aspnetcore/issues/32674

### CODE REVIEW

**Comment by halter73** [comment]
> Also, what's the reason we don't want to do it in Kestrel?

Why would we break something that already works? If WebSockets over HTTP/1.0 is the kind of thing people might try and it works like the issue suggests, disallowing it could break people's working apps when they upgrade. I'm all for providing clearer errors in scenarios it cannot work like with HttpSys/IIS, but I think there'd have to be a compelling reason to disallow it on Kestrel.

**Comment by davidfowl** [comment]
Whenever we want to decide on behavior changes in the server space we should:
- Look at what other servers do
- Think about adding flags if this is a breaking change

We have YARP as a front end that is mostly based on kestrel which means it needs to handle all sorts of crazy traffic.

**Review by Tratcher — COMMENTED** [review]
Seems fine overall.

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs [hunk 1]
```diff
@@ -87,6 +87,10 @@ public Task<Stream> UpgradeAsync()
     {
         if (!IsUpgradableRequest)
         {
+            if (Request.ProtocolVersion < System.Net.HttpVersion.Version11)
+            {
+                throw new InvalidOperationException("Upgrade is not valid on connections targeting HTTP/1.0 or lower.");
+            }
             throw new InvalidOperationException("This request cannot be upgraded, it is incompatible.");
```
[the remark this answers is not in the document]
Comment (halter73) [reply src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:94]: Does this sound reasonable?

```suggestion
            throw new InvalidOperationException("This request cannot be upgraded, because it has a body.");
```

File: src/Servers/HttpSys/test/FunctionalTests/OpaqueUpgradeTests.cs [hunk 2]
```diff
@@ -301,6 +301,70 @@ public async Task OpaqueUpgrade_PostWithBodyAndUpgradeHeaders_Accepted()
...
+                builder.Append(':');
+                builder.Append(uri.Port);
+                builder.AppendLine();
+
+                builder.AppendLine();
+                var requestBytes = Encoding.ASCII.GetBytes(builder.ToString());
+                await stream.WriteAsync(requestBytes, 0, requestBytes.Length);
+
+                var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => upgrade.Task);
+                Assert.Equal("Upgrade is not valid on connections targeting HTTP/1.0 or lower.", ex.Message);
```
Comment (BrennanConroy) [inline src/Servers/HttpSys/test/FunctionalTests/OpaqueUpgradeTests.cs:354]:
```suggestion
                Assert.Equal("Upgrade requires HTTP/1.1.", ex.Message);
```

**Comment by BrennanConroy** [comment]
Kestrel will upgrade an "HTTP/1.0" request successfully assuming it has the proper headers, we should probably not touch Kestrel as part of this change.

IIS (because of Http.Sys) will think it upgraded an HTTP/1.0 request successfully but when it writes the response Http.Sys will fail.

So I think this change should be limited to Http.Sys and IIS.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs [hunk 3]
```diff
@@ -263,7 +263,7 @@ private async Task CompleteInitializeResponseAwaited(Task initializeTask)
     // Http/2 does not support the upgrade mechanic.
     // Http/1.x upgrade requests may have a request body, but that's not allowed in our main scenario (WebSockets) and much
```
Comment (Tratcher) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs:264]:
```suggestion
    // Http/1.1 upgrade requests may have a request body, but that's not allowed in our main scenario (WebSockets) and much
```

**Review by Tratcher — APPROVED** [review]
How would the original failure manifest in SignalR now? The client would send a handshake request, then try to start a websocket but the request isn't a valid websocket due to the nginx downgrade. The websocket middleware would no-op. What would the signalr endpoint do?

**Comment by BrennanConroy** [comment]
> How would the original failure manifest in SignalR now?

SignalR checks `IHttpWebSocketFeature.IsWebSocketRequest` which will check `IHttpUpgradeFeature.IsUpgradeableRequest`, since that will be false now it will fallback to assuming the connection attempt is for LongPolling and will likely result in some sort of websocket error on the client.

**Comment by halter73** [comment]
> > How would the original failure manifest in SignalR now?
> 
> SignalR checks `IHttpWebSocketFeature.IsWebSocketRequest` which will check `IHttpUpgradeFeature.IsUpgradeableRequest`, since that will be false now it will fallback to assuming the connection attempt is for LongPolling and will likely result in some sort of websocket error on the client.

Right now IIS just resets the connection, right? Why hasn't this been merged yet? Is this any worse? I guess it would be nice to check if the client was attempting a WebSocket request without relying on the feature, but I don't think that should hold this up.

**Comment by BrennanConroy** [comment]
> Is this any worse?

Yes and no? I think it's better in the sense that we wont try to call upgrade on an HTTP/1.0 connection which would result in IIS killing the connection, but worse in the sense that SignalR would see it as a non-websocket attempt and try to use LongPolling which might have some super ambiguous hard to debug error. Or maybe it's a fine error, just haven't tried it to see what the experience is.

**Comment by BrennanConroy** [comment]
Using Fiddler to modify the HttpVersion I was getting a 409 error when trying to use WebSockets with SignalR on a HTTP/1.0 connection. Now we get a 200 (which errors on the client side) and the server times out the "long polling" connection after a few seconds while the client falls back to SSE.

**Comment by Tratcher** [comment]
What's the client side error? Something about failure to create a websocket connection?

**Comment by BrennanConroy** [comment]
> WebSocket connection to 'ws://localhost:5000/default?name=as&id=dAfPAb1UFNlc5FJnUtjNyA' failed: Error during WebSocket handshake: Unexpected response code: 200

Not much of an error, but the other one wasn't any better

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs [hunk 4]
```diff
@@ -87,7 +87,11 @@ public Task<Stream> UpgradeAsync()
     {
         if (!IsUpgradableRequest)
         {
-            throw new InvalidOperationException("This request cannot be upgraded, it is incompatible.");
+            if (Request.ProtocolVersion != System.Net.HttpVersion.Version11)
+            {
+                throw new InvalidOperationException("Upgrade requires HTTP/1.1.");
+            }
+            throw new InvalidOperationException("This request cannot be upgraded, because it has a body.");
```
Comment (adityamandaleeka) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.cs:94]:
```suggestion
            throw new InvalidOperationException("This request cannot be upgraded because it has a body.");
```
