### PR TITLE
Stop processing original response streaming content if user has started navigating away

### LINKED ISSUE #50733: StreamRendering on first page continue to render after navigation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using @attribute [StreamRendering(true)] on the landing page or one of its component, the page continue to refresh after navigating to a subpage, replacing the page or part of the page.

[30df6324-6fd5-4e0b-922f-f355dd06e0c2.webm](https://github.com/dotnet/aspnetcore/assets/588045/38a6d982-673f-4f19-8e42-aed6af1190d8)

### Expected Behavior

1) That the page you navigate to not blend with the page you left
2) That it is possible to cancel an OnInitializedAsync with the help of a cancellation token when it is no longer rendered on the page, stopping the long running request or pollling. (A workaround for this except on the landing page is to listen to httpContext.RequestAborted)

### Steps To Reproduce

Create new template:

 change weather forcast delay to 5000ms 
````
        // Simulate asynchronous loading to demonstrate streaming rendering
        await Task.Delay(5000);

````
and replace the home page with the following.
````
@page "/"
@attribute [StreamRendering(true)]
<PageTitle>Home</PageTitle>

<h1>Hello, world @Id!</h1>

Welcome to your new app.

@code {

    private int Id { get; set; }
    protected override async Task OnInitializedAsync()
    {
        for (Id = 0; Id < 10; Id++){
            await Task.Delay(1000);
            StateHasChanged();
        }
    }
}
````

Full sample can be found [here](https://github.com/mattyas/BlazorRefreshBug)

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Stop processing original response streaming content if user has started navigating away

Fix a correctness issue with streaming SSR and enhanced nav

## Description

If enhanced nav occurred while streaming SSR was still in progress, subsequent streaming SSR updates could be inserted into the new page even though they are for the old page.

Fixes #50733

## Customer Impact

Without this fix, the combination of streaming SSR and enhanced navigation (which is on by default) would be subject to edge-case issues where pages could display incorrect content.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Only affects this one scenario. The change is very targeted.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Components/Web.JS/src/Rendering/StreamingRendering.ts [hunk 1]
```diff
@@ -36,7 +36,14 @@ class BlazorStreamingUpdate extends HTMLElement {
...
         if (componentId) {
-          insertStreamingContentIntoDocument(componentId, node.content);
+          // For enhanced nav page loads, we automatically cancel the response stream if another enhanced nav supersedes it. But there's
+          // no way to cancel the original page load. So, to avoid continuing to process <blazor-ssr> blocks from the original page load
+          // if an enhanced nav supersedes it, we must explicitly check whether this content is from the original page load, and if so,
+          // ignore it if any enhanced nav has started yet. Fixes https://github.com/dotnet/aspnetcore/issues/50733
+          const isFromEnhancedNav = node.getAttribute('enhanced-nav') === 'true';
+          if (isFromEnhancedNav || hasNeverStartedAnyEnhancedPageLoad()) {
+            insertStreamingContentIntoDocument(componentId, node.content);
+          }
```
Comment (javiercn) [inline src/Components/Web.JS/src/Rendering/StreamingRendering.ts:46]: Can it happen that we cancel an enhanced nav mid-way (while some content has already been inserted) and we start processing a new enhanced nav response? Would we be in a situation where we've updated half the DOM and we start updating the rest with a newer version? Or will the new version replace the updated bits so far + the non-updated bits.

Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Rendering/StreamingRendering.ts:46]: > Or will the new version replace the updated bits so far + the non-updated bits.

Yes, that. Each enhanced nav response is treated as a desired end state, and we diff as needed to reach that state, no matter what state we were in before.

Because of the single-threadedness of JS, and because we cancel any preceding enhanced nav response stream before we issue a new request, only the latest enhanced nav response is processed and it full replaces whatever was there before. If the previous request was streaming SSR and hadn't finished sending streaming updates, we don't care - we just cancel the previous request and hence won't see any more of its streaming updates.

Comment (javiercn) [reply src/Components/Web.JS/src/Rendering/StreamingRendering.ts:46]: @SteveSandersonMS could that behavior cause weird outcomes/bugs? I imagine that worst case scenario it ends up with the whole document being replaced, I am just trying to think of situations where it could be problematic break things.

**Review by javiercn — APPROVED** [review]

File: src/Components/Web.JS/src/Rendering/StreamingRendering.ts (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Rendering/StreamingRendering.ts:46]: Not that I know of. This is the way it's designed and expected to work. The guiding principle of enhanced nav is that it should produce the same outcome as a full-page navigation, with the exception of specific things we explicitly preserve (interactive components and `data-preserve` elements). On those grounds it's correct to disregard orphaned streaming updates from prior navigations.

**Comment by SteveSandersonMS** [comment]
Note that I've been forced to cherry-pick two other test fixes into this PR in order to get the tests to pass. This may be because the version of Selenium/Chrome has changed in Helix.

**Comment by SteveSandersonMS** [comment]
The one test failure is completely unrelated (it's Kestrel Http2ConnectionTests), so merging anyway to begin unblocking the backlog of merges.
