### PR TITLE
Unify initialization in DefaultHttpContextFactory

### LINKED ISSUE #40705: DefaultHttpContextFactory.Create(IFeatureCollection) does not set DefaultHttpContext._active
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

#29748 added `DefaultHttpContext._active` and set it in `DefaultHttpContext.Initialize(IFeattureCollection)`. The problem is that this method only gets called via `DefaultHttpContextFactory.Initialize(DefaultHttpContext httpContext, IFeatureCollection featureCollection)` and not `DefaultHttpContextFactory.Create(IFeatureCollection featureCollection)`.

This means that the first unpooled request over a given Kestrel connection is never marked `_active.` And since `IISHttpContextOfT<TContext>` does not implement `IHostContextContainer<TContext>`, `_active` is never set for requests coming in over IIS.

image

This means those using memory dump analyzers have to go back to looking if `_features` is zeroed out instead of looking at `_active` which was intended to be the easier way to do this but is currently misleading.

### Expected Behavior

`DefaultHttpContext._active` should be set for all ongoing requests served by both IIS and Kestrel if the `DefaultHttpContextFactory` is in use.

### Steps To Reproduce

Attach a debugger to an ASP.NET Core app using IIS or Kestrel. Inspect the `HttpContext` of a request which should be a `DefaultHttpCotnext`. With Kestrel, `DefaultHttpContext._active` won't be set for the first request sent over a connection (or any other unpooled request). With IIS, `DefaultHttpContext._active` is never set.

### Exceptions (if any)

_No response_

### .NET Version

7.0.100-preview.3.22163.1

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fix #40705

#29748 added `DefaultHttpContext._active` and set it in `DefaultHttpContext.Initialize(IFeatureCollection)`. The problem is that this method only gets called via `DefaultHttpContextFactory.Initialize(DefaultHttpContext httpContext, IFeatureCollection featureCollection)` and not `DefaultHttpContextFactory.Create(IFeatureCollection featureCollection)` which uses `DefaultHttpContextFactory.Initialize(DefaultHttpContext httpContext)` instead of the variant of `Initialize` that takes the `IFeatureCollection`.

This change gets rid of `DefaultHttpContextFactory.Initialize(DefaultHttpContext httpContext)`, inlining its content into its caller, and changes `Create` to use that one.

### CODE REVIEW

File: src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs [hunk 1]
```diff
@@ -49,7 +49,7 @@ public HttpContext Create(IFeatureCollection featureCollection)
         }
 
         var httpContext = new DefaultHttpContext(featureCollection);
-        Initialize(httpContext);
+        Initialize(httpContext, featureCollection);
```
Comment (halter73) [inline src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs:52]: Can we add a test similar to to [InternalActiveFlagIsSetAndUnset](https://github.com/dotnet/aspnetcore/blob/2f68ef8d42646046eb36ff2db5f17965a7893545/src/Http/Http/test/DefaultHttpContextTests.cs#L259-L273) but for DefaultHttpContextFactory.Create() and DefaultHttpContextFactory.Initialize()?

Comment (adityamandaleeka) [reply src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs:52]: Good idea, done.

**Review by halter73 — APPROVED** [review]
