### PR TITLE
[Blazor] Dynamic authentication requests

### LINKED ISSUE #42580: [Blazor][Wasm] Dynamic and extensible authentication requests
The new additions offer a loosely coupled model to interact with the underlying authentication service for customizing the authentication details as well as more granular control of the process.

This proposal unblocks:
https://github.com/dotnet/aspnetcore/issues/37365
https://github.com/dotnet/aspnetcore/issues/32640
https://github.com/dotnet/aspnetcore/issues/32782
https://github.com/dotnet/aspnetcore/issues/19925
https://github.com/dotnet/aspnetcore/issues/33784

In the initial version of Blazor Webassembly we shipped support for authentication via OAuth supported by oidc-client.js and MSAL.js. Our support allowed people to login, logout and acquire tokens to talk to APIs. All the required parameters were configured statically at startup time.

Over time, we have observed the need from people to dynamically tweak the parameters used for performing these authentication flows. Whether they need to add additional parameters for their provider or pass in additional options to change the login behavior or the behavior when interaction is required to provision a token.

This presented challenges with the current implementation, as all the configuration was defined during startup and there were many options that did not make sense to configure statically, like the login hint or the prompt behavior for the IdP.

In addition to that, adding those options to the existing provider options will add an additional maintenance burden.

In general, there are four scenarios that we want to support:
* The developer can implement login and log out (provisioning a token as part of that flow).
* The developer can customize the login and logout flows to force the user to re-enter credentials or change accounts.
* The user is able to provision a token silently.
* The user is able to provision a token interactively when it can't be provisioned silently. This can happen for several reasons:
  * The user credentials expired and a new login operation must take place.
  * Acquiring a token for the given scopes requires interaction, for example, if the user needs to consent.

```mermaid
stateDiagram-v2

state "/" as Home
state "authentication/login" as Login
state authenticate <<choice>>
state orders <<choice>>
state "orders/list" as Resource
[*] --> Home
Home --> authenticate
authenticate --> Login : Page requires authenticated user.
authenticate --> Login : User clicks login.
authenticate --> Login : User clicks change account.
Login --> Home : User successfullly authenticates
Home --> orders : User navigates to /orders
orders --> Login : [Not Authorized]
Login --> Resource : [Authorized] User successfully authenticates
orders --> Resource : [Authorized]
Resource --> Login : [Credentials expired]\nProvision new credentials
```

Out of those flows, we currently only supported 1 and 3, since we defined the configuration during startup and we relied on the ability to get tokens silently indefinitely in other cases thanks to the AAD ability to consent ahead of time.

Unfortunately, there are scenarios when that functionality doesn't work and in addition to that, the latest best pratices recommend not requesting consent for additional scopes until you need them.

Given the desire to enable these two new scenarios and unblock our customers ability to customize the login process as well as the process for acquiring additional tokens interactively, we are making a few changes to the webassembly authentication system, to better support these concerns.

## The "webassembly authentication" protocol

Up to now, we would redirect users to the `authentication/login` endpoint and we would optionally include a `returnUrl` parameter in the query string, indicating where the user should be sent back when they completed the flow.

This proved enough to implement basic functionality where the `AuthorizeView` will work in concert with the `RedirectToLogin` component in the template to redirect the user to log in and return back to the page.

Similarly, whenever the credentials happened to expire, an exception would be thrown and the user would be redirected to the login endpoint to acquire refreshed credentials and return to the same location.

This approach worked for simple scenarios, but it was not without risks. Passing data through the query string requires us to deal with encoding and decoding the data and can open us to risks like open redirects, etc.

In addition to that, it is hard to pass in structured data (objects) through the query string. There are several approaches, like serializing to JSON and Base64Url encoding the data before putting it on the query string.

To support the new scenarios we care about (customizing the login flow, acquiring tokens interactively, passing in additional data, etc.) we want to allow the developer to pass in parameters to the `authentication/login` endpoint that can flow to the service.

Many of those parameters might be request specific and not suitable to be part of the default ProviderOptions we offer.

Similarly, we don't want to necessarily allow changing things like the authority or similar parameters on a per request basis, as that sets up customers for failure.

## The "upgraded authentication" protocol

To address some of the challenges of the existing protocol, as well as "standarize" in an approach that can enable additional flexibility for future versions, we are going to introduce a new primitive called the `InteractiveAuthenticationRequest`.

This request represents the contract for the `authentication/login` endpoint that the `<RemoteAuthenticatorViewCore>` understands.
```mermaid
classDiagram
class InteractiveAuthenticationRequest{
  string ReturnUrl
  string[] Scopes
  InteractiveAuthenticationRequestType RequestType
  AddAdditionalParameter(string name, TParameter value)
  TParameter GetAdditionalParameter(string name)
}

class InteractiveAuthenticationRequestType{
  <<enumeration>>
  Login
  GetToken
}
```
It provides first class support for some of the standard properties that we need for performing the flows, like ReturnUrl and Scopes.

It provides methods to add and retrieve additional parameters that will be passed down to the underlying JS implementation.

In order to pass these parameters to the login endpoint, we are adding support for passing and retrieving state from the `NavigationManager` when performing internal navigations backed by the history API.

Leveraging the history API offers several benefits:
* The state that we pass to the endpoint is tied to the navigation we perform to the `authentication/login` endpoint.
* Using `state` in the history API we can avoid having to deal with encoding and decoding data.
* Using `state` in the history API reduces the surface attack area, since unlike the query string, it can't be set via a top level navigation nor be influenced from a different origin.
* Using `state` in the history API removes the need for cleanup as the state is attached to the entry and goes away upon successful login (because we replace the history entry).

Passing the data to the login endpoint can be done with an extension method on navigation manager that takes care of serializing the data and putting it on the state parameter when navigating:
```
navigationManager.NavigateToLogin("login/path", interactiveRequest);
```

With that in mind, the scenarios we care about enabling look like this:

#### Customize the login process
```csharp
// Likely will add methods like InteractiveAuthenticationRequest.Login(string returnUrl) tailored for common cases.
var request = new InteractiveAuthenticationRequest(InteractiveAuthenticationRequestType.Authenticate, navigationManager.Uri);

request.AddAdditionalParameter("login_hint","peter@example.com");

navigationManager.NavigateToLogin("authentication/login", request);
```

#### Customize the options before getting a token interactively
```csharp
try{
   await httpclient.Get("/orders");
   ...
}catch(AccessTokenNotAvailableException ex)
{
  ex.Redirect(interactiveRequest => {
    interactiveRequest.AddAdditionalParameter("login_hint", "peter@example.com");
  });
}
```

#### Customize the options when using the IAccessTokenProvider directly
```csharp
var result = provider.GetAccessToken(new AccessTokenOptions{ Scopes = new[] {"a", "b"}});
if(!result.TryGetToken(out var token))
{
  var interaction = result.InteractiveRequest;
  interactiveRequest.AddAdditionalParameter("login_hint", "peter@example.com");
  Navigation.NavigateToLogin(result.InteractiveRequestUrl, interaction);
}
```

In addition to that, we are going to provide a callback that will be invoked when a given Authentication event happens so that applications can also centralize the logic for passing in additional parameters to the different operations.

That's the reason why we don't expose a `IDictionary<string, object>` as the state is serialized between the location originating the navigation (for example the index page) to the `authentication/login` endpoint and deserialized afterwards, which means that the types in the dictionary are lost (replaced for JsonElement) and that would confuse users.

#### Other information
* Why not a typed model?
  * It would involve adding an additional generic parameter to our types (and they already have enough).
  * It would require us to define the types ourselves.
  * These scenarios are more advanced, and people can write nice wrappers around them for their library if needed.

### PR DESCRIPTION
**Pull request by javiercn**
Fixes https://github.com/dotnet/aspnetcore/issues/42580

Adds a new type InteractiveRequestOptions that contains the data developers can use to customize the authentication flows. The data is passed in through the State parameter to the remoteauthenticatorviewcore which then handles the authentication process.

* Updates RemoteAuthenticatorViewCore to rely on navigation history state to pass in data around for authentication operations.
* Adds logging to the RemoteAuthenticatorViewCore
* Updates AuthenticationService.ts to handle requesting additional tokens
* Updates AuthenticationService.ts to account for the interactiverequest options.
* Adds E2E tests that demonstrate:
  * Sign in can be customized.
  * Requesting a token interactively for a second resource.

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 1]
```diff
@@ -52,28 +52,71 @@ export interface AuthenticationResult {
...
+// These are the values for the .NET logger LogLevel
+export enum LogLevel {
+    Trace = 0,
+    Debug = 1,
+    Information = 2,
+    Warning = 3,
+    Error = 4,
+    Critical = 5,
+}
+
```
Comment (javiercn) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:99]: I have been adding logging as even though is "orthogonal", it makes it much easier to debug/troubleshoot things.

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj [hunk 2]
```diff
@@ -24,6 +25,17 @@
...
+    <ItemGroup>
+      <_IdentityUI Include="@(StaticWebAssetProjectConfiguration)" Condition="'%(FileName)' == 'Microsoft.AspNetCore.Identity.UI'" />
+      <_IdentityUI Condition="'%(Identity)' != ''">
+        <AdditionalBuildProperties>@(_IdentityUI->'%(AdditionalBuildProperties)');IdentityDefaultUIFramework=$(IdentityDefaultUIFramework)</AdditionalBuildProperties>
+      </_IdentityUI>
+      <StaticWebAssetProjectConfiguration Remove="@(_IdentityUI)" />
+      <StaticWebAssetProjectConfiguration Include="@(_IdentityUI)" />
+    </ItemGroup>
+  </Target>
+
```
Comment (javiercn) [inline src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj:38]: This just fixes how we consume identity UI as a class library, which was broken.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 3]
```diff
@@ -52,28 +52,71 @@ export interface AuthenticationResult {
...
     completeSignIn(state: unknown): Promise<AuthenticationResult>;
-    signOut(state: unknown): Promise<AuthenticationResult>;
+    signOut(context: AuthenticationContext): Promise<AuthenticationResult>;
     completeSignOut(url: string): Promise<AuthenticationResult>;
 }
 
+export class ManagedLogger {
+    private debug: boolean;
+    private trace: boolean;
+    public constructor(private objectRef: any) {
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:77]: I'm not sure about whether JS interop libs are referenced here, but could `objectRef` be typed as `DotNetObjectReference` (or whatever it's called) instead of `any`?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts [hunk 4]
```diff
@@ -52,28 +52,71 @@ export interface AuthenticationResult {
...
+        this.debug = objectRef.invokeMethod('IsEnabled', LogLevel.Debug);
+        this.trace = objectRef.invokeMethod('IsEnabled', LogLevel.Trace);
+    }
+
+    log(level: LogLevel, message: string): void {
+        if ((level == LogLevel.Trace && this.trace) ||
+            (level == LogLevel.Debug && this.debug)) {
+            return this.objectRef.invokeMethod('Log', level, message);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:85]: TBH We're going to a lot of trouble to redirect the log output from TypeScript code to .NET code which then calls back into JS code (since this is wasm only). Wouldn't it be good enough just to log directly to the JS console from the original TypeScript code?

I know it's theoretically possible people may have set up something custom in the .NET logging config but that would be pretty unusual to do. Is that what motivates going through all the indirection?

At first glance I was a bit worried to see that we're allowing JS code to tell .NET to log a completely arbitrary message with an arbitrary severity. I quickly realised this is wasm only so not a security issue in itself, however we will have to remember not to extend the use of this pattern or the infrastructure you're adding here to Server in the future. It would be a bit safer if the infrastructure didn't exist in the first place.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+/// </summary>
+public sealed class InteractiveRequestOptions
+{
+    /// <summary>
+    /// Initializes a new instance of <see cref="InteractiveRequestOptions"/>.
+    /// </summary>
+    public InteractiveRequestOptions()
+    {
+    }
+
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:21]:
```suggestion
    /// <summary>
    /// Initializes a new instance of <see cref="InteractiveRequestOptions"/>.
    /// </summary>
    public InteractiveRequestOptions()
    {
    }
    
```

Doesn't seem needed

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:21]: Oh no wait, I guess it is needed for JSON deserialization.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+    /// <summary>
+    /// Creates a new <see cref="InteractiveRequestOptions"/> for signing in with the given return url and scopes.
+    /// </summary>
+    /// <param name="returnUrl">The URL to return to after the interactive operation.</param>
+    /// <param name="scopes">The scopes to request interactively.</param>
+    /// <returns>An <see cref="InteractiveRequestOptions"/> configured for signing in.</returns>
+    public static InteractiveRequestOptions SignIn(string returnUrl, IEnumerable<string> scopes)
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:28]: Could we do this and not need the doubles for each overload?

```suggestion
    public static InteractiveRequestOptions SignIn(string returnUrl, IEnumerable<string> scopes = null)
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+    /// implementations the parameters will be JSON serialized using System.Text.Json and passed as a parameter to the
+    /// underlying JavaScript implementation that handles the operation details.
+    /// </remarks>
+    public IDictionary<string, object> AdditionalRequestParameters { get; set; } = new Dictionary<string, object>();
+
+    [UnconditionalSuppressMessage(
+        "Trimming",
+        "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+        Justification = "Serializes 'InteractiveAuthenticationRequest' into a string")]
+    internal string ToState() => JsonSerializer.Serialize(this);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:131]: Is it definitely safe to suppress the trim warning here and below? Is it possible to use the overload of `JsonSerializer.Serialize` that takes the context parameter so it uses the sourcegenerated version of the serializer/deserializer and hence always does the right thing with trimming?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+/// <summary>
+/// Extensions for <see cref="NavigationManager"/>.
+/// </summary>
+public static class NavigationManagerExtensions
+{
+    /// <summary>
+    /// Initiates a logout operation by navigating to the log out endpoint.
+    /// </summary>
+    /// <remarks>
+    /// The navigation includes stated that is added to the browser history entry to
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:15]:
```suggestion
    /// The navigation includes state that is added to the browser history entry to
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+    /// prevent logout operations performed from different contexts.
+    /// </remarks>
+    /// <param name="manager">The <see cref="NavigationManager"/>.</param>
+    /// <param name="logoutPath">The path to navigate too.</param>
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:19]:
```suggestion
    /// <param name="logoutPath">The path to navigate to.</param>
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs (hunk 8 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:15]: Same below

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs [hunk 10]
```diff
@@ -0,0 +1,73 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace Microsoft.AspNetCore.Components.WebAssembly.Authentication;
+
+/// <summary>
+/// Extensions for <see cref="NavigationManager"/>.
+/// </summary>
+public static class NavigationManagerExtensions
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:9]: I suspect many people will try to call these extension methods and be surprised that we're requiring them to specify the URLs to the logout/login pages. It may feel like the framework should know those URLs and do the right thing for them.

Presumably that's not possible without adding some new feature, or you would have already done it. Is that right?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+    /// prevent logout operations performed from different contexts.
+    /// </remarks>
+    /// <param name="manager">The <see cref="NavigationManager"/>.</param>
+    /// <param name="loginPath">The path to the login url.</param>
+    /// <param name="request">The <see cref="InteractiveRequestOptions"/> containing the authorization details.</param>
+    public static void NavigateToLogin(this NavigationManager manager, string loginPath, InteractiveRequestOptions request)
+    {
+        manager.NavigateTo(loginPath, new NavigationOptions
+        {
+            ForceLoad = false,
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:55]:
```suggestion
```

You don't have to specify that, do you?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+    /// Initiates a logout operation by navigating to the log out endpoint.
+    /// </summary>
+    /// <remarks>
+    /// The navigation includes stated that is added to the browser history entry to
+    /// prevent logout operations performed from different contexts.
+    /// </remarks>
+    /// <param name="manager">The <see cref="NavigationManager"/>.</param>
+    /// <param name="loginPath">The path to the login url.</param>
+    /// <param name="request">The <see cref="InteractiveRequestOptions"/> containing the authorization details.</param>
+    public static void NavigateToLogin(this NavigationManager manager, string loginPath, InteractiveRequestOptions request)
```
[the remark this answers is not in the document]
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:51]: I understand that it's commonly the case that a login request would be because you're trying to get to some page that requires auth, but isn't it possible that sometimes you want to programmatically trigger a login request that takes you to some different place? Or do you think the only legit pattern is to send them to the different place first, and then rely on that to trigger the login request?

[the remark this answers is not in the document]
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:51]: Oh, forget this. I just realised you can do that when you configure the `InteractiveRequestOptions`.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs [hunk 13]
```diff
@@ -138,7 +128,7 @@ protected override void BuildRenderTree(RenderTreeBuilder builder)
                 builder.AddContent(0, CompletingLoggingIn);
                 break;
             case RemoteAuthenticationActions.LogInFailed:
-                builder.AddContent(0, LogInFailed(_message));
+                builder.AddContent(0, LogInFailed(Navigation.HistoryEntryState));
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:131]: Could you explain more about what's going on here? It looks as if we're using `Navigation.HistoryEntryState` as part of the user-facing UI now. Is that really where the error message string now lives?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs [hunk 14]
```diff
@@ -235,23 +237,33 @@ private async Task ProcessLogIn(string returnUrl)
...
             case RemoteAuthenticationStatus.OperationCompleted:
                 break;
             case RemoteAuthenticationStatus.Failure:
-                var uri = Navigation.ToAbsoluteUri($"{ApplicationPaths.LogInFailedPath}?message={Uri.EscapeDataString(result.ErrorMessage)}").ToString();
-                NavigateToReturnUrl(uri);
+                Log.LoginCallbackFailed(Logger, result.ErrorMessage);
+                Log.NavigatingToUrl(Logger, ApplicationPaths.LogInFailedPath);
+                Navigation.NavigateTo(
+                    ApplicationPaths.LogInFailedPath,
+                    AuthenticationNavigationOptions with { HistoryEntryState = result.ErrorMessage });
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:266]: Congratulations! First usage of `with` in this codebase (at least that I've noticed)

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs [hunk 15]
```diff
@@ -260,11 +272,12 @@ private async Task ProcessLogInCallback()
 
     private async Task ProcessLogOut(string returnUrl)
     {
-        if (!await SignOutManager.ValidateSignOutState())
+        if ((Navigation.HistoryEntryState != null && !ValidateSignOutRequestState()) ||
+            // For backcompat purposes, keep SignOutManager working, even though we now use the history.state for this.
+            (Navigation.HistoryEntryState == null && !await SignOutManager.ValidateSignOutState()))
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:277]: If we have to keep the `SignOutManager` approach to blocking CSRF anyway, what's the point of having a new mechanism?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 16]
```diff
@@ -23,17 +24,21 @@ public class RemoteAuthenticationService<
...
     IRemoteAuthenticationService<TRemoteAuthenticationState>,
-    IAccessTokenProvider
+    IAccessTokenProvider,
+    IDisposable
     where TRemoteAuthenticationState : RemoteAuthenticationState
     where TProviderOptions : new()
     where TAccount : RemoteUserAccount
 {
     private static readonly TimeSpan _userCacheRefreshInterval = TimeSpan.FromSeconds(60);
+    private readonly ILogger<RemoteAuthenticationService<TRemoteAuthenticationState, TAccount, TProviderOptions>> _logger;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:34]: This particular field doesn't appear to be used anywhere.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 17]
```diff
@@ -23,17 +24,21 @@ public class RemoteAuthenticationService<
...
+    private readonly DotNetObjectReference<LoggerWrapper> _loggerObjectRef;
     private bool _initialized;
 
     // This defaults to 1/1/1970
     private DateTimeOffset _userLastCheck = DateTimeOffset.FromUnixTimeSeconds(0);
     private ClaimsPrincipal _cachedUser = new ClaimsPrincipal(new ClaimsIdentity());
+    private bool disposedValue;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:41]:
```suggestion
    private bool _disposedValue;
```

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 18]
```diff
@@ -67,11 +72,31 @@ public class RemoteAuthenticationService<
         IOptionsSnapshot<RemoteAuthenticationOptions<TProviderOptions>> options,
         NavigationManager navigation,
         AccountClaimsPrincipalFactory<TAccount> accountClaimsPrincipalFactory)
+        : this(jsRuntime, options, navigation, accountClaimsPrincipalFactory, null)
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:75]: My guess is that you're retaining this contructor overload (with logger being set to null) just to avoid the breaking change, or perhaps to keep people's unit tests working.

If so that's fine, and I can see that the logger isn't even used unless we get an incoming JS interop call, so people's unit tests won't be affected.

However, could we at least mark this constructor overload as `[Obsolete]` if there's no good reason for its continued existence in production? It would be nice to clear away this kind of thing eventually.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs [hunk 19]
```diff
@@ -211,6 +233,48 @@ private void UpdateUser(Task<ClaimsPrincipal> task)
...
+            }
+
+            disposedValue = true;
+        }
+    }
+
+    void IDisposable.Dispose()
+    {
+        Dispose(disposing: true);
+        GC.SuppressFinalize(this);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:254]: Do we really need to do all this dispose pattern in full? I don't think the resource we're protecting here (`_loggerObjectRef`) actually benefits, because:

1. `RemoteAuthenticationService` can't be GCed if it's still rooted
2. If `RemoteAuthenticationService` is still rooted, then `_loggerObjectRef` is also still rooted
3. If `_loggerObjectRef` is still rooted, then telling JS to discard it makes no difference

I suspect this full Dispose pattern might be relevant in some edge cases for a JSObjectReference, but not for a DotNetObjectReference. If I've miscalculated, please correct me :)

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Pages/UserPreferences.razor [hunk 20]
```diff
@@ -30,13 +32,7 @@
...
             if (response.IsSuccessStatusCode)
             {
-                var query = new Uri(Navigation.Uri).Query;
-                var hasReturnUrl = System.Text.RegularExpressions.Regex.Match(query, ".*?returnUrl=([^&]+).*");
-                if (hasReturnUrl.Success)
-                {
-                    var returnUrl = hasReturnUrl.Groups[1];
-                    Navigation.NavigateTo(Uri.UnescapeDataString(returnUrl.Value));
-                }
+                    Navigation.NavigateTo(ReturnUrl);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Pages/UserPreferences.razor:35]:
```suggestion
                Navigation.NavigateTo(ReturnUrl);
```

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor [hunk 21]
```diff
@@ -1,10 +1,12 @@
...
+@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
 @using Microsoft.Extensions.Options
+
 @inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> Options
 @code {
 
     protected override void OnInitialized()
     {
-        Navigation.NavigateTo($"{Options.Get(Microsoft.Extensions.Options.Options.DefaultName).AuthenticationPaths.LogInPath}?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");
+        Navigation.NavigateToLogin(Options.Get(Microsoft.Extensions.Options.Options.DefaultName).AuthenticationPaths.LogInPath);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor:10]: Is this the expected usage pattern for customers? It's very verbose. Isn't it practical for `NavigateToLogin` to get the path from these options by default?

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj:38]: It would be good to add a comment indicating what all this stuff is for. i.e., in what way it would be broken otherwise, and why it has to be fixed here rather than in whatever added the identity UI files to the project in the first place.

Hopefully you can appreciate that basically nobody in the world would have any idea why we're doing this apart from you :)

File: src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs [hunk 22]
```diff
@@ -221,6 +221,88 @@ public void AuthenticatedUser_CanGoToProfile()
...
     }
 
+    [Fact]
+    public void CanPassAdditionalParameters_DuringSignIn()
+    {
+        // Register first user
+        ClickAndNavigate(By.PartialLinkText("Register"), "/Identity/Account/Register");
+
+        var userName1 = $"{Guid.NewGuid()}@example.com";
+        var password1 = $"[PLACEHOLDER]-1a";
```
Comment (SteveSandersonMS) [inline src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:231]: What is this `[PLACEHOLDER]` string for? I don't see any other code in this PR that would care what the value of the password is.

Comment (SteveSandersonMS) [reply src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:231]: I see some of the existing tests also use this string, but I still am not sure if it's meant to have some meaning or if it's just a completely arbitrary string (including the square brackets).

File: src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor [hunk 23]
```diff
@@ -26,9 +24,8 @@
 </AuthorizeView>
 
 @code{
-    private async Task BeginSignOut(MouseEventArgs args)
+    public void BeginSignOut()
```
Comment (SteveSandersonMS) [inline src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor:27]: Why `public`?

File: src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualMsalAuth.razor [hunk 24]
```diff
@@ -1,23 +1,20 @@
...
 @using Microsoft.AspNetCore.Components.WebAssembly.Authentication
-
 @inject NavigationManager Navigation
-@inject SignOutSessionStateManager SignOutManager
 
 <AuthorizeView>
     <Authorized>
         Hello, @context.User.Identity?.Name!
-        <button class="nav-link btn btn-link" @onclick="BeginLogout">Log out</button>
+        <button class="nav-link btn btn-link" @onclick="BeginSignOut">Log out</button>
```
Comment (SteveSandersonMS) [inline src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualMsalAuth.razor:8]: Is there any coherent rule about when we say "sign out" vs "log out"?

It's pretty weird to have a link labelled "log out" but the method is called "sign out", which then redirects to a URL containing "logout".

What stops us from using "log out" consistently in this code?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:77]: No, best to keep it simple. `any` is fine.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts (hunk 4 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts:85]: I am fine with doing just that, I somewhat wanted to keep the messages consistent, hence why I opted for this approach. I will simplify this to just pass in from .NET the enabled log levels (to keep things consistent) and log directly through the console in that case.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 6 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:28]: I don't recall us using default values on parameters for APIs other than cancellation token. I generally avoid default parameter values on public APIs, but I am fine changing it if we are generally ok with it.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 7 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:131]: @SteveSandersonMS this is something I wasn't sure about.

We might need APIs to add to the dictionary instead, so that the trimmer can know that it needs to keep those parameters, so instead of having an `AdditionalRequestParameters` dictionary, we would have 3 APIs:
* bool TryAddAdditionalParameter<TParameter>("name", value);
* bool RemoveAdditionalParameter<TParameter("name");
* bool TryGetAdditionalParameter<TParameter>("name");

That's where I started, but I felt it was a bit cumbersome compared to a dictionary, however given the serialization constraints I think it might be best.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs (hunk 10 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:9]: It would require a DI service to be injected, since the URLs are configurable. I also don't want to do things that preclude in the future people having multiple authentication options enabled in the same app (like if you want to have AAD and AAD B2C). 

So being able to pass it in directly makes it more clear in the template and allows different options depending on the context it is being used on.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:131]: It is being passed as part of the state instead of in the query string.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 14 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:266]: It is actually pretty nice because it avoids a lot of repetition and allows you to define common things in one place.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:277]: I am planning to deprecate the SignOutManager in favor of the new way using the NavigationManager, as the SignOutManager relies on local storage, which is not explicitly tied to the navigation action, and requires an additional concept you need to know about.

I am keeping the SignOutManager code around here to avoid the breaking change for people.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 18 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:75]: There are a bunch of things like this that I have done to "avoid the breaking changes", so I will make sure I obsolete things too.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 19 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:254]: I `ctrl+.` my way to victory, technically you can extend `RemoteAuthenticationService` to tweak the auth operations, hence why the full dispose pattern here. It is what you would do if you wanted to plug in a complete separate implementation of the auth operations.

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor (hunk 21 above)
Comment (javiercn) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor:10]: This is only for our tests. On the templates we do `Navigation.NavigateToLogin("authentication/login")` directly, as it is clearer for customers what is going on.

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj (hunk 2 above)
Comment (javiercn) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Wasm.Authentication.Server.csproj:38]: I'll add a comment for this.

File: src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs (hunk 22 above)
Comment (javiercn) [reply src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:231]: I think this is because we generate a Guid for the password and replace it, as we need to ensure it complies with the password policy of having uppercase, lowercase, numbers and special characters, but to be honest, that is a guess. I just copy pasted an existing test to use as a starting point for these tests

File: src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor (hunk 23 above)
Comment (javiercn) [reply src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor:27]:
```suggestion
    private void BeginSignOut()
```

Comment (javiercn) [reply src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor:27]: No particular reason, I just made a mistake (it's sample code though). I have made it private

File: src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualMsalAuth.razor (hunk 24 above)
Comment (javiercn) [reply src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualMsalAuth.razor:8]:
```suggestion
        <button class="nav-link btn btn-link" @onclick="BeginLogOut">Log out</button>
```

Comment (javiercn) [reply src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualMsalAuth.razor:8]: I have changed it, we had a discussion about this like 3 years ago, but I don't remember the details.

Part of what we wanted to make sure was that these things weren't confused with identity concepts, and that's what motivated some of the naming. I have changed it to be more consistent here.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs (hunk 10 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:9]: For additional context, this is how we do it on the template right now:
https://github.com/dotnet/aspnetcore/blob/93d741edb0fa195f59d13743c35d21ee59099fc1/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor#L32

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 13 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:133]: > Could you explain more about what's going on here? It looks as if we're using Navigation.HistoryEntryState as part of the user-facing UI now. Is that really where the error message string now lives?

Is it relevant where the message comes from? From the consuming side, you get the message passed down to you as a parameter, consumers don't know if it comes on the query string or on the history entry state.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 19 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs]: I have removed this.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs (hunk 18 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs:73]: I made the other constructor obsolete

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 15 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:279]: I have obsoleted the `SignOutManager` as part of this change.

File: src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor (hunk 21 above)
Comment (javiercn) [reply src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Shared/RedirectToLogin.razor:10]: For additional context, this is how we do it on the template right now:
https://github.com/dotnet/aspnetcore/blob/93d741edb0fa195f59d13743c35d21ee59099fc1/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/LoginDisplay.IndividualLocalAuth.razor#L32

**Comment by javiercn** [comment]
Updated

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 25]
```diff
@@ -0,0 +1,192 @@
...
+    {
+        ArgumentNullException.ThrowIfNull(name, nameof(name));
+        AdditionalRequestParameters ??= new();
+        return AdditionalRequestParameters.TryAdd(name, value);
+    }
+
+    /// <summary>
+    /// Tries to remove an existing additional parameter.
+    /// </summary>
+    public bool TryRemoveAdditionalParameter<TValue>(string name)
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:109]: Can the generic type param be removed on this method?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 7 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:150]: I see you've done those changes now. It looks totally reasonable to me.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 26]
```diff
@@ -0,0 +1,192 @@
...
+    [UnconditionalSuppressMessage(
+        "Trimming",
+        "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+        Justification = "Serializes 'InteractiveAuthenticationRequest' into a string")]
+    internal string ToState() => JsonSerializer.Serialize(this);
+
+    [UnconditionalSuppressMessage(
+        "Trimming",
+        "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+        Justification = "Deserializes InteractiveAuthenticationRequest")]
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:155]: That's not really a justification for why it's safe. My guess for the justification is something like "property setters are preserved by the Converter class, which in turn is preserved because [give reason]".

In fact now we come to it, is putting [JsonConverter(typeof(SomeType))] enough to preserve the members of SomeType?

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 27]
```diff
@@ -0,0 +1,192 @@
...
+    internal static InteractiveRequestOptions FromState(string state) => JsonSerializer.Deserialize<InteractiveRequestOptions>(state);
+
+    internal class Converter : JsonConverter<InteractiveRequestOptions>
+    {
+        [UnconditionalSuppressMessage(
+            "Trimming",
+            "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+            Justification = "Serializes InteractiveAuthenticationRequest")]
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:163]: That's not really a justification :) But also, I don't see `RequiresUnreferencedCodeAttribute` on this method, so why is it necessary to suppress anything here? Same question on `Write` below.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 28]
```diff
@@ -0,0 +1,192 @@
...
+        "Trimming",
+        "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+        Justification = "Serializes 'InteractiveAuthenticationRequest' into a string")]
+    internal string ToState() => JsonSerializer.Serialize(this);
+
+    [UnconditionalSuppressMessage(
+        "Trimming",
+        "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+        Justification = "Deserializes InteractiveAuthenticationRequest")]
+    internal static InteractiveRequestOptions FromState(string state) => JsonSerializer.Deserialize<InteractiveRequestOptions>(state);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:156]: You might be able to avoid all these problems with linker warnings and suppressions if you use the source-generated version of JSON serialization instead. That's what it's there for.

For example, declare a type like 

```cs
// Our custom JSON serializer context that generates code to serialize
// arrays of planets so that we can use it with our HTTP endpoint.
[JsonSerializable(typeof(InteractiveRequestOptions))]
public partial class InteractiveRequestOptionsSerializerContext : JsonSerializerContext
{
}
```

... and then when calling JsonSerializer.Deserialize or JsonSerializer.Serialize, pass an instance of InteractiveRequestOptionsSerializerContext as the "context" argument.

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:156]: More examples: https://blog.martincostello.com/using-json-source-generators-with-aspnet-core-minimal-apis/

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs [hunk 29]
```diff
@@ -0,0 +1,192 @@
...
+                Interaction = requestOptions.Interaction,
+                ReturnUrl = requestOptions.ReturnUrl,
+                Scopes = requestOptions.Scopes,
+            };
+        }
+
+        [UnconditionalSuppressMessage(
+            "Trimming",
+            "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
+            Justification = "Serializes InteractiveAuthenticationRequest")]
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:180]: Not a justification

File: src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs (hunk 10 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/NavigationManagerExtensions.cs:9]: Understood - thanks for clarifying. The template example looks totally reasonable.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs (hunk 13 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs:133]: OK, it's fine. Can't remember what I was concerned about here.

**Review by SteveSandersonMS — APPROVED** [review]
Looks great!

I think there are still a few details about the JSON serialization trimming suppressions to be solved (preferably by switching to use the source generator - that *should* make things much simpler for you).

Besides that everything looks good so I'll approve now.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 26 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I have updated this area to make sure the members are preserved.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 27 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I have updated the attributes as long as the descriptions here. The culprit here is `JsonSerializer.Serialize` and I have just followed the same approach we do for other types we pass down to json.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 28 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs:99]: If this can be done internally, then we can definitely do that, let me see if I can make it work.

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 29 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I switched to use the serialization context

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 28 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I switched to use the serialization context

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 27 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I switched to use the serialization context

File: src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs (hunk 26 above)
Comment (javiercn) [reply src/Components/WebAssembly/WebAssembly.Authentication/src/Models/InteractiveRequestOptions.cs]: I switched to use the serialization context
