### PR TITLE
[Blazor] Fix antiforgery not being available after first render

### LINKED ISSUE #54533: Antiforgery state doesn't always reach interactive components
Repro:

* Create a Blazor Web App with global WebAssembly interactivity, and "include sample pages"
* Edit `Counter.razor` to include a form

```
<form method="post">
    <AntiforgeryToken />
</form>
```

* Launch the app
* Verify that if you first land on the homepage, then do a client-side navigation to Counter, that the form does **not** contain any `__RequestVerificationToken` hidden field (see this using the DOM inspector)
* Now reload the page while you're on Counter, so that's where you first land. Verify that the form **does** contain the `__RequestVerificationToken` hidden field. Even if you navigate away and back interactively, it will still be there

This inconsistency can't be desirable. Whether or not there's an antiforgery token shouldn't depend on which page you first arrived at.

Also note this is **not** a matter of prerendering. The exact same problem still occurs even if you disable prerendering.

You can work around it by adding `<AntiforgeryToken />` into your layout. The fact that this workaround works suggests that the problem is:

 * We only use the persisted component state during the first WebAssembly render cycle
 * If there isn't an `<AntiforgeryToken />` on the first WebAssembly render cycle, the persisted antiforgery state just gets discarded

I guess we could special-case things for antiforgery by ensuring the WebAssembly renderer *always* reads that state on the first render. Not sure if an equivalent problem could occur for other persistent component state (perhaps not, because app-specific persistent state would only exist if a component is prerendered to emit it, and then the same component should occur during the WebAssembly startup to collect that state - so maybe this bug is just unique to antiforgery data).

### PR DESCRIPTION
**Pull request by javiercn**
Fixes #54533

### CODE REVIEW

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 1]
```diff
@@ -802,6 +804,12 @@ private async Task TryNotifyClientErrorAsync(IClientProxy client, string error,
         });
     }
 
+    private static void RestoreAntiforgeryToken(AsyncServiceScope scope)
+    {
+        var antiforgery = scope.ServiceProvider.GetService<AntiforgeryStateProvider>();
+        _ = antiforgery?.GetAntiforgeryToken();
+    }
+
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitHost.cs:812]: Trying to retrieve the token during the initial render so that we capture it.

Comment (MackinnonBuck) [reply src/Components/Server/src/Circuits/CircuitHost.cs:812]: I don't think I understand why `GetAntiforgeryToken()` needs to be invoked. Does it have some side effect we rely on? If it's an `EndpointAntiforgeryStateProvider`, are we calling `GetAntiforgeryToken()` because it calls `IAntiforgery.GetAndStoreTokens(_context)`?

Would it be possible to directly invoke the missing functionality here rather than relying on `GetAntiforgeryToken()` having a specific implementation? If not, I think it might be worth adding a comment that explains what's going on and why it's correct.

File: src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs [hunk 2]
```diff
@@ -230,4 +233,11 @@ private static void AddWebRootComponents(WebAssemblyRenderer renderer, RootCompo
 
         renderer.NotifyEndUpdateRootComponents(operationBatch.BatchId);
     }
+
+    private void RestoreAntiforgeryToken()
+    {
+        // The act of instantiating the DefaultAntiforgeryStateProvider will automatically
+        // will retrieve the antiforgery token from the persistent state
```
Comment (MackinnonBuck) [inline src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs:240]:
```suggestion
        // The act of instantiating the DefaultAntiforgeryStateProvider will automatically
        // retrieve the antiforgery token from the persistent state
```

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs:812]: Calling `GetAntiforgeryToken` forces the token to be populated. I think it's best if we just call `GetAntiforgeryToken` rather than trying to do something more sophisticated.

> GetAntiforgeryToken() because it calls IAntiforgery.GetAndStoreTokens(_context)?

It does not, in interactive cases it restores the token from persistent component state, but it does so at the time GetAntiforgeryToken is invoked. Since this component is responsible for storing it, it should be responsible for restoring it.

Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: I've added a comment

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 3]
```diff
@@ -802,6 +804,15 @@ private async Task TryNotifyClientErrorAsync(IClientProxy client, string error,
         });
     }
 
+    private static void RestoreAntiforgeryToken(AsyncServiceScope scope)
+    {
+        // GetAntiforgeryToken makes sure the antiforgery token is restored from persitent component
+        // state and is available on the circuit whether or not is used by a component on the first
+        // render.
```
Comment (halter73) [inline src/Components/Server/src/Circuits/CircuitHost.cs:811]: I'm glad to see this logic only pulls the token from persistent component state and will never end up re-invoking the `IAntiforgery` service. I'm guessing we're relying on nothing calling `SetRequestContext` in the interactive scope. Is there an easy way to verify the `IAntiforgery` isn't reused in a test?

**Review by halter73 — APPROVED** [review]
The fact that even we run into these kinds of bugs when trying to use `PersistentComponentState` from our `AntiforgeryToken` component, makes me think we should raise the priority of #51584.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs:811]: Not really, we are the ones calling it in any case.
