### PR TITLE
Pass serialization exceptions to Hub disconnect

### LINKED ISSUE #21315: SignalR server hub: an exception thrown during result serialization will not appear in Hub.OnDisconnectedAsync
### Describe the bug

If an exception occurs during serialization of the invocation result (in custom converter or result property getter), the connection will be closed without this exception, and witout any exception at all (`Hub.OnDisconnectedAsync(null)`). The only information of this exception can be found in logs, but with Debug level for category Microsoft.AspNetCore.SignalR.HubConnectionContext. But this is obvious a server bug, so it may be expected to receive an exception in OnDisconnectedAsync and/or to find a Warning in logs.

Also reproduces for stream results.

### To Reproduce

https://gist.github.com/dlyz/c5fcb59c30d2d35f24659425e4f330ab

### Further technical details

- ASP.NET Core 3.1 and 5.0-preview3

### Additional thoughts

The situation with exceptions that occur during invocation arguments binding is much more complicated. I believe there is no way to distinguish a server bug and a protocol violation. It leads to invocation fail, the connection remains fine (don't know about stream arguments), and it totally makes sense. However, it is hard to diagnose this kind of problems, because the client gets generic exception like "Failed to invoke 'DoWork' due to an error on the server." and the server still logs with Debug level.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/21315

### CODE REVIEW

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 1]
```diff
@@ -336,6 +343,7 @@ private async Task TryWritePingSlowAsync()
             }
             catch (Exception ex)
             {
+                CloseException = ex;
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs:346]: Ping failures too?

Comment (davidfowl) [reply src/SignalR/server/Core/src/HubConnectionContext.cs:346]: I guess this makes sense.

**Review by davidfowl — APPROVED** [review]
