### PR TITLE
Remove application error

### LINKED ISSUE #12946: Response.OnCompleted exceptions not caught when hosted InProcess
Issue #2170 has been reported on this same topic and has been fixed. But now with the InProcess hosting model the same problem exists again. 

Using ASP.NET Core 2.2 using `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`
A simple code like this shows the issue:

```
public async Task<IActionResult> TestOnComplete()
{
        Response.OnCompleted(async () =>
        {
            throw new Exception();
        });
}
```
Response.OnCompleted is said to be invoked after the response is sent to the user, so the user should already have got the answer, whatever happens there.

https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/HttpResponse.cs#L87

```
        /// <summary>
        /// Adds a delegate to be invoked after the response has finished being sent to the client.
        /// </summary>
        /// <param name="callback">The delegate to invoke.</param>
        /// <param name="state">A state object to capture and pass back to the delegate.</param>
        public abstract void OnCompleted(Func<object, Task> callback, object state);
```
But this breaks the response. You can also set a breakpoint on the OnComplete action, the user will wait for the response until the breakpoint is passed.

This means that the OnCompleted is fired before the response is actually sent.

Now, by setting `<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>`, the issue is no longer present and the OnComplete action is executed after the response is send.

While fixing #2170 the file https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L692 has been changed to `await FireOnCompleted();` after calling `await ProduceEnd();` It seems that this still happens for OutOfProcessing. 
While the InProcess model uses https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IIS/src/Core/IISHttpContextOfT.cs#L61 where the `await FireOnCompleted();` is still called before `await ProduceEnd();`

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/dotnet/aspnetcore/issues/12946

This ended up being fixed via https://github.com/dotnet/aspnetcore/pull/24686, but adding a test and also not reporting an application exception to future proof any issues.

### CODE REVIEW

File: src/Servers/IIS/IIS/test/testassets/InProcessWebSite/Startup.cs [hunk 1]
```diff
@@ -1461,6 +1461,16 @@ public Task IncreaseRequestLimit(HttpContext httpContext)
             return Task.CompletedTask;
         }
 
+        public Task OnCompleted(HttpContext httpContext)
```
Comment (Tratcher) [inline src/Servers/IIS/IIS/test/testassets/InProcessWebSite/Startup.cs:1464]:
```suggestion
        public Task OnCompletedThrows(HttpContext httpContext)
```

**Review by Tratcher — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]
