### PR TITLE
Make preventDefault and stopPropagation event flags work without handler on the page

### LINKED ISSUE #18449: @onevent:preventDefault does not trigger when event is not already registered
When using the new `@onevent:preventDefault` directive to prevent the default event behavior for events, I noticed that in order for this to work, there needs to be a `@onevent` handler registered *anywhere* on the page.

Apparently, server-side Blazor registers every event just once on the document instead of on individual elements. So e.g. `@onclick="…"` causes the `click` event to be subscribed on the document. Just using `@onclick:preventDefault` on the page does not appear to register this global event handler on document, so the `preventDefault()` call is also never made in the handler.

My use case for this is managing focus with buttons: When you click a button, then the button stays focused after clicking it, causing the focused style to be applied. In order to avoid this, you can subscribe to the `mousedown` event in JavaScript and just prevent the default behavior:

```html
<button id="test">Test</button>
<script>
    var button = document.getElementById('test')
    button.addEventListener('click', () => console.log('Clicked'));
    button.addEventListener('mousedown', (evt) => evt.preventDefault());
</script>
```

Doing the same in Blazor would look like this:

```cshtml
<button @onclick="Click" @onmousedown:preventDefault>Test</button>

@code {
    void Click() => Console.WriteLine("Click");
}
```

This however does not work if there isn’t also some `mousedown` handler registered somewhere. As soon as you add one *literally anywhere*, it works:

```cshtml
<button @onclick="Click" @onmousedown:preventDefault>Test</button>
<div @onmousedown="() => { }"></div>

@code {
    void Click() => Console.WriteLine("Click");
}
```

This is using server-side Blazor on ASP.NET Core 3.1.

### LINKED ISSUE #24932: Blazor webassembly: @onwheel:preventDefault has no effect
### Describe the bug
Adding `@onwheel:preventDefault` attribute does not prevent the default scrolling behavior.

### To Reproduce
In Counter demo project, on Index page
```
<h1 @onwheel:preventDefault>Hello, world!</h1>
```
The page still bumps up or down when I perform two fingers scroll gesture which indicates that the event was not suppressed.

### Further technical details
Counter demo project on mac from command line. Versions:
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-preview.7.20365.19" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-preview.7.20365.19" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-preview.7.20364.11" />
```

### Workarouond
interop.js:
```js
window.myUtils = {
    addDefaultPreventingHandler: function (element, eventName) {
        element.addEventListener(eventName, e => e.preventDefault(), { passive: false });
    }
};
```
the page:
```cs
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
        await jsRuntime.InvokeVoidAsync("myUtils.addDefaultPreventingHandler", myElementReference, "wheel");
}
```

Possibly blazor does not set the `passive` option correctly when it adds its event listener. It should disable the scroll optimization by setting `passive: false` when `@on<EVENT>:preventDefault` is present for a scrolling event in the razor markup.

### PR DESCRIPTION
**Pull request by oroztocil**
## Investigation

Browser event handling in Blazor is "virtualized". If there is at least one C# event handler for some event on the page, the client-side Blazor code registers a global JS listener. When the event is processed by the listener, Blazor iterates over targeted DOM elements and when it finds a registered handler, it invokes the appropriate .NET code via interop. The important detail here is that if there is no C# handler for the event on the page, this event gets ingored by Blazor.

At the same time, support for `@on{eventName}:preventDefault` and `@on{eventName}:stopPropagation` attributes is implemented by setting up "flags" on elements. A flag value is set when the renderer handles a special internal attibute on the element (e.g. `__internal_preventDefault_{eventName}`).

The flags then get checked when the element is iterated over by the global listener for the event. If an element has the `preventDefault` flag set, Blazor calls `preventDefault` on the browser event. Similarly, Blazor stops iterating over parent elements if it encounters an element with the `stopPropagation` flag set.

However, if no handler is registered for the event on the page, the global listener does not get set up and the flags are never checked.

Furthemore, since the global listener is registered without specifying the `passive` property, it is either active or passive depending on the type of the event. For certain events, namely wheel and touch events, the default is `passive: true` (as an UX optimization). Due to this, Blazor's `preventDefault` flag does nothing for these events.

## Solution

When we set the flag to true for an element, we ensure that the global listener for the browser event is added by calling `addGlobalListener(eventName)` while applying the internal attribute. This either registers a new listener (if there was none), or increments the `countByEventName[eventName]` value.

We also register this listener with explicit `passive: false` while processing the `preventDefault` flag, to ensure that it works for all events. We can set this explicitly to `false` for all events because other event types have this as default anyway.

## Cleaning up unused global listeners

What complicates things is that, ideally, we would want to remove the global listener when there are no actual handlers for that event AND no event flags. That is, we would like to decrement `countByEventName[eventName]` when an event flag is no longer applied - in all situations, including the removal of the parent element.

The fact that an event handler got removed is signalled to the client-side directly in the `RenderBatch` via `DisposedEventHandlerIDs`. There is no equivalent for event flag attributes as those are not tracked by the .NET side. (They are directly emitted on the elements as the internal attributes and forgotten.) That means that if the entire element with the event flag (or some parent section of the DOM) gets removed, the client-side gets no notification that the removed frames included the internal attribute.

**Update:**

Not cleaning up the global listener for an event is a minor issue that happens only in a specific scenario, i.e. the page contains the `preventDefault` flag and all of the elements with a handler or event flag for that event are later removed. Therefore, we decided to not handle such situation in order to not over-complicate the implementation. In cases where the `preventDefault` flag is removed due to the value of its condition changing, the listener gets properly cleaned up. (And users can therefore ensure this by disabling the flag before removing the element from the page, if they really care about the listener potentially being left behind.)

Fixes #18449
Fixes #24932

### CODE REVIEW

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs [hunk 1]
```diff
@@ -1022,9 +1022,16 @@ private static void DisposeFramesInRange(RenderBatchBuilder batchBuilder, int co
...
+            else if (frame.FrameTypeField == RenderTreeFrameType.Attribute)
             {
-                batchBuilder.DisposedEventHandlerIds.Append(frame.AttributeEventHandlerIdField);
+                if (frame.AttributeEventHandlerIdField > 0)
+                {
+                    batchBuilder.DisposedEventHandlerIds.Append(frame.AttributeEventHandlerIdField);
+                }
+                else if (frame.AttributeValueField is bool boolValue && boolValue && frame.AttributeNameField.StartsWith("__internal_", StringComparison.Ordinal))
+                {
+                    batchBuilder.EditsBuffer.Append(RenderTreeEdit.RemoveAttribute(siblingIndex, frame.AttributeNameField));
```
Comment (oroztocil) [inline src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs:1033]: This would be the controversial bit I expect.

Comment (oroztocil) [inline src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs]: This would be the controversial bit I expect.

File: src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts [hunk 2]
```diff
@@ -121,6 +121,11 @@ export class EventDelegator {
       for (const handlerInfo of infosForElement.enumerateHandlers()) {
         this.eventInfoStore.remove(handlerInfo.eventHandlerId);
       }
+
+      for (const eventName of infosForElement.enumeratedEventNamesForEnabledFlags()) {
+        this.eventInfoStore.decrementCountByEventName(eventName);
+      }
```
Comment (oroztocil) [inline src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts]: I am not 100% sure this part is needed. It is possible that the internal attributes/flags would be all cleaned up (and therefore set to false) already.

File: src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs]: What would happen if we were to register a bogus event handler instead? (let's say we see onevent:preventDefault) without an associated `onevent`.

What would happen if we `assumed` a default `onevent` like `@onclick="() => {}`?

Comment (oroztocil) [reply src/Components/Components/src/RenderTree/RenderTreeDiffBuilder.cs]: I have removed the .NET-side changes altogether. See comment below for more details.

**Comment by oroztocil** [comment]
@javiercn Following our discussion about simplicity and "special casing", I decided to go with the client-side only solution. These are my reasons:

- This solution does not increase special casing - it uses the existing special casing in the form of the `setPreventDefault` and `setStopPropagation` methods on the `EventDelegator`.
- The changes are limited to the client-side, no .NET changes.
- No unneeded interop calls.

I also added setting the listener for events with `preventDefault` flag as `passive: false` (this changes behavior only for events that would otherwise ignore the flag, the rest already had this by default), and I added E2E tests.

File: src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts [hunk 3]
```diff
@@ -135,12 +136,30 @@ export class EventDelegator {
...
+    }
   }
 
   public setPreventDefault(element: Element, eventName: string, value: boolean): void {
     const infoForElement = this.getEventHandlerInfosForElement(element, true)!;
+    const currentValue = infoForElement.preventDefault(eventName);
     infoForElement.preventDefault(eventName, value);
+
+    if (!currentValue && value) {
+      // To ensure that preventDefault works for wheel and touch events,,
```
Comment (pavelsavara) [inline src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts:155]: does this have perf implications ? I imagine sending too many events to interactive server could be bad idea.

Comment (oroztocil) [reply src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts:155]: What do you mean by "this"? :-) Of course having a C# handler for a mouse scroll event has perf implications but that was always the case. This just enables `preventDefault` (i.e. supressing local browser event handling) for these events as requested [here](https://github.com/dotnet/aspnetcore/issues/24932).

Comment (oroztocil) [reply src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts:155]: After this PR you actually do not need any C# handler for an event on the page in order to get `preventDefault` working for that event. So this can, in fact, improve perf by not forcing people to use empty C# handlers that lead to uneeded interop calls - if they only need the `preventDefault` behavior. (This used to be needed as a workaround as documented in https://github.com/dotnet/aspnetcore/issues/18449).

Comment (pavelsavara) [reply src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts:155]: thanks

**Review by pavelsavara — APPROVED** [review]

**Review by ilonatommy — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

**Review by javiercn — APPROVED** [review]
Looks great!

Solid work @oroztocil!
