### PR TITLE
Check for sentinel value when setting HTTP/3 error code

### LINKED ISSUE #57933: Critical log on quic connection timeout
Toy repro:  launch server, launch client, wait ~20 seconds

Server
```csharp
using Microsoft.AspNetCore.Server.Kestrel.Core;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenLocalhost(5001, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http3;
        listenOptions.UseHttps();
    });

    options.Limits.KeepAliveTimeout = TimeSpan.FromSeconds(5);
});

var app = builder.Build();

app.MapGet("/", () => "Hello, world!");

app.Run();
```

Client
```csharp
using var client = new HttpClient()
{
    BaseAddress = new Uri("https://localhost:5001"),
    DefaultRequestVersion = new Version(3, 0),
    DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact,
};

try
{
    var response = await client.GetAsync("/");
    response.EnsureSuccessStatusCode();

    var data = await response.Content.ReadAsStringAsync();
    Console.WriteLine(data);
}
catch (HttpRequestException e)
{
    Console.WriteLine($"Request error: {e.Message}");
}
```

_Originally posted by @amcasey in https://github.com/dotnet/aspnetcore/issues/45105#issuecomment-2357056749_

### PR DESCRIPTION
**Pull request by amcasey**
If no error code has been set, `IProtocolErrorFeature.Error` will be `-1`.  If we pass that through verbatim, it will be caught by validation in the setter (ironically, of the same property on the same feature object), resulting in an exception and a Critical (but apparently benign) log message.

Fixes #57933

### CODE REVIEW

**Comment by amcasey** [comment]
This needs a regression test, but I figured I'd run the approach by people before figuring out how to reliably simulate connection timeouts.

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs [hunk 1]
```diff
@@ -546,7 +546,8 @@ public async Task ProcessRequestsAsync<TContext>(IHttpApplication<TContext> appl
                 }
 
                 // Complete
-                Abort(CreateConnectionAbortError(error, clientAbort), (Http3ErrorCode)_errorCodeFeature.Error, reason);
+                var errorCode = _errorCodeFeature.Error == -1 ? Http3ErrorCode.NoError : (Http3ErrorCode)_errorCodeFeature.Error;
```
Comment (amcasey) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:549]: Log that we're replacing the error code.

**Comment by halter73** [comment]
Seems good to me. I see that we're calling `QuicTransportOptions.ValidateErrorCode` everywhere you can manually set the error code, and the `IProtocolErrorCodeFeature.Error` doc comment indicates "The property returns -1 if the error code hasn't been set."

Do we plan to backport this?

**Comment by adityamandaleeka** [comment]
If the critical message is indeed benign, this seems fine to fix in 9.0 servicing to me.

**Comment by amcasey** [comment]
I was going to propose reverting https://github.com/dotnet/aspnetcore/pull/55282 as a safer fix (since it was made to prevent a benign assert in S.N.Q), but I see from the description of that PR that S.N.Q. probably made checks stricter once we stopped passing them bad data, so a forward fix may be our only option.

**Comment by amcasey** [comment]
Hmm, it looks like we were expecting to hit this handler when the connection timed out:
https://amcasey@github.com/amcasey/aspnetcore/blob/d87133f31ae740a2df73e322ea4bdc2705b843d2/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs#L162

**Comment by halter73** [comment]
> Hmm, it looks like we were expecting to hit this handler when the connection timed out:
> 
> https://github.com/dotnet/aspnetcore/blob/d87133f31ae740a2df73e322ea4bdc2705b843d2/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs#L162

I don't think this is the same thing as a keep alive timeout. `QuicError.ConnectionTimeout` seems to be about a transport-level timeout ["waiting for a response from the peer."](https://github.com/dotnet/runtime/blob/bef6d5aadc5a8809d2c555de8f58e3d6afac91d9/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicError.cs#L32). The comment below also seems to indicate that the peer is unresponsive after opening a stream without closing it. This is not a scenario where a keep alive timeout would apply.

https://github.com/dotnet/aspnetcore/blob/d87133f31ae740a2df73e322ea4bdc2705b843d2/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs#L166-L167

What are we actually seeing for a keep alive timeout? Given that we appear to cancel the token passed into `QuicConnectionContext.AcceptAsync` in `StopProcessingNextRequest` which is what we should be calling in the event of a keep alive timeout, I'd expect an OCE which we appear to handle properly.

https://github.com/dotnet/aspnetcore/blob/d05f3586adc0439595436ff6b8677548302fd64d/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs#L123-L124

@JamesNK Does that line up with your expectations?

**Comment by amcasey** [comment]
I was in the debug-only catch-all block and the code was `ConnectionIdle`.  I haven't seen it since that first time though.

**Comment by amcasey** [comment]
Anecdata:
```csharp
var client = new HttpClient()
{
    BaseAddress = new Uri("https://localhost:5001"),
    DefaultRequestVersion = new Version(3, 0),
    DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact,
};

try
{
    var response = await client.GetAsync("/");
    response.EnsureSuccessStatusCode();

    var data = await response.Content.ReadAsStringAsync();
    Console.WriteLine(data);
}
catch (HttpRequestException e)
{
    Console.WriteLine($"Request error: {e.Message}");
}

//Thread.Sleep(TimeSpan.FromSeconds(30)); // ConnectionIdle with Sleep, ConnectionTimeout without
client.Dispose();
```

**Comment by halter73** [comment]
Interesting. I wouldn't have expected `QuicError.ConnectionIdle` considering we try to disable that here:

https://github.com/dotnet/aspnetcore/blob/d05f3586adc0439595436ff6b8677548302fd64d/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs#L89

**Comment by amcasey** [comment]
I'm having trouble figuring out whether the unexpected `ConnectionIdle` exception is related.  I don't think so, since we also need to fix up `-1` in the `ConnectionTimeout` case?  Should I just file a separate issue to investigate that later or is it worth pursuing now in case something in Quic change?

**Comment by amcasey** [comment]
FWIW, S.N.Q is getting it via native callback, presumably from msquic:
```csharp
>	System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(ref Microsoft.Quic.QUIC_CONNECTION_EVENT._Anonymous_e__Union._SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct) Line 659	C#
 	System.Net.Quic.QuicConnection.HandleConnectionEvent(ref Microsoft.Quic.QUIC_CONNECTION_EVENT) Line 761	C#
 	System.Net.Quic.QuicConnection.NativeCallback(Microsoft.Quic.QUIC_HANDLE*, void*, Microsoft.Quic.QUIC_CONNECTION_EVENT*) Line 796	C#
```

**Comment by amcasey** [comment]
If the exception occurs, these lines won't be executed
```csharp
KestrelMetrics.AddConnectionEndReason(MetricsContext, reason);

if (TryStopAcceptingStreams())
{
    SendGoAwayAsync(GetCurrentGoAwayStreamId()).Preserve();
}

_multiplexedContext.Abort(ex);
```

Losing the metric is a bummer, but not shipblocking (IMO).
`TryStopAcceptingStreams` should already have been called [here](https://github.com/dotnet/aspnetcore/blob/d05f3586adc0439595436ff6b8677548302fd64d/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs#L502)
`QuicConnectionContext.Abort` appears to already have been called [here](https://github.com/dotnet/aspnetcore/blob/d05f3586adc0439595436ff6b8677548302fd64d/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs#L170)

Then, in `ProcessRequestsAsync`, we lose
```csharp
// Wait for active requests to complete.
while (_activeRequestCount > 0)
{
    await _streamCompletionAwaitable;
}

TimeoutControl.CancelTimeout();
```

I'm guessing, but haven't verified, that the stream count has to be zero for the connection to time out?
I'm guessing, but haven't verified, that not cancelling the timeout is suboptimal but harmless.

**Comment by amcasey** [comment]
I set this in the repro server, but it doesn't seem to actually matter - the connection times out after ~20 seconds regardless.
```csharp
options.Limits.KeepAliveTimeout = TimeSpan.FromSeconds(5);
```

File: src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs [hunk 2]
```diff
@@ -923,6 +925,11 @@ internal WebTransportSession OpenNewWebTransportSession(Http3Stream http3Stream)
         return session;
     }
 
+    private Http3ErrorCode GetErrorCodeOrNoError()
+    {
+        return _errorCodeFeature.Error <= 0 ? Http3ErrorCode.NoError : (Http3ErrorCode)_errorCodeFeature.Error;
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:930]: Will it be something other than -1 by default? I'd special case that value as getting defaulted to `Http3ErrorCode.NoError`. If someone explicitly sets an invalid value using the feature then they can get an error.
```suggestion
        // The default error value is -1. If it hasn't been changed before abort is called then default to HTTP/3's NoError value.
        return _errorCodeFeature.Error == -1 ? Http3ErrorCode.NoError : (Http3ErrorCode)_errorCodeFeature.Error;
```

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs]: I started with a comparison to `-1`, but I changed it because the other consumers check for `<= 0`.  I'd rather not update them this late though, so I guess we'll just live with the inconsistency in RC2.

**Comment by amcasey** [comment]
FYI @ManickaP that there are late changes in this area.  I don't expect S.N.Q to have to react, but any feedback would be welcome.

Any thoughts on [ConnectionIdle](https://github.com/dotnet/aspnetcore/pull/57934#issuecomment-2359195857) would also be appreciated.

**Comment by amcasey** [comment]
It seems unlikely that this change to `Http3Connection` broke `HttpClientHttp2InteropTests.ServerReset_BeforeRequestBody_ClientBodyThrows`.

**Review by JamesNK — APPROVED** [review]

**Comment by ManickaP** [comment]
> FYI @ManickaP that there are late changes in this area. I don't expect S.N.Q to have to react, but any feedback would be welcome.

Do you still need to differentiate the not-set `ErrorCode` state? If not, why don't you use `NoError` as default value instead of -1. Otherwise, LGTM.
 
> Any thoughts on [ConnectionIdle](https://github.com/dotnet/aspnetcore/pull/57934#issuecomment-2359195857) would also be appreciated.

But the client still has IdleTimeout set. It gets sent to the server in the connection settings and each side will set their idle timeout to the min of the 2 values: https://www.rfc-editor.org/rfc/rfc9000.html#name-idle-timeout.

**Comment by amcasey** [comment]
> Do you still need to differentiate the not-set ErrorCode state? If not, why don't you use NoError as default value instead of -1. Otherwise, LGTM.

I wondered the same thing - I'll investigate when we're not trying to squeeze it into RC2.

**Comment by amcasey** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/49780 to investigate the idle behavior.
