### PR TITLE
Setting the Description in a ProducesResponseTypeAttribute works correctly for Minimal API

### LINKED ISSUE #60518: Description parameter of ProducesResponseTypeAttribute does not work in minimal API app
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

A Description parameter was added to ProducesResponseTypeAttribute in .NET 10 to set the `description` field of the response in the generated OpenAPI document. This works fine in a controller-based app but does not seem to work in a Minimal API app.

### Expected Behavior

The ProducesResponseTypeAttribute, when placed on the delegate parameter of a minimal API app endpoint, should add a description to the response in the generated API.

```csharp
app.MapGet("/weatherforecast",
[ProducesResponseType<IEnumerable<WeatherForecast>>(StatusCodes.Status200OK, Description = "The service is healthy.")]
() =>
{
```

### Steps To Reproduce

I've reproduced the problem in the project in this repo:

https://github.com/mikekistler/ResponseDescription

The problem exists for both the OpenAPI generated at build time and the OpenAPI served from the /openapi/v1.json endpoint.

### Exceptions (if any)

_No response_

### .NET Version

10.0.100-preview.1.25104.26

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sander1095**
# Setting the Description in a ProducesResponseTypeAttribute works correctly for Minimal API

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Using `ProducesResponseType` with the `Description` property works with Minimal API

## Description

This PR fixes the issue where the description is not set in a Minimal API application:

```csharp
app.MapGet("/weatherforecast",
[ProducesResponseType<IEnumerable<WeatherForecast>>(StatusCodes.Status200OK, Description = "The service is healthy.")]
() =>
{
    return new Something();
}
```

This did work for Controllers AND for Minimal API's when the method body was empty. The tests sadly did not cover scenarios where the method body did have content.

This PR adds test cases in several places to check that the Description is added correctly to the OpenAPI document. It also fixes the underlying issues.

**Please perform a careful review of the tests in the ApiExlorer project**! I made some changes and am not 100% sure that the tests are 100% valid and represent real scenarios. 

Fixes #60518

### CODE REVIEW

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 1]
```diff
@@ -375,6 +375,9 @@ private static void AddSupportedResponseTypes(
                     apiResponseType.ApiResponseFormats.Add(defaultResponseFormat);
                 }
 
+                // We set the Description to the first non-null value we find that matches the status code.
+                apiResponseType.Description ??= responseMetadataTypes.FirstOrDefault(x => x.StatusCode == apiResponseType.StatusCode && x.Description is not null)?.Description;
```
Comment (captainsafia) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:379]: Is there a reason the existing logic in the ApiResponseTypeProvider doesn't handle this? That feels like the right place to do this instead of having to filter on the types returned by it to set the description.

Comment (captainsafia) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:379]: @sander1095 Thanks for digging into this and sharing detailed notes. Based on this analysis, I expect this option:

> I could change my code to use the LAST description it encounters in the list, in case multiple descriptions are set

To be the prefered one since it aligns most closely with the way metadata gets respected in other scenarios. We'll have to sanity check this implementation with multiple `ProducesResponseType` attributes on the same endpoint to make sure the additions only apply to the target type and status code.

Comment (sander1095) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: @captainsafia Done! See the latest commits

File: src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs [hunk 2]
```diff
@@ -375,6 +375,9 @@ private static void AddSupportedResponseTypes(
                     apiResponseType.ApiResponseFormats.Add(defaultResponseFormat);
                 }
 
+                // We set the Description to the LAST non-null value we find that matches the status code.
+                apiResponseType.Description ??= responseMetadataTypes.LastOrDefault(x => x.StatusCode == apiResponseType.StatusCode && x.Type == apiResponseType.Type && x.Description is not null)?.Description;
```
Comment (captainsafia) [inline src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs:379]: OK! I think I've grokked what is going on here. The handling is similar to what we do for `AddResponseContentTypes` above except that the implementation only picks the last match.

@sander1095 Thoughts on making this a bit obvious by creating a separate `ApplyDescription` local method that is implemented something like:

```csharp
private static string? GetMatchingResponseTypeDescription(IEnumerable<ApiResponseType> responseMetadataTypes, ApiResponseType apiResponseType)
{
    string? matchingDescription = null;
    foreach (var metadata in responseMetadataTypes)
    {
        if (metadata.StatusCode == apiResponseType.StatusCode && 
            metadata.Type == apiResponseType.Type && 
            metadata.Description is not null)
        {
            matchingDescription = metadata.Description;
        }
    }
    return matchingDescription;
}
 ```

The removal of the Linq helps make it a little bit easier to understand.

Comment (sander1095) [reply src/Mvc/Mvc.ApiExplorer/src/EndpointMetadataApiDescriptionProvider.cs]: Done

**Review by captainsafia — APPROVED** [review]
