### PR TITLE
Emit unhandled exception info via a single console.error call. Fixes #20280

### LINKED ISSUE #20280: Copying exceptions from the browser console is hard
If an unhandled exception occurs in a Blazor WebAssembly app it shows up in the browser console:

image

But copying this error information is pretty messy. If I try to just select and do a copy & paste I get something like this:

```
Failed to load resource: the server responded with a status of 500 ()
blazor.webassembly.js:1 ﻿crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Unhandled exception rendering component: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Error: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Function.createUserManager (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4664)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at async Function.init (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4124)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Error: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Function.createUserManager (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4664)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at async Function.init (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4124)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2dbdc40 + 0x0002c> in <filename unknown>:0 
...
```

Is there anyway we can make it easier and cleaner to report this error information?

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Previously we used `Console.Error.WriteLine`. However this is implemented as the stderr stream, which has no message framing, so the recipient has no way to know how successive lines correspond to the original `Console.Error.WriteLine` calls. So there's no way of putting the lines into groups, hence they each are treated as separate `console.error` calls, hence each line emits its own separate stack trace, leading to #20280.

The fix is to have a separate dedicated channel for unhandled exception info.

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs [hunk 1]
```diff
@@ -98,12 +98,7 @@ private void WriteMessage(LogLevel logLevel, string logName, int eventId, string
                             _jsRuntime.InvokeVoid("console.error", formattedMessage);
                             break;
                         case LogLevel.Critical:
-                            // Writing to Console.Error is even more severe than calling console.error,
-                            // because it also causes the error UI (gold bar) to appear. We use Console.Error
-                            // as the signal for triggering that because it's what the underlying dotnet.wasm
-                            // runtime will do if it encounters a truly severe error outside the Blazor
-                            // code paths.
-                            Console.Error.WriteLine(formattedMessage);
+                            _jsRuntime.InvokeVoid("Blazor._internal.dotNetCriticalError", formattedMessage);
```
Comment (pranavkm) [inline src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs:101]: Unmarshalled?

**Review by pranavkm — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

File: src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs]: OK, that's a good idea. Most times it will make no difference, but I guess if the exception is something like "S.T.J. is somehow completely broken" then we don't want to rely on S.T.J. during the reporting of that error.

Done.

**Review by captainsafia — APPROVED** [review]

**Comment by captainsafia** [comment]
Changed around the base branches so that the build on this can re-kick. I'll monitor this build.

**Comment by SteveSandersonMS** [comment]
Thanks @captainsafia! I've noticed a bug in the new E2E test in `stevesa/cdn` so this is going to fail on the current build. I'm making a fix in the underlying branch then will re-trigger this.

**Comment by captainsafia** [comment]
Merging this into the other branch now!
