### PR TITLE
Defer search for dev cert until build bind time

### LINKED ISSUE #45801: Kestrel config behaves differently when set using env vars vs. in-code
I have a Web API application that I want to configure it to listen on an HTTPS port. The app is containerized and orchestrated using Docker compose.

I can configure it by setting the following env variable in `docker-compose`, which works as expected.

```yaml
services:
  webapi:
    environment:
      - ASPNETCORE_URLS=https://+:443
```

However, when I use the following approach as an alternative to setting the environment variable, it fails with the following error message.

```csharp
builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(
    address: IPAddress.Any,
        port: 443,
        configure: listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
            listenOptions.UseHttps();
        });
});
```

> Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

When I provide the filename and password to the SSL certificate file as the following, it works as expected.

```csharp
builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(
    address: IPAddress.Any,
        port: 443,
        configure: listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
            listenOptions.UseHttps("/root/.aspnet/https/cert.pfx", "Password");
        });
});
```

I assume setting the environment variable `ASPNETCORE_URLS` or calling `ConfigureKestrel` are equivalent, though, I am not sure what I am missing in the second approach. 

### Update 
I was previously getting the following error, which was related to mapping the port `443` to an incorrect port of the container.

> Detected a TLS handshake to an endpoint that does not have TLS enabled.

### PR DESCRIPTION
**Pull request by amcasey**
...so that it can occur after `IConfiguration` is read.  (In particular, so that it occurs during `AddressBinder.BindAsync` which happens strictly after `KestrelConfigurationLoader.Load`.)  This is important in Docker scenarios since the Docker tools use `IConfiguration` to tell us where the dev cert directory is mounted.
    
Fixes #45801

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 1]
```diff
@@ -201,15 +189,34 @@ internal static bool TryUseHttps(this ListenOptions listenOptions)
...
+    /// <param name="listenOptions">The <see cref="ListenOptions"/> to configure.</param>
+    /// <param name="getHttpsOptions">A function returning options to configure HTTPS.</param>
+    /// <returns>The <see cref="ListenOptions"/>.</returns>
+    private static ListenOptions UseHttps(this ListenOptions listenOptions, Func<HttpsConnectionAdapterOptions> getHttpsOptions)
+    {
+        // Set this outside the lambda, which might not be invoked
         listenOptions.IsTls = true;
-        listenOptions.HttpsOptions = httpsOptions;
 
+        // NB: This lambda will only be invoked if either HTTP/1.* or HTTP/2 is being used
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:207]: What happens if there is an HTTP/3-only endpoint? Can it still pick up a certificate specified via UseHttps() now that listenOptions.HttpsOptions is only set in this non-HTTP/3 connection middleware?

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 2]
```diff
@@ -201,15 +192,31 @@ internal static bool TryUseHttps(this ListenOptions listenOptions)
...
-        listenOptions.HttpsOptions = httpsOptions;
+        listenOptions.HttpsOptions = lazyHttpsOptions;
 
+        // NB: This lambda will only be invoked if either HTTP/1.* or HTTP/2 is being used
         listenOptions.Use(next =>
         {
+            // Evaluate the HttpsConnectionAdapterOptions, now that the configuration, if any, has been loaded
+            var httpsOptions = listenOptions.HttpsOptions.Value;
             // Set the list of protocols from listen options
             httpsOptions.HttpProtocols = listenOptions.Protocols;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:216]: Doing this here would be an issue if the HTTP/3 logic needed to reference `HttpsOptions.HttpProtocols`. We could just pass the HttpProtocols directly to the middleware constructor and remove `HttpsOptions.HttpProtocols` to make it clear that this isn't needed for the HTTP/3 path. make it clear that this isn't needed. We could also just move this line into the lazy callback.

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs [hunk 3]
```diff
@@ -252,6 +258,110 @@ public void ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent()
...
+            serverOptions.ConfigurationLoader.Load();
+
+            Assert.NotNull(serverOptions.DefaultCertificate);
+            Assert.Equal(serverOptions.DefaultCertificate.SerialNumber, certificate.SerialNumber);
+
+            var ran1 = false;
+            serverOptions.ListenAnyIP(4545, listenOptions =>
+            {
+                ran1 = true;
+                listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
```
Comment (halter73) [inline src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:285]: This is no longer necessary, right?

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs [hunk 4]
```diff
@@ -252,6 +252,112 @@ public void ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent()
...
+                listenOptions.UseHttps();
+            });
+            Assert.True(ran1);
+
+            var config = new ConfigurationBuilder().AddInMemoryCollection(new[]
+            {
+                new KeyValuePair<string, string>("Certificates:Development:Password", "1234"),
```
Comment (halter73) [inline src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:331]: Since HTTP/3 was a little tricky to make work, can we add end-to-end tests for this scenario to [Http3TlsTests](https://github.com/dotnet/aspnetcore/blob/5a4a8e4b456ad82ab4c3bdb798b3a5f4e2fb9706/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs) where we verify that we can successfully bind and make requests in this scenario that does the docker-style dev cert loading instead of default cert loading. The Http3TlsTests require msquic support, so it might be easier to add a variant of [Http3_UseHttpsNoArgsWithDefaultCertificate_UseDefaultCertificate](
https://github.com/dotnet/aspnetcore/blob/5a4a8e4b456ad82ab4c3bdb798b3a5f4e2fb9706/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs#L409) instead. It should still be a little more end-to-end than these tests, but it uses a mock multiplexed transport and verifies the options flow correctly trhough BindAsync. I think adding a test to just one of these two test classes is fine. Do you have a preference @JamesNK?

For completeness, we could add a similar test [HttpsConnectionMiddlewareTests](https://github.com/dotnet/aspnetcore/blob/5a4a8e4b456ad82ab4c3bdb798b3a5f4e2fb9706/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsConnectionMiddlewareTests.cs#L60) to test the end-to-end given a non-multiplexed in-memory transport.

We should also assert that we're still actually running the callback in all our UseHttps() tests that assert inside the callback. I suspect there are a number of tests where this is no longer happening. For instance, there's `ConfigureHttpsDefaultsNeverLoadsDefaultCert`,

https://github.com/dotnet/aspnetcore/blob/5a4a8e4b456ad82ab4c3bdb798b3a5f4e2fb9706/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs#L109-L119

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 1 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:215]: It couldn't when you wrote this, but it can now.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 2 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs]: It is very hard to keep track of the source of truth for each of these properties and the order in which they need to be accessed.

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs (hunk 3 above)
Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs]: I copied this from the user repro.  Happy to simplify it or use the default, if that would be cleaner.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 2 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs]: To confirm, you're saying this was a problem with the code before my change, right?

File: src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs (hunk 4 above)
Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:329]: Did this part:
> We should also assert that we're still actually running the callback in all our UseHttps() tests that assert inside the callback

Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:326]: Think I did this part:
> add end-to-end tests for this scenario to [Http3TlsTests](https://github.com/dotnet/aspnetcore/blob/5a4a8e4b456ad82ab4c3bdb798b3a5f4e2fb9706/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs)

Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:326]: I did this as practice, but it's just a simpler version of the above, so I reverted it:
> add a variant of Http3_UseHttpsNoArgsWithDefaultCertificate_UseDefaultCertificate

Comment (amcasey) [reply src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:326]: Per our offline discussion, the current coverage seems adequate.

File: src/Servers/Kestrel/Core/src/ListenOptions.cs [hunk 5]
```diff
@@ -140,7 +140,8 @@ internal string Scheme
     }
 
     internal bool IsTls { get; set; }
-    internal HttpsConnectionAdapterOptions? HttpsOptions { get; set; }
+    /// <remarks>Should not be inspected until the configuration has been loaded.</remarks>
+    internal Lazy<HttpsConnectionAdapterOptions>? HttpsOptions { get; set; }
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: I should have caught this last time, but can we make this a func? This should be called again if the endpoint is rebound due to a default certificate change in config.

I think our best bet is keeping the old `internal HttpsConnectionAdapterOptions? HttpsOptions { get; set; }` property, but then also adding a `Func<HttpsConnectionAdapterOptions>` property called `CreateHttpsConnectionOptions` or something like that that we call in `KestrelServerImple.StartAsync+OnBind` and then set `HttpsOptions`.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 6]
```diff
@@ -201,15 +193,31 @@ internal static bool TryUseHttps(this ListenOptions listenOptions)
     /// <returns>The <see cref="ListenOptions"/>.</returns>
     public static ListenOptions UseHttps(this ListenOptions listenOptions, HttpsConnectionAdapterOptions httpsOptions)
     {
-        var loggerFactory = listenOptions.KestrelServerOptions?.ApplicationServices.GetRequiredService<ILoggerFactory>() ?? NullLoggerFactory.Instance;
+        return listenOptions.UseHttps(new Lazy<HttpsConnectionAdapterOptions>(() =>
+        {
+            httpsOptions.HttpProtocols = listenOptions.Protocols;
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:198]: Putting this assignment inside the Lazy callback still feels wrong. It seems like it'd be super easy to forget. It was easy to forget before, but at least it was only set in one place instead of two.

Let's add an HttpProtocols parameter to the internal HttpsConnectionMiddleware, pass it directly from ListenOptions, and delete HttpsConnectionAdapterOptions.HttpProtocols.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 7]
```diff
@@ -201,15 +193,31 @@ internal static bool TryUseHttps(this ListenOptions listenOptions)
...
 
+        // NB: This lambda will only be invoked if either HTTP/1.* or HTTP/2 is being used
         listenOptions.Use(next =>
         {
-            // Set the list of protocols from listen options
-            httpsOptions.HttpProtocols = listenOptions.Protocols;
+            // Evaluate the HttpsConnectionAdapterOptions, now that the configuration, if any, has been loaded
+            var httpsOptions = listenOptions.HttpsOptions.Value;
+            var loggerFactory = listenOptions.KestrelServerOptions?.ApplicationServices.GetRequiredService<ILoggerFactory>() ?? NullLoggerFactory.Instance;
             var middleware = new HttpsConnectionMiddleware(next, httpsOptions, loggerFactory);
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:221]:
```suggestion
            var middleware = new HttpsConnectionMiddleware(next, httpsOptions, listenOptions.Protocols, loggerFactory);
```

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs [hunk 8]
```diff
@@ -163,33 +163,25 @@ public static ListenOptions UseHttps(this ListenOptions listenOptions, Action<Ht
...
+            options.HttpProtocols = listenOptions.Protocols;
 
-        if (options.ServerCertificate == null && options.ServerCertificateSelector == null)
-        {
-            return false;
-        }
+            if (options.ServerCertificate == null && options.ServerCertificateSelector == null)
+            {
+                throw new InvalidOperationException(CoreStrings.NoCertSpecifiedNoDevelopmentCertificateFound);
+            }
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:181]: What's the old and new call stack for this exception? I worry that we're reducing visibility/immediacy of this exception to the caller so it will be harder to debug.

Can we at least run lines the first few lines before the lazy so we don't change their behavior/lifetime?
```
            var options = new HttpsConnectionAdapterOptions();
            listenOptions.KestrelServerOptions.ApplyHttpsDefaults(options);
            configureOptions(options);
            options.HttpProtocols = listenOptions.Protocols;
```

Comment (halter73) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:181]: The first thing `ApplyHttpsDefaults`, is a thing we want to delay, and this check has to come after that. I think this delays the error from when the host resolves the IServer until when it starts it. We should make sure exceptions still cause app.Run() to throw at startup, but I think having IServer.StartAsync throw is a fine way to achieve this.

Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:181]: I just want to make sure we know what the new failure mode looks like.

**Comment by amcasey** [comment]
Force-push is a trivial rebase.  Feedback to be addressed shortly.

File: src/Servers/Kestrel/Core/src/ListenOptions.cs (hunk 5 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: I'm not sure I understand the point about keeping the old property.  I think you're saying that consumers should be able to specify either an `HttpsConnectionAdapterOptions` or a `Func<HttpsConnectionAdapterOptions>`, which would make it unnecessary to wrap an already-in-hand object in a func, but that seems like an unimportant win in code that isn't perf sensitive and has the downside of requiring an understanding of which takes precedence if both are set.  But maybe you had some other reason in mind?

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 8 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:181]: Old
```
>	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions listenOptions, System.Action<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions> configureOptions) Line 186	C#
 	WebApplication51.dll!Program.<Main>$.AnonymousMethod__0_1(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions listenOptions) Line 11	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(System.Net.EndPoint endPoint, System.Action<Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions> configure) Line 435	C#
 	WebApplication51.dll!Program.<Main>$.AnonymousMethod__0_0(Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions options) Line 10	C#
 	Microsoft.Extensions.Options.dll!Microsoft.Extensions.Options.OptionsFactory<Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions>.Create(string name)	Unknown
 	Microsoft.Extensions.Options.dll!Microsoft.Extensions.Options.UnnamedOptionsManager<Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions>.Value.get()	Unknown
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions> options, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, System.Diagnostics.DiagnosticSource diagnosticSource) Line 110	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.KestrelServerImpl(Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions> options, System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Connections.IConnectionListenerFactory> transportFactories, System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Connections.IMultiplexedConnectionListenerFactory> multiplexedFactories, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, System.Diagnostics.DiagnosticSource diagnosticSource) Line 59	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, System.__Canon>.VisitCallSiteMain(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext argument)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, object>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext argument)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(System.Type serviceType)	Unknown
 	System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<System.Type, System.Func<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>>.GetOrAdd(System.Type key, System.Func<System.Type, System.Func<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, object>> valueFactory)	Unknown
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unknown
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.AspNetCore.Hosting.Server.IServer>(System.IServiceProvider provider)	Unknown
 	Microsoft.AspNetCore.dll!Microsoft.AspNetCore.Builder.WebApplication.ServerFeatures.get()	Unknown
 	Microsoft.AspNetCore.dll!Microsoft.AspNetCore.Builder.WebApplication.WebApplication(Microsoft.Extensions.Hosting.IHost host)	Unknown
 	Microsoft.AspNetCore.dll!Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()	Unknown
 	WebApplication51.dll!Program.<Main>$(string[] args) Line 15	C#
```

New
```
>	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps.AnonymousMethod__0() Line 180	C#
 	System.Private.CoreLib.dll!System.Lazy<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions>.ViaFactory(System.Threading.LazyThreadSafetyMode mode)	Unknown
 	System.Private.CoreLib.dll!System.Lazy<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions>.ExecutionAndPublication(System.LazyHelper executionAndPublication, bool useDefaultConstructor)	Unknown
 	System.Private.CoreLib.dll!System.Lazy<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions>.CreateValue()	Unknown
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps.AnonymousMethod__0(Microsoft.AspNetCore.Connections.ConnectionDelegate next) Line 219	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build() Line 201	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync.__OnBind|0(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions options, System.Threading.CancellationToken onBindCancellationToken) Line 206	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions endpoint, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext context, System.Threading.CancellationToken cancellationToken) Line 89	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext context, System.Threading.CancellationToken cancellationToken) Line 225	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext context, System.Threading.CancellationToken cancellationToken) Line 210	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.OverrideWithEndpointsStrategy.BindAsync(Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext context, System.Threading.CancellationToken cancellationToken) Line 193	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions> listenOptions, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext context, System.Threading.CancellationToken cancellationToken) Line 31	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(System.Threading.CancellationToken cancellationToken) Line 317	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync<Microsoft.AspNetCore.Hosting.HostingApplication.Context>(Microsoft.AspNetCore.Hosting.Server.IHttpApplication<Microsoft.AspNetCore.Hosting.HostingApplication.Context> application, System.Threading.CancellationToken cancellationToken) Line 237	C#
 	Microsoft.AspNetCore.Hosting.dll!Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(System.Threading.CancellationToken cancellationToken) Line 158	C#
 	Microsoft.Extensions.Hosting.dll!Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Extensions.Hosting.Abstractions.dll!Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost host, System.Threading.CancellationToken token)	Unknown
 	PlaintextApp.dll!PlaintextApp.Startup.Main(string[] args) Line 59	C#
 	PlaintextApp.dll!PlaintextApp.Startup.<Main>(string[] args)	Unknown
```

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:181]: AFAIK, we _can't_ check as early as we did because certs from config won't be loaded yet.

File: src/Servers/Kestrel/Core/src/ListenOptions.cs (hunk 5 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: I'm having trouble repro'ing a case where Func vs Lazy causes a problem - can you give me an example?  So far, when I try, the lazy gets clobbered with a fresh value here
```
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions listenOptions, System.Lazy<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions> lazyHttpsOptions) Line 213	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions listenOptions, Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions httpsOptions) Line 196	C#
>	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload() Line 373	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.RebindAsync() Line 352	C#
 	Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.TriggerRebind(object state) Line 330	C#
```

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 6 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs]: Always happy to store something in fewer places. :smile:

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 2 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs]: Now passing the protocols to the middleware directly.

File: src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs (hunk 8 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:180]: I'm taking thumbs-up to mean we're satisfied with the new experience.   It's a bit worse, but seems worthwhile to be able to pick up `IConfiguration` consistently.

File: src/Servers/Kestrel/Core/src/ListenOptions.cs (hunk 5 above)
Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: @halter73 I've resolved everything but this thread.   Can you please elaborate a bit on your concerns?

Comment (amcasey) [reply src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: Thinking about this some more, won't a `Lazy<HttpsConnectionAdapterOptions>` be clobbered on rebind, the same way a `HttpsConnectionAdapterOptions` was before my change?

Comment (halter73) [reply src/Servers/Kestrel/Core/src/ListenOptions.cs:144]: I think your right. I forgot that `KestrelConfigurationLoader.Reload` recreates both the ListenOptions and HttpsConnectionAdapterOptions from scratch. This looks good!

**Review by halter73 — APPROVED** [review]
