### PR TITLE
Renderer use-after-disposal tweaks. Fixes #13056

### LINKED ISSUE #13056: RemoteRenderer continues processing after Dispose
RemoteRenderer will continue to process its render queue after the renderer has been disposed.

Currently this will lead to exceptions inside [here](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/Circuits/RemoteRenderer.cs#L103) because the state of the base class has been disposed.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Adds two new behaviors:

 * The `Renderer` base class no longer allows subclasses to call `ProcessPendingRender` to start processing the render queue after disposal
 * The `Renderer` base class now ensures that when *components* try to render themselves after the renderer itself was disposed, this is a no-op and not an error

The first of those doesn't change the existing situation much - it would already have caused an `ObjectDisposedException` from the `ArrayBuilder`. The only change here is that the exception message is now clearer, since it states that the renderer was disposed.

The second one is important because this happens in normal user code (e.g., a component doing async work may request a render after the renderer was disposed), and we don't want this to throw.

### CODE REVIEW

File: src/Components/Components/src/Rendering/Renderer.cs [hunk 1]
```diff
@@ -717,6 +725,7 @@ protected virtual void Dispose(bool disposing)
                 }
             }
 
+            _componentStateById.Clear(); // So we know they were all disposed
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/Rendering/Renderer.cs]: We already had logic that no-ops a render request if the component was already disposed. Adding this line means that when the entire renderer itself is disposed, we treat all its components as being disposed (which they are) so the existing no-op logic takes care of it.

File: src/Components/Components/test/RendererTest.cs [hunk 2]
```diff
@@ -3936,7 +3971,7 @@ private void Render()
                 => _renderHandle.Render(builder =>
                 {
                     builder.OpenElement(0, "my button");
-                    builder.AddAttribute(1, "my click handler", new Action<EventArgs>(eventArgs => OnClick(eventArgs)));
+                    builder.AddAttribute(1, "onmycustomevent", EventCallback.Factory.Create(this, eventArgs => OnClick(eventArgs)));
```
Comment (SteveSandersonMS) [inline src/Components/Components/test/RendererTest.cs]: The unit test that uses this class was falsely passing (as in, it would pass whether or not the behavior it was trying to test was working) ever since the move to `EventCallback`. It's hard to discover false positives like this, but I temporarily removed some of the logic to discover which unit test was covering it, and it turned out that none of them were.

File: src/Components/Components/src/Rendering/Renderer.cs [hunk 3]
```diff
@@ -403,6 +404,11 @@ private ComponentState GetOptionalComponentState(int componentId)
         /// </summary>
         protected virtual void ProcessPendingRender()
         {
+            if (_disposed)
+            {
+                throw new ObjectDisposedException(nameof(Renderer), "Cannot process pending renders after the renderer has been disposed.");
+            }
+
```
Comment (javiercn) [inline src/Components/Components/src/Rendering/Renderer.cs]: Should we log something here and no-op instead? If I recall correctly we no-op in other cases. I'm concerned about getting an unhandled exception thrown from a weird place.

File: src/Components/Components/src/Rendering/Renderer.cs [hunk 4]
```diff
@@ -28,6 +28,7 @@ public abstract partial class Renderer : IDisposable
         private bool _isBatchInProgress;
         private ulong _lastEventHandlerId;
         private List<Task> _pendingTasks;
+        private bool _disposed;
```
Comment (javiercn) [inline src/Components/Components/src/Rendering/Renderer.cs]: Didn't we agree that we were making this concept available to subclasses?

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/Renderer.cs]: Am I correct in understanding that Dispose always run within the sync context?

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/Renderer.cs]: I think no-oping is safer as there might be legitimate scenarios where something got queued into the sync context and the context got disposed before it got a chance to execute (as things get serialized).

I think we need to at least check on the RemoteRenderer before we call ProcessPendingRender during OnRenderCompleted

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 4 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/Renderer.cs]: Ryan mentioned it as an idea, and we can do so if we want to.

Currently I don't think it's necessary. Subclasses can track their disposed state if they want to, and we can add a new protected API for this later if we want to.

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/Renderer.cs]: `CircuitHost` does call `Renderer.Dispose` from within an `Invoke` callback, so yes I think so. I'm not aware of other places where server-side Blazor disposes the renderer.

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/Renderer.cs]: > I think we need to at least check on the RemoteRenderer before we call ProcessPendingRender during OnRenderCompleted

Great point. Yes. I'm adding a check for that.

> Should we log something here and no-op instead?

Since we have no reason to believe it's at possible to make this happen through normal coding patterns, I'd be more interested in having a way of getting alerted if we're wrong and it does somehow happen.

If we can articulate definite scenarios where we want to support this I'm totally open to changing this though!

> I think no-oping is safer as there might be legitimate scenarios where something got queued into the sync context and the context got disposed before it got a chance to execute (as things get serialized).

Do you have specific scenarios in mind? The ones I'm aware of are:

 * If a component asks to be rendered - this already no-opped if the renderer (or component) was already disposed.
 * When adding a new root component. If the renderer was already disposed, I think it's good to throw, since it's so bizarre to be adding a new root component then. For normal server-side Blazor, the registered root component will be added immediately during host creation, so definitely before disposal.
 * When resuming the queue processing after an ACK, which will now be no-opped by the updated logic here.

**Comment by SteveSandersonMS** [comment]
@javiercn @rynowak @pranavkm Can one of you handle merging this? In my view this is OK to go in assuming the build passes. For the outstanding CR comments, I'm fine with you collectively deciding what to do if you want to change it further!

**Review by javiercn — APPROVED** [review]
Great changes!

File: src/Components/Components/src/Rendering/Renderer.cs (hunk 3 above)
Comment (javiercn) [reply src/Components/Components/src/Rendering/Renderer.cs]: I was a bit worried about the consequences of missing out a scenario more than anything and the potential consequences of it. Just wanted to be on the safer side.

File: src/Components/Components/src/Rendering/Renderer.cs [hunk 5]
```diff
@@ -696,6 +702,8 @@ private void UpdateRenderTreeToMatchClientState(ulong eventHandlerId, EventField
         /// <param name="disposing"><see langword="true"/> if this method is being invoked by <see cref="IDisposable.Dispose"/>, otherwise <see langword="false"/>.</param>
         protected virtual void Dispose(bool disposing)
         {
+            _disposed = true;
```
Comment (pranavkm) [inline src/Components/Components/src/Rendering/Renderer.cs]: Should we no-op everything after this if this has already been disposed? 

```C#
if (_disposed)
{
 return;
}

_disposed = true;
```

I realize everything after is safe from double-disposal (we clear the dictionary and the builder allows double-Dispose), but this makes it a lot clearer

File: src/Components/Server/src/Circuits/RemoteRenderer.cs [hunk 6]
```diff
@@ -284,7 +284,15 @@ public Task OnRenderCompleted(long incomingBatchId, string errorMessageOrNull)
                 // missing.
 
                 // We return the task in here, but the caller doesn't await it.
-                return Dispatcher.InvokeAsync(() => ProcessPendingRender());
+                return Dispatcher.InvokeAsync(() =>
+                {
+                    // Now we're on the sync context, check again whether we got disposed since this
+                    // work item was queued. If so there's nothing to do.
+                    if (!_disposing)
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/RemoteRenderer.cs]: 👍

**Review by pranavkm — APPROVED** [review]
