### PR TITLE
[Blazor wasm] Use provided loadBootResource function to override how config is loaded

### LINKED ISSUE #43700: Blazor WASM loading of appsettings.json config doesn't use provided `loadBootResource` function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We use CDN to serve Blazor WASM application. [Per documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#customize-how-boot-resources-are-loaded) `loadBootResource` function can be used to override default behavior of boot resources loading, e.g. modify URL or call `fetch` directly.

This works well except for `appsettings.json` or `appsettings.{environment}.json` files where `WebAssemblyConfigLoader` doesn't use provided `loadBootResource` and fetches configs directly instead. This results in `404 Not Found`.

Related code:
https://github.com/dotnet/aspnetcore/blob/190d5690d41272814564a33bfe41d08abeef2836/src/Components/Web.JS/src/Platform/WebAssemblyConfigLoader.ts#L24-L28

It's different from `WebAssemblyResourceLoader` implementation which relies on the provided `startOptions.loadBootResource`.

We would like to have the same amount of control over the loading of `appsettings.{environment}.json` config files.

### Expected Behavior

When Blazor script has `autostart="false"` attribute set and `loadBootResource` function is provided via `Blazor.start` options, then Blazor config loader should attempt to use this function.

### Steps To Reproduce

Repro: https://github.com/romansp/blazorwasmcdn 

This repro prints to the console the name of every resource that went through `loadBootResource` function.
1. Run repro with `dotnet run`.
2. Inspect browser developer console.

Notice that `appsettings.json` doesn't appear in the console logs but it has been fetched according to the `Network` tab of dev tools.

### Exceptions (if any)

_No response_

### .NET Version

6.0.400

### Anything else?

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### PR DESCRIPTION
**Pull request by romansp**
# [Blazor wasm] Use provided loadBootResource function to override how the config is loaded

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Use "loadBootResource" function to override how the config is loaded.

## Description
PR updates `WebAssemblyConfigLoader.initAsync` to use provided `loadBootResource` function from `startOptions` to override how the config is loaded in runtime. Allows loading config from a custom source, such as an external CDN. Providing similar behavior to loading of other boot resources.

I couldn't find any existing tests that cover current `loadBootResource` behavior for other resources. So, I didn't include any new tests. Though I see that `JsInitializersTest.cs` might be a good place for that? Let me know if these tests are expected and I will work on this too.  

Fixes #43700.

### CODE REVIEW

File: src/Components/Web.JS/src/Platform/WebAssemblyStartOptions.ts [hunk 1]
```diff
@@ -27,4 +27,4 @@ export interface WebAssemblyStartOptions {
 // This type doesn't have to align with anything in BootConfig.
 // Instead, this represents the public API through which certain aspects
 // of boot resource loading can be customized.
-export type WebAssemblyBootResourceType = 'assembly' | 'pdb' | 'dotnetjs' | 'dotnetwasm' | 'globalization' | 'manifest';
+export type WebAssemblyBootResourceType = 'assembly' | 'pdb' | 'dotnetjs' | 'dotnetwasm' | 'globalization' | 'manifest' | 'config';
```
Comment (javiercn) [inline src/Components/Web.JS/src/Platform/WebAssemblyStartOptions.ts:30]: Could we make the value 'configuration'?

Comment (romansp) [reply src/Components/Web.JS/src/Platform/WebAssemblyStartOptions.ts]: Sounds good, updated

**Review by javiercn — APPROVED** [review]
