### PR TITLE
Fix check for auth services in middleware auto-registration

### LINKED ISSUE #43188: Cannot add `scoped` AuthorizationHandler in .NET 7 Preview 7
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding a scoped `IAuthorizationHandler` works in `net6.0` but fails with and `InvalidOperationException` if upgraded to .NET 7 Preview 7.

Singleton `IAuthorizationHandler`s continue to work in .NET 7 Preview 7.

### Expected Behavior

I expect to be able to add a scoped `IAuthorizationHandler` - for example, a handler that depends on a `DbContext`.

### Steps To Reproduce

See https://github.com/frankbuckley/aspnet-7-scoped-authhandler-repro

In a new `net6.0` Web API project, add:

```c#
builder.Services.AddAuthentication();
builder.Services.AddAuthorization();
builder.Services.AddScoped<IAuthorizationHandler, MyAuthHandler>();

// ...

public class MyAuthHandler : IAuthorizationHandler
{
    public Task HandleAsync(AuthorizationHandlerContext context)
    {
        return Task.CompletedTask;
    }
}
```

Run. Starts OK.

Change to `<TargetFramework>net7.0</TargetFramework>`

Run. Fails with System.InvalidOperationException.

Change `AddScoped` to `AddSingleton`. Run. Starts OK.

### Exceptions (if any)

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot resolve 'Microsoft.AspNetCore.Authorization.IAuthorizationHandlerProvider' from root provider because it requires scoped service 'Microsoft.AspNetCore.Authorization.IAuthorizationHandler'.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.ConfigureApplication(WebHostBuilderContext context, IApplicationBuilder app)
   at Microsoft.WebTools.BrowserLink.Net.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\dev\temp\AuthScopedTest\AuthScopedTest\Program.cs:line 36
```

### .NET Version

7.0.100-preview.7.22377.5

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/43188.

### CODE REVIEW

File: src/Security/Authorization/test/AuthorizationMiddlewareTests.cs [hunk 1]
```diff
@@ -658,6 +661,27 @@ public async Task IAuthenticateResultFeature_UsesExistingFeatureAndResult_Withou
         Assert.Same(authenticateResult, authenticateResultFeature.AuthenticateResult);
     }
 
+    // Validation for https://github.com/dotnet/aspnetcore/issues/43188
+    [Fact]
+    public async Task WebApplicationBuilder_CanRegisterAuthzMiddlewareWithScopedService()
+    {
+        var builder = WebApplication.CreateBuilder(new WebApplicationOptions()
+        {
+            EnvironmentName = Environments.Development
```
Comment (captainsafia) [inline src/Security/Authorization/test/AuthorizationMiddlewareTests.cs:670]: Inconsistent scopes on resolved services only get validated in `Development` so we set the environment name explicitly here to validate the broken behavior.

**Review by HaoK — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]
