### PR TITLE
Fix rendering of `foreignObject` in SVGs

### LINKED ISSUE #30973: Fix rendering Blazor elements inside SVG
To address most of the failures outlined in https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/SvgTest.cs, we need to make sure that the SVG rendering supports scenarios like:

- Render fragments inside an SVG
- Render components inside an SVG
- Event handling with an SVG

I'm bucketing these under the general category of "rendering Blazor inside SVG" since the changes to fix this will likely fall in the browser renderer.

### PR DESCRIPTION
**Pull request by captainsafia**
Resolves https://github.com/dotnet/aspnetcore/issues/30973.

SVG supports a `foreignObject` element that can be used to display arbitrary HTML within an SVG. Particularly for Blazor, this HTML can represent a render fragment or Blazor component, like so:

```html
<svg id="svg-with-two-way-binding">
    <foreignObject width="200" height="200">
        <div>
            <input @bind="value" @bind:event="oninput" type="number"/> Two-way binding
        </div>
    </foreignObject>
</svg>
```

Currently, our client-side rendering logic renders the SVG element and all its children under the SVG namespace by invoking `document.createElementNS('http://www.w3.org/2000/svg', tagName)`. However, for the browser to correctly render the HTML content under the `foreignObject` it must be rendered under an XHTML namespace. 

To resolve this, we add an additional check to set the namespace to XHTML for elements that are children of a `foreignObject`.

Previous:

```
- svg (SVG namespace)
  - foreignObject (SVG namespace)
    - div (SVG namespace)
      - input (SVG namespace)
```

Current:
```
- svg (SVG namespace)
  - foreignObject (SVG namespace)
    - div (XHTML namespace)
      - input (XHTML namespace)
```

### CODE REVIEW

File: src/Components/Web.JS/src/Rendering/BrowserRenderer.ts [hunk 1]
```diff
@@ -220,7 +220,17 @@ export class BrowserRenderer {
...
+    // SVG elements support `foreignObject` children that can hold arbitrary HTML.
+    // For these scenarios, the parent SVG and `foreignObject` elements should
+    // be rendered under the SVG namespace, while the HTML content should be rendered
+    // under the XHTML namespace. If the correct namespaces are not provided, most
+    // browsers will fail to render the foreign object content. Here, we ensure that if
+    // we encounter a `foreignObject` in the SVG, then all its children will be placed
+    // under the XHTML namespace.
+    const isSvg = (tagName === 'svg' || isSvgElement(parent)) && !isForeignObject(parent);
+
+    const newDomElementRaw =  isSvg ?
```
Comment (campersau) [inline src/Components/Web.JS/src/Rendering/BrowserRenderer.ts:233]:
```suggestion
    const newDomElementRaw = isSvg ?
```

**Review by TanayParikh — APPROVED** [review]

**Review by javiercn — APPROVED** [review]
Looks great!

File: src/Components/Web.JS/src/Rendering/BrowserRenderer.ts [hunk 2]
```diff
@@ -220,7 +220,17 @@ export class BrowserRenderer {
...
-    const newDomElementRaw = tagName === 'svg' || isSvgElement(parent) ?
+    
+    // SVG elements support `foreignObject` children that can hold arbitrary HTML.
+    // For these scenarios, the parent SVG and `foreignObject` elements should
+    // be rendered under the SVG namespace, while the HTML content should be rendered
+    // under the XHTML namespace. If the correct namespaces are not provided, most
+    // browsers will fail to render the foreign object content. Here, we ensure that if
+    // we encounter a `foreignObject` in the SVG, then all its children will be placed
+    // under the XHTML namespace.
+    const isSvg = (tagName === 'svg' || isSvgElement(parent)) && !isForeignObject(parent);
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Rendering/BrowserRenderer.ts:231]: Note that this isn't the only place where we check `isSvgElement(parent)`. We also do that in `insertMarkup` to vary how we parse markup strings. My guess is that we'd also need to update `insertMarkup` in the same way as this in case we're inserting a markup block as the top-level thing inside a foreign element. Does that sound correct to you?

If this is all true, it suggests to me that instead of having both `isSvgElement` and `isForeignObject` as separate things we have to remember to use together, we should instead replace them both with a single `shouldTreatImmediateChildrenAsSvg` function. This would also have an efficiency benefit, since that function would only need to evaluate `getClosestDomElement(element)` once instead of two methods both evaluating that.

Comment (captainsafia) [reply src/Components/Web.JS/src/Rendering/BrowserRenderer.ts:231]: Great catch!

Yep -- it makes sense to refactor things a bit with an efficiency focus if these check happens more than once.

Will update PR accordingly.
