### PR TITLE
[Blazor] Initializers fixes for Blazor Web

### LINKED ISSUE #50187: [Blazor] Finalize behavior of JavaScript initializers for Blazor Web apps
Open questions with JavaScript initializers:

* Should we update the arguments to `beforeStart` to make it easier to detect which .NET runtime (Server/WebAssembly) is starting?
* In the case of Blazor WebAssembly, should we wait to invoke `beforeStart` until we know for sure that Blazor WebAssembly is starting? Currently, `beforeStart` gets invoked during the Blazor WebAssembly loading procedure, but this doesn't always indicate that Blazor WebAssembly will be used (consider auto mode).
* In the case of Blazor Server, should the `afterStarted` callback run each time a new circuit is created? We plan on closing circuits automatically if all Blazor Server components get removed from the page.
* Should `beforeStart` execute immediately after `Blazor.start()` is called when using `blazor.web.js`? Currently, `beforeStart` only executes just before Blazor WebAssembly or Blazor Server starts up.
  * Or, alternatively, should the module be imported as soon as `Blazor.start()` gets called, but `beforeStart` only gets called when Blazor Server or WebAssembly starts?
* Should we add arguments to the `afterStarted` callback to indicate which .NET runtime started?

### PR DESCRIPTION
**Pull request by javiercn**
Updates the initializers in Blazor to include platform specific variants that can be tailored to each runtime.

## Description

* Initializers in Blazor WebAssembly and Server allowed library authors and applications to define JS modules that would be automatically imported by the JS Blazor runtime when it booted up.
* These JS modules were used to tweak the configuration of a given Blazor Runtime or perform additional initialization of JS libraries on the page.
* Since Blazor Web can have multiple runtimes running simultaneously on the page at the same time (server and webassembly), libraries can run into issues like initializing the wrong runtime, running initialization multiple times, or having to wait until we initialize a runtime to apply custom styles and other logic that might be necessary for the correct function of their libraries.
* This PR addresses that by defining runtime specific extension points that libraries can use to tweak a concrete runtime when it boots as well as an initial extension point to target Blazor Web specific scenarios that don't involve a runtime.

Fixes #50187

## Customer Impact

* Existing libraries with initializers won't be initialized until an interactive component is rendered on the page.
* Initialization logic might run more than once for existing libraries, causing all sorts of unpredictable side effects.
  * For example, double initialization.

## Regression?

- [ ] Yes
- [X] No

It's not a regression in the sense that Blazor Web is a new scenario, but a feature that library authors depend on (for example the Fluent UI Blazor components library does) will not work reliably in this scenario.

## Risk

- [ ] High
- [ ] Medium
- [X] Low

The fix is an extension to the existing mechanism to give library authors a path forward. The previous mechanism is disabled by default in Blazor Web scenarios and this fix gives library authors a path forward to make the feature work reliably here. In addition to that, with this fix app developers are not blocked on library authors updating their packages to work on Blazor web, as they can author adapters for the initializers within their apps that use the extension defined by the fix.

## Verification

- [ ] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

File: src/Components/Web.JS/src/JSInitializers/JSInitializers.Server.ts [hunk 1]
```diff
@@ -5,14 +5,21 @@ import { CircuitStartOptions } from '../Platform/Circuits/CircuitStartOptions';
 import { JSInitializer } from './JSInitializers';
 
 export async function fetchAndInvokeInitializers(options: Partial<CircuitStartOptions>) : Promise<JSInitializer> {
+  if (options.initializers) {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/JSInitializers/JSInitializers.Server.ts:8]: Under what circumstances does this happen?

Comment (javiercn) [reply src/Components/Web.JS/src/JSInitializers/JSInitializers.Server.ts:9]: Only when Blazor web is in charge of loading the initializers.

File: src/Components/Web.JS/src/JSInitializers/JSInitializers.ts [hunk 2]
```diff
@@ -29,19 +55,97 @@ export class JSInitializer {
...
+          options.circuit.initializers.afterStarted.push(afterServerStarted);
+        }
+
+        if (afterWebStarted) {
+          jsInitializer.afterStartedCallbacks.push(afterWebStarted);
+        }
+
+        if (beforeWebStart) {
+          return beforeWebStart(options);
+        }
```
Comment (javiercn) [inline src/Components/Web.JS/src/JSInitializers/JSInitializers.ts:109]: We essentially collect all the callbacks from the initializer for server and webassembly, and set them in their respective options types. After that, we start running the `beforeWebStart` callback and trigger the `afterWebStarted` callbacks once we are done with the first render.

**Comment by javiercn** [comment]
@wtgodbe I will retarget it once I am done with it.

File: src/Components/Web.JS/src/Boot.Server.Common.ts [hunk 3]
```diff
@@ -83,42 +101,72 @@ export async function startServer(components: RootComponentManager<ServerCompone
...
+  circuitStarting = circuit.start();
+  clearCircuitStarting(circuitStarting);
+  return circuitStarting;
+}
+
+async function clearCircuitStarting(circuitStartingPromise: Promise<boolean>) {
+  await circuitStartingPromise;
+  if (circuitStarting === circuitStartingPromise) {
+    circuitStarting = undefined;
+  }
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Boot.Server.Common.ts:145]: It took be a bit to understand but I get why this is necessary. Maybe a minor detail, but should the `circuitStarting` promise itself be the thing that sets `circuitStarting` to `undefined` before resolving? That way there's no possibility that someone awaiting `circuitStarting` will then call `startCircuit()` before this gets a chance to clear.

**Review by MackinnonBuck — COMMENTED** [review]
I still need to go through things in more detail, but the approach looks good to me so far.

File: src/Components/Web.JS/src/Boot.Server.Common.ts (hunk 3 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Boot.Server.Common.ts:145]: If it's hard to understand there should be a comment here providing clarity

File: src/Components/Web.JS/src/Boot.Server.Common.ts [hunk 4]
```diff
@@ -83,42 +101,72 @@ export async function startServer(components: RootComponentManager<ServerCompone
...
+    return circuit.updateRootComponents(operations);
+  } else {
+    scheduleWhenReady(operations);
+  }
+}
+async function scheduleWhenReady(operations: string) {
+  await serverStartPromise;
+  if (await startCircuit()) {
+    return circuit.updateRootComponents(operations);
+  }
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.Common.ts:171]: When we process the document (on update root components) we fire up the server, but we don't wait for it to complete initializing, that's a problem because we later might call updateRootComponents before the server has fully initialized.

What happened before is that we "incorrectly" created the circuit synchronously in the call to startServer and relied upon that fact, so at that point, when we called updateRootComponents we had an already "initialized" circuit (on the client side) even if the circuit was still initializing on the server, so we were able to push the components (even though, they would just get buffered on the client/server until SignalR finished processing the previous request.

The "incorrect" part comes from the fact that initializers must be able to see the options for server/webassembly and are allowed to be asynchronous, which means that the circuit might not be setup by the time `startServer` returns, hence why we need to keep the promise and queue the update.

File: src/Components/Web.JS/src/Boot.Server.ts [hunk 5]
```diff
@@ -18,7 +18,8 @@ function boot(userOptions?: Partial<CircuitStartOptions>): Promise<void> {
   }
   started = true;
 
-  setCircuitOptions(userOptions);
+  const configuredOptions = resolveOptions(userOptions);
+  setCircuitOptions(Promise.resolve(configuredOptions || {}));
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.ts:22]: Yes

File: src/Components/Web.JS/src/Boot.Server.Common.ts (hunk 3 above)
Comment (javiercn) [reply src/Components/Web.JS/src/Boot.Server.Common.ts:145]: `circuitStarting` is a module level variable, that gets assigned the result of `circuit.start()`, so I'd rather keep it as it is rather than have something in CircuitManager refer back to this file, or are you suggesting something else?

I've updated the code base with some comments for clarity.

**Comment by danmoseley** [comment]
this has the servicing-consider label but I don't see a mail for it yet.

**Review by MackinnonBuck — APPROVED** [review]
