### PR TITLE
Avoid null refs in HotReloadAgent when accessing Assembly.Modules

### LINKED ISSUE #33152: Running dotnet watch with a EditForm component with @bind-Value breaks with error "condition `<disabled>' not met"
Running my project I've noticed that the hot reload will exit/crash if it finds a <EditForm> with a @bind-Value inside of it.

Files looks like 
```
<EditForm Model="@Login" OnValidSubmit="HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText @bind-Value="Login.Email" />
    <InputText @bind-Value="Login.Password" />
    <button class="btn btn btn-lg btn-primary" type="submit">Sign in One</button>
</EditForm>

@code {
    private LoginResult Login = new LoginResult();
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount += 30;
    }

    private void HandleValidSubmit()
    {
        Navigation.NavigateTo("/");
    }
}
```

Crashes with when navigating to the page

```
* Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1373, condition `<disabled>' not met
dotnet.6.0.0-preview.4.21253.7.js:1:18291
```

Downgrading the preview packages to Preview 3 (not the SDK) will not crash the application.

I have created a reproduction of the issue here - You will need Preview4 and latest Visual Studio Preview

https://github.com/ShoarW/BlazorHotReloadPreview4

### PR DESCRIPTION
**Pull request by pranavkm**
Accessing Assembly.Modules for arbitrary loaded assemblies may throw which currently results
in the hot reload agent to produce an unhandled exception crashing the app. This change attempts
to perform a targeted fix for that issue.

Fixes https://github.com/dotnet/aspnetcore/issues/33152

### CODE REVIEW

File: src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ private void OnAssemblyLoad(object? _, AssemblyLoadEventArgs eventArgs)
             if (_deltas.TryGetValue(moduleId.Value, out var updateDeltas) && _appliedAssemblies.TryAdd(loadedAssembly, loadedAssembly))
```
Comment (TanayParikh) [inline src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs:39]: Do we use a `ConcurrentDictionary<Assembly, Assembly>` instead of a `ConcurrentBag` to protect against duplicate entries?

**Review by TanayParikh — COMMENTED** [review]
LGTM

File: src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs (hunk 1 above)
Comment (pranavkm) [reply src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs:39]: We really need a ConcurrentSet here. ConcurrentBags have no lookup semantics, it gives you an item with no good way of telling you if a specific instance exists. ConcurrentDictionary with a throw away value acts as a reasonable subsitute.

**Review by captainsafia — APPROVED** [review]
