### PR TITLE
Re-enable SingleFileExe

### LINKED ISSUE #25103: Investigate why SingleFileExe tests fail in Helix
As part of https://github.com/dotnet/aspnetcore/pull/24925 we added tests to verify views + singlefile exe work. These appear to be failing on Helix. I've verified on a couple of different clean machines that the changes work correctly. I suspect the test setup isn't correct. Punting it to get the feature in.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/25103

Updates the test to 
* run on Windows-only to avoid the need to have the runtime available 
* avoids using IdentityUI since that package doesn't work with this very well (Identity UI splits views in to a separate assembly).

### CODE REVIEW

File: src/ProjectTemplates/test/MvcTemplateTest.cs [hunk 1]
```diff
@@ -234,68 +227,45 @@ public async Task MvcTemplate_IndividualAuth(bool useLocalDB)
...
-                        PageUrls.LoginUrl,
-                        PageUrls.HomeUrl,
-                        PageUrls.PrivacyUrl,
-                        PageUrls.ExternalArticle,
-                        PageUrls.PrivacyUrl
-                    }
-                },
-            };
+            PageUrls.HomeUrl,
+            PageUrls.HomeUrl,
```
Comment (TanayParikh) [inline src/ProjectTemplates/test/MvcTemplateTest.cs:250]:
```suggestion
            PageUrls.HomeUrl,
```

**Review by TanayParikh — APPROVED** [review]

File: src/ProjectTemplates/test/MvcTemplateTest.cs [hunk 2]
```diff
@@ -234,68 +227,45 @@ public async Task MvcTemplate_IndividualAuth(bool useLocalDB)
...
-                        PageUrls.RegisterUrl,
-                        PageUrls.LoginUrl,
-                        PageUrls.HomeUrl,
-                        PageUrls.PrivacyUrl,
-                        PageUrls.ExternalArticle,
-                        PageUrls.PrivacyUrl
-                    }
-                },
-            };
+            PageUrls.HomeUrl,
```
Comment (pranavkm) [inline src/ProjectTemplates/test/MvcTemplateTest.cs:249]:
```suggestion
```

File: src/ProjectTemplates/test/MvcTemplateTest.cs [hunk 3]
```diff
@@ -234,68 +227,44 @@ public async Task MvcTemplate_IndividualAuth(bool useLocalDB)
...
```
Comment (pranavkm) [inline src/ProjectTemplates/test/MvcTemplateTest.cs:249]:
```suggestion
            PageUrls.HomeUrl,
            PageUrls.HomeUrl,            
```

Apparently this is intentional because there are two links to the Home page on the landing page.

**Comment by sebastienros** [comment]
This is breaking Helix on Windows ARM64
c.f.: `var runtimeIdentifer = "win-x64";`
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-864ef436f05d4bd2ac/ProjectTemplates.Tests--net7.0/1/console.a6a34a81.log?sv=2019-07-07&se=2022-03-14T12%3A55%3A36Z&sr=c&sp=rl&sig=c3lEDngzUNcTrSEfWQ3QIiAZBJWAmXrOuRxd5OL3VO4%3D
