### PR TITLE
Various virtualization improvements. Fixes #25535

### LINKED ISSUE #25535: Virtualization fixes
Resolve the two main remaining usability issues:

 * Item size calculations can be wrong by a subpixel amount, which accumulates and produces offsets in scrolling
 * When items don't have `@key`, scrolling can get stuck in a loop

### PR DESCRIPTION
**Pull request by MackinnonBuck**
This PR addresses issues with `<Virtualize>`:

## Ask-mode template

*@SteveSandersonMS  editing the PR description from here:*

#### Description

There are some glitches in the new `Virtualize` component that will ship for the first time in RC1:

 * Item size calculations can be wrong by a subpixel amount, which accumulates and produces offsets in scrolling
 * When items don't have `@key`, scrolling can get stuck in a loop

Additionally, there wasn't a way to control the number of items fetched to use as a buffer around the visible region, which resulted in no control over the frequency of rendering.

#### Customer Impact

If we don't merge this, customers will very likely run into one of the above glitches almost immediately. Then they won't be able to try out `<Virtualize>` properly and we won't get useful feedback about it or know if our fixes are correct.

#### Regression?

No, this is a new feature

#### Risk

In the worst case, this might theoretically make `<Virtualize>` behave badly in a different as-yet unknown way.

Addresses https://github.com/dotnet/aspnetcore/issues/25535

### CODE REVIEW

File: src/Components/Web.JS/src/Virtualize.ts [hunk 1]
```diff
@@ -57,7 +57,9 @@ function init(dotNetHelper: any, spacerBefore: HTMLElement, spacerAfter: HTMLEle
         return;
       }
 
-      const spacerSeparation = spacerAfter.offsetTop - (spacerBefore.offsetTop + spacerBefore.offsetHeight);
+      const spacerBeforeRect = spacerBefore.getBoundingClientRect();
+      const spacerAfterRect = spacerAfter.getBoundingClientRect();
+      const spacerSeparation = spacerAfterRect.top - spacerBeforeRect.bottom;
```
Comment (MackinnonBuck) [inline src/Components/Web.JS/src/Virtualize.ts:62]: Using `entry.boundingClientRect` here results in one spacer's rect being slightly more up-to-date than the other's, which is why both are being calculated here. I'm open to alternatives.

**Comment by SteveSandersonMS** [comment]
> I've also implemented a check to see if the calculated item size is within some margin of the user-provided item size

This seems a bit quirky. Maybe it is the right design, but I'd be interested to discuss it. What I'm concerned about is that commonly, developers *think* they know what the item size is, but they are wrong by a small margin of error, perhaps because of the element `margin` being added onto its `height`. My hope had been that we can calculate the actual height and thereby free developers from the consequences of being slightly wrong, whereas the rule in this PR means we couldn't help them in this way.

I understand it's hard to determine the exact height but I'm unsure how bad are the consequences of us getting it wrong by a < 1px fraction or if there are any other approaches you've considered. Let's discuss when possible!

File: src/Components/Web.JS/src/Virtualize.ts (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Virtualize.ts:62]: This looks good to me.

**Comment by SteveSandersonMS** [comment]
OK, I've been looking into this, and was able to reproduce the problem with fractional heights by using the following test case in `FetchData.ts`:

```razor
@if (forecasts == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <div style="overflow-y: auto; height: 200px; border: 1px solid red;">
        <Virtualize Items="forecasts" Context="forecast">
            <div style="border: 0.2px solid green" @key="forecast">
                <span>@forecast.Date.ToShortDateString()</span>
                <span>@forecast.TemperatureC</span>
                <span>@forecast.TemperatureF</span>
                <span>@forecast.Summary</span>
            </div>
        </Virtualize>
    </div>
}
```

I also changed the underlying data source to supply 500 items. Without your fix that uses `getBoundingClientRect`, the behavior goes wrong when scrolling quickly because it misjudges its location within the scroll range because the rounding errors add up. In the example above, it just stops adding new items after a certain point, so the user scrolls into a blank white region.

Then, after adding your fix that uses `getBoundingClientRect`, the problem goes away. I could no longer repro any weirdness in the above example.

So, my remaining two questions are:

 * **Why would it be better to use the developer's own provided `ItemSize` value?** It's hard to see how the developer would be able to give a more accurate value than you're calculating at the subpixel level. Your value is more accurate than what's displayed in the browser dev tools, which round to 2dp.
    * Do you have any repro scenario where things still go wrong after applying the `getBoundingClientRect` fix?
 * **Do we care about supporting the case where the developer fails to provide `@key`?** I found that, if not providing that, the scrolling sometimes goes mad and continues scrolling even after I release the mouse wheel. It's a bit worrying because I don't have an exact reason for why it happens or why `@key` fixes it, or if there might be some case where `@key` doesn't fix it.
    * My best guess is there may be some heuristic within the browser whereby when using wheel scrolling (or perhaps with drag scrolling too), it picks an end point that lines up with one of the existing elements, and continues scrolling until that point is reached. But if we're not using `@key`, then it never reaches that point because we keep moving the target element further in the direction you're already scrolling. If this guess is correct, it explains why `@key` fixes it (because the target element gets removed from the DOM and the process ends). However this guess doesn't predict any good solution other than `@key`.
      * For my own future reference: we did consider forcing the equivalent of `@key` by wrapping each item inside a region with sequence number given by the index into the collection. However this behaves badly if items are inserted/removed, as it incorrectly would match/mismatch items against the earlier output. So it's better to force developers to give a `@key` manually corresponding to the actual collection entry or its ID.
    * Personally I think we could consider it a reasonable requirement that you must use `@key` for good performance and reliable scrolling. Certainly it's the most common case. It would just be great if we could avoid the weirdness in the non-key case too!

**Comment by MackinnonBuck** [comment]
Thanks for the detailed follow-up, @SteveSandersonMS!

> Why would it be better to use the developer's own provided `ItemSize` value?

I do recall that the `getBoundingClientRect` fix would appear to be off by a tenth of a pixel at times, so I left in the logic to snap that value to `ItemSize` if it's that close. I don't remember if I observed any usability issues with the `getBoundingClientRect` solution if I left out the rounding logic, so I'll investigate this further. If I'm not able to recreate the issue without the rounding fix, I think it's fine to remove that bit of logic.

> Do we care about supporting the case where the developer fails to provide `@key`?

What's funny is that @danroth27 experienced this exact issue, showed me the strange behavior he was getting, and even I didn't initially recognize that the issue was the lack of a `@key`. I think it's something easy to forget, so we would definitely have to document it in a visible way if we decide to make it a requirement. It also might be a little confusing that `PlaceholderTemplate` doesn't require a `@key` while `ItemContent` does. Overall, I think it's fine if we require a `@key` unless there's an easy way to do without it.

**Comment by MackinnonBuck** [comment]
Quick update: It does look like removing the custom rounding logic results in the scrollbar being slightly out of sync with the mouse. I didn't notice any strange behavior when using the scroll wheel, just when clicking and dragging the scrollbar. I think it would be nice to be able to avoid using `ItemSize` beyond the initial render, but it might require an entirely different technique.

If we could wrap each item in a `<div>`, we could solve both the `@key` problem and item size calculation because we could just make the `@key` be the item context, and just calculate the height of a single item the first time one is rendered. However, this breaks things for things like tables, where it's illegal to have `<div>`s in certain places.

File: src/Components/Web.JS/src/Virtualize.ts [hunk 2]
```diff
@@ -20,8 +20,16 @@ function findClosestScrollContainer(element: Element | null): Element | null {
 }
 
 function init(dotNetHelper: any, spacerBefore: HTMLElement, spacerAfter: HTMLElement, rootMargin = 50): void {
+  // Overflow anchoring can cause an ongoing scroll loop, because when we resize the spacers, the browser
+  // would update the scroll position to compensate. Then the spacer would remain visible and we'd keep on
+  // trying to resize it.
+  const scrollContainer = findClosestScrollContainer(spacerBefore);
+  if (scrollContainer) {
+    scrollContainer.style.overflowAnchor = 'none';
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Web.JS/src/Virtualize.ts:28]: Have we tried this in combination with `scroll-snap-align` and similar things?

[the remark this answers is not in the document]
Comment (SteveSandersonMS) [reply src/Components/Web.JS/src/Virtualize.ts]: I've tried it in some basic cases, and whether or not it works well depends on exactly how big the snappable items are and whether you're doing mouse or touch scrolling. In a lot of cases it's quite  Sometimes on desktop, I find that `scroll-snap-align` feels pretty weird even natively (without virtualization).

As a point of comparison, I tried out react-window in conjunction with `scroll-snap-align` (by visiting https://react-window.now.sh/#/examples/list/fixed-size and using the dev tools to apply the extra CSS styling). It behaves somewhat OK, probably better than our `<Virtualize>` in this scenario, but there are cases where react-window glitches out badly with this. If you scroll quickly and happen to release the mouse right in the middle of an element, instead of snapping to the place you let go of the mouse, it scrolls backwards a  long way and snaps to some other element instead.

If we think this is going to be a primary scenario it does seem we're not there yet. However it seems unlikely to me that it would be a core scenario.

File: src/Components/Web/src/Virtualization/Virtualize.cs [hunk 3]
```diff
@@ -88,6 +88,15 @@ public sealed class Virtualize<TItem> : ComponentBase, IVirtualizeJsCallbacks, I
...
         public ICollection<TItem>? Items { get; set; }
 
+        /// <summary>
+        /// Gets or sets a value that determines how many additional items will be rendered
+        /// before and after the visible region. This help to reduce the frequency of rendering
+        /// during scrolling. However, higher values mean that more elements will be present
+        /// in the page.
+        /// </summary>
+        [Parameter]
+        public int OverscanCount { get; set; } = 3;
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Virtualization/Virtualize.cs:98]: @MackinnonBuck What do you think about including this to give developers an extra dial to turn? During my experiments I found it was rendering at a higher frequency than I liked during scrolling, doing quite a bit of CPU work (and in the Blazor Server case, causing a lot of network traffic to get small slices of data).

File: src/Components/Web.JS/src/Virtualize.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Web.JS/src/Virtualize.ts]: > If we think this is going to be a primary scenario it does seem we're not there yet. However it seems unlikely to me that it would be a core scenario.

I'm just trying to make sure we cover our backs and think about these types of things, scroll-snap and friends are new right now, but they will become more prevalent in the futre. My goal is that we understand whether or not we think these things will require a big redesign in the future or just improvements to the existing implementation.

File: src/Components/Web/src/Virtualization/Virtualize.cs (hunk 3 above)
Comment (MackinnonBuck) [reply src/Components/Web/src/Virtualization/Virtualize.cs:98]: @SteveSandersonMS This sounds like a great idea to me.

Comment (SteveSandersonMS) [reply src/Components/Web/src/Virtualization/Virtualize.cs:98]: OK cool. It's a very small and low-risk addition so let's include it.

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT This is rebased to 5.0-rc2 now. Could you please merge it?

**Comment by Pilchie** [comment]
Approved for 5.0 RC2.
