### PR TITLE
Fix up nullability and primitive type handing in schema generation

### LINKED ISSUE #56351: object property causes build crash when generating OpenAPI document at build time
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a project using the Microsoft.Extensions.ApiDescription.Server package to generate the OpenAPI document at build time, the build crashes if a class that will have a generated schema contains a property declared as type "object".

### Expected Behavior

a) the build should not crash
b) the schema for the property should have no `type` assertion -- the property's value can be any type.

### Steps To Reproduce

Declare a property in a class used as a response body like:
```
public object Object { get; set; }
```

### Exceptions (if any)

```text
> dotnet build
Restore complete (0.7s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  aspnet-openapi-examples failed with 31 error(s) and 3 warning(s) (1.6s) → bin\Debug\net9.0\aspnet-openapi-examples.dll
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\Transformers\InfoTransformer.cs(8,23): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\ResponsesApi.cs(148,11): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\Schemas.cs(12,12): warning CS0169: The field 'Schemas.Field' is never used
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error : System.AggregateException: One or more errors occurred. (The node must be of type 'JsonObject'.)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :  ---> System.InvalidOperationException: The node must be of type 'JsonObject'.
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeWrongType(ReadOnlySpan`1 supportedTypeNames)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Nodes.JsonNode.AsObject()
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Nodes.JsonNode.set_Item(String propertyName, JsonNode value)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.JsonNodeSchemaExtensions.ApplySchemaReferenceId(JsonNode schema, JsonSchemaExporterContext context)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.<>c.<.ctor>b__0_2(JsonSchemaExporterContext context, JsonNode schema)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Schema.JsonSchema.<ToJsonNode>g__CompleteSchema|104_0(JsonNode schema, <>c__DisplayClass104_0&)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonTypeInfo typeInfo, JsonSchemaExporterOptions exporterOptions)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonSerializerOptions options, Type type, JsonSchemaExporterOptions exporterOptions)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.CreateSchema(OpenApiSchemaKey key)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiSchemaStore.GetOrAdd(OpenApiSchemaKey key, Func`2 valueFactory)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, ApiParameterDescription parameterDescription, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponseAsync(ApiDescription apiDescription, Int32 statusCode, ApiResponseType apiResponseType, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponsesAsync(ApiDescription description, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescriptions.OpenApiDocumentProvider.GenerateAsync(String documentName, TextWriter writer, OpenApiSpecVersion openApiSpecVersion)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    --- End of inner exception stack trace ---
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocument(String documentName, String projectName, String outputDirectory, MethodInfo generateMethod, Object service, MethodInfo generateWithVersionMethod)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocuments(IServiceProvider services)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.Process()
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error MSB3073: The command "dotnet "C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.6.24320.6\build\../tools/dotnet-getdocument.dll" --assembly "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\bin\Debug\net9.0\aspnet-openapi-examples.dll" --file-list "obj\aspnet-openapi-examples.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v9.0" --output "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples" --project "aspnet-openapi-examples" --assets-file "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\obj\project.assets.json" --platform "AnyCPU" " exited with code 11.

Build failed with 31 error(s) and 3 warning(s) in 2.6s
```

### .NET Version

9.0.100-preview.6.24320.9

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
- Use `IsGetNullable` and `IsSetNullable` properties to set nullability status for properties
- Use per-instance `NullabilityInfoContext` instead of shared static instance
- Avoid allocating schemas for select primitive types
- Avoid including special `?` character in reference ID for nullable schemas
- Massage representation of `object` schemas to close https://github.com/dotnet/aspnetcore/issues/56351

Addresses feedback from https://github.com/dotnet/aspnetcore/pull/56330#discussion_r1649371307 and https://github.com/dotnet/aspnetcore/issues/56318

### CODE REVIEW

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs [hunk 1]
```diff
@@ -365,7 +363,8 @@ internal static void ApplyNullabilityContextInfo(this JsonNode schema, Parameter
             return;
         }
 
-        var nullabilityInfo = _nullabilityInfoContext.Create(parameterInfo);
+        var nullabilityInfoContext = new NullabilityInfoContext();
```
Comment (eiriktsarpalis) [inline src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:366]: You can use JsonPropertyInfo.AssociatedParameterInfo.IsNullable here.

Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:366]: It looks like that API is limited to properties that are sourced from a constructor parameter? This particular case applies to parameters source from the handler method, such as `name` in`app.MapGet("/", (string name) => ...)`. I don't think there's a JSON info-based API for that?

Comment (eiriktsarpalis) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:366]: Ah yes, you're correct. You're on your own when it comes to method parameters.

Comment (eiriktsarpalis) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:366]: One thing you might want to be aware of is that `NullabilityInfoContext` has a feature switch that can turn it off (resulting in exceptions). We learned this the hard way because the blazor sdk was turning it off by default, so I had to introduce defensive code in the STJ side that [checked for the feature switch](https://github.com/dotnet/runtime/pull/102852) before exercising `NullabilityInfoContext` APIs.

We decided in API review that the feature switch was a bad idea and we're going to remove it [at some point](https://github.com/dotnet/runtime/issues/103298#issuecomment-2161338112), though I'm not sure we'll be able to get to that for .NET 9.

Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:372]: > One thing you might want to be aware of is that NullabilityInfoContext has a feature switch that can turn it off (resulting in exceptions being thrown every time you call its APIs). We learned this the hard way because the blazor sdk was turning it off by default, so I had to introduce defensive code in the STJ side that https://github.com/dotnet/runtime/pull/102852 before exercising NullabilityInfoContext APIs.

Good note!  I've applied a similar check here to guard against this.

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs [hunk 2]
```diff
@@ -376,16 +381,10 @@ internal static void ApplyNullabilityContextInfo(this JsonNode schema, Parameter
...
+    internal static void ApplyNullabilityContextInfo(this JsonNode schema, JsonPropertyInfo propertyInfo)
     {
-        var nullabilityInfo = attributeProvider switch
-        {
-            PropertyInfo propertyInfo => !propertyInfo.PropertyType.IsValueType ? _nullabilityInfoContext.Create(propertyInfo) : null,
-            FieldInfo fieldInfo => !fieldInfo.FieldType.IsValueType ? _nullabilityInfoContext.Create(fieldInfo) : null,
-            _ => null
-        };
-        if (nullabilityInfo is { WriteState: NullabilityState.Nullable } or { ReadState: NullabilityState.Nullable })
+        if (propertyInfo.PropertyType != typeof(object) && (propertyInfo.IsGetNullable || propertyInfo.IsSetNullable))
```
Comment (BrennanConroy) [inline src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:387]: What's the `object` check doing?

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs [hunk 3]
```diff
@@ -98,23 +122,14 @@ internal static string GetSchemaReferenceId(this Type type, JsonSerializerOption
...
-            else
-            {
-                var genericTypeName = type.Name[..type.Name.LastIndexOf('`')];
-                var genericArguments = type.GetGenericArguments();
-                var argumentNames = string.Join("And", genericArguments.Select(arg => arg.GetSchemaReferenceId(options)));
-                return $"{genericTypeName}Of{argumentNames}";
-            }
+            var genericTypeName = type.Name[..type.Name.LastIndexOf('`')];
+            var genericArguments = type.GetGenericArguments();
+            var argumentNames = string.Join("And", genericArguments.Select(arg => arg.GetSchemaReferenceId(options)));
```
Comment (BrennanConroy) [inline src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:131]: Is `Null` ok in the name here?

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs [hunk 4]
```diff
@@ -11,6 +11,21 @@ namespace Microsoft.AspNetCore.OpenApi;
 
 internal static class JsonTypeInfoExtensions
 {
+    private static readonly List<Type> _exemptPrimitives =
```
Comment (BrennanConroy) [inline src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:14]: Are these from an OpenAPI spec? Otherwise there are probably other primitives, e.g. `nint`, `byte`

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs (hunk 2 above)
Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:386]: The JsonInfo for `object` types marks them as nullable but we want to maintain an empty "catch-all" schema for them in OpenAPI (no type, no format, no constraints) so we exempt them from this check here. I'll add a comment about this above.

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs (hunk 4 above)
Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:14]: Added these and a few more other primitive types. Lemme know what you think of the list.

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs (hunk 3 above)
Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:143]: This calls into the overload that never exempts primitives so we're covered here. `JsonTypeInfoExtensionsTests.GetSchemaReferenceId_Works` has test cases to cover generics/enumerables with primitive types so we cover this case.

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs (hunk 4 above)
Comment (martincostello) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:14]: Any of `Guid`, `Uri`, `TimeSpan`, `DateOnly` and `TimeOnly`? Just comparing to the list we have in Swashbuckle and they're the only ones that are different to this set. They basically end up as a `string` with a `format` of some kind in the schema.

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs (hunk 1 above)
Comment (eiriktsarpalis) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:369]: I just deleted the feature switch altogether from runtime, so assuming you only target .NET 9 you should be good.

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs (hunk 4 above)
Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:14]: Ah, yes! I recall you sharing this in the other PR. I've updated this set so it's consistent between the two. I wasn't able to find the logic in NSwag for this but this probably a set that we should be consist with throughout the implementations. 🤔

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs (hunk 1 above)
Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:369]: Yep, I went ahead and remove this check from here as well.

File: src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs (hunk 4 above)
Comment (martincostello) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs:14]: I'd forgotten about `Version` 😄

Did you want `TimeSpan` too, or was there a reason to skip that?

Comment (captainsafia) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs]: Yet another reason to make this public 😓 Added that as well. Let me know if there is anything else I missed. I'd like to get this PR in soon to ease some of the build failures it is causing but happy to add things in a follow-up PR.

Comment (martincostello) [reply src/OpenApi/src/Extensions/JsonTypeInfoExtensions.cs]: The new set seems to cover all the common primitives/cases I'm aware of 👍

**Review by BrennanConroy — APPROVED** [review]
