### PR TITLE
[6.0] Skip empty lines between requests

### LINKED ISSUE #42697: Requests with new lines at the end cause extra 400 responses
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a follow up to https://github.com/dotnet/aspnetcore/issues/40747. That fixed an issue where extra CRLF's between requests would cause 400s. It missed a case where if those CRLFs where after the last request of a connection then that would also trigger an extra 400.

### Expected Behavior

Extra CRLFs after the body are ignored and the connection gracefully closed.

### Steps To Reproduce

Send a request. Include one or more extra CRLF's at the end that are not accounted for in the normal body (e.g. beyond the content-length). After the server responds to the initial request, half-close the connection from the client. This triggers the incoming pipe reader to complete and the HttpParser errors if there's still data left, producing an extra 400 response.

### Exceptions (if any)

```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

### .NET Version

6.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Backport https://github.com/dotnet/aspnetcore/pull/43228 to 6.0

Some clients send extra new lines (CRLF) between requests. This updates Kestrel to allow that.

## Description

The extra lines were being interpreted as an invalid start of the next request, causing a 400 response after the first response. We previously fixed a case where we consumed these at the start of a request, but we missed a case where they were not consumed at the end of a connection.

Fixes #42697

## Customer Impact

Customers are seeing failed responses (400) at the end of a connection.

## Regression?

- [ ] Yes
- [x] No

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Minimal change to skip known data. Validated by internal team.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@Tratcher

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/BadHttpRequestTests.cs [hunk 1]
```diff
@@ -323,6 +323,190 @@ await using (var server = new TestServer(context => Task.CompletedTask, new Test
...
+            Assert.False(badRequestEventListener.EventFired);
+        }
+
+        [Theory]
+        [InlineData("\r")]
+        [InlineData("\n")]
+        [InlineData("\r\n")]
+        [InlineData("\n\r")]
+        [InlineData("\r\n\r\n")]
+        [InlineData("\r\r\r\r\r")]
```
Comment (danmoseley) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/BadHttpRequestTests.cs:463]: does any system use `\r` as a newline? they are all `\n` or `\r\n` that I know of. I don't see `\n\n` here.

Comment (Tratcher) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/BadHttpRequestTests.cs:463]: The HTTP spec requires `\r\n`, that's not OS specific.

**Review by Tratcher — APPROVED** [review]

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/BadHttpRequestTests.cs (hunk 1 above)
Comment (adityamandaleeka) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/BadHttpRequestTests.cs:463]: It's not so much that any system uses `\r` as a newline, but rather that clients in the wild sometimes have _interesting_ implementations of HTTP. The bare CR was one such example that we encountered.

RFC 7230 encourages some leniency in this area (ignoring empty lines) and this also matches IIS's behavior which makes things smoother for folks migrating over to Kestrel, so we decided this is a safe change.

The `\n\n` case works too, I'll add it.
