### PR TITLE
Wait to dispose CTS for IIS

### LINKED ISSUE #4422: .NET Runtime Exception: ObjectDisposedException
### Describe the bug
After upgrading to ASP.NET Core 2.2, we frequently face this error and our website gets restarted. This happens once an hour or so. We had to target 2.1 again to fix this issue.
Here are the errors from event viewer (in the order they have occurred): 

```
Application: dotnet.exe
CoreCLR Version: 4.6.27110.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.IO.FileStream.FileStreamCompletionSource.CompleteCallback(UInt64 packedResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

```
Faulting application name: dotnet.exe, version: 2.2.27110.6, time stamp: 0x5be769ed
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2adb
Exception code: 0xe0434352
Fault offset: 0x0000000000033c58
Faulting process id: 0x34374
Faulting application start time: 0x01d48cab8dc6d688
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: aaeaddc7-02d9-45ce-9f29-318127ca0951
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: C:\Program Files\dotnet\dotnet.exe
P2: 2.2.27110.6
P3: 5be769ed
P4: System.Private.CoreLib
P5: 4.6.27110.4
P6: 5be75665
P7: 27fd
P8: b
P9: System.ObjectDisposedException
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_C__Program Files_55e13f92ac2eada5e8dd2daa7dea78fd1e8d5d_0e1906bf_ade641d7

Analysis symbol: 
Rechecking for solution: 0
Report Id: aaeaddc7-02d9-45ce-9f29-318127ca0951
Report Status: 4
Hashed bucket: 
```

```
Fault bucket 1396378374383491433, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: C:\Program Files\dotnet\dotnet.exe
P2: 2.2.27110.6
P3: 5be769ed
P4: System.Private.CoreLib
P5: 4.6.27110.4
P6: 5be75665
P7: 27fd
P8: b
P9: System.ObjectDisposedException
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_C__Program Files_55e13f92ac2eada5e8dd2daa7dea78fd1e8d5d_0e1906bf_69a648dc

Analysis symbol: 
Rechecking for solution: 0
Report Id: aaeaddc7-02d9-45ce-9f29-318127ca0951
Report Status: 0
Hashed bucket: 0fdfa957dcca13d25360eebbb12a5969
```

### To Reproduce
Use SDK v2.2.100 with IIS on Windows Server 2016

### Additional context
Include the output of `dotnet --info`

```
Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/aspnet/AspNetCore/issues/4422
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/1831

Still have a few tests I need to write. Will mark ready for review when appropriate. 

@halter73 I lightly explored making a helper for safe disposal/cancellation, and it didn't look great. I'm going to keep them separate for now.

### CODE REVIEW

**Comment by jkotalik** [comment]
This will also address some gaps we had between Kestrel and IIS, specifically not cancelling the cts after writing the entire content and checking content length.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs [hunk 1]
```diff
@@ -12,6 +11,9 @@ internal partial class IISHttpContext : IHttpRequestLifetimeFeature
     {
         private CancellationTokenSource _abortedCts;
         private CancellationToken? _manuallySetRequestAbortToken;
+        private object _abortLock = new object();
+        private bool _preventRequestAbortedCancellation;
+        protected bool _connectionAborted;
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs]: Might as well call it _requestAborted hear since the whole type has a request lifetime.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs [hunk 2]
```diff
@@ -12,6 +11,9 @@ internal partial class IISHttpContext : IHttpRequestLifetimeFeature
     {
         private CancellationTokenSource _abortedCts;
         private CancellationToken? _manuallySetRequestAbortToken;
+        private object _abortLock = new object();
+        private bool _preventRequestAbortedCancellation;
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs]: As discussed offline, don't worry about _preventRequestAbortedCancellation unless customers report unexpected cancellation after fully buffering a content-length response.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs (hunk 1 above)
Comment (jkotalik) [reply src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs]: I had a rename that I thought went through...

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs [hunk 3]
```diff
@@ -198,14 +272,27 @@ internal void AbortIO(bool clientDisconnect)
 
             _bodyOutput.Dispose();
 
-            var cts = _abortedCts;
-            if (cts != null)
+            if (shouldScheduleCancellation)
             {
+                // Potentially calling user code. CancelRequestAbortedToken logs any exceptions.
                 ThreadPool.QueueUserWorkItem(t =>
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: Nit: I know this isn't new, but why doesn't this use UnsafeQueueUserWorkItem and pass this as the state variable?

Comment (jkotalik) [reply src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: Probably should 😄

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs [hunk 4]
```diff
@@ -186,9 +189,17 @@ private async Task WriteBody(bool flush = false)
...
+                if (_requestAborted)
+                {
+                    return;
+                }
+
+                shouldScheduleCancellation = _abortedCts != null;
+                _requestAborted = true;
             }
 
             if (clientDisconnect)
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: What is the clientDisconnect parameter about anyway? Should it influence whether the RequestAborted token fires?

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs [hunk 5]
```diff
@@ -198,20 +207,33 @@ internal void AbortIO(bool clientDisconnect)
...
+                        // If we cancel the cts, we don't dispose as people may still be using
+                        // the cts. It also isn't necessary to dispose a canceled cts.
+                        localAbortCts?.Cancel();
                     }
                     catch (Exception ex)
                     {
                         Log.ApplicationError(_logger, ((IHttpConnectionFeature)this).ConnectionId, TraceIdentifier, ex);
                     }
-                });
+                }, this, preferLocal: false);
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: Use the state parameter smh 😆

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs (hunk 4 above)
Comment (jkotalik) [reply src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: It represents whether the client was the one to initiate the abort or not. This would be true if we called WriteAsync and it threw a ConnectionResetException, and false if the server initiated the abort (ctx.Abort()). In both scenarios I believe we should try to cancel the abortedCts if it exists.

I think no matter what, we want RequestAborted to fire if the client or server disconnected.

File: src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs [hunk 6]
```diff
@@ -52,7 +54,7 @@ public async Task WritesSucceedAfterClientDisconnect()
         }
 
         [ConditionalFact]
-        [Flaky("https://github.com/aspnet/AspNetCore-Internal/issues/1831", FlakyOn.All)]
+        [Repeat(20)]
```
Comment (halter73) [inline src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs]: Nit: you might save a few cycles if you put a small Task.Delay in the while(true) loop that calls WriteAsync.  Or a lot of cycles depending how long it takes to observe backpressure or the RequestAborted firing.

File: src/Servers/IIS/IIS/test/IIS.Tests/ResponseAbortTests.cs [hunk 7]
```diff
@@ -138,6 +138,31 @@ public async Task RequestAbortedIsTrippedAfterAbort()
...
+                var token = ctx.RequestAborted;
+                var originalRegistration = token.Register(() => { });
+
+                ctx.Abort();
+
+                Assert.True(token.WaitHandle.WaitOne(10000));
+                Assert.True(ctx.RequestAborted.WaitHandle.WaitOne(10000));
+                Assert.Equal(token, originalRegistration.Token);
+
+                await Task.CompletedTask;
```
Comment (halter73) [inline src/Servers/IIS/IIS/test/IIS.Tests/ResponseAbortTests.cs]: lol

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
File an issue for creating a LazyResettableCts type so we can backlog it 😉

File: src/Servers/IIS/IIS/test/IIS.Tests/ResponseAbortTests.cs (hunk 7 above)
Comment (jkotalik) [reply src/Servers/IIS/IIS/test/IIS.Tests/ResponseAbortTests.cs]: Nothing to see here (̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs [hunk 8]
```diff
@@ -198,20 +207,33 @@ internal void AbortIO(bool clientDisconnect)
 
             _bodyOutput.Dispose();
 
-            var cts = _abortedCts;
-            if (cts != null)
+            if (shouldScheduleCancellation)
             {
-                ThreadPool.QueueUserWorkItem(t =>
+                // Potentially calling user code. CancelRequestAbortedToken logs any exceptions.
```
Comment (Tratcher) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IO.cs]: CancelRequestAbortedToken sounds like a great place to put this code.

**Review by Tratcher — APPROVED** [review]

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/issues/9419

**Comment by jkotalik** [comment]
Debugging the inproc failure with NTLM tests. Seems like there was a failed request.

**Comment by jkotalik** [comment]
Figured it out, bad check for requestAborted.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs [hunk 9]
```diff
@@ -12,6 +11,8 @@ internal partial class IISHttpContext : IHttpRequestLifetimeFeature
     {
         private CancellationTokenSource _abortedCts;
         private CancellationToken? _manuallySetRequestAbortToken;
+        private object _abortLock = new object();
+        protected bool _requestAborted;
```
Comment (halter73) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.IHttpRequestLifetimeFeature.cs]: [In Kestrel this is volatile](https://github.com/aspnet/AspNetCore/blob/d957bc38a5eea8705c8777ae1094e62e6efdd93e/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L38). Observing an abort late isn't the end of the world, but since you're removing the Volatile.Reads and Interlocked.Exchanges used to access this before, you might as well make this field volatile.

**Comment by jkotalik** [comment]
@javiercn 
`YARN : error [ERR_STREAM_WRITE_AFTER_END]: write after end [F:\workspace\_work\1\s\src\SignalR\clients\ts\FunctionalTests\SignalR.Npm.FunctionalTests.npmproj]`

https://dev.azure.com/dnceng/public/_build/results?buildId=157804

**Comment by javiercn** [comment]
Never seen that one before.

**Comment by anurse** [comment]
That's in SignalR (cc @mikaelm12)

Doesn't seem like something we can control...
