### PR TITLE
Make default stack size to be 1 MB in base16

### LINKED ISSUE #60762: stackSize override is not correct value format
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When aspnetcore for in process hosting overrides the default stack size for new threads on the threadpool (https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-9.0) the value is incorrectly defaulted. https://github.com/dotnet/aspnetcore/blob/e05d6f6cb38617e2092e842fb7fb76ebf257cbba/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp#L68

https://github.com/dotnet/aspnetcore/commit/3be11f6544485948ba17646ffa7b4242c2c5339a

The internals of coreclr is looking for the value as base16. The default value of 1048576 is treating as base16. This is not 1 MB. This is 17 MB.

If you take a memory dump of an inprocess hosted .net core 8 app and view !address -f:MEM_RESERVE,Stack you will notice reserved memory for stack around this 0x1048576 size. In 32bit world this is a bad situation as you will run out of memory if your process needs to create many threads.

In the learning document it indicates how to set it to 2MB however this actually would set it to 34~ MB.

### Expected Behavior

Actually set stack to a reasonable size similar to what .net core does by default 1.5 MB for 32bit app and 4MB for x64.

### Steps To Reproduce

If you take a memory dump of an inprocess hosted .net core 8 app and view !address -f:MEM_RESERVE,Stack you will notice reserved memory for stack around this 0x1048576 size. In 32bit world this is a bad situation as you will run out of memory if your process needs to create many threads.

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by clintwar**
# Make default stack size to be 1 MB in base16

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description
Current default is expressed in decimal, however that is much larger than desired default.

Fixes #60762

### CODE REVIEW

**Review by mgravell — APPROVED** [review]

**Review by apurvghai — APPROVED** [review]

File: src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp [hunk 1]
```diff
@@ -65,7 +65,7 @@ InProcessOptions::InProcessOptions(const ConfigurationSource &configurationSourc
     const auto handlerSettings = aspNetCoreSection->GetKeyValuePairs(CS_ASPNETCORE_HANDLER_SETTINGS);
     m_fSetCurrentDirectory = equals_ignore_case(find_element(handlerSettings, CS_ASPNETCORE_HANDLER_SET_CURRENT_DIRECTORY).value_or(L"true"), L"true");
     m_fCallStartupHook = equals_ignore_case(find_element(handlerSettings, CS_ASPNETCORE_HANDLER_CALL_STARTUP_HOOK).value_or(L"true"), L"true");
-    m_strStackSize = find_element(handlerSettings, CS_ASPNETCORE_HANDLER_STACK_SIZE).value_or(L"1048576");
+    m_strStackSize = find_element(handlerSettings, CS_ASPNETCORE_HANDLER_STACK_SIZE).value_or(L"100000"); // this is correct as it should be in base16 1 MB
```
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp:68]:
```suggestion
    m_strStackSize = find_element(handlerSettings, CS_ASPNETCORE_HANDLER_STACK_SIZE).value_or(L"100000"); // 1 MB in hex
```

Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp:68]: I might actually also rename the variable to indicate the base.

**Comment by adityamandaleeka** [comment]
Thanks for finding and fixing this!

File: src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp (hunk 1 above)
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp:68]: Can we put an 0x in front of this for clarity as well?

Comment (clintwar) [reply src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessOptions.cpp]: addressed

**Comment by adityamandaleeka** [comment]
Sorry for the confusion here, but I just realized that the default stack size should already be 1MB... why are we ever setting this explicitly if the config option isn't set? We should confirm that the default is 1MB and just not set it unless the user specified something else.

**Comment by clintwar** [comment]
and actually for x64 I believe it is 4 MB

**Comment by adityamandaleeka** [comment]
Just checked... it seems like it's 1.5 MB for both 32 and 64 bit on Windows, for .NET console apps. However, I'm not sure that also applies in the IIS case. Will confirm that.

**Comment by adityamandaleeka** [comment]
Looks like in IIS we might have smaller stacks. With that in mind, this change seems fine (and strictly better than it was before).

**Review by adityamandaleeka — APPROVED** [review]

**Comment by clintwar** [comment]
Do the checks need to be re-enqueued?

**Comment by clintwar** [comment]
I am not sure about those 3 other checks but they seem to have failed again.

**Comment by clintwar** [comment]
Seems like build is still failing all checks.
