### PR TITLE
Fix pRequestInfo INVALID_POINTER_READ caused by GCs

### LINKED ISSUE #50445: Crash due to INVALID_POINTER_READ NativeRequestContext.GetRequestInfo
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the IHttpSysRequestInfoFeature it's possible to hit invalid pointer read errors which causes a process crash. It's also possible to hit other issue (see below). The error occurs when a GC moves to memory of the request's _backingBuffer before trying to access the RequestInfo property of IHttpSysRequestInfoFeature. 

The issue is with [this](https://github.com/dotnet/aspnetcore/blob/7eec26ec37f0277f13340ed959e2bec778b647fd/src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs#L765C13-L765C62) line of code. Indexing into the pointer will try to deference it but the pointer first needs to be adjusted using the baseAddress to account for any GC moves. 

```c#
var requestInfo = nativeRequest->pRequestInfo[i];
```

### Expected Behavior

No exceptions should happen. 

### Steps To Reproduce

_No response_

### Exceptions (if any)

The bug can surface in a few different ways, depending on exactly how the memory was moved around.

## INVALID_POINTER_READ crash
This happens when the memory where pRequestInfo points to in no longer valid for the application to reference. 

## ArgumentOutOfRangeException

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.AspNetCore.HttpSys.Internal.NativeRequestContext.GetRequestInfo(IntPtr baseAddress, HTTP_REQUEST_V2* nativeRequest)
   at Microsoft.AspNetCore.HttpSys.Internal.NativeRequestContext.GetRequestInfo()
   at Microsoft.AspNetCore.Server.HttpSys.Request.get_RequestInfo()
   at Nanorouter.Metering.RequestTimingFeature.GetHttpSysTimestamps()
```

## ArgumentException

```
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.AspNetCore.HttpSys.Internal.NativeRequestContext.GetRequestInfo(IntPtr baseAddress, HTTP_REQUEST_V2* nativeRequest)
   at Microsoft.AspNetCore.HttpSys.Internal.NativeRequestContext.GetRequestInfo()
   at Microsoft.AspNetCore.Server.HttpSys.Request.get_RequestInfo()
   at Nanorouter.Metering.RequestTimingFeature.GetHttpSysTimestamps()
```

### .NET Version

6.0.21

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NGloreous**
# Fix pRequestInfo INVALID_POINTER_READ caused by GCs

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

When using the IHttpSysRequestInfoFeature it's possible to hit invalid pointer read errors which causes a process crash. It's also possible to hit other issue caused by the invalid pointer. The error occurs when a GC moves to memory of the request's _backingBuffer before trying to access the RequestInfo property of IHttpSysRequestInfoFeature. 

The fix is to adjust the pRequestInfo pointer similar to how other pointers in this class are adjusted.

Fixes #50445

### CODE REVIEW

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs [hunk 1]
```diff
@@ -760,9 +760,12 @@ private uint GetChunksHelper(ref int dataChunkIndex, ref uint dataChunkOffset, b
 
         var info = new Dictionary<int, ReadOnlyMemory<byte>>(count);
 
+        long fixup = (byte*)nativeRequest - (byte*)baseAddress;
+        var pRequestInfo = (HttpApiTypes.HTTP_REQUEST_INFO*)((byte*)nativeRequest->pRequestInfo + fixup);
```
Comment (BrennanConroy) [inline src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: Is the `baseAddress` usage in `_backingBuffer.Memory.Slice((int)((long)requestInfo.pInfo - (long)baseAddress)` needed anymore if we're already adjusting the pointer?

Comment (Tratcher) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: Comparing to https://github.com/dotnet/aspnetcore/blob/137c9aa6792390c20ed0f7c98468d4c9a7dda983/src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs#L812C79-L812C86, should that be + fixup instead?

**Comment by Tratcher** [comment]
Once merged this will also need to be backported to release/8.0. There's a bot we can use for that.

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs (hunk 1 above)
Comment (NGloreous) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: @BrennanConroy yes that other fixup is still needed because that is also a pointer to the possibly old location of that data. 

@Tratcher yes, good catch.

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs [hunk 2]
```diff
@@ -760,9 +760,12 @@ private uint GetChunksHelper(ref int dataChunkIndex, ref uint dataChunkOffset, b
 
         var info = new Dictionary<int, ReadOnlyMemory<byte>>(count);
 
+        long fixup = (byte*)nativeRequest - (byte*)baseAddress;
```
[the remark this answers is not in the document]
Comment (NGloreous) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:763]: @gfoidl are there guidelines on this? I was just being consistent with usage in this file. Also using var here seems wrong to me since it's non-obvious it's a long to me at least :)

File: src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs (hunk 1 above)
Comment (BrennanConroy) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: > that is also a pointer to the possibly old location of that data

Ah, should have noticed the `p` prefix on the property 😄 I assumed it was the actual data so adding a pointer wouldn't have made sense.

Comment (NGloreous) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: @BrennanConroy yes it's not confusing at all :) I knew there was a bug in this code and I started at it for quite a while and didn't catch it. It too a memory dump to find it.

Comment (NGloreous) [reply src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs:764]: @Tratcher I think what I have is correct.

**Review by Tratcher — APPROVED** [review]
