### PR TITLE
no dispatchGlobalEventToAllElements when no renderer attached

### LINKED ISSUE #57828: clean up global event listener, when connection closed
I found the ROOT CAUSE, @javiercn can we clean up the global event listener, when connection closed?
when Blazor connection closed, the [detachWebRendererInterop](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts#L160C45-L160C69) in the callback of connection.onclose will be invoked. here, it will invoke [interopMethodsByRenderer.delete(rendererId);](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L48C1-L49C1), all the interopMethodsByRenderer will be cleaned. also There are lots of global event listener in form.js like window.addEventListener('focus'), window.addEventListener('keydown'). if user still interact with our app like focus, click, the global event will be triggered, then invoked [EventDelegator.onGlobalEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L134), invoked [EventDelegator.dispatchGlobalEventToAllElements](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L153) invoked [WebRendererInteropMethods.dispatchEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L66C17-L66C30) invoked [WebRendererInteropMethods.getInteropMethods](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L78C10-L78C27), here since the interopMethodsByRenderer is empty, will throw this exception.

_Originally posted by @zuizuihao in https://github.com/dotnet/aspnetcore/issues/56813#issuecomment-2345157777_

### PR DESCRIPTION
**Pull request by zuizuihao**
## ROOT CAUSE
when Blazor connection closed, the [detachWebRendererInterop](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts#L160C45-L160C69) in the callback of connection.onclose will be invoked. here, it will invoke [interopMethodsByRenderer.delete(rendererId);](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L48C1-L49C1), all the interopMethodsByRenderer will be cleaned. also There are lots of global event listener in form.js like window.addEventListener('focus'), window.addEventListener('keydown'). if user still interact with our app like focus, click, the global event will be triggered, then invoked [EventDelegator.onGlobalEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L134), invoked [EventDelegator.dispatchGlobalEventToAllElements](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L153) invoked [WebRendererInteropMethods.dispatchEvent](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L66C17-L66C30) invoked [WebRendererInteropMethods.getInteropMethods](https://github.com/dotnet/aspnetcore/blob/7e21f2e65a5dfaed143015cfbcf0139ce3cce8da/src/Components/Web.JS/src/Rendering/WebRendererInteropMethods.ts#L78C10-L78C27), here since the interopMethodsByRenderer is empty, will throw this exception.

## SOLUTION:
check isRendererAttached before dispatchGlobalEventToAllElements in EventDelegator

Fixes #57828 

Before Fixes:
no_interop_methods_for_render

After Fixes:
no_interop_methods_for_render_solution

### CODE REVIEW

**Comment by zuizuihao** [comment]
any progress on it @javiercn

**Comment by tomvandyckVdP** [comment]
I've got the impression quite some people are experiencing this issues ... any updates on the solution please?

**Comment by jscott1277** [comment]
Would love to see this fix get merged in as well.  Thanks!

File: src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts [hunk 1]
```diff
@@ -136,6 +136,13 @@ export class EventDelegator {
       return;
     }
 
+    if (!isRendererAttached(this.browserRendererId)) {
+      // when connection closed, it will detachWebRendererInterop, so we need to check if the renderer is still attached
+      const targetElement = evt.target as Element;
+      console.warn(`${evt.type} on ${targetElement.localName}${targetElement.className ? ' with class ' + targetElement.className : ''} is not handled because the renderer is not attached`);
```
Comment (javiercn) [inline src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts:142]:
```suggestion
```
I don't think we need the warn here. We don't log to the console directly, in any case we would use the logger, but more importantly, this is a valid scenario that shouldn't result in a warning.

**Review by javiercn — APPROVED** [review]

**Comment by tomvandyckVdP** [comment]
@dotnet-policy-service agree



Met vriendelijke groet, Meilleures salutations, Best regards, Mit freundlichen Grüssen, Cordiali saluti,


Transport Van de Poel
Atealaan 32
2270 Herenthout
Belgium

www.vandepoel.com
Tom Van Dyck
ICT

***@***.***  +32 14 28 38 24
***@***.***  +32 485 55 76 65
***@***.***  ***@***.***
