### PR TITLE
Fix circular reference resolution for schemas containing arrays

### LINKED ISSUE #64048: OpenApi components schema $ref may not correct
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

My Cshrap models:

```csharp
public class SystemPermissionGroup : EntityBase
{
    /// <summary>
    /// 
    /// </summary>
    [MaxLength(30)]
    public required string Name { get; set; }
    /// <summary>
    /// 
    /// </summary>
    [MaxLength(1000)]
    public string? Description { get; set; }

    public ICollection<SystemPermission> Permissions { get; set; } = [];

    public ICollection<SystemRole> Roles { get; set; } = [];
}

```

OpenApi Json:

```json
   "SystemPermissionGroup": {
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "maxLength": 30,
            "type": "string",
            "description": "权限名称标识"
          },
          "description": {
            "maxLength": 1000,
            "type": [
              "null",
              "string"
            ],
            "description": "权限说明"
          },
          "permissions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SystemPermission"
            }
          },
          "roles": {
            "$ref": "#/components/schemas/SystemUserInfoDto/properties/systemRoles/items/properties/permissionGroups/items/properties/permissions/items/properties/group/properties/roles"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "createdTime": {
            "type": "string",
            "format": "date-time"
          },
          "updatedTime": {
            "type": "string",
            "format": "date-time"
          },
          "isDeleted": {
            "type": "boolean"
          }
        }
      },

```

see the roles $ref:

```json
 "roles": {
    "$ref": "#/components/schemas/SystemUserInfoDto/properties/systemRoles/items/properties/permissionGroups/items/properties/permissions/items/properties/group/properties/roles"
  }
```

💀💀 What's this?

But `permissions` schema is correct.

And I did have a `SystemUserInfoDto` model:

```chsrap
public class SystemUserInfoDto
{
    /// <summary>
    /// user name
    /// </summary>
    [MaxLength(30)]
    public required string UserName { get; set; }

    public Guid Id { get; set; }
    public ICollection<SystemRole> SystemRoles { get; set; } = [];
}
```

### Expected Behavior

the roles schema should be like:

```json
"roles": {
  "type": "array",
  "items": {
    "$ref": "#/components/schemas/SystemRole"
  }
},
```

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

.net10.rc1   .net10.rc2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by desjoerd**
# OpenAPI: Fix component $ref registration into the workspace so references get resolved correctly

The fix is done by registering components before going deep into the recursion tree (where the leaves would be registered first).

Fixing this revealed an issue for default values for "local" attributes. Local attributes/parameter info should not apply to componetized schemas.

## Background on the changes:

The main change is to register components in the `Workspace` with the correct id, this is done via `document.AddComponent(schemaId, schema)`. This changes two things:
1. The schema will be registered correctly so the document can resolve schema references
2. `document.AddComponent(schemaId, schema)` does not overwrite an existing schema with the same id, this is completely different in how it worked, as the current implementation overwrites the schema. So from Last registration wins to the First registration wins.

Because of this the components need to be registered before completely resolving references (to make sure the first one wins and it handles circular references). So the actual registration is moved up in `ResolveSchemaReferences`. By having this moved up, and because the openapi document now resolves references correctly a lot of logic in ResolveSchemaReferences was not required any more.

### Subreferences
The logic around sub references is removed as this does not occur in any of the code paths, or it gave unwanted results, for example #64048.

Fixes #64048
Fixes #63598

### CODE REVIEW

**Comment by desjoerd** [comment]
@captainsafia  I am just putting it out there, there is still some "dirty" code. I know this has a bit of a "refactor" vibe, but that is not my intention. By diving deep into the "patching" of the JsonSchemaExporter's result, I think this would be the best solution for now.

I've added two more tests for different orderings as the schema exporting logic sometimes feels a bit like a lottery.

I needed to fix the "default" on the schema reference and the test, as "default" values from a controller action should not apply to a componetized schema. Do you want me to add a test to proof it was an issue. That is, the `Status` enum is also used as the response, which should not have the `default` set based on the parameter info. As it's applied to the componetized schema it would set the `default` for this schema on all locations that it is used.

~~When you agree with this direction for the fix I am going to check if it possibly fixes https://github.com/dotnet/aspnetcore/issues/64024 as well.~~

Edit: will fix the nullability warnings in the tests tomorrow.

**Comment by desjoerd** [comment]
It also fixes the component registration in the workspace, as they where not registered correctly. It makes https://github.com/dotnet/aspnetcore/pull/63606 obsolete.

As we the schema is added immediately there was a check required to not overwrite the schema. `document.AddComponent` does this check for us, and registers the component in the correct location of the Workspace.

**Comment by desjoerd** [comment]
@captainsafia I am sorry, the PR is now bigger.... I could not help it 🫣. I was going through the flows and if statements, and I noticed the cases at the end did nothing anymore (or would result in a undesired result, another issue which someone would need to fix). The resolving of references is now quite a bit simplified.

I am fine to revert this commit (for portback) https://github.com/dotnet/aspnetcore/pull/64109/commits/32a3dd18a3123f184953a167b1a850381b9db833 and do it as a seperate PR.

File: src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs [hunk 1]
```diff
@@ -18,4 +20,43 @@ public static IOpenApiSchema CreateOneOfNullableWrapper(this IOpenApiSchema orig
...
+            && !string.IsNullOrEmpty(schemaIdString))
+        {
+            schemaId = schemaIdString;
+            return true;
+        }
+        schemaId = string.Empty;
+        return false;
+    }
+
+    public static OpenApiSchemaReference CreateReference(this OpenApiSchema schema, OpenApiDocument document)
```
Comment (captainsafia) [inline src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs]: Is this called anywhere? Doesn't seem like it?

File: src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs [hunk 2]
```diff
@@ -429,6 +434,36 @@ internal static void ApplySchemaReferenceId(this JsonNode schema, JsonSchemaExpo
         }
     }
 
+    /// <summary>
+    /// Determines whether the specified JSON schema will be moved into the components section.
+    /// </summary>
+    /// <param name="schema">The <see cref="JsonNode"/> produced by the underlying schema generator.</param>
+    /// <returns><see langword="true"/> if the schema will be componentized; otherwise, <see langword="false"/>.</returns>
+    internal static bool WillBeComponentized(this JsonNode schema)
```
Comment (captainsafia) [inline src/OpenApi/src/Extensions/JsonNodeSchemaExtensions.cs:442]: I like introducing these APIs! Cleans up a lot of these checks in the codebase.

File: src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs (hunk 1 above)
Comment (desjoerd) [reply src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs]: Ah, this was before I found out that I could do everything via the workspace by registering it first before resolving references. Will fix tomorrow!

File: src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs [hunk 3]
```diff
@@ -14,28 +14,33 @@ internal static class OpenApiDocumentExtensions
     /// <param name="document">The <see cref="OpenApiDocument"/> to register the schema onto.</param>
     /// <param name="schemaId">The ID that serves as the key for the schema in the schema store.</param>
     /// <param name="schema">The <see cref="IOpenApiSchema" /> to register into the document.</param>
-    /// <returns>An <see cref="IOpenApiSchema"/> with a reference to the stored schema.</returns>
-    public static IOpenApiSchema AddOpenApiSchemaByReference(this OpenApiDocument document, string schemaId, IOpenApiSchema schema)
+    /// <param name="schemaReference">An <see cref="IOpenApiSchema"/> with a reference to the stored schema.</param>
+    /// <returns>Whether the schema was added or already existed</returns>
```
Comment (martincostello) [inline src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs]:
```suggestion
    /// <returns>Whether the schema was added or already existed.</returns>
```

File: src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs [hunk 4]
```diff
@@ -14,28 +14,33 @@ internal static class OpenApiDocumentExtensions
...
         document.Workspace ??= new();
-        var location = document.BaseUri + "/components/schemas/" + schemaId;
-        document.Workspace.RegisterComponentForDocument(document, schema, location);
+        // AddComponent will only add the schema if it doesn't already exist.
+        var schemaAdded = document.AddComponent(schemaId, schema);
 
         object? description = null;
         object? example = null;
+        object? defaultAnnotation = null;
         if (schema is OpenApiSchema actualSchema)
```
Comment (martincostello) [inline src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs]: Could add a null check for metadata here, then the next three lines don't need the `?`.

File: src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs [hunk 5]
```diff
@@ -18,4 +18,21 @@ public static IOpenApiSchema CreateOneOfNullableWrapper(this IOpenApiSchema orig
...
+    {
+        if(schema.Metadata is not null
+            && schema.Metadata.TryGetValue(OpenApiConstants.SchemaId, out var schemaIdAsObject)
+            && schemaIdAsObject is string schemaIdString
+            && !string.IsNullOrEmpty(schemaIdString))
+        {
+            schemaId = schemaIdString;
+            return true;
+        }
+        schemaId = string.Empty;
```
Comment (martincostello) [inline src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs]: Just curious, why does this return empty when the other extension of the same name returns null?

Comment (captainsafia) [reply src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs]: Yep, good spot. This should probably be null. It might've passed the sniff test because we use `IsNullOrEmpty` to evaluate the ID in a bunch of places.

File: src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs (hunk 4 above)
Comment (desjoerd) [reply src/OpenApi/src/Extensions/OpenApiDocumentExtensions.cs]: Done!

File: src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs (hunk 5 above)
Comment (desjoerd) [reply src/OpenApi/src/Extensions/OpenApiSchemaExtensions.cs]: Fixed!

**Comment by desjoerd** [comment]
@captainsafia and @martincostello I've fixed the comments.

Just a note, I've also removed the x-ref-id Metadata which contained the "original" $ref from the JsonSchemaExporter as it was not used anymkre in any of the code paths.

**Review by captainsafia — APPROVED** [review]
