### PR TITLE
Ensure error boundary service is registered as part of call to AddBlazorWebView

### LINKED ISSUE #4502: Blazor Hybrid WinForms apps give error if there's an ErrorBoundary
### Description

Ironically it's the `ErrorBoundary` that *causes* the error.

image

This may also affect WPF/MAUI but I haven't tried those yet.

### Steps to Reproduce

Put `<ErrorBoundary>` inside a Blazor Hybrid WinForms app.

Fix: We need to add a default `IErrorBoundaryLogger` to the DI container. Presumably it should just log to console.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/maui/issues/4502

* This brings AddBlazorWebView to parity with other AddBlazor* equivalents.
* I was able to verify that the change worked with a 6.0 version of a WinForms app.

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

File: src/Components/WebView/WebView/src/Services/WebViewErrorBoundaryLogger.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    public WebViewErrorBoundaryLogger(ILogger<ErrorBoundary> errorBoundaryLogger)
+    {
+        _errorBoundaryLogger = errorBoundaryLogger;
+    }
+
+    public ValueTask LogErrorAsync(Exception exception)
+    {
+        // For, client-side code, all internal state is visible to the end user. We can just
+        // log directly to the console.
+        _errorBoundaryLogger.LogError(exception, exception.ToString());
```
Comment (Kahbazi) [inline src/Components/WebView/WebView/src/Services/WebViewErrorBoundaryLogger.cs:22]:
```suggestion
        _errorBoundaryLogger.LogError(exception, exception.Message);
```
I'm not sure if I'm right, but most `ILogger` implementations would add `exception.ToString()` to their log and passing `exception.ToString()` might be redundant.
https://github.com/dotnet/aspnetcore/blob/5fb8db4fdb67ca22f18f356df4916dceccd05066/src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs#L136

**Review by SteveSandersonMS — APPROVED** [review]
