### PR TITLE
Fix NavigationManager.Refresh() on SSR-only pages

### LINKED ISSUE #51222: NavigationManager.Refresh throws on SSR-only pages
It throws:

> NotImplementedException: The type Microsoft.AspNetCore.Components.Endpoints.HttpNavigationManager does not support supplying NavigationOptions. To add support, that type should override NavigateToCore(string uri, NavigationOptions options).

As far as I know, `NavigationManager.Refresh` should be supported and should be equivalent to calling `Nav.NavigateTo(Nav.Uri)` (which does work).

### LINKED ISSUE #51482: [Blazor] `NavigationManager.Refresh()` fails during static server rendering if server interactivity is enabled
If Blazor server interactivity is enabled via `IRazorComponentsBuilder.AddInteractiveServerComponents()`, then attempting to call `NavigationManager.Refresh()` during static server rendering throws the following exception:

```text
System.ArgumentNullException: Value cannot be null. (Parameter 'jsRuntime')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) in C:\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\JSRuntimeExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass14_0.<<Refresh>g__RefreshAsync|0>d.MoveNext() in C:\aspnetcore\src\Components\Server\src\Circuits\RemoteNavigationManager.cs:line 129
```

This can be easily fixed by updating the `RemoteNavigationManager.Refresh()` implementation to throw a `NavigationException` if `RemoteNavigationManager._jsRuntime` is `null`, similar to what happens in `RemoteNavigationManager.NavigateToCore()`.

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fix NavigationManager.Refresh() on SSR-only pages

1. Fixes NavigationManager.Refresh() on SSR-only pages with no interactivity present by implementing the missing method in `HttpNavigationManager.cs`.

2. Fixes NavigationManager.Refresh() on SSR-only pages with server interactivity enabled by throwing `NavigationException` in `RemoteNavigationManager.Refresh()`.

3. In order to **not** push new history entry when enhanced navigation is on and `NavigationManager.Refresh()` has occured we check on the client side that redirection URL is the same as the current URL. This also affects `NavigationManager.NavigateTo(NavigationManager.Uri)`.

Fixes #51222
Fixes #51482

### CODE REVIEW

File: src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Prerendering.cs [hunk 1]
```diff
@@ -81,6 +82,15 @@ public static void MarkAsAllowingEnhancedNavigation(HttpContext context)
         context.Response.Headers.Add("blazor-enhanced-nav", "allow");
     }
 
+    public static void ProcessEnhancedNavigationReplaceHistoryCookie(HttpContext context)
+    {
+        if (context.Request.Cookies.ContainsKey(_enhancedNavReplaceHistory))
+        {
+            context.Response.Headers.Add(_enhancedNavReplaceHistory, "true");
+            context.Response.Cookies.Delete(_enhancedNavReplaceHistory);
+        }
```
[the remark this answers is not in the document]
Comment (SteveSandersonMS) [reply src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.Prerendering.cs:91]: Unfortunately that's not really true. `redirect: manual` does **not** do what everyone thinks it will do. In fact, unless you're writing a service worker, there's basically nothing useful that it does at all. See https://stackoverflow.com/questions/42716082/fetch-api-whats-the-use-of-redirect-manual for more info, or generally search for the hundreds of posts across the web where people really cannot believe that `redirect: manual` is this unhelpful, but it actually is :)

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts [hunk 2]
```diff
@@ -239,7 +240,10 @@ export async function performEnhancedPageLoad(internalDestinationHref: string, i
           history.replaceState(null, '', response.url);
         } else {
           // For non-gets, we're still on the source page, so need to append a whole new history entry
-          history.pushState(null, '', response.url);
+          if (response.url !== previousLocation)
+          {
```
Comment (SteveSandersonMS) [inline src/Components/Web.JS/src/Services/NavigationEnhancement.ts:244]:
```suggestion
          if (response.url !== previousLocation) {
```

Also, just out of curiosity, could you say why we need to capture `location.href` in the `previousLocation` variable? Would it be different if the code checked `if (response.url !== location.href)` directly here?

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Forms/FormThatCallsNavigationManagerRefresh.razor [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+
+    private Guid Guid = Guid.NewGuid();
+
+    protected override void OnInitialized()
+    {
+
+        var httpContext = HttpContextAccessor.HttpContext;
+        _method = httpContext?.Request.Method;
+
+        base.OnInitialized();
```
Comment (SteveSandersonMS) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Forms/FormThatCallsNavigationManagerRefresh.razor:28]:
```suggestion
        var httpContext = HttpContextAccessor.HttpContext;
        _method = httpContext?.Request.Method;
```

Comment (SteveSandersonMS) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Forms/FormThatCallsNavigationManagerRefresh.razor:28]: Nit: no need to call `base` here

**Review by SteveSandersonMS — APPROVED** [review]
Looks great!

File: src/Components/Web.JS/src/Services/NavigationEnhancement.ts (hunk 2 above)
Comment (surayya-MS) [reply src/Components/Web.JS/src/Services/NavigationEnhancement.ts:244]: I checked `if (response.url !== location.href)` and it works the same. I mistakenly assumed that the location would be changed when this check is happening. I'll change the code. Thanks!
