### PR TITLE
Clarify DefaultPolicy and FallbackPolicy Behavior in XML Docs

### LINKED ISSUE #60452: Authorization FallbackPolicy is misleading
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using the Fall back policy like;

```c#
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});
```

And configuring the endpoint auth with either `app.MapControllers().RequireAuthorization();` or adding an empty attribute `[Authorize]`. It uses the default auth policy. Even though another auth policy has not been defined.

This might be intended but could lead to some big headaches for teams. As the Attribute `AuthorizeAttribute` dose not require you to set the policy adding something like `[Authorize(AuthenticationSchemes = "example")]` would cause the endpoint to use the default not the fallback. This could lead to some sad times if it's not caught before prod.

This might be internecinal design, looking at the [class responsible](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Core/src/AuthorizationPolicy.cs) for this the occurs as by using any auth header or by setting an empty `app.MapControllers().RequireAuthorization()` the code loops though the `authorizeData` and as no policies have explicitly been set uses the default.

This seems unintuitive to me, and if you agree I think adding a check before adding the default to try and get the fallback policy, mean is used over the default. Since the user has explicitly set the fallback, but not named another policy, and can not have a null default policy.

### Expected Behavior

The fallback will be used in all cases where no policy has been explicitly provided, including when a policy attribute has been provided but the policy property has not been set.

If the design is intended to be misleading in this way code docs on FallbackPolicy explaining this and updated docs would be useful.

### Steps To Reproduce

Create a project, and add a fallback policy. Then add in an empty auth attribute on either a controller or when mapping the endpoints.

### Exceptions (if any)

_No response_

### .NET Version

Microsoft.AspNetCore.Authorization 8.0.13

also in the current [source].(https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Core/src/AuthorizationPolicy.cs)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shethaadit**
## Description
This PR updates the XML documentation for `DefaultPolicy` and `FallbackPolicy` in the `AuthorizationPolicy` class to provide **clearer explanations of when each policy applies**.  

### **Changes:**  
- **FallbackPolicy:**  
  - Clarifies that it **only applies when no authorization metadata is present** (e.g., no `[Authorize]` attributes or `RequireAuthorization()` calls).  
  - Explains why it is **not used** when an `[Authorize]` attribute is present without a policy name.  
  - Emphasizes that it is **primarily relevant for middleware-based authorization**.  

- **DefaultPolicy:**  
  - States that it **applies whenever authorization is required but no specific policy is set**.  
  - Clarifies that an `[Authorize]` attribute without a policy name will **always use DefaultPolicy instead of FallbackPolicy**.  
  - Provides guidance on explicitly defining policies to avoid confusion.  

### **Why This Change?**  
- Addresses user concerns about **unexpected behavior when using `[Authorize]` without a policy name**.  
- Ensures developers understand **when FallbackPolicy is ignored** and why DefaultPolicy takes precedence.  
- Prevents security risks due to **misinterpretations of policy precedence**.  

Fixes #60452

### CODE REVIEW

File: src/Security/Authorization/Core/src/AuthorizationOptions.cs [hunk 1]
```diff
@@ -24,21 +24,26 @@ public class AuthorizationOptions
...
     /// <summary>
-    /// Gets or sets the default authorization policy. Defaults to require authenticated users.
+    /// Gets or sets the default authorization policy. Defaults to requiring authenticated users.
     /// </summary>
     /// <remarks>
-    /// The default policy used when evaluating <see cref="IAuthorizeData"/> with no policy name specified.
+    /// - The `DefaultPolicy` applies whenever authorization is required, but no specific policy is set.
+    /// - If an `[Authorize]` attribute is present without a policy name, the `DefaultPolicy` is used instead of the `FallbackPolicy`.
+    /// - This behavior ensures that endpoints explicitly requesting authorization (via `[Authorize]` or `RequireAuthorization()`) default to a secure policy.
+    /// - If a different default behavior is needed, developers should explicitly define policies rather than relying on `FallbackPolicy`.
```
Comment (halter73) [inline src/Security/Authorization/Core/src/AuthorizationOptions.cs:33]:
```suggestion
    /// - When non-default behavior is needed, developers should define named policies.
```

I don't think it's worth it to call out the `FallbackPolicy` again here. I think that's well covered by the second bullet point.

**Review by halter73 — APPROVED** [review]
Thanks! This looks like a big improvement.

Part of me wanted to continue to cross-reference `IAuthorizeData` for completeness, but most consumers of the API won't have any familiarity with that and are better served by the new mentions to `[Authorize]` and `RequireAuthorization()`.

**Comment by shethaadit** [comment]
Hi @halter73, Than you for all suggestions. I have committed them. Could you please re-approve and merge?

**Comment by shethaadit** [comment]
> Hi @halter73, Than you for all suggestions. I have committed them. Could you please re-approve and merge?

Hi @halter73, a gentle reminder on this. :)

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Thank you!
