### PR TITLE
Make sure route binding isn't case sensitive

### LINKED ISSUE #35087: Ignore Casing for route parameters in Minimal APIs
### Describe the bug
When the route parameters do not match due to casing, Minimal APIs throws an exception. We would like either to ignore casing and stay consistent with other other attributes. 

### To Reproduce

```c#
   app.MapGet("/user/{FirstName}/{lastName}", ([FromRoute()]string? firstName, [FromRoute()]string lastName) => 
    UserService.GetUser(firstName, lastName, "aa"));
```

### Exceptions (if any)

Error message (Notice FirstName != firstName):
```c#
System.InvalidOperationException: 'firstName is not a route paramter.'
```
### Further technical details
NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21404.12
 Commit:    78fb921136

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21404.12\

Host (useful for support):
  Version: 6.0.0-rc.1.21403.13
  Commit:  c082af307d

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21404.12 [C:\Program Files\dotnet\sdk]

### PR DESCRIPTION
**Pull request by davidfowl**
- For error handling cases, we were doing a case sensitive match against route parameters instead of a case insensitive one.
- Added tests

Fixes https://github.com/dotnet/aspnetcore/issues/35087

### CODE REVIEW

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs [hunk 1]
```diff
@@ -208,7 +208,7 @@ private static Expression CreateArgument(ParameterInfo parameter, FactoryContext
 
             if (parameterCustomAttributes.OfType<IFromRouteMetadata>().FirstOrDefault() is { } routeAttribute)
             {
-                if (factoryContext.RouteParameters is { } routeParams && !routeParams.Contains(parameter.Name))
+                if (factoryContext.RouteParameters is { } routeParams && !routeParams.Contains(parameter.Name, StringComparer.OrdinalIgnoreCase))
```
Comment (pranavkm) [inline src/Http/Http.Extensions/src/RequestDelegateFactory.cs:211]: Isn't this using Linq? Can we turn this in to `HashSet` instead? or write a bespoke iterator? The Linq one will result in allocations: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Contains.cs#L33

**Review by pranavkm — APPROVED** [review]
Tests look great. I know it's a one time cost, but the Linq allocations appears at Startup for a whole slew of data types / parameters and it would be great if we can avoid these allocations.

**Comment by davidfowl** [comment]
We should file another item to measure and fix the low hanging startup performance fruit here

File: src/Http/Http.Extensions/src/RequestDelegateFactory.cs (hunk 1 above)
Comment (davidfowl) [reply src/Http/Http.Extensions/src/RequestDelegateFactory.cs:211]: I think we should do that in another PR and did all the things. But I agree with you. There's too much LINQ usage here at startup
