### PR TITLE
Make H2 WebSockets ignore MaxRequestBodySize and MinRequestBodyDataRate

### LINKED ISSUE #42224: [dotnet-sdk-7.0.100-preview.6.22313.7] Blazor Server apps with System.Net.WebSockets.WebSocketException Error when accessing with https
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**When binding the https for "Kestrel" via appsettings.json, --urls or set the ASPNETCORE_URLS environment variable, Blazor server app site can be launched with https://*:5001, but it will be disconnected about every 5s.**

**Application Name** : eShopOnBlazor, OqtaneFramework, EasyDataBasicDemoBlazorAppServerNet5, Blazorise,BlazorPolyfill(Blazor Server apps running on .net7 preview 6)
**OS:** Windows 10 RS5
**CPU**: X64
**.NET Build Number:** dotnet-sdk-7.0.100-preview.6.22313.7
**Also can check details from Devdiv Bug:**   https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1555938 

### Expected Behavior

App will launch successful.

### Steps To Reproduce

**The machine has dotnet-sdk-7.0.100-preview.6.22313.7 installed**

1) Create blazor server app: dotnet new blazorserver
2) Add this line to appsettings.json for workaround : (https://github.com/dotnet/aspnetcore/issues/42161)
```
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://localhost:5000"
      },
      "Https": {
        "Url": "https://localhost:5001"
      }
    }
  }
}
```
3) Publish the app
4) Run the app
5) Go to https://localhost:5001

### Exceptions (if any)

**App will launch but it will disconnect every 5 seconds**

**Exception:**
```
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "0", Target: "ConnectCircuit", Arguments: [ CfDJ8AYSpQtcIQlEtmnE9v80hhPUStHYmXqWNAynR434yWDQx4lxFI0bjNOgGYkSJ-0lsvSk7UuVPgKlJOWhIL4v_4ssVv69Eir-dHoC8Fckb12Y2SP68Pq5n-z4n77zPzGflvnoD27odwNiHKkFv6MLcuuoC9VOav_bGDF-I_6l8lkFF-dixudaVyKS7tnTLh3-tKZil7zpOEW4NGem_hwOGLw ], StreamIds: [  ] }.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[14]
      Socket connection closed prematurely.
      System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
       ---> System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
      Waiting for the application to finish sending data.

```

### .NET Version

dotnet-sdk-7.0.100-preview.6.22313.7

### Anything else?

```
C:\Users\v-gwei>dotnet --info
.NET SDK:
 Version:   7.0.100-preview.6.22313.7
 Commit:    693b8eb2cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.6.22313.7\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.6.22312.1
  Architecture: x64
  Commit:       5c5e66e6c0

.NET SDKs installed:
  7.0.100-preview.6.22313.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.6.22312.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22312.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.6.22311.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
https://aka.ms/dotnet/runtimes-sdk-info
```
@dotnet-actwx-bot @dotnet/compat

### PR DESCRIPTION
**Pull request by Tratcher**
Contributes to #42101 (I didn't do the part yet about preventing use of the request or response body for these types of requests).
Fixes #42224

H2 WebSockets were using the normal H2 request body, meaning they were subject to the MaxRequestBodySize and MinRequestBodyDataRate limits. This caused issues like an idle blazor page to disconnect every 6 seconds.

I've also further distinguished the CONNECT scenario from the Upgrade scenario by giving it its own state bools.

### CODE REVIEW

File: src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.FeatureCollection.cs [hunk 1]
```diff
@@ -195,7 +195,7 @@ bool IHttpBodyControlFeature.AllowSynchronousIO
         set => AllowSynchronousIO = value;
     }
 
-    bool IHttpMaxRequestBodySizeFeature.IsReadOnly => HasStartedConsumingRequestBody || IsUpgraded;
+    bool IHttpMaxRequestBodySizeFeature.IsReadOnly => HasStartedConsumingRequestBody || IsUpgraded || IsExtendedConnectRequest;
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.FeatureCollection.cs:198]: @halter73 this is what you recommended, but it's actually stricter than Upgrade which only prevents modification after upgrade is called. Neither null out the size limit field, they just ignore it. The data rate limit property is similarly ignored.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.FeatureCollection.cs:198]: I think this is good. With extended CONNECT requests, middleware has not chance to run before the "upgrade" so-to-speak. The request is pre-upgraded.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs [hunk 2]
```diff
@@ -62,7 +64,11 @@ public override void AdvanceTo(SequencePosition consumed, SequencePosition exami
 
         // The HTTP/2 flow control window cannot be larger than 2^31-1 which limits bytesRead.
         _context.OnDataRead((int)newlyExaminedBytes);
-        AddAndCheckObservedBytes(newlyExaminedBytes);
+
+        if (!ExtendedConnect)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:68]:
```suggestion
        // Don't limit extended CONNECT requests to the MaxRequestBodySize.
        if (!ExtendedConnect)
```

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs [hunk 3]
```diff
@@ -19,14 +19,15 @@ public Http2MessageBody(Http2Stream context)
...
+        ExtendedConnect = _context.IsExtendedConnectRequest;
     }
 
     protected override void OnReadStarting()
     {
         // Note ContentLength or MaxRequestBodySize may be null
         var maxRequestBodySize = _context.MaxRequestBodySize;
 
-        if (_context.RequestHeaders.ContentLength > maxRequestBodySize)
+        if (!ExtendedConnect && _context.RequestHeaders.ContentLength > maxRequestBodySize)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:30]:
```suggestion
        if (_context.RequestHeaders.ContentLength > maxRequestBodySize)
```

Do we even allow `Content-Length` request headers for extended CONNECTs? I don't want to add checks for things that cannot happen. I cannot imagine not wanting to reject a `Content-Length` request headers greater than the `MaxRequestBodySize` in any case.

File: src/Servers/Kestrel/Core/src/Internal/Http/MessageBody.cs [hunk 4]
```diff
@@ -122,7 +124,7 @@ protected Task TryStartAsync()
         OnReadStarting();
         _context.HasStartedConsumingRequestBody = true;
 
-        if (!RequestUpgrade)
+        if (!RequestUpgrade && !ExtendedConnect)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/MessageBody.cs:127]: Let's do the same thing in `TryStop`.

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs (hunk 3 above)
Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:30]: You're right that it would be weird to even have a Content-Length, so we don't have to check this here.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs [hunk 5]
```diff
@@ -310,4 +312,130 @@ public async Task HEADERS_Received_ProtocolWithoutCONNECTMethod_Reset()
 
         await StopConnectionAsync(expectedLastStreamId: 1, ignoreNonGoAwayFrames: false);
     }
+
+    [Fact]
+    public async Task ExtendedCONNET_AcceptAsyncStream_IsNotLimitedByMinRequestBodyDataRate()
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:317]:
```suggestion
    public async Task ExtendedCONNECT_AcceptAsyncStream_IsNotLimitedByMinRequestBodyDataRate()
```

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs [hunk 6]
```diff
@@ -310,4 +312,130 @@ public async Task HEADERS_Received_ProtocolWithoutCONNECTMethod_Reset()
...
+        dataFrame = await ExpectAsync(Http2FrameType.DATA,
+            withLength: 0,
+            withFlags: (byte)Http2DataFrameFlags.END_STREAM,
+            withStreamId: 1);
+
+        await StopConnectionAsync(expectedLastStreamId: 1, ignoreNonGoAwayFrames: false);
+    }
+
+    [Fact]
+    public async Task ExtendedCONNET_AcceptAsyncStream_IsNotLimitedByMaxRequestBodySize()
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2WebSocketTests.cs:379]:
```suggestion
    public async Task ExtendedCONNECT_AcceptAsyncStream_IsNotLimitedByMaxRequestBodySize()
```

File: src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs [hunk 7]
```diff
@@ -51,6 +52,7 @@ public override void Reset()
     {
         base.Reset();
         _readResult = default;
+        ExtendedConnect = _context.IsExtendedConnectRequest;
```
Comment (BrennanConroy) [inline src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:55]: Is this correct?

Comment (BrennanConroy) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:55]: Talked offline: yes, basically the context gets reset separately and will have the correct value when the Http2MessageBody is reset

Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:55]: Isn't it always false here though? Let's not make it any more convoluted than necessary.

Comment (JamesNK) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:55]: Could make `ExtendedConnect` virtual, and override in `Http2MessageBody` to wrap `Context.IsExtendedConnectRequest`. Simpler, safer, but very small perf hit of virtual property call.

Comment (Tratcher) [reply src/Servers/Kestrel/Core/src/Internal/Http2/Http2MessageBody.cs:55]: IsExtendedConnectRequest is initialized before Http2MessageBody is reset.

**Review by JamesNK — APPROVED** [review]
