### PR TITLE
Handle JSON comments and trailing commas in user-jwts

### LINKED ISSUE #54814: user-jwts cannot handle comments in JSON secrets.json, and does not inform which file is the problem
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I sometimes keep two or more copies of a configuration value in a project's secrets.json with all but one of them commented out - so that I can quickly and easily switch between values when running the project.

    {
      "ConnectionStrings:Database": "Server=host1....",
      //"ConnectionStrings:Database": "Server=host2....",
      //"ConnectionStrings:Database": "Server=host2....",
    }

When I ran `user-jwts` today it gave me the semi-helpful error

    > dotnet user-jwts create
    '/' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 2 | BytePositionInLine: 2. 

Unfortunately it did not tell me that it was secrets.json to blame, and it took a little while to track down.

### Expected Behavior

Ideally `user-jwts` would simply handle the (admittedly malformed) JSON.  The secrets file has so far been accepted by all the other dotnet tools I've used on the project.

If that is not possible, then it would be incredibly helpful if the error indicated which file the user must fix.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

8.0.200

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by martincostello**
# Handle JSON comments and trailing commas

Handle JSON comments and trailing commas in user secrets files.

## Description

Handle the presence of comments and trailing commas in JSON files processed by `user-jwts` so the JSON serializer doesn't throw exceptions when it encounters them.

Also fixes up some of the IDE suggestions found while making the change.

Fixes #54814

### CODE REVIEW

File: src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs [hunk 1]
```diff
@@ -13,8 +13,10 @@ internal sealed record JwtAuthenticationSchemeSettings(string SchemeName, List<s
     private const string AuthenticationKey = "Authentication";
     private const string SchemesKey = "Schemes";
 
-    private static readonly JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions
+    private static readonly JsonSerializerOptions _jsonSerializerOptions = new()
     {
+        AllowTrailingCommas = true,
```
Comment (amcasey) [inline src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs:18]: Do I understand correctly that the new options will be ignored during serialization (as opposed to deserialization)?

Comment (amcasey) [reply src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs:18]: Given the duplication below, I wonder if it would make more sense to pull out and share deserialization options and leave these as-is.

File: src/Tools/dotnet-user-jwts/test/UserJwtsTests.cs [hunk 2]
```diff
@@ -71,12 +71,10 @@ public void Create_CanModifyExistingScheme()
 
         app.Run(new[] { "create", "--project", project });
         Assert.Contains("New JWT saved", _console.GetOutput());
-        var matches = Regex.Matches(_console.GetOutput(), "New JWT saved with ID '(.*?)'");
```
Comment (amcasey) [inline src/Tools/dotnet-user-jwts/test/UserJwtsTests.cs:74]: FYI to other reviewers - these moved to the bottom of the test.

**Review by amcasey — COMMENTED** [review]
Seems like a win to me.  @captainsafia?

File: src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs (hunk 1 above)
Comment (martincostello) [reply src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs:18]: My understanding is that these two extra options only apply to deserialisation.

I did consider moving the options to a central place so there was 1 not 4, but wasn't sure _where_ to put that one.

Comment (amcasey) [reply src/Tools/dotnet-user-jwts/src/Helpers/JwtAuthenticationSchemeSettings.cs:18]: I'd be okay with putting them in their own file in the Helpers folder.  My concern is that they could get out sync and then the JSON rules would vary from place to place.

File: src/Tools/dotnet-user-jwts/src/Helpers/SerializerOptions.cs [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Text.Json;
+
+namespace Microsoft.AspNetCore.Authentication.JwtBearer.Tools;
+
+internal static class SerializerOptions
```
Comment (martincostello) [inline src/Tools/dotnet-user-jwts/src/Helpers/SerializerOptions.cs:8]: Happy to rename this if there's a better more-specific name.

Comment (amcasey) [reply src/Tools/dotnet-user-jwts/src/Helpers/SerializerOptions.cs:8]: What about "JwtSerializerOptions"?

Comment (amcasey) [reply src/Tools/dotnet-user-jwts/src/Helpers/SerializerOptions.cs:8]: (I don't love mine either but the good name is already taken by the type 😆)

**Review by amcasey — APPROVED** [review]
Thanks!

**Review by captainsafia — COMMENTED** [review]
Retroactive approval! ✅ TY, @martincostello!
