### PR TITLE
BDN workaround for netcoreapp5.0->net5.0 moniker rebranding

### LINKED ISSUE #22915: Mvc.Performance benchmark failing to run: An assembly specified in the application dependencies manifest has already been found but with a different file extension
### Describe the bug
I'm unable to run the benchmarks in Microsoft.AspNetCore.Mvc.Performance due to an issue resolving the dependencies.

### To Reproduce
```powershell
.\build.ps1 -BuildManaged -Configuration Release
cd src\Mvc\benchmarks\Microsoft.AspNetCore.Mvc.Performance
dotnet run -c Release
# run benchmark 2
```

### Exceptions (if any)
// Execute: dotnet "32037691-5c3b-4f41-ae36-96fed54708cd.exe" --benchmarkName "Microsoft.AspNetCore.Mvc.Performance.HelperPerformanceBenchmark.RenderView(ViewPath: "~/Views/HelperPartialTagHelper.cshtml")" --job "Server=True, Toolchain=.NET Core 5.0, InvocationCount=1, RunStrategy=Throughput, UnrollFactor=1" --benchmarkId 4 in C:\dev\dotnet\aspnetcore\artifacts\bin\Microsoft.AspNetCore.Mvc.Performance\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd\bin\Release\net5.0
Error:
  An assembly specified in the application dependencies manifest (32037691-5c3b-4f41-ae36-96fed54708cd.deps.json) has already been found but with a different file extension:
    package: '32037691-5c3b-4f41-ae36-96fed54708cd', version: '5.0.0-dev'
    path: '32037691-5c3b-4f41-ae36-96fed54708cd.dll'
    previously found assembly: 'C:\dev\dotnet\aspnetcore\artifacts\bin\Microsoft.AspNetCore.Mvc.Performance\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd\bin\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd.exe'
ExitCode != 0
// Benchmark Process 5420 has exited with code -2147450740
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

### Further technical details
This happens on current master https://github.com/dotnet/aspnetcore/commit/28b3ab82308c7d2f90894c9bac0f40333557acbb

### PR DESCRIPTION
**Pull request by adamsitnik**
A workaround for BDN bug caused by netcoreapp5.0->net5.0 moniker rebranding

The proper fix is available at: https://github.com/dotnet/BenchmarkDotNet/pull/1479 but before we ship new BDN version to NuGet.org (most probably a matter of months) you can use this workaround.

@JamesNK 

Fixes https://github.com/dotnet/aspnetcore/issues/22915

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
Confirmed that this works. Temporary work around can be removed when updating to new BDN.

File: src/Shared/BenchmarkRunner/Program.cs [hunk 1]
```diff
@@ -57,6 +60,24 @@ private static int Main(string[] args)
...
+        private static IConfig GetConfig()
+        {
+#if NET5_0 || NETCOREAPP5_0
+            return ManualConfig.CreateEmpty()
+                .AddJob(Job.Default
+                    .WithToolchain(CsProjCoreToolchain.From(new NetCoreAppSettings
+                    (
+                        // not using "net5.0", a workaround for https://github.com/dotnet/BenchmarkDotNet/pull/1479
+                        targetFrameworkMoniker: "netcoreapp5.0",
+                        runtimeFrameworkVersion: default,
```
Comment (halter73) [inline src/Shared/BenchmarkRunner/Program.cs:72]: @JamesNK @adamsitnik When I was running benchmarks on net5.0, I got a MethodAccessException when trying to reference `Encoding.Latin1`:

```
OverheadJitting  1: 512 op, 386800.00 ns, 755.4688 ns/op

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Server.Kestrel.Performance.Http1ConnectionBenchmark+<>c.<Setup>b__7_0(System.String)' to access method 'System.Text.Encoding.get_Latin1()' failed.
   at Microsoft.AspNetCore.Server.Kestrel.Performance.Http1ConnectionBenchmark.<>c.<Setup>b__7_0(String _) in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\perf\Kestrel.Performance\Http1ConnectionBenchmark.cs:line 39
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.HttpUtilities.GetRequestHeaderString(ReadOnlySpan`1 span, String name, Func`2 encodingSelector) in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\HttpUtilities.cs:line 146
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders.Append(ReadOnlySpan`1 name, ReadOnlySpan`1 value) in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpHeaders.Generated.cs:line 6686
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnHeader(ReadOnlySpan`1 name, ReadOnlySpan`1 value) in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 522
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.TryTakeSingleHeader(TRequestHandler handler, ReadOnlySpan`1 headerLine) in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpParser.cs:line 342
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseHeaders(TRequestHandler handler, SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Performance.Http1ConnectionBenchmark.ParseData() in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\perf\Kestrel.Performance\Http1ConnectionBenchmark.cs:line 91
   at Microsoft.AspNetCore.Server.Kestrel.Performance.Http1ConnectionBenchmark.LiveAspNet() in F:\dev\aspnet\AspNetCore\src\Servers\Kestrel\perf\Kestrel.Performance\Http1ConnectionBenchmark.cs:line 74
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in F:\dev\aspnet\AspNetCore\artifacts\bin\Microsoft.AspNetCore.Server.Kestrel.Performance\Release\net5.0\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1.notcs:line 838
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in F:\dev\aspnet\AspNetCore\artifacts\bin\Microsoft.AspNetCore.Server.Kestrel.Performance\Release\net5.0\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1.notcs:line 164
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in F:\dev\aspnet\AspNetCore\artifacts\bin\Microsoft.AspNetCore.Server.Kestrel.Performance\Release\net5.0\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1\0a11fc5a-0daf-42c0-9c2d-b77a4ffb15f1.notcs:line 47
```

I knew we had workarounds in place to make "net5.0" work with BenchmarkDotNet, so I found this PR. I figured this kind of MethodAccessException was likely caused by a runtime framework version mismatch, so locally I changed `runtimeFrameworkVersion: default,` to `runtimeFrameworkVersion: "5.0.0-preview.8.20323.9",`.

Sure enough, this fixed it, but is there a better way to fix this than manually passing the runtimeFrameworkVersion in here? It wasn't the most obvious thing, and is a bit of a pain.
