### PR TITLE
Forms PRG and error handling fixes

### LINKED ISSUE #47903: Blazor SSR form post handling: integrate errors with ErrorBoundary
As of preview 4, the new form post mechanism will have an inconsistency in exception handling:

 * If an exception occurs during initial rendering, it will trigger the normal `ErrorBoundary` mechanisms, and the response will be a 200
 * If an exception occurs during the form submit event dispatch, it will bypass any `ErrorBoundary`, and the response will be a 500 because the exception flows up into the ASP.NET Core pipeline

We actually want the exception to flow up into the ASP.NET Core pipeline in both cases (leading to a 500 by default) as that's more helpful for SSR.

### Suggested implementation

Hopefully we could remove the special-case logic in `Renderer.cs` that distinguishes these cases based on the `quiesce` flag (which really should be orthogonal to this anyway): https://github.com/dotnet/aspnetcore/pull/47716/files#diff-329ab76a7fca1f1325c9c8a21d79c9d7731b5a2163b81b7797a86291b53e0153R432-R436

Instead, we could change `HandleExceptionViaErrorBoundary` or similar to be `virtual` so that the default renderer uses `ErrorBoundary` in all cases (which is the appropriate thing to do for interactive rendering) and the `EndpointHtmlRenderer` would have its own different behavior of bypassing error boundaries in all cases.

We need to check we have E2E tests showing the expected behavior occurs:

 * In interactive rendering for synchronous exceptions
 * In interactive rendering for asynchronous exceptions
 * In SSR for synchronous exceptions
 * In SSR for asynchronous exceptions

The first two of these should be covered already by our existing E2E tests, but we should check. I don't know whether we have E2E tests for the SSR error cases.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes https://github.com/dotnet/aspnetcore/issues/47903 and https://github.com/dotnet/aspnetcore/issues/49143

Mostly it's just tweaks to the flow in `RazorComponentEndpointInvoker`, plus a ton of E2E cases.

### Forms + streaming rendering

While doing this I realised the way we dispatch form events isn't as integrated into streaming SSR as I thought. What I thought would happen is:

 * Initial synchronous render
 * Streaming begins
   * Any series of further async renders until quiescence
   * Dispatch submit event
   * Any series of (possibly async) renders until quiescence

... but what actually happens is:

* Initial synchronous render
* Pause until quiescence, not doing any streaming during this time
* Dispatch submit event
* Streaming begins
   * Any series of (possibly async) renders until quiescence

So, it's not streaming until the submit event is dispatched. I tried fixing this but it involves more changes than I was ready to do just hours before the CC deadline. One particularly tricky bit is that the handling for returning 400 errors in the case of invalid/missing form names relies on the response not yet having started. If we are willing to do real streaming *before* we even get to the submit event dispatch, we also have to deal with the case where we then see it's an invalid submission but the response has already started.

We already handle "error after response already started" when it's an exception - we send a message over the SSR channel about it. Extending this to handle cases that aren't unhandled exceptions makes the flow more complex.

If we choose to do this in the future, the main aspects of the work are something like:

 * Move the call to `DispatchEventAsync` inside `BeginRenderingRootComponent`.
   * `BeginRenderingRootComponent` should continue waiting only until the non-streaming tasks have completed and then return an `HtmlRootComponent`, but now it should represent the *entire* rest of the process including event dispatch. That way the upstream code doesn't have to differentiate all these cases.
   * To achieve that, we probably need some new `protected` API on `StaticHtmlRenderer` that waits for a supplied task (for which we'll pass the original quiescence task) and then dispatches an event and return an `HtmlRootComponent` with a `QuiescenceTask` representing quiescence after that event
   * Then, `EndpointHtmlRenderer` would return that instead of the original `HtmlRootComponent`
   * The tricky bit with "invalid submission" remains. The best I can think of is throwing some kind of new "InvalidFormSubmitException" that we then catch at the same level we'd catch `NavigationException` and convert that into a 400 (if the response hasn't started) or a new streaming SSR message (if it has)

That's not going to happen for preview 7 but we can consider whether it's important for RC1.

**Update** Great point from @javiercn below about why the user experience is better if we don't change this: https://github.com/dotnet/aspnetcore/pull/49472#issuecomment-1638674411

### CODE REVIEW

File: src/Components/Web/src/Forms/Mapping/FormValueMappingContext.cs [hunk 1]
```diff
@@ -13,31 +13,31 @@ public class FormValueMappingContext
...
     {
-        ArgumentNullException.ThrowIfNull(mappingScopeName, nameof(mappingScopeName));
+        ArgumentNullException.ThrowIfNull(acceptMappingScopeName, nameof(acceptMappingScopeName));
         ArgumentNullException.ThrowIfNull(valueType, nameof(valueType));
         ArgumentNullException.ThrowIfNull(parameterName, nameof(parameterName));
 
-        MappingScopeName = mappingScopeName;
-        RestrictToFormName = restrictToFormName;
+        AcceptMappingScopeName = acceptMappingScopeName;
+        AcceptFormName = acceptFormName;
```
Comment (SteveSandersonMS) [inline src/Components/Web/src/Forms/Mapping/FormValueMappingContext.cs:27]: These unrelated renames are follow-up on code-review feedback from an earlier PR. Just trying to clear up!

**Comment by javiercn** [comment]
> So, it's not streaming until the submit event is dispatched. I tried fixing this but it involves more changes than I was ready to do just hours before the CC deadline. One particularly tricky bit is that the handling for returning 400 errors in the case of invalid/missing form names relies on the response not yet having started. If we are willing to do real streaming before we even get to the submit event dispatch, we also have to deal with the case where we then see it's an invalid submission but the response has already started.

I don't think we should do streaming rendering before we dispatch the event. It will result in a very inconsistent experience if you try to alter the response in any way as part of the POST and there is not a ton of value for it. (You are not getting to the page for the first time nor getting new data to consume, you are waiting the results from an action you triggered).

**Comment by SteveSandersonMS** [comment]
> It will result in a very inconsistent experience if you try to alter the response in any way as part of the POST and there is not a ton of value for it. (You are not getting to the page for the first time nor getting new data to consume, you are waiting the results from an action you triggered).

Great point. TBH I don't have a certain sense of there being important scenarios for streaming before dispatching the event, now you've made me think of it more clearly.

Happy to leave it as-is then.

**Review by MackinnonBuck — APPROVED** [review]

**Comment by darena-pjindal** [comment]
Hello - Was the issue reported by Daniel in https://github.com/dotnet/aspnetcore/issues/49143 fixed in the latest release? I am still having that issue. Is there a workaround for this?  The form code below crashes. 
@page "/Test"
@inject NavigationManager NavigationManager

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<EditForm method="post" Model="new()" OnValidSubmit="Navigate" FormName="form11">
    <button type="submit">Submit and navigate</button>
</EditForm>

@code {
    void Navigate()
    {
        Console.WriteLine("Navigate");
        NavigationManager.NavigateTo("/counter");
    }
}

**Comment by SteveSandersonMS** [comment]
@darena-pjindal Are you sure that code crashes? It works fine for me. Is it possible that it doesn't really crash, but you've got the VS debugger connected and it's telling you about first-chance exceptions instead?

**Comment by darena-pjindal** [comment]
Hi @SteveSandersonMS - 
I get the following exception and am not able to debug it. It does work if I run without debugging. I need to be able to debug. Is there a setting that I  have to choose for VS to ignore specific types of exceptions? 

image

**Comment by SteveSandersonMS** [comment]
Yes, see the checkbox in the screenshot labelled "break wen this exception type is user-unhandled"

**Comment by darena-pjindal** [comment]
Ah ok. That made it work. Thank you so much.

**Comment by schaveyt** [comment]
@SteveSandersonMS and @darena-pjindal - I am attempting the same sneaky thing where trying to "simulate" interactivity of a button in an SSR page using the form. When the user clicks the button, it gathers some data and tries to redirect/`NavigateTo` a new Uri....but that pesky NavigationException continues to occur and the redirection do NOT occur.

I try/catch the exception and it just nothing happens.

**Comment by julioct** [comment]
Hi @SteveSandersonMS Long time! Hey, I'm also getting the NavigationException in VS Code, as part of a tutorial I'm preparing for folks new to Blazor:

image

I don't think it is a good experience for folks new to the platform, and they should not need to mess around with code editor settings to work around such a simple scenario.

Is there anything that can be done to properly handle the exception in the runtime itself?

**Comment by siroman** [comment]
are you sure you are not mixing renderModes? i.e. you are trying to NavigateTo from a SSR mode page to an InteractiveServer one?

**Comment by julioct** [comment]
> are you sure you are not mixing renderModes? i.e. you are trying to NavigateTo from a SSR mode page to an InteractiveServer one?

I'm sure. There's no interactivity enabled for this project. Pure SSR.

**Comment by julioct** [comment]
Got it, happens here:

```csharp
    public void AddGameDetails()
    {
        DB.GameDetails.Add(GameDetails);
        NavigationManager.NavigateTo("/gamedetails");
    }
```

But does not happen here:

```csharp
    public async Task AddGameDetails()
    {
        DB.GameDetails.Add(GameDetails);
        NavigationManager.NavigateTo("/gamedetails");
        await Task.CompletedTask;
    }
```

Created that with the Blazor scaffolder in VS. 

In the async version I see this in the debugger logs:

Exception thrown: 'Microsoft.AspNetCore.Components.NavigationException' in Microsoft.AspNetCore.Components.Endpoints.dll

...but the debugger does not break into the exception and the app happily continues to the next page.

**Comment by SteveSandersonMS** [comment]
Hey @julioct!

> Is there anything that can be done to properly handle the exception in the runtime itself?

I'm afraid the exception already *is* properly handled in the runtime itself. That's why the app "happily continues to the next page".

The issue is just that the debugger is being very proactive about telling you about an internal implementation detail of the framework (this exception). People don't need to know about this, so it's unfortunate it shows up on the log there.

Longer term we might change how the navigation is signalled to avoid this sort of weirdness. Nobody really likes using an exception here, but we did it to recreate the same semantics that happen on other platforms. We may decide that allowing the app code to continue executing even after the redirection is acceptable, and then would not need to use the exception.

**Comment by julioct** [comment]
Sounds good, thank you Steve!

**Comment by zarna-flywheel** [comment]
Interestingly, if I wrap 

```
 NavigationManager.NavigateTo("/account");
 await Task.CompletedTask;

```
in a try-catch block, the redirection does not happen (as it hits the catch block).

Any insights on how I can get this to work in a try-catch block correctly?

**Comment by SteveSandersonMS** [comment]
> Any insights on how I can get this to work in a try-catch block correctly?

Don't catch `System.Exception` (instead, catch the subclass that you're planning to deal with). Or if you must do that, then check if the exception you caught is `NavigationException`, and if it is, use `throw;'` to rethrow it.

**Comment by mohiyo** [comment]
@SteveSandersonMS I have a Login Form inside a Blazor Server App which is working fine with built-in functionality. 
But now I am trying to solve a problem where I will be allowing Users to log in automatically when they reach from certain URL and with certain parameters, **Without submitting a form**

I tried this in my Login Component

```
protected override async Task OnInitializedAsync() {
  try {
    if (HttpMethods.IsGet(HttpContext.Request.Method))
      await HttpContext.SignOutAsync();

    if (parameter && condition) {
      await DirectLogin();
    }
  } catch (Exception ex) {
    _logger.LogError(message: ex.Message);
  }
}

async Task DirectLogin() {
  try {
  //Perform some logic here and then SignIn

    await HttpContext.SignInAsync(principal, new AuthenticationProperties {
      ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(5)
    });

    _navigation.NavigateTo($"/direct/page/{parameter}", true);
    //Here I get this exception "Microsoft.AspNetCore.Components.NavigationException"

  } catch (Exception ex) {
    errorMessage = $ "Error: {ex.Message}";
    _logger.LogError(message: ex.Message);
  }
}

```

This login Component is in a Static Server Render mode whereas after the successful SignIn, the User will be redirected to an Interactive Server Component. 

But Navigation is not working and I am getting this exception 

> Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown
