### PR TITLE
Fixes encoded values on Blazor Router

### LINKED ISSUE #52808: Blazor NavigationManager redirect to NotFound if route parameter contains encoded /
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NavigationManager redirects to NotFound if route parameter contains encoded '/' instead of requested page. 

ex:
/cars/parts%20w%2F%20issue/show

It was working in .net 6. Stops after update to .net8.

### Expected Behavior

Navigate to page and bind parameter.

### Steps To Reproduce
[repo](https://github.com/pmpbpl/blazor-issue-52808)

### Exceptions (if any)

_No response_

### .NET Version

.net8.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by javiercn**
Fix handling of encoded `/` in URLs within the Blazor router.

Fixes https://github.com/dotnet/aspnetcore/issues/52808, https://github.com/dotnet/aspnetcore/issues/53138, https://github.com/dotnet/aspnetcore/issues/53262

In .NET 8.0 we unified the routing system for ASP.NET Core and Blazor in order to bridge the functionality gaps and provide a consistent experience for SSR and interactive routing. 
As part of such, we had to make adjustments to account for some of the quirks of the Blazor router (where it would behave slightly different than the ASP.NET Core router).
As part of this, we were decoding the entire URL before passing it to the Blazor router instead of (as it did before), splitting each segment and decoding each segment individually.

This introduced a regression when using URLs that contained encoded segments with `/` in them, as the router would then treat the `/` as a path separator instead of part of the segment and we would not be able to route correctly.

To fix this, we now decode each segment individually inside the router when the code runs as part of Blazor. In addition to that, when the routing happens server side, we now post-process the resulting values to URL decode them so that they match the behavior of the Blazor router.

To summarize, here is the before and after behavior:

Before:
Framework version and router | pattern | request | result
|--- | --- | --- | --- |
7.0 interactive | `/some/{parameter}` | `/some/encoded%2Fvalue` | `parameter = "encoded/value"`
8.0 SSR | `/some/{parameter}` | `/some/encoded%2Fvalue` | `parameter = "encoded%2Fvalue"`
8.0 interactive | `/some/{parameter}` | `/some/encoded%2Fvalue` | Not Found (URI got decoded as /some/encoded/value)

After:
Framework version and router | pattern | request | result
|--- | --- | --- | --- |
7.0 interactive | `/some/{parameter}` | `/some/encoded%2Fvalue` | `parameter = "encoded/value"`
8.0 SSR | `/some/{parameter}` | `/some/encoded%2Fvalue` | `parameter = "encoded/value"`
8.0 interactive | `/some/{parameter}` | `/some/encoded%2Fvalue` | `parameter = "encoded/value"`

### CODE REVIEW

File: src/Components/Components/src/Routing/RouteTableFactory.cs [hunk 1]
```diff
@@ -112,9 +113,11 @@ private static string[] GetTemplates(Type componentType)
     [UnconditionalSuppressMessage("Trimming", "IL2067", Justification = "Application code does not get trimmed, and the framework does not define routable components.")]
     internal static RouteTable Create(Dictionary<Type, string[]> templatesByHandler, IServiceProvider serviceProvider)
     {
+        var routeOptions = Options.Create(new RouteOptions());
+        routeOptions.Value.SetParameterPolicy("regex", typeof(RegexInlineRouteConstraint));
```
Comment (SteveSandersonMS) [inline src/Components/Components/src/Routing/RouteTableFactory.cs:117]: I'm unsure if this is part of dealing with encoding or if it's addressing a separate issue. Could you clarify?

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedCatchAll.razor [hunk 2]
```diff
@@ -0,0 +1,25 @@
+﻿@page "/🙂/routing/catch-all/{*parameter}"
```
Comment (SteveSandersonMS) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedCatchAll.razor:1]: If I ever see a URL like this in the wild, I'll know it's time to go live off-grid and pretend never to have heard of computers...

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedConstrainedCatchAll.razor [hunk 3]
```diff
@@ -0,0 +1,24 @@
+﻿@page "/🙂/routing/constrained-catch-all/{*parameter:regex(http:%2F%2Fwww\\.example\\.com%2Flogin%2Fcallback\\/another)}"
```
Comment (SteveSandersonMS) [inline src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedConstrainedCatchAll.razor:1]: My eyes

**Review by SteveSandersonMS — APPROVED** [review]
Great!

File: src/Components/Components/src/Routing/RouteTableFactory.cs (hunk 1 above)
Comment (javiercn) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:117]: This is addressing a separate issue, we weren't wiring up the regex, which was needed to test this fully, as it doesn't affect other constraints that the Blazor router supports and we don't have support for authoring custom constraints either.

File: src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedConstrainedCatchAll.razor (hunk 3 above)
Comment (javiercn) [reply src/Components/test/testassets/Components.TestServer/RazorComponents/Pages/Routing/Encoded/EncodedConstrainedCatchAll.razor:1]: Yeah, this is a bit extreme, but I wanted to make sure we cover all the edge cases correctly, as this is very tricky.

File: src/Components/Components/src/Routing/RouteTableFactory.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:117]: Have we effectively added a whole new feature with this line of code then? I'm totally fine with this being added, assuming it doesn't appreciably impact the default bundle size for a Blazor WebAssembly app.

Could you confirm if that's the case?

Comment (javiercn) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:117]: I'm in the process of confirming the bundle size, it's not a feature, it's a bug fix IMO. It works on SSR routing but won't work once it becomes interactive.

Comment (SteveSandersonMS) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:117]: Thanks, please do confirm! I think we still have a choice of whether to include that feature for interactive mode, given that it's never worked on interactive mode in the past.

Comment (javiercn) [reply src/Components/Components/src/Routing/RouteTableFactory.cs:117]: It turns out that this regressed the size, so I'm going to take it out into its own separate PR that enables this conditionally on WebAssembly behind a feature flag. The feature flag will also need a change in the Blazor SDK to control it, but for the purposes of this repo, we'll keep it enabled.

image

**Review by SteveSandersonMS — APPROVED** [review]
