### PR TITLE
[Blazor][Fixes #14999] Razor Class Library Static Assets with spaces do not resolve

### LINKED ISSUE #14999: Razor Class Library Static Assets with spaces do not resolve.
If any files (images for example) contain a space.  When they are coded with %20 they are not resolved.

To reproduce.
   1.  Create a RCL with a wwwroot folder.
   2.  Add one image file without a space, Add one image file with a space.
   3.  Create a Web App and reference the RCL
   4.  Run the app.

In my test app.  https://localhost:44362/_content/RclTestCore3/MoneyBag.png resolves just fine.

However, https://localhost:44362/_content/RclTestCore3/Piggy Bank.png, which gets encoded as https://localhost:44362/_content/RclTestCore3/Piggy%20Bank.png, will return a 404 error.

I can workaround this by removing the spaces, but I happen to have a lot of images with spaces in their filenames.

Thanks

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

File: src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsFileProvider.cs [hunk 1]
```diff
@@ -46,7 +46,7 @@ public IDirectoryContents GetDirectoryContents(string subpath)
             }
             else
             {
-                return InnerProvider.GetDirectoryContents(physicalPath);
+                return InnerProvider.GetDirectoryContents(physicalPath.Value);
```
Comment (javiercn) [inline src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsFileProvider.cs]: This was being implicitly converted to "string" and that would encode spaces as "%20". The fix simply passes down the raw value (which was already decoded by hosting) to the underlying provider

**Review by Tratcher — APPROVED** [review]
