### PR TITLE
Split KestrelTrace into multiple files

### LINKED ISSUE #41143: Order KestrelTrace by event ID
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During a refactor some Kestrel trace log methods were reordered to group them together by logic. This makes it difficult to understand what event IDs (an incrementing number) are used, and what the next event ID should be.
 https://github.com/dotnet/aspnetcore/blob/c00e0e775208cb7cb377f9bd0c8a66a0b3d0ed4d/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs

### Expected Behavior

Methods ordered by event ID, e.g. 0, 1, 2, 3, etc. That means oldest to newest.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aclark09**
# Split KestrelTrace into multiple files

Split KestrelTrace up into multiple files for better organization.

## Description

Refactored KestrelTrace into 5 new files:
- KestrelTrace.BadRequests
- KestrelTrace.Connections
- KestrelTrace.General
- KestrelTrace.Http2
- KestrelTrace.Http3

Current IDs were kept for backwards compatibility, but new logs can be added starting at 60 for each category.

Fixes #41143

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=41245) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=41245) before we can accept your contribution.<br/><br/>:x: aclark09 [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=41245)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=41245) it.</sub>

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Connections.cs [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+    }
+
+    public void ApplicationAbortedConnection(string connectionId, string traceIdentifier)
+    {
+        ConnectionsLog.ApplicationAbortedConnection(_connectionsLogger, connectionId, traceIdentifier);
+    }
+
+    public static partial class ConnectionsLog
+    {
+        [LoggerMessage(39, LogLevel.Debug, @"Connection id ""{ConnectionId}"" accepted.", EventName = "ConnectionAccepted")]
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Connections.cs:67]: Could you order the log message methods by event id? e.g. 1, 2, 3, 4.

These were reordered at one point so they are grouped together by logic, but we don't really care. The most useful bit of info is what is the last ID. If they're ordered we can simply look at the bottom of the class.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Http2.cs [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+    }
+
+    public void Http2UnexpectedConnectionQueueError(string connectionId, Exception ex)
+    {
+        Http2Log.Http2UnexpectedConnectionQueueError(_http2Logger, connectionId, ex);
+    }
+
+    public static partial class Http2Log
+    {
+        [LoggerMessage(29, LogLevel.Debug, @"Connection id ""{ConnectionId}"": HTTP/2 connection error.", EventName = "Http2ConnectionError")]
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Http2.cs:90]: Reorder

**Comment by JamesNK** [comment]
Looks good. A couple of minor things to clean up.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.BadRequests.cs [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+        public static partial void RequestBodyMinimumDataRateNotSatisfied(ILogger logger, string connectionId, string? traceIdentifier, double rate);
+
+        [LoggerMessage(28, LogLevel.Debug, @"Connection id ""{ConnectionId}"", Request id ""{TraceIdentifier}"": the connection was closed because the response was not read by the client at the specified minimum data rate.", EventName = "ResponseMinimumDataRateNotSatisfied")]
+        public static partial void ResponseMinimumDataRateNotSatisfied(ILogger logger, string connectionId, string? traceIdentifier);
+
+        [LoggerMessage(54, LogLevel.Debug, @"Connection id ""{ConnectionId}"": Invalid content received on connection. Possible incorrect HTTP version detected. Expected {ExpectedHttpVersion} but received {DetectedHttpVersion}.", EventName = "PossibleInvalidHttpVersionDetected", SkipEnabledCheck = true)]
+        public static partial void PossibleInvalidHttpVersionDetected(ILogger logger, string connectionId, string expectedHttpVersion, string detectedHttpVersion);
+    }
```
Comment (JamesNK) [inline src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.BadRequests.cs:55]:
```suggestion

        // Highest shared ID is 63. New consecutive IDs start at 64
    }
```
Please add a comment like this to the bottom of each static log type so it's obvious to future engineers what new IDs are numbered as.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.BadRequests.cs [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+
+    public void PossibleInvalidHttpVersionDetected(string connectionId, HttpVersion expectedHttpVersion, HttpVersion detectedHttpVersion)
+    {
+        if (_generalLogger.IsEnabled(LogLevel.Debug))
+        {
+            BadRequestsLog.PossibleInvalidHttpVersionDetected(_badRequestsLogger, connectionId, HttpUtilities.VersionToString(expectedHttpVersion), HttpUtilities.VersionToString(detectedHttpVersion));
+        }
+    }
+
+    public static partial class BadRequestsLog
```
[the remark this answers is not in the document]
Comment (aclark09) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.BadRequests.cs]: Thanks, I went ahead and fixed this. I thought at first this wouldn't compile, but that was because I had set the methods inside to private as well as the class.

File: src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Connections.cs (hunk 1 above)
Comment (aclark09) [reply src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.Connections.cs]: Yup, re-ordered in both files.

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
Perfect. This is much more organized and understandable. Thanks!
