### PR TITLE
[8.0] Optionally respect HTTP/1.0 keep-Alive for HTTP.sys

### LINKED ISSUE #56223: Connection Close Behavior on HTTP1.0 Requests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspnetcore/blob/83573c72d12e1c2018805bc5d461d730bcb9dcc4/src/Servers/HttpSys/src/RequestProcessing/Response.cs#L406

> if (requestVersion <= Constants.V1_0 // Http.Sys does not support "Keep-Alive: true" or "Connection: Keep-Alive"

The comment in the code indicates http.sys does not support "Connection: Keep-Alive". However, we certainly see that header got to work in IIS, so the comment might be wrong. Thus, we want to change the behavior so that it aligns with IIS.

The reason we want to change this behavior on the server-side is that we don't want to keep closing connections on every request for http1.0, that will increase TLS costs on our end for subsequent re-connects. Given http1.0 traffic is not trivial amount.

### Expected Behavior

If the request is http1.0 AND the request contains "Connection: keep-alive", we also send the "Connection: keep-alive" header in the response.

### Steps To Reproduce

Send http 1.0 request using curl to ASP.NET endpoint with "Connection: keep-alive" header
> curl.exe --http1.0 -i <ASP.NET endpoint uri> -H "Connection: keep-alive"

From the response, you'll see the "Connection: close" header.

### Exceptions (if any)

_No response_

### .NET Version

6.0.131

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adityamandaleeka**
# Optionally respect HTTP/1.0 keep-Alive for HTTP.sys

#56558 was done in 9.0 and made it so we respect keep-alives from 1.0 clients in HTTP.sys. This effectively backports that logic to 8.0 but in an opt-in way (behind an AppContext switch).

## Description

This change adds an AppContext switch that, when enabled (it's off by default), will allow our HTTP.sys server to respect HTTP/1.0 clients' `Connection: Keep-Alive` header.

Fixes #56223

## Customer Impact

With this change, servers that serve HTTP/1.0 clients can opt in to respecting the keep-alive header, and thereby save on the fixed costs of connection set up/teardown. For situations where there is a significant amount of 1.0 traffic, this can lead to significant cost savings.

## Regression?

- [ ] Yes
- [x] No

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This behavior is opt-in behind an AppContext switch.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs [hunk 1]
```diff
@@ -31,6 +31,9 @@ internal sealed class Response
     private HttpApiTypes.HTTP_RESPONSE_V2 _nativeResponse;
     private HeaderCollection? _trailers;
 
+    private const string RespectHttp10KeepAliveSwitch = "Microsoft.AspNetCore.Server.HttpSys.RespectHttp10KeepAlive";
```
Comment (amcasey) [inline src/Servers/HttpSys/src/RequestProcessing/Response.cs:34]: I guess we don't need a follow up work item since it's already "removed" in 9.0.

File: src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs [hunk 2]
```diff
@@ -207,20 +208,85 @@ public async Task ResponseHeaders_11HeadRequestStatusCodeWithoutBody_NoContentLe
     }
 
     [ConditionalFact]
-    public async Task ResponseHeaders_HTTP10KeepAliveRequest_Gets11Close()
+    public async Task ResponseHeaders_HTTP10KeepAliveRequest_KeepAliveHeader_RespectsSwitch()
+    {
+        AppContext.SetSwitch("Microsoft.AspNetCore.Server.HttpSys.RespectHttp10KeepAlive", true);
```
Comment (amcasey) [inline src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:213]: I remember there being some complexity here around interactions between different tests.  That is, if tests are running in parallel, I don't think we want this changing states.  I'm pretty sure Chris suggested I create an internal property populated from the context switch but overridable by tests.

Comment (amcasey) [reply src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:213]: See `KestrelServerOptions.FinOnError`.

Comment (mgravell) [reply src/Servers/HttpSys/test/FunctionalTests/Listener/ResponseHeaderTests.cs:213]: for `EnableKernelResponseBuffering`, I made use of an `internal` property on `HttpSysOptions`, that is initialized in the .ctor via the app-context switch - that way, relevant tests can set it explicitly via the `internal` property rather than the app-context switch

but yes @amcasey  you're right that changing app-context directly in tests makes for a race condition in parallel tests

File: src/Servers/HttpSys/src/HttpSysOptions.cs [hunk 3]
```diff
@@ -29,6 +29,9 @@ public class HttpSysOptions
     private long? _maxRequestBodySize = DefaultMaxRequestBodySize;
     private string? _requestQueueName;
 
+    private const string RespectHttp10KeepAliveSwitch = "Microsoft.AspNetCore.Server.HttpSys.RespectHttp10KeepAlive";
+    internal bool RespectHttp10KeepAlive = AppContext.TryGetSwitch(RespectHttp10KeepAliveSwitch, out var enabled) && enabled;
```
Comment (amcasey) [inline src/Servers/HttpSys/src/HttpSysOptions.cs:33]: I might say "// Internal for testing".

**Review by amcasey — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

File: src/Servers/HttpSys/src/RequestProcessing/Response.cs [hunk 4]
```diff
@@ -402,12 +405,25 @@ internal HttpApiTypes.HTTP_FLAGS ComputeHeaders(long writeCount, bool endOfReque
...
+        {
+            // In .NET 9, we updated the behavior for 1.0 clients here to match
+            // RFC 2068. The new behavior is available down-level behind an
+            // AppContext switch.
+
+            // An HTTP/1.1 server may also establish persistent connections with
+            // HTTP/1.0 clients upon receipt of a Keep-Alive connection token.
+            // However, a persistent connection with an HTTP/1.0 client cannot make
+            // use of the chunked transfer-coding. From: https://www.rfc-editor.org/rfc/rfc2068#section-19.7.1
+            keepConnectionAlive = _respectHttp10KeepAlive && requestConnectionKeepAliveSet && !responseChunkedSet;
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/Response.cs:425]: responseChunkedSet is only for cases where the application sets the chunked header and does the chunking themselves, it doesn't cover the default case where the server does chunking automatically. See `_boundaryType = BoundaryType.Chunked;` vs `_boundaryType = BoundaryType.PassThrough;` below.

Comment (adityamandaleeka) [reply src/Servers/HttpSys/src/RequestProcessing/Response.cs:425]: Thanks for the review!
