### PR TITLE
Fixed bug - Passing options to UseStaticFiles breaks Blazor Server

### LINKED ISSUE #19578: Passing options to UseStaticFiles breaks Blazor Server's static file service
### Describe the bug

If you pass any kind of `StaticFileOptions` object to `app.UseStaticFiles()`, then Blazor Server will no longer be able to serve `blazor.server.js`, breaking Blazor.

### To Reproduce

* Create the template Blazor Server app
* Run it and observe that it works correctly
* Change the `app.UseStaticFiles()` call in Startup.Configure to read `app.UseStaticFiles(new StaticFileOptions())`
* Run the app again and observe that blazor.server.js is 404'd, and hence the app doesn't work.

What appears to be happening is that if you don't pass any configuration to `UseStaticFiles`, then the framework correctly calls `ConfigureStaticFilesOptions.PostConfigure` after the pipeline is built.  This configures the static file middleware to serve the Blazor JS from manifest resources.

As soon as there's any configuration passed to `UseStaticFiles`, then `ConfigureStaticFilesOptions` is no longer called.   It doesn't matter what specific properties are in the `StaticFileOptions` object - it's just the presence of the object which causes the problem.

I will debug this further if it's helpful, but I suspect someone more familiar with the `IPostConfigureOptions` mechanism will know what's going on instantly.

Maybe there's some work-around, but if so then it would be helpful if it could be somehow more obvious, because "I added a static file extension and Blazor stopped working" is somewhat surprising.

I think this may be same issue as #18222, which was perhaps rather confusingly titled and ended up being closed, but I think there is a real issue here.

### Further technical details
- ASP.NET Core version  3.1.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version  VS 16.4.5 on Win10

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fixed bug - Passing options to UseStaticFiles breaks Blazor Server

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

1. Mapped endpoint to serve blazor.server.js from manifest resources.
2. Deleted no longer used ConfigureStaticFilesOptions

Tested manually by running sample BlazorServerApp.

Fixes #19578

### CODE REVIEW

File: src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs [hunk 1]
```diff
@@ -113,6 +115,33 @@ public static ComponentEndpointConventionBuilder MapBlazorHub(this IEndpointRout
...
+        {
+            // Set endpoint to null so the static files middleware will handle the request.
+            context.SetEndpoint(null);
+
+            return next(context);
+        });
+        app.UseStaticFiles(options);
+
+        var blazorEndpoint = endpoints.Map("/_framework/blazor.server.js", app.Build())
+            .WithDisplayName("Blazor static files");
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:141]: This approach looks fairly plausible but would love to get @javiercn's take since he has focused a lot on how the server-side endpoints are set up and how static files are served.

Comment (javiercn) [reply src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:141]: This will work, the only "slight" concern that I have is that we loose the ability to server blazor.server.js independently of where we are serving the other endpoints, but I do not see a big drawback to it.

Essentially if you want to map blazor to a subdir, you need to call `app.MapPath("subdir", sub => { sub.UseRouting(); sub.UseStaticFiles(); sub.UseEndpoints(e => e.MapComponentHub()); }`, set the base path on the document accordingly.

There might have been other ways to make it work that might not work now, but I do not think they are critical.

File: src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs [hunk 2]
```diff
@@ -113,6 +115,33 @@ public static ComponentEndpointConventionBuilder MapBlazorHub(this IEndpointRout
...
+
+        blazorEndpoint.Add((builder) => ((RouteEndpointBuilder)builder).Order = -1);
```
Comment (javiercn) [inline src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:143]: The `-1` here makes it so that this endpoint has priority over other endpoints independent of their specificity, so this means that a controller or a file are not going to match over this endpoint. 

With that said, I think we should be a bit more conservative here as people might also register their own routes with a custom order, which might cause those routes to match over this one. For that reason, we should do something similar but opposite to what we do in `MapFallbackToPage` and give it the lowest order possible `(int.MinValue)` so that we can guarantee under most circumstances, no other route will match over this one.

Comment (javiercn) [reply src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:143]: The only time this might cause issues is if someone customizes routing extensively, which I am not too worried about.

**Review by javiercn — APPROVED** [review]
I think the change looks great.

We have plenty of time to get feedback on this if we missed anything.

File: src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs [hunk 3]
```diff
@@ -113,6 +115,33 @@ public static ComponentEndpointConventionBuilder MapBlazorHub(this IEndpointRout
...
+        var blazorEndpoint = GetBlazorEndpoint(endpoints);
+
+        return new ComponentEndpointConventionBuilder(hubEndpoint, disconnectEndpoint, jsInitializersEndpoint, blazorEndpoint);
+    }
+
+    private static IEndpointConventionBuilder GetBlazorEndpoint(IEndpointRouteBuilder endpoints)
+    {
+        var options = new StaticFileOptions
+        {
+            FileProvider = new ManifestEmbeddedFileProvider(typeof(ComponentEndpointRouteBuilderExtensions).Assembly)
```
[the remark this answers is not in the document]
Comment (javiercn) [reply src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:127]: Nope.

That's a good catch.

@surayya-MS can you take a look?

[the remark this answers is not in the document]
Comment (surayya-MS) [reply src/Components/Server/src/Builder/ComponentEndpointRouteBuilderExtensions.cs:127]: @campersau, thanks for noticing.
