### PR TITLE
[Blazor] Dispatch inbound activity handlers in Blazor Web apps

### LINKED ISSUE #51934: CreateInboundActivityHandler override in .net 8 RC2 not being called
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CreateInboundActivityHandler introduced in .net 8 preview 3, as seen in the dotnet blog post linked below, does not appear to work in .net 8 release candidate 2.

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/#monitor-blazor-server-circuit-activity

Within the same circuit handler the overrides for circuit open, circuit closed, connection up and connection down work as expected.

Are there any situations which would cause the CreateInboundActivityHandler to not be called when UI events fire in an interactive server component that is functioning as expected?

### Expected Behavior

The CreateInboundActivityHandler is called when any user interface events within a blazor component are activated, e.g. the changing of text, the click of a button.

### Steps To Reproduce

Repo: https://github.com/Thomas-Explc/CreateInboundActivityHandler_Bug_Example

Go to counter page, use the button and enter test in the input field, no UI events cause function to fire.

Logger in CreateInboundActivityHandler is not hit, no breakpoints within that function are reached.

### Exceptions (if any)

None, issue is logical.

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Visual Studio 2022, 17.8.0 Preview 6.0.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Dispatch inbound activity handlers in Blazor Web apps

Fixes an issue where inbound activity handlers do not get invoked in Blazor Web apps

## Description

This PR fixes the issue by:
* Building the inbound activity pipeline in Blazor Web apps just after circuit handlers are retrieved
* Invoking inbound activity handlers in web root component updates

Fixes #51934

### CODE REVIEW

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 1]
```diff
@@ -773,43 +776,50 @@ private async Task TryNotifyClientErrorAsync(IClientProxy client, string error,
...
-                                pendingTasks[i] = task;
+                                case RootComponentOperationType.Add:
+                                    pendingTasks[i] = webRootComponentManager.AddRootComponentAsync(
+                                        operation.SsrComponentId,
+                                        operation.Descriptor.ComponentType,
+                                        operation.Marker.Value.Key,
+                                        operation.Descriptor.Parameters);
+                                    break;
+                                case RootComponentOperationType.Update:
+                                    pendingTasks[i] = webRootComponentManager.UpdateRootComponentAsync(
```
Comment (MackinnonBuck) [inline src/Components/Server/src/Circuits/CircuitHost.cs:800]: We previously didn't wait for "update" operations to complete before clearing persistent state in the first root component update batch. But it's likely preferable to wait for them to complete before returning back up the inbound activity handler pipeline, hence this change. If others think this change is problematic, we could take another approach (maybe collecting the "add" operations separately and awaiting those).

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs:800]: @javiercn has been the one with the most specific opinions about the semantics for persistent state clearing, so hopefully we can get his view and explanation.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 2]
```diff
@@ -762,6 +764,7 @@ private async Task TryNotifyClientErrorAsync(IClientProxy client, string error,
 
                     // Retrieve the circuit handlers at this point.
                     _circuitHandlers = [.. _scope.ServiceProvider.GetServices<CircuitHandler>().OrderBy(h => h.Order)];
+                    _dispatchInboundActivity = BuildInboundActivityDispatcher(_circuitHandlers, Circuit);
```
Comment (SteveSandersonMS) [inline src/Components/Server/src/Circuits/CircuitHost.cs:767]: This is pretty odd - it's hard to see why we have to do this here in particular. Is it just a matter of lazy initialization? If so would it be clearer still if the field was a `Lazy<T>` that was always initialized during the constructor, and then we wouldn't need to initialize it explicitly in other places.

Comment (MackinnonBuck) [reply src/Components/Server/src/Circuits/CircuitHost.cs:765]: I agree it's a bit confusing. I believe the reason we collect the circuit handlers here is that calling `_scope.GetServices<CircuitHandler>()` may construct new instances of services registered as circuit handlers, and those services may access persistent component state in their constructors. So we need to be sure that persistent component state is available by the time these services get constructed. We might be able to use a `Lazy<T>`, but my concern is that making circuit handlers lazily and implicitly initialized might cause us to accidentally change when circuit handlers are constructed without us knowing it.

Comment (javiercn) [reply src/Components/Server/src/Circuits/CircuitHost.cs:765]: Yeah, this code is correct. The Blazor Server version also does the same thing.

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 3]
```diff
@@ -777,35 +778,36 @@ private async Task TryNotifyClientErrorAsync(IClientProxy client, string error,
...
+                                    operation.Descriptor.Parameters);
+                                break;
+                            case RootComponentOperationType.Remove:
+                                webRootComponentManager.RemoveRootComponent(operation.SsrComponentId);
+                                break;
+                        }
                     }
-                }
+
+                    return Task.CompletedTask;
```
[the remark this answers is not in the document]
Comment (MackinnonBuck) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: I restructured things a little - let me know if you think this is still a concern!

**Review by javiercn — APPROVED** [review]
Looks good to me
