### PR TITLE
Prevent JS interop after circuit disposal. Fixes #32808

### LINKED ISSUE #32808: Blazor virtualize component causes scoped services to never be disposed
### Describe the bug
Virtualize component prevents scoped injected services from being disposed.

### To Reproduce
Here is a sample repo:
[BlazorVirtualizeServiceDisposeTest](https://github.com/cristian-recoseanu/BlazorVirtualizeServiceDisposeTest)

The `VirtualizePage` renders multiple `TestComponent` components which depend on the scoped service `ScopedServiceTest`.

Using the `Virtualize` component to render them causes the scoped service to never be disposed when refreshing/closing the page.

image

Uncommenting the section using the `Virtualize` component and using a foreach works as indented. The scoped service is created and always disposed correctly.

image

### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21180.15
 Commit:    19ce2535ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21180.15\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 16.9.5

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
See more details about the problem at https://github.com/dotnet/aspnetcore/issues/32808#issuecomment-845236683. In summary, any component that attempts JS interop during disposal (for example, `<Virtualize>`) would hang until the JS call times out, preventing cleanup of any scoped resources for that period.

This PR changes how JS interop works after a circuit has begun disposal (which typically means the user has closed their browser tab or navigated away):

 * Before: JS interop calls would not get any response from the browser, so they'd just hang for a minute and eventually time out with an exception
 * After: JS interop calls will throw immediately using a new exception type (`JSDisconnectedException`)

I think we can regard this as *not* a breaking change because the calls would have eventually thrown anyway, and still do. It now just completes this process faster. The advantages of this change are:

1. DI scopes no longer live for an extra minute before cleanup in this case (e.g., when you have an active `<Virtualize>` component and the user closes the tab). They now clean up immediately.
2. Component authors who want to treat this as not-an-error now have a specific exception type they can catch and suppress. This is now done inside `Virtualize` so it won't even get logged as an error. This makes sense in cases where you were only trying to do JS interop to clean up browser-side state, and obviously don't care about that if the browser is already gone.

If we wanted, we could consider more dramatic options like:

 * **Not treating JS interop calls as failing with exceptions if the browser is disconnected.** I think that's a bad idea because (1) it would be hugely breaking, and (2) semantically it doesn't make sense - we won't know if the developer actually requires some info back from the browser or wants to know for sure whether a void call was received and completed.
 * **Auto-suppressing `JSDisconnectedException` entirely from logs.** I think that's a bad idea because it likely prevents developers from discovering that one was even happening. And then if their disposal logic looked like `DoJsCleanUp(); DoDotNetCleanUp();`, they would not realise that the `DoDotNetCleanUp` part never executes. I think developers need to know this is an error and it's up to them to try/catch if they want to control how it's handled.

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 1]
```diff
@@ -78,17 +79,32 @@ protected override void BeginInvokeJS(long asyncHandle, string identifier, strin
...
-                    "JavaScript interop calls cannot be issued at this time. This is because the component is being " +
-                    $"statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed " +
-                    $"during the OnAfterRenderAsync lifecycle method.");
+                if (_permanentlyDisconnected)
+                {
+                    throw new JSDisconnectedException(
+                           "JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected " +
+                           "and is being disposed.");
+                }
+                else
```
Comment (mkArtakMSFT) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:88]: Minor: Do we have a convention to have `else` always? I would simply not have it and throw.

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @SteveSandersonMS!

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 2]
```diff
@@ -78,17 +79,32 @@ protected override void BeginInvokeJS(long asyncHandle, string identifier, strin
...
             {
-                throw new InvalidOperationException(
-                    "JavaScript interop calls cannot be issued at this time. This is because the component is being " +
-                    $"statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed " +
-                    $"during the OnAfterRenderAsync lifecycle method.");
+                if (_permanentlyDisconnected)
+                {
+                    throw new JSDisconnectedException(
+                           "JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected " +
+                           "and is being disposed.");
```
Comment (pranavkm) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:86]:
```suggestion
                   "JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected " +
                   "and is being disposed.");
```

File: src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+
+namespace Microsoft.JSInterop
+{
+    /// <summary>
+    /// Represents errors that occur during an interop call from .NET to JavaScript.
+    /// </summary>
+    public class JSDisconnectedException : Exception
```
Comment (pranavkm) [inline src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs:11]:
```suggestion
    public sealed class JSDisconnectedException : Exception
```

**Review by pranavkm — APPROVED** [review]

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:88]: In cases where the `if`/`else` clauses could be written equally in either order (like this one), I usually prefer to have the `else` explicitly so as to make the two halves of more equal status to each other. I think it more closely matches how people speak in natural language when talking about two alternatives. For example a person might say "*if it's sunny go to the park, otherwise go to the museum*", whereas they wouldn't say "*if it's sunny go to the park and ignore anything else I say. Go to the museum.*"

I normally prefer to skip the `else` in cases where the `if` part plays the role of a guard clause, where it's natural to terminate the flow if the guard clause applies. This is more like "*Customers under 18 are not permitted. All customers must wear a mask.*"

Of course it's all subjective and there isn't really a ground truth here. Based on preference I propose to leave it, but if this is really troubling to anyone, I'll change it!

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 4]
```diff
@@ -78,17 +79,32 @@ protected override void BeginInvokeJS(long asyncHandle, string identifier, strin
...
             {
-                throw new InvalidOperationException(
-                    "JavaScript interop calls cannot be issued at this time. This is because the component is being " +
-                    $"statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed " +
-                    $"during the OnAfterRenderAsync lifecycle method.");
+                if (_permanentlyDisconnected)
+                {
+                    throw new JSDisconnectedException(
+                   "JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected " +
+                   "and is being disposed.");
```
Comment (TanayParikh) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:86]:
```suggestion
                    throw new JSDisconnectedException(
                        "JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected " +
                        "and is being disposed.");
```

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 5]
```diff
@@ -78,17 +79,32 @@ protected override void BeginInvokeJS(long asyncHandle, string identifier, strin
...
+                }
+                else
+                {
+                    throw new InvalidOperationException(
+                        "JavaScript interop calls cannot be issued at this time. This is because the component is being " +
+                        $"statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed " +
+                        $"during the OnAfterRenderAsync lifecycle method.");
```
Comment (TanayParikh) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:93]:
```suggestion
                        "statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed " +
                        "during the OnAfterRenderAsync lifecycle method.");
```

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 6]
```diff
@@ -78,17 +79,32 @@ protected override void BeginInvokeJS(long asyncHandle, string identifier, strin
...
             }
 
             Log.BeginInvokeJS(_logger, asyncHandle, identifier);
 
             _clientProxy.SendAsync("JS.BeginInvokeJS", asyncHandle, identifier, argsJson, (int)resultType, targetInstanceId);
         }
 
+        public void MarkPermanentlyDisconnected()
+        {
+            _permanentlyDisconnected = true;
```
Comment (TanayParikh) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:104]: We aren't concerned about a potential race condition between this func and https://github.com/dotnet/aspnetcore/pull/32901/files#diff-7fac6aa482260bd9b68de9fd59db0da9d8532c59ecdfd4468c0f51d371b562aaR82 because we assume a single thread, correct?

**Review by TanayParikh — APPROVED** [review]

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs (hunk 4 above)
Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:86]: Ohhh https://github.com/dotnet/aspnetcore/pull/32901#discussion_r637072301 😄

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs (hunk 6 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:104]: Great question, and yes, we absolutely expect code invoking the JS runtime to be on the circuit sync context, so only one at a time.

**Review by javiercn — APPROVED** [review]
Changes look great!

Do we need to do anything for calls that might already be `in-flight`?

File: src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs [hunk 7]
```diff
@@ -0,0 +1,21 @@
+// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+
+namespace Microsoft.JSInterop
+{
+    /// <summary>
+    /// Represents errors that occur during an interop call from .NET to JavaScript.
```
Comment (BrennanConroy) [inline src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs:9]: API review: add more description here

**Comment by SteveSandersonMS** [comment]
> Do we need to do anything for calls that might already be in-flight?

I considered it, but didn't think it was desirable because:

(1) it's not required to solve any known problem (the call will eventually time out anyway, and isn't keeping the circuit open)
(2) it's more likely to affect people with existing code in ways we haven't predicted
(3) it's trickier to implement since we would have to change a bunch of things about how the timeouts get triggered or get surfaced as exceptions

Overall since it's not required to solve the current problem here, I wasn't inclined to expand the scope of the solution. We could do it in the future if a sufficient need arises.

File: src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs (hunk 7 above)
Comment (SteveSandersonMS) [inline src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs:9]:
```suggestion
    /// Represents errors that occur during an interop call from .NET to JavaScript when the JavaScript runtime becomes disconnected.
```

Comment (SteveSandersonMS) [reply src/JSInterop/Microsoft.JSInterop/src/JSDisconnectedException.cs]: Done

**Comment by pos777** [comment]
Hello @SteveSandersonMS,

I am using the sample from the https://github.com/dotnet/aspnetcore/issues/32808#issue-894160450 issue with .NET v5.0.6.
If I open the 'Virtualize test' page, then close it, and wait for a while, I get the `TaskCanceledException`:
image

Assume, I'm developing a custom `Virtualize` component. Currently, I have to write something like this to avoid this exception:
```
public async ValueTask DisposeAsync()
{
    try
    {
        if (_selfReference != null)
        {
            await _jsRuntime.InvokeVoidAsync($"{JsFunctionsPrefix}.dispose", _selfReference);
        }
    }
    catch (**TaskCanceledException**)
    {
        // If the browser is gone, we don't need it to clean up any browser-side state
    }
}
```

Will this code break under .NET 6?
Since the `JSDisconnectedException` is a new class and it is not available in .NET 5, should I create two versions of the custom `Virtualize` component? One with the `TaskCanceledException` processing for .NET 5, and the other with the `JSDisconnectedException` processing for .NET 6.

Thanks,
Ilya
