### PR TITLE
Fixup OpenAPI displayed param type when using TryParse

### LINKED ISSUE #36412: OpenAPI documentation is incorrect when using custom TryParse() binding with Minimal APIs
### Describe the bug

If a type with a static `TryParse()` method is used as a parameter for a Minimal APIs action, the OpenAPI description does not work as would be expected.

There are two examples of this I have found for `MapGet()` and `MapPost()`.

#### `MapGet`

If a parameter uses a custom type which has a `TryParse()` method, it will be reported as an object parameter, rather than the string that is received to be parsed.

image

#### `MapPost`

If a parameter uses a custom type which has a `TryParse()` method, it will be reported as both an object query string parameter _and_ as the request body. If `[FromBody]` is used on the parameter, the extra parameter is not shown.

image

### To Reproduce

Create an empty ASP.NET Core 6 project with a reference to `Swashbuckle.AspNetCore` with the below code as `Program.cs`.

```csharp
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = builder.Environment.ApplicationName, Version = "v1" });
});

var app = builder.Build();

// Will report a student as a query string parameter and as the request body
app.MapPost("/enroll1", (Student student) => Results.NoContent())
   .Accepts<Student>("application/json");

// Will report the student in the body only
app.MapPost("/enroll2", ([FromBody] Student student) => Results.NoContent())
   .Accepts<Student>("application/json");

// Will report the parameter as an object instead of as a string
app.MapGet("/student/{student}", (Student student) => $"Hi {student.Name}");

app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.EnableTryItOutByDefault();
    options.SwaggerEndpoint("/swagger/v1/swagger.json", $"{builder.Environment.ApplicationName} v1");
});

app.Run();

public record Student(string Name)
{
    public static bool TryParse(string value, out Student? result)
    {
        if (value is null)
        {
            result = null;
            return false;
        }

        result = new Student(value);
        return true;
    }
}
```

### Further technical details

.NET SDK version `6.0.100-rc.1.21460.8`

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/36412

Before query and path would show object for complex types, now they display string and for primitives we keep them as the primitives name.

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

File: src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs [hunk 1]
```diff
@@ -266,19 +266,47 @@ static void AssertPathParameter(ApiDescription apiDescription)
...
-                Assert.Equal(typeof(TryParseStringRecord), param.ModelMetadata.ModelType);
+                Assert.Equal(typeof(string), param.ModelMetadata.ModelType);
                 Assert.Equal(BindingSource.Path, param.Source);
             }
 
             AssertPathParameter(GetApiDescription((TryParseStringRecord foo) => { }, "/{foo}"));
         }
 
+        [Fact]
+        public void AddsFromRouteParameterAsPathWithCustomTypeWithTryParse()
```
Comment (BrennanConroy) [inline src/Mvc/Mvc.ApiExplorer/test/EndpointMetadataApiDescriptionProviderTest.cs:283]:
```suggestion
        public void AddsFromRouteParameterAsPathWithPrimitiveTypeWithTryParse()
```

**Comment by BrennanConroy** [comment]
FYI, added a nullable primitive type check
