### PR TITLE
Synchronize writing to connection and aborting connection

### LINKED ISSUE #6701: "Writing is not allowed after writer was completed", with SignalR 1.1
### Describe the bug
I'm receiving "Writing is not allowed after writer was completed" on the latest release of SignalR with .NET Core 2.2. We previously used 1.0.0-rc1-final without any issues, and all of a sudden started receiving this issue with 1.1 on the client. We also receive a lot of "Task was cancelled" from the RedisHubLifetimeManager. Attaching screenshots below.

We ran SignalR 1.1 on the backend with 1.0.0-rc1-final on the client without any issues, but when we upgraded our client to 1.1, we started receiving this in our logs.

Another change we did while upgrading was to add "skipNegotiate: true" on the client, as well as forcing websockets. Not sure if this is related. I can't reproduce the error locally, since it doesn't happen often and seems related to only a few of our clients.

Also, the server seems to go down quite often after the upgrade. Can't seem to find any reason for this, but it was stable before we upped our clients.

### To Reproduce
Can't reproduce the error locally, we just see it in our production environment logs. 

### Expected behavior
Expected it to be gone with 1.1.0, since I saw previous reports of the problem on RC versions.

### Screenshots

Screenshot of writing is not allowed message:
image

Screenshot of task cancelled exception:
image

### Additional context
`dotnet --info` output:
image 
This is on our production environment. Locally we have the 2.2 runtime.

EDIT: If this issue is misplaced or inproper, feel free to close it. I didn't know where to turn.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/AspNetCore/issues/6701

Verified perf didn't change.

### CODE REVIEW

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 1]
```diff
@@ -533,11 +557,15 @@ private void CheckClientTimeout()
             }
         }
 
-        private static void AbortConnection(object state)
+        private static async void AbortConnection(object state)
```
Comment (BrennanConroy) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Yes I know... open to suggestions

Comment (davidfowl) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: Async void.....

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 2]
```diff
@@ -533,11 +557,15 @@ private void CheckClientTimeout()
...
         {
             var connection = (HubConnectionContext)state;
+
+            await connection._writeLock.WaitAsync();
+
             try
             {
+                connection.Input.CancelPendingRead();
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: This doesn’t need to be synchronized

**Comment by davidfowl** [comment]
Help me understand this change? The description of the fix is a bit light on explanation.

**Comment by BrennanConroy** [comment]
Servers could get error logs saying "Writing is not allowed after writer was completed" if the connection was closed while writing, especially when writing the ping message. This synchronizes the abort with the writing so we wont see error logs when writing would be expected to fail.

File: src/SignalR/server/Core/src/HubConnectionContext.cs (hunk 1 above)
Comment (halter73) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: More "async avoid", amirite?

I'll show myself out 🤦

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 3]
```diff
@@ -355,19 +380,19 @@ private async Task WriteHandshakeResponseAsync(HandshakeResponseMessage message)
...
                 return;
             }
 
-            _connectedAborted = true;
-
             Input.CancelPendingRead();
 
             // We fire and forget since this can trigger user code to run
-            ThreadPool.QueueUserWorkItem(_abortedCallback, this);
+            _ = Task.Factory.StartNew(AbortConnection, this, cancellationToken: default, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Why?

**Comment by JamesNK** [comment]
Unit test?

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 4]
```diff
@@ -355,19 +380,19 @@ private async Task WriteHandshakeResponseAsync(HandshakeResponseMessage message)
...
                 return;
             }
 
-            _connectedAborted = true;
-
             Input.CancelPendingRead();
 
             // We fire and forget since this can trigger user code to run
-            ThreadPool.QueueUserWorkItem(_abortedCallback, this);
+            _ = Task.Run(AbortConnection);
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: This allocates

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 5]
```diff
@@ -551,18 +577,28 @@ private void CheckClientTimeout()
...
-            }
-            catch (Exception ex)
-            {
-                Log.AbortFailed(connection._logger, ex);
-            }
-            finally
+
+            _ = InnerAbortConnection(connection);
+
+            async Task InnerAbortConnection(HubConnectionContext connection)
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: static

Comment (BrennanConroy) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: Didn't even realize that was a thing for local functions

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 6]
```diff
@@ -551,18 +577,28 @@ private void CheckClientTimeout()
...
             {
-                // Communicate the fact that we're finished triggering abort callbacks
-                connection._abortCompletedTcs.TrySetResult(null);
+                await connection._writeLock.WaitAsync();
+
+                try
+                {
+                    connection._connectionAbortedTokenSource.Cancel();
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: This is calling user code under a lock.

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 7]
```diff
@@ -561,8 +588,23 @@ private static void AbortConnection(object state)
...
             finally
             {
-                // Communicate the fact that we're finished triggering abort callbacks
-                connection._abortCompletedTcs.TrySetResult(null);
+                _ = InnerAbortConnection(connection);
+            }
+
+            static async Task InnerAbortConnection(HubConnectionContext connection)
+            {
+                await connection._writeLock.WaitAsync();
```
Comment (davidfowl) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Add a comment here about why we're waiting

**Comment by BrennanConroy** [comment]
>Unit test?

It's a race and there isn't anywhere to inject our own test code to force it.

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 8]
```diff
@@ -173,7 +178,7 @@ public virtual ValueTask WriteAsync(HubMessage message, CancellationToken cancel
         /// <returns></returns>
         public virtual ValueTask WriteAsync(SerializedHubMessage message, CancellationToken cancellationToken = default)
         {
-            if (_connectedAborted)
+            if (_connectionAborted)
```
Comment (halter73) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Is there much reason to check _connectionAborted before acquiring the lock when we check immediately after? Presumably, if the connection is aborted, whoever has the lock shouldn't for long. I prefer removing redundant checks if possible.

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 9]
```diff
@@ -313,13 +333,19 @@ private async Task TryWritePingSlowAsync()
         {
             try
             {
+                if (_connectionAborted)
```
Comment (halter73) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Just looking at this for the first time, I find it very funny that we have TryWritePingSlowAsync for the normal case when we actually write a ping, but save on the state machine allocation in the TryWritePingAsync failure case when it can't immediately acquire the write lock.

I think we might have officially jumped the shark with this fast/slow/awaited pattern 🤣

Comment (anurse) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: fonzie jumping the shark

File: src/SignalR/server/Core/src/HubConnectionContext.cs [hunk 10]
```diff
@@ -355,15 +381,15 @@ private async Task WriteHandshakeResponseAsync(HandshakeResponseMessage message)
         /// </summary>
         public virtual void Abort()
         {
+            _connectionAborted = true;
```
Comment (halter73) [inline src/SignalR/server/Core/src/HubConnectionContext.cs]: Why was this moved? If _connectionAbortedTokenSource.IsCancellationRequested is true, doesn't that mean that Abort() must have been called?

Also, since _connectionAborted is set outside a lock and PipeReader.CancelPendingRead doesn't necessarily schedule the reader because the reader can observer cancellation synchronously, _connectionAborted should be `volatile`.

Comment (halter73) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: Forget about the `volatile`. My brain is still a little poisoned back from when Pipes/SocketInput locked less. [This lock](https://github.com/dotnet/corefx/blob/87b2e237fafbdfb01f03f16558f3fa17f8288f91/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L600) should mean the volatile is unnecessary.

**Review by davidfowl — APPROVED** [review]

File: src/SignalR/server/Core/src/HubConnectionContext.cs (hunk 8 above)
Comment (davidfowl) [reply src/SignalR/server/Core/src/HubConnectionContext.cs]: Agreed

**Comment by davidfowl** [comment]
Do we need to backport this?

**Comment by BrennanConroy** [comment]
>Do we need to backport this?

Worst case it's an erroneous error log. There is no functional issue here. Based on that I don't think we should, but open to other opinions.

**Comment by davidfowl** [comment]
Looks like a legit test failures:
- Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.ConnectionTimesOutIfInitialPingAndThenNoMessages
- 
Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.AbortFromHubMethodForcesClientDisconnect

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=186945&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2511
