### PR TITLE
Fix sending to another client from OnConnectedAsync

### LINKED ISSUE #47189: Client.Client(connectionId) returing incorrect proxy connection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The issue only happens on OnConnectedAsync. The issue does not happen on OnDisconnectedAsync and will work as expected.

image

### Expected Behavior

When calling Clients.Client with a Connection Id, I would expect the correct client proxy to be returned.

### Steps To Reproduce

Create a notification hub 

`public class NotificationHub : Hub, INotificationHub`

Try to call another connected client when a different client is connecting.

`public override async Task OnConnectedAsync()`

When the first client is connecting in "OnConnectedAsync()", try to get the proxy of an existing connection via the Clients.Client(otherId). The current connecting connection proxy will be returned instead of the one requested.

```
var client = Clients.Client(connectionId);
await client.SendCoreAsync(nameof(SendSingleNotification), new object[] { message });
```

### Exceptions (if any)

_No response_

### .NET Version

7.0.201

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/47189

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]

File: src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs [hunk 1]
```diff
@@ -4891,6 +4891,39 @@ public void TooManyParametersWithServiceThrows()
...
+            {
+                HttpContext = httpContext
+            };
+            client2.Connection.Features.Set<IHttpContextFeature>(feature);
+
+            var connectionHandlerTask = await client1.ConnectAsync(connectionHandler).DefaultTimeout();
+            _ = await client2.ConnectAsync(connectionHandler).DefaultTimeout();
+
+            var message = Assert.IsType<InvocationMessage>(await client1.ReadAsync().DefaultTimeout());
+            Assert.Equal(1, message.Arguments.Length);
```
Comment (BrennanConroy) [inline src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs:4921]:
```suggestion
            Assert.Single(message.Arguments);
```

**Review by halter73 — APPROVED** [review]

File: src/SignalR/server/Core/src/Internal/HubCallerClients.cs [hunk 2]
```diff
@@ -50,7 +50,7 @@ public ISingleClientProxy Client(string connectionId)
     {
         if (!InvokeAllowed)
         {
-            return new NoInvokeSingleClientProxy(_hubClients.Client(_connectionId));
```
Comment (halter73) [inline src/SignalR/server/Core/src/Internal/HubCallerClients.cs:53]: 😢
