### PR TITLE
Fix OpenAPI transformer lifetimes and disposal

### LINKED ISSUE #57211: OpenAPI activates transformers too many times
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm doing so work comparing the performance of M.A.OpenApi with NSwag and Swashbuckle, and based on my current numbers, M.A.OpenApi is coming out as the slowest.

As part of looking into that I noticed that using `AddSchemaTransformer<T>()` seemed to be significantly slower (~20ms: https://github.com/martincostello/aspnetcore-openapi/pull/23#issuecomment-2273228860) than `AddSchemaTransformer(IOpenApiSchemaTransformer)`. It makes sense that the former is slower as it's DI-activated vs. a singleton, but I was surprised at how much slower.

Doing some further digging with trying to make the service a singleton, I noticed that the transformer instance was being activated 15 times per HTTP request to get the OpenAPI document - I would expect only one for the lifetime of the application.

### Expected Behavior

Document/operation/schema transformers are only activated as many times as their associated service registration requires (singleton vs. scoped vs. transient etc.).

### Steps To Reproduce

1. Clone https://github.com/martincostello/aspnetcore-openapi/commit/8805a51f3cb68444177a47f1112b4f630cd0cfe5
2. Launch the application in a debugger
3. Navigate to the `https://localhost:50001/swagger-ui/index.html` URL
4. Observe the following debug output:

```
Activations: 1
Activations: 2
Activations: 3
Activations: 4
Activations: 5
Activations: 6
Activations: 7
Activations: 8
Activations: 9
Activations: 10
Activations: 11
Activations: 12
Activations: 13
Activations: 14
Activations: 15
```

### Exceptions (if any)

_No response_

### .NET Version

9.0.100-preview.7.24406.8

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #57211.

This PR fixes an underlying issue with factory-activated operation and schema transformers being initialized/disposed too frequently in the OpenAPI document generation pipeline.

Prior to this change, factory-activated schema transformers would be activated/disposed once for each schema within a document. Factory-activated operation transformers would be activated/disposed once for each endpoint within an application.

For an application like the following:

```csharp
var builder = WebApplication.CreateBuilder();

builder.Services.AddOpenApi(options =>
{
	options.AddOperationTransformer<ActivatedOperationTransformer>();
	options.AddSchemaTransformer<ActivatedSchemaTransformer>();
})

var app = builder.Build();

app.MapPost("/"project, (Todo todo) => new Project(todo));
app.MapPost("/project", (Project project) => project);
app.MapGet("/project", () => new Project());
```

The `ActivatedOperationTransformer` would be instantiated/disposed three times for each endpoint and the `AddSchemaTransformer` would be instantiated/disposed twice for each request to the document. After this change, both transformers are activated/disposed once.

This PR also updates the `OpenApiDocumentService` to consume the scoped IServiceProvider instance from `HttpContext.RequestServices` to all transformer contexts to support resolving scoped dependencies. Factory-activated transformers have the following behavior for constructor-injected dependencies:

- Transformers always have a scoped lifetime where the "unit-of-work" is a single request to generate the OpenAPI document.
- Factory-activated transformers respect the singleton lifetime of constructor-injected dependencies they take with that lifetime.
- Factory-activated transformers respect the scoped lifetime of constructor-dependencies they take with that lifetime.
- Factory-activated transformers do not respect the transient lifetime of dependencies they take on (those are always effectively scoped).
	- Transient scope is respected if transient services are resolved using `OpenApiXTransformerContext.ApplicationServices`. 

The transformer benchmarks are as follows after this change:

|                         Method | TransformerCount |       Mean |     Error |    StdDev |      Op/s |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------------------- |----------------- |-----------:|----------:|----------:|----------:|-------:|-------:|------:|----------:|
|  ActivatedOperationTransformer |               10 |   2.628 us | 0.0229 us | 0.0191 us | 380,574.6 | 0.0572 | 0.0153 |     - |      7 KB |
| OperationTransformerAsDelegate |               10 |   2.568 us | 0.0234 us | 0.0219 us | 389,388.6 | 0.0534 | 0.0114 |     - |      7 KB |
|   ActivatedDocumentTransformer |               10 |   2.487 us | 0.0312 us | 0.0261 us | 402,106.0 | 0.0534 | 0.0114 |     - |      7 KB |
|  DocumentTransformerAsDelegate |               10 |   2.433 us | 0.0466 us | 0.0436 us | 410,945.3 | 0.0534 | 0.0114 |     - |      6 KB |
|     ActivatedSchemaTransformer |               10 |  33.116 us | 0.5669 us | 0.5026 us |  30,197.3 | 0.2441 |      - |     - |     48 KB |
|    SchemaTransformerAsDelegate |               10 |  32.653 us | 0.5819 us | 0.7768 us |  30,625.3 | 0.2441 |      - |     - |     48 KB |
|  ActivatedOperationTransformer |              100 |   4.832 us | 0.0705 us | 0.0659 us | 206,961.1 | 0.0839 | 0.0153 |     - |     11 KB |
| OperationTransformerAsDelegate |              100 |   4.687 us | 0.0455 us | 0.0426 us | 213,375.7 | 0.0687 | 0.0153 |     - |      9 KB |
|   ActivatedDocumentTransformer |              100 |   3.991 us | 0.0705 us | 0.0625 us | 250,570.7 | 0.0687 | 0.0153 |     - |      9 KB |
|  DocumentTransformerAsDelegate |              100 |   3.238 us | 0.0531 us | 0.0496 us | 308,811.6 | 0.0534 | 0.0114 |     - |      6 KB |
|     ActivatedSchemaTransformer |              100 |  88.081 us | 0.3926 us | 0.3672 us |  11,353.2 | 0.4883 |      - |     - |     87 KB |
|    SchemaTransformerAsDelegate |              100 |  86.935 us | 0.2593 us | 0.2426 us |  11,502.8 | 0.4883 |      - |     - |     85 KB |
|  ActivatedOperationTransformer |             1000 |  38.982 us | 0.7751 us | 0.8926 us |  25,652.8 | 0.3662 | 0.0610 |     - |     46 KB |
| OperationTransformerAsDelegate |             1000 |  26.782 us | 0.5325 us | 0.6340 us |  37,338.1 | 0.1831 | 0.0305 |     - |     23 KB |
|   ActivatedDocumentTransformer |             1000 |  34.239 us | 0.5840 us | 0.5463 us |  29,206.1 | 0.2441 |      - |     - |     30 KB |
|  DocumentTransformerAsDelegate |             1000 |  12.339 us | 0.0918 us | 0.0858 us |  81,043.6 | 0.0458 | 0.0153 |     - |      6 KB |
|     ActivatedSchemaTransformer |             1000 | 600.651 us | 5.7270 us | 5.3570 us |   1,664.9 |      - |      - |     - |    474 KB |
|    SchemaTransformerAsDelegate |             1000 | 613.103 us | 2.8785 us | 2.5517 us |   1,631.0 | 1.9531 |      - |     - |    450 KB |

### CODE REVIEW

File: src/OpenApi/src/Services/OpenApiDocumentProvider.cs [hunk 1]
```diff
@@ -44,7 +44,8 @@ public async Task GenerateAsync(string documentName, TextWriter writer, OpenApiS
         // document to a file. See https://github.com/microsoft/OpenAPI.NET/issues/421 for
         // more info.
         var targetDocumentService = serviceProvider.GetRequiredKeyedService<OpenApiDocumentService>(documentName);
-        var document = await targetDocumentService.GetOpenApiDocumentAsync();
+        var scopedService = serviceProvider.CreateScope();
```
Comment (amcasey) [inline src/OpenApi/src/Services/OpenApiDocumentProvider.cs:47]: When does this scope end?  This seems like the sort of thing that would need to be disposed.

**Review by amcasey — COMMENTED** [review]
The concept makes sense, but I don't fully understand the implementation details (chiefly, how scoping works in DI).

File: src/OpenApi/src/Services/OpenApiDocumentProvider.cs (hunk 1 above)
Comment (captainsafia) [reply src/OpenApi/src/Services/OpenApiDocumentProvider.cs:47]: Ah good catch -- there should be a `using` at the beginning of this line. The scope terminates after the call to `GetOpenApiDocumentAsync` to mimic what happens at at runtime when an HTTP request is sent to retrieve the OpenAPI document.

This codepath is a bit unique because the `IDocumentProvider` is queried once per document at build-time when the app is launched via the `HostFactoryResolver` so there isn't an HTTP request-based scope at all (in fact, there's [no server running](https://github.com/dotnet/aspnetcore/blob/01da7cd4614bf573776ab3455239e05a8f2b0e9b/src/Tools/GetDocumentInsider/src/Commands/GetDocumentCommandWorker.cs#L67-L76)).

File: src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs [hunk 2]
```diff
@@ -139,45 +138,31 @@ internal async Task<OpenApiSchema> GetOrCreateSchemaAsync(Type type, ApiParamete
...
-        await ApplySchemaTransformersAsync(schema, type, parameterDescription, cancellationToken);
+        await ApplySchemaTransformersAsync(schema, type, scopedServiceProvider, schemaTransformers, parameterDescription, cancellationToken);
         _schemaStore.PopulateSchemaIntoReferenceCache(schema, captureSchemaByRef);
         return schema;
     }
 
-    internal async Task ApplySchemaTransformersAsync(OpenApiSchema schema, Type type, ApiParameterDescription? parameterDescription = null, CancellationToken cancellationToken = default)
+    internal async Task ApplySchemaTransformersAsync(OpenApiSchema schema, Type type, IServiceProvider scopedServiceProvider, List<IOpenApiSchemaTransformer>? schemaTransformers, ApiParameterDescription? parameterDescription = null, CancellationToken cancellationToken = default)
     {
+        if (schemaTransformers is null)
```
Comment (martincostello) [inline src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:148]: Also test for empty?

File: src/OpenApi/src/Transformers/TypeBasedTransforrmerExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+namespace Microsoft.AspNetCore.OpenApi;
+
+internal static class TypeBasedTransformerExtensions
+{
+    /// <summary>
+    /// Supports disposing of factory-based transformers that implement <see cref="IDisposable"/> or <see cref="IAsyncDisposable"/>
+    /// after a given OpenAPI document generation request has been completed.
+    /// </summary>
+    /// <remarks>
+    /// This method is intended to be invoked on <see cref="TypeBasedOpenApiOperationTransformer" /> and <see cref="TypeBasedOpenApiSchemaTransformer" /> instances.
```
Comment (martincostello) [inline src/OpenApi/src/Transformers/TypeBasedTransforrmerExtensions.cs:13]:
```suggestion
    /// This method is intended to be invoked on <see cref="TypeBasedOpenApiOperationTransformer" /> and <see cref="TypeBasedOpenApiSchemaTransformer" />
```

**Review by martincostello — APPROVED** [review]

File: src/OpenApi/src/Services/OpenApiDocumentService.cs [hunk 4]
```diff
@@ -38,6 +38,9 @@ internal sealed class OpenApiDocumentService(
     private readonly OpenApiSchemaService _componentService = serviceProvider.GetRequiredKeyedService<OpenApiSchemaService>(documentName);
     private readonly OpenApiSchemaReferenceTransformer _schemaReferenceTransformer = new();
 
+    private List<IOpenApiSchemaTransformer>? _schemaTransformers;
```
Comment (amcasey) [inline src/OpenApi/src/Services/OpenApiDocumentService.cs:41]: Do null and empty have different meanings?  If not, would it be easier to initialize these to empty lists?

**Review by amcasey — APPROVED** [review]

File: src/OpenApi/src/Services/OpenApiDocumentService.cs [hunk 5]
```diff
@@ -50,28 +53,36 @@ internal sealed class OpenApiDocumentService(
...
+    private async Task ApplyTransformersAsync(OpenApiDocument document, IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
     {
         var documentTransformerContext = new OpenApiDocumentTransformerContext
         {
             DocumentName = documentName,
-            ApplicationServices = serviceProvider,
+            ApplicationServices = scopedServiceProvider,
             DescriptionGroups = apiDescriptionGroupCollectionProvider.ApiDescriptionGroups.Items,
         };
         // Use index-based for loop to avoid allocating an enumerator with a foreach.
```
Comment (amcasey) [inline src/OpenApi/src/Services/OpenApiDocumentService.cs:88]: I think `List<T>.Enumerator` is a struct?

Comment (amcasey) [reply src/OpenApi/src/Services/OpenApiDocumentService.cs:88]: Nit: If we're micro-optimizing this loop, do we want to call `Count` once, up-front, rather than on every iteration?

File: src/OpenApi/src/Services/OpenApiDocumentService.cs (hunk 4 above)
Comment (captainsafia) [reply src/OpenApi/src/Services/OpenApiDocumentService.cs]: Yeah...I think this was an unfounded case of premature optimization.
