### PR TITLE
Use reference equality to compare model instances in EditContext

### LINKED ISSUE #18069: Blazor: EditContext fieldstate tracking falls apart when model implements GetHashCode
### Describe the bug
When a model implements `GetHashCode`, the `_fieldState` dictionary within `EditContext` continually adds to it's collection for the same field, effectively breaking the field-state logic.

### To Reproduce
In my case, I used a protocol buffer to generate a simple C# class.  Here's a gist: https://gist.github.com/aaronhudon-ts/6f9b079014115f539feef9b599a2c14d

- Put a breakpoint in EditContext.cs `GetFieldState`.  Start changing values in fields. You will notice that the call to `TryGetValue` always fails due to the underlying `GetHashCode` call of the `FieldIdentifier`.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore/issues/18069

### CODE REVIEW

File: src/Components/Forms/src/FieldIdentifier.cs [hunk 1]
```diff
@@ -35,7 +38,7 @@ public static FieldIdentifier Create<TField>(Expression<Func<TField>> accessor)
         /// <param name="fieldName">The name of the editable field.</param>
         public FieldIdentifier(object model, string fieldName)
         {
-            if (model == null)
+            if (model is null)
```
Comment (pranavkm) [inline src/Components/Forms/src/FieldIdentifier.cs]: In case a user type has a poorly implemented equality operator.

File: src/Components/Forms/src/FieldIdentifier.cs [hunk 2]
```diff
@@ -64,18 +67,27 @@ public FieldIdentifier(object model, string fieldName)
 
         /// <inheritdoc />
         public override int GetHashCode()
-            => (Model, FieldName).GetHashCode();
+        {
+            // Ww want to compare Model instances by reference RuntimeHelpers.GetHashCode returns identical hashes for equal object references which is what we want.
+            var modelHash = RuntimeHelpers.GetHashCode(Model);
+            var fieldHash = StringComparer.Ordinal.GetHashCode(FieldName);
```
Comment (pranavkm) [inline src/Components/Forms/src/FieldIdentifier.cs]: Changed to use the same Comparer used by `Equals`

File: src/Components/Forms/src/FieldIdentifier.cs [hunk 3]
```diff
@@ -64,7 +65,16 @@ public FieldIdentifier(object model, string fieldName)
 
         /// <inheritdoc />
         public override int GetHashCode()
-            => (Model, FieldName).GetHashCode();
+        {
+            // Ww want to compare Model instances by reference RuntimeHelpers.GetHashCode returns identical hashes for equal object references which is what we want.
```
Comment (SteveSandersonMS) [inline src/Components/Forms/src/FieldIdentifier.cs]:
```suggestion
            // We want to compare Model instances by reference. RuntimeHelpers.GetHashCode returns identical hashes for equal object references (ignoring any `Equals`/`GetHashCode` overrides) which is what we want.
```

File: src/Components/Forms/test/FieldIdentifierTest.cs [hunk 4]
```diff
@@ -89,6 +102,19 @@ public void SameContentsProduceSameHashCodesAndEquality()
             Assert.True(fieldIdentifier1.Equals(fieldIdentifier2));
         }
 
+        [Fact]
+        public void SameContents_WithOverridenEqualsAndGetHashCode_ProduceSameHashCodesAndEquality()
+        {
+            // Arrange
+            var model = new EquatableModel();
+            var fieldIdentifier1 = new FieldIdentifier(model, nameof(EquatableModel.Property));
+            var fieldIdentifier2 = new FieldIdentifier(model, nameof(EquatableModel.Property));
```
Comment (SteveSandersonMS) [inline src/Components/Forms/test/FieldIdentifierTest.cs]:
```suggestion
            model.Property = "changed value"; // To show it makes no difference if the overridden `GetHashCode` result changes
            var fieldIdentifier2 = new FieldIdentifier(model, nameof(EquatableModel.Property));
```

Not sure this suggestion really adds that much extra value so please feel free to ignore it if you prefer.

**Review by SteveSandersonMS — APPROVED** [review]
Looks great!

**Comment by rynowak** [comment]
:shipit:

**Comment by aaronhudon** [comment]
@pranavkm when will this bugfix be available ?

**Comment by pranavkm** [comment]
@aaronhudon the change was ported to the 3.1.3 release as part of https://github.com/dotnet/aspnetcore/pull/18649. 3.1.3 is scheduled to be released mid-March.

**Comment by aaronhudon** [comment]
@pranavkm I have installed the 3.1.3 runtime, and SDK.  Unfortunately I'm not seeing a change in behavior (e.g. the bug isn't fixed).   Are there any additional project settings that need to be applied?  I'm assuming no.

**Comment by pranavkm** [comment]
@aaronhudon are you building a Blazor Server project?

**Comment by aaronhudon** [comment]
> @aaronhudon are you building a Blazor Server project?

Yes

**Comment by aaronhudon** [comment]
@pranavkm Any updates on this?

**Comment by SteveSandersonMS** [comment]
This is fixed in `master` and so will ship in the 5.0 releases (e.g., https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-1/)

**Comment by aaronhudon** [comment]
> This is fixed in `master` and so will ship in the 5.0 releases (e.g., https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-1/)

So it did *not* make it in to 3.1.103 ?

**Comment by pranavkm** [comment]
@SteveSandersonMS we ported the fix to 3.1.3. @aaronhudon are you certain you have `Microsoft.AspNetCore.App 3.1.3` installed on your box? If you're still seeing the issue, could you file a new issue so we can track it?

**Comment by aaronhudon** [comment]
This is what `dotnet --list-runtimes` is showing me.  The behavior still has not changed when using protocol buffers as models.  I can dig up my original repro and submit it to you again.

```
PM> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by aaronhudon** [comment]
@pranavkm how can one tell if the 3.1.3 runtime is being used, as opposed to 3.1.0, 3.1.2 (which I also have installed)?

**Comment by aaronhudon** [comment]
@pranavkm !#%^%^   My project file had `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` which was forcing the runtime to 3.1.  

Removed, and the fix is fantastic.  Thanks again!

**Comment by pranavkm** [comment]
@aaronhudon you might have an older SDK. The version of the .NET runtime for self contained deployment is determined by the version of the SDK. Using 3.1.103 should get you the right version, but you want to make sure you're not using a different preview.
