### PR TITLE
Removing from API Description parameters when inferred (FromPath) and not in the route

### LINKED ISSUE #26234: ApiExplorer not handling multiple routes on same action method correctly
### Describe the bug

Given the following action method bound to multiple routes:

```csharp
[HttpGet]
[Route("foo")]
[Route("bar/{id}")]
public IActionResult Get(int id = 0)
```

As expected, the ApiExplorer surfaces two `ApiDescription` instances, one for each route. However, for the first route "foo", the `ApiDescription` includes the `id` path parameter, despite the fact that it's not part of the route template. For example, here's the ApiExplorer data (serialized as json):

```
[
  {
    relativePath: "Test/foo",
    httpMethod: "GET",
    parameters: [
      {
        name: "id",
        source: {
          displayName: "Path",
          id: "Path",
          isGreedy: false,
          isFromRequest: true,
        },
      }
    ],
  },
  {
    relativePath: "Test/bar/{id}",
    httpMethod: "GET",
    parameters: [
      {
        name: "id",
        source: {
          displayName: "Path",
          id: "Path",
          isGreedy: false,
          isFromRequest: true,
        },
      }
    ],
  },
]
```

### To Reproduce

```
> git clone git@github.com:domaindrivendev/ApiExplorerIssue.git
> cd ApiExplorerIssue
> dotnet run

Then navigate to "http://localhost:5000/apidescriptions" to see the ApiExplorer data
``` 

### Further technical details
- ASP.NET Core version: 3.1

### PR DESCRIPTION
**Pull request by brunolins16**
# Changing from Path to ModelBinding when inferred API parameters

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

The  `InferParameterBindingInfoConvention` will follow the rule described here [ApiBehaviorOptions.SuppressInferBindingSourcesForParameters Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apibehavioroptions.suppressinferbindingsourcesforparameters?view=aspnetcore-6.0)

image

https://github.com/dotnet/aspnetcore/blob/2325e1297aa85b089cce53bc93da3bc9cda7165a/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L94

However, it causes the issue #26234, since both will contain the parameter listed from route. With that in this PR I am adding a small check to verify if the parameter with `BindingSource == Path` and that does not contain a `FromRoute` attribute is part of the current route and if not, it will be changed back to `ModelBinding`.

This change will affect only the `APIExplorer` provider.

Fixes #26234

### CODE REVIEW

**Comment by brunolins16** [comment]
As mentioned in the PR description, I am changing only the `DefaultApiDescriptionProvider` avoiding to the `InferParameterBindingInfoConvention`, since it explicit set the parameter `BindingSource` as `Path` when it is part of any route (even if the route does not add it). However, that might be a good question if this part is really correct.

**Comment by pranavkm** [comment]
What's the inferred binding source for `id`? From what I can recall, it's supposed to be FromRoute as long as it appears in at least one route: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L101-L104.

**Comment by captainsafia** [comment]
@brunolins16 Can you educate me about where the InferParameterBinderConvention gets called before the changeset here gets called?

I just had a thought about whether or not it is possible to tweak that logic in the convention without disabling it outright but not sure if it has access to all the state we need to decide the binding source for the buggy scenario.

**Comment by brunolins16** [comment]
> @brunolins16 Bruno Lins de Oliveira FTE Can you educate me about where the InferParameterBinderConvention gets called before the changeset here gets called?
> 
> I just had a thought about whether or not it is possible to tweak that logic in the convention without disabling it outright but not sure if it has access to all the state we need to decide the binding source for the buggy scenario.

@captainsafia Sure.

Here is what I found.

It is called from `ApiBehaviorApplicationModelProvider` that is a `ApplicationModelProvider` called from `ApplicationModelFactory`. The `ApplicationModelFactory` is called by the `ControllerActionDescriptorProvider.OnProvidersExecuting`.

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.Core/src/ApplicationModels/ApiBehaviorApplicationModelProvider.cs#L48

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.Core/src/ApplicationModels/ApiBehaviorApplicationModelProvider.cs#L80

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.Core/src/ApplicationModels/ApplicationModelFactory.cs#L40

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.Core/src/ApplicationModels/ControllerActionDescriptorProvider.cs#L85

The `ApiDescriptionGroupCollectionProvider` will use `ActionDescriptorCollectionProvider.ActionDescriptors` (will call the `ControllerActionDescriptorProvider` and others only if the collection is not initialized yet) to call the `ApiDescriptionProviders` to process the actions.

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.ApiExplorer/src/ApiDescriptionGroupCollectionProvider.cs#L39

https://github.com/dotnet/aspnetcore/blob/1ca07094ce3827229658c8abb741a9c3bc1fd9ae/src/Mvc/Mvc.Core/src/Infrastructure/DefaultActionDescriptorCollectionProvider.cs#L47

I tried to find a way to not process the `InferParameterBinderConvention ` without break anything, but I was not able to. Will be great if you have ideas to share.

**Comment by captainsafia** [comment]
@brunolins16 Ah, I see. I was thinking about making a change somewhere here but I don't believe that we have access to the `ApiParameterContext.RouteParameters` object to be able to make the decision on whether or not the parameter appeared on the route here.

https://github.com/dotnet/aspnetcore/blob/6850cc8187751cdec3e4071e8786aeffe29d11ee/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L63-L76

**Comment by brunolins16** [comment]
> be able to make the decision on whether or not the parameter appeared on the route here.

If I understood your idea, that is exactly what it does here (but to find if the parameter is part of any route and set all as FromRoute)

https://github.com/dotnet/aspnetcore/blob/6850cc8187751cdec3e4071e8786aeffe29d11ee/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L109

The problem, that I was not able to figure out, is because the ActionDescriptors (InferParameterBindingInfoConvention) could be populated before the ApiDescriptionProviders we don't have any way to change them other them re-populating that will affect the execution.

**Comment by brunolins16** [comment]
> What's the inferred binding source for `id`? From what I can recall, it's supposed to be FromRoute as long as it appears in at least one route: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L101-L104.

@pranavkm Do you happen to know what is the reason why we set all of them FromRoute if it appears in one of the routes?

**Comment by pranavkm** [comment]
> Today the following is happening, and I don't feel it is completely right.

We'd wanted the rules to be easy to reason about. It's fairly unusual to have a parameter be bound from the route for one template but not the other. That said, it would be a breaking change to tweak this behavior particularly since nobody's really complained about the runtime behavior.

**Comment by brunolins16** [comment]
> > Today the following is happening, and I don't feel it is completely right.
> 
> We'd wanted the rules to be easy to reason about. It's fairly unusual to have a parameter be bound from the route for one template but not the other. That said, it would be a breaking change to tweak this behavior particularly since nobody's really complained about the runtime behavior.

Got it, so, in this case my fix is wrong because what should happen in this case, if I understood correctly, is the API explorer not include the parameter as part of the API description, is that right?

**Comment by pranavkm** [comment]
I don't know if it should not be included, but in the test:

```
    [InlineData("api/products/{id}", nameof(BindingSource.Path), nameof(BindingSource.Path))]
    [InlineData("api/products", nameof(BindingSource.Path), nameof(BindingSource.ModelBinding))]
    [InlineData("api/products", nameof(BindingSource.Body), nameof(BindingSource.Body))]
    public void GetApiDescription_WithInferredBindingSource(
        string template,
        string inferredBindingSourceName,
        string expectedBindingSourceName)
```

I would expect the inferred and expected binding source to be the same for all 3. If enough people complained that `BindingSource.Path` is the incorrect inferred value for `id`, then we could consider adding a switch / quirks mode to the infer parameter binding convention, but I wouldn't change just the api description because the runtime behavior would still only support binding from a route. (`?id=10` wouldn't bind but `my-route/10` would)

**Comment by brunolins16** [comment]
> d value for `id`, then we could consider adding a switch / quirks mode to the infer parameter binding convention, but I wouldn't change just the api description because the runtime behavior would still only support binding from a route. (`?id=10` wouldn't bind but `my-route/10` would)

I got the binding behavior, however, if I have a controller like this

``` csharp
    [HttpGet("api/products", Name = "Foo")]
    [HttpGet("api/products/{id}", Name = "Bar")]
    public IActionResult Get(int id = 0);
```

And use the `swagger.json` to generate the client. I will get this:

`public System.Threading.Tasks.Task BarAsync(int id);`
`public System.Threading.Tasks.Task FooAsync(int id);`

This in my opinion, is wrong because the id will never be bound in the `FooAsync(int id)` and that is what I mean about remove the parameter from the API Explorer.

Maybe it is an unusual scenario and, also, the API name will help the client, however, I still feel that it is wrong.

**Comment by pranavkm** [comment]
>  and that is what I mean about remove the parameter from the API Explorer.

Ok, that makes sense. Assuming the code doesn't end up being too gnarly, we could consider it.

File: src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs [hunk 1]
```diff
@@ -258,9 +261,30 @@ private void ProcessRouteParameters(ApiParameterContext context)
...
+                {
+                    if (parameter.Source == BindingSource.Path &&
+                        parameter.ModelMetadata is DefaultModelMetadata defaultModelMetadata &&
+                        !defaultModelMetadata.Attributes.Attributes.OfType<IFromRouteMetadata>().Any())
+                    {
+                        // If we didn't see the parameter in the route and no FromRoute metadata is set, it probably means
+                        // the parameter binding source was inferred (InferParameterBindingInfoConvention)  
+                        // probably because another route to this action contains it as route parameter.
+                        // let's add it to be removed from the API description
+                        inferredPathParametersToRemove.Add(parameter);
```
Comment (pranavkm) [inline src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:274]: Could we do this inline without the extra List allocation? Use a indexed loop that starts from the end so you can call `RemoveAt(i)`

File: src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs [hunk 2]
```diff
@@ -243,6 +243,46 @@ public void GetApiDescription_CreatesMultipleDescriptionsForMultipleHttpMethods(
...
 
+    [Theory]
+    [InlineData("api/products/{id}", nameof(BindingSource.Path), true)]
+    [InlineData("api/products", nameof(BindingSource.Path), false)]
+    [InlineData("api/products", nameof(BindingSource.Body), true)]
+    [InlineData("api/products", nameof(BindingSource.Query), true)]
+    public void GetApiDescription_WithInferredBindingSource(
+        string template,
+        string inferredBindingSourceName,
+        bool inferredParameterShouldBeIncluded)
```
Comment (pranavkm) [inline src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs:254]: Can we make these separate tests instead of ? `GetApiDescription_WithInferredBindingSource_IncludesPathParametersWhenPresentInRoute` / `GetApiDescription_WithInferredBindingSource_ExcludesPathParametersWhenNotPresentInRoute`?

Also do we need tests that verifies we don't change this if the BindingSource is not inferred?

File: src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs [hunk 3]
```diff
@@ -243,6 +245,59 @@ public void GetApiDescription_CreatesMultipleDescriptionsForMultipleHttpMethods(
...
+        };
+
+        // Act
+        var descriptions = GetApiDescriptions(action);
+
+        // Assert
+        var description = Assert.Single(descriptions);
+        Assert.Empty(description.ParameterDescriptions);
+    }
+
```
Comment (pranavkm) [inline src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs:267]:
```suggestion
```

File: src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs [hunk 4]
```diff
@@ -5,6 +5,7 @@
 using System.ComponentModel.DataAnnotations;
 using System.Reflection;
 using System.Text;
+
```
Comment (pranavkm) [inline src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs:8]:
```suggestion
```

File: src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs [hunk 5]
```diff
@@ -21,6 +22,7 @@
 using Microsoft.AspNetCore.Routing.Template;
 using Microsoft.Extensions.Options;
 using Microsoft.Net.Http.Headers;
+
```
Comment (pranavkm) [inline src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs:25]:
```suggestion
```

**Review by pranavkm — APPROVED** [review]

File: src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs [hunk 6]
```diff
@@ -239,11 +241,13 @@ private void ProcessRouteParameters(ApiParameterContext context)
...
-        foreach (var parameter in context.Results)
+        for (var i = context.Results.Count - 1; i >= 0; i--)
         {
+            var parameter = context.Results[i];
+
             if (parameter.Source == BindingSource.Path ||
-                parameter.Source == BindingSource.ModelBinding ||
-                parameter.Source == BindingSource.Custom)
+                   parameter.Source == BindingSource.ModelBinding ||
+                   parameter.Source == BindingSource.Custom)
```
Comment (halter73) [inline src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:250]:
```suggestion
               parameter.Source == BindingSource.ModelBinding ||
               parameter.Source == BindingSource.Custom)
```

File: src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs [hunk 7]
```diff
@@ -258,6 +262,20 @@ private void ProcessRouteParameters(ApiParameterContext context)
                         parameter.Source = BindingSource.Path;
                     }
                 }
+                else
+                {
+                    if (parameter.Source == BindingSource.Path &&
```
Comment (halter73) [inline src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:267]: Nit: `else if`?

File: src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs [hunk 8]
```diff
@@ -258,6 +262,20 @@ private void ProcessRouteParameters(ApiParameterContext context)
...
+                        parameter.ModelMetadata is DefaultModelMetadata defaultModelMetadata &&
+                        !defaultModelMetadata.Attributes.Attributes.OfType<IFromRouteMetadata>().Any())
+                    {
+                        // If we didn't see the parameter in the route and no FromRoute metadata is set, it probably means
+                        // the parameter binding source was inferred (InferParameterBindingInfoConvention)  
+                        // probably because another route to this action contains it as route parameter and
+                        // will be removed from the API description
+                        // https://github.com/dotnet/aspnetcore/issues/26234
+                        context.Results.RemoveAt(i);
```
Comment (halter73) [inline src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:276]: Does this situation only occur for parameters with default values? Given the scenario in the issue,

```C#
[HttpGet]
[Route("foo")]
[Route("bar/{id}")]
public IActionResult Get(int id = 0)
```

`id` could never come from the query string for the `foo` route, could it? Assuming not, this looks good.

**Review by halter73 — APPROVED** [review]

File: src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs (hunk 8 above)
Comment (pranavkm) [reply src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:276]: It does not because we stamp in `id`'s BindingSource as `FromRoute` due to this - https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ApplicationModels/InferParameterBindingInfoConvention.cs#L109-L126 (essentially there's one ParameterInfo for all of the route templates, so we treat the templates as a union)

Comment (brunolins16) [reply src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs:276]: Just to include an example: https://github.com/dotnet/aspnetcore/pull/39607#issuecomment-1017772958
