### PR TITLE
Treat ValidationContext as required in validation resolver APIs

### LINKED ISSUE #61738: Min API validation NRE when ValidationContext is not set on ValidateContext
Repro:
```csharp
using Microsoft.AspNetCore.Http.Validation;
using Microsoft.Extensions.Options;
using System.ComponentModel.DataAnnotations;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddValidation();
var app = builder.Build();

var model = new Model { Name = "Name" };

var validationOptions = app.Services.GetService<IOptions<ValidationOptions>>()!.Value;
if (!validationOptions.TryGetValidatableTypeInfo(typeof(Model), out var typeInfo))
{
    throw new InvalidOperationException("Type not found in validation options.");
}
var validateContext = new ValidateContext()
{
    ValidationOptions = validationOptions,
    // ValidationContext = new ValidationContext(model) // Uncomment this to fix it
};
await typeInfo.ValidateAsync(model, validateContext, CancellationToken.None);

[ValidatableType]
class Model
{
    [Required]
    public required string Name { get; init; }
}
```

This throws an exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Validation.ValidatablePropertyInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Validation.ValidatableTypeInfo.ValidateAsync(Object value, ValidateContext context, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/svbomer/src/test-apps/validationGen/Program.cs:line 21
```

### PR DESCRIPTION
**Pull request by captainsafia**
This pull request improves the validation logic in the `Microsoft.AspNetCore.Http.Validation` namespace by ensuring that a `ValidationContext` is a required property.

Fixes https://github.com/dotnet/aspnetcore/issues/61738

This pull request introduces several updates to the validation framework in `Microsoft.AspNetCore.Http`, focusing on improving type safety, simplifying validation logic, and enhancing test coverage. The key changes include making the `ValidationContext` property in `ValidateContext` required, removing redundant `Debug.Assert` statements, and updating tests to align with the new `ValidateContext` initialization pattern.

### Validation Framework Updates:

* **`ValidationContext` Property Update**:
  - The `ValidationContext` property in `ValidateContext` is now marked as `required`, ensuring it is always initialized. Additional documentation and examples have been added to clarify its usage. (`[[1]](diffhunk://#diff-b16fffb7593a94827187c81633f618740d0315cafe67c1ad148e74ee73d48369L19-R36)`, `[[2]](diffhunk://#diff-c25699c95b8367fb6f1c1c20b4566b5f15479fae809d04f1aee4faef7e36c883L27-R27)`)
  - The `ValidationContext` initialization in tests has been updated to use object initializers, improving readability and consistency. (`[[1]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43L44-R53)`, `[[2]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43L99-R111)`, `[[3]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43R143-L159)`, and others)

* **Simplification of Validation Logic**:
  - Removed `Debug.Assert` statements that checked for the presence of `ValidationContext`, as this is now enforced by the `required` modifier. (`[[1]](diffhunk://#diff-688f42bea373bd51787ca8ee43ca3a6456beba2ccf638189bc4d64a549627401L63-L64)`, `[[2]](diffhunk://#diff-c3a66d105b9c639c52f0ac3f111af08016219a354b470f31322b068cfadab37cL64-L65)`, `[[3]](diffhunk://#diff-4747a7dd84b487cb53a7e83e9402dac63077283371409e02b324106251c36d5bL48)`)
  - Adjusted the `Create` method in `ValidationEndpointFilterFactory` to initialize `ValidateContext` lazily, reducing unnecessary object creation. (`[[1]](diffhunk://#diff-5d39135cbdf8958ffced3a56b7d0b970c302cb2c24d32b8672b1c9c9c004c187L46-R46)`, `[[2]](diffhunk://#diff-5d39135cbdf8958ffced3a56b7d0b970c302cb2c24d32b8672b1c9c9c004c187L60-R81)`)

### Test Enhancements:

* Updated test cases in `ValidatableTypeInfoTests` to reflect the new `ValidateContext` initialization pattern, ensuring consistency and improved maintainability. (`[[1]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43L308-L313)`, `[[2]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43R346-L362)`, `[[3]](diffhunk://#diff-f089fa164925b2123ac8f2eb82a21c16006c355262f84596e6cbf32a0ab25a43R381-L398)`, and others)

### CODE REVIEW

File: src/Http/Http.Abstractions/test/Validation/ValidatableParameterInfoTests.cs [hunk 1]
```diff
@@ -285,6 +285,60 @@ public async Task Validate_ExceptionDuringValidation_CapturesExceptionAsError()
...
+        };
+
+        // Sanity check
+        Assert.Null(context.ValidationContext);
+
+        // Act
+        await paramInfo.ValidateAsync(null, context, default);
+
+        // Assert – a ValidationContext should have been created and the error recorded
+        Assert.NotNull(context.ValidationContext);
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/test/Validation/ValidatableParameterInfoTests.cs:311]: Any concerns with the internally created `ValidationContext` "leaking" outside of the validate call?

File: src/Http/Http.Abstractions/src/Validation/ValidatableTypeInfo.cs [hunk 2]
```diff
@@ -44,12 +43,15 @@ protected ValidatableTypeInfo(
     /// <inheritdoc />
     public virtual async Task ValidateAsync(object? value, ValidateContext context, CancellationToken cancellationToken)
     {
-        Debug.Assert(context.ValidationContext is not null);
         if (value == null)
         {
             return;
         }
 
+        // Although classes can be annotated with [DisplayName], we only process display names when producing
```
Comment (BrennanConroy) [inline src/Http/Http.Abstractions/src/Validation/ValidatableTypeInfo.cs:51]: Seems fine. Future looking, any reason we might prefer `[DisplayName]` here?

**Review by BrennanConroy — APPROVED** [review]

File: src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs [hunk 3]
```diff
@@ -58,14 +57,17 @@ protected ValidatableParameterInfo(
...
         // Skip validation if value is null and parameter is optional
         if (value == null && ParameterType.IsNullable())
         {
             return;
         }
 
+        // ValidationContext requires a non-null value although the invocation pattern that we use
+        // calls `GetValidationResult` and passes the value there. `GetValidationResult` tolerates
+        // null values so we only need to set a non-null value to the ValidationContext here.
+        context.ValidationContext ??= new ValidationContext(value ?? new object(), displayName: DisplayName, serviceProvider: null, items: null);
```
Comment (DamianEdwards) [inline src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: Can we avoid allocating a new value each time in the case we don't need one?

Comment (DamianEdwards) [inline src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: Curious about the `serviceProvider: null` here. Is there any case where validation logic using this context instance would require the context to be able to resolve services?

Comment (BrennanConroy) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: Oh yeah, like only newing up in the getter?

Comment (captainsafia) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: AFAIK, this will primarily affect scenarios where we are trying to validate `IValidatableObject`s that resolve something from the DI container. In that case, we probably want to provide guidance to whoever is invoking the resolver APIs at the root to make sure they set the validation context with the desired service provider like we do in [the ValidationEndpointFilterFactory](https://source.dot.net/#Microsoft.AspNetCore.Routing/ValidationEndpointFilterFactory.cs,6ee97ebed0cf10ef).

File: src/Http/Http.Abstractions/src/Validation/ValidatableTypeInfo.cs (hunk 2 above)
Comment (captainsafia) [reply src/Http/Http.Abstractions/src/Validation/ValidatableTypeInfo.cs:51]: I think the biggest issue would be that the default behavior here is inconsistent with how we handle properties and parameters where we do respect the attribute.

Also, this comment should be updated to say `[Display(Name = "")]`. 😓

File: src/Http/Http.Abstractions/test/Validation/ValidatableParameterInfoTests.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Abstractions/test/Validation/ValidatableParameterInfoTests.cs:311]: I don't think so? There isn't any state on the ValidationContext that the caller wouldn't be able to derive anyway.

Ideally, we wouldn't have this type at all and we'd have a single type that somehow unions ValidateContext and ValidationContext.

File: src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs (hunk 3 above)
Comment (DamianEdwards) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: OK, the scenario I'm not as sure about is a custom `ValidationAttribute` implementation that overrides `RequiresValidationContext` to return `true` and wants to resolve services from the `ValidationContext` directly (as it implements `IServiceProvider`). There are examples of this pattern around on the web, e.g. https://github.com/dotnet/aspnetcore/discussions/23305, https://andrewlock.net/injecting-services-into-validationattributes-in-asp-net-core, https://rossjayjones.github.io/dotnetcore/aspnetcore/mvc/dotnet/2018/09/09/injecting-services-into-validation-attributes-aspnetcore.html, https://stackoverflow.com/questions/62559817/how-to-get-inject-services-in-custom-validationattributes, https://forloop.co.uk/blog/resolving-ioc-container-services-for-validation-attributes-in-asp.net-mvc. Also this was supported in ASP.NET MVC (aspnet/mvc#6346) and is supported in ASP.NET Core MVC (#39382). It was raised for Blazor and closed without fixing (#23380).

Comment (captainsafia) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: I see. For this scenario, as long as the thing querying the resolver APIs is the validation filter then the service provider will be propagated correctly.

This issue came up when SignalR and dotnet-monitor tried to use the resolver APIs directly in their frameworks and ran into issues with the fact that we assume that it is always initialized "softly" via a `Debug.Assert`.

It seems there's enough evidence that accessing the DI container during validation is a common scenario, so we can make the `ValidationContext` property required on the `ValidateContext` and require whatever framework is calling into the resolver APIs to instantiate it (hopefully with the correct service provider for their context).

Comment (DamianEdwards) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs:69]: >For this scenario, as long as the thing querying the resolver APIs is the validation filter then the service provider will be propagated correctly.

I think that's the important part, i.e. that the caller (in this case, us) sets it up. It seems that at least the `ValidationAttribute` APIs have always supported some scenarios where the `ValidationContext` is null, or that its `IServiceProvider` implementation always returns null, but the methods on `System.ComponentModel.DataAnnotations.Validator` and of course `IValidatableObject.Validate` require an instance of `ValidationContext`, even if its `IServiceProvider` implementation returns null.

Comment (captainsafia) [reply src/Http/Http.Abstractions/src/Validation/ValidatableParameterInfo.cs]: I made a change in https://github.com/dotnet/aspnetcore/pull/61854/commits/1ec6dcfbfe1752194c8625a4ca6ee3721d4f85ce to make the ValidationContext property required so that the framework calling into the resolver APIs is always required to set it.

It makes aspect of the instantiation a little annoying but considering we marked the API as experimental I'm fine doing this for now and seeing how callers react to the change.

**Review by BrennanConroy — APPROVED** [review]
