### PR TITLE
Fix NavMenuHighlightsCurrentLocation in headless mode

### LINKED ISSUE #54497: Quarantine NavMenuHighlightsCurrentLocation
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.NavMenuHighlightsCurrentLocation

## Error Message

```text
System.AggregateException : One or more errors occurred. (Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 502
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/8daf92050ee64c50aff7c205ae31e5ed.png'
Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated tests work consistently on mobile browsers. -->
    <meta name="viewport" content="width=1024">
    <title>Blazor standalone</title>
    <base href="/">
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="app.css" rel="stylesheet">
</head>
<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled exception has occurred. See browser dev tools for details.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">\ud83d\uddd9</a>
    </div>

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        (function(){
            Blazor.start().then(function () {
                window['__aspnetcore__testing__blazor_wasm__started__'] = true;
            });
        })();
    </script>


</body>
) (Xunit.Sdk.NotEqualException: Assert.NotEqual() Failure
Expected: Not "Loading..."
Actual:   "Loading..."
   at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 302
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/c6fd42c442f74279a0d295a2a594784c.png'
Encountered browser errors
[2024-03-11T13:57:17Z] [Warning] http://127.0.0.1:33145/_framework/dotnet.runtime.9.0.0-preview.3.24156.1.aovcbg8by0.js 2:18098 "[--000dc9bc-emsc] MONO_WASM: Failed to find unused WebWorker, this may deadlock. Please increase the pthreadPoolReady. Running threads 0. Loading workers: 0"Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated tests work consistently on mobile browsers. -->
    <meta name="viewport" content="width=1024">
    <title>Blazor standalone</title>
    <base href="/">
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="app.css" rel="stylesheet">
</head>
<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled exception has occurred. See browser dev tools for details.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">\ud83d\uddd9</a>
    </div>

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        (function(){
            Blazor.start().then(function () {
                window['__aspnetcore__testing__blazor_wasm__started__'] = true;
            });
        })();
    </script>


</body>
)
---- OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 502
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/8daf92050ee64c50aff7c205ae31e5ed.png'
Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated 
```

## Stacktrace

<details>

```text

```
</details>

## Logs

[Standard_Console_Output (9).log](https://github.com/dotnet/aspnetcore/files/14572401/Standard_Console_Output.9.log)

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=597714&view=results

### PR DESCRIPTION
**Pull request by oroztocil**
This test is failing in CI and when run locally without debugger. The reason is that in the headless mode the window width is too small and the sidebar UI is hidden. This causes visibility-sensitive properties such as `IWebElement.Text` to return empty strings for hidden elements from the sidebar, causing assertions to fail.

The PR solves the issue by explicitly setting the window size for this particular test. We can discuss if the preferred solution is to set the window size globally when creating the test browser in the headless mode. Alternatively, the test could be fixed by using a visibility-independent API such as `IWebElement.GetDomProperty("innerText")` for reading the relevant values. However, using a realistic window size seems more appropriate for an E2E test.

The PR also adds the `IWebDriver.SetWindowSize` extension method. A few existing cases where window size is manipulated were refactored to use this method in order to make such cases more discoverable.

Fixes #54497

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]
I do not see any tests that would manipulate with window size or would rely on a specific view, so setting it globally for all sounds like a good idea.

**Comment by oroztocil** [comment]
> I do not see any tests that would manipulate with window size or would rely on a specific view, so setting it globally for all sounds like a good idea.

There are few in `src/Components/test/E2ETest/Tests/ComponentRenderingTestBase.cs` - the one's that I updated to use the new extension method. However, if I understand it correctly, there would be no problem to have a default window size explicitly set because these tests will override the size (just as they do now). So the question is if there are some tests that implicitly rely on no value being set by default.

File: src/Components/test/E2ETest/Tests/StandaloneAppTest.cs [hunk 1]
```diff
@@ -44,6 +44,12 @@ public void NavMenuHighlightsCurrentLocation()
         var activeNavLinksSelector = By.CssSelector(".sidebar a.active");
         var mainHeaderSelector = By.TagName("h1");
 
+        // The sidebar is hidden if the screen is too narrow.
+        // Without setting the window size explicitly, visibility-sensitive properties
+        // such as IWebElement.Text can return empty strings, causing assertions to fail.
+        // In particular, this happens in the headless mode (used when running without debugger).
+        Browser.SetWindowSize(1920, 1080);
```
Comment (akoeplinger) [inline src/Components/test/E2ETest/Tests/StandaloneAppTest.cs]: I assume this doesn't fail if the physical screen size is lower than this right?

**Review by akoeplinger — APPROVED** [review]

File: src/Components/test/E2ETest/Tests/StandaloneAppTest.cs (hunk 1 above)
Comment (oroztocil) [reply src/Components/test/E2ETest/Tests/StandaloneAppTest.cs]: Based on docs and empirical testing:

- In GUI mode the size is clamped so that the window fits into the screen.
- In headless mode the window size is set to whatever is specified and the rest of the test executes fine. (I tried 10000x10000 and had no issues.)

**Review by javiercn — APPROVED** [review]

**Comment by oroztocil** [comment]
We also decided to add a mechanism for resetting the window size between individual tests to prevent unexpected dependencies between tests in the future.
