### PR TITLE
Fix Complete in Message Bodies

### LINKED ISSUE #9600: Calling HttpContext.Request.BodyReader.Complete causes an exception
In ASP.NET Core 3.0 Preview 4 calling `HttpContext.Request.BodyReader.Complete()` eventually triggers an exception with the following call stack:

```
Http1ContentLengthMessageBody.ThrowIfCompleted() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1ContentLengthMessageBody.TryRead() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1MessageBody.OnConsumeAsync() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1ContentLengthMessageBody.ConsumeAsync() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
async HttpProtocol.ProcessRequests<Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context>() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
...
```

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/aspnet/AspNetCore/issues/9600
This will still cause an application exception if you set one.

### CODE REVIEW

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 1]
```diff
@@ -1236,7 +1236,7 @@ public async Task OnWriterCompletedForNoContentLengthNoop()
         }
 
         [Fact]
-        public async Task CompleteForContentLengthDoesNotCompleteConnectionPipeMakesReadReturnThrow()
+        public async Task CompleteForContentLengthDoesNotCompleteConnectionPipeMakes()
```
Comment (Tratcher) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]:
```suggestion
        public async Task CompleteForContentLengthDoesNotCompleteConnectionPipe()
```

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs [hunk 2]
```diff
@@ -57,6 +57,36 @@ public async Task StreamsAreNotPersistedAcrossRequests()
             }
         }
 
+        [Fact]
+        public async Task Test()
```
Comment (Tratcher) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: ?

Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: It's been a long day.

**Comment by davidfowl** [comment]
Part of me thinks it’s fine to throw when a user does ReadAsync after completing but you want to avoid throwing inside of kestrel on drain. We also probably won’t encourage people to complete anyways so maybe it’s not a big deal

**Comment by jkotalik** [comment]
🆙 📅

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs [hunk 3]
```diff
@@ -57,6 +58,37 @@ public async Task StreamsAreNotPersistedAcrossRequests()
...
         }
 
+        [Fact]
+        public async Task CallingCompleteDoesNotLogGreaterThanInfo()
+        {
+            var testContext = new TestServiceContext(LoggerFactory);
+
+            await using (var server = new TestServer(async context =>
+            {
+                // This will hang if 0 content length is not assumed by the server
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: What will hang when?

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 4]
```diff
@@ -1255,14 +1255,12 @@ public async Task CompleteForContentLengthDoesNotCompleteConnectionPipeMakesRead
                 reader.Complete();
                 reader.AdvanceTo(readResult.Buffer.End);
 
-                Assert.Throws<InvalidOperationException>(() => reader.TryRead(out readResult));
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: Why remove this line? Shouldn't we be verifying that read doesn't trhow after calling Complete()?

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 5]
```diff
@@ -1281,14 +1279,12 @@ public async Task CompleteForChunkedDoesNotCompleteConnectionPipeMakesReadThrow(
 
                 reader.Complete();
 
-                Assert.Throws<InvalidOperationException>(() => reader.TryRead(out readResult));
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: ditto

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 6]
```diff
@@ -1307,13 +1303,10 @@ public async Task CompleteForUpgradeDoesNotCompleteConnectionPipeMakesReadThrow(
...
```
Comment (halter73) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: ditto

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs (hunk 4 above)
Comment (jkotalik) [reply src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: Yeah probably, but ¯\\_(ツ)_/¯

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs (hunk 3 above)
Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: This comment was a bunch of spaghetti. Let me rethink this.

Comment (halter73) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: That said, I don't think you need to post a body in this test. Kestrel will create a log warning the app didn't consume the request body. Today, I think it is info-level, but that could change. If it started to be logged as a warning, this test would start failing.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs [hunk 7]
```diff
@@ -57,6 +58,37 @@ public async Task StreamsAreNotPersistedAcrossRequests()
...
+            {
+                context.Request.BodyReader.Complete();
+                await Task.CompletedTask;
+            }, testContext))
+            {
+                using (var connection = server.CreateConnection())
+                {
+                    await connection.Send(
+                        "POST / HTTP/1.0",
+                        "Content-Length: 11",
```
Comment (halter73) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: Just send a GET so any logs about not consuming the request body don't interfere with this test.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs (hunk 3 above)
Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: I think I do here because I'm verifying the behavior of ConsumeAsync which I believe requires a request body to be there.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs (hunk 7 above)
Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: I do need to send a post. Why is that log not consistent? Shouldn't it either always or never be logged? 

If it isn't consistent, I can change the max loglevel to warning.

Comment (halter73) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: I'm talking specifically about the RequestBodyNotEntirelyRead info-level log. I'm just pointing out that could be made higher severity later. That said, it now occurs to me that this test might be verifying the RequestBodyNotEntirelyRead log itself isn't higher than info level. Is that the case?

Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: The goal of this test is to make sure that an exception wasn't thrown from ConsumeAsync if the pipe is completed. I'd be fine with this test breaking if we increase the severity later.

Comment (halter73) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs]: I don't think I read this correctly the first time. I think this is OK.

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 8]
```diff
@@ -1261,6 +1285,31 @@ public async Task CompleteForContentLengthDoesNotCompleteConnectionPipeMakesRead
             }
         }
 
+
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: nit: Extra space.

File: src/Servers/Kestrel/Core/test/MessageBodyTests.cs [hunk 9]
```diff
@@ -1235,6 +1235,30 @@ public async Task OnWriterCompletedForNoContentLengthNoop()
...
+                input.Add("a");
+
+                Assert.True(reader.TryRead(out var readResult));
+
+                Assert.False(readResult.IsCompleted);
+
+                input.Add("asdf");
+
+                reader.Complete();
+                reader.AdvanceTo(readResult.Buffer.End);
```
Comment (davidfowl) [inline src/Servers/Kestrel/Core/test/MessageBodyTests.cs]: AdvanceTo after complete is weird.

**Comment by davidfowl** [comment]
Can you add a functional test as well? In memory is fine.

**Comment by jkotalik** [comment]
I had one before that I forced pushed over... I'll revive it shortly.

File: src/Servers/Kestrel/test/InMemory.FunctionalTests/ChunkedRequestTests.cs [hunk 10]
```diff
@@ -991,6 +992,62 @@ public async Task ChunkedRequestCallCompleteThrowsExceptionOnRead()
...
+            {
+                var request = httpContext.Request;
+
+                // This read may receive all data, but what we care about
+                // is that ConsumeAsync is called and doesn't error. Calling
+                // TryRead before would always fail.
+                var readResult = await request.BodyReader.ReadAsync();
+                request.BodyReader.AdvanceTo(readResult.Buffer.End);
+
+                httpContext.Request.BodyReader.Complete();
```
Comment (davidfowl) [inline src/Servers/Kestrel/test/InMemory.FunctionalTests/ChunkedRequestTests.cs]: nit: Use the request local?

Comment (jkotalik) [reply src/Servers/Kestrel/test/InMemory.FunctionalTests/ChunkedRequestTests.cs]:
```suggestion
                request.BodyReader.Complete();
```

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs [hunk 11]
```diff
@@ -78,5 +77,15 @@ public override Task StopAsync()
         {
             return Task.CompletedTask;
         }
+
+        public override bool TryReadInternal(out ReadResult readResult)
```
Comment (halter73) [inline src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs]: It might be clearer to call this unchecked instead of internal

**Review by halter73 — APPROVED** [review]

File: src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs (hunk 11 above)
Comment (jkotalik) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs]: I've seen the Internal pattern with a higher frequency. If you feel strongly about it I can change it, but I personally prefer Internal.

Comment (halter73) [reply src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs]: I don't feel strongly at all. I agree Internal usually implies no validation, so I'm fine as is.
