### PR TITLE
fix: ignore proxy for local address supports comma separated values

### LINKED ISSUE #52475: Blazor Debugger does not support comma separated NO_PROXY value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Similar to #22012 - I'm unable to debug Blazor applications. 

Changing `NO_PROXY` to `localhost` fixes the issue as a temporary workaround however I already had `NO_PROXY` values set that I needed for other applications (such as Git).

My `NO_PROXY` was previously set to: `.example.com, .sub.example.com`. 

Adding localhost as one of these values: `localhost,.example.com,.sub.example.com` does not seem to get picked up by Visual Studio as I still get the error:

```
Invalid value for NO_PROXY: localhost,.example.com,.sub.example.com (Expected values: "localhost" or "127.0.0.1")
```

### Expected Behavior

Expected Visual Studio to see that `localhost` was already one of the `NO_PROXY` values rather than requiring an exclusive value of `localhost` on its own. 

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

Both Visual Studio 17.8.2 & 17.9.0 Preview 1.1

### PR DESCRIPTION
**Pull request by RyanGaudion**
# Make Blazor Debugger noproxy more flexible to allow for more complex scenarios.

Summary of the changes (Less than 80 chars): Allows comma based NO_PROXY values by WebAssembly Debugger

## Description

Splits the NO_PROXY value to support support comma separated lists of NO_PROXY. Continues to work with previously accepted NO_PROXY values.

Fixes #52475

### CODE REVIEW

File: src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs [hunk 1]
```diff
@@ -43,7 +43,8 @@ private static string GetIgnoreProxyForLocalAddress()
         var noProxyEnvVar = Environment.GetEnvironmentVariable("NO_PROXY");
         if (noProxyEnvVar is not null)
         {
-            if (noProxyEnvVar.Equals("localhost") || noProxyEnvVar.Equals("127.0.0.1"))
+            var noProxyEnvVarValues = noProxyEnvVar.Split(",", StringSplitOptions.None);
+            if (noProxyEnvVarValues.Any(noProxyValue => noProxyValue.Equals("localhost") || noProxyValue.Equals("127.0.0.1")))
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs:47]: Would it be worth using `StringSplitOptions.TrimEntries` so it's also allowed to have spaces in the string?

I notice your original example was `.example.com, .sub.example.com` but without trimming it wouldn't work to specify `.example.com, .sub.example.com, localhost`.

**Review by SteveSandersonMS — APPROVED** [review]
Looks great - thanks!
