### PR TITLE
Fixed Router renders component twice

### LINKED ISSUE #47058: [Blazor] Router seems to be rendering twice
From what I can tell, when there is no handler passed to the router, it will render the component twice:
https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/Routing/Router.cs#L256-L259

Probably there should be an early return after the highlighted `Refresh`

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fixed Router renders component twice

Fixes #47058

### CODE REVIEW

File: src/Components/Components/src/Routing/Router.cs [hunk 1]
```diff
@@ -136,8 +136,10 @@ public async Task SetParametersAsync(ParameterView parameters)
             _onNavigateCalled = true;
             await RunOnNavigateAsync(NavigationManager.ToBaseRelativePath(_locationAbsolute), isNavigationIntercepted: false);
         }
-
-        Refresh(isNavigationIntercepted: false);
+        else
+        {
+            Refresh(isNavigationIntercepted: false);
+        }
```
Comment (javiercn) [inline src/Components/Components/src/Routing/Router.cs:142]: Could you write a test for it?

Comment (surayya-MS) [reply src/Components/Components/src/Routing/Router.cs:142]: I think our E2E Router tests could be enough. They will check whether `Router` renders the appropriate component. 
Or do you mean a test for checking that the component renders just once?

Comment (javiercn) [reply src/Components/Components/src/Routing/Router.cs:142]: We want to have a test that ensures we only render once. It's likely possible to author one as a unit test, rather than splurge for an E2E test.

Comment (javiercn) [reply src/Components/Components/src/Routing/Router.cs:142]: If we notice something in code like this, and we didn't catch it before, it means that there is a gap in our testing, so we want to 1) put a test in place to ensure the right behavior (before and after) and 2) prevent the behavior from regressing in the future

Comment (surayya-MS) [reply src/Components/Components/src/Routing/Router.cs:142]: Sorry I removed my previous comment. I just checked unit tests and agreed that we need a test for that and removed my question. and you were already typing the reply. 

Thanks!

**Review by javiercn — APPROVED** [review]
