### PR TITLE
Fix NativeAOT with minimal actions

### LINKED ISSUE #34875: Support Minimal APIs with NativeAOT
Today we use expression tree compilation to create the thunks for minimal APIs invocations it fails to work when used with NativeAOT compilation. ~We need to provide an alterative implementation that doesn't use dynamic code generation in order to make this work. The options are source generators or a reflection based fallback.~

Turns out expression tree compilation is interpreted with NativeAOT and that's a fine fallback (though not the most optimized for high throughput). Where it does fail is the TryParse reflection:

```
Unhandled Exception: System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.Exception: static bool System.Enum.TryParse<TEnum>(string? value, out TEnum result) not found.
   at Microsoft.AspNetCore.Http.TryParseMethodCache.GetEnumTryParseMethod() + 0x2b9
   at Microsoft.AspNetCore.Http.TryParseMethodCache..cctor() + 0x20
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27e
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x1b
   at Microsoft.AspNetCore.Http.RequestDelegateFactory..cctor() + 0xe3d
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27e
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x1b
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Create(Delegate, RequestDelegateFactoryOptions) + 0xc2
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder, RoutePattern, Delegate) + 0x253
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.MapMethods(IEndpointRouteBuilder, String, IEnumerable`1, Delegate) + 0xa1
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.MapGet(IEndpointRouteBuilder, String, Delegate) + 0x42
   at Program.<Main>$(String[]) + 0xe1
   at WebApplication520!<BaseAddress>+0x10b0897
   at WebApplication520!<BaseAddress>+0x10b0920
```

### PR DESCRIPTION
**Pull request by davidfowl**
- Generic methods for value types need to be visible at compile time so that the AOT compiler can generate code for the right instantiations (closed generic types). Since Enum.TryParse\<T\> is used purely via reflection is gets removed from the final AOT binary. This causes our logic that looks for Enum.TryParse\<T\> to fail. Instead, we call back to the non-generic overload which doesn't get trimmed and can at runtime lookup the metadata for the enum type in order to allow parsing.
- Made TryParseMethodCache creatable so it could be tested more easily.
- Added tests

Fixes #34875 

PS: To get a better sense of what the exception looks like for not having the code for a specific generic instantiation:

```
Unhandled Exception: EETypeRva:0x01CA62A8(System.Reflection.MissingRuntimeArtifactException): MakeGenericMethod() cannot create this generic method instantiation because no code was generated for it: 'System.Enum.TryParse<Choice>(System.String,System.Boolean,out Choice&)'.
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x1dc
   at System.Reflection.Runtime.MethodInfos.RuntimeConstructedGenericMethodInfo.get_UncachedMethodInvoker() + 0x3b
   at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.get_MethodInvoker() + 0x1c0
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x3e9
   at Microsoft.AspNetCore.Http.TryParseMethodCache.<FindTryParseMethod>g__Finder|4_0(Type) + 0xfd
   at WebApplication520!<BaseAddress>+0x104bc58
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0x124
   at Microsoft.AspNetCore.Http.TryParseMethodCache.FindTryParseMethod(Type) + 0x56
   at Microsoft.AspNetCore.Http.TryParseMethodCache.HasTryParseMethod(ParameterInfo) + 0x87
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArgument(ParameterInfo, RequestDelegateFactory.FactoryContext) + 0xa31
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArguments(ParameterInfo[], RequestDelegateFactory.FactoryContext) + 0xd6
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateTargetableRequestDelegate(MethodInfo, RequestDelegateFactoryOptions, Expression) + 0x1bc
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Create(Delegate, RequestDelegateFactoryOptions) + 0x188
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder, RoutePattern, Delegate) + 0x253
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.MapMethods(IEndpointRouteBuilder, String, IEnumerable`1, Delegate) + 0xa1
   at Microsoft.AspNetCore.Builder.MinimalActionEndpointRouteBuilderExtensions.MapGet(IEndpointRouteBuilder, String, Delegate) + 0x42
   at Program.<Main>$(String[]) + 0x703
   at WebApplication520!<BaseAddress>+0x10ad997
   at WebApplication520!<BaseAddress>+0x10ada20
```

Also, to see how this all of this expression compilation works with native AOT, the expression tree interpreter is used:

```C#
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/", () => Environment.StackTrace);

app.Run();
```

```
   at System.Environment.get_StackTrace() + 0x32
   at Program.<>c.<<Main>$>b__0_0() + 0x19
   at WebApplication520!<BaseAddress>+0x13d245e
   at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x1ac
   at Internal.Runtime.Augments.RuntimeAugments.CallDynamicInvokeMethod(Object, IntPtr, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean) + 0x68
   at Internal.Reflection.Execution.MethodInvokers.InstanceMethodInvoker.Invoke(Object, Object[], BinderBundle, Boolean) + 0x108
   at Internal.Reflection.Core.Execution.MethodInvoker.Invoke(Object, Object[], Binder, BindingFlags, CultureInfo) + 0x83
   at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) + 0x86
   at System.Reflection.MethodBase.Invoke(Object, Object[]) + 0x4d
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame) + 0x170
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame) + 0x69
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[]) + 0xac
   at WebApplication520!<BaseAddress>+0x1084590
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass33_0.<Create>b__0(HttpContext) + 0x62
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext) + 0x1f4
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext) + 0xf3
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext) + 0x16a
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext) + 0x8d
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(HostingApplication.Context) + 0x53
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__223`1.MoveNext() + 0x497
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object) + 0x6a
   at WebApplication520!<BaseAddress>+0x10a353a
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object) + 0x73
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread) + 0x124
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread) + 0x1f
   at System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object, Thread) + 0x52
   at System.Threading.ThreadPoolWorkQueue.Dispatch() + 0x177
   at System.Threading.ThreadPool.DispatchCallback(IntPtr, IntPtr, IntPtr) + 0x6e
```

### CODE REVIEW

File: src/Shared/TryParseMethodCache.cs [hunk 1]
```diff
@@ -87,32 +115,59 @@ public static bool HasTryParseMethod(ParameterInfo parameter)
...
+                    tryParseParameters[2].IsOut)
+                {
+                    nonGenericCandidate = method;
+                }
+            }
+
+            if (genericCandidate is null && nonGenericCandidate is null)
+            {
+                Debug.Fail("No suitable System.Enum.TryParse method not found.");
+                throw new Exception("No suitable System.Enum.TryParse method not found.");
```
Comment (martincostello) [inline src/Shared/TryParseMethodCache.cs:162]: Nit: double-negatives.

```suggestion
                Debug.Fail("No suitable System.Enum.TryParse method found.");
                throw new Exception("No suitable System.Enum.TryParse method found.");
```

Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs]: Good catch!

File: src/Shared/TryParseMethodCache.cs [hunk 2]
```diff
@@ -15,35 +15,63 @@
...
+        private readonly ConcurrentDictionary<Type, Func<Expression, Expression>?> _methodCallCache = new();
 
-        public static bool HasTryParseMethod(ParameterInfo parameter)
+        internal readonly ParameterExpression TempSourceStringExpr = Expression.Variable(typeof(string), "tempSourceString");
+
+        public TryParseMethodCache() : this(preferNonGenericEnumParseOverload: false)
+        {
+        }
+
+        public TryParseMethodCache(bool preferNonGenericEnumParseOverload)
```
Comment (pranavkm) [inline src/Shared/TryParseMethodCache.cs:31]: Is this only true in test code? If so, could you make a note of this? I imagine you wouldn't intentionally want this to be true.

File: src/Shared/TryParseMethodCache.cs [hunk 3]
```diff
@@ -87,32 +115,59 @@ public static bool HasTryParseMethod(ParameterInfo parameter)
...
+                    tryParseParameters[2].IsOut)
+                {
+                    nonGenericCandidate = method;
+                }
+            }
+
+            if (genericCandidate is null && nonGenericCandidate is null)
+            {
+                Debug.Fail("No suitable System.Enum.TryParse method found.");
+                throw new Exception("No suitable System.Enum.TryParse method found.");
```
Comment (pranavkm) [inline src/Shared/TryParseMethodCache.cs:162]:
```suggestion
                throw new MissingMethodException("No suitable System.Enum.TryParse method found.");
```

File: src/Shared/TryParseMethodCache.cs [hunk 4]
```diff
@@ -87,32 +115,59 @@ public static bool HasTryParseMethod(ParameterInfo parameter)
...
+            return _methodCallCache.GetOrAdd(type, Finder);
         }
 
-        private static MethodInfo GetEnumTryParseMethod()
+        private static MethodInfo GetEnumTryParseMethod(bool preferNonGenericEnumParseOverload)
         {
             var staticEnumMethods = typeof(Enum).GetMethods(BindingFlags.Public | BindingFlags.Static);
 
+            // With NativeAOT, if there's no static usage of Enum.TryParse<T>, it will be removed
+            // we fallback to the non-generic version if that is the case
```
Comment (pranavkm) [inline src/Shared/TryParseMethodCache.cs:126]: Is there a reason the non-generic one does not get trimmed?

**Review by pranavkm — APPROVED** [review]

File: src/Shared/TryParseMethodCache.cs (hunk 4 above)
Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs:126]: I assume it's because something else uses it. I have no idea what.

File: src/Shared/TryParseMethodCache.cs [hunk 5]
```diff
@@ -15,35 +15,63 @@
 
 namespace Microsoft.AspNetCore.Http
 {
-    internal static class TryParseMethodCache
+    internal class TryParseMethodCache
```
Comment (davidfowl) [inline src/Shared/TryParseMethodCache.cs:18]:
```suggestion
    internal sealed class TryParseMethodCache
```

File: src/Shared/TryParseMethodCache.cs (hunk 2 above)
Comment (davidfowl) [inline src/Shared/TryParseMethodCache.cs:31]:
```suggestion
        // This is for testing
        public TryParseMethodCache(bool preferNonGenericEnumParseOverload)
```

File: src/Shared/TryParseMethodCache.cs (hunk 4 above)
Comment (pranavkm) [reply src/Shared/TryParseMethodCache.cs:127]: Should we force it to be kept (e.g using `DynamicDependency`)

Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs:127]: I'm not sure if it's needed TBH, I *think* `typeof(Enum).GetMethods(BindingFlags.Public | BindingFlags.Static)` is visible to the linker but I'd need to make sure.

cc @MichalStrehovsky @eerhardt

Comment (eerhardt) [reply src/Shared/TryParseMethodCache.cs:127]: This is surprising to me. 

```C#
var staticEnumMethods = typeof(Enum).GetMethods(BindingFlags.Public | BindingFlags.Static);
```

That should "mark" all public static methods on `Enum`, and the AOT compiler shouldn't trim any of them.

Is it possible to build up the `GetMethod` query correctly so you only select the one method you are looking for?

Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs:127]: We still can't use the generic version of the other reasons mentioned in the PR.

Comment (jkotas) [reply src/Shared/TryParseMethodCache.cs:127]: > typeof(Enum).GetMethods(BindingFlags.Public | BindingFlags.Static) is visible to the linker but I'd need to make sure.

Yes. It is a bug in NativeAOT: https://github.com/dotnet/runtimelab/issues/1402

Once this bug gets fixed, this will be broken again.

FWIW, I think fallbacks like this are wrong way to fix trimming and AOT friendliness issues.

Comment (MichalStrehovsky) [reply src/Shared/TryParseMethodCache.cs:127]: I didn't realize this is going to return `TryParse<T>` if that method got reflection-rooted through other means. The fact that it's not just rooted from `GetMethod` is kind of a bug but it only happens because the compiler figured there's not much it can do there - by default the AOT compiler will try to enable metadata for the method and generate a shared instantiation (over reference types), but the constraints on `TryParse<T>` rule out reference types. Right now, because it can't make a usable method body, it will not generate the metadata either. But we can fix it to create the metadata.

Yes, this is likely going to fail at `MakeGenericMethod` later.

Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs:127]: > Once this bug gets fixed, this will be broken again.

Thanks. I'll look into that.

> FWIW, I think fallbacks like this are wrong way to fix trimming and AOT friendliness issues.

It just needs to work well enough (or barely work) to enable people to try it out and give feedback. Seems like we need something a bit more creative here (like a check for IsDynamicCodeCompiled maybe).

Comment (MichalStrehovsky) [reply src/Shared/TryParseMethodCache.cs:127]: IsDynamicCodeSupported is what I did in the DataContractSerializer as a temporary workaround while we figure things out: https://github.com/dotnet/runtimelab/pull/692/files#diff-5c36d3b2cc664a8e51d53ac77390c98eca051ca63b13443233afc38ccee5e65fR60-R64

Comment (davidfowl) [reply src/Shared/TryParseMethodCache.cs:127]: Yep, this is what I'll do. FWIW I have a pretty good handle on most of the AOT friendly problems that will plague ASP.NET Core (like JSON 😄 ) and have prototypes for how to tackle most of them.
