### PR TITLE
Empty "http.route" tags should be set to "/"

### LINKED ISSUE #62431: HostingMetrics: empty "http.route" tags shouldn't be present
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

`Microsoft.AspNetCore.Hosting` create a metric called `http.server.request.duration` documented here: <https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/built-in>

One the available labels is `http.route` which is optional.

**Issue:**

`http.route` can be populated with various string such as:
- path/to/my/route/{id}
- index
- api/controller/route
- \<empty string\>
- ...

And it can also be missing.

However, based on the [OpenMetrics spec](https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md#label) used by Prometheus, empty label values should be treated as if the label was not present.
That means when exporting data to prometheus, we currently create two different metrics (one for http_route= \<empty string\>, one for the missing http_route), which create a "duplicate sample for timestamp" error when importing data.

**Fix:**

To fix this issue, I changed the metric labelling so an empty route doesn't create the label, as if the variable was null.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

9.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Elanis**
# HostingMetrics: empty "http.route" tags shouldn't be present

When pushing metrics to third-party softwares such as prometheus. Having empty-valued labels will cause issues

## Description

`Microsoft.AspNetCore.Hosting` create a metric called `http.server.request.duration` documented here: <https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/built-in>

One the available labels is `http.route` which is optional.

**Issue:**

`http.route` can be populated with various string such as:
- path/to/my/route/{id}
- index
- api/controller/route
- \<empty string\>
- ...

And it can also be missing.

However, based on the [OpenMetrics spec](https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md#label) used by Prometheus, empty label values should be treated as if the label was not present.
That means when exporting data to prometheus, we currently create two different metrics (one for http_route= \<empty string\>, one for the missing http_route), which create a "duplicate sample for timestamp" error when importing data.

**Fix:**

To fix this issue, I changed the metric labelling so an empty route doesn't create the label, as if the variable was null.

Fixes #62431

### CODE REVIEW

**Comment by Elanis** [comment]
@dotnet-policy-service agree

**Comment by Elanis** [comment]
Feel free to ping me whenever someone in the team have time to review this :)
Also, I don't know what's the usual way to do things here since it's my first contribution, so feel free to guide me.

And finally, if this feature can be backported in .NET 9 I would be extremely happy as it's producing lots of erroneous data in my monitoring stack 😅 (thus why I noticed this)

**Comment by Elanis** [comment]
(This PR is awaiting further discussions in #62431 )

**Comment by Elanis** [comment]
Rebased on latest main, and applied changed decided in #62431

File: src/Hosting/Hosting/src/Internal/HostingMetrics.cs [hunk 1]
```diff
@@ -66,10 +67,12 @@ public void RequestEnd(string protocol, string scheme, string method, string? ro
 
             // Add information gathered during request.
             tags.Add("http.response.status_code", GetBoxedStatusCode(statusCode));
-            if (route != null)
+            var httpRoute = route;
+            if (string.IsNullOrEmpty(httpRoute))
```
Comment (sebastienros) [inline src/Hosting/Hosting/src/Internal/HostingMetrics.cs]: Should a `null` route be converted or just the empty string?

Comment (Elanis) [reply src/Hosting/Hosting/src/Internal/HostingMetrics.cs]: I was wondering the same thing when re-reading my code. I was about to ask

Comment (sebastienros) [reply src/Hosting/Hosting/src/Internal/HostingMetrics.cs]: Something like 

```c#
if (route != null)
{
  tags.Add("http.route", route == string.Empty ? "/" : route)
}
```

Comment (Elanis) [reply src/Hosting/Hosting/src/Internal/HostingMetrics.cs]: I think the null value will cause the same issues. But semantically, it's not the same as an empty route, I suppose.

Comment (Elanis) [reply src/Hosting/Hosting/src/Internal/HostingMetrics.cs]: Let's just fix the empty route bug as for now and if another bug with null happens, I'll open a dedicated issue/PR. I don't want to cause side-effects

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
@Elanis I rebased and updated the routing metric to be consistent.

**Comment by Elanis** [comment]
Thanks!

**Review by BrennanConroy — APPROVED** [review]
