### PR TITLE
Framework.Tests: support running against Linux build artifacts.

### LINKED ISSUE #46524: DOTNET_ROOT while running tests
`DOTNET_ROOT` is used to resolve ASP.NET Core folders in two places:

https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/src/Framework/test/TargetingPackTests.cs#L28-L32

https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/src/Framework/test/SharedFxTests.cs#L27-L31

What is `DOTNET_ROOT` supposed to be set to?
Can it be the root of the the dotnet installation that is used for the build?
Or should it be set to something that contains the ASP.NET Core bits that got build? To what?

I've currently set it to the first (`<repo>/.dotnet`), and I get test failures for:
```
Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsExpectedFiles
Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsListedAssemblies
Microsoft.AspNetCore.SharedFxTests.RuntimeListContainsCorrectEntries
Microsoft.AspNetCore.TargetingPackTests.PlatformManifestListsAllFiles
```
which look like:
```
Xunit.Sdk.EmptyException: Assert.Empty() Failure\nExpected: <empty>\nActual:   [\"System.Diagnostics.EventLog.Messages\"]
at Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsExpectedFiles() in /_/src/Framework/test/SharedFxTests.cs:line 81
```

My build uses these two commands:
```
eng/build.sh --ci --arch x64 -c Release --restore --build --pack
eng/build.sh --ci --arch x64 -c Release --test
```

@dougbu am I using the proper value for `DOTNET_ROOT`?

cc @omajid

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/aspnetcore/issues/46524.

@dougbu ptal.

These are the changes that make the tests pass for a local build.

Can we make it so that the aspnetcore CI when running on X will consume the binaries built for X?
Or will CI keep on running these tests against Windows build artifacts only?

In what files should I make the changes for `HELIX_WORKITEM_ROOT`?

cc @omajid

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @tmds.
@wtgodbe can you please review this? Thanks!

File: src/Framework/test/TestData.cs [hunk 1]
```diff
@@ -154,6 +155,12 @@ static TestData()
                 "System.Threading.RateLimiting",
             };
 
+        // System.Diagnostics.EventLog.Messages is only present in the Windows build.
+        if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
+        {
+            ListedSharedFxAssemblies.Remove("System.Diagnostics.EventLog.Messages");
```
Comment (wtgodbe) [inline src/Framework/test/TestData.cs:161]: This won't work on Helix since we always run tests against the windows assets there (we don't intend to change that) - you could add `!SkipOnHelixAttribute.OnHelix()` to this condition to account for that

File: src/Framework/test/Microsoft.AspNetCore.App.UnitTests.csproj [hunk 2]
```diff
@@ -18,15 +18,15 @@
...
     <!--
       Special-case System.Diagnostics.EventLog.Messages.dll because that assembly name does _not_ match a
       package. Can't mention it in @(ExternalAspNetCoreAppReference) or underlying
       @(_TransitiveExternalAspNetCoreAppReference) without thoroughly confusing eng/targets/ResolveReferences.targets.
     -->
-    <_ExpectedSharedFrameworkBinaries Include="@(_SharedFrameworkBinariesFromRepo);
-        @(ExternalAspNetCoreAppReference);
-        @(_TransitiveExternalAspNetCoreAppReference);
-        System.Diagnostics.EventLog.Messages" />
+    <_ExpectedSharedFrameworkBinaries Condition="'$(TargetOsName)' == 'win'" Include="System.Diagnostics.EventLog.Messages" />
```
Comment (wtgodbe) [inline src/Framework/test/Microsoft.AspNetCore.App.UnitTests.csproj:29]: I'm not crazy about this since right now we're able to calculate the expected contents of our SharedFx/Targeting Pack without hard coding anything - @dougbu any ideas on how to get around that?

**Review by wtgodbe — CHANGES_REQUESTED** [review]
Looks good to me other than the change to TestData, which won't work in Helix

**Comment by wtgodbe** [comment]
> In what files should I make the changes for HELIX_WORKITEM_ROOT?

What changes do you mean?

File: src/Framework/test/Microsoft.AspNetCore.App.UnitTests.csproj (hunk 2 above)
Comment (tmds) [inline src/Framework/test/Microsoft.AspNetCore.App.UnitTests.csproj:29]: Is there some Helix check needed here too?

File: src/Framework/test/TestData.cs (hunk 1 above)
Comment (tmds) [reply src/Framework/test/TestData.cs:161]: I'll make the change.
I'm curious, is there a reason you only run these tests against the Windows assets?

Comment (wtgodbe) [reply src/Framework/test/TestData.cs:163]: We try to run every test we can on Helix because it saves resources, and helix works by building assets once & sending them off to multiple test queues. So the answer is essentially "because we can" - but, I might be swayed by an argument that these tests should _not_ be run on Helix because they're testing if the assets were _produced_ correctly on the target OS, not that they _run_ correctly there. @dougbu what do you think?

Comment (wtgodbe) [reply src/Framework/test/TestData.cs:163]: My point is that these tests check "Was the sharedFx built correctly?". Since we run them in helix, we're only testing "Was the sharedFx built on windows built correctly?" - we don't run this test against a SharedFx built on Linux or Mac (in CI).

Comment (wtgodbe) [reply src/Framework/test/TestData.cs:163]: > The condition now looks like it'll work fine when run on Helix agents. Am I missing something❔

The tests failed on non-windows on helix in the first iteration because of this test, because of this condition (they ran on non-windows, but tested against a SharedFx built on windows)

File: src/Framework/test/SharedFxTests.cs [hunk 3]
```diff
@@ -324,10 +324,8 @@ public void RuntimeListContainsCorrectPaths()
         var packageFolder = SkipOnHelixAttribute.OnHelix() ?
             Environment.GetEnvironmentVariable("HELIX_WORKITEM_ROOT") :
             TestData.GetPackagesFolder();
-        var sharedFxPath = Path.Combine(
-            packageFolder,
-            "Microsoft.AspNetCore.App.Runtime.win-x64." + TestData.GetSharedFxVersion() + ".nupkg");
-        AssertEx.FileExists(sharedFxPath);
+        var sharedFxPath = Directory.GetFiles(packageFolder, "Microsoft.AspNetCore.App.Runtime.*-x64." + TestData.GetSharedFxVersion() + ".nupkg").FirstOrDefault();
```
[the remark this answers is not in the document]
Comment (tmds) [reply src/Framework/test/SharedFxTests.cs]: Oops, this should match any architecture. I've fixed it.

File: src/Framework/test/TestData.cs (hunk 1 above)
Comment (dougbu) [reply src/Framework/test/TestData.cs:163]: > My point is that these tests check "Was the sharedFx built correctly?". Since we run them in helix, we're only testing "Was the sharedFx built on windows built correctly?" - we don't run this test against a SharedFx built on Linux or Mac (in CI).

One way to add such testing would be to move the tests off Helix. Unfortunately, that goes against our preference to test _everything_ we can in Helix and avoid duplicate testing.

This also pretty normal because _all_ of our assemblies are built on Windows and tested on the Helix agents. The main unusual thing is that we actually ship shared Fx packages built on non-Windows agents.

Until and unless we centralize `crossgen2` execution to the Windows build, let's ignore this. Thoughts❔

Comment (dougbu) [reply src/Framework/test/TestData.cs:163]: > > The condition now looks like it'll work fine when run on Helix agents. Am I missing something❔
> 
> The tests failed on non-windows on helix in the first iteration because of this test, because of this condition (they ran on non-windows, but tested against a SharedFx built on windows)

Are we 🆗 from your perspective here now❔

Comment (wtgodbe) [reply src/Framework/test/TestData.cs:163]: > One way to add such testing would be to move the tests off Helix. Unfortunately, that goes against our preference to test everything we can in Helix and avoid duplicate testing. This also pretty normal because all of our assemblies are built on Windows and tested on the Helix agents. The main unusual thing is that we actually ship shared Fx packages built on non-Windows agents.

There are some exceptions to that rule though, and I think this should be one of them - these tests are different from others in that they're not testing "do these bits run on this platform", they're testing "Did we produce the correct set of bits for this platform". As it is today, there's no point in running this test on the Windows, Linux, and MacOS queues - all three are testing "Did we build the correct set of bits for windows", and none are testing "Did we build the correct set of bits for Mac/Linux"

Comment (dougbu) [reply src/Framework/test/TestData.cs:163]: > There are some exceptions to that rule though, and I think this should be one of them

The exceptions are all **bugs** and I would prefer we don't pile on more technical debt. But I also don't disagree our tests of the shared Fx packages is a touch of tunnel vision.

My thought was also about urgency because we haven't hit significant platform-specific problems w/ the shared Fx packages (ignoring those that show up when building in the CI) more than a couple of times (if that). I also plan to try centralizing `crossgen2` sooner rather than later.

**Review by wtgodbe — APPROVED** [review]

File: src/Framework/test/TestData.cs (hunk 1 above)
Comment (wtgodbe) [reply src/Framework/test/TestData.cs:163]: I don't think we need to block this PR on it - I opened https://github.com/dotnet/aspnetcore/issues/46620 to track fixing it in the future.

**Comment by tmds** [comment]
CI is happy. @dougbu can you merge this please?
