### PR TITLE
Fix use of precedence in endpoint routing DFA

### LINKED ISSUE #16579: ASP.NET Core 3.0 catch-all route unexpected behavior
### Describe the bug
Recently i encounter some unexpected issue

I'm using ASP.NET Core 3.0 and i defined two routes in StartUp.cs

**StartUp.cs**
```
   app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });

        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=File}/{action=Index}/{filename}");
    });
```
**FileController.cs**
```
public class FileController : Controller
{
    public IActionResult Folder(string path)
    {
        return Ok(path);
    }

    public IActionResult Index(string filename)
    {
        return Ok(filename);
    }
}
```
request to file/folder/abc/abc i expected to match first route but the result was 404 not found

but if i changed order of route

```
   app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=File}/{action=Index}/{filename}");

        endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });
    });
```
It work!

### Expected behavior
My questing is why first version don't work if i defined `{controller=File}/folder/{*path}` on top

I thought it will check route table sequentially

### LINKED ISSUE #18677: Odd results mixing fully-tokenized attribute-route and wildcard-map within endpoint-routing
### Describe the bug

The presence of the attribute-route seems to clobber requests that should go through the separate wildcard-mapped middleware. This only seems to affect fully tokenized and path-separated attribute-routes (i.e. `{firstName}/{lastName}`, etc.). Something like `api/{firstName}/{lastName}` is not affected.

*My expectation using the sample below is that any request starting with `/middleware` would go through the middleware due to having a more-exact match based on available endpoints.*

### To Reproduce

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Patterns;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Threading.Tasks;

namespace SampleRouteConflict
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app
                .UseHttpsRedirection()
                .UseRouting()
                .UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();

                    var appBuilder = endpoints.CreateApplicationBuilder();
                    var pattern = RoutePatternFactory.Parse("/middleware");

                    var pipeline = appBuilder
                        .UsePathBase(pattern.RawText)
                        .UseMiddleware<TestRouteMiddleware>()
                        .Build();

                    endpoints.Map(pattern.RawText + "/{**_}", pipeline);
                });
        }
    }

    [ApiController]
    public class TestRouteController : ControllerBase
    {
        [HttpGet]
        [Route("{firstName}/{lastName}")]
        public IActionResult Index(string firstName, string lastName)
        {
            return Ok(new { firstName, lastName });
        }
    }

    public class TestRouteMiddleware
    {
        public TestRouteMiddleware(RequestDelegate next)
        { }

        public async Task Invoke(HttpContext context)
        {
            await context.Response.WriteAsync("got to the middleware");
        }
    }
}
```

#### Results

|Request|API Match|Middleware Match|404?|
|:-:|:-:|:-:|:-:|
|/middleware||X||
|/middleware/test|X|||
|/middleware/test1/test2|||X|
|/bill/boga|X|||

#### Results **removing `endpoints.MapControllers();`**

|Request|API Match|Middleware Match|404?|
|:-:|:-:|:-:|:-:|
|/middleware||X||
|/middleware/test||X||
|/middleware/test1/test2||X||
|/bill/boga|||X|

### Further technical details

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
```

### PR DESCRIPTION
**Pull request by rynowak**
Fixes: #18677
Fixes: #16579

This is a change to how sorting is use when building endpoint routing's graph of
nodes that is eventually transformed into the route table. There were
bugs in how this was done that made it incompatible in some niche
scenarios both with previous implementations and how we describe the
features in the abstract.

There are a wide array of cases that might have been impacted by this
bug because routing is a pattern language. Generally the bugs will involve a
catch-all, and some something that changes ordering of templates.

Issue #18677 has the simplest repro for this, the following templates
would not behave as expected:

```
a/{*b}
{a}/{b}
```

One would expect any URL Path starting with `/a` to match the first
route, but that's not what happens.

---

The root cause of this bug was an issue in how the algorithm used to be
build the DFA was designed. Specifically that it uses a BFS to build the
graph, and it uses an up-front one-time sort of endpoints in order to
drive that BFS.

The building of the graph has the expectation that at each level, we
will process **all** literal segments (`/a`) and then **all** parameter
segments (`/{a}`) and then **all** catch-all segments (`/{*a}`). Routing
defines a concept called *precedence* that defines the *conceptual*
order in while segments types are ordered.

So there are two problems:

- We sort based on criteria other than precedence (#16579)
- We can't rely on a one-time sort, it needs to be done at each level
(#18677)

---

The fix is to repeat the sort operation at each level and use precedence
as the only key for sorting (as dictated by the graph building algo).

We do a sort of the matches of each node *after* building the
precedence-based part of the DFA, based on the full sorting criteria, to
maintain compatibility.

Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

### CODE REVIEW

File: src/Http/Routing/src/Matching/DfaMatcherBuilder.cs [hunk 1]
```diff
@@ -670,6 +698,10 @@ private void ApplyPolicies(DfaNode node)
                 return;
             }
 
+            // We're done with the precedence based work. Sort the endpoints
+            // before applying policies for simplicity in policy-related code.
+            node.Matches.Sort(_comparer);
```
Comment (JamesNK) [inline src/Http/Routing/src/Matching/DfaMatcherBuilder.cs:703]: Is this sort verified by any tests?

The tests you've added don't have policies. Do existing policy tests fail if this is removed?

Comment (rynowak) [reply src/Http/Routing/src/Matching/DfaMatcherBuilder.cs:703]: It wouldn't hurt to add a test for it, but I expect something would have failed. We don't  re-sort these in our policy implementations.

**Review by pranavkm — APPROVED** [review]
:shipit: once @JamesNK is happy

File: src/Http/Routing/src/Matching/DfaMatcherBuilder.cs (hunk 1 above)
Comment (JamesNK) [reply src/Http/Routing/src/Matching/DfaMatcherBuilder.cs:703]: I'd like to test please 😄

We're potentially passing the matches to a user implemented policy. I think we should verify the order so we don't accidentally change it now or in the future.

File: src/Http/Routing/src/Matching/DfaMatcherBuilder.cs [hunk 2]
```diff
@@ -79,21 +74,37 @@ public DfaNode BuildDfaTree(bool includeLabel = false)
             for (var i = 0; i < _endpoints.Count; i++)
             {
                 var endpoint = _endpoints[i];
-                maxDepth = Math.Max(maxDepth, endpoint.RoutePattern.PathSegments.Count);
+                var precedenceDigit = GetPrecedenceDigitAtDepth(endpoint, depth: 0);
+                work.Add((endpoint, precedenceDigit, new List<DfaNode>() { root, }));
 
-                work.Add((endpoint, new List<DfaNode>() { root, }));
+                maxDepth = Math.Max(maxDepth, endpoint.RoutePattern.PathSegments.Count);
```
[the remark this answers is not in the document]
Comment (rynowak) [reply src/Http/Routing/src/Matching/DfaMatcherBuilder.cs:80]: No, it just seemed to make sense to me to place after the other stuff.

**Comment by rynowak** [comment]
Updated with a brand new test 🥂

File: src/Http/Routing/src/Matching/DfaMatcherBuilder.cs (hunk 1 above)
Comment (rynowak) [reply src/Http/Routing/src/Matching/DfaMatcherBuilder.cs:706]: I've added a new test oriented specifically at the sorting issue.

**Review by JamesNK — APPROVED** [review]
