### PR TITLE
Close connection 

### LINKED ISSUE #18893: Close connections periodically
### Problem

We have multiple VMs with AspNetCore running behind a load balancer. Clients reuse TCP connections as much as possible, and therefore VMs get "pinned" to a subset of clients. We often reach states where one or two VMs are using >90% of CPU resources, whereas most other VMs are <5%. This causes a noticeable degradation and is a recurrent event.

### Proposal

One proposal is provide a setting that tells the maximum number of requests a given TCP connection can deliver.

Another is to allow closing a connection programatically. In this case, the `HttpContext` or other class should expose metrics such as number of requests delivered on that connection, although we can have a good estimate from the request payload itself (i.e. number of requests that a given IP address has performed) or we can simply throw dice and close connections on 0.1% of requests.

In either case, the developer should have ability tell if the closing of a connection will be immediate or graceful. In case of immediate termination of TCP connection, it's fine for ASP.NET to throw exceptions at I/O operations of previously existing requests.

In case of graceful termination, the service must only mark for closing, and stop processing new requests. Requests that exist before close initiated should be satisfied. In `HTTP/11`, the server can automatically return `503` responses for any request that arrives after close is initiated, until the last previously existing request is responded, after which the server can close the TCP socket. The server should also add `Connection: close` header as a hint to clients stop sending new requests. In `HTTP/2` or `HTTP/3`, the server should send a `GOAWAY` frame and ignore new streams, as dictated by the RFC.

### Workaround

The only workaround we know is to restart the AspNetCore application (or entire VM) periodically. However this is cumbersome to implement because we must restart only too-busy nodes, avoid simultaneous restarts of more than one node, and also avoid restarts of two distinct nodes too close to each other. If you have another workaround, please let us know!

Thanks
Fernando Colombo

### PR DESCRIPTION
**Pull request by Kahbazi**
I started working on http.sys and I have couple of questions.

- Kestrel register a callback to `ConnectionClosedRequested` in order to close the connection and in trigger the `ConnectionClosedRequested` in `RequestClose`. 
https://github.com/dotnet/aspnetcore/blob/202c1e8c8b77ad87a45d9eccb646a4abe1353282/src/Servers/Kestrel/Core/src/Internal/HttpConnection.cs#L98
https://github.com/dotnet/aspnetcore/blob/864fa0d2effa7b760246a4e862373a252a195b2f/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnection.cs#L158
Should it be the same for http.sys or adding a connection close header in `RequestClose` in enough?

- What should be a default implementation of `IConnectionLifetimeNotificationFeature` that `DefaultConnectionInfo` would use if the feature does not exists in feature collection? Should it be noop or should `RequestClose` trigger the `ConnectionClosedRequested`?

- Are there any functional tests for closing the connection in kestrel, http.sys and IIS, so I can add a test for the new method there?

- Does setting the connection close header also works for IIS?

Fixes #18893

@Tratcher

### CODE REVIEW

File: src/Http/Http/src/Internal/DefaultConnectionInfo.cs [hunk 1]
```diff
@@ -86,10 +92,16 @@ public override int LocalPort
             return TlsConnectionFeature.GetClientCertificateAsync(cancellationToken);
         }
 
+        public override void RequestClose()
+        {
+            ConnectionLifetime.RequestClose();
```
Comment (davidfowl) [inline src/Http/Http/src/Internal/DefaultConnectionInfo.cs:97]: null check?

File: src/Http/Http/src/Internal/DefaultConnectionInfo.cs [hunk 2]
```diff
@@ -44,6 +47,9 @@ public void Uninitialize()
         private ITlsConnectionFeature TlsConnectionFeature=>
             _features.Fetch(ref _features.Cache.TlsConnection, _newTlsConnectionFeature)!;
 
+        private IConnectionLifetimeNotificationFeature ConnectionLifetime =>
+            _features.Fetch(ref _features.Cache.ConnectionLifetime, _newConnectionLifetime)!;
```
Comment (davidfowl) [inline src/Http/Http/src/Internal/DefaultConnectionInfo.cs:51]: Can't this be null?

Comment (Kahbazi) [reply src/Http/Http/src/Internal/DefaultConnectionInfo.cs:51]: This is one of my questions that if a server does not have `IConnectionLifetimeNotificationFeature` should there be a default implementation of `IConnectionLifetimeNotificationFeature` which at least trigger its cancellation token on `RequestClose`?

File: src/Http/Http/src/Internal/DefaultConnectionInfo.cs [hunk 3]
```diff
@@ -15,6 +16,8 @@ internal sealed class DefaultConnectionInfo : ConnectionInfo
         // Lambdas hoisted to static readonly fields to improve inlining https://github.com/dotnet/roslyn/issues/13624
         private readonly static Func<IFeatureCollection, IHttpConnectionFeature> _newHttpConnectionFeature = f => new HttpConnectionFeature();
         private readonly static Func<IFeatureCollection, ITlsConnectionFeature> _newTlsConnectionFeature = f => new TlsConnectionFeature();
+        // Should there be a default IConnectionLifetimeNotificationFeature which does nothing!?
```
Comment (halter73) [inline src/Http/Http/src/Internal/DefaultConnectionInfo.cs:19]: I don't think it should do nothing. Let's throw a clear error instead of potentially returning null.

Comment (davidfowl) [reply src/Http/Http/src/Internal/DefaultConnectionInfo.cs:19]: Or set the header?

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs [hunk 4]
```diff
@@ -602,6 +610,9 @@ IHeaderDictionary IHttpResponseTrailersFeature.Trailers
 
         public bool CanDelegate => Request.CanDelegate;
 
+        // Should therer be a cts for this so it could get triggered when RequestClose called?
+        CancellationToken IConnectionLifetimeNotificationFeature.ConnectionClosedRequested { get; set; }
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:614]: This can return a default non-cancellable token for now. We can revisit if there's interest in the token.

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs [hunk 5]
```diff
@@ -728,5 +739,14 @@ public void DelegateRequest(DelegationRule destination)
             Delegate(destination);
             _responseStarted = true;
         }
+
+        void IConnectionLifetimeNotificationFeature.RequestClose()
+        {
+            // Set the connection close feature if the response hasn't sent headers as yet
+            if (!Response.HasStarted)
+            {
+                Response.Headers[HeaderNames.Connection] = "close";
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:748]: FYI the actual close logic is over here:
https://github.com/dotnet/aspnetcore/blob/4c9c303b971b99169a14b42a35d95eb47e67ebfb/src/Servers/HttpSys/src/RequestProcessing/Response.cs#L464-L477

Setting the close header is not required for the HTTP/2 code path, it gets converted to a flag instead, but this is adequate for now.

File: src/Http/Http/src/Internal/DefaultConnectionInfo.cs (hunk 2 above)
Comment (Tratcher) [reply src/Http/Http/src/Internal/DefaultConnectionInfo.cs:51]: The default should look like the default Abort feature, plus maybe adding the close header:
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Features/HttpRequestLifetimeFeature.cs

**Review by Tratcher — COMMENTED** [review]
Do you plan to do IIS as well?

**Comment by Kahbazi** [comment]
> Do you plan to do IIS as well?

Yes. Does setting the connection close header also work for IIS? Does both in process and out of process support this?

**Comment by Tratcher** [comment]
> Does both in process and out of process support this?

This won't be supported for out-of-process.

> Does setting the connection close header also work for IIS?

@jkotalik there's a different API for HTTP/2, right?

File: src/Servers/Connections.Abstractions/src/Features/DefaultConnectionLifetimeNotificationFeature.cs [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+        public CancellationToken ConnectionClosedRequested { get; set; }
+
+        ///<inheritdoc/>
+        public void RequestClose()
+        {
+            if (_httpResponseFeature != null)
+            {
+                if (!_httpResponseFeature.HasStarted)
+                {
+                    _httpResponseFeature.Headers["Connection"] = "close";
```
Comment (Tratcher) [inline src/Servers/Connections.Abstractions/src/Features/DefaultConnectionLifetimeNotificationFeature.cs:31]: Hot new API:
```suggestion
                    _httpResponseFeature.Headers.Connection = "close";
```

File: src/Servers/Connections.Abstractions/src/Features/DefaultConnectionLifetimeNotificationFeature.cs [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+namespace Microsoft.AspNetCore.Connections.Features
+{
+    /// <summary>
+    /// Default implementation of <see cref="IConnectionLifetimeNotificationFeature"/>.
+    /// </summary>
+    public class DefaultConnectionLifetimeNotificationFeature : IConnectionLifetimeNotificationFeature
+    {
+        private readonly IHttpResponseFeature? _httpResponseFeature;
+
+        public DefaultConnectionLifetimeNotificationFeature(IHttpResponseFeature? httpResponseFeature)
```
Comment (Tratcher) [inline src/Servers/Connections.Abstractions/src/Features/DefaultConnectionLifetimeNotificationFeature.cs:16]: This isn't going to work once you rebase, Connections.Abstractions no longer depends on Http.Features, it depends on Extensions.Features. You'll have to move this class into the `Http` assembly where it's used.

**Comment by Tratcher** [comment]
It looks like we added the same `Connection: close` behavior for IIS:
https://github.com/dotnet/aspnetcore/pull/24598/

**Comment by Tratcher** [comment]
@jkotalik pointed out that #24598 was closed, not merged, but you can revive it now with the feature wired directly to HttpSetNeedGoAway.

**Comment by Tratcher** [comment]
@Kahbazi are you able to continue on this one, or are you stuck on something?

**Comment by Kahbazi** [comment]
@Tratcher I've added the implementations. Could you please guide me on how I can test this?

**Comment by Tratcher** [comment]
We use a shared source tool called http2cat to test http/2 scenarios at the frame level. HttpSys already has a similar test for this: https://github.com/dotnet/aspnetcore/blob/1a2b3260c6161ae9b7f639de228a6eb0488a1075/src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs#L362-L371

You can copy these IIS tests and adapt them to this scenario:
https://github.com/dotnet/aspnetcore/blob/1a2b3260c6161ae9b7f639de228a6eb0488a1075/src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs#L218-L222

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs [hunk 8]
```diff
@@ -728,5 +736,14 @@ public void DelegateRequest(DelegationRule destination)
             Delegate(destination);
             _responseStarted = true;
         }
+
+        void IConnectionLifetimeNotificationFeature.RequestClose()
+        {
+            // Set the connection close feature if the response hasn't sent headers as yet
+            if (!Response.HasStarted)
+            {
+                Response.Headers["Connection"] = "close";
```
Comment (Tratcher) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:745]: Are HeaderNames in scope?
```suggestion
                Response.Headers[HeaderNames.Connection] = "close";
```

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs [hunk 9]
```diff
@@ -499,5 +502,15 @@ private void DisableCompression()
...
             serverVariableFeature["IIS_EnableDynamicCompression"] = "0";
         }
+
+        void IConnectionLifetimeNotificationFeature.RequestClose()
+        {
+            // Set the connection close feature if the response hasn't sent headers as yet
+            if (!HasResponseStarted)
+            {
+                ResponseHeaders.Connection = ConnectionClose;
+            }
```
Comment (Tratcher) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs:512]: Since IIS never supported this feature via headers, let's skip setting the header and instead try calling `NativeMethods.HttpSetNeedGoAway(_requestNativeHandle);` directly. You'll still need the HasResponseStarted check since GoAway is implemented in Http.Sys as a response flag.

Comment (Tratcher) [reply src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs:512]: Wait, we still need it for HTTP/1.1 don't we. Nevermind, this is fine.

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs [hunk 10]
```diff
@@ -742,7 +742,7 @@ void IConnectionLifetimeNotificationFeature.RequestClose()
             // Set the connection close feature if the response hasn't sent headers as yet
             if (!Response.HasStarted)
             {
-                Response.Headers["Connection"] = "close";
+                Response.Headers[HeaderNames.Connection] = "close";
```
Comment (davidfowl) [inline src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:745]:
```suggestion
                Response.Headers.Connection = "close";
```

Comment (Kahbazi) [reply src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:745]: I tried this at first, but got error. If I'm not wrong the reason is `Connection` is a default interface property and is implicit and here `Response.Headers` type is `HeaderCollection` and not `IHeaderDictionary`.

**Review by halter73 — APPROVED** [review]

File: src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs (hunk 10 above)
Comment (davidfowl) [reply src/Servers/HttpSys/src/RequestProcessing/RequestContext.FeatureCollection.cs:745]: Ah

File: src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs [hunk 11]
```diff
@@ -470,6 +470,80 @@ public async Task ConnectionClose_AdditionalRequests_ReceivesSecondGoAway()
                 .Build().RunAsync();
         }
 
+        [ConditionalFact]
+        [MinimumOSVersion(OperatingSystems.Windows, WindowsVersions.Win10_19H2, SkipReason = "GoAway support was added in Win10_19H2.")]
+        public async Task ConnectionRequestClose_AdditionalRequests_ReceivesSecondGoAway()
```
Comment (Tratcher) [inline src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs:475]: You've copied more complex test. You can cover this new behavior by copying the simpler test ConnectionClose_OSSupport_SendsGoAway.

**Review by Tratcher — COMMENTED** [review]
Progress. How about the test for IIS?

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.Features.cs [hunk 12]
```diff
@@ -274,19 +281,27 @@ internal void FastFeatureSet(Type key, object? feature)
...
             }
             if (key == IHttpResponseTrailersFeature)
             {
                 _currentIHttpResponseTrailersFeature = feature;
+                return;
             }
             if (key == IHttpResetFeature)
             {
                 _currentIHttpResetFeature = feature;
+                return;
```
Comment (Kahbazi) [inline src/Servers/IIS/IIS/src/Core/IISHttpContext.Features.cs:294]: These `return`s were missing, right?

File: src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs [hunk 13]
```diff
@@ -240,6 +240,40 @@ public async Task Reset_BeforeResponse_Resets()
                 .Build().RunAsync();
         }
 
+        [ConditionalFact]
+        [RequiresNewHandler]
+        [MinimumOSVersion(OperatingSystems.Windows, WindowsVersionForTrailers)]
+        public async Task Reset_ConnectionRequestClose()
```
Comment (Kahbazi) [inline src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs:246]: @Tratcher I couldn't run IIS tests on my machine. I'm not sure if this test is correct.

File: src/Servers/IIS/IIS/src/Core/IISHttpContext.Features.cs (hunk 12 above)
Comment (Tratcher) [reply src/Servers/IIS/IIS/src/Core/IISHttpContext.Features.cs:294]: Good find.

File: src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs (hunk 13 above)
Comment (Tratcher) [reply src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs:246]: I'll verify it locally, it still requires a preview build of windows.

**Comment by pranavkm** [comment]
Let's make the default implementation non-public. Outside of that, API looks :shipit:

File: src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs (hunk 13 above)
Comment (Tratcher) [reply src/Servers/IIS/IIS/test/IIS.FunctionalTests/Http2TrailersResetTests.cs:246]:
```suggestion
        public async Task RequestClose_SendsGoAway()
```

**Review by Tratcher — APPROVED** [review]
I've run the IIS tests locally to confirm they work. For some reason they kept getting skipped in VS with a warning about not running as admin despite VS being run as admin. I overrode it by forcing the test to a `[Fact]`.

**Comment by Tratcher** [comment]
Thanks again @Kahbazi!

**Comment by davidfowl** [comment]
This is a great contribution (as usual) @Kahbazi !
