### PR TITLE
return value for single HttpContext parameter

### LINKED ISSUE #39956: Minimal APIs: Moving handler with single parameter of type `HttpContext` to separate method results in empty response
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Moving Minimal APIs handler with single param of type `HttpContext` results in empty response.

```csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder();
WebApplication app = builder.Build();
app.Map("/Fails", Fails);
app.Map("/Fails1", Fails1);
app.Map("/Works", async (HttpContext c) =>
{
    var response = await Task.Run(() => { return "response"; });
    return response;
});
// /WorksToo?someParam=1
app.Map("/WorksToo", Works);
app.Map("/WorksToo1", Works1);
app.Map("/WorksToo2", Works2);
app.Run();
static async Task<string> Fails1(HttpContext context)
{
    var response = await Task.FromResult("response");
    return response;
}
public partial class Program
{
    internal static async Task<string> Fails(HttpContext context) => await Task.FromResult("response");

    internal static async Task<string> Works(HttpContext context, string someParam) => await Task.FromResult("response");

    internal static async Task<string> Works1(HttpContext context, ILogger<Program> _) => await Task.FromResult("response");

    internal static async Task<string> Works2(HttpRequest context) => await Task.FromResult("response");
}
```

Endpoints named `Fails` return empty result (chrome, postman, no Content-Type) while others result in `response` (Content-Type: text/plain; charset=utf-8")

### Expected Behavior

All returns the same - `response`.

### Steps To Reproduce

Run the app in the description and call endpoints.

### Exceptions (if any)

_No response_

### .NET Version

6.0.101

### Anything else?

- IDE: both VS 2022 and Rider
- dotnet info:
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

### PR DESCRIPTION
**Pull request by feiyun0112**
fix #39956

### CODE REVIEW

File: src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs [hunk 1]
```diff
@@ -38,6 +38,10 @@ public static class EndpointRouteBuilderExtensions
         string pattern,
         RequestDelegate requestDelegate)
     {
+        if (requestDelegate.Method.ReturnType.IsGenericType)
```
Comment (davidfowl) [inline src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: This doesn't seem right. This should be checking specifically for `Task<T>`.
```suggestion
        var returnType = f.Method.ReturnType;
        if (returnType is { IsGenericType: true } && returnType.GetGenericTypeDefinition() == typeof(Task<>))
```

Comment (feiyun0112) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: @davidfowl 

[RequestDelegate](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/RequestDelegate.cs) use Task as ReturnType
`public delegate Task RequestDelegate(HttpContext context);`

if returnType.IsGenericType, it must be `Task<>`, right?

Comment (davidfowl) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: Nope:

```C#
var f = MyClass<int> () => new(() => { });

Console.WriteLine(f.Method.ReturnType.IsGenericType);

class MyClass<T> : Task
{
    public MyClass(Action action) : base(action)
    {
    }
}
```

Comment (davidfowl) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: Hmm, trying to get a better example (if possible) that shows this case with the overload.

Comment (davidfowl) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: Here ya go:

```C#

Thing(() => new MyClass<int>());

void Thing(ReturnsATask del)
{
    Console.WriteLine(del.Method.ReturnType.IsGenericType);
}

delegate Task ReturnsATask();

class MyClass<T> : Task
{
    public MyClass() : base(() => { })
    {
    }
}

```

File: src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs [hunk 2]
```diff
@@ -31,6 +31,28 @@ namespace Microsoft.AspNetCore.Tests;
...
+    {
+        var builder = WebApplication.CreateBuilder();
+        builder.WebHost.UseTestServer();
+        await using var app = builder.Build();
+
+        static async Task<string> Fails(HttpContext context) => await Task.FromResult("response");
+
+        app.MapGet("/Fails", Fails);
+
+        app.UseRouting();
```
Comment (davidfowl) [inline src/DefaultBuilder/test/Microsoft.AspNetCore.Tests/WebApplicationTests.cs:45]: Remove this.

File: src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs (hunk 1 above)
Comment (davidfowl) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: Now that I've tried to reproduce this, I realized it doesn't seem to work at all. What is your test verifying exactly?

Comment (davidfowl) [reply src/Http/Routing/src/Builder/EndpointRouteBuilderExtensions.cs:41]: OK scratch that, I can reproduce the problem now and the fix now. This is a tricky issue because I guess the problem only reproduces with method groups.

```C#

Task<int> Fails() => Task.FromResult(1);
MyClass<int> Fails1() => new MyClass<int>();

Mapper.Map(Fails1);

delegate Task ReturnsATask();

class MyClass<T> : Task
{
    public MyClass() : base(() => { })
    {
    }
}
```

**Comment by davidfowl** [comment]
We do need a test but you can add a test here https://github.com/dotnet/aspnetcore/blob/ad46e0355613b8cfca9d401a44d9eba7004a175b/src/Http/Routing/test/UnitTests/Builder/EndpointRoutingApplicationBuilderExtensionsTest.cs

OR here 

https://github.com/dotnet/aspnetcore/blob/ad46e0355613b8cfca9d401a44d9eba7004a175b/src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 3]
```diff
@@ -69,6 +69,27 @@ public void MapEndpoint_StringPattern_BuildsEndpoint()
         Assert.Equal("/", endpointBuilder1.RoutePattern.RawText);
     }
 
+    [Fact]
+    public void MapEndpoint_ReturnGenericTypeTask_GeneratedDelegate()
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:73]: Add an assert that observes we write to the body.

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 4]
```diff
@@ -69,6 +69,27 @@ public void MapEndpoint_StringPattern_BuildsEndpoint()
...
+        static async Task<string> GenericTypeTaskDelegate(HttpContext context) => await Task.FromResult("response");
+
+        // Act
+        var endpointBuilder = builder.MapGet("/", GenericTypeTaskDelegate);
+
+        // Assert
+        var endpointBuilder1 = GetRouteEndpointBuilder(builder);
+        var target = endpointBuilder1.RequestDelegate.Target;
+        Assert.NotNull(target);
+        var handlerField = target.GetType().GetField("handler");
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:86]: What is this doing? It's unclear, can you add a comment.

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs (hunk 3 above)
Comment (feiyun0112) [reply src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:73]: how to assert body in unit test?

Comment (halter73) [reply src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:73]: Create a mock `HttpContext` with a `MemoryStream` as the `HttpResponse.Body`. Then call `endpointBuilder1.RequestDelegate` with the mock. Once that's done, verify that "response" was written to the MemoryStream. Here's a similar example:

https://github.com/dotnet/aspnetcore/blob/95dcd9d252842cabe4a25fb07a67c0c220ae9807/src/Http/Http.Extensions/test/RequestDelegateFactoryTests.cs#L2501-L2518

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 5]
```diff
@@ -69,6 +74,30 @@ public void MapEndpoint_StringPattern_BuildsEndpoint()
         Assert.Equal("/", endpointBuilder1.RoutePattern.RawText);
     }
 
+    [Fact]
+    public async void MapEndpoint_ReturnGenericTypeTask_GeneratedDelegate()
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:78]:
```suggestion
    public async Task MapEndpoint_ReturnGenericTypeTask_GeneratedDelegate()
```

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 6]
```diff
@@ -217,4 +246,102 @@ private class Attribute1 : Attribute
...
+
+        public CancellationToken RequestAborted { get => _requestAbortedCts.Token; set => throw new NotImplementedException(); }
+
+        public void Abort()
+        {
+            _requestAbortedCts.Cancel();
+        }
+    }
+
+    private class TestHttpResponseFeature : IHttpResponseFeature, IHttpResponseBodyFeature
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:278]: You shouldn't need this.

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 7]
```diff
@@ -217,4 +246,102 @@ private class Attribute1 : Attribute
...
     }
+
+    private DefaultHttpContext CreateHttpContext()
+    {
+        var responseFeature = new TestHttpResponseFeature();
+
+        return new()
+        {
+            RequestServices = new ServiceCollection().BuildServiceProvider(),
+            Features =
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:257]: You don't need this.

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 8]
```diff
@@ -69,6 +74,30 @@ public void MapEndpoint_StringPattern_BuildsEndpoint()
         Assert.Equal("/", endpointBuilder1.RoutePattern.RawText);
     }
 
+    [Fact]
+    public async Task MapEndpoint_ReturnGenericTypeTask_GeneratedDelegate()
+    {
+        var httpContext = CreateHttpContext();
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:80]:
```suggestion
        var httpContext = new DefaultHttpContext();
```

File: src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs [hunk 9]
```diff
@@ -217,4 +246,11 @@ private class Attribute1 : Attribute
     private class Attribute2 : Attribute
     {
     }
+
+    private DefaultHttpContext CreateHttpContext()
+    {
+        return new()
+        {
+        };
+    }
```
Comment (davidfowl) [inline src/Http/Routing/test/UnitTests/Builder/RequestDelegateEndpointRouteBuilderExtensionsTest.cs:255]:
```suggestion
```

**Review by halter73 — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
Great work @feiyun0112 !
