### PR TITLE
Re-enable `FormWithParentBindingContextTest.CanUseFormWithMethodGet`

### LINKED ISSUE #61882: Quarantine `FormWithParentBindingContextTest.CanUseFormWithMethodGet`
## Failing Test(s)

Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.CanUseFormWithMethodGet(suppressEnhancedNavigation: True)

## Error Message

```text
[xUnit.net 00:01:14.31]     Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.CanUseFormWithMethodGet(suppressEnhancedNavigation: True) [FAIL]
  Failed Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.CanUseFormWithMethodGet(suppressEnhancedNavigation: True) [44 s]
  Error Message:
   OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: Initial value
Actual:   Edited value
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 154
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass19_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 104
```
Blocked in https://github.com/dotnet/aspnetcore/pull/61881.

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=1037724&view=logs&j=5c945968-3a2e-573b-5d84-9df2797877cd&t=9b5db1c9-6a37-5ace-21ee-0f4c6c556658

### PR DESCRIPTION
**Pull request by dariatiurina**
# Re-enable `FormWithParentBindingContextTest.CanUseFormWithMethodGet`

## Description

This pull request re-enables `FormWithParentBindingContextTest.CanUseFormWithMethodGet` by refactoring the test coverage for form handling with browser back/forward navigation by moving the relevant test from `FormWithParentBindingContextTest` to a new dedicated test class, `FormWithNoBackForwardCacheTest`. Additionally, it introduces a new browser context and configuration to ensure correct browser behavior for these tests. 

### Changes
* The `CanUseFormWithMethodGet` test has been removed from `FormWithParentBindingContextTest` and added to a new file and class, `FormWithNoBackForwardCacheTest` with different browser context.
* Added a new browser context constant, `BackForwardCacheContext`, to `BrowserFixture` for tests needing control over Chrome's back/forward cache.

### Reasoning behind changes:
In the recent changes in Chrome the Back/forward cache is now enabled by default. Due to this `autocomplete="off"` is not working correctly in the test. The new created ServerFixtureContext that disables this default behaviour in Chrome.

Fixes #61882

### CODE REVIEW

File: src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithNoBackForwardCacheTest.cs [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+        BrowserFixture browserFixture,
+        BasicTestAppServerSiteFixture<RazorComponentEndpointsStartup<App>> serverFixture,
+        ITestOutputHelper output)
+        : base(browserFixture, serverFixture, output)
+    {
+    }
+
+    public override Task InitializeAsync()
+    {
+        return InitializeAsync(BrowserFixture.BackForwardCacheContext);
```
Comment (ilonatommy) [inline src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithNoBackForwardCacheTest.cs]: This overrides `BrowserFixture.StreamingContext`. I know you wanted the flag to be passed but we have to keep `streaming` in the browser context, it affects how we load the page (we have the `None` policy activated with streaming, otherwise it's `Normal`).
We have 2 options:
1) Check who else is using streaming context and assess how many tests would run with the outdated settings if we added cache fallback to all of them by default, then move this test back to the original class and add the cache fallback flag for streaming.
2) Have a separate context `StreamingBackForwardCacheContext` that would activate both features.

Comment (ilonatommy) [reply src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithNoBackForwardCacheTest.cs]: Update: never mind, you implemented the 2nd option, I missed that. Sorry. Could we rename it to `StreamingBackForwardCacheContext `? It would avoid confusion.

**Review by ilonatommy — APPROVED** [review]
