### PR TITLE
Components: don't block the SignalR loop during init. Fixes #8274

### LINKED ISSUE #8274: Tasks returned from JSRuntime.InvokeAsync during OnInitAsync never finishes in preview3
### Describe the bug
Tasks returned from JSRuntime.InvokeAsync during second call to OnInitAsync (after prerendering) never finishes.

### To Reproduce
Create a new razorcomponents project.

Add a js interop function to Index.cshtml and disable prerendering

```html
    <script>
        window.interopDuringOnInit = function() {
            return "Hello World";
        }
    </script>

    <app></app>

    <script src="_framework/components.server.js"></script>
```

Call js interop during OnAsyncInit in Index.razor

```razor
<h1>@Greeting!</h1>

Welcome to your new app.

@functions {
    string Greeting;

    protected override async Task OnInitAsync()
    {
        try
        {
            Console.WriteLine("Calling browser");
            Greeting = await JSRuntime.InvokeAsync<string>("interopDuringOnInit");
            Console.WriteLine("Returned from browser");
        }
        catch (Exception ex)
        {
            Console.WriteLine("Could not invoke interop during OnInit, " + ex.ToString());
        }
    }
}
```

When OnInitAsync is called as part of an initial load (prerendering disabled) the task never finishes, This leaves the circuit hanging, and no further events are processed.

If this component is loaded from a `IUriHelper.OnLocationChange`, the above code works as expected.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
For more details, see https://github.com/aspnet/AspNetCore/issues/8274#issuecomment-477203983

### CODE REVIEW

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 1]
```diff
@@ -104,21 +104,32 @@ public Task<IEnumerable<string>> PrerenderComponentAsync(Type componentType, Par
...
-                    var (componentType, domElementSelector) = Descriptors[i];
-                    await Renderer.AddComponentAsync(componentType, domElementSelector);
-                }
+                    SetCurrentCircuitHost(this);
 
-                await OnCircuitOpenedAsync(cancellationToken);
+                    for (var i = 0; i < Descriptors.Count; i++)
+                    {
+                        var (componentType, domElementSelector) = Descriptors[i];
+                        await Renderer.AddComponentAsync(componentType, domElementSelector);
```
Comment (javiercn) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: Do we still have to work for quiescence here until we declare the circuit opened?

**Review by javiercn — APPROVED** [review]
Looks great. Could we perhaps have an E2E test for this?

**Comment by SteveSandersonMS** [comment]
@javiercn I don't think we have any infrastructure for E2E tests specifically about initialization, since all our E2E tests run in a context where the app has already started running. I agree it would be good if we did have more coverage around that, but it's not something I'd like to get deep into at this point.

File: src/Components/Server/src/Circuits/CircuitHost.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: No, if we did that, then JSInterop calls made in the meantime (e.g., during InitAsync) would throw because they are only allowed once the circuit is flagged as opened.

We need the circuit to be regarded as opened synchronously. Since dispatcher calls are serialized, and since (non-quiescent) rendering is synchronous, we already know that we'll only start to process incoming JSInterop calls *after* the first synchronous render, which is the right time to start processing them.

File: src/Components/Server/src/ComponentHub.cs [hunk 2]
```diff
@@ -64,7 +64,7 @@ public override Task OnDisconnectedAsync(Exception exception)
         /// <summary>
         /// Intended for framework use only. Applications should not call this method directly.
         /// </summary>
-        public async Task<string> StartCircuit(string uriAbsolute, string baseUriAbsolute)
+        public string StartCircuit(string uriAbsolute, string baseUriAbsolute)
```
Comment (pranavkm) [inline src/Components/Server/src/ComponentHub.cs]: :+1:

**Review by pranavkm — APPROVED** [review]

File: src/Components/Server/src/Circuits/CircuitHost.cs [hunk 3]
```diff
@@ -104,21 +104,32 @@ public Task<IEnumerable<string>> PrerenderComponentAsync(Type componentType, Par
             });
         }
 
-        public async Task InitializeAsync(CancellationToken cancellationToken)
```
Comment (rynowak) [inline src/Components/Server/src/Circuits/CircuitHost.cs]: It would be really nice to leave the signature alone and have the hub be the one to fire-and-forget this task. When we have async code we need to be able to await it in a test or errors will creep in. 

Basically have a big, thick, gooey async method that returns a task, and have a small stub (`StartCircuit` in this case) do `_ = InitializeAsync()`

Comment (SteveSandersonMS) [reply src/Components/Server/src/Circuits/CircuitHost.cs]: Sure, done.

**Review by rynowak — APPROVED** [review]
