### PR TITLE
Make HttpLogging middleware endpoint aware

### LINKED ISSUE #46703: Under certain circumstances, the HttpLogging middleware does not follow the ResponseBodyLogLimit setting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At this time, the buffer length may be longer than the `ResponseBodyLogLimit` setting
https://github.com/dotnet/aspnetcore/blob/6a7bcda42de7b98196b38924cc354216eba57c9b/src/Middleware/HttpLogging/src/ResponseBufferingStream.cs#L116

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

net6.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrennanConroy**
Addresses https://github.com/dotnet/aspnetcore/issues/43222

And fixes https://github.com/dotnet/aspnetcore/issues/46703 as it was preventing testing the response byte limit.

### CODE REVIEW

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs [hunk 1]
```diff
@@ -96,36 +82,40 @@ public override async Task WriteAsync(byte[] buffer, int offset, int count, Canc
...
     private void OnFirstWrite()
     {
         if (!FirstWrite)
         {
             // Log headers as first write occurs (headers locked now)
-            HttpLoggingMiddleware.LogResponseHeaders(_context.Response, _options, _logger);
+            HttpLoggingMiddleware.LogResponseHeaders(_context.Response, _loggingFields, _allowedResponseHeaders, _logger);
 
             MediaTypeHelpers.TryGetEncodingForMediaType(_context.Response.ContentType, _encodings, out _encoding);
             FirstWrite = true;
```
Comment (Tratcher) [inline src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:121]: This bool name is confusing.

File: src/Middleware/HttpLogging/src/ResponseBufferingStream.cs [hunk 2]
```diff
@@ -96,36 +82,40 @@ public override async Task WriteAsync(byte[] buffer, int offset, int count, Canc
...
         var remaining = _limit - _bytesBuffered;
-        var innerCount = Math.Min(remaining, buffer.Length);
+        var innerCount = Math.Min(remaining, span.Length);
 
         OnFirstWrite();
 
         if (innerCount > 0)
         {
-            if (_tailMemory.Length - innerCount > 0)
+            if (span.Slice(0, innerCount).TryCopyTo(_tailMemory.Span))
```
Comment (Tratcher) [inline src/Middleware/HttpLogging/src/ResponseBufferingStream.cs:100]: Avoid duplicating the slice?

File: src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
+public sealed class HttpLoggingAttribute : Attribute
+{
+    /// <summary>
+    /// Initializes an instance of the <see cref="HttpLoggingAttribute"/> class.
+    /// </summary>
+    /// <param name="loggingFields">Specifies what fields to log for the endpoint.</param>
+    /// <param name="requestBodyLogLimit">Specifies the maximum number of bytes to be logged for the request body. A negative value means use the default setting in <see cref="HttpLoggingOptions.RequestBodyLogLimit"/>.</param>
+    /// <param name="responseBodyLogLimit">Specifies the maximum number of bytes to be logged for the response body. A negative value means use the default setting in <see cref="HttpLoggingOptions.ResponseBodyLogLimit"/>.</param>
+    public HttpLoggingAttribute(HttpLoggingFields loggingFields, int requestBodyLogLimit = -1, int responseBodyLogLimit = -1)
```
Comment (Tratcher) [inline src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs:18]: Couldn't use `int?`?

**Review by Tratcher — APPROVED** [review]

File: src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs (hunk 3 above)
Comment (BrennanConroy) [reply src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs:18]: Oh right, forgot about this change. You aren't allowed to use generics in attributes. And since int is a struct, `int?` is actually `Nullable<int>`. We'll need to update the approved API.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by JamesNK** [comment]
I believe there are analyzers for checking endpoint-aware middleware is between UseRouting and UseEndpoint. Should it be updated to check HttpLogging middleware position?

File: src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    {
+        LoggingFields = loggingFields;
+        RequestBodyLogLimit = requestBodyLogLimit < 0 ? null : requestBodyLogLimit;
```
Comment (halter73) [inline src/Middleware/HttpLogging/src/HttpLoggingAttribute.cs:21]: I think we should probably reject arguments that are negative but not `-1`. That's what we do in `System.IO.Pipelines.PipeOptions`. I mentioned this in the issue, but I think we should leave the properties non-nullable to match the constructor parameters. This is also what `PipeOptions` does.

File: src/Middleware/HttpLogging/src/HttpLoggingEndpointConventionBuilderExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+/// </summary>
+public static class HttpLoggingEndpointConventionBuilderExtensions
+{
+    /// <summary>
+    /// Adds endpoint specific settings for the HttpLogging middleware.
+    /// </summary>
+    /// <typeparam name="TBuilder">The type of endpoint convention builder.</typeparam>
+    /// <param name="builder">The endpoint convention builder.</param>
+    /// <param name="loggingFields">The <see cref="HttpLoggingFields"/> to apply to this endpoint.</param>
+    /// <param name="requestBodyLogLimit">Sets the <see cref="HttpLoggingOptions.RequestBodyLogLimit"/> for this endpoint.</param>
```
Comment (Tratcher) [inline src/Middleware/HttpLogging/src/HttpLoggingEndpointConventionBuilderExtensions.cs:19]: -1 means....

**Review by Tratcher — APPROVED** [review]
