### PR TITLE
Throw if a component produces an invalid render tree. Fixes #24579

### LINKED ISSUE #24579: Try / Catch does not work in razor markup
### Describe the bug

Try/Catch does not work in razor code when encountering index out of bounds. 
Expected behavior of code below would be to see "Index out of bounds" in the div.
Actual behavior, page hangs and eventually gives out of memory exception.

### To Reproduce

Create standard Blazor WASM project.  Replace Counter page with following:

```razor
@page "/counter"

@try
{
    <div>@Strings[5]</div>
}
catch (Exception ex)
{
    <div>@ex.ToString()</div>
}

@code {
    private List<string> Strings = new List<string> { "String one", "String 2" };
}
```

### Exceptions (if any)
Out of Memory error

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 16.6.5

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
The cause of #24579 was what I thought. Components aren't allowed to produce invalid trees - this has always been an unsupported situation. However it's unfortunate that developers can produce invalid trees using something as reasonable-seeming as a `try`/`catch` block, so we need to do something to prevent this class of problems.

Previously we didn't detect this scenario, so the diffing logic could just get stuck on it. With this PR we check whether there were any unclosed tree entries left behind, and if so, fails the entire rendering process with an exception, so the behavior is properly defined.

Longer term we might want to prevent the `try`/`catch` block at compile time in the Razor compiler, but this runtime check is still desirable, and is sufficient to block the situation.

### CODE REVIEW

File: src/Components/Components/test/Rendering/RenderTreeBuilderTest.cs [hunk 1]
```diff
@@ -1831,6 +1831,69 @@ public void ProcessDuplicateAttributes_CanRemoveOverwrittenAttributes()
...
+        {
+            // Arrange
+            var builder = new RenderTreeBuilder();
+            var component = new TestComponent();
+            builder.OpenElement(0, "myElem");
+            builder.OpenRegion(1);
+            builder.OpenComponent<OtherComponent>(2);
+            builder.CloseComponent();
+            builder.CloseRegion();
+            builder.CloseElement();
```
Comment (javiercn) [inline src/Components/Components/test/Rendering/RenderTreeBuilderTest.cs:1845]: Do we have validation for when the close statements balance out but are in different order? For example
```
builder.OpenElement()
builder.OpenRegion().
builder.CloseElement();
builder.CloseRegion()
```

File: src/Components/Components/src/Rendering/RenderTreeBuilder.cs [hunk 2]
```diff
@@ -685,6 +685,17 @@ internal void InsertAttributeExpensive(int insertAtIndex, int sequence, string a
         public ArrayRange<RenderTreeFrame> GetFrames() =>
             _entries.ToRange();
 
+        internal void AssertTreeIsValid(IComponent component)
+        {
+            if (_openElementIndices.Count > 0)
+            {
+                // It's never valid to leave an element/component/region unclosed. Doing so
+                // could cause undefined behavior in diffing.
+                ref var invalidFrame = ref _entries.Buffer[_openElementIndices.Peek()];
```
Comment (javiercn) [inline src/Components/Components/src/Rendering/RenderTreeBuilder.cs:694]: Is it always guaranteed that the index is going to be in range (assuming there are no bugs in the RenderTreeBuilder code) I believe that's the case, but given we are dealing with "failure modes" here I ask just in case to be more cautious.

**Comment by javiercn** [comment]
> Previously we didn't detect this scenario, so the diffing logic could just get stuck on it. With this PR we check whether there were any unclosed tree entries left behind, and if so, fails the entire rendering process with an exception, so the behavior is properly defined.

Is this something worth patching in 3.1 with an app compat switch? (so that we can turn it on for 3.1 in the templates and users don't get surprised when it breaks later on)

File: src/Components/Components/test/Rendering/RenderTreeBuilderTest.cs (hunk 1 above)
Comment (SteveSandersonMS) [reply src/Components/Components/test/Rendering/RenderTreeBuilderTest.cs:1845]: It's a good point to raise, but I think we're OK with this one. In practice all of the `Close` methods will close whatever frame is outstanding on the stack, so even if you do deliberately get the order wrong it won't be harmful. The only weirdness you could cause by this would be failing to pass parameters to a child component because that's the only difference between the close methods.

Considering how perf-critical is this low-level part of rendering, we wouldn't want penalize people using `.razor` to produce normal components by introduce extra checking logic for cases that a valid `.razor` component could never trigger. We've always been clear that anyone writing rendertreebuilder logic manually is in the same situation as people writing C# logic manually: if you write a bug, you have a bug.

File: src/Components/Components/src/Rendering/RenderTreeBuilder.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/Components/src/Rendering/RenderTreeBuilder.cs:694]: Yes, but even if not, the code here is certain to throw (either from the `throw` statement on L695, or an index-out-of-range on L694), which is all we need.

**Comment by SteveSandersonMS** [comment]
> Is this something worth patching in 3.1 with an app compat switch? (so that we can turn it on for 3.1 in the templates and users don't get surprised when it breaks later on)

I don't know we have a mechanism for an appcompat switch given that this is purely a `netstandard2.1` class library in 3.1 and doesn't depend on ASP.NET Core libraries.

**Comment by javiercn** [comment]
> I don't know we have a mechanism for an appcompat switch given that this is purely a `netstandard2.1` class library in 3.1 and doesn't depend on ASP.NET Core libraries.

I was referring to https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=netstandard-2.1, wouldn't this work?

**Comment by SteveSandersonMS** [comment]
Maybe. It’s worth considering. We need to check if it has any meaningful impact on app size after linking. Might not do if other framework code already references it.

**Review by javiercn — APPROVED** [review]
