### PR TITLE
[blazor] Diagnostic traces - OTEL names review

### LINKED ISSUE #62556: [API Proposal] Diagnostic traces for Blazor
## Background and Motivation

In Net10 we are adding new diagnostic traces for Blazor. This is not C# API but about **OTEL names.**

Implementation is in https://github.com/dotnet/aspnetcore/pull/61609 and https://github.com/dotnet/aspnetcore/pull/62286

There was already feedback about names in both implementation PRs 
There is also feedback in external OTEL repo that guides the naming conventions https://github.com/open-telemetry/semantic-conventions/pull/2235

### new source `Microsoft.AspNetCore.Components`
- Trace name: `Microsoft.AspNetCore.Components.RouteChange` 
    - Description: User navigated to new Blazor route/page
    - Tag: `aspnetcore.components.type` - class name of the Page component
    - Tag: `aspnetcore.components.route` - URL path pattern of the Blazor page
    - Tag: `error.type` - exception type full name, optional
    - Link: HTTP trace
    - Link: SignalR trace
    - Link: Circuit trace
    - Usage: which Blazor pages this session visited ?
- Trace name: `Microsoft.AspNetCore.Components.HandleEvent` 
    - Description: User interacted with the component
    - Tag: `aspnetcore.components.type` - full name of target C# component that receives the event
    - Tag: `aspnetcore.components.method` - C# method name of the handler
    - Tag: `aspnetcore.components.attribute.name` - name of the HTML attribute that triggers the event, i.e. `onClick`
    - Tag: `error.type` - exception type full name, optional
    - Link: HTTP trace
    - Link: SignalR trace
    - Link: Circuit trace
    - Link: Route trace
    - Usage: click to which component caused exception ? On which page ?
    - Usage: in which linked circuit and with what HTTP context it happened ?

### new source `Microsoft.AspNetCore.Components.Server.Circuits`

- Trace name: `Microsoft.AspNetCore.Components.Server.Circuits.CircuitStart` 
    - Description: User navigated to interactive server Blazor page
    - Tag: `aspnetcore.components.circuit.id` - class name of the Page component
    - Tag: `error.type` - exception type full name, optional
    - Link: HTTP trace
    - Link: SignalR trace
    - Usage: links other Blazor traces of the same session/circuit to HTTP and SignalR contexts

## Usage Examples

```cs
builder.Services.ConfigureOpenTelemetryTracerProvider(tracerProvider =>
{
    tracerProvider.AddSource("Microsoft.AspNetCore.Components");
    tracerProvider.AddSource("Microsoft.AspNetCore.Components.Server.Circuits");
});
```

## Alternative Designs

- OTEL feedback was that they don't use plurals in names and that our namespace `aspnetcore.components` is breaking that rule. 
    - I prefer to stick to existing .NET namespace.

## Risks

Small perf impact when enabled/subscribed to.

### PR DESCRIPTION
**Pull request by pavelsavara**
- rename `RouteChange` ->`Navigate`
- don't propagate HTTP/SignalR links to event traces
- rename internal methods to match above

Fixes https://github.com/dotnet/aspnetcore/issues/62556

### CODE REVIEW

File: src/Components/Components/src/ComponentsActivitySource.cs [hunk 1]
```diff
@@ -12,7 +12,7 @@ namespace Microsoft.AspNetCore.Components;
 internal class ComponentsActivitySource
 {
     internal const string Name = "Microsoft.AspNetCore.Components";
-    internal const string OnRouteName = $"{Name}.RouteChange";
+    internal const string OnRouteName = $"{Name}.Navigate";
     internal const string OnEventName = $"{Name}.HandleEvent";
```
Comment (javiercn) [inline src/Components/Components/src/ComponentsActivitySource.cs:16]: Did we not decide to also change `HandleEvent`? (Just asking, I don't remember 100%)

**Review by javiercn — APPROVED** [review]

File: src/Components/Components/src/ComponentsActivitySource.cs (hunk 1 above)
Comment (pavelsavara) [reply src/Components/Components/src/ComponentsActivitySource.cs:16]: We went full circle on that one. We first considered to rename all of it to nouns. 
But then Daniel said he preferred verbs for traces. And then I made the metrics names to match.

Below is screenshot of my final notes from the call recording.

image
