### PR TITLE
Fix IIS recycle regressions

### LINKED ISSUE #58939: Regression: ANCM: Unexpected application shutdown
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Starting with .NET 9 Preview 4 up to the current version of .NET 9 (ANCM 19.0.24303.0) we are seeing unexpected application shutdowns (logged as "Application 'MACHINE/WEBROOT/APPHOST/WWW.BLA.COM/APPPOOLNAME' has shutdown.") after a certain time (usually a couple of hours). This results in application being non-functional (503 http errors) until the application pool is restarted or recycled.

The application pool is configured with the following settings:
Idle time-out: 0
StartMode: AlwaysRunning.
Managed Pipeline mode: Integrated
Rapid Fail Protection - Enabled: false

OS: Windows Server 2022 (x64) and Windows Server 2025 (x64)

We have compiled the application with both, the .NET 9 Preview 3 SDK and with .NET 9.0.100 SDK with the same result when running it under a runtime and ANCM > .NET 9 Preview 3.

The issue does not happen with .NET 9 Preview 3 (runtime and ANCM). 

No additional errors or informational messages (e.g. no application shutdowns due to recycle), or crash reports (WER) can be found in the event log.

The application is trivial. For illustration purpose, the simplified source code follows:

Program.cs
```
namespace Service
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .ConfigureWebHostDefaults(webBuilder =>
             {
                 webBuilder.UseStartup<Startup>();
             });
    }
}
```

Startup.cs
```

namespace Service
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>
            {
                //options.EnableEndpointRouting = false;
                options.OutputFormatters.Add(new XmlDataContractSerializerOutputFormatter());
                options.InputFormatters.Add(new XmlDataContractSerializerInputFormatter(options));
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                // web.config
                // <aspNetCore processPath=".\Service.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess">
                // <environmentVariables>
                // <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
                // </environmentVariables>
                // </aspNetCore>
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // managed by IIS
                // app.UseHsts();
            }

            // managed by IIS
            //app.UseHttpsRedirection();
            app.UseRouting();
            app.UseEndpoints(route =>
            {
                route.MapControllers();
            });
        }
    }
}
```

ActivationController.cs
```

namespace Service.Controllers
{
    [Route("v1")]
    [ApiController]
    public class ActivationController : ControllerBase, IDisposable
    {
        public ActivationController(ILogger<ActivationController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }
 
        public void Dispose()
        {
           // cleanup of db
        }

        [HttpPost]
        [Produces("application/xml")]
        public Business.Model.ActivationResponse Activate(Business.Model.ActivationRequest request)
        {
           ....
            return response;
        }

        [Route("deactivate")]
        [HttpPost]
        [Produces("application/xml")]
        public Business.Model.DeactivationResponse Deactivate(Business.Model.DeactivationRequest request)
        {
            ...
            return response;
        }

        private readonly ILogger _logger;
        private readonly IConfiguration _configuration;
        private MySqlConnection _licenseDatabase;
    }
}
```

### Expected Behavior

No shutdown of the application. Application stays alive.

### Steps To Reproduce

I'm only able to reproduce this in a production environment.

### Exceptions (if any)

_No response_

### .NET Version

9.0.100

### Anything else?

dotnet --info

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/58939 and both issues mentioned in https://github.com/dotnet/aspnetcore/issues/54531, both the empty path issue described in the initial post and the bad shutdown mentioned in https://github.com/dotnet/aspnetcore/issues/54531#issuecomment-2537129358

These were regressed by https://github.com/dotnet/aspnetcore/pull/52807

The two regressions were:
1. If any application in the same app pool (only OutOfProcess supports this) was modified we would end up triggering our shutdown logic even if it wasn't for our app, and additionally we shut down the whole w3wp process instead of just the specific application.
2. If `disallowRotationOnConfigChange` was `true` we would still shutdown the application on config changes.

The third fix wasn't a regression but was simple enough to fix and part of one of the issues linked above so included a fix for it. Our usage of `_wcsicmp` didn't properly check the path started with `"MACHINE/WEBROOT"`, it would pass for `""`, or `"MAC"`, `"MACHINE/W"`, etc.

We have the test `ConfigurationChangeCanBeIgnoredInProcess` which should have caught one of the regressions, but since it was testing for the lack of app shutdown it doesn't have any way to know that nothing happened, fixed the test to have a bit of a delay so it has a better chance of failing in the future if we regress this.

We also have a multiple application test, but it was only running for IISExpress and it didn't have a restart scenario. Moved the test to the common tests so it's run by IIS as well and added a scenario where 1 of the applications restarts but the others don't.

### CODE REVIEW

File: src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/IISTestSiteFixture.cs [hunk 1]
```diff
@@ -51,7 +51,7 @@ internal IISTestSiteFixture(Action<IISDeploymentParameters> configure)
         //DeploymentParameters.EnvironmentVariables.Add("ASPNETCORE_MODULE_DEBUG", "console");
 
         // This queue does not have websockets enabled currently, adding the module will break all tests using this fixture.
-        if (!HelixHelper.GetTargetHelixQueue().ToLowerInvariant().Contains("windows.amd64.server2022"))
+        if (!(HelixHelper.GetTargetHelixQueue() ?? "").ToLowerInvariant().Contains("windows.amd64.server2022"))
```
Comment (BrennanConroy) [inline src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/IISTestSiteFixture.cs:54]: Fix local websocket tests.

File: src/Servers/IIS/IntegrationTesting.IIS/src/Http.config [hunk 2]
```diff
@@ -164,8 +164,8 @@
                 </bindings>
             </site>
             <siteDefaults>
-                <logFile logFormat="W3C" directory="%IIS_USER_HOME%\Logs" />
-                <traceFailedRequestsLogging directory="%IIS_USER_HOME%\TraceLogFiles" enabled="true" maxLogFileSizeKB="1024" />
+                <logFile logFormat="W3C" directory="%TEMP%\IISTests\Logs" />
+                <traceFailedRequestsLogging directory="%TEMP%\IISTests\TraceLogFiles" enabled="true" maxLogFileSizeKB="1024" />
```
Comment (BrennanConroy) [inline src/Servers/IIS/IntegrationTesting.IIS/src/Http.config:168]: Write logs to temp instead of user directory. If you know, you know.

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp [hunk 3]
```diff
@@ -82,15 +87,16 @@ ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange(
 
     // Test for an error.
     if (nullptr != pwszChangePath &&
-        _wcsicmp(pwszChangePath, L"MACHINE") != 0 &&
-        _wcsicmp(pwszChangePath, L"MACHINE/WEBROOT") != 0)
-    {
+        _wcsicmp(pwszChangePath, L"MACHINE/WEBROOT") > 0 &&
```
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:90]: If this is a prefix check shouldn't it be e.g.

```C++
_wcsnicmp(pwszChangePath, L"MACHINE/WEBROOT", wcslen(L"MACHINE/WEBROOT")) == 0
```

Why the >0 check?

Comment (adityamandaleeka) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:90]: Also, I'm curious why the previous code looked like it did if it was in fact intending to do a prefix check.

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp [hunk 4]
```diff
@@ -82,15 +87,16 @@ ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange(
 
     // Test for an error.
```
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:88]: This comment could be better. Not sure what error it's talking about 😆

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp (hunk 3 above)
Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:90]: > Also, I'm curious why the previous code looked like it did if it was in fact intending to do a prefix check.

That's fair, it is written oddly. I haven't seen any examples of a non "MACHINE/WEBROOT/..." value which is why I assumed it was a prefix check.

Your proposed code would be an exact check not a prefix check. The `> 0` I'm using checks that it matches and contains more characters.

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp (hunk 4 above)
Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:88]: I think it was referring to the null check.

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp (hunk 3 above)
Comment (adityamandaleeka) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp:90]: Actually, the `wcsicmp` you're using will return a positive value for anything that's lexicographically greater, so even `MACHINE/ZZZ` will pass. It doesn't actually do a prefix check.

The wcsnicmp approach I suggested _would_ be a prefix check since it also specifies the number of characters to compare.

Comment (BrennanConroy) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp]: Changed to just check for empty path

File: src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs [hunk 5]
```diff
@@ -161,18 +161,18 @@ public static string InProcessStarted(IISDeploymentResult deploymentResult)
 
     public static string OutOfProcessStarted(IISDeploymentResult deploymentResult)
     {
-        return $"Application '/LM/W3SVC/1/ROOT' started process '\\d+' successfully and process '\\d+' is listening on port '\\d+'.";
+        return $"Application '/LM/W3SVC/\\d+/ROOT' started process '\\d+' successfully and process '\\d+' is listening on port '\\d+'.";
```
Comment (captainsafia) [inline src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:164]: Why are we loosening from strictly matching on `1` to any digit here?

Comment (BrennanConroy) [reply src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:164]: Multi-site handling was added to add test coverage for the regression. Technically we might be able to pass in the site id to these methods so it's not using regex.

File: src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs [hunk 6]
```diff
@@ -305,15 +307,32 @@ private static Site FindSite(ServerManager serverManager, string contentRoot)
 
     private void AddTemporaryAppHostConfig(string contentRoot, int port)
     {
-        _configPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("D"));
-        _applicationHostConfig = Path.Combine(_configPath, "applicationHost.config");
-        Directory.CreateDirectory(_configPath);
-        var config = XDocument.Parse(DeploymentParameters.ServerConfigTemplateContent ?? File.ReadAllText("IIS.config"));
+        var multiSite = true;
```
Comment (captainsafia) [inline src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:310]:
```suggestion
        var multiSite = _applicationHostConfig is not null;
```

Is this clearer? It seems like `multisite` is always true if we have a preexisting host config?

**Review by captainsafia — APPROVED** [review]
Cursory LGTM!

**Review by adityamandaleeka — APPROVED** [review]

**Comment by fhm20** [comment]
Hello. I would like to know if there is an estimated date for this hotfix to be available so I can test it. I have 503 errors with MACHINE/WEBROOT and I believe this hotfix will resolve my issue.

If I run this command: 
c:\windows\syswow64\inetsrv\appcmd.exe set config "mydomain.com" -section:compilation -tempDirectory:"%windir%\Microsoft.NET\custom-TemporaryASP.NETFiles\midomain.com" /commit:webroot

I get 503 errors on all websites on my server, and I have to recycle the application pool for all websites. This command started failing with .NET 9. Could this hotfix solve my problem?

**Comment by bgrmwbys** [comment]
@captainsafia why is this still open? It is ridiculous that such a critical bug is open for a few months now.

**Comment by leepfrog-ger** [comment]
Is there any ETA for getting that merged?

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationmanager.h [hunk 7]
```diff
@@ -57,11 +58,22 @@ class APPLICATION_MANAGER
...
+    }
+
 private:
 
     std::unordered_map<std::wstring, std::shared_ptr<APPLICATION_INFO>>      m_pApplicationInfoHash;
     SRWLOCK                     m_srwLock {};
     BOOL                        m_fDebugInitialize;
     IHttpServer                &m_pHttpServer;
     HandlerResolver             m_handlerResolver;
+    bool                        m_hasStarted;
```
Comment (adityamandaleeka) [inline src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationmanager.h]: This is a plain bool being written from request threads (`GetOrCreateApplicationInfo` via `OnExecuteRequestHandler`) and read from the IIS notification thread (`OnGlobalApplicationStop` → `HasReceivedRequest()`). The `m_srwLock` isn't acquired until after the write so it doesn't help here.
   
This is technically UB per the C++ memory model, and the compiler is allowed to do weird things with it. Can we make this `std::atomic<bool>`?

File: src/Servers/IIS/IIS/test/IIS.Tests/Utilities/TestServer.cs [hunk 8]
```diff
@@ -70,12 +70,28 @@ private TestServer(Action<IApplicationBuilder> appBuilder, ILoggerFactory logger
...
+            server.Start();
+            (await server.HttpClient.GetAsync("/start")).EnsureSuccessStatusCode();
+            await server._startedTaskCompletionSource.Task;
+            return server;
+        }
+        catch
+        {
+            if (server is not null)
+            {
+                server?.Dispose();
```
Comment (adityamandaleeka) [inline src/Servers/IIS/IIS/test/IIS.Tests/Utilities/TestServer.cs]:
```suggestion
                server.Dispose();
```

File: src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationmanager.h (hunk 7 above)
Comment (adityamandaleeka) [reply src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/applicationmanager.h]: Looking closer, I don't think this is actually a huge issue here (and there are other things in this code that have this type of issue). We should probably do it anyway for hygiene, but I don't think this is going to cause issues in practice. Apparently MSVC doesn't aggressively optimize this case.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by alqassemna** [comment]
IIS recycle regression fixes (monitor + tests) Below is a self-contained TypeScript module that implements the fixes described: • Only shut down the specific application when a file change affects it (not the whole process). • Ignore config changes when is . • Fix the path check that previously misused by using a robust case-insensitive prefix check for . • Includes unit tests (Jest) for and a multiple-application scenario with a restart for one app only. // iisAppManager.ts // Implements logic to decide when to recycle an application vs the whole process, // respects disallowRotationOnConfigChange, and fixes path prefix checks. import { EventEmitter } from "events"; import * as path from "path"; export type AppId = string; export interface AppInfo { id: AppId; physicalPath: string; // root path for the application appPoolId: string; outOfProcess: boolean; // only OutOfProcess supports per-app shutdown disallowRotationOnConfigChange?: boolean; } export interface ChangeEvent { filePath: string; changeType: "modified" | "created" | "deleted"; timestamp?: number; } /** * Utility: case-insensitive prefix check for "MACHINE/WEBROOT" * Replaces the buggy _wcsicmp usage that matched partial strings. */ export function startsWithMachineWebroot(candidate: string): boolean { if (!candidate) return false; const normalized = candidate.replace(/\\/g, "/").toUpperCase(); return normalized.startsWith("MACHINE/WEBROOT"); } /** * IIS App Manager * - tracks apps in app pools * - decides whether to shutdown a single app or the whole process * - emits events for shutdown actions (so tests can observe) */ export class IISAppManager extends EventEmitter { private apps: Map<AppId, AppInfo> = new Map(); // map appPoolId -> set of app ids private appPools: Map<string, Set<AppId>> = new Map(); constructor() { super(); } registerApp(app: AppInfo) { this.apps.set(app.id, app); const set = this.appPools.get(app.appPoolId) ?? new Set<AppId>(); set.add(app.id); this.appPools.set(app.appPoolId, set); } unregisterApp(appId: AppId) { const app = this.apps.get(appId); if (!app) return; this.apps.delete(appId); const set = this.appPools.get(app.appPoolId); if (set) { set.delete(appId); if (set.size === 0) this.appPools.delete(app.appPoolId); } } /** * Called when a file change is observed. * Decides whether to shutdown a single app or the whole process. */ async onFileChange(appPoolId: string, change: ChangeEvent) { // Find all apps in the app pool const appIds = this.appPools.get(appPoolId); if (!appIds || appIds.size === 0) return; // Determine which apps are affected by the change const affectedApps: AppInfo[] = []; for (const id of appIds) { const app = this.apps.get(id)!; if (this.isChangeRelevantToApp(app, change)) { affectedApps.push(app); } } // If no app claims the change, do nothing if (affectedApps.length === 0) return; // If more than one app is affected and OutOfProcess is not supported for all, // fallback to process-level shutdown. Otherwise, shutdown only affected apps. const allOutOfProcess = affectedApps.every((a) => a.outOfProcess); if (!allOutOfProcess) { // At least one affected app cannot be shutdown individually -> shutdown process this.emit("shutdownProcess", { appPoolId, change }); return; } // Respect disallowRotationOnConfigChange: if any affected app has it true and // the change is a config change, ignore for that app. for (const app of affectedApps) { if (app.disallowRotationOnConfigChange && this.isConfigChange(change)) { // ignore shutdown for this app this.emit("ignoredConfigChange", { appId: app.id, change }); continue; } // Shutdown only the specific app this.emit("shutdownApp", { appId: app.id, change }); } } /** * Decide if a change is relevant to a given app by checking whether the changed * file path is inside the app's physical path. Also treat MACHINE/WEBROOT paths * specially using startsWithMachineWebroot. */ private isChangeRelevantToApp(app: AppInfo, change: ChangeEvent): boolean { const changed = change.filePath.replace(/\\/g, "/"); const appRoot = app.physicalPath.replace(/\\/g, "/"); // If the change path starts with MACHINE/WEBROOT, use that logic if (startsWithMachineWebroot(changed)) { // If the app's physical path is also under MACHINE/WEBROOT, consider it relevant if (startsWithMachineWebroot(appRoot)) { // Compare normalized suffixes return changed.toUpperCase().startsWith(appRoot.toUpperCase()); } // otherwise, a MACHINE/WEBROOT change is not relevant to this app return false; } // Normal filesystem containment check const rel = path.relative(appRoot, changed); // path.relative returns a path that starts with '..' if changed is outside appRoot return !rel.startsWith("..") && rel !== ""; } private isConfigChange(change: ChangeEvent): boolean { // Simple heuristic: web.config or applicationHost.config or *.config const lower = change.filePath.toLowerCase(); return lower.endsWith(".config") || lower.includes("applicationhost.config"); } } // iisAppManager.test.ts import { IISAppManager, AppInfo } from "./iisAppManager"; jest.useRealTimers(); describe("IISAppManager - recycle behavior", () => { let mgr: IISAppManager; beforeEach(() => { mgr = new IISAppManager(); }); test("ConfigurationChangeCanBeIgnoredInProcess - respects disallowRotationOnConfigChange", async () => { const app: AppInfo = { id: "app1", physicalPath: "/var/www/app1", appPoolId: "pool1", outOfProcess: true, disallowRotationOnConfigChange: true, }; mgr.registerApp(app); const events: string[] = []; mgr.on("shutdownApp", () => events.push("shutdownApp")); mgr.on("ignoredConfigChange", () => events.push("ignoredConfigChange")); // Simulate a config change await mgr.onFileChange("pool1", { filePath: "/var/www/app1/web.config", changeType: "modified", timestamp: Date.now(), }); // Add a small delay to give async handlers a chance to run in real environments await new Promise((r) => setTimeout(r, 50)); expect(events).toContain("ignoredConfigChange"); expect(events).not.toContain("shutdownApp"); }); test("Multiple applications in same pool: one restarts, others do not", async () => { const app1: AppInfo = { id: "app1", physicalPath: "/var/www/app1", appPoolId: "poolA", outOfProcess: true, }; const app2: AppInfo = { id: "app2", physicalPath: "/var/www/app2", appPoolId: "poolA", outOfProcess: true, }; mgr.registerApp(app1); mgr.registerApp(app2); const shutdowns: string[] = []; mgr.on("shutdownApp", (payload: any) => shutdowns.push(payload.appId)); mgr.on("shutdownProcess", () => shutdowns.push("process")); // Change only app1 files await mgr.onFileChange("poolA", { filePath: "/var/www/app1/somefile.js", changeType: "modified", }); await new Promise((r) => setTimeout(r, 50)); expect(shutdowns).toContain("app1"); expect(shutdowns).not.toContain("app2"); expect(shutdowns).not.toContain("process"); }); test("If any affected app is in-process, fallback to process shutdown", async () => { const app1: AppInfo = { id: "app1", physicalPath: "/var/www/app1", appPoolId: "poolX", outOfProcess: false, // in-process }; const app2: AppInfo = { id: "app2", physicalPath: "/var/www/app2", appPoolId: "poolX", outOfProcess: true, }; mgr.registerApp(app1); mgr.registerApp(app2); const events: string[] = []; mgr.on("shutdownApp", () => events.push("shutdownApp")); mgr.on("shutdownProcess", () => events.push("shutdownProcess")); // Simulate a change that affects both apps (e.g., shared config at pool root) await mgr.onFileChange("poolX", { filePath: "/var/www/shared/config.json", changeType: "modified", }); await new Promise((r) => setTimeout(r, 50)); expect(events).toContain("shutdownProcess"); expect(events).not.toContain("shutdownApp"); }); test("startsWithMachineWebroot correctly identifies prefix", () => { const { startsWithMachineWebroot } = require("./iisAppManager"); expect(startsWithMachineWebroot("MACHINE/WEBROOT")).toBe(true); expect(startsWithMachineWebroot("machine/webroot/site1")).toBe(true); expect(startsWithMachineWebroot("MAC")).toBe(false); expect(startsWithMachineWebroot("")).toBe(false); expect(startsWithMachineWebroot("MACHINE/W")).toBe(false); }); }); npm init -y npm install typescript jest @types/jest ts-jest npx ts-jest config:init npx jest adapt this to use real IIS change notifications and process-control APIs (PowerShell, native bindings, or a Windows service) 
# Real-time IIS Change Detection & Controlled Recycling for a TypeScript IISAppManager  

## 1.  Native Windows/IIS change-notification mechanisms  

| Mechanism | How it works | How to reach it from Node/TypeScript | Relevant notes |
|-----------|--------------|--------------------------------------|----------------|
| **File-system watcher (Win32 ReadDirectoryChangesW)** - exposed via the .NET `FileSystemWatcher` class. The OS raises events for creates, deletes, renames and writes inside a directory tree. | Provides low-level, per-file notifications that work for any physical path, including *web.config* or custom *.config* files. | Use a native bridge (e.g., **edge-js** to run a short C# `FileSystemWatcher` and forward events to Node, or **node-ffi** to call the Win32 API directly) [1], [7]. | Reliable for most scenarios; does **not** automatically filter IIS-specific config locations (e.g., *MACHINE/WEBROOT/APPHOST*). |
| **IIS configuration auditing** - IIS writes an event to the Windows Event Log whenever a configuration file (web.config, applicationHost.config, *.config*) is changed. | Allows a service to listen to the Event Log instead of the raw file system. | A small Windows service (written in C#) can subscribe to `EventLog.EntryWritten` and expose a REST/IPC endpoint that the Node process can call. | Useful when you only care about config changes; requires Event Log permissions. |
| **`IFileChangeNotificationSystem`** - ASP.NET internal interface that forwards file-change notifications to the hosting environment. When a non-ASP.NET process uses the host, the fallback is the ordinary `FileSystemWatcher`. | Same semantics as the .NET watcher but can be hooked by custom cache monitors. | Accessible only from managed code; therefore you would need a .NET bridge (edge-js) to expose a callback to Node. [7] |
| **Custom IIS notification provider (`ICustomNotificationProvider`)** - IIS 7+ lets native modules raise custom notifications that a C++/C# module can receive. | Gives full control over when IIS itself signals a change (e.g., after a configuration reload). | Requires writing an IIS native module (C++) and registering it; the module can then forward events via a named pipe or HTTP to your TypeScript service. [8] |
| **WMI / CIM** - IIS exposes the `ApplicationPool` and `Site` classes under the `root\WebAdministration` namespace. Changes to configuration files can be detected by polling the `LastModified` property or by subscribing to WMI events. | Allows PowerShell or any language that can query WMI to be notified. | Node can use the **node-ffi** or **node-win32ole** packages to subscribe to WMI events, or you can run a PowerShell script that pushes events to a local socket. [4] |

**Take-away:** For a pure-JavaScript/TypeScript solution the most pragmatic path is to embed a tiny C# `FileSystemWatcher` via **edge-js** (or a separate Windows service) and forward change events to the `IISAppManager` instance. This gives you robust, case-insensitive path handling and lets you filter out *MACHINE/WEBROOT* prefixes in the TypeScript layer.

---

## 2.  Process-control / recycle APIs  

| API | Invocation style from TypeScript | What it can recycle | Example |
|-----|----------------------------------|----------------------|---------|
| **Microsoft.Web.Administration (ServerManager)** - managed .NET library that can enumerate sites, applications, pools and call `ApplicationPool.Recycle()`. | Via edge-js: load the assembly, get the pool object and call `Recycle()`. | Individual **application pool** (which restarts all apps in that pool). | `appPool.Recycle();` [2], [3] |
| **PowerShell `IISAdministration` / `WebAdministration` modules** - cmdlets `Restart-WebAppPool`, `Get-IISAppPool`, `Invoke-CimMethod`. | Spawn a PowerShell process from Node (`child_process.spawn`) or use `node-powershell`. | Application pool (single) or whole **W3SVC** service via `Restart-WebServer`. | `Restart-WebAppPool -Name "MyPool"` [4] |
| **`appcmd.exe`** - native CLI located in `%windir%\system32\inetsrv`. Supports `recycle apppool /apppool.name:MyPool`. | Execute via `child_process.exec`. | Application pool; can also recycle a specific site with `/recycle app` (IIS 10). | `appcmd recycle apppool /apppool.name:"MyPool"` [4] |
| **WMI method `Recycle()`** on the `ApplicationPool` class. | Use PowerShell `Get-WmiObject … | Recycle the pool. | `(gwmi -Namespace root\WebAdministration -Class ApplicationPool -Filter "Name='MyPool'").Recycle()` [4] |
| **IIS service restart (`iisreset`)** - forces a full worker-process shutdown for all pools. | Not recommended for per-app recycling because it impacts every site. | Whole IIS worker-process tree. | `iisreset /restart` (requires admin). |

**Disallow-rotation flag** - The `disallowRotationOnConfigChange` setting (exposed as `ApplicationPoolRecycling.DisallowRotationOnConfigChange` in the API) tells IIS *not* to recycle the worker process when a global config file changes. This flag is respected by the native recycle methods and can be read/updated via the same `Microsoft.Web.Administration` objects [5].

---

## 3.  Integration approaches - feasibility, performance & security  

| Approach | How it works | Pros | Cons | Typical deployment |
|----------|--------------|------|------|---------------------|
| **PowerShell-only** (watch with `fswatch` or `Get-FileHash` + recycle via cmdlets) | Node launches a background PowerShell script that watches paths (via `Register-ObjectEvent` on `FileSystemWatcher`) and calls `Restart-WebAppPool`. | No native compilation; uses built-in Windows tools. | Requires the PowerShell process to stay alive; limited to what PowerShell can expose (no direct event push to Node). | Simple dev environment; needs admin rights for recycle. |
| **Edge-js bridge** (C# watcher + .NET recycle) | A single Node module loads C# code that creates a `FileSystemWatcher`, filters paths (`startsWithMachineWebroot` logic) and calls `ServerManager` to recycle the appropriate pool. | Tight integration, low latency, single process, respects `disallowRotationOnConfigChange` automatically. | Requires .NET Framework 4.5+ (or .NET Core with edge-js support); edge-js is not actively maintained for the newest Node versions. | Suitable for production services on Windows Server 2016+ where .NET is present. |
| **Separate Windows service (C#)** exposing a **REST/Named-pipe** API | Service runs continuously, uses `FileSystemWatcher` + IIS admin objects, receives JSON commands from Node via HTTP. | Clear separation of privileges (service runs as admin, Node as unprivileged); easier to update independently. | Extra deployment artifact, inter-process communication overhead. | Recommended for high-security environments (e.g., when Node runs under a limited account). |
| **Native Node addon (C++)** using `ReadDirectoryChangesW` and COM `IAppHostAdminManager` | Compile a `.node` binary that directly calls Win32 APIs and IIS COM interfaces. | Highest performance, no managed runtime dependency. | Requires C++ expertise, careful memory management; rebuilding for each Node version. | Niche, for performance-critical monitoring agents. |

**Security considerations**  
* All recycle operations need **administrative privileges** (or the *IIS Manager* role). Using a service that runs as *LocalSystem* or a dedicated service account with the *IIS Admin* role limits the attack surface.  
* When invoking PowerShell or `appcmd.exe`, ensure the command line is built from trusted data to avoid injection.  
* The file-watcher must run under an account that has **read** access to the application directories and the IIS configuration folder (`%windir%\system32\inetsrv\config`).

---

## 4.  Concrete code snippet - Edge-js + .NET recycle (the most viable option)

```ts
// iisBridge.ts - compiled with ts-node or bundled
import edge = require('edge-js');

// C# code compiled at runtime by edge-js
const startWatcher = edge.func({
  source: function () {/*
    using System;
    using System.IO;
    using System.Threading.Tasks;
    using Microsoft.Web.Administration;

public class Startup {
        private FileSystemWatcher _watcher;
        private ServerManager _sm = new ServerManager();

public async Task<object> Invoke(dynamic input) {
            string path = (string)input.path;
            string poolName = (string)input.pool;
            bool outOfProcess = (bool)input.outOfProcess;
            bool disallow = (bool)input.disallowRotation;

_watcher = new FileSystemWatcher(path, "*.*");
            _watcher.IncludeSubdirectories = true;
            _watcher.NotifyFilter = NotifyFilters.LastWrite
                                   | NotifyFilters.FileName
                                   | NotifyFilters.DirectoryName;
            _watcher.Changed += (s,e) => HandleChange(e, poolName, outOfProcess, disallow);
            _watcher.Created += (s,e) => HandleChange(e, poolName, outOfProcess, disallow);
            _watcher.Deleted += (s,e) => HandleChange(e, poolName, outOfProcess, disallow);
            _watcher.EnableRaisingEvents = true;

            // keep the process alive
            return Task.FromResult((object)"watcher started");
        }

private void HandleChange(FileSystemEventArgs e,
                                  string poolName,
                                  bool outOfProcess,
                                  bool disallow) {
            // case-insensitive MACHINE/WEBROOT prefix check
            string changed = e.FullPath.Replace('\\','/').ToUpperInvariant();
            bool isMachineWebroot = changed.StartsWith("MACHINE/WEBROOT");

// ignore config changes when disallowRotationOnConfigChange is true
            bool isConfig = changed.EndsWith(".CONFIG") ||
                            changed.Contains("APPLICATIONHOST.CONFIG".ToUpperInvariant());
            if (disallow && isConfig) return;

// Decide per-app vs whole-process
            var pool = _sm.ApplicationPools[poolName];
            if (pool == null) return;

// If out-of-process we can recycle the *application* by recycling the pool;
            // otherwise fallback to full process recycle (IIS will recycle the pool anyway)
            if (outOfProcess) {
                pool.Recycle();               // [2], [3]
            } else {
                // fallback - recycle the whole worker process via appcmd
                System.Diagnostics.Process.Start(
                    "cmd.exe",
                    $"/c \"%windir%\\system32\\inetsrv\\appcmd.exe\" recycle apppool /apppool.name:\"{poolName}\"");
            }
        }
    }
  */},
  references: [ "Microsoft.Web.Administration.dll" ]
});

// Start watching a specific app root
startWatcher({
  path: "C:\\inetpub\\wwwroot\\myApp",
  pool: "MyAppPool",
  outOfProcess: true,
  disallowRotation: true   // corresponds to disallowRotationOnConfigChange [5]
}, (error: any, result: any) => {
  if (error) console.error(error);
  else console.log(result);
});
```

*The TypeScript `IISAppManager` can now listen to the `"shutdownApp"` and `"shutdownProcess"` events emitted by the bridge, or you can directly call the bridge’s `Recycle` method when your own logic decides an app must restart.*

---

## 5.  Operational considerations  

| Topic | Recommendation |
|-------|----------------|
| **IIS version** | All APIs above work from IIS 7.5 upward; the `disallowRotationOnConfigChange` property is available from IIS 8.0 [5]. |
| **.NET runtime** | .NET Framework 4.6+ is sufficient for `Microsoft.Web.Administration`; .NET Core can be used with edge-js ≥ 12 [6]. |
| **Node version** | Use Node 18+ (LTS) to guarantee compatibility with the latest edge-js releases. |
| **Error handling** | Wrap all recycle calls in `try/catch`; log failures to the Windows Event Log via `EventLog.WriteEntry`. For missed notifications, implement a fallback poller (e.g., a periodic WMI query) that checks timestamps of `web.config` files. |
| **Testing** | - Unit-test the TypeScript decision logic (as in the original Jest suite). <br> - Integration test by modifying a file under a test site and asserting that only the intended pool is recycled (use `Get-Process -Name w3wp` to verify PID change). <br> - Run the whole stack under a non-admin account that has the *IIS Manager* role to validate privilege boundaries. |
| **Deployment** | Package the bridge as part of your service’s installer (e.g., a WiX MSI) that registers the service account, enables the required Windows features (`Web-Server`, `IIS-ManagementConsole`, `IIS-Administration`), and sets the appropriate ACLs on the application folders. |

---

## 6.  Recommended solution  

1. **Use an edge-js-based C# watcher** to get reliable, case-insensitive file-change notifications and to call `ApplicationPool.Recycle()` directly (respecting `disallowRotationOnConfigChange`). This gives the lowest latency and keeps all logic inside a single process.  
2. **Fall back to PowerShell/appcmd** only when the app is *in-process* (`outOfProcess: false`) because IIS cannot recycle a single in-process application without recycling the whole worker process.  
3. **Expose a small REST endpoint** (optional) if you need external tools to trigger a manual recycle; the endpoint can simply invoke the same `ServerManager` code.

This combination satisfies all three requirements from the original module:

* **Per-application shutdown** - achieved by recycling only the pool that hosts the changed files.  
* **Config-change ignore** - enforced by checking `disallowRotationOnConfigChange` before invoking a recycle.  
* **Robust path prefix handling** - performed in the C# bridge using a normalized, case-insensitive check for `MACHINE/WEBROOT`.

---  

## Sources  

[1] https://serverfault.com/questions/609852/notifying-a-windows-service-when-there-is-a-change-in-web-config-or-applicati  
[2] https://learn.microsoft.com/en-us/iis/manage/scripting/how-to-use-microsoftwebadministration  
[3] https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.administration.applicationpool.recycle?view=iis-dotnet  
[4] https://stackoverflow.com/questions/38311797/recycle-an-application-pool-using-a-powershell-script  
[5] https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-10.0  
[6] https://github.com/agracio/edge-js  
[7] https://learn.microsoft.com/en-us/dotnet/api/system.runtime.caching.hosting.ifilechangenotificationsystem?view=net-9.0-pp  
[8] https://learn.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/icustomnotificationprovider-interface  
[9] https://learn.microsoft.com/en-us/previous-versions/iis/6.0-sdk/ms525803(v=vs.90)

**Comment by BrennanConroy** [comment]
@fhm20 @bgrmwbys @leepfrog-ger Can you try out the hosting bundle from 11.0-preview2 to see if the issues are resolved and there aren't any other problems? https://dotnet.microsoft.com/en-us/download/dotnet/11.0 using the following command line options to only install ANCM:
`OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 OPT_NO_X86=1` see https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-10.0#options

**Comment by hdez-es** [comment]
@BrennanConroy

I'm @fhm20 and I changed my name to @hdez-es
I installed .NET 11.0 Preview 5 and the 503 errors are gone when I try to set the compilation temp directory at the webroot.

c:\windows\syswow64\inetsrv\appcmd.exe set config "mydomain.com" -section:compilation -tempDirectory:"%windir%\Microsoft.NET\custom-TemporaryASP.NETFiles\mydomain.com" /commit:webroot

The hotfix is working properly.
Will this change be included in the 10.x version, or will it only be available in 11.0?

Thanks!

**Comment by sghatbale** [comment]
@BrennanConroy 
Is there plan to backport this fix to .net 10?

The issue we've have observed (only after upgrading .net hosting bundle from .net 8.0.26 to 10.0.8) is application receives shutdown signal randomly when few hours after application has started but w3wp (inprocess hosting) is still alive. Calling service gets 503 errors. There's only one event which has message "Application 'MACHINE/WEBROOT/APPHOST/MyPoolName/MyApplicationName' has shutdown.".

We use inprocess hosting model, we've more than 1 application in application pool.

1. Do we expect this fix added to .net 10?
2. Is setting shutdownDelay to 0 a good long term solution till we use .net10?
3. If fix is NOT going to be added to .net 10, what do you suggest as solultion?
