### PR TITLE
Prevent NRE when body is not set

### LINKED ISSUE #46333: OutputCacheMiddleware throws NullReferenceException when trying to serve requests from cache
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I saw in our logs occasional `NullReferenceException`s being thrown by OutputCacheMiddleware but wasn't able to replicate that error locally until I also added the Rate Limiting feature. Now I'm able to consistently replicate the exception.

Just clone the sample project and hammer it with requests, and some of the queued requests will fail with a 500 error and a `NullReferenceException`. I have the queue set to 5, and some will fail and some will succeed. E.g. in the test I just did the first queued request failed failed, then the next two succeeded, then the last two also failed.

It seems to be specific to the case that the request is not able to be cached because cookies were set as part of the request.

I don't believe this error is unique to `RateLimitingMiddleware` because I did see this error in our logs before adding that. I'm not able to replicate it in the sample project below without using the RateLimitingMiddleware.

### Expected Behavior

`OutputCacheMiddleware` should never throw a `NullReferenceException`

### Steps To Reproduce

Sample project: https://github.com/DanielStout5/OutputCacheNullReferenceException

### Exceptions (if any)

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.TryServeCachedResponseAsync(OutputCacheContext context, OutputCacheEntry cacheEntry, IReadOnlyList`1 policies)
   at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.InvokeAwaited(HttpContext httpContext, IReadOnlyList`1 policies)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

7.0.101

### Anything else?

ASP.NET Core 7.0.2

Visual Studio 2022

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #46333

### CODE REVIEW

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs [hunk 1]
```diff
@@ -826,6 +824,53 @@ public async Task Locking_PreventsConcurrentRequests()
         Assert.Equal(1, responseCounter);
     }
 
+    [Fact]
+    public async Task Locking_IgnoresNonCacheableResponses()
+    {
+        var responseCounter = 0;
+
+        var task1Executing = new ManualResetEventSlim(false);
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:832]: Use `TaskCompletionSource`

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs [hunk 2]
```diff
@@ -826,6 +824,53 @@ public async Task Locking_PreventsConcurrentRequests()
...
+        // Wait for the first request to be processed before sending a second one
+        task1Executing.Wait();
+
+        var task2 = Task.Run(() => middleware.Invoke(context2.HttpContext));
+
+        task2Executing.Set();
+
+        await Task.WhenAll(task1, task2);
+
+        Assert.Equal(2, responseCounter);
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:871]: Can you write something unique to the bodies and verify that the response contains it as well as is different between the two responses (showing it wasn't cached)

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs (hunk 1 above)
Comment (sebastienros) [reply src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:832]: It's funny because I could swear I wrote a similar unit test a few years ago and you made the same comment ... I can't learn

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs (hunk 2 above)
Comment (sebastienros) [reply src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:875]: Updated

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs (hunk 1 above)
Comment (sebastienros) [reply src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs]: Updated

File: src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs [hunk 3]
```diff
@@ -826,35 +827,86 @@ public async Task Locking_PreventsConcurrentRequests()
...
+        options.AddBasePolicy(build => build.Cache());
+
+        var middleware = TestUtils.CreateTestMiddleware(options: options, next: async c =>
+        {
+            responseCounter++;
+
+            if (responseCounter == 1)
+            {
+                blocker.SetResult(true);
+                await Task.Delay(500);
```
Comment (BrennanConroy) [inline src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:850]: 😢 any way to use a synchronization primitive instead? Or is the second request waiting purely internal and not observable in any way?

Comment (sebastienros) [reply src/Middleware/OutputCaching/test/OutputCacheMiddlewareTests.cs:850]: There is no code path to unblock the second request at a known moment.

**Review by BrennanConroy — APPROVED** [review]
