### PR TITLE
LdapAdapter: Keep track of already processed groups to account for circular references

### LINKED ISSUE #37225: Linux: RBAC claims resolution hangs if nested groups have circular dependencies
### Describe the bug
Real-world AD deployments can have groups [circularly reference](https://serverfault.com/questions/351524/what-are-the-consequences-of-an-ad-group-that-has-as-its-member-a-group-that-is) each other, e.g. `GroupA -> GroupB -> GroupC -> GroupA`.
In this case, when nested claims resolution is enabled, Linux clients will hang on recursive resolution at https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs#L123

### To Reproduce

1. Set up any AD server (`contoso.com` in the example).
2. Add several AD groups so that they reference each other circularly, e.g. `GroupA -> GroupB -> GroupC -> GroupA`.
3. Add user to any of these groups.
4. Create a simple API project, set up RBAC claims resolution:
```C#
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate(options =>
            {
                if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    return;
                }

                options.EnableLdap(settings =>
                {
                    settings.Domain = "contoso.com";
                    settings.MachineAccountName = "someuser";
                    settings.MachineAccountPassword = "somepassword";
                });
            });

            services.AddAuthorization();
```
```C#
    [ApiController]
    [Route("api/[controller]")]
    [Authorize(Roles = "GroupA")]
    public class SomeController : Controller
    {
        [HttpGet]
        [Route("someMethod")]
        public async Task<ActionResult<int>> SomeMethod()
        {
            return 1;
        }
     }
```
5. Run it inside docker container `dotnet/aspnet:6.0`

### Exceptions (if any)
API call hangs, and eventually results in `StackOverflowException`.

### Further technical details
- ASP.NET Core 5.0, 6.0-preview5, via docker `dotnet/aspnet:6.0`
- Visual Studio 2019

### LINKED ISSUE #38769: Negotiate auth handler LDAP integration goes in infinate loop when AD groups have circular relationship on Linux
When using Negotiate authentication provider on Linux with LDAP integration for group resolution enabled, the application freezes if the principal has groups that have a circular relationships. 

Example: User belongs to AD Group A. Group A is `memberof` Group B. GroupB is also a `memberof` group A. 

These kinds of relationships are valid in AD, but recursion logic built into Negotiate provider's LDAP integration does not handle circular relationships of groups causing infinite recursive resolution.

[Relevant code](https://github.com/dotnet/aspnetcore/blob/1453530131334670ebcdd686300c1d8dfc0fbc8b/src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs#L99).

### To Reproduce
1. Create two AD groups.
2. Add each group as member of the other (circular)
3. Assign one of the groups to an AD user
4. Enable LDAP integration for Negotiate authentication middleware
5. Run under Linux
6. Attempt to authenticate the user.

Further technical details
- ASP.NET Core version: 5.0 (though 6.0 should also be affected as code is the same)
- Jetbrains Rider, Windows 10 /w WSL2 Ubuntu
- Include the output of `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.402 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

</details>

### Proposed fix
I have an alternate Negotiate adapter as part of my own project that does LDAP resolution properly. The logic can be seen [here](https://github.com/NMica/NMica.Security/blob/3868ceab4880058fbca4b66d651a169d04757d1d/src/NMica.AspNetCore.Authentication.Spnego/Ldap/LdapRolesClaimsTransformation.cs#L66)

I would be happy to build and submit a PR for this issue once this is confirmed and the proposed solution is accepted.

### PR DESCRIPTION
**Pull request by RoadTrain**
## Description

This PR fixes a particular corner case which is possible in real-world AD deployments, namely circular group references.
That is, e.g. `GroupA -> GroupB -> GroupC -> GroupA`. This is a problematic scenario for [any software working with AD](https://serverfault.com/questions/351524/what-are-the-consequences-of-an-ad-group-that-has-as-its-member-a-group-that-is).

The fix is basically to keep track of groups that we already processed by recursively passing a `HashSet` containing already processed entries.

Fixes #37225
Fixes #38769

### CODE REVIEW

File: src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs [hunk 1]
```diff
@@ -109,18 +111,26 @@ private static void GetNestedGroups(LdapConnection connection, ClaimsIdentity pr
                 logger.LogWarning($"More than one response received for query: {filter} with distinguished name: {distinguishedName}");
             }
 
-            var group = searchResponse.Entries[0]; //Get the object that was found on ldap
-            string name = group.DistinguishedName;
-            retrievedClaims.Add(name);
```
Comment (RoadTrain) [inline src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs:114]: Usually, we use a group Common Name (CN, like `SomeGroup`) as a claim name. In this particular instance, a Distinguished Name (DN, like `CN=SomeGroup,DC=domain,DC=com`) was used instead, which I think is incorrect.
Possibly a typo, was introduced in #25075

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
@RoadTrain @macsux, this should show up in our 7.0 rolling builds by next week. Can you download and verify the fix from there?
https://github.com/dotnet/installer#installers-and-binaries
