### PR TITLE
Blazor RemoteJSRuntime Use SignalR Hub Options before Global Options

### LINKED ISSUE #38205: RemoteJSRuntime uses SignalR global options instead of ComponentHub options
### Describe the bug
I'm trying to deserialize a > 32KB Uint8Array from JavaScript to Blazor and I'm receiving "Exceeded the maximum byte array transfer limit for a call" even if I've increased "MaximumReceiveMessageSize"

image

The only way to fix it it's to increase SignalR global options "MaximumReceiveMessageSize"

image

Is that a wanted behaviour? From what I'm seeing problem is here https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L42 

### To Reproduce
Try to get a > 32KB Uint8Array from JavaScript to Blazor by using JSRuntime

### Exceptions (if any)
image

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: 17.0.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.520 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

</details>

### LINKED ISSUE #38941: [.NET 6 Blazor server] 'Exceeded the maximum byte array transfer limit for a call' when transfer byte array from js to c#
Hello guys, i juste migrate my blazor server app from .NET 5 to .NET 6.

Now i try to profit of the improvement and i face problem on the way we can transfer byte array from js to c#.

from c# to js i don't have many problems (i use stream) but from the other way i have a fatal exception

this is the stack
````
blazor.server.js:1 [2021-12-10T12:30:11.816Z] Error: System.ArgumentOutOfRangeException: Exceeded the maximum byte array transfer limit for a call. (Parameter 'data')
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.ReceiveByteArray(Int32 id, Byte[] data)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ReceiveByteArray(JSRuntime jsRuntime, Int32 id, Byte[] data)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass44_0.<ReceiveByteArray>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.ReceiveByteArray(Int32 id, Byte[] data)
````

i already change the MaximumReceiveMessageSize parameter at startup
````
.AddHubOptions(o =>
                {
                    o.MaximumReceiveMessageSize = 100 * 1024 * 1024; // 100MB;/
                });
````

with the 64based string representation , i don't have this problem (the document i transfer is not more than 1Mb)

i send on this manner
`myComponent.invokeMethodAsync("OnDocumentSigned", lSignedDocByteArray);`
and receive
```
[JSInvokable]
        public async Task OnDocumentSigned(byte[] pDocumentSigned)
```

You have an idea on this ?

thanks !

### PR DESCRIPTION
**Pull request by TanayParikh**
Updated to use hub options over global options per Brennan's suggestion [here](https://github.com/dotnet/aspnetcore/issues/38205#issuecomment-977172370).

Fixes: https://github.com/dotnet/aspnetcore/issues/38205
Fixes: https://github.com/dotnet/aspnetcore/issues/38941

### CODE REVIEW

File: src/Components/Server/src/Circuits/RemoteJSRuntime.cs [hunk 1]
```diff
@@ -35,13 +35,14 @@ internal partial class RemoteJSRuntime : JSRuntime
...
-        IOptions<HubOptions> hubOptions,
+        IOptions<HubOptions<ComponentHub>> hubOptions,
+        IOptions<HubOptions> globalHubOptions,
         ILogger<RemoteJSRuntime> logger)
     {
         _options = circuitOptions.Value;
-        _maximumIncomingBytes = hubOptions.Value.MaximumReceiveMessageSize is null
-            ? long.MaxValue
-            : hubOptions.Value.MaximumReceiveMessageSize.Value;
+        _maximumIncomingBytes = hubOptions.Value.MaximumReceiveMessageSize ??
```
Comment (BrennanConroy) [inline src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: `null` is a valid value. So if a user set `MaximumReceiveMessageSize` in the hub specific options to null then they want that hub to have no limit. As this is written you would ignore the user set null value and use the global option instead which might be 10 bytes for all you know.

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: So is there any case where we would care about the global options here or should we only be considering the `ComponentHub` options? Ie, should I just revert this to the prior logic on lines 42-44 (using ComponentHub options instead of global hub options).

Comment (pranavkm) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: Should we straight up ignore global options? For e.g. it's valid to do this no:

```C#
.AddSignalR(options => options.MaxRMS = 100)
.AddBlazorServer(options => options.MaxRMS = null)
```

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: > Should we straight up ignore global options

I think the answer is yes, but I'll let Brennan confirm in case there are other considerations.

Comment (BrennanConroy) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: There are a few different scenarios here:
```
.AddSignalR(options => options.MaxRMS = 100)
.AddBlazorServer(options => options.MaxRMS = null) // use blazor server options
```
```
.AddSignalR(options => options.MaxRMS = 100); // use global options
```
```
.AddBlazorServer(options => options.MaxRMS = null) // use blazor server options
```

As the code is written the first scenario would use 100 when it should be `long.MaxValue`.

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: In the middle case there where we want to use the global options, wouldn't the component hub options default to `null` (and thus we would interpret it as `long.MaxValue`)?

I guess what I'm trying to determine is how to determine if the component options are null because the value wasn't provided and we want to use the global options, or if the component hub option was purposely set to null.

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: On second thought, based on the comment above and 

https://github.com/dotnet/aspnetcore/blob/f346a2793d5acee12f2129050c2fb7cda1ac7eb1/src/SignalR/server/SignalR/src/SignalRDependencyInjectionExtensions.cs#L51

it appears that the `ComponentHub` options roll in the global options. So we should only be looking at the component hub options. 

```
_maximumIncomingBytes = componentHubOptions.Value.MaximumReceiveMessageSize ?? long.MaxValue;
```

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: @BrennanConroy is the above understanding correct (always only look at the component hub options as the global options are "rolled in")?

Comment (BrennanConroy) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs:43]: > (always only look at the component hub options as the global options are "rolled in")?

Oh, that might be true, shouldn't be too hard to test

Comment (TanayParikh) [reply src/Components/Server/src/Circuits/RemoteJSRuntime.cs]: Verified, the global options are "rolled into" the component hub options. Thanks for the discussion! 😄

**Review by BrennanConroy — APPROVED** [review]
