### PR TITLE
[blazor] Fix InvariantGlobalization startup without AOT

### LINKED ISSUE #55750: [Blazor WASM] InvariantGlobalization causes error after upgrading to .Net 6 Preview 6
### Describe the bug
In .Net6-preview-6, Blazor WASM apps stop working when enabling `InvariantGlobalization`.
It worked in .Net 6 preview 5.

### To Reproduce
Example:
https://github.com/srpeirce/Blazor6-6/blob/main/Blazor6-6.Web/Blazor6-6.Web.csproj

Install dotnet 6 preview 6.

Create a new blazor project.
Run the project - it works!

Goto csproj and add:
`<InvariantGlobalization>true</InvariantGlobalization>`

The Blazor app now fails to load, with error in console.

### Exceptions (if any)
image

```
dotnet.6.0.0-preview.6.21352.12.js:1 /__w/1/s/src/mono/mono/metadata/icall.c:6619 <disabled>
550895 @ dotnet.6.0.0-preview.6.21352.12.js:1
blazor.webassembly.js:1 undefined
window.Module.s.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at _abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at <anonymous>:wasm-function[5994]:0x13d6ec
    at <anonymous>:wasm-function[2461]:0x78f19
    at <anonymous>:wasm-function[2187]:0x6130b
    at <anonymous>:wasm-function[6671]:0x15d556
    at <anonymous>:wasm-function[6495]:0x154eb0
    at <anonymous>:wasm-function[3347]:0xa8bfc
    at <anonymous>:wasm-function[676]:0x1646f
    at <anonymous>:wasm-function[304]:0xa0b5
```

### Further technical details
Dotnet version: `6.0.100-preview.6.21355.2`

### PR DESCRIPTION
**Pull request by pavelsavara**
The environment variables could be only set when the runtime is ready.
Fixes https://github.com/dotnet/runtime/issues/55750

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks good to me!

Thanks for following through!

@pranavkm do you have any further thoughts?

**Comment by pranavkm** [comment]
@lewing could you do a once-over to make sure this is the right change?

**Comment by radical** [comment]
- What changed that broke this?
- Also, @pranavkm are there are "functional" tests, where the app is run? It would be useful to have a test like that for this case

File: src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts [hunk 1]
```diff
@@ -279,6 +279,13 @@ function createEmscriptenModuleInstance(resourceLoader: WebAssemblyResourceLoade
     return []; // No exports
   };
 
+  module.onRuntimeInitialized = () => {
+    if (!icuDataResource) {
+      // Use invariant culture if the app does not carry icu data.
```
Comment (eerhardt) [inline src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts:284]: Maybe add a comment why this has to happen in `onRuntimeInitialized` and not in `preRun`?

**Comment by eerhardt** [comment]
> are there are "functional" tests, where the app is run? It would be useful to have a test like that for this case

+1

**Comment by eerhardt** [comment]
> What changed that broke this?

I'm pretty sure my change to fix https://github.com/dotnet/runtime/issues/49391 exposed this bug in how environment variables are handled in WASM. I think this was always broken, but because the error was being eaten, no one noticed.

**Comment by lewing** [comment]
There is also https://github.com/dotnet/runtime/pull/56667

**Comment by radical** [comment]
There are E2E wasm tests, like https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/WebAssemblyGlobalizationTest.cs . One for this case can be added there.

**Comment by radical** [comment]
> There are E2E wasm tests, like [https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/WebAssemblyGlobalizationTest.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/WebAssemblyGlobalizationTest.cs?rgh-link-date=2021-08-01T00%3A17%3A27Z) . One for this case can be added there.

Is there a test that is already covering this, but was disabled?
