### PR TITLE
Consistently produce an instance of WebAssemblyJSObjectReference from WebAssemblyJSRuntime

### LINKED ISSUE #26588: Synchronous JS interop: casting to IJSInProcessObjectReference throws
Looking at the preliminary docs here:
https://github.com/dotnet/AspNetCore.Docs/blob/ddc899a36770fca83cff263244df7523cea2aeb6/aspnetcore/blazor/webassembly-performance-best-practices.md

Using .NET 5: 5.0.0-rc.2.20474.6

In my Blaror WASM app I have a service like this:

```
public class WebcamService : IWebcamService, IAsyncDisposable
    {
        private readonly Lazy<Task<IJSObjectReference>> _moduleTask;

        public WebcamService(IJSRuntime jsRuntime)
        {
            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>(
               "import", "./jsinterop/webcam.js").AsTask());
        }

        public async Task StartVideo(WebcamOptions options)
        {
            var module = await _moduleTask.Value;
            ((IJSInProcessObjectReference)module).InvokeVoid("startVideo", options);
        }

        public async Task TakePicture()
        {
            var module = await _moduleTask.Value;
            ((IJSInProcessObjectReference)module).InvokeVoid("takePicture");
        }

        public async ValueTask DisposeAsync()
        {
            if (_moduleTask.IsValueCreated)
            {
                var module = await _moduleTask.Value;
                await module.DisposeAsync();
            }
        }
    }
```

When calling e.g. the StartVideo method, the code throws:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at ConfTool.Client.Webcam.WebcamService.StartVideo(WebcamOptions options) in C:\sources\blazor-webassembly-demo\Client\Webcam\WebcamService.cs:line 20
   at ConfTool.Client.Webcam.Webcam.StartVideoAsync() in C:\sources\blazor-webassembly-demo\Client\Webcam\Webcam.razor:line 40
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Not sure what could be wrong here.

Repro can be found here:
https://github.com/thinktecture/blazor-webassembly-demo/blob/net5-sync-js/Client/Webcam/WebcamService.cs#L20

Thanks!

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/26588

---- API review:

```C#
namespace Microsoft.JSInterop.Implementation
{
  public static class JSObjectReferenceJsonWorker
  {
     static long ReadJSObjectReferenceIdentifier(ref System.Text.Json.Utf8JsonReader reader);
     static void WriteJSObjectReference(Utf8JsonWriter writer, JSObjectReference! objectReference);
  }
}
```

### CODE REVIEW

**Comment by pranavkm** [comment]
Ping

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReference.cs [hunk 1]
```diff
@@ -9,11 +9,14 @@ internal class WebAssemblyJSObjectReference : JSInProcessObjectReference, IJSUnm
...
         private readonly WebAssemblyJSRuntime _jsRuntime;
 
-        public WebAssemblyJSObjectReference(WebAssemblyJSRuntime jsRuntime, long id) : base(jsRuntime, id)
+        public WebAssemblyJSObjectReference(WebAssemblyJSRuntime jsRuntime, long id)
+            : base(jsRuntime, id)
         {
             _jsRuntime = jsRuntime;
         }
 
+        internal new long Id => base.Id;
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReference.cs:18]: Nitpick :)

If there's no product-code reason for this to exist, it's a bit weird for it to do so, and means that every time the class accesses its own `Id` it does through via an unnecessary extra method call. This suffix avoids that and makes the code more honest.

```suggestion
        internal long IdForTests => base.Id;
```

Comment (SteveSandersonMS) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReference.cs:18]: Oh no wait, I see it's not only for tests.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+            _jsRuntime = jsRuntime;
+        }
+
+        public override bool CanConvert(Type typeToConvert)
+        {
+            return typeToConvert == typeof(WebAssemblyJSObjectReference) ||
+                typeToConvert == typeof(IJSObjectReference) ||
+                typeToConvert == typeof(IJSInProcessObjectReference) ||
+                typeToConvert == typeof(IJSUnmarshalledObjectReference) ||
+                typeToConvert == typeof(JSObjectReference);
```
Comment (SteveSandersonMS) [inline src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs:26]: I don't think `JSObjectReference` should be on the list.

 * It's not needed for serialization, since the only instances that should exist on wasm are `WebAssemblyJSObjectReference`
 * It's actively harmful to allow it for deserialization, because then developers don't have to use the interface type, which means their components can no longer be tested (e.g., via bUnit).

If I remember correctly, in 5.0 we explicitly ensured we would only deserialize when the interface types were requested (and not if the concrete type was requested) for that reason.

File: src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System.Text.Json;
+
+namespace Microsoft.JSInterop
+{
+    /// <summary>
+    /// Used by JsonConverters to read or write a IJSObjectReference instance.
+    /// </summary>
+    internal static class JSObjectReferenceJsonWorker
```
Comment (SteveSandersonMS) [inline src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs:11]: Should we consider making this `public` and in the `Microsoft.JSInterop.Implementation` namespace?

I'm thinking about other platform implementations like Mobile Blazor Bindings (and later, Blazor Desktop). They will also receive JSON blobs from JS interop that have the `__jsObjectId` on them, and also need to deserialize them to instances of their platform-specific `IJSObjectReference` type.

Comment (SteveSandersonMS) [reply src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs:11]: Technically we could do that later, but then it may involve cross-repo collaboration on timings for that. If we just do it now we save ourselves a bunch of coordination later.

File: src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+            if (id == -1)
+            {
+                throw new JsonException($"Required property {_idKey} not found.");
+            }
+
+            return id;
+        }
+
+        public static void Write(Utf8JsonWriter writer, long identifier)
```
Comment (SteveSandersonMS) [inline src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs:47]: You may have already considered this, but what about having this method accept an `JSObjectReference` instance instead of the `identifier`? Then it can read the ID directly because it's `internal` to this assembly anyway.

Then:

1. The WebAssembly variant doesn't need to shadow the `Id` property (it doesn't ever need to read it directly)
2. Other platform implementations can ignore the matter of IDs too

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs (hunk 2 above)
Comment (pranavkm) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs:26]: The current implementation specifically checks for the implementation type:

* https://github.com/dotnet/aspnetcore/blob/master/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/JSObjectReferenceJsonConverter.cs#L25
* https://github.com/dotnet/aspnetcore/blob/master/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs#L41
* `TImplementation` == `typeof(JSObjectReference)`


We could change it, but it is somewhat breaking.

File: src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs (hunk 4 above)
Comment (pranavkm) [reply src/Shared/JSInterop/JSObjectReferenceJsonWorker.cs:47]: I think if we were to make it a public API as you suggested earlier, we could make it work. Right now it's shared source and therefore cannot access `JSObjectReference.Id` when used from WASM, so ends up requiring this indirection.

File: src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs (hunk 2 above)
Comment (SteveSandersonMS) [reply src/Components/WebAssembly/JSInterop/src/WebAssemblyJSObjectReferenceJsonConverter.cs:26]: This might be an unintentional inconsistency in the implementation then. In https://github.com/dotnet/aspnetcore/blob/master/src/Shared/JSInterop/JSCallResultTypeHelper.cs, we very deliberately only included the interface types.

It's strange that you can get a concrete `JSObjectReference` as an incoming method parameter, but not as the return value  to an outgoing call. Seems clear it would be *better* if the JSON converter was tightened up to impose the same restriction, but as you've pointed out, it's somewhat breaking. 

If this was the sort of breaking change you could discover at compile-time I'd be fine with doing it in 6.0. But since instead it would show up as a hard-to-understand runtime error, I'm not really inclined to do it. I know we could theoretically implement an analyzer about this, but the cost of that seems disproportionate to the benefit.

What's your take? If we're leaving this in, it would be good at least to add a comment stating the inconsistency and that it's here for back-compat reasons even though we hope people aren't declaring `JSObjectReference` as a JSInvokable method parameter type.

**Review by javiercn — APPROVED** [review]
