### PR TITLE
Fix metrics duration and http.route tag with exception handling

### LINKED ISSUE #52648: Investigate metrics endpoint behavior when exception middleware runs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

OTEL folks noticed that the endpoint is cleared when exception middleware runs. See https://github.com/open-telemetry/opentelemetry-dotnet/issues/5134

Investigate whether this impacts ASP.NET Core's use of the endpoint when building tags for metrics.

### Expected Behavior

Metrics endpoint route tag is present when exception middleware runs.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

net8.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/52648

The `http.server.request.duration` counter records information about every HTTP request. One piece of recorded information is the `http.route` which is the matched route pattern. The route pattern is taken from `HttpContext`'s `Endpoint`.

There is a bug that causes `http.route` to not be available when:
* Incoming request to an app that has enabled metrics
* There is an unhandled exception
* App is using `UseExceptionHandler`
* Response hasn't started or aborted
* The exception handler clears the `HttpContext` and re-executes the middleware pipeline **<- problem**
* Value is recorded to `http.server.request.duration` without `http.route`

The exception handler clears the endpoint from the context and re-executes the middleware pipeline. There is no longer an endpoint on the context when `http.server.request.duration` is recorded and the `http.route` value is lost.

The fix is to stash the original endpoint to a known location (a stable key in `HttpContext.Items`) and then falls back to getting the endpoint from that location if the endpoint isn't set. `HttpContext.Items` is used because `IExceptionHandlerPathFeature` (which has an `Endpoint` property with the original endpoint) isn't available at the hosting layer.

A magic string in a dictionary isn't ideal, but we do use this technique in some other places. It would be better to add a new feature - `IOriginalEndpointFeature` perhaps? - but it doesn't seem worth it for this scenario.

### CODE REVIEW

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 1]
```diff
@@ -150,7 +150,13 @@ public void RequestEnd(HttpContext httpContext, Exception? exception, HostingApp
 
             if (context.MetricsEnabled)
             {
-                var route = httpContext.GetEndpoint()?.Metadata.GetMetadata<IRouteDiagnosticsMetadata>()?.Route;
+                var endpoint = httpContext.GetEndpoint();
+                if (httpContext.Items.TryGetValue(HttpExtensions.ClearedEndpointKey, out var e) && e is Endpoint clearedEndpoint)
```
Comment (JamesNK) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:154]:
```suggestion
                // Some middleware re-executing the pipeline. Before they do this, they clear the endpoint.
                // The original endpoint is stashed with a known key in HttpContext.Items. Use it as a fallback.
                if (endpoint is null && httpContext.Items.TryGetValue(HttpExtensions.ClearedEndpointKey, out var e) && e is Endpoint clearedEndpoint)
```

File: src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs [hunk 2]
```diff
@@ -150,7 +150,15 @@ public void RequestEnd(HttpContext httpContext, Exception? exception, HostingApp
 
             if (context.MetricsEnabled)
             {
-                var route = httpContext.GetEndpoint()?.Metadata.GetMetadata<IRouteDiagnosticsMetadata>()?.Route;
+                var endpoint = httpContext.GetEndpoint();
+                // Some middleware re-executing the pipeline. Before they do this, they clear the endpoint.
```
Comment (JamesNK) [inline src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs:154]:
```suggestion
                // Some middleware re-execute the middleware pipeline with the HttpContext. Before they do this, they clear state from context, such as the previously matched endpoint.
```

File: src/Shared/HttpExtensions.cs [hunk 3]
```diff
@@ -10,6 +11,8 @@ internal static class HttpExtensions
     internal static bool IsValidHttpMethodForForm(string method) =>
         HttpMethods.IsPost(method) || HttpMethods.IsPut(method) || HttpMethods.IsPatch(method);
 
+    internal const string ClearedEndpointKey = "__ClearedEndpoint";
```
[the remark this answers is not in the document]
Comment (mitchdenny) [reply src/Shared/HttpExtensions.cs:14]: No strong opinion but Original sounds more correct.

[the remark this answers is not in the document]
Comment (captainsafia) [reply src/Shared/HttpExtensions.cs:14]: 👍🏽  to `OriginalEndpoint`.

File: src/Shared/HttpExtensions.cs [hunk 4]
```diff
@@ -1,6 +1,8 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
+using System.Net.Http;
```
Comment (captainsafia) [inline src/Shared/HttpExtensions.cs:3]: Is this needed?

**Review by captainsafia — APPROVED** [review]
LGTM -- dealing with issues that came as a result of the middleware pipeline being reinvoked is always a pain but I agree that stashing `OriginalEndpoint` in `HttpContext.Items` is probably the most sensible approach here.

File: src/Shared/HttpExtensions.cs [hunk 5]
```diff
@@ -10,6 +12,8 @@ internal static class HttpExtensions
     internal static bool IsValidHttpMethodForForm(string method) =>
         HttpMethods.IsPost(method) || HttpMethods.IsPut(method) || HttpMethods.IsPatch(method);
 
+    internal const string OriginalEndpointKey = "__OriginalEndpoint";
```
Comment (davidfowl) [inline src/Shared/HttpExtensions.cs:15]: Add a comment explaining why this is a string (because of shared code?)

Comment (JamesNK) [inline src/Shared/HttpExtensions.cs:15]:
```suggestion
    // Key is a string so shared code works across different assemblies (hosting, error handling middleware, etc).
    internal const string OriginalEndpointKey = "__OriginalEndpoint";
```
