### PR TITLE
[Java] Observe error to avoid crash

### LINKED ISSUE #20187: Signal R Core Java Client Crashing
**Describe the bug**
When using the Java client SDK for Signal R Core, it crashes  when the socket pipe had broken. I attach a log through Firebase and this issue couldn't been reproduce on my own device.

**To Reproduce**
I couldn't reproduce/replicate this issue. Only information available is stack trace.

**Stack trace is...**

```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.subjects.CompletableSubject.onError(CompletableSubject.java:131)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
       at okio.Okio$1.write(Okio.java:79)
       at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
       at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.java:212)
       at okhttp3.internal.ws.WebSocketWriter$FrameSink.close(WebSocketWriter.java:252)
       at okio.RealBufferedSink.close(RealBufferedSink.java:248)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame(RealWebSocket.java:500)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:158)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Further technical details**
+ signalR 5.0.0-preview (installed using gradle: implementation 'com.microsoft.signalr:signalr:+')

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/20187

Thanks @jaragones for testing out a fix since I could never repro this.

### CODE REVIEW

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java [hunk 1]
```diff
@@ -94,6 +94,10 @@ public void onClosing(WebSocket webSocket, int code, String reason) {
         @Override
         public void onFailure(WebSocket webSocket, Throwable t, Response response) {
             logger.error("WebSocket closed from an error: {}.", t.getMessage());
+            // Register a default error handler to avoid unhandled exceptions crashing the process
+            // This can happen if the connection closes from a network issue instead of the user calling stop()
+            // In which case no one is observing the closeSubject error.
+            closeSubject.doOnError((e) -> {});
             closeSubject.onError(new RuntimeException(t));
             onClose.invoke(null, t.getMessage());
             checkStartFailure();
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:103]: Is there a chance that checkStartFailure() ever gets called before the Completable is returned from start() meaning we'd need to do the same ting for startSubject?

**Review by halter73 — DISMISSED** [review]
Thanks @jaragones!

**Comment by jaragones** [comment]
Let's see if it helps :)

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java (hunk 1 above)
Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:103]: I think that is technically possible, but very unlikely in practice.

I'm not sure how the global error handler works in that case, because the startSubject will be observed by someone, they just haven't registered the handler by the time onError is called.

Comment (halter73) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:103]: If it's possible, we should handle it.

> I'm not sure how the global error handler works in that case, because the startSubject will be observed by someone, they just haven't registered the handler by the time onError is called.

We could test this by intentionally faulting the startSubject before returning. I expect it would also  be crashing. How would the runtime even know the startSubject will be observed by someone in the future?

File: src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java [hunk 2]
```diff
@@ -87,14 +89,29 @@ public void onMessage(WebSocket webSocket, String message) {
         @Override
         public void onClosing(WebSocket webSocket, int code, String reason) {
             onClose.invoke(code, reason);
-            closeSubject.onComplete();
+            try {
+                closeLock.lock();
+                closeSubject.onComplete();
```
Comment (halter73) [inline src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:94]: Should we check that the closeSubject hasn't already been completed with an error here?

Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:94]: Calling onComplete should noop if the subject is already completed either with an error or without an error.

Comment (BrennanConroy) [reply src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java:94]: @halter73 any other feedback?

**Review by halter73 — APPROVED** [review]
